### ISSUE TITLE
"Promote" button is confusing when the version is already promoted.

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10002]
Can we hide the promote button for the promoted version entirely? It seems like it is greyed out, but I think that's still a bit confusing

![image](https://github.com/coder/coder/assets/22407953/fed45494-931a-425e-92fa-5295fe2d51b1)

**Comment by matifali** [comment]
@BrunoQuaresma @10504 could be related

**Comment by aslilac** [comment]
we display this intentionally, because it looks bad for it to not be there when there are multiple versions. we can tweak the styling if it would help tho.

**Comment by BrunoQuaresma** [comment]
I can confirm it is fixed by https://github.com/coder/coder/pull/10555! 👍
