### ISSUE TITLE
OIDC access token exposed via "coder state pull"

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#10000]
We noticed that the state returned by `coder state pull` includes the OIDC access token: https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#owner_oidc_access_token

While it seems reasonable to store this token for internal use, it probably shouldn't be exposed through the API/CLI. It would be easy to accidentally log or persist the token when using `coder state pull` for an unrelated purpose.

Would it be possible to redact this from the data returned by this API?

**Comment by kylecarbs** [comment]
We don't presently mutate the state, so this would be new.

The problem with mutating is that if a user `coder state push` the pulled statefile, then it would cause some state misconfiguration because of the missing token unless we injected it again, which seems _sketchy_.

I'm open to more ideas on how we do this, though... I agree it's sketchy.

**Comment by aaronlehmann** [comment]
Maybe encrypting the token stored in the state would make sense, similar to what's now supported at the database level?

**Comment by matifali** [comment]
We may mark it as [`Sensitive`](https://developer.hashicorp.com/terraform/language/state/sensitive-data), the same as the hcp-terraform-provider does for [`data.hcp_vault_secrets_secret.example.secret_value`](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/data-sources/vault_secrets_secret#secret_value)

See an example here:
https://github.com/hashicorp/terraform-provider-hcp/blob/d58d335805f6c67ecd26d547afdc10273aa96709/internal/provider/vaultsecrets/data_source_vault_secrets_secret.go#L57

**Comment by matifali** [comment]
We could probably mark them as [sensitive](https://developer.hashicorp.com/terraform/language/state/sensitive-data).

I have seen an example in `hcp-terraform-provider` where they return [`data. hcp_vault_secrets_secret.example.secret_value`](https://registry.terraform.io/providers/hashicorp/hcp/latest/docs/data-sources/vault_secrets_secret#secret_value) as a secret. 

A related code snippet for this is:

https://github.com/hashicorp/terraform-provider-hcp/blob/d58d335805f6c67ecd26d547afdc10273aa96709/internal/provider/vaultsecrets/data_source_vault_secrets_secret.go#L54-L58

We should do it for 
1.
