### ISSUE TITLE
External Auth: Github Callback 404

### ISSUE THREAD

**Issue by djarbz** [coder/coder#10032]
I am attempting to setup the Github App integration and the callback keeps returning a 404.

```bash
CODER_EXTERNAL_AUTH_0_ID=github
CODER_EXTERNAL_AUTH_0_TYPE=github
CODER_EXTERNAL_AUTH_0_CLIENT_ID=...
CODER_EXTERNAL_AUTH_0_CLIENT_SECRET=...
```
```
https://coder.example.com/gitauth/github/callback?code=...&installation_id=...&setup_action=install
```

I have tried changing to `/externalauth` and `/external-auth` with no luck.
I have also tried changing the callback name to `primary-github` as shown in the [documentation](https://coder.com/docs/v2/latest/admin/external-auth).

**Comment by matifali** [comment]
@djarbz This has yet to be released and is not included in v2.2.0 it will be available in the next release.
YOu can check https://coder.com/docs/v2/v2.2.0/admin/auth for current documentation.

cc; @kylecarbs, @bpmct and @BrunoQuaresma 
We should not show the latest docs but the docs from the last released version by default. Also, there should be an easy way to switch to previous versions of docs.

**Comment by djarbz** [comment]
Thank you for the quick response, that makes sense.

I would agree that showing the latest release docs by default would be helpful.

I didn't even think of checking if it was released or not as it seemed to be referenced elsewhere that made me believe it has been released for a while. Can't remember where exactly, I was looking through a lot of documentation last night.

**Comment by kylecarbs** [comment]
Yeah, I'm going to revert my docs change and leave it in a PR for now until release...

**Comment by kylecarbs** [comment]
https://github.com/coder/coder/pull/10044

**Comment by matifali** [comment]
Closing in favour of #10103 and #10104
