### ISSUE TITLE
Coder CLI Login doesn't handle Access URL Redirect

### ISSUE THREAD

**Issue by djarbz** [coder/coder#10031]
When executing `coder login https://coder.prod.example.com` I receive an error as it is responding with a redirect to the proper URL.
Coder should handle this and retry at the new URL.

```bash
$ curl https://coder.prod.example.com
<a href="https://coder.example.com">Temporary Redirect</a>.
```

**Comment by Emyrk** [comment]
Can you post some method to reproduce this?

I tried running a small server that does 307 redirects and it works. Can you send the proxy server that is doing the redirects? The HTML is making me think the status code is something like 200?

```golang
func main() {
	http.ListenAndServe(":5555", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "http://localhost:3000"+r.URL.Path, http.StatusTemporaryRedirect)
	}))
}
```


```bash
$ coder login http://localhost:5555                                                           
Your browser has been opened to visit:

	http://localhost:5555/cli-auth

> Paste your token here: zvbmiHvEIS-6Obwwe3339iJWBW5upmAAE
> Welcome to Coder, admin! You're authenticated.

```

**Comment by Emyrk** [comment]
Closing this from lack of activity
