### ISSUE TITLE
Editing a file in the template editor removes the executable bit from other files (e.g. scripts)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10034]
I have a template with a bunch of `.sh` files that have the executable bit set (`chmod +x *.sh`). If I edit a file in the template editor (Web UI), all the `.sh` files lose their executable bit (`chmod -x *.sh`).

We should keep the executable bit when making changes in the Web UI.

**Comment by BrunoQuaresma** [comment]
How can I reproduce that and test if the fix is working?

**Comment by mafredri** [comment]
@BrunoQuaresma 

1. Create a template/folder with a script file (doesn't need to be references in tf and can be empty):

```shell
# ls my-template/
main.tf
script.sh
```

2. Then make it executable and push it

```shell
chmod +x my-template/script.sh

ls -l my-template/script.sh
-rwxr-xr-x ... my-template/script.sh

coder templates push -d ./my-template
```

3. Edit `main.tf` in the web editor (I believe this will suffice, otherwise you can try editing `script.sh` too)

4. Pull the template `coder templates pull my-template` and examine `script.sh` via `ls -l` again, it should still have the `x` (eXecutable bit) in `-rwxr-xr-x`, but it doesn't.

**Comment by BrunoQuaresma** [comment]
@mafredri I think it was fixed by https://github.com/coder/coder/pull/12000 can you please do a double check? 🙏
