### ISSUE TITLE
☂️ Autostop requirement

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10042]
An autostop requirement will replace "max TTL" to ensure all workspaces are stopped (and updated) weekly or nightly. This is configurable on the template-level, and users can set their own quiet hours to avoid restarts interrupting their flow in their timezone.

![image](https://github.com/coder/coder/assets/22407953/6d36d2fd-0000-40aa-b9c2-5fb82b85ba8a)

![image](https://github.com/coder/coder/assets/22407953/0f9dd623-80b5-42ff-bb72-b3f803505b48)

This feature is currently under `CODER_EXPERIMENTS`. To enable it, set the following `coder server` vars:

```sh
CODER_EXPERIMENTS="*,template_autostop_requirement"
CODER_QUIET_HOURS_DEFAULT_SCHEDULE="CRON_TZ=America/Denver 0 0 * * *"
```

---

This is an issue for the [Autostop Requirement](https://github.com/coder/coder/milestone/25) milestone. Track our progress here

**Comment by stirby** [comment]
We shipped this! 

https://coder.com/docs/v2/latest/workspaces#autostop-requirement-enterprise
