### ISSUE TITLE
Additional role spec

### ISSUE THREAD

**Issue by shanehughes1990** [coder/coder#10054]
Hello, I'm looking to build a workspace that would need files injected during runtime but I have from what I can tell no way of adding additional roles to the rbac creation for the service account, what I need is to be able to create a configmap resource but the coder account only has access to pvc's, pods and optional deployments, it should be pretty easy to add similar to additional annotations where you let the user define additional roles to be created for the service account and just merge them into the _rbac.yaml.

If there is another way in the mean time to get around mounting files into a pod during runtime please let me know as I'm kind of stuck without building it into the workspace container itself or opting out of the helm chart rbac yaml and building it myself.

**Comment by kylecarbs** [comment]
You can always use a custom service account instead of ours. 

Ours is just OOTB for ease of getting started.
