### ISSUE TITLE
Enterprise: Group handling of dormant users currently inconsistent

### ISSUE THREAD

**Issue by janLo** [coder/coder#10064]
Following up from https://discord.com/channels/747933592273027093/1156904174504656986

I was just investigating a failure of our custom user-group-sync between our LDAP and Coder using the coder API. The error I saw was the following:
```
{"message":"Cannot add the same user to a group twice!","detail":"execute transaction: insert group member \\"a22ce41a-c5e5-42a6-a327-2f8f9c079ba6\\": pq: duplicate key value violates unique constraint \\"group_members_user_id_group_id_key\\""}\n
```

I dumped all data from coder to understand this because I could not see where the duplicate user came from. I finally discovered that the issue here is how dormant users are handled. They get removed from all groups if you ask the API for group members. My sync code, on the other hand, gets the state from LDAP, fetches the Groups from LDAP and creates a diff of all members who are in both systems.

This means that it will see that dormant users have no group memberships and tries to add them to the necessary groups - which then fails with the error above.

As a workaround, I will just ignore all dormant users in coder for now and only sync active ones. But this has the downside, that when a dormant user activates its account by logging in, the group memberships will be out of sync until the next sync run. 

Would it be possible to return dormant group members from the API? This would allow a more consistent view on the system, in my opinion. 

The current state might also pose a compliance issue, as it is not transparent to an admin or auditor what members a group currently has. There might be dormant users who are neither visible in the Web-UI nor in the API results. As soon as they log in again, they get suddenly active and become members.

Therefore, I think it should also be possible to add and especially remove dormant users from groups.

**Comment by Kira-Pilot** [comment]
Resolved by #10333
