### ISSUE TITLE
Too many workspace statuses in UI

### ISSUE THREAD

**Issue by ammario** [coder/coder#10067]
I believe I opened an issue for this before but I lost it.

A major usability problem in the Workspaces page is the amount of "Statuses" one can filter by. The colors are ambiguous, and when debugging provisioning you probably want to see all building workspaces regardless of the start and end state.

<img width="1063" alt="Screenshot 2023-10-04 at 4 33 06 PM" src="https://github.com/coder/coder/assets/7416144/45a2f8ad-1981-4384-8f51-0a68bee7b43b">

I propose we simplify the list to:

* Running
* Stopped
* Failed
* Building (incl. Pending)

---

cc @BrunoQuaresma @kylecarbs @sreya

**Comment by BrunoQuaresma** [comment]
I think it makes sense. I also find confusing too many statuses.
