### ISSUE TITLE
`Error getting agent logs` displaying upon workspace start/stops, despite no issue

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10078]
since upgrading to 2.2.0, i've been seeing the below banner display during workspace stop/starts. i'm unable to consistently reproduce, and it is displaying even when there is no issue with the workspace agent init/startup script.

![image](https://github.com/coder/coder/assets/9683576/9ceb06cd-32a5-4469-9de3-0f16258bfac4)

**Comment by BrunoQuaresma** [comment]
I figured out this happens with Safari's old versions rather than 15.3

https://github.com/mdn/browser-compat-data/issues/15592

**Comment by BrunoQuaresma** [comment]
Adding a polyfill should work:

```ts
if (!Array.prototype.at) {
  Array.prototype.at = function at(n) {
    let i = Math.trunc(n) || 0

    if (i < 0) i += this.length

    if (i < 0 || i >= this.length) return undefined

    return this[i]
  }
}
```

Took from https://github.com/vercel/next.js/pull/44436/files#diff-2f5596fa58e0c6b1fc2c6453e3a99ba4e25c585b657625c58f019b9e044e766cR133-R143

**Comment by BrunoQuaresma** [comment]
@ericpaulsen this is related to old browser versions, so I would like to know from you how frequently we see customers using browser versions +2 years old.

**Comment by BrunoQuaresma** [comment]
It was not related to the `.at` this time that I tried it 🤔. It is an known "bug" when dealing with incoming messages when the connection is closed https://github.com/socketio/socket.io/issues/2016
