### ISSUE TITLE
web terminal characters are not rendering in v2.1.5+

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10082]
multiple customers have reported characters not being rendered in the web terminal until `Enter` is clicked.

we've tracked this down to a regression in the `webgl` package, which can be found here: https://github.com/xtermjs/xterm.js/issues/4665. `webgl` was introduced in Coder version 2.1.4 https://github.com/coder/coder/pull/9320. to fix this, we should default back to the previous rendering binary `canvas`, and create a deployment-wide flag to opt-in to `webgl`. the `webgl` regression should be fixed in upcoming versions of Chrome.

![image](https://github.com/coder/coder/assets/9683576/4c348be6-4736-47dc-ba1e-991d4587c5a9)

![image](https://github.com/coder/coder/assets/9683576/8c5e1457-33c0-48af-9503-7e1bde0ee2fc)

**Comment by MrPeacockNLB** [comment]
good catch

**Comment by BrunoQuaresma** [comment]
We had issues with canvas in the past. That was the reason we started to use webgl. @code-asher has more context on that.

**Comment by matifali** [comment]
This is an upstream issue with chromium when Vulkan is used and as per [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1476475#c14) has been addressed in v119.

**Comment by code-asher** [comment]
> @code-asher has more context on that.

For a full history of the rendering engine changes, we initially used canvas, then we switched to html on accident, which caused rendering issues, then we switched back to canvas, then, (from what I understand) we switched to webgl because of performance issues.

**Comment by code-asher** [comment]
Forgot to finish my thought.  So, the switch back to canvas should be chill, probably better to be a bit slow than not rendering at all, and for users where performance is an issue they can opt into webgl.
