### ISSUE TITLE
Make external auth providers optional

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10109]
## Background

We have a `coder_external_auth` data source that requires the user auth with git or another sevice before creating the template.

## Current behavior

When git auth is added to a template, it is currently required. However, some organizations are migrating from one git provider to another or rolling out a provider to others. This means not all template users have an account on a given service. Terraform is also capable of conditional logic, such as cloning a repo if the user authed

## Proposed behavior

A provider can be marked as optional.

```hcl
data "coder_external_auth" "experimental_github" {
  id = "experimental_github"
  required = false # default is true to avoid a breaking change
}

resource "coder_agent" "my script" {
  # ...
  startup_script=<<EOF
  # this is pseudocode 
  if [${data.coder_parameter.external_auth.token == !null}] then;
    git clone ...
  fi
  EOF
}
```

**Comment by kylecarbs** [comment]
I think instead we'll invert it:
```
optional = true
````

**Comment by bpmct** [comment]
Sure. I think the default should be false :)

**Comment by MrPeacockNLB** [comment]
This is super cool because currently we have to make a 100% copy of our template just without the external auth. Reason is we want to make e2e tests with playwright. As of today this wont work as the used technical account is not able to sign in into GitHub. If it is optional then we can run the e2e tests against our current template.

So thumbs up!

**Comment by michaelbrewer** [comment]
I assume this also fixes when external authentication is not being prompted for `mode=auto`?

**Comment by aslilac** [comment]
I didn't make any changes to `mode=auto`, so if there was a bug there it likely still exists (unless someone else fixed it)

**Comment by michaelbrewer** [comment]
Ok cool. I have opened a bug related to mode=auto.
