### ISSUE TITLE
Add "Refresh Authentication" Mechanism for `coder_external_auth`

### ISSUE THREAD

**Issue by matifali** [coder/coder#10124]
# Refresh Authentication Mechanism for `coder_external_auth` Resource

## Description
In the current setup, a user can only authenticate via the [`coder_external_auth`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/external_auth) Terraform data source on the workspace creation screen. Post creation, there isn't a way to manually re-authenticate or refresh the authentication token. This limitation can disrupt workflow, especially when the token expires or is invalidated for any reason.

## Proposed Solution
Extend the authentication functionality to the workspace settings page by replicating the authentication button from the workspace creation screen with an additional "Refresh" button. This way, users can see their authentication status and have the ability to re-trigger the OAuth flow to obtain a new token if necessary.

![image](https://github.com/coder/coder/assets/10648092/b68967da-c65f-45cc-be8d-50bc8b28008a)

The OAuth flow should be re-triggered upon clicking the "Refresh" button.

## Impact
By implementing this enhancement, users will have the flexibility to refresh their authentication tokens post workspace creation, ensuring uninterrupted access to external resources. This will significantly improve the user experience and the application's usability.

## Additional Context
A seamless authentication experience is crucial for applications interfacing with external resources. A way to manage authentication post workspace creation will empower users to maintain continuous access and resolve authentication issues on demand.

cc: @bpmct, @kylecarbs

**Comment by kylecarbs** [comment]
Super easy for us to add!

**Comment by Shocktrooper** [comment]
This would be super useful for external providers + git auth as our users have complained about tools not connecting to external systems once the auth expires in the workspace.

**Comment by matifali** [comment]
@kylecarbs, can this be done sooner? It would help me in testing External Auth integration.

**Comment by matifali** [comment]
As a workaround, one can go to https://coder.example.com/external-auth/EXTERNAL_AUTH_ID and click **Reauthenticate**.

**Comment by matifali** [comment]
Closed by #10945
