### ISSUE TITLE
Service banner is not updated in Web UI without a refresh

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10127]
The service banner should be periodically updated in the Web UI, otherwise users will be non-the-wiser unless they reload the whole web page.

One use-case is in scale testing (`big.cdr.dev`), here we update the service banner based on if a scale test is running, succeeded or failed (or not at all), but status updates can only be seen by hitting reload (Cmd + R).

<img width="400" alt="image" src="https://github.com/coder/coder/assets/147409/2a162767-59df-4967-9378-76178b3ab035">

I don't think this is browser related, but for completeness:

OS: macOS Sonoma 14.0
Browser: Safari 17.0

**Comment by matifali** [comment]
I agree. The service banner is meant for general announcements and updates on each page refresh which is enough for this intended use case. 
Maybe we should link it with motd for the evs who may never open the dashboard and only use the workspace via CLI/SSH/IDEs

**Comment by mafredri** [comment]
Without some sort of refresh, I do believe some people might not get the message. A user could easily leave the same tab open for a week without refresh, and never get the message. Especially true if they only use the web terminal and other browser based tools like code-server.
