### ISSUE TITLE
Timeout of UI redirects incorrectly

### ISSUE THREAD

**Issue by smolinari** [coder/coder#10126]
Hi,

This is a really, really minute issue. Basically a cosmetic one, but still annoying. 

I'm using Coder with OIDC (Keycloak). 

When the UI session times out, I get redirected to this:

![image](https://github.com/coder/coder/assets/3314957/9e6090eb-60d6-4e16-94a7-5f059b489fa8)

And I have to change the URL to the coder base URL and I can log in again normally via OIDC. 

![image](https://github.com/coder/coder/assets/3314957/6b995e56-1a41-4779-8654-17eeeba3584c)

I believe the system should do the same thing and not show me this error or rather, the button to log in via OIDC should be available here too. But yeah, this shouldn't be an error really. :grin: 

Scott

**Comment by Shocktrooper** [comment]
We have also experienced this.  Our end users were a tad confused when they ran into this issue.

**Comment by BrunoQuaresma** [comment]
> And I have to change the URL to the coder base URL

Is it redirecting to the wrong domain? Or when you just refresh the page it work?

**Comment by smolinari** [comment]
Coder redirects to the `/login` path (after some sort of timeout??) and shows the error above. I have to remove the `/login` path and refresh and then I get the correct login options (the second screen). 

Scott

**Comment by smolinari** [comment]
Hey, 

not sure if something was done to try to fix this, but now with version 2.3.2, instead of an error, the browser ends up in an endless redirect loop. 

Scott

**Comment by aslilac** [comment]
hey @smolinari, I'm having trouble reproducing this.

- is this "test-user" in the email field something you entered?
- could you share a screen recording of this redirect loop that you're seeing now? it might be helpful to set the `CODER_SESSION_DURATION` environment variable to something like `30s` so that sessions are shorter.
- can you provide details about any other configuration/deployment details that might help me reproduce this?

**Comment by smolinari** [comment]
@aslilac - Hi Kayla,

I ended up deleting cookies at one point and now I have the same error, but without redirecting to login.

![image](https://github.com/coder/coder/assets/3314957/c3806417-b90f-4453-8ac1-79a5b2d2a231)

I can't share a screen recording, as the endless redirect loop is no longer happening. 

To reproduce, you need Keycloak/ OIDC provider with a session timeout setting. This error happens, when that session ends. 

These are the session settings I have currently:

![image](https://github.com/coder/coder/assets/3314957/32eb9490-1bd9-4218-bba0-c6f3b4c4bcaf)

So, when I get back to work the next day, I'm met with that first screen above in this post now (and no longer the screen in the OP). 

Scott

**Comment by matifali** [comment]
Hi @smolinari can you elaborate on what do you expect as the desired behavior?

**Comment by smolinari** [comment]
@matifali - The desired behavior would be to just be shown the login page. The warning about the inability to refresh is superfluous. I'm obviously logged out of OIDC, so I should be logged out of Coder too (and be redirected to log in). 

In a scenario where an admin is troubleshooting OIDC connectivity, such error messages could be helpful, but they could and probably should be output as logs (with more information) on the server and not as an error in the UI. 

Does that help?

Scott

**Comment by matifali** [comment]
cc: @BrunoQuaresma

**Comment by smolinari** [comment]
This issue has gone away. I'm not sure when or rather with what version. But, now I come to this screen after not being on the computer (but leaving it on overnight) or when the connection to the database disconnects. Both are, to me, the expected behavior. 

![image](https://github.com/coder/coder/assets/3314957/de00b18a-a2d6-4a05-8289-000007e8a2e8)

I'm going to close this as resolved. If I ever run into the issue again, I'll reopen. But, it seems to be fixed. Thanks! :grin: 

Scott
