### ISSUE TITLE
Visual glitch for long lines in startup logs

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10176]
See line 241

<img width="212" alt="image" src="https://github.com/coder/coder/assets/147409/4b034d9b-2e4b-4f50-a112-bd51d93d4138">

Line:
```
0m38m4235m  3 0m37m40m1m36C0m30m4240m|4;41H|5;41H|6;41H|7;41H|8;41H|9;41H|10;41H|11;41H|12;41H|13;41H|14;41H|15;41H|16;41H|17;41H|18;41H|19;41H|20;41H|21;41H|22;41H|0m37m40m1m4;1H0m3240m~
```

**Comment by BrunoQuaresma** [comment]
@code-asher @kylecarbs I think we had a similar issue in the past related to this right? 🤔

**Comment by code-asher** [comment]
Hmm that does sound vaguely familiar but I am not sure.

**Comment by BrunoQuaresma** [comment]
@mafredri how can I reproduce this?

**Comment by mafredri** [comment]
@BrunoQuaresma I think this should do it, if you add to a startup script:

```shell
for i in $(seq 1 1000); do echo -n hi; done; echo
```
