### ISSUE TITLE
Improve UI around archiving/unarchiving template versions

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#10192]
Existing UI https://github.com/coder/coder/pull/10182

"Archving" a template version essentially hides it from the UI by default. This allows cleaning up the noise generated over time. Primarily it is helpful for hiding template versions that "failed" and are unusable. 

Template versions can be archived if:
- No workspace is currently using it
- The template version is "complete", meaning it is not "pending" or still "running" (still provisioning)

This action is reversible via "unarchive".

Lastly, there exists an api call that can archive either:
- All failed template versions
- All unused template versions.

CLI commands exist for this management.

-----

# Requirements

- The UI should be able to view archived template versions using `&include_archived=true` on the api fetching versions.
  -  https://github.com/coder/coder/blob/e3d9ed6c27a5525bd084dc4d1163985a6389d7d0/coderd/templateversions.go#L707-L707
-  Be able to unarchive template versions from the UI
- (Optional): Button to "Archive all failed versions"

**Comment by BrunoQuaresma** [comment]
@Emyrk is there a way to only see the `archived` versions? I think I'm going to use a filter or tab like we do for the workspaces and users.

**Comment by Emyrk** [comment]
On the api atm there is not, but the SQL query does support it.

**Comment by BrunoQuaresma** [comment]
> We could add another query param like archived=true/false?

@Emyrk I think this would be better if that is ok for you

**Comment by Emyrk** [comment]
If we only have `archived=true/false` and not `include_archived`, you can never query **all** template versions. Which the cli currently does when using `--all`

**Comment by Emyrk** [comment]
So might include both? Or have some `archived=all` special value?

**Comment by BrunoQuaresma** [comment]
I think what we do for the other filters is:
- If empty, return all
- We set a default value for the main field on the FE in case the filter is empty

So I guess we don't need this special type in the BE. 

You can do the BE and I can do the FE on the same PR to avoid regression of any kind.

**Comment by Emyrk** [comment]
@BrunoQuaresma my only objection to that is I wanted the default `no arguments` provided to omit the archived versions.

**Comment by BrunoQuaresma** [comment]
Sure, we can do it in the FE but if you feel strong about to make it in the BE, I'm good too 👍

**Comment by Emyrk** [comment]
@BrunoQuaresma are you trying to finish this by Friday? This Sprint?

**Comment by BrunoQuaresma** [comment]
Nops, but I think I would have time in case you find some on your side.
