### ISSUE TITLE
A new workspace from docker template does not source `.bashrc`

### ISSUE THREAD

**Issue by matifali** [coder/coder#10209]
A new workspace created from the [docker](https://github.com/coder/coder/tree/main/examples/templates/docker) template does not source `.bashrc`

This prevents setting env variables or paths defined in `.bashrc`

Coder version : [v2.2.1-devel+fafecbd9b](https://github.com/coder/coder/commit/fafecbd9b3450fb7dd02c982d46d918c99beeb13)

**Comment by mafredri** [comment]
Could you share more about the setup? `~/.bashrc` should definitely be sourced, assuming `bash` is the default shell for the user.

**Comment by matifali** [comment]
Yes. If I do `echo $SHELL` I see `/bin/bash`
And if I manually do `source .bashrc` my environment variables are set.

**Comment by johnstcn** [comment]
Bash runs as a login shell by default, which means you need to have a `.profile` or `.bash_profile`. Normally you'd source `.bashrc` in those files.

**Comment by matifali** [comment]
As per internal discussion, we can fix this by populating a new workspace `$HOME` with files from `/etc/skel/` if not present already by using the `startup_script`

**Comment by MrPeacockNLB** [comment]
We are making heavely use of scripts in our template and has to source each and everywhere the **.bashrc** or adding ~/bin to the path again as this wont work out of the box. It would be nice to get rid of this.

**Comment by mafredri** [comment]
@MrPeacockNLB alternatively, you can take a look at #12913 for how I'd solve this specific issue (#10209).
