### ISSUE TITLE
Track experiments in telemetry

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10218]
It'd be great to know what % of deployments have `CODER_EXPERIMENTS=*` or specific experiments opted-in

**Comment by bpmct** [comment]
@ammario - any interest in this one?

**Comment by ammario** [comment]
It's a good idea. I have a backlog of telemetry stuff I'm working on right now but will fix this if convenient.

**Comment by stirby** [comment]
Big fan of this idea!

**Comment by stirby** [comment]
I believe danny did this for 2.10.0.
