### ISSUE TITLE
tailscale rebinds if there is no STUN among the 3 fastest regions

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#10236]
tailscale's netcheck has an "incremental" mode where it only probes the 3 fastest regions based on the last netcheck

https://github.com/coder/tailscale/blob/c821c9c9966dd8a58f0fb03aca30743f151e57de/net/netcheck/netcheck.go#L420

If we have more than 3 regions _without_ STUN in addition to at least one region with STUN, then the incremental netcheck could choose the non-STUN regions, and not set the `IPv4CanSend` boolean true in the netcheck report.

Then, our modified logic to determine whether we should rebind:

https://github.com/coder/tailscale/blob/c821c9c9966dd8a58f0fb03aca30743f151e57de/wgengine/magicsock/magicsock.go#L539

determines that we _should_ rebind because we didn't actually send any STUN probes, but there are STUN regions in the DERPMap.

----

Yet another case of tailscale.com's assumptions (there is a STUN server in every region) not matching our deployment scenario.

**Comment by spikecurtis** [comment]
My initial take on the right solution is that we should modify the probe planning logic to include the union of the 3 fastest regions overall and the 3 fastest regions with STUN.

Something like...

```go
numSTUN := 0
for ri, reg := range sortRegions(dm, last) {
	if numSTUN == numIncrementalRegions {
		break
	}
	if ri >= numIncrementalRegions && !hasSTUN(reg) {
		continue
	}
	if hasSTUN(reg) {
		numSTUN++
	}
	...
}
```

but I'd like your opinion @deansheather @coadler

**Comment by coadler** [comment]
> My initial take on the right solution is that we should modify the probe planning logic to include the union of the 3 fastest regions overall and the 3 fastest regions with STUN.

That seems pretty reasonable to me :+1:

**Comment by spikecurtis** [comment]
Actually, it looks like we just ignore the probe entirely if there is no STUN, so I've filtered out all non-STUN regions in the planning phase, rather than taking the union of the fastest 3 overall and fastest STUN.
