### ISSUE TITLE
Improve Login Type: "None" user creation workflow

### ISSUE THREAD

**Issue by matifali** [coder/coder#10246]
## Problem

The current workflow lets you create a user, but the newly created user can not be used until a user with the role "owner" creates a token for the newly created user using the [REST API](https://coder.com/docs/v2/latest/api/users#create-token-api-key)
![image](https://github.com/coder/coder/assets/10648092/3d9852fc-459c-4614-b23e-7e4e9d75ae42)

## Suggested Solution

We can improve the UX by doing the following,

- [ ] Automatically create a token and display it in UI when a new user with Login Type: "None" is created. 
- [ ] Hide the password field altogether, as it does not apply to the user.

**Comment by aslilac** [comment]
we've discussed this elsewhere, but the disabled password field is there to reduce flicker, and I'm not keen on removing it.

**Comment by matifali** [comment]
@aslilac ok. If you think that hiding it dynamically will cause a flicker, let's keep it.

**Comment by matifali** [comment]
@Parkreiner are you still interested in this?

**Comment by Parkreiner** [comment]
Yeah, sorry about this – I can take care of this during the new sprint

**Comment by matifali** [comment]
@bpmct is this still planned? I see its assigned but couldn't make it to any sprints.

**Comment by Kira-Pilot** [comment]
Pretty old - closing for now
