### ISSUE TITLE
Improve `Validation failed` error message for template names with underscores

### ISSUE THREAD

**Issue by mnebelnlb** [coder/coder#10244]
In most programming languages I'm used to, a lower dash '_' is handled like a character and a normal dash '-' ist not allowed in variable names.  With the template names it's the other way around: a '-' is allowed and a '_' leads to a cryptic "Validation failed" after terraform ran. 

I would suggest to raise some kind of warning, when the template name is invalid.

**Comment by bpmct** [comment]
I totally agree we should have a better error message here.

**Comment by bpmct** [comment]
Related https://github.com/coder/coder/issues/7046
