### ISSUE TITLE
support configurable TLS ciphers

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10269]
we currently do not allow operators to set ciphers for the built-in TLS server. a prospect reached out about setting their own ciphers, as a result of a security scan.

note that TLS 1.3 does not support configurable ciphers, so this would only be applicable to TLS 1.2 & below.

**Comment by Emyrk** [comment]
Around here: https://github.com/coder/coder/blob/6b7858c5166dc89c1768ecadcdd025d84bc751ea/cli/server.go#L1460-L1460
