### ISSUE TITLE
bug: If a user is dormant, the Group UI will not show them in the list view.

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10267]
Version: [`v2.3.0+04e6783`](https://github.com/coder/coder/commit/04e67836a500d668c0bd3c8eb825c799a893dbb0)

If a user is dormant, the Group UI will not show them in the list view.

This can lead to conditions like an admin thinks they added a user to a group, but they do not show in the list. They try adding the user again, and it says a duplicate user is already in the group.

**Comment by BrunoQuaresma** [comment]
I found this is an API thing where dormant users are not displayed. In this case, we need some BE + FE work. cc. @mtojek do you think we can do it on the next few days or is it better to move it to the next sprint?

**Comment by sreya** [comment]
I'll fix this tomorrow.

**Comment by janLo** [comment]
I guess this will also fix #10064
