### ISSUE TITLE
bug: python ports showing in `ports` workspace UI when running Jupyter

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10266]
Version: [`v2.3.0+04e6783`](https://github.com/coder/coder/commit/04e67836a500d668c0bd3c8eb825c799a893dbb0)

python ports showing in `ports` workspace UI when running Jupyter

This is an annoyance and should be hidden.

![image](https://github.com/coder/coder/assets/2022166/b0b03268-bfa2-499b-a3f3-5689f73e6536)

Temporary fix is to disable the ports UI app in `coder_agent`

```hcl
  display_apps {
    port_forwarding_helper = false
  }
```

**Comment by matifali** [comment]
IMO, We should stop detecting ports automatically and only display the ports a user forwards manually. It isn't easy to filter the ports otherwise.  
cc;; @bpmct for thoughts?
