### ISSUE TITLE
Consolidate coder agent network requests to coderd API under a single WebSocket or gRPC

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10278]
Currently there are multiple HTTP requests that the coder agent does periodically towards the coderd API.

- Agent lifecycle
	- There are only a few of these, if we consolidate them, it's to reduce server load caused by a lot of agents starting up simultaneously
- Agent stats, typically reported once every 30 seconds
- Agent metadata, reported once every (some intersection between `min(interval)` and `num(unique interval)`)
- Agent logs, typically reported in batched bursts whenever a script is running
	- Does not make sense to consolidate with the other data, though, it may cause congestion for stats/metadata which are more important
- Get service banner, fetched every 2 minutes
	- This is periodically fetched, it could be consolidated via a pubsub subscription server side and pushed to agent on change, in a 1000 agent deployment, that's a reduction of 8 requests/second
- Get manifest / post startup
	- This is done once on startup, but similar to the lifecycle report, could be consolidated to reduce simultaneous agent startup load
- App health check reports, reported every second (but only if the health changed)

Consolidating all of most of these requests under a single WebSocket (except agent logs) would help reduce load caused by initiating HTTPS requests and the single connection nature would also help reduce the impact of how much load a single misbehaving agent may cause (#8556).

**Comment by spikecurtis** [comment]
Fixed along with #10534
