### ISSUE TITLE
bug: unable to pass in a list of strings as a rich parameter through CLI

### ISSUE THREAD

**Issue by cforno12** [coder/coder#10293]
Hi Coder devs! After some debugging with Phorcys over in the discord server, we have come to the conclusion that the CLI does not support the ability to send a list of strings as a rich parameter. See thread for more information: https://discord.com/channels/747933592273027093/1162136691214135327/1162136691214135327

Thanks!

**Comment by cforno12** [comment]
Sure, so I'm attempting to create a workspace via the CLI with a given `coder_parameter`. This `coder_parameter` is of `type=list(string)` with the default value of `jsonencode(["A","B","C"]).` Since it seems that I can't specify `default` as the value. I'm not able to create a workspace like this, for examble, `coder create workspace-cforno12 --parameter param=["A","B","C"]`. The CLI complains that it is not valid, `format key=value expected, but got B`. When inspecting how the web UI sends in the request to the Coder server, the request looks like:
```
{name: "param", value: "["A","B","C"]"}
name: "param"
value: "[\"A\",\"B\",\"C\"]"
template_id: "2d34ae33-903e-487e-bce0-f24818fde433"
```
Therefore, we concluded that the CLI does not support sending in a list of strings as a rich parameter.

**Comment by mtojek** [comment]
> This coder_parameter is of type=list(string) with the default value of jsonencode(["A","B","C"]).

For readers: Coder treats workspace build parameters as string values. In this case, the `list(string)` is mapped to a JSON string.

> Since it seems that I can't specify default as the value, I have to explicitly list the values that I want.

I agree this may be inconvenient, but I'm happy to see your CLI proposal on how this can be improved.

> The CLI complains that it is not valid, format key=value expected, but got B.

I see what you mean. I'm afraid that it is outcome of the default behavior of the library we're using for flags, spf13/pflag. I believe this is a [similar issue](https://github.com/spf13/pflag/issues/370) to yours. As a workaround, we could switch from StringArray to a simple string, and parse it in Coder.

**Comment by cforno12** [comment]
For others that might run into this issue as well; I used the flag `--rich-parameter-file` and added the parameter list string in a yaml file and passed it in and works.

**Comment by geiseri** [comment]
For those that find this on google, its documented in [here](https://coder.com/docs/templates/parameters#types).
