### ISSUE TITLE
Set fs.inotify.max_user_watches on host machine

### ISSUE THREAD

**Issue by jbcdnr** [coder/coder#10309]
Hello,

We need to increase the `max_user_watches` for watching some files. Trying to increase `max_user_watches` in the coder container fails:

```bash
$ echo 65536 | sudo tee /proc/sys/fs/inotify/max_user_watches
tee: /proc/sys/fs/inotify/max_user_watches: Read-only file system
65536
```

We need to run this command on the hostmachine. Where can we configure this?

Thanks a lot.

**Comment by matifali** [comment]
Hi @jbcdnr, https://github.com/coder/code-server/issues/628 is related. You need to set this on the docker host machine.
