### ISSUE TITLE
Preflight checks to stop launch failures on limited compute

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#10323]
Just wondering if there's been any movements on preflight checking facility in Coder?

We now have a FastAPI endpoint for pre-flight checking capacity on a Kubernetes cluster based on inputs but we'd like Coder to fail the apply before it got to the terraform apply part.

**Comment by kylecarbs** [comment]
I wonder if you could do this jankily with a data-source instead in Terraform? Maybe with the HTTP provider?

**Comment by dcarrion87** [comment]
@kylecarbs that's what we're doing. But like you said it's extremely janky in the way it fails. This could be a nice addition to coder to handle gracefully.
