### ISSUE TITLE
Admin view of outdated & deprecated agents

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#10341]
#10339 adds support for tracking the Agent API version
#10340 defines a new "deprecated" state for an agent to be in relative to the server Agent API Version

We need to give Coder admins the ability to find all outdated or deprecated agents (or rather all workspaces with outdated or deprecated agents).

This could be accomplished with the existing WorkspacesPage by surfacing the agent's API and Product Versions (and filters for outdated and deprecated), or with a new page.

**Comment by bpmct** [comment]
I guess we need to add a search query for this?
