### ISSUE TITLE
Provisioner Daemons page on the dashboard

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#10344]
#10343 adds tracking Provisioner Daemons

Add a page to the dashboard, visible to administrators, that shows all connected Provisioner Daemons.  Page should be broadly tabular with columns:

 * name
 * tags
 * connection time (or duration since connection)
 * Product version
 * API version
 * in-memory or external
 * warnings: outdated or deprecated
 
Where "deprecated" means the API version is one or more major versions behind the server API version, and "outdated" means the product version is behind the server Product version

**Comment by BrunoQuaresma** [comment]
@spikecurtis is it ready for development in the UI?

**Comment by spikecurtis** [comment]
@BrunoQuaresma  #10343 needs to be finished before we can actually implement, but would love to get some figma/wireframes/storybooks for what it might look like

**Comment by matifali** [comment]
@spikecurtis @BrunoQuaresma we have many of these on the new health page except "_connection time (or duration since connection)_"

**Comment by bpmct** [comment]
![Screenshot 2024-04-26 at 9 45 00 AM](https://github.com/coder/coder/assets/22407953/5bbde1ca-4098-4a04-be99-fedca6db26c2)

I'd say we're close enough
