### ISSUE TITLE
Feature Request: CLI to suggest self update to match server version

### ISSUE THREAD

**Issue by matroscoe** [coder/coder#10357]
The CLI seems to work best when exactly paired with the version deployed to the server. It would be a really nice feature to have a self update or even if you try to run the update that it brings you to the download page for the exact version of coder that you should be installing based on the server you are attempting to connect to.

**Comment by matifali** [comment]
CLI already suggest how to download the correct version

```console
coder ls
version mismatch: client v2.2.1+46551e6, server v2.3.1-devel+b79901483
download the server version with: 'curl -L https://coder.com/install.sh | sh -s -- --version 2.3.1'
```

**Comment by kconley-sq** [comment]
I've also been wishing a feature like this could be added so that the CLI binary could self-update to match the server version when a version mismatch is detected, to avoid the user having to copy and paste the install script command.

**Comment by bpmct** [comment]
Hey - we've been hesitant to do this as many folks deploy Coder in network-gapped environments where the artifact is not downloaded from the public internet. We want to suppor this in a neutral way. We also want to support package managers, like our install script.

If y'all have examples of software that does this well, let us know.
