### ISSUE TITLE
feat: Make it optional to restart workspace if template version is changed

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10367]
A customer gave feedback that when iterating through template development, it would be nice to optional not automatically restart a workspace when a template version is changed.

**Comment by mafredri** [comment]
I've also had a need for this when developing templates. My current workflow involves pressing the update button, and then immediately hitting cancel afterwards. It's far from ideal.

A soft update that switches to the new version on next manual (or schedules) workspace start would be ideal.
