### ISSUE TITLE
When will Coder update its DockerHub images from `20.04` to a more recent release?

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10368]
A customer is asking when our base Ubuntu image will be updated to a more recent [release](https://releases.ubuntu.com/) of Ubuntu? e.g., `22.04.3 LTS`

Coder's [Dockerfile](https://github.com/coder/enterprise-images/blob/main/images/base/Dockerfile.ubuntu) for base image with `ubuntu:20.04`

**Comment by matifali** [comment]
Images are now based on Ubuntu 22.04.
