### ISSUE TITLE
Docker-Compose Aarch64

### ISSUE THREAD

**Issue by DJSwiss** [coder/coder#10370]
I'd be happy who would work on the Arm Platform with Docker.
.

**Comment by mafredri** [comment]
What issue did you have? Coder is supported on ARM64.

For instance, this command works just fine:

```
docker run --platform linux/arm64 -it --rm ghcr.io/coder/coder:v2.3.2
```

Note: I'm explicitly providing `--platform` here for demonstration purposes, but that's not required.
