### ISSUE TITLE
Introduce a minimum lifetime to templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10372]
## Current behavior

Our current scheduling behavior will turn off a workspace after `n` hours of inactivity. When a user is active in their workspace, the

## Product Requirements 

We might do this via a module or a first-class feature. See https://github.com/coder/customers/issues/318 for fine-grained details

**Comment by sreya** [comment]
@bpmct what if we just expose another setting for the interval we use to bump a workspace's TTL when we detect activity? We can default to what we do now and users who don't like it can use whatever interval they think makes sense.

**Comment by matifali** [comment]
Closed in #10704
