### ISSUE TITLE
Unable to configure a CLI option to be the empty string via environment variables

### ISSUE THREAD

**Issue by beepboop271** [coder/coder#10389]
I was trying to switch agent and server logging to use JSON entirely rather than the human format, but noticed that I couldn't seem to achieve this properly by setting environment variables.

https://github.com/coder/coder/blob/main/cli/agent.go#L76-L96

https://github.com/coder/coder/blob/8f1b4fb061365b071f7b6ad881ac759a8464a6f0/cli/agent.go#L76-L106

The code seems to want a value of an empty string, but when I set the necessary environment variable to an empty string, I get the default setting (where the human logger is set to `/dev/stderr`).

In the meantime, I've just set the human logger to something else, but I believe this code is the cause for the above issue:

https://github.com/coder/coder/blob/main/cli/clibase/option.go#L274-L284

https://github.com/coder/coder/blob/8f1b4fb061365b071f7b6ad881ac759a8464a6f0/cli/clibase/option.go#L274-L284

As the code itself notes, it would be nice if this behaviour was changed.

**Comment by bpmct** [comment]
Hey @beepboop271, sorry we never responded here! Since October, we moved to a different CLI so I'd imagine the behavior has changed. We're currently bulk-closing issues but if you are still seeing / working around this behavior, let us know and we can take a look
