### ISSUE TITLE
Coder CLI Remove Template Version

### ISSUE THREAD

**Issue by faresherhar** [coder/coder#10405]
Hi,
We're managing multiple templates, and for some templates, we're having too many versions, so we thought of deleting the older versions.
What it would be a good idea, is to add a `Template Version Deletion ` feature, especially from the CLI, like `coder templates versions remove TEMPLATE_NAME  --name VERSION_NAME`.

**Comment by matifali** [comment]
This is available with `coder templates archive` to achieve old versions. This should be available as per v2.3.0.
Please take a look at #10179 for more context. 

@Emyrk can put more highlights on this.

**Comment by faresherhar** [comment]
@matifali I tried it, but on the interface, I still can see the older versions, and the users can use any of the older versions to create a workspace.

> Archiving

![Capture](https://github.com/coder/coder/assets/102948288/3bd4995d-367c-4e76-980f-dc1f8c4d4441)

> Coder Interface

![Capturez](https://github.com/coder/coder/assets/102948288/a1380204-c1bb-4a43-9649-c50075ea0f57)
