### ISSUE TITLE
"Address already in use"

### ISSUE THREAD

**Issue by FormunaGit** [coder/coder#10410]
So i'm trying to install Coder and it installs but when I start the server it gives this error:

```bash
walugu@wserver:~$ coder server
Coder v2.3.2+1372bf8 - Your Self-Hosted Remote Development Platform
Encountered an error running "coder server"
configure http(s): listen tcp 127.0.0.1:3000: bind: address already in use
```
I've tried an Nmap on it, no the ports aren't being used. I also use Invidious belong side other apps, so I edited the ports for Invidious (by default it's 3000:3000, the same with Coder) to different ones but still didn't work.

SYSTEM INFO:
OS: Linux Mint 21.2 x86_64
Host: VivoBook_ASUSLaptop E203NA 1.0
Kernel: 5.15.0-76-generic
Shell: bash 5.1.16
CPU: Intel Celeron N3350 (2) @ 2.400GHz
GPU: Intel HD Graphics 500
RAM: 2GB

**Comment by matifali** [comment]
How are you installing and running the coder?
You can try changing the coder port by setting
`CODER_HTTP_ADDRESS=localhost:3001`

**Comment by FormunaGit** [comment]
Hi @matifali, I installed it via Docker and ran `coder server`
I can't use your idea right now because for some reason my server keeps destroying my router after I installed PiHole. I will try to use your idea after.

**Comment by matifali** [comment]
Any update @FormunaGit ?
