### ISSUE TITLE
Provisioner Metadata

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10412]
## Background

Coder [Provisioners](https://coder.com/docs/v2/latest/admin/provisioners) allow specific templates (or all templates) to be provisioned on a separate machine from the Coder server.

Provisioners can be a very secure way to run Coder across clusters or datacenters since limited network access or permissions are needed for the central Coder server.

With #5979, users can pick which provisioner they would like to use for their template to ensure that their workspace is always provisioned on the same system, for example. Whether that is a bare metal machine, local machine, or Kubernetes cluster.

## Proposal

Provisioners may have different qualities (e.g. datacenter, region, operating system, or % CPU on the host). It would be valuable to display this unique info about provisioners in the Coder dashboard, CLI, and API. Specifically the "create workspace" flow.

Unlike agent metadata, which is defined with Terraform and bash that runs on the host, I think it is fine if, in the first version, provisioner metadata can only be updated/modified via the REST API. 

This will allow the following use cases:
- Users can see what network/cluster each provisioner runs on (deciding factor for running workspace)
- Users can see how many GPUs each cluster has
- Users can see how many workspaces are on each host (allows admins to create some basic "packing")
  - This won't actually prevent provisioning but can showcase when a provisioner is crammed

## Product Requirements

> **Note**
> #5979 is a prerequisite for this issue

### Must have

- Provisioner metadata is displayed on the create workspace screen and CLI flow for creating workspaces
   <img width="1470" alt="Screenshot 2023-10-29 at 4 56 42 PM" src="https://github.com/coder/coder/assets/22407953/8db75617-2513-43db-889b-3e15a1461020">
- Provisioner metadata can be set via REST API (e.g. some 3rd-party service updates metadata every 15 mins or sets it once)

## Should have

- Some default metadata about the provisioner (OS, Architecture) is sent via metadata, but can optionally be disabled

## Nice to have

- Provisioner metadata can be set via UI and CLI (e.g. commands that run on provisioner? idk)

**Comment by spikecurtis** [comment]
The example use cases, I think, fall into two broad categories so far:

Identity type metadata about the provisioner, for attribution and debugging.

* Pod / Namespace (K8s)
* Instance ID (VMs)
* IP address
* OS
* Architecture

Resources in the cluster

 * CPU
 * GPU
 * Number of workspaces
 
In the former case, all the examples I've heard of are static.
 
In the latter case, this metadata isn't actually scoped to the _provisioner_, it's scoped to the cluster.  The relationship between provisioners and clusters is not 1:1 in the general case.  There may be multiple provisioners servicing a single cluster, and/or a provisioner might service multiple clusters.

**Comment by matifali** [comment]
Are we talking about auto assigning metadata? We can assign any metadata as tags to provisioners via CLI only on provisioner start. 
Would be good to also update that via UI without restarting the provisioners.
