### ISSUE TITLE
Let users always see their own groups from the Accounts page

### ISSUE THREAD

**Issue by Parkreiner** [coder/coder#10425]
Continuation of #10284

Basically, one of the current issues with the website is that it if a user doesn't have permission to view the Groups page, they have zero ability to see what groups they belong to.

Ben floated the idea of putting the information inside the User dropdown, but I have a few concerns about that:
- Group names have no limits to how long they can be
- As the number of groups a user belongs to keeps growing, the dropdown will eventually get cartoonishly long
- The account dropdown isn't terribly wide to begin with
- If we try to cram all the information in the dropdown anyway, the only solution I can think of would involve hover behavior. The problem is, because the hover modal would need to be placed in the account dropdown, we'd have modals inside of modals, which poses accessibility risks

I think the better option is to add the information to the main Account page. That way, there aren't any modals to worry about, and we have a lot more space to work with when laying out the UI elements.

**Comment by matifali** [comment]
The account page sounds like the better option.
