### ISSUE TITLE
AWS TLV(il-central-1) Region is not supported

### ISSUE THREAD

**Issue by NathanelLevi** [coder/coder#10433]
Hi!

We had an issue with setting up coder environment above EC2's in AWS TLV region.
We have our own coder server that is implemented in K8S cluster with only 1 pod.
And we have a template that is created with Terraform in order to set this remote DEV env for the users.

The problem is the fact that we are getting this error while trying to set up the EC2 instance in the TLV region:
```
2023-10-18 07:45:05.455 [warn]  run exited with error ...
    error= exchange token:
               github.com/coder/coder/v2/agent.(*agent).run
                   /home/runner/actions-runner/_work/coder/coder/agent/agent.go:576
             - POST [http://int-skai-coder-staging.internalk-stg.com/api/v2/workspaceagents/aws-instance-identity ](http://int-skai-coder-staging.internalk-stg.com/api/v2/workspaceagents/aws-instance-identity): unexpected status code 401: Invalid AWS identity.: Try logging in using 'coder login <url>'.
                Error: crypto/rsa: verification error
```
As I see in your implementation the TLV region Public RSA key is not there.

[AWS identity implementation](https://github.com/coder/coder/blob/main/coderd/awsidentity/awsidentity.go#L18-L26)

Can you please add it and release a newer version with support for that?

Thanks in advanced

**Comment by kylecarbs** [comment]
Ahh, yes! We'll do this now.

**Comment by kylecarbs** [comment]
@NathanelLevi I've gone ahead and added all new regions to zero-trust identity. It will be out in the next release!

Is this blocking you?

**Comment by NathanelLevi** [comment]
@kylecarbs thanks!! 🥇 

Yes, It's blocking us for now.
How long will it take in order to release this new version with the above changes?

**Comment by kylecarbs** [comment]
We can do a release right away after merge. 30m!

**Comment by NathanelLevi** [comment]
@kylecarbs WOW !!

I would be happy to try it 😇

**Comment by NathanelLevi** [comment]
@kylecarbs I saw that there is a new tag with this new version but it's still not in the releases.
Can I use it already?
Or should I wait for the released tag?

**Comment by kylecarbs** [comment]
The release workflow failed. Well run it again... normal assets will be published.

**Comment by kylecarbs** [comment]
@NathanelLevi it's published!
