### ISSUE TITLE
feat: allow coder_app to open in new tab

### ISSUE THREAD

**Issue by stirby** [coder/coder#10437]
## Overview
Currently, `coder_app` resources open their respective interfaces in a new browser window, but we've had some requests to allow them to open in a new tab instead. Instead of making this behavior a default, it could be built with an opt-in for individual users.

## Previous Implementation
This was built in #4950, then reverted due to complaints about the lack of configurability.

## Implementation details 
This should be configurable for each user and simply employ the behavior form #4950 when enabled. The option would be to open the app into a new browser window (default), or new tab (enabled). The dialogue could be as simple as “Open Coder Apps in new tab”.

To add this into user settings, the "schedule" tab could be converted to a "workspace settings" tab. This tab would contain the workspace schedule, this `coder_app` configuration, and leave room for related features in the future.

**Comment by kylecarbs** [comment]
@stirby the title should be more descriptive. There are a million ways an app could be configured. Your description is great!

**Comment by stirby** [comment]
Super low priority, will revisit if customers raise this.

**Comment by eswolinsky3241** [comment]
@stirby Not a high priority for us but I'd be interested in having this as an option
