### ISSUE TITLE
bug: Experiment `dashboard_theme` sometimes reverts to blue-ish original colors

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10440]
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

<img width="1287" alt="image" src="https://github.com/coder/coder/assets/2022166/42ccff94-516d-483e-b5bd-72af6258a3cd">

I have the `dashboard_theme` experiment enabled. Across Firefox and Chrome, I sometimes notice the original blue-ish, not entirely black theme. A hard refresh of the browser fixes this temporarily.

Also the default home page has a bluish graphic which should be adjusted.

<img width="1020" alt="image" src="https://github.com/coder/coder/assets/2022166/eff13fb7-0fa2-40ec-9fdd-94339acdf0ba">

**Comment by sreya** [comment]
Theming has gone through a significant overhaul, feel free to reopen if this issue persists
