### ISSUE TITLE
Propose RFC for enabling downgrades 

### ISSUE THREAD

**Issue by sreya** [coder/coder#10446]
Right now it's not possible to downgrade deployment versions after an upgrade. This can be obnoxious for users as it requires a lot of effort on their end to ensure that they can continue to use the product if they encounter a regression (e.g. create a db snapshot).

**Comment by Emyrk** [comment]
We are not going to support downgrading at this time.

Downgrading will still require backing up the database. 

Investigation notes: https://www.notion.so/coderhq/Downgrading-Coder-Investigation-721f2394da874d45895faf5dacb32b81


Tl;dr: we could support downgrading patches without migrations (db changes) in the future.
