### ISSUE TITLE
bug: On workspace list view, pagination says there is another page, but if I click it, nothing is there

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10452]
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

The pagination says there is another page, but if I click it, nothing is there

Loom video of bug
https://www.loom.com/share/68e1a684fd45458fb7be048f107944db

**Comment by BrunoQuaresma** [comment]
@Parkreiner if you have time, would be amazing to refactor this component to a better DX. Right now, at least for me, it looks confusing to use and not very declarative. Wdyt?

**Comment by Parkreiner** [comment]
@BrunoQuaresma Yeah, I can definitely take a crack at refactoring this

**Comment by Parkreiner** [comment]
Marking this as closed. There are still a couple of pagination-related issues I'd like to get to, but I went ahead and documented them in new issues. Aiming to start on these problems next sprint.
