### ISSUE TITLE
Option to recreate a workspace with same settings as before

### ISSUE THREAD

**Issue by clitters** [coder/coder#10477]
Hi,

this is my first issue. I am glad for anyone helping me to contribute as good as possible so feel free to add some hints for me.

We are working on many repositories with the same container template. To make that easier I added options to the templates for our devs to select the repo and other options. So far that works absolutely great.

Sometimes while developing things get messed up. As you restart the workspace, the container is recreated. But the docker volume stays persistent, which is totally by design I think.

But to start over from scratch it would be very handy to have an option to recreate the workspace with one click and with that the corresponding volume. For me it would be ideal located beside the delete button for the workspace, as it also causes possible loss of data.

I also could try to create a pull request if that would be helpful and maybe with a little bit of help.

thanks in advice
christoph

**Comment by matifali** [comment]
If you wish you can make the docker volume non persistent or not mount a volume at all. That would be a fully ephemeral workspace. 
And for your request, I guess is similar.

**Comment by clitters** [comment]
Thank you for the reply.
You are right if I would like to have it always ephemeral that would be a nice solution.
But I want to persist the data in general and also be able to recreate if I need to.
