### ISSUE TITLE
feat: store dotfiles url by user

### ISSUE THREAD

**Issue by stirby** [coder/coder#10478]
## Problem statement

Currently developers must re-enter their Dotfiles URL every time they create a new workspace. Most developers are not using a diverse set of dotfile repositories, so this action becomes repetitive. To avoid tedious repetition, we can reduce the number of times Dotfiles URLs are repeated.  

## Implementation notes

Customers have suggested a few methods to allow users to store or cache their Dotfiles by account rather than by workspace.

### Option 1 - User Storage

A straightforward system would allow users to store their dotfiles URL in the account settings. Then, the coder_parameter would be automatically filled with the account dotfiles URL, or simply be a boolean checkbox to “Clone Dotfile repository from account”.

<img width="809" alt="Screenshot 2023-11-01 at 2 55 21 PM" src="https://github.com/coder/coder/assets/58410745/adc1ebcd-e44a-4b82-b4a5-3209f0ac9e8c">

### Option 2 - Caching last used Dotfiles URL

The customer suggested that the Dotfiles parameter text could simply be pre-filled with the last repository entered for a given user. To extend this, the text field could also have a drop-down (possibly searchable) list of previously-entered Dotfile URLs sorted by usage. This list would be appended to with each new repository entered.

### Option 3 - Generic user-wide parameters

To extend the capability of option 1, a generic user-wide parameter list could be created to store any variable currently used in coder_parameter's, similarly to how tokens are configured now. This functionality is better described [here](https://github.com/coder/coder/issues/7087).

## Impact

This is an annoyance for users that costs time during the creation of workspaces. For a more empirical measurement of impact, our Dotfiles module on the registry has over 2300 installs.

**Comment by matifali** [comment]
That would be super helpful. Issues #7087 , #7272 and #7280 are similar. 

This is a duplicate of #7272. You may close one of these.

**Comment by kylecarbs** [comment]
I really like option 2. It's a clean abstraction that can be per-template for users that create a lot of workspaces.

**Comment by matifali** [comment]
For option 2. Could we also use browser cache/storage? cc: @BrunoQuaresma 
It could also work like password autofill works by suggesting last typed values.

**Comment by ammario** [comment]
My understanding of option 2 is we would suggest the list of previously used values for the same parameter name (regardless of whether it's "dotfiles_url")?

@matifali — I think we should lean on the DB here to provide a consistent experience since we already have the parameter data there.

**Comment by matifali** [comment]
@ammario if we do want to use database then I think option 1 is better. We can just allow a user to specify their dotfiles in their account settings page.

**Comment by ammario** [comment]
Option 1 is a non-starter to me, as it adds a new, opinionated "dotfiles" primitive to the product. I also don't see how using the database would make Option 1 better. We can go with Option 2 using what we already store in the DB.

**Comment by fcsonline** [comment]
Option 3 would be awesome! I know that is the one that requires more development, but it is the more and predictable solution. Even we could do something like:

```diff
 data "coder_parameter" "dotfiles_uri" {
   name        = "What dotfiles repo would you like to use for your workspace?"
   description = "Dotfiles repo URI (optional). See https://dotfiles.github.io"
   icon        = "/emojis/1f9f0.png"
   default = "https://github.com/example/dotfiles.git"
+  default_env = "DOTFILES_URI" # This will load the environment variable configured in the user profile
   mutable = false
 }
```

The cool thing about this approach is that we can extend it to whatever `coder_parameter` we have, not only the dotfiles one.

**Comment by aaronlehmann** [comment]
I agree that option 3 for generic user-specified `coder_parameter` defaults would be really valuable. The dotfiles use case presented here makes a lot of sense, and I could also see this being very useful for things like region defaults (East Coast users can select the "US East" region as their default, etc.).
