### ISSUE TITLE
Add prometheus metrics for full workspace start up time

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10479]
## Background

We have customers who are very interested in measuring and optimizing the time it takes for an engineer to create or start a workspace. When a workspace is starting, two primary steps are kicked off:
- provisioner job (`terraform apply` to create infrastructure)
  - current metric: coderd_provisionerd_job_timings_seconds  
- waiting for agent to download and connect on workspace
  - current metric: `coderd_agents_up` (kinda, it's not a timing but it changes from 0 to 1)
- waiting for startup script to complete
  - current metric: none

We have `coderd_provisionerd_job_timings_seconds` for jobs but not for how long it takes for a startup script.

## Proposal

- Add metric for how long it takes for startup script
- Add metric for how long it takes for agent to connect
- Add overall metric for workspace start time

**Comment by bpmct** [comment]
I'm not a prom/grafana expert though so I may be misunderstanding the best way to measure this

**Comment by Emyrk** [comment]
In v1 I added a way for the agent to push arbitrary metrics, making adding workspace side metrics very easy.

I think right now we send over a custom metrics payload?

**Comment by Emyrk** [comment]
Hmm we only support counters and gauges at the present: https://github.com/coder/coder/blob/78517cab527c5c1d4eae35f31f3fbc3cb7ca76ca/agent/metrics.go#L71-L84

Makes some things a bit challenging.
