### ISSUE TITLE
No error message when creating a workspace with a duplicate name

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#10476]
Specifying a workspace name that duplicates the name of an existing workspace just causes the UI to return immediately without showing an error or doing anything. It would be clearer if the UI showed an error message in this case.

**Comment by kylecarbs** [comment]
Oofta, this is a bad bug. @BrunoQuaresma

**Comment by ericpaulsen** [comment]
i believe this was fixed in 2.3.3. previously closed issue: https://github.com/coder/coder/issues/10268.

@aaronlehmann are you seeing this behavior in 2.3.3?

**Comment by aaronlehmann** [comment]
Ah, no, looks like we're still on 2.2.0. Thanks for the quick reply and sorry for the noise.
