### ISSUE TITLE
stick to consistent terminology re: build options / ephemeral parameters

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#10488]
When authoring templates the concept is called an "ephemeral parameter" but when starting workspaces it's a "build option."  The CLI help gives no further explanation of what a build option is.

We need to use consistent terminology.  Template authors are often end users.  Template authors and end users need to be able to communicate with one another about templates and workspaces, so they need a common set of terms.

**Comment by BrunoQuaresma** [comment]
cc.: @mtojek

**Comment by mtojek** [comment]
@spikecurtis Referring to our [docs](https://coder.com/docs/v2/latest/templates/parameters#ephemeral-parameters):
* in Terraform it is called "ephemeral" parameter
* in UI it is build option.

AFAIR, ephemeral was considered to be a bit mysterious, hence we decided to replace it with simpler term, a "build option".  Without breaking API/Terraform changes, we can remove all references to ephemeral except for the Terraform template, unless we deprecate it, and define a new one - `build_option = true`.

Personally, I like the `ephemeral` as it is more descriptive.

**Comment by spikecurtis** [comment]
I just want it to be consistent in both places.  We'll have to deprecate the old term in one place or other but keep it as an alias for back compat.

**Comment by mtojek** [comment]
@bpmct Are we good with deprecating `ephemeral` and replacing it with `build_option`? This will affect code, database schema, and docs, but it shouldn't be breaking.

**Comment by bpmct** [comment]
@kylecarbs expressed that the terminology build_option compared to build_parameter is pretty confusing. I agree. Naming is hard 😅 

Because of this, my preference is to remove any terminology/db stuff for `build_option` as well 👍🏼

**Comment by bpmct** [comment]
Yep

**Comment by bpmct** [comment]
Did we do this? adding it into next sprint as a good debt item

**Comment by defelmnq** [comment]
Trying to understand the whole scope of this ticket as I'm working on it , I've seen there's two parameters : 

```
      --build-option string-array, $CODER_BUILD_OPTION
          Build option value in the format "name=value".

      --build-options bool
          Prompt for one-time build options defined with ephemeral parameters.
```

Do we want to deprecate both or one specifically ? 

The first one seems to be a list of key=value while the second one is enabling the prompt for each parameter considered as ephemeral in the template.

**Comment by spikecurtis** [comment]
I think we want to deprecate both, but keep them around as an alias to "ephemeral parameters"

**Comment by defelmnq** [comment]
Closing this one as we merged [the associated PR ](https://github.com/coder/coder/pull/15030). Should be good with build-option(s) staying as deprecated and ephemeral-parameters replacing it.
