### ISSUE TITLE
Mark workspaces of suspended users as dormant immediately

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10480]
Suspended users may have workspaces automatically running. We have had a major customer request that we leverage workspace cleanup to auto-mark suspended users' workspaces as dormant to accelerate the workspace being deleted to free up infrastructure.

**Comment by sreya** [comment]
Dormancy is tied to the template. We can place workspaces in the dormant state to avoid them being autostarted but autodeletion is dictated by the template's setting. I'm not sure how ensure all workspaces get deleted short of introducing a deployment-wide flag for a max workspace dormancy ttl.

**Comment by kylecarbs** [comment]
Seems like this is old and no longer relevant? Closing.
