### ISSUE TITLE
feat: add actual http route to prometheus metrics

### ISSUE THREAD

**Issue by sreya** [coder/coder#10498]
We export requests processed but we only have the generic route akin to `/api/v2/workspaceagents/{workspace_agent}`. When troubleshooting a spike in 500 errors it's difficult to figure out which workspace agent is at fault. We should also add the actual HTTP route being hit that includes the ID under some label like `real_path`.

**Comment by sreya** [comment]
Ahh I see that's unfortunate.

**Comment by Emyrk** [comment]
@spikecurtis I think we do this though if `prometheus-collect-agent-stats` is set to true.

https://github.com/coder/coder/blob/921b6eb4ee9f78059b5991a66d7aeaa4efbb385b/codersdk/deployment.go#L874-L882

**Comment by spikecurtis** [comment]
Even with that flag and the warning, we would need to be very careful to _only_ include agent IDs, not just the raw HTTP path on our HTTP metrics, which would include all kinds of unbounded IDs (users, workspaces, builds, etc).

I still think the right answer is to look at logs for this use case.
