### ISSUE TITLE
Agent process metrics

### ISSUE THREAD

**Issue by raphaelfff** [coder/coder#10509]
It would be very useful fo have workspace metrics in coder, like cpu, ram, process etc, similar to the GCP OpsAgent: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent

**Comment by kylecarbs** [comment]
Could you use something like the Ops agent with the Coder agent already? I think that'd be preferred over us going into the monitoring space.

**Comment by raphaelfff** [comment]
I can't use the OpsAgent it seems...
And any other system, means that now I have to get into the monitoring space ^^

**Comment by ammario** [comment]
Can [Agent Metadata](https://coder.com/docs/v2/latest/templates/agent-metadata#agent-metadata) solve your problem?

**Comment by raphaelfff** [comment]
Not really, the real issue i m trying to solve: Sometimes, we have a workspace crash due to resource exhaustion (mem or cpu), so we wanna be able to figure out what caused the crash. When running a straight up VM, i would use the ops agent, look at the charts for cpu/mem & process history
Its also helpfun to help size the workspace, based on historical data
I would like to replicate the same in Coder

**Comment by ammario** [comment]
To close the loop here, while we see the value of integrated monitoring _eventually_, we don't have the resources to consider building it in the short term.
