### ISSUE TITLE
button to promote template version displayed to members, not clickable

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10504]
our button to promote a template version is displayed to `member` roles, despite them not having the privilege to conduct the operation. clicking the button itself does not do anything, and we should remove it from view.

reproduced on 2.3.3

<img width="430" alt="Screenshot 2023-11-02 at 16 25 03" src="https://github.com/coder/coder/assets/9683576/821cf47d-8cbb-49f1-a7fd-8b4b51559ae6">

**Comment by BrunoQuaresma** [comment]
@aslilac is probably related https://github.com/coder/coder/issues/10002 is it something I can assign to you as well?
