### ISSUE TITLE
Display "update" CTA for out of date workspace

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10506]
We avoid putting the CTA here

![image](https://github.com/coder/coder/assets/22407953/054b150d-abd3-4ed1-8eba-69dfd3d43c69)

Despite having one here

![image](https://github.com/coder/coder/assets/22407953/5abcdf30-5adf-453d-b33f-f903f7cf5fba)

I think adding an update button / CTA is very important in the blue update prompt

**Comment by BrunoQuaresma** [comment]
Not applicable anymore in the new design.
