### ISSUE TITLE
Showing the regex in parameter validation error is not user-friendly

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10525]
## Current behavior

If there is a custom validation error set, it shows both the error and regex, which is a bit funky.

## Proposed behavior

Only show the regex if there is no custom validation error.

See an example in this private issue: https://github.com/coder/customers/issues/320

**Comment by BrunoQuaresma** [comment]
Do we support custom validation errors? 🤔 cc.: @mtojek

**Comment by mtojek** [comment]
This might be just a response from BE. If you have time, you can try to find the right place in BE validation and remove the regex part from error message.

**Comment by kylecarbs** [comment]
Seems like someone fixed this? That text doesn't exist in the codebase anymore.
