### ISSUE TITLE
Add Agent API v2 Support to Coderd

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#10530]
Agents will communicate with Coderd via a new [dRPC based API](https://github.com/coder/coder/blob/main/agent/proto/agent.proto).  This adds support for the new API to Coderd including tests, but does not remove the old protocol or alter the Agent to start using it.

**Comment by spikecurtis** [comment]
@deansheather I don't think we ever finished changing the old API calls to use the new code paths.

At this point, I think we should have a serious discussion about whether to fix them up, or drop back compatibility in the next release.  Any agents from 2.8 or earlier would have to get a workspace rebuild.  That'll be 3 releases if dropping back compatibility ships in 2.12

cc @bpmct @sreya

**Comment by sreya** [comment]
Whoever ends up removing the old v1 routes can refer to this [document](https://www.notion.so/coderhq/Deprecated-Agent-v1-routes-fab264d2f2fe4470b2fdb86dae122773) for what to delete.
