### ISSUE TITLE
Navigation buttons on Users page in UI have some funky enabled/disabled issues

### ISSUE THREAD

**Issue by vkbo** [coder/coder#10549]
The page navigation buttons on the Users page have some funky issues with when they're enabled/disabled. Forward is disabled on page 1 of 2, and backward isn't. On page 2 of 2, forward is enabled again and leads to a non-existing page 3 with an error message. On page 1, backwards leads to an identical page 0.

Coder version 2.3.3

![image](https://github.com/coder/coder/assets/1619840/d1d382db-45db-464f-b55c-c3df54956466)

![image](https://github.com/coder/coder/assets/1619840/ad9a2cd6-82c9-48ad-8a8c-2f3ca1ffa059)

**Comment by matifali** [comment]
Related to #10452.

**Comment by vkbo** [comment]
Thanks! Navigation by number buttons still works, so it's not a major problem for us at least. 😃

**Comment by Parkreiner** [comment]
Marking this as closed. There are still a couple of pagination-related issues I'd like to get to, but I went ahead and documented them in new issues. Aiming to start on these problems next sprint.
