### ISSUE TITLE
removing group access to a template prevents access to existing workspaces

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10568]
this was reported by a customer and i've reproduced on 2.3.3. it's unclear to me whether or not this is expected functionality.

from the customer:

> Once I hide the template (remove the group from template permissions), the workspace is also gone from user's UI, and they can't connect to it either. What we expect to happen is: users cannot see/create new workspaces on the old template, BUT existing workspaces can still function as normal (i.e start/stop), and users can still connect to it.

**Comment by ammario** [comment]
I believe @sreya worked on this behavior and that it was an intentional security decision. We should prioritize https://github.com/coder/coder/issues/6534 as its oft requested and straight-forward to implement.

**Comment by sreya** [comment]
Yeah I don't think it warrants a full RFC but I'll put together an issue that describes the behavior and implementation of template deprecation.

**Comment by ammario** [comment]
Closing this.

You can follow the PR that adds deprecation here: https://github.com/coder/coder/pull/10745.
