### ISSUE TITLE
Unable to access "Build workspace" button when number of ephemeral resources requires "scrolling"

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10577]
I'm unable to access the button without resizing the browser window, scrolling does not work.

Browser: Safari

<img width="373" alt="image" src="https://github.com/coder/coder/assets/147409/e36f608f-5960-4589-bf30-d966664003a9">

In fact, this dialogue disables scrolling on the entire page while it's open.

**Comment by matifali** [comment]
Good catch. May be we should move the button to top and also add scrolling to this view. 
cc: @coder/ts

**Comment by BrunoQuaresma** [comment]
I don't think moving the button to the top solves the issue, but the scrolling definitely does.

**Comment by aslilac** [comment]
we should just make this a dialog instead of a drop down imo

**Comment by BrunoQuaresma** [comment]
Why a dialog would be better?

**Comment by Parkreiner** [comment]
I'm with Kayla. It feels to me that dropdowns are best when they're presenting a short list of links/buttons. But this dropdown can sometimes have so many parameters and config options that it turns into a form with 6+ inputs

I think my preference would be a dialog or rendering out content in the main part of the page

**Comment by BrunoQuaresma** [comment]
I see, where would add the button, I would try not adding a new one in the header because there is not too much space left there.

**Comment by aslilac** [comment]
honestly I think the down arrow button would still be a fine way to summon it 🤷‍♀️ or maybe a &hellip; because I love those

**Comment by BrunoQuaresma** [comment]
I had an idea! 😁
