### ISSUE TITLE
The Template Insights is not showing any data

### ISSUE THREAD

**Issue by NathanelLevi** [coder/coder#10575]
Hi
We have upgraded our coder to version 2.3.3 since we need the ability to use the AWS TLV region.

Since we have upgraded the version we are not able to see proper insights in the Insights panel.

You can also see it in the video below:

https://github.com/coder/coder/assets/58429485/b86d0976-69ce-44ca-836a-6f73688c3e38

I would be happy to get some assistance here :) 
And if, indeed, it's a big I would be happy that someone will take it 😊

**Comment by BrunoQuaresma** [comment]
Hey, sorry for that. If you try a different date, does it work?

**Comment by NathanelLevi** [comment]
@BrunoQuaresma 
Hi :)
Thanks for your input.
Yes, it looks okay but just for the Daily Insights and not for the weekly insights..

**Comment by matifali** [comment]
@BrunoQuaresma, I guess we should also change the default view to weekly with 12 weeks span or daily with 14 days span too

The current default of weekly 4 weeks just shows 4 data points that'd doesn't look that great.
