### ISSUE TITLE
Agent logs are sometimes empty from api/v2/workspaceagents/<agent>/logs?follow&after=0

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#10576]
<img width="1899" alt="no-build-logs" src="https://github.com/coder/coder/assets/5375600/f2e4f3bd-c292-4338-8b3f-872643befb4c">

Results in blank logs on Front End.  Rebuilding generally seems to help.

**Comment by spikecurtis** [comment]
Well, the logs aren't in the database...

**Comment by mafredri** [comment]
That's peculiar. AFAIK we only delete logs if the agent hasn't connected for >7 days. 🤔

**Comment by spikecurtis** [comment]
Yeah, my current suspicion is some agent problem where it doesn't send any...

**Comment by mafredri** [comment]
If this happens again, can you verify if there are script logs in `/tmp` and if the agent logs contain anything interesting? It feels unlikely that _all_ startup scripts would fail to send logs (each `module` usually adds its own script with log output, and each script output is handled separately).

**Comment by spikecurtis** [comment]
Oh snap!, we're deleting them.  My logs where there yesterday and I refreshed the page this morning and they're gone.

**Comment by bpmct** [comment]
We should at least add a message that logs are only being persisted for `n` days instead of it being blank. +1 for this being a (hidden) server flag

![Screenshot 2024-04-26 at 9 33 58 AM](https://github.com/coder/coder/assets/22407953/04f4df29-e9de-4aa3-8082-c4c33cac02a5)

**Comment by mafredri** [comment]
We could also just retain latest build logs indefinitely, should fully solve the issue and is a simple query change.

**Comment by bpmct** [comment]
Unsure what the overhead is for this exactly and what our recommendation would be for large deployments with large scripts, but generally open to having these persisted.

**Comment by mafredri** [comment]
@bpmct, if we always keep the log from latest build, and retain the behavior that we otherwise keep logs for up to 7 days. I don't think this changes much in terms of recommendations for customers.

Why? I believe it's fairly uncommon that workspaces are kept alive indefinitely. So once a workspace is stopped, the logs are eligible for deletion (after 7 days from start).

There's another protection in place, too, currently we cut off the logs at 1 MB written to DB, so the logs won't grow indefinitely either.

**Comment by kylecarbs** [comment]
I think we should just notify the users that logs are gone, that seems fine to me.

We could also always persist logs for the latest build, that doesn't seem too bad.

**Comment by mafredri** [comment]
> We could also always persist logs for the latest build, that doesn't seem too bad.

This seems like the simplest option to me (easy win and doesn't require notifying the user).

**Comment by johnstcn** [comment]
https://github.com/coder/coder/pull/14460 should hopefully address this.
