### ISSUE TITLE
Misplaced `0` at the bottom of user search table when no matches

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10581]
When the user search produces no results, there seems to be a misplaced `0` at the bottom of the table, as per:

<img width="838" alt="image" src="https://github.com/coder/coder/assets/147409/81c55ce0-7c98-42af-a723-156a6b95062e">

**Comment by Parkreiner** [comment]
Looks like some conditional rendering logic gone awry. I can look into this really quickly

**Comment by Parkreiner** [comment]
Only needed to change one line. Hotfix should be getting merged in the next few minutes
