### ISSUE TITLE
bug: coderd upgrade or restart can fail workspace builds

### ISSUE THREAD

**Issue by matifali** [coder/coder#10607]
## Problem

On dev.coder.com, I noticed that my scheduled workspace restart failed because of a `coderd` upgrade. 
server logs: [here](https://app.datadoghq.com/logs?query=host%3Acoder.c.coder-dogfood.internal%20service%3Acoder&cols=host%2Cservice&context_event=AYutTtxlAABnkePWRDHODAAG&event=&index=%2A&messageDisplay=inline&refresh_mode=paused&screenId=8fa-ww9-kny&screenName=devcodercom&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAYutTsrThLQDgQAAAAAAAAAYAAAAAEFZdXRUdHhsQUFCbmtlUFdSREhPREFBYwAAACQAAAAAMDE4YmFkZWUtNzJlMi00YjY0LWFlNzctMTI0NGU2M2Q2ZmUw&viz=&from_ts=1699419403498&to_ts=1699419704020&live=false)
build logs: [here](https://dev.coder.com/@matifali/coder/builds/378)

## Proposed solution

We should try to retry starting scheduled builds if they are failed at least once.

**Comment by bpmct** [comment]
We have this with "failure cleanup". Plus, running external provisioners should fix this I think
