### ISSUE TITLE
Demo mode

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10610]
## Background

Coder employees spend a lot of time giving product demos. Demos are often tailored with specific templates (e.g. Kubernetes), but they all lack one thing: active users.

For example, we have some powerful insights features such as a weekly user calculation, popular IDEs, common parameters, etc. In all of our demos, there are only 1-2 people in the DAUs graph which makes it difficult to showcase actual usage metrics. Additionally, it is difficult to showcase features like groups.

I have created a project [portable-coder](https://github.com/coder/portable-coder) to help spin up demo environments seeded with templates and users, but the activity metrics are still missing.

To attempt to tie this to a customer problem, many of our customers run staging environments which they may use for testing new releases or doing internal demos. They also use it to attempt to catch any issues in the product that may break users, templates, or workspaces in their "production" Coder environment. 

## Proposal

Some of this is intentionally vague as I haven't thought through all of the details. 

Should have:
- Historical data: A CLI command (such as `coder server --demo` or `coder scaletest demo-activity`) will populate a Coder deployment with users, groups, and even seed the database with historical "activity" that will show up in audit log, template insights, etc.
- Can work against an existing deployment with templates so it fits into existing use case demos (e.g. data science vs windows desktop). 

Nice to have:
- Real time data: A CLI command can be used to simulate actual "real time activity" such as workspaces being spun up and people running builds. Unlike our normal scaletest, this should use random parameters, random intervals, and random load in workspaces. This could be used to generate "chaos" or just simulate an actual deployment to identify what a realistic monitoring scenario would be. 
- A way to clean up all junk demo data and users independently from actual users

**Comment by matifali** [comment]
The demand is genuine but I think it should not be part of coder. May be a separate utility that can inject some fake data.

**Comment by kylecarbs** [comment]
@matifali it can just be a hidden subcommand that connects to the PostgreSQL database. No need for it to be anything crazy IMO.
