### ISSUE TITLE
Upgrading via latest Helm chart breaks permissions for configmaps causing workspace builds to fail

### ISSUE THREAD

**Issue by evan-ravenelle** [coder/coder#10611]
After upgrading via Helm chart, the role permissions have changed and workspace provisioning can no longer access configmaps in the `coder` namespace.

The error:
```
...
kubernetes_deployment.main[0]: Plan to update
Plan: 0 to add, 1 to change, 0 to destroy.
Error: configmaps "coder-workspace-evan-demo-workspace-1-token" is forbidden: User "system:serviceaccount:coder:coder" cannot get resource "configmaps" in API group "" in the namespace "coder"
on main.tf line 440, in resource "kubernetes_config_map" "coder_agent_token":
  440: resource "kubernetes_config_map" "coder_agent_token" {
```

After the Helm upgrade, the role `coder-workspace-perms`  is missing permissions for `configmaps`:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{"meta.helm.sh/release-name":"coder","meta.helm.sh/release-namespace":"coder"},"creationTimestamp":"2023-10-25T02$
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
  creationTimestamp: "2023-10-25T02:11:31Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: coder-workspace-perms
  namespace: coder
  resourceVersion: "202818590"
  uid: ed16fbd8-468b-41f7-8f6d-9c5492d7eca2
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
 ```

Adding permissions for `configmaps` resource type to the role resolves the issue.

**Comment by ericpaulsen** [comment]
hi @evan-ravenelle - thank you for submitting this issue.

was the `configmaps` permission manually added to the `coder-workspace-perms` role post-deployment of Coder? if so, a Coder upgrade will overwrite the modified role with what is defined in the Helm chart (as you note above).

[there is an open PR](https://github.com/coder/coder/pull/10590) for supporting custom resources and permissions in the `rbac.yaml` of the Helm chart. once merged, you will be able to add the `configmaps` permission and have it persisted through upgrades.

i will close this issue out in favor of that PR.

**Comment by evan-ravenelle** [comment]
> was the configmaps permission manually added to the coder-workspace-perms role post-deployment of Coder? if so, a Coder upgrade will overwrite the modified role with what is defined in the Helm chart (as you note above).

Ah, that's right. I assumed it was managed by the Helm chart, but the configmap is something we added to the namespace post-install.  I'll keep that in mind for next upgrade if the PR you referenced hasn't merged by then.
