### ISSUE TITLE
feat(api): add workspace scheduling data to API response

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#10621]
Ref: https://github.com/coder/coder/pull/10596#discussion_r1389371591

> Should we include the datapoints "calculated" here in the API response instead (obviously not the formatting, but timestamps, etc). I'm thinking it'd be better if our CLI was "dumber", and it might help other API consumers too.
>
> ```
> GET /workspace/uuid
> {
>   ...,
>   "schedule": {
>     "starts_next": time,
>     "stops_next": time,
> 	...
>   },
>   ...
> }
> ```
> 
> Maybe more fields if it makes sense. Basically I'm thinking if we can avoid the need to call cron.Weekly, etc since a client who wants to know this information will need to be able to parse cron tabs (+ any other business logic that may be releavant).

**Comment by bpmct** [comment]
Closing this as we now have a dedicated effort around improving the API here. Assuming this is outdated. Feel free to reopen if I'm mistaken
