### ISSUE TITLE
`coder port-forward` hangs upon workspace restart, `ssh -L` exits cleanly

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10626]
a customer noted this behavior and I've reproduced on our latest version, `2.3.3`. with an active port forwarding session open, restarting the workspace will has two different effects:

1. `ssh -L 8000:localhost:8000` command exits cleanly
2. `coder port-forward <workspace> --tcp 8000:8000` to continue hanging in the terminal (browser tab will also hang)

**Comment by mafredri** [comment]
This also applies to workspace deletion, even as a workspace is deleted the `port-forward` command stays running.
