### ISSUE TITLE
allow auditors to query `insights/user-latency`

### ISSUE THREAD

**Issue by yi-lu** [coder/coder#10627]
Getting `{"message":"Resource not found or you do not have access to this resource"}` when querying `insights/user-latency` with an Auditor role. Could we consider allow Auditor role for this endpoint please

**Comment by mtojek** [comment]
Thanks for opening the issue!

@johnstcn Is it compliant with other RBAC policies for templates? AFAIR this is restricted now to the template author role. But if we introduce this request, it will allow an auditor to see all templates, their parameters, etc.

cc @bpmct

**Comment by johnstcn** [comment]
@mtojek Auditor can already read all templates

https://github.com/coder/coder/blob/main/coderd/rbac/roles.go#L162-L180

The problem as I see it is that you need permission to update templates to be able to call `GetUserLatencyInsights`

See: https://github.com/coder/coder/blob/main/coderd/database/dbauthz/dbauthz.go#L1555-L1557

We should probably introduce a psuedo-resource for this.

**Comment by mtojek** [comment]
> The problem as I see it is that you need permission to update templates to be able to call GetUserLatencyInsights

Yes, this is how we modelled the "Template author" level ~ somebody who can update the template.
