### ISSUE TITLE
bug: Insights page Active Users, App & IDE Usage and Parameters use in Template UI spins

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10622]
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

<img width="1043" alt="image" src="https://github.com/coder/coder/assets/2022166/2f93ee4c-8822-40b5-b98d-f94508cbcf0a">

After looking at Chrome Inspect, I see this. Not sure if related.

<img width="1043" alt="image" src="https://github.com/coder/coder/assets/2022166/c8dbf4e8-2439-4045-9f28-1a8366266126">

**Comment by matifali** [comment]
@sharkymark I believe this has been recently fixed in #10595 and is a duplicate of #10575
