### ISSUE TITLE
When a coder_app crashes, what should the ideal UX be?

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10625]
## Problem statement

Imagine this scenario, a developer is running a build that occupies a lot of resources within their workspace. Suddenly, code-server is disconnected and they see this error:

![image](https://github.com/coder/coder/assets/22407953/78c474ba-421b-40c9-b379-10a2b61eeb66)

The developer's first instinct is often that this is a Coder error and report it to the Coder operator or create a GitHub issue. 

## Suggestions

- Explain that there is no app running on port 13337 on the workspace and the app may have crashed
- Add CTA to restart workspace

**Comment by BrunoQuaresma** [comment]
Why a CTA to restart workspace? 🤔

**Comment by kylecarbs** [comment]
We just added the HTTP(s) switcher thing, so closing this out!
