### ISSUE TITLE
bug: After correcting a duplicate workspace name, the validation errors remain

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10637]
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

Coder correctly checks if a duplicate workspace name is chosen at workspace creation.

However, if I change the name, the red errors still appear, but if I press create, the workspace creates fine.

![image](https://github.com/coder/coder/assets/2022166/5a3f6117-a83c-4c5b-ad93-5c5e2dabc0a3)

**Comment by matifali** [comment]
This is because we do not recheck the field before we press the create button. @BrunoQuaresma, please correct me if I am wrong.

**Comment by BrunoQuaresma** [comment]
@matifali you are 100% right
