### ISSUE TITLE
bug: existing workspace shows old `Autostop` value after template's `Default autostop` changed

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10636]
Version: [`v2.3.3+e491217`](https://github.com/coder/coder/commit/e491217a12abd3a00f5ed247f23f104732883c90)

I have a workspace where `Autostop` is set in the template to 1 hour and the template does not let users change it.

As the Coder Operator, and `owner` role, I change the template's `Default autostop` from 1 to 4 hours.

![image](https://github.com/coder/coder/assets/2022166/3ac1a9e0-19f7-4512-a9ca-6643bb6815f2)

I rebuild the workspace but it still shows `1 hour` for `Autostop`.

![image](https://github.com/coder/coder/assets/2022166/0ff0b1c8-8c34-4a17-a815-d737e4f8cd6d)

I am not sure if that is a UI thing, and the `4 hours` will be honored or if `1 hour` is not changed.

**Comment by stirby** [comment]
Fixed by https://github.com/coder/coder/pull/12910.
