### ISSUE TITLE
Allow creating new templates from registry templates

### ISSUE THREAD

**Issue by matifali** [coder/coder#10641]
## Context
This will allow the use of the templates on regsitry.coder.com to create a new template from within the Coder dashboard.

## Prerequisite(s)

- [x] #10639

## Design

An initial mockup by @bpmct is available in the RF document on Notion.
![template builder drawio](https://github.com/coder/coder/assets/10648092/cbed88bd-4555-4a9d-878d-bfff668e68f8)

**Comment by stirby** [comment]
We're going to have to revisit this integration with air-gapped customers in mind.
