### ISSUE TITLE
Backstage Integration

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10656]
## Background

[Backstage](https://backstage.io/) is an OSS software catalog and developer platform that allows developers to discover services (e.g. "ticketing frontend"), see API docs, manage CI pipelines, and much more. It is designed to be extremely customizable per-organization.

At a very basic level, think of it as a "hydrated" view of a git repo that shows all of the pipelines, team members, and dependencies that it needs to run across environments.

Users can also create new services from the catalog, which essentially forks an example service. Backstage will often work with CI/CD to deploy the service to several environments (test, staging, prod). It is a self-serve developer portal ran by platform engineers.

We have some Coder users who have already built an integration with Coder on top of backstage. Essentially, a developer can go to a service, see whether it is compatible with Coder via metadata in the `catalog-info.yaml` in the repo, and then "Open in Coder" to work on the project in a CDE versus cloning and working on it manually.

> **Note**
> Coder folks: You can see my video of Backstage [here](https://codercom.slack.com/archives/CJURPL8DN/p1674852205958659)

## Proposal

> **Note**
> This is a draft, we may expand this as we get more familiar with backstage.

We make an official Backstage plugin that allows users to open a catalog item (e.g. "ticketing frontend") directly in Coder. 

## Must have have

- Via the catalog-info.yaml a user can put whether it is Coder compatible + template + params which creates an Open in Coder in backstage UI

## Should have

- When a new catalog item is created, Backstage magically provisions a Coder workspace on behalf of the "owner." Other users can create/view their workspaces for a catalog in the backstage UI.

## Nice to have
- Full workspace management in Backstage

**Comment by stirby** [comment]
The Coder Backstage Plugin is now live! Check it out here:

https://coder.com/solutions/backstage 

Or in our backstage-plugins repository:

https://github.com/coder/backstage-plugins
