### ISSUE TITLE
template editor: make file explorer and build logs side bars collapsible

### ISSUE THREAD

**Issue by matifali** [coder/coder#10651]
## Context
The current design doesn't automatically hide the build logs sidebar, and that consumes a lot of real state, making the code section very small (depending on your screen resolution) 

We could move build logs to the bottom and make them collapsible. (similar to how the terminal is displayed in most IDEs, e.g., VSCode, JetBrains, etc. )

This could also allow us to [show suggested modules](https://github.com/coder/coder/issues/10642) on the right side

## Prerequisite

- None

**Comment by BrunoQuaresma** [comment]
Closing this as design task. Opened a new one for implementation: https://github.com/coder/coder/issues/10990
