### ISSUE TITLE
Some type of "cache server" / "cache volume" to store shared assets

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10652]
> [!Note]
> This issue needs an RFC/design.

## Background

Every time a workspace starts, Coder will `curl` the agent from the server. Many modules also `curl` tools from the public internet, such as the JFrog CLI and code-server.

This is slow, redundant, uses network bandwidth, and requires workarounds for network-gapped or restricted Coder deployments.

## Proposal

Within a Kubernetes cluster, or even for VMS, mount a volume to workspaces that have these binaries so workspaces can call them directly without any downloading.

Thanks @hh for this idea.

**Comment by kylecarbs** [comment]
Users could pretty easily mount our `coder` Docker image as a sidecar and copy/mount the binary in. For that reason, I suggest we close this out for now.
