### ISSUE TITLE
feat: query workspaces by parameter value

### ISSUE THREAD

**Issue by stirby** [coder/coder#10661]
## Problem statement
Users should be able to query workspaces in a deployment by the set value of a `coder_parameter`. For example, if I wanted to list all workspaces in my organization that use a specific AWS region.

## Implementation details 
This could be implemented as a new query option for the [list workspaces](https://coder.com/docs/v2/latest/api/workspaces#list-workspaces) API endpoint. 

If we wanted to enable multiple parameter querying:
```json
"q": { "parameters" : [
    "param_name": "target_value",
    ...
  ]
}
``` 

## Impact Notes
Customer requested feature. This can already be done by querying the resources provisioned by workspaces in some cases, but it's messy. This would be valuable for checking deprecated images, keys, and other configuration.

**Comment by bpmct** [comment]
I like this idea, ideally you could also query this in the UI too using our search for workspaces. I always thought it would be cool if some parameter values could show up in the table too, but not exactly sure how that would work since all templates have different parametrs

**Comment by bpmct** [comment]
Nice! This would help a lot for #10656 as then Backstage can determine which workspaces use which repos :)

**Comment by sreya** [comment]
We should support both `name`, `value` for parameters so you can query for certain values of parameters

**Comment by Emyrk** [comment]
I am thinking `has_param:<param_name>` and `param:<name>=<value>`. Tbd on sql query

**Comment by sreya** [comment]
What about just `param: <name>[=<value>]`?
