### ISSUE TITLE
visiting our dogfood deployment led to a crash

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10660]
I typed dev.coder.com and saw this. I cannot consistently reproduce

https://files.slack.com/files-pri/T1ZPT2FL0-F0653QB0EQ7/screenshot_2023-11-13_at_2.03.49___pm.png

**Comment by mtojek** [comment]
I was not able to reproduce, but I'm wondering how hard would it be to use decrypted asset files, so we can quickly narrow down such issues, @BrunoQuaresma?

**Comment by mtojek** [comment]
Yeah, technically speaking it is minification. Do you know if there are any recommended approaches to catch the full error trace in such situations?

**Comment by BrunoQuaresma** [comment]
Having source maps is one of them but usually, you are only able to use them to "decrypt" the stack trace when using the developer tab but I can take a look if there is a way to do that on the UI. 

I know some track systems like Sentry already make that but I didn't have time to set it up yet.

**Comment by mtojek** [comment]
Sentry might be an overkill, but it would be worth exploring lighter alternatives.

**Comment by matifali** [comment]
I see this constantly after I reduced the number of replicas of my deployment. A redeployment is not helping.

**Comment by stirby** [comment]
Stale.
