### ISSUE TITLE
bug: "user" must be an existing uuid or username

### ISSUE THREAD

**Issue by mtojek** [coder/coder#10675]
I'm not sure if this is intended behavior, but most likely we should adjust the site routing.

<img width="739" alt="Screenshot 2023-11-14 at 14 40 30" src="https://github.com/coder/coder/assets/14044910/4ce202ad-ed76-4e0c-ba6d-f7aa3727991e">

```
"user" must be an existing uuid or username.
queried user="deployment"
```

**Comment by MrPeacockNLB** [comment]
I had yesterday a similar issue. We were in transitioning to a new domain and we had forgotten to fix the fqdn in GitHub OAuth2 App and new external auth. Instead of you are now authenticated we see this queried user="gitauth" message.

**Comment by BrunoQuaresma** [comment]
I'm not sure what is the desired behavior here 🤔

**Comment by BrunoQuaresma** [comment]
cc.: @mtojek we may can close this one?

**Comment by mtojek** [comment]
Let's reopen it if somebody can navigate to the broken URL.
