### ISSUE TITLE
add health check for out-of-date provisioner daemon

### ISSUE THREAD

**Issue by mtojek** [coder/coder#10676]
Extracted from https://github.com/coder/coder/issues/9558

if provisioner daemons are out of date with the server version, unexpected behavior can occur. the health check endpoint `/api/v2/debug/health` should display configured, provisioners, and their versions.

TODOs:

- [x] https://github.com/coder/coder/pull/10949 Prune inactive provisioner daemons from database.
- [x] https://github.com/coder/coder/pull/11033 Add `provisioner_daemon.version` to database.
- [x] https://github.com/coder/coder/pull/11077 Stabilize provisioner name generation (no more `gallant_galois0`).
- [x] https://github.com/coder/coder/pull/11178 Add support for upserting provisioner daemons
- [x] Populate [provisionerdaemons](https://dev.coder.com/api/v2/organizations/703f72a1-76f6-4f89-9de6-8a3989693fe5/provisionerdaemons) https://github.com/coder/coder/pull/11207
- [x] Add "heartbeat" to connected provisioner daemons https://github.com/coder/coder/pull/11207
- [x] Add `major.minor` version check of active provisioner daemons. https://github.com/coder/coder/pull/11393, https://github.com/coder/coder/pull/11490
- [x] Build the health check section for provisioner daemons. https://github.com/coder/coder/pull/11494

**Comment by johnstcn** [comment]
@mtojek Yeah I think that makes sense.

**Comment by mtojek** [comment]
@spikecurtis raised questions around the vision, so let me elaborate more on MVP referring to [healthcheck requirements](https://github.com/coder/coder/issues/10676#issuecomment-1831904794)

1. We'd like to include a basic section for provisioners in the healthcheck that signals if the provisioner didn't report status in time. The property `last_seen_at` (and the corresponding field in the database), will be refreshed every few minutes.
2. Healthcheck section will evaluate if the provisioner is up or unresponsive. Let's say it does not report its state in 15 minutes. For now, we can consider only provisioners which checked in during the last 24h. 
3. Older entries would be swiped with `DeleteOld... job`.

**Comment by spikecurtis** [comment]
> We'd like to include a basic section for provisioners in the healthcheck that signals if the provisioner didn't report status in time. The property last_seen_at (and the corresponding field in the database), will be refreshed every few minutes.

My interpretation of this is some kind of heartbeat. Is that correct?  Are we just having Coderd do the heartbeats as long as there is a connection to the provisionerd, or does it need to be originated at the Provisionerd (e.g. to detect provisioners that are deadlocked even tho the connection is up)?


> Healthcheck section will evaluate if the provisioner is up or unresponsive. Let's say it does not report its state in 15 minutes. For now, we can consider only provisioners which checked in during the last 24h.

In a deployment where external provisioner daemons are scaled up and down you'll see a bunch of provisioner daemons that haven't reported in because they were stopped in a scale-down event.  I think we need to be careful in the design to not be "alarmist" about these: just note that they were last connected within 24 hours and are now not connected. Don't call this a "warning."

**Comment by johnstcn** [comment]
> My interpretation of this is some kind of heartbeat. Is that correct? Are we just having Coderd do the heartbeats as long as there is a connection to the provisionerd, or does it need to be originated at the Provisionerd (e.g. to detect provisioners that are deadlocked even tho the connection is up)?

My original thought was to have provisionerdserver bump `last_seen_at` whenever `AcquireJob` or `AcquireJobWithCancel` is called. In the latter case, we may need to spawn a separate goroutine to bump `last_seen_at` while the in-memory channel is waiting for a job.

Having provisionerd ping a separate endpoint that bumps last_seen_at is a bit further removed than I'd like.

**Comment by spikecurtis** [comment]
> My original thought was to have provisionerdserver bump last_seen_at whenever AcquireJob or AcquireJobWithCancel is called. In the latter case, we may need to spawn a separate goroutine to bump last_seen_at while the in-memory channel is waiting for a job.

Tying the `last_seen_at` bump explicitly to jobs is going to create annoying edge cases.  What if a job takes 10 minutes to run? We should just create a goroutine that bumps it periodically as long as the provisioner is connected.

**Comment by mtojek** [comment]
I know that Cian wrote the mini-design doc (thanks!), but it would be nice to close the conversation.

>  Are we just having Coderd do the heartbeats as long as there is a connection to the provisionerd, or does it need to be originated at the Provisionerd (e.g. to detect provisioners that are deadlocked even tho the connection is up)?

I defer the final decision to the person responsible for implementation, but my recommendation is to use the best efforts. If a deadlock detection mechanism is hard to implement, I'm fine with scheduling it as a follow-up. Provisionerd heartbeat would be already a great improvement.

> because they were stopped in a scale-down event.

Do you know, @spikecurtis, if existing provisionerd could handle the scale-down signal somehow? Even responding to OS signal, and firing an HTTP request to coderd could be a nice starter. 

> What if a job takes 30 minutes to run? We should just create a goroutine that bumps it periodically as long as the provisioner is connected.

This or and artificial, hidden ALIVE packet streamed similarly to job log entries.

**Comment by johnstcn** [comment]
@stirby current status: this week I've been finishing off the final pieces of this issue. Please see issue description for task list / updates.

**Comment by johnstcn** [comment]
Closing based on completed to-do list in issue description.
