### ISSUE TITLE
Document registry integration behavior for air-gapped installations

### ISSUE THREAD

**Issue by matifali** [coder/coder#10682]
## Context

As we move to fetching and displaying templates from the registry, we should document the behavior for air-gapped/restricted installations that can not reach the registry.

## Suggestions

We have multiple options here.

1. Pinhole registry.coder.com to allow deployments to access templates and modules.
2. https://github.com/coder/registry.coder.com/issues/8
3. #10684
4. more ideas @coder/pm?

**Comment by matifali** [comment]
@bpmct I added those to #10640 and #10639

**Comment by bpmct** [comment]
Basically, there will be cases where an airgapped person simply cannot use a custom registry or pinhole and rely on the legacy method of storing providers via a filesystem mirror

**Comment by matifali** [comment]
After #11788, air-gapped installations probably do not need to use a registry at all.
