### ISSUE TITLE
feat: customize install message in cli

### ISSUE THREAD

**Issue by stirby** [coder/coder#10718]
## Overview
Currently, when a user's `coder` CLI version is behind the control plane's version, they're prompted to update [here](https://github.com/coder/coder/blob/e7fd2cb1a64040e58ed26b0e45ac258311c58b52/cli/root.go#L819). For deployments with a custom install script, this message's link pointing to [coder.com](https://coder.com/) is not useful. A customer has requested that this URL (or the entire message) be customizable so it may point to their custom install script. 

## Impact
This would complete the use case of defining a custom installation routine in any deployment.

## Implementation details
The customer simply wants the URL to direct to their control plane rather than coder.com, but it would be best if this message could be fully customizable by users.

**Comment by matifali** [comment]
I think this can be handled with #2744. A previous [attempt](https://github.com/coder/coder/pull/7659) by @sreya couldn't make it to the `main`
