### ISSUE TITLE
Realistic Scale Testing Simulation

### ISSUE THREAD

**Issue by matifali** [coder/coder#10728]
## Description

This issue outlines the requirements for a realistic scale testing simulation for an organization with **X** Daily Active Users (DAU) on Coder. The focus is on simulating start/stop/restart/create/delete actions of workspaces in a manner that closely resembles real-world usage patterns.

## Objectives

- **Replicate Real-World Usage Patterns**: Simulate user behavior that accurately reflects the activities within an organization.
- **Identify System Limits**: Understand at what user activity levels the system starts to experience performance issues.
- **Ensure Robustness**: Validate that the system can effectively handle peak and off-peak loads.
- **Suggested System Requirements**: Propose specific resource requirements for `coderd` and the database based on the simulation results.

### 1. Simulate Peak and Off-Peak Hours

- **Peak Hours** (e.g., beginning/end of the workday): Simulate 30-50% of users starting, stopping, or restarting workspaces.
- **Off-Peak Hours**: Lower this to 10-20%.

### 2. Workspace Creation and Deletion

- **Workspace Creation**: Assume 5-10% of DAU engaging in creating new workspaces. (This does depend on organization practices. Some organizations using ephemeral workspace may use one workspace per PR, etc. We should treat such use cases as unique)
- **Workspace Deletion**: Simulate 2-5% of DAU performing deletion tasks.

### 3. Account for Weekday and Weekend Variability

- **Weekdays**: Higher activity levels, especially on Mondays and mid-week.
- **Weekends**: Simulate significantly lower activity (5-15% for start/stop/restart) [For multi-replica setups, `coderd` pods can scale down on weekends]

### 4. Include Special Scenarios

- Consider higher activity scenarios like project deadlines or release days. i.e. 30-50%

### 5. Introduce Randomness

- Implement random variability in user actions to reflect unpredictable user behavior.

### 6. Gradual Scaling

- Start testing with lower percentages and gradually increase to identify performance thresholds.

### 7. Use Historical Data and Feedback

- Refine these simulations based on historical user data and feedback if available. Get real data from current customers.

>[!NOTE]
> All percentage users are assumptions and should be refined with actual data.

**Comment by bpmct** [comment]
A few suggestions:

- Enable Datadog Agent Live Processes Monitoring on our various dogfood container runtimes (e.g. Charlie)
- Look at common load patterns/load from different dog fooders (e.g. Spike, Colin, Marcin, etc)
- Create an "average Coder developer" load pattern that we can run inside workspace containers (e.g. start coding at 9am, network traffic, 1-2 builds per day `stress` or even the direct commands we run.
- Run a scaletest with these "average developer" containers that runs for 10 hours

**Comment by kylecarbs** [comment]
I'm closing this because we already do a lot of realistic testing for scale tests and this doesn't have a clear end point.
