### ISSUE TITLE
Docs edit for JetBrains Gateway, step 8 - Change "Running" to "Ready"

### ISSUE THREAD

**Issue by mreadie** [coder/coder#10723]
In step 8 of v2 docs here, change "Running" to "Ready": https://coder.com/docs/v2/latest/ides/gateway#using-coders-jetbrains-gateway-plugin
Explanation: Step 8 says to look for "Running" but in the screenshot that follows step 8 and the Gateway UI we're really looking for "Ready" (the Coder UI says "running", but we're not looking there at this step).

**Comment by matifali** [comment]
@code-asher, should we rename "Ready" to "Running"  in the JetBrains-coder plugin to match our Dashboard UI?
We can then update the screenshot.

**Comment by code-asher** [comment]
Ah yeah the discrepancy comes from the plugin using a combined workspace and agent status while the dashboard displays just the workspace status.

So the plugin will show `Running` when the workspace is running but the agent is not yet ready.  Then it will display `Ready` once both the workspace is running and the agent is ready.

We could split this combined status into separate workspace and agent status columns, then we can match the dashboard which also shows them separately.

**Comment by code-asher** [comment]
But we would still need a docs change in that case, because users still would need to look for the `Ready` status.

**Comment by kylecarbs** [comment]
Closing because stale.
