### ISSUE TITLE
feat: log connections to workspaces owned by another user

### ISSUE THREAD

**Issue by stirby** [coder/coder#10737]
## Overview

Currently, there’s no way to track users connecting to workspaces they do not own. A customer requested that this event be added to the audit log so they can review admin access to workspaces in the deployment. This would improve security and activity visibility for Coder admins. 

## Implementation

This would be a deployment-wide opt-in feature, likely disabled by default. We only want to  show connections to workspaces the user does not own to avoid unnecessarily polluting the logs. 

## Impact

This is not blocking anything and would be a nice-to-have.

**Comment by kylecarbs** [comment]
I don't think this should be a flag. Seems like a good reasonable feature for Enterprise.
