### ISSUE TITLE
feature request: hide agent rows on workspace page

### ISSUE THREAD

**Issue by matifali** [coder/coder#10734]
## Context

Sometimes workspaces can have multiple [`coder_agent`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#display_apps) resources, but it is not required to have access to all of them using the workspace page. 

## Proposal

We should allow hiding specific agent rows from the workspace page for workspaces with multiple agents.
I know we can hide individual apps using [`dipslay_apps`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#display_apps), but an easy way to hide the agent row from the workspace page would help a lot.

```hcl
resource "coder_agent" "secondary" {
	...
	hide = true
}
```
![image](https://github.com/coder/coder/assets/10648092/c91c8268-3f51-4142-8c8f-b0424289ddf4)

## Prerequiste

- Add the `hide` attribute to the `coder_agent` resource in terraform provider

cc: @coder/pm

**Comment by bpmct** [comment]
We now render each resource as its own page!
