### ISSUE TITLE
Devcontainer VM Templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10735]
- [x] #11248 
- [x] #11246 
- [ ] Azure VMs

This is simular to architecture of other CDE platforms, a single VM which runs a container!

**Comment by matifali** [comment]
That would be useful. We may use it for implementing #8462 too.

**Comment by matifali** [comment]
I am taking this one.

**Comment by matifali** [comment]
@ggjulio not at the moment. Please see
- https://github.com/coder/envbuilder/issues/25

**Comment by matifali** [comment]
@kylecarbs can we make docker work inside devcontainer built by the `envbuilder`?
Or at least make the host docker docker available.

**Comment by ggjulio** [comment]
@matifali  thanks for the answer !

I forgot to mention this option that seem to be an hack to make everything works fine for `GH codespaces` (They use azure)
![image](https://github.com/coder/coder/assets/13398285/a73fa6b4-67d9-4751-b15c-9ec2f1713cc8)

source: https://github.com/devcontainers/features/blob/main/src/docker-in-docker/devcontainer-feature.json#L33

It may work out of the box on Azure, but could have some issues on GPC and AWS.

**Comment by ggjulio** [comment]
@matifali Is it acceptable to use the devcontainer cli instead of envbuilder for VM templates ?

I know the devcontainer cli is not perfect... and require node to be installed.
Which add up to the initial provisioning time.

But the devcontainer cli could be a first step for supporting the `dind` feature on coder platform.

**Comment by matifali** [comment]
@ggjulio, you can use whatever you wish to create a custom template. `envbuilder` is mainly focused on building an image from devcontainer spec to be run in Kubernetes workspaces.
