### ISSUE TITLE
Chore: Add missing read perm to RoleAuditor

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1074]
## Overview

This comment was in `rbac > role.go` for `RoleAuditor`:

```go
// TODO: @emyrk when audit logs are added, add back a read perm
```

This is blocked by audit log backend.

See #1066

**Comment by Emyrk** [comment]
This is not worth an issue right now. When we add audit logs, we should update the Auditor role. I think that is apart of the Audit log effort.

Closing this
