### ISSUE TITLE
bug: incorrect display name for Bitbucket cloud as an external authenticator

### ISSUE THREAD

**Issue by gpt14** [coder/coder#10741]
Hi!

This is a minor cosmetic issue with the external authentication provider functionality but could cause some confusion among users when both Bitbucket Cloud and Bitbucket server are configured.

-----

When I have configure Bitbucket cloud as an external authenticator in a template using the `coder_external_auth` data source as

```
data "coder_external_auth" "bitbucket" {
  # Matches the ID of the external auth provider in Coder.
  id = "primary-bitbucket"
}
```
it is rendered out `Authenticated with bitbucket-server` on the workspace creation page as shown below

<img width="1090" alt="image" src="https://github.com/coder/coder/assets/17963268/89151ff1-74a8-4ef7-90e6-5ed06aa1b62c">

**Comment by matifali** [comment]
As a workaround, you can set `CODER_EXTERNAL_AUTH_0_DISPLAY_NAME` to change to whatever you wish.

**Comment by kylecarbs** [comment]
We'll fix this!

**Comment by gpt14** [comment]
I apologies, i forgot about the `CODER_EXTERNAL_AUTH_0_TYPE` environment variable was still set to bitbucket-server in my coder.env file. Changing that to `bitbucket-cloud` also changed it on the UI. Thank you!

**Comment by kylecarbs** [comment]
Oh, we should still set a display name for BitBucket server @matifali

**Comment by matifali** [comment]
@kylecarbs, so we want to display "Bitbucket Server" instead of "bitbucket-server" on the button?

**Comment by BrunoQuaresma** [comment]
I don't see that in our UI, is that fixed @matifali ?

**Comment by matifali** [comment]
No it's still unresolved
