### ISSUE TITLE
template update policies: update copy to use consistent terminology

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10754]
> * The template settings copy is confusing since we inconsistently use the terms "active" "promoted" and "latest" template version to mean the same thing.
>   * The distance between this copy and the copy in the workspace setting page is a part of the confusion. Idea: keep the workspace copy the same and copy it over to the template settings with the prefix "Require".

**Comment by sreya** [comment]
fixed by https://github.com/coder/coder/pull/10662
