### ISSUE TITLE
Re-evaluate design of `--orphan` option in delete workspace dialog

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#10772]
The current design (below) displays an `--orphan` section in the workspace delete dialog that is only visible to Template Admins.

![Screenshot 2023-11-17 at 4 13 57 PM](https://github.com/coder/coder/assets/19142439/614372c1-1eae-4f37-ba6c-415906fbe45d)

We should consider whether or not the `--orphan` checkbox should be a first-class option in the delete modal considering it is both a risky and rare selection.

Another consideration is that we should add this functionality to batch delete (in case a template breaks and multiple workspaces must be orphaned).

**Comment by aslilac** [comment]
Moving discussion about batch deletion to #11162

Closing since everything else has been tidied up in various PRs
