### ISSUE TITLE
Initial migration corrupts database on new installs when Kubernetes pod times out

### ISSUE THREAD

**Issue by Milias** [coder/coder#10781]
Hello,

Firstly, thanks for your work on Coder: it is an amazing product!

I have found an issue while deploying the latest version of Coder on Kubernetes (`2.4.0`) as a completely new installation. After postgres is deployed and running, and Coder starts migrating the database schema, after ~90 seconds by default of the health check failing Kubernetes deletes the pod.

This means that [this issue](https://github.com/golang-migrate/migrate/issues/282) on `golang-migrate` is triggered. The initial migration is interrupted so when the pod restarts it immediately fails with an error similar to:

```
Dirty database version XX. Fix and force version
```

Where `XX` is a number that changes depending on how far the migration got. I suppose it depends on how fast the database processes those. Since I imagine Coder applies all migrations at initialization, over time this may become a more urgent issue.

For the moment I am manually removing the healthcheck from the deployment so that the pod is not restarted, however a more systematic solution is likely needed.

Thanks a lot for reading.

**Comment by spikecurtis** [comment]
c.f. #10966  - this should help with corruption

Doesn't look like we modified the Helm chart to run the migration in an init container to avoid the healthcheck timeout, so I'm leaving this issue open
