### ISSUE TITLE
Used by in templates list is innacurate

### ISSUE THREAD

**Issue by bpmct** [coder/coder#10820]
From dev.coder.com

https://github.com/coder/coder/assets/22407953/3da7993b-8561-41cd-92fd-cebc47f60d08

https://github.com/coder/coder/assets/22407953/3ee06059-4eb9-4727-9b58-790ff44939f5

**Comment by f0ssel** [comment]
Okay I did some digging and found some good stuff: That number is not template DAUs, it's total unique users _ever_. 

So now I have to ask, do we want to display total unique users, or DAUs here?

@bpmct @sreya

**Comment by f0ssel** [comment]
So to clarify what we want to display here, I want to think about it a little more if we go with DAUs. 

1. We can make a new query that just checks the # of workspaces using the template grouped by user id and get the count of users that way. 
2. We can re-use the insights DAUs for each template (I think). This seems like the best option to be consistent with the insights page. 
3. We can just change the label to clarify the current data. The existing data is valuable, it's the lifetime record of users not just the current active ones. We just need to present it more clearly.

**Comment by f0ssel** [comment]
I think what users expect is the count of unique users that have workspaces based off that template. Here's a sql query for example:
```
-- name: GetWorkspaceUniqueOwnerCountByTemplateIDs :many
SELECT template_id, COUNT(DISTINCT owner_id) AS unique_owners_sum
FROM workspaces
WHERE template_id = ANY(@template_ids)
GROUP BY template_id;
```
So if there's 10 workspaces based on that template across 3 users the number will be 3. If all of the workspaces from one of those users gets deleted, the number goes down to 2.

**Comment by f0ssel** [comment]
@kylecarbs I think you may be able to weigh in here with opinions on what data we should present. Thanks

**Comment by kylecarbs** [comment]
I think we display unique users with workspaces for simplicity. I think we just have to exclude deleted in our current query, right?

**Comment by f0ssel** [comment]
Sort of, it current is based off template DAUs which is based off workspace_agent_stats. My PR for this changes it to use the workspace table and returns unique workspace owners and filters out deleted workspaces. 

We may be able to extend the existing query to filter out by deleted workspaces to get it more accurate, but there's cases where workspace_agent_stats won't be populated and you'll get inaccuracies again, like a workspace that exists but has always "failed". 

PR: https://github.com/coder/coder/pull/11044
