### ISSUE TITLE
Remove swr

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1082]
## Problem
Initially, v2 used the swr library, but then we moved away from it. However, it's still installed and we may have some code related to it. This is tech debt, and it's good to have as few dependencies as possible.

## Definition of Done
swr is uninstalled and there is no dead code related to it.

## Related

There was a related `TODO` comment in removed in #1066

**Comment by bpmct** [comment]
@presleyp @BrunoQuaresma I noticed this was in enqueue. could add a problem statement and def. of done? I'm not sure about the context here.

Would also appreciate your thoughts on the priority (I'd imagine debt-related) and estimate.
