### ISSUE TITLE
Is it expected behavior that an `Owner` role gets notified of dormant workspaces not in their name?

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10847]
Version: [`v2.4.0+d19a762`](https://github.com/coder/coder/commit/d19a762589e84afd18f2245ebc03daccb53cb13f)

I am an `Owner` role and have no dormant workspaces in my name yet the user interface notifies me I may  dormant workspaces and to take action if I want to save them.

Seems like a bug.

![image](https://github.com/coder/coder/assets/2022166/83c45004-2a6d-4c02-b274-b5aae75330bb)

**Comment by matifali** [comment]
cc: @bpmct

**Comment by sreya** [comment]
It only notifies you based on the current query. So if you're searching with `owner:me` and none of your workspaces are dormant then you shouldn't get a banner regardless of whether you're an admin or not. I just verified this is the case.
