### ISSUE TITLE
Saving tabs and terminals

### ISSUE THREAD

**Issue by syfulin** [coder/coder#10851]
Is it possible to do this so that when the same user re-logs in or opens code-server in another browser, open tabs and terminals are saved in the vs code editor?

What would work the same as in AWS Cloud 9

That is:
1. I worked. Left open tabs and terminals.
2. Logged out and closed the browser.
3. I sat down at another computer, opened the browser and logged in.
4. I observe my open tabs and terminals with running programs

Is it really possible to set up this ability to save state?

![CleanShot 2023-11-24 at 14 12 08@2x](https://github.com/coder/coder/assets/20333151/d92a4927-0281-4a99-b823-d7fd56c5aa17)

**Comment by kylecarbs** [comment]
This isn't particularly easy for us to do, so unless we get a lot of community support I'm going to say we won't do it.

Please comment if you'd like this!
