### ISSUE TITLE
Display github login configuration on the /deployment page

### ISSUE THREAD

**Issue by matifali** [coder/coder#10865]
We already show the OIDC sign-in configuration on the `/deployment/userauth` page. We also show if GitHub sign-in is configured. It would be nice to see the allowed GitHub organizations and if signups are allowed on this page.
 
![image](https://github.com/coder/coder/assets/10648092/b3f3dde5-8ac1-4b50-84cb-ba55751771c6)
We are currently showing no options to configure, which is wrong as we do have the configuration for GitHub.

```env
CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS=true.                           # show this
CODER_OAUTH2_GITHUB_ALLOWED_ORGS="org1,org2"                      # show this
CODER_OAUTH2_GITHUB_CLIENT_ID="XXXXXXXXX"                         # show this
CODER_OAUTH2_GITHUB_CLIENT_SECRET="YYYYYYYYYYYYYYYYYYYYYYYYYYYYY" # do not show
```

**Comment by Teja-11** [comment]
Can i work on this?

**Comment by matifali** [comment]
@Teja-11 yes sure. You are welcome to contribute.

**Comment by mtojek** [comment]
hey @BrunoQuaresma Is it site-only issue or do you need a backend hand here?
