### ISSUE TITLE
getting license error trying to create a template with `max-ttl` but I have signed up for the 30-day trial

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#10872]
Version: [`v2.4.0+d19a762`](https://github.com/coder/coder/commit/d19a762589e84afd18f2245ebc03daccb53cb13f)

I signed up for the in-product 30-day trial but none of enterprise features are available.

I noticed this because:
1. The `Audit` tab is not available
2. I tried adding a new template and it failed saying `max-ttl` is not allowed without a license

Message received:
`your license is not entitled to use advanced template scheduling, so you cannot set --failure-ttl, --inactivity-ttl, or --max-ttl`

Notice the license in the Deployment UI

![image](https://github.com/coder/coder/assets/2022166/b1f16c1c-55db-4912-b726-1eb5744186b5)

If I logged out and logged back in, the CLI command works.

**Comment by kylecarbs** [comment]
Closing because inactive.
