### ISSUE TITLE
Change the `coder_parameter` description causes the workspace parameter value to be reset to the default value on update

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#10886]
Coder version: 2.3.0

We've changed the description of a `coder_parameter` resource:

![image](https://github.com/coder/coder/assets/1318438/93cf091a-a86a-4187-baff-6512c7c5bbdb)

After updating a workspace to the new version of the template, the value of this parameter in the workspace, which was set to a different value than the default of 64, is reset to the default. This caused replacing of the home volume of workspaces of our users.

**Comment by Kira-Pilot** [comment]
@NiklasRosenstein Sorry this happened! Parameter names are unique identifiers, so changing the name *would* reset to the default. We suggest setting [the `display_name` value](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter#display_name) to avoid this happening in the future.

**Comment by NiklasRosenstein** [comment]
Ah, of course, I see it now. For some reason I confused the `name` with the `description` when describing this issue.

**Comment by Kira-Pilot** [comment]
@NiklasRosenstein Not at this time; however feel free to open a separate issue if this is something you'd like us to consider!
