### ISSUE TITLE
How to tell in a template if a Workspace is being updated by Coder?

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#10887]
When a running workspace is being updated, it doesn't first stop and then start the workspace. However, in our template this doesn't cause the `kubernetes_pod` to be replaced. It will then fail to connect because "Agent trying to connect from non-latest build."

![image](https://github.com/coder/coder/assets/1318438/a0aae69e-0464-4416-81cc-d77413532884)

I was looking for a "build id" attribute in the Terraform provider to use as a trigger to replace the `kubernetes_pod` resource, but couldn't find any such attribute.

**Comment by matifali** [comment]
Related to #6229

**Comment by kylecarbs** [comment]
This is more of a template issue than a Coder issue. You can use `kubernetes_deployment` with a replica size of 1 instead.
