### ISSUE TITLE
UX Improvement: Port Sharing in the UI

### ISSUE THREAD

**Issue by stirby** [coder/coder#10908]
# Problem Statement
Currently, modifying the access level of a port or coder_app requires configuration in the template using the `share` attribute in the [Coder Terraform provider](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app#optional). This implies that template admins are expected to operate port sharing at the workspace level which misaligns with the use case. 

Instead, the port sharing level should be configurable in the Coder UI by the workspace owner per port. 

## Implementation details
Here's a **rough** example of what this improved UX might look like: 

<img width="517" alt="port sharing" src="https://github.com/coder/coder/assets/58410745/c3f02a85-1609-4688-ad63-3d07e159655f">

The user would be able to set one of the visibility options [`owner` (default), `authenticated`, `public`] with this button, ideally through a dropdown. 

To accommodate security expectations, the maximum port `share` level should be controlled by template admins at the deployment level. However, it could make sense to configure this per template rather than per deployment, depending on implementation difficulty and security opinions. 

## Impact
The individual that would want to forward a port should not have to edit their template to modify port visibility. This is a frequently requested use case by the community and has been recently discussed in detail with an enterprise customer. 

### Related issues 
- #10393 
- #4615 

### CLI (**Update**)
To fully utilize this feature, the customer asked that it also be available in the CLI. I am under the impression it would fall under `coder port-forward` but will defer to engineering.

**Comment by ammario** [comment]
For the record we should call these "shared ports" and not "Dev URLs" (v1). The "Dev URL" language makes it seem like the feature is doing more than it is.

**Comment by deansheather** [comment]
I removed the networking label as this is just related to the database and authz. Networking label is just for tailnet/networking related bugs/features

**Comment by deansheather** [comment]
This should be implemented as a table with `workspace_id, agent_name, port, access_level`, and then the workspaceapps ticket issuance code can be upgraded to check this table on port requests.

**Comment by stirby** [comment]
Added note on CLI implementation requested by customer.

**Comment by BrunoQuaresma** [comment]
Do we still want to have the "automatic" port detection or only ports shared via config + manually added by the user?

**Comment by stirby** [comment]
Closing in favor of https://github.com/coder/coder/issues/11486.
