### ISSUE TITLE
☂️ Naming/Renaming

### ISSUE THREAD

**Issue by matifali** [coder/coder#10919]
We have multiple issues regarding the naming/renaming of `workspaces`, `templates`, `template versions`, `users`, and `groups.` I am creating this issue to consolidate them to have a uniform naming convention across all items.

- [ ] #8145 
- [x] #8900 
- [x] #5839 
- [ ] #10244 
- [x] #10922 
- others I have missed.

cc: @coder/eng @coder/pms

**Comment by stirby** [comment]
Just requested: https://github.com/coder/coder/issues/10922

**Comment by kylecarbs** [comment]
We stopped doing these umbrella issues so I'm closing.
