### ISSUE TITLE
Workspace renames can break builds

### ISSUE THREAD

**Issue by stirby** [coder/coder#10922]
## Problem Statement
A customer has templates whose functionality depends on the workspace never being renamed. Currently, the only way this can be prevented is by warning users not to change the names manually.

## Implementation
The customer requested this be a deployment-wide flag to reduce repetition. Unfortunately, this would likely limit the usability and doesn't fall under the types of limitations we allow for global parameters. A compromise might be: allow it as a per-template option under Template Settings > Operations under the name "Prevent workspace renaming" and disable it by default. 

## Impact
This would allow template admins to build stable systems around workspace names.

**Comment by matifali** [comment]
I suggest we make these immutable and remove the ability to rename workspaces altogether. I don't see any significant benefit in allowing renaming after creation. They can still delete and recreate a new one with the new name. 

Also as an additional benefit it would allow template admins to use workspace name to name persistent resources.

**Comment by mafredri** [comment]
I’m worried this feature will be missed once it’s gone. Renaming something to represent it’s utility is a very human thing to do and annoying when that can’t be done without data loss.

I would like to propose an alternative solution. How about we introduce workspace alias(es) instead? Under the hood, the workspace would retain its original name, however, it would be displayed and accessed using its alias. This way the workspace would reserve two names and we avoid the underlying issue.

**Comment by matifali** [comment]
@mafredri and when we delete it we release both the name and the alias? It means we need to store an extra column for the alias everytime a user renames.

**Comment by mafredri** [comment]
> @mafredri and when we delete it we release both the name and the alias? It means we need to store an extra column for the alias everytime a user renames.

Yes for the release, however, we only need one extra column for the alias, multiple renames can just change it directly so there's always at most 2 reserved names (original and alias).

**Comment by Emyrk** [comment]
We have the concept of "Display name" in multiple other resources. Maybe if we call it that vs an Alias, it can easily imply there is only 1 alias instance.

**Comment by ammario** [comment]
Can we solve this problem by making it more clear to the user which resources will be re-created upon rename? The same confirmation flow could be used to make _all_ workspace update operations more safe?

**Comment by mafredri** [comment]
@ammario I like the idea of being able to make updates safer, however, I worry about bleeding the abstraction to the user wrt purpose of terraform resources. Generalizing a bit, only a template author/admin cares about terraform resources, users simply want click & p[lr]ay.

Another issue is how we'd implement this detection. As far as I can recall, the previous times this has come up there were no great solutions. I can think of two options, though, 1) parse the terraform and figure out where the input data is used as part of names/IDs and 2) run `terraform plan` using the new inputs and see what would change. In the former case, we don't know if a parameter will significantly affect a resource and in the latter case, we don't necessarily know the purpose of a resource, so essentially we'd be relying on user intuition (not great IMO).

Granted, having an immutable creation-name and a mutable display name will bring its own set of problems, like how do we represent this intuitively in TF. Let's say a template admin wants to set an env `MY_ENV=workspace-name`, they'd need to understand the concept and use the mutable one. Likewise when defining the workspace resource, they need to not accidentally use the mutable name. Alternatively, the mutable name is not available in the workspace, which might be OK too.

**Comment by stirby** [comment]
After a discussion with @ammario and the requester, a new `stable_name` attribute in the `coder_workspace` data source in our Terraform provider would solve this. When users want to automate around a workspace name they will use that field.

**Comment by matifali** [comment]
We use a similar flow for [`coder_paramter`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter) but use `name` and `display_name` instead where `name` can be used for automation while `display_name` can be freely changed.

**Comment by f0ssel** [comment]
My 2 cents: Workspaces are not like GCP projects, workspaces are much easier to throw away and make new ones (or at least they should be). Reading though the suggested ideas here I don't seem convinced that adding a `display_name` actually justifies the complexity being discussed. 

My suggestion would be to disable it entirely to keep the changes simple and make builds predictable. I can't really imagine a customer coming to us saying that not allowing renames breaks their workflows, but allowing them clearly does.

**Comment by f0ssel** [comment]
I don't super think the special flag is needed, but I don't know all the ways people work. If we really think there are emergency cases to rename a workspace I'm OK with the flag, but we should probably circle back and manually remove it instead of having it magically stop working at some date in the future.

**Comment by ammario** [comment]
We usually forget to remove our deprecated and "temporary" options, which is why I'd like to experiment with their death predetermined on insertion.
