### ISSUE TITLE
Improve coder cli re-login experience when api token is expired

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#10925]
We have a user that received this when trying to ssh to their workspace:

```
check entitlement warnings error: get user me: GET https://coder/api/v2/users/me: unexpected status code 401: You are signed out or your session has expired. Please sign in again to continue.: Try logging in using 'coder login <url>'.
        Error: API key expired at "2023-11-24 20:13:30.881157 +0000 UTC".
You are signed out or your session has expired. Please sign in again to continue.
Try logging in using 'coder login <url>'.
kex_exchange_identification: Connection closed by remote host
```

Since they see a URL from the unsuccessful API call, it's tempting to click that but it won't solve their problem. For re-logging in, instead of `<url>` in the message, would it be possible to display the URL there so it's a simple copy and paste operation?

Could the URL be optional so that `coder login` will just re-login to the same server?

**Comment by matifali** [comment]
> Could the URL be optional so that coder login will just re-login to the same server?

This has been previously requested in a discord [discussion](https://discord.com/channels/747933592273027093/991429648200245358/1160972057874546708)

**Comment by mafredri** [comment]
For illustrative purposes, I'm adding a screenshot to show how jarring this issue really is:

<img width="1932" alt="image" src="https://github.com/coder/coder/assets/147409/5cfb7aa9-ff1f-4784-af41-f08008b2df60">

I would like to see the following changes:

1. Entitlement error never shows up unless it's the primary error
2. Same for `GET:https://big.cdr.dev/api/v2/workspaces?q=owner%3Ame` & co.
3. Expiry date doesn't seem all that important? We could skip it (maybe show in verbose mode)
4. Allow `coder login` to log into existing deployment, but update output to show "Authenticating with https://dev.coder.com..." or something similar.

Right now, we seem to be lacking a lot in CLI validation. This kind of error should _definitely not_ be shown when typing `coder login`:

<img width="1088" alt="image" src="https://github.com/coder/coder/assets/147409/add05e92-2e36-4f4a-9ebf-0d9e1a80f06d">
