### ISSUE TITLE
creating group with same name as existing group does not return error

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10928]
similar behavior to this issue: https://github.com/coder/coder/issues/10268

when clicking `Submit`, nothing occurs. the correct `409` is returned in the browser console, however, saying `Group with name "DataScience" already exists.`

**Comment by aslilac** [comment]
*sigh*, another bug that could've been caught by storybook. related to #11420, we probably want to make sure that error states are tested in storybook as much as possible.
