### ISSUE TITLE
disabling auto-start & stop fields at the template level does not update workspace fields

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10930]
#10022 disables the input fields, but does not turn off the auto-start or auto-stop once it is disabled at the template level. here is an example, where i have a workspace with both auto-start and stop enabled, but disabled at the template level:

<img width="1041" alt="Screenshot 2023-11-28 at 16 04 14" src="https://github.com/coder/coder/assets/9683576/cba89f0e-408b-4834-b1d9-8c4b69e16543">

**Comment by BrunoQuaresma** [comment]
I think this is not a FE issue. Ideally, when the template changes its settings, the BE should update the related workspaces to match the new config.

**Comment by BrunoQuaresma** [comment]
Since it is related to scheduling, I think @sreya is a better person to handle it 🙏

**Comment by Kira-Pilot** [comment]
Similar to  #10636

**Comment by ericpaulsen** [comment]
@BrunoQuaresma I disagree, the front-end issue is that the input fields are still selectable and editable, despite the autostart/stop & stop being disabled at the template level.

the expected behavior should be: if autostart/stop is disabled at the template level, then the `Enable Autostart/stop` toggles are switched off, to prevent field editing.

**Comment by bpmct** [comment]
We'll be able to get to this first thing in January!

**Comment by bpmct** [comment]
The way this is described gives the admin the impression that it limits the days all workspaces can be autostarted. The desired behavior from our customers is that it does this as well

<img width="1122" alt="Screenshot 2023-12-20 at 9 39 39 AM" src="https://github.com/coder/coder/assets/22407953/39377cd3-6132-4856-8a86-40b8362d6297">
