### ISSUE TITLE
autostart weekends are disabled at template level, but still selectable at workspace level

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#10931]
related #10930 

at the template level, i disabled workspace auto-start on the weekends here:

<img width="603" alt="Screenshot 2023-11-28 at 16 07 01" src="https://github.com/coder/coder/assets/9683576/74f2a295-123f-4f19-ac01-381099a3e537">

but at the workspace level, i am still able to select weekends for auto-start:

<img width="1042" alt="Screenshot 2023-11-28 at 16 10 52" src="https://github.com/coder/coder/assets/9683576/c7923070-92ac-411c-938b-5bfce1ccc440">

clicking the `Submit` button does not display any message, but I do receive a `204` API response in the browser console. in addition, the changes to the autostart selections are not persisted when navigating to another template tab, such as `Parameters`, even after clicking `Submit`.

**Comment by Kira-Pilot** [comment]
Similar to https://github.com/coder/coder/issues/10636

**Comment by bpmct** [comment]
We'll be able to get to this first thing in January!
