### ISSUE TITLE
macOS: "routerIP/FetchRIB: sysctl: cannot allocate memory"

### ISSUE THREAD

**Issue by mafredri** [coder/coder#10953]
Saw this error pop up in my SSH session today whilst I was doing some port-forwarding (`ssh coder.scaletest -L 6060:127.0.0.1:6060`).

```
2023/11/30 16:15:56 routerIP/FetchRIB: sysctl: cannot allocate memory
```

It popped up ~35 minutes into the SSH session.

Related tailscale issue: https://github.com/tailscale/tailscale/issues/3299

**Comment by kylecarbs** [comment]
I think this might go away because we disabled stdlib logging in ssh.
