### ISSUE TITLE
GitHub Login: If a user changes their primary email on GitHub Coder creates a new account for them instead of updating the email on existing account

### ISSUE THREAD

**Issue by matifali** [coder/coder#10972]
I updated my primary email in GitHub, and after that, when I tried to log in to Coder using GitHub, Coder created a new username for me with username `old_user_name_SOME_RANDOM_STRING` with the new email address. I got locked out of my old account.
Related #10726, #4618

![image](https://github.com/coder/coder/assets/10648092/94c6ac14-bdef-47a5-ad01-745e36e6586c)

See how a new user account is created for me after changing the email. Both are GitHub accounts. 

### Steps to reproduce:

1. Go to https://github.com/settings/emails and chnage your primary email
2. Logout and login to Coder

**Comment by kylecarbs** [comment]
@sreya don't we link based on ID?

**Comment by sreya** [comment]
Yeah we should be.

**Comment by matifali** [comment]
We should also automatically update email and username for GitHub and OIDC accounts as requested in #10516.

**Comment by Emyrk** [comment]
We find the link by github id: https://github.com/coder/coder/blob/ff9959fe7e49ae13d7e8923a99d4fd52f28d100f/coderd/userauth.go#L1681-L1684

But then we do a check to find any user with the given email: https://github.com/coder/coder/blob/ff9959fe7e49ae13d7e8923a99d4fd52f28d100f/coderd/userauth.go#L1698-L1709

And we only check 1 email, their verified or primary: 
https://github.com/coder/coder/blob/ff9959fe7e49ae13d7e8923a99d4fd52f28d100f/coderd/userauth.go#L607-L607

**Comment by Emyrk** [comment]
I actually cannot reproduce this :thinking:

**Comment by Emyrk** [comment]
@matifali can you reproduce this? I cannot and maybe it has been fixed and we can close?

**Comment by matifali** [comment]
@Emyrk I changed my GitHub primary email to my Coder email address and I can't log in anymore as I already havy an google OIDC account. Ideal should be to merge both accounts in this case. 

![Screenshot_20240126-215839](https://github.com/coder/coder/assets/10648092/7dbc5b0e-3e87-43b0-af58-d15c20457c36)


If I change my primary email to some other email address Coder created. Anew account for me again. 

![Screenshot_20240126-220105](https://github.com/coder/coder/assets/10648092/b9beaf1e-fe0c-4f9e-ba9f-f105667b55ec)

**Comment by Emyrk** [comment]
> @Emyrk I changed my GitHub primary email to my Coder email address and I can't log in anymore as I already havy an google OIDC account. Ideal should be to merge both accounts in this case.
> 
> ![Screenshot_20240126-215839](https://private-user-images.githubusercontent.com/10648092/300085038-7dbc5b0e-3e87-43b0-af58-d15c20457c36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTY0NTksIm5iZiI6MTcwNjI5NjE1OSwicGF0aCI6Ii8xMDY0ODA5Mi8zMDAwODUwMzgtN2RiYzViMGUtM2U4Ny00M2IwLWFmNTgtZDE1YzIwNDU3YzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE5MDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMDk0MGM1ZjVjZDMyMDRlMmNjMTc0OWE0NTY2MGI2MjgwMzgxODZhNmQ0N2I0YmRhZGJkZjI3MWQxZTBiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fhDYRsL24TZ1p4Fgaw_pdtUBC-TNk9eTClaKvbt0FLE)
> 
> If I change my primary email to some other email address Coder created. Anew account for me again.
> 
> ![Screenshot_20240126-220105](https://private-user-images.githubusercontent.com/10648092/300085065-b9beaf1e-fe0c-4f9e-ba9f-f105667b55ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTY0NTksIm5iZiI6MTcwNjI5NjE1OSwicGF0aCI6Ii8xMDY0ODA5Mi8zMDAwODUwNjUtYjliZWFmMWUtZmUwYy00ZjllLWJhOWYtZjEwNTY2N2I1NWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE5MDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNzhiZDliMjE2ZmIwNDE4YWI5NDgxNGFkMWMyMDBmY2VlYzJlY2U3ODI3MzVkZmU0NDExMGMwZDQzYjg0NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCzBtcD8BTw0ZVCjwtiZH-AcRlzL7Elvu2ca6QSGd-0)

Yup this is actually intentional. Merging accounts can be done similar to how we do "Convert to OIDC" from password auth.

We **cannot automatically merge** them. We would need the user to authenticate via both oauth methods, then click merge _from both sides_ (whatever that looks like).

----

So this behavior is currently intentional.

**Comment by matifali** [comment]
@Ben, @stirby can you try to reproduce this too? I can consistently reproduce.

**Comment by f0ssel** [comment]
Attempt to reproduce

When I change my primary github email from `garrett@delfosse.dev` to `garrett@coder.com` I get the following conflict error. 
```json
{"message":"Failed to process OAuth login.","detail":"in tx: execute transaction: update user profile: pq: duplicate key value violates unique constraint \"idx_users_email\""}
```
This makes sense, since I have a gmail login with `garrett@coder.com` already and that's a separate coder account. 

When I change the primary email to `delfossegarrett@gmail.com` which should not have a conflict I am logged into my existing account (formerly `garrett@delfosse.dev`) correctly.

So I'd say I also cannot reproduce the same behavior Atif is seeing. I did not touch anything regarding my "public email" in this experiment, thought it was worth mentioning.

**Comment by stirby** [comment]
I experienced the exact same behavior as @f0ssel, unable to reproduce the other issue.

**Comment by matifali** [comment]
@Emyrk and I figured out how to reproduce this. You need to delete your account once.
