### ISSUE TITLE
Allow specifying initial state of workspaces

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1097]
(From an impromptu discussion with @kylecarbs and @coadler)

# What:
Currently, when you create a workspace, a provisioner job is automatically created that brings the workspace into the "running" state.

This should remain the default behaviour, but we should allow users to specify whether the workspace is in the "running" state or the "stopped" state.

e.g. `coder workspaces build my-workspace --state=stopped`

# Why:
A number of potential user-cases exist where you may wish to (pre-)provision the resources for a workspace without actually starting it:
- Unit/Integration/Load Testing
- Pre-warming / mass user onboarding
- ???

**Comment by ketang** [comment]
Will also want this via the web UI.
