### ISSUE TITLE
flake: updateWorkspace.spec.ts e2e test

### ISSUE THREAD

**Issue by Parkreiner** [coder/coder#10989]
[Link to job](https://github.com/coder/coder/actions/runs/7060462551/job/19220076573)
[Footage](https://github.com/coder/coder/assets/28937484/67b5f244-d98c-4f4c-bcf1-4a5903ec0921)

Error:
```txt
/home/runner/actions-runner/_work/coder/coder/site/e2e/helpers.ts:656:
   at helpers.ts:656

  654 |           "']",
  655 |       );
> 656 |       await parameterField.check();
      |                            ^
  657 |     } else if (richParameter.type === "list(string)") {
  658 |       throw new Error("not implemented yet"); // FIXME
  659 |     } else {
elementHandle.check: Element is not attached to the DOM
```
As far as I can tell, here's a basic summary of the issue:
1. The offending test is "update workspace – new, optional, immutable parameter added" from `updateWorkspace.spec`
2. We're getting an error from the call to the `fillParameters` helper function because the input field that is supposed to be getting filled out isn't being rendered to the DOM
3. The helper is called when the test case calls the `createWorkspace` and `updateWorkspace` helpers, but from the footage, it looks like the error is from the update step?

**Comment by mtojek** [comment]
Thanks for the report, Michael!

> We're getting an error from the call to the fillParameters helper function because the input field that is supposed to be getting filled out isn't being rendered to the DOM

@BrunoQuaresma Has something changed in forms rendering? Is it possible that they get detached, and re-attached?

**Comment by BrunoQuaresma** [comment]
Not that I'm aware of 🤔

**Comment by Parkreiner** [comment]
It's also possible that the correct UI wouldn't get rendered out because the backend data isn't reaching the "client"
