### ISSUE TITLE
[Implementation] Display modules and templates from registry.coder.com in the dashboard

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#10991]
Related to:
- https://github.com/coder/coder/issues/10640
- https://github.com/coder/coder/issues/10639

Design:
- https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-Product-V2?type=design&node-id=2776-578&mode=design&t=nmSEmWhW7phWT7Cb-0

**Comment by kylecarbs** [comment]
We need to discuss how we're doing this before deciding whether to implement it or not.
