### ISSUE TITLE
Template Editor: Implement the new template editor design including modules support

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#10990]
- Modules support
- Toggle sidebar

Related to:
- https://github.com/coder/coder/issues/10651
- https://github.com/coder/coder/issues/10642

Design:
https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-Product-V2?type=design&node-id=2791-578&mode=design&t=nmSEmWhW7phWT7Cb-0

**Comment by kylecarbs** [comment]
Similar to my other comment, we should decide how to integrate this before keeping this open.
