### ISSUE TITLE
GET /users/:userid/profile

### ISSUE THREAD

**Issue by deansheather** [coder/coder#1100]
## Problem

Because we have `PUT /users/:userid/profile`. These fields are available from `GET /users/:userid` today, but we don't want users to be able to read other users' private profile fields, so this will act as a public "user info" route.

## Are there any workarounds to get this functionality today?

`GET /users/:userid`

## Definition of Done

Add `GET /users/:userid/profile` that returns public user profile fields

**Comment by BrunoQuaresma** [comment]
@bpmct @deansheather what are the public user info?
