### ISSUE TITLE
feat(cli): make argument handling more intuitive to use

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#11002]
The argument handling could be better, it took me a bit to remember that arguments worked with equals and nothing really seemed to indicate so in the help.

See my terminal "transcript" below to see the experience i had.

![image](https://github.com/coder/coder/assets/57866459/38d3da49-a1c0-4b56-9107-47d0c8cb63f7)

---

`Coder v2.4.0+d19a762`

---

cc: @matifali

**Comment by kylecarbs** [comment]
I agree this is jank, but we have the umbrella issue to tackle this.
