### ISSUE TITLE
Print a CLI warning if user is already authenticated

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#11004]
Currently, the CLI lets you log in as many times as you wish even though you're already logged in.
I think the CLI shouldn't let you do that or at least tell you that you're already logged in as a "warning".

Something like, "your Coder CLI is already authenticated as phorcys @ https://coder.domain.tld".

This occurs to me whenever I go back to use coder on a machine I don't use frequently, I never know if I'm logged in or not.
I think there could also be a `coder whoami` command letting you know what user you're connected with, on what instance and how long your authentication will be valid.

I would like this because I go between my own instance and the dogfood instance, that feature would be pretty handy.

---

```
PS C:\Users\Phorcys> coder login https://coder.domain.tld
Your browser has been opened to visit:

        https://coder.domain.tld/cli-auth

> Paste your token here: [...]
> Welcome to Coder, phorcys! You're authenticated.
PS C:\Users\Phorcys> coder login https://coder.domain.tld
Your browser has been opened to visit:

        https://coder.domain.tld/cli-auth

> Paste your token here: [...]
> Welcome to Coder, phorcys! You're authenticated.
```

---

`Coder v2.4.0+d19a762`

---

cc: @matifali

**Comment by mafredri** [comment]
I'm pro-warning (You're already authenticated as foobar, are you sure you want to re-authenticate?) because there will be cases where you might want to auth as another user, or some such. Also `coder whoami` could be `coder auth status`.

**Comment by matifali** [comment]
@mafredri yes
I have seen this format with other programs.
where login is `coder auth login` and status is `coder auth status` also to get the current token `coder auth token`.

We still have to keep `coder login` for backward compatibility.

**Comment by BRAVO68WEB** [comment]
`coder whoami` added in #13814 [docs](https://coder.com/docs/cli/whoami)
Can we close this issue?

**Comment by BRAVO68WEB** [comment]
Hey, I want to work on this? Can you let me know what is to be done?

**Comment by phorcys420** [comment]
> Hey, I want to work on this? Can you let me know what is to be done?

Thanks!
All that's to be done is to add a warning when using `coder login` and a session already exists. ("You're already authenticated as foobar, are you sure you want to re-authenticate?" like @mafredri mentioned)

**Comment by BRAVO68WEB** [comment]
Ok, I will be creating a PR for this

**Comment by matifali** [comment]
There is already a `coder whoami` command as of `2.14.0`.

**Comment by phorcys420** [comment]
> There is already a `coder whoami` command as of `2.14.0`.

yes, my issue was about both this command and a warning for when you use `coder login`!
