### ISSUE TITLE
Query element "template:" cannot start or end with ':'

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11017]
The search gives of an error before I've finished typing my query. This results in a jarring experience, you're not doing anything wrong but you might stop and try to figure out why it's giving you an error. If you continue typing everything is fine.

<img width="870" alt="image" src="https://github.com/coder/coder/assets/147409/10c2516b-8d42-4586-b547-c7cdce44b76f">

This may be a WebUI or API bug, or both.

**Comment by BrunoQuaresma** [comment]
We do some deboucing, I think it is 500ms, to avoid querying when the user is typing but if you take too much time it will do the query with an invalid value. Not sure if this is something worth"fixing".

**Comment by mafredri** [comment]
@BrunoQuaresma I don't think it needs fixing on the frontend, I see it as an API bug. I can't think of a reason an empty filter wouldn't be OK. It'd just show all templates. As for worth fixing or not? I'd say yes, 100%, seeing that red text is quite jarring for a user.

**Comment by BrunoQuaresma** [comment]
Ah ok, now I can see this better by looking at it as an "empty" value for templates 👍
