### ISSUE TITLE
Web terminal fails after a short while of doing `cat /dev/zero`: WebSocket failed: socket errored

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11036]
**Update:** Based on further discoveries, the issue here seems that `coderd` web terminal sessions have gone defunct after the above error. As for what caused it? That's unknown at this time.

If I type `cat /dev/zero` in the web terminal, I observe 3 issues.

1. ~~I see no output~~ (Actually, this is normal for `cat /dev/zero`)
2. Opening a new web terminal simply freezes
3. Shortly thereafter, terminal session is closed via: `WebSocket failed: socket errored`
4. Web terminal to workspace seems permanently defunct, even after waiting a long time and ensuring processes inside the agent are terminated

<img width="900" alt="Screenshot 2023-12-05 at 15 23 02" src="https://github.com/coder/coder/assets/147409/6e6ba251-a656-46e3-8e1b-0ec98994cdcd">

This also has a pretty significant impact on `coderd` CPU usage (#11039):

<img width="1815" alt="image" src="https://github.com/coder/coder/assets/147409/064bec0b-7649-4b8d-b11e-042ea326a138">

Refs #8556

**Comment by mafredri** [comment]
Regarding 4, this was found in the coderd logs:

```json
{
  "insertId": "nrxny06r6n02jz3b",
  "jsonPayload": {
    "message": "derp: 10.10.0.209:16613: client [12HJV]: readFrameHeader: read tcp 10.64.0.182:8443->10.10.0.209:16613: read: connection reset by peer",
    "logging.googleapis.com/severity": "DEBUG"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "pod_name": "coder-5cd55775cf-c97bb",
      "namespace_name": "coder-big",
      "container_name": "coder",
      "project_id": "v2-loadtest",
      "location": "us-central1-a",
      "cluster_name": "big"
    }
  },
  "timestamp": "2023-12-05T13:22:13.479878805Z",
  "severity": "DEBUG",
  "labels": {
    "k8s-pod/app_kubernetes_io/version": "2.4.0",
    "k8s-pod/helm_sh/chart": "coder-2.4.0",
    "k8s-pod/pod-template-hash": "5cd55775cf",
    "compute.googleapis.com/resource_name": "gke-big-big-coder-8a85823c-eghm",
    "k8s-pod/app_kubernetes_io/instance": "big",
    "k8s-pod/app_kubernetes_io/name": "coder",
    "k8s-pod/app_kubernetes_io/managed-by": "Helm",
    "k8s-pod/app_kubernetes_io/part-of": "coder"
  },
  "logName": "projects/v2-loadtest/logs/stderr",
  "operation": {
    "producer": "coderd.derp"
  },
  "sourceLocation": {
    "file": "/home/runner/go/pkg/mod/github.com/coder/tailscale@v1.1.1-0.20231106123012-ba3acaa26275/derp/derp_server.go",
    "line": "440",
    "function": "tailscale.com/derp.(*Server).Accept"
  },
  "receiveTimestamp": "2023-12-05T13:22:17.111282731Z"
}
```

(Link to [Logs Explorer](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-12-05T13:22:15.989920045Z;endTime=2023-12-05T13:23:00.000Z;query=resource.labels.namespace_name%3D%22coder-big%22%0Alabels.%22k8s-pod%2Fapp_kubernetes_io%2Fname%22%3D%22coder%22%0Atimestamp%3D%222023-12-05T13:22:13.479878805Z%22%0AinsertId%3D%22nrxny06r6n02jz3b%22;startTime=2023-12-05T13:01:00.000Z?project=v2-loadtest).)

Could this indicate we have a bug where the connection (single tailnet) is broken and we don't attempt to re-establish it?

**Comment by kylecarbs** [comment]
This doesn't happen anymore! I left it running in my workspace for a minute, and was able to open a new terminal and such!
