### ISSUE TITLE
JavaScript error in Brave when clicking on workspace entry in browser UI

### ISSUE THREAD

**Issue by BjoernKW** [coder/coder#11035]
When clicking on a workspace entry at https://coder.spring-boot.spaces.workshops.de/workspaces in the browser UI with the Brave browser ([version 1.60.125 Chromium: 119.0.6045.199 (Official Build) (arm64)](https://brave.com/latest/)) I get this error message (also see the attached screenshot):

"TypeError: Failed to fetch dynamically imported module: https://coder.spring-boot.spaces.workshops.de/assets/WorkspacePage-529c670d.js"

I have these extensions installed (so, no additional ad / JavaScript blocker besides the one that comes with Brave itself):

* 1Password - Password Manager
* Angular DevTools
* Bear Chrome extension
* React Developer Tools
* Vue.js devtools

<img width="698" alt="Screenshot 2023-12-05 at 13 32 27" src="https://github.com/coder/coder/assets/125270/c862d3cd-adc5-478a-aec8-eeb422c822d2">

**Comment by BrunoQuaresma** [comment]
If you refresh the page does it work? We see that happening when the user try to access the Workspace page during a Coder update.

**Comment by BrunoQuaresma** [comment]
Hmm... interesting. Are you able to access the page in other browsers? Wondering if it is a privacy/security setting on Brave that is blocking this file from being loaded correctly.

**Comment by BjoernKW** [comment]
> Hmm... interesting. Are you able to access the page in other browsers? Wondering if it is a privacy/security setting on Brave that is blocking this file from being loaded correctly.

Yes, it works in Safari, for instance.

**Comment by BrunoQuaresma** [comment]
Looks like there is a config/extension in the browser that is blocking this file from being loaded correctly. I never used Brave so I have no idea. Ping @coder/ts folks to see if someone can help with that.

**Comment by aslilac** [comment]
afaik there isn't anything we can do to work around it if the browser decides to block a js file short of awful proxy shenanigans (make someone else request the file and tunnel it through them)

I used to use Brave, and iirc you can click on the lion logo in the address bar and adjust the privacy setting to "allow fingerprinting" or something. I don't remember exactly, and I don't have it installed anymore, but I just remember it being a vaguely scary sounding setting that basically amounts to "disable network filtering and let them run webgl". It's an origin-specific setting, so it'll only affect the domain you access Coder from.

**Comment by BjoernKW** [comment]
> https://coder.spring-boot.spaces.workshops.de/workspaces

Unfortunately, it doesn't work either with a setting of "Allow fingerprinting".
<img width="372" alt="Screenshot 2023-12-06 at 08 22 43" src="https://github.com/coder/coder/assets/125270/c0c3667d-a82b-430a-bbe5-0ee3da345936">

I have to allow trackers and ads for it to work:
<img width="374" alt="Screenshot 2023-12-06 at 08 24 18" src="https://github.com/coder/coder/assets/125270/4e7b7f29-10e2-48ce-9ec2-09b8929516aa">

Apparently, that particular script either does some kind of tracking or at least is categorised as a tracker by Brave.

**Comment by BrunoQuaresma** [comment]
We don't do any kind of FE tracking in the UI 🤔 but on this page, we have a WebSocket connection to update the workspace data in real-time... not sure if this is the reason why Brave is marking it as a tracker. I also don't know if the modification, for some reason, is generating some words that are getting caught by the Brave analysis.

I don't think there is something we can do on our side, are you comfortable closing this issue?

**Comment by BjoernKW** [comment]
Yes, I think closing the issue is fine. Thanks for your help!
