### ISSUE TITLE
Integrate `sqlc verify` into Github actions

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#11047]
SQLc has a cloud product in "beta" atm that allows running a command called `sqlc verify`. The tools are still in their infancy, but already can generate some value. 

There are 2 things that we can benefit from if we **integrate this into our actions**.

# Verify Schema Changes

[Blog post](https://sqlc.dev/posts/2023/11/21/sqlc-v1-24-0-verify-schema-changes/)

### Blue/Green deployments?

Verify can catch breaking changes that would prevent a blue/green deployment of Coder. We have had customers ask if this is a supported deployment style, which at current we do not have any insight on. 

_I am not sure_ if we can support this, so the tool will help us answer that question going forward. 
There is some more work ontop of this likely necessary, but this can generate true negatives to the question.

### Broken queries

Our go unit tests currently will find any broken query as a result of a db migration. The `sqlc verify` can just more quickly and aptly describe the failure. If we mark this as a required job for the postgres tests, we can reduce the CI time for obvious failures. Debugging this failed action should also be way quicker then debugging the failed go tests.

# Table scans and indexs

[Blog post](https://sqlc.dev/posts/2023/11/30/detect-sequence-scans-with-verify/)

This is something we have not put a lot of effort towards, but optimizing some queries could improve some of our scaletests performances and page load times.

The sqlc tool can print out queries that could be slow based on our indices. At present, detecting slow queries would likely take running a scaletest and observing the prometheus metrics? 

Example:

```
=== Warning
=== WARN: authors query.sql ListAuthors (sequence-scan-in-query-plan)
    Running this query may result in a sequence scan against the authors table.
    To suppress this warning, add the following annotation to your query:
        -- @sqlc-verify-disable sequence-scan-in-query-plan

    -- name: ListAuthors :many
    SELECT id, name, bio FROM authors
    ORDER BY name
```

# What is SQLc?

SQLc has been the tool that all of our database queries are written ontop of. It has drastically reduced our writing SQL -> prod delivery. The latest offerings of the tool have expanded beyond our original use of the tool.

**Comment by matifali** [comment]
@Emyrk I think we have this integrated in ci now, or are we still missing something?

**Comment by Emyrk** [comment]
@matifali I think I have it integrated enough for now. As their tool grows, we can expand what it does.
