### ISSUE TITLE
make it easy to host offline docs in kubernetes

### ISSUE THREAD

**Issue by matifali** [coder/coder#11055]
We provide a tar.gz of our documentation in static HTML format for the benefit of air-gapped customers so that they can have our documentation available offline.

For air-gapped customers using Kubernetes, a nice QoL feature would be to add the capability to our Helm chart to automatically deploy the docs to their cluster using e.g. nginx.

Original description:

> 
> - [ ] Convert our existing .tgz documentation files into a containerized format.
> - [ ] Publish as a package e.g., `ghcr.io/coder/docs:v2.4.0`
> - [ ] Include a builtin-server, e.g., `nginx`, that serves the docs as the container's `entrypoint`.
>

**Comment by bpmct** [comment]
I'm not convinced we should do this. Our customers can serve this statically using something like GitHub pages and can always run a `nginx` image with the docs mounted. It requires some extra work but is flexible enough to support many options. Perhaps we could add a doc on how to serve an nginx container with the docs filesystem mounted?

**Comment by bpmct** [comment]
I'm fine if we run the `nginx` container with our Helm chart and the docs mounted but don't want us to make a custom `coder-docs` image we publish

**Comment by matifali** [comment]
@bpmct so the idea is to update the Helm chart to run an optional `nginx` container that will pull and server the correct version of offline docs.

**Comment by johnstcn** [comment]
I think this could use a mini RFC before make any code changes.

**Comment by matifali** [comment]
As an MVP, we should first serve offline docs for our dogfood instance. This will allow us to test if search, navigation, etc., works as expected.
