### ISSUE TITLE
give better error messages when queries in modelqueries.go break

### ISSUE THREAD

**Issue by aslilac** [coder/coder#11073]
We have some hand-written queries in coderd/database/modelqueries.go that need to be updated manually sometimes, in contrast to most of our queries which are generated automatically based off of our database schema. We also have some tests that will fail when these queries become out of date, which is good, but the error messages the tests end up giving don't point in the right direction.

We should improve the test cases to more directly guide you to the right place.

**Comment by Emyrk** [comment]
@aslilac https://github.com/coder/coder/pull/11211 should make things a bit better. This will fail on `make gen` now with some helpful message

**Comment by aslilac** [comment]
nice!
