### ISSUE TITLE
Allow Coder to be an OAuth provider

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11084]
Currently, we support External Authentication which lets people link external providers to their Coder account. However, we do not allow people to link their Coder accounts to an external account (e.g. "Link your Coder account to Backstage" or "Link your Coder account to Vault")

GitHub supports this in account settings:

<img width="1448" alt="Screenshot 2023-12-07 at 8 39 54 AM" src="https://github.com/coder/coder/assets/22407953/28175e8e-4aa7-4c4c-941b-dbfcc41e0500">

Refresh token capability is covered as part of this ticket

**Comment by bpmct** [comment]
Related #10656

**Comment by matifali** [comment]
For vault we may look into as one of [supported auth methods](https://developer.hashicorp.com/vault/docs/auth)
More details: https://developer.hashicorp.com/vault/docs/concepts/auth

I think our flow can work best similar to GitHub auth method. Where we pre configure vault with a Coder OAuth app and then can login simply 
With 
```shell
vault login -method=coder token=$CODER_SESSION_TOKEN
```

**Comment by matifali** [comment]
> For vault we may look into as becoming one of the supported [auth methods](https://developer.hashicorp.com/vault/docs/auth) More details: [developer.hashicorp.com/vault/docs/concepts/auth](https://developer.hashicorp.com/vault/docs/concepts/auth)
> 
> I think our flow can work best similar to [GitHub auth method](https://developer.hashicorp.com/vault/docs/auth/github). Where we pre configure vault with a Coder OAuth app and then can login simply With
> 
> ```shell
> vault login -method=coder token=$CODER_SESSION_TOKEN
> ```
> 
> Reference: [developer.hashicorp.com/vault/docs/auth/github](https://developer.hashicorp.com/vault/docs/auth/github)

Hi @Kira-Pilot, do we also support the use case above?

**Comment by Kira-Pilot** [comment]
@matifali we do not currently!

**Comment by Kira-Pilot** [comment]
This is effectively done; just want to finish adding it to Backstage.

**Comment by Kira-Pilot** [comment]
Making a new ticket for Ben's requests above and closing this guy out as its pretty old

**Comment by matifali** [comment]
> Make the route publicly accessible

@Kira-Pilot, can you help me find what the API endpoint for this is? I am exploring this for a validation integration in context of #13127
