### ISSUE TITLE
`coderd_insights_applications_usage_seconds` does not iterate for JetBrains Gateway applications

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11103]
[this PR](https://github.com/coder/coder/pull/10346) added support for the `coderd_insights_applications_usage_seconds`, but in my testing, does not go iterate greater than `0` for JetBrains Gateway applications present in a template.

produced on 2.4.0. this may be fixed once this PR is merged https://github.com/coder/coder/pull/10968

**Comment by mafredri** [comment]
@ericpaulsen I believe you could test this image to see if #10968 fixes the issue: https://github.com/coder/coder/pkgs/container/coder-preview/155780357?tag=main-2.4.0-devel-dbbf8acc2

**Comment by ericpaulsen** [comment]
resolved.
