### ISSUE TITLE
workspace proxies: unique health check error if being treated as a subdomain app

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11116]
## Background

A customer may mistakenly put a proxy in the same DNS path as wildcard apps, where the wildcard app somehow takes priority.

e.g. `*.demo.coder.com` vs `proxy.demo.coder.com`

![image](https://github.com/coder/coder/assets/22407953/86df19a2-f10d-4d89-82c1-4b1cd6429087)
![image](https://github.com/coder/coder/assets/22407953/95c4cad7-0bb9-4851-bad4-40797d6edd8c)
![image](https://github.com/coder/coder/assets/22407953/91fa8027-1e08-49e8-a1ec-f4ceede59c44)

## Proposal

Show a unique error in the health check to explain the conflict and resolution

**Comment by bpmct** [comment]
@deansheather mind taking this one?

**Comment by Emyrk** [comment]
This seems highly niche.

We also output the appropriate values when you do `coder wsproxy create`

```
CODER_PROXY_SESSION_TOKEN=<token> coder wsproxy server --primary-access-url https://<host>.com --http-address=0.0.0.0:3001 
```

---

I am having trouble even setting this up. When you create a new proxy, it requests the `/buildinfo` endpoint, which doesn't return a json payload, so you get:

```
$ go run main.go wsproxy server --primary-access-url=https://filebrowser--dev--coder--emyrk--apps.dev.coder.com/ ...
#...
Encountered an error running "coder workspace-proxy server"
create workspace proxy: failed to fetch build info from "https://filebrowser--dev--coder--emyrk--apps.dev.coder.com/": invalid character '<' looking for beginning of value
```

So you can't even start the workspace proxy here to set it up in the first place.

**Comment by bpmct** [comment]
I think @sharkymark did this somehow?

I'm down to close this if you want to label it as an edge case

**Comment by Emyrk** [comment]
@bpmct I have already spent some time on this path, and I found some little things I can improve. I'll put up a PR or two, but I don't think I have the setup for this specific situation.

**Comment by Emyrk** [comment]
Cli error improvements: https://github.com/coder/coder/pull/11584

**Comment by Emyrk** [comment]
Found the way to reproduce, had it backwards. Fixed
