### ISSUE TITLE
feat: Allow upload of custom icons for templates and banner usage

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#11128]
Version: [`v2.4.0+d19a762`](https://github.com/coder/coder/commit/d19a762589e84afd18f2245ebc03daccb53cb13f)

A customer wants the ability to upload custom icons for templates and banner usage

Using URLs is not always possible

**Comment by matifali** [comment]
Same as #3974

**Comment by BrunoQuaresma** [comment]
Requires BE cc.: @mtojek

**Comment by mtojek** [comment]
It needs also an action plan or a short RFC, so we won't iterate on this many times.
