### ISSUE TITLE
support markdown on deprecated message, like service banners

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11138]
Right now it renders in plaintext

<img width="1299" alt="Screenshot 2023-12-11 at 3 59 52 PM" src="https://github.com/coder/coder/assets/22407953/d8ef0124-5073-4d8d-83b4-990cc92a0fa4">

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by matifali** [comment]
We should make use of https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts.

**Comment by 20RitikSingh** [comment]
can you explain the issue a bit more

**Comment by matifali** [comment]
We have a property `deprecated` that allows a template to be marked as deprecated with a deprecation message. Currently the message displayed in the UI is plaintext and doesn't support markdown rendering. 
For minimum it should support markdown links and making font **bold**, _italic_, etc.
