### ISSUE TITLE
first admin account missing organization

### ISSUE THREAD

**Issue by Archer57** [coder/coder#11137]
Hi,

I'm working on automating the Coder setup using Terraform.
When I stop the server after the initial installation, run `coder server create-admin-user` with the required parameters, the admin user gets created. But when I start the Coder server again and want to log in with the admin user, I recieve an error saying that the user doesn't belong to an organization.
For some reason, I can get authenticated to call the api this way. So when I call `/api/v2/users`, I can see my admin user and that it doesn't belong to any organization. If I visit my main Coder URL again, I'm logged in as well.

In my opinion, both ways are not intended. If I recieve an error trying to log in, I should not be authenticated after that. But at the same time, I need a way for automating the process of creating a valid initial admin account that I can log in with.
Maybe, the `coder server create-admin-user` command needs to be extended so that it creates an organization if there is none present.

Best regards

**Comment by matifali** [comment]
To create first user you should use
```shell
coder login \ 
	 --first-user-username admin \ 
	 --first-user-email padmin@coder.com \ 
	 --first-user-password SomeSecurePassword! \ 
	 --use-token-as-session \ 
	 https://coder.example.com
```
as shown here: https://github.com/coder/coder/blob/b7ea330aea4c33ba0827b95daa35d594f68a0246/.github/workflows/pr-deploy.yaml#L412-L418

**Comment by matifali** [comment]
cc: @Emyrk @bpmct we should prevent running `coder server create-admin-user` if a deployment has not been setup and there is no organization created. I think this is a bug with how `coder server create-admin-user` works.

**Comment by Emyrk** [comment]
The first user created should **always** generate a first org: 

https://github.com/coder/coder/blob/ad3f47f7f9187ff993ff7e0837a8cafb41067c49/coderd/users.go#L174-L174

Is there a bug that allows you to make a first user and skip that somehow?

**Comment by Archer57** [comment]
Thank you all very much for your responses!

> `coder server create-admin-user` is only used to create additional admin users once a deployment is already setup. As per [docs](https://coder.com/docs/v2/latest/cli/server_create-admin-user#usage)

The [Installation Docs](https://coder.com/docs/v2/latest/install) currently just explain how to install Coder initally and redirect to [Configuration](https://coder.com/docs/v2/latest/admin/configure). Here, some examples for using the coder.env are given. I would suggest that as part of this process, the creation of a initial user is mentioned to prevent missunderstandings.


> The first user created should **always** generate a first org:
> 
> https://github.com/coder/coder/blob/ad3f47f7f9187ff993ff7e0837a8cafb41067c49/coderd/users.go#L174-L174
> 
> Is there a bug that allows you to make a first user and skip that somehow?

Yes. Currently, the command `coder server create-admin-user` creates an admin user. This process counts as "creating a first user" as I get `"message": "The initial user has already been created!"` when calling `/api/v2/users/first`.

For my deployment, it is a workaround to create a initial user to get a first organization, but because I want to use OAuth to authenticate users via GitLab, this just adds anouther user next to the admin that is never used.

Because `coder server create-admin-user` already switches the API endpoint `/api/v2/users/first`, the easiest way to fix this issue in my opinion is to add a check weither there are already existing organizations in the Coder instance and if not, create one before creating the admin user.
