### ISSUE TITLE
healthcheck for wsproxy inaccurate

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#11184]
Version: [`v2.5.0+cab8ffa`](https://github.com/coder/coder/commit/cab8ffa54ad88b34b965b0aeb859f35c335c5fcb)

The default or primary wsproxy says it is 2023 years old. 

![image](https://github.com/coder/coder/assets/2022166/3a8ed8d7-131e-4418-855a-b7248ee2fcf8)

**Comment by matifali** [comment]
Same observation on dev.coder.con
