### ISSUE TITLE
agent metadata shows red, but I have plenty of storage

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#11187]
Version: [`v2.5.0+cab8ffa`](https://github.com/coder/coder/commit/cab8ffa54ad88b34b965b0aeb859f35c335c5fcb)

![image](https://github.com/coder/coder/assets/2022166/d60a739c-e688-409f-a84e-26e38531bd45)

**Comment by BrunoQuaresma** [comment]
🤔 it is red when the metadata returns an error but we probably should add a tooltip with the error message to help with debugging or replace the value with the error message. Wdyt @matifali ?

**Comment by matifali** [comment]
@BrunoQuaresma so you are saying that red color is because of an error and the value is actually an old value?

If this is the case I think we should just replace the stale value with error message.

**Comment by BrunoQuaresma** [comment]
The error is an actual error. Let's say the first time the data is loaded it returns the value "2" but on the second try it gets an error like "Error on script C:/some/ohter/random/path with line 232323 at bash.sh" so we return the error but keep using the old value. 

I realized these script errors can be quite big so I'm wondering if a tooltip could be better 🤔

**Comment by matifali** [comment]
You are the UI/UX expert. I trust your expertise. If you think a tooltip is better go for it.

**Comment by bpmct** [comment]
This is based on the exit code of the command, we plan on keeping this behavior but should ensure our examples have valid commands
