### ISSUE TITLE
When workspace build fails due to Quota check, the UI does not give proper indication

### ISSUE THREAD

**Issue by mreadie** [coder/coder#11192]
When a user tries to create a workspace and it fails the quota check, the UI does not convey the failure properly: the progress bar keeps cycling, and clicking the `Cancel` button doesn't make it stop. To get out of this, the user must click another section of the UI (such as Workspaces), and then click back into the failed workspace to get the proper message they should get as soon as it fails about failure due to quota. 
Attached is a video of this undesirable behavior. 

https://github.com/coder/coder/assets/147888467/ba157dba-170e-49bc-b6c9-7e01bbbf43c0

**Comment by matifali** [comment]
Can we disable the create workspace button if a user doesn't have sufficient quota left?

**Comment by bpmct** [comment]
@matifali sadly we can't because calculating the quota often involves a `terraform apply` since it can be dynamic (e.g. based on disk size)

**Comment by bpmct** [comment]
I do think we can improve the UX even if it is after a workspace is already requested. For example, it constantly "loading" makes it seem buggy
