### ISSUE TITLE
Cannot edit Dockerfile

### ISSUE THREAD

**Issue by CTORH** [coder/coder#11203]
Version: [`v2.5.0+cab8ffa`](https://github.com/coder/coder/commit/cab8ffa54ad88b34b965b0aeb859f35c335c5fcb)

Dockerfile is now shown when expanding the build folder

**Comment by kylecarbs** [comment]
I assume this is in the web editor. 

cc @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
@CTORH could you share a screenshot of your folder structure, please?

**Comment by BrunoQuaresma** [comment]
@SagePetit thanks for sharing.

**Comment by SamORichards** [comment]
I also have the same problem, not showing on Chrome as well

**Comment by BrunoQuaresma** [comment]
I'm wondering if we can have a Coder env like `CODER_EDITABLE_TEMPLATE_FILES` that would accept a regex.

**Comment by BrunoQuaresma** [comment]
For now, I'm going to work on fix the sub folder problem.
