### ISSUE TITLE
Custom files in templates are not working

### ISSUE THREAD

**Issue by jaulz** [coder/coder#11221]
It seems that files not having `.tf`, `.md` or `.sh` are ignored while pushing the template. Is there any specific reason for it? I would like to add `.sql` files in my template which I can then bind into a docker container. 

After a while I saw that the web editor also doesn't allow it:
![image](https://github.com/coder/coder/assets/5358638/9a3fa26e-5f13-4bc7-92ba-82a94834f167)

It would be great if there was a workaround at least.

**Comment by matifali** [comment]
cc: @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
We don't allow custom files for security reasons since a few template files can contain sensitive information like GPG keys. I'm not sure if it still a reality tho. I will start an internal conversation to see what we can do here.

**Comment by jaulz** [comment]
@BrunoQuaresma thanks! A global flag would be fine as well? Also an hint while pushing the template would have saved me a couple of hours 😁 

A workaround is by the way to create a Dockerfile which extends the image from hub and uses COPY to copy the files to the image first.

**Comment by BrunoQuaresma** [comment]
Supported by https://github.com/coder/coder/pull/12000

**Comment by jaulz** [comment]
@BrunoQuaresma thanks for the hint but I as far as I can see the change is only about the front-end? The CLI still does not upload all files?

**Comment by BrunoQuaresma** [comment]
Hm... I think it does, could you please confirm that? I would appreciate any screenshot or video showing the issue 🙏 . The CLI creates a `.tar` file and uploads it so I'm guessing the `.tar` file contains all the files without filtering them.

**Comment by jaulz** [comment]
@BrunoQuaresma so this is my local structure:
![image](https://github.com/coder/coder/assets/5358638/9b2297fb-ab37-47f4-8137-4aa0f64a3083)

Then I use `coder templates push --directory ./templates/supabase/ --yes --verbose` to upload the template and I see these files in the editor only:
![image](https://github.com/coder/coder/assets/5358638/df334b82-c830-41f2-9627-470769c5bfd1)

Also, I still see this error message:
![image](https://github.com/coder/coder/assets/5358638/27e03fd3-c899-4675-9399-95f054cc3c68)

However, while replying to you I checked whether there was any release since your message and your change is probably not released at all? 😊

**Comment by BrunoQuaresma** [comment]
Which version are you using?

**Comment by jaulz** [comment]
I upgraded before and use [v2.8.1+908d236](https://github.com/coder/coder/commit/908d236a19a113e8e3e6f98d748857094ec96a5d)

**Comment by BrunoQuaresma** [comment]
Ahh ok, should be available in the next release 🤞 but please let me know if after that you still facing this issue. I appreciate your help and patience.
