### ISSUE TITLE
Proposal: add API based end-to-end (aka e2e) testing

### ISSUE THREAD

**Issue by LinuxSuRen** [coder/coder#11230]
## Describe the feature
I'm the author of [api-testing](https://github.com/LinuxSuRen/api-testing) which is an API testing tool. It seems that no e2e testing in this project. I'd be happy to implement it if you believe it's worth.

In order to let you have a quick kowning about it. Please see also the user's of [api-testing](https://github.com/LinuxSuRen/api-testing/discussions/284).

**Comment by bpmct** [comment]
Hey @LinuxSuRen - sorry we missed your message. We've currently started making more of an effort to do e2e testing, which you can follow here: https://github.com/coder/coder/milestone/30

If you think api-testing would be beneficial still, we welcome contributions!
