### ISSUE TITLE
terraform state mismatch when the build times out, but resource is eventually created

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11237]
a customer experienced node-level issues that caused workspace pods to become stuck in a `ContainerCreating` state for over an hour, leading to the terraform build timing out, and users attempting to "Start" the workspace, resulting in a `pod already exists` error.

> 
> The workspace build timed out due to an issue with the node in the cluster, but after it timed out, the pod in the cluster was not deleted. It kept trying to spin up the pod.
> 
> Eventually it spinned up the pod and the pod started running. But since the workspace build was timed out, the user tried to rebuild the workspace, and the terraform errored, saying the pod already existed.
> 
> The expected behavior was that the workspace build time out would delete the underlying pod from the cluster. But instead it kept on running and then the user could not rebuild her workspace.

**Comment by spikecurtis** [comment]
We should look into what terraform state (if any) we capture on a build timeout.  If terraform is recording the state and we are not capturing it, then that's a bug, and would result in this kind of issue.

If terraform doesn't record the state of the pod on a timeout, we might need to look into the K8s provider and/or terraform itself.  Without the state we can't hope for the next build to be able to tell the difference between a pod that was created on the previous build and a legit pod name collision.
