### ISSUE TITLE
refactor coderd: detect provisioner PSK and set provisionerd actor in context

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#11236]
From discussion in https://github.com/coder/coder/pull/11207/files#r1427825729

Currently, for provisionerd PSK auth, we just check the auth header manually. This is a bug risk as we can simply forget to do this at all the relevant points.

It would be cleaner and safer to modify our auth middleware to set the provisionerd actor in context if a PSK header is set.

**Comment by kylecarbs** [comment]
This is getting old so I'm going to close. If you disagree please reopen @johnstcn!
