### ISSUE TITLE
broken formatting for CLI docs

### ISSUE THREAD

**Issue by matifali** [coder/coder#11247]
https://coder.com/docs/v2/latest/cli/config-ssh#--wait
![image](https://github.com/coder/coder/assets/10648092/f85e9247-8604-4682-a2af-1761f206d928)

**Comment by pravinkumarone** [comment]
Hey @matifali I would like to fix this bug.

Is this the expected result you are looking for?
![image](https://github.com/coder/coder/assets/109470708/3e168503-eeed-4c53-a97c-397bfdc2bae7)

**Comment by matifali** [comment]
@pravinkumarone Yes, this does look alright. Be sure to update the code as these are auto-generated docs.

**Comment by pravinkumarone** [comment]
Sure no worries, please assign this issue to me

**Comment by pravinkumarone** [comment]
I've raised a PR

`fix broken formatting docs/cli/configssh #11333`

**Comment by pravinkumarone** [comment]
Hey @matifali sorry about that, I'm new to open source but I'll figure out and fix this soon

**Comment by mtojek** [comment]
I'm looking into this.
