### ISSUE TITLE
dbmem: ensure that behaviour matches that of real DB

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#11263]
> Is this really the same return signature the DB gives? I believe you have to check the affected rows of the `Exec` as it will not return an error, just zero affected rows.
> I wonder if we rely on similar assumptions elsewhere in the code, seeing as the generated code doesn't check affected rows 🤔

_Originally posted by @mafredri in https://github.com/coder/coder/pull/11207#discussion_r1427890907_

**Comment by kylecarbs** [comment]
This is too broad to consider open or closed. If there's something specific we should do, please narrow the scope!
