### ISSUE TITLE
agentproto: use Request and Response types in RPC calls rather than the raw inner type

### ISSUE THREAD

**Issue by deansheather** [coder/coder#11265]
Using a `Request` and `Response` wrapper like `UpdateLifecycleRequest` and `UpdateLifecycleResponse` means we can add additional fields to the requests and responses in the future without changing the inner type `Lifecycle`.

This means we don't need to make breaking API version changes in the future to add fields that only impact clients on the latest version. For example, we might add the previous `Lifecycle` in the response as a new field or something.

This needs to happen before we start consuming agentapi on agents otherwise it will become a breaking change to convert to this.

**Comment by kylecarbs** [comment]
@deansheather closing this because I'm not sure of the prio. Feel free to reopen if you think we should still do it!
