### ISSUE TITLE
`coder port-forward` decreases bandwidth by 50% vs. direct connection to workspace

### ISSUE THREAD

**Issue by mambon2** [coder/coder#11272]
I have tested network bandwidth using iperf3 utility with and without coder port-forward relay.  Here are my findings below.

iperf3 -t 120 -c 10.36.77.55 (direct, no coder)
iperf3 -t 120 -c localhost (with coder port-forward)

NYCVPN Mac client to us-east-1 EC2 direct

[  5]   0.00-120.00 sec   576 MBytes  40.3 Mbits/sec                  sender
[  5]   0.00-120.01 sec   576 MBytes  40.3 Mbits/sec                  receiver

NYCVPN Mac client to us-east-1 EC2 with coder port-forward

[  7]   0.00-120.01 sec   256 MBytes  17.9 Mbits/sec                  sender
[  7]   0.00-120.04 sec   252 MBytes  17.6 Mbits/sec                  receiver

Test were conducted week of 12/6/23

**Comment by mambon2** [comment]
Coder v2.3.1

**Comment by kylecarbs** [comment]
We've actively worked on improving the throughput, and in an upcoming release it will get even better (#13406).

Let me know if this is still a problem!
