### ISSUE TITLE
Docs search is non-operational

### ISSUE THREAD

**Issue by stirby** [coder/coder#11287]
## Overview 
Our docs search (Algolia) is down. No terms are searchable in the site. Occurs on multiple browsers.

<img width="833" alt="Screenshot 2023-12-19 at 3 45 26 PM" src="https://github.com/coder/coder/assets/58410745/184b1f0a-2907-4863-a8ea-d87e8513af29">

**Comment by bpmct** [comment]
seems to work now?

**Comment by stirby** [comment]
Assuming an intermittent bug with Algolia. Will revisit when refactoring with Orbit.
