### ISSUE TITLE
Differentiate between coder agent disconnect and shutdown

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11298]
In some cases, it's possible that the `coder agent` has gracefully exited inside a workspace (let's say a VM is turned off).

It would be nice to reflect this state in the coder UI (web/cli) instead of simply stating that "the agent lost connection".

Currently, this state is detectable:

```
❯ coder list --output=json | jq -r '.[] | select(.name == "w") | .latest_build.resources[].agents[]? | .lifecycle_state'
ready

❯ ssh coder.w 'pkill -INT -f "coder agent"'

❯ coder list --output=json | jq -r '.[] | select(.name == "w") | .latest_build.resources[].agents[]? | .lifecycle_state'
off
```

Currently the web shows "disconnected"/unhealthy, and the CLI also shows no warning (e.g. `coder ssh` simply, seemingly, hangs).

In the `shutting_down`/`off` state, there is a good chance the agent isn't coming back, so we should inform the user.

**Note:** Even though the `coder agent` supports reporting this, it's dependent on how the shutdown process of the e.g. VM terminates the agent.

**Comment by matifali** [comment]
As a workaround, we can make the coder_agent ephemeral by setting `count = data.coder_worksapce.me.start_count`. But your suggestion looks like a true solution.

**Comment by mafredri** [comment]
@matifali I think that's a separate issue and something we may consider for other functionality. This suggestions doesn't directly tie into terraform, per-se.
