### ISSUE TITLE
Improve PR deployment workflow 

### ISSUE THREAD

**Issue by matifali** [coder/coder#11331]
The current workflow works fine, but it takes way too long (>10 minutes) for a developer to be willing to wait (greater than 10 minutes)

Some possible improvements. 
1. Use a single wildcard cert for all PR deployments supporting wildcards for individual deployments. 
2. Improve automatic redeployment (current behavior checks diff between consecutive commits, which prevents redeployment in case of non-code changes).
3. Allow deploying by a PR comment
4. Allow deploying a branch without creating a PR

**Comment by kylecarbs** [comment]
Closing for now, but feel free to do this of course! Just wanna keep the tracker clean.
