### ISSUE TITLE
terraform variable of object type

### ISSUE THREAD

**Issue by s4s0l** [coder/coder#11354]
How to pass object type variables to terraform when creating a template?

In tf i've got:

```tf
variable "host_params" {
  type = object({
    target_machine = string
    dns            = string
    coder_host     = string
    coder_ip       = string
  })
  default = {
    target_machine = ""
    dns        = "100.100.100.100"
    coder_host = ""
    coder_ip   = ""
  }
}
```

and i want to pass them from --variables-file like this:

```yml
host_params:
  target_machine: "machine"
  dns: "1.1.1.1"
  coder_host: "host"
  coder_ip: "10.213.0.101"
```
but i'm getting error while doing template create

```
Encountered an error running "coder templates create"
yaml: unmarshal errors:
  line 2: cannot unmarshal !!map into string
```

It seem that only flat maps are supported. Can I work it around?

Not a big deal, I can get rid of object type, but it is handy when validation of terraform parameters is based on values of multiple parameters...

```
→ coder version
Coder v2.6.0+b3e3521 Thu Dec 21 22:33:13 UTC 2023
https://github.com/coder/coder/commit/b3e352127478bfd044a1efa77baace096096d1e6

Full build of Coder, supports the  server  subcommand.

```

**Comment by stirby** [comment]
This seems to be an HCL syntax issue, not a problem with the way Coder parses the template file.

If you're still having an issue, I would open a ticket in the terraform repo.
