### ISSUE TITLE
Allow viewing and modifying provisioner tags on template versions via the dashboard

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#11360]
Template versions can be tagged with key-value pairs to allow the correct selection of provisioners when building a workspace based on the template.  These tags can be set with the CLI, but the dashboard isn't aware of them.

c.f. #11359 

In addition to preserving tags that are already set, we should enhance the dashboard to display the template version tags and allow them to be modified.

**Comment by matifali** [comment]
@f0ssel, can we also increase the scope of the issue to include the capability of adding new tags to the template creation form?

**Comment by f0ssel** [comment]
It will affect different pages on the frontend, so let's have them be separate tickets and I can complete the create page after this one
