### ISSUE TITLE
Insights datepicker doesn't update when navigating via historystate (back/forward)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11382]
Whenever a new range is selected in the insights datepicker, the URL is also updated to match. However, the opposite is not true. When navigating back/forward via browser history, the graph data _does_ change correctly, but the datepicker shows the old selected range.

In the following scenario, I selected Jan 1 - Jan 3, then Jan 3 - Jan 3 and hit the back button afterwards. The datepicker stayed on Jan 3 - Jan 3 but the data updated to the previous one, Jane 1 - Jan 3.

<img width="906" alt="image" src="https://github.com/coder/coder/assets/147409/76523d30-12f8-4638-b5b4-93f920fdb131">

Side-note: The graph animations are also quite slow (I'm using Safari if that matters), making the above transition look odd.

**Comment by BrunoQuaresma** [comment]
Closed by https://github.com/coder/coder/pull/11391
