### ISSUE TITLE
CSRF enforcement in v2.6.0 breaks RStudio IDE and other POST requests

### ISSUE THREAD

**Issue by JensHeise** [coder/coder#11406]
Hello,

we have a template running code-server and RStudio as IDEs.
The v2.6.0 release seems to brake the RStudio IDE and all POST requests inside apps running in vscode.

We think we got it down to #11283 enforcing CSRF.
All requests to the Coder API are functional but inside the IDEs POST requests are not.
This is due to the X-CSRF-TOKEN header not being set on the other requests.

Is there some way to fix this on our side or should there maybe another exempt in [coderd/httpmw/csrf.go](https://github.com/coder/coder/blob/ce380580b79ace6b3f955db21b9ccd41c590a044/coderd/httpmw/csrf.go) for the URLs where apps are running, e.g. `/@USER/test.instance/apps/`?
Or maybe a switch to remove the enforcement of CSRF for now?
I'm not really experienced with CSRF so I'm looking forward to your help!

## Expected Behavior

RStudio opens as usual, which it did before upgrading to v2.6.0.

## Actual Behavior
RStudio does not start and throws the following error:
<img width="415" alt="image" src="https://github.com/coder/coder/assets/62468949/85f2aaa7-1212-4252-b34b-e6830d324d47">

This can be backtraced to this POST call failing due to the coder CSRF protection kicking in.
_Note that the rs-csrf-token and csrf-token cookies are from RStudio and the csrf_token cookie is from Coder_
``` bash
curl 'https://coder.example.com/@USER/test.instance/apps/rstudio/rpc/client_init' \
  -H 'authority: coder.example.com' \
  -H 'accept: application/json' \
  -H 'cookie: coder_signed_app_token=<REDACTED>; user-id=<REDACTED>; user-list-id=<REDACTED>; persist-auth=0; rs-csrf-token=853023c5-6fe8-428a-9984-547f927d34a0; csrf-token=853023c5-6fe8-428a-9984-547f927d34a0; csrf_token=jadP8iK3mcFW5T24bfmSPKGbiWEYzKxS8k4gc5HcVbo=; oauth_state=<REDACTED>; oauth_redirect=/; coder_session_token=<REDACTED>' \
  -H 'origin: https://coder.example.com' \
  -H 'referer: https://coder.example.com/@USER/test.instance/apps/rstudio/' \
  -H 'x-rs-csrf-token: 853023c5-6fe8-428a-9984-547f927d34a0' \
  -H 'x-rs-rid: -256097717' \
  --data-raw '{"method":"client_init", "params":["https://coder.example.com/@USER/test.instance/apps/rstudio/","unfj3yhzabbmh01252nbz5tmv6z1fl1k"], "kwparams":{"restore_workspace":2, "run_rprofile":2}, "clientVersion":""}' \
  --compressed
```
Response:
`400 | Something is wrong with your CSRF token. Please refresh the page. If this error persists, try clearing your cookies.`

When I set the X-CSRF-TOKEN header manually and resend the request, it gets through but RStudio still doesn't start...

## Steps to Reproduce the Problem

  1. Setup template like described in documentation [here](https://coder.com/docs/v2/latest/ides/web-ides#rstudio)
  1. Start workspace from template
  1. Start RStudio

## Specifications

  - Version: v2.6.0
  - Platform: Linux
  - Subsystem: Ubuntu 22.04

**Comment by Emyrk** [comment]
Thank you for reporting this. This is a bug and I will work on this.

I think this can be solved by exempting all path based application routes.

**Comment by Emyrk** [comment]
fix and test to ensure this does not happen again: https://github.com/coder/coder/pull/11430

**Comment by bfqrst** [comment]
@Emyrk thanks for working on this issue and a belated Happy New Year while am at it! Since this CSRF situations really bites us in the back in some form or another in our apps, I wanted to ask if there's a timeline regarding cutting the next release?

Cheers

**Comment by bpmct** [comment]
Hey! I can cut a release tomorrow :)

**Comment by bpmct** [comment]
Update: we ran into several release blockers. Might have to wait until tomorrow or Monday.

**Comment by bfqrst** [comment]
I see. Good luck! Thanks for the heads up...

**Comment by murr4y** [comment]
@bpmct Hey, stumbled across this resolved issue. Since that CSRF enforcement renders many of our apps unusable as well, I was wondering if those release blockers have been resolved? Appreciate it! :)

**Comment by bpmct** [comment]
Yep - v2.7.1 includes the fix
