### ISSUE TITLE
support site-wide default theme flag

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11408]
a customer noted they'd like to set a site-wide default theme, so that any upgrades don't inadvertently change the theme, and surprise users. this occurred from `2.3.x -> 2.4.0`.

we told the customer that a user's theme preference (in account settings) will persist through upgrades.

**Comment by bpmct** [comment]
This would be a good pair with https://github.com/coder/coder/issues/11711

**Comment by BrunoQuaresma** [comment]
I guess it would require some BE to store that info. Maybe an ENV variable like `CODER_THEME` and add it into deployment data somehow?

**Comment by BrunoQuaresma** [comment]
cc. @mtojek

**Comment by stirby** [comment]
Not critical right now, want to avoid further site-wide config.
