### ISSUE TITLE
Hide DERP tags on the health page if they are false

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#11417]
Some feedback, the red pills such as `DERP Only` and `Disabled` make it look like something is wrong. Thoughts on just hiding them if the value is false?

[Slack Message](https://codercom.slack.com/archives/C04M9CNGHGF/p1704394665466889?thread_ts=1704394665.466889&cid=C04M9CNGHGF)

**Comment by spikecurtis** [comment]
I think it's ok to hide `DERP Only` if it's false.  My assumption is the default will be DERP + app proxy for most users.

I don't see `Disabled` on the page, so maybe this is referring to `Deleted`?  We soft-delete workspace proxies, so any proxy that is deleted should not be shown at all on the health page.

**Comment by BrunoQuaresma** [comment]
@johnstcn maybe we should update the backend to only return WS Proxies that are not deleted?

**Comment by johnstcn** [comment]
> @johnstcn maybe we should update the backend to only return WS Proxies that are not deleted?

Filed https://github.com/coder/coder/issues/11440
