### ISSUE TITLE
add a storybook for each FE component

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#11420]
We should have a storybook for each major visual component in our application

**Comment by aslilac** [comment]
| name                              | assignment | storybook | tests | notes                                                                                                                                                                                          |
| --------------------------------- | ---------- | --------- | ----- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `BuildAvatar`                     |            | x         |       | we have too much "avatar" spread around in the codebase. between this, `Avatar`, `AvatarIcon`, `AvatarData`, some of them are grouped together, some like this are on their own...what a mess. |
| `BuildIcon`                       |            | x         |       | similar thoughts as above. plus these both have "build" in the name, what's even the difference?? I'd love to see a PR collectively tackle all this stuff + add more stories                   |
| `FileUpload`                      |            | x         | x     |                                                                                                                                                                                                |
| `Form`                            |            | x         |       |                                                                                                                                                                                                |
| components/FullPageLayout/\*      | Bruno      | x         |       | Bruno added these recently, would be nice to have stories pls                                                                                                                                  |
| `InfoTooltip`                     |            | x         |       | I added a story, but it basically only checks the icon in chromatic. we should figure out how interaction testing works.                                                                       |
| `Loader`                          |            | x         |       | (already has `data-chromatic="ignore"`, convenient for devs tho, and chromatic will still check the bounding box/screen position)                                                              |
| Menu/Search.tsx                   |            | x         |       | could go for a small refactor (just put styles in the `styles` object, mainly). definitely needs to be moved somewhere, current spot makes no sense. maybe just components/Search/Search.tsx?  |
| `MoreMenu`                        |            | x         |       | needs some cleanup. use the `FC` type and get rid of inline `{}` type definitions.                                                                                                             |
| `Paywall`                         |            | x         |       | could use `AuditPaywall` as a reference                                                                                                                                                        |
| `Popover`                         |            | x         |       | another one that would benefit from interaction testing.                                                                                                                                       |
| `ProxyStatusLatency`              |            | x         |       | good candidate to move into modules/proxy/ perhaps? or we could just give it a more generic name like `Latency`                                                                                |
| `RequirePermission`               |            |           | x     | kind of a low-value test imo given the current component usage... it'd be cool to refactor this to take a permission name or something instead                                                 |
| `Stack`                           |            | x         |       | sort of nuts this doesn't have a story already                                                                                                                                                 |
| `UserAvatar`                      |            | x         |       | ahh, yeah, of course, another vague image component.                                                                                                                                           |
| `TableEmpty`                      |            | x         |       |                                                                                                                                                                                                |
| `TableLoader`                     |            | x         |       |                                                                                                                                                                                                |
| `TableToolbar`                    |            | x         |       |                                                                                                                                                                                                |
| `Template*`                       |            | x         |       | good candidates to move to modules/template/?                                                                                                                                                  |
| `UserAutocomplete`                |            |           | x     | already has stories, but has a lot of state, and could probably use some tests.                                                                                                                |
| `Workspace*`                      |            | x         |       | good candidates to move to modules/workspace/?                                                                                                                                                 |
| `WorkspaceBuildLogs`              |            |           |       | why is this not the sole consumer of `useWorkspaceBuildLogs`?                                                                                                                                  |
| 404Page.tsx                       |            | x         |       |                                                                                                                                                                                                |
| `CreateTokenPage`                 |            | x         |       |                                                                                                                                                                                                |
| `DeploySettingsPage`              |            |           | x     |                                                                                                                                                                                                |
| `ExternalAuthPage`                |            |           | x     |                                                                                                                                                                                                |
| `GroupsPage`                      |            |           | x     |                                                                                                                                                                                                |
| `TemplatePage`                    |            |           | x     |                                                                                                                                                                                                |
| `TemplatePermissionsPage`         |            |           | x     |                                                                                                                                                                                                |
| UserSettingsPage/ExternalAuthPage |            |           | x     |                                                                                                                                                                                                |
| `TokensPage`                      |            |           | x     |                                                                                                                                                                                                |

finished going through my evaluation, I think this is a rough summary of work to do to improve testing coverage
