### ISSUE TITLE
add tests for our custom hooks

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#11421]
We have several custom hooks on the FE and we should add jest tests for each.

**Comment by Parkreiner** [comment]
Taking a quick break from Backstage stuff to look into this more. Taking a note from @aslilac's post for the Storybook milestone:
| Done? | Hook name | Filepath | Status | Comments |
| --- | --- | --- | --- | --- |
|  | useDebouncedFunction |  `./hooks/debounce` | Touch up | One of the first custom hooks tests I ever wrote |
|  | useDebouncedValue |  `./hooks/debounce` | Touch up | One of the first custom hooks tests I ever wrote |
| | useCustomEvent | `./hooks/events` | Touch up | In a great spot; some assertions could be simplified |
|  | useEffectEvent | `./hooks/hookPolyfills` | Touch up | |
| | useClassName  | `./hooks/useClassName` | Needs test |  |
| | useClickable | `./hooks/useClickable` | Needs test |  Could probably have some TypeScript type definitions cleaned up too (sorry) |
| | useClickableTableRow  | `./hooks/useClickableTableRow` | Needs test |  |
|  | useClipboard | `./hooks/useClipboard ` | Needs test |  Had test made for revamp I tried, but when we had to revert it, the test was no longer applicable |
| | usePaginatedQuery  | `./hooks/usePaginatedQuery` | Has tests |  Might be good to go; there are a lot of tests for this already |
| | usePagination   | `./hooks/usePagination` | Needs test | Feels like it's right at the boundary between a custom hook and a utility function; might be better to remove the hook behavior |
| | useTab   | `./hooks/useTab` | Needs test |  |
| | useWorkspaceBuildLogs | `./hooks/useWorkspaceBuildLogs` | Needs test |  |
|  | useCoderTheme | `./src/components/SyntaxHighlighter/coderTheme` | Needs test/could be inlined | Very small hook used in one spot |
|  | useFilter | `./src/components/Filter/filter` | Needs test | Not general enough to go in the hooks folder, but used in several spots |
|  | useFilterMenu | `./src/components/Filter/menu` | Needs test | Not general enough to go in the hooks folder, but used in several spots |
|  | usePopover | `./src/components/Popover` | Needs test | Not general enough to go in the hooks folder, but used in several spots. Might be better to test the main component and the hook together? |
|  | useProxy | `./src/components/ProxyContainer` | Needs to double check | Not general enough to go in the hooks folder, but used in several spots. There's a test for the component, which might be enough? |
|  | useProxyLatency | `./src/contexts/useProxyLatency` | Need to double-check | This thing scares me. There's already a test for the overall context, though |
|  | useAuth | `./src/contexts/auth/useAuth` | Need to double-check | Used in several places; probably covered already via the test for the RequireAuth component |
|  | useMe | `./src/contexts/auth/useMe` | Need to double-check | Used in several places; probably covered already via the test for the RequireAuth component |
|  | useOrganizationId | `./src/contexts/auth/useOrganizationId` | Need to double-check | Used in several places; probably covered already via the test for the RequireAuth component |
|  | usePermissions | `./src/contexts/auth/usePermissions` | Need to double-check | Used in several places; probably covered already via the test for the RequireAuth component |
|  | useDashboard | `./src/modules/dashboard/useDashboard` | Need to double-check | Used in several places; probably covered already via the component tests |
|  | useFeatureVisibility | `./src/modules/dashboard/useFeatureVisibility` | Need to double-check | Used in several places; probably covered already via the component tests |
|  | useUpdateCheck | `./src/modules/dashboard/useUpdateCheck` | Need to double-check | Used in several places; probably covered already via the component tests |
|  | useUpdateCheck | `./src/modules/dashboard/useUpdateCheck` | Has tests | |
|  | useActionFilterMenu | `./src/pages/AuditPage/AuditFilter` | Need to double-check | Might already be covered via component tests |
|  | useResourceTypeFilterMenu | `./src/pages/AuditPage/AuditFilter` | Need to double-check | Might already be covered via component tests |
|  | useWorkspaceDuplication | `./src/pages/CreateWorkspacePage/useWorkspaceDuplication` | Need to double-check | Might already be covered via component tests |

Will fill out the rest of the list later. Searched via the regex:
```txt
export (function|const) use(?!State|Ref|LayoutEffect|Effect|Id|Query|Callback|Memo|Router|Theme)[A-Z][a-zA-Z]+
```


I've actually been trying to get better at testing lately, and these would be a really good way for me to practice. Could probably get all the files in the `.hooks` folder done this weekend.

**Comment by Parkreiner** [comment]
Update: even just the main `./hooks` directory was too much to do in one day. I've been trying to fix tests and actual functionality as I go (don't want to test against bad functionality), but I made decent progress. Aiming to get a PR for `useClipboard` opened by the end of today, too

**Comment by Parkreiner** [comment]
#12248
`useClickableTableRow` might require a lot more untangling than I thought

**Comment by Parkreiner** [comment]
Three more hooks down, and we have a better test helper for testing routing-based hooks. For simplicity, I'm going to split this issue up into four pieces in a few minutes.

Ben and I were talking the other day about me possibly taking a breather from Backstage after we launch, and doing a bunch of testing and bug-fixes in core. Happy to do a bunch of hook work when that happens

**Comment by kylecarbs** [comment]
There are a lot of separated issues for this, so I'm going to close out this gigaissue. @Kira-Pilot feel free to reopen if you disagree!

**Comment by Kira-Pilot** [comment]
@Parkreiner just a heads up - if there's anything in this ticket that we need, can we move into the child issues?
