### ISSUE TITLE
Allowing templates to have 2 provisioners and choosing which provisioner to use

### ISSUE THREAD

**Issue by ssncoder** [coder/coder#11424]
There's the concern of having 3 different provisioners for 3 different accounts which would result in needing 3 templates. Ideally would like to have 1 template.

**Comment by matifali** [comment]
We do have a similar request to make provisioners choice #5979.
Is this different?

**Comment by spikecurtis** [comment]
I think this dupes #5979 so closing in favor of that issue which has a lot of discussion and context.
