### ISSUE TITLE
Automate SSO group sync with SCIM

### ISSUE THREAD

**Issue by ssncoder** [coder/coder#11425]
automate when a new group is created in Microsoft Entra, the group is immediately created in Coder, without having to wait for a login event to trigger the group creation.

**Comment by bpmct** [comment]
From Colin:

> We don't currently support groups in SCIM, but it would probably be an easy add.

**Comment by bpmct** [comment]
No plans do this at this point, we just haven't heard the request much as the log-in seems to work fine for deprovisioning groups from most users. We have an internal issue we're tacking
