### ISSUE TITLE
Arrow keys are not working inside workspace (Ubuntu) via `coder ssh` on Windows client (Windows 11 VM)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11435]
Arrow keys are not working inside workspace (Ubuntu) via `coder ssh` on Windows client (Windows 11 VM).

Here are the steps to reproduce the issue:

1. Created a Windows 11 VM on Parallels
2. Installed Coder and authenticated
3. From Windows Terminal PowerShell, ran `coder ssh main` (an Ubuntu instance)
4. The arrow keys are completely dead in multiple shells (zsh and bash) and in a curses-based app

Expected result:

Arrow keys should work inside the workspace via `coder ssh` (e.g. navigate shell history with up/down arrows).

Other observations:

- When using OpenSSH (`ssh coder.main`), the keys work in the above scenarios
- Linux commands that can detect color capability, like `ls`, aren't outputting colors (needs verification)

**Comment by kylecarbs** [comment]
@mafredri is this still a thing? This seems pretty high prio if so... I assume we just need to set some terminal mode to fix, right?

**Comment by mafredri** [comment]
@kylecarbs Most likely fixed by #12990, but I haven't verified.

**Comment by kylecarbs** [comment]
Let's close this out for now then. If someone else reports we open again!
