### ISSUE TITLE
bug: JetBrains Gateway session count metric not returned for K8s pod, VM workspaces

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11460]
the session count metric for JetBrains at the `/api/v2/deployment/stats` endpoint is returned for Docker container-based workspaces, but is not returned for pods, VM workspaces. associated Prometheus metric is `coderd_agentstats_session_count_jetbrains`

a customer is currently experiencing this on `2.5.1`. i've reproduced on `2.6.0`.

**Comment by sreya** [comment]
closed by https://github.com/coder/coder/pull/11653
