### ISSUE TITLE
☂️ Example Templates

### ISSUE THREAD

**Issue by matifali** [coder/coder#11466]
We have a variety of [example templates](https://registry.coder.com/templates) covering major clouds, docker, Kubernetes, and nomad. 

It would be nice to have example templates for,

- [ ] Oracle Cloud
- [ ] IBM Cloud
- [ ] Linode
- [x] #10401
- [ ] Alibaba Cloud
- [ ] Hetzner Cloud
- [ ] Vultr
- [ ] Civo
- [ ] Proxmox VMs
- [ ] VMware vSphere VMs
- [x] LXD/Incus LXC containers
- [ ] Windows Containers

Contributions are welcomed.

> [!Note]
> Contributions are welcomed. Coder templates are written in terraform [hcl](https://developer.hashicorp.com/terraform/language/syntax/configuration).

**Comment by Ghvinerias** [comment]
Would love to see proxmox LXC template as a template. been working on it for a while now but some things are still fuzzy, since i'm still new to terraform.

**Comment by matifali** [comment]
@Ghvinerias it would be cool if you can contribute your efforts in the form of a PR.

**Comment by kylecarbs** [comment]
I'd rather us have specific issues for specific template types that are highly requested so we can gauge upvotes!
