### ISSUE TITLE
Workspace Autostop settings displaying incorrect value when template is updated

### ISSUE THREAD

**Issue by janLo** [coder/coder#11471]
We have a template with a three day autostop timer. Originally, this was only 24h.

Someone in our team created a workspace before we prolonged this. It appears that this timeout did not change for him (the WS was stopped after 24h). A manual adjustment (even as Owner) was also not possible because custom timeouts were not allowed for the template.

Now he did an update of his workspace and has inconsistent timeout settings in the UI:
- The Dashboard reports the 72 hours:
![Screenshot_20240108_100920](https://github.com/coder/coder/assets/96146/dcd2b6b5-6b25-43c3-83b1-c63ad2350c19)

- The Settings report 24 hours:
![Screenshot_20240108_101150](https://github.com/coder/coder/assets/96146/a6f05e2a-0086-46f5-82bb-4f51a2c1faf3)

Which one is correct, and how can this be aligned?

The settings in the template look like this:
![Screenshot_20240108_101258](https://github.com/coder/coder/assets/96146/26242187-ace9-491e-9833-1f1576419b8f)

Another question: How can I as an owner change the autostop settings for all Workspaces of a template after adjusting the value in the template (and not allowing custom values) without having to recreate all WS?

Thank you!

**Comment by stirby** [comment]
@janLo I am unable to reproduce the issue where template-level Autostop doesn't propagate to workspaces. 

The intended behavior is:
- Template Autostop is changed
- Workspace restarts
- Workspace Autostop should be updated to template setting

What version are you on?

**Comment by stirby** [comment]
Ah I see the issue. The workspace settings will display the user-configured Autostop hours, but the **template level autostop will be used**. So this is purely a visual bug. We can fix how this is displayed in the workspace settings. 

Also, the next release will also include improved visibility on when a workspace will start. Here I've overridden a workspace whose Autostop was set at 24 hours with the template setting of 4 hours: 

<img width="692" alt="Screenshot 2024-03-07 at 2 04 41 PM" src="https://github.com/coder/coder/assets/58410745/e54a46cc-c7f1-4ed4-8fd9-a166a716045f">

**Comment by stirby** [comment]
@sreya marking `must-do` per discussion.

**Comment by Kira-Pilot** [comment]
**sprint planning notes**
If you update the template autostart, it updates all workspace TTLs but doesn't update the setting that controls the TTL.
