### ISSUE TITLE
refactor: healthcheck: move message declarations to a single file

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#11493]
nit: maybe we should move all messages to a single file

_Originally posted by @mtojek in https://github.com/coder/coder/pull/11490#discussion_r1444650874_
            
Refactor existing healthcheck package and extract our existing messages to the `healthcheck/health` package.

**Comment by kylecarbs** [comment]
@johnstcn feel free to reopen if you feel it's important we do this! Just tryna keep the tracker clean.
