### ISSUE TITLE
☂️ Scheduling Stabilization

### ISSUE THREAD

**Issue by stirby** [coder/coder#11503]
Umbrella issue for stabilizing scheduling functionality and documentation.

Feature Requests
- [x] #2028
- [x] #11455
- [ ] #9775 
  (Should come after #11990)
- [ ] #10183

Docs Improvements
- [x] #11496

Workspace/Template scheduling not synced/stable
- [x] #11471
- [x] #10636
- [x] #10930
- [x] #10931
- [x] #11383
- [x] #11677
- [x] #11812
- [x] #11990

**Comment by matifali** [comment]
@stirby, I added a few more related issues.

**Comment by johnstcn** [comment]
"Last Used At" versus "Deadline" seems to be a source of potential confusion (see: https://github.com/coder/coder/issues/11986)

**Comment by kylecarbs** [comment]
Closing because we're not doing gigaissues anymore, and this is mostly complete based on the attached issues.
