### ISSUE TITLE
ImagePullBackOff

### ISSUE THREAD

**Issue by nikhil-phadke31** [coder/coder#11527]
I have created one Privete GKE cluster and followed all the steps mentioned in the given Docs.
https://coder.com/docs/v2/latest/install/kubernetes
But still, I'm getting Error: Back-off pulling image "ghcr.io/coder/coder:v2.6.0"

**Comment by MrPeacockNLB** [comment]
Is outbound traffic protected with a firewall? If so make ghcr.io domain accessible from inside your private cluster

**Comment by kylecarbs** [comment]
Seems like this is an infrastructure issue. Let me know if we can help!
