### ISSUE TITLE
ssh'ing to stopped workspace did not start it

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#11522]
A user ssh'ing to their stopped workspace received this output:

```
myuser@~]$ ssh coder.myuser
Workspace was stopped, starting workspace to allow connecting to "myuser"...
Connection timed out during banner exchange
```

The workspace however did not show any start attempts. They retried with `coder ssh myuser` and it did trigger a workspace start.

**Comment by kylecarbs** [comment]
This seems like an intermittent network issue, I'm not sure we should add a retry to fetching the banner, because then we'd wanna retry all network requests!

**Comment by mattlqx** [comment]
The issue is that ssh'ing to the alias didn't trigger the workspace start like the message said. Verified by looking at the workspace history. But using `coder ssh` did.
