### ISSUE TITLE
Disable screen startup message

### ISSUE THREAD

**Issue by code-asher** [coder/coder#11557]
There is a message that shows in the bottom left corner when starting screen via the web terminal that appears for about five seconds.  It makes it look like the terminal is still loading because the prompt will not be showing during this time although you can type and the message will be dismissed and the prompt will appear.  We should disable this message so the prompt appears right away.

Or if screen has a way to force it to display the prompt even when the startup message is showing, that would be reasonable too.

**Comment by matifali** [comment]
closing in favour of #11872
