### ISSUE TITLE
bug: can not authenticate GitHub external auth

### ISSUE THREAD

**Issue by matifali** [coder/coder#11577]
Can not authenticate GitHub external auth:
datadog [logs](https://app.datadoghq.com/logs?query=host%3Agke-dogfood-v2-cool-pool-095811aa-8r0k.c.coder-dogfood-v2.internal%20service%3Acoder%20container_id%3A9f10dd5fc6e0f578aee5d8485308d395f1c50c15b682361ba98a0473f0e28aec%20filename%3A0.log%20&cols=host%2Cservice&context_event=AYz439QQAAB8ljzSQadtrQBn&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAYz44AtmA3XsewAAAAAAAAAYAAAAAEFZejQ0QTZsQUFBa3VQdEdiYjFpdFFCMwAAACQAAAAAMDE4Y2Y4ZTAtMGI2Ni00YjM3LTg0ZmItNDA4YjY2NDkxZTkx&viz=&from_ts=1704982162755&to_ts=1704982481767&live=false|logs),

```console
response_body
{"message":"Failed to authorize device.","detail":"invalid character 'd' looking for beginning of value"}
status_code
500
```

[Slack Message](https://codercom.slack.com/archives/CJURPL8DN/p1704983063691329?thread_ts=1704983063.691329&cid=CJURPL8DN)

My and @johnstcn guess that it is also caused by #10853, and a possible solution can be to handle the error response better.

The windows have an ever-spinning spinner.

[image](https://github.com/coder/coder/assets/10648092/a5f3db91-2b55-4369-9a60-89b6d13daaa7)

**Comment by johnstcn** [comment]
possible duplicate of https://github.com/coder/coder/issues/10853

**Comment by Emyrk** [comment]
Fixed here:https://github.com/coder/coder/pull/11554

The error message was not valid json. We should improve this further though, I am unsure what the correct status code is.

**Comment by matifali** [comment]
Can not reproduce anymore.
