### ISSUE TITLE
bug: workspace creation page buttons misalignment and not able to create workspace

### ISSUE THREAD

**Issue by matifali** [coder/coder#11570]
### How to reproduce

1. Login to dev.coder.com
2. Create a workspace with Coder in Coder
3. Click on Login with Artifactory or GitHub

> [!Note]
> A refresh does not help and just restarts the loop

![image](https://github.com/coder/coder/assets/10648092/f604c4de-0bd0-4033-9a68-7768fc851483)

**Comment by matifali** [comment]
Signing into GitHub from Settings --> External Authentication is not working either. Could be related to #10853 
![image](https://github.com/coder/coder/assets/10648092/06ce4735-87b6-49ea-86df-ee22e3095767)

**Comment by BrunoQuaresma** [comment]
Some findings:

About the second error... Looks like the backend is not sending the right response. After authenticate with JFRog I'm receiving this payload from the endpoint `/api/v2/templateversions/:version-id/external-auth`.

```json
[
    {
        "id": "jfrog",
        "type": "jfrog",
        "display_name": "JFrog Artifactory (https://jfrt.cdr.dev/)",
        "display_icon": "/icon/jfrog.svg",
        "authenticate_url": "https://dev.coder.com/external-auth/jfrog",
        "authenticated": false
    },
    {
        "id": "github",
        "type": "github",
        "display_name": "GitHub",
        "display_icon": "/icon/github.svg",
        "authenticate_url": "https://dev.coder.com/external-auth/github",
        "authenticated": true
    }
]
```

When the JFrog login is displayed, I see the following response from the endpoint `/api/v2/external-auth/jfrog`:
```json
{
    "authenticated": true,
    "device": false,
    "display_name": "JFrog Artifactory (https://jfrt.cdr.dev/)",
    "user": null,
    "app_installable": false,
    "installations": [],
    "app_install_url": ""
}
```

Maybe there is some "sync" bug?

**Comment by BrunoQuaresma** [comment]
Click on "Reauthenticate" fixed the issue. Thanks @f0ssel for this but it stills look like a bug 🤔

**Comment by BrunoQuaresma** [comment]
cc.: @Emyrk

**Comment by Emyrk** [comment]
@BrunoQuaresma it happens when a 429 or 404 is sent back. The page doesn't interpret the error.

**Comment by BrunoQuaresma** [comment]
Not sure if I got it, when I'm on the page, Im getting a 2xx response 👀. I will take a look into it again

**Comment by matifali** [comment]
Can't reproduce anymore.

**Comment by Emyrk** [comment]
I can trigger this failure. I made a PR to add a feature to the test idp: https://github.com/coder/coder/pull/12365

Steps:
1. Run fake idp: `go run ./scripts/testidp/main.go --device-flow --429=device`
2. Run coderd with fake as external auth
3. Try to login. You will see a spinner, and a failure in the network logs.

![Screenshot from 2024-02-29 08-51-47](https://github.com/coder/coder/assets/5446298/39baf4e1-716d-4e3d-8889-1dd12b1c1319)

**Comment by BrunoQuaresma** [comment]
Is this on the login page or the create workspace page?

**Comment by Emyrk** [comment]
@BrunoQuaresma Any page where you can login into an external auth. So it can be triggered through the workspace or external auth page.

**Comment by Emyrk** [comment]
@BrunoQuaresma I will do so now.

**Comment by Emyrk** [comment]
Closed in favor of https://github.com/coder/coder/issues/12366
