### ISSUE TITLE
External auth fails silently without AuthURL set

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#11589]
If AuthURL is **not** set, we always return `true` for the validate function. This was causing our jfrog tokens to fail silently.

We need to implement a solution to prevent this kind of silent error.

**Comment by matifali** [comment]
I think you mean unset?

**Comment by Emyrk** [comment]
Closed by https://github.com/coder/coder/pull/11762

ValidateToken now returns `false` for expired tokens.
