### ISSUE TITLE
Allow unix path for --http-address

### ISSUE THREAD

**Issue by nolange** [coder/coder#11592]
Please add an option to use an unix socket as internal endpoint.

I would like to run code via rootless podman/docker and use a reverse Proxy (nginx).

Using this via IP network means a userspace network stack will emulate a network interface and the connection to the real socket. An alternative would be to use a unix socket that is mapped into the containers (coder and potentially nginx).
The upside would be better isolation and performance.

**Comment by kylecarbs** [comment]
We will do this!
