### ISSUE TITLE
`coder ssh` does not update worskpace to latest template version upon start

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11595]
with workspaces set to auto-update to latest template version, `coder ssh` will start the workspace, but then (correctly) fail, because the non-admin user is attempting to build a workspace with an outdated version:

```
insert workspace build
cannot use non-active version: unauthorized: rbac: forbidden
```

`coder ssh` should auto-update the workspace template version, as done in the UI.

**Comment by mtojek** [comment]
This issue will need more love...

UI, and probably CLI too, ignores the template option `Require workspaces automatically update when started`, and `Start` button is active.
