### ISSUE TITLE
Support setting `supportLinks` as env variables

### ISSUE THREAD

**Issue by matifali** [coder/coder#11628]
We should be able to set SupportLinks as individual ENV variables in `coder.env` as follows,
```env
CODER_SUPPORT_LINK_0_NAME="On-call :fire:"
CODER_SUPPORT_LINK_0_TARGET="http://on-call.example.internal/"
CODER_SUPPORT_LINK_0_ICON=":bug:"
CODER_SUPPORT_LINK_1_NAME="😉 Getting started with Go!"
CODER_SUPPORT_LINK_1_TARGET="https://go.dev/"
CODER_SUPPORT_LINK_1_ICON=":chat:"
```

We should revert #11612 once we support this. It is not recommended to mix `config.yaml` and Helm chart values.

**Comment by MrPeacockNLB** [comment]
this sounds much cleaner. Thumbs up

**Comment by mtojek** [comment]
I have touched support links recently, so let me see where is the problem...

**Comment by mtojek** [comment]
@matifali I researched this problem, and Coder lacks the logic to understand array items (`..._0_NAME`, `..._1_NAME`) [here](https://github.com/coder/coder/blob/1f0e6ba6c6163fb3155a81f1129cead3d3b80f8a/cli/clibase/option.go#L264).

This might be relatively tangled logic with variable detection, reflection, and determining the schema, so I was wondering if we could use a more flexible, future proof form:

```
export CODER_SUPPORT_LINKS='[{"name":"aaa", "target":"bbb", "icon":"ccc"},{"name":"ddd", "target":"eee", "icon":"fff"}]'
```

Let me know your thoughts!
