### ISSUE TITLE
Coder CLI: only push templates if there are changes 

### ISSUE THREAD

**Issue by Conor-Behard333** [coder/coder#11642]
I want to implement a CI/CD pipeline for pushing templates to coder. I have a repository which stores all the templates for coder and a Gitlab pipeline which pushes them to coder.  

However, currently, the coder cli will push a new version of the template even if there are no changes to the template. Having a feature in the cli that can either: 
- check for differences in the current template (if one exists) 
  OR
- adjust the current push function so it won't push to coder if there are no changes.

This would make the pipeline far more usable

**Comment by kylecarbs** [comment]
Seems like it'd be really easy for us to do this... we can just ignore mtime when creating archives, and then compare the hash of the resulting archive.

**Comment by matifali** [comment]
@Conor-Behard333 why you don't prefer doing it in CI? So would advise checking diff and then conditionally pushing the templates that are changed.

**Comment by Conor-Behard333** [comment]
Ahh didn't think about doing git diff!

Would definitely see it being easier tho if coder only pushed when there are changes. As I don't really see the point in pushing identical templates which then notifies users that workspaces need updating even tho it's the same. 

However, git diff seems like it would also resolve this issue so it's more up to you lot if you think the changes should be made.

**Comment by matifali** [comment]
@Conor-Behard333 For this to work, the Coder must first pull the template, extract it, and compare files. We do not plan to add this anytime soon, as a CI job can do that and only use `coder push` if required.

**Comment by Conor-Behard333** [comment]
Yeah no worries I managed to get a working pipeline using git diff. Which seems to be working how I wanted it to. Thank you for the help!

**Comment by joshzarrabi-picnic** [comment]
Hi, Jumping in here. I would really like this behavior as well. It would make CI simpler, but also, if someone just pushes a template for whatever reasons without changes I really don't think everyone should think they need to update their workspaces.
