### ISSUE TITLE
Refactor `agentssh` testing

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11650]
Right now we test `agentssh` functionality in a few places, `cli`, `agent` and `agentssh` itself, perhaps more. Ideally we would move all (or most) tests into `agentssh` where we test both client and server behavior.

We may also want to refactor logic from `cli` into exported methods in the `agentssh` package, so the code is more re-usable and testable.

This came up in https://github.com/coder/coder/pull/11631#discussion_r1453837317.

**Comment by stirby** [comment]
@mafredri closing because stale, feel free to re-open.
