### ISSUE TITLE
show deprecation message on the template page

### ISSUE THREAD

**Issue by matifali** [coder/coder#11660]
We should show the deprecation message on the template page to guide users to go to the new template.

![image](https://github.com/coder/coder/assets/10648092/b357b70d-a7af-4e35-9c66-a282cb9fd0bf)

**Comment by jaivardhan-bhola** [comment]
Can I work on this?

**Comment by jaivardhan-bhola** [comment]
Can I please get the link of the new template?

**Comment by BrunoQuaresma** [comment]
Hey @jaivardhan-bhola sorry for the delay and I appreciate your availability to work on this.

I'm going to work on this right now but feel free to reach out if you have any questions or want to take a look at other `good-first-issues` issues https://github.com/coder/coder/issues?q=is%3Aopen+is%3Aissue+label%3Agood-first-issue
