### ISSUE TITLE
light theme: web terminal white text on white background

### ISSUE THREAD

**Issue by matifali** [coder/coder#11662]
Raise your hand if you can read `hello world`
![image](https://github.com/coder/coder/assets/10648092/f1d7b903-b3b9-4d8b-afc7-bba07ddf513c)

**Comment by aslilac** [comment]
> Raise your hand if you can read hello world

This is a trick, because you typed "hello white" :^)

**Comment by mafredri** [comment]
Also ran into this 😄

<img width="900" alt="image" src="https://github.com/coder/coder/assets/147409/8179056e-cb14-44c5-9d58-5c3ffa0da2af">

This is hard-mode (ultimately a separate terminal color setting might make sense).
