### ISSUE TITLE
WSProxies dropdown shows when only one option is available

### ISSUE THREAD

**Issue by stirby** [coder/coder#11678]
Workspace proxy dropdown is available in deployments where only one option (default) is available. Leading to an arbitrary window insinuating control that does not exist.  We should disable this dropdown in this case.

![wsproxy](https://github.com/coder/coder/assets/58410745/06e92d35-05c5-43c7-9fc6-d19e59c7a503)

A customer pointed this out to us.

**Comment by stirby** [comment]
@matifali I like the idea of linking to docs instead of not showing it. 

We could change the dropdown to show a brief explanation and link?

**Comment by matifali** [comment]
It would need some frontend refactoring to replace links to settings with docs.

**Comment by stirby** [comment]
I see no reason for barring that information behind the condition of poor latency. It could just be another avenue to learn about workspace proxies?

**Comment by BrunoQuaresma** [comment]
Wondering if we should wait for more customer feedback before doing this 🤔

I want to try to void adding one more conditional for something that is not a blocker or making things hard to use IMO.
