### ISSUE TITLE
Customizable error page, when OIDC signup is disabled.

### ISSUE THREAD

**Issue by ssncoder** [coder/coder#11679]
Would like a customizable error page, when OIDC signup is disabled.

> [!NOTE]
> See product requirements in the comment below

**Comment by kylecarbs** [comment]
@ssncoder, could you add some additional details on the need here? I'm not exactly sure what this means.

**Comment by sempie** [comment]
Currently when a non-coder user tries to login via OIDC they get a raw JSON error message saying OIDC signups not enabled.  The request is to have this error message output as part of the login page, or at least a coder web UI page rather than raw JSON.

**Comment by bpmct** [comment]
To reproduce:

1. Set up a Coder deployment and set https://coder.com/docs/v2/latest/cli/server#--oidc-allow-signups to false
2. Try to log in with a new OIDC user
3. Observe that there is a plaintext page with JSON (not particularly professional)

Product requirements:

- Add server flag to allow people to set a custom error message that renders on the sign in page
- Custom error message should include markdown to link to an internal wiki

e.g.

```sh
CODER_OIDC_SIGNUPS_DISABLED_MESSAGE="Coder is in early access mode. To request access, fill out [this form](https://internal.form.com)
```

**Comment by matifali** [comment]
@bpmct Instead of adding another option for customization, we can also add a generic error page that says Signups are disabled. Please get in touch with your Coder administrator.
![image](https://github.com/coder/coder/assets/10648092/4298d8b0-65ea-4857-895a-55d7003bc6bf)

**Comment by bpmct** [comment]
@matifali I'm in favor of making it customizable because often Coder is deployed centrally to thousands of users, who may not be aware who the coder admin is or how to contact them. Similar to how we have custom error messages for the agent and support links, I think this is a good opportunity for folks to have a custom message.
