### ISSUE TITLE
Feature: Support ZIP files to upload/download templates

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#11687]
- Better support on JS libraries than writing our own tar library
- Maybe a better experience for Mac and windows since those support Zip natively

**Comment by MrPeacockNLB** [comment]
Thinking about this feature we may consider that it may be useful to protect this via RBAC role. Even showing the whole template should be protected as well.

**Comment by mtojek** [comment]
I like this idea, so I'm going to review what we should do to support .zip files.

**Comment by mtojek** [comment]
@BrunoQuaresma I think that you can try to experiment with .zip files. Upload API accepts it, but to download a .zip, you can to append query param `?format=zip`.

**Comment by BrunoQuaresma** [comment]
That is awesome. Ty!

**Comment by mtojek** [comment]
@BrunoQuaresma Did you find some time to play with it?

**Comment by mtojek** [comment]
Moving to _Blocked_ until we have FE capacity to follow up with it.

**Comment by BrunoQuaresma** [comment]
Zip upload is supported by the UI now. I need to evaluate changing the template editor to use zip more carefully since this part of the code is a bit fragile at the moment. 

https://github.com/coder/coder/issues/12346
