### ISSUE TITLE
Option to auto-retry workspace auto-start failures

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#11689]
We sometimes reach an AWS capacity limit when many folks share the same time for their auto-start schedule. It would be desirable to be able to configure a retry limit and delay in this circumstance so that when the user does end up using their workspace, they don't have to wait for it from a manual start. And multiple attempts can increase the probability of it finding capacity. (We have some automation that tries to maintain a capacity buffer with capacity reservations that runs pretty frequently.)

**Comment by kylecarbs** [comment]
@mattlqx, do you have insight into the average workspace start time? Mostly curious because limiting concurrent builds seemingly could also fix this.

**Comment by mattlqx** [comment]
Sure, usually less than 60 seconds for a start. I think some sort of retry is better than limiting parallelization on these as I'd probably want to make the retry interval something like 5 or 10 minutes since capacity isn't available immediately.
