### ISSUE TITLE
capture "full name" from the SSO identity provider + "new user" form

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11704]
We recently added support for a "full name" in Coder, which is in the account settings and passed into Terraform. #11639 #11583. Could we also add support for the identify provider (OIDC or GitHub) from a configurable scope typically [name](https://auth0.com/docs/secure/tokens/id-tokens/id-token-structure#sample-id-token)?

Could we also add support for optionally specifying the full name in the "new user" form?

<img width="511" alt="Screenshot 2024-01-19 at 9 43 06 AM" src="https://github.com/coder/coder/assets/22407953/09070624-fd64-47c5-a7b1-a90e7a56b846">

**Comment by michaelbrewer** [comment]
This would be great to get the "DisplayName" from something like MS Entra Id user profiles to populate as this is later on used for the commit messages. 

From a user experience point of view, onboarding with no additional steps is ideal.

**Comment by michaelbrewer** [comment]
@bpmct I would not mind working on this feature? Or is this on the roadmap for completion.

I would also note that User Porfiles should be readonly for OIDC users.

**Comment by bpmct** [comment]
Hey @michaelbrewer. We'll be working on this as part of our "manage coder via IaC + identify providers" effort this quarter

**Comment by michaelbrewer** [comment]
This would be awesome. And potentially allow more fields to be mapped into coder like the profile photo, display name, city etc. 

This helps various use case:
- display name (for git author)
- city (to help identify which region the user belongs to)
- photo (for easier identification)

Not all providers have all of these or requires mappings.

**Comment by johnstcn** [comment]
@bpmct should we break out the second piece

> Could we also add support for optionally specifying the full name in the "new user" form?

into a separate ticket?

**Comment by bpmct** [comment]
Closing as completed. https://github.com/coder/coder/issues/13490 can be used to track the new user form

**Comment by michaelbrewer** [comment]
Awesome will test out "CODER_OIDC_NAME_FIELD" mapping when it is available.
