### ISSUE TITLE
better indication when a workspace is "active"

### ISSUE THREAD

**Issue by stirby** [coder/coder#11710]
Currently, it's not entirely clear in the UI when a workspace is actively being used. Having a clearer status in the workspace page will help users understand when their 1-hour bumps (or inactivity timer in the future) is going to push the workspace's TTL. 

The top banner should show a new box indicating whether or not users are active in their workspace. 

Having a status that displays (Active | inactive) may cause confusion when the coder agent is connected but the user is not inside their workspace. We need to be clear on the distinction between "activity" from the user and the agent with this change. To mitigate this confusion, we could include the method of connection (e.g. SSH, VSCode desktop, code-server).   
  

<img width="685" alt="active-connected" src="https://github.com/coder/coder/assets/58410745/3d4d3ba0-23c2-49aa-b6d0-01e3b5823530">

---

Waiting until next sprint (01/28) to do this per @sreya.

**Comment by aslilac** [comment]
<img width="586" alt="Screenshot 2024-01-26 at 1 00 56 PM" src="https://github.com/coder/coder/assets/418348/cce0b704-fd02-4f40-b8fb-e1621354a422">

Maybe something like this?
