### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11711]
Some customers may want a color theme that aligns with their branding. To reduce complexity, the admin should only set up to 10 colors (ideally less), and the theming engine figures out the rest.

**Comment by stirby** [comment]
This seems like a feature with a lot of hidden difficulty. Does this complicate our FE testing? How can we ensure the visibility of UI elements if admins can configure their colors? Are we letting them configure 10, then interpreting niche colors?

I think the customers that want custom UIs will usually have a team to build their own front end. wdyt @bpmct?

@ammario also had some opinions I believe.

**Comment by ammario** [comment]
Issues like https://github.com/coder/coder/issues/13370 will become commonplace and undetectable to us. I feel strongly against us introducing this kind of UI complexity with our existing frontend resourcing.
