### ISSUE TITLE
Active VSCode Editor counter is incorrect

### ISSUE THREAD

**Issue by ntimo** [coder/coder#11727]
Hello Coder team,
its seems like the "Active Connections" counter for vscode is incorrect. I am the only user of the coder instance and the workspace is stopped + vscode on my computer is closed. Therefore I wonder how the count can be at 3. For my understanding it should be at 0.

![image](https://github.com/coder/coder/assets/6145026/a16cbf3d-ca5d-46da-83f6-c6d58db6704b)

if you can help to debug this somehow please let me know. Restarting coder does not solve this. I am running 2.7.0

**Comment by matifali** [comment]
cc: @code-asher

**Comment by code-asher** [comment]
Does this happen even if you wait around ~5 minutes?  I think the default refresh interval might be around that long.

Did the workspace shut off while connected to VS Code?  I wonder if maybe a workspace shutting down does not reset its counters.
