### ISSUE TITLE
Wrong proxy responses (mixed workspaces)

### ISSUE THREAD

**Issue by fcsonline** [coder/coder#11737]
Today we have updated our Coder instance to version `v.2.7.0` and we have faced a weird proxy redirection in many of our workspaces. Some workspace assets were delivered from the wrong workspace. We don't have much information because we restored the previous version, but it looked that the first request was cached somehow and shown in other independent workspaces.

The scenario looks a bit more or less like this:

*Workspace `foo`:*
- Requests `http://frontend--foo.example.dev/something.json` returns `{ "foo": true }`

*Workspace `bar`:*
- Requests `http://frontend--bar.example.dev/something.json` returns `{ "foo": true }`

Did someone else face this?

We had to roll back to `v.2.6.0` to make it work again.

**Comment by beagleknight** [comment]
Can this https://github.com/coder/coder/issues/11732 be related?

**Comment by embold-tyler** [comment]
We're also getting weird proxy misdirects on v2.7.1. We're running the docker image behind an apache reverse proxy. Random and doesn't happen for everyone all the time.

https://webapp--main--workspace1--user1.example.app/  > https://webapp--main--workspace2--user2.example.app/

**Comment by coadler** [comment]
Fixed by https://github.com/coder/coder/pull/11789

**Comment by fcsonline** [comment]
Awesome! Thanks for this fast bug fix! 🎉
