### ISSUE TITLE
bug: Path-based VS Code port forwarding broken in v2.7.1

### ISSUE THREAD

**Issue by JensHeise** [coder/coder#11754]
Hello,

it appears, as if maybe #11657 broke the path-based port forwarding inside VS Code Web.
The env var `VSCODE_PROXY_URI` was constructed correctly in v2.6.0 and before.

## Expected Behavior

VSCode starts with the correct env var `VSCODE_PROXY_URI` for path-based VS Code like this:
`https://coder.example.com/@USER/test.instance/apps/code-server/proxy/{{port}}`

## Actual Behavior

If I start a web app in the workspace the automated port forwarder in VS Code constructs a URL for a subdomain based app, like:
`https://{{port}}--instance--test--USER.coder.example.com/`

Since subdomain based routing is not an option for us, this breaks our VS Code setup.

## Steps to Reproduce the Problem

1. Setup template like described in documentation [here](https://coder.com/docs/v2/latest/ides/web-ides#code-server)
2. Switch to a path based app in template
3. Start workspace from template
4. Start VS Code browser
5. Start web application in VS Code

## Specifications

  - Version: v2.7.1
  - Platform: Linux
  - Subsystem: Ubuntu 22.04

**Comment by Emyrk** [comment]
Is there a chance this has been broken for longer?

This is the code that used to run:
https://goplay.tools/snippet/e8F6JWInwji

After seeing this issue, I think it is supposed to append the appropriate path like `https://coder.example.com/@USER/test.instance/apps/code-server/proxy/{{port}}`.

There is nothing in the old code that does that from what I can tell.

**Comment by Emyrk** [comment]
`VSCODE_PROXY_URI` has not changed in quite a few versions.

I have tested `code-server` and the proxy url `http://localhost:3000/@admin/workspace.agent/apps/code-server/proxy/3000` works.

Can you provide screenshots or network requests of what you are expecting vs what is happening?

**Comment by JensHeise** [comment]
Thanks for the quick response!
I'm really quite sure, that we did not have this behavior in 2.6.0. I will send you screenshots later, when I'm back home :)

**Comment by Emyrk** [comment]
Can you also provide your version of code-server?

**Comment by JensHeise** [comment]
Sure, here is our VS Code version:
```
code-server: v4.20.0
Code: 1.85.1
Commit: 0b84523121d6302fbe30eda7899ec3b81810748e
Date: 2023-12-18T20:21:20.879Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
```
We also already have a Renovate pull request for version v4.20.1 waiting...

As per your PR #11759 I also have no idea what's going on here, as testing it now, I get following result in the VS Code environment:
```
USER@test:~$ env | grep VSCODE
VSCODE_PROXY_URI=https://coder.example.com/
VSCODE_GIT_ASKPASS_NODE=/usr/lib/code-server/lib/node
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_IPC_HANDLE=/tmp/vscode-git-98a1136227.sock
VSCODE_GIT_ASKPASS_MAIN=/usr/lib/code-server/lib/vscode/extensions/git/dist/askpass-main.js
VSCODE_IPC_HOOK_CLI=/tmp/vscode-ipc-a1ecd5fd-2961-43d9-9791-fa5afdfdb3f2.sock
```

Here is a screenshot of the forwarded ports in code-server as well:
![image](https://github.com/coder/coder/assets/62468949/22eceac4-62de-4be0-b416-7362268e96d5)
Those links are obviously not working and earlier today, we had the subdomain based links in there. (I sadly don't have a screenshot of this)

I can 100% assure you that this was working as of v2.6.0 but I couldn't spot nothing in the changelog regarding this.

**Comment by Emyrk** [comment]
Another thing I noticed is you need to restart your workspace **and** share a new port to see the effects. Ports that were already listed in code-server do not have their urls updated. And workspaces already built do not update their env vars.

So if you are testing the latest PR, restart the workspace and open a new port.

**Comment by JensHeise** [comment]
We have 2 setups running with v2.7.1 at the moment: One with `CODER_WILDCARD_ACCESS_URL` unset and one with it being `*.example.com`

Values for `VSCODE_PROXY_URI` are:
Unset -> `https://coder.example.com/`
*.example.com -> `https://{{port}}--instance--workspace--USER.coder.example.com/`

Running v2.6.0 we had the `CODER_WILDCARD_ACCESS_URL` definitely set to `*.example.com`, while it was working.
We did not use the wildcard url, but had it configured to maybe tinker with it later.
After getting the described error yesterday, I removed the wildcard url from the configuration, thinking it could solve the problem.
Following that the `VSCODE_PROXY_URI` is set to plain `https://coder.example.com/`...

With our configuration we would need a database rollback to test it with v2.6.0 again, so we would like to avoid that if possible.
I can test the PR later on my local machine though!

**Comment by Emyrk** [comment]
No need to rollback, I'd rather just fix this going forward. 

From what I can tell, if it was working before, it was not intentional on the Coder side. Coder was configured to use subdomains for port forwarding, and it did not leverage code-server's proxy path before. We actually intentionally do not forward ports on path based apps, so code-server proxy path is a workaround.

All that being said, if `CODER_WILDCARD_ACCESS_URL` is set, you should be using the subdomain based port forwarding urls. They are safer from a security POV.

I will merge my PR as I got it working and had a few others confirm. The PR intentionally allows code-server to handle path based apps, rather than trying to dictate it from Coder itself.

**Comment by Emyrk** [comment]
@JensHeise When this is released, or before if you are able, let me know if you still have issues. 

And if the issues persist in the next release, feel free to reopen this and tag me :+1:

**Comment by bfqrst** [comment]
Any chance this is worth another bugfix release?

**Comment by JensHeise** [comment]
**Update from our side:** 
We got a workaround in place as of now, which sets the `VSCODE_PROXY_URI` env var to the path based URI.
``` terraform
resource "coder_env" "vscode_proxy_uri" {
  agent_id = coder_agent.instance.id
  name     = "VSCODE_PROXY_URI"
  value    = "${data.coder_workspace.me.access_url}/@${data.coder_workspace.me.owner}/${data.coder_workspace.me.name}.instance/apps/code-server/proxy/{{port}}/"
}
```

I've also tried to remove the env var completely as your fix does, but then VS Code redirected the port to `http://localhost:{{port}}`...
Maybe we do something vastly different or wrong compared to you, but with the workaround its working flawlessly!

**Comment by Emyrk** [comment]
> I've also tried to remove the env var completely as your fix does, but then VS Code redirected the port to `http://localhost:{{port}}`... Maybe we do something vastly different or wrong compared to you, but with the workaround its working flawlessly!

How did you remove the env var? I ask because Coder injects the env var when the agent is started. So you would have to unset it where you did your current workaround. Can you unset an env var from terraform?
