### ISSUE TITLE
2 workspaces of the same user with jupyterlab, both apps redirecting to first opened 

### ISSUE THREAD

**Issue by madhosoi** [coder/coder#11767]
Hi,
After upgrade to version 2.7.0 (also tested with coder-preview:latest), when I have 2 workspaces that have jupyterlab exposed, it seems the traffic of services is not redirected properly, e.g:
![image](https://github.com/coder/coder/assets/5636474/2ead0d39-b910-474b-8d3b-51618f9fdd21)

The behaviour is weird, the first jupyter is opened perfectly. The second is opening the content of the first one:
![image](https://github.com/coder/coder/assets/5636474/7e2a599c-e2c6-43f8-9a36-29fdf9543f4c)

Thanks!

_Originally posted by @madhosoi in https://github.com/coder/coder/issues/11672#issuecomment-1901865727_

**Comment by matifali** [comment]
cc: @Emyrk

**Comment by madhosoi** [comment]
Also reproduced in version 2.7.1
