### ISSUE TITLE
support `last_built_at` metric in the audit logs

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#11761]
in Coder v1, we exposed a `last_built_at` metric. a large customer of ours is using this to track platform usage. they are requesting for this to be included in the v2 audit logs.

please comment below if we have an equivalent metric via Prometheus or the API.

**Comment by bpmct** [comment]
Our API has this metric when you look up a workspace, but not via the audit log: 

https://coder.com/docs/v2/latest/api/workspaces#get-workspace-metadata-by-user-and-workspace-name

see `latest_build.created_at`
