### ISSUE TITLE
update Template variables can chose is to Promote version

### ISSUE THREAD

**Issue by glenn2wang** [coder/coder#11765]
when update the Template variables，coder will create a new version and set the new version to Promote

hope it can be chose is to set Promote

**Comment by matifali** [comment]
@glenn2wang, is it a bit unclear? Can you possibly add a screenshot or screenshot of what is happening and what you expect?

**Comment by glenn2wang** [comment]
<img width="587" alt="image" src="https://github.com/coder/coder/assets/12504766/727c47ca-bfa8-40ab-bfd1-88cccc5fd7de">

when update the the Template variables. like p1
coder will create a new version and set the new version to active ,like p2
<img width="1121" alt="image" src="https://github.com/coder/coder/assets/12504766/2551d865-b348-44a2-bb27-fc5ab05accc7">

**Comment by matifali** [comment]
If you are publishing templates from CLI, you can pass the `--activate=false` flag or if doing from dashboard just uncheck the publish button.
