### ISSUE TITLE
Update coder when starting a workspace leads to an orphaned workspace

### ISSUE THREAD

**Issue by btwatanabe** [coder/coder#11776]
Version: [`v2.7.1+66f119b`](https://github.com/coder/coder/commit/66f119bde8102e5808570eb2f5ec9f0481929e99)

When upgrading from 2.6.x to 2.7.1, I inadvertently started the upgrade via Helm before another workspace finished starting up. This led to a failed startup on the workspace, but attempts to retry the startup resulted in an error stating that the workspace already exists. The pod then had to be manually deleted using the kubctl cmd and then the workspace could be created using the UI. It's probably not a common problem for smaller teams, but I could see how this would happen too frequently on larger installs.

![image](https://github.com/coder/coder/assets/110203413/6d845468-39bd-402a-af15-4be1f3fefbf4)
![image](https://github.com/coder/coder/assets/110203413/1d9f230b-5157-4df6-ba7f-a00211bdc85b)

**Comment by matifali** [comment]
Duplicate of #10607
