### ISSUE TITLE
`arch` returned by `coder_provisioner` and what `coder_agent` expects don't match

### ISSUE THREAD

**Issue by matifali** [coder/coder#11782]
While running on a Raspberry Pi with armv7 architecture. A user reported this error. 
![image](https://github.com/coder/coder/assets/10648092/2a45f71a-47a2-41b4-a128-c744b8d5450e)

@bpmct could you try to reproduce on your Raspberry Pi?

Both workspace and Coder provisioner are running on Raspberry Pi. 

Manually changing `arch = armv7` for the `coder_agent` fixed the issue.

**Comment by johnstcn** [comment]
Need repro, would be good to know which model?

**Comment by matifali** [comment]
As per the docs, all Raspberry After 2 should be `arm64`. [Raspberry Pi 2](https://www.raspberrypi.com/products/raspberry-pi-2-model-b/) had an [armv7 architecture](https://developer.arm.com/Processors/Cortex-A7).

**Comment by johnstcn** [comment]
My bad, it's actually an armv6 model B that I have.

**Comment by johnstcn** [comment]
No joy with QEMU armv7 emulation just yet (followed [these steps](https://www.willhaley.com/blog/debian-arm-qemu/) to set up a Debian 12 armhf VM). Will see if I can get my hands on some real hardware.

**Comment by johnstcn** [comment]
https://go.dev/wiki/GoArm#supported-architectures

```
GOARCH=arm
GOARM=7
```
