### ISSUE TITLE
Coder (specifically tailnet) is using a lot of memory with 2000 and 30% receiving web terminal traffic (potentially OOM killed because of it)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#11797]
With 2000 workspaces and sending web terminal traffic to 30% of them (600), we see that coder memory usage shoots up.

The OOM kill did not happen, however, before we also started a concurrent workspace app proxying test. But I suppose web term and workspace apps function on much the same principle.

<img width="1065" alt="image" src="https://github.com/coder/coder/assets/147409/59707d7a-3bd1-4bb8-b1c2-6bf24eb0b636">

From the heap, we can observe that a lot of this memory is allocated by WireGuard:

<img width="300" alt="image" src="https://github.com/coder/coder/assets/147409/1021cb03-79f0-4b27-9713-83fd825c3d72">
<img width="300" alt="image" src="https://github.com/coder/coder/assets/147409/1cbda451-9363-4732-ab5c-63cc24787575">

IIRC, single tailnet was supposed to help with this. So I'm wondering if this is a regression?

// ping @coadler @spikecurtis

**Comment by coadler** [comment]
Was this run on main? https://github.com/coder/coder/pull/11789 has a bugfix that definitely has a negative performance impact, but that should be resolved by https://github.com/coder/coder/pull/11810.

**Comment by mafredri** [comment]
@coadler nah, this was v2.7.1, I can try running against `main` tomorrow to see if it performs any better. 👍🏻

**Comment by spikecurtis** [comment]
I don't see how #11789 would affect Wireguard, since Wireguard is just pushing IP (layer 3) packets and HTTP connection caching is TCP (layer 4). Also, the web terminal uses a single websocket, so caching the connection won't help.

**Comment by mafredri** [comment]
I gave https://ghcr.io/coder/coder-preview:main-2.7.1-devel-3d76e1b55 a try, and with 100 web terminal connections it seemed that memory usage had been improved, but after another try with 500 web terminal connections, we ran out of memory again (16 GB limit) with two coder instances. In other words, we went from 2GB used to >16 GB + OOM.

I still believe there's been a regression since we initially tried out the `single_tailnet` experiment. There we could handle 500 web terminals with ease and only 4 GB of RAM.

**Comment by spikecurtis** [comment]
Perhaps we aren't correctly detecting the agents as not-legacy.

I propose we don't chase our tails just yet because I have a [PR to remove `wsconncache` entirely](https://github.com/coder/coder/pull/11816), which moots the legacy vs not legacy question.
