### ISSUE TITLE
exp/scaletest: add configurable retry during workspace creation

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#11801]
Workspace creation may fail for various reasons. Add a configurable retry option to scaletest workspace creation that will retry the build up to N times before marking the test as failed.

cc @mafredri

**Comment by mafredri** [comment]
👍🏻

In addition, I was thinking we would also add a "make sure exactly this many workspaces exist based on this template". This will help if creation fails mid-way irrespective of the retry, consecutive runs don't need to change anything.

**Comment by mafredri** [comment]
> In addition, I was thinking we would also add a "make sure exactly this many workspaces exist based on this template". This will help if creation fails mid-way irrespective of the retry, consecutive runs don't need to change anything.

With retry, this is actually less important IMO, so we can punt this until there's a more concrete need. Marking this as fixed by #11825.
