### ISSUE TITLE
Adding a license brings user to setup screen for 5-15 seconds

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11800]
Related https://github.com/coder/coder/issues/11799

Not able to reproduce anymore, but it used to happen constantly.

**Comment by bpmct** [comment]
i managed to reproduce

https://github.com/coder/coder/assets/22407953/4a2bb50a-78f5-4040-a47a-c0997334e903

**Comment by johnstcn** [comment]
@bpmct if you have a moment, can you try with ghcr.io/coder/coder-preview:main-v2.7.1-devel-42e997d39-amd64 ?

**Comment by johnstcn** [comment]
I haven't heard any further reports of this, so I'm going to close this out as fixed by https://github.com/coder/coder/pull/11840. Please re-open if this is not the case.
