### ISSUE TITLE
Login via GitHub when another user exists with same GitHub Id. 

### ISSUE THREAD

**Issue by matifali** [coder/coder#11860]
While testing #10972. got locked out of account and got this error. 

```json
{"message":"Failed to process OAuth login.","detail":"in tx: execute transaction: update user profile: pq: duplicate key value violates unique constraint \"idx_users_email\""}
```

This can happen if we try to login with GitHub after changing GitHub's primary email.

**Comment by matifali** [comment]
Suggestion si to improve the error message to be more descriptive.

**Comment by Emyrk** [comment]
@matifali figured out how to reproduce this. You need to delete your account.

**Comment by Emyrk** [comment]
We need to fix this: https://github.com/coder/coder/issues/11861

**Comment by Emyrk** [comment]
I am going to close this. The issue was with a deleted account sharing the same linked_id as an active user. This was resolved with a trigger.

In practice, the schema still allow something like this to happen, and that is addressed here: https://github.com/coder/coder/issues/12116
