### ISSUE TITLE
chore(docs): update /networking with information on port requirements

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#11876]
Our docs do not make any mention of the port requirements for Coder, either for direct or indirect connections. 
Provide:
- A high-level summary of all ports required for direct connections.
- A high-level summary of how a direct connection is established to a Coder workspace.

An in-depth explanation of STUN / DERP is out of scope here. Just link to relevant documentation if folks want to read more.

**Comment by bpmct** [comment]
Nice, this will be super helpful. I have started a [WIP rework of this page](https://github.com/coder/coder/compare/main...networking-docs) but wasn't sure about the ports necessary for direct connections / other requirements for [NAT traversal](https://tailscale.com/blog/how-nat-traversal-works) so totally in favor of this enhancement in the meantime we I can work it into the larger rework / in-depth explanation of STUN / DERP
