### ISSUE TITLE
constantly prompted for missing variables when entering template editor

### ISSUE THREAD

**Issue by bpmct** [coder/coder#11870]
Steps to reproduce: 

1. Use a template with variables (e.g. Kubernetes)
2. Enter the template editor

https://github.com/coder/coder/assets/22407953/f626c34d-073b-4bf6-87ac-3891d494aec2

**Comment by BrunoQuaresma** [comment]
I tried to reproduce this issue, but was unable to do so.

**Comment by BrunoQuaresma** [comment]
https://github.com/coder/coder/assets/3165839/df508568-ead1-4b03-8f2d-3ddb0ebd61eb

**Comment by BrunoQuaresma** [comment]
@bpmct did you edit anything before build? I'm wondering if there are some edge cases we're not covering, or if for some reason BE wasn't returning the expected response.

**Comment by bpmct** [comment]
Ah, it appears you have to edit the variables first. Strangely, I did not do that the first time but that seems to reliably reproduce it. If I refresh, it works again

https://github.com/coder/coder/assets/22407953/79424716-2f9b-468b-95e9-0c28de039866

**Comment by BrunoQuaresma** [comment]
Interesting use case 🤔 thx!
