### ISSUE TITLE
Getting error when I am trying to login to coder

### ISSUE THREAD

**Issue by MohanVagalla** [coder/coder#11873]
**Version**
v2.7.2+a82a8c7

**Path**
`/workspaces`

**Error**
```
TypeError: Object.keys(...).map(...).filter(...).sort(...).at is not a function
```

**Comment by BrunoQuaresma** [comment]
Hey @MohanVagalla I'm sorry for that. What browser and version are you using? We have seen this behavior in old browsers but I just want to confirm.

**Comment by MohanVagalla** [comment]
Hello @BrunoQuaresma,

Just now I have checked with colleague's version. Yes, mine is very old. I will upgrade it.
Thanks for the helping :)

**Comment by BrunoQuaresma** [comment]
Closing it for now, let me know if you need any extra help 🙏
