### ISSUE TITLE
Create Template: Move default values to BE

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#11917]
When creating a new template, the FE must pass the default values in the API request, but this should not be mandatory so that the client can send requests with only the necessary data and be consistent.

https://github.com/coder/coder/blob/05eac64be41f24e743d9ab69b8254ea56fdc219e/site/src/pages/CreateTemplatePage/CreateTemplateForm.tsx#L93-L113

**Comment by BrunoQuaresma** [comment]
cc. @mtojek

**Comment by mtojek** [comment]
> When creating a new template, the FE must pass the default values in the API request, but this should not be mandatory so that the client can send requests with only the necessary data and be consistent.

How can the user clear the parameter value? Let's assume that the variable/parameter is allowed to be empty, then you need to pass either the default or empty right? Unfortunately, in Golang there is no way to distinguish if the value is unset or "", and I don't want to fiddle with nulls.
