### ISSUE TITLE
Make `coder ssh --wait=no` more discoverable

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#11923]
Most people don't know that `coder ssh --wait=no` is a thing if the workspace startup scripts are still running and are under the perception that they must wait for it to do whatever its doing. I think `--wait=yes` is a reasonable default, but the message that's present that the workspace is still starting could also note that they can bypass it with `--wait=no`.

**Comment by stirby** [comment]
Sorry we didn't see this @mattlqx. Thanks for the feedback.

I'll add this to our next sprint.
