### ISSUE TITLE
Feat: Support database storage for roles (enables custom roles)

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#1194]
## What is your suggestion?

Currently all rbac roles are stored in memory as constants. This will not support custom roles in the future, and mapping external "roles" to coder roles.

We should have a `rbac_roles` table that maps a role name to it's json payload of permissions.

### One Idea

To implement this, all `organization-member:uuid` roles should be created for each org. So all roles are 1:1 with a json payload.

## Why do you want this feature?

Support custom roles in the future. 

## Are there any workarounds to get this functionality today?

Yes, the in memory solution works as long as we don't support custom roles.

## Are you interested in submitting a PR for this?

PR can wait until custom roles are needed

**Comment by ammario** [comment]
Closing for now since it's unlikely we'll work on it in the next few months. cc @tjcran @misskniss
