### ISSUE TITLE
If a template does not enforce workspace quotas, why show groups' credits in UI?

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#11956]
Version: [`v2.7.2+a82a8c7`](https://github.com/coder/coder/commit/a82a8c7b021c00cf98ad2b48284c081cca75ebce)

![image](https://github.com/coder/coder/assets/2022166/17739e5d-28ac-4cc2-a39f-2789b3880e6d)

**Comment by matifali** [comment]
We should not show credits if the value is 0. Right?

**Comment by BrunoQuaresma** [comment]
@matifali I think it is a good one.
