### ISSUE TITLE
Autostop maximum appears busted/blocked.

### ISSUE THREAD

**Issue by elliot-graebert-skydio** [coder/coder#11990]
Issue: 

- I'm running `coder schedule override-stop my-workspace 49h` and it fails with "Cannot extend workspace beyuond max deadline"
- The autostop requirement is off, and the max lifetime is also off. I've tried setting and unsetting these values, but it doesn't seem to work.
![Screenshot 2024-02-01 at 8 20 24 PM](https://github.com/coder/coder/assets/126726750/0ea55491-8cf3-4473-b4ec-fd5297ab48bc)

**Comment by stirby** [comment]
We believe this was fixed in v2.8.5 with the patched max deadline issue.

**Comment by deansheather** [comment]
Closing as I believe this is fixed by https://github.com/coder/coder/pull/12446. Feel free to reopen if you can reproduce on `v2.8.5` or `v2.9.0`+
