### ISSUE TITLE
bug: dogfood: non-nix image build failing due to dependency issues

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#11998]
Seen here: https://github.com/coder/coder/actions/runs/7758370013/job/21160678449

```
6.366 openssl set to manually installed.
6.366 Some packages could not be installed. This may mean that you have
6.366 requested an impossible situation or if you are using the unstable
6.366 distribution that some required packages have not yet been created
6.366 or been moved out of Incoming.
6.366 The following information may help to resolve the situation:
6.366 
6.366 The following packages have unmet dependencies:
6.450  libssl-dev : Depends: libssl3 (= 3.0.2-0ubuntu1.12) but 3.0.2-0ubuntu1.13 is to be installed
6.457 E: Unable to correct problems, you have held broken packages.
```

**Comment by matifali** [comment]
Our non-nix image needs a major cleanup too.

**Comment by johnstcn** [comment]
It looks like this may be a transient error. If I remove the customized `sources.list` then the non-Nix image builds OK.

@matifali is there any benefit to using Teraswitch mirrors if we're using depot.dev to build the image though?

**Comment by matifali** [comment]
@johnstcn I am not away of why we are using the terraswith mirrors.
They are also hosted in Pittsburgh. 
Which dont help developers who run workspaces in Europe or other regions outside the US.

**Comment by johnstcn** [comment]
Hetzner has its own set of apt mirrors 🤔 
https://docs.hetzner.com/robot/dedicated-server/operating-systems/hetzner-aptitude-mirror/#ubuntu-2204-jammy-jellyfish

**Comment by johnstcn** [comment]
@matifali I think these mirrors mainly benefit users in the US. And as the dogfood image should already contain the required pacckages, it should not be necessary to install many packages. So we can probably remove this custom list and stick with the Ubuntu defaults.

**Comment by matifali** [comment]
Sounds fine to me.
