### ISSUE TITLE
Need my coder environment to be running always. After restart most of the deployments are lost

### ISSUE THREAD

**Issue by GurubasavarajuMN1** [coder/coder#11997]
Version: [`v2.5.1+e6e65fd`](https://github.com/coder/coder/commit/e6e65fdc64e1c33e5cc02d46d629c6e5d3408931)

Need my coder environment to be running always. After restart most of the deployments are lost

**Comment by matifali** [comment]
@GurubasavarajuMN1 how are you installing and running Coder?
