### ISSUE TITLE
Integrate A/B testing framework

### ISSUE THREAD

**Issue by bryphe-coder** [coder/coder#120]
A/B testing will be an important tool for us to use to experiment with some of our new 'v2' paradigms.

For example, we already have questions in our design, like:
- Is it better to keep Applications + DevURLs separate? Or consolidate them to a unified concept?

We've created some collateral around integrating [StatSig](https://statsig.com/) into our product - hopefully can dust that off and bring it into V2 for MVP.

**Comment by bpmct** [comment]
We won't be a/b testing anytime soon - community feedback has been instrumental in our progress though :)

**Comment by ketang** [comment]
Will want to make sure @spikecurtis has this use case in mind, because we will be coming back to this
