### ISSUE TITLE
Provide examples of provisioning (and CLI access) using the user's cloud identity

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12008]
## Background

Coder workspaces are typically provisioned using a `coder` service account, whether that is in a Kubernetes cluster or cloud provider. This means that all workspaces are "owned" and "managed" by a Coder user. Inside the workspace, a user can still log in with their cloud account using a CLI (e.g. `aws configure`), but there are several drawbacks to this:
- The workspace is still "owned" and "provisioned" by the Coder service account. While labels can be used to associate the user email or group, the Coder service account still needs privileged access to clusters
- User cloud secrets are stored inside the PVC, accessible by the Coder service account
- The user has to do a manual step to configure their cloud CLIs and manage tokens

## Proposal

Coder has [external auth](https://coder.com/docs/v2/latest/admin/external-auth) which can be used to require a user to authenticate with an external provider, such as a cloud, before workspace provisioning. Not only can this be used to pre-authenticate a CLI within the workspace ([example](https://github.com/coder/modules/blob/acab6437bca3201d33604ddd1add550ca6d8c5b4/jfrog-oauth/run.sh#L18)), but the token can also be passed to a Terraform provider to provision a resource using that user's token, instead of a general service account token. Here is a basic example (untested pseudocode):

```hcl
data "coder_external_auth" "gcp" {
  # Matches the ID of the external auth provider in Coder.
  id = "gcp"
}

provider "google" {
  project     = "coder-workspaces"
  region      = "us-central1"
  # Authenticate using the user's GCP access token
  access_token = data.coder_external_auth.gcp.access_token
}

resource "coder_script" "gcloud_login" {
 script =<<EOF
 if [[ !provisioned_with_gcp_service_account ]]
   gcloud auth login --token ${data.coder_external_auth.gcp.access_token}
 fi
 EOF
}
```

## Product requirements

Provide modules and documentation in https://github.com/coder/modules for each cloud (AWS, Azure, GCP) that supports:

1. Provisioning resources based on user cloud identity (not a Coder service account)
2. Authenticating the CLI inside workspaces based on cloud identity 

If the user just wants to do one of the things (e.g. just authenticate CLI, just provision), this should be supported in the module via variables. 

If some providers (e.g. AWS) do not support OAuth, document other ways that Coder can assume another user's IAM role (perhaps based on email or username) to provision resources on their behalf. Ideally, external auth can be used.

**Comment by bpmct** [comment]
Related: https://github.com/coder/coder/issues/9120

**Comment by sharkymark** [comment]
Good one!
