### ISSUE TITLE
Stuck on: A workspace build is already active

### ISSUE THREAD

**Issue by mayzyo** [coder/coder#12010]
I am running in Kubernetes, with Coder v2.7.2+a82a8c7

I have a Jupyter Notebook workspace that was working before. With the latest version, when I tried starting the workspace, it takes a very long time to start as it normally would (4mins or so). But the UI hung, and was stuck on "starting", so I tried deleting the workspace's container as I usually do. Now I'm unable to stop or delete the workspace both in the UI or in the coder CLI. What should I do?

![image](https://github.com/coder/coder/assets/25147960/1bbf5bf6-289c-4220-aa34-ef981d7cea14)

**Comment by mayzyo** [comment]
Trying the step in the documentation "Repairing workspaces" also failed:

![image](https://github.com/coder/coder/assets/25147960/fedab920-0a48-497d-832e-1757bb1993da)

**Comment by matifali** [comment]
Hi @mayzyo is it a single template issue or ist happening with all templates?

**Comment by mayzyo** [comment]
> Hi @mayzyo is it a single template issue or ist happening with all templates?

Hi @matifali it's a single template at this point. But I wouldn't be surprised if it can be replicated on the other templates.

I ended up purging the database and recreating everything from template docs I had in backup.

I think the main issue here is a lack of --force option of sorts. The engine can get stuck in a state that seems to be permanent.

**Comment by stirby** [comment]
Hey @mayzyo, sorry you're running into this. If this happens again, can you report this in discord?

https://discord.gg/coder
