### ISSUE TITLE
Feat: Improve Validation on Workspace Creation 

### ISSUE THREAD

**Issue by carbonaratara** [coder/coder#12033]
Request to improve clarity on when there's an error. Example: when both workspace name and authentication is missing, only the workspace name shows as an error, and if user attempts to fix workspace, the authentication is still an error but not explicitly stated or showing in red or highlighted. Request for there to be an indicator or red notification around the area that is an error for each error.

**Comment by ericpaulsen** [comment]
cc: @BrunoQuaresma @Kira-Pilot

**Comment by BrunoQuaresma** [comment]
@aslilac maybe this was fixed by your changes related to the "inline authentication". Wdyt?

**Comment by aslilac** [comment]
yeah, I think so! tho those changes haven't been released yet

**Comment by BrunoQuaresma** [comment]
Thank you @aslilac
