### ISSUE TITLE
`/audit` API route requires parameters to be passed, swagger docs incorrect 

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#12038]
our docs say the below parameters are not required:

<img width="538" alt="Screenshot 2024-02-06 at 15 42 47" src="https://github.com/coder/coder/assets/9683576/e6516cc8-f8fe-40ec-bf8e-421cb573ebec">

though when calling `/audit` with no parameters, the request fails. need to update the documentation to reflect required params.

**Comment by coadler** [comment]
It looks like only `limit` is "required" per-se, since not providing it just returns an empty array. We could probably just default to 25 if an empty limit is given.

**Comment by ericpaulsen** [comment]
@coadler i'm going to set this to required in the meantime.

**Comment by matifali** [comment]
Closed in #12043
