### ISSUE TITLE
Insights API has incorrect swagger documentation

### ISSUE THREAD

**Issue by carbonaratara** [coder/coder#12036]
/insights/templates, /insights/user-activity, /insights/user-latency all seem to be incorrect in the Swagger Doc. The API says no parameters are needed, but all 3 return a 400 response that start_time and end_time are required query parameters

**Comment by stirby** [comment]
I believe the `/insights` endpoint is still broken.

This is from api.go, where it says `start_time`, `end_time`:
https://github.com/coder/coder/blob/2b29559984c66c5b060ec70e2560665684e66954/site/src/api/api.ts#L341

But on the swagger docs, it's `before`, `after`:
https://dev.coder.com/swagger/index.html#/Insights/get-insights-about-user-latency
