### ISSUE TITLE
Render template update messages as markdown

### ISSUE THREAD

**Issue by TheZoker** [coder/coder#12049]
Hi there,

We like to include the changelog for every update to our templates.
Currently we pass the release changelogs to the `--message` section of the `coder templates push` command, like this (via github actions):
```
      - name: "Push template"
        run: |
          coder templates push $CODER_TEMPLATE_NAME --directory $CODER_TEMPLATE_DIR --yes --name="$CODER_TEMPLATE_VERSION" --message="$CODER_TEMPLATE_MESSAGE"
        env:
          ...
          CODER_TEMPLATE_MESSAGE: ${{ gitea.event.release.body }}
```

While the release notes looks like this:
![image](https://github.com/coder/coder/assets/1368405/f1f0d318-9128-4c66-8b11-dadf51fd5957)

The changelog then looks like this:
![image](https://github.com/coder/coder/assets/1368405/4b5618e4-8c05-450f-9b83-cafaa02af183)

It would be nice, if we can have multiline or markdown support, so it looks more like this:
![image](https://github.com/coder/coder/assets/1368405/797b8c84-da8d-4c14-941d-d66b1391ea7f)

Thanks!

**Comment by kylecarbs** [comment]
Great idea! Thanks for the request.
