### ISSUE TITLE
Update to v2.8.0 breaks connection to coder

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#12057]
# Description

After update to the latest release v2.8.0 suddenly the communication between workspace and coder instance is not possible.

![image](https://github.com/coder/coder/assets/103434584/8e9f87a5-499d-4b58-8bd4-60573bc634b0)

There were a ton of yamux errors in workspace logs.

# What was changed

We are using coder with external provisionerd in an Kubernetes setup. The only change was to raise both versions from v2.7.2 to v2.8.0

# What is expected

A update without a breaking change should work

**Comment by kylecarbs** [comment]
Woah, this shouldn't be happening.

If you rebuild the workspace does it work?

**Comment by MrPeacockNLB** [comment]
I just restarted 2 workspaces. Both the same error. Let me try to create a new one from scratch to see if it work

**Comment by kylecarbs** [comment]
Is there any chance something with your infrastructure changed? Or are you confident it's on the Coder side?

**Comment by MrPeacockNLB** [comment]
nothing has changed. Just updated helm charts to use newest tag

**Comment by kylecarbs** [comment]
Got it. We're working on this as a P1... will keep you posted.

**Comment by bpmct** [comment]
We just sent you an email if you want to set up a call to troubleshoot live

**Comment by spikecurtis** [comment]
That error comes from the websocket layer --- the limit seems to be fairly arbitrary, but set to that by default. I wonder if they have an unusually large startup script or something.

**Comment by MrPeacockNLB** [comment]
yes, our startup script is huge as it takes all the logic.

**Comment by MrPeacockNLB** [comment]
sadly I am unable to verify if a workspace with a small startup_script fixes the problem. This is a chicken egg problem as we were using a coder workspace to publish a new template version.
