### ISSUE TITLE
My coder instance is going to unhealthy state always

### ISSUE THREAD

**Issue by GurubasavarajuMN1** [coder/coder#12050]
Version: [`v2.5.1+e6e65fd`](https://github.com/coder/coder/commit/e6e65fdc64e1c33e5cc02d46d629c6e5d3408931)

![image](https://github.com/coder/coder/assets/97588561/c9c08cd7-e8e6-4a40-bffa-c69228bca5aa)

Workspace is unhealthy
Your workspace is running but 1 agent is unhealthy.

**Comment by kylecarbs** [comment]
We'll need a bit more info to do anything here.

Are there any agent logs? Can you connect to it?

**Comment by kylecarbs** [comment]
Closing until we get more info, but please comment!

**Comment by SteadEXE** [comment]
I got the exact same issue, there is no logs anywhere

**Comment by kylecarbs** [comment]
@SteadEXE there are no agent logs? In `/tmp/coder-agent.log`?

**Comment by kylecarbs** [comment]
@SteadEXE happy you got it working!
