### ISSUE TITLE
Install ssh certificates on workspace start

### ISSUE THREAD

**Issue by pmoody-** [coder/coder#12062]
I understand that restarting coder instances reinstalls ssh server and hence regenerates host keys, but I loath the use of the options `StrictHostKeyChecking=no` and `UserKnownHostsFile=/dev/null`.

What would it take to incorporate and ssh certificate CA and install a host certificate on bootup?

**Comment by kylecarbs** [comment]
Why do you loathe the usage of such options?

Adding host key verification wouldn't provide any security guarantees. The workspace agent would just request the key from coderd, which any SSH server could use to impersonate anyways.

**Comment by pmoody-** [comment]
> Why do you loathe the usage of such options?

because as you note, those options facilitate host spoofing. I was initially under the impression that that sshd(8) was involved but it sounds like it's not.

> Adding host key verification wouldn't provide any security guarantees. The workspace agent would just request the key from coderd, which any SSH server could use to impersonate anyways.

is there a doc that explains the flow from the client ssh process through the coder ProxyCommand to whatever is responding with `SSH-2.0-Go` on the server side? i see docs on how to run the various commands but not a description of the flow.

**Comment by kylecarbs** [comment]
There isn't a doc that describes it right now.

Essentially the Coder CLI is executed via ProxyCommand which dials a workspace using an SSH server written in Go. All authentication is via the Coder CLI, which is why host key verification is a noop.

**Comment by pmoody-** [comment]
apologies for peppering you with questions; how does the coder cli know that it's connected to the right host?

**Comment by stirby** [comment]
@pmoody-, thanks for your questions and feedback. We're more active in these discussions on our [community Discord server](https://discord.gg/coder). Please continue this discussion there.
