### ISSUE TITLE
Improve error message for startup_script failure

### ISSUE THREAD

**Issue by matifali** [coder/coder#12075]
The agent is successfully connected but part of the script has failed. Which shows it as 

> Error starting the agent
Something went wrong during the agent startup. [Troubleshoot](https://coder.com/docs/coder-oss/latest/templates#troubleshooting-templates).

**Comment by BrunoQuaresma** [comment]
Is there any screenshot? Wondering if the agent is detecting the failure correctly. Cc @mafredri

**Comment by mafredri** [comment]
@BrunoQuaresma I think the agent is reporting the issue correctly but the dashboard is interpreting "unhealthy" as a single boolean, even though it can be unhealthy due to agent can't connect, or agent startup scripts failed, etc. There is a "unhealthy reason" in the API response that can be shown, although we might want to switch to "error codes" here in the future, like we do with provisioners etc.

```json
						"health": {
							"healthy": false,
							"reason": "agent startup script exited with an error"
						},
```

**Comment by mafredri** [comment]
As for screenshots, here:
<img width="1002" alt="image" src="https://github.com/coder/coder/assets/147409/fb55da7e-e98a-4441-8c55-eb064f55b134">
<img width="430" alt="image" src="https://github.com/coder/coder/assets/147409/0ec7a60e-6565-4035-8fd6-244381331c68">

https://dev.coder.com/@mafredri/w

**Comment by matifali** [comment]
My suggestion is that we should not say that agent is unhealthy if only 1 of the scripts is failing. It could be a mild warning.

**Comment by mafredri** [comment]
> My suggestion is that we should not say that agent is unhealthy if only 1 of the scripts is failing. It could be a mild warning.

I don’t see how we can differentiate between one and all scripts failing in terms of severity, both could be equally bad. But perhaps it would be ok to consider all script failures as mild/warning. I do think it makes sense to think about it in tens of agent health though. So maybe we need to add severity to the health status for the agent?

**Comment by matifali** [comment]
I am only concerned about the phrase "agent is unhealthy". As an agent is actually running fine in this case but I Bly the script failed. 

We should change the message to not say that the agent is unhealthy here and instead focus on script failure. 

It should be a warning. 
Like the "agent is connected is healthy but scripts failed so workspace could be not ready to use."

**Comment by BrunoQuaresma** [comment]
It is not clear to me what changes we want to make in the UI 🤔

**Comment by matifali** [comment]
@BrunoQuaresma It is about if the agent is connected we should chnage the phrasing to not say that `Error starting the agent`
It is fine with me if we skip the 1st line and only show `Error in running script`

**Comment by BrunoQuaresma** [comment]
Like @mafredri said before, I don't think we can diff those two things right now.
