### ISSUE TITLE
Add ordering to `coder_metadata` entries

### ISSUE THREAD

**Issue by matifali** [coder/coder#12074]
A customer reported that
> resource "coder_metadata" - In the UI, this shows up in alphabetical order, whereas we would like to show up in the order we specify the keys in Terraform

But in our dogfood template, the following snippet renders in the correct order given in the template file. 
```tf
resource "coder_metadata" "container_info" {
  count       = data.coder_workspace.me.start_count
  resource_id = docker_container.workspace[0].id
  item {
    key   = "memory"
    value = docker_container.workspace[0].memory
  }
  item {
    key   = "runtime"
    value = docker_container.workspace[0].runtime
  }
  item {
    key   = "region"
    value = data.coder_parameter.region.option[index(data.coder_parameter.region.option.*.value, data.coder_parameter.region.value)].name
  }
}
```
![image](https://github.com/coder/coder/assets/10648092/c4ee7792-2c9e-4df6-898c-22876fed6a97)

**Comment by matifali** [comment]
This is already rendered in the same order as written in the file.

**Comment by matifali** [comment]
@mtojek I am not sure if its a bug as I am not able to reproduce the reported behavior.

**Comment by MrPeacockNLB** [comment]
I can confirm that the ordering is the same as in source code. But I think it ist counter intuitive if order is missing here as yesterday ordering for https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#order has been merged.

**Comment by mtojek** [comment]
Don't worry, I will sort it out. I'm going through [this list](https://github.com/coder/coder/issues/8995#issue-1843274476).

> I can confirm that the ordering is the same as in source code. But I think it ist counter intuitive if order is missing here as yesterday ordering for https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#order has been merged.

I merged support for `order` for `coder_agent`'s internal metadata. From Terraform perspective, this is a different resource.

**Comment by mtojek** [comment]
Looking into this

**Comment by mtojek** [comment]
Alright, I had some time to review this request.

Metadata `item`s are stored in the same form as `coder_parameter`s, so [array](https://github.com/coder/coder/blob/97e4d5195355ad0d3c92b951b30934adb7e6e892/provisioner/terraform/resources.go#L115). To ensure consistency with parameters, we should depend on the array too, and do not force users to append extra `order` property.

```
resource "coder_metadata" "home_info_2" {
  resource_id = docker_image.main.id

  item {
    key   = "disk-2"
    value = "5 GiB"
  }
  item {
    key   = "disk-1"
    value = "6 GiB"
  }
}
```

I'm going to close this issue now, and write docs describing `order` of different resources as part of https://github.com/coder/coder/issues/8995 .
