### ISSUE TITLE
Change `template_version_id` -> `template_active_version_id` in API docs

### ISSUE THREAD

**Issue by mdanish-kh** [coder/coder#12090]
Following up from the [discord thread](https://discord.com/channels/747933592273027093/1204991551843991602/1204991551843991602)

I noticed the [API docs for create workspace](https://coder.com/docs/v2/latest/api/workspaces#create-user-workspace-by-organization) haven't been updated to mention this change. `template_version_id` no longer works for creating a workspace through an API call. It seems to have been replaced with `template_active_version_id`

**Comment by Emyrk** [comment]
I see it still as `template_version_id`: https://github.com/coder/coder/blob/main/codersdk/organizations.go#L145-L145



The issue ran into in discord is you cannot provide both `template_id` and `template_version_id`. They are mutually exclusive. I will update the docs
