### ISSUE TITLE
E2E test redirects

### ISSUE THREAD

**Issue by presleyp** [coder/coder#1209]
## Problem
In some cases it's hard to integration test redirection because the test isn't rendering the whole app. Post-CE, we should make some time to round out our E2E testing. We can keep a list here of places we'd like to test:

## Definition of Done
- When I visit a page that requires auth besides the templates page, and I'm signed out, I should be redirected to the sign in page, and when I sign in, I should be redirected to the page I was originally trying to visit.
- When I create a new user successfully, I should be redirected to the users page.

## Acceptance Criteria

**Comment by kylecarbs** [comment]
@presleyp I'm going to close this for now. I like how you decomposed the XState refactors, and I think it'd be wise for us to do similar for targeting specific E2E tests! Let me know if you'd like to keep this open.
