### ISSUE TITLE
Display build status via Prometheus

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12128]
A customer reported they were unable to get build status (e.g. "failed," "succeeded") via Promethus metrics and had to script with our audit API to get this detail.

Use case: "how often are developer builds failing"

**Comment by MrPeacockNLB** [comment]
As we are using only one script for all use cases, it is good to know if any edge cases lets our startup_script fail

**Comment by mtojek** [comment]
Looking into this

**Comment by mtojek** [comment]
Here ist the current state:

```
# HELP coderd_workspace_builds_total The number of workspaces started, updated, or deleted.
# TYPE coderd_workspace_builds_total counter
coderd_workspace_builds_total{status="failed",template_name="docker",template_version="dazzling_chaum0",workspace_name="workspace-1",workspace_owner="admin",workspace_transition="START"} 1
coderd_workspace_builds_total{status="success",template_name="docker",template_version="dazzling_chaum0",workspace_name="workspace-1",workspace_owner="admin",workspace_transition="START"} 1
coderd_workspace_builds_total{status="success",template_name="docker",template_version="dazzling_chaum0",workspace_name="workspace-1",workspace_owner="admin",workspace_transition="STOP"} 1
```

@bpmct We already have some metrics for workspace builds, success/failed, transition, template version, etc. What would we like to add here? A build failure reason?

**Comment by amtunlimited** [comment]
Original customer here: I see that metric in documentation but I'm not seeing it in our Grafana. Where is it emitted from?

**Comment by mtojek** [comment]
@amtunlimited We had a short chat internally, and this might be an issue if you use external provisioners. We may need to add separate prom endpoints for them, I will check if this is a low hanging fruit.

**Comment by amtunlimited** [comment]
We are, in fact, using external provisioners. Thanks for looking into it
