### ISSUE TITLE
autostop ignores template level config if turned off at workspace level

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#12124]
i have a workspace that's been running for multiple days, despite the template-level autostop being set to 1 hour.

<img width="1159" alt="Screenshot 2024-02-13 at 11 23 00" src="https://github.com/coder/coder/assets/9683576/1c8e76ae-899f-4211-a2cb-419ee29dcf51">

conversely, the autostop is turned off at the workspace level:

<img width="1176" alt="Screenshot 2024-02-13 at 11 23 29" src="https://github.com/coder/coder/assets/9683576/170fd375-d03a-4440-ad6e-d67e4ff0cc73">

**Comment by stirby** [comment]
I can help reproduce/diagnose, but the wording here confuses me:

> I have a workspace that's been running for multiple days, despite the template-level autostop being set to 1 hour.

> ...conversely, the autostop is turned off at the template level

Is the autostop disabled at the workspace level? Does the template allow workspace-level autostop configuration?

**Comment by stirby** [comment]
This is intended behavior, but indicates that we need to revisit how we document this.
