### ISSUE TITLE
A slow SQL query is causing high database load

### ISSUE THREAD

**Issue by liji-canva** [coder/coder#12134]
By checking our AWS RDS metrics, we found that one slow query is consuming a lot of database resource and causing high database load. 

This is the query ```
-- name: GetDeploymentDAUs :many SELECT (created_at at TIME ZONE cast($1::integer as text))::date as date, user_id FROM workspace_agent_stats WHERE connection_count > ? GROUP BY date, user_id ORDER BY date ASC```

We may have a query or table to optimise here. The avg latency per call is 42s for a single query.
<img width="1725" alt="Screenshot 2024-02-14 at 2 26 07 pm" src="https://github.com/coder/coder/assets/50728668/6f347498-f200-429b-8232-5c11a492d6aa">

**Comment by ericpaulsen** [comment]
hi @liji-canva - thank you for reaching out. we have a related issue you can follow here: https://github.com/coder/coder/issues/12122

cc: @mafredri

**Comment by liji-canva** [comment]
Cool, thank you.

**Comment by liji-canva** [comment]
@ericpaulsen Is there any temporary solution for now? This query seems to be a none critical statistics query. Can we turn it off?

Also our db cluster has a read replica, is it possible to configure it to query from the read replica?

**Comment by mafredri** [comment]
@liji-canva a quick fix to reduce the load would be to delete some agent stats by executing the following query against the db:

https://github.com/coder/coder/blob/1bb4aecf49c11209cfeeaa4456dc7d4402eff8b6/coderd/database/queries/workspaceagentstats.sql#L93

Essentially, you can reduce the 180 day retention by as much as you can tolerate to lose (using 30 days should help _a lot_). **NOTE:** This will also remove data used by template insights, in case that’s important to you.

**Comment by liji-canva** [comment]
@mafredri  After I delete the data from this `workspace_agent_stats`, do I also lose older template insights metrics data?
