### ISSUE TITLE
Workspace response for date times are different when getting updated from Server Events.

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#12139]
When fetching a workspace, the response for the date fields is an ISO string, but when getting updates from Server Events, they are returned as an object:

```ts
deleting_at: {Time: '0001-01-01T00:00:00Z', Valid: false},
dormant_at: {Time: '0001-01-01T00:00:00Z', Valid: false}
```

**Comment by johnstcn** [comment]
Looks like it's time for `convertWorkspace` to be refactored.
