### ISSUE TITLE
end-to-end tests for web terminal

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12131]
We have run into several issues with our web terminal which is an important app in all workspaces:

- https://github.com/coder/coder/issues/8772
- https://github.com/coder/coder/issues/12005
- https://github.com/coder/coder/issues/9685
- https://github.com/coder/coder/issues/11933 [retro](https://www.notion.so/coderhq/The-terminal-and-build-pages-are-broken-bae992ef466241bda3feaffbfba5d0fb?pvs=4)
- https://github.com/coder/coder/issues/9806
- https://github.com/coder/coder/issues/11872

could an end-to-end test be used to identify whether the terminal is rendering properly / fast enough / at all?

**Comment by bpmct** [comment]
Criteria I think we should test for:

- Does the terminal connect
- How long does it take to connect
- Does resizing work properly
- Does terminal work with `screen`
- Does terminal work without `screen`

**Comment by stirby** [comment]
Happy with e2e tests now.
