### ISSUE TITLE
feat: support bundle: automatically diagnose STUN issues in network support bundle

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12165]
Part of https://github.com/coder/coder/issues/12160

The support bundle includes a netcheck report.
We can potentially automatically diagnose STUN issues by checking the netcheck output:
- Is there at least one configured STUN server,
- Can we reach all configured STUN servers,
- Does the address detected by STUN vary by STUN region (Hard NAT)

**Comment by johnstcn** [comment]
@spikecurtis @deansheather are there other things we should be looking for w.r.t. STUN programmatically?

**Comment by spikecurtis** [comment]
With respect to STUN, the main things to know are

a) whether we can reach the configured STUN servers (or, that there are no configured STUN servers)
b) whether the detected address varies by STUN region (Hard NAT)

DERP doesn't enter into STUN issues really at all.

**Comment by johnstcn** [comment]
Notes for self: https://github.com/tailscale/tailscale/blob/main/ipn/localapi/debugderp.go has some stuff directly related to this
