### ISSUE TITLE
Coder Docker Port forwarding

### ISSUE THREAD

**Issue by thdonadkar413** [coder/coder#12203]
Hi I had hosted coder on my ec2 server and I had hosted it using docker.
now when I created code-server workspace and made a simple react application on code-server workspace of coder now the issue coming is port forwarding is not working here i am not able to open my react Application.
please help if someone know what is issue and how to solve it

![image](https://github.com/coder/coder/assets/97872661/9ed1120d-a118-4fc6-bf3a-26a11c7ceda2)

![image](https://github.com/coder/coder/assets/97872661/f61bf808-e925-4383-8c49-822e37d6dd55)

**Comment by pskamble** [comment]
I have the same issue. For me code-server only works on port 8080 and doesn't recognize custom port provided by --port param. Even if I start code-server on the default port, my java application is not accessible. Same issue for any application hosted on the latest version. I did not have this issue in 2.7.2 version of coder. More details here: https://discord.com/channels/747933592273027093/1206785446127079434

**Comment by stirby** [comment]
@coder-pie @thdonadkar413 I'm closing this for now, please re-open with an update if you are still encountering issues.

**Comment by coder-pie** [comment]
@stirby My issue was resolved by #12875 Thanks.
