### ISSUE TITLE
UI: Paramter field has wrong size

### ISSUE THREAD

**Issue by 0xmeyer** [coder/coder#12202]
Coder version 2.8.2

Hello,

all fields where user can enter parameters for their workspaces have the wrong size (see image below). This is quite inconvenient, as parameters cannot be displayed or changed properly.

![Screenshot from 2024-02-19 07-29-29](https://github.com/coder/coder/assets/125983009/c5b43bbf-9c9c-4963-841b-9ac8ba85b14b)

Thank you!

**Comment by BrunoQuaresma** [comment]
Hey, @0xmeyer could you please explain a bit more about the issue you are facing like:
- What is the page?
- Is the width of the inputs incorrect?
- Could you please take a full screenshot so we can better understand the context?
- What browser are you using?

**Comment by 0xmeyer** [comment]
Hi @BrunoQuaresma,

> What is the page? Is the width of the inputs incorrect?

When I try to create a workspace from a template, the user parameter input fields have the wrong width. In the previous installed version 2.6.0, the width of these fields was still OK.

> Could you please take a full screenshot so we can better understand the context?

![Screenshot from 2024-02-20 13-28-27](https://github.com/coder/coder/assets/125983009/978c9204-55bb-40a5-b969-53622219a906)

> What browser are you using?

I'm using Firefox ESR (115.7.0esr), but the problem also exists on Chromium (121.0.6167.160).

**Comment by BrunoQuaresma** [comment]
Ahhh I see. I'm able to reproduce that 👍

**Comment by 0xmeyer** [comment]
Hi @BrunoQuaresma,

is there a chance that the fix will be released in a patch release by Wednesday?

Thanks in advance!

**Comment by BrunoQuaresma** [comment]
cc.: @bpmct
