### ISSUE TITLE
prometheus: do not add username / workspace name / template name to series by default

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12221]
We currently label most of our prometheus metrics by `agent_name`, `template_name`, `template_version`, `workspace_name`, and `username`. This results in a rather large number of metrics. We should allow folks to opt out of these additional metric labels, especially for larger deployments.

**Comment by kylecarbs** [comment]
Why opt out instead of changing our default? It seems the default is unacceptable for large deployments right now, which is our ICP.

cc @dannykopping

**Comment by johnstcn** [comment]
@kylecarbs sounds like you're more in favour of changing the default to 'do not aggregate' and calling this out in the release notes? 

We can make a separate change to change the default aggregation level

**Comment by kylecarbs** [comment]
I think that might be wise.

We should be built for scale out of the box, and I'd hate for another knob needed for all big deployments.

**Comment by dannykopping** [comment]
My view is that the larger your deployment, the more specificity you want from your metrics to pinpoint who/what is being problematic.

However, some folks may not need that level of specificity at their discretion so we're allowing them to tune it down, but in general we should encourage the existing behaviour.

**Comment by dannykopping** [comment]
@kylecarbs following up on this: what do you think about maintaining the existing behaviour?

**Comment by kylecarbs** [comment]
I think that's a fair perspective!

**Comment by dannykopping** [comment]
Cool, thanks @kylecarbs  👍 I'll close this out once I merge https://github.com/coder/coder/pull/12468 which will retain the existing behaviour.

**Comment by dannykopping** [comment]
Closed by #12535
