### ISSUE TITLE
Coder parameters are filled in automatically, even if the templates contain default values

### ISSUE THREAD

**Issue by 0xmeyer** [coder/coder#12226]
Coder version: 2.8.2
Browser: Firefox ESR (115.7.0esr), but the problem also exists on Chromium (121.0.6167.160).

Since the 2.8 release, Coder has the great feature of auto-fill parameters, when the template doesn't specify default values.

If I have a `coder_parameter` resource in my Terraform template that sets a default value and I create a new workspace, the auto-fill function should not set the parameter, should it?

```terraform
data "coder_parameter" "image" {
  name    = "Container image"
  type    = "string"
  mutable = true
  default = "registry/docker/images/code-server"
}
```

If I have understood the function correctly, then it is not working properly.

![Screenshot from 2024-02-20 13-28-27](https://github.com/coder/coder/assets/125983009/6d250702-a1a4-4d98-8006-1a60f74b9dc7)

Thank you!

**Comment by Kamainkokamain** [comment]
Hheeheh
