### ISSUE TITLE
shared ports: cleanup shared ports on template max share level change

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#12236]

**Comment by stirby** [comment]
I did notice the following behavior:
- Max template sharing level is `public`
- Have process on port 3000 on workspace X
- share port as `public`
- reduce max sharing level in template
- the dropdown UI is updated, but the port is still shared as `public`

I assume issue seeks to address strict enforcement of the template sharing level?

**Comment by f0ssel** [comment]
Exactly, any shared ports based on that template that are above the new sharing level will be reduced down to the new level. This ensures that revoking access at the template level immediately goes into effect for all workspaces based on it.

**Comment by f0ssel** [comment]
This also means that when the level is reduced to `owner` that all the shared ports will be deleted. I think this is better than trying to show some representation of a "public" shared port that is disabled because of the template level - just seemed too complicated to explain to the user IMO.

**Comment by stirby** [comment]
Sounds great - Totally agree on deleting the shared ports when an admin reduces the max level to owner.

Can we add a note or disclaimer that when the admin reduces it? Something as simple as "Reducing max share level to owner will remove shared ports on workspaces using this template."
