### ISSUE TITLE
Coder Lag when not LogIn in Coder via CLI

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#12234]
I had the report of some users that Coder became laggy after a while. 

One user found lag disappears whenever she log in on the CLI with the command `coder login coder.instance.com` . 

The user starts WS1 on Web Page and starts to sense lag on connection, run the coder login command and lags disappears. Then starts a new WS2 on Web Page and lag re-appears, relogs with the command and lags is gone and so on....

I'm not sure what could be the root-cause of the lag on the users WS, but something with the login command unplugs the lag of the users and their WS. 

The lag was present on all the WS views (Vscode, terminal or web Vscode). 
We are running on a K8s Backend.

**Comment by stirby** [comment]
Can you clarify the term lag? Are you experiencing latency issues here?

It's possible that some networking features are only made available for authenticated users.

I'm going to close this out for now, but if you're still having issues @francisco-mata please reopen and include the Coder version on the user's client and the server.
