### ISSUE TITLE
Allow editing starter templates

### ISSUE THREAD

**Issue by nguyenthanhtien** [coder/coder#12243]
I ran Coder at Docker local, but when i try use Starter template. I can't edit them.
Can help me guide how to edit?
![image](https://github.com/coder/coder/assets/9321745/a64dd402-5c22-4044-b746-f50bda47aac6)

**Comment by matifali** [comment]
If you need to edit, please get the template from https://registry.coder.com/templates and modify it as needed. 

We have also added the ability to start a template from scratch within the UI, which will be available in a future minor release. 
![image](https://github.com/coder/coder/assets/10648092/9cb0d29d-ab5d-43da-ace5-2ccd4ef2212f)



@BrunoQuaresma could we allow editing templates before we build them?

**Comment by BrunoQuaresma** [comment]
@nguyenthanhtien right now you can only edit a template after it is created so you can do:
- Choose a template you want to use
- Click on use template
- Create the template 
- On the template page, click on the "three dots" button on the right
- Click on edit files

Please, let me know if that works for you 🙏 we are thinking of better ways to improve this flow.

**Comment by BrunoQuaresma** [comment]
@matifali hm... I don't know, we would need some BE thoughts about that. Something we may think about is introducing the concept of template drafts or published/not-published templates so we could create template drafts in the background using some basic info without having to build them.

**Comment by nguyenthanhtien** [comment]
When i try Create Template, it's show this error, how to solve this one?
![image](https://github.com/coder/coder/assets/9321745/73b34587-d39e-476c-b9a7-adecd281a195)
![image](https://github.com/coder/coder/assets/9321745/4018706a-f355-4252-9319-a75f17d6497b)

**Comment by BrunoQuaresma** [comment]
cc.: @matifali

**Comment by matifali** [comment]
Hi @nguyenthanhtien this an issue with `coder` user not having access to docker socket. `coder` user should be a member of `docker` group b

**Comment by nguyenthanhtien** [comment]
@matifali how to resolve that Matifali.

**Comment by matifali** [comment]
It depends on how did you install Coder? Is it running as a system service and you installed via install script? Or is it running in as a docker container or k8s deployment?

For a system service you should do
```shell
sudo usermod -aG docker $USER
```

For docker you can use `--group_add` to add the container user to the docker group.

**Comment by stirby** [comment]
@nguyenthanhtien are you still encountering issues?

**Comment by stirby** [comment]
We're not going to allow editing of the starter templates, but we do have plans to update the list of starter templates soon.
