### ISSUE TITLE
Allow adding/updating provisioner tags on templates via terraform

### ISSUE THREAD

**Issue by matifali** [coder/coder#12267]
We should Allow adding/updating tags from Terraform to allow controlling them as IaC. Currently, it's only possible via API, CLI, or UI.

_Originally posted by @matifali in https://github.com/coder/coder/issues/6442#issuecomment-1955749134_

**Comment by matifali** [comment]
Related to #9948 and #13007.

**Comment by johnstcn** [comment]
@matifali #5979 is slightly different. Template tags are still a separate entity.

**Comment by matifali** [comment]
Hmm. Ok but with #5979 we can update the tags per workspace using terraform. 
My original issue actually requested this and #5979 provides an alternative solution to it. 

I agree that we still have template tags if someone isn't using the new `coder_workspace_tags` data source to update them per workspace.
