### ISSUE TITLE
Implement deleting organizations

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#12310]
Organizations cannot currently be deleted. The logic to delete an organization is going to be a bit involved with cleaning up resources.

**Comment by stirby** [comment]
@Emyrk is this issue still relevant?

**Comment by Emyrk** [comment]
@stirby I do not think this has been implemented yet, so yes

**Comment by Emyrk** [comment]
Closed by https://github.com/coder/coder/pull/13287
