### ISSUE TITLE
☂️  Improved (e2e) test coverage for common flows in the product

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12332]
Before a release, we should run (end-to-end?) tests to ensure that developer and admin flows are not broken.

> [!NOTE]
> Some of these have not been split into individual issues yet. If you want to take one, please create any necessary issue(s). We need your help understanding which components of the product are easy to test, or if they are tested already via other tests.

These flows are ranked in the order of how common they are combined with how error-prone they are.

## Error-prone/critical areas:

- [ ] https://github.com/coder/coder/issues/12131
- [ ] Long-lived connections
  - [ ] Can a client connect, and remain connected to a workspace for multiple hours without disconnecting?
    - [ ] websocket
    - [ ] DERP
    - [ ] STUN

## Common flows

- [ ] Create workspace
  - [ ] via `coder create` against a template with parameters
  - [ ] via the UI against a template with parameters
- [ ] Connect to a workspace
  - [ ] via a `coder_app`
    - [ ] does the proper path resolve
    - [ ] does a websocket session remain open
  - [ ] via VS Code Desktop
    - [ ] can a direct connection be established
    - [ ] can a DERP connection be established
  - [ ] via terminal 
    - https://github.com/coder/coder/issues/12131 for complete issue
- [ ] Update workspace
  - [ ] against a template with no new parameters
  - [ ] against a template with a new parameter introduced
  - [ ] against a template with a `type: select` parameter updated so the previous option is not available 
  - [ ] passing an ephemeral parameter via the UI
- [ ] Update template
  - [ ] via the template editor
  - [ ] via the CLI
  - [ ] creating a promoted template version
  - [ ] creating a non-promoted template version
  - [ ] with variables supplied via a variables file
  - [ ] with variables supplied via the `--var` flag
- [ ] Scheduling
  - [ ] https://github.com/coder/coder/issues/12388
- [ ] Audit log
  - [ ] Are [all the actions that we document](https://coder.com/docs/v2/latest/admin/audit-logs#tracked-events
) being properly audited?

**Comment by stirby** [comment]
Added a list of scheduling flows.

**Comment by stirby** [comment]
@bpmct @sreya Is this aligned with our current progress in testing coverage? Maybe we make a plan and revisit tracking methods here?

**Comment by stirby** [comment]
We're happy with e2e tests now.
