### ISSUE TITLE
chore: Evaluate replace .tar library on FE to use ZIPJS 

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#12346]
The idea is to make our file handling more reliable using a well-supported zip library rather than writing and maintaining our own.

**Comment by mtojek** [comment]
@BrunoQuaresma Remember that we do not drop support for .tar entirely. It would be great to discuss the next steps with product. cc @bpmct

**Comment by BrunoQuaresma** [comment]
Yes, I'm aware of that. Since it is an internal thing, what library to use, and how we want to maintain the code on the template editor, I think it is more an engineering decision than a product.

**Comment by BrunoQuaresma** [comment]
I think we can ignore this for now since what we have is stable enough and I would avoid introducing changes without a good reason to.
