### ISSUE TITLE
Create an example custom-skinned Coder dashboard

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12341]
We have several users who are currently or are interested in creating their front end for Coder to fit into their own workflows, design system, or internal developer portal.

This is all entirely possible today, but many folks have to start from scratch, and while we provide a few API examples, certain things (e.g. updating a workspace) are a bit difficult to do with the API as it requires multiple requests to get the info needed (org id, template version).

To help with this use case, we could try doing this ourselves and publish a sample version. Aside from the sample code, this can also be used to inform:
- What API endpoints could we improve/document better in this case?
- Could we provide/extract core React components (e.g. `CoderTerminal`, `CreateWorkspace`, `WorkspaceList`, `WorkspaceApps` that could be imported so customers don't have to reinvent the wheel for this?
- How can we integrate this into our Backstage plugin

**Comment by matifali** [comment]
@bpmct I know some students are doing this as their graduation project, and they have built a nice frontend around the Coder API. They may probably wish to open-source it someday, and we can link to that as an example.

cc: @mdanish-kh

**Comment by bpmct** [comment]
Hi [mdanish-kh](https://github.com/mdanish-kh). This sounds interesting, can you send me a message on Discord if you are still working on this? https://discord.gg/coder?

I'm closing this out for now as it's not likely anybody at Coder can do this in the next 6 months

**Comment by mdanish-kh** [comment]
@bpmct Pinged you on Discord :)
