### ISSUE TITLE
Automatically forward ports in VS Code Web

### ISSUE THREAD

**Issue by matifali** [coder/coder#12357]
The [VS Code Web module](https://registry.coder.com/modules/vscode-web) adds VS Code Server but cannot automatically auto-detect and forward ports. Can we force/enable port forwarding from within the VS Code Server as with the code-server?

See related discussion in this [slack thread](https://codercom.slack.com/archives/C014JH42DBJ/p1709123728034249?thread_ts=1709123728.034249&cid=C014JH42DBJ)

@code-asher suggested creating a new extension that updates the tunnel address for forwarding ports.

**Comment by michaelbrewer** [comment]
Is this not related to https://github.com/coder/coder/issues/11871

**Comment by matifali** [comment]
duplicate of #11871
