### ISSUE TITLE
Health tab does not always show detailed error message

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12408]
The "Access URL" and "Websocket" pages under "Health" do not show detailed error messages or further troubleshooting information.

For example:

Given: Coder instance with misconfigured scheme in `CODER_ACCESS_URL` (e.g. `https://localhost:7080` which is generally HTTP and not HTTPS)

When: you hit the health tab

Then: you see the following information:

```
Severity: error
Access URL: https://localhost:7080
Reachable: No
Status Code: 0
```

![image](https://github.com/coder/coder/assets/4949514/42cb0f32-b20b-4e5c-ab4c-b15e494635dd)

But the `/api/v2/debug/health` endpoint provides more detailed information, e.g.:

```
"access_url": {
"healthy": false,
"severity": "error",
"warnings": [],
"dismissed": false,
"access_url": "https://localhost:7080/",
"reachable": false,
"status_code": 0,
"healthz_response": "",
"error": "EACS03: get healthz endpoint: Get \"https://localhost:7080/healthz\": http: server gave HTTP response to HTTPS client"
},
```

Ditto for websocket check.

**Comment by johnstcn** [comment]
@coder-labeler good bot

**Comment by matifali** [comment]
`s2` as we have a workaround to get this info by hitting the debug endpoint manually.

**Comment by BrunoQuaresma** [comment]
@matifali I disagree this is a bug because it was the expected behavior when we planned this feature.

**Comment by BrunoQuaresma** [comment]
Just checking, for both we should display what is in the `error` attribute right?

**Comment by BrunoQuaresma** [comment]
@johnstcn would be nice if it could also return the error code `EACS03 `
