### ISSUE TITLE
create scoped keys, tags for provisioners

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#12416]
a prospect has not adopted provisioners because every provisioner uses the same pre-shared key, and tags can be duplicated across provisioners. they want:

- Scoped pre-shared keys per-provisioner
- Limit which tags can be used for particular provisioners

**Comment by ericpaulsen** [comment]
related https://github.com/coder/customers/issues/524

**Comment by MrPeacockNLB** [comment]
seams very reasonable
