### ISSUE TITLE
update template ACL via CLI

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#12428]
we support this via API and UI, but not via the CLI. a customer is requesting this, and this would fit nicely into the CI/CD flow they have for pushing templates into Coder.

**Comment by ericpaulsen** [comment]
related: https://github.com/coder/customers/issues/527

**Comment by bpmct** [comment]
We don't plan on doing this, but do have plans to make it possible to manage ACLs via Terraform, ideally by the end of Q2 2024. In the meantime, you can use the API or CLI.

If this doesn't work for your use case, please let us know and we may reevaluate.

**Comment by ssncoder** [comment]
From customer: 

Want to do it in CLI when template in created at the ATL 
- No plans to use terraform 
- Need to do a lot of API calls
