### ISSUE TITLE
investigate automatically setting GOMAXPROCS

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12432]
From [this dicsussion](https://github.com/coder/coder/issues/12385#issuecomment-1979295048_) with @dannykopping 

`github.com/uber-go/autogomaxprocs` allows us to automatically set `GOMAXPROCS` to match the host or container runtime. This could be useful as a number of Coder deployments run on Kubernetes/Docker. 

This should be its own change as it's fairly fundamental and may have unforeseen consequences, especially around the tailnet/wireguard area.

**Comment by bpmct** [comment]
Seems scary, feel free to reopen if it feels important but closing to reduce issues and we may not realistically get to it this year
