### ISSUE TITLE
`coder tunnel` does not update workspace `last_used` with long-lived connections

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#12431]
a customer is connecting to their workspace via `coder tunnel`, and the `last_used` metric is not being updated. this is across Linux and Windows VMs.

**Comment by ericpaulsen** [comment]
this was working in `2.4.0`, not working in `2.8.3`

**Comment by johnstcn** [comment]
`coder port-forward` currently only considers new connections as activity; long-lived connections such as websockets will only be counted once.
As a workaround, curling the port-forwarded address periodically (or even just executing a `nc -z` ) will cause workspace `last_used_at` to be updated. Downgrading to `s2` based on this new information.

**Comment by ericpaulsen** [comment]
thanks @johnstcn - do you know why this was previously working in `2.4.0`?

**Comment by johnstcn** [comment]
We made changes to how workspace activity was detected between 2.4.0 and 2.5.0 in order to support dormancy.

**Comment by johnstcn** [comment]
https://github.com/coder/coder/pull/12659

**Comment by johnstcn** [comment]
https://github.com/coder/coder/pull/12659 modifies the port-forward command to continuously update last_used_at for the respective workspace while it is running.

**Comment by johnstcn** [comment]
This issue was a symptom of how we currently perform workspace activity tracking. Filed https://github.com/coder/coder/issues/12693 to continue the process of standardizing this.
