### ISSUE TITLE
Feat: Option for background execution in `coder_script`

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#12448]
When using terraform modules that rely on `coder_script` there is no option to offload things in to the background

```terraform
module "code-server" {
  source         = "registry.coder.com/modules/code-server/coder"
  version        = "1.0.7"
  agent_id       = coder_agent.main.id
  folder         = "/workspace/${local.folder_name}"
  install_prefix = "/workspace/.coder-server"
  settings = {
    "workbench.colorTheme" : "Visual Studio Dark"
    "workbench.startupEditor" : "readme"
  }
  extensions = [
    "ms-python.python",
    "hashicorp.terraform",
    "ms-azuretools.vscode-docker"
  ]
}
```

Ideally things like installing the extensions could run in the background, instead of making the developer wait.

<img width="576" alt="Screenshot 2024-03-06 at 4 19 31 PM" src="https://github.com/coder/coder/assets/5442469/f9baaf1c-d7a4-4d76-84ac-d3f0cb658e7e">

This could be an issue for https://github.com/coder/modules instead? 

---

Other solutions might be to have `code-server` or `vscode-web` be preloaded with extensions

**Comment by matifali** [comment]
I would ask @mafredri for his thoughts on this.

**Comment by mafredri** [comment]
I think this is a perfectly valid request, especially in the case of `coder_app`s like `code-server` and `vscode-web` that are fairly self-contained.

I think in the case of these two modules, it would make sense to allow specifying the `start_blocks_login` parameter. It could default to false, even.

However, the coder CLI does not try to detect which scripts have finished executing (in fact, the agent doesn't expose this information anywhere), so we simply check for the presence of a single `start_blocks_login` startup script to enter blocking mode. This would make the change moot if any such script is included.

Ideally I'd like to see an RFC for how we take `coder_script`s forward. Right now they work alright for many use-cases but there are quite a few rough edges.

For example, do we introduce a new parameter like `background => true`, do we execute `start_blocks_login` script separately from non-blocking? What should happen to the workspace? Should it become `ready` immediately if there are no `start_blocks_login` scripts, even though there are startup scripts still executing? Etc.

**Comment by matifali** [comment]
I agree that we should open an RFC to discuss how to plan the future of `coder_script`.

**Comment by matifali** [comment]
Also, I saw [this example in lxd](https://github.com/terraform-lxd/terraform-provider-lxd/issues/422#issuecomment-1908358132), where the script output can be returned to terraform.

**Comment by michaelbrewer** [comment]
I wonder if some if the run.sh scripts would have a background block 

```bash
{
    echo "Installing vscode extensions.."
} &
```
