### ISSUE TITLE
Stable Releases: Document new release channels, cadence

### ISSUE THREAD

**Issue by stirby** [coder/coder#12463]
Part of [Stable Releases](https://www.notion.so/coderhq/Stable-Releases-fcc801d8b9384d94975b2a2b63b20550).

## Overview 

We need a new page under docs/install that describes the changes to our release channels. @stirby has a draft already, this issue is mostly for tracking.

### Changes/new info summary 
- New formal cadence (monthly releases)
- Support for stable channel
- CVE support note (past three versions)
- Read above doc for full info

## Requirements

- [ ] update landing page to display release disclaimer:

<img width="646" alt="Screenshot 2024-03-06 at 3 41 04 PM" src="https://github.com/coder/coder/assets/58410745/0549e1a1-dda6-4067-804d-b10b4927245d">

- [ ] Add releases doc 
  - [ ] describes differences between `mainline` and `stable`
  - [ ] Shows a release schedule 
  - [ ] Links to github releases in explanation

The following is an outdated mock, just for visual placeholder. "Latest" would be "mainline".
<img width="649" alt="Screenshot 2024-03-04 at 2 56 30 PM" src="https://github.com/coder/coder/assets/58410745/79df01d2-8db2-4f3c-9bde-4471e3835744">

**Comment by bpmct** [comment]
We'll consider this complete as the release scripts get merged!

**Comment by matifali** [comment]
Would be nice to add Coder to https://endoflife.date/
Some instructions here: https://endoflife.date/contribute#new-adding-a-new-product
