### ISSUE TITLE
Feature: Documentation link should point to the related version and not `latest`

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#12478]
Current link points to `https://coder.com/docs/coder-oss` which redirects to `https://coder.com/docs/v2/latest`

https://github.com/coder/coder/blob/1e17782ff6ab6983e0666f62075e8bdefa4e8315/coderd/appearance/appearance.go#L14-L18

Ideally it should point to the corresponding version of coder running on the server ie: `https://coder.com/docs/@v2.8.4`

This avoids confusion as to which features the server supports, as "latest" might include unreleased features

**Comment by matifali** [comment]
@stirby IIRC we fixed this a while back. I wonder why it's not working as expected.

**Comment by michaelbrewer** [comment]
As feedback I would argue that "latest" docs should be the "latest released version of coder", otherwise the label should be "unreleased" (or the branch name which you are releasing from with a warning that this is not necessarily available and have a link to "latest"). It's just confusing reading docs for features that are not available to you. 

Having a drop down in the docs to the version you are running is also a great feature, so you can quickly jump between releases. 

Another possible solution for docs is to bundle the matching version in the deployment itself (/docs/), then you can navigate from there. But to be fair the docs are for multiple audiences (admins, template admins and less likely users).

**Comment by stirby** [comment]
We discussed this before yes:
https://github.com/coder/coder/issues/8324

There were two attempts to fix this as a part of a docs version picker:
https://github.com/coder/coder.com/pull/368
https://github.com/coder/coder.com/pull/387

After reverting these we never fixed the docs pointing to `main`.

We could slim down that work into just fixing the default path from `main` to our `latest` release. Otherwise we would need to revive the version picker.

What do you think @Kira-Pilot?

**Comment by Kira-Pilot** [comment]
@stirby let's discuss what this would take next week after Backstage is delivered!

**Comment by michaelbrewer** [comment]
@stirby @matifali  - `https://coder.com/docs/v2/v2.8.4` this link no longer works for versioned docs.

**Comment by matifali** [comment]
The URLs are recently restructured. Can you try
https://coder.com/docs/@v2.8.4

@kylecarbs could you look into creating the redirects? Thank you.

**Comment by michaelbrewer** [comment]
Awesome, i can at least fix it on my end.
