### ISSUE TITLE
Feat: Add a log download feature to workspace detail page

### ISSUE THREAD

**Issue by gtaylor** [coder/coder#12485]
We've received feedback from our users that it is sometimes difficult to share workspace logs with us to assist with debugging issues. They've shared that it is tedious and sometimes tricky to copy and paste many lines.

I'd suggest adding a log download facility to the workspace detail page to make it easier for users to share log output with one another (and us). Admins can visit their workspace page to view directly, but most of our users aren't admins.

**Comment by kylecarbs** [comment]
We'll certainly do this!

Would copy to clipboard be preferred? We limit logs to 1MB right now anyway.

**Comment by gtaylor** [comment]
Good question! I was thinking a log download but stuffing it in the clipboard is probably fine, too.

**Comment by stirby** [comment]
This is a great idea!

**Comment by bpmct** [comment]
Slotting this in for our next sprint. In fact, you can't even select all and copy for the agent logs right now.

**Comment by BrunoQuaresma** [comment]
By logs do you mean build logs, agent logs, or both? We can add a copy button where logs are displayed and an option in the workspace "more actions" menu to download all the logs (build and agent).

**Comment by gtaylor** [comment]
I was originally thinking build logs but both would be fantastic!

**Comment by stirby** [comment]
@BrunoQuaresma I think copying logs via "more options" in the workspace dashboard is perfectly fine. Agree with bundling both agent and build logs. 

Would it be too much clutter to also add a download option? While I'm fine with just the copy, but I would instinctively dump my clipboard in a file when sending them.

**Comment by BrunoQuaresma** [comment]
Ok, I will develop something and share it with you in a preview environment. 👍

**Comment by BrunoQuaresma** [comment]
In the workspace page, I added the "Download logs" option to the "More options" menu in the header and added the options for copying and downloading agent logs at the bottom of the agent card.

![Frame 2](https://github.com/coder/coder/assets/3165839/170c9f05-87d9-425d-946e-0b820f1ea62b)

@stirby @gtaylor @kylecarbs I would appreciate feedback.

Side question: Should we also support download agent and build logs from the CLI?

**Comment by stirby** [comment]
Looks great. I like how you added the options to the bar. Just to confirm, the options stay there when you expand the log viewer?

> Should we also support download agent and build logs from the CLI?

I think of this more as a nice-to-have. It would be nice to add it under the `coder support` command:

```console
# cats the *latest* build and agent logs from the workspace

coder support get-logs <workspace>
```

**Comment by BrunoQuaresma** [comment]
> Looks great. I like how you added the options to the bar. Just to confirm, the options stay there when you expand the log viewer?

Yes, it does.

**Comment by gtaylor** [comment]
@BrunoQuaresma I like it! Definitely solves for our needs.

I'd also agree that logs via `coder` CLI would be a nice-to-have but imagine we'd get significantly more mileage out of the web-based option. I suspect we'd fall back to the CLI in exceptional cases, but I'm not yet sure what those would be.

**Comment by dannykopping** [comment]
@BrunoQuaresma I suspect this should be named _Provisioner Logs_ since that's what's being streamed into the logs section right now. I don't believe we have a mechanism to view the agent logs in the UI currently.

![image](https://github.com/coder/coder/assets/373762/d940c80c-a469-4115-adfd-714c37495647)

I'm not entirely sure of the value of "Copy" here; these logs could be up to 1MB in size, which is a lot of text, so I don't think that'd be very useful.

![image](https://github.com/coder/coder/assets/373762/757be4f6-d753-4a2c-ba66-15bde5bc8637)

Other than those nits, this looks really cool 👍 

I think the download functionality should download either a ZIP containing `provisioner.log` and `agent.log`, or download two separate files (which can sometimes be problematic with some browsers).

**Comment by matifali** [comment]
> I'm not entirely sure of the value of "Copy" here; these logs could be up to 1MB in size, which is a lot of text, so I don't think that'd be very useful.

Can we show it conditionally depending on the number of lines? Only display Copy when logs are less than, say, 1000 lines. 

> I don't believe we have a mechanism to view the agent logs in the UI currently.
 
Agent logs are the ones that are from `startup_script` and `coder_script` resources. We do display them.

**Comment by BrunoQuaresma** [comment]
- As @matifali mentioned before, we do display agent logs
- Related to copy, it makes sense. We can remove it. It is better than having a visibility condition that is unclear to the user.
- The "Download logs" from the "More options" menu will download the agent and provisioner logs in a zip file

**Comment by stirby** [comment]
I agree with removing the copy, as said before I would always use the download option.
