### ISSUE TITLE
Can't select `public` sharing level for shared port

### ISSUE THREAD

**Issue by stirby** [coder/coder#12480]
Maximum sharing level on the template is set to "Public" but it can't selected in the UI for a given workspace.

The public option is not disabled in the dropdown, but isn't clickable. Verified on multiple templates/workspaces.

https://github.com/coder/coder/assets/58410745/82a87bb0-1801-4bba-8b57-ecae50279917

cc @f0ssel

**Comment by f0ssel** [comment]
Will look into it, probably has something to do with when I added the tooltip to the disabled selections. Thanks
