### ISSUE TITLE
Correct and improve workspace scheduling settings around Autostop

### ISSUE THREAD

**Issue by stirby** [coder/coder#12481]
The workspace schedule settings page shows confusing and incorrect information around Autostop.

<img width="1097" alt="Screenshot 2024-03-08 at 12 24 03 PM" src="https://github.com/coder/coder/assets/58410745/3d8e60cc-9127-49ee-8c13-14ded05a5982">

The auto-stop in this screenshot is incorrect as the user setting is overridden by the template policy. We should make the following changes:
- [x] https://github.com/coder/coder/issues/11471:
   Change the value of “time until shutdown” to the template-level setting, if enforced (in this case it is 8 hours)
- [x] Add text below showing that the template enforces this autostop behavior, similar to how we show it from the “template policies” one (below)
- [x] Remove the “disabled” pill. This is small, and many users will think that “Disabled” means there is no auto stop for their workspace, not that they can’t modify it. 

<img width="1080" alt="Screenshot 2024-03-08 at 12 25 07 PM" src="https://github.com/coder/coder/assets/58410745/78803903-490b-4d17-944e-32932d9ce357">

**Comment by BrunoQuaresma** [comment]
@stirby related to the following

> Add text below showing that the template enforces this autostop behavior, similar to how we show it from the “template policies” one (below)

What message should we show?

**Comment by stirby** [comment]
I like:

"The template for this workspace does not allow modification of autostop."

**Comment by BrunoQuaresma** [comment]
@stirby Should we also remove the disabled badge and move the text under the field for the autostop as well?
