### ISSUE TITLE
`MoreMenu` component can have confusing presentation

### ISSUE THREAD

**Issue by aslilac** [coder/coder#12482]
https://github.com/coder/coder/pull/12464#issuecomment-1985824241

Basically if an item has keyboard focus _and_ you're hovering with your mouse, things get weird.

**Comment by Parkreiner** [comment]
This is one of those things where I feel like MUI has to have something for handling this, but if necessary, I don't think it'd be too bad to add custom focus/hover management to the component

**Comment by aslilac** [comment]
these components are already just thin wrappers around MUI, and this is what we get by default. my concern is that this might be something we fix despite MUI, not with it. 🙃

**Comment by Parkreiner** [comment]
It's been a while since I looked at the code, but I want to say that we're using `cloneElement` under the hood, which could be breaking things. It might be an implementation issue on our part

**Comment by aslilac** [comment]
we only use `cloneElement` in `MoreMenuTrigger` :\ but maybe there's some easy way to improve it

**Comment by bpmct** [comment]
If you want to take this, feel free to pull into next sprint or just solve anyways. We have a lot of s3s so trying to clean things up a bit
