### ISSUE TITLE
Bug: Launching a workspace with`mode=auto` does not check for required external authentication for the template

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#12491]
When using "Open in Coder" and selecting `mode=auto` the developer should still be prompted to do external authentication if that requirement was not met.

You get the expected outcome when you use `mode=form`

<img width="1169" alt="Screenshot 2024-03-08 at 4 27 01 PM" src="https://github.com/coder/coder/assets/5442469/a87e895d-82cf-446b-b3e1-c14688db7ba3">

Related Coder Docs: https://coder.com/docs/v2/latest/admin/external-auth#require-git-authentication-in-templates
Running 2.8.4 Coderd

**Comment by kylecarbs** [comment]
Oof, good bug. Will fix!
