### ISSUE TITLE
Test deprecate template flow

### ISSUE THREAD

**Issue by sreya** [coder/coder#12505]
Part of this issue is determining whether an e2e test is necessary for listing templates. We do not support querying for this page so it may be suitable to simply have a unit test here.

**Comment by mtojek** [comment]
@BrunoQuaresma As the listing view does not provide any paging capabilities, you can create a view with:
1. Regular template
2. Regular template with an overridden `display_name`.
3. Deprecate the template + check that the user can't click Create Workspace.

I'm good with resolving this issue if you can prove that these are covered with the frontend or storybook tests.

**Comment by BrunoQuaresma** [comment]
Hm... it is a good test case. Could I change this issue title to "Test deprecate template flow" instead of "e2e: List Templates"?
