### ISSUE TITLE
e2e: Deployment Page

### ISSUE THREAD

**Issue by sreya** [coder/coder#12508]
Add e2e test(s) that validate we report server configuration correctly. Given the breadth of our configuration options it may be prudent to decompose this into multiple PRs. This should also encompass validating we report workspace proxies and provisioner daemons correctly.

**Comment by mtojek** [comment]
Here is the battle plan:
- [ ] General:
  - Enabled experiments
- [ ] Licenses
  - Valid Until January 15, 2025
- [ ] Appearance
  - Set application name
  - Set logo URL
  - Set service banner 
- [ ] Security
  - Verify configuration consistency
- [ ] User Authentication
  - Verify configuration consistency
- [ ] Network
  - Verify configuration consistency
- [ ] Workspace Proxies
  - Configure proxy? Wait until it is healthy


External Authentication will be covered in https://github.com/coder/coder/issues/12585.
