### ISSUE TITLE
e2e: List Workspaces

### ISSUE THREAD

**Issue by sreya** [coder/coder#12503]
Add an e2e test for listing workspaces. This should cover querying for workspaces by various criteria.

**Comment by BrunoQuaresma** [comment]
@sreya would be nice to have those "querying" well defined.

**Comment by mtojek** [comment]
@BrunoQuaresma I think this view is important to verify as it exposes different filtering options (see advanced filtering: owner, template, status) + paging.

Here are sample test cases to cover:
1. A list of 10 workspaces using different templates, with different owners, and statuses - check advanced filtering.
2. A list of 1000 workspaces to page over all the pages (including the last one)
3. _No search results_ No results matched your search
4. Not found page - if we are beyond the last page.

**Comment by BrunoQuaresma** [comment]
I think all of these are already covered.

> 1. A list of 10 workspaces using different templates, with different owners, and statuses - check advanced filtering.

It is already covered on the BE tests. The FE also has tests to check filtering.

> A list of 1000 workspaces to page over all the pages (including the last one)

The FE tests that we have already checked this.

> No search results No results matched your search

Same.

> Not found page - if we are beyond the last page.

I added this test last week.

**Comment by mtojek** [comment]
Great! It seems to be covered then 👍
