### ISSUE TITLE
bug: ci workflow being cancelled on `main`

### ISSUE THREAD

**Issue by matifali** [coder/coder#12532]
See:

1. https://github.com/coder/coder/actions/runs/8234146513
2. https://github.com/coder/coder/actions/runs/8234091664
3. https://github.com/coder/coder/actions/runs/8234032894
4. https://github.com/coder/coder/actions/runs/8234005088
5. https://github.com/coder/coder/actions/runs/8233555043

ci should run on all commits to `main` and not be canceled or skipped.

As a side-effect, this does not update htps://ghcr.io/coder/coder-preview and dogfood deployment.

~Possible issue with database migrations~

Imagine some database migrations get missed because of missing deployments.

![image](https://github.com/coder/coder/assets/10648092/4898bb4b-d1d9-4dd9-867b-3467f3eba5ab)

**Comment by matifali** [comment]
cc: @deansheather @johnstcn

**Comment by deansheather** [comment]
Migrations will be applied on subsequent deployments if they were missed. We store the migrations we've applied in a table, and any that are missing get applied in order. Missing a deployment will not break the DB schema, so skipping in main is fine. Although we should only be skipping when there's a large backlog or no code changes were made.

**Comment by matifali** [comment]
CI is still being canceled on `main` https://github.com/coder/coder/actions/runs/8882391332
