### ISSUE TITLE
Columns missing in telemetry DB

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12536]
We manually have to update the schema in BigQuery when adding items to `telemetry.go` which has resulted in lots of data missing. For example:

https://github.com/coder/coder/blob/83af8674e83a9c6a971817a2bc3f2610bfa179b8/coderd/telemetry/telemetry.go#L671-L684

- [ ] Audit which fields are missing and add them into BigQuery
- [ ] Create docs/pr template/something so folks know we need to do this when adding extra columns

Telemetry is important for us to understand which features are being used. Of course, people can opt out

**Comment by bpmct** [comment]
@dannykopping - did we fix this? Do we have some form of preventative measure to ensure new telemetry items are also represented as columns in BQ?

**Comment by stirby** [comment]
@bpmct bumping this as it's related to our recent discussions.

**Comment by bpmct** [comment]
Thanks, closing for now as i'm moving it to an internal doc we have
