### ISSUE TITLE
flake: multiple TestWorkspaceProxyWorkspaceApps/* flakes

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12531]
Seen here: https://github.com/coder/coder/actions/runs/8233181037/job/22512128222?pr=12515

```
=== Failed
=== FAIL: enterprise/wsproxy TestWorkspaceProxyWorkspaceApps/WorkspaceAppsProxySubdomain/ProxyError (0.07s)
    apptest.go:921: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/workspaceapps/apptest/apptest.go:921
        	Error:      	Not equal: 
        	            	expected: 502
        	            	actual  : 200
        	Test:       	TestWorkspaceProxyWorkspaceApps/WorkspaceAppsProxySubdomain/ProxyError

=== FAIL: enterprise/wsproxy TestWorkspaceProxyWorkspaceApps/WorkspaceAppsProxyPath/ProxyError (0.00s)
    apptest.go:382: 
        	Error Trace:	/Users/runner/work/coder/coder/coderd/workspaceapps/apptest/apptest.go:382
        	Error:      	Not equal: 
        	            	expected: 502
        	            	actual  : 200
        	Test:       	TestWorkspaceProxyWorkspaceApps/WorkspaceAppsProxyPath/ProxyError

=== FAIL: enterprise/wsproxy TestWorkspaceProxyWorkspaceApps/WorkspaceAppsProxySubdomain (1.63s)
```

**Comment by spikecurtis** [comment]
I'm also seeing this: https://github.com/coder/coder/runs/22597523247

**Comment by Emyrk** [comment]
> Also saw these in https://github.com/coder/coder/actions/runs/8251597743/job/22569038030?pr=12559:
> 
> ```
> === Failed
> === FAIL: enterprise/wsproxy TestWorkspaceProxyWorkspaceApps_BlockDirect/WorkspaceAppsProxyPath/NoProxyPort (10.00s)
>     apptest.go:400: 
>         	Error Trace:	/Users/runner/work/coder/coder/coderd/workspaceapps/apptest/apptest.go:1727
>         	            				/Users/runner/work/coder/coder/coderd/workspaceapps/apptest/apptest.go:400
>         	Error:      	Condition never satisfied
>         	Test:       	TestWorkspaceProxyWorkspaceApps_BlockDirect/WorkspaceAppsProxyPath/NoProxyPort
>         	Messages:   	workspace LastUsedAt not updated when it should have been
> 
> === FAIL: enterprise/wsproxy TestWorkspaceProxyWorkspaceApps_BlockDirect/WorkspaceAppsProxyPath/LoginWithoutAuthOnProxy (10.03s)
>     apptest.go:189: 
>         	Error Trace:	/Users/runner/work/coder/coder/coderd/workspaceapps/apptest/apptest.go:1727
>         	            				/Users/runner/work/coder/coder/coderd/workspaceapps/apptest/apptest.go:189
>         	Error:      	Condition never satisfied
>         	Test:       	TestWorkspaceProxyWorkspaceApps_BlockDirect/WorkspaceAppsProxyPath/LoginWithoutAuthOnProxy
>         	Messages:   	workspace LastUsedAt not updated when it should have been
> ```
> 
> I've expanded the scope of the issue to encompass multiple `TestWorkspaceProxyWorkspaceApps` flakes.

This one is still unsolved. The other 2 I fixed in https://github.com/coder/coder/pull/12580

**Comment by Emyrk** [comment]
I am going to close this as a subset was definitely fixed. The remaining might still exist, and can be reopened.

**Comment by dannykopping** [comment]
Flakes seem to have reappeared in https://github.com/coder/coder/actions/runs/10629250399/job/29465715027?pr=14478, although they seem to be different now.

Shall I reopen this or open a new one @Emyrk?

**Comment by Emyrk** [comment]
@dannykopping I have not seen it happen in a bit iirc

**Comment by dannykopping** [comment]
Another datapoint: https://github.com/coder/coder/actions/runs/10680634527/job/29602814387
