### ISSUE TITLE
Investigate Implementing HyStart in gVisor

### ISSUE THREAD

**Issue by sreya** [coder/coder#12540]
# Background

gVisor, which we use for our TCP/IP stack for tunneled networking to workspaces, exhibits a behavior where it can get stuck during the first few seconds on a large transfer, and have low throughput until it recovers.  This particularly affects "medium" size transfers that we expect to complete within a few seconds: getting stuck can make them take twice as long.

What's happening is that gVisor's TCP congestion control algorithm during slow start "overshoots" a healthy window size, which causes a big burst of packets to be dropped.

![6Mrecv-16Msnd-SACK-RACK](https://github.com/coder/coder/assets/5375600/260d62f4-1a6e-4fe1-a7a3-50430d7d9be8)

The dropped packets have to be retransmitted and this brings the TCP stack to a halt for a while.

Linux's TCP/IP stack does not exhibit this behavior because it has implemented a slow-start algorithm called [HyStart](https://www.rfc-editor.org/rfc/rfc9406.html).

# Task

We are strongly considering implementing HyStart in gVisor, and this task is to investigate what it would require to implement and ideally upstream to gVisor.

The algorithm itself is well described in the RFC.

The unknowns are

* how to integrate with the rest of gVisor
* difficulty of building and testing gVisor with Bazel
* how to write unit tests in gVisor's frameworks
* what additional testing (integration, system, performance, etc.) the gVisor team needs before they could accept a contribution
* integration with gVisor would have to be at the tip to be accepted upstream, but we have imported an older version, which also needs to be integrated with tailscale.

**Comment by spikecurtis** [comment]
I've written up the implementation tasks in #12794
