### ISSUE TITLE
feat(cli): use CLI to interact with multiple servers

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#12576]
The `coder` CLI allows a `--url` argument to be passed, which might lead one to reasonably assume the CLI could be used to interact with multiple servers. However, this is not the case.

`coder`'s config is not namespaced by URL.

```bash
$ ls -l '/Users/danny/Library/Application Support/coderv2/'
total 12
-rw------- 1 danny 347 Feb 17 17:07 devtunnel
drwxr-x--- 8 danny 256 Mar  5 13:26 postgres
-rw------- 1 danny  33 Mar 13 09:46 session
-rw------- 1 danny  21 Mar 13 09:46 url
```

**Comment by MrPeacockNLB** [comment]
We've build a wrapper around `coder` CLI. This allows us to switch between different environments with ease. It is relative easy to archive with gum.

**Comment by matifali** [comment]
Related to https://github.com/coder/vscode-coder/issues/10, https://github.com/coder/vscode-coder/issues/102, and https://github.com/coder/vscode-coder/issues/173 as vscode uses the coder binary to connect via `ProxyCommad`

**Comment by stirby** [comment]
Folding into https://github.com/coder/coder/issues/13325.
