### ISSUE TITLE
Coder workspace stuck in 'starting'

### ISSUE THREAD

**Issue by 0xmeyer** [coder/coder#12579]
Coder Version: 2.6.0

Hello,

A workspace was unable to start and has been in the 'running' state since then. 
Is there a way to reset the status of this workspace? `coder stop`, `coder delete` both terminate with the error `A workspace build is already active.`. This only applies to a single workspace and is not reproducible.

![Bildschirmfoto vom 2024-03-13 11-38-32](https://github.com/coder/coder/assets/125983009/99cf2270-a46d-4925-bf1a-da457967a1f5)

The problem is **not** urgent!

Many thanks and best regards

**Comment by 0xmeyer** [comment]
Maybe it's related to https://github.com/coder/coder/issues/12010, but I can't purge the database.

**Comment by matifali** [comment]
What happens when you hit cancel?

**Comment by 0xmeyer** [comment]
A admonition appears with the following text: "Job has already completed!".

**Comment by 0xmeyer** [comment]
Hi @matifali,

any ideas how to fix the problem?

**Comment by matifali** [comment]
Hi. Is it happening with each template or a specific one?

**Comment by 0xmeyer** [comment]
It only happened with a single workspace. Other workspaces run fine, so it is not dependent on the template.

**Comment by bpmct** [comment]
Hey @0xmeyer, sorry you're running into this. If this happens again, can you report this in discord? https://discord.gg/coder
