### ISSUE TITLE
bug: external auth button redirects the primary coder page, not just the pop-up

### ISSUE THREAD

**Issue by bpmct** [coder/coder#12581]
https://github.com/coder/coder/assets/22407953/5d4aef32-0389-4190-a746-20bfdb5aa3d6

Tested on atif.cdr.dev which deploys against main

**Comment by BrunoQuaresma** [comment]
Does it have a workaround? If yes, it is a s2

**Comment by bpmct** [comment]
I couldn't find a way to successfully link my provider

**Comment by BrunoQuaresma** [comment]
Ahhh ok, the "state mismatched" error is probably related to the API getting cut off or an error from the BE. cc.: @Emyrk

**Comment by bpmct** [comment]
This also seems like a regression so was considering s0

**Comment by sreya** [comment]
You can still authenticate with the external provider and it only affects users who aren't already authenticated so it's not an s0 imo but I agree this is extremely disruptive so s1 seems appropriate.

**Comment by Emyrk** [comment]
I think the problem is both windows are doing an oauth authentication flow, where only 1 should. The primary page should not redirect to `/external-auth/<app_id>`

**Comment by matifali** [comment]
It's a bit off-topic, but our [release script](https://github.com/coder/coder/blob/main/scripts/release.sh) does not care about the `block-release` label.

**Comment by michaelbrewer** [comment]
Workaround is to navigate back and try again to get past the `State mismatched` error. 

In general alot of the external auth errors are just 503s or json. It would be helpful to have custom error screens and events going to the site admins to see if was a config error or bug or user error.
