### ISSUE TITLE
Define template as base template + modules

### ISSUE THREAD

**Issue by ffenix113** [coder/coder#12583]
First of all thanks for this great piece of machinery!

As a suggestion it could be nice to have a workspace that is created by a combination of a base template and some number of modules, and probably be able to have template to be defined as another template + modules.

The benefit would be that now multiple templates can be defined that all depend on single base template and set of modules, all of which could be maintained separately. When base template, or used modules, are updated - resulting template can be marked as outdated and be rebuilt to create new version.
Also this would also allow for more GUI-friendly template creation, as they could be assembled from already existing parts(templates and modules) visually, instead of editing Terraform configurations.

Example hierarchy could look like:
```
Base template - Template #1
Template #2 = Template #1 + Module A, B
Template #3 = Template #2 + Module F
```

**Comment by matifali** [comment]
We recently added a new [scratch](https://registry.coder.com/templates/scratch) template that can be used as a starting point and can be extended using modules. Building templates using modules has been previously discussed in https://github.com/coder/coder/issues/10641 as part of https://github.com/coder/coder/issues/10664.
