### ISSUE TITLE
bug: any typo in template matadata is crashing registry.coder.com deployment

### ISSUE THREAD

**Issue by matifali** [coder/coder#12588]
See logs:
1. https://vercel.com/codercom/registry/6xHz3A1oBP3iyix3J1AH9vA1rchY
2. https://vercel.com/codercom/registry/9QgZvTD5pMeDX51x8fVzei3GtD5B

I attempted to fix the fail depoyments in #12587, but it still needs to be deployed.

**Comment by mafredri** [comment]
@Kira-Pilot sorry, looks like I grabbed this from under @code-asher, didn't know you were on top of it. 😅

**Comment by Kira-Pilot** [comment]
@mafredri we hadn't looked at it yet! Thank you for the fix!
