### ISSUE TITLE
Template schedule settings page reorganization  

### ISSUE THREAD

**Issue by stirby** [coder/coder#12617]
## Overview
Template schedule settings needs organizational and copy cleanup. The settings can be divided into three major categories: Autostop, Autostart and Dormancy. The page should reflect this division. 

### Autostart and Autostop
- [x] Replace ambiguous "Schedule" header with "Autostop"
- [x] Remove MAX_TTL in the UI (we're removing this entirely)
- [x] Replace "Allow Users Scheduling" with "Autostart"
- [x] Replace "Allow users to customize autostop..." with "Enforce these changes across all workspaces"
- [x] Move the checkbox up, directly under autostop config 
<img width="1222" alt="Screenshot 2024-03-15 at 2 14 05 PM" src="https://github.com/coder/coder/assets/58410745/3359cd33-0228-4507-8baf-4241a0d74446">

### Part 2: Dormancy changes
- [x] Move "Failure Cleanup" to the bottom of settings
<img width="676" alt="Screenshot 2024-03-15 at 2 27 29 PM" src="https://github.com/coder/coder/assets/58410745/d819ad3c-34fe-459d-b8bc-cd6e046bb2c5">

### FE Decisions
Ben and I added larger headers for Autostop, Autostart and Dormancy to pronounce the three categories in these mocks. Leaving the decision up to FE.

**Comment by bpmct** [comment]
@johnstcn is working on some refactors around workspace activity detection, not sure if this would also be a good fit to take on.

**Comment by BrunoQuaresma** [comment]
@johnstcn checking if your work would impact or be impacted by this issue.

**Comment by johnstcn** [comment]
@BrunoQuaresma the refactors are backend-only and should not impact the FE.

**Comment by BrunoQuaresma** [comment]
https://github.com/coder/coder/assets/3165839/7f3a599c-f9ed-41be-912f-f1aee9149afa


cc.: @bpmct @stirby

**Comment by BrunoQuaresma** [comment]
https://github.com/coder/coder/assets/3165839/66d4f238-d31f-4ee8-a3de-ce68215b0492

**Autostop**
![Image](https://github.com/coder/coder/assets/3165839/7d7430b9-fdb6-4842-ab2d-3b22cebe579e)

**Autostart**
![Image](https://github.com/coder/coder/assets/3165839/fd65865e-f996-4b17-b16b-679fd8c6b449)

**Dormancy**
![Image](https://github.com/coder/coder/assets/3165839/625e4769-7742-47c7-bce8-b33a54abaa34)

cc.: @bpmct @stirby

**Comment by stirby** [comment]
Beautiful @BrunoQuaresma. Knew you would have some great creative input!

Can we change "Enforce these **changes** across all workspaces" to "Enforce these **settings** across all workspaces"?

I think this would make more sense after seeing it in the UI.
