### ISSUE TITLE
Show queue size on provisioner health page. 

### ISSUE THREAD

**Issue by matifali** [coder/coder#12627]
We are now showing queue position in the workspace list page, and also on the CI. Let us show the queue size along with the job details (e.g., workspace name, creating/starting/stopping/deleting etc.) on the `/health` page for each provisioner. 
### Must have
- [ ] Display queue size on the provisioner health page. 
### Nice to have
- [ ] show an expand table with each job's name and type.

_Originally posted by @matifali in https://github.com/coder/coder/issues/12606#issuecomment-2003136447_

**Comment by bpmct** [comment]
This is visible in coder/observability
