### ISSUE TITLE
Simplify and rewrite README.md

### ISSUE THREAD

**Issue by matifali** [coder/coder#12628]
Clean up and simplify READEME.md

- [x] Remove duplicates
- [x] Add badges for slack/discord
- [x] Remove unmaintained community projects links
- [x] Link to Coder [registry](https://registry.coder.com)
- [ ] link to [modules](https://github.com/coder/modules), [backstage-plugins](https://github.com/coder/backstage-plugins) and, [envbuilder](https://github.com/coder/envbuilder) repos. 
- [ ] @ericpaulsen @bpmct @kylecarbs @ammario add more suggestions

Probably: 

- [ ] Sync README.md with https://coder.com/docs/v2/latest to prevent any drift.

**Comment by kylecarbs** [comment]
I'll do this!
