### ISSUE TITLE
improve design for `coder_metadata` items

### ISSUE THREAD

**Issue by matifali** [coder/coder#12652]
![image](https://github.com/coder/coder/assets/10648092/ee04a77a-ef48-45a7-986d-14eb0c46863e)
Given our design of the workspace page, the `coder_metadata` items look outdated. It would be nice to redesign how we display them.

**Comment by matifali** [comment]
Related to #11837.

**Comment by bpmct** [comment]
We'll likely do a redesign of this page at some point but are trying to reduce issues in tracker
