### ISSUE TITLE
Shared Ports: share ports with specific users

### ISSUE THREAD

**Issue by matifali** [coder/coder#12651]
Related to #11201

**Comment by bpmct** [comment]
We do not plan on doing this this year. We plan on keeping sharing group-based. Live share can be used to share with specific users per-session

**Comment by matifali** [comment]
This can still be useful for pair programming in air-gapped restricted enterprise environments, as liveshare is not P2P and depends on MS servers.

Or a Coder VSCode/JetBrains extension/plugin to achieve the same P2P.

**Comment by matifali** [comment]
duplicate of #11201
