### ISSUE TITLE
Replace Jest with Vitest

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#12683]

**Comment by mtojek** [comment]
@BrunoQuaresma What is the status of this issue? I can't see the scope.

**Comment by BrunoQuaresma** [comment]
I started this but after migrating to Vite I started to get a bunch of errors in the tests. I fixed a few but I was not able to complete the task. Here is the branch if you want to take a look https://github.com/coder/coder/tree/bq/use-vitest

**Comment by mtojek** [comment]
Thanks for the update. Do you plan to continue working on this in the future or is it paused for now?

**Comment by BrunoQuaresma** [comment]
Yes, I plan to work on this in the future for sure. It is kinda related to #11418 but not directly

**Comment by stirby** [comment]
@BrunoQuaresma I'm closing in our issue cleaning session since it's become stale. You can re-open it or add it to the umbrella issue.
