### ISSUE TITLE
Allow running a limited number of external provisioners in Coder OSS

### ISSUE THREAD

**Issue by matifali** [coder/coder#12688]
We discussed this in our February community call on Discord to allow a limited number (1-2) [external provisioners](https://coder.com/docs/v2/latest/admin/provisioners) in the OSS version. 

The OSS benefit of external provisioners is to provide ease of provisioning workspaces on any infrastructure without explicitly exposing the services to `coderd`.

An example is provisioning [LXD](https://ubuntu.com/server/docs/containers-lxd) container workspace without exposing the lxd API over network/internet and instead run an external provisioner on the same machine. 

@bpmct for comments.

**Comment by stirby** [comment]
Closed during issue cleaning, feel free to re-open.
