### ISSUE TITLE
Bug: API key always expires, even on the host

### ISSUE THREAD

**Issue by bpmct** [coder/coder#1269]
## OS Information

- OS: Debian 11 (production VM running Coder)
- Architecture:
- `coder --version`:

    ```
    root@coder-v2:~/coder# coder --version
    Coder v0.0.0-devel+1df943e Mon Apr 18 23:01:49 UTC 2022
    https:/github.com/coder/coder/commit/1df943e010cdf576fb169293db02daf93f3f268e
    ```

## Steps to Reproduce

1. Set up a Coder deployment somewhere and keep it running (or maybe this happens if you are logged in to dev.coder.com)
2. Log in to that deployment (`coder login <url>`)
3. Wait 3 days (unsure of interval), or simulate expiration somehow in the code
4. Run `coder ws ls`

## Expected

I can use a long-lived API token or session on the Coder host, or even my developer laptop.

## Actual

My key expires every 1-3 days. I'm not quite sure the interval.

```sh
$ coder ws ls
status code 401: api key expired at "2022-04-29 18:52:01.463991 +0000 UTC"
```

**Comment by Emyrk** [comment]
@bpmct is 1 week good? Meaning you have to be active within once a week. It will refresh every hour and is refreshed for 1 week.

If so we can close this from https://github.com/coder/coder/pull/1935

**Comment by bpmct** [comment]
Oh, sorry I missed this, 1 week sessions sound good 👍🏼

It may be a bit odd `sshing` into a Coder host after a few weeks and seeing the CLI session is inactive, but really not a huge deal to just follow the prompt and log in again. We can close this.
