### ISSUE TITLE
Make additional data from external auth provider available to resource coder_external_auth

### ISSUE THREAD

**Issue by MaximeNoulin** [coder/coder#12704]
While I'm setting up an instance of coder (by the way great work guys!), I wanted to auto-add the git author name and email to the workspace.

The module "Git config" (https://registry.coder.com/modules/git-config) works pretty good but the data could only come from the coder user.

I wanted to set up the variable using the external-auth account as it makes more sense to be sync with the Gitlab account then the Coder account.

For now, we can only get the access_token from the resource "coder_external_auth", but it could open a lot of feature cases to have access to data like:
- the username of the user
- the full name of the user (the one I would need in my example)

I've tried to check in the codebase how complicated it could be to add it, but I couldn't manage to find the way it has been implemented

Feel free to ask if I'm not clear on what I'm suggesting

**Comment by kylecarbs** [comment]
I think you could use [the GitLab current user data source](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/data-sources/current_user) to accomplish this.

We intentionally don't obtain extra data from the tokens because we could add so many fields that differ per provider.

**Comment by kylecarbs** [comment]
@MaximeNoulin, it might look something like this:

```tf
data "coder_git_auth" "gitlab" {
  id = "gitlab"
}

provider "gitlab" {
  token = data.coder_git_auth.gitlab.access_token
}

data "gitlab_current_user" "user" {}

resource "kubernetes_pod" "dev" {
  name = data.gitlab_current_user.user.name
}
```

**Comment by MaximeNoulin** [comment]
@kylecarbs that would be awesome but it seems that we can't use datasource data to configure a provider as it's loaded by terraform at first (unless I'm mistaken)

**Comment by kylecarbs** [comment]
@MaximeNoulin I believe you're mistaken. I've done this pattern before. You cannot use resources to configure a provider, but you can data sources.

**Comment by MaximeNoulin** [comment]
Are you sure? I've tried it for the past few hours and I couldn't make it work

And then I found this doc on terraform documentation: https://developer.hashicorp.com/terraform/language/providers/configuration

"You can use [expressions](https://developer.hashicorp.com/terraform/language/expressions) in the values of these configuration arguments, but can only reference values that are known before the configuration is applied. This means you can safely reference input variables, but not attributes exported by resources (with an exception for resource arguments that are specified directly in the configuration)."

**Comment by kylecarbs** [comment]
@MaximeNoulin just tried it.

![image](https://github.com/coder/coder/assets/7122116/14d86dfa-1a60-48be-b7ad-d8e8b73f6b17)

Exact code:

```tf
terraform {
  required_providers {
    gitlab = {
      source = "gitlabhq/gitlab"
      version = "16.9.1"
    }
        coder = {
      source = "coder/coder"
      version = "0.18.0"
    }
  }
}

data "coder_external_auth" "test" {
    id = "gitlab"
}

provider "gitlab" {
    token = data.coder_external_auth.test.access_token
}

data "gitlab_current_user" "user" {}
```

**Comment by MaximeNoulin** [comment]
Well I'm getting crazy here ahah

I've tried:
- to export the access_token in a coder_env to be absolutely sure there is a token (and I've got one)
- I've created a new template with the button "Create Template" > "From scratch", add your code, and try to build it, but it refuse to build (as I guess there is no external auth token when building the template)

To be able to build the template, I had to use some tricks so that it won't call gitlab unless he has a token

```terraform
provider "gitlab" {
  early_auth_check = false
  token = coalesce(data.coder_external_auth.gitlab.access_token, "-") 
}

data "gitlab_current_user" "me" {
  count = length(data.coder_external_auth.gitlab.access_token) > 0 ? 1 : 0
  depends_on = [ data.coder_external_auth.gitlab ]
}
```

I got the error
```
Error: unable to extract iid from global id "". Was looking for an integer after the last slash (/).
```

And the error seems to be the same if I force "-" as a token

**Comment by kylecarbs** [comment]
*Super* weird. You could always just use the HTTP data provider and make the call yourself... but that's kinda weird.

```tf
data "http" "example" {
  url = "https://gitlab.com/api/v4/user"

  request_headers = {
    Authorization = "Bearer ${data.coder_aexternal_auth.gitlab.access_token}"
    Accept = "application/json"
  }
}
```

**Comment by MaximeNoulin** [comment]
Thanks a lot @kylecarbs i'll do that then
