### ISSUE TITLE
HTTP_PROXY settings block app proxying

### ISSUE THREAD

**Issue by deansheather** [coder/coder#12703]
App proxying over internal tailnet IPs gets influenced by HTTP proxying settings on the `coderd` pod. HTTP proxy settings should not influence these connections as they happen over tailnet and aren't real TCP connections.

Coder should still support HTTP_PROXY settings for other connections, just not for connections within tailnet as proxies will not be able to route to them.

You can avoid this temporarily if you use HTTP proxy settings by setting `NO_PROXY=::/0` to disable proxying to IPv6 addresses (which we use for tailnet connections).

Original issue #12292

**Comment by sreya** [comment]
https://github.com/coder/coder/pull/12875
