### ISSUE TITLE
Non-pinned versions of the Terraform provider to Coder breaks V2

### ISSUE THREAD

**Issue by misskniss** [coder/coder#1271]
v2 is currently broken due to non-pinned versions of the Terraform provider to Coder. This PR pins them, but I assume we'll do something later on to force a version from Coder itself.

**Comment by spikecurtis** [comment]
I'm confused.  There is a comment that this is fixed by #1238 but

1. If that is true, why is this issue still open?
2. #1238 appears to be about agent urls and tokens, not about pinning terraform version.

Help?

**Comment by misskniss** [comment]
We ill cover this in Grooming. I agree about the confusion here. Maybe it was me typing the wrong issue number?

**Comment by misskniss** [comment]
Closing this per conversation with Kyle. This is likely to confuse people right now.
