### ISSUE TITLE
Optional external auth blocking workspace create

### ISSUE THREAD

**Issue by oldsj** [coder/coder#12719]
When trying the new [optional param](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/external_auth#optional) in `coder_external_auth`, (with Github) I am unable to create a workspace if I have not authenticated with Github. The blue 'Create Workspace' button does not work, even though all other required parameters have been set.

```
terraform {
  required_providers {
    coder = {
      source  = "coder/coder"
      version = "0.18.0"
    }
...
```

```
data "coder_external_auth" "github" {
  # Matches the ID of the git auth provider in Coder.
  id       = "primary-github"
  optional = true
}
```
<img width="245" alt="image" src="https://github.com/coder/coder/assets/12104969/4f06b76c-ea73-4cad-9824-832126ae19a8">

**Comment by BrunoQuaresma** [comment]
@oldsj do you only have GitHub set as external auth?

**Comment by oldsj** [comment]
@BrunoQuaresma yes:
```
    - name: CODER_EXTERNAL_AUTH_0_ID
      value: primary-github
    - name: CODER_EXTERNAL_AUTH_0_TYPE
      value: github
   ```
   
   And that's the only external auth I have set. If I do auth with it then the workspace creates fine.

**Comment by aslilac** [comment]
looks like this was some crossed wires in 2.9.1. thanks for reporting!

**Comment by oldsj** [comment]
Thanks for this feature and for the quick fix!
