### ISSUE TITLE
AlecAivazis/survey is no longer maintained

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#12720]
https://github.com/AlecAivazis/survey currently shows this message:

![image](https://github.com/coder/coder/assets/373762/d7b2b1fd-6505-4fae-8526-cf9990981934)

We should consider migrating to another library. We only use it in `cli/cliui/select.go` at present, so it shouldn't be a very heavy lift.

**Comment by stirby** [comment]
We do monthly issue cleaning where we close tickets that sit too silently in the backlog. If you're passionate about executing on this, you're welcome to re-open.

**Comment by Emyrk** [comment]
I reopened this. We are currently using a deprecated library for rich parameters and custom roles. Cli prompting has become a UX flow for our cli and should be using a maintained library if it is an easy lift.

**Comment by Emyrk** [comment]
An example of an issue with the existing `survey` package: https://github.com/coder/coder/pull/13885

**Comment by a0m0rajab** [comment]
To see where the related library have been used, you can check this link: 

https://github.com/search?q=repo%3Acoder%2Fcoder+github.com%2FAlecAivazis%2Fsurvey&type=code
