### ISSUE TITLE
Warn about using old/removed/invalid experiments

### ISSUE THREAD

**Issue by matifali** [coder/coder#12725]
We should warn users if they are using old experiments which don't exist anymore (removed or promoted). An example is `moons` that was to enable  workspace proxies which is now GA and is not needed anymore.

Optionally we can also display warnings as toasts/tooltips on the invalid experiments on the `/deployment` page. 

[Slack Message](https://codercom.slack.com/archives/C04M9CNGHGF/p1711116529227839?thread_ts=1711116317.374119&cid=C04M9CNGHGF)

**Comment by mtojek** [comment]
Hey @dannykopping, it might be worth adding some context why this issue is blocked.

**Comment by mtojek** [comment]
Yeah, definitely _in progress_ :) Let's see if @Parkreiner can help with the review 👍
