### ISSUE TITLE
Add option to hide ports from listening ports dialog

### ISSUE THREAD

**Issue by tpambor** [coder/coder#12722]
Hello,

it would be helpful to be able to exclude ports from the listening port dialog of the workspace page. This would be beneficial for workspaces where some processes need to communicate solely with each other within the container.

Having the option to specify a list of ports to exclude in the Terraform file, the dialog could be kept focused on relevant ports.

**Comment by matifali** [comment]
We should do it. @f0ssel. 
We can do it as a dismiss button so that the port doesn't show up again.

**Comment by stirby** [comment]
Hey @tpambor, we're bringing Sharable ports #11486 into GA soon. It will add the ability to 'pin' ports in this UI and a scroll bar for the listening ports.

It can currently be enabled as an experiment in 2.9/2.10.

This should solve your navigation problems. Feel free to comment there if you disagree.
