### ISSUE TITLE
Coder's /oauth2 route overrides app's route

### ISSUE THREAD

**Issue by alasdairtran** [coder/coder#12736]
It looks like recently, Coder introduced a new route handler for `/oauth2` in #12240 which conflicts with our own app's route. In our development server, we set up an Ory Hydra's OAuth2 server in the backend and create a Coder app pointing to it. When logging in from our frontend, our login page first makes a request to:

```
https://hydra--main--workspace--username.coder.example.com/oauth2
```

where we've set up `*.coder.example.com` as our `CODER_WILDCARD_ACCESS_URL`

It used to work normally before #12240 was merged. Unfortunately, Coder now intercepts the request and displays an error message:

```
{
"message": "OAuth2 provider is under development."
}
```

Is it possible to disable Coder's built-in `/oauth2` route? More generally, I feel that Coder shouldn't intercept any paths under the wildcard access URL.

**Comment by Emyrk** [comment]
This was fixed here: https://github.com/coder/coder/pull/12732

I made sure this does not happen again: https://github.com/coder/coder/pull/12812
