### ISSUE TITLE
Dotfiles usage docs for users

### ISSUE THREAD

**Issue by misskniss** [coder/coder#1274]
As a user I would like to know how to use my personal dot files with V2 since we are not initially supporting them the way we do for V1.

**Comment by f0ssel** [comment]
@bpmct @jsjoeio Could we get something in the docs or examples so we can close this out?

**Comment by bpmct** [comment]
Yeah, apologies, PR is out. Hoping to work better with engineering sprints to avoid delays like this.

**Comment by bpmct** [comment]
Closed as completed by #2046
