### ISSUE TITLE
Deprecate gauge metrics named like counters

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#12744]
`coderd_oauth2_external_requests_rate_limit_total` and `coderd_api_workspace_latest_build_total` are both gauges, but use the `_total` suffix which is usually used to indicate a counter, as described by the prometheus [documentation on naming](https://prometheus.io/docs/instrumenting/writing_exporters/#naming:~:text=_total%20is%20a%20convention%20for%20counters%2C%20you%20should%20use%20it%20if%20you%E2%80%99re%20using%20the%20COUNTER%20type.).

While this is not strictly a problem, it may lead to users incorrectly assuming they can perform aggregations on these metrics rather than just using their current value; aggregations such as `rate` on gauges make no sense.

I'd suggest that we deprecate these metric names, export another metric without the `_total` suffix alongside them, and mark the original metrics for removal in the next major release. _IMHO metrics are part of the API surface, and therefore should be treated in a semver-observant manner._

**Comment by snark87** [comment]
Is this issue free to take as the first contribution?

**Comment by dannykopping** [comment]
@snark87 go ahead 👍 I've assigned it to you
Thank you!
