### ISSUE TITLE
VSCode Cloud Changes (Sync)

### ISSUE THREAD

**Issue by brxyxn** [coder/coder#12756]
Hi! I'm just exploring this awesome tool, and I really love it, using it to create my dev containers as a freelancer it's really nice. However, I'd like to keep my settings and sync the Web IDE (vscode), but this is not possible.

I researched on the web looking for a possible solution and found nothing. I think this should be something related to the Template I'm using (not sure), or maybe this was not an intended feature.

![image](https://github.com/coder/coder/assets/8520122/4549bf35-f3e3-4986-8f66-5796b72ccd71)

If this is not an issue please help me with any suggestions or examples. Thanks!

OS: Ubuntu 22.04
Coder version: Coder v2.9.1+2a2fd70

**Comment by kylecarbs** [comment]
You should use [VS Code Web](https://registry.coder.com/modules/vscode-web) instead of code-server to do this!

Unfortunately, you'll need subdomain enabled to do this, but then you can use official extensions!
