### ISSUE TITLE
Coder randomly deleted our VM instances causing a severe downtime on our usage

### ISSUE THREAD

**Issue by kush-work** [coder/coder#12758]
Hello team;

We are evaluating coder for our in-house usage of VM management platform but we have been facing a occasional yet serious bug which is hindering our evaluation.

Coder while stopping workspaces randomly deleted the EC2 machine which also deletes our relevant EBS volumes causing loss of data many times. I tried to search the past issues but can't find any such issue; it would be really helpful if someone can assist on what is going wrong here.

<img width="1278" alt="Screenshot 2024-03-26 at 1 44 01 PM" src="https://github.com/coder/coder/assets/99680990/cd91e479-aa58-4deb-b1ca-23cbd34a3087">

**Comment by mtojek** [comment]
Could you please share the template you're using? It can help us see if there is any issue in your configuration. Also, was autostart/autostop option enabled?

**Comment by mtojek** [comment]
Here are some actions you can take:

1. Review Coder examples for AWS: [aws-container](https://github.com/coder/coder/blob/main/examples/templates/aws-container/main.tf) or [aws-linux](https://github.com/coder/coder/blob/main/examples/templates/aws-linux/main.tf)

As you can see, `aws_instance` is missing `lifecycle` constraint:

```
  lifecycle {
    ignore_changes = [ami]
  }
```

... which may result in replacing the machine.

2. As stated in [Bulletproofing](https://coder.com/docs/v2/latest/templates/resource-persistence#-bulletproofing), consider enabling `lifecycle` > `ignore_changes` = `all` for resources that should not be recreated. 

I don't see any obvious bug in our examples, but maybe I'm missing something @matifali ?

**Comment by kush-work** [comment]
> Here are some actions you can take:
> 
> 1. Review Coder examples for AWS: [aws-container](https://github.com/coder/coder/blob/main/examples/templates/aws-container/main.tf) or [aws-linux](https://github.com/coder/coder/blob/main/examples/templates/aws-linux/main.tf)
> 
> As you can see, `aws_instance` is missing `lifecycle` constraint:
> 
> ```
>   lifecycle {
>     ignore_changes = [ami]
>   }
> ```
> 
> ... which may result in replacing the machine.
> 
> 2. As stated in [Bulletproofing](https://coder.com/docs/v2/latest/templates/resource-persistence#-bulletproofing), consider enabling `lifecycle` > `ignore_changes` = `all` for resources that should not be recreated.
> 
> I don't see any obvious bug in our examples, but maybe I'm missing something @matifali ?

I will make these changes ASAP; we extended the default template which was provided when you install coder. Maybe we can change those default templates to have these changes or we were at older version of coder when we installed it?

**Comment by johnstcn** [comment]
FWIW we updated the `aws-linux` example template to include `ignore_changes = [ami]` in #10773.

**Comment by kylecarbs** [comment]
Going to close this for now. It seems likely to be an issue with the template, but I'm sorry you had to go through this pain!

Please comment if the `lifecycle` doesn't fix the problem (or if it does)!

**Comment by kush-work** [comment]
@kylecarbs @johnstcn Thanks a lot for the help; now our disks are not deleted that often, and things are working fine.
However, there is another substantial problem that we have started to face, whenever we release new template versions & when developers updates the workspace to use the latest version, their coder home folder in the VM is often deleted. We then need to manually create the user coder in the EC2 machine & then the VM starts working, but during this, all the data which the user has inside the coder home folder gets deleted, hindering our usage.
Do we have any solution for this problem?

**Comment by johnstcn** [comment]
Hey @kush-work , if your template still looks like what you posted above, it appears that all data is going into the `aws_instance.dev.root_block_device`. 

I'd recommend:
- Adding a separate EBS volume to the template which you would mount under `/home/coder` -- this would be completely separate to the underlying AMI. This is similar to how the `kubernetes` template works. If something then changes in the underlying AMI, the user data should not be impacted.
- Creating a custom AMI where you pre-create the coder user and perform any other customizations you might need for your development environment. 

You might also be interested in checking out our community Discord https://discord.gg/coder for other folks using AWS templates.
