### ISSUE TITLE
bug: Misleading error message when a Coder workspace tries to pull down a repo that the user does not have permission to access

### ISSUE THREAD

**Issue by Parkreiner** [coder/coder#12765]
Was running into this issue last week when doing coding challenges for applicants to get hired by Coder. Not sure if this is something that would be more frontend- or backend-focused, though. Will try to look into this myself later this week

## Problem
- Sometimes, a Coder workspace is configured to auto-pull a specific GitHub repo. However, while a user can be authenticated with GitHub within Coder, they still might not have access to the repo
   - We ran into this with candidates – they were authenticated, but (1) they weren't part of the Coder GitHub organization, and (2)  they hadn't yet accepted the invitation to be a collaborator for the repo
- When this happens, the workspace will encounter a fatal error, and will stop pulling things down. However, there are additional error indicators in the UI mentioning Agents.
   - From what I can tell, there isn't anything wrong with the agent logic, though – this is entirely an issue with the workspace not being able to pull down the repo
- I looked at the [troubleshooting docs](https://coder.com/docs/v2/latest/templates/troubleshooting), and they don't make any mention of this being a potential issue

![Screenshot 2024-03-26 at 11 34 58 AM](https://github.com/coder/coder/assets/28937484/bf782cff-7b4c-4859-bd1d-2bfcba5cdf83)

## Steps to reproduce
These steps apply only for Coder employees with permission to access dev.coder.com and the repo for the [Fullstack Coder challenge](https://github.com/coder/coder-fs-challenge)

1. Have a separate GitHub account ready that is not part of the Coder organization (reach out to me on Slack if you want the login info for a test user I made)
2. Verify that the user has not accepted any invitations to be a collaborator for the FS Challenge repo (they can have the invitation – they just shouldn't accept it yet)
3. Log into the candidate@coder.com account on dev.coder.com (again, message me on Slack if you need the login info)
4. Make sure that the Coder account is authenticated with the test user
5. Create a new workspace with the `Candidate Template` template
6. Wait for the workspace's pull command to fail

**Note:** If you need to use the candidate account to debug anything, please reach out to @Kira-Pilot and me first, so we can coordinate. We have a slight lull right now, but we are still using this account for giving applicants their coding challenges.

**Comment by bpmct** [comment]
This is the message `git` leaves when the user does not have permission to a repo. Here is some reading on why: https://meta.stackexchange.com/a/258764

If we wanted, we could wrap our git clone module to check if the clone had a non zero exit code and show a different error message. If we did, it should probably be opt-in since some folks may be surprised to see a different response from git
