### ISSUE TITLE
docs: add troubleshooting guide

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12774]
Add a "Troubleshooting Guide" under https://coder.com/docs/v2/latest/guides

This should link to the various extant troubleshooting sections in the docs:
- https://coder.com/docs/v2/latest/templates/troubleshooting
- https://coder.com/docs/v2/latest/install/docker#troubleshooting
- etc.

Additionally, it should provide information on using `coder suport bundle` (https://coder.com/docs/v2/latest/cli/support_bundle#support-bundle) to aid diagnosing issues:
- What information is collected
- What it can troubleshoot
- What it cannot troubleshoot

**Comment by bpmct** [comment]
In this doc, can we also explain what data the bundle collects and doesn't collect so we can link to it to help folks feel  more comfortable running it?

**Comment by bpmct** [comment]
Just leaving a note here, let's also tag @ericpaulsen as a reviewer

**Comment by bpmct** [comment]
@johnstcn have you already started on this? I'm happy to take a stab

**Comment by johnstcn** [comment]
@bpmct oops, forgot to close this out. Fixed in https://github.com/coder/coder/pull/12931 but please feel point out any issues / omissions you see there.
