### ISSUE TITLE
feat: support bundle: collect deployment information from multiple coderd instances

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12776]
Part of https://github.com/coder/coder/issues/12160

We currently only connect to `CODER_ACCESS_URL` and fetch data from whatever coderd replica answers the call.

A heterogeneous deployment could cause any number of issues that might not be detected.
When creating a support bundle, fetch relvant deployment details from all running coderd replicas.

**Comment by bpmct** [comment]
Going to close this as we want to primarily leverage feedback from support/customers on prioritization for the support bundle
