### ISSUE TITLE
coder cli login with goteleport

### ISSUE THREAD

**Issue by gallois** [coder/coder#12777]
I'm running coder in EKS and accessing it through [teleport](https://goteleport.com/). When trying to `coder login URL`, the browser opens, but the token I get is said to be invalid. To work around this issue, I have to start a local proxy, which handles the custom SSL settings

I was wondering if it would make sense to add options for passing the certs and keys through the CLI, perhaps as env vars to solve the problem without the need for using a proxy.

Let me know if that sounds reasonable and if there's anything else I can help with

**Comment by kylecarbs** [comment]
Go will respect the local certificate store.

Can you add your certificate to your machine? Then you wouldn't have to proxy. Go also supports `SSL_CERT_DIR` and `SSL_CERT_FILE`: https://go.dev/src/crypto/x509/root_unix.go.

**Comment by gallois** [comment]
Adding it to the machine might be a bit cumbersome, as they get regenerated by teleport. The latter option looks appealing, but I couldn't get it to work. Teleport's app proxy generates two files, a certificate and a key, while also presenting a `curl` example for it, which looks something like:
```
curl \
  --cert path_to_generated_cert \
  --key path_to_generated_key \
  url
```
This, unsurprisingly, works. I didn't find a way to use the key as an env var, though. I've also tried concatenating the certificate and the key, `curl` happily takes it, but it didn't work with coder's cli, where I got the same issue as before

Thanks for the super quick answer!!

**Comment by kylecarbs** [comment]
`SSL_CERT_FILE` pointing to the generated certificate didn't work?

**Comment by gallois** [comment]
it didn't unfortunately :( I get the same results:
- `build_info` prints out some errors/warnings:
```
build info: GET 'redirected_url' : unexpected status code 200: unexpected non-JSON response "text/html; charset=utf-8"
(...) some HTML (...)
```
- And `That's not a valid token!` when I paste the token

**Comment by kylecarbs** [comment]
Do you have a proxy in front? This isn't a certificate issue... your Coder instance simply is returning HTML instead of the expected JSON.

**Comment by gallois** [comment]
We use teleport to access coder. If I try to `coder login` to it directly, using the same URL I use for the browser. I get the error. My workaround so far is to use `tsh proxy app coder` and `coder login localhost:PORT_FROM_PROXY`, but that's a bit cumbersome. I can do `tsh apps login coder`, which generates the certificates for me and allows me to at least use the same URL I use for browsing, but that requires me to use the certificate and key it provides. `curl` works fine for that, but I didn't find a way to make it work with the coder cli

**Comment by bpmct** [comment]
I believe we solved this on a call! Let me know if I am mistaken

**Comment by joefitzgerald** [comment]
@bpmct what was the solution? We are running into the same issue.
