### ISSUE TITLE
Write an RFC about workspaces states

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#12772]
Currently we have some naming inconsistencies which cause confusion & suboptimal UX.

The RFC should include:

- definitions of each possible state (and entry/exit transitions)
  - _optionally create a flow diagram to illustrate, which can be copied to documentation_
- identify inconsistencies in UIs (API, CLI, browser UI) and propose a ubiquitous language
- discuss challenges or impediments to making these changes everywhere
- discuss possibility of implementing a finite state machine on the backend to facilitate these state transitions and implement strong rules & callbacks in a central codepath

**Comment by dannykopping** [comment]
For example:

When I visit the _Settings_ page of a workspace and then view _Parameters_, I see this view:

![image](https://github.com/coder/coder/assets/373762/5ca5abfb-31cc-4a6b-9aba-9c8b016d1e94)

**Submit** gives no indication about what will happen next to the workspace. Will it be rebuilt? What does rebuilt mean?

In reality, button is sending a request to [`/api/v2/workspaces/{workspace}/builds`](https://coder.com/docs/v2/latest/api/builds#create-workspace-build); this may not be immediately clear to the user at first glance. A "build" is comprised of a stop (`terraform apply -var start_count=0`) and a subsequent start (`terraform apply -var start_count=1`) which will delete any ephemeral parameters.

---

The closest analog to this _Settings_ page on the CLI is the [`restart`](https://coder.com/docs/v2/latest/cli/restart) command.

`coder restart <workspace> --always-prompt=true` will bring up a UI allowing us to reconfigure parameters:

![image](https://github.com/coder/coder/assets/373762/b6b06bc3-fa57-4bf2-b165-080352f57408)

The terminology across these two workflows is inconsistent, but they do the same thing.

A user might reasonably expect that `restart` simply stops and starts a docker container / VM / whatever they're using, but in reality it's more like "destroy" and "rebuild".

**Comment by dannykopping** [comment]
https://www.notion.so/coderhq/Workspace-Activity-4ff78c70d38b400c83f77d7f0a513a98?pvs=4 will be useful for this as well.

**Comment by stirby** [comment]
@dannykopping Can you create a draft RFC internally instead (avoiding sensitive information)? Then, you could make it public and link it in issues where you see inconsistency in workspace state. I appreciate you being public with the plans. 

Just closing this because I don't think it fits in the tracker. Also feel free to migrate to one of the internal trackers.
