### ISSUE TITLE
feat: No way to fetch external auth refresh token

### ISSUE THREAD

**Issue by ns-mkusper** [coder/coder#12787]
Version: [`v2.9.1+2a2fd70`](https://github.com/coder/coder/commit/2a2fd706b5b45e48788bf269a93d4c592ed0eec3)

There is currently no way (or at least not via the Coder CLI or API) to fetch the refresh token for an external auth provider in Coder. I have an external app I am trying to integrate with coder, and its config files require **both** the access token and the refresh token as a starting point.

A simple solution to me seems to be to add the `refresh_token` to the [GET /workspaceagents/me/external-auth](https://coder.com/docs/v2/latest/api/agents#get-workspace-agent-external-auth) response.

**Comment by matifali** [comment]
cc: @Emyrk @kylecarbs

**Comment by kylecarbs** [comment]
@matifali we will do this but should not do the other.

**Comment by Emyrk** [comment]
I feel like the cli should be able to expose the user external-auth api endpoints.

The workspace agent endpoint is a bit limiting in the fact it's designed for `ASK_PASS` style prompting.

We could add `ls` and other commands using the user apis.

**Comment by ns-mkusper** [comment]
If we could fetch the refresh token via the coder CLI that would be great.

**Comment by Emyrk** [comment]
@kylecarbs brought up a good point. If the refresh token is exposed, it can be used to generate new tokens outside Coder, leaving coder with a stale refresh token.

What application specifically is requesting this? Maybe there is a workaround on that side?

**Comment by ns-mkusper** [comment]
After a bit of research I found we manage a wrapper around an API client library that is essentially the app we're trying to integrate, and that can be easily extended to use the coder CLI to get the updated access token instead of the client library which calls `/v1/token` itself to refresh tokens. 

That library assumes the oauth2 apps are configured with a PKCE challenge rather than client secrets, so the requests from it to refresh the token itself fail.

At this point I'm fine to close this issue, but I'm not positive that this wouldn't be useful for others. As for the security concerns, wouldn't a normal non-admin user only be able to view their own refresh token?

**Comment by Emyrk** [comment]
If we did expose a `refresh_token` it would also break any other workspaces that are sharing the same external auth app. Since 1 workspace "takes charge" of it.

I'm curious why the refresh token is required to auth into your app anyway :thinking:. Feels strange, unless it is a clientside app that is managing some oauth state.

**Comment by ns-mkusper** [comment]
> Feels strange, unless it is a clientside app that is managing some oauth state.

It is indeed a client-side app that is managing Oauth state on its own.

**Comment by Emyrk** [comment]
Are you able to share what that app is? @ns-mkusper

**Comment by ns-mkusper** [comment]
Yep, this is the app in question: https://github.com/rigetti/qcs-api-client-python

**Comment by Emyrk** [comment]
@ns-mkusper I see. I think this is a general problem we might run into more often. Where a client app wants to manage the token lifecycle.

I think allowing Coderd & a clientside app to manage a token is not a can of worms I'd like to open.

A better approach would be to generate a fresh token for each workspace. The external auth token could be used by the startup scripts to create a new one. Cleaning up tokens might not be trivial if they have a long TTL.

----

As a summary though, I am going to close this issue. I appreciate the communication of the challenges you are facing. If this arises for other apps and clients, I'll merge things into a larger ticket :+1:
