### ISSUE TITLE
Doc: Documentation on how to run a workspace proxy via `systemctl`

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#12783]
Current docs describe how to setup a Workspace Proxy via the CLI:

- https://coder.com/docs/v2/latest/admin/workspace-proxies

Some docs should be added like:

```bash
# Edit this file /etc/coder.d/coder-workspace-proxy.env
sudo systemctl enable --now coder-workspace-proxy
```

PR #12810

**Comment by kylecarbs** [comment]
We'll definitely do this. Not sure why we don't have a systemd unit for these, but we should.

For whoever implements, we should bundle a "coder-workspace-proxy" service file with our deb distribution, but not enable it by default.

**Comment by michaelbrewer** [comment]
Thanks @kylecarbs this will greatly simplify setup :)

**Comment by kylecarbs** [comment]
@michaelbrewer turns out we already have this!

```
sudo systemctl enable --now coder-workspace-proxy
```

We'll add docs though... that is missing!

**Comment by michaelbrewer** [comment]
Thanks @matifali  for running `make fmt` , i did manage to run `prettier --write` to manual fix it later, but will at how to build the coder dev environment right ;)
