### ISSUE TITLE
terraform login does not open native web browser

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#12808]
terraform login does not launch web browser when in code-server, vscode or vscode-web, like how coder login other tools

After some digging, it looks like this should be fixed on the terraform cli side:

related bug on the terraform side : [#34902](https://github.com/hashicorp/terraform/issues/34902)

**Comment by ericpaulsen** [comment]
thanks @michaelbrewer - since its on the Terraform side, I'll close out.
