### ISSUE TITLE
Add an `e2e` test that uses a real TF provisioner

### ISSUE THREAD

**Issue by sreya** [coder/coder#12821]
Add a test to `site/e2e` that uses a real TF provisioner. Ideally uses the runner's Docker daemon. May need to investigate using our own runner otherwise.

**Comment by Emyrk** [comment]
I ended up working on getting `--ui`, enterprise testing, and generally getting e2e more stable.

**Comment by Emyrk** [comment]
Followup issue: https://github.com/coder/coder/issues/13163
