### ISSUE TITLE
JFrog Xray integration

### ISSUE THREAD

**Issue by matifali** [coder/coder#12838]
## Context

Coder recently published a [guide](https://coder.com/docs/v2/latest/guides/xray-integration) on how to integrate with [JFrog Xray](https://jfrog.com/xray/) to scan workspace images. That guide uses [`coder-xray`](https://github.com/coder/coder-xray) utility which can be deployed to scan all workspaces in a given K8s `namespace`. This works great but has limitations.

- Only works for K8s-based workspaces
- Requires deploying `coder-xray` as a service

## Suggested solution

Coder makes use of `terraform` as the provisioner to create workspaces. This gives Coder flexibility to provide a range of computing, storage, and network resources for any platform with a terraform provider. While researching, I came across [`xray-terraform-provider`](https://registry.terraform.io/providers/jfrog/xray/latest/docs/data-sources/artifacts_scan) which can be used to fetch the xray-scan results of an artifact. (Thanks to @alexhung for adding this feature.)

This has the added benefit of enabling the integration of all types of workspaces where the image is being sourced from JFrog Artifactory. (See this [guide](https://coder.com/docs/v2/latest/guides/artifactory-integration) on enabling Artifactory integration.)

The result then can be displayed as [`coder_metadata`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/metadata) resource on the workspace page.

```tf
provider "xray" {
  url = "https://jfrt.cdr.dev/xray"
  access_token = "TOKEN"
  check_license = false
}

data "xray_artifacts_scan" "image_scan" {
  repo = "docker-local"
  repo_path = "/codercom/enterprise-base:local"
}

locals {
  vulnerabilities = data.xray_artifacts_scan.image_scan.results[0].sec_issues
}

resource "coder_metadata" "workspace_info" {
  count       = data.coder_workspace.me.start_count
  resource_id = "WORKSPACE_RESOURCE_ID"
  item {
    key   = "Critical"
    value = local.vulnerabilities.critical
  }
  item {
    key    = "High"
    value = local.vulnerabilities.high
  }
  item {
    key   = "Medium"
    value = local.vulnerabilities.medium
  }
  item {
    key   = "Low"
    value = local.vulnerabilities.low
  }
}
```

Which renders as 
![image](https://github.com/coder/coder/assets/10648092/4a521342-1ca8-4aa1-9404-c3f4e1055609)

### TODO

- [ ] xray-integration(docs): update the [guide](https://coder.com/docs/v2/latest/guides/xray-integration) to recommend this terraform method instead of using `coder-xray`
- [ ] coder/modules#244
- [ ] #12839

**Comment by matifali** [comment]
Optionally, a module can also be published that adds the metadata to any workspace given the image repo, name, and xray-url.

```tf
module "coder-xray" {
  source         = "registry.coder.com/modules/coder-xray/coder"
  version        = "x.x.x"
  agent_id       = coder_agent.example.id
  xray_url       = "https://example.jfrog.io"
  image          = "docker-local/codercom/enterprise-base:latest"
}
```

**Comment by bpmct** [comment]
Will reopen as we get more requests for this

**Comment by matifali** [comment]
We have seen a request to disable the builtin integration.
> BTW, another thing we see on every page load is a 404 from /api/v2/integrations/jfrog/xray-scan. It appears to be harmless, but since we don't use this integration (I assume?), is there a way to disable it.

**Comment by matifali** [comment]
> xray-integration(docs): update the [guide](https://coder.com/docs/v2/latest/guides/xray-integration) to recommend this terraform method instead of using coder-xray

@DevelopmentCats can you also make a PR for the docs?
