### ISSUE TITLE
Group display name removed when user added to or removed from group

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#12848]
(Version 2.9.1): Each time a user is added or removed to/from a group then the group display name is removed. It is probable that this endpoint isn't implementing patch requests correctly and instead requiring that the entire request object is sent down. Perhaps we are forgetting to set the group display name.
~We should fix this and add an E2E test.~ see comment below

**Comment by BrunoQuaresma** [comment]
fyi: I'm adding e2e tests for this scenario as part of the https://github.com/coder/coder/issues/12506 issue.

**Comment by f0ssel** [comment]
@BrunoQuaresma 's changes fixed the issue. We actually did handle it correctly on the backend, but the frontend was sending an explicit override of `""` to wipe the name. Think this is good to close with his fixes in place now.
