### ISSUE TITLE
Document activity based behavior of workspaces

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#12853]
Just document activity vs last_used_at vs insights. Status quo situation.

Document here: https://www.notion.so/coderhq/Workspace-Activity-4ff78c70d38b400c83f77d7f0a513a98

- https://github.com/coder/coder/issues/12304
- https://github.com/coder/coder/issues/12012
- https://github.com/coder/coder/issues/11986
- https://github.com/coder/coder/issues/11812

**Comment by Emyrk** [comment]
Current brain dump: https://www.notion.so/coderhq/Workspace-Activity-4ff78c70d38b400c83f77d7f0a513a98

**Comment by dannykopping** [comment]
@Emyrk perhaps we can link up at some point; I'm also thinking along these lines with https://github.com/coder/coder/issues/12772. If we had a state machine that was invoked by various operations, we could centralise the logic for updating stats; we'd also have a model which would be easier to understand by devs & users alike.
