### ISSUE TITLE
Helm chart should support topology spread constraints

### ISSUE THREAD

**Issue by psprings** [coder/coder#12904]
## Summary

The Coder Helm chart lacks fine-grained control for spreading Coder control plane Pods across failure domains such as region or zone and should be enabled by supporting `topologySpreadConstraints `.

<https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/>

## Motivation 

To ensure that the control plane is highly available, it should be distributed across regions/zones. At present, the [Coder control plane `Deployment`](https://github.com/coder/coder/blob/main/helm/libcoder/templates/_coder.yaml) supports [`tolerations`](https://github.com/coder/coder/blob/11123018a282cceb20c38f5524f15e2b48c7ddb3/helm/libcoder/templates/_coder.yaml#L39) and [`affinity`](https://github.com/coder/coder/blob/11123018a282cceb20c38f5524f15e2b48c7ddb3/helm/libcoder/templates/_coder.yaml#L35) which can be leveraged to influence how Pods are scheduled, however, `podAntiAffinity`'s single-factor targeting either doesn't guarantee spread across regions/zones or creates scheduling bottlenecks depending on if you choose `preferredDuringSchedulingIgnoredDuringExecution` or `requiredDuringSchedulingIgnoredDuringExecution`.

Topology spread constraints are considered a best practices way to accomplish this with [features](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition) like:
* `minDomains`
* `maxSkew`
* `whenUnsatisfiable`

**Comment by ericpaulsen** [comment]
hi @psprings - thank you for the feedback. i will take this on

**Comment by psprings** [comment]
Thanks for the quick response @ericpaulsen -- I'm happy to submit a PR for it if needed, just let me know.

**Comment by cmanfre4** [comment]
I'm looking for this capability in the chart as well. Any updates?

**Comment by ericpaulsen** [comment]
closed via #15168
