### ISSUE TITLE
test flake: enterprise/coderd TestEntitlements/FullLicense

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12932]
Seen here: https://github.com/coder/coder/actions/runs/8636759071/job/23677410475

Relevant logs:
```
    t.go:108: 2024-04-10 19:33:07.338 [erro]  coderd.pgcoord: failed to send coordinator delete  coordinator_id=61203490-ef90-48e4-a7c2-1fa681311603  error="sql: database is closed"
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
    t.go:99: 2024-04-10 19:33:07.339 [debu]  coderd.pgcoord: ending cleanupLoop  coordinator_id=61203490-ef90-48e4-a7c2-1fa681311603  error="context canceled"
```

**Comment by johnstcn** [comment]
Potentially similar to https://github.com/coder/coder/issues/9921 ?

**Comment by stirby** [comment]
@johnstcn closing this to clean up the tracker. Feel free to re-open if you'd like to take it. 

For context, we clean up the issues monthly. Flakes that sit idly for 2-3 months are closed.
