### ISSUE TITLE
Issue with Workspace Build Failure and Terraform Apply Error

### ISSUE THREAD

**Issue by lucine1010** [coder/coder#12953]
Version: [`v2.4.0+d19a762`](https://github.com/coder/coder/commit/d19a762589e84afd18f2245ebc03daccb53cb13f)

Dear Coder Support Team,

I hope this message finds you well. I am writing to report an issue I am experiencing with my Workspace.I am an interaction design student at Sheridan college. I have a problem using the coder ixd workspace provided by our school. I am unable to attach a screenshot, but I am encountering the following error message: "Workspace build failed" and "terraform apply: exit status 1". Despite multiple attempts to retry, I am still unable to open the Workspace. I've attached a screenshot showing the interface that I can't open.

Could you please assist me in resolving this issue? I appreciate any help or guidance you can provide.

Thank you for your attention to this matter.

Best regards,
Xinyu Lu

<img width="1332" alt="Screenshot 2024-04-13 at 12 36 55 AM" src="https://github.com/coder/coder/assets/166898653/1a483808-c122-42c4-b75a-89eeb7d71a4a">

**Comment by MrPeacockNLB** [comment]
It seems that this failure has nothing to do with coder. It seems there is something wrong with the TLS certificate to mount your home directory. Maybe it is worth to contact your administrator about that.

**Comment by stirby** [comment]
Thanks for helping out here @MrPeacockNLB!
