### ISSUE TITLE
Running helm upgrade causes a License alert

### ISSUE THREAD

**Issue by evilhamsterman** [coder/coder#12966]
When running a `helm upgrade` command to upgrade a k8s deployment of a basic Coder service in k8s, the UI will display a large red banner complaining we have "multiple replicas but high availability is an Enterprise feature"
![image](https://github.com/coder/coder/assets/59560/c335b465-d975-4b46-8ba8-64ca967482fe)

We don't have multiple replicas running, there's overlap between when the old replica and the new replica start due to Helm but after the upgrade is complete there is only a single instance running. The banner remains until we delete the current pod causing the deployment to deploy a new pod.

**Comment by kylecarbs** [comment]
Sorry about this! We'll have to fix the replica shutdown. I'll look into this!

**Comment by evilhamsterman** [comment]
Thank you for the rapid response, this looks like it is a duplicate of #8665 I'll close this in favor of that.
