### ISSUE TITLE
☂️ Improved Activity Detection 

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#12965]
This is an umbrella ticket for issues related to improving workspace activity detection and reporting.

Issues to be added once created.

Bugs related to this issue:
- https://github.com/coder/coder/issues/12304
- https://github.com/coder/coder/issues/11812
- https://github.com/coder/coder/issues/11986
- https://github.com/coder/coder/issues/12864
- https://github.com/coder/coder/issues/12012

**Comment by mtojek** [comment]
FYI Removing the umbrella issue from sprint in favor of smaller items in the issue description.

**Comment by stirby** [comment]
Closing in favor of
https://github.com/coder/coder/issues/13279
