### ISSUE TITLE
Add OSS features to the Enterprise table in docs

### ISSUE THREAD

**Issue by mreadie** [coder/coder#12973]
We should have the features in the OSS listed above the Enterprise-only features on https://coder.com/docs/v2/latest/enterprise
The list already exists on coder.com/pricing, we would just need to add it and links to the OSS features to make it complete. 
This will help with OSS adoption as well as helping Enterprise prospects and customers to understand all that's in Enterprise.

**Comment by bpmct** [comment]
Closing as we're tracking in an umbrella issue
