### ISSUE TITLE
Healthcheck failes since latest update

### ISSUE THREAD

**Issue by DuelistRag3** [coder/coder#12975]
following errors in healthcheck (nothing changed in nginx config)

`EACS03: get healthz endpoint: Get "https://example.test/healthz": dial tcp *:443: i/o timeout`

![Screenshot_1](https://github.com/coder/coder/assets/23101343/1e52a3c2-c469-4c85-85ce-24204638f3ca)

`EWS01: websocket dial: failed to WebSocket dial: failed to send handshake request: Get "https://example.test/api/v2/debug/ws": dial tcp *:443: i/o timeout`

**Comment by kylecarbs** [comment]
Your access URL is `example.test`. Are you sure that resolves to your Coder deployment?

**Comment by DuelistRag3** [comment]
yes, i access it via that url

**Comment by DuelistRag3** [comment]
> Your access URL is `example.test`. Are you sure that resolves to your Coder deployment?

i only changed it for the issue, the real one is another

**Comment by DuelistRag3** [comment]
accessing the websocket debug directly results in
`WebSocket protocol violation: Upgrade header "" does not contain websocket
unable to accept:failed to accept WebSocket connection: WebSocket protocol violation: Upgrade header "" does not contain websocket`

**Comment by stirby** [comment]
@DuelistRag3 please re-open if you still encounter issues on the [latest stable version](https://github.com/coder/coder/releases/latest).
