### ISSUE TITLE
outdated invalid parameter prevent workspace update without implicit warning 

### ISSUE THREAD

**Issue by garylavayou** [coder/coder#12983]
## Summary

After updating a workspace template's parameter, the existing workspace's corresponding parameter becomes invalid as it is out of range. This will prevent the workspace from being updated using the new version of the template.

## Details

The template has a parameter `memory`:

```terraform
data "coder_parameter" "memory" {
  name        = "Memory"
  type        = "number"
  description = "The memory limit for the container in MBs."
  mutable     = true
  default     = 4096
  icon        = "/icon/container.svg"

  validation {
    min = 2048
    max = 8192
  }
}
```
which previously have a min value of `1024` for validation, and a workspace's `memory` value is set to 1024 with the previous version of template.

After the template updates, the workspace's `memory` value becomes invalid, which prevents the workspace being updated to the new version.

### Related Logs

The following is the information from network activity records in browser.

The network request is:

```http
POST https://coderdev.com/api/v2/workspaces/7fe36e42-fea1-4bdc-9a1b-adb4bf91c364/builds
{"transition":"start","template_version_id":"abdb9fa6-4a60-4ec8-a593-6c431ac46d95","rich_parameter_values":[]}
```

The response is
```http
400 Bad Request
{
    "message": "Unable to validate parameter \"Memory\"",
    "detail": "can't validate build parameter \"Memory\": value 1024 is less than the minimum 2048"
}
```

### Coder Version

[`v2.9.0+3215464`](https://github.com/coder/coder/commit/321546474b2d1a3936e70fc9d22d028fa5080c9e).

## Suggestion

The error message should be explained to users instead of being silently ignored in the background.
If a parameter's value will become invalid, show the error response in an appropriate way to users, and let them first update the invalid value of the parameter to a valid one before update.

**Comment by mtojek** [comment]
> After the template updates, the workspace's memory value becomes invalid, which prevents the workspace being updated to the new version.

@garylavayou Use _Workspace Settings > Parameters_ to change the value accordingly, then bump up the template version. I agree that the workflow might look tangled in this case, but it isn't blocking.

**Comment by mtojek** [comment]
Resolving for now
