### ISSUE TITLE
RDP Docs improvements

### ISSUE THREAD

**Issue by mreadie** [coder/coder#13003]
There are 3 items that need to be fixed/improved on the RDP section of the Remote Desktops docs page: https://coder.com/docs/v2/latest/ides/remote-desktops#rdp-desktop

1. Need to point out that the user needs to install Coder on their local machine first. 
2. The gcp community template link is wrong (it goes to a Microsoft page) - Improvement would be to give links to templates for all 3 clouds: GCP, AWS and Azure to cover more users' needs.
3. It’s not clear where the commands listed are supposed to be run - local machine or on the workspace?

**Comment by bpmct** [comment]
Closing as we're tracking in an umbrella issue
