### ISSUE TITLE
Allow sharing Coder apps to groups or individual users

### ISSUE THREAD

**Issue by ns-mkusper** [coder/coder#13005]
We have a use case where users would like to share access to path-based applications (benign applications from a security perspective) to a limited audience. Unfortunately, it's only possible currently to share access to [all authenticated users or everyone with access to the Coder endpoint](https://registry.terraform.io/providers/coder/coder/0.6.18-rc2/docs/resources/app#share).

It would be great if we could provide either a user group we could manage or a list of users to share the app to.

**Comment by stirby** [comment]
Hello, this is a popular request. We have a long-standing tracker already so I'm going to close this one out.

Duplicate: https://github.com/coder/coder/issues/11201

Feel free to join in the discussion there!
