### ISSUE TITLE
Explore Workspace Activity RFC 

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#13004]
This sprint we are aiming to finish up the [Workspace Activity RFC](https://www.notion.so/coderhq/Unified-Workspace-Statistics-and-Activity-Detection-11cdaf2b55bc493382ecfc302ca3d6f9), which puts us in a good position to start implementation next sprint. With this in mind, we should dedicate some time this sprint to familiarizing ourselves with the RFC, defining any ambiguous areas, and sketching out a plan of attack. Outcome of this ticket could be ticket creation.

**Comment by f0ssel** [comment]
Reviewed both related RFC and left comments, and made an epic with the issues for completing this effort. https://github.com/coder/coder/issues/13146
