### ISSUE TITLE
Windows Defender detected coder-windows-amd64.exe from VSCode extension as virus

### ISSUE THREAD

**Issue by blueset** [coder/coder#13014]
Windows Defender detected `coder-windows-arm64.exe` downloaded from the Coder VSCode extension as a virus.

Details from Windows Defender:
```
VirTool:Win64/Myrddin.F!MTB

Alert level: Severe
Status: Active
Category: Tool
Details: This program is used to create viruses, worms or other malware.

Affected items:
- file: C:\Users\user\AppData\Roaming\Code\User\globalStorage\coder.coder-remote\bin\coder-windows-amd64.exe
```

**Comment by kylecarbs** [comment]
Odd that the VS Code bin was detected as a virus.

I can say with pretty high confidence it isn't one, but we should definitely be signing these if it's consistent.

**Comment by MrPeacockNLB** [comment]
Should not #359 solve this problem?

**Comment by kylecarbs** [comment]
It would for the fat binary, but we'd also have to sign the slim ones which is a bit trickier.

**Comment by matifali** [comment]
This is also causing `winget` validation to fail. 
See
1. https://github.com/microsoft/winget-pkgs/pull/150531#issuecomment-2071110594
2. https://github.com/microsoft/winget-pkgs/pull/150531#issuecomment-2071110594

**Comment by MrPeacockNLB** [comment]
Now I'm also affected. I'm unable to use local VSCode with Coder extension. As in #13047 described I see this error too.

**Comment by kylecarbs** [comment]
Working on this.

**Comment by kylecarbs** [comment]
@MrPeacockNLB are you on Windows 10 or 11?

**Comment by kylecarbs** [comment]
2.10.1 and 2.10.2 amd64 and arm64 are pending for false positive detection.

arm64 never had the false positive, just amd64. Unfortunately, nobody uses arm64 with Windows ;p

**Comment by kylecarbs** [comment]
![image](https://github.com/coder/coder/assets/7122116/b1125071-9d89-4ff5-bc2f-003f67c4a6a2)
![image](https://github.com/coder/coder/assets/7122116/ab988aa1-24c6-4b4e-a7ca-fb9303cbec56)
Monitoring now. Will keep everyone updated!

**Comment by djarbz** [comment]
Just wanted to add that I am getting this with Jetbrains as well.
Worked fine yesterday, just triggered this morning.
I think I saw that a new version of CW was published yesterday? My setup auto-updates nightly.

`C:\Users\<USERNAME>\AppData\Local\coder-gateway\coder.arbour.me\coder-windows-amd64.exe`

**Comment by kylecarbs** [comment]
@djarbz to confirm, what version of Coder are you using?

**Comment by kylecarbs** [comment]
Update: 2.10.2 has automatically scanned and found nothing (of course, because we know it's a false positive). Just waiting for them to remove the flag:

![image](https://github.com/coder/coder/assets/7122116/9a36248d-33ff-4046-a261-a9cce2a184b2)

**Comment by djarbz** [comment]
[v2.10.2+a11b169](https://github.com/coder/coder/commit/a11b1690298cb067b26b06de530d4b3f886efad1)

**Comment by kylecarbs** [comment]
Awesome. Should be fixed soon for you!

**Comment by kylecarbs** [comment]
No new update. Still pending.

**Comment by kylecarbs** [comment]
Update: this thing now says pending :eyes: 

![image](https://github.com/coder/coder/assets/7122116/3e09ab28-50a0-4394-9920-15af6bc4b02f)

**Comment by kylecarbs** [comment]
This is now fixed for 2.10.2:
```
At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
```
2.10.1 pending!

**Comment by kylecarbs** [comment]
Because 2.10.2 is a patch above 2.10.x, I'm going to close this out. Please comment if the binary is still being flagged for you!

**Comment by djarbz** [comment]
Can confirm, removed my temp exception and updated the signatures.
No issues launching this morning.

Thanks for the quick resolution!

**Comment by kylecarbs** [comment]
Awesome, happy to hear it! 🥳

**Comment by blueset** [comment]
Upgraded both server and client to 2.10.2, can confirmed that Windows Defender is now happy with the new binary. Thanks for the quick fix!
