### ISSUE TITLE
fix: API should upgrade `start` requests to `update` if require_active_version=true

### ISSUE THREAD

**Issue by sreya** [coder/coder#13016]
It's becoming obnoxious to have to implement this behavior in every consumer of the API (plugins, CLI, backstage, etc). This ticket includes the following changes:

~- [ ] Automatically update the `template_version_id` to the active version for `start` requests in `POST /workspacebuilds` if `require_active_version=true`~
~- [ ] Remove relevant client-side code from CLI to update `template_version_id`~
- [ ] Re-enable `Start` button in the UI but tag the button with some sort of indicator to inform the user a `Start` will update their workspace.

We can also simplify the plugins but we should track that in their respective repos.

**Comment by Kira-Pilot** [comment]
@sreya Should we change the 'Update' button to 'Start & Update' instead of adding another button here?

**Comment by Kira-Pilot** [comment]
@aslilac good one to tackle during our gap week

**Comment by sreya** [comment]
@Kira-Pilot it wouldn't be adding another button it would just be annotating the `Start` button to inform the user that it's going to do an update.

**Comment by aslilac** [comment]
we were talking about this this morning, and my concern was that having a "start" button that will update and start, and an "update" button that will update and start right next to each other is a bit odd. I think it'd make more sense to just have an "update and start" button that is clear about "you have to do these two things together" rather than two buttons.

**Comment by sreya** [comment]
As long as we don't think that'll be confusing for users I'm all for it. I agree displaying two buttons that do the same thing seems redundant.

**Comment by matifali** [comment]
We can also dynamically update the button text. Display **Start** if the workspace is stopped and no update is available, otherwise show **Update** when the workspace is in running state.

**Comment by BrunoQuaresma** [comment]
For now, we can fix this issue in the UI but I think the best solution is to have the API return what actions that workspace, given the logged-in user, can take.

I see we have some opinions and I'm unsure what the final decision is. In the past, users complained that the start button should not update the workspace so we added the update button. From what I can understand, we want to have the Update + Start button together only when the template enforces the updates. Is that right? If yes, displaying the start button with a warning icon + tooltip sharing more info is a good solution IMO.

**Comment by aaronlehmann** [comment]
I don't think this can be fixed in the UI. The original issue was that clients like JB Gateway fail to start a workspace that requires an automatic update - thus the proposal to do this at the API level.

The UI issue is tracked in #13002. I think this is also important to fix.

**Comment by BrunoQuaresma** [comment]
You are right, the UI part of this fix is tracked on https://github.com/coder/coder/issues/13002 and I'm working on it. Leaving the decision related to the API fix to @sreya and @bpmct

**Comment by sreya** [comment]
Closing this since the UI has been fixed and we decided against moving this logic into the API
