### ISSUE TITLE
feat: sign in without mouse interaction

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#13046]
# Description

One has to use mouse to click the login button.

![image](https://github.com/coder/coder/assets/103434584/be87c87e-b39c-4bea-8086-ea9487ce9f5b)

# Expected behaviour

As login button is the only element, a confimation with return/enter should be ok.

**Comment by BrunoQuaresma** [comment]
Does it work with tab navigation?

**Comment by MrPeacockNLB** [comment]
Hi @BrunoQuaresma ,

yes. If I do a tab then the button get highlighted and I can hit enter and start the action.

**Comment by BrunoQuaresma** [comment]
@MrPeacockNLB since the tab navigation works I don't see too much value in adding more code to handle this use case. I'm closing it for now but feel free to reopen it if you think we must support this feature. cc. @stirby
