### ISSUE TITLE
Unkown Error when tring to connect with Coder extension in VS Code

### ISSUE THREAD

**Issue by DraviaVemal** [coder/coder#13047]
# Unkown Error when tring to connect with Coder extension in VS Code

![image](https://github.com/coder/coder/assets/16499844/249088db-1bd8-47a8-a608-595dc84a1877)

I got very minimal details. Please let me know where to get the debug details to provide more context.

This is what I know.
Using Coder version v2.10.2
Coder server routed through traefik proxy.
Only failing to connect with vs-code coder extension.

Observation:
Coder is downloading  something in app data and then this error is thrown

Coder-Cli SSH forward method work perfectly fine.

**Comment by m0rke** [comment]
I have been getting the same error since today. I suspect this is due to Windows Defender classifying a coder resource as a threat
![image](https://github.com/coder/coder/assets/16209552/35734cf1-d9de-4987-9a51-e36c00c8dfa0)

Looks like this issue to me
[#13014](https://github.com/coder/coder/issues/13014)

**Comment by kylecarbs** [comment]
Oof, we'll have to do this ASAP then!

**Comment by DraviaVemal** [comment]
> I have been getting the same error since today. I suspect this is due to Windows Defender classifying a coder resource as a threat ![image](https://private-user-images.githubusercontent.com/16209552/324750652-35734cf1-d9de-4987-9a51-e36c00c8dfa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzI2NzQsIm5iZiI6MTcxMzg3MjM3NCwicGF0aCI6Ii8xNjIwOTU1Mi8zMjQ3NTA2NTItMzU3MzRjZjEtZDlkZS00OTg3LTlhNTEtZTM2YzAwYzhkZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExMzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MmI5M2U1ZTIzZWRjMjVmZTE5OWZhYjhhZjBmZDA4ZTlmYzcwOGM5Nzg1ZTg5MTZlZDNjM2VlYTU1MDM2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rs3zKakcmre_QNEU27ITqIk9VuHD_T9yMqU78ZtKQR0)
> 
> Looks like this issue to me [#13014](https://github.com/coder/coder/issues/13014)
> 
> As a workaround, the file can be classified as non-threatening in Windows defender - still doesn't feel so good.

I didn't notice or Defender didn't throw any notification. Thanks for the info. Adding it to exception works.

**Comment by kylecarbs** [comment]
Check the attached signing issue. I've reported as false positives and we're working on signing now so this never happens again.

Sorry folks!

**Comment by kylecarbs** [comment]
Closing in favor of https://github.com/coder/coder/issues/13014. This is p1.
