### ISSUE TITLE
Update feature comparison table for Gitpod

### ISSUE THREAD

**Issue by gtsiolis** [coder/coder#13066]
Hello friendly neighbors! 👋 

The **feature comparison table for Gitpod** is quite out of date on https://coder.com/vs/gitpod-self-hosted-alternative. ⚠️ 

We've created a table for you that is representative of our current feature set. We'd also like to note that Gitpod Enterprise is self-hosted so mention of us not having a self-hosted deployment offering is incorrect.

<img width="1312" alt="Frame 2189" src="https://github.com/coder/coder/assets/120486/5911d39c-9e7f-4ade-b48a-3bf513e4ea7e">

**Comment by kylecarbs** [comment]
Hey @gtsiolis! We'll review our comparison page; we last updated it a long time ago! I appreciate your fair comparison in the table. We'll try to make ours similarly unbiased.

To me, in the open-source world, self-hosting is the ability to independently host the software without contacting a company. If the company goes defunct, I can continue to self-host as well.

Based on your public docs, this is not the case. If I'm wrong, I'll update our page!

Going to close this out (we'll track in our coder.com repo). Feel free to ping if you'd like updates!
