### ISSUE TITLE
Use docker in workspace 

### ISSUE THREAD

**Issue by capjiang** [coder/coder#13060]
I used `curl -L https://coder.com/install.sh | sh` to deploy Coder and installed Sysbox and Docker, but still unable to use Docker in the workspace normally. I have added Coder to the Docker user group.
These are the two different templates I tried.
1. starter template Docker Containers ( I downloaded Docker in the workspace.)
2. starter template Docker Containers but
`
image = "codercom/ubuntu-docker:latest"
`
error
`docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.`

**Comment by kylecarbs** [comment]
Are you certain the Coder user is in the Docker group?

You can try `sudo su coder` and running `docker ps` to see if the perms are correct.

**Comment by capjiang** [comment]
> Are you certain the Coder user is in the Docker group?
> 
> You can try `sudo su coder` and running `docker ps` to see if the perms are correct.

![Snipaste_2024-04-25_09-52-12](https://github.com/coder/coder/assets/95555443/d789b4da-23e4-4450-97c6-47430494c338)
It's indeed in the Docker group.

**Comment by capjiang** [comment]
If just starter template Docker Containers 
![image](https://github.com/coder/coder/assets/95555443/311339ca-765b-463f-9bc4-8bab16ed4237)
Is there a good way to use Docker in this workspace.

**Comment by capjiang** [comment]
There is a way to get workspace to use Docker which is on a host
Dockerfile
`
RUN apt-get update \
	&& apt-get install -y \
	curl \
	git \
	golang \
	sudo \
	vim \
	wget \
	# add docker cli
	docker.io \
	&& rm -rf /var/lib/apt/lists/*
`
main.tf
`
resource "docker_container" "workspace" {
  # add
  volumes {
    host_path = "/var/run/docker.sock"
    container_path = "/var/run/docker.sock"
  }
}

![image](https://github.com/coder/coder/assets/95555443/3f533c9e-1c71-4458-911c-646f39da8d51)
Is there a good way to use Docker in this workspace and still keep Ubuntu.

**Comment by matifali** [comment]
This gives the workspace full access to the host docker socket, which is unsafe.
YOu should check https://coder.com/docs/v2/latest/templates/docker-in-workspaces#use-sysbox-in-docker-based-templates for a safer way.
