### ISSUE TITLE
UI shows long float when setting dormancy to non-day units

### ISSUE THREAD

**Issue by stirby** [coder/coder#13071]
We only allow dormancy configuration to be set by number of days as an integer in the UI. In the CLI, we allow it to be set by hours. Doing so causes the UI to translate the time into days and show a messy float:

![Screenshot 2024-04-24 at 3 51 02 PM](https://github.com/coder/coder/assets/58410745/0d35c1d2-a4de-41c0-ba7b-e0b777ac2c4c)

Can we still have it show days, but truncate the value? If it's not cleanly divisible by days we could add a note expressing it in hours:

> Coder will automatically delete dormant workspaces after 0.416 days (10 hours).

**Comment by BrunoQuaresma** [comment]
Is "hour" the minimum unit for those fields? If yes, I think we should update the UI to use hours instead of days. Wdyt?

**Comment by matifali** [comment]
Also `time_tl_dormant_ms` shouldn't be shown in UI. MAybe replace with **Time until dormant (gour)**

**Comment by stirby** [comment]
Hour is the minimum unit, but most of the time people will be configuring in days. Not a fan of switching to hours because of user confusion, and it makes it easy to set an unreasonably low value.

**Comment by matifali** [comment]
I made a typo the focus was on `time_tl_dormant_ms` in the above field. Forget hours :D

**Comment by BrunoQuaresma** [comment]
Ok, so we should accept floats in the UI instead of only integers. Is it correct?

**Comment by BrunoQuaresma** [comment]
I have an idea that I will explore next week.

**Comment by BrunoQuaresma** [comment]
My thoughts: 

I don't think supporting truncated float numbers is a good option because they can cause incorrect times to be saved. For example. 0.416666 days is not equal to 0.42 causing a few minutes difference which is important.

A good option IMO is to have a field where the user could select the time unit to be used. I mocked something very simple below:

![Frame 1 (2)](https://github.com/coder/coder/assets/3165839/8ec9c687-8042-4596-a779-b939ae06489f)

Wdyt?

**Comment by stirby** [comment]
This would be sick. Would it interpret which unit to display based on the underlying value? Or just be a toggle for which unit is displayed?

I.E. If I change the value from 24 hours to 10 hours in the API, will the float still be displayed when I select days? (Assuming we leave days as the default)
