### ISSUE TITLE
Template-enforced autostop can be overridden in the UI

### ISSUE THREAD

**Issue by stirby** [coder/coder#13078]
Users can override the default template Autostop in the UI even if it's prevented in the template settings.

![autostop_enforcement](https://github.com/coder/coder/assets/58410745/27eae19e-c3fc-4c2d-8b26-d6d8e01f7e0f)

![stop_in_13_hours](https://github.com/coder/coder/assets/58410745/5336342f-50c2-4396-b667-1fd5361b5305)

Tested with both admin and user roles, though I'm not sure if it can be modified via CLI/API from the user.

Effectively makes the "enforce changes..." option obsolete. 

---

Two options for fixing this: 

We can disable [+] and leave [-] enabled, since we don't want to prevent users from reducing cloud spend.

Or we can hide the [-] [+] entirely for simplicity.

**Comment by BrunoQuaresma** [comment]
So what we want to do is, if the template enforces autostop, the user should never be able to stop it. Is that correct?

I would assume the autostop is just a default value since the user could just start the workspace again after the workspace is stopped anyway. 🤔

**Comment by stirby** [comment]
> So what we want to do is, if the template enforces autostop, the user should never be able to stop it. Is that correct?

Specifically, the user should not be able to extend autostop. While they can still restart their workspace to reset the timer, admins are frustrated with the user's ability to extend the timer for convenience. 

The ability to modify the autostop timer is disabled in the workspace settings when the template "enforces" the setting, we should also disable it here.
