### ISSUE TITLE
FEAT: Update all (my) Workspaces

### ISSUE THREAD

**Issue by djarbz** [coder/coder#13079]
I would like to request a feature to add a button in my personal workspace view to update all workspaces that have pending template updates. Currently I have to do them one by one.

I know there is an auto-update feature, but I would prefer to do it interactively.

**Comment by stirby** [comment]
Hey, thanks for the request. 

We have an option to apply a bulk update in the UI:
![Screenshot 2024-04-25 at 3 46 09 PM](https://github.com/coder/coder/assets/58410745/a5be297b-825c-4e2a-8fcb-96bff61b68c8)

Is this the flow you're currently using?

**Comment by djarbz** [comment]
Hmm, I do not have the ability to select multiple with checkboxes or the Actions drop down.
Is that an Enterprise only feature?

**Comment by stirby** [comment]
It's only available to deployment admins under our [RBAC](https://coder.com/docs/v2/latest/admin/rbac) which is an enterprise feature.
