### ISSUE TITLE
Add basic authentication to shared `coder_app`

### ISSUE THREAD

**Issue by matifali** [coder/coder#13087]
## Context

Sometimes, we need to share a `coder_app` with some users temporarily without adding them to our Coder deployment as users but still need the access to be authenticated.

Currently, when a `coder_app` is shared with `share = "public"`, anyone on the network can access that `coder_app` without any restriction. There is `share = "authenticated"`, but it requires the user to be a registered Coder user.

## Suggestion

In case we need to share a `coder_app` over the network, allow setting a password to make these shares secure and only accessible with targeted people.

It would be nice if we have another share method, `password` that sets up a password protected `coder_app`

### Option 1

Introduce a new share method `password` and property `password` to setup password on a `coder_app`. 

```tf
resource "coder_app" "my_app" {
  agent_id     = coder_agent.example.id
  slug         = "myapp"
  url          = "http://localhost:40000"
  share        = "password"
  password     = "SomeSecurePassword!"
}
```

### Option 2

Introduce a new property `password` that when provided sets up a password protected `coder_app`

```tf
resource "coder_app" "my_app" {
  agent_id     = coder_agent.example.id
  slug         = "myapp"
  url          = "http://localhost:40000"
  share        = "public"
  password     = "SomeSecurePassword!"
}
```

## Possible Implementation

- [ ] Update terraform provider to allow setting a password for coder_app resource.
- [ ] Create a basic login page to accept a single "Password" input.
- [ ] Update [`ReverseProxy`](https://github.com/coder/coder/blob/15157c1c401c4fb233d39c15099045eae30fc538/coderd/tailnet.go#L348) method to check for authentication.

### native auth

Individual applications have their own auth methods which can be configured to set up an authentication mechanism. For example,
1. [code-server](https://coder.com/docs/code-server/latest/FAQ#how-does-the-config-file-work)
2. [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/5.7.1/public_server.html#securing-a-notebook-server)
3. [filebrowser](https://filebrowser.org/configuration/authentication-method)

### reverse proxy

Serve the app behind an nginx or caddy proxy can also include basic authentication.

**Comment by bpmct** [comment]
An nginx proxy can also include basic authentication.

**Comment by bpmct** [comment]
We're not going to do this in-product, but the app itself can include basic authentication with caddy or nginx
