### ISSUE TITLE
AWS EC2 Linux workspace default template not working

### ISSUE THREAD

**Issue by PapayaNotCheap** [coder/coder#13089]
I have used the docker workspace template, and it worked. So i continued to tried the AWS EC2 Linux workspace template, and it managed to provision an EC2 instance, but it seems like the agent does not connect back to Coder, leaving me with an error saying that the agent is unhealthy 
I have checked the coder-agent.log for the error, and it was trying to connect to coder service but it always fail. 2024-04-29 02:00:21.995 [debu]  sdk request  method=POST  url=http://coderwebsite.com/api/v2/workspaceagents/aws-instance-identity  body=""

Does anyone knows the reason for this issue?
<img width="716" alt="image" src="https://github.com/coder/coder/assets/163074972/cbddcf8c-20a9-44c9-a873-b97172078558">

**Comment by matifali** [comment]
Hi @PapayaNotCheap, have you followed the instructions [here](https://github.com/coder/coder/tree/main/examples/templates/aws-linux#prerequisites)?

**Comment by PapayaNotCheap** [comment]
Yes it worked, I tried it again, I probably copied or change something and forgot about it :/
