### ISSUE TITLE
UPNP errors appearing in SSH CLI stderr

### ISSUE THREAD

**Issue by raphaelfff** [coder/coder#13144]
Not sure of this is the right audience, when I have an idling SSH connections to a coder workspace, i come back to the ssh session with my screen flooded with some of these:

```
2024/05/03 13:49:15 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 500 Internal Server Error\r\nDATE: Fri, 03 May 2024 12:49:15 GMT\r\nConnection: Keep-Alive\r\nServer: Sky Router UPnP\r\nContent-Length: 460\r\nContent-Type: text/xml; charset=\"utf-8\"\r\nEXT:\r\n\r\n<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\r\n <s:Body>\r\n  <s:Fault>\r\n   <faultcode>s:Client</faultcode>\r\n   <faultstring>UPnPError</faultstring>\r\n   <detail>\r\n    <UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\">\r\n     <errorCode>402</errorCode>\r\n     2024/05/03 14:49:22 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 500 Internal Server Error\r\nDATE: Fri, 03 May 2024 13:49:22 GMT\r\nConnection: Keep-Alive\r\nServer: Sky Router UPnP\r\nContent-Length: 460\r\nContent-Type: text/xml; charset=\"utf-8\"\r\nEXT:\r\n\r\n<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">\r\n <s:Body>\r\n  <s:Fault>\r\n   <faultcode>s:Client</faultcode>\r\n   <faultstring>UPnPError</faultstring>\r\n   <detail>\r\n    <UPnPError xmlns=\"urn:schemas-upnp-org:control-1-0\">\r\n     <errorCode>402</errorCode>\r\n     <errorDescription>Invalid Args</errorDescription>\r\n    </UPnPError>\r\n   </detail>\r\n  </s:Fault>\r\n </s:Body>\r\n</s:Envelope>\r\n"; err=<nil>
```

I could disable Upnp on my router, but that sounds like a nuclear option, wondering if there is some proper way to address that

**Comment by kylecarbs** [comment]
When you say screen flooded, I assume this is happening in an SSH session?

**Comment by coadler** [comment]
This is interesting. The log originates from the Go stdlib: https://github.com/golang/go/blob/master/src/net/http/transport.go#L2360. This seems to suggest that your router is misbehaving and sending a response on a TCP connection while there are no active HTTP requests. We probably should suppress these logs.

**Comment by raphaelfff** [comment]
Yeah started happening as i downgraded broadband... Thx for the quick fix, it was the right audience after all!

**Comment by raphaelfff** [comment]
When will that be available to a release... i m getting annoyed at my rogue router...

**Comment by coadler** [comment]
Looks like it just missed the cutoff for v2.11, so it'll make it into v2.12. Since this only affects the CLI, you could just build a binary from main to use locally without updating your deployment.

**Comment by coadler** [comment]
@raphaelfff good news, i was able to pull this into `v2.11.2`
