### ISSUE TITLE
Mark the Helm chart as official

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#13183]
The [Coder helm charts](https://artifacthub.io/packages/search?org=coder&sort=relevance&page=1) are not marked as official even though they are, I think this should be fixed.

![image](https://github.com/coder/coder/assets/57866459/1152943f-37f1-4bd0-a83c-328faccaeef4)

(cc: @kylecarbs)

**Comment by matifali** [comment]
The process to get official status is listed [here](https://artifacthub.io/docs/topics/repositories/#official-status).

**Comment by matifali** [comment]
@mattvollmer Will you be interested in this?

**Comment by phorcys420** [comment]
I have submitted https://github.com/artifacthub/hub/issues/4094, now we wait!

**Comment by matifali** [comment]
Can you include all of [these](https://artifacthub.io/packages/search?org=coder&sort=relevance&page=1) repos (except the one with blue logo)
![Image](https://github.com/user-attachments/assets/08d6a8eb-3ab3-483b-a2b3-19290c91020b)

Also, we should try to change the category to something else from Security.

**Comment by phorcys420** [comment]
@matifali I've included the Coder v1 and Coder v2 repos so the only package that won't be marked as "official" is Coder Observability, but that's because it repacks Grafana and other observability tools, therefore it can't be official.

**Comment by matifali** [comment]
Thank you for looking into it. Security is ok then.

**Comment by phorcys420** [comment]
Official status acquired!

I think we should sign the packages too to have an extra badge.

**Comment by matifali** [comment]
Will coder/internal#88 help getting that?
