### ISSUE TITLE
bug(web): flickering log output in workspace page

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#13184]
Running Coder `v2.9.4`

---

This is happening when scrolling to the bottom of the logs on a workspace's page.
I think it's due to the fact it's trying to hide the horizontal scroll bar when you scrolled to the bottom, which makes it go up and show it again, but then it hides it again.

https://github.com/coder/coder/assets/57866459/b2ea9d67-a5e6-4b7e-8e01-bfee246da8e0

**Comment by stirby** [comment]
Thanks Phorcys. Might be windows-only, unable to reproduce on mac+chrome.

**Comment by phorcys420** [comment]
I don't have any other machine to try this on, but maybe!

**Comment by BrunoQuaresma** [comment]
Maybe this is a very specific situation that can be caused by the logs' width and size. @phorcys420 could you please copy and paste those logs into a gist and send it to me? If it is sensitive, can you send me over Discord? I appreciate your help 🙏

**Comment by phorcys420** [comment]
hey @BrunoQuaresma, sent you a quick vid on Discord!

**Comment by mtojek** [comment]
@BrunoQuaresma @phorcys420 Is it still a valid issue?

**Comment by phorcys420** [comment]
@mtojek i'll try to repro when I get back from Open Source Summit :)
