### ISSUE TITLE
External auth docs aren't clear about which platforms are supported

### ISSUE THREAD

**Issue by deansheather** [coder/coder#13208]
External auth supports any valid Oauth2 provider. However, our docs say that only a few platforms are supported:
https://coder.com/docs/v2/latest/admin/external-auth#configuration

The doc should be reworded to say that the listed platforms are "enhanced" external auth providers, where we will fetch some extra data about the user after they authenticate for convenience purposes.

Any other platform not listed is supported, just make sure you use a unique and unchanging `TYPE` when configuring the external auth provider.

**Comment by bpmct** [comment]
We're reworking our docs now. I'll be sure to include it
