### ISSUE TITLE
site: "Preview" badge doesn't automatically disappear after changing a service banner's color

### ISSUE THREAD

**Issue by Parkreiner** [coder/coder#13206]
## Steps to reproduce
1. Log into Coder with a user who has permission to view the deployment page
2. Navigate to the Deployment page view the navbar
3. Switch to the Appearance sub-page
4. Scroll down to the "Service Banner" section
5. Put in a new color and submit it
6. Scroll back up to top of the page
7. See that the Preview badge is still there, even after navigating to different pages

The badge won't disappear until you do a full page refresh.

## Video
https://github.com/coder/coder/assets/28937484/d548d527-d83f-4ba7-a68e-6b4e7d7a7538

## Notes
- This bug only triggers from changing the color. Changing the banner text works perfectly fine.

**Comment by BrunoQuaresma** [comment]
@aslilac just a heads up

**Comment by aslilac** [comment]
I entirely ripped out the "preview" functionality in a PR that got merged just after this, lol
