### ISSUE TITLE
coderd: select provisioners based on workspace tags

### ISSUE THREAD

**Issue by mtojek** [coder/coder#13219]
Related: https://github.com/coder/coder/issues/5979

Adjust `WorkspaceBuilder` logic to consider `coder_workspace_tags` stored in the database in provisioner tags evaluation. This would allow end users to use `coder_parameters` to select appropriate tags for their workspaces.

**Comment by michaelbrewer** [comment]
@mtojek  sounds like a cool feature, from what i can tell you can have a eu-central, us-west provisioner and a single workspace template, and then the end-user can select which provisioner to use.

is there examples for this? or docs on the specifics?

**Comment by mtojek** [comment]
Hi Michael, yes there is a dedicated doc page [Workspace Tags](https://coder.com/docs/templates/workspace-tags), and the [example](https://github.com/coder/terraform-provider-coder/blob/main/examples/resources/coder_workspace_tags/resource.tf) in terraform-provider-coder.

Feel free to play with the feature!
