### ISSUE TITLE
coder cli colors override terminal's theming

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#13211]
We have a user that reports:

> in case we have control over this, yellow might not be the best text color here. seems lots of coder-related things output specific colors and bypass my terminal's theme, leading to text that isn't always easy to read

![image_720-1](https://github.com/coder/coder/assets/739851/1acca824-a115-4d20-9ba5-c4f5183e809d)

Is there a way to make these colors more friendly to non-dark background terminals?

**Comment by kylecarbs** [comment]
Certainly! Will do.

**Comment by johnstcn** [comment]
Idea: serialize `$CODER_CONFIG_DIR/theme` to disk in some human-readable format?
