### ISSUE TITLE
Define: clear path to debugging a broken workspace

### ISSUE THREAD

**Issue by ammario** [coder/coder#1321]
Ok, so I have an old workspace called `ding`, but I can never SSH into it. I've tried restarting it to no avail.

[![asciicast](https://asciinema.org/a/EZOyz5sQriNv7D4DYT4gr7cra.svg)](https://asciinema.org/a/EZOyz5sQriNv7D4DYT4gr7cra)

The natural thing to do is disassemble the terraform, find the underlying resource, and then check on the agent. While I can list templates, I have no way of presenting the underlying terraform or configuration values. 

<img width="483" alt="image" src="https://user-images.githubusercontent.com/7416144/167169776-771dd50c-92f3-44e7-b27e-a02a88dc53c2.png">

## Lame workaround
The only workaround is asking the Coder admin where the terraform source is and what values they configured the template with. This makes the coder admin a bottleneck, and even they have to use recall instead of information from the Coder product.

**Comment by misskniss** [comment]
Moving this to an Epic after our grooming discussion. Tickets needed: 

Time out on agent connect after a successful build (2 min, 10 min?). 

- Add CLI command and Show the agent connect failure on the FE for users. Potentially dump all the names of the resources used. Add meta data (key-value mapping related to a resource) instead and an FE ticket to show this information to the user.  See ticket #1325 
- Error when build fails - The error property is Exit 1 - make this more useful.
