### ISSUE TITLE
Sharable ports UI redesign

### ISSUE THREAD

**Issue by stirby** [coder/coder#13215]
Originally raised by @pauliuspetk here:
https://github.com/coder/coder/issues/11486#issuecomment-2101286444

The sharable ports UI is a little overly complex since we added protocol control. There are several overly implicit flows and a few duplicate methods of achieving the same result. We've had to work directly with customers already to explain the feature's usage. 

![Screenshot 2024-05-01 at 1 15 10 PM](https://github.com/coder/coder/assets/58410745/16ade6c6-8a58-480b-8048-94da66610023)

I agree with @pauliuspetk we should consolidate into a single table; this was actually part of some of our original mockups. All controls would be in-line with their respective port. 

![](https://private-user-images.githubusercontent.com/92528042/329015864-0f83aaaf-bbd2-40ef-ac18-70b36793a35d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzI5NDEsIm5iZiI6MTcxNTI3MjY0MSwicGF0aCI6Ii85MjUyODA0Mi8zMjkwMTU4NjQtMGY4M2FhYWYtYmJkMi00MGVmLWFjMTgtNzBiMzY3OTNhMzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE2MzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwNDc4MTk2MzUyODI0YzMzNTA1MjExNThhYjNmNTMzYzYwMjZhOGIyZjQ4YzZiNTQ5ZDU1MGNhYzU5NGNkODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kvcyXeKkS1IQMG1baEzxgHd20Zee0hDnk0hvJDgfCSs)

Here, all listening ports would default to the hidden "Owner" and HTTP. Shared ports would be pinned to the top of the list and remain visible even if the listening port goes quiet.

**Comment by Kira-Pilot** [comment]
Taking resources off of this so we can stay focused on RBAC and Workspace Activity this sprint.

**Comment by ggjulio** [comment]
When using devcontainers it would be nice if the `devcontainer config` was reflected in the sharable ports UI.

![image](https://github.com/user-attachments/assets/f02f3a8d-f390-4dea-8642-2954a508fe25) ![image](https://github.com/user-attachments/assets/91256579-943b-4f63-b36e-3b38a0fb0346)

The simplest approach would be to provide the coder agent with a well known path of the `effective devcontainer config`.
- https://github.com/devcontainers/cli/blob/5eaf712d24eb96e7e4fcae247232467c37455373/example-usage/tool-vscode-server/start.sh#L11

A new option `devcontainer_effective_configuration` in the `coder_agent` can be added for flexibility :
`devcontainer_effective_configuration = /custom-path/to/effective-config.json`



The vscode repo can be used for reproduction: https://github.com/microsoft/vscode
