### ISSUE TITLE
Install script with `--stable` flag pulls mainline on macOS

### ISSUE THREAD

**Issue by stirby** [coder/coder#13214]
On MacOS `install.sh --stable` uses brew, which installs mainline by default. 

We should edit the script to use the stable version number with brew when the `--stable` flag is passed.

**Comment by matifali** [comment]
macOS defaults to brew which is on mainline. We should either push a stable/mainline brew package and handle that accordingly or change default to GitHub release binaries.

**Comment by stirby** [comment]
We're just going to change the `install.sh` script, adding support for `--stable` on macOS to close this. We should add another package on homebrew soon too.
