### ISSUE TITLE
Add UI pages and features for Multi Organizational navigation & management

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#13241]
UI for the multi-org story and RBAC features. Completion of this issue yields all UI views required to interact with multi-organizations and custom-roles premium features.

(Edited by @aslilac)

Based on the unified-orgs mocks

- [x] Create and delete orgs
- [x] Edit org names, descriptions, icons
- [x] Add and remove org members https://github.com/coder/coder/pull/13817
- [x] Multi-org groups page https://github.com/coder/coder/pull/13887
- [x] #13775
- [x] #13877
- [x] #13911
- [x] https://github.com/coder/coder/issues/13913
- [x] https://github.com/coder/coder/issues/13914
- [ ] https://github.com/coder/coder/issues/13915
- [x] Template table to include organization context for the templates. https://github.com/coder/coder/pull/14224
  - [x] Backend work to make a templates search query   https://github.com/coder/coder/pull/14211

**Comment by Kira-Pilot** [comment]
@aslilac Can we update this checklist to be aligned with the Figma docs? I'd like to work off this for the next two sprints so we can get an experimental version of the UI out by Aug.

**Comment by aslilac** [comment]
done!

**Comment by Kira-Pilot** [comment]
This sprint, @aslilac working on adding & removing org members + multi-org groups page. @jaaydenh working on the multi-org template page.

**Comment by Emyrk** [comment]
Mock made by @BrunoQuaresma for the templates table to include org context

![Screenshot from 2024-08-07 11-55-26](https://github.com/user-attachments/assets/8d63418a-a120-404b-9dcb-2f9d527f2924)
