### ISSUE TITLE
public port sharing not available on OSS deployment

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#13259]
From https://github.com/coder/coder/issues/11486#issuecomment-2101178378

> @kylecarbs the feature allows admins to restrict the maximum sharing level of ports in the template settings. If you're on our dev template the maximum sharing level is Authenticated.
> 
> We could add a tooltip if this is unclear.
> 
> @stirby What do you mean by "If you're on our dev template"?
> 
> I'm on an OSS deployment, upgraded from v2.10.2 to v2.11.0 today, and am seeing the same thing as @kylecarbs: "public" option is greyed out.
> 
> In the workspace settings, the "Public" option is pre-selected and unmodifiable, as expected.
> 
> The [documentation on port forwarding](https://coder.com/docs/v2/latest/networking/port-forwarding) says:
> 
> OSS deployments allow all workspaces to share ports at both the authenticated and public levels.
> 
> I can't seem to find a way to enable public port sharing via the port helper.

I've started a OSS deployment and I see the issue described:
<img width="433" alt="image" src="https://github.com/coder/coder/assets/19379394/6358c624-9139-4f75-b230-58e256da6ef6">

**Comment by stirby** [comment]
A community member reported this issue in discord, they were on an OSS deployment as well.
