### ISSUE TITLE
failed workspaces batch deletion not working

### ISSUE THREAD

**Issue by matifali** [coder/coder#13257]
I am unable to delete failed workspaces. The Dashboard shows them as deleted, but they reappear after some time. Please take a look at the attached video.
Can reproduce on
Version: 2.11.0
and https://dev.coder.com

https://github.com/coder/coder/assets/10648092/d72df01e-1bd0-44be-bc3c-00a368143ffc

**Comment by matifali** [comment]
This has been bugging me a lot from last few days. Still there on v2.11.1.

**Comment by matifali** [comment]
Am I the only one affected by this? Can anyone try to reproduce and share what I am missing? Thanks.

**Comment by stirby** [comment]
Can't reproduce this on dev. Closing for now for issue cleaning.
