### ISSUE TITLE
Optionally hide `coder_app` button in dashboard

### ISSUE THREAD

**Issue by stirby** [coder/coder#13265]
A customer wants to run a `coder_app` in their workspace and access a service via a fixed URL but not have it appear in the dashboard as a button. They can't use listening/shared ports because their deployment doesn't support wildcard domains. 

One option is to allow users to hide `coder_app`s in the UI by adding a new attribute. 

```hcl
resource "coder_app" "hidden-service-url" {
  agent_id     = coder_agent.dev.id
  slug         = "my-hidden-service"
  command      = "run service"
  ...
  hidden       = true  # defaults to false
  # or 
  button       = false # defaults to true
} 
```

This could ergonomically expand the ability to use workspaces as service providers.

**Comment by matifali** [comment]
It has been previously discussed in #8326 and #11356

**Comment by aaronlehmann** [comment]
Those discussions seem to be about conditionally enabling an app, not having an app that doesn't display a button.

**Comment by matifali** [comment]
@aaronlehmann Yes, they are a different use case. I linked them here for context.

**Comment by sreya** [comment]
What if we just interpreted leaving the `icon` value empty as indicative of an app that shouldn't be displayed? We should probably still display it _somehow_ so that we can convey the health of the app even if we make it obvious that it's not supposed to be interacted with in the traditional sense.

**Comment by aaronlehmann** [comment]
In my use case, it's for internal purposes and I'd prefer it not be exposed to users in the UI at all.

**Comment by stirby** [comment]
This could also be a remedy for defining shared ports as code, a similar request we've received.

**Comment by mtojek** [comment]
@stirby Coconut team can help here. What is the most convenient solution? Add `hidden` property to `coder_app`, and just don't expose it in the UI?

**Comment by stirby** [comment]
That'd be perfect @mtojek.

**Comment by matifali** [comment]
Let us dogfood this feature.
