### ISSUE TITLE
examples: update envbuilder devcontainer templates

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#13278]
After https://github.com/coder/envbuilder/issues/25 we can update our existing devcontainer examples to use the approaches documented there.

              We should also update our VM devcontainer templates to use docker outside docker approach. 
1. https://github.com/coder/coder/tree/main/examples/templates/aws-devcontainer
2. https://github.com/coder/coder/tree/main/examples/templates/gcp-devcontainer

_Originally posted by @matifali in https://github.com/coder/envbuilder/issues/25#issuecomment-2112716668_

**Comment by mtojek** [comment]
Is https://github.com/coder/coder/pull/13796 relavant to this one?

**Comment by johnstcn** [comment]
> Is #13796 relavant to this one?

Nope, doesn't touch those templates. Those are still TODO.

**Comment by matifali** [comment]
We still need to update the `aws-devcontainer` template.

**Comment by johnstcn** [comment]
> We still need to update the `aws-devcontainer` template.

Finally got this done, sorry about the wait!

**Comment by johnstcn** [comment]
I think this should be done now.

**Comment by ggjulio** [comment]
@johnstcn nice,
Do you know if there is any ongoing work to make `docker-in-docker` feature work instead of `dood` ?

Dind is more user friendly, and way better when working with bind mounts.

**Comment by johnstcn** [comment]
> @johnstcn nice, Do you know if there is any ongoing work to make `docker-in-docker` feature work instead of `dood` ?
> 
> Dind is more user friendly, and way better when working with bind mounts.

Is [this example](https://github.com/coder/envbuilder/tree/main/examples/docker/03_dind_feature) not working for you? If not, please file a separate issue!
