### ISSUE TITLE
Docs anchor links not copying to clipboard

### ISSUE THREAD

**Issue by mattvollmer** [coder/coder#13283]
As a user, I expect the anchor link for each docs header to be copied to my clipboard when I click the link icon. Currently, it does not copy in any browser. Bug?

<img width="1115" alt="image" src="https://github.com/coder/coder/assets/95866673/6541d133-6e35-4c34-97d3-3aeb64c8c790">

**Comment by kylecarbs** [comment]
It changes the URL, just as a static link would. I'm not sure if it should be copied.

**Comment by stirby** [comment]
I think the standard behavior is to just stick it in the search bar, not copy to clipboard.

**Comment by stirby** [comment]
Verified on Vercel docs, which I consider to be a good standard. 

Test here:
https://vercel.com/docs/deployments/builds#build-process
