### ISSUE TITLE
Create notification templates for key events

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#13328]
**Note: notifications should not be sent to the user which initiated the event.**

## Workspace events
_All of these events will go to the resource owner._

- [x] marked dormant
- [x] marked for deletion
- [ ] ~queued for deletion~
    - [ ] ~72h warning~
    - [ ] ~24h warning~
    - [ ] ~30m warning~
- [x] deleted
- [x] automatic build failure
- [x] automatically updated

## Template events
- [x] deprecated _(receiver: owner)_ https://github.com/coder/coder/issues/15117
- [x] manual build failure
- [x] automatic build failure _(receiver: template admin)_

## Account events
- [x] user account created _(receiver: user admin)_
- [x] user account deleted _(receiver: user admin)_
- [ ] user account suspended/reactivated _(receiver: user admin, user)_
- [ ] password reset _(receiver: user)_
- [ ] ~user email verification _(receiver: user)_~

**Comment by michaelbrewer** [comment]
I assume "All of these events will go to the resource owner", is the user that created a the workspace about to expire?

**Comment by dannykopping** [comment]
@michaelbrewer that is correct 👍

**Comment by stirby** [comment]
Notifications reach beta next Tuesday (10/01/2024). We've implemented our base set of notification templates for the feature, so I'm marking this closed. 

We'll revisit deployment health notifications in another issue.

**Comment by stirby** [comment]
Added https://github.com/coder/coder/issues/15117
