### ISSUE TITLE
Create notification preferences UI

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#13332]
Adds two pages to configure notifications:

A page in all users' account settings to optionally mute certain notifications for key template events. 

~A page in the deployment settings to disable certain notifications for all users.~

A page in the deployment settings to change the delivery method of notifications. 

- [x] User-scoped
- [x] Deployment-scoped

Organization-level configuration is tracked in another issue.

**Comment by stirby** [comment]
This has been shipped!
