### ISSUE TITLE
Link to versioned docs in the product

### ISSUE THREAD

**Issue by stirby** [coder/coder#13369]
We have "learn more" documentation links in the product to explain features or debug known issues. These URLs always point to the latest version of the docs, regardless of your deployment/CLI version. 

We should have these take users to docs matching their version of Coder using the URL scheme `coder.com/docs/@<version-tag>/*`.

This will prevent showing mismatched documentation.

**Comment by a0m0rajab** [comment]
Hi @matifali @stirby, just stumbled upon code today, and felt it's interesting to contribute. 
this issues seems to be doable by updating the docs function in the utilts/docs file

https://github.com/coder/coder/blob/bac9b38e05bc3fe2ffc45da068dcb1ad4ae0334b/site/src/utils/docs.ts

I was trying to understand how the deployment/CLI does provide the version, would you be able to help me and point out how to set the CLI version? so that I would see how to add this to the code.

**Comment by matifali** [comment]
@a0m0rajab We have a `./scripts/version.sh` that emits the current version. Other than that, you can see how the version is populated in the user dropdown.
See:

https://github.com/coder/coder/blob/bac9b38e05bc3fe2ffc45da068dcb1ad4ae0334b/site/src/modules/dashboard/Navbar/UserDropdown/UserDropdownContent.tsx#L187

**Comment by a0m0rajab** [comment]
@matifali thank you for showing that it's used in the product, 
I followed the provided link to the next code: 

https://github.com/coder/coder/blob/8beb0b131fb1d705602d01a7ccea250d8987a79e/site/src/modules/dashboard/Navbar/Navbar.tsx#L13

The path (from child to parent): `dropdowncontent -> dropdown -> navbarview -> navbar` 

I think it's possible to use the same query in the docs function, which would satisfy this issue. 
My guess would be having an async function that gets the build info then change the link to that would solve this. 

I need to explore the development and contribution guide to run the project, is it okay to open a PR now and test it later?

**Comment by stirby** [comment]
For now, you can use the following URL schema to access versions of our docs.

```coder.com/docs/@<tag>```

Example:
[coder.com/docs/@v2.11.0/install](coder.com/docs/@v2.11.0/install)

**Comment by matifali** [comment]
I think we should also update the user dropdown docs link to version specific. What do you think @stirby?

![image](https://github.com/user-attachments/assets/774e287f-674d-48b2-ae0c-b581a2f210d4)


https://github.com/coder/coder/blob/d6c4d472291101124e9f91a5bdc910aa4d50c44f/coderd/appearance/appearance.go#L16

**Comment by bcpeinhardt** [comment]
@matifali #14176 changes that link.

**Comment by matifali** [comment]
Thank you @bcpeinhardt. You may close it as completed now or along with #14176 then.
