### ISSUE TITLE
Envbuilder, Gitea, External Git Authentication - Git auth works in container, but envbuilder cannot clone repo

### ISSUE THREAD

**Issue by danhenrydev** [coder/coder#13367]
I'm struggling to make sense of external auth when using envbuilder.

**The Issue:**
I can get git authentication to work in envbuilder to pull a private repo from Gitea, and I can get git authentication to work properly in the workspace.  I cannot however get git authentication to work properly for both.

When I use the environment variables to set the `GIT_USERNAME` and `GIT_PASSWORD`, envbuilder can successfully clone the private repository, however the token of course eventually expires so git eventually stops working properly in the workspace.
```
  env = [
...
    "GIT_USERNAME=oauth2",
    "GIT_PASSWORD=${data.coder_external_auth.gitea.access_token}",
    "GIT_URL=${data.coder_parameter.repo.value == "custom" ? data.coder_parameter.custom_repo_url.value : data.coder_parameter.repo.value}",
...
  ]
```

![Successful Pull](https://github.com/coder/coder/assets/6625866/9b309ccd-b758-407d-a6a3-3d02b838ede9)

When I remove the `GIT_USERNAME` and `GIT_PASSWORD` environment variables, envbuilder is unable to authenticate so it reverts to the fallback image.  

![Failed Pull](https://github.com/coder/coder/assets/6625866/d942150b-36a7-4c86-b8db-309fff841f30)

With the environment variables still commented out in the template, if I pull a public repository using the same template I am then able to clone the private repository from within the workspace as expected:

![vscode-pull](https://github.com/coder/coder/assets/6625866/45760032-9279-4a99-b81f-5687276cd09a)

![Successful clone](https://github.com/coder/coder/assets/6625866/d0e7e29c-7322-414e-8092-34cff631beeb)

For clarity, every redacted git repository is the exact same private repository hosted on a self hosted Gitea server.

I am quite new to Coder, Envbuilder, and open source collaboration in general, and I have tried to be as verbose as possible in my issue.  I assume this is an oversight on my part, or a fundamental misunderstanding of how I should be doing this and not an issue with Coder/Envbuilder.  

Here is the complete Terraform file for the template.

```
terraform {
  required_providers {
    coder = {
      source = "coder/coder"
    }
    docker = {
      source = "kreuzwerker/docker"
    }
  }
}

data "coder_external_auth" "gitea" {
  # Matches the ID of the git auth provider in Coder.
  id = "gitea"
}

data "coder_provisioner" "me" {
}

provider "docker" {
}

data "coder_workspace" "me" {
}

resource "coder_agent" "main" {
  arch           = data.coder_provisioner.me.arch
  os             = "linux"
  startup_script = <<-EOT
    set -e
    git config --global credential.useHttpPath true

    # install and start code-server
    curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix=/tmp/code-server --version 4.11.0
    /tmp/code-server/bin/code-server --auth none --port 13337 >/tmp/code-server.log 2>&1 &
  EOT
  dir            = "/workspaces"
  
  # These environment variables allow you to make Git commits right away after creating a
  # workspace. Note that they take precedence over configuration defined in ~/.gitconfig!
  # You can remove this block if you'd prefer to configure Git manually or using
  # dotfiles. (see docs/dotfiles.md)
  env = {
    GIT_AUTHOR_NAME     = coalesce(data.coder_workspace.me.owner_name, data.coder_workspace.me.owner)
    GIT_AUTHOR_EMAIL    = "${data.coder_workspace.me.owner_email}"
    GIT_COMMITTER_NAME  = coalesce(data.coder_workspace.me.owner_name, data.coder_workspace.me.owner)
    GIT_COMMITTER_EMAIL = "${data.coder_workspace.me.owner_email}"


  }



  # The following metadata blocks are optional. They are used to display
  # information about your workspace in the dashboard. You can remove them
  # if you don't want to display any information.
  # For basic resources, you can use the `coder stat` command.
  # If you need more control, you can write your own script.
  metadata {
    display_name = "CPU Usage"
    key          = "0_cpu_usage"
    script       = "coder stat cpu"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "RAM Usage"
    key          = "1_ram_usage"
    script       = "coder stat mem"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Home Disk"
    key          = "3_home_disk"
    script       = "coder stat disk --path $HOME"
    interval     = 60
    timeout      = 1
  }

  metadata {
    display_name = "CPU Usage (Host)"
    key          = "4_cpu_usage_host"
    script       = "coder stat cpu --host"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Memory Usage (Host)"
    key          = "5_mem_usage_host"
    script       = "coder stat mem --host"
    interval     = 10
    timeout      = 1
  }

  metadata {
    display_name = "Load Average (Host)"
    key          = "6_load_host"
    # get load avg scaled by number of cores
    script   = <<EOT
      echo "`cat /proc/loadavg | awk '{ print $1 }'` `nproc`" | awk '{ printf "%0.2f", $1/$2 }'
    EOT
    interval = 60
    timeout  = 1
  }

  metadata {
    display_name = "Swap Usage (Host)"
    key          = "7_swap_host"
    script       = <<EOT
      free -b | awk '/^Swap/ { printf("%.1f/%.1f", $3/1024.0/1024.0/1024.0, $2/1024.0/1024.0/1024.0) }'
    EOT
    interval     = 10
    timeout      = 1
  }
}

resource "coder_app" "code-server" {
  agent_id     = coder_agent.main.id
  slug         = "code-server"
  display_name = "code-server"
  url          = "http://localhost:13337/?folder=/workspaces"
  icon         = "/icon/code.svg"
  subdomain    = false
  share        = "owner"

  healthcheck {
    url       = "http://localhost:13337/healthz"
    interval  = 5
    threshold = 6
  }
}


resource "docker_volume" "workspaces" {
  name = "coder-${data.coder_workspace.me.id}"
  # Protect the volume from being deleted due to changes in attributes.
  lifecycle {
    ignore_changes = all
  }
  # Add labels in Docker to keep track of orphan resources.
  labels {
    label = "coder.owner"
    value = data.coder_workspace.me.owner
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace.me.owner_id
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
  # This field becomes outdated if the workspace is renamed but can
  # be useful for debugging or cleaning out dangling volumes.
  labels {
    label = "coder.workspace_name_at_creation"
    value = data.coder_workspace.me.name
  }
}

data "coder_parameter" "repo" {
  name         = "repo"
  display_name = "Repository (auto)"
  order        = 1
  description  = "Select a repository to automatically clone and start working with a devcontainer."
  mutable      = true
  option {
    name        = "vercel/next.js"
    description = "The React Framework"
    value       = "https://github.com/vercel/next.js"
  }
  option {
    name        = "home-assistant/core"
    description = "🏡 Open source home automation that puts local control and privacy first."
    value       = "https://github.com/home-assistant/core"
  }
  option {
    name        = "discourse/discourse"
    description = "A platform for community discussion. Free, open, simple."
    value       = "https://github.com/discourse/discourse"
  }
  option {
    name        = "denoland/deno"
    description = "A modern runtime for JavaScript and TypeScript."
    value       = "https://github.com/denoland/deno"
  }
  option {
    name        = "microsoft/vscode"
    icon        = "/icon/code.svg"
    description = "Code editing. Redefined."
    value       = "https://github.com/microsoft/vscode"
  }
  option {
    name        = "Custom"
    icon        = "/emojis/1f5c3.png"
    description = "Specify a custom repo URL below"
    value       = "custom"
  }
}

data "coder_parameter" "custom_repo_url" {
  name         = "custom_repo"
  display_name = "Repository URL (custom)"
  order        = 2
  default      = ""
  description  = "Optionally enter a custom repository URL, see [awesome-devcontainers](https://github.com/manekinekko/awesome-devcontainers)."
  mutable      = true
}

resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  # Find the latest version here:
  # https://github.com/coder/envbuilder/tags
  image = "ghcr.io/coder/envbuilder:0.2.9"
  # Uses lower() to avoid Docker restriction on container names.
  name = "coder-${data.coder_workspace.me.owner}-${lower(data.coder_workspace.me.name)}"
  # Hostname makes the shell more user friendly: coder@my-workspace:~$
  hostname = data.coder_workspace.me.name
  # Use the docker gateway if the access URL is 127.0.0.1
  
  env = [
    "CODER_AGENT_TOKEN=${coder_agent.main.token}",
    "CODER_AGENT_URL=${replace(data.coder_workspace.me.access_url, "/localhost|127\\.0\\.0\\.1/", "host.docker.internal")}",
    # "GIT_USERNAME=oauth2",
    # "GIT_PASSWORD=${data.coder_external_auth.gitea.access_token}",
    "GIT_URL=${data.coder_parameter.repo.value == "custom" ? data.coder_parameter.custom_repo_url.value : data.coder_parameter.repo.value}",
    "INIT_SCRIPT=${replace(coder_agent.main.init_script, "/localhost|127\\.0\\.0\\.1/", "host.docker.internal")}",
    "FALLBACK_IMAGE=codercom/enterprise-base:ubuntu" # This image runs if builds fail

  ]

  host {
    host = "host.docker.internal"
    ip   = "host-gateway"
  }
  volumes {
    container_path = "/workspaces"
    volume_name    = docker_volume.workspaces.name
    read_only      = false
  }
  # Add labels in Docker to keep track of orphan resources.
  labels {
    label = "coder.owner"
    value = data.coder_workspace.me.owner
  }
  labels {
    label = "coder.owner_id"
    value = data.coder_workspace.me.owner_id
  }
  labels {
    label = "coder.workspace_id"
    value = data.coder_workspace.me.id
  }
  labels {
    label = "coder.workspace_name"
    value = data.coder_workspace.me.name
  }
}
```

**Comment by kylecarbs** [comment]
Will look thoroughly in a bit. Thanks for being so descriptive in your issue!

**Comment by stauder** [comment]
I can confirm the same behavior but with github. To clone the private repo with the .envbuilder directory in does not work. But inside of a final container (I tested with the fallback image) it works to clone very same repo.

**Comment by stauder** [comment]
I could solve it in the meanwhile with this [documentation](https://github.com/coder/envbuilder?tab=readme-ov-file#http-authentication) (that was not obvious for me to find).

You already have configured your external auth:
```
data "coder_external_auth" "gitea" {
  # Matches the ID of the git auth provider in Coder.
  id = "gitea"
}
```

In my case for github (not sure for gitea) I had to add this:
```
resource "docker_container" "workspace" {
  env = [
    "GIT_USERNAME=${data.coder_external_auth. gitea.access_token}"
  ]
}

```

I also tried to set `ENVBUILDER_GIT_USERNAME` but this had no effect.

**Comment by matifali** [comment]
> I also tried to set ENVBUILDER_GIT_USERNAME but this had no effect.

This change in environment variables names hasn't been released yet. This is the reason `ENVBUILDER_GIT_USERNAME` didn't work but `GIT_USERNAME` did.

**Comment by danhenrydev** [comment]
> I could solve it in the meanwhile with this [documentation](https://github.com/coder/envbuilder?tab=readme-ov-file#http-authentication) (that was not obvious for me to find).
> 
> You already have configured your external auth:
> 
> ```
> data "coder_external_auth" "gitea" {
>   # Matches the ID of the git auth provider in Coder.
>   id = "gitea"
> }
> ```
> 
> In my case for github (not sure for gitea) I had to add this:
> 
> ```
> resource "docker_container" "workspace" {
>   env = [
>     "GIT_USERNAME=${data.coder_external_auth.gitea.access_token}"
>   ]
> }
> ```
> 
> I also tried to set `ENVBUILDER_GIT_USERNAME` but this had no effect.

The problem with this solution is that once the access token expires git will no longer be able to work within the workspace.  I'm not sure how long Github's token is good for, but with my Gitea instance git stops working after an hour.

**Comment by matifali** [comment]
> The problem with this solution is that once the access token expires git will no longer work within the workspace. I'm not sure how long Github's token is good for, but with my Gitea instance git stops working after an hour.

To solve this you should not inject the token into the workspace (inner container) and rely on Coder's external auth to mange git authentication. 

https://coder.com/docs/admin/external-auth#native-git-authentication-will-auto-refresh-tokens

**Comment by danhenrydev** [comment]
> > The problem with this solution is that once the access token expires git will no longer work within the workspace. I'm not sure how long Github's token is good for, but with my Gitea instance git stops working after an hour.
> 
> To solve this you should not inject the token into the workspace (inner container) and rely on Coder's external auth to mange git authentication.
> 
> https://coder.com/docs/admin/external-auth#native-git-authentication-will-auto-refresh-tokens

Right, which is the problem.  When I do it that way, envbuilder is not able to clone the repository.

**Comment by matifali** [comment]
> Right, which is the problem. When I do it that way, envbuilder is not able to clone the repository.

For envbuilder you need to inject the environment variable. Envbuilder is running as the outer container which needs the token to clone the repo and build the devcontainer. We just should not add it into the built workspace.

**Comment by matifali** [comment]
I will request @Emyrk to explain this better.

**Comment by danhenrydev** [comment]
> > Right, which is the problem. When I do it that way, envbuilder is not able to clone the repository.
> 
> For envbuilder you need to inject the environment variable. Envbuilder is running as the outer container which needs the token to clone the repo and build the devcontainer. We just should not add it into the built workspace.

That makes sense to me, and I appreciate your help.  What's still lost on me is _how_ I would do that.

Thank you again for your time and help.

**Comment by Emyrk** [comment]
> Right, which is the problem. When I do it that way, envbuilder is not able to clone the repository

Yea, this makes sense. When you do not inject the token, we set `GIT_ASKPASS` to use the `coder` executable to fetch the token on demand. This allows coderd to do any refreshing.

I am not familiar with env builder, is the `coder` executable present in the outer container? I feel it should be possible to make the outer container do the dynamic fetch.

**Comment by danhenrydev** [comment]
> > Right, which is the problem. When I do it that way, envbuilder is not able to clone the repository
> 
> Yea, this makes sense. When you do not inject the token, we set `GIT_ASKPASS` to use the `coder` executable to fetch the token on demand. This allows coderd to do any refreshing.
> 
> I am not familiar with env builder, is the `coder` executable present in the outer container? I feel it should be possible to make the outer container do the dynamic fetch.

I'm not sure how to answer this question properly, as I'm not sure I fully understand the concept of inner and outer containers..  The coder executable is for sure available within the workspace after it has launched, as I can use `GIT_ASKPASS` properly and it uses the coder executable. I suspect that this is the 'inner container' that the envbuilder container actually builds.

I think that would mean that the container from the envbuilder image

```
...
resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  # Find the latest version here:
  # https://github.com/coder/envbuilder/tags
  image = "ghcr.io/coder/envbuilder:0.2.9"
...
```

Looking at the README for the envbuilder project 
https://github.com/coder/envbuilder
It doesn't mention the coder executable.  

Am I moving in the right direction here?

Thank you for your time, help, and patience.

**Comment by Emyrk** [comment]
@danhenrydev 100% correct in everything you said. I just talked with someone more familiar with enbuilder and he confirmed the `coder` executable is not present.

So you cannot use the auto refresh tokens in the envbuilder outer container. The inner container (the workspace) it can be used.

----

One workaround suggestion I have is to not use `GIT_URL`. That instructs `envbuilder` to do a clone, which is done in [golang](https://github.com/coder/envbuilder/blob/c1961333a3df64677665b01e1a013f39f2f14236/git.go#L48-L48), not `git`, to even further complicate this matter. 

I have not tried this, so maybe @matifali can provide some more detailed instruction, but you could instead instruct the workspace agent (which is the workspace/inner container) to do the clone. There exists a module to make this even more simple: https://registry.coder.com/modules/git-clone

**Comment by Emyrk** [comment]
@danhenrydev to clarify. Is the repo you are trying to clone defining a dev container? Or is it just a git repo you want in your working directory **inside** the workspace?

**Comment by danhenrydev** [comment]
> @danhenrydev to clarify. Is the repo you are trying to clone defining a dev container? Or is it just a git repo you want in your working directory **inside** the workspace?

The repo I'm trying to clone is defining a devcontainer.

**Comment by stauder** [comment]
Just to sum up my understanding:

In main.yaml the outer container is defined in 

```
resource "docker_container" "workspace" {
  image = "ghcr.io/coder/envbuilder:0.2.9"
}

```

This container then loads the repo and loads the (inner) container that is defined there in .devcontainer/devcontainer.json .

In my understanding the coder agent just runs inside the inner container, but not in the outer container.
But as the outer container has to clone the git repo to get the inner container, we need a git authentication in the outer container.

Now my approach to set GIT_USERNAME seems to be bad for two reasons:

1. the token is just set when the outer container is started and then outdates quickly and is never updated as the coder agent is not running in the outer container.
2. as @Emyrk mentioned it is then using envbuilder to do the clone instead of git.

What I do not understand is what the alternative would look like. The way proposed by @Emyrk "you could instead instruct the workspace agent (which is the workspace/inner container) to do the clone" does not work IMHO as you have to clone first to get the devcontainer/devcontainer.json where the inner container is defined. So the inner container does not yet exist when you clone.

**Comment by Emyrk** [comment]
You are correct, my original suggestion will not work. I was misunderstanding that the git repo was the devcontainers repo.

I'll raise this to the envbuilder team to continue this conversation

**Comment by johnstcn** [comment]
Firstly, thanks @danhenrydev for providing such detailed information. This really helps.

In the case of using envbuilder from coder, the recommended way to clone private repositories over http is through the Coder agent `GIT_ASKPASS` integration in combination with `coder_external_auth`. It's also important to note that tokens with limited expiry time _should_ be automatically refreshed by the agent.

To perform the initial clone of a private repo over HTTP(S), you need to make the `(ENVBUILDER_)?GIT_USERNAME` / `(ENVBUILDER_)?GIT_PASSWORD` environment variables available to the `envbuilder` image. These credentials will only be used during the initial build process -- once the build process completes, envbuilder unsets the environment variables it consumes as options and executes `(ENVBUILDER_)INIT_SCRIPT`. In this scenario, `INIT_SCRIPT` fetches and starts the Coder agent, which has its own different set of environment variables related to Git authentication.

(Side note: there is no such thing as an 'inner' or 'outer' container in the context of envbuilder -- it's all the same container and there is no nesting involved.)

It's important to note that the `GIT_ASKPASS` integration only works if you access the environment _through the Coder agent_. If you build a Docker container using envbuilder and access it by any means other than through the Coder agent (e.g. web terminal / coder ssh), you will still have the old credentials.

To validate the above, I set up a test environment with the [following compose file](https://gist.github.com/johnstcn/2ac4e7884c5e3c9a09692f19a36fabae).
This includes the required environment variables for external Git authentication with Gitea.

I also created a private repository in Gitea containing a `.devcontainer/devcontainer.json`

```
{
    "build": {
        "dockerfile": "Dockerfile"
    }
}
```

and a Dockerfile:

```
FROM codercom/enterprise-base:ubuntu
USER root
RUN apt-get update && apt-get install -y cowsay
USER coder
```

I then created a template using the example provided in the original comment, uncommented the `GIT_USERNAME` / `GIT_PASSWORD` credentials, and built a workspace specifying the HTTP URL of the private git repo hosted on the local Gitea instance (http://HOSTNAME_GOES_HERE/cian/devcontainer.git#refs/heads/main)

The template built successfully and I noted the presence of `cowsay` in the resulting container under `/usr/games/cowsay`.

I also noted the **absence** of `GIT_USERNAME` / `GIT_PASSWORD` when accessing the workspace via Coder, and the **presence** of those same variables when accessing the container directly e.g. via `docker exec -it <container> env`. This is expected, as the Coder agent is responsible for setting the required environment variables for git authentication via external auth.

I then proceeded to check the validity of the access token:

```
$ coder external-auth access-token gitea | cut -d '.' -f 2 |  base64 -d
{"gnt":1,"tt":0,"exp":1717751822,"iat":1717748222}base64: invalid input
```

I then waited an hour and ensured that the access token was refreshed after expiry, and it was:
```
coder@test:/workspaces/devcontainer.git$ date +%s
1717751861
coder@test:/workspaces/devcontainer.git$ coder external-auth access-token gitea | cut -d '.' -f 2 |  base64 -d
{"gnt":1,"tt":0,"exp":1717755463,"iat":1717751863}base64: invalid input
```

I also validated that a separate private git repository hosted on the Gitea instance could be cloned and pushed to.

All the above is merely a long-winded way of saying 'it works on my machine'.

The only variable I'm not sure of is which version of Coder @danhenrydev is currently using?

**Comment by danhenrydev** [comment]
Sorry for the late response.

I am using Coder version v2.11.1+d565144

I did give this another shot, and unfortunately was still having the same issues.   I ultimately was forced to change my workflow due to this and Envbuilder also not supporting Docker Compose.

I'm happy to assist in any way I can moving forward, although I don't think I'll be much help.  

Ultimately it seems like it was a configuration issue on my end, so I think it makes sense to close this issue.

Thanks again for everyone's time and help.
