### ISSUE TITLE
External IP of Google Instance disappears randomly after starting the Coder Instance.

### ISSUE THREAD

**Issue by kbamponsem** [coder/coder#13371]
Version: [`v2.8.3+01c6266`](https://github.com/coder/coder/commit/01c6266e3ebf2391b6373a5b61d91b90dbb44a3c)

This error happens quite often and so it makes the coder `VS Code` button disappear.

No matter how many times I restart it happens.

**Comment by kbamponsem** [comment]
When it happens what I normally do is to delete my Google Instance and then restart my coder environment.

**Comment by matifali** [comment]
@kbamponsem it's a but strange on how Coder server can affect the static IP of the GCP VM. It's most probably a cloud provider issue. 

Would you like to share more context and steps to reproduce this so that we can diagnose this issue. 

Thank you.

**Comment by kbamponsem** [comment]
I would love to but this happens randomly so atm, I am even unsure what causes it.
I will try and observe more to see what happens.
