### ISSUE TITLE
Option to disable `scp`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#13383]
For Coder deployments in secure networks, the transfer of files from a local filesystem to a remote Coder workspace is particularly risky. While we're exploring other options to disable file transfer in other editors that do not use scp (code-server, JetBrains, VS Code Desktop), it seems like it should be possible for us to disable `scp` on our SSH server implimentation.

## Product requirements

Should have
-  This can be an environment variable when starting the agent. That way, it's still configured per-template or per-environment, which could be useful.

Nice to have
- Show the user a friendly message that scp is disabled. If this is difficult, we can avoid this.

**Comment by kylecarbs** [comment]
This can be an environment variable when starting the agent. That way, it's still configured per-template or per-environment, which could be useful.

**Comment by bpmct** [comment]
Understood, changed!

**Comment by mtojek** [comment]
@bpmct Actually SCP is not a protocol we can control, but rather a special mode of ssh command ([wiki](https://en.wikipedia.org/wiki/Secure_copy_protocol) see _Function_).

1. What we can do, is check if there is _Session_ incoming, and if contains _RawCmd_ with `scp`. As you can imagine, user can be smart and rename `scp` binary to `foobar`, and our mechanism won't detect it.
2. Another option would be asking customers to deploy `rbash` (restricted bash) which limits access to specific commands, BUT... there are plenty of materials over the internet [how to escape rbash](https://systemweakness.com/how-to-breakout-of-rbash-restricted-bash-4e07f0fd95e).

We can implement the blocking mechanism, but do not consider it to be a security guard, rather "Do not trespass" sign.

Does it work for you?

**Comment by bpmct** [comment]
Hey, thanks for the investigation. I think I was operating under the impression that scp has a subSystemHandler, like sftp.

Let's move forward with the "do not trespass" approach, if it is relatively a low lift to allow someone to block specific `rawCmd`s when starting the agent.

**Comment by mtojek** [comment]
Alright, basic check merged. Admin can enable it by adding using `CODER_AGENT_BLOCK_FILE_TRANSFER=true` to workspace's env, so that agent can notice it.
