### ISSUE TITLE
Shared Workspaces

### ISSUE THREAD

**Issue by bpmct** [coder/coder#13425]
There are some cases many users on a group (team) may wish to connect to a single workspace:

- QA / reproduction environments
- On call environments
- Shared infrastructure (e.g. databases, caches)

Unlike a workspaces today, shared workspaces will be owned by a group, not a user. This prevents secrets from an individual user (e.g. their git credentials) from being shared and instead relies on service accounts.

- The `qa` group owns the `windows-benchmark` workspace which is used for benchmarking. 
- The `engineering` group owns the `scaletest` workspace, used for scale testing.
- The `data-science` group owns the `example-datasets` workspace.

## Requirements

- When a user connects to a group workspace, this should be audited
- We need to write an RFC to consider permissions (who can edit these workspaces, who can connect, etc) as well as whether the owner should be a headless user or group.

## Related

**What about pair programming?** 

Pair programming use cases are handled very well by existing IDE plugins (CodeTogether, VS Code Live Share, Ducky) as they can control read/write terminal access, multiple people typing, and kicking users from the session. These work with Coder today. As a separate effort, we can explore if we create a deeper integration with these pair programming extensions.

**Comment by matifali** [comment]
related #13361 and #2425

**Comment by kyle-hobbs** [comment]
Just throwing this idea out there. Could you share your workspace with everyone without an enterprise license, but to restrict it to a group that is an enterprise feature? This would be helpful for non-enterprise deployments too.

**Comment by bpmct** [comment]
Closing this one out for now in favor of #2425
