### ISSUE TITLE
test flake: `TestDeleteOldWorkspaceAgentStats`

### ISSUE THREAD

**Issue by coadler** [coder/coder#13430]
Slack context: https://codercom.slack.com/archives/CJURPL8DN/p1717174598761439

Likely due to it being the last of the month.

https://github.com/coder/coder/actions/runs/9325137323/job/25671626698?pr=13429#step:5:345

```
    dbpurge_test.go:123: 
        	Error Trace:	/home/runner/actions-runner/_work/coder/coder/coderd/database/dbpurge/dbpurge_test.go:123
        	Error:      	Condition never satisfied
        	Test:       	TestDeleteOldWorkspaceAgentStats
        	Messages:   	it should delete old stats: []
```

**Comment by dannykopping** [comment]
Another datapoint: https://github.com/coder/coder/actions/runs/10629250399/job/29465714269?pr=14478

**Comment by ethanndickson** [comment]
It looks like it's going to happen on every commit today, until my PR is merged😭

**Comment by dannykopping** [comment]
Approved your PR 👍
