### ISSUE TITLE
Unable to add user's Name with member role

### ISSUE THREAD

**Issue by matifali** [coder/coder#13454]
version: v2.11.2 and `main`
The feild is disabled. 
![image](https://github.com/coder/coder/assets/10648092/cd8748cf-6130-42a3-adce-76a7e467d95f)

**Comment by matifali** [comment]
This was working previously.

**Comment by johnstcn** [comment]
@matifali can you try the following cURL and see if you can update your name via HTTP API:

```
curl 'https://dev.coder.com/api/v2/users/me/profile' \
  -X 'PUT' \
  -H 'content-type: application/json' \
  -H "Coder-Session-Token: ${CODER_SESSION_TOKEN}" \
  --data-raw '{"username":"myname","name":"My New Name"}'
```

**Comment by matifali** [comment]
@johnstcn It works
```console
{"id":"d1e1792a-221d-413b-a7f4-51f33f395a9b","username":"atif-ali","avatar_url":"","name":"My Nee Name","email":"matifali@live.com","created_at":"2024-04-18T18:16:38.311145Z","last_seen_at":"2024-06-04T11:47:28.669799Z","status":"active","login_type":"password","theme_preference":"","organization_ids":["703f72a1-76f6-4f89-9de6-8a3989693fe5"],"roles":[]}
```

**Comment by johnstcn** [comment]
> This was working previously.

Can you provide more detail as to when this was known to be possible in the UI?

**Comment by johnstcn** [comment]
> Using this API, I can update both `username` and `name` but not `email`.

AFAIK updating user `email` isn't supported becuase that's a unique identifier for us.

**Comment by BrunoQuaresma** [comment]
Username is also a unique identifier I guess 🤔

**Comment by matifali** [comment]
> > This was working previously.
> 
> Can you provide more detail as to when this was known to be possible in the UI?

IIRC, I don't remember testing it with a member role as I am an owner on all my deployments. 

But my assumption is that it should be possible for members to update their display name so that it can be used by modules like https://registry.coder.com/modules/git-config can use their specified name. 

We currently do not support setting this value from the iDP too.

**Comment by matifali** [comment]
> Username is also a unique identifier I guess 🤔 

Yes. Username is unique and should not be allowed to change by a member role. That's a different bug. 

Here I am suggesting that we should allow updating names from the UI

**Comment by johnstcn** [comment]
> We currently do not support setting this value from the iDP too.

see https://github.com/coder/coder/issues/11704

**Comment by matifali** [comment]
@johnstcn should we disallow a user with the role `member` to update their username from the API too. This can lead to re-creating some terraform resources and possible data loss when used to name resources in the templates. 

Workspace remaining was recently disabled for a similar reason too
