### ISSUE TITLE
UI Not Showing "Start" button if template requires active version

### ISSUE THREAD

**Issue by eswolinsky3241** [coder/coder#13481]
Recently updated our staging deployment to v2.12.0. Noticed that none of my stopped workspaces had a "Start" button.
![image](https://github.com/coder/coder/assets/58117461/50695072-51cb-4214-9e74-44bf026926fe)

If I turn off the requirement for users to always update their workspace to the active template version, the issue is resolved.

Expect this is related to https://github.com/coder/coder/pull/13334.

**Comment by coadler** [comment]
Thanks for the report. We noticed this earlier and I should have a fix out soon

**Comment by eswolinsky3241** [comment]
Thank you @coadler, I installed the update and do see the Start button. Just FYI I did notice that the button also appears when a workspace is in the "Starting" phase, where before it was greyed out.
![image](https://github.com/coder/coder/assets/58117461/cf7e7a79-db1d-4f75-9e3c-adabaf6d5713)
