### ISSUE TITLE
Add "Full Name" to "Create User" form and CLI

### ISSUE THREAD

**Issue by bpmct** [coder/coder#13490]
We recently added a full name field (https://github.com/coder/coder/pull/11639). Let's add this into 

1) The form on the first-time setup page,

2) The "New user" form on the `Users` page. 

![image](https://github.com/coder/coder/assets/22407953/b3842ee5-e25b-4592-90b2-7a9946b8b3fa)
> Missing the "Full name" field

As well as the CLI, just an example:

```diff
coder v2.12.0+ba0bf43

USAGE:
  coder users create [flags]

OPTIONS:
  -e, --email string
          Specifies an email address for the new user.

      --login-type string
          Optionally specify the login type for the user. Valid values are:
          password, none, github, oidc. Using 'none' prevents the user from
          authenticating and requires an API key/token to be generated by an
          admin.

  -p, --password string
          Specifies a password for the new user.

  -u, --username string
          Specifies a username for the new user.
+     --full-name string 
+         Specifies a full name for the user (optional)
———
Run `coder --help` for a list of global options.

```

**Comment by johnstcn** [comment]
There's two possible avenues that I see here:

1) Plumb through the new field into `CreateFirstUserRequest` (simpler, but larger)
2) Use the existing `updateUserProfile` machinery to set the user's name as a separate request. This is likely a smaller change, but more complex.

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/coder/pull/13659
