### ISSUE TITLE
Missing documentation on advanced filtering

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#13505]
When you click on the list for advanced filtering

<img width="448" alt="Screenshot 2024-06-07 at 11 03 18 AM" src="https://github.com/coder/coder/assets/5442469/fc44768b-51f6-49c9-863e-73215bd0125a">

The documentation only covers the basics of filtering

<img width="1283" alt="Screenshot 2024-06-07 at 11 04 24 AM" src="https://github.com/coder/coder/assets/5442469/d1f00d67-a0b1-4924-9fd6-44732ed34183">

**Comment by coadler** [comment]
Definitely needs updating, cc @stirby
