### ISSUE TITLE
Provide completions for the coder CLI

### ISSUE THREAD

**Issue by kfkonrad** [coder/coder#13502]
Please consider adding `coder completion` subcommand. Working with a plethora of CLIs is so much easier when the next completion is at your fingertips. Also writing completions manually is a capital P Pain

I know you've forked cobra to make serpent and I'm not sure if serpent supports generating completions out of the box. If that's the case it should be a fairly simple change and if not it's a great chance to extend the CLI framework

**Comment by coadler** [comment]
Good idea, we should definitely do this. Probably something we'll need to add to https://github.com/coder/serpent
