### ISSUE TITLE
Jupyter Notebook/Lab UI is not loading 

### ISSUE THREAD

**Issue by sureshkumar1010** [coder/coder#13533]
Hi team,
In the dockerfile I installed python3 pip3 and jupyter notebook and jupyter lab.All the commands are found in the cli.When I perfom the jupyter commands such as **jupyter notebook** or **jupyter lab** It is giving me a browser url for the notebook.But if I try to open the url in the browser it is showing 404-The page is not found.But when I curl the same url it gives a proper html page as a response.Please help me in this regard.Thanks!

**Comment by matifali** [comment]
Could you share the error screenshot and the URL you get after running the command?

---

Additionally please try using the [module](https://registry.coder.com/modules/jupyter-notebook) and report back. 

> [!NOTE]
> Jupyter Lab/Notebook can only be hosted on a subdomain and require a [wildcard access URL](https://coder.com/docs/admin/configure#wildcard-access-url) to be configured.

**Comment by stirby** [comment]
Hey @sureshkumar1010, did you try our module? If you're still encountering issues, please open an issue with details in our [coder/modules](https://github.com/coder/modules/issues) repo.

Otherwise, please reach out via our [Discord server](https://discord.gg/coder).
