### ISSUE TITLE
support targeting server binary in install script

### ISSUE THREAD

**Issue by stirby** [coder/coder#13548]
### Background

In the v2.12.0, the mainline CLI was not compatible with the stable server release. Since our default method of installation points to mainline, messaging the correct version to users may be inconsistent. IE, if they have an internal wrapper for the install script but don't consistently use `stable` for production, the install flag may not be consistent. We should support a method of installing the same binary as your deployment.

### Proposal

For users who have already authenticated an outdated CLI, and want to upgrade:

We could take the deployment URL / token to identify the desired version. The user would be prompted upon running the install script to use their deployment's server version by default, or force the server version with a `--server` flag. 

```shell
# implicitly detects server version from stored config
... install.sh --server
```

Or could we support something like the following?

```shell
... install.sh --server <deployment_url>
```
Which takes the server version from the URL, but I suppose this would be awkward for unauthenticated users, or those downloading the CLI for the first time.

**Comment by kylecarbs** [comment]
Good idea

**Comment by matifali** [comment]
There was a previous attempt to add a `coder upgrade` command that downloads the alim binary from the logged in the Coder deployment. 

See: #7659

**Comment by stirby** [comment]
There was more steam behind the `coder upgrade` command. Regardless of which implementation we go for, we should reconsider adding this.

Keeping clients up-to-date with the server can be a headache for admins. This would simplify that task.

**Comment by matifali** [comment]
I think having it as a native `coder upgrade` command would also be nice to have along with support in the install script.

**Comment by aslilac** [comment]
I have a couple of thoughts about this:

1. I don't think that this should be a flag to the `curl https://coder.com/install.sh`, but rather, we should bundle an install.sh script in the coder server, and users would run `curl -fsSL https://dev.coder.com/install.sh | sh` to get a slim binary matching the version of their coder deployment. This has the added benefit of working for air-gapped deployments.

**Comment by Emyrk** [comment]
> I don't think that this should be a flag to the curl https://coder.com/install.sh, but rather, we should bundle an install.sh script in the coder server, and users would run curl -fsSL https://dev.coder.com/install.sh | sh to get a slim binary matching the version of their coder deployment. This has the added benefit of working for air-gapped deployments.

This feels very reasonable. Does `install.sh` today allow you to download the slim version? And not the fat? I ask because anyone downloading from a coder deployment probably only needs the slim version.

> A coder upgrade command would need to be very carefully considered. What happens if I run coder upgrade from a full build of coder? What if it's a slim build, but the slim build I'm running is newer than the server? xxx upgrade has an established meaning of "get me the same or newer" that I'm sure is really what we want/what would be useful in this context.

I would guess `coder upgrade` would only work if you used `install.sh`. So if you install coder from some other means, like `brew` or something, the command should fail???

If that is the case, we can know some assumptions.

> What if we took a slightly different approach and had a shim binary that just checked the server version every time you run a command and updated itself automatically? Never deal with mismatches again, it just handles the updates for you, like what corepack does for Node.js.

I dislike auto updates that are magic. Just my 2c. If it was a wrapper, then that would be fine 🤷.

**Comment by aslilac** [comment]
> If it was a wrapper

yeah, that's my thought. "coder-shim" would check if the right version is downloaded locally. if not, it would download it and cache it somewhere. then it would execute the right version of "coder-slim" with the arguments passed to the shim.

**Comment by matifali** [comment]
> Does `install.sh` today allow you to download the slim version? And not the fat?

No

> I ask because anyone downloading from a coder deployment probably only needs the slim version.

Yes.

> if we go with this route, we entirely bypass the need for a coder upgrade command and don't need to deal with the mess of answering any of those questions, which I'm in favor of.

It would be cool if whenever we detect a version mismatch we prompt the user and automatgcally fetch the correct binary from the server.
