### ISSUE TITLE
Coder does not release the memory after the Terraform task completed

### ISSUE THREAD

**Issue by pan93412** [coder/coder#13559]
## Description

I deploy Coder on Zeabur with the Docker image, `ghcr.io/coder/coder:latest`. I have noticed high memory usage after starting a workspace or updating the template. Typically, it only takes around 50MB, but the memory usage spikes and persists after performing such tasks.

![CleanShot 2024-06-13 at 02 00 44@2x](https://github.com/coder/coder/assets/28441561/f7b39b0b-1308-4710-9fae-f8c455510d43)

My workspaces are running on a dedicated AWS EC2 instance. This Coder instance is only for managing my EC2s, so I do not run any container on this. I am the only user in this Coder instance, and own only two workspaces and one templates. That two workspaces are stopped for most time.

I expect the memory usage to decrease to the baseline, which is about 50MB, after an interval with no further activity. However, it seems Coder does not intend to release this memory – it was still stuck on ~700MB. I often have to restart Coder to release them. However, according to the figure, Coder still uses ~300MB even after I have restarted Coder. A bit unexpected.

- Ref: [Discord](https://discord.com/channels/747933592273027093/1250450032977514627/1250450032977514627)

## Versions

- Coder: `v2.12.1+3fbfb53`
- Database: PostgreSQL

**Comment by kylecarbs** [comment]
Hmm, this is surprising. For the baseline, is this before doing initial setup?

**Comment by coadler** [comment]
Go is a garbage collected language, so it generally has full control as to when to release memory back to the operating system.

You'll have to enable pprof to see what's actually being held in the heap by coder. See `--pprof-enable` && `--pprof-address`. Then you can use `go tool pprof http://<hostname>:<port>/debug/pprof/heap` to grab a snapshot. Email us (firstname@coder.com) or upload the resulting tar and we can take a look.

**Comment by pan93412** [comment]
> Go is a garbage collected language, so it generally has full control as to when to release memory back to the operating system.
> 
> You'll have to enable pprof to see what's actually being held in the heap by coder. See `--pprof-enable` && `--pprof-address`. Then you can use `go tool pprof http://<hostname>:<port>/debug/pprof/heap` to grab a snapshot. Email us ([firstname@coder.com](mailto:firstname@coder.com)) or upload the resulting tar and we can take a look.

Here you are:

[Before starting the workspace (profile.pb.gz)](https://github.com/user-attachments/files/15814317/profile.pb.gz)
[After starting the workspace (profile.pb-2.gz)](https://github.com/user-attachments/files/15814362/profile.pb-2.gz)

Notably, there is a big object `ensureBlock` that exists whether before or after starting the workspace:

![CleanShot 2024-06-13 at 13 43 02@2x](https://github.com/coder/coder/assets/28441561/600e867c-a872-4292-a5a4-18b5c45a9fe0)

Besides, it seems there are no significant changes in `pprof` or the `coder server` itself before and after starting a workspace. I afraid this issue may be due to a memory allocation problem in the Alpine image.

**Before running a Terraform operation**
![CleanShot 2024-06-13 at 13 59 49@2x](https://github.com/coder/coder/assets/28441561/cbe6247d-71fa-4761-a97e-a1a2a19e57a4)

**When running a Terraform operation**
![CleanShot 2024-06-13 at 14 01 42@2x](https://github.com/coder/coder/assets/28441561/954ef353-9220-464d-9f88-eb8a37cb1b0f)

**After running a Terraform operation**
![CleanShot 2024-06-13 at 14 05 37@2x](https://github.com/coder/coder/assets/28441561/9ac8279e-3351-4e43-8eed-346f0a6506be)

**Comment by kylecarbs** [comment]
https://github.com/coder/coder/blob/c587af7c0e2bf5d186cc396210a57a880bc98add/site/site.go#L727

**Comment by pan93412** [comment]
> I'm quite certain this is due to storing the Coder binaries in-memory. I don't believe this is a leak of any kind.

Probably. I do also not think this leak is from the Coder binary itself.

**Comment by sreya** [comment]
Closing this since it does not appear to be a real memory leak
