### ISSUE TITLE
Problem in launching the Jupyter lab/notebook in workspace.

### ISSUE THREAD

**Issue by PraveenkumarLilly** [coder/coder#13575]
I have installed all dependent packages related to jupyter lab when I try to launch jupyter notebook it's running when I try to open in the browser in the new tab it's throwing 404. Please help me with this issue.

Thanks.

**Comment by PraveenkumarLilly** [comment]
I'm attaching the screenshots related to this issue for your reference. 
<img width="1725" alt="Screenshot 2024-06-14 at 11 15 13 AM" src="https://github.com/coder/coder/assets/166356722/c444e493-2786-494f-80a5-f3cb0f3fff6f">
<img width="1728" alt="Screenshot 2024-06-14 at 11 15 43 AM" src="https://github.com/coder/coder/assets/166356722/6e81127d-4f7c-4577-8fc6-54fa335f7363">

**Comment by ericpaulsen** [comment]
hi @PraveenkumarLilly - are you available for a phone call this week to troubleshoot?

**Comment by PraveenkumarLilly** [comment]
Hi @ericpaulsen 

Yes sure.

**Comment by PraveenkumarLilly** [comment]
Sure 
I'll do that.
Thanks.

**Comment by PraveenkumarLilly** [comment]
Hi @ericpaulsen,
Have mailed you. Please schedule the call based on that.

Thanks.

**Comment by PraveenkumarLilly** [comment]
Hi @ericpaulsen,
As per your suggestion we have added the wildcard URL in our deployment file.
After that we tried launching the jupyter lab we the routing is happening but in the new browser window again throwing the 404. Attaching screenshot for your reference.
<img width="1728" alt="Screenshot 2024-06-25 at 2 34 32 PM" src="https://github.com/coder/coder/assets/166356722/2035e2ee-5650-4ab4-ad39-818b2ce45e4f">

<img width="514" alt="Screenshot 2024-06-25 at 2 35 57 PM" src="https://github.com/coder/coder/assets/166356722/09ec5368-3e3a-4dcf-b5e2-50902bd0b0e0">


Please let me know if I missed something.
Thanks

**Comment by ericpaulsen** [comment]
resolved - the ingress configuration was missing the wildcard access URL.
