### ISSUE TITLE
Can not start workspace from template

### ISSUE THREAD

**Issue by HaoyunJi** [coder/coder#13581]
[root@code ~]# journalctl -u coder -f
Jun 15 03:56:23 xxx coder[3310]: 2024-06-15 08:56:23.204 [info]  terraform: unpacking template source archive  session_id=c2dd653a-2f31-45dc-b804-edcd3c54cd52  size_bytes=11264
Jun 15 03:56:23 xxx coder[3310]: 2024-06-15 08:56:23.260 [info]  terraform: clean stale Terraform plugins  cache_path=/var/cache/coder/coder/provisioner-0/tf
Jun 15 03:56:26 xxx coder[3310]: 2024-06-15 08:56:26.828 [info]  provisionerd-code-0.runner: dry-run provision failure  job_id=732c1f34-5708-4400-85bc-16d8bd529a62  error="terraform plan: exit status 1"
Jun 15 03:56:26 xxx coder[3310]: 2024-06-15 08:56:26.840 [info]  terraform: recv done on Session  session_id=c2dd653a-2f31-45dc-b804-edcd3c54cd52  error=EOF
[root@code ~]# cd /var/cache/coder/coder/provisioner-0/tf
[root@code tf]# ls
LICENSE.txt  lock  registry.terraform.io  terraform
[root@code tf]# coder --version
Coder v2.11.2+d53c94b Wed May 22 18:12:23 UTC 2024
https://github.com/coder/coder/commit/d53c94b32a0f4336bb583ee4327cd880479476b5

Full build of Coder, supports the  server  subcommand.

**Comment by matifali** [comment]
Can you verify if the template is a valid file i.e. `terraform validate`. 

Could be a possible duplicate or related to #13608
