### ISSUE TITLE
Connecting v2 on mobile 

### ISSUE THREAD

**Issue by weber77** [coder/coder#13600]
when I connect on mobile it opens in metamask but does prompt for connection 

Link to repo: https://github.com/weber77/wagmi-mobile-test

https://github.com/rainbow-me/rainbowkit/assets/44323398/5a22f4cd-3be0-46e1-b898-5588e05059eb

**Comment by weber77** [comment]
I provide the info in the videos

**Comment by coadler** [comment]
Hi @weber77, this doesn't have anything to do with our product.
