### ISSUE TITLE
Release scripts: Remote ref check errors

### ISSUE THREAD

**Issue by stirby** [coder/coder#13648]
We're using branches to maintain the release channels `release/2.x`. When the release script checks if commits exist in a remote ref, it always fails. This occurs both on patches and minor releases.

It seems to be hitting our `version.sh` script which produces a valid version for any commit.

```
ERROR: Ref 0669a23efa24d900547013940233cd46ff79fbcb is already part of another release: v2.11.2-5-g0669a23ef on release/2.11.
```

cc @mafredri

**Comment by mafredri** [comment]
@stirby I tried reproducing this but I'm not sure what the circumstances for it happening were.

When I went looking:

```
❯ git log 0669a23efa24d900547013940233cd46ff79fbcb
fatal: bad object 0669a23efa24d900547013940233cd46ff79fbcb
```

Which branch did you have checked out when this happened? Did it have local changes? And what were the CLI arguments to `release.sh`?

To me it seems like this is erroring before hitting `version.sh`, at:

```
release_contains_ref="$(git branch --remotes --contains "${ref}" --list "${remote}/release/*" --format='%(refname)')"
```

This is just a safety check, though. Skipping it is fine if the operator is sure that it's incorrectly detecting an error case. But there may be something underlying we should investigate further.

**Comment by stirby** [comment]
@mafredri I believe this only happens when patching an existing release with cherry-picked commits. I can't recall the exact situation, but I think this was where it errored:

I was on `release/2.12` with a few cherry-picked commits. Ran this:

```shell
./scripts/release.sh --mainline --patch
```

And it errors on the line you mentioned above. I have been commenting that out for patches, but this causes the autoversion PR section of the script to fail. 

I am going to attempt reproduction when we patch v2.12, should be within the next couple days.

**Comment by bpmct** [comment]
We should be able to reproduce this async today when we do a patch release.

**Comment by stirby** [comment]
We were able to reproduce this. The scripts did not initially account for us pushing the release branch before creating a tag, so we need to skip checks in the release branches. 

This is circumnavigable by commenting out the check, but it breaks the autoversion PR.

Mathias said he should be able to take a look before the next release day.

**Comment by stirby** [comment]
I think it's still just hitting the remote branch but it threw an interesting error referencing 2.10 today:

```shell
coder@release-14:~/coder$ ./scripts/release.sh --mainline --minor --ignore-script-out-of-date
Checking remote origin for repo...
Fetching main and tags from origin...
ERROR: Ref HEAD is already part of another release: v2.10.0-697-gae40f8a82 on release/2.14.
```
