### ISSUE TITLE
Organization options showing as regular user

### ISSUE THREAD

**Issue by maeanes** [coder/coder#13654]
Button to view organizations under deployment is showing to me as a regular user. Clicking the button does nothing. 

<img width="1235" alt="image" src="https://github.com/coder/coder/assets/97917268/1c18fe71-e9be-4298-8a94-7b7bd05ac3a0">

**Comment by stirby** [comment]
Assuming this is in dogfood (dev.coder.com) and not a fresh deployment? Should be hidden behind an experiment.

**Comment by stirby** [comment]
Should still fix though. 

cc @aslilac

**Comment by aslilac** [comment]
it is hidden behind an experiment, this won't affect any users. this'll be fixed before it ships.

**Comment by Kira-Pilot** [comment]
Closing this as we're just dogfooding a new feature that is hidden.
