### ISSUE TITLE
React native app: not reflecting new code changes when building in coder-server workspace

### ISSUE THREAD

**Issue by keravanos** [coder/coder#13664]
We recently discovered a bug during development where code changes don't reflect in Coders port forwarded environment. 

Steps to reproduce: 

1. Acces coder-server 
2. Create react native application
3. npm run start 
4. port-forwarding works and browser opens the application
5. make a change to the code and refresh page to see changes

Often it will show the new change in the UI, but after a few change iterations it stops reflecting the changes. I also noticed today that if I kill the react app and rebuild, it will sometimes only show the first change I made.

**Comment by keravanos** [comment]
Thanks for the reply! Is there a plan to fix this in a future update?

**Comment by keravanos** [comment]
It should be noted that running a Python Flask page does reflect each change

**Comment by stirby** [comment]
Hey @keravanos, thanks for raising this issue. I'm folding the thread into the new issue from Atif. You can follow progress there.

https://github.com/coder/coder/issues/13726

**Comment by keravanos** [comment]
[like]  Mark Wells reacted to your message:
________________________________
