### ISSUE TITLE
Telemetry for V2 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#1367]
As a company we would like the ability to track some basic metrics for the product to help us improve the experience. 

See internal [RFC](https://www.notion.so/coderhq/Telemetry-8715027603394f80bb4707529d1d7154) 

- Framework for adding tracking events in the backend
- Using Prometheus
- Go Metrics library?

**Comment by ketang** [comment]
We have basic telemetry.  Future issues should focus on specific incremental improvements to make rather than this vague and broad issue.
