### ISSUE TITLE
Local accounts: Missing ability to edit user account details

### ISSUE THREAD

**Issue by wegerts** [coder/coder#13672]
We are running an instance of coder for evaluation purposes and therefore currently using local accounts only.
As a user admin or instance owner I'd like to have the option to edit account details after creation, e.g. for Adding a users display name which is used in templates for setting the git name.

Another issue we found is that users are not able to edit their account (display name) unless we grant the user admin role. Is this a bug or as designed?

Coder version: v2.12.2

Regards and: Really great work!...

**Comment by kylecarbs** [comment]
@stirby

**Comment by matifali** [comment]
Duplicate of #13454 and it has been fixed. Should be available in next mainline release.

**Comment by wegerts** [comment]
Will wait for this - ty!
