### ISSUE TITLE
Profile & speed up Terraform workspace starts

### ISSUE THREAD

**Issue by bpmct** [coder/coder#13691]
Workspace starts in dev.coder.com in particular feel very slow, and I think we should investigate:

- Modules: We have to download modules every time. Can we explore either:
  - Storing these as pulled via `terraform init` and uploading them to DB
  - Optional filesystem cache for modules
- Terraform in general
  - I think we're doing something weird here compared to normal Terraform, perhaps due to locking db transactions? Regardless of the reason, I think Coder's `terraform apply` in Dogfood in particular is significantly slower than a normal `terraform apply`.
  - I wish I have numbers but haven't been able to quantify this.

**Comment by matifali** [comment]
module cache should be a must and will significantly improve the builds. Unfortunately terraform has yet to implement it. See https://github.com/hashicorp/terraform/issues/34634

**Comment by dannykopping** [comment]
I've knocked together https://github.com/coder/terracache/ which might solve this problem.
