### ISSUE TITLE
Trying to download logs for failed workspace makes entire page for that workspace unusable

### ISSUE THREAD

**Issue by Parkreiner** [coder/coder#13723]
Ran into this while testing out some of the RDP Coder module stuff

## Problem
Trying to download the logs for a workspace that has failed throws an uncaught UI error. In addition, navigating away from the page and then trying to go back to the page still causes that error to persist. The page doesn't become usable again until you do a full page refresh from the browser.

## Steps to reproduce
1. Create a template that will run a script that is guaranteed to fail
2. Create a new workspace from that template
3. Navigate to that workspace's page
4. Click the Additional Actions dropdown menu, and then "Download Logs"
5. Once the uncaught error is thrown, press back on the browser
6. Try to navigate back to the workspace page
7. See the same uncaught UI error

## Video
https://github.com/coder/coder/assets/28937484/f56007f8-321f-49aa-9b18-d8047e37c4f7

## Workarounds
- As mentioned above, you can get around this by refreshing the page, but trying to download the logs again causes the issue to reappear.

**Comment by Kira-Pilot** [comment]
Seems as though this is only failing with RDP

**Comment by stirby** [comment]
@Parkreiner just a reminder for your investigation: if this bug is reproducible on other templates please let me know so we can patch v2.13 after it goes out.

**Comment by Parkreiner** [comment]
Just got this into a reliably reproducible state. Next orders of business:
1. Dig through the UI code to figure out 
2. Get a fix in place for this issue specifically

But to go a little beyond, I think it'd a be a good idea to beef up our error handling in the UI, because to be honest, we don't really have a lot. This is also the [second time we've had a breaking UI bug slip through in the past two months](#13130).

Proposing an update to the UI that:
1. Makes it so that errors like these don't blow up the entire UI, and at least parts of it will still be usable
2. Gets rid of the default error styling
3. Replaces the content that broke with a CTA that helps the user refresh the page and get things back on track

**Comment by Parkreiner** [comment]
Closing this in favor of making a new issue for improving the app's error handling in general.
