### ISSUE TITLE
[Feature Request] allow open a '.code-workspace' file instead of a folder

### ISSUE THREAD

**Issue by ccll** [coder/coder#13760]
The 'coder-agent' terraform resource accepts a `dir` specifies which folder to open when clicking the IDE button.
```hcl
resource "coder_agent" "main" {
  arch = data.coder_provisioner.me.arch
  os   = "linux"
  dir  = "/workspace"
  ...
}
```

But all our vscode projects use '.code-workspace' file instead of a plain folder, which allow us to use multi-root feature in vscode.

Please allow the user to specify a file to open, in additional to open a folder.

**Comment by kylecarbs** [comment]
Yeah, we can do this.

It'd probably be better for us to add this in our [VS Code Module](https://registry.coder.com/modules/vscode-desktop) instead though.

**Comment by matifali** [comment]
> Yeah, we can do this.
> 
> It'd probably be better for us to add this in our [VS Code Module](https://registry.coder.com/modules/vscode-desktop) instead though.

@kylecarbs the module already supports opening workspace files if `folder` is set to the path of the `.code-workspace` file.

@ccll please try the module and let us know if it solves your issue.

**Comment by ccll** [comment]
@matifali Perfect! Confirmed it works, thanks!

Need to note that the file name '.code-workspace' can't actually be used due to a VSCode issue, tripped me a while.
- https://github.com/microsoft/vscode/issues/104418

Name it 'ws.code-workspace' or whatever would make it work.
