### ISSUE TITLE
Organization scoped provisioners

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#13762]
Provisioners have an [`organization_id`](https://github.com/coder/coder/blob/e5b038948f52f157d1bbc9bcd48ae3a861583117/coderd/database/dump.sql#L687-L687), but authentication and setup are still globally scoped with a [single shared key](https://github.com/coder/coder/blob/e5b038948f52f157d1bbc9bcd48ae3a861583117/codersdk/deployment.go#L419-L419).

Provisioners need an authentication flow scoped to an organization to allow organization admins to create, maintain, and remove provisioners in their org. The flow should also include the ability to set the provisioner tags.

Tasks
- [x] Add provisioner auth tokens table to database - https://github.com/coder/coder/pull/13857
- [x] Add POST provisioner tokens route - https://github.com/coder/coder/pull/13857
- [x] Add DELETE provisioner tokens route - https://github.com/coder/coder/pull/13857
- [x] Add GET provisioner tokens route - https://github.com/coder/coder/pull/13857
- [x] Add create provisioner tokens CLI command - https://github.com/coder/coder/pull/13875
- [x] Add delete provisioner tokens CLI command - https://github.com/coder/coder/pull/13875
- [x] Add list provisioner tokens CLI command - https://github.com/coder/coder/pull/13875
- [x] ~~Make `built-in` provisioners use auth tokens~~ - No need since they use in memory pipe
- [x] Make provisionerd take an org flag - https://github.com/coder/coder/pull/13923
- [x] Add org scoped GET provisioners route - https://github.com/coder/coder/pull/13953
- [x] Move cli commands to slim build - https://github.com/coder/coder/pull/13993
- [x] Accept auth tokens on provisionerd register endpoint - https://github.com/coder/coder/pull/13972
- [x] Add tags concept to provisioner keys - https://github.com/coder/coder/pull/13989
- [x] Add auth tokens flag to provisionerd command - https://github.com/coder/coder/pull/14002
- [x] Shorten auth token length - https://github.com/coder/coder/pull/14017
- [x] ~~Upgrade path for preshared keys to new authentication tokens~~ - covered in docs
- [x] Relevant doc changes - met with ben to go over https://github.com/coder/coder/pull/14012

**Comment by Kira-Pilot** [comment]
@f0ssel we can use this as an umbrella ticket for the tickets that fall out of the provisioner RFC.
