### ISSUE TITLE
flake: `TestUserOIDC/RoleSync/NewUserAndRemoveRolesOnReAuth`

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#13788]
https://github.com/coder/coder/actions/runs/9791002172/job/27033833510?pr=13537

```go
...
    t.go:108: 2024-07-04 08:31:18.415 [erro]  http call not found  path=/derp
         *** slogtest: log detected at level ERROR; TEST FAILURE ***
    idp.go:1165: unexpected request to IDP at path "/derp". Not supported
...
```

**Comment by Emyrk** [comment]
This is really strange. Why would we hit the `/derp` endpoint on the IDP?

My hunch is the idp took the same port as a coderd from a previous test. Then the other test hit the `/derp` port before it was fully closed.

I added some logs to output the port of the fake IDP: https://github.com/coder/coder/pull/13818

If this happens again with the logs, I can search if the port is being used by more than 1 test

**Comment by Emyrk** [comment]
Datadog is not showing this as a very common failure on `main`. Considering how infrequent it is, I am going to close this out for now. If this reappears, the additional logs from https://github.com/coder/coder/pull/13818 will aid in debugging.

![Screenshot from 2024-07-10 09-32-05](https://github.com/coder/coder/assets/5446298/5ce2f774-edc8-46e1-9a59-48c45564cca3)


Reopen if this flakes on `main` :+1:
