### ISSUE TITLE
No way to delete a dormant Workspace from within workspace page

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#13786]
# Description

I can not delete a dormant workspace from workspace page.

![image](https://github.com/coder/coder/assets/103434584/d11eb870-d654-477c-aa80-75031bbb5e26)

The 3 dot menu is disabled. It is possible to delete the workspace via multi select action delete from workspaces page, but  should be possible from workspace page too.

Version: Coder v2.12.3

# Solution

Enable 3 dots menu delete action, so a user is able to delete a dormant workspace from workspace page without activating.

**Comment by stirby** [comment]
Oof, we'll fix this. Thank you for reporting.

**Comment by stirby** [comment]
@BrunoQuaresma can we allow the dropdown with only the delete option enabled?
