### ISSUE TITLE
Issue: Incorrect Response Message for DELETE /api/v2/workspaces/{workspace_id}/favorite

### ISSUE THREAD

**Issue by polymorphisma** [coder/coder#13791]
Description:

I encountered an issue when making the following API request:

Request:
```
DELETE /api/v2/workspaces/********************************/favorite
Headers:
  - 'Coder-Session-Token': '*******************'
  - 'Content-Type': 'application/json'
  - 'Accept': 'application/json'
````
Actual Response:
```
{
  "success": true,
  "message": "Password changed successfully."
}
```

Documentation:
Refer to the official https://coder.com/docs/api/workspaces#unfavorite-workspace-by-id.
Steps to Reproduce:

Send a DELETE request to /api/v2/workspaces/{workspace_id}/favorite with the appropriate headers.
Observe the response message.
Notes:

The response status code was correct (204), but the message in the response body is incorrect and unrelated to the unfavorite action.
Please investigate and address this issue.

Thank you!

**Comment by deansheather** [comment]
This doesn't seem to be an error that is possible to be returned from Coder on any route (we don't return `"success": true` anywhere), so I think you may be mistaken. I'm going to close this issue, and if you can reproduce it on Coder then feel free to reopen.

**Comment by polymorphisma** [comment]
Thank you for your clarification. it was communication gap on our side. but if we request to the endpoint why it doesn't response anything in the response? it just returns 204 status code with no response message.

**Comment by angrycub** [comment]
@polymorphisma, The [204](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) is a logically complete response.
 
>A 204 No Content in response to these request methods has the following meaning and results:
>
>[DELETE](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE): The action was successful, and no further information needs to be supplied.
> ...

Using 204s to indicate successful deletes reduces response size and eliminates parsing of a "success" object that has dubious value. Had there been an error you would have received a response code >= 400, specifically based on the permalink above, a 403 if the workspace the caller deleting the favorite doesn't own it or a 500 if there is an internal error while attempting to service your request.

Hopefully this additional context helps.
