### ISSUE TITLE
CLI Docs: explain `--rich-parameter-file` format

### ISSUE THREAD

**Issue by stirby** [coder/coder#13839]
The CLI docs for `coder create --rich-parameter-file` do not explain the format or syntax for a parameter file. The alternative is to use `--parameter "key=value"` for every parameter in the template, which is tedious. We should briefly describe how to create a parameter file for this flag.

https://coder.com/docs/cli/create#--rich-parameter-file

cc: @mtojek

**Comment by joobisb** [comment]
@EdwardAngert @stirby 

I've raised a PR for this, please do have a look
