### ISSUE TITLE
Can't Upgrade Coder Google Cloud Marketplace Deployment

### ISSUE THREAD

**Issue by Chukwueloka** [coder/coder#13905]
I installed Coder through the Google Cloud Marketplace. How do I upgrade to the latest stable release (live version 2.12) since there is no place to upgrade from Google Cloud and Coder comes with version 2.3.2 (an old version) on Google Cloud Marketplace?

**Comment by ericpaulsen** [comment]
hi @Chukwueloka can you SSH onto the VM and run this command:

```
curl -L https://coder.com/install.sh | sh
```

this will upgrade the Coder binary on the machine.

**Comment by Chukwueloka** [comment]
Sure. I'll try and get back to you now.

**Comment by Chukwueloka** [comment]
Well, I ran the code you provided, started the server, logged out, and logged back in. But I still get the old coder of version 2.3.2. So I guess nothing changed. Is there another thing I can do on the machine?

**Comment by Chukwueloka** [comment]
Wait...

I just saw a new link when I started the server, checked it, and a fresh new installation opened. So I guess it worked.

**Comment by ericpaulsen** [comment]
@Chukwueloka you'll need to run:

```
sudo systemctl restart coder.service
```

in order to restart the Coder service with the newly upgraded binary. give this a try and reload the URL.
