### ISSUE TITLE
Handle shared enums between codersdk and other packages

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#1390]
## What is your suggestion?

Currently `codersdk` handles some enums and the typescript generator finds these and generates them in the typescript. We could more autogen validation code for this too.

Unfortunately, some enums come from other packages, such as `rbac.Actions`, `database.ProvisionerType`, `database.ProvisionerStorageMethod`, and some others. (See comments on [`typesGenerated.ts`](https://github.com/coder/coder/blob/d74eeb421591177733561b4f0bab37ee83b81334/site/src/api/typesGenerated.ts#L165))

We should come up with a solution that lets both packages use the same enum type, and ensure the typescript autogenerator will generate the enum type in typescript.

**Disclaimer**: I'm not sure how best to do this at the moment. A package just for `enums` feels like it might have issues in the future? Only if the enums ever need to have functions on them that need to import other packages.

## Why do you want this feature?

- Reduce enum duplication.
- Ensure shared enums between go and typescript
- Ensure all parts of the codebase are using the same enums (duplicating enums can desync them)
- Provide a central place to write enum validation logic for `go-playground/validate`

## Are there any workarounds to get this functionality today?

You can put the enum in `codersdk` and import it from your package. But `database` importing `codersdk` for an enum is kinda excessive and this might cause import loops later.

## Are you interested in submitting a PR for this?

I don't at this time, but happy to spend more time on it. Just a problem that I noticed.

**Comment by Emyrk** [comment]
@tjcran we can push it

**Comment by f0ssel** [comment]
@Emyrk I kind of like the intentional duplication of the two so it's obvious who is consuming what. Do you feel like there's still work that needs to be done here?

**Comment by Emyrk** [comment]
If we do stay with the copy, I think we should update `apitypings/main.go` to pull them over from the db into `.go` similar to how we make `.ts` files. I just think it's easy for the db and sdk to drift on things like enums.

The other thing about enums is that we do not validate enum strings atm, but if we autogen, we can autogen those validation functions/usage.

Right now the enums are quite weak in codersdk imo.

**Comment by kylecarbs** [comment]
@Emyrk I'm going to close this for now. I think we can make this more specific, and with the current broad framing, it seems unlikely to get done. Let me know if you disagree!
