### ISSUE TITLE
Add the ability to manage member roles from within the organization page

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#13914]
In our new organization view, [we list all org members](https://dev.coder.com/organizations/Default/members). We should give Coder operators the ability to manage member roles from within this view so they can permission members with r[oles they've created](https://github.com/coder/coder/issues/13911) (and remove permissions when necessary).

Note that ideally, we would like to de-duplicate user views rather than having multiple. For example, when this ticket is completed we will have user views for 
1) all users in a deployment 
2) all users in an org
3) all users in a group
We will revisit design and explore consolidating views after orgs is in experimental.

**Requirements**
- [ ] Give users the ability to add custom roles for org members in to `/organizations/[orgSlug]/members` which is already scaffolded and indicate success or failure with a toast
- [ ] Give users the ability to remove custom roles for org members in to `/organizations/[orgSlug]/members` which is already scaffolded and indicate success or failure with a toast
- [ ] For prior art, look at our [existing user table functionality](https://dev.coder.com/users?filter=status%3Aactive)
![Screenshot 2024-07-16 at 4 58 01 PM](https://github.com/user-attachments/assets/24b8c051-9fd8-42be-bd97-a650c853a400)
- [ ] Ensure only org admins, site wide user admins, and owners can add and remove roles for org members
- [ ] Add Jest tests for basic functionality
- [ ] Add storybooks
- [ ] Create a separate issue to encapsulate the work required to consolidate our three user views so that we can get started on this consideration after orgs is available as an experiment (and make sure to add this to the milestone!)

**Comment by Kira-Pilot** [comment]
>  Ensure only admins can add and remove roles for org members
@aslilac @Emyrk who can add and remove roles for org members? Is this correct?

**Comment by Emyrk** [comment]
@Kira-Pilot org admins, site wide user admins, and owners
