### ISSUE TITLE
CLI command to register a provisionerd and return a token

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#1392]
Problem:

Administrators who want to set up provisionerd running on a different server than Coder server need a credential to allow provisionerd to authenticate with Coder server.

Acceptance Criteria:

1. Log into Coder server as an admin
2. Run `coder provisionerd register`
3. Verify you obtain a token

**Comment by bpmct** [comment]
@spikecurtis would you be able to help with a problem statement and def of done on this one?

**Comment by kylecarbs** [comment]
Superseded by https://github.com/coder/coder/issues/44
