### ISSUE TITLE
flake: `TestProvisionerDaemon_SessionToken/PrometheusEnabled`

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#13931]
https://github.com/coder/coder/actions/runs/9987661978/job/27602490812?pr=13902

```
    provisionerdaemons_test.go:207: 
        	Error Trace:	/home/runner/work/coder/coder/enterprise/cli/provisionerdaemons_test.go:207
        	Error:      	Condition never satisfied
        	Test:       	TestProvisionerDaemon_SessionToken/PrometheusEnabled
```

```go
// Fetch metrics from Prometheus endpoint
var res *http.Response
require.Eventually(t, func() bool {
	req, err := http.NewRequestWithContext(ctx, "GET", fmt.Sprintf("http://127.0.0.1:%d", prometheusPort), nil)
	assert.NoError(t, err)
	// nolint:bodyclose
	res, err = http.DefaultClient.Do(req)
	return err == nil
}, testutil.WaitShort, testutil.IntervalFast)
```

**Comment by matifali** [comment]
seen again on `main`
logs: https://github.com/coder/coder/actions/runs/10017620244/job/27692037213#step:5:478

**Comment by mtojek** [comment]
It is not fixed yet. I'm thinkin about alternative solutions.

**Comment by dannykopping** [comment]
I'm sure you're referring to https://github.com/coder/coder/actions/runs/10058757918/job/27802570559?pr=13983 @mtojek , but I thought I'd add it here in case not.

**Comment by mtojek** [comment]
Unfortunately, I'm able to reproduce it fairly easy in the CI now, but I don't see an obvious reason [why it is happening](https://github.com/coder/coder/actions/runs/10059800516/job/27805888307):

```
t.go:102: 2024-07-23 13:27:18.148 [erro]  cli: http server listen  name=prometheus  error="listen tcp 127.0.0.1:54626: bind: address already in use"
```

 I tried to involve `lsof` to confirm that this port is utilized by go tests, but failed that as well (no command output?)

**Comment by matifali** [comment]
If it helps one can get SSH access into the CI runner, by adding this [action](https://github.com/mxschmitt/action-tmate) step

```yaml
- name: Setup tmate session
  uses: mxschmitt/action-tmate@v3
```
