### ISSUE TITLE
Provisionerd reads authentication token on startup

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#1393]
## Problem

Standalone provisionerd instances authenticate with Coder Server via a token. Admins need to pass this token when starting provisionerd.

## Definition of Done

1. export `CODER_PROVISIONERD_TOKEN` environment variable set to a valid token
2. start standalone provisionerd from commandline
3. verify provisionerd connects successfully to Coder Server.

**Comment by bpmct** [comment]
@spikecurtis would you be able to help with a problem statement and def of done on this one?

**Comment by kylecarbs** [comment]
Superseded by https://github.com/coder/coder/issues/44
