### ISSUE TITLE
cli: license expiry warning shows for end-users, customers

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#13939]
the CLI provides a warning for license expiry: 

![image](https://github.com/user-attachments/assets/b4f41c8c-84a7-42be-9db2-7aa80cfad771)

we have customers who are asking for us to remove this. it should only be kept for trial licenses.

**Comment by ericpaulsen** [comment]
related https://github.com/coder/coder/pull/13865

**Comment by ammario** [comment]
This was by design to encourage compliance. It's pretty easy to forget and delay license breaches in Coder.

**Comment by stirby** [comment]
We will keep the expiry notice and only show it to admins. 

It shouldn't be a burden to end-users.
