### ISSUE TITLE
flake: Test_sshConfigExecEscape

### ISSUE THREAD

**Issue by matifali** [coder/coder#13962]
flake: failed on `main` https://github.com/coder/coder/actions/runs/10017620244/job/27692037213#step:5:469

Seen 3 times in last 15 days.

**Test execution**: [Test_sshConfigExecEscape](https://app.datadoghq.com/ci/test/AgAAAZDOdFHAbeKHZQAAAAAAAAAYAAAAAEFaRE9kRkhBQUFEd1FzR1VMcEpCN19nRgAAACQAAAAAMDE5MGNlNzUtYWQ1NC00MjhhLWFkYmYtZDhiZTk0NzBjNmJk)

**Error**: 
```

Failed

=== Failed
=== FAIL: cli Test_sshConfigExecEscape/spaces (0.01s)
    configssh_internal_test.go:182: 
        	Error Trace:	/home/runner/work/coder/coder/cli/configssh_internal_test.go:182
        	Error:      	Received unexpected error:
        	            	exit status 126
        	Test:       	Test_sshConfigExecEscape/spaces

=== FAIL: cli Test_sshConfigExecEscape (0.00s)
```

**Comment by dannykopping** [comment]
Another datapoint: https://github.com/coder/coder/actions/runs/10244773420/job/28338436835?pr=14100

**Comment by mafredri** [comment]
Exit code 126 indicates the user wan't allowed to execute (e.g. missing +x permission), however, `os.WriteFile` is called with `0o755` so that shouldn't be the case. The fact that such a simple test is flaking sporadically is really weird. It does feel like something else is the cause.

**Comment by mafredri** [comment]
Nice find @ethanndickson! The path collision is very mind boggling since it should be unique on both t.TempDir and tt.path. It’d be interesting to know the exact cause but just disabling parallel seems like the best option for now 👍
