### ISSUE TITLE
Organizational scoped provisioner UI page 

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#13976]
Provisioners need a UI page, at the very least for view-only provisioner access. Provisioner page can be similar to `deployment/workspace-proxies` as far as functionality.

The provisioner page should show each provisioner key and the active provisioner daemons using said authorization key. This means keys are 1:many, and this relationship should be clear in the UI.

Each provisioner key has:
- `tags []string`
- `name string`

Each provisioner daemon that is created has:
- `name string`
- `version string`
- `date last_seen` :: influences health_status
- `provisioner_type []string` :: can only be `echo` or `terraform` (or both)
- `health_status string` :: We should do something similar to [workspace proxy](https://github.com/coder/coder/blob/c94f3e678774105d69759dd768602e4c9e012282/site/src/pages/UserSettingsPage/WorkspaceProxyPage/WorkspaceProxyRow.tsx#L180-L191) status to give a quick summary of the status. Enum list tbd
- `scope string` :: Can be `organization` or `user`. **Should user scoped provisioners show up here??**

```mermaid
erDiagram
    PROVISIONER_KEY {
        string[] tags
        string name
    }

    PROVISIONER_DAEMON {
        string name
        string version
        date last_seen
        string[] provisioner_type
        string health_status
        string scope
    }

    PROVISIONER_KEY ||--|{ PROVISIONER_DAEMON : creates
```

Listed above includes all the information from `/health/provisioner-daemons`, and expands on it. 

The design for this page should consider and draw up CRUD options to interact with the `keys`. Implementation can stay with view-only.

**Comment by Kira-Pilot** [comment]
@Emyrk can we fold this ticket into the 2 that @jaaydenh created off of his designs?
https://github.com/coder/coder/issues/14423
https://github.com/coder/coder/issues/14424

**Comment by Emyrk** [comment]
@Kira-Pilot I think you linked the wrong ones. This ticket is provisioners, not group/role sync

**Comment by Kira-Pilot** [comment]
> @Kira-Pilot I think you linked the wrong ones. This ticket is provisioners, not group/role sync

Whoops you're right!
