### ISSUE TITLE
Allow a configurable default TTL to tokens generated by `coder login`

### ISSUE THREAD

**Issue by stirby** [coder/coder#13990]
Some customers have requested that we allow the default TTL for session tokens to be customizable. Adjusting our native default cannot improve this, as some customers have requested tighter lifetimes for security purposes, whereas others want to extend them for convenience. 

We should allow the default to be customizable at the deployment level. We don't need to allow users to pass a TTL in the `coder login` call, just need to allow administrators to customize the default maximum.

**Comment by stirby** [comment]
Ideally this will be org-scoped in the future.

**Comment by mariodescanva** [comment]
Is there an opportunity here to also communicate with the Coder's Intellij plugin to pick up the new token once refreshed, so the user experience is not impacted?

**Comment by bpmct** [comment]
How does this compare with https://coder.com/docs/cli/server#--session-duration?

**Comment by ethanndickson** [comment]
`--session-duration` currently defaults to 24 hours, whilst tokens from `/cli-auth` last the unconfigurable 7 days. Making `/cli-auth` tokens last 24 hours by default sounds a little annoying, and I imagine there's good reason for browser sessions to only last 24 hours. I'd like to avoid another flag like `--cli-session-duration`, but can we reasonably consolidate either of these default durations?
