### ISSUE TITLE
Site: Most UI elements for templates cannot handle long text

### ISSUE THREAD

**Issue by Parkreiner** [coder/coder#14007]
Spurred by a customer request. This should be a quick CSS fix; hoping to get this closed out by end of day tomorrow.

## Problem
On the `/workspaces` and `/templates` routes, several UI elements that deal with templates are not able to handle long text that don't have natural semantic line breakpoints (such as URLs that don't use hyphens to separate words). Long text like this is neither truncated nor forced to have per-character line breaks. In some cases, this makes elements entirely unreadable.

### `/workspaces` page

This was the main customer request. When there are no workspaces available, the UI will show an empty state with templates that can be used. The cards in this empty state cannot handle long text values for either the title or the description.

<img width="1004" alt="Screenshot 2024-07-24 at 5 06 41 PM" src="https://github.com/user-attachments/assets/e6a834e0-e12f-4c37-9d2b-7ad3484975bb">

### `/templates` page
Most template titles cause the user count to overflow in an awkward way, with too much text leading relative to the text size. Text doesn't need to be especially long to trigger this edge case.
<img width="703" alt="Screenshot 2024-07-24 at 4 39 31 PM" src="https://github.com/user-attachments/assets/4c91bddb-c83e-4db1-a6e1-aa10e136a935">
Just because these boxes are so thin, I think the user count should be moved down, inline with the "default" text. That would also give the titles a lot more room.

Similar to the workspaces issue, if a long enough text value with no natural line breaks is put in a template description, it overflows past the container. In this case, this doesn't obscure any nearby elements, but it does make the affected template a lot harder to read.
<img width="724" alt="Screenshot 2024-07-24 at 4 55 08 PM" src="https://github.com/user-attachments/assets/fbb058af-b640-41db-af26-8a2e68331f76">

The titles themselves also don't handle long text like this well
<img width="1333" alt="Screenshot 2024-07-24 at 4 57 51 PM" src="https://github.com/user-attachments/assets/67d241ee-71d8-414a-aece-55f444572aa2">

## Steps to reproduce

1. Create a template with a long title and/or description (something like 100+ characters).
2. Navigate to the `/workspaces` page while there are no workspaces associated with the account
3. Afterwards, navigate to the `/templates` page

## Other notes
Not strictly something that affects functionality, but we have a lot of unused space in the main Templates page. Going to see what I can do to update this without changing the aspect ratios on the cards too much
<img width="1379" alt="Screenshot 2024-07-24 at 5 01 23 PM" src="https://github.com/user-attachments/assets/ff8a80e6-3928-4044-9668-25470e9e7fb7">

**Comment by ukane-philemon** [comment]
fixed by #14015.
