### ISSUE TITLE
flake: `TestWebhook`

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#14060]
https://github.com/coder/coder/actions/runs/10160076838/job/28099341613

```
=== Failed
=== FAIL: coderd/notifications/dispatch TestWebhook/timeout (0.00s)
    webhook_test.go:141: 
        	Error Trace:	C:/a/coder/coder/coderd/notifications/dispatch/webhook_test.go:141
        	Error:      	Error "request failed: Post \"[http://127.0.0.1:58567\](http://127.0.0.1:58567/)": dial tcp 127.0.0.1:58567: i/o timeout" does not contain "request timeout"
        	Test:       	TestWebhook/timeout
```

**Comment by DanielleMaywood** [comment]
Seen here: https://github.com/coder/coder/actions/runs/10616310615/job/29426476782?pr=14475

**Comment by dannykopping** [comment]
Another datapoint: https://github.com/coder/coder/actions/runs/10631235935/job/29471729607

**Comment by johnstcn** [comment]
Also seen here except with `EOF` instead: https://github.com/coder/coder/actions/runs/10631520132/job/29472618127?pr=14460

**Comment by dannykopping** [comment]
Thanks for the datapoints folks, I'll get on this today.
