### ISSUE TITLE
[Bug] Wrong Emoji descriptions

### ISSUE THREAD

**Issue by Ed1ks** [coder/coder#14105]
Coder Version: v2.13.2+48c4859
Bug: A lot of Emojis have a wrong description/wrong emoji code. Image does not match code, and after selectiing it shows the emoji from code.
![image](https://github.com/user-attachments/assets/6929d676-4936-44e4-a1ac-f78ac411cc26)

**Comment by matifali** [comment]
cc: @coder/ts

**Comment by code-asher** [comment]
Might have been fixed by https://github.com/coder/coder/pull/13746
