### ISSUE TITLE
Uploading template zip file in the UI does not work

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#14124]
When trying to upload a zip file in the UI to create a template nothing happens but an error is shown in the console.

**Comment by mtojek** [comment]
Taking a look

**Comment by mtojek** [comment]
Confirmed. 

Steps:

1. Download the template using CLI: `./scripts/coder-dev.sh templates pull --zip docker-copy > t1.zip`
2. Push t1.zip using browser.

There is an error reported in the Chrome console. Apparently the site expects .tar archive?

```
Warning: An unhandled error was caught from submitForm() dit: run parse: recv parse source: extract archive: read template source archive: archive/tar: invalid tar header
    at UQ (http://localhost:3000/assets/index-B65M6Mso.js:610:113486)
    at async Object.uit [as mutationFn] (http://localhost:3000/assets/index-B65M6Mso.js:610:112638)
```

Most likely
