### ISSUE TITLE
User cannot set name

### ISSUE THREAD

**Issue by dgaiero** [coder/coder#14142]
Version: [`v2.12.6+d65eea8`](https://github.com/coder/coder/commit/d65eea8132117777302296d91cd19469ea2c92c3)

I'm using OIDC authentication with Entra ID, and my users cannot set the `name` field in their Account - it is greyed out. However, when I promote a user to the `User Admin` role, they are able to change their name.

The `Name` field should pull from the name OIDC claim or allow the user to set it in their account settings. Since they cannot set it, the user's GitHub commits have the name of `default`.

**Comment by kylecarbs** [comment]
Hmm, will investigate. TY

**Comment by ericpaulsen** [comment]
@dgaiero the design here is intentional, as Terraform resources are typically named using the field `data.coder_workspace_owner.full_name`, so allowing for users to change this field can result in resource deletion & data loss. - https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace_owner#full_name

the best practice is to maintain your users' `name` field in your OIDC provider, and have Coder treat that as the source of truth via the claim sync. i'm happy to help troubleshoot the `name` claim synchronization if need be.

**Comment by dgaiero** [comment]
Okay, that makes sense to me. When I navigate to: https://coder.domain.com/api/v2/debug/jdoe/debug-link, the output is:

```json
{
    "id_token_claims": {
        "rh": "<REDACTED>",
        "aio": "<REDACTED>",
        "aud": "<REDACTED>",
        "exp": "<REDACTED>",
        "iat": "<REDACTED>",
        "iss": "https://login.microsoftonline.com/<REDACTED>/v2.0",
        "nbf": "<REDACTED>",
        "oid": "<REDACTED>",
        "sub": "<REDACTED>",
        "tid": "<REDACTED>",
        "uti": "<REDACTED>",
        "ver": "2.0",
        "name": "John Doe",
        "email": "jdoe@domain.com",
        "preferred_username": "jdoe@domain.com"
    },
    "user_info_claims": {
        "sub": "<REDACTED>",
        "name": "John Doe",
        "email": "jdoe@domain.com",
        "picture": "https://graph.microsoft.com/v1.0/me/photo/$value",
        "given_name": "John",
        "family_name": "Doe"
    }
}
```

So, I see the name claim in there, and it looks correct, but in Coder, it is not picked up.

And the service logs for docker container show:

```
2024-08-04 19:39:53.274 [debu]  coderd.userauth: got oidc claims  request_id=bc929245-79f7-4eb3-bee1-02a12ecd360c  source=id_token  claim_fields="[aio aud email exp family_name given_name iat iss name nbf oid preferred_username rh sub tid uti ver]"  blank=[]
```

**Comment by ericpaulsen** [comment]
@dgaiero the claims output looks good. can you provide the OIDC-related environment variables set on the Coder server?

**Comment by dgaiero** [comment]
@ericpaulsen 

These are my OIDC-related env vars:

```
CODER_OIDC_CLIENT_ID=4c15f3f1-7b84-4107-9abd-621b97599ad7
CODER_OIDC_CLIENT_SECRET=<REDACTED>
CODER_OIDC_EMAIL_DOMAIN=domain.com
CODER_OIDC_GROUP_AUTO_CREATE=true
CODER_OIDC_ISSUER_URL=https://login.microsoftonline.com/4c15f3f1-7b84-4107-9abd-621b97599ad7/v2.0
CODER_OIDC_SIGN_IN_TEXT=Sign in with SSO
```

And, looking at the Deployment page on the web app, I see the scopes are set to the default:

- openid
- profile
- email

**Comment by ericpaulsen** [comment]
thank you @dgaiero - can you try including the `name` scope in your `CODER_OIDC_SCOPES` environment variable?

**Comment by dgaiero** [comment]
Hmm, that didn't seem to work. When I access https://coder.domain.com, I am greeted with just this:

```
{
    "message": "Encountered error in oidc process: invalid_client",
    "detail": "AADSTS650053: The application 'Coder' asked for scope 'name' that doesn't exist on the resource '00000007-0000-0000-f000-000000000000'. Contact the app vendor. Trace ID: 1238f723-091b-4fac-afb2-73673a0a804d Correlation ID: f11e7bc5-2960-47d9-b124-3c4365c965fe Timestamp: 2024-08-04 23:32:01Z"
}
```

**Comment by dgaiero** [comment]
I updated coder to the mainline `2.13.3` release, and the name works as intended, although the member role can update their name.

https://github.com/coder/coder/issues/13694 - I'm going to go ahead and close this, thanks for your help troubleshooting!
