### ISSUE TITLE
Organization Provisioner Daemons API GA

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#14188]
Tasks related to preparing provisioner daemon APIs for general use. Not all tasks may be required and the list will be added to as new items are identified. 

- [x] Allow provisioner tags to be removed - https://github.com/coder/coder/pull/14187
- [x] ~~Display **accurate** tags in provisioner start logs when using a provisioner key~~ Would require too many auth changes to make displaying the calculated tags it worth it, will continue to display the input tags (which are always empty `{}`)
- [x] Stop requiring org field when providing provisioner key
- [x] Create plan for PSK deprecation
- [x] ~~merge PSK and provisioner key arg in cli~~ Deprecated psk flag and point to key flag
- [x] ~~return provisioner warnings to FE~~ - handled on FE

Reach
- [x] ~~We should have realtime data on the connection status of provisioners. This will allow us to build better UX with less dead ends when setting up and running new organizations. (out of scope for GA)~~

**Comment by Kira-Pilot** [comment]
Est: S
