### ISSUE TITLE
Multi-Organization Role Sync compatibility upgrade

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#14203]
Role sync currently only works for site-wide roles. This functionality should remain, with the addition that organization roles can also be assigned.

[`oidcRoles`](https://github.com/coder/coder/blob/8c0565177e5bc5611130df54cf857f9e6a468027/coderd/userauth.go#L1161-L1161) should return `[]rbac.RoleIdentifier` rather than `[]string` to support organizational roles.

Given the "self serve" nature of organizations, org role assignment configuration might want to be deferred to org admins. So the current deployment wide config _could remain_, with an organization specific configuration extension.

Some debugging and visual tools to see which roles are available via the IDP would be required.

# Deployment configuration to upgrade

# Static role mapping

[User role mapping](https://github.com/coder/coder/blob/8c0565177e5bc5611130df54cf857f9e6a468027/codersdk/deployment.go#L1600-L1609) is defined as a static `OIDC_Role -> Coder Site Role`. We either need to allow an organization context in the existing configuration option, or add a new config field to inject an organization role.

**Comment by Kira-Pilot** [comment]
Est: L

**Comment by Emyrk** [comment]
Closed
https://github.com/coder/coder/pull/14649
https://github.com/coder/coder/pull/14692
