### ISSUE TITLE
Multi-Organization SCIM compatibility upgrade

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#14204]
SCIM assumes the default org when [inserting a new user](https://github.com/coder/coder/blob/8c0565177e5bc5611130df54cf857f9e6a468027/enterprise/coderd/scim.go#L239-L239). What this means is SCIM can only assign members into the first organization, then it manages the user from a site-wide perspective.

~~A simple solution to push this down the road is to add a new config option such as `SCIM_ORGANIZATION` which allows specifying the organization to insert SCIM users when they first appear. We can use the keyword `default` to designate the default organization.~~

A simple solution is to just drop SCIM adding users into any org. It just creates a user on the site with 0 orgs. Let OIDC organization sync handle org associations.

In the future, we might want SCIM to take action within an organization, such as removing a member. At present, we can rely on group sync to do this?

**Comment by Kira-Pilot** [comment]
Est: S
