### ISSUE TITLE
Account settings page currently lists the current groups a user is in. Should either replace, or include which organizations

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#14213]
Multi-organizations make this listing of groups not a full accounting of a user's memberships on the product. We should probably list all the organizations and their groups within each organization.

Screenshot from `/settings/account` page

**Requirements**

- [ ] add additional detail to give org-scope without scrapping original design (keep design scope small)
- [ ] add org name and avatar to existing query
- [ ] Ensure storybook exists and update it

![Screenshot from 2024-08-07 16-32-28](https://github.com/user-attachments/assets/8afb6c5d-f0cd-4a9c-9123-e2bbf3906cef)

Related: https://github.com/coder/coder/pull/14200

**Comment by Emyrk** [comment]
This is the api call to use: https://github.com/coder/coder/blob/a8c89a4a2f2cc196b05470bf4a8b2615efd40d3c/enterprise/coderd/groups.go#L404-L413

You must include the query param `has_member` to the userid of the user displayed.

**Comment by Kira-Pilot** [comment]
Est: M
