### ISSUE TITLE
Add password reset via email

### ISSUE THREAD

**Issue by stirby** [coder/coder#14232]
We allow administrators to reset a user's password via the CLI by connecting directly to the database (https://github.com/coder/coder/pull/1380). Otherwise, users may change their password in their [account settings](https://dev.coder.com/settings/security).

As a user, when I forget my password, I would like to reset it autonomously. This flow is facilitated in most products through a reset password link delivered to the user's email. We can implement the same flow using the new system-generated notifications. 

When SMTP notifications are configured for a deployment, a new option would appear on the login page:

![Screenshot 2024-08-13 at 4 29 15 PM](https://github.com/user-attachments/assets/260eaeff-78da-497f-8252-9fa28aede0e2)

They'd then receive an email containing a link to create a new password.

> [!NOTE]
> This would introduce a security vulnerability for teams, so admins should be able to disable the feature for their deployment or organization (once merged).

**Comment by DanielleMaywood** [comment]
Proposal for how this would look:

- User clicks "Forgot password?"
- User is presented with a screen that asks for their email
- User enters the email of their account
  - A one-time-passcode is sent to their email (with a short expiry)
  - User is presented with a field for the one-time-passcode
  - Show message in the UI such as "A one-time-passcode has been sent to your email if the provided email is valid"
    - We shouldn't have a different message if the email is valid or not to prevent enumeration attacks
- User enters one-time-passcode
  - All existing sessions are logged out
- User is logged into account
- User is presented with a mandatory reset password screen

The decision to send a one-time-passcode to the users email over sending a password reset link is that many places advise against clicking links in emails as it makes people more susceptible to phishing attacks. This flow doesn't pose the same risk as the user never has to click a link from their email.

@stirby thoughts on this approach?

**Comment by stirby** [comment]
This is exactly as I imagined, except: 

> The decision to send a one-time-passcode to the users email over sending a password reset link is that many places advise against clicking links in emails as it makes people more susceptible to phishing attacks. 

But your rationale is very thoughtful. Let's do it.

**Comment by DanielleMaywood** [comment]
After a discussion with @johnstcn and @mafredri we have come up with a slightly simplified flow.

Rather than these final 3 steps as originally presented:
- User enters one-time-passcode
  - All existing sessions are logged out
- User is logged into account
- User is presented with a mandatory reset password screen

We'd instead do this:
- User enters one-time-passcode and new password (with a confirmation field).
  - All existing sessions are logged out.
  - User is logged in.

This removes an extra step from the flow.

How does this sound to you @stirby?

**Comment by stirby** [comment]
Yes, all for simplification @DanielleMaywood. 

One more question: do we hide the button when
- User sign-in is not simple (password) 
- SMTP is not configured

**Comment by DanielleMaywood** [comment]
For both it will be hidden.

- If password sign-in isn't enabled, then the button would be misleading.
- If SMTP is not configured, then we cannot send the email with the code, making the feature useless.

**Comment by mtojek** [comment]
@BrunoQuaresma Heads-up, this issue will require frontend work 👍 @DanielleMaywood will share details.

**Comment by chrifro** [comment]
To help with the UI, I created mockups based on the existing design and the described user flow. Note: the mockups are not pixel-perfect as they are partially based on screenshots
See [Figma](https://www.figma.com/design/OR75XeUI0Z3ksqt1mHsNQw/Dashbord-v1?node-id=438-1998&t=R7Kph2Eu3wzBf3mp-1)

![Image](https://github.com/user-attachments/assets/7a206fd3-99a4-43eb-bf6b-f8fa1aad9070)
![Image](https://github.com/user-attachments/assets/ad55e093-2f4e-4a29-b2ff-ebab6be59064)
![Image](https://github.com/user-attachments/assets/eb747a51-8e7e-4c8b-a742-823443612ee1)
![Image](https://github.com/user-attachments/assets/d2935f10-b3ab-4a3d-85cb-b663d35689c4)

Over to you @BrunoQuaresma 🏀

**Comment by johnstcn** [comment]
Thought: we should probably add a more aggressive rate-limit to the "request password reset" page. I think once per minute should be more than sufficient.

**Comment by BrunoQuaresma** [comment]
Closed by https://github.com/coder/coder/pull/15108
