### ISSUE TITLE
`coder delete` doesn't accept fully qualified workspace name

### ISSUE THREAD

**Issue by ammario** [coder/coder#1424]
<img width="588" alt="Screen Shot 2022-05-13 at 10 21 11 AM" src="https://user-images.githubusercontent.com/7416144/168315338-9c3d3c63-3f15-458d-8ce7-922e4fcd7b3e.png">

**Comment by kylecarbs** [comment]
Admins can access workspaces for many users:
![image](https://user-images.githubusercontent.com/7122116/171209759-d5264d5e-6a9d-4444-a977-7c716cdae77c.png)

They should be able to interface with other users' workspaces just like their own, and namespace with `<username>/`.

eg.
```
coder rm someone/workspace
```
