### ISSUE TITLE
Notifications: allow customers to rebrand email

### ISSUE THREAD

**Issue by stirby** [coder/coder#14253]
Some customers use our deployment appearance options to rebrand the UI. If their users receive an email from Coder when the platform has been cosmetically changed, they may block the unfamiliar source.

We should pull from the deployment appearance and display it in the email like so:

![Screenshot 2024-08-09 at 10 54 54 AM](https://github.com/user-attachments/assets/bc7ded2f-08b6-4134-9844-fecbfa862b18)

Oddly, we suggest a logo with a 3:1 aspect ratio alongside the deployment name. Maybe we should only use the logo in the email, as some customers may include text in the image. 

This doesn't block experimental but should be included in GA.

**Comment by stirby** [comment]
cc @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
I think I can take this inside of the current sprint. Wdyt?

**Comment by stirby** [comment]
That'd be great.
