### ISSUE TITLE
:star: Add organization context to the workspaces table 

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#14278]
Add organization information to the workspaces table. One option is to put the organization name underneath the Template name.

**Requirements**

- [x] add org name only (not a link) to workspace table
- [x] only display org name according to existing `useDashboard` hook's `dashboard.showOrganizations` prop - if requirements shift, this ticket is no longer valid
- [ ] add test for conditional logic 
- [ ] timebox design to 1 day
-

![Screenshot from 2024-08-15 13-55-52](https://github.com/user-attachments/assets/1716d545-97d3-471a-ac00-edc64946bf1f)

**Comment by kylecarbs** [comment]
Just to confirm, the orgnaizations stuff only shows up if you have more than one, right?

**Comment by Emyrk** [comment]
I find it a bit strange to have conditional ui like that. The idea is to place it in the "Templates" column to not take up any more horizontal space. _Something like_ this.

![Screenshot from 2024-08-21 09-56-48](https://github.com/user-attachments/assets/0ac6fc27-42e0-4ed2-a2d3-8e5b3dfdcbdb)

"More than 1" could mean you have no workspaces in more than 1 org, but you belong to more than 1 org.

It could mean you are a member of 1 org, but there exists more than 1.

In those two cases, I think we'd want to show orgs?

**Comment by Kira-Pilot** [comment]
**idea from other mocks**
![Screenshot 2024-08-26 at 12 12 01 PM](https://github.com/user-attachments/assets/510ebeed-505a-4559-86a6-07339cf1dc50)

**Comment by Kira-Pilot** [comment]
Est: S
