### ISSUE TITLE
:star: Custom roles no premium license behavior

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#14318]
This feature requires a premium license, not an enterprise license and we should differentiate it somehow.
Custom roles can also still exist, even if the license does not exist, or is expired. Custom roles should still be listed in a view-only mode. So keep the table regardless of the license. Just show an empty table if no custom roles exist.

**Requirements**
- [ ] Theme the premium license in a different color palette and consult Matt V for branding inspiration
- [ ] Paywall should always show if license isn't valid
- [ ] Table should always show regardless of license according to the criteria below
- [ ] Add table for custom roles if custom roles exist even if license is no longer valid
- [ ] Add table for empty state (no custom roles)
- [ ] Add storybooks for different states

![Screenshot from 2024-08-15 16-18-06](https://github.com/user-attachments/assets/9ae0df31-738e-4e7a-af0e-126db847eef3)

**Comment by Kira-Pilot** [comment]
@mattvollmer Do you have any existing design or insight as to the new premium license color palette?

**Comment by mattvollmer** [comment]
Hey, thanks for tagging me in. Let's aim for something in this palette:
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/9d9f5ebf-dec9-4e73-b37d-a26c6b7d8fe9">

I can help with copy, too. Just let me know what you need.

**Comment by Kira-Pilot** [comment]
Est: S

**Comment by mattvollmer** [comment]
@jaaydenh let me know if there is a permutation I missed:

For the New Organization Premium banner:
> Create multiple organizations within a single Coder deployment, allowing several platform teams to operate with isolated users, templates, and distinct underlying infrastructure.

For the New Organization Premium banner (existing customer on a Standard license):
> The Organizations feature is available in the Premium plan and requires an upgraded license. Please contact your Customer Success team for more information.

For Custom Roles:
> Create custom roles to grant users a tailored set of granular permissions.

For Custom Roles (existing customer on a Standard license):
> Custom Roles are available in the Premium plan and require an upgraded license. Please contact your Customer Success team for more information.

**Comment by jaaydenh** [comment]
@mattvollmer looks like you added text for the banner description on the left. Do you also want to update the bullet points on the right side of the banner?

**Comment by mattvollmer** [comment]
> @mattvollmer looks like you added text for the banner description on the left. Do you also want to update the bullet points on the right side of the banner?

Good point. I updated my previous comment. If these points are too long, let me know. Hopefully, we can adjust the padding to squeeze them in.
