### ISSUE TITLE
New scratch template and upload template are not visible in the UI

### ISSUE THREAD

**Issue by alessandro-newzoo** [coder/coder#14323]
Hello,

[I've been told](https://github.com/coder/coder/discussions/14258#discussioncomment-10356083) there should be buttons to:
- create a new template from scratch
- upload a template

But I don't see either.

https://github.com/user-attachments/assets/a947aba9-8396-46e7-af20-29127c2f23cb

![CleanShotX - Arc  16 08 2024 at 11-27-39 @2x](https://github.com/user-attachments/assets/3e60537c-1a02-49da-97b4-f5644d5cf9c9)
![CleanShotX - Arc  16 08 2024 at 11-27-58 @2x](https://github.com/user-attachments/assets/10adfe14-6bcc-4a3d-a4ac-c6fc887c093f)
![CleanShotX - Arc  16 08 2024 at 11-28-26 @2x](https://github.com/user-attachments/assets/9b4951f9-adf9-44fe-a9e4-8f1f6ab1deca)
![CleanShotX - Arc  16 08 2024 at 11-30-48 @2x](https://github.com/user-attachments/assets/dfbf3686-d554-4f69-9c6f-36fb8289fcc3)

```
coder --version
Coder v2.14.1+db94b30 Wed Aug  7 16:56:07 UTC 2024
https://github.com/coder/coder/commit/db94b30b1c418b3ab77a0f5e205a2992288b10e7
```

Coder was installed on a VPS running `Ubuntu 24.04` with:
`curl -L https://coder.com/install.sh | sh`

Browsers tested (macOS):
- Arc 1.56.0 (52658)
Chromium Engine Version 127.0.6533.120
- Safari 17.6

**Comment by matifali** [comment]
@stirby I can reproduce this on 2.14.1 but not on `main`. It could have been lost during the redesign of the multi-org experiment.

**Comment by stirby** [comment]
This is fixed in the latest releases!
