### ISSUE TITLE
Template constraint for workspace scheduling

### ISSUE THREAD

**Issue by ammario** [coder/coder#1433]
Related https://github.com/coder/coder/issues/813

In v1, we have customers that wanted to shut down all workspaces in an organization on a period while simultaneously giving their developers control to suit their working patterns and time zone. 

The problem with developer controlled auto stop is they're not the ones incentivized to reduce costs.

## Solution

The cleanest solution I could think of is we allow the ability to set an auto-start at the _template_ level in addition to the workspace level. That auto-stop can be overridden by the workspace, but only by schedules that have the same interval or less. For example, if a daily auto-stop is set in the template, a daily one must be set by the user.

Auto start policy is flipped, the template interval serves as the floor instead of the ceiling.

A caveat with this approach is UX complexity.

For example, if I set a template cron auto start of 9am CST Mon to Fri, and then a user configures 9AM GMT Tues to Sun (one extra day), we need a really clear error, because it's an easy mistake to make. 

## Org-level auto-start
We don't implement this. For one, it's added complexity. For two, the templates describe the resource costs, they should also describe the cost management. This is consistent with [my proposed quota system.](https://www.notion.so/coderhq/Quotas-v2-c03453d1aba64e7d801c2cd5d1b11049)

---

cc @johnstcn 

## Acceptance Criteria

- [/] Template: set `max_ttl` and `min_autostart_duration`
- [/] Workspace: `ttl` and `autostart_schedule` constrained by template
- [/] Template: update `max_ttl` and `min_autostart_duration`

**Comment by ammario** [comment]
> * Autostop: adding a field `max_ttl` on the template which limits the maximum value of `ttl` on all workspaces derived from that template. Defaulting to 168 hours, enforced on edits to workspace metadata.
Makes sense.


> * Autostart: adding a field `min_autostart_duration` which limits the minimum duration between successive autostarts of a template, measured from a single reference time. Defaulting to 1 hour, enforced on edits to workspace metadata.

Isn't it impossible for autostarts to be less than 24h apart in the current implementation?

**Comment by ammario** [comment]
Oh, how would a user configure an auto start that is more frequent than 24h a day? I can't figure it out in the CLI or the UI.

**Comment by johnstcn** [comment]
> Oh, how would a user configure an auto start that is more frequent than 24h a day? I can't figure it out in the CLI or the UI.

You'd have to do something like:
```
coder autostart enable test --minute=0 --hour='*' --tz Europe/Dublin
```

This would start the workspace on the hour.

**Comment by ammario** [comment]
Oh, right 🤦🏽‍♂️. Yeah I don't think it matters too much either way. The CLI experience should be good but I think we can be more reactive on interval limits.

**Comment by ammario** [comment]
@johnstcn why can't constraints be updated after the template is first created?

**Comment by johnstcn** [comment]
> @johnstcn why can't constraints be updated after the template is first created?

#2159

**Comment by ketang** [comment]
Nit: could it be confusing to use the `edit` command to change metadata rather than the core scripts?

Can these be edited non-interactively via command line arguments?

**Comment by johnstcn** [comment]
> Nit: could it be confusing to use the edit command to change metadata rather than the core scripts?

What do you suggest as an alternative name? Would `editmeta` or `metadata` sound better?

> Can these be edited non-interactively via command line arguments?

Currently, only non-interactive editing is supported.

**Comment by ketang** [comment]
Perhaps `coder template schedule`?

Non interactive only is fine.

**Comment by johnstcn** [comment]
> Perhaps `coder template schedule`?

There's other template-specific metadata such as description that doesn't relate specifically to the template schedule; do you want to break this out into separate template subcommands?

**Comment by ketang** [comment]
Maybe not.  Given that this is non-interactive, then it isn't the issue I assumed because users aren't prompted for a bunch of stuff they don't want to change.  They opt in via the arguments they pass.  `edit` is good, carry on, carry on.

**Comment by ammario** [comment]
Your rationale makes sense.
