### ISSUE TITLE
design: quota consumption UI

### ISSUE THREAD

**Issue by jaaydenh** [coder/coder#14358]
Design for org-scoped quota consumption.

https://www.figma.com/board/RhKLJDa5Kx0d2poMQodwg1/Design-Sprint?node-id=8-144&t=0GkBAIaIjmXBBlGt-4

![Screenshot 2024-08-30 092602](https://github.com/user-attachments/assets/4cc36960-2da4-4af3-8ae1-16b1d0ef4eb0)

**Comment by stirby** [comment]
@Kira-Pilot, @jaaydenh, closing this in favor of the finished design.

https://github.com/coder/coder/issues/14435
