### ISSUE TITLE
cannot search template name with spaces 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#14384]
https://github.com/user-attachments/assets/526e4b74-6160-46f9-bd02-07490b72c438

**Comment by Emyrk** [comment]
This is a UI issue actually. The error is the same as returned on the workspaces page. We should match that behavior.

![Screenshot from 2024-08-29 10-00-11](https://github.com/user-attachments/assets/e6b7e100-8830-4215-a5a9-538f18600dea)

**Comment by bpmct** [comment]
Can we still make this UX better? People will not know to wrap the name in quotes

**Comment by bpmct** [comment]
One suggestion is to automatically wrap in quotes. Another is to automatically pass %20 into the query. Really not sure, but right now the search feels quite useless

https://github.com/user-attachments/assets/ed2b1729-191a-4d28-8ae6-d6f995044fdf

**Comment by Emyrk** [comment]
I think we only search the `name` not the `display_name`. Should we switch it, or search both names?

**Comment by matifali** [comment]
Searching both name and display-name could be better.

**Comment by rafrdz** [comment]
Created a PR: https://github.com/coder/coder/pull/19552 to add support for spaces in search queries and added support for searching on `name` and `display_name` in templates. I added some videos and examples on some downsides to searching on both. In the PR I propose searching only on `display_name` when a user enters text into the search box and only search on `name` if a user searches for a name specifically. Happy to hear some feedback on that proposal and make any changes 😄
