### ISSUE TITLE
Support names longer than 32 characters

### ISSUE THREAD

**Issue by bpmct** [coder/coder#14408]
In several places, we limit names to being only 32 characters. We have some users who want to support longer group names for group sync, longer usernames, etc. Can we increase this to at least 36 characters to support GUIDs, which is common for group sync?

Since the group name is an internal field (the display name overrides it), I am not concerned about this causing display issues in the Ui. It may become a problem for usernames, but don't think there's much harm in increasing to 36

<img width="652" alt="Screenshot 2024-08-22 at 5 08 49 PM" src="https://github.com/user-attachments/assets/3f4e35e9-540c-4945-ae3d-1597aef98917">

**Comment by matifali** [comment]
Related to #10708

**Comment by LMezler** [comment]
For EnBW this is an urgent topic. We cannot use the group mapping because the groups we use are added dynamically ( we do not know them in advance) and changing the group mapping requires a restart of Coder.  And we need to set GUIDs from EntraID as group names to use the group sync feature.
