### ISSUE TITLE
Long response times and high latency

### ISSUE THREAD

**Issue by pxPP** [coder/coder#14413]
Hi!

Since yesterday we have been experiencing very long loading times and high latency.
The problem occurs both in the Coder interface itself and in all our workspaces.

![image](https://github.com/user-attachments/assets/42b65dde-15fe-4476-b135-0a582c8d1920)
![image](https://github.com/user-attachments/assets/c87c50af-4aee-42ba-a47e-18ca98ffe45f)

In workspace applications the loading times are even slower, around 20 sec for a JS bundle. It seems that the more assets are loaded at the same time, the longer it takes. 

We have not changed anything in our setup since the problems started.

We run Coder as a Docker container on a dedicated Hetzner VServer.
The server has 2 cores and 8GB RAM and has a load average of 0.2.
A Traeffik runs as a proxy in front of the coder container.
We have Traeffik running in version 2.11.
We have tested Coder with both 2.14.1 and 2.14.2.

A server ping is around 15ms.
Server Internet Connections is in download around 2200 Mbps and in upload 1400 Mbps with a ping of 5ms

Our workspaces are located in the Google Cloud.

We have been running this setup for over a year now with about 8 people without any loss of performance. The problem can be found at various locations, so a local Internet problem can be ruled out.

Of course we have already tried a server restart.

We are now at a point where we no longer know what we can do?
Is there anyone with similar experiences or ideas?

Regards

**Comment by matifali** [comment]
Hi @pxPP Where do you host the Postgres Database? And what do you see on the `/heath` page?

**Comment by pxPP** [comment]
Hi @matifali 
The Database is hosted within the same docker-compose file as the coder application.

There is nothing conspicuous for me on the health side.
Which values are most interesting for you?

```
Database Reachable
Yes
Latency
0ms
Threshold
15ms
```

**Comment by matifali** [comment]
I was interested in knowing the latency between Coder control plane and database if its an external database. But as its in the same node as Coder so that is ruled out. There should not be any other reason of slow responses other than a network issue. 

Do you still face this issue consistently? Also what is the disk space status? Do you have enough free disk space?

**Comment by pxPP** [comment]
Yes, we have also created a ticket with our server operator for a check to rule out server or network problems. But all the server values so far look just as normal and unobtrusive.

Disk space is still over 50% available.

The latency problem can always be reproduced with a hard reload of the dashboard. The page then remains white for approx. 5 - 6 seconds until the bundle has finished loading.

**Comment by pxPP** [comment]
After analysis by the hoster, a problem in the network was identified. There is therefore no problem in the application! 

Thanks for the support though!
