### ISSUE TITLE
UI: Integrate backend data with skeleton UI for IDP Sync

### ISSUE THREAD

**Issue by jaaydenh** [coder/coder#14424]
1. Populate the fields, groups field, roles field, group regex filter, auto create groups boolean
2. Populate groups and roles mapping tables
3. Display error UI when a mapped coder group or role doesn't exist
4. Display disabled UI state for group and role sync fields when they are empty
5. Check for correct experiment, license and permissions
6. Tooltip when mousing over coder group or role pill in error state
7. Tooltip when mousing over group.role sync field in disabled state
8. Add storybook stories for data driven UI states
9. Handle 'export Policy' button download behavior

Figma - https://www.figma.com/design/Y5vaPBgsXK8Lrmx5SljvUp/Group%2FRole-Sync?node-id=1-2&t=eEe85rYA397Z8KIr-4

Design

![Role Sync](https://github.com/user-attachments/assets/f931c70c-a2ac-4934-8768-343a4c69b051)

**Comment by Kira-Pilot** [comment]
Est: M

**Comment by BrunoQuaresma** [comment]
I think the design is ok but I would align the Coder Groups and Coder Roles columns to the left. It is a bit strange to me to have them aligned to the center, I usually don't see table content, inside of app interfaces, aligned to the center.

**Comment by BrunoQuaresma** [comment]
I think right works well! 👍
