### ISSUE TITLE
UI: Create skeleton page for IDP sync

### ISSUE THREAD

**Issue by jaaydenh** [coder/coder#14423]
Setup the basic structure and location in the UI. Can be completed before backend work is finished.

Requirements

1. Link to docs page
2. Table for group sync mappings
3. Table for role sync mappings
4. Export policy button
5. Fields for group, role, and group regex filter
6. Switch field for auto create groups
7. ? icon with help tooltip
8. Status indicator for group/role sync fields
9. Storybook stories

**Note**: let's use a lowercase `d` so we conform to the standard casing

Figma - https://www.figma.com/design/Y5vaPBgsXK8Lrmx5SljvUp/Group%2FRole-Sync?node-id=62-353&t=eEe85rYA397Z8KIr-4

Design

![Role Sync No Mappings](https://github.com/user-attachments/assets/a74bfc52-5e7c-4dee-aec9-36c852c6eba5)

**Comment by Kira-Pilot** [comment]
@jaaydenh nice! Can we add a link to the OG Figma?

**Comment by Kira-Pilot** [comment]
Est: M
