### ISSUE TITLE
Ensure we are utilizing the multi-org hook everywhere

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#14445]
Any place we directly check the experiment or entitlements related to the multi-org work we should instead use the custom hook for this feature. Specifically, this is the useDashboard hook's `dashboard.showOrganizations` prop.

Reminder to check the templates table and ensure that the Organizations column is hidden if there is only 1 org or if user is missing permissions to see any organizations at the member level.

**Comment by Kira-Pilot** [comment]
Tackle during bug bash week
