### ISSUE TITLE
ui(provisioners): show tags for PSK provisioners

### ISSUE THREAD

**Issue by aslilac** [coder/coder#14441]
Built-in provisioners cannot have tags (other than `scope:organization`) and keyed provisioners are assigned their tags by the key. PSK provisioners are unique, in that they will be grouped by the UI, but each provisioner can have it's own independent tags. We should account for this in the UI.

**Requirements**

- [ ] tooltip if provisioner has multiple tags
- [ ] multiple tags should wrap inside tooltip
- [ ] inline tag if provisioner only has one tag
- [ ] only show multiple tags label if provisioners have distinct tags from one another (otherwise hide)
- [ ] update storybooks

**Comment by aslilac** [comment]
<img width="1280" alt="Provisioners View – Built-in + PSK" src="https://github.com/user-attachments/assets/4fb3232e-7811-47fa-a00b-53538e695294">

https://www.figma.com/design/sruiQdZ5R73EBiaxqrVGxX/Provisioners?node-id=3010-286&t=0qcIIgUtLV1YesAR-1

**Comment by Kira-Pilot** [comment]
Est: S
