### ISSUE TITLE
ui(provisioners): group provisioners by authentication method

### ISSUE THREAD

**Issue by aslilac** [coder/coder#14459]
Once we have a basic implementation of the provisioners page ready without grouping, we rework the UI to group them by authentication method (PSK, built-in, or key)

**Requirements**

- [ ] group provisioners by auth method and represent this grouping the UI according to the above mock
- [ ] don't show provisioner keys that don't have any provisioners (we will view these in the CLI only right now)
- [ ] don't worry about pagination right now
- [ ] ensure provisioner expansion has max-height with own scrolling area 
- [ ] ensure responsive design doesn't break page (but doesn't need to be perfected)
- [ ] update storybooks for new view

**Comment by aslilac** [comment]
<img width="1280" alt="Provisioners View – Grouping stage 1" src="https://github.com/user-attachments/assets/872e0032-8888-4126-9b38-d0c55ed61b82">

**Comment by Kira-Pilot** [comment]
Est: M
