### ISSUE TITLE
Broken support for documented dotfile setup script names

### ISSUE THREAD

**Issue by stevenharman** [coder/coder#14453]
The [Coder docs explicitly mention](https://coder.com/docs/dotfiles#setup-script-support) that any of the following list of files can be used for a custom dotfiles setup:

* `install.sh`
* `install`
* `bootstrap.sh`
* `bootstrap`
* `script/bootstrap`
* `setup.sh`
* `setup`
* `script/setup`

I initially tried `script/setup` as it aligned well with [my dotfiles](https://github.com/stevenharman/config). However, on booting a Workspace where my dotfiles use `script/setup`, the file is ignored and the default behavior or symlinking everything kicks in.

<img width="842" alt="snap-2024-08-27-10 53 15" src="https://github.com/user-attachments/assets/651a212b-e78f-49c0-928c-58543336edb5">

If I switch to `setup.sh` in the root of the dotfiles, Coder uses that script instead, as expected:

<img width="1224" alt="snap-2024-08-27-11 49 25" src="https://github.com/user-attachments/assets/702159ea-73d8-4cec-b572-893afa632282">

So either the documentation is wrong, or there's a bug. I'm hoping the later as GitHub CodeSpaces do allow the full list of files.

Version: [`v2.12.3+534d4ea`](https://github.com/coder/coder/commit/534d4ea752bf2e72a5c3b46710ee7e56c33411c3)

**Comment by ethanndickson** [comment]
Good catch, thanks for reporting!

**Comment by stevenharman** [comment]
Thanks for the fast turnaround, @ethanndickson. Any idea how long it takes this to propagate to production?

**Comment by ethanndickson** [comment]
This'll get included in the next mainline release on the 3rd of September! (First Tuesday of each month)
