### ISSUE TITLE
The coder in the container always listens to port 8080

### ISSUE THREAD

**Issue by SiriusXT** [coder/coder#14487]
The coder in the container always listens to port 8080, and the port on which the coder in the container runs cannot be changed through the path coder/.config/code-server/config.yaml.
Since the program I'm debugging in the container listens to 8080 by default, I need to make coder listen to a different port

**Comment by ethanndickson** [comment]
You can set the port `code-server` listens on as part of the `bind-addr` flag:
e.g.
code-server --bind-addr 127.0.0.1:3000
