### ISSUE TITLE
[Develop in a container on a Google Cloud VM]: "Could not download module "gce-container" (main.tf:57) source code from git" error when creating template 

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#1451]
## OS Information

- OS: Windows 10
- Browser (if applicable):
- Architecture:
- `coder --version`: 0.5.5, 0.5.6

## Steps to Reproduce

1. run coder login https://qa.cdr.dev
2. enter session token
3. run coder templates init
4. select 'Develop in a container on a Google Cloud VM'
5. run cd ./gcp-vm-container && coder templates create
6. paste JSON private key for Google Cloud Service Account (https://www.notion.so/coderhq/Coder-QA-93bb2e68b58d488895ebd8de6133d656)

## Expected

Template is created without errors

## Actual

The following error is displayed:

_template import provision for start: recv import provision: initialize terraform: exit status 1

Error: Failed to download module

Could not download module "gce-container" (main.tf:57) source code from
"git::https://github.com/terraform-google-modules/terraform-google-container-vm?ref=v3.0.0":
error downloading
'https://github.com/terraform-google-modules/terraform-google-container-vm?ref=v3.0.0':
git must be available and on the PATH._

## Screenshot

![2022-05-14_10h57_59](https://user-images.githubusercontent.com/35501151/168419972-9a1ef041-0d38-4edf-8206-db545ba4b2ec.png)

## Notes

also reproduced with https://dev.coder.com 
--dev works fine for both 0.5.5 and 0.5.6, template was created without issues

**Comment by tjcran** [comment]
Closing this issue as "won't fix", but we should also consider a separate issue for making the error on this more clear, perhaps.
