### ISSUE TITLE
flake: `UsersPage.test.tsx`

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#14535]
https://github.com/coder/coder/actions/runs/10680634527/job/29602816185

```
FAIL src/pages/UsersPage/UsersPage.test.tsx (19.402 s)
  ● UsersPage › suspend user › when it is success › shows a success message

...
      24 | 	const user = userEvent.setup();
      25 | 	// Get the first user in the table
    > 26 | 	const moreButtons = await screen.findAllByLabelText("More options");
         | 	                                 ^
      27 | 	const firstMoreButton = moreButtons[0];
      28 | 	await user.click(firstMoreButton);
      29 |

      at waitForWrapper (node_modules/.pnpm/@testing-library+dom@9.3.3/node_modules/@testing-library/dom/dist/wait-for.js:162:27)
      at node_modules/.pnpm/@testing-library+dom@9.3.3/node_modules/@testing-library/dom/dist/query-helpers.js:86:31
      at findAllByLabelText (src/pages/UsersPage/UsersPage.test.tsx:26:35)
      at Object.suspendUser (src/pages/UsersPage/UsersPage.test.tsx:141:11)
```

**Comment by BrunoQuaresma** [comment]
Another failing job just for the record https://github.com/coder/coder/actions/runs/10706938607/job/29685833175?pr=14564

**Comment by DanielleMaywood** [comment]
Just had 3 in a row:
- https://github.com/coder/coder/actions/runs/10718732428/job/29721267822?pr=14570
- https://github.com/coder/coder/actions/runs/10718732428/job/29721779231?pr=14570
- https://github.com/coder/coder/actions/runs/10718732428/job/29722153547?pr=14570

**Comment by Parkreiner** [comment]
I'm so sorry, Bruno, but it's back
https://github.com/coder/coder/actions/runs/10786037607/job/29912253809?pr=14629#logs

**Comment by BrunoQuaresma** [comment]
@Parkreiner is it updated with main? Because I literally removed the test file  https://github.com/coder/coder/pull/14579/files#diff-1dbaa705844a001ee47037bae756983ca35300457ea2d362c535c81acc0aee54

**Comment by BrunoQuaresma** [comment]
Looks like it's not. I checked, and UsersPage.test.tsx does not exist on main anymore. Please close the issue again if the test passes after you update the branch with the current main. 🙏
