### ISSUE TITLE
UI: Set min and max attributes for workspace number parameters

### ISSUE THREAD

**Issue by toshikish** [coder/coder#14532]
Currently, the min and max attributes for workspace number parameter input elements are missing.

- If a user enters a number that is outside the allowed range, an error message appears below the input field.
- If a user enters numbers that don't follow the expected increasing or decreasing pattern, an error message shows up in an alert box after clicking the submit button.

![image](https://github.com/user-attachments/assets/e94d75c6-6293-41d5-a105-d04ff443cb90)

The min and max attribute values should be the following:

|Parameter type|`min` attribute|`max` attribute|
|---|---|---|
|`number` (general)|`min`|`max`|
|`number` (monotonic=`increasing`)|Previous value|`max`|
|`number` (monotonic=`decreasing`)|`min`|Previous value|

**Comment by stirby** [comment]
Thank you for raising this, I'm adding it into our next sprint.
