### ISSUE TITLE
Metadata dup key yields in internal error

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#14569]
# Description

By accident I want to push a template update to Coder, but this ends in an internal error.

![image](https://github.com/user-attachments/assets/bf7be294-eddf-4b46-9448-31552369b001)

After next try I saw another error which was the hint to solve this problem:

![image](https://github.com/user-attachments/assets/6739c334-48b2-4bf7-95d1-ebdcff2929e1)

# Expected

Terraform plant should recognize a non uquie **key** for a metadata object

**Comment by ethanndickson** [comment]
These are unfortunately two different issues. 

The second screenshot shows the response from `coderd` when a new template version is made with the same name as an existing template version for the same template. This message is justifiably confusing, so I'll improve it in #14572.

The same PR will also improve the error message in the first screenshot, when there are duplicate metadata keys, by including the error trace. Ideally this error would get picked up during a `terraform plan` on a template, in which case Terraform would give us a nice human readable error - I'll try and make a change to the `coder` provider to do this.
