### ISSUE TITLE
coder_app share settings "public" doesn't work as expected

### ISSUE THREAD

**Issue by pnowy** [coder/coder#14563]
Hi,

we wanted to use coder_app terraform object to share button and link available to all users.

```
resource "coder_app" "web" {
  agent_id     = coder_agent.main.id
  slug         = "7443s"
  display_name = "my-webapp"
  icon         = "https://example.com/logo.png"
  url          = "http://localhost:7443"
  subdomain    = true
  share        = "public"

  healthcheck {
    url       = "http://localhost:7443"
    interval  = 10
    threshold = 30
  }
}
```

The problem is that `public` does not work as a public. When we try to open URL from incognito we receiving:

`You are signed out or your session has expired. Please sign in again to continue.`

But - what interesting when we share port on UI (the same port, HTTPS) - and with setting public then everything works fine. We would expect the same behavior on the terraform template.

We are using code helm chart 2.14.2 (with appVersion 2.14.2).

PS. One question related to that coder_app - is there a way to specify there HTTPS port (similar like additional "s" for port number - I didn't find a way except naming the slug the same as port).

Thx

**Comment by pnowy** [comment]
And regarding the terraform coder module version is the latest one `version = "1.0.1"`.

**Comment by MrPeacockNLB** [comment]
ran today into the same issue

**Comment by YouXam** [comment]
Refer to [this link](https://coder.com/docs/faqs#i-want-to-allow-code-server-to-be-accessible-by-other-users-in-my-deployment) or use the `--dangerous-allow-path-app-sharing` flag.

Warning, this may pose security risks (such as cookie theft), so it's recommended to prioritize using subdomains.

> `--dangerous-allow-path-app-sharing` `bool`, `$CODER_DANGEROUS_ALLOW_PATH_APP_SHARING`
Allow workspace apps that are not served from subdomains to be shared. Path-based app sharing is DISABLED by default for security purposes. Path-based apps can make requests to the Coder API and pose a security risk when the workspace serves malicious JavaScript.  Path-based apps can be disabled entirely with `--disable-path-apps` for further security.
