### ISSUE TITLE
Add warning to documentation for Fly.io

### ISSUE THREAD

**Issue by shymega** [coder/coder#14599]
I am under the impression that Fly.io is no longer supported by Coder because
of the unmaintained Terraform provider.

This issue is to track the progress of adding a deprecation warning to the
documentation located
[here](https://coder.com/blog/remote-developer-environments-on-fly-io_)

Please do correct me if I am incorrect in my conclusion.

**Comment by phorcys420** [comment]
Yes, the Terraform provider for Fly.io [was dropped by Fly and is now unmaintained](https://community.fly.io/t/fresh-produce-volumes-endpoints-in-machines-api/14408/20).

This is pretty sad news, but unfortunately this is out of our control.
Thanks for the heads-up, we should update our blog post to show that it is now deprecated.

cc: @matifali

**Comment by matifali** [comment]
Thank you @shymega for reporting this. We do plan to update the blog to use the Fly kubernetes service (FKS) with our existing kubernetes terraform provider. It's being demonstrated in https://github.com/coder/coder/issues/9690#issuecomment-2075286754

Meanwhile I will add a deprecation warning to blog post.

**Comment by matifali** [comment]
Updated the blog post with a warning on deprecation of Fly.io terraform provider.
https://github.com/fly-apps/terraform-provider-fly

**Comment by shymega** [comment]
Thanks for this :-)
