### ISSUE TITLE
Group sync API + CLI CRUD

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#14626]
Implement api interface for group sync settings crud. Group sync settings are now configured in the database and mutable at runtime.

Requires api endpoint to set and read the group sync runtime settings.

The code to interact with the settings from an api handler:

```golang
	settings := api.IDPSync.GroupSyncSettings()
	rlv := api.Options.RuntimeConfig.OrganizationResolver(db, org.ID)
	err := settings.SetRuntimeValue(ctx, rlv, &idpsync.GroupSyncSettings{
		// Values
	})
```

The problem we currently have is the RBAC story is not fully fleshed out. The current authz call is `ResourceSystem`: https://github.com/coder/coder/blob/1995c13217f4ccf4fd63ee5b0605588e16d49984/coderd/database/dbauthz/dbauthz.go#L3939-L3944

**Comment by aslilac** [comment]
Requires https://github.com/coder/coder/pull/14578
