### ISSUE TITLE
UI: Updates for Premium Licenses

### ISSUE THREAD

**Issue by jaaydenh** [coder/coder#14636]

**Comment by mattvollmer** [comment]
Updates:
- [ ] Apply the four new bullet points to: Appearance, Organizations
- [ ] Groups banner references "Enterprise" in the second sentence
- [ ] Template permissions banner references "Enterprise" in the second sentence
- [ ] For Organizations, please use the content [from here](https://github.com/coder/coder/issues/14318#issuecomment-2329513846)
- [ ] ON the Template General Setting page, please fix the typo in the `Operations` section that reads "Premium license required to **enabled**"

Questions:
- Does this effort include conditional logic to show different messaging to existing Enterprise license holders? I see the Custom Roles banner displays [the text](https://github.com/coder/coder/issues/14318#issuecomment-2329513846) that only existing Enterprise customers should see.
- I'm unclear when the "backend" messages display. When do end users see these messages?

**Comment by mattvollmer** [comment]
This was a feature that @bpmct requested. I'll defer to him on priority. FWIW, my opinion is that it's not a must-have for October 1 unless we have the free bandwidth.

Until then, please use:

For the New Organization Premium banner:
> Create multiple organizations within a single Coder deployment, allowing several platform teams to operate with isolated users, templates, and distinct underlying infrastructure.

For Custom Roles:
>Create custom roles to grant users a tailored set of granular permissions.
