### ISSUE TITLE
UI: update licensing pills to reflect new premium tier

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#14657]
## Summary
We are introducing a new licensing tier - "Premium" - and should update our licensing badges in the UI so that they appropriately communicate a feature's licensing level to the user.

## Background
We indicate licensing for specific features with pills, e.g. in the screenshot below, appearance configuration is an enterprise feature which is currently accessible to the user:
![Screenshot 2024-09-12 at 4 12 50 PM](https://github.com/user-attachments/assets/e7063792-24a0-49f3-a3a8-c982d66c02a7)

Alongside the `enterprise` pill we see an `entitled` pill which indicates whether or not a user has a valid license to use that feature as some (but not all) features may be administratively enabled or disabled at the deployment level. If a feature is both entitled and enabled, then it is used on the deployment.

After we GA orgs, we don't want to expose Enterprise as an available plan to OSS users as Premium will be our only paid tier going forward; however, we do need to retain an `enterprise` badge for existing Enterprise customers so that they may differentiate between features they have access to and features they don't (Premium features).

## Requirements

- [ ] First, let's remove all `entitled` badges from our UI. While the concept of entitlement are still valid within our product, we will find another way at another time to convey that meaning to users
- [ ] Create a badge component that accepts licensing info and toggle the label in that badge based on the below table:
```
                | enterprise feature | premium feature
premium license | 'premium'          |  'premium'
enterpr license | 'enterprise'       |  'premium'
no      license | 'premium'          |  'premium'
```

- [ ] Ensure the Premium badge state displays the appropriate licensing info tooltip (and documentation link!) on hover, e.g.
![Screenshot 2024-09-12 at 4 22 37 PM](https://github.com/user-attachments/assets/463ca422-54f5-4d4f-88d4-31d6568938de)
- [ ] Ensure there is *no* tooltip or documentation link on `Enterprise` badges as this concept will no longer exist in our documentation

**Comment by Kira-Pilot** [comment]
@mattvollmer any thoughts about how we want to handle documentation in the above ticket if showing an `enterprise` label? Will there still be enterprise docs? Should we still have a tooltip with a documentation link?

**Comment by Kira-Pilot** [comment]
@mattvollmer should we still link the `Enterprise` badge to `https://coder.com/docs/enterprise`?

Also maybe we should update the badge in either the docs or the UI so that they match? The badge in your screenshot looks different than the one we have on dev but maybe that's just a mockup.

**Comment by mattvollmer** [comment]
I don't think we should link the Enterprise tags because that page will no longer exist (it will be replaced with Premium). 

I'm not surprised that the designs differ and I agree, they should be consistent.

**Comment by Kira-Pilot** [comment]
Updated requirements to reflect that there will be no tooltip or doc link for `Enterprise` badges. Note that docs should match the styling of the UI badges when they are eventually created.

**Comment by jaaydenh** [comment]
@mattvollmer Can we confirm what the copy should be for the premium banners for Appearance and Observability?

<img width="819" alt="Screenshot 2024-09-13 at 2 00 21 PM" src="https://github.com/user-attachments/assets/d10f613c-2521-4b02-a504-c950315cae16">
<img width="822" alt="Screenshot 2024-09-13 at 2 00 14 PM" src="https://github.com/user-attachments/assets/6f44bd8c-7c48-4293-b76e-bff15fe35d8f">

**Comment by mattvollmer** [comment]
Observability is fine. For Appearance:

> With a Premium license, you can customize the appearance and branding of your deployment.

**Comment by Kira-Pilot** [comment]
@jaaydenh was this ticket resolved by https://github.com/coder/coder/pull/14670? Can we close it out?
