### ISSUE TITLE
Explore non-claims based group/org/role sync alternatives (Google, GitHub)

### ISSUE THREAD

**Issue by deansheather** [coder/coder#14685]
SSO providers such as Google Workspace and GitHub do not provide a groups claim and requires a separate API request or something to get the users groups for features like [group sync](https://coder.com/docs/admin/auth#group-sync-enterprise).

Let's explore what it would take for us to hardcode group sync for specific providers and start with support for Google and GitHub since this is a milestone feature for governance. This will also allow us to use our dev environment for take homes, as we can sync people to organizations based on their GitHub org (e.g. [coder-contrib](https://github.com/coder-contrib) adds people to the take home org).

### Must have

- First-class support for group/role/organization sync based on groups in Google Workspace

### Should have

Added GitHub here so that we can support this in our take-home envs and also validate the abstraction if we must support other OIDC providers down the road.

- First-class support for group/role/organization sync based on organizations in GitHub

## Old description

Google Workspace doesn't support adding a groups claim to auth tokens, which means Google groups cannot be synced to Coder. However, there's a non-standard API you can use (with a corresponding scope) to retrieve groups information.

Coder could support Google sign-in better if it detected a Google OIDC config (with the correct scope necessary) and automatically made the request to fetch group information.

**Comment by matifali** [comment]
I was recently working on a Vault OIDC integarywoth Google and noticed that the groups oidc field was always empty.

**Comment by bpmct** [comment]
Moved GitHub to "should have" as it's not strictly a customer requirement but seems like it'd be beneficial to users down the road, and for our dogfooding cc @deansheather @sreya

**Comment by matifali** [comment]
For GitHub, it would be nice if we can also read team memberships to assign users to groups.

**Comment by bpmct** [comment]
> As in, Coder would detect a specific SSO (github, google, etc), and make a SSO specific API request to fetch some user attributes.

Yeah I think we'd have to do that for these outlier, non-claims style SSO.

> I think I will need to get a google workspace trial or license to verify this specific functionality. If my initial understanding is correct, the largest challenge I can see is how we configure this.

We are Google Workspace users and have it set up with dev.coder.com so we can dogfood. @kylecarbs may be able to help with admin-side things.

> The configuration sounds like it could be SSO specific. Meaning, the Github config options would look different than Google, etc. Just unsure how this transform would look.

👍🏼

**Comment by bpmct** [comment]
FYI we were originally targeting the November release, but it looks like it may be more complex so it may go into the September release.

**Comment by Emyrk** [comment]
@bpmct I setup a Google workspace to begin investigating this.

What I am seeing is that Google workspaces cannot function as an IdP.
Google workspaces organizes users into groups and organizational units. 
Organizational Units can have SSO configured via a [**third party identity provider**](https://support.google.com/a/topic/7579248?hl=en&ref_topic=7556686&sjid=10927403354788953718-NC).

I followed this guide to use Okta as my IDP:
- https://saml-doc.okta.com/SAML_Docs/How-to-Enable-SAML-2.0-in-Google-Apps.html?baseAdminUrl=https://dev-12222860-admin.okta.com&app=google&instanceId=0oakf131c2oMuQ50w5d7

If you do this, then you can no longer log in via Gmail, or the regular google platform. Okta becomes the IdP for google workspaces and now controls authentication.

![Image](https://github.com/user-attachments/assets/c7771f83-2add-44a2-8092-31f45e201b7d)

Unless I am mistaken, Google Workspaces is **not** an IdP and therefore cannot be used for SSO into Coder. A third party IdP must be used. What IdP are we currently running into issues with? I am assuming the IdP's need some way to "sync" the groups and organizational units. Okta provides a method for this.

**The call to action** is can get some information about the authentication stack that is running into issues? With as much specifics as possible. 


---

Other links:
- https://cloud.google.com/architecture/identity/single-sign-on

There is something about workspace apps that seem to be allowed to do Oauth: https://support.google.com/a/answer/2538798?hl=en. But Coder is not an app on the marketplace.

**Comment by bpmct** [comment]
What is this "Google" sign in option on dev.coder.com? I assume this is what the customer is using. Perhaps it is not Google Workspaces but it is configured via Google Cloud and uses Google Workspaces identity. I assumed this was what the customer was using and did not use IDP middleware such as Okta.

![Image](https://github.com/user-attachments/assets/582711f2-3429-4da3-8be1-efc46febbb69)

**Comment by Emyrk** [comment]
I would need to confirm, but I'm pretty sure it's Google Cloud for us. It's likely what the customer is using too, but I would like to confirm that.

If this is the case, Coder does not communicate with Google Workspaces. Nor is Coder aware Google Workspaces is the primary source for user configuration.

We need to gather more information, as the ticket today is a bit confusing. Dean is on sabbatical unfortunately, so I am having to retrace his steps. I'd like to confirm the exact tech stack we are trying to solve for.

## Based on the original description

In the original description:

> ...SSO providers such as Google Workspace

Google workspace is not an SSO. Google Sign-In

> Coder could support Google sign-in better if it detected a Google OIDC config (with the correct scope necessary) and automatically made the request to fetch group information.

Google sign-in is 1 example of an SSO, but it works for **all** google accounts. Not just those in the Google workspace. So detecting a Google OIDC config does not mean Google workspaces is being used.

Secondly, I do not believe a user access token is sufficient to access Google Workspaces API. See this [doc](https://developers.google.com/workspace/guides/create-credentials) for what credentials are required.

### Google Workspace Apps

Google workspace does have the concept of an "App" that uses Oauth to authenticate. However, it advises using the App store, which Coder is not on. I do not think this is the correct approach for us.

----

# How I _think_ it works

This is my current understanding, where the IdP can be Google Sign on or Cloud Identity (are these the same?). There might be a need to have Coder communicate with Google Workspaces, however, I'd like to investigate alternative options in the IdP's directly first.

```mermaid
sequenceDiagram
    Browser ->>Coder: Visits Coder

    loop On updates
        IdP --> Google Workspaces: Syncs information in background
    end
    destroy Google Workspaces 
    IdP --> Google Workspaces: Not used in auth flow
    

    Browser ->>Coder: Log in
    activate Coder
    Coder ->> Browser: Log into IdP, then come back
    deactivate Coder

    Browser ->> IdP: Log in
    activate IdP
    IdP ->> Browser: Authentication success
    deactivate IdP

    Browser ->> Coder: Redirect with IdP state

    activate Coder
    Coder ->> IdP: Confirm state & User
    Coder ->> IdP: Fetch user information
    Coder ->> Browser: Authenticated as alice@coder.com
    deactivate Coder
```


----

# Extra tidbit

I found it surprising how much Google Workspaces mentions Microsoft Entra. On the security page for "SSO with third party IdP", this is shown. By default Microsoft accounts just work for google workspaces?

![Image](https://github.com/user-attachments/assets/71496b71-0225-4898-96be-efabe7fad5df)

And their [SSO docs](https://support.google.com/a/answer/12032922?hl=en) just assume Microsoft Entra is used for OIDC?

**Comment by Kira-Pilot** [comment]
@bpmct @stirby shall we set up a call with the users?

**Comment by Emyrk** [comment]
Ok, so I was _kinda wrong_. Google Workspaces does have external IDP configuration. **However**, nested in docs that are hard to find is this: https://developers.google.com/identity/protocols/oauth2

Basically, you can configure an oauth app to your Google APIs. And these oauth apps can act as an OIDC auth flow for your google workspace. This is done through the GCP dashboard, which confused me. So you have to setup a GCP console project for your Google workspace project.

Here are the scopes listed:

![Image](https://github.com/user-attachments/assets/d9feb1cd-89dd-4fd7-b7dc-8483cab7889c)

My current steps are looking through the available scopes: 
https://developers.google.com/identity/protocols/oauth2/scopes

I am unsure what custom claims options we have.

**Comment by Emyrk** [comment]
Just some more notes:

Google workspaces API can use `https://admin.googleapis.com/admin/directory/v1/groups?userKey=<user_email>` to fetch the user's groups.

https://developers.google.com/workspace/explore?authuser=2&filter=&discoveryRef=resources.groups.methods.list&discoveryUrl=https%3A%2F%2Fadmin.googleapis.com%2F%24discovery%2Frest%3Fversion%3Ddirectory_v1&operationId=directory.groups.list

As far as I can tell, we cannot return custom claims with the Google OAuth apps.

----

Google Identity Platform is their firebase auth app that does support Cloud Run functions to add claims. But these apps require the Firebase auth integration, not Oauth?

**Comment by Kira-Pilot** [comment]
To implement this ticket, we would have to make use of Google's admin API token, a concept contrastive to most IdPs. For now, we are closing this issue.
