### ISSUE TITLE
feature(site): update documentation links with new Org content

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#14707]
Product is creating some guides for Orgs & Custom roles and for our new Premium license tier. We should do a pass in the UI and ensure that all of our content links are updated appropriately.

**Requirements**
- [ ]  premium doc links in the tooltip on the Premium badge and banner
- [ ] IDP sync page
- [ ] provisioner docs on help icon on provisioners page:
<img width="614" alt="Screenshot 2024-09-18 at 11 29 29 AM" src="https://github.com/user-attachments/assets/3e09e6d3-177c-4c12-9b4d-3115a630858b">

**Comment by Kira-Pilot** [comment]
Closing in favor of https://github.com/coder/coder/pull/14778

**Comment by bpmct** [comment]
@Kira-Pilot we'll need to update the in-product links so I think this is still worth tracking. unless you want my PR to address the in-product links too. probably best TBH

**Comment by bpmct** [comment]
yeah, I added that as a TODO in https://github.com/coder/coder/pull/14778
