### ISSUE TITLE
Centralised location to manage all of my code-servers

### ISSUE THREAD

**Issue by alonahmias** [coder/coder#14711]
I want a place where i can startup a code server and manage all of the instances that are running, like jupyterhub
I have a web app that allow users to create files edit code, but i want to be able to "control" what they are doing 
Isaw a repo that do exactly that but it looks not maintained at all
https://github.com/HuJK/Code-Server-Hub

**Comment by kylecarbs** [comment]
You've stumbled on a repo that solves your problem.

Try deploying Coder. It's just two commands, check out the README.
