### ISSUE TITLE
`coder ping` UX concerns

### ISSUE THREAD

**Issue by ammario** [coder/coder#14752]
1. The standard `ping` command runs forever. `coder ping` goes for 10 round trips by default, which seems arbitrary and often frustrates me. `ping` running forever is a feature not a bug. It means I can leave it up on a terminal to monitor my network conditions for a long time. When I ctrl+c on `coder ping` I want a statistical summary just like `ping`.
2. Related, the new diagnostics info introduced https://github.com/coder/coder/pull/14426 should go at the beginning of the ping log and not the end. When placed at the end of the log, the feature becomes more and more useless as `-n` approaches infinity.

cc @ethanndickson

**Comment by ethanndickson** [comment]
These both sound reasonable, although this would of course mean any diagnostics we determine would always get shown. We currently don't show them if a direct connection was established, as to avoid overloading the user with warnings when their connection is already preferable.

**Comment by deansheather** [comment]
Since we need to do pings to determine whether we got p2p or not we definitely need to put the diagnostics last. We can make them get written after you hit ctrl+c or after the `-n` count is reached.

**Comment by ammario** [comment]
Can we do one silent ping to show diagnostics and then print the rest?
