### ISSUE TITLE
Proposal: consolidate parameter memory

### ISSUE THREAD

**Issue by ammario** [coder/coder#14757]
When discussing user-level parameters with @stirby I came to an idea about how we can simplify the parameter system. Right now we have an `ephemeral bool` flag on `coder_parameter` and our plan of action for introducing autofill was to create an `autofill bool` flag. I realize these features have conceptual overlap and would be better represented a single flag on parameters:

```
memory = "build" | "workspace" | "template" | "org" | "user"
```

This option would default to `workspace`. `memory = user` solves for user-level parameters. `memory = build` is equivalent to today's `ephemeral = true`.

We would need to hide, deprecate, and remove the `ephemeral` opt—which is a happy thing for me.

Related:
* https://github.com/coder/coder/issues/14458
* #11731 

cc @code-asher

**Comment by stirby** [comment]
We're doing this as part of "Magic Parameters."

**Comment by bpmct** [comment]
We're working on a new design
