### ISSUE TITLE
Some users reporting 0ms latency on template insights

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#14805]
May be related to recent usage query changes, or may have been there before those changes, not 100% sure. Most likely the issue is we are selecting a latest stat somewhere with a 0ms instead of correctly selecting max from the period. Most likely related to a specific type of session since it only seems to affect some users. 

![Screenshot 2024-09-25 at 2 22 24 PM](https://github.com/user-attachments/assets/839cebfe-a6c6-4ee1-b588-393040249dcc)

**Comment by ethanndickson** [comment]
Some stats are now reporting `-1`:
![Image](https://github.com/user-attachments/assets/6d737a1f-52c0-4680-990f-65cf8eb29dbf)
