### ISSUE TITLE
Make web ui link more prominent in the terminal

### ISSUE THREAD

**Issue by chrifro** [coder/coder#14818]
Problem:
It's difficult to discover the link for the web UI in the logs
<img width="561" alt="Screenshot 2024-09-09 at 08 29 52" src="https://github.com/user-attachments/assets/33844e8f-5399-4d33-8c16-4322e6069bd8">

Possible solution:
<img width="347" alt="Screenshot 2024-09-26 at 13 48 16" src="https://github.com/user-attachments/assets/447144c2-e39e-451d-acd7-c6fcae6fba14">

**Comment by ethanndickson** [comment]
We ended up improving this in https://github.com/coder/coder/pull/14761 :) Happy to hear any thoughts on the new design!

**Comment by chrifro** [comment]
Closing the issue as it has already been addressed in #14761 ✨
