### ISSUE TITLE
Hovering over avatar in breadcrumb shows URL?

### ISSUE THREAD

**Issue by ammario** [coder/coder#14810]
![image](https://github.com/user-attachments/assets/2a3239cf-5038-495d-8f8c-763e876b399c)

This seems like a bug? I can't imagine a good reason to show this.

cc @Parkreiner. I think this may be related to one of your changes but could be wrong.

**Comment by Parkreiner** [comment]
@ammario Yeah, there's zero reasons for things to be like this. It was a single-prop typo that wasn't caught during testing because the logic only triggered for avatar values not hosted directly on Coder.com

Made a quick hotfix
