### ISSUE TITLE
Remove Dark Blue theme

### ISSUE THREAD

**Issue by ammario** [coder/coder#14811]
At this point, it's quite ugly due to clashing colors and I don't think it's worth the engineering effort to maintain it. I think we've kept it for compatibility with our original design. Maybe there are some users that like it due to familiarity, but I can't imagine right-minded new users preferring it over the Dark Theme.

![image](https://github.com/user-attachments/assets/2a2bc231-f4f1-411d-8bdd-b74af8f3b506)

**Comment by ammario** [comment]
cc @chrifro in case you have thoughts here.

**Comment by Parkreiner** [comment]
Yeah, definitely on board with this. We had this labeled as a beta theme for the longest time, but then decided to remove the label for some reason

I don't know if we have any screenshots of the old blue theme before we decided to add the current dark/light themes, but the current blue theme fell off somewhere along the way. A lot of the colors are wrong (a lot of the colors from the black theme are accidentally being brought in), and it's to the point, and highlight/banding colors are missing, so the theme has worse information hierarchy

Worse yet, we don't have a single Storybook test that covers the blue theme, so if we have any regressions, we won't have a way to surface them with CI. The theme almost shipped with bright-red debug colors and only got caught right before a release

**Comment by chrifro** [comment]
Sounds good to me 👌

That simplifies the color alignment, I'm working on a lot ( #14780). So thanks for bringing it up now ✨

**Comment by coadler** [comment]
Closed by https://github.com/coder/coder/pull/14890

**Comment by ammario** [comment]
🎉
