### ISSUE TITLE
Unable to start any workspaces due to http 500 errors from registry.coder.com

### ISSUE THREAD

**Issue by yonirab** [coder/coder#14815]
Version: [`v2.13.4+bddf0bf`](https://github.com/coder/coder/commit/bddf0bf85a9d95725f5c95da308fff40592f5a02)

Workspaces fail to start with the following errors:

```

Error: Error accessing remote module registry
  on modules/cr_k8s_rstudio_jupyter/external.tf line 2:
   2: module "jetbrains_gateway" {
Failed to retrieve available versions for module "jetbrains_gateway"
(modules/cr_k8s_rstudio_jupyter/external.tf:2) from registry.coder.com: the
request failed after 2 attempts, please try again later: 500 Internal Server
Error returned from
https://registry.coder.com/api/modules/v1/modules/jetbrains-gateway/coder/versions.
Error: Error accessing remote module registry
  on modules/cr_k8s_rstudio_jupyter/external.tf line 13:
  13: module "slackme" {
Failed to retrieve available versions for module "slackme"
(modules/cr_k8s_rstudio_jupyter/external.tf:13) from registry.coder.com: the
request failed after 2 attempts, please try again later: 500 Internal Server
Error returned from
https://registry.coder.com/api/modules/v1/modules/slackme/coder/versions.
Error: Error accessing remote module registry
  on modules/cr_k8s_rstudio_jupyter/external.tf line 23:
  23: module "personalize" {
Failed to retrieve available versions for module "personalize"
(modules/cr_k8s_rstudio_jupyter/external.tf:23) from registry.coder.com: the
request failed after 2 attempts, please try again later: 500 Internal Server
Error returned from
https://registry.coder.com/api/modules/v1/modules/personalize/coder/versions.
Cleaning Up
```

**Comment by matifali** [comment]
Looking into it.

**Comment by yonirab** [comment]
Thanks @matifali . 
Please note that this is an emergency issue for us (completely stops work across our entire company).
Please prioritize accordingly.
Thanks!

**Comment by matifali** [comment]
Thank you for reporting and your patience @yonirab. The issue has been resolved, and regsitry.coder.com should be running again.

**Comment by yonirab** [comment]
Thanks for the fast turnaround @matifali !
What was the root cause of the outage, and how can such incidents be avoided in the future?

**Comment by spikecurtis** [comment]
@yonirab we will schedule an internal post mortem analysis and update this issue when it is complete.

**Comment by Kira-Pilot** [comment]
Hi @yonirab, wanted to follow-up: after completing our post-mortem, we identified that this outage was related to how the Registry handled dynamic content, which introduced reliability issues. Since then, we've rearchitected the service to generate static assets at build time, eliminating this problem.

This change has significantly improved stability, and we don't expect this issue to occur again. I'll be closing this ticket but please let us know if you experience any further problems! You can also check our status page [here](https://coder.instatus.com/).

**Comment by yonirab** [comment]
Thank you very much for the update @Kira-Pilot! 
Great to see that their is now a status page for this!
