### ISSUE TITLE
Remember a user when logging in

### ISSUE THREAD

**Issue by chrifro** [coder/coder#14823]
**Issue:**
It's tedious to always fill out the login form when starting Coder. 
Note: this might be a bug 
![image](https://github.com/user-attachments/assets/4ee92d6b-b0f4-489a-bba2-42b7da4ec0c4)

**Comment by stirby** [comment]
The browser session length is determined by the generated token's TTL. This is configurable by administrators. 

We don't indefinitely persist the user session for the sake of security.
