### ISSUE TITLE
Coder does not handle paths correctly when placed in a subpath

### ISSUE THREAD

**Issue by techrevo** [coder/coder#14832]
# Setup and environment variables

- Docker 27.3.1
- Caddy 2.8.4
- Coder 2.15.0

- `CODER_ACCESS_URL`: `https://example.com/coder/`
- `CODER_WILDCARD_ACCESS_URL`: `*.dev.example.com`

# Issue

Setting `CODER_ACCESS_URL` to a subpath of my main domain and setting caddy to handle correctly it, Coder continues fetching assets and APIs via base URL (`https://example.com/*`) instead of subpath (`https://example.com/coder/*`) . For example: if I type in the browser `example.com/coder/` it loads only base html file and not css and javascript ones, searching them in `example.com/assets/` and not in `example.com/coder/assets/` while trying to connect to API at `example.com/api/` and not `example.com/coder/api/`.

My Caddyfile:
```
example.com {

        # Coder
        redir /coder /coder/
        handle /coder/* {
                reverse_proxy :3000  
        }
}
```

**Comment by mafredri** [comment]
Hey @techrevo, subpaths are not supported and we currently don't have plans for supporting it. Have you considered using a subdomain instead?

**Comment by techrevo** [comment]
Thanks for the answer, @mafredri. Using a subpath would have been more convenient for me but a subdomain will work just as well. 

For anyone who was trying to achieve the same, I think the only solution is to modify the HTTP responses via modules like `ngx_http_sub_module` for nginx. I haven't tested it but with the right regex it should work.

**Comment by mafredri** [comment]
You're welcome @techrevo, happy to hear the solution works for you. I can understand that you'd prefer a sub path, unfortunately there is complexity as well as security consideration involved with using path based routing. For instance, we do support path based workspace apps, but see `DANGEROUS OPTIONS` under `coder server --help` for why we don't recommend it.

**Comment by SuperCoolAlan** [comment]
> Thanks for the answer, [@mafredri](https://github.com/mafredri). Using a subpath would have been more convenient for me but a subdomain will work just as well.
> 
> For anyone who was trying to achieve the same, I think the only solution is to modify the HTTP responses via modules like `ngx_http_sub_module` for nginx. I haven't tested it but with the right regex it should work.

I gave this a shot! While `ngx_http_sub_module` is effective for responses coming from the Coder instance, scripts that run on the client-side inherit the URL for API requests via `document.location.href` which do not resolve to the configured subpath. With this finding, I am going to employ a subdomain instead.

Thanks!
