### ISSUE TITLE
[bug] fix tooltip content

### ISSUE THREAD

**Issue by chrifro** [coder/coder#14848]
when hovering over my username, I get this cryptic tooltip. 
![image](https://github.com/user-attachments/assets/3c7aab8c-0904-4c69-93f5-bd07fcbfa216)

**Comment by matifali** [comment]
@Parkreiner this could be related to the recent changes with User Avatars.

**Comment by Parkreiner** [comment]
Somewhat related, but it should've been fixed via issue #14810 (which got addressed Wednesday night)

@chrifro Can you refresh your page and confirm whether you're still seeing this issue? I'm not sure if this is the same workspace, but I opened up your `testing` workspace, and this is what I see:
<img width="373" alt="Screenshot 2024-09-27 at 9 16 52 AM" src="https://github.com/user-attachments/assets/741236c4-a90a-4145-8189-d8a8b3c9935c">

**Comment by chrifro** [comment]
Nice. I can confirm that the issue has already been resolved.  Thanks @Parkreiner 🎉
