### ISSUE TITLE
Expose 30d trial form via CLI

### ISSUE THREAD

**Issue by bpmct** [coder/coder#14856]
The UI requires these fields

![image](https://github.com/user-attachments/assets/6cfd3190-e395-4830-bb43-b026e8f4ed58)

However the CLI setup does not

![image (1)](https://github.com/user-attachments/assets/144cec84-5315-40ac-9373-55473845a5a0)

Thanks @dannykopping for discovering this!

**Comment by joobisb** [comment]
Hi @bpmct ,

I've raised a PR for this, please do have a look

**Comment by matifali** [comment]
@bpmct, is the purpose here to make the form mandatory to request a trial via CLI? That means we need to drop support for `--first-user-trial` flag. That would be a breaking change.
