### ISSUE TITLE
Add OpenSSF ScoreCard to Coder

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#14879]
When working with OpenSource at enterprise companies; governance, compliance and security comes up, adding OpenSSF ScoreCard  - https://openssf.org/. Could be a good way to address that, especially when it comes to auditing

example open source repo that does this well and they also have a good docs describing how the processes work:

<img width="955" alt="Screenshot 2024-09-30 at 8 34 54 AM" src="https://github.com/user-attachments/assets/5a6127ae-7639-4ee3-860e-2ed84b6c3d51">

https://docs.powertools.aws.dev/lambda/python/latest/security/

**Comment by bpmct** [comment]
Thanks for suggesting, we'll definitely look into this cc @matifali @phorcys420

**Comment by michaelbrewer** [comment]
Awesome turn around. Useful to keep track of this and helps with our risk assessment.

**Comment by matifali** [comment]
We have improved our score to 8.5 now.
A continual improvement towards this goal is documented here: https://github.com/coder/internal/issues/89
