### ISSUE TITLE
Expose the agent timings in the /workspace/:workspaceId/timings endpoint

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#14876]
Right now, the timings endpoint returns only provisioner timings but we also want to include the agent timings to display them in the UI. 

Related to:
- https://github.com/coder/coder/issues/14630
- https://github.com/coder/internal/issues/44

**Comment by dannykopping** [comment]
@BrunoQuaresma will you add a separate issue for the agent registration timings, or will that be included in this one?

**Comment by BrunoQuaresma** [comment]
Are agent registration timings done? Could you please link the related issue?

**Comment by BrunoQuaresma** [comment]
@dannykopping Are agent registration timings done? Could you please link the related issue?

**Comment by dannykopping** [comment]
No, those also have to be implemented

**Comment by BrunoQuaresma** [comment]
So I think we can do it in a separated issue.
