### ISSUE TITLE
Fix workspace links to doc - parameters section

### ISSUE THREAD

**Issue by defelmnq** [coder/coder#14889]
After installing Coder locally, some of the links are redirecting to a non-existing version of the doc. (see screenshots for links)

The URL generated is : 
https://coder.com/docs/@v2.15.0+190cd1c/templates/parameters

while it seems it should be : 
https://coder.com/docs/@v2.15.0/templates/parameters

Coder version : 
```
Coder v2.15.0+190cd1c Tue Sep  3 16:31:04 UTC 2024
https://github.com/coder/coder/commit/190cd1c7130bdeabbe690e8c2b8b08210873366a
```

Installed today using :
`curl -L https://coder.com/install.sh | sh`

<img width="1406" alt="Screenshot 2024-10-01 at 09 19 35" src="https://github.com/user-attachments/assets/7891b4a3-edf1-4799-8bab-775f35ed135c">
<img width="400" alt="Screenshot 2024-10-01 at 09 18 28" src="https://github.com/user-attachments/assets/8f92fde3-a524-4173-b893-261807b5d77a">

**Comment by matifali** [comment]
I think this has been fixed in https://github.com/coder/coder/pull/14601, which hasn't been released yet. 
@stirby we should cherrypick this for the new stable.
