### ISSUE TITLE
Notifications: verify rendered action

### ISSUE THREAD

**Issue by mtojek** [coder/coder#14913]
The directory [rendered-templates](https://github.com/coder/coder/tree/e6d8f674ad48a601f25bb98420a14f1150914ead/coderd/notifications/testdata/rendered-templates) contains bodies and titles. We could extend it to also cover actions (in JSON format?).

**Comment by dannykopping** [comment]
What do you mean by "actions"? Do you mean payloads, perhaps?

**Comment by mtojek** [comment]
No, [Actions](https://github.com/coder/coder/blob/main/coderd/notifications/types/payload.go#L18).

BTW we should rename `TemplateActions` to `Actions` as they are not limited only to templates.

**Comment by dannykopping** [comment]
Why just the actions?

**Comment by mtojek** [comment]
What do you mean? Can you be more specific about what are you thinking of?

We have versioned titles and bodies as human-readable entities without `\"` escaping and nasty JSON-formatted payloads. Alternatively, I guess, we could convert them into `.json` files representing payloads, but the main goal of these tests is to check if coderd renders templates correctly, and some action links contain placeholders too.

**Comment by dannykopping** [comment]
The whole payload is used to produce the template, so I think if we're expanding test coverage we should do the full thing.
I like your idea of storing them as `.json` files. If we can ensure that a given set of inputs perfectly produces the same payloads, then that'll give us a lot of confidence in the tests.

We wouldn't even need to handle title/body specifically then, in this case.
