### ISSUE TITLE
CLI: replace double negative on blocked `coder update`

### ISSUE THREAD

**Issue by stirby** [coder/coder#14940]
When [`coder update`](https://coder.com/docs/reference/cli/update) fails on an up-to-date workspace, it returns an awkward error. 

```
$ coder update dev-main
Workspace isn't outdated!
```

Let's replace "Workspace isn't outdated!" with "Workspace is up-to-date."

Related: https://github.com/coder/coder/issues/11111

**Comment by defelmnq** [comment]
Resolved ✅
