### ISSUE TITLE
Links to Documentation in the Latest Version of Coder are Broken

### ISSUE THREAD

**Issue by techwithanirudh** [coder/coder#14945]
**Issue Description:**

In the latest version of Coder, many links to the documentation are broken. 
For example: Clicking the docs link in the profile popup directs to a broken page.

**Steps to Reproduce:**
1. Navigate to the profile popup.
2. Click on the documentation link.
3. The page opened results in a 404 error.

**Expected Behavior:**
Documentation links should point to the correct version of the Coder docs.

**Actual Behavior:**
Links lead to 404 error pages instead of the expected documentation.
(e.g. https://coder.com/docs/@v2.16.0+683a720)

**Affected Versions:**
- Coder v2.16.0+683a720 

**Screenshots/Videos:**
- [Link to the video showing the issue](https://share.cleanshot.com/5h1S1PjY)

**Comment by matifali** [comment]
Thank you for reporting the issue. This should have been fixed by https://github.com/coder/coder/pull/14601 which looks like we missed in https://github.com/coder/coder/pull/14919.

@stirby to look into it.

**Comment by ethanndickson** [comment]
This looks like a new bug that wasn't addressed by #14601, as that fix is included in v2.16.0: https://github.com/coder/coder/blob/v2.16.0/site/src/utils/docs.ts

**Comment by spikecurtis** [comment]
@techwithanirudh what is the URL you are getting redirected to?

**Comment by ethanndickson** [comment]
OP posted it on the Discord earlier, it's the same problem: `https://coder.com/docs/@v2.16.0+683a720`

**Comment by mattvollmer** [comment]
FWIW I encountered a similar issue here (on 2.15.0):


https://github.com/user-attachments/assets/2b39fa26-6d74-4c12-ab9e-03dd3d0a2202

**Comment by aslilac** [comment]
Closed by #14963
