### ISSUE TITLE
Insecure password blocking sign up flow is annoying

### ISSUE THREAD

**Issue by ammario** [coder/coder#14984]
So this is quite annoying:
* We don't give the user clear instructions how the password should come into compliance, instead forcing a trial-and-error flow
* Makes it hard to quickly set up a Coder deployment for testing
* The warning only updates on submit... it should update in real time. These entropy checks are not expensive?

Since this is a product directed towards a technical audience I would much prefer we make this entropy check a warning and _not_ block sign up. Deployments with hefty security requirements should use SSO and not built in auth anyways.

<img width="842" alt="Screenshot 2024-10-04 at 1 29 55 PM" src="https://github.com/user-attachments/assets/69c53a86-93e1-4243-995e-7168eb75b441">

**Comment by defelmnq** [comment]
@ammario I'm working on this one currently. Based on your comments and what I checked in the code - I plan to : 

- Remove the entropy validation in the backend (not explicit enough.)
- Add a condition both frontend and backend side to ensure the password is between 6 and 64 characters - does not matter the pattern.
- Validation will be done frontend side (so will be easier to iterate on for the users.) but I keep it also backend side just in case obviously.

We can add more rules if we want, but I feel like based on your description it will be enough.

**Comment by ammario** [comment]
If I understand it correctly you're removing all entropy checking? I think it's a nice feature on the frontend (when non-blocking) but don't feel strongly we should have it if inconvenient to implement.


> Validation will be done frontend side (so will be easier to iterate on for the users.) but I keep it also backend side just in case obviously.
The backend implementation is important for CLI flows. Some of our users build new frontends around Coder too.

An idea is keeping all validation in the backend and implementing a "check" endpoint to avoid issues of behavioral mismatch between FE and BE. The FE can send inputted passwords to the BE with a debounce before the user hits submit.

> Also, do we want to use this opportunity to change it overall in our password flows , or just for this specific one ?

And, I do believe we should have a consistent UX and code-paths for every place we accept new passwords.

**Comment by mtojek** [comment]
@defelmnq Is there anything left here or can we resolve this issue now?

**Comment by defelmnq** [comment]
All good now, resolved with the PR merged for a first iteration.
