### ISSUE TITLE
Docs: Broken administration link

### ISSUE THREAD

**Issue by hibare** [coder/coder#14987]
The administration link is broken on docs

![image](https://github.com/user-attachments/assets/4d35e143-66a3-43cb-893b-64442475d2ef)

**Comment by matifali** [comment]
Hi @hibare, we recently merged the docs restructure, and it takes a few minutes to invalidate the old cache. It should be fine for you now. https://coder.com/docs/admin
Please feel free to let me know if you still see the issue.
