### ISSUE TITLE
Improve default avatar style

### ISSUE THREAD

**Issue by chrifro** [coder/coder#14997]
**Problem:**
the current default avatar is very boring, has no character and can't be distinguished if they are several of them
![Image](https://github.com/user-attachments/assets/da07b6e1-29fe-4464-8c6b-57651dc0eb9b)

**Solution:**
Let's create something more interesting and that represents the initals of the name

See [Figma](https://www.figma.com/design/WfqIgsTFXN2BscBSSyXWF8/Coder-kit?node-id=711-383&t=9upOl1lQgOBtphAq-1)
![Image](https://github.com/user-attachments/assets/27a6979c-4aa9-4a8f-b177-c86dac575409)

**Comment by bpmct** [comment]
Design LGTM 👍🏼

**Comment by BrunoQuaresma** [comment]
@Christin I noticed we currently have three sizes for the avatar, and I’m wondering if we should add another size for pages like this one—the template page—where the avatar is quite large (48px).

<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/abc78d9b-1f17-41ee-a98b-d18d45aea244" />

**Comment by BrunoQuaresma** [comment]
@chrifro @jaaydenh I noticed we’re currently using numeric values as the "size ID" for components. Do we want to stick with this approach, or should we switch to using aliases like `xs`, `sm`, `md`, `lg`, etc.?

**Numeric Example:**
```tsx
<Avatar size={18} />
```

**Alias Example:**
```tsx
<Avatar size="sm" />
```

**Comment by jaaydenh** [comment]
I think aliases will be better so we can stick to a standard set of sizes.

**Comment by BrunoQuaresma** [comment]
Should this set of sizes be specific to the component or more broadly defined? For example, would the `sm` unit always be 18 for other components as well, or just for the avatar? In my opinion, it makes sense for the sizes to be component-specific, but I just want to make sure we’re aligned.

**Comment by jaaydenh** [comment]
I think component specific makes sense also for consistency we should probably keep the Tailwind naming conventions of  "xs","sm","md","lg","xl", etc

**Comment by BrunoQuaresma** [comment]
Just sharing my status on [Improve default avatar style](https://github.com/coder/coder/issues/14997). It’s been more work than I initially thought. I didn’t realize how many different places were using the Avatar component with custom styles applied. I’ve managed to get the new design in place, but a few components need extra work to look good with the changes.

Chromatic flagged [254 affected snapshots](https://www.chromatic.com/build?appId=624de63c6aacee003aa84340&number=18365), and I’m reviewing them one by one to ensure everything is in place and looks professional.
