### ISSUE TITLE
Improve template and organization emojis

### ISSUE THREAD

**Issue by chrifro** [coder/coder#14998]
**Problem**
- the current template and organization icons look very playful, rather unprofessional,
 and don't align with our minimalistic style
- it's not obvious that users can upload their custom images that are based on a URL
![Image](https://github.com/user-attachments/assets/9f06719d-a05a-48ed-a964-50dbb940b820)
![Image](https://github.com/user-attachments/assets/5b31b86e-47f8-4a59-8071-1adf582fd88a)
![Image](https://github.com/user-attachments/assets/b96bed41-168e-4b0e-9fb1-2393f7b2d2a6)

**Context**
- we got customer feedback that customers really like to use a pre-defined emoji library for their templates
- allowing to upload custom images without a URL is technically very tricky to implement. Where would we store the information?

**Suggested solution**
- swap default emoji/icon library with the apple emojis (https://github.com/missive/emoji-mart/tree/main/packages/emoji-mart-data/sets/15)
![Image](https://github.com/user-attachments/assets/597d73f4-2f30-4961-a762-1cc83e5eec75)
related issue #14997

**Comment by bpmct** [comment]
I'm in favor of moving to the apple set 👍
