### ISSUE TITLE
No NGINX documentation

### ISSUE THREAD

**Issue by ggtylerr** [coder/coder#15021]
The current version of the docs doesn't list anything for nginx - it mentions a page in the FAQ that supposedly has a config, but that leads to a 404: 

https://coder.com/docs/tutorials/faqs#how-do-i-configure-nginx-as-the-reverse-proxy-in-front-of-coder
https://coder.com/docs/admin/setup/web-server/nginx

Normally I'd just use a standard nginx configuration for this, but it seems like it needs more than that, since a websocket connection is complaining about needing an upgrade:
`WebSocket protocol violation: handshake request must be at least HTTP/1.1: "HTTP/1.0" unable to accept:failed to accept WebSocket connection: WebSocket protocol violation: handshake request must be at least HTTP/1.1: "HTTP/1.0"`

**Comment by kylecarbs** [comment]
cc @stirby

**Comment by ggtylerr** [comment]
Unrelated to this but coder seems to be causing problems with nginx as a whole - I just had a downtime of a few hours because for some reason it's making nginx take forever to load. I'm running under Docker too, so I know it isn't messing with anything system wise... I'll make a new issue for this though, once this is resolved :)

**Comment by matifali** [comment]
We have a fix in progress.
