### ISSUE TITLE
Workspace Stuck on Stopping Procedure

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#15023]
Hello Coders,

I got a workspace stuck on the stopping procedure, we use K8s baremetal, the pod already is Terminated so it doesnt exist anymore on K8s. 

![Image](https://github.com/user-attachments/assets/199a448b-9dab-4439-9830-a6eed7b0d59e)

The Web UI its stuck on this Stopping procedure. If I cancel it, the only option I got its to "Retry"

![Image](https://github.com/user-attachments/assets/00734a51-c9fa-44ab-ade8-3a33d52a3a32)

But I dont want to "Retry", I already know it will stay stuck. Is there a way to skip this procedure, to get the "Start", considering that all K8s components of these workspace are already free.

**Comment by matifali** [comment]
Can you try stopping again from the cli using `coder stop ws-x86`?

**Comment by francisco-mata** [comment]
Thanks that worked :)

**Comment by matifali** [comment]
This could also be solved by #14995.
