### ISSUE TITLE
Display the template name in Workspace details page

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#15033]
# Description

It is hard to figure out which template is used in the Workspace details page. We only have two templates (production and testing) but a rich set of demo Workspaces to find out if all works as excepected. The names are derived from use case so they are in both template the same.

When testing and switching between these it is error prone as one has to leave Workspace details page and get back to Workspace listing page to find out  what template drives this Workspace. 

![Image](https://github.com/user-attachments/assets/e9066422-ed37-4ea8-8252-2d4e7f9eda43)

# Solution

Show the template in the UI

E.g. like this bread crumb
[USERNAME] --> [TEMPLATENAME] --> [WORKSPACENAME]

**Comment by matifali** [comment]
I agree and a +1 from me.

**Comment by aslilac** [comment]
this is very unrelated to #14309 😅

the template name is already visible if you hover over the workspace name. there's probably somewhere better to show it, but I'm not convinced that the breadcrumbs are the right one.

**Comment by MrPeacockNLB** [comment]
Hovering over the workspace name does not show the template name. It only shows the current version of the template. I did not find any place on the workspace page where I can get the template name.

![Image](https://github.com/user-attachments/assets/a0c159be-ed06-4f9f-9fca-fc09bf0db7c1)

As you can see there is only the version shown. For me ( I'm not an UX expert ) it seems logical in that order of  [USERNAME] --> [TEMPLATENAME] --> [WORKSPACENAME].

Hoovering over username should show the organisation and maybe the group. Over template name one should see the version and finally hoovering Workspacename shows build history. @aslilac  what do you think?

**Comment by aslilac** [comment]
oh, it looks like that popover won't fall back to the `template_name` value like we usually do if `template_display_name` isn't set. I'll get that fixed.

I think showing build history in a popover is probably a bit much, and the organization is its own breadcrumb–if you have organizations enabled. Showing group information sounds interesting, but there's not really any strong correlation between a template and a group. A group you're in might give you permission to use a certain template, but that permission could also come from multiple groups so it gets a bit messy.
