### ISSUE TITLE
Add a variable to ask for socket in Docker-based example templates

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#15035]
When adding one of the Docker-based starter templates (from/starter-templates) while using an external Docker daemon that does not match the Docker provider's default value (`/var/run/docker.sock`), you will be met by an error message telling you that the Docker socket can't be reached.

This also means that the template won't be added to your instance due to the error, and you can't just change that, so you need to clone and edit the example from the repo, and then push it to your Coder instance.

I think we can fix this pretty easily by just adding a `variable` block asking for the socket's path.

cc: @matifali

**Comment by phorcys420** [comment]
This is what will happen if you try to create a template from the Docker-based starter templates when you don't have a Docker socket, and then you're just stuck.

```
Error: Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
on main.tf line 19, in provider "docker":
  19: provider "docker" {
```

![Image](https://github.com/user-attachments/assets/0683995e-60f5-4ca2-b318-1b04eb36fb12)

**Comment by matifali** [comment]
This was previously discussed in https://github.com/coder/coder/issues/6860#issuecomment-1488464552, but it ended in that we still need a valid default value for the docker socket; otherwise, the docker provider refuses to initialize in the planning phase.
I am open to making it a template variable if that solves the issue.
