### ISSUE TITLE
Improve UX when there is no corresponding provisioner for a workspace/template

### ISSUE THREAD

**Issue by bpmct** [coder/coder#15048]
Since more and more of our users are using external provisioners and [provisioner tags](https://coder.com/docs/admin/provisioners#provisioner-tags), especially with Organizations, we should explore ways to improve the UX when a provisioner is not running. 

### Create/duplicate template

![Image](https://github.com/user-attachments/assets/375b8415-21de-48ea-b6bb-7c485e9193d6)

### Template Editor

https://github.com/user-attachments/assets/fa1f5c2c-e965-4009-af8b-ed8113a95069

> Suggestion: "No provisioners are running with the tag `provisioner=missing` in the `data-science` org. Learn more about provisioners in [the Coder documentation](https://coder.com/docs/admin/provisioners)"

## Create workspace

![Image](https://github.com/user-attachments/assets/5510622c-6740-47a9-a55c-7bb497997795)

> Suggestion: "No provisioners are running with the tag `provisioner=missing` in the `data-science` org.
> Learn more about provisioners in [the Coder documentation](https://coder.com/docs/admin/provisioners)"

## Desired state

- Some meaningful and actionable error. One suggestion:
    > No provisioners are running with the tag `provisioner=missing` in the `data-science` org
    > Learn more about provisioners in [the Coder documentation](https://coder.com/docs/admin/provisioners)"
- Perhaps a custom troubleshooting URL for users, similar to the [agent](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#troubleshooting_url) as the organization/template may have internal docs about provisioners work in their organization.

**Comment by bpmct** [comment]
cc @chrifro @Kira-Pilot

**Comment by matifali** [comment]
Related to #12331

**Comment by chrifro** [comment]
Related/duplicated issue https://github.com/coder/coder/issues/14845

**Comment by chrifro** [comment]
[Here](https://www.figma.com/design/OR75XeUI0Z3ksqt1mHsNQw/Dashbord-v1?node-id=747-10892&t=iOBUYZbcP7mhFI90-1) are the mockups for the three different pages with the error messages. I marked the changes with comments. What do you think @BrunoQuaresma @bpmct ?

**Comment by chrifro** [comment]
Ben has approved the new error states. They will look like this
![Image](https://github.com/user-attachments/assets/5ecb81fe-1117-47b6-be5a-a41e04596a0c)
![Image](https://github.com/user-attachments/assets/3b9bcdff-e48b-41e8-b68e-5e664b6327b6)
![Image](https://github.com/user-attachments/assets/23bafb22-2ca1-48a9-a9c7-404cc4b5328b)


The exact changes are marked in [Figma](https://www.figma.com/design/OR75XeUI0Z3ksqt1mHsNQw/Dashbord-v1?node-id=747-10892&t=OSeUj1KIG63ece0l-1).

**Comment by SasSwart** [comment]
My current understanding of this issue yields the following backend requirements:
* determine how best to provide provisioner status to the frontend (as api documentation)
* determine how to collect the information required for the new/updated endpoint
* implement the endpoint with a mock response
* do the plumbing to gather the required information and serve it via the endpoint

Each of these steps will require attention paid to tests, logging, documentation, etc.

**Comment by johnstcn** [comment]
@SasSwart Mathias and I discussed this issue today:

This check should **not** be done in the frontend, as it would require duplication of the logic we currently use to match provisioner jobs to provisioners (currently in the `AcquireProvisionerJob` database query).

This means that the check **must** be done in the backend. We also **must not** block creating a provisioner job if a provisioner is not available, as this could simply be a temporary issue (provisioner got restarted but will be coming back up).

So the options that are left to us to implement this feature are somewhat limited. I would suggest adding a new "pre-flight" endpoint for both a template version and workspace build jobs. The function of this "pre-flight" URL is to determine if any provisioner is capable of taking the job.

Note that there is a separate issue whereby workspace tags can be defined __inside the template version Terraform itself__. You can __ignore this__ for the purposes of this issue, as there exists a [separate issue](https://github.com/coder/coder/issues/15087) for that feature.

**Comment by johnstcn** [comment]
> [@johnstcn](https://github.com/johnstcn) Makes sense. Instead of a preflight api call, I was thinking of making the current call return this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
> 
> If there are no matching provisioners currently available.

The problem with that approach is that it requires the user to click 'submit' in order to determine if the job can be even accomplished. As far as I can tell, the proposed UX requires that the user is able to know _a priori_ if the job can be actioned with its current set of tags.

**Comment by SasSwart** [comment]
Proposed API:
```
// @Summary Get recently seen provisioner daemons by tags
// @ID get-recently-seen-provisioner-daemons-by-tags
// @Security CoderSessionToken
// @Produce json
// @Tags Enterprise
// @Param organization path string true "Organization ID" format(uuid)
// @Param tags query []string false "Tags required by acceptable provisioners"
// @Success 200 {array} codersdk.ProvisionerDaemon
// @Router /organizations/{organization}/provisionerdaemons/recentlyseen [get]
```

The idea is that you can request this endpoint from the frontend to determine whether any provisioners with the required tags were recently seen. If it returns an empty list, then you can display the error. If it returns any elements at all, then we have confidence that at least one provisioner can accept the and we can therefore allow the user to proceed with the flow. 

For provisioning jobs that are already in progress,  where we currently display a loading screen, you might have to poll this endpoint occasionally to determine if the error is still applicable. As an optimisation, we could later do this over websocket if we find it necessary.

The definition of "recently seen" would be abstracted by the backend. It would be based on some measure of the heartbeat of the provisioners. To start with probably simply the last seen value as per the database.

Any thoughts or considerations?

cc @BrunoQuaresma @johnstcn

**Comment by johnstcn** [comment]
We could alternatively piggy-back on the existing provisioner daemon endpoint either and allow filtering by tags?

```
/api/v2/organizations/:id/provisionerdaemons?tags=foo%3Dbar%2Crazzle%3Ddazzle
```

**Comment by johnstcn** [comment]
> Question: When creating a template, how do I know which tags should I use to get this data?

You actually don't! I'm working on this right now https://github.com/coder/coder/issues/15087

**Comment by bpmct** [comment]
I see we did this on template-level for v2.18. Looks super nice! @SasSwart 

![Image](https://github.com/user-attachments/assets/fef07e91-2bd3-4d69-b5b8-eace33dfedc4)

Any plans for workspace-level?

![Image](https://github.com/user-attachments/assets/d9fabcb4-7c5d-4809-b23b-99727bd283d7)

**Comment by johnstcn** [comment]
@bpmct Workspace-level is in progress here:
- CLI, API: https://github.com/coder/coder/pull/15688
- UI: https://github.com/coder/coder/pull/15686
