### ISSUE TITLE
Command-line build log overwrites previous CLI output

### ISSUE THREAD

**Issue by mafredri** [coder/coder#1506]
In some cases, the CLI can overwrite previous output.

## Steps to Reproduce

1. Run `coder create`
2. When prompted `Confirm create? (yes/no)`, answer `yes`
3. The `Confirm create?` line is overwritten by `✔ Queued [136ms]? (yes/no) yes`

## Expected

No previously output lines should be overwritten (with the exception of status updates).

## Actual

The line is overwritten.

## Screenshot

<img width="664" alt="image" src="https://user-images.githubusercontent.com/147409/168772942-92292a67-3693-423d-b125-7b93edddc55d.png">

(Ignore the terraform error, it's probably EU West that is not set up.)

## Notes

This is likely fixed by adding a newline somewhere, but we should check if we can update the cli packages to guard against this.

**Comment by mafredri** [comment]
This still happens on occasion, but needs deeper investigation to narrow down cause and where it happens (for instance, it has also happened when prompting for terraform variable input which is confusing since part or all of the message is missing -- this may or may not have been fixed).

**Comment by bpmct** [comment]
@kylecarbs is this fixed by #4740?

**Comment by kylecarbs** [comment]
yup
