### ISSUE TITLE
chore: generate countries.tsx from Go code

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#15074]
# Motivation

Context: https://github.com/coder/coder/pull/15054#discussion_r1798774679

We have a hard-coded list of countries in https://github.com/coder/coder/blob/main/site/src/pages/SetupPage/countries.tsx

This unfortunately means that the Go code in coder/coder doesn't have an easy way of utilizing it.

# Proposed solution

Generate `countries.tsx` from Go code. This would entail modifying `countries.tsx` to Go syntax and using code generation to write `countries.tsx`.

This should be a relatively small lift as we have extensive code generation already in place. It could possibly be generated by `scripts/apitypings`.

**Comment by joobisb** [comment]
@johnstcn could you please assign this to me

**Comment by dannykopping** [comment]
@joobisb done 👍 thank you
