### ISSUE TITLE
Embedding Coder Instance - CSP Frame Ancestor Issue

### ISSUE THREAD

**Issue by gskolber** [coder/coder#15118]
Hello!

We are currently using Coder in some of our tests. However, for our use case, we intend to embed the instance within our platform. Is it possible to achieve this today?

When attempting this, we encounter the following issue:

```
Refused to frame 'https://s6bk5npn0e4j8.pit-1.try.coder.app/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

Is there any alternative or workaround for this?

Thanks in advance!

**Comment by kylecarbs** [comment]
cc @Emyrk resident CSP expert

**Comment by Emyrk** [comment]
I will find some time to look into this.

This is where we currently configure our CSP policy: https://github.com/coder/coder/blob/512cbf16823593187172ba4f9c3cf643f34e895a/coderd/httpmw/csp.go#L48-L48

It sounds like we might need to add in some controls to configure a more open policy.

With all of these header style protections, a workaround is always there to put a reverse proxy infront of Coder to mutate the headers. 

For the CSP in question, [`frame-ancestors`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) the best solution will be to explictly list the parent website.

---

@gskolber I can't promise a solution at this very moment, but would a static configuration field to list the parent domain be enough? Meaning, is the root website that embeds Coder a static domain url that could be passed into Coder when you boot Coder? It would be loaded as an `ENV` var, flag, or something like that.

**Comment by gskolber** [comment]
I believe that having the option to pass this field as a static value would indeed solve the problem and be quite straightforward to implement.

For now, we will use a reverse proxy to continue with the implementations on our side. Thank you very much for your attention.
