### ISSUE TITLE
Correct log line when using tagged --key provisioner

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#15126]
Right now we log a line with the tags we are using for the provisioner, and when using `--key` it says it's "untagged" which isn't true. 

```
2024-11-06 21:29:27.404 [info]  starting provisioner daemon  tags={}  name=coder-provisioner-67d54c74dc-qds64

```

The issue is that the key authentication does not have permission to describe the key and get the tags, and since we don't get any from the cli args, it logs that there's no tags. 

Options I see:
1. Add permissions to provisioner keys to get tag information
2. Remove log line altogether if it's not critical information

Spun out from https://github.com/coder/coder/issues/15047

**Comment by johnstcn** [comment]
Checked with @f0ssel and the best approach seems to be to add a new endpoint authorized by a valid provisioner key and returns the detailed of the provisioner key used to authenticate. Kind of similar to `/api/v2/users/me`. 
This will also allow the provisioner to validate the key before opening a websocket and connecting to coderd.
