### ISSUE TITLE
bug: broken documentation link

### ISSUE THREAD

**Issue by sreya** [coder/coder#15211]
Attempting to click the `Documentation` link in v2.15.3 and v2.16.0 results in a 404. Notice it tries to navigate to a version that appends the commit hash.

![Image](https://github.com/user-attachments/assets/f834d492-3c1d-4982-aa7e-d1327479f53c)

![Image](https://github.com/user-attachments/assets/61d37dd4-1a9e-46ab-bfb4-a6e1d7f5daf3)

**Comment by ethanndickson** [comment]
Fixed in [#14963](https://github.com/coder/coder/pull/14963)
