### ISSUE TITLE
User Admin can't view the /deployment/users page

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#15212]
I have a user that has role `User Admin` (and `Template Admin` if that matters).

When I try to view the `/deployment/users` page, it responds

> **Forbidden.**
> Please check the developer console for more details.

In the browser dev tools, I can see that requests to 

* `/api/v2/deployment/config` and
* `/api/v2/deployment/stats`

are both coming back 403 Forbidden.

**Comment by johnstcn** [comment]
I think this is a UI issue. I can replicate the "Forbidden" error with a user having only the "User Admin" role but a request to `/api/v2/users` returns successfully. Similarly, the following CLI commands work as expected:

```
# main@095c9797c
$ ./scripts/coder-dev.sh users list
USERNAME   EMAIL                CREATED AT                 STATUS   
admin      admin@coder.com      2024-10-21T10:58:14+01:00  active   
member     member@coder.com     2024-10-21T10:58:24+01:00  dormant  
useradmin  useradmin@coder.com  2024-10-24T15:52:34+01:00  active   
$ ./scripts/coder-dev.sh whoami
  Coder is running at http://localhost:3000, You're authenticated as useradmin !
```

**Comment by Parkreiner** [comment]
Yeah, I just tested all combos of user admins and template admins, and am getting the same issue. I'm poking around the UI code now

**Comment by spikecurtis** [comment]
@Parkreiner any idea what version we regressed on?

**Comment by Parkreiner** [comment]
@spikecurtis I don't think we've pushed this out to anyone yet.
The issue got introduced [in this PR](https://github.com/coder/coder/pull/14885), but that was merged in Oct 3. The last non-patch release was Oct 1
