### ISSUE TITLE
Coder is not functioning properly

### ISSUE THREAD

**Issue by kerwin612** [coder/coder#15244]
* New Template from a started template[/templates/new?exampleId=docker](/templates/new?exampleId=docker)
![Image](https://github.com/user-attachments/assets/79462fb9-370c-4d42-80a6-3dedb4f42c00)

* Without making any changes, create a workspace using the template added in the previous step, It's not working properly
![Image](https://github.com/user-attachments/assets/e258bc0f-ac0a-4b96-86b5-55578aa810b1)

* Coder nohup output
![Image](https://github.com/user-attachments/assets/5df9d639-30e2-451b-ab71-427c793a457a)

* ps -ef | grep coder
![Image](https://github.com/user-attachments/assets/9a60bfd9-0008-440e-82f7-921a7c6c0878)

**Comment by kerwin612** [comment]
![Image](https://github.com/user-attachments/assets/6a7ba6e6-8808-4e82-ae43-fe9cbfd01a3a)

**Comment by stirby** [comment]
Hey there, did you follow our local quickstart guide with Docker Desktop?

**Comment by kerwin612** [comment]
> Hey there, did you follow our local quickstart guide with Docker Desktop?

I installed it manually offline.

**Comment by kerwin612** [comment]
It seems that I've found the issue.   
This problem arises when I configure the `dns` under the `docker_container`:

```tf
resource "docker_container" "workspace" {
  count = data.coder_workspace.me.start_count
  image = docker_image.main.name
  # Uses lower() to avoid Docker restriction on container names.
  name = "coder-${data.coder_workspace_owner.me.name}-${lower(data.coder_workspace.me.name)}"
  # Hostname makes the shell more user friendly: coder@my-workspace:~$
  hostname = data.coder_workspace.me.name
  ...
  dns = ["172.16.3.12", "114.114.114.114"]
  ...
}
```

**Comment by matifali** [comment]
What DNS values work and what doesn't?

**Comment by kerwin612** [comment]
> 哪些 DNS 值有效，哪些无效？

Both of these dns are actually valid, but when they are applied, the issues mentioned above arise, and the system returns to normal when they are removed.

**Comment by matifali** [comment]
Are these public or internal DNS servers? 
Also you can check the docker container logs `docker logs <container_name_or_id>`  to see if there are any network issues when using the above specified DNS servers.

**Comment by kerwin612** [comment]
> Are these public or internal DNS servers? Also you can check the docker container logs `docker logs <container_name_or_id>` to see if there are any network issues when using the above specified DNS servers.

```bash
$ docker logs fe20a50c38b9  
+ trap waitonexit EXIT
+ mktemp -d -t coder.XXXXXX
+ BINARY_DIR=/tmp/coder.1uZgEp
+ BINARY_NAME=coder
+ BINARY_URL=http://cde.mprtimes.net:3000/bin/coder-linux-amd64
+ cd /tmp/coder.1uZgEp
+ :
+ status=
+ command -v curl
+ curl -fsSL --compressed http://cde.mprtimes.net:3000/bin/coder-linux-amd64 -o coder
curl: (6) Could not resolve host: cde.mprtimes.net
+ status=6
+ echo error: failed to download coder agent
+ echo        command returned: 6
+ echo Trying again in 30 seconds...
+ sleep 30
error: failed to download coder agent
command returned: 6
Trying again in 30 seconds..
```

Indeed, it was caused by improper use of DNS, so I will close this issue.
However, I'd like to make a suggestion along the way; for issues like this, could there be some prompts and log entry points on the UI interface? This would make it easier to identify problems without feeling overwhelmed and helpless.

**Comment by matifali** [comment]
Thank you for the feedback. I have proposed an improvement to troubleshoot the agent connection in #15423 and am hopeful that it will help improve the situation.
