### ISSUE TITLE
Issue with workspace builds timing RBAC

### ISSUE THREAD

**Issue by DanielleMaywood** [coder/coder#15250]
Currently if a user with a template admin role attempts to view the provisioning time for a workspace build of another user they get a 500 internal server error response. The user is still able to see the build logs, but they are unable to see the provisioner timings.

The endpoint
```
https://dev.coder.com/api/v2/workspacebuilds/<workspace_id>/timings
```

The response 
```json
{
  "message": "Internal error fetching timings.",
  "detail": "fetching workspace agent script timings: unauthorized: rbac: forbidden"
}
```

**Comment by bpmct** [comment]
Great find. Added to our next sprint

**Comment by Emyrk** [comment]
This query is preventing it: https://github.com/coder/coder/blob/b05b00c797506ed6a0512b9f164f7ee7d71fece5/coderd/database/dbauthz/dbauthz.go#L2424-L2429
