### ISSUE TITLE
Rotate server logs

### ISSUE THREAD

**Issue by bpmct** [coder/coder#15309]
We currently [rotate agent logs](https://github.com/coder/coder/blob/330acd127071eaf0aec50cd72d51abffdff98bbb/cli/agent.go#L113-L118) and had a customer request to rotate the server logs as well for `CODER_LOGGING_HUMAN`

**Comment by johnstcn** [comment]
This would only be a valid behaviour if Coder is logging directly to a file. If logging to stdout/stderr directly then whatever is consuming that stream should be responsible for log rotation (e.g. `journald`, `kubelet`, or `docker`).
