### ISSUE TITLE
500 Error on Duplicate Template Name Change, No UI Error Displayed

### ISSUE THREAD

**Issue by minagishl** [coder/coder#15311]
When selecting a template from the template list, opening "Settings," and attempting to change the name to one that already exists, the API returns a 500 error with the following message. However, there is no error displayed in the UI, making it difficult to understand the issue.

```json
{
    "message": "An internal server error occurred.",
    "detail": "execute transaction: update template metadata: pq: duplicate key value violates unique constraint \"templates_organization_id_name_idx\""
}
```

This text was translated from Japanese to English using ChatGPT, so there may be minor contextual inaccuracies. Thank you for your understanding.

**Comment by matifali** [comment]
Hi, @minagishl could you share the coder version you are on?

**Comment by minagishl** [comment]
Hello, @matifali 
The version of Coder I am using is v2.16.0+683a720.

**Comment by matifali** [comment]
Thank you for reporting. I can reproduce this on dev.coder.com.
