### ISSUE TITLE
Link to code of conduct is timing out of giving a 302

### ISSUE THREAD

**Issue by michaelbrewer** [coder/coder#15369]
I assume this is the correct link is : `https://coder.com/docs/contributing/CODE_OF_CONDUCT`, Github normally looks for `CODE_OF_CONDUCT.md`

![Image](https://github.com/user-attachments/assets/d810bf23-ceed-496e-97b1-274c509c9125)

**Comment by matifali** [comment]
@EdwardAngert can you look into this?

**Comment by EdwardAngert** [comment]
thanks @michaelbrewer (and @matifali )! 

We do have the code of conduct built as a page on <https://coder.com/docs/contributing/CODE_OF_CONDUCT>, but I do like having it accessible from the repo too, so I added a page with a link in https://github.com/coder/coder/pull/15386
