### ISSUE TITLE
Disabling autostop causes workspace to get stuck with last autostop value

### ISSUE THREAD

**Issue by code-asher** [coder/coder#15390]
To reproduce:

1. Create a new template using the "Docker Containers" starter template (notice it does not allow customizing the autostop and has a default of 24 hours).
2. Create a workspace using that template.  The workspace must be created while autostop is currently enabled.  Workspaces that are initially created with autostop disabled somehow do not have any problems updating correctly.
3. Disable autostop in the template through the UI.
4. Update the workspace, notice it will continue to say "stops in a day" despite autostop being disabled in the template, and showing as disabled in the workspace settings.
5. New workspaces are fine and do not have any autostop.

I think the default autostop gets set on the workspace, but when you disable autostop it does not then remove it from the workspaces, and you cannot change it as a user either because autostop is disabled in this scenario.

**Comment by code-asher** [comment]
Also, not sure if this is a bug but it feels a little unexpected to me, if you set the default to zero then no workspaces will autostop (expected), then later set the default to 24 all workspaces will autostop after 24 hours (expected), then later again enable customizing autostop, some workspaces may have no autostop depending on what the default was when they were created (unexpected?).  I think I would expect them to all have 24 hours.

**Comment by johnstcn** [comment]
cc @bpmct should we add this to the upcoming sprint? Possible 🥥 issue

**Comment by DanielleMaywood** [comment]
With https://github.com/coder/coder/pull/15761 being merged, when a template's TTL is modified, _and users are unable to change their workspace's autostop_, then workspaces using this template have their TTL modified.

This doesn't have an effect on running workspaces though. As an example, if a workspace was started when autostop was 8 hours, and then the template admin decided to disable autostop, the running workspace still has the same 8 hour deadline. Only when the workspace is next started does this take effect.

A question I have is do we want to modify a running workspace's deadline based on the changing TTL or do we leave that as is? My thoughts are that if the TTL is _increased_ then there is no harm in extending the workspace's deadline, but I'm not sure if it is a good user experience to decrease a workspace's deadline when the TTL is decreased. @bpmct I feel like this might need product's perspective.

**Comment by bpmct** [comment]
> A question I have is do we want to modify a running workspace's deadline based on the changing TTL or do we leave that as is? My thoughts are that if the TTL is increased then there is no harm in extending the workspace's deadline, but I'm not sure if it is a good user experience to decrease a workspace's deadline when the TTL is decreased. @bpmct I feel like this might need product's perspective.

I totally agree with your perspective here. We should never allow a bulk change to decrease a living workspaces' autostop. Increasing is _fine_, but I am also totally OK if we just require an update for the changes to take effect. Will defer to your judgement here.

Bulk workspace actions or CLIs can be used to update workspaces.
