### ISSUE TITLE
UX: It is not easy to find coder scripts details

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#15393]
# description

In addition to #15392 the timeline is not visible to the user. I've to scroll a lot to get to the start of the **workspace start** transition.

![Image](https://github.com/user-attachments/assets/95b2f98f-23d3-4a9f-9d6e-133864148436)

As one could see in the screenshot above the scrollbar is short and almost at the right side.

In addition why is the **workspace start** transition not unfolded by default? I've had no clue what are these blue bubbles as they are all equal.

# Solution

Autoscroll to the begining of **workspace start** sequence and unfold **workspace start**

**Comment by BrunoQuaresma** [comment]
It appears to be a duplicate of https://github.com/coder/coder/issues/15374. I am closing it for now, but please let me know if there is a different context.
