### ISSUE TITLE
[bug] pixelated image on /docs

### ISSUE THREAD

**Issue by chrifro** [coder/coder#15407]
This image is huge and pixelated. If we decrease the image size the image quality should work fine and it will be easier to grasp the information for the reader. 
URL: https://coder.com/docs/CONTRIBUTING
![Image](https://github.com/user-attachments/assets/f2b82ee4-dfae-4125-8811-5b688bc4bde7)

**Comment by matifali** [comment]
Thank you for raising this. We have a general image sizing problem in our docs. And you should be able to find more examples of oversized images easily. 

@EdwardAngert may have plans to fix these systematically.

**Comment by EdwardAngert** [comment]
@matifali I'm testing that PR with a `max-width` attribute, if that succeeds, I feel like we can find somewhere in `src/components/Docs
/HTMLRenderer.tsx` Lines 107-110 to make it a rule, but I'm not totally sure how just yet. I can poke around later, but figured I'd drop it here in case it's something you already know about 🤞
