### ISSUE TITLE
Feat: Add `coder version` subcommand and remove the shorthand `-v` (to give room for `-v` as verbose)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#1543]
## What is your suggestion?

I'm suggesting we add a `coder version` subcommand and remove the shorthand `-v` flag. This is similar to how `git` and `gh` behave.

Docker implements `docker version` as extended version output, whereas `--version` is short.

An option is to rename `-v` to `-V` which is used in some tools, but not in the aforementioned ones.

## Why do you want this feature?

I think it would be nice to reserve `-v` for getting more verbose output from the CLI/server.

## Are there any workarounds to get this functionality today?

No.

## Are you interested in submitting a PR for this?

Yes.

**Comment by Emyrk** [comment]
https://github.com/coder/coder/pull/2090

**Comment by ketang** [comment]
I like `-vv` for extreeeeeeme verbosity.

**Comment by Emyrk** [comment]
https://github.com/coder/coder/pull/2090 Adds `coder version` and removes flags `-v` and `--version`
