### ISSUE TITLE
Difficult to debug failures of agent init script in Docker provider

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1544]
# Definition of Done
Clear log should be provided to surface errors so users do not have to go down several rabbit holes to try and understand what went wrong. 

One acceptable outcome suggested in backend variety: 

> the Docker agent init script could log errors and then sleep forever if it hits a problem, instead of exiting. This would keep the container from exiting, and so the end user would see the build succeed, but the agent failed to connect. They could then docker logs ... to see what's up.

> alternatively, we just fix kreuzwerker/docker to (optionally?) not delete containers after 15s

# What

If the init script fails, there is very little way to debug the root cause (e.g. with Docker).
For example, if you set the Coder access URL to something invalid in the template, then all Docker containers will exit immediately e.g.

![image](https://user-images.githubusercontent.com/4949514/169035108-443a79bb-6426-4ad6-b031-336d17b0f1a0.png)

In the above example, the error "container exited immediately" is actually coming from `kreuzwerker/docker` itself -- see https://github.com/kreuzwerker/terraform-provider-docker/issues/92

To actually dig out the root cause of the error, you have to e.g. turn on debug logging in the Docker daemon and check the daemon logs to actually see what's going wrong.

This isn't great usability, and we should have a better way of surfacing various kinds of errors from the agent init script.

There are quite a few possibilities for things to go wrong, including:
- `curl` does not exist
- failed to create temporary directory
- failed to fetch agent binary
- failed to `chmod` binary
- `coder agent` failed
- ...

# Why

Make it easier for users to figure out why their container won't start.

**Comment by tjcran** [comment]
> Good suggestion from @dwahler : [#1198 (comment)](https://github.com/coder/coder/issues/1198#issuecomment-1136063522)

@johnstcn is this one worth keeping open as #1198 is closed? or is this one still reproducible?

**Comment by johnstcn** [comment]
@tjcran we should keep it open; having the wrong agent URL set will still cause this to happen.

**Comment by spikecurtis** [comment]
From discussion in Backend variety: the Docker agent init script could log errors and then sleep forever if it hits a problem, instead of exiting.  This would keep the container from exiting, and so the end user would see the build succeed, but the agent failed to connect.  They could then `docker logs ...` to see what's up.

**Comment by johnstcn** [comment]
(Also from Backend variety): alternatively, we just fix `kreuzwerker/docker` to (optionally?) not delete containers after 15s

**Comment by johnstcn** [comment]
https://github.com/coder/coder/commit/9f90ee39f0538ad9f59fa81796b700307511820a should address this.

Please reopen if this is not the case.
