### ISSUE TITLE
`CODER_NOTIFICATIONS_EMAIL_SMARTHOST`'s value is never used

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#15480]
`CODER_NOTIFICATIONS_EMAIL_SMARTHOST` is now deprecated, and superseded by `CODER_EMAIL_SMARTHOST` in https://github.com/coder/coder/pull/15270.

However, if `CODER_EMAIL_SMARTHOST` is unset then the value from `CODER_NOTIFICATIONS_EMAIL_SMARTHOST` should be used. Currently it is not, and I suspect it's because `CODER_EMAIL_SMARTHOST` has a default value:

```go
	emailSmarthost := serpent.Option{
		Name:        "Email: Smarthost",
		Description: "The intermediary SMTP host through which emails are sent.",
		Flag:        "email-smarthost",
		Env:         "CODER_EMAIL_SMARTHOST",
		Default:     "localhost:587", // To pass validation.
		Value:       &c.Notifications.SMTP.Smarthost,
		Group:       &deploymentGroupEmail,
		YAML:        "smarthost",
	}
```

**Comment by DanielleMaywood** [comment]
Fixed by https://github.com/coder/coder/pull/15476
