### ISSUE TITLE
Terminal Font Setting for Web Terminal

### ISSUE THREAD

**Issue by matifali** [coder/coder#15493]
### Discussed in https://github.com/coder/coder/discussions/14364

<div type='discussions-op-text'>

<sup>Originally posted by **dean-boi** August 20, 2024</sup>
Hi, 

Is anyone using a Neovim distro in coder terminal? Is it possible to set fonts for the coder terminal web interface? For me LazyVim is displaying broken in the web terminal, but works properly in the code-server terminal.... 

![image](https://github.com/user-attachments/assets/76c2a509-2d6d-4bf4-9ec3-13eb61a82b2c)

![image](https://github.com/user-attachments/assets/992b7195-c314-456a-87aa-1c150ed29b88)
</div>

**Comment by Mr-Coxall** [comment]
I already have an issue created about this: https://github.com/coder/coder/issues/15024
