### ISSUE TITLE
How can I bump autostop to leave room for long-running scripts?

### ISSUE THREAD

**Issue by bpmct** [coder/coder#15515]
We currently [have documentation](https://coder.com/docs/reference#workspace-agents) for using the REST API to imitate session activity to bump the workspace if a script is not working, but we have seen some reports of this not working.

Similarly, the `coder schedule override-stop` does not work if a policy is set on the template for autostop. Can we spend some cycles to have a revised opinion on how to recommend users keep the workspace running if they have, for example, a training job running?

Some ideas:
- Introduce a `coder schedule bump` CLI command
- Improved visibility in UI (a [customer](https://codercom.slack.com/archives/C04EHNF3A0Y/p1730222790643979) reported the autostop warning UI only shows up when the workspace hits the deadline, not always)
- verify the endpoint and/or update the docs

**Comment by aaronlehmann** [comment]
Specifically, the `/extend` endpoint doesn't work for us because it requires the "Allow users to customize autostop duration for workspaces" setting to be enabled. We don't want users to be able to customize the autostop duration, but do want to allow them to bump autostop when needed (up to the limit imposed by the template).

**Comment by bpmct** [comment]
> I'm not sure the current approach makes the most sense. This endpoint doesn't provide the ability to extend the workspace's "MaxDeadline", meaning it doesn't enable a user to do anything they couldn't already do by just connecting to their workspace. Restricting users from calling this endpoint doesn't really solve anything I feel (from a point of cost-saving or otherwise).

@bpmct thoughts on this?

Totally agree. I think the user should be able to hit this endpoint since it doesn't impact the max deadline. Being able to use this endpoint to keep the workspace running for a long script would be great.

Thoughts on also making/renaming a CLI command to `coder schedule bump`?

**Comment by stirby** [comment]
We should revert that check. These actions are around "activity bump" - a distinct feature from autostop.

All of the methods for simulating user activity should be executable by the user.
