### ISSUE TITLE
Incorrect/misleading text on "Workspace Schedule" settings page

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#15536]
![Image](https://github.com/user-attachments/assets/9c1f5799-2990-4422-ba31-df925078a1ec)

"We delay shutdown by 1 hour when we detect activity" is incorrect in this case (it's bumped by 3 hours at a time according to the template settings) and also inconsistent with "This will be extended by 3 hours after last activity in the workspace was detected." just to the left. The `1 hour` text appears to be [hardcoded](https://github.com/coder/coder/blob/12a9d6336ba69ce93d9b0b0f903d0c0fbc3b0a3c/site/src/pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx#L467).

**Comment by stirby** [comment]
Thanks for reporting this @aaronlehmann. We will fix this in the upcoming sprint.

The hardcoded `1 hour` is an artifact from when the activity bump was immutable.
