### ISSUE TITLE
One-click deploy to app platforms (Heroku, Railway, fly.io, AWS ECS, Google Cloud Run)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#1554]
> Note: This will be fairly simple, but requires the repo to be public.

## What is your suggestion?

Create one click apps to deploy the `ghcr.io/coder/coder` container image to cloud app platforms. Most of these services provide a domain, postgres instance, and allow you to configure env vars so it can be a "one-click" experience to have a production-ready deployment of Coder.

## Why do you want this feature?

Quick way to use Coder in prod and test with other users.

## Are there any workarounds to get this functionality today?

Users create their own "deploy" repos or manually deploy the container to the app platform

## Are you interested in submitting a PR for this?

Yes

**Comment by tjcran** [comment]
@bpmct i _think_ this would work with the DigitalOcean app platform as well.

**Comment by bpmct** [comment]
@misskniss I don't think I can do this in our current sprint.

**Comment by matifali** [comment]
related to #7257

**Comment by matifali** [comment]
We have all of them now in https://github.com/coder/packages
