### ISSUE TITLE
Terraform error when trying to run coder in docker-compose

### ISSUE THREAD

**Issue by jon-peel** [coder/coder#15554]
Hi, 
I am trying to run coder in docker-compose.

I am working off the steps and compose file linked to here: https://coder.com/docs/install/docker

I am able to get everything running, but when I try and create a workspace from the template I get the error "initialize terraform: exit status 1".

I included the "group_add" in the configuration, incase that is the problem (in my case the group is 984, according to the command provided in the tutorial).

Is this a known issue, are there any known fixes to it?
I tried to search for the error, in relation to Coder, but I was not successful in coming up with anything.

Thanks.

---
The logs (from docker), after trying to create a workspace:
```
coder-1           | 2024-11-17 11:41:30.187 [info]  coderd: audit_log  ID=fbafc1b3-9f4e-43cf-96be-90b10b0eef12  Time="2024-11-17T11:41:30.180241Z"  UserID=d8575cfe-af2f-4149-b82b-c20c9094a806  OrganizationID=cab2a988-74e3-4e60-a073-5c443937e470  Ip=192.168.0.104  UserAgent="Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0"  ResourceType=template_version  ResourceID=da5479ac-fc8a-4f80-9781-42585d000296  ResourceTarget=exciting_clarke7  Action=create  Diff="{\"created_by\":{\"Old\":\"\",\"New\":\"d8575cfe-af2f-4149-b82b-c20c9094a806\",\"Secret\":false},\"id\":{\"Old\":\"\",\"New\":\"da5479ac-fc8a-4f80-9781-42585d000296\",\"Secret\":false},\"name\":{\"Old\":\"\",\"New\":\"exciting_clarke7\",\"Secret\":false}}"  StatusCode=201  AdditionalFields="{}"  RequestID=42c242c3-c9a6-4869-8a03-14b19999b1ae  ResourceIcon=""  actor="&{ID:d8575cfe-af2f-4149-b82b-c20c9094a806 Email:me@jonathanpeel.co.za Username:me}"
coder-1           | 2024-11-17 11:41:30.194 [info]  provisionerd-9a1ac41d1e9b-2: unpacking template source archive  session_id=a8875229-37e3-4749-8cc9-d5302eda9c52  size_bytes=11776
coder-1           | 2024-11-17 11:41:30.257 [info]  provisionerd-9a1ac41d1e9b-2: clean stale Terraform plugins  cache_path=/home/coder/.cache/coder/provisioner-2/tf
coder-1           | 2024-11-17 11:41:30.619 [info]  provisionerd-9a1ac41d1e9b-2.runner: dry-run provision failure  job_id=f11faf70-11a4-4c87-b455-c9cdb5e9c0ce  error="initialize terraform: exit status 1"
coder-1           | 2024-11-17 11:41:30.629 [info]  provisionerd-9a1ac41d1e9b-2: recv done on Session  session_id=a8875229-37e3-4749-8cc9-d5302eda9c52  error=EOF
```

**Comment by SasSwart** [comment]
Hey Jon,

I followed the tutorial from scratch in a new Ubuntu VM to see if I encountered the same issue. 
Before setting the `group_add` option, I could not even create the template. After setting the option, I was able to create the template and then subsequently a workspace.

It sounds like you were able to create the template, because you would have had to do so before you could attempt to create a workspace. Therefore, your coder installation must be able to access the Docker socket. 

Perhaps the failure was unrelated to Docker access?

In this case, the logs displayed by Docker are not super specific. The logs displayed in the coder frontend should be more useful. Could you try to create a workspace again and post any relevant logs from the frontend here?

Which template are you using to create the workspace?

**Comment by jon-peel** [comment]
Hi, I am not quite sure what you mean by "logs from the front end".

I am trying to create a docker template.

When I click the button to create a workspace all I see is this:
![Image](https://github.com/user-attachments/assets/913d8fba-7904-493e-84c9-a1f723d60a16)

The logs in docker are as I described.

**Comment by jon-peel** [comment]
In the browser F12 console I get:
```
Warning: An unhandled error was caught from submitForm() Error: template import provision for start: initialize terraform: exit status 1
```

**Comment by SasSwart** [comment]
> Hi, I am not quite sure what you mean by "logs from the front end".
> 
> I am trying to create a docker template.
> 
> When I click the button to create a workspace all I see is this: ![Image](https://github.com/user-attachments/assets/913d8fba-7904-493e-84c9-a1f723d60a16)
> 
> The logs in docker are as I described.

This screenshot is useful. Thanks. That loading spinner is usually replaced by log output as soon as Terraform starts producing logs. The fact that we're not seeing logs tells me that Terraform is experiencing a failur early in the process.

I'll share this with my team.

**Comment by SasSwart** [comment]
I checked with the team. We do have an open issue that will make this easier to troubleshoot:
https://github.com/coder/coder/issues/15554

That won't solve your issue, but it will make it easier to find.
In the mean time, I'll try to replicate your issue so that we can resolve it.

**Comment by jon-peel** [comment]
> To help troubleshoot this, would you mind sharing:
> 
>     * which template you are attempting to create?
> 
>     * which Operating System you're using?

I am trying to create a Docker template.
I am on Fedora, running coder in Docker.

**Comment by SasSwart** [comment]
Hi there,

I tested this on Fedora using the Docker template and I wasn't able to replicate the issue.
There is some variable factor that's different between our environments and I would like to find it.

I'm going to document my approach and findings here as soon as I can. If you're still testing/using Coder, It would be a great help if you could look at what I did and let me know if there's any specific thing that you did differently.

That would help us narrow down the issue.

**Comment by SasSwart** [comment]
On a brand new aws ec2 instance running [Fedora](https://aws.amazon.com/marketplace/pp/prodview-3bn3xvm7jsaqe?applicationId=AWSMPContessa&ref_=beagle&sr=0-5), I did the following as instructed by the tutorial:
```
[fedora@ip-172-31-14-30 ~]$ history
    1  ls
    2  history
    3  docker compose
    4  sudo dnf -y install dnf-plugins-core
    5  sudo dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    6  sudo dnf install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    7  sudo systemctl enable --now docker
    8  sudo docker run hello-world
    9  sudo getent group docker
   10  sudo usermod -aG docker fedora
   11  exit
   12  history
   13  docker ps
   14  sudo getent group docker
   15  vim docker-compose.yml
   16  sudo dnf install vim
   17  vim docker-compose.yml
   18  docker compose up
   19  history
```

I was able to create a new Docker template and then a workspace based on the docker template. Screenshots attached. If anything that I did differs from your setup, please let me know and I'll try to replicate further.

Thanks, Sas.
![Image](https://github.com/user-attachments/assets/b0a0049a-9d22-419c-b587-3b8c9a5e6b21)
![Image](https://github.com/user-attachments/assets/3c596ee4-911d-412f-9a51-5aad674d159d)
![Image](https://github.com/user-attachments/assets/efafa4e2-90e6-47bf-a557-f00c8d8e4ce3)

**Comment by SasSwart** [comment]
I'm closing this issue for now. We haven't been able to replicate this and can't proceed without more information. Feel free to get in touch and we'll reopen this is we have any new leads.

**Comment by jon-peel** [comment]
Hi, I managed to get this running by using a VPN.

Terraform is blocking my IP, and not letting me install.
