### ISSUE TITLE
Unhelpful warning is displayed when using deprecated configs

### ISSUE THREAD

**Issue by dannykopping** [coder/coder#15568]
When a deprecated setting is used, a warning is posted but it doesn't indicate the flag or the env to be used, but rather its name.

`PrintDeprecatedOptions()` is where this is defined. We should probably print the CLI flag, env var name, or a link to the documentation.

```
WARN: Notifications: Email Auth: Password is deprecated, please use Email Auth: Password instead.
WARN: Telemetry (backwards compatibility) is deprecated, please use Telemetry Enable instead.
```

**Comment by DanielleMaywood** [comment]
The related code is located here

https://github.com/coder/coder/blob/a2433b1f320750ad2bc20eacba1082baf56f67da/cli/server.go#L1265-L1297

This could be made nicer by inspecting `opt.ValueSource` to see how the end user has configured the option and printing the relevant flags this way.
