### ISSUE TITLE
Remove workspace_build "name" field

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#1561]
`name` is randomly generated to make it easier for humans to identify a build.  However, with #1534 we introduce a `build_number` which is probably just as easy. 

- [ ] change DB schema to drop "name"
- [ ] change queries to query by workspace_id and build_number, drop queries by name
- [ ] change API to drop queries by name in favor of build_number

**Comment by ketang** [comment]
I agree with changing the queries; I'm not sure I want to get rid of the name entirely.

**Comment by spikecurtis** [comment]
Why do you want to keep it?

**Comment by ketang** [comment]
I'm thinking about potential human to human verbal communication, maybe a collaboration feature or for support.  Although user + workspace name + build number is functionally equivalent, right?  Hmm.

**Comment by spikecurtis** [comment]
Yeah, right now we have API endpoints on:

 - `workspace_id + build_name` - not very human friendly because the workspace ID is UUID
 - `user_name + workspace_name + build_number` - pretty human friendly

So, there isn't aren't at present any human-friendly API endpoints based on build name.

**Comment by ketang** [comment]
Yeah, though those would be trivial to add.  But we shouldn't.  The only use case I could think of is satisfied by the username, workspace name, and build number.  The generated build name adds nothing.  We can yank it.

**Comment by kylecarbs** [comment]
Adding this to EE. It's a trivial fix and should be done for clarity.
