### ISSUE TITLE
feat: custom user key/value attribute

### ISSUE THREAD

**Issue by gjrtimmer** [coder/coder#15636]
## Summary / Context

While trying to implement several options, I came across the following use case, which could be valuable as a feature. When implementing the `personalize` module, for example, you must make a script every time you want to personalize your workspace. Other case put in the URL for your own dotfiles repo. I was trying to think why set this up every time for every workspace.

## Feature Request

Ability to have an admin or user administrator create key/value Pairs + display name on the user or server administration side. 

As an admin, I want to go to some admin panel and click `New Attribute`, which contains the following.

- `Display Name`, to be shown on the user's account page
- `key` key of the attribute (no spaces allowed) used in getting the value
- `value` value which the user can set on their account page
- optional/required: If required, the user cannot start any workspace without setting the attribute

### Access to values

- API: the key/value is set on the user object and can be fetched with the API
- a `coder_user_attribute` data terraform thingy where I only put in the key configured on the attribute creation, and then I can access the value in terraform, like fetching the personalize repo, etc. Of course, the terraform developer is responsible for checking empty values for optional attributes.

Someone good at graphical design can whip up some screenshots/mockups?!?

P.S.
I hope this makes sense.

**Comment by matifali** [comment]
cc: @stirby and @code-asher as you are working on a similar feature.

**Comment by code-asher** [comment]
Yeah I think what we are working on will cover these use cases.

**Comment by gjrtimmer** [comment]
@code-asher In such a way that we can use it in terraform like the use case, user set gitlab token and github token on custom variables on profile and we can use it in terraform ? Will this be community or premium?

**Comment by code-asher** [comment]
Yup, basically you (as the template admin) will be able to mark parameters as "user-level", and parameters marked this way can be filled out by users when creating/editing a workspace, or in a new form in the account page, and the value will be shared across all their workspaces so they only have to enter it once.

It will be in community.

**Comment by code-asher** [comment]
I made a new issue for this, so tentatively closing this one: https://github.com/coder/coder/issues/15722
