### ISSUE TITLE
fix: unify `coder create` and `coder delete` help message

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#15668]
# Problem Description

The CLI reference for [`coder create`](https://coder.com/docs/reference/cli/create) mentions clearly that you can create workspaces for other users, but the reference for [`coder delete`](https://coder.com/docs/reference/cli/delete) doesn't say anything about other users.

I think we should do the following:

`coder create`
```
USAGE:
  coder create [flags] [workspace]

  Create a workspace

    - Create a workspace for another user (if you have permission):

        $ coder create <username>/<workspace_name>
```

`coder delete`
```
USAGE:
  coder delete [flags] <workspace>

  Delete a workspace

    - Delete a workspace for another user (if you have permission):

        $ coder delete <username>/<workspace_name>
```

# User feedback

Based on [Discord discussion](https://discord.com/channels/747933592273027093/1306212095380946985/1306539962862141532)

**Comment by phorcys420** [comment]
I would implement this myself but I got pretty confused as to what I have to edit for the changes to be available both on the website and in the CLI, and for it to pass test.

I would appreciate if someone from the team could link an example PR for a simple change like this.

**Comment by matifali** [comment]
> I want to fix this myself but I got pretty confused as to what I have to edit for the changes to be available both on the website and in the CLI, and for it to pass test.

You should change the Description in `cli` directory and relevant commands go file then run `make gen` and `make update-golden-files`
