### ISSUE TITLE
Support for Terragrunt

### ISSUE THREAD

**Issue by gjrtimmer** [coder/coder#15763]
As many might know code in terraform can quite repeat itself when dealing with multiple environments.

I wold like to request support for `[terragrunt](https://terragrunt.gruntwork.io/)`

Summary:
TerraGrunt is a wrapper around Terraform that allows not only multiple environments, but also allow easy deployments regarding environments.

Regarding implementation I would like to see the ability to configure Terraform or Terragrunt as executor, with keeping Terraform as the default for backwards compatibility. However when you select TerraGrunt as executor, you can also configure some field for a template which environment to deploy, it will allow easy development, using a prod environment where modules are using their registry URL and a Git URL for the dev environment. Using this approach it make development of templates much easier.

**Comment by phorcys420** [comment]
Hey @gjrtimmer, thanks a lot for showing interest in this feature!
We have an open issue about supporting other provisioners -> https://github.com/coder/coder/issues/4528, please leave a comment there :-)
