### ISSUE TITLE
Request: Helm chart allows adding sidecar to coder server deployment

### ISSUE THREAD

**Issue by aarosil** [coder/coder#15802]
Hi, wanted to see if ya'll would be open to a PR to to update the Helm chart values.yaml so I can add a sidecar to the coder server deployment pod spec. 

I'm using cloudsql proxy auth sidecar to access GKE SQL instances. Without this ability, I'll need to add more templates for deploy pgbouncer and add the sidecar on that. 

Thanks!!

**Comment by deansheather** [comment]
We have `initContainers` so it does seem like we should add a value like `extraContainers` too. I'd be open to accepting a PR for this.

**Comment by aarosil** [comment]
Thanks, I ended up using `initContainers` too, but I'll form a PR at some point to add this for later.

**Comment by ericpaulsen** [comment]
@deansheather @aarosil [according to the K8s docs](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-containers-and-pod-lifecycle), we do not need to implement a separate `extraContainers` value, but rather set `restartPolicy: Always` on the `initContainer` value, and K8s will treat it as a sidecar:

> If an init container is created with its restartPolicy set to Always, it will start and remain running during the entire life of the Pod. This can be helpful for running supporting services separated from the main application containers.

this means our Helm chart already supports such a use-case. i'll close this out, but please re-open if i am incorrect here.
