### ISSUE TITLE
Agent is taking too long to connect

### ISSUE THREAD

**Issue by datapedd** [coder/coder#15867]
When Downloading a very large image (here kasm) then it makes this warning. Better would be to know that it is still downloading and everything is fine:

Agent is taking too long to connect

![Image](https://github.com/user-attachments/assets/d09f467d-2130-4285-8e11-96ad3cbe6bc8)

**Comment by matifali** [comment]
Hi @datapedd were you able to get the agent connected successfully or it stays in this state?

**Comment by matifali** [comment]
Closing because not enough information to reproduce. 
Please feel free to comment on the issue or reach out at https://discord.gg/coder if you need any more help.
