### ISSUE TITLE
Can only open 3 workspace tabs open at a time on Chrome without HTTP2 proxy

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#15887]
Currently, an open workspace page uses 2 server side event (SSE) connections. These connections remains open as long as the page is open.

![Image](https://github.com/user-attachments/assets/85ffcb26-aa60-48e7-899c-87ef7c8838db)

Google Chrome only supports a maximum of 6 open connections per host.

Firefox also has a limit, but for whatever reason, the SSE endpoints fail on Firefox. So on firefox, we do not hit the concurrent connection limit.

<details> 
  <summary>Firefox network log</summary>
   A1: JavaScript 

![Image](https://github.com/user-attachments/assets/20200b7a-69d9-464e-af8d-9068dcfcb31a)

</details>

You cannot reproduce this on `https://dev.coder.com` because (for w/e reason), all requests uses HTTP2. So there must be some multiplexing/connection pooling going on by Chrome.

I also tested this through a cloudflare tunnel, which uses HTTP3 and also does not have the issue.

# Reproducing

1. To reproduce, you must be using HTTP 1.1 from Chrome.
2. Open a running workspace page on 4 tabs
3. Open on a fourth tab, and the web request will be stuck in "pending" forever.

# Workaround

A current workaround is to use a reverse proxy in front of Coder that enables HTTP2. Or you can enable TLS on the Coder server (`--tls-enable`). Golang serves HTTP2 on TLS servers by default.

# Implementation Notes

~~The easiest solution would just be to support HTTP2 on non-TLS connections in Coder. We explicitly opt in for TLS serving here: https://github.com/coder/coder/blob/202f7f70f03a0acda6b34a564be3760b6b011fe8/cli/server.go#L1523-L1523~~

HTTP2 does not work over non-tls. 

Solution suggestion is to implement something in the frontend to detect HTTP 1.1 vs HTTP2.0 and display a warning?

**Comment by coadler** [comment]
HTTP2 without TLS is [h2c](https://pkg.go.dev/golang.org/x/net/http2/h2c), but browsers don't implement it. Probably worth noting that websockets are always forced to http/1.1.

**Comment by Emyrk** [comment]
@coadler I wonder if we can determine http 1.1 or 2 on the UI and display some warning or something then 🤔

**Comment by Emyrk** [comment]
Added a basic warning to the UI. We can make this more obvious in the future if we need to
