### ISSUE TITLE
Support passing `tfvars` files for terraform based provisioner workspaces

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#1590]
## What is your suggestion?

Terraform supports using a [`tfvars`](https://www.terraform.io/language/values/variables#variable-definitions-tfvars-files). It would be nice if you could do a `coder workspaces create --tfvars=my.tfvars`.

Currently we are aiming to support yaml/json files to answer all prompts (#1377, #1541). 

Supporting tfvars gets a bit complicated. For one, ideally we do not interpret/parse the tfvars, and pass it "as is" to terraform apply/plan. One solution is to support passing a new `ParameterDestination` type `file`, which lets writing files to the directory where terraform is run. This could possibly be a security issue though, as now users can not only set all parameters, but are writing arbitrary files to the provisionerd node :(. 

Options:
- Parse the tfvars first and do some sanity checks before uploading the file. This would require us to understand the file extension type, rather than a generic "file upload param".

## Why do you want this feature?

`terraform apply` and `coder workspace create` become "synonymous"  for sake of testing.

## Are there any workarounds to get this functionality today?

Yes, use `yaml` or `json` files instead.

**Comment by tjcran** [comment]
@Emyrk i'm inclined to say this is a `nice to have` for now. Any reason I should bump this up to sooner?

**Comment by ketang** [comment]
We shouldn't have a top level argument that is Terraform-specific.  We can do something like `--var name=value` and handle this in a provisioner-independent way.

**Comment by Emyrk** [comment]
@ketang there is different ideas on how to implement this, but we currently support yaml var files. So any other format would just be "in addition too" the general format.

**Comment by ketang** [comment]
> maybe we'll have to add `--tfvars-file` to our provision step?

Do they directly invoke a Terraform-specific provisioner?  If it's through an abstraction, then I have the same comment as above re TF-specific variables and arguments in provisioner-agnostic interfaces and code.

**Comment by kylecarbs** [comment]
This seems like something we should wait for customers to request before we implement any parsing logic. Closing for now.
