### ISSUE TITLE
error: configure http(s): listen tcp 127.0.0.1:3000: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by RockNHawk** [coder/coder#15957]
C:\Users\r>"C:\Program Files\Coder\bin\coder.exe" server
Coder v2.18.1+765d99c - Your Self-Hosted Remote Development Platform
failed to sync sloghuman: sync /dev/stderr: The handle is invalid.
Encountered an error running "coder server", see "coder server --help" for more information
error: configure http(s): listen tcp 127.0.0.1:3000: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

Application is alread run as administator:
<img width="860" alt="Image" src="https://github.com/user-attachments/assets/dbdbb7d5-8f7f-404b-ae78-b3d3d083588e" />

**Comment by dannykopping** [comment]
@RockNHawk I was unable to replicate this using the same build on Windows 10.

I found this on SO - have you tried any/all of these suggested fixes? https://stackoverflow.com/questions/10461257/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi

**Comment by RockNHawk** [comment]
I have similay issue with another program, I use this command fixed my issue

sc stop winnat
sc start winnat
pause

**Comment by RockNHawk** [comment]
@dannykopping  excuse me ,why I successfuly run on WSL, but I visit url show a blank page with error "ERR_EMPTY_RESPONSE"

# ON WSL Linux

export DOCKER_GROUP=$(getent group docker | cut -d: -f3)
docker run --rm -it \
 -p 4001:3000 \
  -e CODER_ACCESS_URL="https://coder.example.com" \
  -e CODER_PG_CONNECTION_URL="postgresql://root:xxx@192.168.3.118/coder?sslmode=disable" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $DOCKER_GROUP \
  ghcr.io/coder/coder:latest





x@PC:/mnt/c/Users/r$ docker run --rm -it  -p 4001:3000   -e CODER_ACCESS_URL="https://coder.example.com"   -e CODER_PG_CONNECTION_URL="postgresql://root:xxx@192.168.3.118/coder?sslmode=disable"   -v /var/run/docker.sock:/var/run/docker.sock   --group-add $DOCKER_GROUP   ghcr.io/coder/coder:latest
Coder v2.18.1+765d99c - Your Self-Hosted Remote Development Platform
Started HTTP listener at http://127.0.0.1:3000
WARN: The access URL  https://coder.example.com  could not be resolved, this may cause unexpected problems when creating workspaces. Generate a unique *.try.coder.app URL by not specifying an access URL.

╔═══════════════════════════════╗
║       View the Web UI:        ║
║   https://coder.example.com   ║
╚═══════════════════════════════╝

==> Logs will stream in below (press ctrl+c to gracefully exit):
2024-12-25 15:10:58.407 [info]  coderd.keyrotator: no valid keys detected, inserting new key  feature=workspace_apps_token
2024-12-25 15:10:58.412 [info]  coderd.keyrotator: inserted new key for feature  feature=workspace_apps_token
2024-12-25 15:10:58.412 [info]  coderd.keyrotator: no valid keys detected, inserting new key  feature=workspace_apps_api_key
2024-12-25 15:10:58.415 [info]  coderd.keyrotator: inserted new key for feature  feature=workspace_apps_api_key
2024-12-25 15:10:58.416 [info]  coderd.keyrotator: no valid keys detected, inserting new key  feature=oidc_convert
2024-12-25 15:10:58.419 [info]  coderd.keyrotator: inserted new key for feature  feature=oidc_convert
2024-12-25 15:10:58.419 [info]  coderd.keyrotator: no valid keys detected, inserting new key  feature=tailnet_resume
2024-12-25 15:10:58.422 [info]  coderd.keyrotator: inserted new key for feature  feature=tailnet_resume
2024-12-25 15:10:58.430 [info]  coderd.servertailnet: obtained tailnet API v2+ client
Notifications are currently disabled as there are no configured delivery methods. See https://coder.com/docs/admin/monitoring/notifications#delivery-methods for more details.
2024-12-25 15:10:58.463 [info]  provisionerd-716aa3b30da9-1: successfully connected to coderd
2024-12-25 15:10:58.464 [info]  provisionerd-716aa3b30da9-0: successfully connected to coderd
2024-12-25 15:10:58.657 [info]  dbpurge: purged old database entries  duration=203.142453ms
2024-12-25 15:10:58.683 [info]  provisionerd-716aa3b30da9-2: successfully connected to coderd
2024-12-25 15:10:59.790 [info]  provisionerd-716aa3b30da9-2: detected terraform version  installed_version=1.9.8  min_version=1.1.0  max_version=1.9.9
2024-12-25 15:10:59.794 [info]  provisionerd-716aa3b30da9-1: detected terraform version  installed_version=1.9.8  min_version=1.1.0  max_version=1.9.9
2024-12-25 15:11:00.089 [info]  provisionerd-716aa3b30da9-0: detected terraform version  installed_version=1.9.8  min_version=1.1.0  max_version=1.9.9

**Comment by dannykopping** [comment]
It's likely because of this:

> WARN: The access URL https://coder.example.com/ could not be resolved, this may cause unexpected problems when creating workspaces. Generate a unique *.try.coder.app URL by not specifying an access URL.

I'm going to close this issue because it seems you have fixed the original problem of binding to the appropriate port.

Please follow our documentation on how to set `CODER_ACCESS_URL`: https://coder.com/docs/admin/setup#access-url
If you leave this value blank, a value will be generated for you under the `try.coder.app` subdomain which will be accessible.

> Generate a unique *.try.coder.app URL by not specifying an access URL.

**Comment by RockNHawk** [comment]
> It's likely because of this:这可能是因为：
> 
> > WARN: The access URL https://coder.example.com/ could not be resolved, this may cause unexpected problems when creating workspaces. Generate a unique *.try.coder.app URL by not specifying an access URL.警告：无法访问 URL https://coder.example.com/ 无法解析，这可能会导致创建工作区时出现意外问题。通过不指定访问 URL 生成唯一的 *.try.coder.app URL。
> 
> I'm going to close this issue because it seems you have fixed the original problem of binding to the appropriate port.我将关闭此问题，因为您似乎已经解决了绑定到相应端口的原始问题。
> 
> Please follow our documentation on how to set `CODER_ACCESS_URL`: https://coder.com/docs/admin/setup#access-url请按照我们的文档了解如何设置 `CODER_ACCESS_URL`：https://coder.com/docs/admin/setup#access-url If you leave this value blank, a value will be generated for you under the `try.coder.app` subdomain which will be accessible.如果您将此值留空，则会在 `try.coder.app` 子域下为您生成一个可访问的值。
> 
> > Generate a unique *.try.coder.app URL by not specifying an access URL.通过不指定访问 URL 生成唯一的 *.try.coder.app URL。

I use http://127.0.0.1:4001 visit (mapped from  docker -p 4001:3000 )， not the CODER_ACCESS_URL

**Comment by dannykopping** [comment]
> export DOCKER_GROUP=$(getent group docker | cut -d: -f3)
> docker run --rm -it
> -p 4001:3000
> -e CODER_ACCESS_URL="https://coder.example.com"
> -e CODER_PG_CONNECTION_URL="postgresql://root:xxx@192.168.1.20/coder?sslmode=disable"
> -v /var/run/docker.sock:/var/run/docker.sock
> --group-add $DOCKER_GROUP
> ghcr.io/coder/coder:latest

You've defined `CODER_ACCESS_URL` above; remove it and things should work.

**Comment by RockNHawk** [comment]
> > export DOCKER_GROUP=$(getent group docker | cut -d: -f3)
> > docker run --rm -it
> > -p 4001:3000
> > -e CODER_ACCESS_URL="https://coder.example.com"
> > -e CODER_PG_CONNECTION_URL="postgresql://root:xxx@192.168.1.20/coder?sslmode=disable"
> > -v /var/run/docker.sock:/var/run/docker.sock
> > --group-add $DOCKER_GROUP
> > ghcr.io/coder/coder:latest
> 
> You've defined `CODER_ACCESS_URL` above; remove it and things should work.

I have already tried, but not work :=(
Thank you for reply.

**Comment by mtojek** [comment]
1. What is the location of your setup? Have you checked with telnet if `pit-1.try.coder.app` is reachable?
2. What do you see when you enter http://localhost:4001/ ?

Anyway, it does not seem to be a bug with Coder. Please feel free to reach out at https://discord.gg/coder if you need any more help.
