### ISSUE TITLE
Provisionerd should register the running provisioners when it connects

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#1605]
## What is your suggestion?

Right now we just hardcode the provisioner types that are registered to a provisionerd in the database, but you can start provisionerd with different sets.  In our unit tests, we start only echo, in production we start only terraform.  Instead of hardcoding, the provisionerd should send a registration message on connection that says which provisioners it is running.

## Why do you want this feature?

This can help us detect config errors where templates are created for provisioner types that aren't supported by the cluster, and can prevent jobs from being sent to provisionerds that cannot run them.

## Are there any workarounds to get this functionality today?

Always start all provisioners.

## Are you interested in submitting a PR for this?

yes

**Comment by kylecarbs** [comment]
@dwahler this might be smart to include as part of #3563 . Thoughts?

**Comment by bpmct** [comment]
going to close as part of #44
