### ISSUE TITLE
Subcommands in CLI don't report error (unknown command)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#1616]
## Information

- `coder --version`: Coder v0.5.11-devel+adb7d20c Fri May 20 04:07:23 UTC 2022 https://github.com/coder/coder/commit/adb7d20c16195463abf17f149b6ddc0f5b2cccdc

## Steps to Reproduce

1. Run `coder hello`
2. Observe error
3. Run `coder templates hello`
4. Observe no error

## Expected

Running `coder templates hello` should print `unknown command "hello" for "coder templates"`.

## Actual

No error and `--help` is automatically shown.

## Screenshot

<img width="478" alt="image" src="https://user-images.githubusercontent.com/147409/169494359-b942d5d0-d56c-485d-9d5a-30d8fc921e3f.png">

## Notes

I tried quickly looking into this and I can't figure out why it's behaving this way without spending more time on it. It works for the root command and the sub commands are not significantly different.

**Comment by kylecarbs** [comment]
https://github.com/spf13/cobra/issues/706

**Comment by mafredri** [comment]
Nice find @kylecarbs, so looks like the workaround we can make is to add:

```go
		Args: cobra.NoArgs,
		Run: func(*cobra.Command, []string) {},
```

To all our commands that have subcommands. We could probably automatically process the command tree to do this in runtime.
