### ISSUE TITLE
Add link to open any port in dashboard

### ISSUE THREAD

**Issue by presleyp** [coder/coder#1624]
Once #3753 is merged, users can navigate to ports running on their agent from the web browser 🌏 🔗 

For example, if I have a Python server running on port `3333` on my `main` agent in my `blue` workspace on `dev.coder.com`, I can access the app via: `https://bpmct--blue--main--3333.dev.coder.com/` OR `https://dev.coder.com/@bpmct/blue/apps/3333/`.

## Prior art

@code-asher created a port-forwarding dropdown in the workspaces that also auto-detects ports via agent: #1824. This was previously blocked by no backend routing (#3753).

## TODO

- There are some todos in #1824
- If an admin doesn't set up a wildcard domain, the port forwarding dropdown should not use a subdomain.
  - Coder Classic entirely disabled port forwarding via the dashboard when `coderd. devurlsHost ` was not set.
  - @bpmct suggestion: use a deployment-wide environment variable to enable subdomain apps. When disabled, use path URLs and link to docs to enable subdomains via the dropdown (many apps don't work by default as a path).

**Comment by kylecarbs** [comment]
@tjcran this can only be done when DevURLs are added. I think that needs more investigation before we just do it.

**Comment by kylecarbs** [comment]
@tjcran for that reason, I think we should take it off August roadmap.

**Comment by bpmct** [comment]
@deansheather @presleyp could you share the designs for dev URLs from the design sprint we did?

**Comment by BrunoQuaresma** [comment]
Done in #3812

**Comment by ammario** [comment]
@deansheather is taking another stab at this.

**Comment by kylecarbs** [comment]
This is now done!
