### ISSUE TITLE
Missing validation of workspace name

### ISSUE THREAD

**Issue by presleyp** [coder/coder#1639]
It appears that Terraform requires workspaces to contain only lowercase letters and numbers - no uppercase letters.

```Error: metadata.0.name a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')```

Current behavior: the create workspace page allows me to submit a workspace named PresleysWorkspace. Creation succeeds, but workspaces always fail.

Expected behavior: the create workspace form gives me a validation error and doesn't allow me to submit until I remove uppercase letters.

**Comment by tjcran** [comment]
@deansheather are you handling that in this ticket or do you have a different one?

**Comment by Emyrk** [comment]
@deansheather lmk the status of this or if you want me to pick it up.

**Comment by misskniss** [comment]
Leaving this open for Dean to validate. If may get fixed with a different ticket he is working now.

**Comment by deansheather** [comment]
We currently use the same validations we use for usernames, which is:
- between 1 and 32 characters in length
- `^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*`
