### ISSUE TITLE
Enhance: There are no definitions in the UI yet for key features

### ISSUE THREAD

**Issue by misskniss** [coder/coder#1640]
As a user, I would like descriptions for key features available in the UI. 

For features and functionality that are relevant to the view I am in that tell me: 

- What is it? 
- What should I know about it? / What does it do for me? 
- What is is required for? (i.e. you have to create a workspace using a template)
- Where do I make changes to it?

For instance:

- Templates 
- Workspaces
- Resource 
- Agent

These could be info icon pop overs, collapsible descriptions, etc.

**Comment by BrunoQuaresma** [comment]
@misskniss I can understand your point but I'm wondering what you have in your mind. Do you have a SaaS or UI reference that makes that pretty well? Maybe some copy changes in the empty states - since it is the first user-facing state - should help with that. Thoughts?
