### ISSUE TITLE
Unify all workspace information in `coder show`

### ISSUE THREAD

**Issue by ammario** [coder/coder#1646]
Right now, we have autostop information within `coder autostop show`, which is potentially confusing as a user has an expectation that all workspace data would be presented in a single view. Even if it's not confusing, it's cumbersome to run multiple commands to get the complete picture of a workspace.

See https://github.com/coder/coder/issues/1431#issuecomment-1126517684 for background.

**Comment by tjcran** [comment]
@vapurrmaid @johnstcn what are both of your thoughts on this one? I agree that it makes sense to remedy this one.

**Comment by ammario** [comment]
@johnstcn it seems hard to combine the existing resources view with the new schedule information. What do you think about just showing schedule information in `coder schedule show`?

<img width="649" alt="Screen Shot 2022-06-14 at 2 58 59 PM" src="https://user-images.githubusercontent.com/7416144/173677801-90263378-0a21-433b-941b-2ee2c34e6ba7.png">

**Comment by johnstcn** [comment]
@ammario Kyle was suggesting just dropping the fancy table altogether

**Comment by ketang** [comment]
But without shouting field labels right?

**Comment by johnstcn** [comment]
I suppose field labels only need to be shouty when they're a table header.

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/coder/pull/2402
