### ISSUE TITLE
Coder login command: That would be nice to remove extra slash in case url to server is ending with it (as it is done in V1), now I see 404 page

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1663]
## OS Information

- OS: Windows 10
- Browser (if applicable): 
- Architecture:
- `coder --version`:
Coder v0.5.10+ba818b3

## Steps to Reproduce

1. In terminal type:  coder login https://dev.coder.com/

## Expected

The following page is opened https://dev.coder.com/cli-auth 

When I do copy paste of server url, sometimes I paste it with "/" in the end. And this is leading to page https://dev.coder.com//cli-auth that is 404 and confuses user. In V1 CLI this case is handled (see attachments)

## Actual

Browser is opened on https://dev.coder.com//cli-auth 

 404 page is displayed

## Screenshot

V1 
![V1](https://user-images.githubusercontent.com/9592232/169834310-50c20176-a51b-4886-b864-08b41027efa1.PNG)

V2
![V2](https://user-images.githubusercontent.com/9592232/169837701-cb46c185-7879-473b-9167-818e3b7cdfdb.PNG)

## Notes

When I do copy paste url, sometimes I paste it with "/" in the end. And page https://dev.coder.com//cli-auth that is 404 is opened. In V1 CLI this case is handled (see in attachments)

**Comment by ketang** [comment]
This is no longer a problem.
