### ISSUE TITLE
chore: Remove dependabot

### ISSUE THREAD

**Issue by ammario** [coder/coder#1667]
cc @vapurrmaid 

The majority of our pull requests are from dependabot making it annoying to sift through Pull Requests. Also, unless dependabot is submitting a security fix, an upgrade may just break the code (see Minimum Version Selection).

**Comment by kylecarbs** [comment]
I removed labels from dependabot here: #2110. This should help make it less visually spammy.

I agree with Ketan that dependabot is useful for vulnerabilities. This is a won't fix for now!
