### ISSUE TITLE
CLI: getting "Validation failed name: username" error in cli in case workspace or template name does not follow allowed pattern

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1673]
## OS Information

- OS: Windows 10
- `coder --version`:
Coder v0.5.10+ba818b3 Wed May 18 00:07:20 UTC 2022
https://github.com/coder/coder/commit/ba818b3a10aa364073c90a217631dd1d17c32393

## Steps to Reproduce

1. Init any template
2. Run "coder template create **wrong-name_** -d "[path to template]"
3. Set service account key
4. Confirm create? (yes/no) yes

## Expected

Any error message that template name has a wrong format is displayed

## Actual

status code 400: Validation failed
        name: username

The same  for a new worskpace created with CLI.

## What is your suggestion?

Currently if Workspace Name or Template Name does not match names rules: "Name must start with a-Z or 0-9 and can contain a-Z, 0-9 or -."
in CLI the resulting error is:

status code 400: Validation failed
        **name: username**

That is confusing since this is not username that causes the error, but template name or workspace name in case workspace was created. 

## Screenshot
Template error

![image](https://user-images.githubusercontent.com/9592232/169867486-8b628b68-d953-48e5-8481-b8d2141dda3f.png)

Workspace error

![image](https://user-images.githubusercontent.com/9592232/169868497-b57b8cab-c6c3-4f3f-95ec-276c4d713d0c.png)

**Comment by mafredri** [comment]
This issue will be fixed by #3390, once merged, the output will look like this:

```
> Confirm create? (yes/no) Validation failed.
- name: Validation failed for tag "template_name" with value: "wrong-name_"
Run 'coder templates create --help' for usage.
```
