### ISSUE TITLE
Change Timeline Status from workspace status to job status

### ISSUE THREAD

**Issue by presleyp** [coder/coder#1677]
Currently, the Timeline has a Status column that shows the workspace status, such as "Running" or "Stopping"

This is redundant with the status bar for the current build, and confusing for past builds (how is it still "Running"?)

Desired: show the `workspace.latest_build.job.status` in this column instead of the derived `workspaceStatus`. The desired value will show, for example, `Succeeded` instead of `Running`, which makes more sense.

**Comment by BrunoQuaresma** [comment]
I remember we had a conversation about this and I remember we decided to make it on Enterprise but looks like the status is kinda confusing and I'm wondering if we should do this for Community MVP by making the status "calculation" in the BE. Thoughts?

**Comment by presleyp** [comment]
@BrunoQuaresma this ticket only needs a small frontend change: show `job.status` in the workspace Timeline. I think we should do that now, but wait on adding to what the backend sends the frontend.

**Comment by ketang** [comment]
Wanted to chime in that I continue to be slightly confused and then slightly more frustrated when a job shows "Running" even though it's not.

**Comment by tjcran** [comment]
> Ahh I see, should we rename the label to "Last job status" instead? cc.: @tjcran @misskniss

@BrunoQuaresma yes!
