### ISSUE TITLE
Username with uppercase letters causes workspace starts to fail

### ISSUE THREAD

**Issue by oxy** [coder/coder#1689]
## Steps to Reproduce

1. Set username to something starting with an uppercase letter (eg. Oxy, Lucy)
2. Create a workspace
3. Start the workspace

## Expected

Workspace creates and starts successfully.

## Actual

Starting workspace fails with a Terraform error.

## Screenshot

![Workspace logs](https://user-images.githubusercontent.com/19502779/169888804-a039fb21-67be-4efa-a3aa-1e59c4958d74.png)

## Notes

Might need more validation than already exists? The frontend already does not let me set `Oxy@` as a username (with a rather cryptic error:)
![Screenshot from 2022-05-23 16-55-00](https://user-images.githubusercontent.com/19502779/169904635-8063880a-6d28-45b1-836c-cce8ce82bc48.png)

I might try looking at fixing this later this week!

**Comment by ammario** [comment]
This is an issue with certain templates and not Coder. We could put stricture rules around usernames, but we can never solve this categorically.
