### ISSUE TITLE
 Variables (var.service_account, var.zone) are in CLI create templates and create workspace output among instructions, displayed not formatted, looks like debug data

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1703]
## OS Information

- OS: Windows
- Architecture:
- `coder --version`:
Coder v0.0.0-devel+9b70a9b Tue May 24 00:04:38 UTC 2022
https://github.com/coder/coder/commit/9b70a9b2eb6a8ab5b8e5e9686733623794dd68b8

## Steps to Reproduce
Create template steps

1. Launch terminal
2. Run coder login <server url>
3.  Init templates if not yet
4.  Run: coder templates create [template name] -d [template directory]

Create workspace steps
1. Run coder create --template="[template name]" [workspace-name]

## Expected
If variable is intended to be displayed - it should be better formated as now it looks like some unexpected debug data.

## Actual

Create template:
**var.service_account** is displayed after " This template has required variables! They are scoped to
  the template, and not viewable after being set." 

![image](https://user-images.githubusercontent.com/9592232/169972348-15df5f65-0f62-40c0-8976-5cf99ede7102.png)

Create workspace:
var.zone is displayed after  "This template has customizable parameters. Values can be
  changed after create, but may have unintended side effects
  (like data loss)." 
![image](https://user-images.githubusercontent.com/9592232/169973580-c8177206-40aa-49ae-b885-f2450784ac3d.png)

**Comment by bpmct** [comment]
These variables no longer exist as Coder relies on `gcloud` for auth
