### ISSUE TITLE
Adding a new variable to terraform template breaks `coder templates update`

### ISSUE THREAD

**Issue by mafredri** [coder/coder#1751]
## Steps to Reproduce

1. Run `coder template create -d examples/do-droplet-linux` or another example (see #1749)
2. Add variable (see below) to `main.tf`
3. Run `coder template update do-droplet-linux -d examples/do-droplet-linux`
4. Observe error (see below)

```
variable "step3_random_var" {
  type        = string
  description = "Hello"
}
```

## Expected

Prompt input for the new variable (if marked sensitive), otherwise just work™️.

## Actual

Error:

```
❯ coder template update do-droplet-linux -d ~/src/coder/examples/do-droplet-linux
> Upload "~/src/coder/examples/do-droplet-linux"? (yes/no)
terraform (info):
terraform (info):
terraform (info):
job failed
Run 'coder templates update --help' for usage.
```

**Comment by tjcran** [comment]
Closing this one as #1886 covers this and more.
