### ISSUE TITLE
UX: When I create a template on the CLI, I'd like it to be usable in the dashboard without refreshing

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1753]
## What is your suggestion?

:wave: Hi, it's Grey here, a fellow Coder coder. Whenever I develop (using `scripts/develop`), I ultimately
run through the flow of initializing a template and creating a workspace from it. I had the dashboard open
and noticed that because we don't poll or watch or really do anything to keep data up to date, that when I
create a template from the CLI, I cannot create a workspace in the dashboard until I refresh or navigate away from
and back to certain pages.

Instead the experiences goes like:

- CTA to create a workspace
- Can't create a workspace because no templates

I'd love it if the system became aware that I now have a template and allow me to perform these actions.

## Why do you want this feature?

It's a nice user experience, but shouldn't be considered as higher than "nice-to-have".

## Are there any workarounds to get this functionality today?

Simply refresh or perform some navigations

## Are you interested in submitting a PR for this?

Yes, but only post-mvp.

**Comment by sharkymark** [comment]
@f0ssel @kylecarbs If this is the one where templates index view doesn't auto-refresh, I think it should be done.

I looks jank that the workspaces index view auto-refreshes.
