### ISSUE TITLE
Semantics of username being applied to usernames and workspace names

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1756]
## Developer Story

We have a custom username validator (that we register on Go Validator) called `username`:

https://github.com/coder/coder/blob/527f1f3bc3ddebc28e733b35e5eb8af9c21b2aae/coderd/httpapi/httpapi.go#L34

It's being applied to both usernames:

https://github.com/coder/coder/blob/a3556b12dab3fd1e4d8f306f8c7ca57bdbc7b2a9/codersdk/users.go#L44

and workspace names:

https://github.com/coder/coder/blob/c7ca86d3742a0c0d685cf6502272132a7c6dc555/codersdk/organizations.go#L69

These semantics don't overlap cleanly - is a workspace name a username ?

It may be the case that workspace names and usernames have the same validation under-the-hood, but the questions remain:

- should `username` be generalized then (renamed)
- should we create a new validation for workspace name (even though it's the same)

---

S/o to @oxy for helping to identify this :tada: !

**Comment by bpmct** [comment]
Gonna close for now, but this is related to this use case #3321
