### ISSUE TITLE
fix: autostop: set upper bound on workspace TTL

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1758]
# What

Enforce an initial upper bound of 1 week on workspace TTL.

# Why

It's easier to change an upper bound than later it is to add one.
Additionally, well-defined upper bounds enable certain functionality (see: https://github.com/coder/coder/pull/1701#issuecomment-1137611919)

**Comment by nadzeyav** [comment]
Verified in [Coder v0.0.0-devel+b4f5920](https://github.com/coder/coder/commit/b4f5920df5d2bcea441d6f7572dd40df447dbadc)
on UI and with CLI: cannot set TTL value to more then 168h
