### ISSUE TITLE
On new deployments, prompt user for username and password on the frontend

### ISSUE THREAD

**Issue by bpmct** [coder/coder#1763]
## Problem Summary

When you install Coder for the first time, users must install & use the CLI to set up their user account with the following command `coder login <url>`. If they visit the web dashboard directly, they will be faced with a login screen and no way to set up their account.

If you are an admin you need an account to get started with (user #1). We need something similar to a "Welcome to coder, set up your first account" when you first deploy. This is only for the admin.

## Are there any workarounds to get this functionality today?

Running `coder login [url]` on the CLI, then using the terminal

## Definition of Done

For a complete frontend experience, Coder can prompt the admin when they first visit the access URL to set the first user's email, username, and password, just as they would for `coder login`

### Notes

The API for this is available now. 
1. Design and build the registration page. 
2. Figure out if you need to show the registration page and show it.
This issue may need to be broken up into those 2 pieces above.

**Comment by misskniss** [comment]
@presleyp lets split out, solve the confusion piece first and put the additional ticket in the ready column. Reference those here before closing this.

**Comment by bpmct** [comment]
Here's what the signup flow looks like from the CLI @presleyp: https://asciinema.org/a/cy8QVTPwazDAV6cxcV6DF1Qnj

**Comment by presleyp** [comment]
Replaced by #3223 and #3225

**Comment by bpmct** [comment]
@presleyp can we "closed as not planned" as the work has not been completed yet?
