### ISSUE TITLE
Update embedded terraform to version 1.2.1

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1777]
## What is your suggestion?

Update Terraform to 1.2.1 from 1.1.9. We currently default to version 1.1.9 if no existing `terraform` binary is found.

## Why do you want this feature?

Keep up-to-date with upstream Terraform versions

## Are there any workarounds to get this functionality today?

Manually install the desired terraform version.

## Are you interested in submitting a PR for this?

Yes

**Comment by bpmct** [comment]
@johnstcn is this still relevant?

**Comment by johnstcn** [comment]
@bpmct Yep!
