### ISSUE TITLE
Add user password reset functionality to CLI similar to the one that is on UI

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1782]
## What is your suggestion?
That would be nice for Admin to reset own and users passwords with CLI, similar functionality as on UI now. 
Currently there is a reset-password command available, but it does a different thing (resets password directly in database for admin and is not working in dev mode)

## Are there any workarounds to get this functionality today?

Reset password on UI.

**Comment by f0ssel** [comment]
You can now reset user's passwords as an admin:
![image](https://user-images.githubusercontent.com/19379394/181805916-9a9a3a50-ed9b-4198-b1a1-e20786879fef.png)

Users can also now reset their own passwords in the Settings -> Security page:
![image](https://user-images.githubusercontent.com/19379394/181806129-e41d3d36-eada-4388-9d99-deecf45d87b5.png)

**Comment by kylecarbs** [comment]
I don't know what this means. Closing for now.
