### ISSUE TITLE
If you update 'time until shutdown' in a running workspace, the workspace UI has the old value

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1783]
In https://github.com/coder/coder/pull/1778 we added support for setting a deadline on a single workspace build. In that implementation, the deadline can only increase monotonically. Changes to workspace TTL do not affect the deadline of an active workspace build.

> So what will be the behavior when the user changes the TTL on a running workspace? Will you add functionality to the CLI so we also update the deadline to be closer to the new TTL?

_Originally posted by @deansheather in https://github.com/coder/coder/pull/1778#pullrequestreview-986196037_ (paraphrased)

Seems like this would be useful behaviour, but there are some ins and outs to this we need to think through:

- If the workspace is not running, there is nothing to do here.
- If the workspace is running and the build does not have a deadline set, we would need to set the deadline. Users would need to be warned that this would affect running builds of their workspace.
  - Time should be measured from the workspace start time.
  - In the client interfaces (UI/CLI), show a message "This operation will cause the workspace to shut down at HH:MM".
- If the workspace is running and the build has a deadline set and the new deadline based on the TTL would cause the workspace to stop (i.e. new deadline would be at or before now), the user should DEFINITELY be warned of this.
  - Time should be measured from the workspace start time.
  - In the client interfaces (UI/CLI), show a message "This operation will cause the workspace to shut down immediately".
- If the workspace is running and the build has a deadline set and the new deadline based on the TTL would cause the user to hit the 30-minute notifcation, that's probably fine.
- (New issue): Make applying the updated deadline *optional* (i.e. prompt the user)

## Acceptance Criteria:

1) Given a user has a workspace with no deadline/TTL set and the workspace is not running
  When the user updates the workspace TTL
  Then: the TTL is updated

2) Given a user has a workspace with a deadline set and the workspace is running
  When the user updates the workspace TTL such that the updated deadline would affect a running workspace 
  Then: the user is notified about the effect of the change (workspace will be stopped at X time) and be prompted to confirm.

3) Given a user has a workspace with a deadline set and the workspace is running
  When: the user updates the workspace TTL such at the updated deadline would cause the running workspace to be stopped
  Then: the user is notified about the effect of the change (workspace will be stopped immediately) and be prompted to confirm.

## Implementation Notes:

- WorkspaceScheduleForm
  - Pass in workspace to WorkspaceScheduleFormValues
  - Add function to (workspace, startTime) -> use dayJS to check next schedule
  - Add a warning message to the `ttl` TextField
  - Use `Language` component of WorkspaceSchedule

**Comment by vapurrmaid** [comment]
This got duplicated as a bug in #2055 , meaning it's tripping users up.

Here's @mtm20176 's comment:

## OS Information

- OS:
- Browser (if applicable): 
- Architecture:
- `coder --version`: 0.6.0

## Steps to Reproduce

1. Have `Time until shutdown` already configured e.g., 8 hours

2. The workspace is running

3. Change the `Time until shutdown` to 1 hour

4. The workspace UI says 7 hours remaining (the leftover part from the original 8 hours)

## Expected

Not quite sure, but something based on the new `Time until shutdown` - so maybe 1 hour in this example

## Actual

The shutdown remaining in workspace UI is based on the previous `Time until shutdown`

## Logs

## Screenshot

<img width="461" alt="image" src="https://user-images.githubusercontent.com/2022166/172027547-011094d7-ea65-490e-bb8a-34e377727555.png">

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/2022166/172027552-924bee2a-d11d-495a-911e-269e58441aeb.png">


## Notes

Nope

**Comment by vapurrmaid** [comment]
Here's @ketang 's comment from the dupe:

I poked at this to see how it behaved.  To start more from scratch:
1. create a workspace
2. set its shutdown time to 3 hours
3. start the workspace
4. when it is starting or has started, change the schedule to shut down after an hour
Result: the workspaces page still shows "SHUTDOWN: 3 hours after start."

Doing a hard page reload doesn't change anything; it still shows 3 hours.  *However*, if I hit the "Stop" button, then schedule card then shows "1 hour after start" 🤷🏾‍♂️

**Comment by vapurrmaid** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workspaces-V2-Hub-62019e46b7e29b0014a7f850/issues/coder/coder/1783?planning-poker) with ZenHub @johnstcn
