### ISSUE TITLE
Discussion about path patterns we should use for the frontend

### ISSUE THREAD

**Issue by deansheather** [coder/coder#1787]
Right now workspaces terminal is accessible at `/:username/:workspace_name/terminal` (if I'm not mistaken) and we want to add `/:username/:workspace_name/apps`.

We could instead use `/users/:username/workspaces/:workspace_name/{terminal,apps}` to be more like a REST API.

I prefer the more verbose way of writing it because otherwise we have to reserve usernames like `organizations` so we can have `/organizations/:org_id` and reserve workspace names like `preferences` so we can have `/:username/preferences` pages. Doing it more verbosely and having a dedicated path for pattern matched stuff avoids needing reserved names. I'm also down for shortening the verbosity i.e. `/u/:username/w/:workspace_name/terminal`

@kylecarbs @f0ssel @ketang @Emyrk @vapurrmaid

**Comment by kylecarbs** [comment]
What edge-cases do you foresee with using `@`? It seems pretty namespaced to workspaces from my perspective.

- Replit
- GitHub
- GitLab
- Vercel
- BuildKite

And others have pretty URLs that don't reflect their API but are very friendly to users. I don't think we need to reinvent the wheel here, and I'd rather just take the prior art.

**Comment by ketang** [comment]
The simplest, IMO least controversial option and the one least likely to lead to future problems is just prefixes like `'/u` and `/w`.  We can always do something at the top level if we see the need later, but it's harder to go from top level to one level down.

**Comment by ketang** [comment]
Depends on which status quo you mean.  Namespacing is widely used also, and it's more future proof and reversible.  I wonder how many of the companies that didn't do namespacing now regret it.  I've been there.  I don't want to be there again.  Two characters is a low low price, especially since it's only one more than the `@`.

**Comment by kylecarbs** [comment]
The status quo of accessing the primary namespaced object inside the product using a top-level routing pattern.

Could you provide some examples of co's that do the opposite? I'm sure they're out there, but I'm unaware of any developer tool ones that do it.

**Comment by ketang** [comment]
I'm not sure this is a developer tool specific thing.

The most prominent example that comes to mind is LinkedIn.

I suspect there are going to be differences depending on whether it's a SaaS product with a global namespace.

This detail isn't worth a lot of discussion.  Let's just go with `@`.

**Comment by vapurrmaid** [comment]
Meta question: should this issue have been a discussion instead?

**Comment by f0ssel** [comment]
> What edge-cases do you foresee with using `@`? It seems pretty namespaced to workspaces from my perspective.
> 
> * Replit
> * GitHub
> * GitLab
> * Vercel
> * BuildKite
> 
> And others have pretty URLs that don't reflect their API but are very friendly to users. I don't think we need to reinvent the wheel here, and I'd rather just take the prior art.

My issue with @ is that it doesn't cover the workspace name, so you would still need reserved workspace names. 



> If we want to do what's the lowest risk and least controversial, then we should use the status quo in the market of doing top-level routing as the companies listed. It's arguably more controversial to invent something and wait for feedback because we don't need to invent it.

The absolute most safe and boring answer is `/users/:username/workspaces/:workspace_name/{terminal,apps}`. The other platforms do it for other value reasons, and again I think comparing us to saas here makes less sense. Let's be real, no one is paying money to a kid on discord for a leet username on their company's Coder deployment.

**Comment by kylecarbs** [comment]
What do you mean it doesn't cover the workspace name? We'd do `/@kylecarbs/<workspace-name>`

**Comment by f0ssel** [comment]
The proposal also included `/@kylecarbs/workspace-name/app-name` which means if we wanted anything under the workspace key we would have to reserve certain words. It's easier than usernames (since no oauth envolved) but still not a noop. What would you like to do in that case?

**Comment by kylecarbs** [comment]
I think `/@kylecarbs/workspace-name/apps/app-name` makes sense for the cases you brought up!

**Comment by f0ssel** [comment]
What about user settings? ("@kyle/settings") Is "settings" going to be a reserved keyword we don't allow workspaces to be named? 

The answer that matters here is "do we really need a scheme that forces us to reserve keywords" and haven't addressed that fully here yet.

**Comment by kylecarbs** [comment]
That question shouldn't be answered with an invention by us, which is why I'm stating that following GitHub, GitLab, Vercel, and others is a safer bet.

**Comment by f0ssel** [comment]
Will we reserve words for:
- users - @ symbol gets us around this
- workspaces - what do we do with `@kyle/settings`? Is `settings` a reserved word now you can't use for workspace names or not? These are not product questions, these are engineering questions. 
- If we are good with apps why not just be safe with the other resources? What makes users and workspaces special? 

Give me a list of reserved words for the resources you wish, or give me a path that doesn't need them. I don't want to discuss "other products" at all until this engineering question is answered.

**Comment by f0ssel** [comment]
Remember that the PR will include fixing existing workspaces to become invalid names and handle that migration process if we ever want a reserved key in the future.

**Comment by kylecarbs** [comment]
Well... we could always just swap to use `/workspaces/<user>/<workspace>`, right?

**Comment by kylecarbs** [comment]
Seems like we've landed on this. Closing for now!
