### ISSUE TITLE
UX: Replace native time picker with MUI Time Picker

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1791]
## User Story 👥 

Our Workspace Schedule form uses a native `<input type="time">` picker. Unfortunately, it's hard to make this appearance sit well on all browsers in our dark theme, and folx might not be able to see the dark clock against the dark theme.

- More on `<input type="time">` here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#appearance

![time-picker-native](https://user-images.githubusercontent.com/11184711/170541904-e06886ad-bae0-4f46-a110-6d23d0514d3e.PNG)

Instead of this less-than-stellar design, I'd love to see a TimePicker like I see in modern mobile applications.

https://material-ui-pickers.dev/demo/timepicker#time-picker

![1](https://user-images.githubusercontent.com/11184711/170542570-64b1207b-393b-4798-ae10-c00c1c165264.PNG)
![2](https://user-images.githubusercontent.com/11184711/170542571-5688965f-df34-4ae6-8603-d315bd5ab660.PNG)

## Note

The underlying data representation should not change, we use `HH:mm` (24 hour format).

**Comment by Kira-Pilot** [comment]
A downside here is that [I don't think that MUI Time Picker modal has keyboard support](https://github.com/mui/material-ui/issues/4787). Maybe we could tweak it so it behaves, or disable the modal itself on keyboard only.

Is it a pain to just change the color of the little clock icon in the existing timepicker? SO claims we can do it with a filter, but I haven't tried it or tested it cross browser.

**Comment by tjcran** [comment]
> A downside here is that [I don't think that MUI Time Picker modal has keyboard support](https://github.com/mui/material-ui/issues/4787). Maybe we could tweak it so it behaves, or disable the modal itself on keyboard only.
> 
> Is it a pain to just change the color of the little clock icon in the existing timepicker? SO claims we can do it with a filter, but I haven't tried it or tested it cross browser.

@vapurrmaid tells me the color of the clock can't be changed, and it's impossible to see on the dark mode background.. I'm open to other alternatives, though. whatever makes it easiest for users to understand how to change the time using an actual time picker.

**Comment by Kira-Pilot** [comment]
I think we can change it, at least on Chrome. I'll do some testing on other browsers. Maybe we can chat at grooming and see if there were other concerns besides color.
![Screen Shot 2022-05-31 at 10 53 35 AM](https://user-images.githubusercontent.com/19142439/171203896-e0245a2a-8f01-45d9-b4c7-03e5d4a37c58.png)

**Comment by vapurrmaid** [comment]
> I think we can change it, at least on Chrome. I'll do some testing on other browsers. Maybe we can chat at grooming and see if there were other concerns besides color. ![Screen Shot 2022-05-31 at 10 53 35 AM](https://user-images.githubusercontent.com/19142439/171203896-e0245a2a-8f01-45d9-b4c7-03e5d4a37c58.png)

Nice, I was unsuccessful in my first past in understanding how to change if. I think we should move forward with simply just that and scrap moving forward with the time picker.

**Comment by vapurrmaid** [comment]
> @vapurrmaid tells me the color of the clock can't be changed

Turns out I just didn't figure out how in my pass, but @Kira-Pilot sure as heck did (:tada:).
