### ISSUE TITLE
Workspace ID should be Workspace Name on build log page

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#1801]
I think it would be more helpful if we showed the workspace name instead of ID (keep link the same). 
![image](https://user-images.githubusercontent.com/19379394/170559739-89e2e03e-a255-45d8-9c01-9286cb8dbe26.png)

**Comment by ammario** [comment]
A big problem in v1 for both latency and DB load was recursive queries. Could embedding the workspace or workspace name in the build log let us achieve the issue without the aforementioned problems?

**Comment by kylecarbs** [comment]
Recursive queries don't exist anymore, because we bulk requests by ID. eg. `GetWorkspaceBuildsByWorkspaceIDs`

**Comment by ammario** [comment]
I think you're talking about loading lists one by one.

I'm talking about when loading a page requires a query to further detail a past query.

**Comment by ammario** [comment]
![image](https://user-images.githubusercontent.com/7416144/171048261-70355504-1c9f-411f-833e-945cbf0c1fe4.png)

**Comment by ketang** [comment]
How often are we going to be querying for a workspace and *don't* want the workspace name?  It seems infrequent enough that we shouldn't make what I expect will be a relatively common case (wanting both) to require two steps.

Also this doesn't have issues with arbitrary follow-up queries, so I don't think we need to be paranoid about performance impact.  This adds exactly one primary key database query per API call.

**Comment by f0ssel** [comment]
There's already a `workspace` middleware since it's a workspace ID route, so there's already a DB hit and no addition for adding this data to the API schema. I love questions like this though.

**Comment by spikecurtis** [comment]
One interesting question is whether we should modify the `codersdk.WorkspaceBuild` type to include the workspace name, affecting all endpoints that use it, or return some new type just for this endpoint.

**Comment by spikecurtis** [comment]
Turns out literally everywhere we currently use that type we already have a workspace object in hand, so I'm going with that

**Comment by misskniss** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workspaces-V2-Hub-62019e46b7e29b0014a7f850/issues/coder/coder/1801?planning-poker) with ZenHub @f0ssel

**Comment by nadzeyav** [comment]
Verified workspace name displayed instead of ID on build log page.
[Coder v0.0.0-devel+51c420c](https://github.com/coder/coder/commit/51c420c90ad215dc3e0a6634d7cfc0b0fb750203)

![image](https://user-images.githubusercontent.com/9592232/171603440-5f3c6b0b-7096-4fec-a888-3cbc1df09356.png)
