### ISSUE TITLE
UX: clarify that create workspace won't copy current directory into workspace

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#1816]
## Problem

One user wasn't sure what would happen when creating a workspace from a current directory. They didn't know if the current directory contents would be copied into the workspace.

## Suggestion

Clarify the wording around create workspace. Print line explaining that it wouldn't copy current dir into workspace.

**Comment by f0ssel** [comment]
Do we still think this is something we should do? I'm not convinced this will be the expectation for all new users.

**Comment by ketang** [comment]
If it causes confusion, someone will tell us.
