### ISSUE TITLE
UI: Confirmation Dialogs and Snackbar Notifs have an alarming red

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1832]
## 👥 

![suspend](https://user-images.githubusercontent.com/11184711/170712447-d98cf47d-7756-4b3c-be74-6c696e727293.png)

- The red is _too red_
- The cancel action and main action are both _too red_ especially against an already _too red_ background
- The button spacing and border feels _tacky_

![very-red](https://user-images.githubusercontent.com/11184711/170713053-c9909141-10a4-4772-b68e-4225bc24ecff.png)

consider spacing the buttons apart so users don't click the wrong one, e.g:
![Screen Shot 2022-05-27 at 12 44 54 PM](https://user-images.githubusercontent.com/19142439/170743107-f74d43aa-f4b8-4d90-a75b-cccea1b7802b.png)

**Comment by AbhineetJain** [comment]
@vapurrmaid I am planning to pick this up. Do we have the requirements finalized for this, or should I just try to make it nicer?

**Comment by BrunoQuaresma** [comment]
@AbhineetJain I have some ideas, I will add a Figma mock here in a few minutes.

**Comment by AbhineetJain** [comment]
Thank you, @BrunoQuaresma! 🙌

**Comment by BrunoQuaresma** [comment]
I think we could do:
<img width="1030" alt="Screen Shot 2022-06-01 at 12 31 40" src="https://user-images.githubusercontent.com/3165839/171442708-ca5b0f66-c90a-417e-989b-ddb124473b5e.png">

Figma link: https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-v2-Design?node-id=297%3A535

Confirmation:
- We can keep the same size of things
- The background is theme.palette.background.paper
- It has a border theme.palette.divider
- The text is using the secondary color, theme.palette.text.secondary
- The radius is 2px, theme.shape.radius I guess...
- We can use the regular button for secondary action - Cancel, and a red one for the main action. We can use the current red we are using.

Snackbar:
- We can keep the same size of things
- The background is theme.palette.background.paper
- It has a border theme.palette.divider
- The radius is 2px, theme.shape.radius I guess...
- The text is using the secondary color, theme.palette.text.secondary
- We can use on the left border the current red we have.

Please, let me know if you have any questions or need me to give you permission to Figma.

**Comment by AbhineetJain** [comment]
@BrunoQuaresma These look great, thank you so much. Let me try implementing this and see if I can try a few other things around for design.
