### ISSUE TITLE
Refactor Deadline field of codersdk.WorkspaceBuild to *time.Time

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1834]
This was implemented as a `time.Time` but would be nicer for the UI to consume as a `*time.Time`.

> 🙈 I should probably have made that type a `*time.Time` for you -- we can refactor that in a follow up PR.

_Originally posted by @johnstcn in https://github.com/coder/coder/pull/1825#discussion_r883360485_

**Comment by kylecarbs** [comment]
This could use #3552

**Comment by mafredri** [comment]
Good callout @kylecarbs, I can grab this one too.

**Comment by mafredri** [comment]
Actually, it looks like this one and #2015 are duplicates, I'm closing this in favor of #2015 (which has a bit more context).
