### ISSUE TITLE
Add a way to populate template description in CLI to allow display on UI templates screen

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1839]
### Problem
There is a template description field supported via API.
but there is no way for how to populate it (or it is not obvious, no CLI ~or UI~ is available).

### Definition of Done
The property is added to API and mentioned that should be avaialble to be set through CLI, but there is no such option

![image](https://user-images.githubusercontent.com/9592232/170721959-6fe5688b-b026-469d-af6e-7665212b247a.png)

Implementation Notes: 
This is read only in the frontend.

**Comment by misskniss** [comment]
Added @oxy  to assist in validation that the template descriptions shows up in the UI

**Comment by misskniss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workspaces-V2-Hub-62019e46b7e29b0014a7f850/issues/coder/coder/1839?planning-poker) with ZenHub @oxy @coadler

**Comment by johnstcn** [comment]
#2159 covers the CLI part of this

**Comment by bpmct** [comment]
How does this compare to the description parsed in the README and that displays in `coder templates init`? 

IMO, I prefer using markdown for metadata like this, or perhaps #2987 down the road..

**Comment by oxy** [comment]
![image](https://user-images.githubusercontent.com/19502779/181578633-af7e6186-4106-42c4-95ef-351a7b8631a6.png)
Template descriptions [when set] do already show!

Copy was edited in #2247 to remove the "no description" text: https://github.com/coder/coder/commit/eab5c15062f25f3079a0a2312df4b26cafd2baf3#diff-943704768957dc526907e01c9a3798d7804c3c560704712c2ae8d05dd90a953b

Can we close the issue as done?

**Comment by bpmct** [comment]
@oxy following up on this question

> How does this compare to the description parsed in the README and that displays in coder templates init?
> 
> IMO, I prefer using markdown for metadata like this, or perhaps https://github.com/coder/coder/issues/2987 down the road..

**Comment by oxy** [comment]
The `coder templates init` hint [eg. Develop in Docker...] shows up in yaml front matter for `README.md` in the template itself, but the `description` field returned by the server is a metadata tag that the server stores separately [and is initialized separately by the CLI] (see #2159)

I'm not sure if you're suggesting that we use the front matter for the description; and if so, if we should make the CLI responsible for parsing front matter and then sending that as the description tag, or if we want to approach this another way

**Comment by bpmct** [comment]
I'm personally confused that there are 2 different descriptions for a template, but I think you're right this can be considered done 👍🏼

**Comment by ketang** [comment]
> I'm personally confused that there are 2 different descriptions for a template

@bpmct this is worth a little effort to try to simplify
