### ISSUE TITLE
Bug: User with "Auditor" role can't log in

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#1843]
## OS Information

- OS: Windows 10
- Browser (if applicable): Chrome
- Architecture:
- `coder --version`: Coder v0.6.0

## Steps to Reproduce

1. Log in as Admin
2. Create a new user
3. Set Auditor role to the new user
4. Try to log in as the new user

## Expected

User is logged in

## Actual

Noting happens after clicking on Sigh in button, the user is not logged in
{"message":"forbidden"}

Also there's no message that could tell the user why they are not able to log in

## Screenshot

![image](https://user-images.githubusercontent.com/35501151/170727689-03a8288e-2065-4477-a2ce-21908534f68d.png)

**Comment by tjcran** [comment]
The problem on this one is that "member" privileges are needed for sign-in and we don't support a user being only an Auditor at the moment.  Once #1593 is complete it will remove the "member" checkbox and all users will have member by default, including auditors. , this will no longer be an issue. Closing this one.
