### ISSUE TITLE
Bug: Users: Admin is able to remove admin role from themselves via just click and get locked as well as simply remove all admins

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1847]
## OS Information

- OS: Windows
- Browser (if applicable): Chrome
- Architecture:
- `coder --version`:
[Coder v0.0.0-devel+1361c13](https://github.com/coder/coder/commit/1361c1357a6d538e0fd41ead2bbda44edaf59219)

## Steps to Reproduce

1. Login as Admin user
2.  Go to users
3. Expand Admin user roles dropdown and uncheck Member role and then Admin role

## Expected

At least any notification about Are you sure, but maybe better will be not allow to unassign admins roles from themselves.

## Actual

Admin user has no roles assigne at all, cannot fix this issue in current session and after is logged off even no error message is displayed at login

## Screenshot

https://user-images.githubusercontent.com/9592232/170735217-3af7aaad-fd0f-492d-a38b-71a6bc0982d0.mp4

**Comment by misskniss** [comment]
Check that the toast for the error pops up correctly on the FE when this is fixed @Emyrk .

**Comment by f0ssel** [comment]
I think blocking self-role changing entirely is a good first step and if a case comes up where we need to support something we didn't think about we can add it later.
