### ISSUE TITLE
Configure interface member sorting

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1853]
## Developer Story 👥 

At FE V, we decided that we want our TS interfaces to be easier to read at a glance. For this reason, we'll implement https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-ordering.md on `interface`s with `alphabetical` ordering.

**Comment by kylecarbs** [comment]
It seems like something that we can backburner for now.

This is just my impartial take, so if anyone disagrees I'm happy to open again!
