### ISSUE TITLE
cli: bump: auto-detect workspace name if inside workspace

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1857]
Auto-detect workspace name _somehow_ from inside a workspace -- possibly an environment variable?

>  I don't know if we have a way to determine the workspace name yet from inside the workspace, and last I checked we aren't automagically logged in... yet.

_Originally posted by @johnstcn in https://github.com/coder/coder/pull/1828#discussion_r883775704_

**Comment by ammario** [comment]
Should we consider inferring the workspace name in other commands too?

**Comment by ketang** [comment]
How often is someone going to use workspace specific commands from within a workspace?

**Comment by bpmct** [comment]
If I'm understanding this correctly, we can use environment variables for now

```hcl
resource "kubernetes_pod" "dev" {
  # ... other stuff
  env {
     name = "CODER_WORKSPACE_NAME"
     value = data.coder_workspace.me.name
  }
}
