### ISSUE TITLE
Use Terraform auth

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#1868]
## What is your suggestion?

Instead of having templates prompt users for secrets, we should use [Terraform auth](https://www.terraform.io/cli/auth).

## Why do you want this feature?

It will solve two issues reported by a user:
- "Never show secrets like AWS keys shown as text on a terminal screen. They should be masked."
- "It should have picked up my AWS profile in my shell environment but it didn't."

## Are there any workarounds to get this functionality today?

No, just use product as is.

## Are you interested in submitting a PR for this?

Maybe with some guidance.

**Comment by bpmct** [comment]
This is completed :)

**Comment by misskniss** [comment]
@bpmct is there a PR that points to this fix to attach here?

**Comment by bpmct** [comment]
Yep, there are few!

#2104 #2051 #2039
