### ISSUE TITLE
No default VPC for this user when selecting Linux EC2 template

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#1869]
## OS Information

- OS: macOS
- Browser (if applicable): n/a 
- Architecture: amd64
- `coder --version`: 0.6.0

## Steps to Reproduce

1. `coder templates init`
2. Select Linux EC2 on AWS
3.  `cd` and create workspace with template
4. see error

## Logs

```shell
No default VPC for this user
```

## Screenshot

https://www.loom.com/share/3aedc8a362ed4001a917450be82f6599?t=299

**Comment by bpmct** [comment]
Closing - templates are currently intended to be edited
