### ISSUE TITLE
UX: after workspace creation, tell user what to do

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#1870]
## What is your suggestion?

After workspace creation, print line to tell user what to do next:

“Congrats! You created your first workspace. Run coder ssh <workspace> and try out your new dev environment!”

## Why do you want this feature?

Less guesswork for user

## Are there any workarounds to get this functionality today?

N/A

## Are you interested in submitting a PR for this?

Sure!

**Comment by ketang** [comment]
It'd be cool if we could have an embedded terminal in the workspace page.

**Comment by BrunoQuaresma** [comment]
@ketang I REALLY like this idea!

**Comment by tjcran** [comment]
> It'd be cool if we could have an embedded terminal in the workspace page.

Is the idea that it would replace the new window that opens up? or would we still allow for that? There's an argument that it's more helpful to have it open into a separate window, ie the current behavior. 

Does it auto-connect? or do you have to click a button to start the connection? Is there a way to close the connection with a click other than just typing "exit" in terminal? How can you tell if the terminal is "in focus" for input? 

I'm not for or against the embedded terminal. I'm just posing some logical questions I can think of and am not sure if it drives any value. "wow" is nice, but would it _actually_ make the user experience better? If we can definitively say that it does, great!

**Comment by ketang** [comment]
Automatically have a terminal in the page.  Use a cursor or highlight border to show when it's in focus.  You can launch another terminal, and you can also pop out the in-page terminal to a new window.  Exiting the embedded terminal does nothing or results in a restart.

**Comment by tjcran** [comment]
Closing this one as it is unclear what we should improve. Making a new and separate issue for embedded terminal (tbd if we end up doing that)

**Comment by ketang** [comment]
I think that we're at least partly resolved here by having app icons appear.  There will be things to click.
