### ISSUE TITLE
UX: list Docker and recommend Docker in templates

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#1871]
The easiest way to get started with `coder` (without needing any keys, accounts) is using Docker. Therefore, we should list this as the first template and add "Recommended" to the title.

**Comment by misskniss** [comment]
We should have alignment on the Template examples before working on this one so we understand what the definition of done should be. What if Docker is not installed? what if you need to edit the docker host? etc.

**Comment by jsjoeio** [comment]
I would classify "Done" as: 
- Docker is listed first
- Docker has (Recommended) in title

> What if Docker is not installed

I think that's okay. We're just giving the users recommendations. I think they would know not to use this if they didn't have Docker. Similar example would be a project recommending a TypeScript template over a JS one. If a user doesn't have TS, they probably won't select it.

This is easily reversible too so if we find it makes it more confusing for users we can revertgam
