### ISSUE TITLE
Reprompt for new workspace parameters if terraform plan validation fails in the CLI

### ISSUE THREAD

**Issue by deansheather** [coder/coder#1873]
## What is your suggestion?

If the workspace plan step of creating a workspace with the CLI fails with a validation error from terraform, then we should reprompt users for the parameters that failed validation and try again.

## Why do you want this feature?

Means that users won't have to restart the workspace create command if their parameters don't pass validation

## Are there any workarounds to get this functionality today?

If validation fails, the command exits and they can try again instantly.

## Are you interested in submitting a PR for this?

Yes

**Comment by bpmct** [comment]
It's a good idea but gonna close for now to reduce items in the tracker.
