### ISSUE TITLE
Allowing sorting on Users UI 

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#1882]
## What is your suggestion?
I take it the sorting right now in 0.6.0 is hard coded to created_at or something like that.
I guess this can be done for the templates and workspaces UI list views as well.

## Why do you want this feature?
To find a user faster, versus using command+F

## Are there any workarounds to get this functionality today?
No 

## Are you interested in submitting a PR for this?
No

**Comment by tjcran** [comment]
related: #595
