### ISSUE TITLE
Add `coder ping [workspace]`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#1883]
## What is your suggestion?

Coder Classic includes a `coder workspace ping` feature. Here's an example: 

```sh
➜  ~ coder workspaces ping ben-stable
——: connected in 1496.95ms (proxied via [CODER_URL]) candidates=turn:[CODER_URL]
63.11ms: you ↔ [CODER_URL] ↔ workspace
31.60ms: you ↔ [CODER_URL] ↔ workspace
31.56ms: you ↔ [CODER_URL] ↔ workspace
```

## Why do you want this feature?

This adds a basic way to test if you have a fast and/or stable connection to your workspace. This is particularly important with Coder v2's distribution of infrastructure & network options.

## Are there any workarounds to get this functionality today?

I don't think so. `sshping` does not work with Coder's advanced tunnel

**Comment by ketang** [comment]
Perhaps there's a special argument that pings all of them, probably `*` though the user would have to escape it.

**Comment by ketang** [comment]
Do we have this in the V2 web UI yet?

**Comment by kylecarbs** [comment]
Nope, not yet.

**Comment by bpmct** [comment]
Gonna keep this alive for a bit longer, perhaps a candidate for September.

**Comment by bpmct** [comment]
Whoops, sorry I missed that Kyle. `coder speedtest <workspace>` now does a full speed test as well as ping :)
