### ISSUE TITLE
Add feedback widget

### ISSUE THREAD

**Issue by ketang** [coder/coder#1885]
## What is your suggestion?
Add a live feedback widget e.g. Intercom to the web UI.

## Why do you want this feature?
So users can provide direct feedback.

## Are there any workarounds to get this functionality today?
Emails, Discord, GitHub issues, etc., but none are in product.

## Are you interested in submitting a PR for this?
No.

### Implementation Ideas: 

This could start as something as simple as [a link to a prefilled github template](https://github.com/coder/coder/issues/new?assignees=&labels=bug+%3Abug%3A%2Cneeds+grooming+%3Arazor%3A&template=bug-report.md&title=Bug%3A+) OR a service for feedback collection 

See also the VSCode approach for feedback as suggested by @oxy 

## Implementation Decision (for first iteration):

- [ ] Add link text in footer to the right of the version with the copy: "Submit feedback"
<img width="500" alt="Add Feebback link here" src="https://user-images.githubusercontent.com/2394436/171728058-485acad2-5a5e-4260-a2c4-c616047a878d.png">

- [ ] this should open an minimalist template in Github in a new tab
- [ ] The version should auto populate into the form
- [ ] The users can enter whatever text they want from there

**Comment by ammario** [comment]
If this is done, it should be less intrusive than your run of the mill persistent chat icon in the bottom right corner. Dev Tools / Infrastructure products (maybe any that cater to the technical audience) do not have these kind of persistent widgets.

I speculate these reasons:
* Open Source Software prefers to accept feedback via the public tracker
* Developers have a lower tolerance for bloatware, UI noise, and threats to their privacy 

There's also the fact that a chat widget would be awkward in our industrial design.

A callout in the footer to file an issue with any feedback seems like a good way to solve the problem.
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/7416144/171047324-95cfddb1-754c-4079-974a-00e672c87fc8.png">

**Comment by ketang** [comment]
This seems like a great opportunity for using an A/B testing tool, not just so we can see what works best but also in order for us to be able to adjust the amount of feedback that we're getting at any given time.  If we're getting too much, we can show it less prominently less often to fewer users.  If we're getting too little, we do the opposite.

**Comment by ammario** [comment]
To be clear, you're OK with a link to file an issue?

**Comment by ketang** [comment]
I would like to try multiple things.  That can be the first.

**Comment by misskniss** [comment]
Made this an Epic since it is going to have multiple parts.

**Comment by ammario** [comment]
@misskniss what parts were you thinking? In my mind this was an a link to file a new GitHub issue somewhere in the product.

**Comment by tjcran** [comment]
Let's start really simple. It's an OSS product and feedback should go into Github. Let's provide an in-app "widget" that takes them right to a new issue form in Github. Per discussion with Ammar/Kyle live.

**Comment by tjcran** [comment]
One note: I think this should actually be wider than "reporting an issue" aka bugs. I think we should also be using this to gather feedback as well.

**Comment by Kira-Pilot** [comment]
@tjcran given that we're going with a link, what sort of language do you think we should use? Maybe something like 'Report an issue or share feedback"?

**Comment by tjcran** [comment]
@Kira-Pilot i think the or statement is fine since the whole thing is pretty small. Can you also clarify what is the square to the left of the words? 
![image](https://user-images.githubusercontent.com/7042112/174369771-0534f044-2424-4422-9bad-497c21ca96ed.png)

**Comment by Kira-Pilot** [comment]
@tjcran it's a little beetle (for bug). Did you grab that screenshot from chromatic/storybook?
![Screen Shot 2022-06-16 at 7 25 11 PM](https://user-images.githubusercontent.com/19142439/174375567-73f9a046-d576-4ae0-9118-300e14059d04.png)

If it's too cutesy or if its not showing up for you IRL, I can definitely take it out.

**Comment by tjcran** [comment]
@Kira-Pilot my screenshot was from dev.coder.com and it is not showing up there. I like it. but doesn't seem to be working.

**Comment by Kira-Pilot** [comment]
@tjcran as discussed, seems to be a windows issue. I will take out for now and adjust wording. In the future, we can add a small png if we feel like we need more pizzazz
