### ISSUE TITLE
Bug: Link "Create a workspace" on workspaces page leads to templates page

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1890]
## OS Information

- OS: Windows
- Browser (if applicable): Chrome
- Architecture:
- `coder --version`:
[Coder v0.0.0-devel+6850db2](https://github.com/coder/coder/commit/6850db2a47834d0c50142c9e1004195e53c96209)
## Steps to Reproduce

1. Login as a user with no workspaces
2. Open workspaces page
3. Click link "Create a workspace" in workspaces list section

## Expected
Create workspace form, or in case there should be a link to templates list - it should be renamed to something like: "Templates list"

## Actual
Templates page is opened

## Screenshot
This one opens <coder url>/templates

![image](https://user-images.githubusercontent.com/9592232/170982135-17b44536-8581-4eb1-8a24-626220d81d51.png)

**Comment by misskniss** [comment]
This is no longer an issue.
<img width="505" alt="Screen Shot 2022-06-01 at 12 40 20 AM" src="https://user-images.githubusercontent.com/2394436/171328989-4f5c5254-e99c-4934-8aa0-39c4fb09fb25.png">
