### ISSUE TITLE
Bug: Workspace Schedule: Days of week are not defaulted to settings defined at creation time via cli (new workspace)

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1901]
## OS Information

- OS: Windows
- Browser (if applicable): Chrome. Firefox
- Architecture:
- `coder --version`:
[Coder v0.0.0-devel+6850db2](https://github.com/coder/coder/commit/6850db2a47834d0c50142c9e1004195e53c96209)
## Steps to Reproduce

1. Create a workspace via cli: coder create [workspace-name] --template="[your template name]" --autostart-day-of-week **MON-TUE** --autostart-hour 5
2. Login to Web UI
3.  Open created workspace -> schedule is displayed as specified at creation time
4. Click Edit schedule

## Expected
Monday and Tuesday checkboxes are checked

## Actual

All week day checkboxes are unchecked

## Screenshot

https://user-images.githubusercontent.com/9592232/171023765-700fef8b-74ce-483c-afbb-bf6f606aa636.mp4

**Comment by vapurrmaid** [comment]
The issue here is that our FE conversion from the BE response only considers numbers for dow, not MON, TUES etc. We can either make the FE convertor understand both formats, or unify the formats in the BE.

cc @johnstcn for opinion.

I'm of the opinion that the FE should understand both formats.

**Comment by johnstcn** [comment]
According to the [manual page for crontab](https://linux.die.net/man/5/crontab) names can be used only for the `day-of-week` and `month` fields. Since we do not (yet) allow setting the `month` field, I think adding support for day-of-week names is reasonable here.
