### ISSUE TITLE
Replace Workspace ID with Workspace Name in URLs

### ISSUE THREAD

**Issue by ammario** [coder/coder#1905]
Workspace URLs are formatted as such right now:

`dev.coder.com/workspaces/fea18c8b-c9a1-4df8-a516-647ecb18d0cb`

Instead, we should format them as such:

`dev.coder.com/workspaces/coadler/colin`

for clarity.

**Comment by mtm20176** [comment]
@ammario 👍

**Comment by kylecarbs** [comment]
The terminal presently uses `/<username>/<workspace>`.

What do you think about that? I'm concerned with apps, URLs will become pretty long. eg. `/workspaces/kylecarbs/dev/apps/code-server`

**Comment by kylecarbs** [comment]
An alternative is `/@kylecarbs/dev/apps/code-server`, which I like!

**Comment by ammario** [comment]
👍 for "@" prefix.

**Comment by kylecarbs** [comment]
@ammario see https://github.com/coder/coder/issues/1787

**Comment by ketang** [comment]
A small consideration: if we have workspaces that are owned by multiple people, how would they be addressed?  I see a few options:
* only one *real* owner
* resolvable in the namespace under all owners' names
* have a canonical URL that is not namespaced and relies on the UUID

**Comment by kylecarbs** [comment]
I'm a fan of one owner.

GitHub adds redirects when repositories are transferred. If a new repo gets made under the same name, the redirect stops. Once we add workspace ownership transfers, we could take a similar approach.

**Comment by ketang** [comment]
I think the way to think about this depends on how heavy or frequent an event this is.  Is it going to be rare, like with GitHub?  Or is it going to be frequent, like with Google Docs?  I think it's going to be pretty rare, so making it less smooth and ambiguous is probably okay.

**Comment by ammario** [comment]
Multiple workspace owners is dangerous since security keys are either revealed or lose their 1:1 accountability. We've had at least one major customer state such a feature would have to be disabled for them to adopt our product.

**Comment by ketang** [comment]
That's an excellent reason to make this a "probably never" feature.  Good to have that documented.

**Comment by ammario** [comment]
> To summarize: The suggestion after discussion here is to change the workspaces URL in the browser to
> 
> * `/<username>/<workspace>`
>   OR
> * `/<@username>/<workspace>`
> 
> Do I have that right?

`/username` is not a viable option since it could conflict with other top-level routes. I have strong preference for the `@` it's the globally accepted username prefix at this point.

**Comment by misskniss** [comment]
fixed by #2101
