### ISSUE TITLE
Show "build log number" in UI/CLI

### ISSUE THREAD

**Issue by ammario** [coder/coder#1906]
I can't remember who I discussed this issue with, but someone explained to me that build logs would have an internal representation as a per workspace sequential ID.

I like this approach for the following reasons:

* It's easy to glance at the number and know whether you're looking at an old build.
* Build URLs become clearer and shorter.
  *  `workspaces/coadler/colin/builds/105` instead of `/builds/2a243358-aa3a-4ec3-acf9-d24234d2212d`

**Comment by ketang** [comment]
I think being able to tell whether it's old or new will require a little bit more, e.g. labels and decoration in the UI, perhaps a canonical `/latest` that we redirect you to if the number you choose is the latest (though that has the drawback of taking the number out of the URL)...
