### ISSUE TITLE
Bug: Workspace Schedule UI: submitting long TTL for workspace in UI caused error to update and workspace to hang and become unusable

### ISSUE THREAD

**Issue by tjcran** [coder/coder#1908]
- Browser (if applicable):  Chrome, in Windows

## Steps to Reproduce

- Set TTL to 100000000000  (after filling in the other fields with acceptable defaults)
- Hit submit
- UI hangs and never updates and becomes unusable

## Expected

 
If the TTL is truly invalid, I should receive an error message preventing the submit and telling me what the values are. Even better if the UI has input validation or at least some help text. 

## Actual

 
UI hangs forever

## Screenshot
![image](https://user-images.githubusercontent.com/7042112/171048447-21f28730-a54b-437d-a062-4addf59e0bd0.png)

**Comment by ketang** [comment]
Recommendation: if you have a TTL, it cannot be longer than 72 hours.  If that's insufficient, and for some reasons they still want a TTL, someone will tell us.

**Comment by vapurrmaid** [comment]
> Recommendation: if you have a TTL, it cannot be longer than 72 hours. If that's insufficient, and for some reasons they still want a TTL, someone will tell us.

CC @johnstcn - we can create this constraint

**Comment by johnstcn** [comment]
@vapurrmaid FWIW I added some upper bounds in https://github.com/coder/coder/commit/a8ae9b39b3b44c6ca2c1094564d77104046f6922 -- in this case I set the upper bound to 7 days (184 hours).

**Comment by ketang** [comment]
3 days is no less arbitrary than 7 days (which is 168 hours not 184).  What matters is that there's a limit that's not ridiculous.
