### ISSUE TITLE
UX improvement hitlist for Workspace Schedule page

### ISSUE THREAD

**Issue by ammario** [coder/coder#1909]
Related #1908 

cc @vapurrmaid (some of these are taken from the PR)

1. Allow setting "Days of Week" when "Start time" is unset
   * This one confused me. We shouldn't assume that users will fill out the form in top to bottom order.
1. Timezone should be select list, then we can avoid the user education. Also: why does time zone have a dashed border instead of a solid border?
2. Timezone should default the the browser's declared time zone
3. Clock icon blends in with background. Lighten it.
4. Rewrite "TTL" for clarity (see screenshot)

![image](https://user-images.githubusercontent.com/7416144/171055679-2ef6abe3-9fa4-40bc-839d-163d74d72518.png)

**Comment by mtm20176** [comment]
@ammario or Time Zone should be a user profile setting. A reference example is OutReach or Salesforce, where this specified at the user-level.

**Comment by ammario** [comment]
> @ammario or Time Zone should be a user profile setting. A reference example is OutReach or Salesforce, where this specified at the user-level.

That's a good idea, too. We could show them their user-configured timezone on the schedule page and then link out to user settings for them to change it.

**Comment by ketang** [comment]
I think we should eventually have a deployment-level or orgranization-level default @tjcran

**Comment by vapurrmaid** [comment]
> Clock icon blends in with background. Lighten it.

As far as I'm aware (so far), this one is out of our control. I posted #1791 as an even better solution - @ammario , @ketang , @tjcran , are you OK with that approach?

**Comment by vapurrmaid** [comment]
> > @ammario or Time Zone should be a user profile setting. A reference example is OutReach or Salesforce, where this specified at the user-level.
> 
> That's a good idea, too. We could show them their user-configured timezone on the schedule page and then link out to user settings for them to change it.

This is exactly what I had in mind too, and was going to follow-up with. Should that be CE or EE ?

**Comment by vapurrmaid** [comment]
> why does time zone have a dashed border instead of a solid border?

It's dotted when "disabled". I don't like how it looks either. It's disabled when start-time is unset. We can massage this.

**Comment by vapurrmaid** [comment]
Everyone: I'm going to separate out tickets per each discussed request made here. I'm going to parallelize this effort with other folx since some of these changes do not conflict with one another.

I love all the suggestions here, let's get it!

🙌🏻

**Comment by ammario** [comment]
> > > @ammario or Time Zone should be a user profile setting. A reference example is OutReach or Salesforce, where this specified at the user-level.
> > 
> > 
> > That's a good idea, too. We could show them their user-configured timezone on the schedule page and then link out to user settings for them to change it.
> 
> This is exactly what I had in mind too, and was going to follow-up with. Should that be CE or EE ?

I think start by just making it default to browser time zone with a drop down, very similar to how it is now. There are no other features that I can think of in CE that require timezone, so I don't think we should abstract it into user settings now.

**Comment by tjcran** [comment]
> > > > @ammario or Time Zone should be a user profile setting. A reference example is OutReach or Salesforce, where this specified at the user-level.
> > > 
> > > 
> > > That's a good idea, too. We could show them their user-configured timezone on the schedule page and then link out to user settings for them to change it.
> > 
> > 
> > This is exactly what I had in mind too, and was going to follow-up with. Should that be CE or EE ?
> 
> I think start by just making it default to browser time zone with a drop down, very similar to how it is now. There are no other features that I can think of in CE that require timezone, so I don't think we should abstract it into user settings now.

Agreed. All we need to do is make it a regular timezone picklist like any other app (this was always the plan)

**Comment by vapurrmaid** [comment]
Broke out #1958 from here

**Comment by vapurrmaid** [comment]
Broke out https://github.com/coder/coder/issues/1959 from here

**Comment by vapurrmaid** [comment]
> Clock icon blends in with background. Lighten it

@Kira-Pilot solved this with #1923 :tada: !

**Comment by vapurrmaid** [comment]
I'm closing this hitlist as I've now either addressed or groomed all tasks, and some have been implemented with the help of the team (go @Kira-Pilot and @AbhineetJain 🙌🏻 ).

Thanks all!
