### ISSUE TITLE
Bug: Workspace page: Stop and Start workspace buttons are displayed for workspace in Failed status

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1913]
## OS Information

- OS: Windows
- Browser (if applicable): Chrome
- Architecture:
- `coder --version`:
[Coder v0.0.0-devel+e02ef6f](https://github.com/coder/coder/commit/e02ef6f2288f5b401aa488d9866d2e5f5b7512b3)

## Steps to Reproduce

(pre-condition: ther is a template that workspace cannot be created from. On dev may use latest-linux it is configured to use service account key that is disabled)

1.  Login to coder web
2. Click Create workspace and choose broken template
3. Specify name
4. Click Submit

## Expected
Workspace goes to Failed state and there is a button "Retry" (?) according to https://github.com/coder/coder/pull/1362

## Actual

Both Start and Stop are displayed

## Screenshot

![image](https://user-images.githubusercontent.com/9592232/171168161-02de29db-b714-403c-8294-0563ecc3df9f.png)

**Comment by misskniss** [comment]
Closing this. It is not longer a problem.
