### ISSUE TITLE
Install Coder via homebrew

### ISSUE THREAD

**Issue by bpmct** [coder/coder#1925]
## What is your suggestion?

Publish Homebrew releases for Coder, similar to what we do for [code-server](https://coder.com/docs/code-server/latest/install#macos) and Coder Classic's CLI. 

## Why do you want this feature?

Familiar OSX install path, easy to spin up a service on OSX.

## Are there any workarounds to get this functionality today?

The install script (#1852) will use the GitHub release, so this isn't a huge priority unless we get many requests for it.

## Are you interested in submitting a PR for this?

Yes, but down the road. I do no think we need it for community MVP

**Comment by bpmct** [comment]
@endingwithali is working on this :)

**Comment by jskrzypek** [comment]
@bpmct I have a working homebrew cask on my personal tap: https://github.com/jskrzypek/homebrew-tap/blob/main/Casks/coder.rb, feel free to take/use it

I also have a formula, https://github.com/jskrzypek/homebrew-tap/blob/main/Formulae/coder.rb, but I don't know if it takes the right approach, as it just calls into `./scripts/build_go.sh`. I struggled to get the `make install` target to run and didn't fully grok all of the steps involved in the dependent targets (e.g. if the `protoc` and `yarn` pre-build targets were actually necessary...) so I just skipped them. When installing the formula it seems to work, but I am going to use my cask version for now.

**Comment by kylecarbs** [comment]
@jskrzypek would you mind submitting this as a formula to the brew repo? https://github.com/Homebrew/homebrew-core/tree/master/Formula

It'd be awesome if we could get it added there.

**Comment by jskrzypek** [comment]
@kylecarbs I'll be happy to, but does the way I build the go lib in the formula actually do the right thing for the tool? I saw there were other build steps in the makefile's install that had complex dependencies and that I skipped, e.g. the yarn & protoc stuff. Are those needed for the cli tool? (It feels like the protoc bit would be at least for the grpc?)

Or are you suggesting I submit the Cask I wrote to homebrew/homebrew-cask?

**Comment by jskrzypek** [comment]
Also in my opinion, it might be advisable for coder to just start a tap in addition to the formulae in the homebrew repos... Also for code-server and the legacy coder formula... That way you could add steps to your CD to auto-update your tap, which any homebrew maintainers could reference for updates to the formulae/casks on the official repos

**Comment by ghuntley** [comment]
> just start a tap in addition to the formulae in the homebrew repos

and use something such as https://github.com/marketplace/actions/homebrew-releaser to keep it up to date.

**Comment by ghuntley** [comment]
Been thinking about this @deansheather 

**proposal**:

- use `brew tap codr/coder` from https://github.com/coder/homebrew-coder
- keep `brew install coder-cli` and `brew install coder-cli-nightly` formulas until v1 is deprecated.
- implement `brew install coder` formula now.
- implement automation that keeps `brew install coder` up to date.

**Comment by NedkoHristov** [comment]
Bumping up the PR. Hope we'll receive a homebrew support anytime soon.

**Comment by bpmct** [comment]
@NedkoHristov - there are no immediate plans to do this, but we'd happily accept a PR.

**Comment by aslilac** [comment]
given that we need to distribute the full binary via a tap (because of licensing), this might be on hold again for a minute?

**Comment by matifali** [comment]
@aslilac, Are you planning to make this automatic for future releases? Same as we do for Winget and Chocolatey in https://github.com/coder/coder/blob/main/.github/workflows/release.yaml#L331

**Comment by aslilac** [comment]
If we do update our tap to have formulas for v2, we will probably want to automate those.

**Comment by matifali** [comment]
Should we close this as completed?

**Comment by aslilac** [comment]
well, this issue is specifically to track "using homebrew to install coder when running our install.sh script", which has not yet been done

**Comment by matifali** [comment]
@aslilac I just installed using `brew install coder`
and I can see that it is a full build
```console
coder version
Coder v2.0.2
https://github.com/coder/coder

Full build of Coder, supports the  server  subcommand.
```

**Comment by aslilac** [comment]
Are you sure that's the homebrew version? What do you see when running `which coder`?

**Comment by matifali** [comment]
@aslilac, yes
```console
which coder
/opt/homebrew/bin/coder
coder version
Coder v2.0.2
https://github.com/coder/coder

Full build of Coder, supports the  server  subcommand.
```

**Comment by bpmct** [comment]
I'm not sure I understand the concern publishing a full build in the first place. It's nice that I can `brew install coder` on my mac and start a full build

**Comment by matifali** [comment]
Maybe we should keep this opened until we or the homebrew people make updates automatically.

**Comment by matifali** [comment]
@aslilac Wow that's awesome.

**Comment by matifali** [comment]
It looks like the Coder is automatically being kept updated.
https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+coder+
@bpmct @aslilac 
Do you think we should close the issue?

**Comment by aslilac** [comment]
I think there’s still an open question of “what do we do about the install script?”

**Comment by deansheather** [comment]
> I'm not sure I understand the concern publishing a full build in the first place. It's nice that I can brew install coder on my mac and start a server

@bpmct The "slim" message in the version text only gets added if the binary is built with `-tags slim`. Since the binary isn't built with any tags like `slim` or `embed`, it can start an API server but it can't serve the dashboard or workspace agent binaries.

It's also an AGPL-only binary so it can't use any enterprise features. Any code/features in the `enterprise` directory is not included in an AGPL build.

I think we should make our own homebrew thing like we did in v1 https://github.com/coder/homebrew-coder so we can ship our release binaries (fat, with dashboard and agent binaries, with enterprise code, and signed by our dev certificate). Once we've done this we should deprecate the official formula if the maintainers will let us.

**Comment by aslilac** [comment]
I still disagree that we should remove the upstream formula. It is useful for people. but we should open a PR to add `-tags slim` to the build.

**Comment by aslilac** [comment]
Just submitted https://github.com/Homebrew/homebrew-core/pull/140710, which correctly identifies the binary as AGPL and slim. Gonna work a little on updating our tap.

**Comment by aslilac** [comment]
> if the maintainers will let us.

Just found this in the docs btw :p https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#official-vendor-taps

> We are not willing to remove software packaged in Homebrew/homebrew-core in favour of an upstream tap. We are not willing to instruct users in our formulae to use your formulae instead.

**Comment by aslilac** [comment]
had some time to spend on this today and yesterday though! after a bunch of various pull requests to various repos, I think this should be ready to close soon.
