### ISSUE TITLE
Display informative message when there is no workspaces or templates

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#1926]
- When there is no template we want to teach the user how to create one.
- We also want to automatically refresh the templates when the user comes back to the page

![Screen Shot 2022-05-31 at 14.10.51.png](https://images.zenhubusercontent.com/624b0b948eaef9e6bd542a2e/dbfbd6f4-75ec-44ea-9bff-b17e9b913188)

**Comment by BrunoQuaresma** [comment]
Related to #1638

**Comment by f0ssel** [comment]
We probably should only show this to admins who could actually run those commands successfully.

**Comment by nadzeyav** [comment]
Verified
Admin role: no templates, no workspaces
Admin role: several templates, no workspaces

Member and Auditor: no templates not workspaces - > minor issue reported: https://github.com/coder/coder/issues/1979
Member and Auditor: have templates, no workspaces
