### ISSUE TITLE
Make it prettier for the Community - UI / CLI Touch Ups

### ISSUE THREAD

**Issue by misskniss** [coder/coder#1939]
This is the collection of things that we would like to fix in the UI if time allows. 

-----
## Highest Priority Items

- [x] #2243 
- [x] #2254 
- [x] #1386 

-----
## Everything Else

- [x] #651 
- [x] #1374 
- [x] #1601 
- [x] #1646 
- [x] #2030 

### Completed Items
- [x] #724 
- [x] #1036 
- [x] #1269 
- [x] #1274 
- [x] #1326 
- [x] #1335  
- [x] #1359 
- [x] #1424 
- [x] #1426 
- [x] #1508 
- [x] #1542 
- [x] #1543 
- [x] #1528 
- [x] #1583 
- [x] #1593 
- [x] #1639 
- [x] #1640
- [x] #1677
- [x] #1694 
- [x] #1710 
- [x] #1768
- [x] #1765 
- [x] #1769 
- [x] #1784
- [x] #1791 
- [x] #1801
- [x] #1820 (1972)
- [x] #1827 
- [x] #1832
- [x] #1852
- [x] #1854 
- [x] #1864 
- [x] #1885
- [x] #1886 
- [x] #1911 
- [x] #1937 
- [x] #1887 
- [x] #1888 
- [x] #1889 
- [x] #1890
- [x] #1899 
- [x] #1904 
- [x] #1905 
- [x] #1906
- [x] #1909 
- [x] #1910 
- [x] #1913 
- [x] #1940
- [x] #1941
- [x] #1949
- [x] #1953 
- [x] #1955 
- [x] #1958
- [x] #1959
- [x] #1966
- [x] #1967 
- [x] #1977
- [x] #1988 
- [x] #1983
- [x] #1984
- [x] #1991
- [x] #1993 
- [x] #2000 
- [x] #2001
- [x] #2003
- [x] #2004 
- [x] #2019
- [x] #2021
- [x] #2022
- [x] #2029
- [x] #2031
- [x] #2033 
- [x] #2034
- [x] #2120 
- [x] #2141 
- [x] #2148 
- [x] #2149 
- [x] #2161 
- [x] #2242 
- [x] #2255 
- [x] #2258 
- [x] #2300

**Comment by ammario** [comment]
Recs:
* https://github.com/coder/coder/pull/1972
* https://github.com/coder/coder/issues/1991
* https://github.com/coder/coder/issues/1992
* https://github.com/coder/coder/issues/1993
* https://github.com/coder/coder/issues/1647
