### ISSUE TITLE
Autostop: fall back to workspace.ttl if workspace.latest_build.deadline is zero

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#1942]
## Definition of Done

Workspace autostop should fallback to the `workspace.ttl` if the `workspace.latest_build.deadline` is zero.

## Steps to Reproduce

- Create a workspace with autostop enabled
- Start workspace and wait for transition to complete
- Edit database and set workspace.latest_build.deadline to time.Zero e.g.
  ```
    update workspace_builds set deadline='0001-01-01 00:00:00+00' where id = 'deadbeef-dead-beef-dead-beefdeadbeef';
  ```
- Observe that workspace does not auto-stop

## Expected

Workspace should auto-stop after now plus workspace TTL.

## Actual

Workspace does not auto-stop.

## Logs

```
Jun 01 13:39:57 coder coder[28025]: 2022-06-01 13:39:57.575 [DEBUG]        <./coderd/autobuild/executor/lifecycle_executor.go:132>        (*Executor).runOnce.func2        latest workspace build has zero deadline, skipping        {"workspace_
id": "64ff14cb-3b2d-4aad-8011-247f2cf9332f", "workspace_build_id": "a67e7139-6266-4e03-8d91-eb21ed14642d"}
```

## Notes

- This is in addition to [updating deadlines of active workspace builds if workspace.ttl is updated; tracked separately ](https://github.com/coder/coder/issues/1783)

**Comment by ketang** [comment]
Maybe I don't understand the internals, but I'm not seeing how this is a bug.

**Comment by johnstcn** [comment]
This leads to confusing behaviour. If you create a workspace with autostop not enabled, and then enable autostop, this will equate to the behaviour we originally wanted to avoid in https://github.com/coder/coder/issues/2229. Closing.
