### ISSUE TITLE
Consistently display error messages from backend 

### ISSUE THREAD

**Issue by presleyp** [coder/coder#1943]
As was done in the `usersXService`, we should go through the frontend and make sure all error messages from the API are being unpacked properly to avoid over-reliance on default error messages, or displaying unhelpful error messages (the error has a less helpful message than the response). `getErrorMessage` and `getFormErrors` help with this.

## To be done

- [x]  convert this to an epic
- [x] create issues for each XService

## Problem
The frontend does not always display the error messages sent from the backend, and even when it does, it does not display the `detail` that is sometimes sent along with it. 

## Definition of done for each ticket
- There are no uses of `displayError` in this XService. To replace the error snackbar, render `ErrorSummary` in the relevant components with the `dismissible` prop. This way, the user can expand the error detail if desired without the snackbar disappearing on them.
- There are no uses of `getFormHelpers` in the relevant components; switch to `getFormHelpersWithError` even if no error. (We will eventually rename it to replace the original `getFormHelpers`.)
- The XService always `assign`s the API error, rather than a hard-coded error message. If a hard-coded error message is needed as a fallback, send it as a prop to `ErrorSummary`.
- Errors are only unpacked in `ErrorSummary` and `getFormHelpersWithError`.
- Storybook has a story for when the error(s) are showing.

## Tickets

- [x] #3106
- [x] #3088
- [x] #3097 
- [x] #3094
- [ ] #3096 
- [ ] #3095 
- [ ] #3093 
- [x] #3091 
- [ ] #3090 
- [ ] #3089 
- [ ] #3209
- [x] #3343

**Comment by presleyp** [comment]
I think this should be an epic with one ticket per XService. I'd like to work on it because I already put some thought and code into it, but I don't think it's a high enough priority for pre-launch.

**Comment by misskniss** [comment]
Deliverable for this sprint would be to create the Epic and shred it into its issues

**Comment by misskniss** [comment]
Let's pick these off to complete as we get time. These are not high priority but should get attention as we go.

**Comment by kylecarbs** [comment]
Seems like this issue is decomposed, so I'm going to close it in favor of the others. They'll still reference this so the context isn't lost.
