### ISSUE TITLE
Allow quick option to set Auto On/Off to manual 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#1956]
As a user, I want a quick and obvious way to set the Auto On/Off schedule to Manual so I do not have to deselect all the days to make it work as a Manual Schedule

Right now, you can have a manual On/Off schedule but it is not obvious that you do this by deselecting all the days in the schedule. 

Instead it would help to have a Manual toggle or schedule type selector available that a user can chose to set this as a schedule or a manual setting in the UI.

**Comment by kylecarbs** [comment]
I think we already added this...? Closing!
