### ISSUE TITLE
API Response for an invalid TTL is too general

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1957]
## Steps

1. (prior to merging fix for #1908): enter an invalid ttl (very long)
2. Hit submit
3. Observe that there's no error from the api mapping to the `ttl` field

## Expected

The client-side expects that form errors conform to this interface:

```ts
interface FieldError {
  field: string
  detail: string
}

interface ApiErrorResponse {
  message: string
  errors?: FieldError[]
}
```

## Actual

```json
{
    "message": "read body: json: cannot unmarshal number 6.0479999892e+21 into Go struct field UpdateWorkspaceTTLRequest.ttl of type time.Duration"
}
```

**Comment by vapurrmaid** [comment]
I recognize that sometimes there _are_ general errors that don't map to a specific field. However, in this case, the error we're returning (which is related to Go constructs) really represents the reality that we're failing go-validator for the maximum allowed number. I feel that this one is field-specific.

I do not know if there's a general way to approach field-level go-validator problems, or that we must do it case-by-case.

I also do not think this one is a high priority, and is `nice-to-have`, particularly if we can think about a general way to clean up go-validator errors that are specific to fields.

**Comment by BrunoQuaresma** [comment]
I think we made some fixes on this right? At least in the API, I see better error messages 🤔 cc.: @johnstcn

**Comment by johnstcn** [comment]
I don't believe this is possible to trigger any longer. Closin gout.
