### ISSUE TITLE
User Timezone Preferences

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1960]
## User Story 👥 

I want to be able to go to my user profile and change my default/preferred timezone. If I don't have a timezone preference set, I want it prefilled with my brower's settings. I should be able to set or unset my default/preferred timezone from `/settings/account`.

![account-settings](https://user-images.githubusercontent.com/11184711/171475660-d853adb5-22c6-4810-9ab0-ac3cb3d06719.png)

### Related Story (Separate Ticket)

As a user of the Coder platform, I want workspace scheduling timezone to be prefilled with my timezone preference. 

## Implementation Notes

- We can detect the user's current timezone using `dayjs`: https://day.js.org/docs/en/timezone/guessing-user-timezone

**Comment by johnstcn** [comment]
For the CLI:
- On Linux/MacOS we can just check `/etc/localtime` or read the `TZ` environment variable 
- On Windows, there seems to be some form of arcane Powershell incantation you can use ([link](https://superuser.com/a/1584968))
