### ISSUE TITLE
Track changes to resources whenever parameter values change

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#1970]
## What is your suggestion?

We need to recompute and track workspace resources each time the effective set of parameter values changes in order to correctly report resources in the way they are currently presented.

I think it makes sense to do this via a mechanism that snapshots the set of parameter values which we persist.  This allows us to clearly determine from the database whether the resource computation is pending or up to date, and will be beneficial for debugging failed builds.

## Why do you want this feature?

Our current resources UX attempts to tell the user _what would happen in the future_ if they run a build.  When we tell a user a resource is ephemeral, we are telling them that it won't exist when they stop the workspace, but will exist when they start it.  When we tell them it is permanent, we are telling them it will be there on start and stop.

The resources, in general, depend on the values of parameters in the template.  Change the parameters, and you've potentially changed the resources (kind, number, properties, etc.), so we need to recompute the resources via a dry-run (e.g. terraform plan) and persist that information.

## Are there any workarounds to get this functionality today?

There are some semi-broken ways, like looking at the dry-run on template creation, which is often mostly correct, depending on how the template has been implemented, c.f. #1937

Alternatively, we could drop the expectation that we tell the users about the future, and instead just report the present state of resources (i.e. drop ephemeral / permanent).

## Are you interested in submitting a PR for this?

Yes

**Comment by ketang** [comment]
I think we're good for now with the simpler case of reporting on the latest state.  I think it's a relatively small number of users that will want to know the plan before it's executed, and they'll let us know if they need it.

We're also going to have to do something richer with resource tracking anyway, and neither of these options seems to help us get there faster.  We might as well go with the method if we know it's going to be superseded.
