### ISSUE TITLE
Canonicalize colors in theme

### ISSUE THREAD

**Issue by oxy** [coder/coder#1973]
## What is your suggestion?

Right now, we've grown various shades of grey/orange/blue/purple in random files in the site; ideally, we would at least centralize all of the color definitions in a single file, and also unify a lot of the colors (for example, orange is the selected indicator in the top menu, and the selected indicator on the profile settings page is blue)

![image](https://user-images.githubusercontent.com/19502779/171518593-5cd4b8b2-f135-412d-bd53-86775ab582a1.png)

## Why do you want this feature?
I think that consistency in colors used throughout the project would give off the general appearance of confidence/it would look a little more uniform.

## Are there any workarounds to get this functionality today?
Not really.

## Are you interested in submitting a PR for this?
Yes!

**Comment by Kira-Pilot** [comment]
@BrunoQuaresma is this one completed now?

**Comment by BrunoQuaresma** [comment]
We are using the colors from the template.
