### ISSUE TITLE
(feature) No templates and no workspaces case: There is a suggestion to create a template for Member instead of ask an Admin on create workspace form

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1979]
## OS Information

- OS: Windows
- Browser (if applicable): Chrome
- Architecture:
- `coder --version`:
[Coder v0.0.0-devel+9e3a625](https://github.com/coder/coder/commit/9e3a62589898119b38fdfd52a92380bada45fa4b)
## Steps to Reproduce

1. Delete all workspaces and templates
2. Login as a user with Member role
3. Open workspaces and click Create workspace

## Expected

Message similar to message on workspaces page: 
Create your first template
Contact your **Coder administrator** to create a template. You can share the code below.

## Actual
The following message is displayed on popup:
To create a workspace you need to have a template. You can [create one from scratch](https://github.com/coder/coder/blob/main/docs/templates.md) or use a built-in template by typing the following Coder CLI command:

## Screenshot

https://user-images.githubusercontent.com/9592232/171625535-8da37803-3c2f-4aa5-8fa8-1b3269187661.mp4

## Notes
This case most probably is super rare one.

**Comment by tjcran** [comment]
@BrunoQuaresma it looks like the messaging should be scoped differently for admin vs non-admin users because non-admin users are told to create a template but they do not have the ability to do so.
