### ISSUE TITLE
WorkspaceScheduleForm should use my timezone preference

### ISSUE THREAD

**Issue by vapurrmaid** [coder/coder#1981]
## User Story 👥 

This story is a continuation from #1960

As a user that has set a preferred timezone in my user profile, the `WorkspaceScheduleForm` should:

- use the timezone from my workspace schedule, if set
- otherwise use the timezone in my preference

As a user that does not have a preferred timezone in my user profile, the `WorkspaceScheduleForm` should:

- use the timezone from my workspace schedule, if set
- otherwise use `dayjs` guess

It would be nice if the helperText linked to the user profile page that sets the timezone.

## Implementation Notes

Separate piece of work that comes after #1960 as a continuation.

**Comment by kylecarbs** [comment]
Seems like this is blocked on #1960. Closing for now!
