### ISSUE TITLE
Flexbox improvement checklist on the workspace page

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#1982]
## What is your suggestion?
There are a couple of flexbox improvements that we can make to the workspace page:

- [ ] As discussed in #1963, reconsider the spacing on the tables such that all the status columns align neatly (and preferably under the action buttons.
- [ ] On smaller screens, we are having difficulties with a two column layout (see #1953). Even with that aforementioned ticked resolved, we still get wrap on the status columns:
![Screen Shot 2022-06-02 at 10 03 50 AM](https://user-images.githubusercontent.com/19142439/171647436-c20ad028-c458-4835-8b00-3a55c1e72576.png)
I think the best way to handle this would just be to create two rows at a certain resolution. A quick mock in Figma is probably warranted. 

## Are there any workarounds to get this functionality today?
Screen is totally usable as is

## Are you interested in submitting a PR for this?
Sure

**Comment by misskniss** [comment]
Deliverable on this one is yo investigate if this is still a need.
