### ISSUE TITLE
Unclear admin persmissions: Admin can use Open terminal link on other users workspaces, but terminal is opened with Web Socket error 

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#1988]
## OS Information

- OS: Windows
- Browser (if applicable): Chrome
- Architecture:
- `coder --version`:
[Coder v0.0.0-devel+9e3a625](https://github.com/coder/coder/commit/9e3a62589898119b38fdfd52a92380bada45fa4b)
## Steps to Reproduce

1.  Login as user with role Member and create a workspace
2. Login as Admin
3. Open member's workspace
4. Click link Open Terminal link

## Expected

Terminal is opened or link to open should be not displayed in case Admin should not be able to connect

## Actual

Web Socket error (see screenshot)

## Screenshot

![image](https://user-images.githubusercontent.com/9592232/171667936-84daaa50-3f87-4c71-9ddf-b515f341e17a.png)

## Notes

have this issue in --dev mode, did not verify on production version

**Comment by tjcran** [comment]
Acceptance Criteria: The terminal link/icon should only be visible to the owner of the workspace when viewing the workspace page
