### ISSUE TITLE
A lot of space is wasted on Resources Card due to agent columns

### ISSUE THREAD

**Issue by ammario** [coder/coder#1998]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/7416144/171715531-95d99c00-2696-4cb2-ad8c-3f236189169f.png">

Assumption: most resources will not have an agent, therefore these columns will be mostly empty.

**Comment by presleyp** [comment]
Is there other info you want to use that space for? My assumption is that the most useful thing to do on the workspace page is click the links in the agent area (open a terminal, or app/dev url).

**Comment by ammario** [comment]
> Is there other info you want to use that space for? My assumption is that the most useful thing to do on the workspace page is click the links in the agent area (open a terminal, or app/dev url).

I'm not sure. Those are important operations and they should definitely still be highlighted. Perhaps we're leaning too much into the table here.

**Comment by ketang** [comment]
I've got issues with the term "agent" #2063 that are tangentially relevant here, namely what exactly are we trying to do for the user here with this information, and what is the most effective way to accomplish it?  I think for agent all we're communicating is that the resource is compute that can run stuff and be logged into.  While we're in the neighborhood of the subject, I don't think calling a resource "Coder" is useful.

Right now the only useful thing I see that the agent column communicates is the operating system.  How about we put that over into the "Resource" column?  Maybe "Linux on kubernetes_deplyoment" or "Compute/Linux" or its own row?

One thing I would use the additional space for is identifiers.  What if you have two hosts or three PVCs or four S3 buckets?  Right now we just show the type, which will be insufficient in those cases.  Even if you only have one, having the name there is good confirmation that things are working as expected (and smoke if they're not).

**Comment by misskniss** [comment]
related to #2003

**Comment by presleyp** [comment]
We discussed this in office hours and decided to close this ticket, but note that https://github.com/coder/coder/issues/2422 will open up some space in the resources card.
