### ISSUE TITLE
Quick access to workspaces filter to see who has created a workspace with a specific template

### ISSUE THREAD

**Issue by tjcran** [coder/coder#1999]
## Problem statement
A newly onboarded user who is joining their team's Coder deployment for the first time will want to know what templates are being used by other team members. This will avoid the back and forth for a new team member trying to figure out what everyone else is doing. 

## Definition of Done
Clicking on the "view workspaces" link under the "used by x users"  on a Template detail page is a hyperlink that takes you to the Workspaces page with a prepopulated search filter to show you ONLY the workspaces that were made with that same template. 

![image](https://user-images.githubusercontent.com/7042112/171718787-c5dae605-9b44-4da1-b665-fa718227a9b0.png)

This is a `nice to have` that lets users easily see who else is using a template. The hypothesis is that it would help with onboarding users and quickly seeing what others on your team are doing. 

There is a workaround where you can manually use the search on the workspaces page (#1972)

**Comment by f0ssel** [comment]
@tjcran @kylecarbs @Emyrk Want to ask a questioned regarding what we actually build here:
1. Do we want this to link to a list of users? @Emyrk is working on adding the same filter to the users page, so this will be possible soon. If so, are we good with some sort of filter key like `uses-template:coder`?
2. Do we want to add a link to a list of Workspaces with that template? I'm pretty sure this was a common ask for V1 with Images. If so, we need to add a stat for # of workspaces using the template to the API. Does that seem good @kylecarbs ?

**Comment by Emyrk** [comment]
`template` param already exists :+1: 

![Screenshot from 2022-06-24 16-56-15](https://user-images.githubusercontent.com/5446298/175698033-1bfd495a-7351-4f18-9f3b-9ca21c9c6d93.png)

**Comment by tjcran** [comment]
> `template` param already exists 👍
> 
> ![Screenshot from 2022-06-24 16-56-15](https://user-images.githubusercontent.com/5446298/175698033-1bfd495a-7351-4f18-9f3b-9ca21c9c6d93.png)

nice! so that means we'd just have to link to this template param filter from the "22 users" as a link, with the particular template already populated in the filter. I don't think it needs to be more complicated than that.
![image](https://user-images.githubusercontent.com/7042112/175970779-afc81560-511c-49df-9a9f-cba48ffabebf.png)

**Comment by f0ssel** [comment]
I think the action we are talking about here is ambiguous. My original understanding was that this button would link to the "Users" page with a filter that would only show the users using this template. What Tyler is outlining is a link to the "Workspaces" page which would show you the workspace using the template, which would not be the "22 users" the text suggest. 

So I think we either:
1. Change this text to say "X workspaces" and link to the Workspaces page with the template filter.
2. Leave text and link to a Users page with a template filter. This filter does not currently exist. 

Reason 2 is not super straight forward because the model relationship goes: 

User -> Workspace <- Template

So we would need a db query that queries users who have a workspace  that is based off this template ID. Not necessarily hard just something worth noting.

**Comment by kylecarbs** [comment]
I think showing the number of users with a specific template is important, because it's proportional to the deployment.

I don't think we need to filter by this for now TBH, but we could add a users endpoint to a template in the future.

**Comment by Emyrk** [comment]
@f0ssel I think the `user.sql` query we can add something like this: (I put a list of template_ids)

```
	AND CASE
		WHEN cardinality(@template_ids :: text[]) > 0 THEN
			id IN (SELECT owner_id FROM workspaces WHERE id IN
				(SELECT * FROM templates WHERE id = ANY(@template_ids :: text[])))
		ELSE true
	END
```

I'm not sure how "optimized" subqueries are vs joins, but I'm sure it's fine for now. I also like how these cases only pay the additional SQL cost when the filter option is selected.

**Comment by kylecarbs** [comment]
I don't think we need to do this for now. It's kinda nice, but it's really easy to do already with our CLI or even with Ctrl+F in the UI.
