### ISSUE TITLE
Enhance: Version column 'outdated' status to allow update in place

### ISSUE THREAD

**Issue by misskniss** [coder/coder#2001]
As a user it is helpful to know that a workspace is out of date but it would be more useful to allow me to update it there as well and/or see the information about what version it is on (similar to the up to date hover action issue #2000) so that I can see that information at a glance. 

![outdated workspace.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/623d4ff2-059f-4a28-af90-7e6201e79c1d)

**Comment by ketang** [comment]
Put a `⟳` in there to update.  Maybe just a `?` to describe the delta?
