### ISSUE TITLE
Bug: Ensure agent websockets from outdated builds are rejected before websocket is opened

### ISSUE THREAD

**Issue by coadler** [coder/coder#2004]
Exponential backoff is only enabled if the websocket fails to open. If
the websocket is opened but immediately killed, the agent will try to
immediately reconnect. This is desireable in cases where coderd is being
replaced or network conditions cause the connection to die, but not for
permanent errors

**Comment by ketang** [comment]
Back off should probably be bounded, i.e. once we get to once per 30 seconds or thereabouts, I don't think we should back off more.

**Comment by coadler** [comment]
@ketang it looks like the backoff is currently capped at 10s.
