### ISSUE TITLE
UI workspace schedule supports hours + minutes

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2016]
## User Story 👥 

The UI for workspace schedule currently only supports `ttl` as hours. If a non-round time is set via CLI, the UI will round it in the form.

We'd like to extend this input to understand a greater precision (minutes for now, possibly more later). We need a more sophisticated input to accommodate this (possibly 1 input for hour, 1 input for minutes ?)

1. Create any template
2.  Run via CLI: coder create --t [template name] [template-name] --ttl 68m
3. Open workspace via UI

## Implementation Notes

The rounding is here: https://github.com/coder/coder/commit/37aff0c8a9ab3ae2f59d356d48d089415407c7cc#diff-6479a1168ce67746239902a493ef38452c899d19da0741eb84812f89e47e3aa0R97

**Comment by vapurrmaid** [comment]
I don't see this as a bug, it's a feature for us to extend this precision to the UI and was done purposefully for agile reasons.

I'm going to edit the ticket to capture that we want this behavior in the future

**Comment by kylecarbs** [comment]
This doesn't have a clear purpose or objective. Closing!
