### ISSUE TITLE
Make workspace timeline rows obviously clickable

### ISSUE THREAD

**Issue by ketang** [coder/coder#2021]
## What is your suggestion?
It is not obvious that these rows are clickable
<img width="1057" alt="Screen Shot 2022-06-03 at 16 29 12" src="https://user-images.githubusercontent.com/33678/171874885-df20deed-7144-4a97-8e7b-a2c44cf585ed.png">

## Why do you want this feature?
So users understand they can get more information about a workspace.

## Are there any workarounds to get this functionality today?
n/a

## Are you interested in submitting a PR for this?
no

**Comment by ketang** [comment]
Perfect

**Comment by BrunoQuaresma** [comment]
For who is going to take this ticket:
- The icon is ChevronRight from MUI
- We can change the hover color of the row to match the hover color from the nav item to make it consistent

**Comment by f0ssel** [comment]
Chatted with @BrunoQuaresma , we think these improvements should also be made to the templates page for the same reasons!

**Comment by AbhineetJain** [comment]
@f0ssel Thank you for the update! I'll take care of both in the same PR then!

**Comment by AbhineetJain** [comment]
![Screen Shot 2022-06-03 at 4 12 33 PM](https://user-images.githubusercontent.com/7511231/171944757-6f98a4c7-1ddc-4271-9d34-1a45bb48f91a.png)

@f0ssel @BrunoQuaresma Just wanted to confirm if this was the table we wanted to add the icon to. We already have an anchor link with the template name here. Should we still keep that? Or just make the row clickable to go to that link? Additionally should we do the same on the Workspaces list page?
