### ISSUE TITLE
Add `command` to workspace applications

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#2023]
The command property exists in the `WorkspaceApp` type but is currently unused.

In the web, this should open a reconnecting terminal with the command running. On the command line, this should execute an SSH session with the command.

**Comment by bpmct** [comment]
> On the command line, this should execute an SSH session with the command.

How will desktop apps such as VS Code Remote SSH or VNC viewers work with the coder app commands?

**Comment by kylecarbs** [comment]
The `command` will execute on the remote machine, not the local. So VS Code Remote should have essentially no interaction with this for now.

**Comment by ketang** [comment]
Yeah supporting those things is a non-goal.  They go through vanilla ssh and `ProxyCommand` anyway.
