### ISSUE TITLE
Autostop: bump deadline if workspace hits autostart time

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2028]
## What is your suggestion?

We may want to change autostop behaviour to bump the workspace deadline when it hits the scheduled autostart time.

### Current Behaviour

Given:
- A workspace exists that has an autostart schedule at e.g. 0900 every day and an autostop schedule for 8 hours after start
- A user manually starts the workspace at 0200

When:
- It turns 1000 hours

Then:
- The workspace is stopped automatically

### Desired Behaviour

When:
- It turns 1000 hours

Then:
- The workspace's deadline is extended to the autostart time plus normal TTL, and it stops at the "scheduled" time of 1700 hours.

## Why do you want this feature?

Some folks were surprised that their workspaces got shut down at the configured time.

## Are there any workarounds to get this functionality today?

`coder bump my-workspace however-many-hours-you-need`

## Are you interested in submitting a PR for this?

Yes

**Comment by ammario** [comment]
The desired behavior makes a lot more sense to me, too.

**Comment by vapurrmaid** [comment]
I agree with the desired behavior. Thinking of this, I wrote some (probably incorrect) pseudo-logic around it in the RFC, that you should only be able to extend your workspace deadline up to the next auto-on time, assuming that at the scheduled auto-on, your deadline would refresh.

> I don’t know if this is overkill for the RFC Solution, but I was thinking that we could allow auto-off to be extended until it is ≥ than the auto-on time.
> 
> Example:
> 
> Grey: 9am → 9pm
> 
> If I extend by 12+ hours, the backend will just 201 my request to extend. When 9am hits the following day, my workspace will still be on so that auto-on will no-op.
> 
> Logic looks like this:
> 
> const startTime = “09:00 2022-03-04” // assume mod 24
> const offTime = “21:00 2022-03-04” // assume mod 24
> 
> let scheduled = offTime
> 
> func extend () {
>   nextTime = scheduled + “90 minutes”
> 
>   if nextTime ≥ startTime && nextTime < offTime {
>     scheduled = offTime + “24 hours” // “21:00 2022-03-05”
>     return 201
>   } else {
>     scheduled = nextTime
>     return 200
>   }
> }

**Comment by ammario** [comment]
Hmm why don't limit Auto-Off to `start_time_interval - 1`?

**Comment by kylecarbs** [comment]
@johnstcn how complex is this to do? I don't have an idea of it, but if it's trivial it might be nice to add to the EE milestone.

**Comment by johnstcn** [comment]
> @johnstcn how complex is this to do? I don't have an idea of it, but if it's trivial it might be nice to add to the EE milestone.

I would hesitate to call this "trivial".

**Comment by kylecarbs** [comment]
We haven't gotten suggestions for this, so I'm closing for now!

**Comment by mafredri** [comment]
I'm in support of making this change. Sometimes I restart the workspace in the evening (say 8pm) and with a normal schedule of 9:30am + 14h, this would result in autostop happening after at 10am, at which point the workspace will be stopped when I try to login in the morning.

**Comment by bpmct** [comment]
@deansheather is working on changes related to our scheduling behavior to avoid this. Basically, workspaces will only stop during "quiet hours" to prevent workspaces from stopping at inconvenient times, such as right before an autostart. Going to close in favor of that

**Comment by bpmct** [comment]
Yep: https://github.com/coder/coder/pull/8117

**Comment by deansheather** [comment]
Quiet hours does not interact with regular TTL (only the "restart requirement") so this needs to be reopened. I think we should just change the activity bumping code to be like:
```go
newDeadline := time.Now().Add(ttl)
if newDeadline.After(nextAutoStartTime) {
  newDeadline = nextAutoStartTime.Add(ttl)
}
```

**Comment by deansheather** [comment]
We also need to change the initial calculation for deadline to have this extra clause too, in `autostop.CalculateAutostop()`

**Comment by bpmct** [comment]
@deansheather - is this still on your plate

**Comment by deansheather** [comment]
I had a PR for this but it went stale due to the offsite and my vacation. I don't think it's super high priority though TBH

**Comment by stirby** [comment]
Bumping this and re-opened the PR. We should bring it into this sprint.

**Comment by mattlqx** [comment]
A couple of our folks have noticed this quirk as well. Not having this breaks the assumption that your workspace will be up from `autostart time` to `autostart time + autostop duration` when using an auto-start schedule.

**Comment by stirby** [comment]
@bpmct @sreya I think this is a `must-do` for the upcoming sprint. Several customers have been experiencing unexpected workspace shutoffs due to Autostop issues. Solving this would both improve user experience and expedite debugging of other scheduling issues.

**Comment by bpmct** [comment]
Sounds good to me.

**Comment by stirby** [comment]
We fixed this a while back!
https://github.com/coder/coder/commit/290180b1047ef1304b4cc15570dcbad32a073e40
