### ISSUE TITLE
Show Initiator in Build Logs

### ISSUE THREAD

**Issue by ammario** [coder/coder#2029]
There have been cases where either:
1. Auto-start/Auto-stop triggers a start/stop
2. An admin user triggers a start/stop

And it's unclear why a workspace transitioned state. I used this opaqueness to troll Kyle for multiple days.

I suggest we add an ~"Actor"~ Initiated By column to the Timeline table in the Workspace page and an Actor field on the Build Log page.

## Implementation notes: 

We should add a system user here to report in the logs for what user is taking what actions. 

## AC
Show a human readable name for the initiator ID for all builds. 
Add another column in the build logs for initiator
Testing: storybook for UI, human readable name, check that the name appears on the page, unit test for API returning human readable name

**Comment by tjcran** [comment]
DigitalOcean logs just have a "User" column and it has your own user, system, and sometimes distinguishes it with other parts of the system. 

![image](https://user-images.githubusercontent.com/7042112/172421926-cac24325-8efa-4539-ab64-08e34ed7c809.png)

**Comment by Emyrk** [comment]
I will add `initiator_name` to the payload response for the api to use

**Comment by Emyrk** [comment]
Should we add a `system` user? Without a special user in the database, and foreign key relations will not work. So the field will have to be `null` for the `intiator_id`? And we'd treat `null` special?

Does anyone oppose adding a `system` user much like Github's [Ghost](https://github.com/Ghost) user?

**Comment by kylecarbs** [comment]
I'm a fan of this.

I'm uncertain whether having it in the database is best, or making it a static UUID instead like reserving `uuid.Nil` is safer.

**Comment by Emyrk** [comment]
@kylecarbs I was thinking a special uuid, but if we have foreign key relations setup, we will need a row in the db to satisfy constraints. 

I imagine we'd do both. Use a special uuid, and insert into the db.

**Comment by AbhineetJain** [comment]
@kylecarbs @Emyrk Just wanted to reach a decision on the discussion here. Considering the foreign key behavior of `initiator_id`, we might need a db reference, unless we handle the null value in code.

**Comment by kylecarbs** [comment]
I'd also prefer non-null.

**Comment by Emyrk** [comment]
Keep it non-null. I'm curious if we ever need to distinguish between initiated_by being `system` and `autostart`. Or something akin to that. I don't want to populate the db with a bunch of random system users. Maybe just `system` is enough for now...

Would be nice to know it started because of `autostart` though, rather than the vague `system`.

**Comment by AbhineetJain** [comment]
I understand if it is really out there, but I'd love for it to be named `coderbot`. 😂 Not sure if `autostart` is a good name for the stop action, would prefer something more generic.

**Comment by Emyrk** [comment]
`autostart` was not a good suggestion, you are correct. Maybe `scheduler` or something idk. Regardless, that would either require 2 system users, or some sort of meta data field to elaborate the `system` user

**Comment by ketang** [comment]
I like both `coderbot` and `scheduler`.  The latter has more specificity, although maybe we need to put that information in a different column (`reason`?) rather than relying on the name, and we still might need to call it `coder-scheduler` or something.  And perhaps highlight system users in a different color.

**Comment by AbhineetJain** [comment]
That makes sense. This looks like a separate issue of its own though. I wonder if we'd wanna figure out the reasons ourselves, or let admins/users input their reasons when taking the action. In case we end up always assigning the same reason when the initiator is the same, it would seem moot to add the column.

**Comment by ketang** [comment]
Yep, can be separate.

**Comment by ammario** [comment]
`system` is the name I usually see used for these kinds of operations. If we wanted to delineate the subsystem perhaps we could use an actor like `system/scheduler`.

I also like the idea of coloring this user differently when it appears in the UI.

**Comment by tjcran** [comment]
+1 on "system" and +1000 on different color

**Comment by AbhineetJain** [comment]
@ketang I filed https://github.com/coder/coder/issues/2410 for discussion on the `reason` column.

@ammario I like `system/scheduler`.

**Comment by AbhineetJain** [comment]
#2428 adds a system user with a special uuid.
