### ISSUE TITLE
Entering minutes field in workspace schedule start time triggers day of week validation failure

### ISSUE THREAD

**Issue by ketang** [coder/coder#2030]
## OS Information

Mac OS X
`Chrome Version 101.0.4951.64 (Official Build) (arm64)`
`Coder v0.0.0-devel+d6e9eab`

## Steps to Reproduce

1. From a workspace page, click Edit Schedule
2. Click the "start time" field to give it focus
3. Type a value for hours, e.g. 10
4. Type a value for minutes, e.g 3

## Expected

Days of week stay chill; I'll get to you.

## Actual

Happy
<img width="490" alt="Screen Shot 2022-06-03 at 16 52 45" src="https://user-images.githubusercontent.com/33678/171878808-dab94c96-ad8b-4b62-92d5-1cc007e79bd0.png">

One `3` later: sad.
<img width="477" alt="Screen Shot 2022-06-03 at 16 52 53" src="https://user-images.githubusercontent.com/33678/171878824-d9154dc4-f5e0-4516-87f3-28b029f38b67.png">

**Comment by vapurrmaid** [comment]
I **do not** think this is a bug.

**Comment by ketang** [comment]
Why not?  I shouldn't be chastised for not selecting days of the week if I haven't gotten to that part of the form.

Also, even if that were the case, why wouldn't it be in that error state from the start?  Why does it happen when I go from just hours to hours and minutes?

**Comment by vapurrmaid** [comment]
I misunderstood, it's that the validation is happening before it's touched. I will change this back over to a bug.

**Comment by johnstcn** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Workspaces-V2-Hub-62019e46b7e29b0014a7f850/issues/coder/coder/2030?planning-poker) with ZenHub @vapurrmaid

**Comment by johnstcn** [comment]
I'm no longer able to reproduce this issue. Opening the schedule and un-checking/deleting everything, and then just entering '1' in the 'hours' field no longer triggers a validation error. Entering both hours and minutes then triggers the day-of-week validation, which is required if you set the minute and hour.
