### ISSUE TITLE
Host docs on coder.com/docs

### ISSUE THREAD

**Issue by ammario** [coder/coder#2033]
As we all know, documentation is critical to a user's first steps into a product. I propose we move our documentation to coder.com/docs before the June 10th release if at all possible.

In terms of naming and URL scheming to avoid confusion with our v1 product, I suggest we rename the v1 section to "Coder (Classic)", keeping all the URLs the same to avoid breakage.

The v2 section could become "Coder (OSS)" and the URL can be `coder-oss` for now. 

To avoid confusion, we may want to place a static banner on the Coder Classic docs site educating users to check out the OSS docs if they're using `coder/coder`.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/7416144/171905897-85f2cac8-8365-412b-9d09-3df91a528d5d.png">

Thoughts @BrunoQuaresma?

**Comment by BrunoQuaresma** [comment]
@ammario yes, we can make it. We need to have a manifest.json on the coder/coder repo. @khorne3 can you help me with that?

@kylecarbs I see you changed the title, but right now, the docs are on coder.com/docs 🤔

**Comment by khorne3** [comment]
@BrunoQuaresma yes, can do!
