### ISSUE TITLE
Workspace search without classifier has confusing results

### ISSUE THREAD

**Issue by ammario** [coder/coder#2043]
When `owner:` is omitted, the results make sense only half of the time. For example:

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/7416144/171926799-8e3608c4-22f5-45c3-b39e-75415a2adf34.png">

I also thing a substring match makes more sense than a prefix match. For example, "woo" should show my "weewoo" workspace.

cc @f0ssel 

Related #2041 #2042

**Comment by f0ssel** [comment]
agreed!
