### ISSUE TITLE
As an admin, I can stop a workspace in UI, but not in terminal/CLI

### ISSUE THREAD

**Issue by mtm20176** [coder/coder#2048]
## OS Information

- OS:
- Browser (if applicable): 
- Architecture:
- `coder --version`: 0.6.0

## Steps to Reproduce

A user other than me has a running workspace.

I try and `coder stop` it in the CLI, and get:

`status code 403: forbidden
Run 'coder stop --help' for usage.`

## Expected

The workspace stops

## Actual

`status code 403: forbidden
Run 'coder stop --help' for usage.`

## Screenshot

<img width="412" alt="image" src="https://user-images.githubusercontent.com/2022166/171954227-a8ce5a67-468d-4596-8eeb-3fe2198a2c5c.png">
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/2022166/171954257-cde0aeeb-5d8d-4ffb-9089-4ce1459e130e.png">

**Comment by ammario** [comment]
This has been fixed at some point.
