### ISSUE TITLE
I stop a workspace in the UI, got the list view of workspaces, and it never updates to stopped from stopping, unless with a refresh

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2049]
## Problem Summary
Workspace list in UI does not automatically refresh when a change is made to stop a running workspace. It looks like it's in progress the entire time, even if it has finished.

## Definition of done
 Page should fetch and update the status without requiring a user refresh.

## Steps to Reproduce

In UI, I stop a workspace, and return to the workspaces list view in UI

## Expected

Status should change from Stopping to Stopped without a page refresh

## Actual

I never changes, is in Stopping. If I open a new window, it shows the workspace is stopped.

## Screenshot

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/2022166/171954660-00a539c1-ff16-4677-a861-53abde702815.png">

**Comment by tjcran** [comment]
Problem: Page should fetch and update the status without requiring a user refresh.

**Comment by tjcran** [comment]
> Yeah this is a known limitation, I believe the idea was to fix it when we switch to using websockets to update workspaces.

@presleyp got it! is that covered in the build log websockets item or does it have a separate issue? I'm not seeing one other than the build log one: #2569

**Comment by presleyp** [comment]
I don't see a ticket for it, although I thought I remembered a related one existing (for using websockets on the workspace page generally, not just the build log). But this ticket can serve as the ticket for using one on the workspaces page.

**Comment by misskniss** [comment]
@mark-theshark will you try this again and see if you can repro it? We are not able to atm/.

**Comment by BrunoQuaresma** [comment]
I tried to reproduce this as well and I was not able to. I think we can close it.

**Comment by misskniss** [comment]
Closing this!
