### ISSUE TITLE
Bug: There is no delete button in the UI, and I can't delete someone else's stopped workspace. So I had to kill coder server to do it

### ISSUE THREAD

**Issue by mtm20176** [coder/coder#2050]
## OS Information

- OS:
- Browser (if applicable): 
- Architecture:
- `coder --version`: 0.6.0

## Steps to Reproduce

Have users create some workspaces. You can stop them in the UI, as an admin, but there is no delete button.

The admin cannot delete them in the CLI.

So I had to kill the server and lose my templates - but that did destroy the workspaces.

## Expected

A delete workspace button in the UI, and admins should be able to delete workspaces in the CLI

## Actual

`markmilligan@mtmcoder ~/d/d/v2> coderv2 delete dogface
> Confirm delete workspace? (yes/no) yes
status code 403: forbidden
Run 'coder delete --help' for usage.`

## Notes

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/2022166/171955383-b2672de7-e9b9-4b1c-ba00-fd323ed0fc84.png">

**Comment by ammario** [comment]
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/7416144/172021681-e28d4e0e-683f-452c-bea0-71c0c5d18abb.png">

This is fixed in master.
