### ISSUE TITLE
Expand SSH Key text field

### ISSUE THREAD

**Issue by ammario** [coder/coder#2052]
<img width="712" alt="Screen Shot 2022-06-04 at 1 45 52 PM" src="https://user-images.githubusercontent.com/7416144/172021422-d6a182d5-876a-43c7-88c6-a03afb0f20f7.png">

should show the full text field without scrolling IMO. The SSH key has a static size so a constant-dimension solution presents well.

**Comment by ketang** [comment]
I agree there should be no scrollbars, but doesn't the key length vary based on parameters and algorithm?

**Comment by ammario** [comment]
Since we control the algorithm, not really. The OpenSSH cleartext representation of the ed25519 public key is always 68 chars. If we switch to another elliptic curve algo it will be roughly similar.

**Comment by ketang** [comment]
I guess if and when we support something else we can probably adjust the size of the area correspondingly.

**Comment by f0ssel** [comment]
Yeah just went to report this and found this, this looks pretty rough

**Comment by ammario** [comment]
Reopening as super simple
