### ISSUE TITLE
Preselect weekdays when setting a new auto-on schedule

### ISSUE THREAD

**Issue by ketang** [coder/coder#2053]
## What is your suggestion?
Preselect weekdays when setting a new auto-on schedule.  Monday through Friday would be checked off by default.  If a user doesn't want all those days, they can uncheck as necessary.

## Why do you want this feature?
Reducing the expected number of user actions to getting the desired functionality.

## Are there any workarounds to get this functionality today?
n/a

## Are you interested in submitting a PR for this?
Maybe but probably not in time to do good.

**Comment by ketang** [comment]
An elaboration of this would be to store in local storage the days they selected last time they set up a schedule for a workspace, if any, and use that to prepopulate the schedule for the new form.  For many people that'll end up being the same, but if someone has a consistent but non-standard schedule, this will help them further.

**Comment by ammario** [comment]
> An elaboration of this would be to store in local storage the days they selected last time they set up a schedule for a workspace, if any, and use that to prepopulate the schedule for the new form. For many people that'll end up being the same, but if someone has a consistent but non-standard schedule, this will help them further.

This is a good idea. An elaboration still is it could store the time of day and shutdown interval, not just days of week.
