### ISSUE TITLE
Rename "filters" button in workspaces view

### ISSUE THREAD

**Issue by ketang** [coder/coder#2054]
## What is your suggestion?
Currently there is a `Filters` button that offers the options `Your Workspaces` and `All Workspaces.`. "Filters" is a pretty vague word, so I don't think a user is likely to understand what it does except by accident.  Also I think "Your Workspaces" is non-standard; I think typically applications use the first person, e.g. "My Workspaces."

I recommend just showing the selection.  By default it would read `My Workspaces`.  Click on it, and it either offers a choice of `My Workspaces` and `All Workspaces` or just directly switches to whatever wasn't currently selected.

## Why do you want this feature?
Reduce user confusion and make it easier for them to take advantage of this nice filtering feature.

## Are there any workarounds to get this functionality today?
n/a

## Are you interested in submitting a PR for this?
No

**Comment by ammario** [comment]
I agree that "My Workspaces" is more clear than "Your Workspaces. An alternative to "Filters" is "Presets".

**Comment by mtm20176** [comment]
There is prior art: GitHub Issues
<img width="792" alt="image" src="https://user-images.githubusercontent.com/2022166/172025646-413ea266-c66b-4968-b899-e448d2c732b5.png">

**Comment by ketang** [comment]
That pops out a whole drawer of multiple filters presenting multiple criteria like author or date.  We don't have filterS.  We have a binary toggle.
