### ISSUE TITLE
Bug: If you update 'time until shutdown' in a running workspace, the workspace UI has the old value

### ISSUE THREAD

**Issue by mtm20176** [coder/coder#2055]
## OS Information

- OS:
- Browser (if applicable): 
- Architecture:
- `coder --version`: 0.6.0

## Steps to Reproduce

1. Have `Time until shutdown` already configured e.g., 8 hours

2. The workspace is running

3. Change the `Time until shutdown` to 1 hour

4. The workspace UI says 7 hours remaining (the leftover part from the original 8 hours)

## Expected

Not quite sure, but something based on the new `Time until shutdown` - so maybe 1 hour in this example

## Actual

The shutdown remaining in workspace UI is based on the previous `Time until shutdown`

## Screenshot

<img width="461" alt="image" src="https://user-images.githubusercontent.com/2022166/172027547-011094d7-ea65-490e-bb8a-34e377727555.png">

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/2022166/172027552-924bee2a-d11d-495a-911e-269e58441aeb.png">

## Notes

Nope

**Comment by ketang** [comment]
I poked at this to see how it behaved.  To start more from scratch:
1. create a workspace
2. set its shutdown time to 3 hours
3. start the workspace
4. when it is starting or has started, change the schedule to shut down after an hour
Result: the workspaces page still shows "SHUTDOWN: 3 hours after start."

Doing a hard page reload doesn't change anything; it still shows 3 hours.  *However*, if I hit the "Stop" button, then schedule card then shows "1 hour after start" 🤷🏾‍♂️
