### ISSUE TITLE
MacOS paste of service account token during coder templates create fails (regression)

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2056]
## OS Information

- OS:
- Browser (if applicable): 
- Architecture:
- `coder --version`: 0.6.0

## Steps to Reproduce

I know an alternative is to use Terraform's `data "template_file"` but in this case I would like to prompt the admin user in the coder CLI to paste a GCP service account token, as part of creating a template. e.g., `coder templates create gcp-ubuntu-with-docker-engine`

My Macbook Pro makes a noise when I paste the token and only a portion of it has been pasted so I cannot proceed in creating the template.

This is a regression. It was a widely-known bug in 0.3.x+, then it was resolved, and it reverted.

## Expected

I should be able to paste the entire token

## Actual

My Macbook Pro makes a noise when I paste the token and only a portion of it has been pasted so I cannot proceed in creating the template.

## Screenshot

<img width="823" alt="image" src="https://user-images.githubusercontent.com/2022166/172031408-79fba489-8216-43d6-87c2-b059cfde4229.png">

**Comment by ketang** [comment]
It's *sort of* a regression.  The earlier fix made it impossible to use the backspace key for that input.  We decided that it was better to steer users toward the input file method for that field than to make them lose backspace everywhere or to make the behavior vary across different fields.
