### ISSUE TITLE
"agent" terminology is unclear

### ISSUE THREAD

**Issue by ketang** [coder/coder#2063]
## What is your suggestion?
Improve the workspaces page to more effectively communicate... whatever the agent is doing or for.

<img width="1022" alt="Screen Shot 2022-06-05 at 21 03 24" src="https://user-images.githubusercontent.com/33678/172066487-7d4cb16b-1a52-4264-bdd2-2563b36c4908.png">

## Why do you want this feature?

I don't think the word "agent" is meaningful to our typical user.  I barely understand what it's trying to communicate, and it's something very specific to our implementation rather than referring a concept in our problem domain.

## Are there any workarounds to get this functionality today?
n/a

## Are you interested in submitting a PR for this?
No

**Comment by ketang** [comment]
I've discarded a lot of alternatives.  "Host" or "Development host" are two that I don't hate.

**Comment by ketang** [comment]
"Agent" is commonly used, but it's not commonly used for *this*.  The agent is an implementation detail particular to how we designed things, not a first class concept in the product.  The customer never directly interacts with it or configures it or anything.  When you drive to an island you don't care about the bridge.  Those other situations where "agent" is used are ones where people know about and *want* to know about the agent, e.g. a monitoring system or `ssh-agent`.  What the customer cares about is the blob of compute.  Calling it an "agent" obfuscates that.

**Comment by tjcran** [comment]
> "Agent" is commonly used, but it's not commonly used for _this_. The agent is an implementation detail particular to how we designed things, not a first class concept in the product. The customer never directly interacts with it or configures it or anything. When you drive to an island you don't care about the bridge. Those other situations where "agent" is used are ones where people know about and _want_ to know about the agent, e.g. a monitoring system or `ssh-agent`. What the customer cares about is the blob of compute. Calling it an "agent" obfuscates that.

@ketang I talked with @bpmct about this quite a bit and _thus far_ in the demos he's done with community members, this has actually been pretty clear and well understood what this is and what it is doing. In the cases of a single compute resource and a single agent, it's not necessarily helpful, but there's no feedback yet to suggest it is unclear. But it *will* be helpful in other use cases, particularly when k8s is powering the workspace. There's going to be a need to display this and I don't think it's going to be that uncommon

See example below.
![image](https://user-images.githubusercontent.com/7042112/174133249-3b5b95f4-bba0-48d4-9d23-78ace5d53f3a.png)

**Comment by tjcran** [comment]
My vote would be to put any changes to this on hold for now in favor of other improvements to this card such as #2422, which consequently should increase the clarity of the agent and make it simultaneously more helpful. I also now believe that having the agent+status will be valuable in troubleshooting and diagnosing issues with the workspace.

**Comment by tjcran** [comment]
Closing this. We can reopen if we receive feedback from users about the helpfulness of having "agent" displayed.
