### ISSUE TITLE
Rename "timeline" to "history" in workspace page

### ISSUE THREAD

**Issue by ketang** [coder/coder#2064]
## What is your suggestion?
Rename "timeline" to "history" in workspace page

## Why do you want this feature?
Less jargony.

## Are there any workarounds to get this functionality today?
n/a

## Are you interested in submitting a PR for this?
No

**Comment by kylecarbs** [comment]
History doesn't feel friendly for an active job.

What do you find jargony about timeline?

**Comment by ketang** [comment]
I agree with your first point: #2064

"Timeline" is less commonly used in colloquial English.  I associate it with corporate speak ("What's our timeline for that deliverable?" or science fiction.

**Comment by kylecarbs** [comment]
I agree. When building the API I ran into weirdness with this naming too. We eventually landed on just calling it "Builds" in the API.
