### ISSUE TITLE
Separate active jobs from completed jobs

### ISSUE THREAD

**Issue by ketang** [coder/coder#2065]
## What is your suggestion?
Separate the Timeline (which should be "History" #2064) into two parts: active jobs and completed/terminated jobs.  Basically duplicate the current table, limit one to actively running jobs and move it above Resources and omit actively running jobs from the other but leave it otherwise unchanged.  Name the first one something like "Actions in progress" or "Pending actions;" there are a half dozen options that work.

Often this section will be empty and just have a header.  This is a feature and good.

An elaboration that would make this better would be to change some of the columns.  "Pending actions" doesn't need a status, for instance, while it would benefit from an actively updated duration (right now it just shows "In progress" until it's done).  "Status" in the History is more general;  "Result" would be more appropriate to something that will either be "Succeeded," "Failed," or "Unknown."

## Why do you want this feature?
The timeline commingles past and present in a way that can be confusing even ignoring the issue with "Running" (#1677).

## Are there any workarounds to get this functionality today?
n/a

## Are you interested in submitting a PR for this?
no

**Comment by kylecarbs** [comment]
I think this will make the UI confusing. If we fix #1677 I don't believe this will be a problem.

A workspace can only have a single running job, so I'm not sure what the other view would even display.

**Comment by ketang** [comment]
Why can it only have one running job?  I'm not sure that's a good thing forever, for instance a workspace that has a Windows VM and a Linux VM in it.  You'd want to do that in parallel if possible.

Having only one running job doesn't weaken the advantage.  It makes it easy to distinguish between "something is happening" and "nothing is happening."  It's helpful to be able to see that at a glance.

**Comment by ketang** [comment]
I'd like to avoid baking in serial provisioning for a single workspace.  Componentizing templates to be parallelizable will be an adventure, but it's an inevitable one.

**Comment by kylecarbs** [comment]
@tjcran we shouldn't do this for Community. There are many many many unknowns in regards to this ATM.

**Comment by ketang** [comment]
You have no idea what I had to do to create these mocks.

With an active job:
<img width="1438" alt="coder-workspace-active-jobs-mock" src="https://user-images.githubusercontent.com/33678/172187042-1a935831-67a2-4fc8-b46e-d5993fc257d9.png">

With no active jobs:
![coder-workspace-no-active-jobs-mock](https://user-images.githubusercontent.com/33678/172187158-6645cf78-e4f9-44d3-88b5-fc8b6d015747.png)

In retrospect the text should say "No active jobs" instead of "Active jobs."

Eventually we'll have a count.

**Comment by ketang** [comment]
Almost but not quite.  Maybe it's close enough.

**Comment by tjcran** [comment]
Closing this as not planned.
