### ISSUE TITLE
Add support for enabling pprof endpoints in `coder agent` on Windows during runtime

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2081]
## What is your suggestion?

We should add support for enabling pprof endpoints to `coder agent` during runtime when running on Windows.

## Why do you want this feature?

We have support for this on Unix-based operating systems via `kill -USR1 $coder_agent_pid`. It could help with debugging if the agent has entered a weird state. Especially useful where a restart of the agent would resolve the issue.

The issue was brought up during review of https://github.com/coder/coder/pull/1985.

## Are there any workarounds to get this functionality today?

Pprof can be enabled on startup via `CODER_AGENT_PPROF_ENABLE`

## Are you interested in submitting a PR for this?

Not at this time. Due to Windows limitations, we can't use the same approach as on Unix. We need to settle on what a solution would look like and if there are other requirements to consider.

Possible (alternative) ideas were floated in https://github.com/coder/coder/pull/1985#issuecomment-1146176444.

**Comment by kylecarbs** [comment]
@mafredri I wonder if we can just always have pprof endpoints alive? There shouldn't be any overhead, which would be net positive in a debugging situation.

**Comment by mafredri** [comment]
Only downside I can see is we potentially use up a relatively common port? Ultimately I think it'd be nice to have a toggle for this in the WebUI or CLI ("coder enable agent profiling on workspace").

I'd be fine with the always-on approach for now, though.

**Comment by mtojek** [comment]
> I'd be fine with the always-on approach for now, though.

Looking into this.
