### ISSUE TITLE
Provide quick workspace actions on workspaces list page

### ISSUE THREAD

**Issue by ketang** [coder/coder#2082]
## What is your suggestion?
Provide quick workspace actions on workspaces list page
* start
* stop
* update
* delete... maybe, if there's a confirmation

<img width="1407" alt="workspace-summary-actions" src="https://user-images.githubusercontent.com/33678/172181098-919b2586-540b-4609-8e54-9f86db537e50.png">

## Why do you want this feature?
Faster, faster, I must go faster faster.

Especially if a user has multiple workspaces that need updating.

Eventually we'll need to have bulk action support, but that's an "also" not an "instead."

## Are there any workarounds to get this functionality today?
n/a

## Are you interested in submitting a PR for this?
no

**Comment by ammario** [comment]
I agree with @ketang. We also can't represent a bulk change as a transaction at the moment, and a "Mark as" implies such.
