### ISSUE TITLE
Coder gets zsh killed on macOS (not M1) after curl installing 0.6.2 AMD64 build

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2086]
## OS Information

- OS:
- Browser (if applicable): 
- Architecture:
- `coder --version`: 0.6.2

## Steps to Reproduce

curl -L https://coder.com/install.sh | sh

then run coder

## Expected

the list of coder commands

## Actual

markmilligan@mtmcoder ~ % coder
zsh: killed     coder

## Logs

After coder is installed:

`Installing v0.6.2 of the amd64 release from GitHub.

+ Reusing ~/.cache/coder/coder_0.6.2_darwin_amd64.zip
+ mkdir -p /usr/local
+ sudo mkdir -p /usr/local/bin
Password:
+ sudo unzip -d ~/.cache/coder -o ~/.cache/coder/coder_0.6.2_darwin_amd64.zip
Archive:  /Users/markmilligan/.cache/coder/coder_0.6.2_darwin_amd64.zip
  inflating: /Users/markmilligan/.cache/coder/LICENSE  
  inflating: /Users/markmilligan/.cache/coder/README.md  
  inflating: /Users/markmilligan/.cache/coder/coder  
+ sudo cp ~/.cache/coder/coder /usr/local/bin/coder
	Standalone release has been installed into /usr/local/bin/coder

Run Coder (temporary):
  coder server --dev

Or run a production deployment with PostgreSQL:
    CODER_PG_CONNECTION_URL="postgres://<username>@<host>/<database>?password=<password>" \
        coder server`

which coder

`markmilligan@mtmcoder ~ % which coder
/usr/local/bin/coder`

## Notes

I'm blocked

**Comment by ketang** [comment]
Was this on an M1 laptop?  Or an Intel one?

**Comment by bpmct** [comment]
This was an intel laptop, but I'm unable to reproduce

**Comment by bpmct** [comment]
Mark and I debugged this a bit further. He was able to consistently reproduce when upgrading from 0.6.0 to 0.6.2. I was not able to reproduce.

One primary difference is he uses a MacOS Big Sur and I use Monterey. It seems like a reboot also serves the problem for him, but not new terminal sessions.

**Comment by ketang** [comment]
It's not great to say we only support the latest macOS, and it's likely going to be a few months before 13 comes out.  I think we're going to need to tackle this one after initial shipment.

**Comment by mtm20176** [comment]
@bpmct My workaround (for now) is putting $HOME/.cache/coder/coder in the path, since that is where we originally copy `coder` from. And then it works.

**Comment by bpmct** [comment]
Will compare this to the helm install script and see if a permissions issue occurs: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

**Comment by bpmct** [comment]
I believe this has to do with how Apple "trusts" binaries. Deleting the binary right before copying in the new one does the trick.
