### ISSUE TITLE
Workspace fails to delete from UI

### ISSUE THREAD

**Issue by tjcran** [coder/coder#2102]
Workspace fails to delete. The workspace has been unable to start for a few days and a very long attempt at deleting (twice) failed. 

![image](https://user-images.githubusercontent.com/7042112/172236981-ee76ab4e-5040-4b10-871c-8b7b6fea0923.png)

## Steps to Reproduce

 Click "delete"
 Confirm prompt
 Wait 700+ seconds for delete to fail

## Expected
I expected the workspace to delete correctly

## Actual
It took a very long time to tell me that it failed

## Notes
Workspace: https://dev.coder.com/workspaces/8a1b922b-8863-4b09-bc08-9cca556368ca

**Comment by f0ssel** [comment]
Can you still repro this? I can't on dev.coder.com
