### ISSUE TITLE
Access the desktop environment of a workspace

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#2106]
It'd be useful to access the desktop environment of a workspace in Coder.

- Cross-platform browser testing
- Installing applications on Windows (it's hard to install packages on the Windows command line)
- Desktop application development
- Android and iOS development
- ... and I'm sure many more!

This would be implemented as a native access application, similar to the web terminal. A command would be added too, something like: `coder desktop <workspace>` or `coder open desktop <workspace>`.

![image](https://user-images.githubusercontent.com/7122116/172260945-091994f4-405b-4032-86e4-ade227974ac7.png)

# Implementation

VNC clients will use [noVNC](https://github.com/novnc/noVNC) through the browser. This should use noVNC APIs to hide the overlay user interface, making it feel like a native experience.

RDP clients don't currently have a web-based solution (💡 ideas are welcome here). An initial implementation could exclude Windows and still provide significant value, so this shouldn't be a hard blocker!

Although implementations with RDP and VNC are different, we should make this transparent to the user to deliver a consistent experience.

## Linux and macOS

Specify a VNC server address in the `coder_agent` resource (naming subject to change):

```terraform
resource "coder_agent" "dev" {
  vnc = "tcp://localhost:5900"
}
```

In the absence of a VNC server specified:
- On Linux, look for `x11vnc` on `$PATH` and start it with the agent when VNC is requested.
- On macOS, [start the VNC server](https://apple.stackexchange.com/questions/30238/how-to-enable-os-x-screen-sharing-vnc-through-ssh).

Expose the VNC connection through a new DataChannel protocol, and pipe it to a WebSocket endpoint.

## Windows

Specify a RDP server address in the `coder_agent` resource (naming subject to change):

```terraform
resource "coder_agent" "dev" {
  rdp = "tcp://localhost:3389"
}
```

In the absence of an RDP server specified, attempt to start it (I googled around a bit, but was unable to find much).

Expose the RDP connection through a new DataChannel protocol, and pipe it to a WebSocket endpoint.

**Comment by f0ssel** [comment]
I did a quick search for a native go vnc server and didn't find much, which is a bummer because that would fit in really nicely here. 

I did find this, but I can't really read it. It has tags for vnc and rdp and is half go half js, so could be something - https://github.com/dushixiang/next-terminal

**Comment by bpmct** [comment]
Heard great things about apache guacamole: https://guacamole.apache.org/

**Comment by kylecarbs** [comment]
Even if there was a native Go VNC server, we'd still need an X11 server so it wouldn't save us much @f0ssel.

We could totally do something with the Apache Guacamole approach. That would solve our Windows woes.

**Comment by ketang** [comment]
This history gives me confidence
<img width="831" alt="Screen Shot 2022-06-07 at 09 25 49" src="https://user-images.githubusercontent.com/33678/172321063-7a6189f7-8a88-4412-a0bc-6e92b36b55b6.png">

**Comment by tjcran** [comment]
> I've heard great things about apache guacamole: https://guacamole.apache.org/

Came here to recommend Guacamole as well

**Comment by nikhil96widhani** [comment]
I am not a fan of novnc because there is no shared clipboard and many more things. I absolutely love this image from linuxserver's team https://docs.linuxserver.io/images/docker-webtop

If we can adopt the technology used behind this or simply use this inside a workspace

**Comment by sreya** [comment]
Kyle and I talked offline about this but this seems better defined as an app than a coder-provided function. Everything that we offer right now works out of the box. For VNC to work correctly the user needs to have already installed x11.

**Comment by tjcran** [comment]
> Kyle and I talked offline about this but this seems better defined as an app than a coder-provided function. Everything that we offer right now works out of the box. For VNC to work correctly the user needs to have already installed x11.

This makes sense and I think it aligns well with our [proposed templates strategy](https://github.com/coder/coder/issues/2179#issuecomment-1157998232)

**Comment by ketang** [comment]
A potential customer is already using Guacamole, so that's another data point in favor.

**Comment by ntimo** [comment]
I am using https://kasmweb.com/ for desktop apps and it’s truly amazing. Just to drop that there might be useful :)

**Comment by ketang** [comment]
Probably the part we care about: https://github.com/kasmtech/KasmVNC

**Comment by ghuntley** [comment]
> I've heard great things about apache guacamole: https://guacamole.apache.org/

https://nathancatania.com/posts/deploy-guacamole-ssl-saml/ from https://twitter.com/NathanMcNulty/status/1588204579795398658

**Comment by tidux** [comment]
For Linux desktops, another solution would be using [X2go Server](https://wiki.x2go.org), which basically bundles X11 and a few helper protocols over an SSH tunnel.  The `x2goserver`  package has been in Debian main and Ubuntu universe package repositories for years now, and since it's just X11 it's DE agnostic.  I've used it to great success with Fluxbox on personal machines.  The downside is there's no client for iOS or Android or the web.

**Comment by phorcys420** [comment]
I like the approach where the template owner defines their own vnc path, it's gotta save some time rather than struggling writing a vnc implementation for the coder agent.
I think we shouldn't hide the overlay though, it allows copy/paste and other resolution fixes when needed

**Comment by MrPeacockNLB** [comment]
I'm using kasmvnc in my Desktop templates for our eclipse users. It works very well and uses modern technologie transport stream. Even playing youtube videos with low bandwidth is possible.

For me it is on the owner to choose which implementation is used. As we are starting the desktopn environment in the startup script it is more important to give user feedback when one or more services are ready to use. When you think of starting a lot of services this could take some time. Espacially when you have a slow internet connection.

The feedback should not coupled to any service directly. It has to be defined by the owner how many and which services are starting.

**Comment by tidux** [comment]
Another thing to keep in mind is that remote desktop protocols are much more latency sensitive than browser based IDEs.  Maybe `coder open desktop` could ICMP ping the target IP to check latency before connecting, and throw a warning if round trip latency is over 50ms?

```
$ coder open desktop <workspace>
Pinging <workspace> [IPADDR] with 32 bytes of data:
Reply from IPADDR: bytes=32 time=93ms TTL=49
Reply from IPADDR: bytes=32 time=174ms TTL=49
Reply from IPADDR: bytes=32 time=97ms TTL=49
Reply from IPADDR: bytes=32 time=179ms TTL=49
WARNING: latency to Coder workspace <workspace> is over 50ms.  Using a browser IDE or an SSH connection to a local IDE may be preferable!
```

**Comment by phorcys420** [comment]
> Another thing to keep in mind is that remote desktop protocols are much more latency sensitive than browser based IDEs. Maybe `coder open desktop` could ICMP ping the target IP to check latency before connecting, and throw a warning if round trip latency is over 50ms?

I think that if your latency is high you will notice it very quickly.
I think that a ``coder ping`` command might be useful for debugging though.

**Comment by phorcys420** [comment]
I have a template that uses noVNC+Websockify+TigerVNC to allow for remote desktop: [basic-env](https://github.com/uwu/basic-env), you can take a look at it if you want to implement VNC in your Linux template.

As I mentioned in #6448, The Windows implementation doesn't have to use RDP at first, there are VNC servers for windows, which might be a first step towards cross-platform desktop access.

As for Guacamole, there is a "[noauth](https://guacamole.apache.org/doc/0.9.5/gug/noauth.html)" option, which could make the UX snappier without having to enter a password.
Since Guacamole is multi-protocol, I think it should be the prioritized way to bring a unified UX.

> I am using https://kasmweb.com/ for desktop apps and it’s truly amazing. Just to drop that there might be useful :)
The Coder Team is conducting tests on using KasmVNC in templates, and it works atleast as good as my NoVNC template.
I am a bit far away from the servers though, so latency isn't really comparable with my homeserver.
I don't like Kasm's UI much, but that's fine.

**Comment by mattlqx** [comment]
I have RDP setup via Guacamole and an external URL linked to a button. But I was also looking at what it would take to launch the native Remote Desktop app via button. Looks like the rdp:// or remotedesktop:// schemes are dead (and won't have worked on anything but Windows anyway). It seems like it might be possible to do with some javascript to generate an .rdp file with the right connection options.

Or would using the Coder VSCode extension to proxy open an .rdp file that way be possible?

**Comment by matifali** [comment]
We now have a community template that supports Windows RDP in browser OOB. See https://coder.com/docs/v2/latest/ides/remote-desktops#rdp-desktop
related: #6448

**Comment by matifali** [comment]
I suppose it would be possible to support RDP OOB for Windows workspaces using the approach in #6448

**Comment by bpmct** [comment]
We haven't found an awesome web-based Windows RDP client that works well inside a workspace (Myrtille works OK, but hasn't been updated in 2 years). For Linux environments, KasmVNC works quite well. We have community example templates for both.

- [Windows RDP](https://github.com/matifali/coder-templates/tree/main/gcp-windows-rdp)
- [Linux with kasmVNC](https://github.com/bpmct/coder-templates/tree/main/better-vnc)
  - [Script to install kasm on VM](https://gist.github.com/bpmct/4e51d7092089f278c91f53e344749b6c)
  
I think a `coder desktop <workspace>` would be still be significantly helpful over port forwarding and aid the user in the dashboard.

As a workaround, you can add an [external](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app#external) `coder_app` which links to a wiki with some instructions to connect via your desktop RDP:

![Screenshot 2023-06-14 at 11 49 12 AM](https://github.com/coder/coder/assets/22407953/6d61b655-13de-49e8-bee1-5a67c9787a6b)

```hcl
resource "coder_app" "rdp" {
  agent_id     = coder_agent.main.id
  slug         = "rdp"
  display_name = "RDP instructions"
  external     = true
  url          = "https://coder.com/docs/v2/latest/ides/remote-desktops#rdp-desktop"
  icon         = "https://cdn-icons-png.flaticon.com/512/2933/2933245.png"
}
```

**Comment by bartonip** [comment]
Perhaps instead of websockets you could put the VNC stream over WebRTC then everything can just be supported in-browser with no additional client libraries needed?

**Comment by sreya** [comment]
Since there's a workaround for this, closing for now

**Comment by julianpoy** [comment]
@sreya This page is still linked from https://coder.com/docs/ides/remote-desktops

Perhaps that link should be removed?

**Comment by ehfd** [comment]
Hey, I would like to introduce you to https://github.com/selkies-project/selkies-gstreamer. We are very keen on this to be integrated into Coder. We recently observed latency levels close to Moonlight (< 16 ms) when using a hardware encoder, and < 40 ms when using x264. Our CPU consumption over x264 is around 150%, much lower than KasmVNC.

https://github.com/selkies-project/selkies-gstreamer/issues/64

**Comment by ehfd** [comment]
CC @bpmct
