### ISSUE TITLE
Build Logs: "Setting up"/"Cleaning Up" has extra symbol 

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#2116]
**Coder version:**
[Coder v0.0.0-devel+3878e64](https://github.com/coder/coder/commit/3878e6434a7efec17edda367cf4bb4296cad1f2a)

**Steps:**

1. Login to Coder
2. Create/start/stop a workspace
3. Click on a build in Timeline section

**Actual result:** Setting up**0** / Cleaning Up**0**

**Expected result:** Setting up / Cleaning Up

![image](https://user-images.githubusercontent.com/35501151/172328732-9bfa8570-dab7-43a2-9bb5-b3d68ba06070.png)
![image](https://user-images.githubusercontent.com/35501151/172328689-f70039a9-f60c-4620-b1cd-6f04dcbf9ef8.png)

**Comment by tjcran** [comment]
Duplicates #2255
