### ISSUE TITLE
Workspace build logs do not automatically update duration and status on completion

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#2118]
The WebSocket closes for streaming logs once a build operation is complete (in any state, success or failure). After it closes, we should fetch the state again!

---

Coder version:

[Coder v0.0.0-devel+3878e64](https://github.com/coder/coder/commit/3878e6434a7efec17edda367cf4bb4296cad1f2a)

Steps:
1. Login to Coder
2. Create/start/stop workspace
3. Go to the Logs page and wait until the process is complete

Expected result:
DURATION shows time spent
STATUS is updated and corresponds to the actual state (Running/Stopped etc. depending on the action taken in step 2)

Actual result:
DURATION = In progress
STATUS is not updated though the action has already finished
![image](https://user-images.githubusercontent.com/35501151/172372171-5f2f72b3-638a-43e6-a044-e17eeadb9a60.png)

**Comment by f0ssel** [comment]
This is done with the changes we've made to the dashboard since this was created.

**Comment by maryna-hankevich** [comment]
retested on Coder v0.8.6-devel+c8f8c95f and was able to reproduce the issue.
Duration and Status are not updating on Logs page, you have to refresh the page to see the updated data
![image](https://user-images.githubusercontent.com/35501151/186899275-4d40ff52-dd4a-4bd0-874f-88ebe88ff66b.png)
