### ISSUE TITLE
Resource budget for each developer/team (cloud cost control)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#2121]
To manage cloud costs, it would be helpful to give developers or teams a budget/quota around how many cloud resources they can provision.

- Developer 1 uses one large 32-core workspaces
- Developer 2 uses five small workspaces for reproducing bugs on different operating systems

Developer 1 and developer 2 leverage auto-shutdown and spot instances to stay within their resource cap/budget and develop with the infrastructure they need to do their job.

We've discussed this idea before internally, but it was also suggested by @chrisae9 and @jorlina at Sonatype. Folks - feel free to add more context in this issue :)

## Ideas:

- Spending limits and alerts, similar to [GitHub actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/managing-your-spending-limit-for-github-actions)
- Integration with [Infracost](https://github.com/infracost/infracost)

**Comment by ammario** [comment]
I feel good about my [Quotas v2 RFC](https://www.notion.so/coderhq/Quotas-v2-c03453d1aba64e7d801c2cd5d1b11049).

**Comment by ammario** [comment]
An RFC here: #2988

**Comment by bpmct** [comment]
closing in favor of #2998
