### ISSUE TITLE
Tests using Cobra with `ptytest` can hang on macOS (and Windows) unless the output is consumed

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2122]
Unless `ptytest` output is consumed, a test can hang if a command outputs more than `1024` bytes (at least on macOS).

There are two ways to work around this issue:
1. Consume the output via `pty.ExpectMatch()` (ensure no more than 1024 bytes are left unread)
2. Use `cmd.SetOut(io.Discard)` instead

Since using `ptytest` is a common pattern in our tests, it'd be a good idea to rewrite it so that a hang is not possible.

Unless there's a bug to be fixed in underlying libraries, or changes to how ptys are configured, the most robust way to fix this would be for `ptytest` to buffer/consume _all_ command output, irregardless of a call to `ExpectMatch`.

A reproduction of this bug exists as a test in https://github.com/coder/coder/pull/1629 (and will be merged in and skipped on macOS and Windows).

**Comment by kylecarbs** [comment]
@mafredri I updated the title to use the `bug` label instead of the prefix!
