### ISSUE TITLE
Loudly color "admin"/"root" role

### ISSUE THREAD

**Issue by ammario** [coder/coder#2136]
I explain in #2135 why this role is dangerous. I suggest we color admin user rows bright, loud, and potentially annoying. We want to make who has access to your secrets obvious. Simultaneously, we want to discourage an excess "root"/"admin" users.

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/7416144/172468907-60cbd67a-272e-4d43-924b-bc15980b3bfe.png">

cc @AbhineetJain – this seems in your wheelhouse

**Comment by ketang** [comment]
Nailed i
<img width="1392" alt="Screen Shot 2022-06-07 at 21 49 31" src="https://user-images.githubusercontent.com/33678/172469756-f1ff4623-e624-4a60-9f73-5b46592b314d.png">
t

**Comment by ammario** [comment]
@ketang that did make me think of something else. We could show a static red banner or something when the "root" user is used. We need to keep reminding people to use another user.

**Comment by f0ssel** [comment]
May I suggest we use something in the blood family? https://www.color-hex.com/color-palette/2554

**Comment by ketang** [comment]
Applied to this background?

![image](https://user-images.githubusercontent.com/33678/172552793-cc62b0ed-4961-4a21-baa8-4ec3981c54fb.png)

**Comment by ammario** [comment]
These are all excellent ideas team. I'll go ahead and mark this as decided.
