### ISSUE TITLE
Allow disabling Auto-On on a template-by-template basis

### ISSUE THREAD

**Issue by ammario** [coder/coder#2138]
I just had this idea that for truly expensive templates (e.g a GPU monster), a template manager could disable Auto On but leave Auto Off to keep costs low. Another use case is setting up templates for a contractor or some other transient worker. Perhaps this is already on the roadmap, I don't know.

@johnstcn @vapurrmaid what do you think?

**Comment by johnstcn** [comment]
Hack/workaround: set template minimum autostart interval to something really high, say 1 year.

**Comment by ammario** [comment]
Hopefully this is easy enough to implement that our users don't resort to hacks. 🥴

**Comment by ammario** [comment]
Let's tackle in https://github.com/coder/coder/issues/3304
