### ISSUE TITLE
Add callout to Templates page that CLI is required to use template

### ISSUE THREAD

**Issue by ammario** [coder/coder#2146]
## Problem
As a new user, I'm used to a resource pages giving me full CRUD power. On the templates page, there is only Read. 

## Definition of Done
We should add a callout that users can only update, edit and delete templates from the CLI.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/7416144/172490588-68ce2758-43b1-44c9-a96f-74d9ff798564.png">

**Comment by ketang** [comment]
And who can do it.
