### ISSUE TITLE
Question Mark helpers should appear on hover instead of on click

### ISSUE THREAD

**Issue by ammario** [coder/coder#2148]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/7416144/172679219-2bd2e224-15d0-434f-9367-4a9361fd5318.png">

These should appear on hover instead of on click. On hover is more standard and prevents a click.

**Comment by ketang** [comment]
Shouldn't they *always* be present with the explanatory text appearing on hover?  How's a user supposed to know there's helpful information hiding in the link text?
