### ISSUE TITLE
Pop out all apps (e.g code-server) like we do terminal

### ISSUE THREAD

**Issue by ammario** [coder/coder#2149]
For one, it's consistent. For two, @mtm20176 thinks it will demo better. We can easily reverse this change too.

**Comment by mtm20176** [comment]
We can later make a config setting in your profile.

Devs will want their IDE in another window from their dashboard (and corporate apps like email) so they can see all of them at the same time.

@ammario @kylecarbs

**Comment by ketang** [comment]
Pop out as opposed to a new tab?  Seems pretty sensible.

**Comment by vapurrmaid** [comment]
I'd prefer the manifest-per-application (PWA-pa) approach.

We've done this in v1 with code that assembles the manifest on the fly.

An alternative is to make the entire coder dashboard a PWA, but we've gone that route before and it's not as great of an experience as solely having the applications as native-like installs.

**Comment by ammario** [comment]
@vapurrmaid that seems to be an even better enhancement.

Since the original proposal is a one line change, I think the PWA behavior should be in a separate issue. There's also the matter of how apps behave when the user refuses PWAs.

**Comment by ammario** [comment]
A large investment bank customer says pop-out is their users' preferred choice.
