### ISSUE TITLE
Templates view and template view should identify template owner

### ISSUE THREAD

**Issue by ketang** [coder/coder#2151]
In the very near future template owners will be a minority of users in a Coder installation (already true in ours) and a minority of users of any particular template.  Both the view listing the templates and the template detail view should identify that owner.

**Comment by AbhineetJain** [comment]
@ketang Does this look like a reasonable UI?

### Templates list
![Screen Shot 2022-06-08 at 11 18 44 AM](https://user-images.githubusercontent.com/7511231/172654175-9293e9c0-28b7-48b1-b5bf-02814241eb8b.png)

### Template page
![Screen Shot 2022-06-08 at 11 18 37 AM](https://user-images.githubusercontent.com/7511231/172654192-b3f96e57-7131-4ccb-998b-878dc7c104fe.png)

@BrunoQuaresma Thoughts?

**Comment by ketang** [comment]
It works for me!
