### ISSUE TITLE
Frontend view of workspace becomes inconsistent on workspace delete via CLI

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2158]
Frontend view of workspace becomes inconsistent on workspace delete via CLI

Steps to reproduce:
1. Create workspace (web or cli)
2. Open workspace view in web
3. Run `coder delete workspace` with the cli

### What do you expect to happen?

The web UI would fully reflect deletion status and allow me to continue viewing the deleted workspace and its logs. The UI would very explicitly show that this workspace is deleted.

### What actually happens?

Observe the status is not fully propagated to the UI after workspace deletion. It's also a bit racy as the workspace delete status varies between runs:

![image](https://user-images.githubusercontent.com/147409/172594169-495703bd-d4b7-4afa-8de5-5de5a184e5ce.png)

![image](https://user-images.githubusercontent.com/147409/172594612-81744a99-d551-4066-ba7e-16c5c3769cee.png)

Refreshing the page results in:

<img width="538" alt="image" src="https://user-images.githubusercontent.com/147409/172594582-56e9faa5-392f-4291-99da-4c5e21283e66.png">

### Notes

I noticed that if I don't refresh the page, I can click one of the logs (after deletion) and it will successfully show me that log, but when I return I get the same 404 error.

**Comment by ketang** [comment]
A simple thing that could work is to send them back to their workspaces list page *if* we can tack on a message that workspace XYZ is being deleted.  Even if its status is shown in the list, an acknowledgement would be good.

**Comment by mafredri** [comment]
This has been fixed at some point, no longer a problem in `v0.8.2`.

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/147409/183388632-884a5322-a026-4d61-acf4-d9e2009bd757.png">

Deletion is reflected in the UI and refresh shows the same page.
