### ISSUE TITLE
Help for coder show command in cli is missing [workspace name] parameter

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2160]
Coder version:
[Coder v0.0.0-devel+b65259f](https://github.com/coder/coder/commit/b65259f95e53e96cd8daf21a5c3de46e51a56f85)

Steps:
1. Run in cli: coder show --help

**Expected**
help contains: coder show [workspacename] [flags]

**Actual**
![image](https://user-images.githubusercontent.com/9592232/172605524-ef935287-2640-4328-8914-c285eb96f87a.png)

**Comment by kylecarbs** [comment]
It's hard to understand what's actionable here. Closing!
