### ISSUE TITLE
Allow direct API request manipulation through CLI

### ISSUE THREAD

**Issue by ketang** [coder/coder#2163]
This is a little balf-baked, so I apologize if it isn't clear.  Can we make it possible for someone to invoke the CLI to call the API and allow the user to (somehow) specify some subset of request contents (like a `jq` query path + JSON stanza)?  Perhaps `coder api` as the command?  The goal here is to make it possible for the user to use API calls or arguments not exposed in the CLI with having to construct the whole HTTP request and do the authorization and envelope.  We don't need to do anything special for the output in the general case.

However I think there could be an interesting case where you're invoking a call the CLI *does* support but want to augment the call by adding some argument that the CLI doesn't support.  Perhaps we'd want some flag to allow them to print the whole response payload in lieu of the nicely formatted CLI output (both for this and in general).

**Comment by kylecarbs** [comment]
This seems like it'd just add the header, which certainly provides value, but we might not want this use-case.

Closing for now!
