### ISSUE TITLE
Show template requirements, and that examples meant to be edited in CLI

### ISSUE THREAD

**Issue by bpmct** [coder/coder#2168]
When using `coder templates init` and `coder templates create`, the requirements for templates (often in the example README of the example) are not clear. This often leads to users creating an "aws-linux" template and seeing unexpected surprises that:

1. the template uses `~/.aws/credentials` (they need to authenticate with aws-cli)
2. the example may not work out of the box, especially with non-standard AWS accounts (no default VPC, custom security groups, requires MFA). These are just 4 things we've recently seen, but many many more are to come

Suggestions:
- Show template description in `coder templates init`
- Explain example is meant to be edited after an example is picked in `coder templates init`
- Link to example README with instructions on configuring the template, or tell the user to `cat aws/linux.README.md` for instructions configuring the template. There are pretty fantastic docs here

**Comment by kylecarbs** [comment]
@bpmct it'd be smart if we made a larger issue with some usability problems for `coder templates init`, and assigned an owner to it. I'm going to close this in favor of doing that, since there are a few issues UX wise to unpack here.
