### ISSUE TITLE
Open code-server and it prompts me to add folder but then hangs after that, with Chrome tab spinning

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2170]
I am using a Kubernetes pod as the workspace, the 'coder' templat
<img width="1662" alt="Screen Shot 2022-06-08 at 10 32 19 AM" src="https://user-images.githubusercontent.com/2022166/172657398-e51153a2-ad73-48c7-859b-d25069074352.png">
e

**Comment by bpmct** [comment]
This has been fixed

**Comment by misskniss** [comment]
@bpmct is there a PR to point to this fix to attach here?

**Comment by bpmct** [comment]
I'm not really sure what fix addressed this but I have confirmed I'm not seeing the behavior anymore cc @kylecarbs.

#2779 will also address this issue
