### ISSUE TITLE
Workspace created from "docker-image-builds" template fails to start properly

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2173]
coder version:
[Coder v0.0.0-devel+945fa9d](https://github.com/coder/coder/commit/945fa9dacfe995915cc5d066eb192aab09391878)
run mode: --dev
OS: Windows

Steps:
1. Run coder in dev mode: coder server --dev
2.  Init template: docker-image-builds
3. Create template: docker-image-builds
4. Create a workspace using this template: 
  configuration: base
  

**Expected**
Workspace is created
Status is Running
Can connect with ssh

**Actual**
Workspace is created and status is Running,
But cannot connect with ssh
In Docker: contained status is EXITED(6)

Docker log: 
+ mktemp -d -t tmp.coderXXXXXX

+ BINARY_LOCATION=/tmp/tmp.coderHSlOVl/coder

+ BINARY_URL=https://hungry-bell3.try.coder.app/bin/coder-linux-amd64

+ which curl

+ curl -fsSL https://hungry-bell3.try.coder.app/bin/coder-linux-amd64 -o /tmp/tmp.coderHSlOVl/coder

curl: (6) Could not resolve host: hungry-bell3.try.coder.app

![image](https://user-images.githubusercontent.com/9592232/172657857-9dcfc87d-a06c-4299-805c-bad0f0b9736f.png)

![image](https://user-images.githubusercontent.com/9592232/172658106-b557f212-8834-44f6-963e-4321f954d52e.png)

**Comment by kylecarbs** [comment]
This is an old issue and I'm not certain this happens anymore.
