### ISSUE TITLE
Consolidate auto off extension UI

### ISSUE THREAD

**Issue by ammario** [coder/coder#2175]
As per the decision in https://github.com/coder/coder/issues/2141 we should allow bumping the auto off whenever the user wants (except beyond the template constraints), instead of just before the workspace is shutting down.

Furthermore, we should allow the user to set a time for shutdown (instead of or in addition to?) extend by a duration. We could also make the following field editable so no additional UI components are necessary.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/7416144/172667445-a389520f-d408-46e5-82b8-1d2e2a890b0f.png">

Also the Shutdown block needs to share the timezone, otherwise the user will assume it's the Start timezone. And again, we should use the browser timezone instead of the Auto Start configured timezone. The browser timezone is more likely to represent where the user is located on page load.

---

Additional nitpick: we should standardize on 12 hour since most of our customers are in the US/CA.
<img width="106" alt="image" src="https://user-images.githubusercontent.com/7416144/172894268-796b9247-d396-4761-a4d1-f2db83dae73d.png">

**Comment by ammario** [comment]
> I don't remember if I shared this, but I think we should have a way to pop up the dialog, and we should also have one click +30 minutes and +2 hours.

If you could click a +1h button over and over again, that could be a cool way to add time.

Why do you think it should pop out in a new window? How does that help the user experience?

**Comment by ketang** [comment]
Yeah, same idea, but I chose +30 because I don't think people necessarily want the full hour.  You could also argue with equal validity for +15 minutes and +1 hour.

Giving them the pop out gives them a way to specify some exact value instead of in 30 minute or 2 hour increments.  Some people are fussy like that.  Or they want to do an 24 hour extension without clicking 12 times.  I don't think clicking 12 times is a big deal, but I guarantee people will want something that feels less mindless.

**Comment by ammario** [comment]
> Yeah, same idea, but I chose +30 because I don't think people necessarily want the full hour. You could also argue with equal validity for +15 minutes and +1 hour.
> 
> Giving them the pop out gives them a way to specify some exact value instead of in 30 minute or 2 hour increments. Some people are fussy like that. Or they want to do an 24 hour extension without clicking 12 times. I don't think clicking 12 times is a big deal, but I guarantee people will want something that feels less mindless.

Since there will be a way to edit the wall-clock time of shutdown, there is a workaround to spam clicking the bump. In light of this, do you still think there should be a way to customize the bump amount in the UI?

**Comment by ketang** [comment]
> in light of this, do you still think there should be a way to customize the bump amount in the UI?

Well, it's not so much customizing the increment as it is choosing one of a couple of present increment amounts.  Although inevitably customers will want to be able to customize them I guess.

I think it's always better if you can do things in one click versus several.  Whether it's better enough *right now* 🤷🏾‍♂️ .  But eventually?  I have no doubt.
