### ISSUE TITLE
Use systemd to start the agent in the `gcp-linux` template

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2178]
The example `gcp-linux` template executes the coder agent in a startup script as root.

This results, among other things, in the developer being root in their workspace when they SSH in, which is not a great experience.

We should:

 * [x] Run as a normal user
 * [ ] Start the agent via systemd to set up standard environment, use journal for logging, etc

**Comment by bpmct** [comment]
Gonna close this to reduce open issues.
