### ISSUE TITLE
non-interactive option for creating a workspace in CLI

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2181]
I'm doing stress testing on coder and have a shell script that will create 5 workspaces, but when you run `coder create` it prompts the user with `Confirm create? (yes/no)`

Can we add a non-interactive mode parameter so I don't have to type yes 5 times?

<img width="657" alt="image" src="https://user-images.githubusercontent.com/2022166/172703878-72a9313b-8e93-4881-9b5a-208b1dd1f9e0.png">

**Comment by mtm20176** [comment]
Thanks, I just did the main help thinking it would be a parameter for any command. Thanks.

**Comment by Emyrk** [comment]
@mtm20176 can we close this issue? Was that the solution?
