### ISSUE TITLE
Add the ability to rename a workspace. Currently workspace must be deleted and a new one built to workaround this.

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2188]
## Problem Statement
Users must delete a workspace and build a new one if they decide they want to name a workspace something else. It's something that's expected and a really inconvenient and poor experience if you are not able to do this.

## Definition of Done
Users can change the name of a workspace from UI or CLI if they decide they want to name their workspace something else.

**Comment by ammario** [comment]
I agree in principle. A problem is this means that persistent resource names (e.g the disk) cannot be named based on the workspace name. Perhaps that's an anti-pattern anyways.

**Comment by ketang** [comment]
Definitely an anti-pattern to *link* them that way.  Naming them that way isn't terrible because we need to name them *something*, but we shouldn't attach semantics.

**Comment by ammario** [comment]
> Definitely an anti-pattern to _link_ them that way. Naming them that way isn't terrible because we need to name them _something_, but we shouldn't attach semantics.

In GCP at least, a disk's name is its ID. There is no way to rename a disk, except by light copying it via snapshot.

**Comment by ketang** [comment]
I think no matter what we're going to have to treat persistent-across-builds resources differently from throw-away-and-start-over resources.  If that means different naming conventions, okay; it just goes on the pile of other things we'll need to manage differently.

**Comment by tjcran** [comment]
@misskniss earmarking for next sprint

**Comment by ammario** [comment]
@tjcran I see this was marked for a sprint but what happened to this issue? It's a pretty big PITA to build up a workspace and then have to recreate it since the name is a bit off. Like, I don't want to actually keep my workspace named `donkus`...

**Comment by tjcran** [comment]
Duplicates #3000 closing this one in favor of that one which has more detail
