### ISSUE TITLE
Reduce the number of timeline entries in Workspace dashboard and put the rest in an accordion with pagination

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2189]
This is feedback from a v1 customer. Devs don't care about it except maybe the last few entries. Administrators care, but they don't own the workspace and can pull this from logs via other mechanisms.

@kylecarbs

**Comment by tjcran** [comment]
One idea: What if we have tabs on the workspace page so we can keep each view simpler and "hide" the settings/readme/timeline on separate tabs? 
![image](https://user-images.githubusercontent.com/7042112/175069756-8fe100fc-7598-4047-9578-8a66c0bb03b1.png)

**Comment by kylecarbs** [comment]
We'll do this, but I don't think it's actionable *right right* now.
