### ISSUE TITLE
Add resource IDs when hovering over display names in the UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2190]
### Problem 
Many users will want to execute workspace actions from the CLI rather than the UI out of necessity or preference and may want to switch from doing something in the UI to the CLI very quickly. Without unique IDs present in the UI, it can be difficult to make the association for which object you want to act on in the CLI.

### Definition of Done
Users should be able to quickly get an ID in the UI so they can execute on the object from the CLI, find it in Audit Logs, or take other actions. 

Some Ideas: Similar to how we do this in v1 with showing image hash in a workspace.  This could also be present directly on the detail page with a clipboard icon so it can be copied to clipboard quickly.

**Comment by ketang** [comment]
When you hover where?  Everywhere you hover over a workspace name or a template name or a user name?
