### ISSUE TITLE
gcp-* templates should have a powerful default image

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2192]
Currently {gcp-linux, gcp-vm-container, gcp-windows} templates gives an e2-medium machine, which is only effectively 1 vCPU and 4 GB RAM.  My phone is more powerful than this!  We want example templates to hook people on how awesome cloud workspaces are, and so they should default to being _faster_ than an ordinary laptop.

AC:
 - machine type default is e2-standard-8 -- 8 vCPUs and 32 GB RAM.
 - parameter allows bigger machines: e2-standard-16, e2-standard-32, e2-highcpu-16, e2-highcpu-32, e2-highmem-8, e2-highmem-16

**Comment by mtm20176** [comment]
@spikecurtis It's a cost reason, we've seen in v1 trials, that prospects can get surprised by cloud costs. (someone has to pay for this stuff) I see your point, but maybe create a couple of flavors.

**Comment by kylecarbs** [comment]
Let's await feedback before we do this. It'll be helpful to reference this in the future if it comes up.
