### ISSUE TITLE
add code-server to all our quickstart templates

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2193]
### Problem
Every quickstart template should include code-server as a Workspace application.  This reduces time to actually using the product for development.

### Definition of Done:
 For each quickstart template:
  1. create the template with `coder init`, `coder template create`
  2. create a workspace using the template
  3. verify that code-server appears in the Workspace applications on the UI
  4. start coder-server and verify it runs

Please reference the proposed "Template" strategy outlined in #2179

**Comment by tjcran** [comment]
I agree that this should be in _some_ of the templates but we do not want this in all of the templates. Many users/customers will not want code-server/vs-code in their workspace and while adding it to all of them will reduce the number of steps for someone who wants code-server anyway, it's adding an extra burden to remove code-server from the template for those who do not want it (and that's a pretty substantial proportion)

**Comment by ketang** [comment]
Where do we stand on this?  Gonna do something or leave it alone?

**Comment by tjcran** [comment]
> Where do we stand on this? Gonna do something or leave it alone?

It's something we will do. It's not _critical_ this week or anything. But it is the direction we should go with the "Quick start" templates.
