### ISSUE TITLE
Fail to connect to Windows and Linux aws workspaces via ssh 

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2203]
Coder version:
[Coder v0.0.0-devel+74fe38e](https://github.com/coder/coder/commit/74fe38eb3dc293832f2dd4fb3f60a355b5a9a7de)
OS: windows
running in dev mode

Fail to connect via ssh from UI, with CLI using: ssh [workspace] and coder ssh [workspace]

Steps:
1. Start coder via: coder server --dev
2. Init templates: aws-linux and aws-windows
3. Create templates
4. Create a workspaces from these templates

**Expected**
Can connect via ssh in CLI and via Terminal on UI

**Actual**
Via ssh and coder ssh cannot connect - connection is hanging (coder config-ssh was executed)

On UI: resources status is Connecting

![image](https://user-images.githubusercontent.com/9592232/172869807-c5a9b432-1d0c-4434-bd15-abecd17e0148.png)

In log: 
GET /api/v2/workspacebuilds/a79c62ca-7563-4bdd-ba2e-651774dde221/resources 
response is:
[{"id":"8fdd8fd2-36e4-4b20-a6d1-a27c33cd6e93","created_at":"2022-06-09T14:01:04.6784212Z","job_id":"e7855f46-33b5-4bd3-9b73-77429366ffa9","workspace_transition":"start","type":"aws_instance","name":"dev","agents":[{"id":"1d1240a1-e0dd-4fd1-9656-5fced5b1ea13","created_at":"2022-06-09T14:01:04.6789359Z","updated_at":"2022-06-09T14:01:04.6789359Z","status":"connecting","name":"dev","resource_id":"8fdd8fd2-36e4-4b20-a6d1-a27c33cd6e93","architecture":"amd64","environment_variables":null,"operating_system":"linux","apps":[]}]}]

**Comment by kylecarbs** [comment]
This has been fixed with #2198!
