### ISSUE TITLE
All example templates should include dotfiles

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2215]
There is one example template that prompts for a dotfiles repo (`docker-with-dotfiles`) and sets it up, but all our example templates should do this.

AC:

1. For each example template:
  a. Create the template with `coder template init`, `coder template create`.
  b. Create a workspace with the template.  Verify that you are asked for a dotfiles repo name
  c. Start the workspace and verify that dotfiles are applied.
  d. Create a new workspace with the template, leave dotfiles parameter blank.
  e. Start the workspace and verify it comes up correctly.

2. Retire the `docker-with-dotfiles` example since the normal `docker` template will have dotfiles.

**Comment by spikecurtis** [comment]
My goal is for users to just be able to leave the parameter blank and get a workspace with no dotfiles.

**Comment by ketang** [comment]
Right, but admins/project owners are also part of the audience.  I want to avoid them accidentally misunderstanding how our product works.

**Comment by spikecurtis** [comment]
Do you think commentary in the template is sufficient?

Having one template that doesn't have dotfiles doesn't feel very discoverable, and how would we even decide which one?

**Comment by ketang** [comment]
> Do you think commentary in the template is sufficient?

Mmm... I think people can be lazy and cautious.  I want to show them something useful that actually works.

> how would we even decide which one?

If all else fails roll a die.

**Comment by spikecurtis** [comment]
Could have a template called `xxx-no-dotfiles` which increases discoverability (at the expense of having a lot of options) and shows a working example.

**Comment by ketang** [comment]
Good compromise.  I assume we'd have a parallel `yyy-with-dotfiles`?  Maybe this would be a way to show off how to include other scripts for reuse?  Meaning we have a short file for `yyy-with-dotfiles` that defines the dotfiles and includes a bunch of other files for the `yyy` functionality, then we have an almost empty `yyy-no-dotfiles` that *only* includes the other files.

**Comment by ammario** [comment]
This would create a lot of duplication between templates and be difficult to maintain. I believe [the documentation](https://coder.com/docs/coder-oss/latest/dotfiles) is sufficient for now.
