### ISSUE TITLE
Support generalized query language on back end

### ISSUE THREAD

**Issue by ketang** [coder/coder#2217]
Per #2176 some filters applied to the search are transformed from terms in the search query to different parameters on the back end.  What we should do instead is support a fully general query/search string language that can be passed to the back end via the API or CLI so that those clients have the same power as web UI users.

@Emyrk

**Comment by Emyrk** [comment]
Completed here: https://github.com/coder/coder/pull/2232

**Comment by Emyrk** [comment]
CLI work still needed to support raw query

**Comment by ketang** [comment]
#2644 is the next step
