### ISSUE TITLE
Generalized window management/PWA framework for all custom apps

### ISSUE THREAD

**Issue by ketang** [coder/coder#2218]
Ideally we can support every app launching in any of:
* in-page embed/iframe sort of thing
* new tab
* new window
* PWA

With no incremental work per app other than your standard generic app setup.

Can we create a generic PWA or PWA framework that makes it easy to wrap arbitrary apps?  The idea is that any app can become a separate entry in `<Ctrl>/<Cmd>-<Tab>` and capture all keystrokes without us having to do work for each individual app.  Any app customers "install" in Coder can be launched as a PWA.

**Comment by kylecarbs** [comment]
I don't think we should inject a PWA routing system for each app. There are a lot of undesired UX nuances by doing that. We can discuss once we get feedback that we should. Apps can deliver their own PWAs for now.
