### ISSUE TITLE
Icons for templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#2221]
## Acceptance Criteria

The template admin can configure an icon for their template, as part of the `main.tf`

Would be great if templates could optionally have icons instead of being limited to the first letter. Since there is already icon support for the Coder agent, I suggest using the same format, but for the Coder provider. The Coder provider already has one template-specific option: `url`.

e.g:
```diff
provider "coder" {
  url   = "https://coder.bpmct.net" # optional: custom access URL for template
+  icon = "https://avatars.githubusercontent.com/u/2232217?s=200&v=4" # optional: custom icon for the template
}
```

<img width="1618" alt="Screen Shot 2022-06-09 at 5 29 10 PM" src="https://user-images.githubusercontent.com/22407953/172955822-08c32402-154d-432c-a0f3-c268891b5f46.png">

I think this icon can also go next to the workspace. It provides more information and is more visually appealing than the letter itself. 

<details>
  <summary>Also somewhat interesting, templates could allow users specify a custom workspace icon</summary>
  
If the workspace list grabbed the icon from its own metadata and not the template's, templates can ask users for a custom icon. I don't know if anyone would use this

```
variable "custom_workspace_icon" {
  default = ""
}

provider "coder" {
  icon = var.custom_workspace_icon
}
```
</details>

**Comment by mtm20176** [comment]
@bpmct I second that. Love it. Brings the UI to life versus a boring list view.

**Comment by ketang** [comment]
What if we supported a more general specification comparable to `<img src="...">`?  That way we could support data URIs as well.  Maybe that comes for free with the above, but I wanted to make sure.

We need to be careful that this doesn't try to reach any hosts it shouldn't though.  Like `file:///` URLs are just a big nope.

**Comment by bpmct** [comment]
related #2262

**Comment by kylecarbs** [comment]
@bpmct should we just do #2262 for now?

**Comment by bpmct** [comment]
Would it be difficult to do both together? I like the extensibility of adding an image URL, just like `coder_app` does but agree that emojis are easier to add.

**Comment by misskniss** [comment]
@kylecarbs are you up for owning this one? How is this going to be different from the emojis issue?

**Comment by kylecarbs** [comment]
The emojis one is just for emojis, this is for external custom icons.

**Comment by kylecarbs** [comment]
@bpmct I tried the provider route, and that unfortunately is only used as inputs for a Terraform operation. It's not included in the state file, so we'd have to parse Terraform to extract that value (which feels jank).

What do you think about including this in the front matter of the README we already parse? e.g.
```md
---
icon: /icon/code.svg
---

# Develop on Google Cloud

...
```
I'm not a massive fan of this approach, but it would promote people to make READMEs with their templates, which we want anyways.

**Comment by bpmct** [comment]
I think it'd solid doing metadata that way!

**Comment by ketang** [comment]
I like doing this independent of any particular provisioning technology.

I think we're at risk of disordered growth by applying this pattern of embedding metadata in `README.md`.  I see a few options:
1. continue down this path organically -- could become a mess
2. continue down this path but with an explicit goal of supporting YAML blocks for template metadata at the top of `README.md`
3. Take this type of metadata outside of `README.md`; this is not exclusive of the others, of course.

**Comment by phorcys420** [comment]
what about using a manifest file instead?
e.g ``manifest.toml`` or whatever and it'd contain those keys instead, I'm not a fan of adding weird meta at the beginning of the terraform template personally.

**Comment by BrunoQuaresma** [comment]
@ketang some questions:
1. Why it would be a mess?
2. I don't feel supporting YAML inside of the README would be an interesting idea. Front matter is the most popular "metadata notation" for markdown files.
3. I think having another file to manage information adds more complexity without adding too much value IMO. @phorcys420 I like the idea of having a manifest file but sounds too much for now, to only add the icon 🤔 no strong opinion on this tho

**Comment by phorcys420** [comment]
> I think having another file to manage information adds more complexity without adding too much value IMO.

it does add more complexity but it also makes it so that your template is at least runnable in "regular" terraform without modifications.
I also don't really like to deviate from a well-established standard either.

in my opinion adding another file is still manageable since the people making the template are the power users/administrators and they surely will know enough to just add a manifest file, even better if it's documented.

> Sounds too much for now, to only add the icon 🤔 no strong opinion on this tho

it is a bit too much for just an icon but I really don't enjoy the top-of-file manifest idea because it deviates from the standard and also feels a bit hacky to me.

**Comment by bpmct** [comment]
We should do this in the README for now. Please leave comments in #3531 and #2987 respectively if you have thoughts on a consolidated metadata format.

**Comment by BrunoQuaresma** [comment]
Updated points to 8 because of the necessary "pre" work
