### ISSUE TITLE
Automatically keep active workspaces alive

### ISSUE THREAD

**Issue by ammario** [coder/coder#2233]
In v1, we detected when users were engaging with workspaces to keep them alive.

This made for a great developer experience since the developer never had to think about "bumping". The workspace magically stayed on for however long they needed it. While this was great for developers, it was painful for those responsible for cloud costs. Tabs left open overnight and untraceable ghost activity beefed up cloud bills.

Organizations fall on both sides of this trade off.

I believe there's a way to get the best of both worlds here.

We could add a flag like `coder config-ssh --keep-alive`. Every tunnel command in the SSH config would carry along that `--keep-alive` flag, and every coder CLI spawned with the flag would periodically bump the workspace. Idempotent bumping (see #2230) is a necessary prerequisite.

Eventually we could bump within native IDE extensions. We could implement a similar keep-alive behavior on requests to `coder_app`s so browser customers get activity-based shutdown as well.

---

Implementation note: reuse the notification goroutine

**Comment by ketang** [comment]
What does this `--keep-alive` do exactly?  Is it a bump or a pause or...?

**Comment by johnstcn** [comment]
I'm imagining that it just periodically sends a request to `/api/v2/workspaces/:workspace/extend` so that the workspace never gets turned off.

**Comment by ketang** [comment]
Hmm.  My computer never sleeps unless I'm away from home.  I also don't exit VS Code.

**Comment by ammario** [comment]
Yeah that's a challenge. The customer in question is fine with that. The turning off is a big nice to have for them. It also still works well in multi-workspace situations. You're unlikely to keep multiple VS Codes open with multiple workspaces all the time.

**Comment by ketang** [comment]
> You're unlikely to keep multiple VS Codes open with multiple workspaces all the time.

uh 😬

**Comment by ammario** [comment]
> > You're unlikely to keep multiple VS Codes open with multiple workspaces all the time.
> 
> uh 😬

You're an edge case of an edge case of an edge case of an edge case.

**Comment by ketang** [comment]
Possibly.  We should gather data.

**Comment by ajmeese7** [comment]
Contributing data: I'm with @ketang on this one! I love to keep all my projects/workspaces open so I can bounce between them with ease.

**Comment by ammario** [comment]
@ajmeese7 I agree and do the same thing.

Perhaps instead of activity detection at the SSH level we can do something more intelligent as a VS Code plugin. For example, we could bump the workspace on user-interaction.

**Comment by ketang** [comment]
For automatic keep alive, we'll probably want to expose a fair number of knobs and switches, primarily around which events count for liveness and how long their effects are.  Given how tricky this can be to get right, I don't want to have it entirely in opaque, unparameterizable code.

**Comment by ammario** [comment]
What MVP can we start with?

**Comment by ketang** [comment]
Replicate v1 but expose the knobs and switches.

**Comment by ammario** [comment]
> Incrementally replicate v1 but expose the knobs and switches.

What does "replicate v1" mean? Why do you think we need to expose the knobs to right now? Which knobs do you think we should expose?

**Comment by ketang** [comment]
I was kind of waving my hands because I haven't actually looked at the v1 implemention.  But presumably it's basically some set of event types that count as activity and some grace period after each occurrence during which shutdown is deferred.  What we could do is just expose a map from event type to grace period.  We'd have sensible defaults that they could override, either by adding an event type, adjusting the grace period for an event type, or excluding an event type.

**Comment by mark-theshark** [comment]
Relying on a CLI command parameter setting is limited and flawed.

The customers, except for 1, use Coder completely browser-based, so some semblance of idle detection is not met with the CLI configuration.

To be clear, the largest of these customers actually does NOT like the existing idle behavior of v1. Their desired state is if the auto-shutdown behavior set by admins is 4 hours, then in 4 hours, if nothing was going on in the IDE or terminal, the workspace (in this case, a Kubernetes pod, is destroyed)

So their desired state is not met by v1 either.

@ammario @ketang @johnstcn

**Comment by ketang** [comment]
Ah I didn't mean that it would be in the CLI.  It would be server-side.

I think giving customers control is the only realistic option.  We don't know how do it perfectly, and giving them more control is a good compromise until we figure it out.

**Comment by ammario** [comment]
It looks certain we're going to do this. Let's discuss implementation in #2995.
