### ISSUE TITLE
Workspace schedule form: 8h is displayed for workspaces with "Shutdown: Manual" when open schedule for edit

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2237]
Coder version:
[Coder v0.0.0-devel+92bda0d](https://github.com/coder/coder/commit/92bda0d2c1b6663d97c10f2804f3cb34d16e6172)

If I have a workspace with manual shutdown and open Edit schedule - in the field  "Time until shutdown" 8 is displayed, but I expect 0 as it was set.

Steps:
1. Create a workspace
2. Open workspace and click Edit schedule
3. Set value to 0 in  "Time until shutdown" 
4. Save schedule -> workspace Schedule displays "Shutdown: Manual"
5. Click Edit schedule

**Expected**
I expect the same value I have set: 0

**Actual**
8 is displayed

https://user-images.githubusercontent.com/9592232/173067955-6323b43a-937d-4858-b0a3-30022a665a82.mp4

**Comment by vapurrmaid** [comment]
@ammario 
@johnstcn 
@ketang 

I can see how this could be confusing, but I wanted to express that this was initially intention to guide users towards a non-manual, typical schedule.

Right now we don't have a way to distinguish between "schedule has never been set before" and "schedule is manual". On the FE, both just appear as `ttl: 0`.

So we can remove this initialization, if desired, but to me it seems like a useful suggestion.

WDYT ?

**Comment by ammario** [comment]
Yeah @vapurrmaid I noticed that too and was confused. Not being able to set an ephemeral auto off when the schedule was manual was confusing. I think we can put an edit icon by the "Manual" text and a time selector pops up. That seems like a good UX to me.

**Comment by ketang** [comment]
I think the flaw here is overloading `0`.  The typical thing in these cases is to use `-1` as the special case value.

**Comment by johnstcn** [comment]
Still an issue: 
![image](https://user-images.githubusercontent.com/4949514/184617838-1e55befc-06b9-4777-8ae9-739ceeb7107a.png)
