### ISSUE TITLE
Windows cmd: broken symbols in logs

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#2239]
Coder version:
Coder v0.6.5+fff59ef

Steps:

In windows cmd, create a template / workspace
See the logs

Expected result:
symbols are displayed correctly, e.g. if a task/action is completed successfully a check mark should be displayed

Actual result:
symbols are not displayed correctly
![image](https://user-images.githubusercontent.com/35501151/173086530-a2b02b78-fa70-4537-bd8d-26f697981c3c.png)

**Comment by kylecarbs** [comment]
While this is an issue, it seems so low priority that I'm going to close until someone complains!
