### ISSUE TITLE
Pre-launch UI/CLI Copy review

### ISSUE THREAD

**Issue by tjcran** [coder/coder#2242]
## CLI Changes
- [x] `--access-url can be specified instead` should be changed to `If you have your own domain, you can use the --access-url flag instead`
- [x] After Coder is running, it spits out an "Access URL". instead of `access-url: *.try.coder.app` -> Access your Coder UI in a browser at: [access url]
- [x] Invert provisioner daemons so url, username, password are next to each other

## UI Changes

- [x] Workspace tooltip help copy: A workspace is your development environment in the cloud. It includes the compute infrastructure and tools you need to code
- [x] Sentence casing: “Workspace Schedule”
- [x] What is template? tooltip
    - [x] “What is template?” —> “What is a template?”
    - [x] “…for your *team’s* workspaces using Terraform.”
- [ ] Add agent and resource tooltip to Templates page
- [x] If we don’t have a template description, don’t put “No description” — just leave it blank
    - [ ]  Maybe this should display the description in the README metadata for the template
- [x] “Create a new workspace from a Template” ← make the T lowercase

**Comment by ketang** [comment]
>  “…for your *team’s* workspaces using Terraform.”

Hmmm... not a blocking concern, but I'm not completely sure this is the terminology we want to use.
