### ISSUE TITLE
Add JetBrains Projector to example templates

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2243]
Many v1 customers use Projector to access JetBrains IDEs. This should be added to v2.

Note: JetBrains Projector is JetBrains IDEs like IntelliJ and PyCharm in a browser.

Definition of Done: 
This should support Jetbrains on Linux (parity to V1)

**Comment by ketang** [comment]
I consider this a must-have for the MVP because it is necessary for feature parity with v1.

**Comment by misskniss** [comment]
WE consider this complete based on the strategy decided in #2179
