### ISSUE TITLE
coder dotfiles - besides running git clone and install.sh what does it do?

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2244]
I notice we wrap basic commands in our CLI.  What is coder dotfiles doing besides `git clone <dotfiles repo>` and `install.sh`?

**Comment by f0ssel** [comment]
It basically follows this algorithm - https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-codespaces-for-your-account#dotfiles

It clones the repo if it doesn't exist, pulls if it does, and if the repo is different is first makes a backup and moves the existing repo before doing a new clone. Then it runs an install script if it finds one in the order of that list, and if not it will symlink all files starting with `.` to the home directory or directory specified by flag. 

It works in an idempotent way so it's safe to run over and over.

**Comment by ketang** [comment]
A quick note: even if it doesn't seem like it's doing anything complicated, I think the very existence of this feature makes it far more likely that an ordinary developer or team will use version-controlled dotfiles.  They absolutely could do it themselves, but most of them won't and don't.

**Comment by f0ssel** [comment]
Yes, I totally see this as a guiding hand for "a golden path" in coder.
