### ISSUE TITLE
Start time on workspace page is not recalculated to current time zone

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2245]
Coder version:

[Coder v0.0.0-devel+92bda0d](https://github.com/coder/coder/commit/92bda0d2c1b6663d97c10f2804f3cb34d16e6172)

Steps:

1) I have created a workspace with time zone set as Europe/Warsaw and start time 9 AM
![image](https://user-images.githubusercontent.com/9592232/173102783-71613266-f322-422f-9877-994cb964c40a.png)

2) When I open UI -> workspace page displays my local time zone and start time also 9 AM, but if take into account that it should be 9 AM Warsaw time in Minsk time zone it should be 10 AM)

![image](https://user-images.githubusercontent.com/9592232/173104319-b6c0ed29-445b-4650-8f24-235e208e32fb.png)

3) On edit the time zone that I have specified at creation and time that was set is displayed

![image](https://user-images.githubusercontent.com/9592232/173103287-d79de1e6-54cf-49d5-af8c-9ace1cc3d0c6.png)

**Comment by vapurrmaid** [comment]
This is a valid bug, we are displaying the timezone based on browser but the cron string is not converted. I can address this shortly.

**Comment by ketang** [comment]
The cron string should not be converted.  It should be stored with the user's selected time zone.
