### ISSUE TITLE
Stress testing building 8 workspaces from 8 terminals shows a lot of queuing

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2246]
How many concurrent workspaces can Coder build?

I ran a test of 8 pod-based workspaces being created from CLI and a bunch are in queue status.

**Comment by ketang** [comment]
Can you provide more information on durations?

**Comment by tjcran** [comment]
and what templates? what infrastructure? were these on your laptop? or were they targeted at a cloud?

**Comment by tjcran** [comment]
@mark-theshark can you specify the details of the Coder deployment and template?
