### ISSUE TITLE
Persist query params on login redirect

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#2252]
@kylecarbs sent me a link to a terminal (https://dev.coder.com/@f0ssel/f0ssel.coder/terminal?reconnect=f9b87eca-1eb1-40b2-b108-7b038f3cf2b5) and I had to log in. Once I logged in, it took me to a new terminal session with a different reconnect ID. We should persist (probably all?) query params so this ID stays the same.

**Comment by ketang** [comment]
I think all.   I can come up with a few paranoid exceptions, but I don't think they're warranted at this point.
