### ISSUE TITLE
Cannot activate a suspended user in the dashboard

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#2254]
You can suspend a user, but cannot un-suspend a user, making this a permanent seeming action from the dashboard. 
![image](https://user-images.githubusercontent.com/19379394/173126994-2f19f506-2d0e-4b02-ab07-c92230a4ac7d.png)

You should probably be able to do this, right?

**Comment by ketang** [comment]
I'm gonna say this is a must fix.
