### ISSUE TITLE
cli: collect all schedule-related commands under `coder schedule`

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2258]
A lot of schedule-related commands have grown organically around the root command:
- `coder autostart {set,unset} <workspace>`
- `coder ttl {set,unset} <workspace>`
- `coder bump <workspace>` 

For discoverability, collect these all under one single `coder schedule` command:
- `coder autostart set <workspace> <schedule>` -> `coder schedule start <workspace> <schedule>`
- `coder autostart unset <workspace>` -> `coder schedule start <workspace> manual`
- `coder autostart show` -> `coder schedule show`
- `coder ttl set <workspace> <duration>` -> `coder schedule stop <workspace> <duration>`
- `coder ttl unset <workspace>` -> `coder schedule stop <workspace>  manual`
- `coder ttl show` -> `coder schedule show`
- `coder bump <workspace> <duration>` -> `coder schedule override <workspace>`

**Comment by ketang** [comment]
Still not thrilled about `bump`.  How about `adjust`?  We may also want a `reset` in there.  Should there be a `coder schedule set` as well?  That seems like it would be like your `coder schedule start <workspace> <schedule>` except without actually starting.

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/coder/pull/2402
