### ISSUE TITLE
Dashboard spams `/users/{name}/workspace/{name}` route on workspaces page

### ISSUE THREAD

**Issue by coadler** [coder/coder#2260]
![image](https://user-images.githubusercontent.com/6332295/173156314-602fc31b-5240-4234-9a51-ec9a9a02c404.png)
![image](https://user-images.githubusercontent.com/6332295/173156339-a6c0de6b-287b-4088-ae77-118f747e54fe.png)

**Comment by coadler** [comment]
I understand that some sort of polling is currently necessary, but the speed of it seems pretty high to me.

**Comment by ketang** [comment]
I'm seeing what looks like roughly a once per second frequency.  I agree with Colin.  This should be much less frequent.

Any reason this isn't using long polling or web sockets or whatever?

**Comment by ketang** [comment]
I think this is obnoxious enough that we should address it before big release.

**Comment by coadler** [comment]
It's likely we just haven't built out a websocket endpoint for this data yet.

**Comment by ketang** [comment]
Are you aware of a reason that it doesn't just happen automatically with every API call we implement?

**Comment by vapurrmaid** [comment]
I CC'd @f0ssel on this - it's a purposeful poll of the workspace every second. Since we don't rely on a countdown timer for scheduling, I see now harm in reducing this from every second to every 5+.

Last I recall we wanted to replace that poll with a WS, but it wasn't built out yet.

Please read here: https://github.com/coder/coder/pull/1362#discussion_r872912586

**Comment by vapurrmaid** [comment]
The workspace's current status/transition impacts how various pieces display, such as start/stop/cancel buttons, time when it will shutdown, showing build progress etc.

**Comment by ketang** [comment]
But isn't that all server-side state anyway?  And wouldn't pushed updates be able to do the same thing?

**Comment by vapurrmaid** [comment]
I think maybe I caused confusion with the word `purposeful`, let me revisit what I mean:

- @presleyp was building out the status bar in `v2 beta`
- we didn't have a WS route in the backend yet, and no one was avail to really look deeply into it
- we pinged @f0ssel (him and I also talked in Slack and Discord) letting him know we don't like this pattern (from v1 mistakes) but that it was shortest path for now
- we want to replace this behavior with WS; we do use real-time data (ish) on that page

I hope that clears it up, sorry!

**Comment by f0ssel** [comment]
If we touch anything here it should be to just use the websocket on the frontend - I can take this on this week if we feel it's a priority.

**Comment by vapurrmaid** [comment]
We can very cheaply move the 1s to 5s (0.5 pts effort) - _if we want to_. I do agree that the WS is the best approach.

**Comment by ketang** [comment]
Let's kick the can down the road (to contradict/restrain my above enthusiasm).  This is not our highest leverage problem.

**Comment by kylecarbs** [comment]
To make the UI update in a snappier way, we should use a WebSocket to publish updates to this page instead.

**Comment by kylecarbs** [comment]
Seems like this is fixed.
