### ISSUE TITLE
Add support for emojis on templates

### ISSUE THREAD

**Issue by ammario** [coder/coder#2262]
## Acceptance criteria

The template admin can configure emojis to accompany their template as a part of the `main.tf`.

Schema TBD.

![image](https://user-images.githubusercontent.com/7416144/173161081-005a2aff-df86-4311-9979-3cea228164af.png)

Wouldn't this be beautiful?

(idea cred @kylecarbs)

**Comment by Explosion-Scratch** [comment]
Yea but with twemoji

**Comment by ammario** [comment]
@Explosion-Scratch nice idea! We're looking into it.

**Comment by mtm20176** [comment]
👽

**Comment by Explosion-Scratch** [comment]
> @Explosion-Scratch nice idea! We're looking into it.

It wasn't my idea lolit was @kylecarbs apparently

**Comment by ketang** [comment]
This is a silly thing that is also good to have.

We can do emoji in the names already, right?  This would be a dedicated field for selecting one icon?

**Comment by ketang** [comment]
Seems like we should do this for users and workspaces too.  None of this needs to happen immediately, but if easy...

**Comment by kylecarbs** [comment]
I think we add an `icon` column that is a URI. For now it can be `emoji://handwave`, but eventually it can be `file:///` etc.

**Comment by ketang** [comment]
Is `emoji://handwave` a real thing, or did you just invent it?

We don't want to allow `file://` ever.  If you're referring to an icon embedded in the archive, then we should go another way, for instance requiring them to have a file `icon.json` or something.

**Comment by Explosion-Scratch** [comment]
yeah, not exactly sure why to use `emoji://`, wouldn't just using a lookup table and allowing users to choose be fine? Emojis.json was made for this purpose (find on GH)

**Comment by ketang** [comment]
I actually thought `emoji://` was pretty clever.  We could forge a new path!  Modifiers and combinations like skin tone would be interesting though.

**Comment by Explosion-Scratch** [comment]
> I actually thought `emoji://` was pretty clever. We could forge a new path! Modifiers and combinations like skin tone would be interesting though.

"forging a new path" was what you did in 1990. Now it'd just be inefficient, hard to implement, never used by anyone else, and probably insecure

**Comment by ammario** [comment]
> This is a silly thing that is also good to have.
> 
> We can do emoji in the names already, right? This would be a dedicated field for selecting one icon?

The big problem with emojis in the name as opposed to a separate field is it makes it far harder to work with names in the CLI and programmatically.

**Comment by misskniss** [comment]
@kylecarbs are you up for owning this?

**Comment by kylecarbs** [comment]
Sure!

**Comment by ketang** [comment]
While emoji:// would be a neat gimmick, data URIs should be just fine:
```data:text/plain;charset=utf-8;base64,8J+MrvCfpog=```

Should be read as 

```🌮🦈```

**Comment by ammario** [comment]
Can we do https://github.com/coder/coder/issues/2221 instead of this? https://github.com/coder/coder/issues/2221 would still allow emojis, but the more reasonable use case is using OS/Cloud/Software logos as described in that issue.

**Comment by kylecarbs** [comment]
Makes sense to me. I'll swap it out.

**Comment by mark-theshark** [comment]
😞

**Comment by BrunoQuaresma** [comment]
Reopening this, since icons can support emojis if users pass the image path, we want to provide a better experience by adding an emoji picker.
