### ISSUE TITLE
When setting up production mode (PostgreSQL), the docs do not specify coder login must be run to create the admin user

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2266]
This:
https://coder.com/docs/coder-oss/latest/install#:~:text=To%20run%20a%20production%20deployment%20with%20PostgreSQL%3A

needs to be clarified until this is automated.

Production is not a good word, since --dev mode is in-memory and evaluators will want to use Postgres

It may be helpful to clarify pre-steps that database newbies may not know:

1. Install Postgres e.g., brew install postgres and start the database engine
2. Create the super postgres user
3. Create the coder database
4. Create the user and grant rights for the coder database
5. Start coder `coder server` ...

**Comment by khorne3** [comment]
- Fixed with deploy that includes postgres
- CLI now prompts for coder login
- Will address Postgres basics in a separate issue
