### ISSUE TITLE
Add Helm chart to host Coder on Kubernetes

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2267]
### Problem
For users who want to run their Coder dashboard, and workspaces, in Kubernetes, there should be a Helm chart install that will allow users to install and upgrade their Coder deployment. 

### Definition of Done
The first pass will allow for a simple deployment with just a Coder dashboard, but subsequent helm charts should include HA options and the ability to run containerized workspaces in the same K8s cluster.

This is for customers wanting to host Coder entirely on Kubernetes.
```
# The coder/coder namespace is occupied by v1, so we should maybe change it for OSS?
helm install coder coder/coder --namespace coder
```

**Comment by kylecarbs** [comment]
Ideally, we allow customers to provide a `coder.env` file that contains arbitrary environment variables that can be used for configuration. We should not map each configuration value to a key in Helm, as this adds a significant maintenance burden.

This `coder.env` file would allow customers to arbitrarily pass environment variables too, which seems useful. The container should ship with a PostgreSQL sidecar container, similarly to v1. It should not use the built-in PostgreSQL database, as that would not support high-availability (which is likely to be used for Kubernetes).

**Comment by thalesfsp** [comment]
Any updated on this?

**Comment by misskniss** [comment]
This one is currently blocked. @tjcran can you add the items to the comments here around that?

**Comment by ammario** [comment]
Can we include a setup template for the Kubernetes cluster in the MVP? My thoughts are it's a day of work at most beyond the rest of the feature but makes the whole thing twice as valuable. Bare in mind that our users are looking for the Coder platform entirely on Kubernetes, not just the control plane.

**Comment by tjcran** [comment]
> Can we include a setup template for the Kubernetes cluster in the MVP? My thoughts are it's a day of work at most beyond the rest of the feature but makes the whole thing twice as valuable. Bare in mind that our users are looking for the Coder platform entirely on Kubernetes, not just the control plane.

I think that's super reasonable. It won't be "HA" but I think for the <10-15 devs usecase that's just fine.

**Comment by ammario** [comment]
The definition of done in this issue includes running workspaces within the Kubernetes cluster, so I'm reopening.

**Comment by deansheather** [comment]
@ammario @tjcran ^ This should probably be split up into multiple tickets, we already have a separate ticket for HA support #3227. IMO the MVP of the helm chart (being able to deploy coder onto k8s with helm) has already been achieved.

**Comment by tjcran** [comment]
I agree with that. I'll close this one and create an issue for having auto-import for k8s "built-in"
