### ISSUE TITLE
Update Getting Started section to docs

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2271]
### Problem
Like with v1, assume someone knows nothing. Just running our curl command is not a good outcome for every user.

The existing Quickstart is infrastructure-specific and does not cover IDEs, like code-server, or local VS Code and JetBrains.

https://github.com/coder/coder/blob/main/docs/quickstart.md

### Definition of Done
Docs "Getting Started" should include steps on the following
- set up Postgres
- Install Coder
- Build a template
- Build a workspace
- Setup browser and local SSH IDEs (VS Code, JetBrains)

**Comment by ericpaulsen** [comment]
I can take this on if we still deem it relevant. @mark-theshark @tjcran @misskniss

**Comment by tjcran** [comment]
> I can take this on if we still deem it relevant. @mark-theshark @tjcran @misskniss

@ericpaulsen seems good to me! go for it!

**Comment by bpmct** [comment]
@ericpaulsen - I know you were doing some changes to getting started. Should we keep this open?

**Comment by ericpaulsen** [comment]
@bpmct - yeah, let's keep it open. I'm refactoring this our `generic quickstart` page now to have more of a "Getting Started" flow.

**Comment by kylecarbs** [comment]
Seems like this is done.
