### ISSUE TITLE
Be less cowardly about auto-starting failed workspaces

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2279]
# What

Currently Coder will only attempt to autostart workspaces where:
- An autostart schedule is set
- The workspace is not currently transitioning (previous provisioner job completed)
- The workspace is currently not running (i.e. the latest transition is not start)
- The latest provisioner job did not encounter an error

This means that:
- If the autostart build fails, it won't try again until the next scheduled interval
- If the previous stop failed for any reason, it won't try again until the next scheduled interval
- If the user manually started the workspace and it failed, it won't try again until the next scheduled interval

It makes sense to be a bit more assertive. Exactly _how_ assertive is TBD, but the following is proposed:

A workspace should be selected as a candidate for autostart if:
  - An autostart schedule is set
  - The workspace is not currently transitioning (previous provisioner job completed)
  - The workspace is currently not running (i.e. the latest transition is not start)
  - No more than 3 previous "start" transitions failed

# Why

Because in the real world, things just fail sometimes and you just have to try again.

**Comment by johnstcn** [comment]
bump

**Comment by kylecarbs** [comment]
No customers are asking for this right now, so I'm going to close.

@johnstcn reopen if it's important we tackle this in the next 30 days!
