### ISSUE TITLE
Make `created_by` field in templates table not null

### ISSUE THREAD

**Issue by AbhineetJain** [coder/coder#2283]
#2228 added a `created_by` field to the Templates table to track the user that created the template. This field was kept nullable since it was not clear how to populate the field in existing records. @kylecarbs suggested that we make the `created_by` field not nullable and default to the first-created user instead, otherwise it just very odd design for the data model.

**Comment by AbhineetJain** [comment]
I wonder if there's a case for both pieces of information to be _maintained_. `maintained_by` does come with the overhead of allowing someone in the org to update that field, who could do it etc.

**Comment by kylecarbs** [comment]
I think it'd be helpful to understand the maintainer.

If someone gets promoted or leaves a company and is no longer the maintainer, we'd hate for them to display as the contact in created_by.

**Comment by AbhineetJain** [comment]
Makes sense. We can update the field name, but I am guessing the functionality also changes? Like the user would probably want to specify the maintainer when creating the template (we can default to the creator), and have an option to update the maintainer (for some restricted roles).

**Comment by kylecarbs** [comment]
Makes sense to me!
