### ISSUE TITLE
Rename `personalize.sh` to `personalize` in dogfood template

### ISSUE THREAD

**Issue by ammario** [coder/coder#2284]
See title. There's no reason to restrict to shell scripts.

This is pending @kylecarbs uploading the template to git.

**Comment by f0ssel** [comment]
can we just move it to dotfiles flow?

**Comment by ammario** [comment]
@f0ssel do you mean call `coder dotfiles`? I'm not sure how it would get the git URL.

**Comment by f0ssel** [comment]
@ammario We should just add a dotfiles url parameter on the workspace template, and run `coder dotfiles $dotfiles_url` in the startup script.

**Comment by ammario** [comment]
@f0ssel makes sense
