### ISSUE TITLE
Declaratively deploy and configure Coder with Terraform 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#2291]
Instead of managing Coder via ClickOps, it would be nice to add support deploying for deploying Coder (e.g EC2/AMI or Kubernetes cluster, LoadBalancer, replicas, provisioner count) and configuring Coder (organizations, users, templates, admin settings) via Terraform modules and the Coder provider.

```sh
resource "coder_deployment" "coder" {
   access_url = "https://coder.myorg.com"
}

resource "coder_organization" "frontend" {
  name = "Frontend"
  templates = [aws, kubernetes]
}

resource "coder_template" "aws" {
  name = "aws"
  directory = file("./templates/aws-linux")
  parameters = # integrate with secrets provider with tfvars
}
```

Use cases:

- Staging/production Coder deployments
- Avoid configuration drift
- Faster recovery after downtime
- Feature testing
- Demos (spin up a Coder instance with 40 users, 5 organizations, 5 templates)
- Load testing (same reason as above)

**Comment by bpmct** [comment]
My hacky version: https://github.com/bpmct/coder-via-terraform

**Comment by kylecarbs** [comment]
@bpmct that repo is private!

**Comment by bpmct** [comment]
whoops - fixed
