### ISSUE TITLE
code-server hangs when opening a new folder

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#2294]
when navigating to `File` -> `Open Folder...`, code-server `4.4.0` refreshes and perpetually hangs on a blank screen.

![Screen Shot 2022-06-13 at 12 48 39 PM](https://user-images.githubusercontent.com/9683576/173413761-fd4f554e-e7e2-4d3b-9dce-902a24acbae3.png)

this is not an issue with code-server 4.4.0 in Coder Classic, so it's safe to assume this bug is isolated to `coder/coder` and not code-server.

console error:

![image](https://user-images.githubusercontent.com/9683576/173415661-35caea8d-31d9-41c3-b06a-7f9b43b57d1f.png)

**Comment by bpmct** [comment]
I was able to reproduce this as well. Super odd

**Comment by kylecarbs** [comment]
#2779 will fix this!

**Comment by kylecarbs** [comment]
Tracking this in #2779!
