### ISSUE TITLE
bug: putUserRoles incorrectly computes roles

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2295]
spotted during code read.

```
	// User is the user to modify.
	user := httpmw.UserParam(r)
	roles := httpmw.AuthorizationUserRoles(r)
	apiKey := httpmw.APIKey(r)

	if apiKey.UserID == user.ID {
		httpapi.Write(rw, http.StatusBadRequest, httpapi.Response{
			Message: "You cannot change your own roles.",
		})
		return
	}

	var params codersdk.UpdateRoles
	if !httpapi.Read(rw, r, &params) {
		return
	}

	// The member role is always implied.
	impliedTypes := append(params.Roles, rbac.RoleMember())
	added, removed := rbac.ChangeRoleSet(roles.Roles, impliedTypes)
```

The problem is that `roles` here is the current roles of the person calling the API, not the roles of the user you are trying to change.

cc @Emyrk

**Comment by kylecarbs** [comment]
This seems like a pretty big security hole... @Emyrk thoughts?

**Comment by Emyrk** [comment]
What branch is this on? I think this was already fixed.

User is the user param in the url. `actorRoles` is the user trying to do the operation.
https://github.com/coder/coder/blob/aa5c479b20d20e69b02932bfabbb30fa3c24d7c5/coderd/users.go#L527-L529

The diffset is from the user's roles, **not** the actor's roles.
https://github.com/coder/coder/blob/aa5c479b20d20e69b02932bfabbb30fa3c24d7c5/coderd/users.go#L549-L550

**Comment by Emyrk** [comment]
Ah this is an old issue. I'll just write a unit test to confirm it's fixed and push that to close this ticket

**Comment by Emyrk** [comment]
This was resolved
