### ISSUE TITLE
Display text to add a template README if one does not exist

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#2299]
## Description

As a user browsing a template, the README and AGENT sections should be display some text in the UI.

## Motivation

This provides information to the user about this template.

## Examples/Ideas

If Agent is missing, put "unknown".

If REAMDE is missing, put "Oh no! This template doesn't have a README. Want to add one?" and link to template on GitHub

**Comment by jsjoeio** [comment]
> The README idea is great though, and we should totally do it!

Awesome! I will assign to myself.

**Comment by kylecarbs** [comment]
I'm going to close this for now, because we haven't gotten requests for it, and doesn't seem like it will be priority in the short-term.
