### ISSUE TITLE
Consistency between `coder template` and `coder templates`

### ISSUE THREAD

**Issue by AbhineetJain** [coder/coder#2303]
Our Templates List page shows the command `coder template init` to create the first template. However the [docs](https://github.com/coder/coder/blob/main/docs/templates.md#manage-templates) use `coder templates init`. We do support both, but it might be nice to have consistency in our communication.

## Screenshot

![Screen Shot 2022-06-13 at 3 34 41 PM](https://user-images.githubusercontent.com/7511231/173430955-53a9b109-8991-4dfb-b520-e117d430b4e5.png)

**Comment by ketang** [comment]
Canonical should be singular for "template," "workspace", "organization," and "user" (did I miss anything?).
