### ISSUE TITLE
ux: make it clear that actions under Workspace Timeline can be clicked

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#2304]
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/173431961-f9c16bf4-15c2-4300-9a8a-6992d94d2d92.png">

It wasn't obvious that I could click into these actions on the Timeline to see logs.

**Comment by AbhineetJain** [comment]
The `chevron-right` icons were added to provide that idea to the user that the rows in the Timeline table are clickable (not just the actions), they also change background on hover. Do you have any ideas about how we can make it more obvious? You may find some previous discussion in https://github.com/coder/coder/issues/2021.

**Comment by misskniss** [comment]
This looks like it was complete but there is not a PR linked.

**Comment by jsjoeio** [comment]
Ah, missed the `chevron-right`. One idea is to move the `chevron-right` to the start of the line. This is how GitHub does it:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/3806031/173917270-fd09b39c-efb1-49e8-b14d-532aeab8aec4.png">

I think that would solve this.
