### ISSUE TITLE
Failed workspaces cannot be deleted, because the delete fails too

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2313]
Addition from @kylecarbs :wave: 

If infrastructure fails to delete, it's impossible to remove a workspace from Coder forcefully. 

![image](https://user-images.githubusercontent.com/7122116/186455755-c4aa2978-1eaf-4417-ab23-06f119ec671f.png)

It's unclear what to do at this point because I'm happy forcefully drop the infrastructure here (in this case a Docker image reference). Maybe after build failure, we allow a force deletion if you're an admin?

@mafredri I'd love your thoughts!

---

<img width="946" alt="image" src="https://user-images.githubusercontent.com/2022166/173469806-eee42b53-3ebe-4ee8-8796-fe6f8f564280.png">

Expected state: Rollback and do not create metadata for the workspace in Coder if the create fails.

**Comment by ketang** [comment]
I wonder if on the back end we want to allow replacing an existing workspace if we pass in the equivalent of `--force`.  The initial issue here should be fixed cleanly, but I wonder about other inconsistent state issues that may arise.

**Comment by bpmct** [comment]
We've introduced `coder workspace delete <name> --orphan` to address this: #3849
