### ISSUE TITLE
Confusing Resources Status when workspace is stopped

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#2315]
Coder version:
[Coder v0.6.6+cbde8e8](https://github.com/coder/coder/commit/cbde8e8b91097412b2ae0daa72d1b698b61584bc)

Steps:
1. Stop a workspace
2. Observe Resources section

Actual result: Status is "Connecting" but the workspace is stopped so this is confusing
![image](https://user-images.githubusercontent.com/35501151/173565758-a3cd1216-c018-4077-a494-f1163c94a4cb.png)

Expected result: less confusing status, "disconnected" maybe

**Comment by ammario** [comment]
Fixed

<img width="1176" alt="Screen Shot 2022-08-18 at 4 23 04 PM" src="https://user-images.githubusercontent.com/7416144/185497583-d5994564-ecd4-4e63-93a8-41e917bb46b4.png">
