### ISSUE TITLE
TTL >24h has a confusing interaction with auto start

### ISSUE THREAD

**Issue by ammario** [coder/coder#2318]
As a user, if I set my template TTL to 27h and my auto-start to daily at 9am, my workspace schedule behavior looks like this:

```
1. Start at Mon 09:00am
2. Stop  at Tue 12:00pm
3. Start at Wed 09:00am
4. Stop  at Thu 12:00pm
etc.
```

I think we can all agree this is confusing. 

### Solution Ideas
* Limit max TTL is 24h across the board
  * Caveat: this restricts the power of TTL when auto-start is unset
  * Variation: only restrict the TTL when auto-start is enabled
* Reset countdown on each auto-start, so TTLs >24h never trigger
* ???

**Comment by johnstcn** [comment]
@ammario Would we be OK with the following behaviour being possible:

```
1. Start at Mon 09:00am
2. Stop at Tue 08:59am
3. Start at Tue 09:00am
4. Stop at Wed 08:59am
...
```

**Comment by ketang** [comment]
I think the least surprising behavior if a workspace is on during at its scheduled autostart time that we extend its duration to the maximum of its current duration and the scheduled duration.

Examples with a 9am start and 9 hour duration/6pm shutdown:
* if OFF at 9am: start
* if ON at 9am with shutdown extended to 7pm: do nothing
* if ON at 9am with pre-autostart shutdown at 10am: extend shutdown to 6pm

**Comment by johnstcn** [comment]
...unless this would violate template-level maximum, in which case we would extend up and until that maximum and no more.

**Comment by ketang** [comment]
Even if it's before when the workspace would have stopped if it was freshly autostarted?  I don't understand what the benefit of that is.  I think we should put the caveat on the template-level maximum not the workspace schedule, if for no other reason than that we'll have 10x+ more people seeing the latter than the former, and they'll be generally less versed in the details and nuances.

**Comment by ammario** [comment]
The interplay between auto start and auto off will never be obvious so we might as well avoid it. 

Here's what I propose:

Limit out auto off to the smallest distance between auto on intervals (or never, if permitted by template).

**Comment by ammario** [comment]
Actually even that is confusing when you reduce your auto start interval....

The 24h hard max is looking best to me.

**Comment by ketang** [comment]
Yeah the problem with smallest distance is weekends leading to inconsistent behavior.

The hard 24 hour thing is fine.  It's not going to be sufficient for when we allow varying schedules, e.g. 9am-6pm on MWF and 10am-6pm on TTh.

**Comment by ammario** [comment]
> The hard 24 hour thing is fine. It's not going to be sufficient for when we allow varying schedules, e.g. 9am-6pm on MWF and 10am-6pm on TTh.

How would that schedule break it? Both of those ranges are 12h so they would be within the 24h max?

**Comment by ketang** [comment]
Sorry those were meant as examples of variation not *breaking* examples of variation.
