### ISSUE TITLE
Add automatically setup PostgreSQL database for simple production setup

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#2321]
The requirement of a PostgreSQL database to run a production deployment of Coder has led us to create `dev` mode, which spawns an in-memory database for tinkering with Coder. A downside of this is data loss on exit, which can leave hanging cloud resources.

The ideal user experience is to install and run PostgreSQL transparently so all data is persisted. Using [embedded-postgres](https://github.com/fergusstrange/embedded-postgres), we can achieve this in a few lines of code:

```go
ep := embeddedpostgres.NewDatabase(
	embeddedpostgres.DefaultConfig().
		BinariesPath(config.PostgresBinPath()).
		DataPath(config.PostgresDataPath()).
		RuntimePath(config.PostgresRuntimePath()).
		Username(username).
		Password(password).
		Database(database).
		Port(uint32(tcpAddr.Port)),
)
err = ep.Start()
if err != nil {
	return err
}
defer ep.Stop()
```

[embedded-postgres](https://github.com/fergusstrange/embedded-postgres) is tested on Mac, Windows, and Linux. This allows us to remove `dev` more entirely, allowing setup to become:

```
$ coder server
> To use an external PostgreSQL database, specify `CODER_PG_CONNECTION_URL`.
> Would you like Coder to start a PostgreSQL database for you? *yes* 
```

Our `systemd` default would specify this via the command line, allowing for:

```bash
# Install Coder
$ curl -fsSL https://coder.com/install.sh | sh

# Start Coder
$ sudo service coder start

# Login to Coder
$ coder login http://localhost:3000
```

`--dev` would be removed, as it's likely to cause more setup confusion than it solves. Users can access the database by running:

```bash
$ coder server pg
```
This will output the embedded database connection information, allowing for backups, data migration, and all other functionality of a _normal_ PostgreSQL database.

**Will CLI tests use embedded-postgres?**

Nope, we'll keep some flag to allow for the in-memory database to be used for speed.

**Will we still create an initial user automatically?**

Nope, this should simplify and merge these user experiences. On `dev` mode right now, we automatically create and authenticate for easy setup. We will no longer do this.

**Will dogfood user an embedded-postgres?**

Yes.

**Will we recommend customers to use embedded-postgres in production?**

I'd recommend they backup the `~/.config/coder/postgres` directory on a CRON, but it should be safe to use.

**Will migrations work?**

Yes, it's just a normal PostgreSQL database, but started by Coder.

**Comment by bpmct** [comment]
Highly in favor of this. Cool that we're considering using standard tools (Wireguard + Postgres) for the fast setup. No "black boxes" :)

**Comment by f0ssel** [comment]
I think this is a great improvement to the development experience as well, since we often have to build and rebuild the same user stories over and over between compile. I tried this package a while back and noticed that it somehow downloads/extracts the correct postgres runtime at start. Will this work for the user's you've gathered feedback from? I think it should be fine in a gneral sense since you've already outlined putting this data in the postgres config directory, but wanted to point it out since it was less "static" of an implementation than I was expecting.

**Comment by kylecarbs** [comment]
It does download the binaries, which we'll make explicit in the prompt. I'd wager the vast majority of users will be comfortable with this, and the portion that aren't still have a great solution - setup PostgreSQL yourself!

**Comment by spikecurtis** [comment]
we need to ensure that the embedded postgres only listens on the local loopback, not any external interfaces, otherwise we expose a security hole.

**Comment by f0ssel** [comment]
> It does download the binaries, which we'll make explicit in the prompt. I'd wager the vast majority of users will be comfortable with this, and the portion that aren't still have a great solution - setup PostgreSQL yourself!

Cool just wanted to make sure we were aware - I was kind of surprised that was how it worked. I'm good with a prompt as long as using it in tests still works and is easy still 👍

**Comment by ketang** [comment]
Hmmm so this wouldn't work for someone trying to run on an airgapped network?

**Comment by ammario** [comment]
@ketang it would, just that they would have to put the database and server on the same box.

@kylecarbs brilliant idea!

**Comment by ketang** [comment]
Uuuurgh...  I don't like that at all.  At minimum we need to have a nice error message (on startup without a database configured ping `8.8.8.8` or something?), but I'd like to be able to support this for real not too long from now.  Obviously that's easier said than done.

**Comment by ammario** [comment]
> Uuuurgh...  I don't like that at all.  At minimum we need to have a nice error message (on startup without a database configured ping `8.8.8.8` or something?), but I'd like to be able to support this for real not too long from now.  Obviously that's easier said than done.

If by "for real" you mean in a large scale production setting then I don't think there's any avoiding an independent postgres. If you have multiple coderds you have to have a central DB.

The binaries are embedded so I don't see what a ping does.

**Comment by kylecarbs** [comment]
If a user is air-gapped, they can install PostgreSQL manually (just like it is today).

**Comment by ketang** [comment]
I understand that they can.  I dislike that they don't have as simple a startup as people on Internet-connected machines.

**Comment by jsjoeio** [comment]
This sounds like a big win for DX! I see @ketang's point and agree we should have a nice error message at the minimum for air-gapped users. We can always iterate on the UX after we get the first version out too. @bpmct and I can help test.
