### ISSUE TITLE
Documentation doesn't explain how to configure IDEs

### ISSUE THREAD

**Issue by ammario** [coder/coder#2324]
We [mention](https://coder.com/docs/coder-oss/latest/workspaces#editors-and-ides) that we support IDEs but we don't explain how to set them up?

**Comment by mark-theshark** [comment]
@ammario We discussed in a docs meeting this week as an item to add. Thanks for adding this too.

**Comment by khorne3** [comment]
https://github.com/coder/coder/pull/2388

**Comment by ammario** [comment]
#2388 is good but I actually meant this issue from the perspective of template apps.

**Comment by khorne3** [comment]
@ammario similar to this https://github.com/coder/coder/issues/2375?

**Comment by ammario** [comment]
Haha yep
