### ISSUE TITLE
Add global flag to disable non-web connections

### ISSUE THREAD

**Issue by ammario** [coder/coder#2327]
Security-conscious organizations may want all access via the browser.

This should be an Enterprise-only feature. This would disable the public route to negotiate with a workspace agent.

**Comment by ammario** [comment]
@kylecarbs is there a way for the agent to boot with no tunnelling capabilities?

**Comment by kylecarbs** [comment]
Not right now, but it'd be trivial to add. We can add it as an option to the Terraform resource so it can be restricted on a per-template basis.

**Comment by ammario** [comment]
A flag on the `coder_agent` resource makes sense to me.

**Comment by kylecarbs** [comment]
This has been added to Enterprise!
