### ISSUE TITLE
Template error needs to be more verbose

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#2332]
In the screenshot below, there is an issue with the right operand of one of my resource arguments. I don't have any visibility into which resource is throwing this error, and how it can be resolved.

![Screen Shot 2022-06-14 at 5 58 24 PM](https://user-images.githubusercontent.com/9683576/173702932-6e76e21b-0d1d-47b7-b659-8db5526fb4d8.png)

**Comment by ericpaulsen** [comment]
Default terraform error provides the level of detail required to address the issue:

```
Error: Invalid operand
 
  on 2nd.tf line 38, in resource "google_cloud_run_service" "renderer":
  38:         image = "gcr.io/" + var.project_id + "/renderer:latest"
 
Unsuitable value for left operand: a number is required.
```

**Comment by ketang** [comment]
I only skimmed the change, but it looks like you did what I was going to suggest, which is to never let Terraform exit unhappily without printing its last output.
