### ISSUE TITLE
Set environment variables to detect we're inside a Coder workspace

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2340]
> As a user, I want my generic dotfiles to behave a specific way in Coder workspaces

I'm proposing we set the following environment variables inside workspaces:

```
CODER_WORKSPACE_NAME=maf/work
CODER_WORKSPACE_TEMPLATE=docker
CODER_WORKSPACE=true
```

I think the `CODER_WORKSPACE_TEMPLATE` is optional/nice-to-have for extra customization based on env, but the other two seem kind of like standard practice.

Example from Codespaces:

```
CODESPACE_NAME=mafredri-myrepo-a3rj5r302v9
CODESPACES=true
```

This can be done even today by detecting `CODER_AGENT_*` variables, but I consider this "internal logic" that the user can't rely on.

**Comment by ketang** [comment]
I say we go for `CODER=true`

Workspace UUID and workspace build UUID would be good to have.  Also any tunnel-related information.  Maybe the control plane URL too.

**Comment by ammario** [comment]
One could set these environment variables within their template using attributes from the [`coder_workspace`](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#schema) resource as a workaround.

**Comment by mafredri** [comment]
I think we could start with just `CODER=true` always set by the agent, and point to the template for additional environment variables as @ammario suggested. That'd be very low-effort.

I think `CODER=true` is a minimum must-have, though. It's something users can rely on in their dotfiles, when sharing dotfiles, when sharing coder integrations, etc. If it's set in a template then sometimes it works, sometimes it doesn't.

**Comment by ketang** [comment]
This is not well Googleable, but it looks like `CODER` is unlikely to collide with any other environment variables.

Add to the list of later things:
* distribution
* enabled features
* product version
* template version
* workspace authorized users
