### ISSUE TITLE
CI test/go/postgres is flaky

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2347]
these tests are timing out en-mass on many runs, e.g. https://github.com/coder/coder/actions/runs/2502674150/attempts/2

Need to investigate, but some possible issues:

 * we set parallel=1 and timeout=5m --- are these tests just taking too long?
 * are any postgres workers getting OOM killed?
 * are there deadlocks in parallel tests?
 * does it matter that we don't clean up test databases when test runs are over?

**Comment by spikecurtis** [comment]
I _believe_ that's what we are doing.

**Comment by spikecurtis** [comment]
These tests regularly take longer than 5m on my M1 Pro Mac, so unsurprising they'll take longer than 5m on a GitHub runner, which is 2 core 7GB RAM.

**Comment by spikecurtis** [comment]
Today I learned that go test has _both_ `-p` which is how many packages to test in parallel, and `-parallel` which is how many tests per package to run in parallel.  So, the total number of simultaneous postgres connections could be as high as their product.  GitHub runner is 2 vCPU, so that could be 4 or 16 with neither option set (depending on whether hyperthreading shows up for vCPUs), which doesn't seem crazy.

**Comment by spikecurtis** [comment]
@kylecarbs what do you think about ripping out the code that spins up multiple containers?  I don't see why we want local tests to suffer from docker container spin up and spin down.

**Comment by kylecarbs** [comment]
Entirely happy with that @spikecurtis!

**Comment by spikecurtis** [comment]
our tests appear to be leaking TCP sockets, at least on macOS.  Even with `-parallel=2` we end up with ~100 TCP connections to postgres for a big package like clitest, and these persist until the process terminates.  I'm going to try to repro on Linux...

**Comment by spikecurtis** [comment]
also appears to leak on Linux.

**Comment by ammario** [comment]
Thank you for your work on this @spikecurtis. The christmas tree CI log always irks me.

**Comment by spikecurtis** [comment]
I found the leak!  It's in the migration.

**Comment by misskniss** [comment]
This issue resulted in a collection of bugs that Spike has filed that do not make sense to track as an Epic. Closing this as resolved by the creation of those issues .
