### ISSUE TITLE
`coder dotfiles` has no clear advantage over a personalize script

### ISSUE THREAD

**Issue by ammario** [coder/coder#2357]
@f0ssel what advantage does `coder dotfiles` have over a script like:

```bash
#!/bin/bash

pushd ~/dotfiles/
git pull
./install.sh | tee /tmp/personalize.log
```
?

The behavior of `coder dotfiles` is confusing to me. For example, `stow` is the commonly touted way to manage symlinks with dotfiles, but we have our own symlink logic. If we can achieve most of the behavior with a recommended script, is there a point in shipping the `coder dotfiles` command?

**Comment by ammario** [comment]
[Note that Codespaces](https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-codespaces-for-your-account#dotfiles) shares our `coder dotfiles` implementation

**Comment by ketang** [comment]
Looks like to be fully compatible we'd have to support all of:
```install.sh
install
bootstrap.sh
bootstrap
script/bootstrap
setup.sh
setup
script/setup```
Not just `install.sh`

**Comment by ammario** [comment]
Related: https://github.com/coder/coder/issues/2387

**Comment by f0ssel** [comment]
Yup, it's to give a way to support the "dotfiles flow" matched by others in the market so everyone can bring their own. If I use install.sh, and you use a vanilla repo with no install script, we both can use a template that calls `coder dotfiles $dotfiles_url`  and it work. Without this command, your startup script would have to do the dotfiles logic, handle the default symlink behavior, try the different scripts if they exist, make backups if they change, etc. 

Some documentation around this will probably help answer some of this up front.

**Comment by f0ssel** [comment]
> For example, stow is the commonly touted way to manage symlinks with dotfiles

source? I used codespaces and gitpod as examples to follow, but I'm interested in learning how others are doing things.

**Comment by ammario** [comment]
> > For example, stow is the commonly touted way to manage symlinks with dotfiles
> 
> source? I used codespaces and gitpod as examples to follow, but I'm interested in learning how others are doing things.

There are [a few posts](https://www.google.com/search?q=stow+dotfiles&rlz=1C5CHFA_enUS890US890&oq=stow+dotfiles&aqs=chrome.0.0i512j0i22i30j0i15i22i30j0i22i30l2.1219j0j4&sourceid=chrome&ie=UTF-8) I've read on the topic.

**Comment by f0ssel** [comment]
What action items do you want to get out of this issue?

**Comment by ammario** [comment]
I was working on personalization docs and I wasn't sure what to recommend the user. I'll go with `coder dotfiles` for now and suggest a variable for the user to input their Dotfiles URI. Since we share the implementation with Codespaces I think the behavior is safe.
