### ISSUE TITLE
remove persistent & ephemeral resources refs from docs

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2358]
#2333 removes persistent & ephemeral resources from CLI.  We need to update docs https://coder.com/docs/coder-oss/latest/templates to match.

**Comment by khorne3** [comment]
@spikecurtis Can you clarify what it means by removed from the CLI? Are these concepts still in the product otherwise (so we'd need to keep 'em documented, but maybe at a later point of the doc?)

**Comment by spikecurtis** [comment]
The idea is that "persistent" resources are around even when you stop the workspace and "ephemeral" are only there when you start it.  There is nothing wrong with that conceptually, but we are no longer attempting to tell you whether a resource is persistent or ephemeral on the CLI, and I believe the UI doesn't do this either.

So, those words don't appear anywhere in the user experience, so I'm not sure whether we need to give specific names to those concepts anymore: instead just explain that when you stop the workspace, some resources might remain, e.g. volumes that store your data.  When you _delete_ the workspace, all resources are removed.

**Comment by spikecurtis** [comment]
At the very least, the docs referenced shows CLI output that is no longer accurate and needs to be fixed.

**Comment by khorne3** [comment]
https://github.com/coder/coder/pull/2388/files#diff-26b8f82bf01d9104510f3de20f093df1f2c7cd9f3d5111e31e22c3b8bcd87129
