### ISSUE TITLE
Link to docs to describe more detail about Template Init options and how to use them

### ISSUE THREAD

**Issue by misskniss** [coder/coder#2368]
As a user, I want a place to find more information beyond the single sentence description of the options provided when I run `coder template init`.

<img width="443" alt="Screen Shot 2022-06-15 at 10 35 25 AM" src="https://user-images.githubusercontent.com/2394436/173880202-e9b0f99e-c506-4761-be91-c02ac19740a0.png">

Implementation Notes:
Add a link to the template readme.

**Comment by bpmct** [comment]
@misskniss what do you think about adding a section below `A template...`?

```text
Read more about our examples here: https://cdr.co/examples
```
