### ISSUE TITLE
Email address should be accepted as a user identifier in the API

### ISSUE THREAD

**Issue by deansheather** [coder/coder#2373]
## Bug Summary
Example: `coder users show john@example.com` does not work and returns an error: `status code 400: "user" must be an existing uuid or username.`

# Definition of done
In addition to UUID, `"me"` and username, users should be able to query themselves or other users by email address instead. Administrators might not know a user's username, but they'll definitely know their corporate email address and will want to be able to query user info by email address.

**Comment by kylecarbs** [comment]
Let's wait until someone asks for this. It's simple enough for us to add, but I think it's fine to procrastinate this a bit. Closing for now!
