### ISSUE TITLE
How-To: "install.sh" section of install guide is missing information for new users

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2378]
# Steps to reproduce:

## What do I do to set up postgres?
- Create a Linux VM
- Run the install script (version 0.6.6)
- Observe instructions on `/etc/coder.d/coder.env` 
- Look into this file and observe postgres-related variables
- Wonder what to put in here

--> Solution: 

1) Add barebones DB setup steps e.g.

```bash
# Postgres setup on Debian/Ubuntu
sudo apt-get install -y postgresql
sudo systemctl start postgresql
sudo -u postgresql psql
create role coder with login;
create database coder owner coder;
\password coder
<enter password>
```

2) Also add a sample commented postgres connection URL into `/etc/coder.d/coder.env` because I keep needing to look this up and I presume others would also
```
# postgresql://[user[:password]@][netloc][:port][/dbname][?param1=value1&...]
```

## How do I login?

Once the install script is finished and you start the coder service, you may not see the `coder login <host>:<port>` message as it's buried in the depths of `journald`.

--> Solution: also emit this directive in the install.sh output

e.g.

```bash
To get started, run `coder login <host:port>`
```

**Comment by khorne3** [comment]
https://github.com/coder/coder/pull/2430 fixes the DB issue; the CLI now includes login instructions
