### ISSUE TITLE
User-scoped default variables

### ISSUE THREAD

**Issue by ammario** [coder/coder#2387]
As a template admin, I want to automatically clone user dotfiles. If I could use the standard input syntax, the user has to re-enter their dotfiles URI whenever they create a workspace.

Now, we could fix this in the v1 way where we have some built-in dotfiles key value in the user preferences. Alternatively we could implement these as environment variables.

Or, for a similar amount of effort, we could let users define arbitrary key value pairs for input variables. For example, a user may want to set a default region.

## Secrets

As a user, I have many secrets I need in my environments. I want my DatoCMS token, perhaps a GitHub PAT, or maybe even my GCP service account. This _could_ be done via user-scoped environment variables. It's also kind of insecure considering the agent's giant process tree. I'm not sure how I feel about this one. It would also require marking some variables as secrets or requiring some "reveal" action for every variable.

**Comment by ammario** [comment]
I was thinking these would be environment variables, so they wouldn't impact the template syntax.

**Comment by f0ssel** [comment]
That makes sense, we have a hook to inject envs into the agent already, if we have an interface where users can interact with this secret store its trivial to get these values into the workspace.

How would you image this works? We want these to be user scoped, but we may also want admins to be able to set them and restrict control. Do you have any thoughts on how that would look?

**Comment by ammario** [comment]
I could see admins wanting to override/restrict them if those variables competed with other significant variables.  For example, a user overriding `PATH` is threatening to break most templates.  

Perhaps they would be could be prefixed with `USER_` so there's a clear delineation.

**Comment by ketang** [comment]
I like the idea of passing things into the workspace using a synthetic filesystem like `/proc`.  I think it's better than environment variables etc. because they're easily accessed, can be refreshed, don't have any namespace collisions, are pulled rather than pushed, and can be trivially converted into environment variables, command line arguments, and so forth.  We can also get hierarchical namespacing in a native idiom.

**Comment by ammario** [comment]
The synthetic filesystem is very cool but hard to implement.

* FUSE isn't natively supported in MacOS. I'm not sure how the support is in Windows but I know it's a total PITA to get running in MacOS
* FUSE in Linux (and probably elsewhere) requires `root`

---

You could achieve the benefits by supplying a `coder user-value get <name>` syntax. This avoids the security problems of environment variables for secrets as well.

**Comment by ammario** [comment]
For the purpose of secrets, [Doppler](https://www.doppler.com/) seems like an important product to study.

**Comment by ketang** [comment]
I think this should be split:
* in UI/CLI support for setting arbitrary environment variables -- OSS
* integration with paid products like Doppler and Vault -- Enterprise

**Comment by ammario** [comment]
Good question... perhaps both?

**Comment by ketang** [comment]
I think we might need to do both but separately.  I can imagine a template admin wanting to set some environment variables that are used during build that they don't want to share or that may collide with user environment variables.  I'm not endorsing it, just predicting it.  Of course in the former case that forces us to be careful to avoid leakage of those environment variables into user controllable things like a `personalize` script, unless we also make that a responsibility of the template owner to limit users' ability to use those mechanisms (I predict that won't suffice forever).

**Comment by ammario** [comment]
Advanced secrets configuration should be done via [Dynamic Secrets](https://coder.com/docs/coder-oss/latest/secrets#dynamic-secrets) so there is no "advanced integration" side of this issue.

**Comment by ketang** [comment]
I'd qualify that with a "for now" given it's Terraform-centric.

**Comment by kylecarbs** [comment]
This seems unnecessary at the moment and has the potential to cause state conflict with values that template admins set. I don't think we should do this without explicit feedback, so I'm closing for now.
