### ISSUE TITLE
`coder tunnel` intermittently times out

### ISSUE THREAD

**Issue by ammario** [coder/coder#2394]
To reproduce:

In workspace:
1. `git clone https://github.com/coder/coder.com` (I suspect other large frontend apps would work as well)
2. `yarn dev`

On local:
1. `coder tunnel ab --tcp 3000:3000`
2. Open up `localhost:3000` in browser
3. Refresh the page a few times and notice how it fails to load 50% of the time

If you forward with VS Code Remote the load failures don't appear, implying something is wrong with our tunnel.

---

Perhaps @coadler's wireguard work will resolve this.

**Comment by bpmct** [comment]
Closing as wireguard has addressed this
