### ISSUE TITLE
Uploading a template via the CLI breaks if through tunnel

### ISSUE THREAD

**Issue by ammario** [coder/coder#2396]
@kylecarbs thinks this has to do with wireguard ....

trivial to repro

**Comment by coadler** [comment]
I'm not able to reproduce this. Could you share the specifics of what you're doing?

**Comment by ammario** [comment]
ok it's working today.....

**Comment by ammario** [comment]
actually not...

<img width="714" alt="Screen Shot 2022-06-16 at 10 34 27 AM" src="https://user-images.githubusercontent.com/7416144/174106897-7a202ad2-7967-4143-8085-07de7936d88d.png">


I installed coder with `curl -L https://coder.com/install.sh | sh -s -`

**Comment by kylecarbs** [comment]
@coadler is on the case 🕵️
