### ISSUE TITLE
Deleting a workspace does not redirect to an permanent URL and build logs returns 404

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2404]
When deleting a workspace, the URL remains an easy-to-read `http://coder:7080/@maf/work`. It should be updated to include the UUID of the deleted workspace. Otherwise logs/history is inaccessible after a `coder create work` replaces the name.

Clicking the build logs also result in the "spinner" animation, dev console reveals network requests return 404 (`http://coder:7080/@maf/work/builds/4`).

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/147409/174073330-93d9ec21-5759-4b48-88f4-d09ce5af84e0.png">

**Comment by bpmct** [comment]
I've confirmed this behavior still happens and should probably be fixed at some point
