### ISSUE TITLE
Parameter `template_version` scope instead of `import_job` scope

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#2405]
Currently we have an `import_job` scope for parameters. These parameters are attached to the `import_job` of a template_version. When fetching params, you need the JobID of the job that ran for a given template_version. 

This is an extra hop away from the template_version when fetching params, and can be confusing. The confusion comes when a developer needs to fetch the params for a template version, they have to use `template_version.Job.ID` instead of `template_version.ID`.

The values are also set before the job is spun off, but before the template_version is made. This means the job exists before the version... which can complicate the implementation. 

https://github.com/coder/coder/blob/stevenmasley%2Ftemplate_update_params/coderd/templateversions.go#L688-L688

# Current implementation

To get parameters for template_version, you do:

```golang
func VersionParams(ctx context.Context, db database.Store, verisonID uuid.UUID) {
  version, _ := db.GetTemplateVersionByID(ctx, versionID)
  params, _ := db.ParameterValues(context.Background(), database.ParameterValuesParams{
      Scopes: []database.ParameterScope{database.ParameterScopeImportJob},
      ScopeIds: []uuid.UUID{version.Job.ID},
  })
}
```

# Desired Implementation

Use `versionID` directly without needing to fetch the underlying Job.

**Comment by kylecarbs** [comment]
@Emyrk are you interested in tackling this soon? Seems like some good ole debt :cowboy_hat_face:

**Comment by Emyrk** [comment]
Params are going to get a terraform refactor very soon. This seems like something to do when we handle that imo. It'll be touching all the same code. 

I will handle this though. I'll assign to myself and coordinate with Dean

**Comment by Emyrk** [comment]
I never ended up doing this, but I know params were changed a lot. Is this relevant anymore?

**Comment by kylecarbs** [comment]
Nah, it's not. This can be closed.
