### ISSUE TITLE
Show the reason for workspace action on build page

### ISSUE THREAD

**Issue by AbhineetJain** [coder/coder#2410]
Discussion on #2029 with @ketang to show the reason for a workspace action:

We might have multiple reasons to perform a particular action. For instance, a workspace could get (re)started or built as part of administrators forcing all workspaces to update the project.

This needs more discussion:
- Do we ask the user to input the reason when they are taking an action?
- Should we intelligently figure out ourselves what the reason would be? Based on who did it and what they did.
- What should the UX for this be?

**Comment by ammario** [comment]
Reason would only be used for system actions. When using the tabular format, we should avoid sparse columns as much as possible to avoid bloat.

**Comment by Emyrk** [comment]
Don't ask the user for a reason. The reason is "they clicked a button" which is implied imo.

**Comment by AbhineetJain** [comment]
Went ahead with using a `reason` column in place of the system user. Backend PR: #2438 Frontend PR: #2446.
