### ISSUE TITLE
No clear error when embedded postgres fails to start

### ISSUE THREAD

**Issue by ammario** [coder/coder#2412]
[![asciicast](https://asciinema.org/a/QKjokpAy5Tv2rva7r6vt4ULFE.svg)](https://asciinema.org/a/QKjokpAy5Tv2rva7r6vt4ULFE)

**Comment by ammario** [comment]
Well, I can find the full error by running `home/coder/.config/coderv2/postgres/bin/bin/pg_ctl start -w -D /home/coder/.config/coderv2/postgres/data -o "-p 34079"` but it's inconvenient.

**Comment by kylecarbs** [comment]
I'll open a PR for embedded-postgres. This is actually a problem where the logs don't output before close.

**Comment by kylecarbs** [comment]
I unassigned this, but it's certainly an issue. If you ungracefully kill `coder server` while running with an embedded PostgreSQL, you can reproduce this.
