### ISSUE TITLE
Slow SSH negotiation (takes ~1 second extra to connect to workspace)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2414]
I'm noticing that `coder ssh work` and `ssh coder.work` take longer than I'd expect before the prompt is available. There's ~1 second of extra overhead.

Just to confirm that there's nothing odd with my network, I took a Wireshark capture and have attached the CSV here: [wireshark.csv](https://github.com/coder/coder/files/8920729/wireshark.csv)

I don't see anything out of the ordinary, there's just WebSocket chatter going back and forth until we establish DTLS ~1 second later.

For comparison, here is a timing of SSH into a coder workspace, and a VM running on the same NAS.

```
❯ time ssh coder.work echo hi; time ssh vm echo hi
hi
ssh coder.work echo hi  0.01s user 0.01s system 0% cpu 1.641 total
hi
ssh vm echo hi  0.14s user 0.01s system 45% cpu 0.337 total
```

And it doesn't really have to be across the network either, I see the same with Coder running in Docker on a local machine.

**Comment by ketang** [comment]
Can you run it with `strace` or attach a debugger?

**Comment by kylecarbs** [comment]
#2779 will fix this!

**Comment by bpmct** [comment]
Closing as completed by #2779.

```sh
ssh coder.tinker echo hi  0.01s user 0.01s system 0% cpu 1.698 total
ssh vm echo hi  0.04s user 0.01s system 4% cpu 1.053 total
```

**Comment by mafredri** [comment]
@bpmct I still see this behavior even with v0.8.15, although I don't know if there's much we can do about improving it.

```
ssh coder.work exit  0.01s user 0.01s system 1% cpu 1.288 total
ssh vm exit  0.04s user 0.01s system 18% cpu 0.227 total
```

Still takes 1s longer to ssh into the Coder workspace.

Another thing I've noticed is that occasionally connections can start taking up to 8s for me (even on local network). This happens with Tailscale/WireGuard too. The only thing that seems to resolve the issue is _rebooting my MacBook_. Nothing else seems to help so this would suggest some bad routes somehow get locked in and used exclusively until reset by a system reboot.
