### ISSUE TITLE
multiple "drpc server error" - provisionerd disconnects

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#2417]
e.g. from test logs
```
    t.go:81: 2022-06-16 16:09:32.010 [DEBUG]	<github.com/coder/coder/coderd/provisionerdaemons.go:93>	(*API).ListenProvisionerDaemon.func2	drpc server error ...
        "error": stream closed
                 	storj.io/drpc/drpcstream.(*Stream).sendPacket:268
                 	storj.io/drpc/drpcstream.(*Stream).CloseSend:501
                 	storj.io/drpc/drpcserver.(*Server).handleRPC:126
                 	storj.io/drpc/drpcserver.(*Server).ServeOne:66
                 	storj.io/drpc/drpcserver.(*Server).Serve.func2:112
                 	storj.io/drpc/drpcctx.(*Tracker).track:52
```

I believe I have also seen this running the dev server.  We use in-memory transport, so it's not like we're dropping network packets.  Something appears to be closing the stream prematurely.

This makes our tests flaky including incomplete job logs, and could affect the the real thing in a similar way, although I have not seen it personally.

**Comment by kylecarbs** [comment]
Seems like the attached issue had a PR merged. I'll close this for now, but if you find this again, please reopen!
