### ISSUE TITLE
Package more app icons by default

### ISSUE THREAD

**Issue by ammario** [coder/coder#2419]
Right now, we just package in `code.svg`, so if people want to use another IDE they have to host it themselves or use some random URL they find off Google Images. In the case of air-gapped clients, they would have to set up an internal file server or recompile our frontend.

This is pretty easy to add.

**Comment by kylecarbs** [comment]
Off the top of my head:
- All of the JetBrains IDEs
- noVNC
- Jupyter
- RStudio
