### ISSUE TITLE
Add code-server app to all starter templates

### ISSUE THREAD

**Issue by ammario** [coder/coder#2426]
code-server is the most magical part of Coder, even if they may eventually use SSH.

**Comment by mark-theshark** [comment]
💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯

**Comment by tjcran** [comment]
closing duplicates #2193
