### ISSUE TITLE
On workspace and template detail pages include a picker for a different one

### ISSUE THREAD

**Issue by ketang** [coder/coder#2439]
We have a workspace list page and a workspace detail page.  To look at a particular workspace, I click on the workspace name.  To look at another one, I go back, and then I click on it.  I'm impatient.  I don't want to go back.  Give me a picker on the detail page that lists the workspaces I can see.  When I pick one, I go to its workspace detail page.

Same deal for template detail pages.

![image](https://user-images.githubusercontent.com/33678/174162927-a043ad8c-49b3-4421-8646-2f9562bbb826.png)

![image](https://user-images.githubusercontent.com/33678/174162938-7d466dd5-3a9e-4820-83d5-394c29f66b5d.png)

**Comment by kylecarbs** [comment]
This isn't necessary for now. The list page is perfectly fine!
