### ISSUE TITLE
Friendlier labels for resources

### ISSUE THREAD

**Issue by ketang** [coder/coder#2440]
The way we label resources doesn't convey useful information:

![image](https://user-images.githubusercontent.com/33678/174163122-74af9ba2-f5e0-4ce0-8469-e52fcfd42dd7.png)

We need simple labels.  The first one could say something like "compute" or "host."  The second one should use the word "disk."

**Comment by ammario** [comment]
I'm assuming you're referring to "root" and "coder". That is a matter of how they're named in the dogfood template, which is stored on Kyle's computer.

As far `kubernetes_deployment` and the resource types, I believe we should link out to their corresponding terraform docs if possible so the user can dig in.

**Comment by bpmct** [comment]
We're sorting this out with #2989. Some of this has to do with how admins name their resources too.
