### ISSUE TITLE
Create and/or recommend a template for working on Coder

### ISSUE THREAD

**Issue by ketang** [coder/coder#2451]
We should provide a template customized for working on the `coder` project.  It would come configured with appropriate Golang and TypeScript tools installed.  We could have a VSCode flavor and a JetBrains Goland/Webstorm flavor.

Then we should recommend this in `CONTRIBUTING`.

**Comment by jsjoeio** [comment]
Ben and I can tackle this.

**Comment by bpmct** [comment]
Closed as completed by #2959
