### ISSUE TITLE
Add a `back to workspace` button to the build log page

### ISSUE THREAD

**Issue by presleyp** [coder/coder#2459]
As a user, when I click into the details on a build in my workspace timeline, I want to be able to return to my workspace easily. I can press the back button, but I expected to have a button in the Coder UX to take me back to the main page for the associated workspace.

As a user, I want page titles to help me understand what I'm looking at. "Logs" does not help me understand that I'm looking at the logs for one build of one workspace; it sounds like I might be able to find all kinds of logs here. The workspace name is given elsewhere on the page, but the workspace owner and the specific build are not.

I also see steps called "Setting Up0" and "Cleaning Up0" which look odd. I don't know if that's avoidable.

**Comment by kylecarbs** [comment]
@presleyp I updated the title to be a bit more specific, just so this was more approachable and looked less broad! Feel free to adjust as you see fit :)

**Comment by kylecarbs** [comment]
We now have a clickable link, so I think it's safe to close this.
