### ISSUE TITLE
UI: Question mark helpers not always hide and don't allow to scroll the page

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#2461]
Coder version:
[Coder v0.0.0-devel+d0aca86](https://github.com/coder/coder/commit/d0aca866572a79a1eb85c025577839746ed364cd)

Steps: 
1. Go to a page with a Question mark helper (e.g. template/workspace details page / Templates / Workspaces)
2. Hover over the question mark --> tooltip appears
3. Move the mouse off of the question mark, for example in the direction of the top navigation

Expected Result: the tooltip is hidden

Actual Result: the tooltip is not hidden, if there is a scrollbar on the page - it disappears and the user is not able to scroll until they get rid of the tooltip
![2022-06-17_16h56_17](https://user-images.githubusercontent.com/35501151/174319237-0a39cdb9-e525-4829-bc40-04eec8fcb1f7.gif)

**Comment by kylecarbs** [comment]
I've seen this behavior before, but it seems low priority.
