### ISSUE TITLE
Add `coder restart` command

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2464]
When the agent loses connection, users may see the message:

```
The workspace agent lost connection! Wait for it to reconnect or run: coder rebuild
```

This command doesn't exist, and requires `coder stop` followed by `coder start` at the moment.

Should this be added and called `rebuild` or something else? See #1376 about renaming start/stop.

**Comment by kylecarbs** [comment]
I think we prompt for starting again. Much easier short-term solution!

**Comment by mafredri** [comment]
The message appears e.g. during `coder ssh workspace`, and if the agent manages to connect within a few seconds, we may still be stuck at the prompt. If the user selects yes there may be an unnecessary restart cycle.

I also think a `rebuild` or `restart` command would be useful, I've needed to start/stop relatively often during development.

**Comment by ketang** [comment]
I think `rebuild` would be useful, but I'd like a customer to say that.  I don't want to be too liberal with adding subcommands because they express a commitment.
