### ISSUE TITLE
OAuth misconfiguration does not return an error message

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#2465]
After attempting to configure GitHub OAuth, I tried to login with GitHub. I was immediately taken to a 404 page, with no user-friendly context about why I'm receiving the error (other than the error being returned in the URL string).

![Screen Shot 2022-06-17 at 10 25 15 AM](https://user-images.githubusercontent.com/9683576/174329015-47819f94-069c-428e-9dc3-b705d053963a.png)

URL string:

```
https://coderv2.ericpaulsen.io/oauth/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=UsBCktUNaXHWFIIh8RA7R4V6FLTppxI1
```

**Comment by misskniss** [comment]
@ericpaulsen can we get a little more info on this. Was this just an incorrect URL that you fixed?

**Comment by ericpaulsen** [comment]
the issue is with the callback URL i used in my GitHub OAuth configuration. it was `domain.com/oauth/callback` when it should be `domain.com/api/v2/users/oauth2/github/callback`

i document this in #2565

**Comment by kylecarbs** [comment]
I'm going to close this as won't fix since this was primarily user error.
