### ISSUE TITLE
Docs: rename `coder server` to `coder launch`

### ISSUE THREAD

**Issue by ketang** [coder/coder#2467]
Just like #2466 but in our external docs:
>`coder server` sounds just like `code-server`, and I imagine endless confusion resulting from that with lots of calls where someone says "no no no codER, with an 'r'" or "no, I mean CODE server, just the editor." Let's spare ourselves that.

> Rename the `server` command to launch. Keep `server` as an alias so we don't screw anything up, but

Update all the docs and screenshots to use "launch" instead of "server."

**Comment by bpmct** [comment]
Closing for now. We discussed this offline a month ago and settled on `server`
