### ISSUE TITLE
Prompt for workspace/template variables in a consistent order

### ISSUE THREAD

**Issue by dwahler** [coder/coder#2471]
Currently, when a template is created, we don't store or return the parameter schemas in any particular order. So template authors can't control the order in which users are prompted for parameters, and if a template is updated or recreated, the ordering can change unpredictably.

We should return schemas from the API in a consistent order, ideally the same order in which variables were specified in the template file.

**Comment by ketang** [comment]
Completely agree with putting them in the same order.  It's the least surprising and gives a clear mechanism for control.
