### ISSUE TITLE
Processes that exit unexpectedly are not cleaned up

### ISSUE THREAD

**Issue by sreya** [coder/coder#2485]
Working in my shell today I noticed that that I have more shell procs than I have sessions open:

```bash
coder@dev ~ ps aux | grep zsh
coder      26665  0.0  0.0   5100  3328 ?        S    18:36   0:00 /bin/zsh -l
coder      26872  0.0  0.0   8296  6760 pts/0    Ss+  19:33   0:02 /bin/zsh -l
coder      46514  0.3  0.0   7828  6212 pts/1    Ss+  22:32   0:00 /bin/zsh -l
coder      46592  9.5  0.0   8276  6356 pts/2    Ss   22:33   0:00 /bin/zsh -l
```

## Reproduction Steps:

1. Open a session with `ssh coder.<ws>`
2. Run a `ps aux | grep <shell>` 
3. Find the process on your local machine and run `kill -9 <pid>`
4. Open another shell and observe the leaked process

**Comment by kylecarbs** [comment]
This seems fixed by the reaper.
