### ISSUE TITLE
Add an uninstall script

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2487]
### Problem 
The install script is putting files in various folders, which makes it difficult to clean up and remove from a workstation or system

### Definition of Done
,there should be an uninstall script to remove Coder and clean things up.

**Comment by kylecarbs** [comment]
I wonder if docs would suffice here... users can change configuration directories with the CLI too, which makes the uninstall a bit leaky.

This is what we did for code-server, which seems to have worked decently well: https://github.com/coder/code-server/discussions/1989

**Comment by tjcran** [comment]
> I wonder if docs would suffice here... users can change configuration directories with the CLI too, which makes the uninstall a bit leaky.
> 
> This is what we did for code-server, which seems to have worked decently well: [coder/code-server#1989](https://github.com/coder/code-server/discussions/1989)

Docs would certainly be a good first step to take and then re-evaluate. But i'd call that the bare minimum of what we want to do right now.

**Comment by sharkymark** [comment]
For me, what acerbates this, is forgetting I may have 1 install already on my Mac, with an external Postgres, and another with the embedded. 

We'd early trust, as we do with v1, with making stuff easier for folks than expecting everyone is an uber-engineer just because they can be. There's a bigger pie out there.

**Comment by sharkymark** [comment]
Ok,

1. delete the folder with the binary aka CLI
2. rm -rf ~/.cache/coder (where the `curl` script sticks the releases)
3. Where is the embedded Postgres? All I see is my v1 Coder for Docker dir `~/.coder` but that is not it

Help

**Comment by khanakia** [comment]
How do i uninstall coder from ubunut there is no command i found
