### ISSUE TITLE
Graphic on repo README.md says `coder open` but that is not a valid command

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2488]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/2022166/174414125-3ba37948-d7ad-45fe-b4c6-15bea9cdce46.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/2022166/174414167-6a1cba83-6c9e-4b9d-8c55-78d398f921ce.png">

**Comment by bpmct** [comment]
This was fixed

**Comment by misskniss** [comment]
@bpmct is there a PR for the fix that can be attached here?

**Comment by bpmct** [comment]
#3132 and #2566
