### ISSUE TITLE
Deleting a template and recreating it causes Postgres duplicate key value unique constraint violation

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2490]
@deansheather filed this in May https://github.com/coder/coder/issues/1582

But I'm on:
Coder v0.7.1+10dc9e3 Thu Jun 16 01:04:20 UTC 2022
https://github.com/coder/coder/commit/10dc9e3876276244fc83f2376ed25feb764b6207

Using another template name is not an option.

When will this be fixed?

<img width="956" alt="image" src="https://user-images.githubusercontent.com/2022166/174450478-2588b6b6-dca7-4dcc-b3b0-1b91cad0b02a.png">

**Comment by ketang** [comment]
This is also #2152 which was juuuuust fixed in #2454.  It's not in a release yet, but it's coming very soon.

**Comment by deansheather** [comment]
The next release will likely happen either before or on Tuesday
