### ISSUE TITLE
How can I see logs for scripts I'm running in the `coder_agent` Terraform resource's `startup_script`?

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2498]
How can I see logs for scripts I'm running in the `coder_agent` Terraform resource's `startup_script`? (I actually have a mix of commands and a `configure` script) In v1, there was a configure.log which helped.

**Comment by bpmct** [comment]
Hi @mark-theshark - these are now in `/tmp/coder-agent.log` and `/tmp/coder-startup-script.log`.

I'm closing for now as this is now documented and we have #2796 to display this in the build log
