### ISSUE TITLE
error message when upgrading to 0.7.2 with `install.sh`

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2499]
The upgrade appears to work, but got an `error` message and a string of output when running the `install.sh` script for 0.7.2

<img width="972" alt="image" src="https://user-images.githubusercontent.com/2022166/174488627-b64fc643-c9a1-47bd-8c7b-c03c202b79fa.png">

**Comment by bpmct** [comment]
Closing for now. I [wasn't able to reproduce](https://asciinema.org/a/lLTS97sbG99VvXwJqB2JCugM3) and we're on v0.8 now. 

Not a fantastic answer but hoping this bug was fixed.
