### ISSUE TITLE
Allow building workspace from arbitrary previous template version

### ISSUE THREAD

**Issue by ketang** [coder/coder#2501]
Currently the only version selection options with workspaces are to leave it alone or update to newest.  There is no way to reverse an update, nor is there a way to update to anything other than the newest.  We should present a picker that allows users to select any version of an existing template and build from that.

TBD: what administrator controls or restrictions, if any, should we develop around this?

**Comment by kylecarbs** [comment]
There's a lot of risk with users going back and forth between versions. I think this is a great idea, but we should await customer feedback before progressing with it.
