### ISSUE TITLE
Alias singular and plural subcommands

### ISSUE THREAD

**Issue by ketang** [coder/coder#2506]
I'm going to regularly forget whether it's `coder user` or `coder users` (it's `users`).  We do try to offer a little help:
```$ ./coder user
unknown command "user" for "coder"

Did you mean this?
        users

Run 'coder --help' for usage.
```
But I think we should just run `coder users` (with a warning?).  There's no ambiguity in this case; we know what the user wants, so we shouldn't make them go through another step.  Same goes for `coder templates` but *not* `coder dotfiles`.

**Comment by AbhineetJain** [comment]
I have added `user` as an alias in #2522, but I don't see what kind of warning would be helpful in this case, since we are accepting `user` anyway.

**Comment by ketang** [comment]
Yeah maybe the warning part wasn't well thought out.
