### ISSUE TITLE
/bin/ route should return an actual 404 error if the binary doesn't exist

### ISSUE THREAD

**Issue by deansheather** [coder/coder#2510]
If you hit `/bin/asdf` on a deployment, you get a 200 OK response with the index.html of the SPA. The frontend correctly renders a 404 page, but `curl` takes this as a success and the startup script continues onwards.

Any "not found" errors under `/bin/` should return a 400 Not Found response with a response message instead of index.html.

**Comment by kylecarbs** [comment]
Seems like this happens now! Our logic must have changed :sunglasses:
