### ISSUE TITLE
Add Terraform details for adding `code-server` to a template

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2512]
I will open a PR now with suggested changes including a screenshot of `code-server` in the workspace UI.

<img width="1038" alt="code-server-in-ui" src="https://user-images.githubusercontent.com/2022166/174495712-319156e0-2ab7-4a00-80f4-59f47834e6ba.png">

**Comment by mark-theshark** [comment]
PR https://github.com/coder/coder/pull/new/code-server-doc

**Comment by tjcran** [comment]
@kylecarbs I added Katie as a reviewer. Can you review also?
