### ISSUE TITLE
Implement always-visible widget showing my active workspaces

### ISSUE THREAD

**Issue by ketang** [coder/coder#2527]
I should always be able to see what the current status is of my top N workspaces (either fixed or variable based on screen size).  Clicking on one will take me to that workspace's page.  Clicking on the summary at the right or the `>` will take me to the workspaces page filtered to my workspaces.

Blue signifies the workspace is starting up.  We'll want to indicate shutting down the same way we do elsewhere.

![image](https://user-images.githubusercontent.com/33678/174632169-610b0dac-6668-4134-a49d-8534bde8e7de.png)

**Comment by bpmct** [comment]
Most of our users in Coder Classic only use one workspace per day. We've also seen evidence that power users prefer to use the CLI/SSH and rarely interface with the dashboard, when possible. 

While this may change as Coder OSS introduces fancier compute types, I don't think we have enough data to warrant a request like this. Closing for now
