### ISSUE TITLE
Bug: using wrong coder binary for ProxyCommand in config-ssh

### ISSUE THREAD

**Issue by ketang** [coder/coder#2528]
Had a run-in with this one:
```
ketan@Spindrift:/tmp/coder2$ ./coder config-ssh
The current executable path does not match the executable path found in $PATH.
  | This may cause issues connecting to your workspace via SSH.
  |     Current executable path: "/tmp/coder2/coder"
  |     Executable path in $PATH: "/home/ketan/bin/coder"
```
To fix it I had to edit my `.ssh/config` to use the former path as the latter was coder v1.  I think it should either always use the current executable or prompt the user to choose.  In this case `config-ssh` sort of knowingly did the wrong thing, and I think our typical user won't necessarily know how to deal with it.

A cleverer elaboration would be to inspect the various `coder` binaries found and prune the set to the ones that are v2-compatible.

**Comment by sreya** [comment]
Yeah I'm pretty sure this has to be a bug. I'm going to go with the simplest fix which is to simply use the absolute path of the `coder` executable you used to run `./coder config-ssh`
