### ISSUE TITLE
docker-compose.yml bug in image version

### ISSUE THREAD

**Issue by alon-david** [coder/coder#2535]
when no CODER_VERSION is specified, `docker-compose up` does not run the env
there is no consistency in repository, some places are with leading `v` and does not expect this.
from this line I expect the env var to be with leading `v` https://github.com/coder/coder/blob/47c7eda670529ad036b07f13fbae5ce1276934c9/site/src/components/UserDropdownContent/UserDropdownContent.test.tsx#L33

**Comment by bpmct** [comment]
Fixed in #2557
