### ISSUE TITLE
tunnel appears to be hanging again. Can start server.

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2536]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/2022166/174672995-7d63196d-2ed3-4dbd-84d0-d4f962b89152.png">

**Comment by kylecarbs** [comment]
Hmm. This seems to be intermittent... @coadler should we bump the resources of the hosted tunnel?

**Comment by coadler** [comment]
This is fixed.

**Comment by ketang** [comment]
What's the plan for preventing regressions?

**Comment by coadler** [comment]
There were a bunch of duplicate issues about the tunnel, overall improvements being tracked in https://github.com/coder/coder/issues/2666. It's much more stable now though.

**Comment by ketang** [comment]
Sure, but what was fixed can be broken again.  Are there connection stability and performance tests that verify those fixes?
