### ISSUE TITLE
Expand docs for contributors

### ISSUE THREAD

**Issue by ketang** [coder/coder#2538]
I ran into a few problems and unknowns that others are likely to run into as well.

```
bash: shfmt: command not found
```
Resolved by:
```
$ go install [mvdan.cc/sh/v3/cmd/shfmt@latest](http://mvdan.cc/sh/v3/cmd/shfmt@latest)
$ export PATH="$PATH:$HOME/go/bin/"
```
Although obviously that's not sticky.

Also:
```

ERROR: The 'nfpm' dependency is required, but is not available.

ERROR: One or more dependencies are not available, check above log output for more details.
make: *** [Makefile:32: build] Error 1
```
Resolved via installing according to instructions: https://nfpm.goreleaser.com/install/#apt

In addition, there weren't obvious answers to questions I had:
* what's the workflow for my changes?
* how do I name my branch?
* what should my commit message look like?
* how do I cite an issue in the commit message?
* what about squashes and merge commits?
* whom should I add to the PR review?

I don't actually know the correct answers, otherwise I'd do this myself.

**Comment by ketang** [comment]
Also now we need `zstd` too.

**Comment by bpmct** [comment]
related #2739 #2599

**Comment by ammario** [comment]
Closed in favor of https://github.com/coder/coder/issues/2739
