### ISSUE TITLE
UI does not update if a template is deleted or added via CLI

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2540]
So if you delete a template in the CLI, you have to refresh the screen to see the row gone.

**Comment by ketang** [comment]
Not responsive or just not updated?

**Comment by mark-theshark** [comment]
responsive, yes, meaning it updated.

**Comment by mark-theshark** [comment]
@ketang The UI also does not update if a template is added. So only the workspaces UI seems to auto-update on creation.

**Comment by tjcran** [comment]
Duplicates #1753
