### ISSUE TITLE
Licensing RFC

### ISSUE THREAD

**Issue by misskniss** [coder/coder#2549]
As a company, we want to create and review the RFC for our general licensing enforcement support so we can quickly execute for our enterprise customers. 

Definition of Done: 
@tjcran 
## Why do we need this?

Coder’s revenue from OSS will follow a typical OSS/Enterprise model. The OSS Community Edition will be free and available for anyone to use, but some advanced/enterprise-y features will be held back for the paying customers. 

Additionally, we’d like the flexibility of being able to “bundle” various features on an ad hoc and customized basis from a sales perspective. Some paid features should also be closed source while others may be OSS (but only included when customer is paid). 

## When do we need it?

Immediately. This is a pre-requisite to selling the Enterprise Edition and also has potential implications for how we code other features.

**Comment by tjcran** [comment]
@spikecurtis i've added some problem definition, but i'd like to spend time with you to hash out the business/prod requirements soon so you can get started on the rest of the RFC.
