### ISSUE TITLE
Allow user to select and modify GitHub email used for commits

### ISSUE THREAD

**Issue by ketang** [coder/coder#2552]
Related to #2551.  Right now we seem to always choose the primary email address.  That may not be what the user wants.  If the user's primary email address is not visible, we should show a screen on first login that warns them of this and allows them to choose another.  We should also link GitHub docs on how to make an email address visible.

In addition, we should make it easy to see what is configured and to change it.  The changes allowed should be similar to the above, in that they're limited to what GitHub knows about rather than free entry.

**Comment by bpmct** [comment]
This is now completed in #3034
