### ISSUE TITLE
coder docker template needs updated docker addr on dogfood

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#2559]
The docker sock is incorrect on the coder docker template when using dogfood, and you must edit the template to use a tcp port instead of the unix socket. This breaks the core flow devs use for manually testing templates. 

Problem Statement
Customers should not need to know about the docker mechanics to make the template work, just that they have docker installed.

Acceptance Criteria
Customers should be able to use the docker template out of the box without having to change the docker settings of the template. With a fresh VM, a new instance of Coder should allow using the bundled docker template without any additional configuration.

**Comment by misskniss** [comment]
This hung up a few of the devs in a way that we will want to fix this soon.

**Comment by kylecarbs** [comment]
The Docker template shouldn't specify a socket, because `DOCKER_HOST` is used by default if none is specified.

**Comment by johnstcn** [comment]
It looks like Kyle updated the internal Coder template to set `$DOCKER_HOST` correctly.

**Comment by f0ssel** [comment]
I am still running into this on V2 dogfood. 

```
Extracting  docker  to ./docker...
Create your template by running:
                                                            
   cd ./docker && coder templates create                    

Examples provide a starting point and are expected to be edited! 🎨             
➜  coder git:(main) ✗  cd ./docker && coder templates create
> Create and upload "~/coder/docker"? (yes/no) yes
✔ Queued [321ms]
✔ Setting up [1ms]
✔ Adding README.md... [0ms]
✘ Parsing template parameters [56ms]
                                                            
  This template has required variables! They are scoped to  
  the template, and not viewable after being set.           

var.step1_docker_host_warning
  This template will use the Docker socket present on
  the Coder host, which is not necessarily your local machine.
  
  You can specify a different host in the template file and
  surpress this warning.

  >  Continue using /var/run/docker.sock on the Coder host 

var.step2_arch
  arch: What architecture is your Docker host on?
  
  note: codercom/enterprise-* images are only built for amd64

  >  amd64 

var.step3_OS
  What operating system is your Coder host on?

  >  Linux 

✔ Queued [212ms]
✔ Setting up [1ms]
✔ Adding README.md... [0ms]
✔ Parsing template parameters [5ms]
⧗  Detecting persistent resources 
  Terraform 1.1.9
  Error: Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  
✘ Detecting persistent resources [3050ms]
template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1
Run 'coder templates create --help' for usage. 
```

**Comment by johnstcn** [comment]
Yeah @mafredri  and I were investigating this morning and it looks like the Terraform docker provider just doesn't respect `DOCKER_HOST` (or at least, not the way we're using it).

**Comment by johnstcn** [comment]
- Created a fresh Ubuntu 20.04 VM on AWS
- Installed upstream Docker (not `docker.io` from Ubuntu repos)
- Installed Coder with the install script and set the Coder access URL appropriately (we emit instructions to do this in the install script output)
- Created a Docker template straight from what `coder templates init` outputs
- Created a workspace from the template -> no issues
