### ISSUE TITLE
update dev scripts for dogfooding

### ISSUE THREAD

**Issue by misskniss** [coder/coder#2560]
We found there are a couple places with friction when dogfooding because our scripts need some updating. 

wait for server to come up rather than using a sleep
`make bin` updates for 'slim binaries`

Please update dogfooding guide with the changes as well.

**Comment by johnstcn** [comment]
https://github.com/coder/coder/pull/2572 addresses the 'wait instead of sleep' part

**Comment by tjcran** [comment]
Closed via #2572
