### ISSUE TITLE
bug: templates/aws-linux: add keypair to instance

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2571]
# What

Ensure a keypair is present for the instance.

# Why

In case of the Coder agent failing to connect (for whatever reason), allow the user a backdoor into the instance to troubleshoot.

**Comment by johnstcn** [comment]
Oh I was figuring we'd just use `${HOME}/.ssh/id_rsa`, but that means the back door is only accessible from that machine. Maybe intended? I guess this might fall under the heading of "templates are meant to be edited"

**Comment by bpmct** [comment]
> I guess this might fall under the heading of "templates are meant to be edited"

Agreed

Closing for now as this depends on security groups, the host machine, and other things.
