### ISSUE TITLE
The terraform provider has been configured locally, and the offline mode template creation prompts an error

### ISSUE THREAD

**Issue by xiaofan-linux** [coder/coder#2577]
#### Terraform provider  configured
![image](https://user-images.githubusercontent.com/33335754/175053988-f05d2627-7fce-4d5b-9c74-2b07774e7322.png)

#### Error creating template
![image](https://user-images.githubusercontent.com/33335754/175054884-72030380-caaf-4080-a0d7-1de404d53550.png)

**Comment by kylecarbs** [comment]
I found [this guide](https://sleeplessbeastie.eu/2020/12/04/how-to-execute-terraform-in-an-offline-mode/#:~:text=The%20new%20one%20%E2%80%93%20Terraform%200.14).

It should require downloading Terraform providers beforehand, populating the cache directory, and it should _just work_.

**Comment by xiaofan-linux** [comment]
![image](https://user-images.githubusercontent.com/33335754/175076612-713e6660-d720-42e2-82d3-729ede526753.png)

**Comment by kylecarbs** [comment]
Is Coder running as the same user? `ps aux | grep coder`
