### ISSUE TITLE
Warn user when CLI version is out of date

### ISSUE THREAD

**Issue by ammario** [coder/coder#2578]
As a user, I assume issues like https://github.com/coder/coder/issues/2570#issue-1279511617 are active bugs when in fact they are either old bugs or the result of incompatibility. If Coder told me my version was out of date, I can avoid many negative surprises.

**Comment by tjcran** [comment]
this seems like a low hanging fruit item that makes the experience substantially better. adding to next sprint. @misskniss

**Comment by ammario** [comment]
Also, there should be a way to suppress the message. It was super annoying in v1 when I was intentionally using an old version and it would give a warning on each invocation. A `CODER_SUPRESS_VERSION_WARNING` or the like would be nice.
