### ISSUE TITLE
Install docs do not have Windows solution

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#2589]
I am trying to install the coder binary on windows following the readme and it seems all the install material is only for linux and macos.

**Comment by f0ssel** [comment]
Okay I see we do mentioned Windows in the "download the binary" section, but I feel a dedicated Windows set of instructions should be more obvious. You see linux and macos and expect the next section to be windows.

**Comment by bpmct** [comment]
I'm not really how to improve this without a msi installer or publishing Coder to something like `choco`.

Until then, are you suggesting a minor wording change to the `README` to mention windows @f0ssel?

**Comment by kylecarbs** [comment]
I'm going to close this for now, until we get more complaints from Windows users :window:
