### ISSUE TITLE
Contributing guide does not list all dependencies required

### ISSUE THREAD

**Issue by oxy** [coder/coder#2599]
Hi! I attempted to set up an environment to develop `coder` locally on macOS, and ran into the following documentation gaps before I could get an environment up and running.

- `make bin` [to build slim binaries] on macOS required PostgreSQL (`pg_dump` 11) and Docker to build and dump some database stuff; I'm not sure if this was a setup-specific issue
- `make build` also requires `nfpm` to make release packages
- `make dev` is also out of date now - we should update the guide to point users to running `./scripts/develop.sh` directly.

**Comment by bpmct** [comment]
related #2739

**Comment by ammario** [comment]
Closed in favor of https://github.com/coder/coder/issues/2739
