### ISSUE TITLE
Allow admins to set templates to automatically update

### ISSUE THREAD

**Issue by ketang** [coder/coder#2600]
Right now the user has to click the "Update" button to pull a new version of the template.  I can easily imagine cases where the admins and/or project owners don't want to leave that so open-ended.  They should be able to force some kind of update behavior.  I think the options should be at least:
* update when the user wants (status quo)
* update on change (and apply to next restart)
* update on change and force immediate restart

**Comment by bpmct** [comment]
related #2760
