### ISSUE TITLE
JetBrains `projector-container` template does not correctly open

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2621]
I am using the template referenced in the docs
https://coder.com/docs/coder-oss/latest/ides/configuring-web-ides

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/2022166/175402987-40b55430-5592-4523-8b62-a3a34ff14978.png">

**Comment by bpmct** [comment]
Closing as this is a separate project and not recommended in the docs anymore (#3002). I also added a notice to the repo
