### ISSUE TITLE
Docs: replace alpha warning with beta disclaimer

### ISSUE THREAD

**Issue by ketang** [coder/coder#2623]
I think the project has matured beyond the point of needing a statement like this.  I think it's okay to call it beta.  I also would remove the part saying it's not ready for production use; if I recall correctly, there are people using it in production happily right now.

<img width="928" alt="Screen Shot 2022-06-23 at 16 24 07" src="https://user-images.githubusercontent.com/33678/175404886-60c2c186-bed1-4bf9-bbf6-7bba84a0af9d.png">

**Comment by f0ssel** [comment]
Also our dogfood deployment is getting there, we have dozens of daily users right now using it for work. 
![image](https://user-images.githubusercontent.com/19379394/175407859-e4e66f10-b3e4-4928-834f-37e1b4a23f03.png)

**Comment by ketang** [comment]
So maybe we don't even say "beta?"

**Comment by mark-theshark** [comment]
I was not aware OSS is used in production already (besides some of the Coder's engineers). Until terminal disconnects are repaired, it seems premature. But it's OSS so people can do whatever they want.

**Comment by ketang** [comment]
We have some telemetry data that suggests significant usage that matches the pattern you'd see from real production usage.

**Comment by ammario** [comment]
@ketang — can you show that data?
