### ISSUE TITLE
%20 is not handled on the server-side

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#2628]
This causes some assets to not work, I would expect the entirety of the app to not work but apparently not.

(App named "Open VSCode")
![image](https://user-images.githubusercontent.com/57866459/175532742-1224794c-8154-4407-9ccc-8c8807ba5f17.png)

(App named "vscode")
![image](https://user-images.githubusercontent.com/57866459/175760424-baff3b45-c4cf-41f6-9fed-709d174c3944.png)

**Comment by Emyrk** [comment]
@phorcys420 I am not seeing this 404. I assume this is using `code-server` right?

I am using this coder_app
```terraform
resource "coder_app" "code-server" {
  name     = "VS Code"
  agent_id = coder_agent.dev.id
  url      = "http://localhost:8080/?folder=/home/coder"
}
```

I loaded the same asset you are trying to load with this url and it works `http://localhost:3000/@admin/dev/apps/VS%20Code/static/out/vs/workbench/contrib/welcomeGettingStarted/common/media/dark.png?folder=/home/coder`

Can you confirm this issue on the latest version?

**Comment by phorcys420** [comment]
this is my ``code-server``:
```tf
resource "coder_app" "code-server" {
  agent_id = coder_agent.dev.id
  name     = "vscode"
  url      = "http://localhost:8080/?folder=/home/coder"
  icon     = "/code.svg"
}
```

This doesn't work:
```tf
resource "coder_app" "code-server" {
  agent_id = coder_agent.dev.id
  name     = "Open VSCode"
  url      = "http://localhost:8080/?folder=/home/coder"
  icon     = "/code.svg"
}
```

I am closing this issue because it seems that it is resolved (I switched from v.0.7.1 to v.0.7.4)
![image](https://user-images.githubusercontent.com/57866459/175772295-f6444ed2-9217-4027-825e-a30e49e2840d.png)
