### ISSUE TITLE
Ability to run multiple commands in a coder_agent

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#2629]
I would like a clean way to run multiple commands. Currently I have to do the following:
```tf
resource "coder_agent" "dev" {
  startup_script = "command1; command2"
}
```
it does work but it isn't really nice (especially when you want to run something on the code-server host, it just feels improper).

My proposal would a list containing the commands:
```tf
resource "coder_agent" "dev" {
  startup_script = ["command1", "command2"]
}
```

also, maybe a way to group tasks too ?
```tf
resource "coder_agent" "dev" {
  startup_script = {
    taskname = ["command1", "command2"]
  }
}
```
(or maybe with ``taskname`` being an object containing ``{commands = ["command1", "command2"], needed = true}``, that way we can completely error if a ``needed = true`` scripts fail, and just warn the user somehow if a ``needed = false`` script fails)
that way we could identify scripts that cause errors ? (just dropping ideas here about what I think would be nice)

**Comment by ketang** [comment]
Hi, @phorcys420 .  Obviously you're familiar with this mechanism and aware that you could create your own script.  Could you describe how that method falls short in your use case?

**Comment by kylecarbs** [comment]
I think this should be the job of another utility like [concurrently](https://www.npmjs.com/package/concurrently). We'll want to show these logs in the UI with #2957, and it gets a bit messy if we start having N number of logs instead of zero or one.

**Comment by phorcys420** [comment]
As an update, I started making servics using [supervisord](http://supervisord.org) to split out tasks.
