### ISSUE TITLE
Workspace shutdown notification should also be in the workspace list view and not just the workspace dashboard

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2631]
Maybe an icon (in brown) where if clicked, the workspace is extended (correctly)

<img width="967" alt="image" src="https://user-images.githubusercontent.com/2022166/175567376-9dbfeced-c2ae-433f-a746-b8db54ad1383.png">

**Comment by kylecarbs** [comment]
I view this as relatively low priority... so I'm going to close for now. We'll probably get feedback on this soon though, I just want to keep the issue list short and actionable!
