### ISSUE TITLE
Workspace is scheduled to shutdown in 1 hour. I hit extend, and it extends by four hours.

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2633]
After clicking extend, it shows after 2pm, and it's 10am now (so 4 hours)
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/2022166/175567472-d4732295-ea92-4345-9b80-650cff52d5bb.png">

And the actual schedule, 1 hour
<img width="435" alt="image" src="https://user-images.githubusercontent.com/2022166/175567544-c4027acc-bf0e-4d47-b87a-fc3dddb3a825.png">

**Comment by kylecarbs** [comment]
There are other issues that will supersede this I believe.
