### ISSUE TITLE
Nest common components in FE directory

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#2640]
As discussed in the FE variety meeting, we should nest certain common components within the same directory. You can read more about this decision, [here](https://www.notion.so/coderhq/2022-06-24-fdecaabd9ad542619b11e29dc1b94c58).

Examples of component types which can all co-exist in common directories include:
 - modals, e.g. in a folder called `modals`
 -  dialogs, e.g. in a folder called `dialogs`
 - tooltips, , e.g. in a folder called `tooltips`
 - maybe table components, e.g. in a folder called `table_components`

AC
- [ ] components with many common members (examples above) should be moved into new, appropriately named directories
- [ ] index.ts files should be added to each of these directories to import and then export those components.

**Comment by kylecarbs** [comment]
@Kira-Pilot do you think we should do this in the next ~3 months? If not, I'd prefer to close it out.

**Comment by Kira-Pilot** [comment]
@kylecarbs I don't think we need a ticket for it; let's close.
