### ISSUE TITLE
``coder template pull`` with no argument(s) panics

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#2650]
* Version: ``v0.7.4+3f97767``
* Host: ``Windows``

---

``coder template pull`` alone throws a go panic instead of telling the end-user to visit ``coder template pull --help``.

![image](https://user-images.githubusercontent.com/57866459/175772706-815eafa5-7e43-45d0-9af0-15f9ee94009b.png)

**Comment by sreya** [comment]
Thanks for reporting this @phorcys420! :heart:
