### ISSUE TITLE
Workspace auto shutdown warning should appear everywhere in web UI

### ISSUE THREAD

**Issue by ketang** [coder/coder#2652]
My workspace is about to shut down:

![image](https://user-images.githubusercontent.com/33678/175785212-05e0ca70-c455-42a4-91a0-2f921d875084.png)

But I'd left my browser on the build page, so I had no idea:

![image](https://user-images.githubusercontent.com/33678/175785226-4dff7a8a-35ca-434d-a1ec-09223a841e60.png)

We need this warning to appear no matter what page the user is looking at.

**Comment by mark-theshark** [comment]
@ketang I filed something similar before here as well https://github.com/coder/coder/issues/2631

**Comment by kylecarbs** [comment]
I don't agree this should be displayed everywhere. Closing for now until we get more reports!
