### ISSUE TITLE
Web Terminal Can't connect because of a socket error when using port in CODER_ACCESS_URL

### ISSUE THREAD

**Issue by ntimo** [coder/coder#2654]
# Problem Description
When using a non standard port for https like 10443 together with coder in the access url like this CODER_ACCESS_URL="https://coder.example.com:10443" the web terminal does not work and returns a websocket error. The chrome network tools show that it response with a 403 status.

# How to fix this problem the easy way?
Do not use a port in the coder access url. When simply removing it and using the default https port 443 everything works again normally.

**Comment by kylecarbs** [comment]
Good report, fixing now!

**Comment by kylecarbs** [comment]
I _think_ this has been fixed. We'll have to confirm though, so I won't close.

**Comment by bpmct** [comment]
Confirmed this has been fixed :)
