### ISSUE TITLE
Bug: edit schedule link and form render for others' workspaces

### ISSUE THREAD

**Issue by ketang** [coder/coder#2655]
I see the "Edit schedule" link on the workspace page and can view the form on someone else's workspace.  However, I can't make changes; when I attempt to submit the form, I get an error.  The link and form should be hidden if I can't use them.

**Comment by AbhineetJain** [comment]
@ketang Can you point me towards how I can reproduce the issue? I am unable to do it with the access controls provided by the standard Admin/Auditor/Member roles. Either cannot even read the workspace or can do both read and update.

**Comment by ketang** [comment]
I just tried it again, and it no longer behaves the same way.  I see the same behavior as you, which is correct and expected.
