### ISSUE TITLE
Workspace "last built" shows last job not last started

### ISSUE THREAD

**Issue by ketang** [coder/coder#2656]
"Last built" should show the finish time of the last successful start.  Instead it appears to show the last completed job.  If you stop your workspace, it will show the time since that job not since the last successful start.  There are a few ways to go with this:
* last start as described above
* maybe a last stop as well
* last change, which includes both start and stop (but also edits?); should be additional to last start above

More?

**Comment by mattlqx** [comment]
Also "Last built" isn't a good descriptor if it was the time that an instance was last started or stopped.

**Comment by bpmct** [comment]
How about we call it "last job" and call it a day?

**Comment by kylecarbs** [comment]
This isn't displayed on the workspaces table anymore, and it's not entirely clear how we should adjust the behavior from my perspective. I think it's _fine_ for now, and if it becomes problematic we'll adjust.
