### ISSUE TITLE
Allow persisting / in example templates

### ISSUE THREAD

**Issue by ketang** [coder/coder#2657]
Scenario: I installed PostgreSQL yesterday, fiddled around with it, and left.  Today I started the same workspace and discovered PostgreSQL was gone with yesterday's changes.  It took me a moment, but I figured out why: it was installed in ephemeral storage.  Okay, this is works-as-designed, but it's surprising and inconvenient.  In our example templates we should include a parameter where the user building the workspace can choose to persist just `/home` (or is it `/home/coder`?) or `/`, with the former being the default.

**Comment by sreya** [comment]
Unfortunately it's not really possible to persist `/` for containers.

**Comment by ketang** [comment]
Like not at all or it's hard?

**Comment by bpmct** [comment]
Not at all :(

**Comment by ketang** [comment]
I bet there's a way, like with a union FS or ZFS or something.
