### ISSUE TITLE
Pressing "Update" on a workspace does not prompt for newly-created variables

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#2660]
* Version: ``v0.7.4+3f97767``
* Host: ``Debian``

---

Whenever pressing the "update" button on a workspace that already exists, it just goes ahead and updates it without prompting for the unfilled variables
![Update Button](https://user-images.githubusercontent.com/57866459/175828832-3d3b9ff9-c162-4cee-9f62-17aeff23ef1e.png)

I think it should prompt for variables the same was as the workspace creation screen does :
![Variables on creation screen](https://user-images.githubusercontent.com/57866459/175828899-8d757581-2949-437e-b2e4-0454c64b33ad.png)

**Comment by bpmct** [comment]
related #802

**Comment by ammario** [comment]
Let's take this to #802 which discusses a solution.
