### ISSUE TITLE
Add a variable editing UI

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#2661]
Maybe it would be nice to have a button that lets us edit the variables we defined on workspace creation.
e.g: I prompt for dotfiles repo on workspace creation, but what if the user decides to move it to another git provider, how would he edit it?

PS: is there a way to edit variables on the CLI ? if not, then I guess it'd be a nice feature too.

**Comment by bpmct** [comment]
> PS: is there a way to edit variables on the CLI ? if not, then I guess it'd be a nice feature too.

You can now do this with `coder update <workspace-name> --always-prompt`

**Comment by bpmct** [comment]
related #802

**Comment by bpmct** [comment]
Closing in favor of #802. We'll discuss a solution there!
