### ISSUE TITLE
Add PagerDuty to the Coder tunnel

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#2666]
This can just check uptime or periodically check if the tunnel works successfully.

**Comment by ammario** [comment]
There's a plan for Tailscale to take this responsibility off our hands, right?

**Comment by coadler** [comment]
@ammario not at the moment. It's been running without issues for the past 2 months though. There's a memory leak stemming from my patch to `wireguard-go` but it's possible [kyle's pr](https://github.com/coder/wireguard-go/pull/1) fixes it.

**Comment by kylecarbs** [comment]
@coadler do we have PagerDuty on it? That might be wise.

**Comment by ammario** [comment]
We should have basic alerting around all of our user-facing production services. I'm happy to be the first responder in the on-call schedule.
