### ISSUE TITLE
Allow setting arbitrary environment variables for a workspace

### ISSUE THREAD

**Issue by ketang** [coder/coder#2668]
Do it through the Web UI or the CLI.  Yes, they can do it in a template or workspace, but it's something that will happen often that we should provide a more direct way.

**Comment by ammario** [comment]
What use cases do you have in mind?

**Comment by ketang** [comment]
Any environment variable.  You could overwrite out `GIT_*` variables (until we fix them) or set a `PAGER` or extend your `PATH` or set a path to some service.

**Comment by ammario** [comment]
Do you imagine this in addition to https://github.com/coder/coder/issues/2387?

**Comment by ketang** [comment]
That's admin controlled and gets the values from somewhere fancy.  This is set by the user and is just dumb key/value pairs.

**Comment by ammario** [comment]
https://github.com/coder/coder/issues/2387 proposes user-defined key-value pairs.
