### ISSUE TITLE
JetBrains `projector` requires generated password token but passing as a querystring parameter results in a WebSocket close code

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2669]
## Expected Behavior

I have coder_script that
1. installs the JetBrains projector CLI
1. autoinstalls a CLion IDE and makes a config folder
1. it specifies a password since projector CLI now adds that 
1. I start the IDE
1. create a coder_app for http://localhost:8997/?token=<password I created>

When CLion is clicked in the workspace, I should get the license screen (see hack below that gets it)

## Current Behavior

1. If I do not specify a password in the autoinstall, I get an expected Reason: Bad handshake token, since it is not passed in the querystring as a parameter
1. If I do specify the password as a token as a querystring parameter, I get a websockets 1006 error

If I do option 1, and copy the IDE URL into another browser window, and add ?token=<password>, JetBrains works

Option 1 screenshot
<img width="463" alt="image" src="https://user-images.githubusercontent.com/2022166/175833525-7721a463-5c5f-4079-afe3-431d499a6193.png">

Option 1 screenshot with hack to get it to work (manually paste token)
<img width="697" alt="image" src="https://user-images.githubusercontent.com/2022166/175833541-7bc3c30c-6204-4d5e-8128-61d8bfcc9fd1.png">

Option 2 screenshot
<img width="437" alt="image" src="https://user-images.githubusercontent.com/2022166/175833470-3673e3fd-d971-4e56-8ccb-517e9c54db79.png">

**Comment by mark-theshark** [comment]
A big hack, but I noticed that `projector ide autoinstall command` adds the password section in the config.ini, but `projector config add` command does not. So I run `projector ide autoinstall` to download CLion, delete the configs folder with `rm -rf`, run `projector config add` and it works from the UI.

**Comment by kylecarbs** [comment]
@mark-theshark do query parameters need to be passed from the backend to the frontend? If you connect directly, does it work?

**Comment by kconley-sq** [comment]
Maybe related, we noticed we can't provide the [`backgroundColor` URL query parameter](https://github.com/JetBrains/projector-client/blob/master/projector-client-web/README.md#debugtest-parameters) to the `coder_app` resource `url`. When we tried, we saw that the IDE wouldn't launch anymore. Is providing URL query parameters like that such that they would be preserved when the user accesses the IDE via the Coder website not supported?

**Comment by bpmct** [comment]
We found a workaround for the specific password issue.

@kconley-sq - sorry i missed your message. I don't think we plan on supporting query parameters since we use that as a base path for routing. Perhaps you could wrap projector via a full-screen HTML page and pass query parameters that way? I did something similar for VNC: https://github.com/coder/enterprise-images/blob/main/images/vnc/vnc/index.html
