### ISSUE TITLE
UI helper tool-tips for `resource` and `agent` remain even if you no longer hover over them 

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2672]
## Expected Behavior

If I hover over a tool tip for a resource or agent, it should remain open if my cursor is over them, or auto-shutdown in a deterministic amount of time e.g, 2 seconds, if my mouse moves away.

## Current Behavior

Tooltips remain on the screen as I randomly move the mouse around, blocking key information, and getting into the way of my flow.

**Comment by kylecarbs** [comment]
Doesn't happen for me anymore! It used to, so something changed :)

**Comment by kconley-sq** [comment]
@kylecarbs @sharkymark this seems to still be happening for us on 0.9.1, do y'all see it as well?
