### ISSUE TITLE
Coder OSS on an iPhone looks sad and not responsive

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2674]
![2AC47BD5-70EE-4A28-B1FA-939A4EB5864C](https://user-images.githubusercontent.com/2022166/175856422-7a8801f3-5316-456c-9012-48786387704a.jpeg)

v1 looks nice and large (responsive) so OSS should too

**Comment by bpmct** [comment]
related #3012

**Comment by BrunoQuaresma** [comment]
Closing in favor of #3185
