### ISSUE TITLE
dev-only: misleading error message "code-server is offline" when clicking on an app

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2676]
# Problem

If you try to access a workspace application (for example, code-server) from the webpack server running locally, you will get a message:

```
code-server is offline!

{{ .APIResponse.Message }}
```

Problem here is that we populate that with a Go handler, so when running the webpack-only frontend we only display the Go template.

# Solution

We should probably display a different error message here so folks know what's going on. This isn't a huge issue, but is bound to trip up folks who are trying to kick the tyres with local development and/or working on some features relating to workspace applications.

**Comment by bpmct** [comment]
Gonna close for now unless you wanna take a look Cian, I actually ran into this today but would rather keep our tracker small for now
