### ISSUE TITLE
Workspace goes to failed state and cannot be  started, stopped or deleted after cancel-start->stop->start actions

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2683]
### Problem
Workspace goes to failed state and cannot be  started or stopped or deleted after cancel-start->stop->autostart actions

I have met with the issue, that I cannot work with my workspace, getting error Error: Error creating instance: googleapi: Error 409: The resource 'projects/coder-dogfood/zones/europe-west4-b/instances/coder-nadzeya-nadzeya-test-autostart' already exists

Steps to reproduce:

coder version:
[Coder v0.7.4-devel+bbbd5241](https://github.com/coder/coder/commit/bbbd5241c3700d05d9ad8c85a1bbf844b47fb824)

1. Create a workspace (for me it was windows-gcp template on dev.coder.com)
2. Stop it
3. Start it, but cancel action
4. Stop it
5. Try to start

Start fails with
Error: Error creating instance: googleapi: Error 409: The resource 'projects/coder-dogfood/zones/us-central1-a/instances/coder-nadzeya-nadzeya-windows' already exists, alreadyExists

And cannot perform any other actions

Events order list sample:

![image](https://user-images.githubusercontent.com/9592232/175942788-82cef70f-553e-4e25-9c89-0fef434dbf98.png)

### Definition of Done
If a start is cancelled, a user should be able to start/stop a workspace without problems

**Comment by misskniss** [comment]
@bpmct can we get a couple of us together and see: 

- is this still happening?
- what behavior do we expect in these cases?

**Comment by mafredri** [comment]
I'm tackling this issue from the perspective that we currently terminate the Terraform process immediately on a cancel request which does not give Terraform a chance to clean up resources.

This will be changed so that cancellation signals an interrupt and we will wait for Terraform to clean up. A second forceful cancellation request terminates Terraform and may leave resources but can be necessary in some cases where Terraform is stuck cleaning up.

**Comment by mafredri** [comment]
With #3526 merged, I'm hoping this issue is fixed but I'll leave this ticket open for now in case there are more reports of it (it'll be part of the next release, the one after `v0.8.5`).

**Comment by ammario** [comment]
Let's reopen if there is a new report.
