### ISSUE TITLE
Auto ON/OFF Support

### ISSUE THREAD

**Issue by misskniss** [coder/coder#269]
Note this is an "epic of epics" - it contains the beta and enterprise milestone epics.

-----

- [x] https://github.com/coder/coder/issues/272
- [x] https://github.com/coder/coder/issues/850
- [x] https://github.com/coder/coder/issues/1317
- [x] https://github.com/coder/coder/issues/851
-----

## Breakout Discussion
March 24, 2022
[RFC](https://www.notion.so/coderhq/Workspaces-V2-Auto-on-Auto-off-e72bd8e92fe94fc4b4c32b2f2ec561a0)

Note scheduled Auto On/Off is a PAID feature.

## Plan

- Data model : Columns to workspace table and additional table (see RFC)
- workspace auto off 
- remove org level auto on/off table
- add auto start enable, auto stop enable, auto start_at and autostop_at
- workspace lifecycle job table 
- Add required methods for workspace auto start and auto stop
- Auto start scheduler implementation 
- Auto start executor implementation 
- Implement workspace start  - Done
- implement workspace stop. - Done
- support updating workspaces via HTTP API
- support updating workspaces via CLI
Cli commands: 
- autostart enable
- disable
- some kind of scheduling command logic (cron syntax?) 
- extension command
- user notifications and backoff timing (in coder agent to write to all connect sessions, polling coder trigger pgnotify) Write to all TTY that is connected. (if we do this for SSH it would not work for openssh. `wall` command . Warning - wall command is not for windows.)
- CLI system notifications, tray notifications (if we do this we may not have to to the wall - write all - approach)
- somesort of default auto off when you create a workspace so they do not stay forever on when a new one is created. "This workspace will automatically turn of in 8 hours". Maybe a daily shutoff point per workspace. Auto off job created as creation time + lease on create. Enable this globally? or User level? 
- Tyler: customers have expressed wanting to define things at the org level and users have the opportunity to override those org wide settings. 
- It is 8 hours and not changeable unless you upgrade?

Frontend:
- design the component for the Auto On/Off (workspaces/card that opens other forms /dialog for adding/editing schedules. Do we have this in the workspace creation modal and/or in settings for the workspace post-create.
- Implement the user alert that the workspace is about to auto shut off
- countdown visual component to show how much time is left before shut off - (with a snooze and/or dismiss? )
- notifications, snack bars and toasts may need to be implemented

Post MVP
- Create a feature allowing an On/Off schedule to be suspended.
- Reports view for costs. Could start in the CLI and later be added to frontend. Org and user level over some default or specifiable window of time.

**Comment by ketang** [comment]
Scheduling is good enough now
