### ISSUE TITLE
Cannot create the first user with coder started as:  coder server --tunnel

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2700]
Coder version: Coder v0.7.5+3a3aa49 Mon Jun 27 17:15:55 UTC 2022
OS: Windows

Cannot create initial user via running coder server --tunnel

Steps to reproduce:
1. Get Coder v0.7.5
2. Run coder server --tunnel - no issues are in output
3.  In the new command prompt window run coder login <generated url>
4. Enter login, email password

Actual: get an error: login with password: POST https://fccaae8e-c5df-4655-8dee-f05c9290560d.wg-tunnel.coder.app/api/v2/users/login: unexpected status code 500: Internal error inserting API key.
        Error: pq: invalid input syntax for type inet: "<nil>"
Run 'coder login --help' for usage.

![image](https://user-images.githubusercontent.com/9592232/176163102-d208d5ba-1434-4daf-9d51-646343b8372d.png)

**Comment by mark-theshark** [comment]
I got this too @kylecarbs 

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/2022166/176177067-176f72c1-f02e-4d3f-97e2-bee6224ece42.png">

**Comment by kylecarbs** [comment]
A new release is coming out now which should fix it!
