### ISSUE TITLE
Docker container fails to start for a workspace created from docker-code-server template on running on coder with --tunnel option

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2706]
coder version:
Coder v0.7.6+a494489
OS Windows

I have faced the following issue, I wanted to create a workspace from docker-code-server template, out of the box
The following scenario works for me

1. launch coder with `coder server`  -> coder is launched on (http://127.0.0.1:3000)
2. Init template: code-server in Docker
3. Create template using what is out of box
4. Create a workspace from this templates - workspace is created, and vs-code is available

If I use `coder server --tunnel` and all the steps as for scenario above:
Create a template:  code-server in Docker
Create a workspace from that template, I get docker contained in exited state with error : 
![image](https://user-images.githubusercontent.com/9592232/176243053-a5d157ea-4152-4975-892e-8c251790f00d.png)
And on portal for such workspace a see:

![image](https://user-images.githubusercontent.com/9592232/176243226-fd046a9a-6024-45a6-ad63-2790f1beb61f.png)

**Comment by bpmct** [comment]
Our tunnel has changed significantly since then and I was unable to reproduce this on my Windows machine. I suspect the issue was the tunnel was not serving the `/bin` folder.
