### ISSUE TITLE
`coder templates push` pre-hook

### ISSUE THREAD

**Issue by ketang** [coder/coder#2707]
Let's say we have a template with multiple editors.  The template is stored in revision control.  I want to make sure that nobody runs `coder templates push` from an out of date working directory.  A good solution would be a hook that ran before executing the push and returned `0` when the push can go ahead and anything else to reject it.  I think it's fine to require that this hook be in the same directory (or directory tree).  We could make it configurable, or we could just say that we'll run everything in `./hooks/pre`, and they all need to pass.

We will likely want post push hooks as well, but those can be server-side rather than client-side.

**Comment by bpmct** [comment]
If templates are stored in revision control, `coder templates <push/update/edit>` should probably be disabled and left up to CI or Coder's own update mechanism. Then, pre-commit hooks or CI can be left to do any checks.

I suggest we close, but perhaps I'm misunderstanding @ketang
