### ISSUE TITLE
Parameters design and UX flow for editing/creating parameters associated with template versions/workspaces

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#2719]
# Problem

Currently parameters have some ambiguity around how they are supposed to behave. 
- Parameters currently act in a hierarchy: `workspace > version > template`. 
- The prompting for params depends on the `sensitive` field of the terraform variable.
- Parameter scope `template` is unused in the codebase.
- Parameter scope `import_job` is associated with a job, but should probably be tied to a template_version

CLI prompts for new params and handles deleted params in a new version, but the UI does not. The decision tree for how to handle param prompting is complex.
- Do param files override previous version values?
- Should param files require all values? Just new values?
- UI has to copy the cli behavior

CLI param handling code is unique for template flow and workspace flow. We should unify this logic.
- What if workspace sets a "sensitive" value?

Who can read param values? Secret values? 

How to inherit params from previous version/workspace build?

# Design

A design document for params should be created on how params should function. From the terraform value, to the database store, to how to fill in param values. The terraform file _should_ be able to indicate where values should be prompted (at the version create or workspace create)

A good parameter viewer to indicate which param values are associated with a version/workspace and where they came from. Maybe an editor to change these values??

Should we keep a param hierarchy? Or should some values be required to be set at a certain scope, and disallow workspaces from setting them?

Prompt for missing params does not cleanup broken template versions.

# Acceptance Criteria

- [ ] Design doc detailing how to use params as a developer and as a user
- [ ] ???

**Comment by bpmct** [comment]
@Emyrk and I discussed how the behavior is slightly different now as template-wide (e.g `sensitive`) parameters cannot be overridden by the workspace now: https://github.com/coder/coder/blob/f7ea016494c1a936649cfebd287e03618bd242bb/coderd/parameter/compute.go#L183-L187

**Comment by kylecarbs** [comment]
@Emyrk do you want to own this? I feel like you're passionate about it.

**Comment by Emyrk** [comment]
@kylecarbs Yes. With @deansheather 's latest mini RFC, I want that "approved" first from a terraform design. Then we can determine the backend design imo.

**Comment by bpmct** [comment]
Closing since #4311 reworks this
