### ISSUE TITLE
Make it possible to delete user accounts

### ISSUE THREAD

**Issue by ntimo** [coder/coder#2731]
## Synopsis
Currently its not possible to delete user accounts.

## Feature description
It should be possible to delete user accounts, and not just suspend them. Deletion should be possible using the cli and the web ui. And all the resources attached to the user should be removed with them. 

## Why is this necessary
E.g. a person leaves a team then the account should be deleted not just suspended.

**Comment by Emyrk** [comment]
We don't have audit logging _yet_, but we will. In Coder v1 we saw the problem that audit logs use `id` fields to reference resources (like users). When you delete the user, you lose the contextual information like "username", "email", etc.

I would like to ask what is that deletion can do that suspension cannot? Suspended users cannot interact with the product anymore, and cannot re-authenticate. A deleted user could use oidc to "regenerate" their account.

I do know that currently the suspension feature is pretty "soft" as their resources still exist (workspaces etc). It would be nice to have an easier time cleaning up these remaining resources.

**Comment by BrunoQuaresma** [comment]
@Emyrk I liked the idea of having a "Clean up user resources" feature. We also could display on the "Suspend" confirmation an option to clean up the resources.

**Comment by ketang** [comment]
Suspending a user ought to halt all their workspaces and workspace schedules.

What if we suspend a template owner?

We will need actual deletion at some point.  You don't want to suspend someone who quit.  It doesn't have to be a database deletion; I think tombstoning is fine, just as long as it doesn't interfere with anything (e.g. someone using the same username or email in the future).

**Comment by ammario** [comment]
We can begin by rejecting deletes when the user has workspaces.

**Comment by BrunoQuaresma** [comment]
Since we have audit logs, is that ok for us to start working on this one?

**Comment by bpmct** [comment]
Absolutely, but I think @kylecarbs is working on this?

**Comment by BrunoQuaresma** [comment]
Ahhh I see he is assigned. My bad.
