### ISSUE TITLE
Allow setting shutdown schedule at time of workspace creation

### ISSUE THREAD

**Issue by matifali** [coder/coder#2733]
In the current version we do not have any settings in the webui to set a shutdown schedule for a new workspace. 

I propose to add a default shutdown schedule in the template and also a setting to choose while creating the workspaces.

**Comment by bpmct** [comment]
@matifali Thanks for your issue - sorry we're just seeing this now. I've edited the title to include web dashboard. In the CLI, you can do this with

```sh
coder templates edit <template-name> --max_ttl [seconds]
```

**Comment by matifali** [comment]
Hasent this been addressed already?

**Comment by bpmct** [comment]
@deansheather what are your thoughts on this? There's also #5572, so I'm curious how you think that should play in?

**Comment by matifali** [comment]
Hi! @BrunoQuaresma would you like to do that or should we close as not planned?

**Comment by BrunoQuaresma** [comment]
I think we can close for now, but I think we have something like this already 🤔

**Comment by matifali** [comment]
We have but not at time of workspace creation, We can only change the schedule after the workspace is created
