### ISSUE TITLE
All users have the same ssh public key. 

### ISSUE THREAD

**Issue by matifali** [coder/coder#2734]
Coder inserts a private key in every workspace it creates and gives users a public key to add to services like GitHub. 

When we create multiple users, I have noticed that they have the exact same public ssh key. 

I believe it should be different for all users.

**Comment by mark-theshark** [comment]
@matifali Hi, I just created a second user in my deployment, and although first part has some similar characters, I see that they are different.  Have you tried copy and pasting out each into an editor and comparing?

**Comment by matifali** [comment]
Thank you @mark-theshark I rechecked and you are correct. I did not check the end chracters.
