### ISSUE TITLE
Provide a `coder upgrade` command that pulls `coder` directly from the server

### ISSUE THREAD

**Issue by sreya** [coder/coder#2744]
It would be great if the CLI provided a way to download the client directly from a deployment. While `curl -L https://coder.com/install.sh | sh` is great for getting started, for users who did not set up the deployment it still requires some work to determine the correct version their deployment is running and then ensure they download the correct client. It also has the added benefit of making it super easy to switch seamlessly between multiple deployments. Just run `coder upgrade --url "https://my-coder.com"` and your `coder` binary is now synced with the deployment you plan on interfacing with.

**Comment by matifali** [comment]
I am doing this for all my end devices using 
`curl -o .local/bin "https://my-coder.com/bin/coder-linux-amd64" && chmod +x .local/bin/coder`
This works for first install as well as upgrades.

**Comment by bpmct** [comment]
The install script could detect if you have Coder installed & authenticated, query the version, and download the proper asset from GitHub releases.

**Comment by matifali** [comment]
Bump

**Comment by bpmct** [comment]
Kinda related #5781

**Comment by matifali** [comment]
yeah, a simple `fly version upgrade` is all you need.

**Comment by matifali** [comment]
`flyctl` keeps it as a warning if there is a new version available for all subsequent commands.

**Comment by matifali** [comment]
we can call it `coder version upgrade` maybe.

**Comment by stirby** [comment]
Bumping this over #10718. Customer recently requested, it's a high priority for them.
