### ISSUE TITLE
Variable Project Id from default gcp templates fail to pass from UI for workspace creation

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2747]
Coder version Coder v0.7.6+a494489

I did templates init for Google Cloud Windows and Linux templates. The only change was done - path to credentials added - see file attached. Template is successfully created, but workspace fails to be created via UI. Creation via CLI works.

Steps:
1. Do templates init for gcp-linux or gcp-windows
2. Edit main.tf to add path to creds
3. Create template - template is created, user is requested to set project id 
4. Try to create a workspace via cli -> pass project id -> workspace is created successfully
5. Open Portal and try to create a workspace via created template: pass project Id and choose a region
6. Click Submit

Actual:  Workspace fails to be created via UI

https://user-images.githubusercontent.com/9592232/176646343-e9b24e9a-c3ce-401d-9281-11ef4ed03e8f.mp4

Via CLI - all is ok:

![image](https://user-images.githubusercontent.com/9592232/176647906-6bf05427-3241-4ccc-ba68-bb61903887e0.png)

Expected: Workspace is created

Note: if I add default value in template for project id - all works fine

Content of my .tf file
[main.txt](https://github.com/coder/coder/files/9018415/main.txt)

**Comment by kylecarbs** [comment]
Not sure what the action is here.
