### ISSUE TITLE
Move workspace actions into a grouped button

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#2748]
Moving the workspace actions into a grouped button will help us to free up some space in the header making some space to accommodate the schedule info.

**Design:**
<img width="1792" alt="Action dropdown" src="https://user-images.githubusercontent.com/3165839/176695458-92d6f48f-d2c4-4629-b839-b6088fffdbae.png">

**Figma link:**
https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-v2-Design?node-id=444%3A603

**How it works:**
- The main action should be on the left, and the other secondary actions, inside of the dropdown.
- If there are no secondary actions, we can just disable the dropdown instead of "hide" it to avoid flickering the screen.
- The button should have a fixed width to avoid size changes between states to avoid flickering the screen.
- By flickering, I mean things that can change size quickly and modify the layout too fast causing a weird feeling of "laggy". 

**Considerations:**
- We should try to always use existent components from the codebase or Material UI package.
- We should use existing colors.
- The grouped button should be accessible via keyboard.
- Please, let me know if you have any questions about this.
- The "schedule" component will be made in another ticket.
- if we are in an intermediate state and have the following actions: start | stop | delete -> display start, hides stop and delete

**Comment by Kira-Pilot** [comment]
chatted with Bruno about #1928. Below is the outcome for intermediate states.
Will update the AC.

Case:
start | stop | delete -> display start, hides stop and delete
cancel | delete -> display cancel, hides delete
cancel -> display cancel
