### ISSUE TITLE
Make a more helpful UI error message when failing to update schedule

### ISSUE THREAD

**Issue by sreya** [coder/coder#2752]
### Updated problem statement
The backend error has been fixed, but the frontend validation of TTL has a bug. It's hard-coded to have a certain max, but in reality the max comes from the template. The frontend should validate based on the template max so the user gets feedback before submitting the form.

### Initial problem statement
In this case, the user attempted to add a value that was greater than the maximum TTL. They were prevented from doing so, but the error message was not helpful and did not indicate why it did not work. 

![image](https://user-images.githubusercontent.com/4856196/176726906-f81116b6-f1bb-461a-897a-15a178782d11.png)

payload:

```
{"message":"Error updating workspace time until shutdown!","detail":"execute transaction: ttl must be below template maximum 12h0m0s","validations":[{"field":"ttl_ms","detail":"ttl must be below template maximum 12h0m0s"}]}
```

## Definition of Done

Given a template has a max TTL of n hours,
When a user enters a TTL higher than n,
Then the user sees red text saying that the "time until shutdown" (not TTL) is higher than their template max, and giving their template max, and the form cannot be submitted.
When the user changes the number to be <= n, 
Then the error message disappears and the form can be submitted.

**Comment by ketang** [comment]
Is the issue that there's not a visible helpful error message even though the back end provides one?

**Comment by sreya** [comment]
Pretty much. Given that we seem to be able to know the max TTL ahead of time I shouldn't be able to input a value greater than the maximum.

**Comment by presleyp** [comment]
This ticket can serve for the FE validation while #3097 handles surfacing BE errors. The FE has the max TTL hard-coded in WorkspaceScheduleForm.tsx, but it should be pulled from the template.

**Comment by misskniss** [comment]
Moving this to the backlog;. This behavior may change based on #2995 coming up.

**Comment by presleyp** [comment]
#3497 did most of the work for fixing this and then was closed; when we're ready for more work on this it may be helpful!
