### ISSUE TITLE
Additional output formats from the command line

### ISSUE THREAD

**Issue by ketang** [coder/coder#2753]
### Problem
Some users may want to have additional format options for CLI output for easier reading or data usage or testing, such as json or table output. 

### Definition of Done
We should allow CLI users to specify a different format for the output for non-interactive uses.  The immediate use case is testing, but I think it would be good for users as well.  I propose we use `--format=json`.  An alternative is `--json`, but that's a little less forward-compatible with other formats in the future.  An open question is whether we allow use of this format when someone is interactively typing in inputs.  I don't have a strong feeling about it; I'm open to other people's stronger feelings or just whatever is easiest.

### Acceptance Criteria

- New optional global flag on all CLI commands called `--output` (shorthand `-o`) with available values `"table"` and `"json"`.
- When the flag is specified, the output format should match the flag if the command supports it
    - Some commands won't support the output flag because they don't really output anything other than a "success" message, like `login`
- Ensure that no errors/log statements are being written to stdout, they should only be written to stderr
- Ensure that no output is being written to stderr, they should only be written to stdout

**Comment by ammario** [comment]
This is a nice convenience provided by k8s, gcloud and others. The challenge is it leads to a rigid interface that restricts the expressiveness of our human-readable output. I think we should wait until there's large demand for scriptability so as to not hurt the experience of new users.

**Comment by ketang** [comment]
How would it hurt their experience?

There's a near-immediate need for this for automated testing.

**Comment by ketang** [comment]
Ok I think we're talking about different things.  What I'm proposing is that, if you pass `--format=json`, you don't see any part of the interactive UI unless there's an error.  You get a JSON dump of action results to `stdout` which you would probably pipe or redirect.  I'm not talking about how that JSON dump is structured (yet).  I'm also most heavily considering commands that initiate actions; the actions you show above are descriptive ones, which may need a different treatment (e.g. `.yaml` like your first example).

**Comment by ammario** [comment]
I think we're aligned actually, and I think I'm guessing too much about the engineering difficulty—that would be better for an engineer to suss out.

I think `json` is better to start with due to `jq`... but also adding yaml should be trivial then.

**Comment by ketang** [comment]
Also you get 95% of the benefit with output to *any* common structured data format; providing a specific different one on top of that is going to be just 5%.

**Comment by bpmct** [comment]
@deansheather since you did #3176, how would you estimate doing this for `templates` and `workspaces` in the CLI too? unsure if it'd be better to do a generic approach or duplicate work

**Comment by bpmct** [comment]
To clarify, just supporting JSON output, not other stuff

**Comment by deansheather** [comment]
I don't think we should add yaml support unless we plan on letting people supply yaml files to create commands ala `kubectl apply -f file.yaml`. Otherwise there's no purpose of having yaml output. JSON output is very useful because you can pipe it into jq and process it further

IDK what the estimate would be, I'd probably spend a little bit of time splitting my current implementation for the `coder users list/get` commands up into reusable components, move the flag to be a global flag, and then write some output glue that figures out how to output based on the flag. So probably a 3

**Comment by ketang** [comment]
YAML format is unnecessary at this point but our choices re JSON will dictate what the YAML looks like, and we will want to do that eventually, so it bears a small amount of thought today.
