### ISSUE TITLE
Allow Coder agent to detect if it is orphaned and take actions

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#2754]
# Problem:

It's possible for Coder to provision instances that do not get cleaned up (for example, if you run in development mode and kill the server before it has a chance to clean up).

This is a possible cost leak for developing or hacking on Coder if you use a template that can provision resources that cost money.

# Proposed Solution (high-level):

We had a brainstorm in office hours and had the idea of adding the capability to the Coder agent to trigger some action if it is unable to phone home after a number of tries / specific length of time.

This action could be one or more of the following, depending on specific requirements:
- Send a notification to an email address (e.g. via AWS SNS)
- Shut down the instance
- Terminate the instance

Essentially we'd be adding lifecycle hooks on a workspace agent that get triggered on failing to phone home to Coder consistently for a given duration.

We'd probably want this action to be configurable in the workspace template.

# User Story

Alice is working on adding a feature to Coder that involves creating resources in Rainforest Cloud Services (RCS) using a workspace template. She is conscious of the cost of spinning up these workspaces, so she adds a lifecycle hook to her template that triggers when the instance fails to connect to her development Coder instance after 2 hours that stop the instance. 
She then continues working on her feature implementation, testing creating resources in RCS. She closes her laptop at the end of her working day, and her Coder development server gets suspended. The test resources she creates in RCS time out after 2 hours, and clean themselves up automatically.

**Comment by kylecarbs** [comment]
These are great ideas!
