### ISSUE TITLE
Create user flow password selection is cumbersome/insecure

### ISSUE THREAD

**Issue by ammario** [coder/coder#2756]
<img width="654" alt="Screen Shot 2022-06-30 at 11 23 53 AM" src="https://user-images.githubusercontent.com/7416144/176728716-edf38706-06b8-46c5-a672-d11c1e302047.png">

As an administrator, generating a secure password involves going to another website and copying some generated password. I might also just smash my keyboard and use an insecure password such as "dog123" or "Asdf234".

Neither of these workflows are ideal.

**Comment by ketang** [comment]
So you want us to generate a random password for them?  Seems like it would make things a little smoother.

> generating a secure password involves going to another website and copying some generated password

With respect to prioritization, though, how is this different from every other signup flow?

**Comment by ammario** [comment]
Most sign up flows I interact with generate a random password when adding a new user.

**Comment by ketang** [comment]
🤦🏾‍♂️ oh right, this is the *admin* flow

**Comment by ammario** [comment]
Another security issue: this password field autofills to the password saved in your browser, which is likely the admin account.

**Comment by kotx** [comment]
> Another security issue: this password field autofills to the password saved in your browser, which is likely to the admin account.

It would be better to use `autocomplete="new-password"` in the `<input>` tag. Usually the user-agent (browser) will automatically generate a password. (Or if we want to avoid the browser saving that generated password, we can set `autocomplete="none"`).

**Comment by ammario** [comment]
Let's move to https://github.com/coder/coder/issues/4308
