### ISSUE TITLE
Logging out from web terminal keeps window open

### ISSUE THREAD

**Issue by ketang** [coder/coder#2762]
If I intentionally exit the shell, I expect the window to go away.  In v1 we offered a reconnect option; I'd like to think we can tell when it's an intended exit versus e.g. a network problem and just do the right thing without asking for an additional input.

![image](https://user-images.githubusercontent.com/33678/176758141-24e0edb5-e6b4-4565-acdf-666b2888d53e.png)

**Comment by kylecarbs** [comment]
#2156
