### ISSUE TITLE
Make the applications more notable in the resources table

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#2763]
Right now, the applications are not very easy to find on the workspaces page. To solve that, we can style the application links to look like buttons. See the screenshot below:
![image](https://user-images.githubusercontent.com/3165839/176761990-b71962de-29cb-4f1f-8b66-1e723a634708.png)

You can also check some user feedback here: https://discord.com/channels/747933592273027093/992114316486647838/992119290226548816

**Details**
The screenshot attached is using:
- padding as `8px 12px`
- border radius as 2px
- font size as 14px
- gap is 4px
- it is flex and uses flex-wrap in case we have more items

Feel free to change those values if you think they are not looking good during the implementation.

**Comment by ketang** [comment]
That's pretty far to the right.  I want to get rid of that AGENT column, but if that's held up, how about swapping the order?  Or even putting the buttons with the RESOURCE column?

**Comment by BrunoQuaresma** [comment]
Hm... Idk, I think the right alignment for actions is consistent with other "table" UIs where the actions are on the right. Saying that because usually, users expect a repeatable pattern. But I'm also working on improving the resources table, you can see what it looks like here: https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-v2-Design?node-id=473%3A612

**Comment by ketang** [comment]
That's a fair argument.  I guess it's just that it's so faaaaar to the right.

**Comment by ketang** [comment]
Here's what it looks like
![image](https://user-images.githubusercontent.com/33678/176955247-95b4d732-0705-4f26-b82c-a1dacde44538.png)

**Comment by BrunoQuaresma** [comment]
We had another update a few minutes ago and now it looks like this:
<img width="1792" alt="Screen Shot 2022-07-01 at 16 11 31" src="https://user-images.githubusercontent.com/3165839/176956958-413aab3a-8d61-4a40-bdd9-6df88ce8f7f9.png">
