### ISSUE TITLE
Bug in v0.7.6 a494489: web terminal gets disconnected after about 1 min. of inactivity

### ISSUE THREAD

**Issue by kconley-sq** [coder/coder#2769]
## Expected Behavior

Web terminal does not disconnect due to user inactivity (otherwise assuming a workspace remains online).

## Current Behavior

Web terminal gets disconnected after about 1 minute of inactivity, requiring the user to refresh the window to resume their web terminal session.

**Comment by kylecarbs** [comment]
#2779 should fix this! Let's track it there.
