### ISSUE TITLE
coder templates pull displays some numbers/null

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#2777]
[Coder v0.7.6](https://github.com/coder/coder/commit/a494489ffac76d977c2733c8d33112bf95235ea3)
Windows 10, cmd

Steps:
run coder templates pull [template] and write to a file
view cli output and file content

Actual Result: some numbers are displayed in console after readme.md and main.tf, also NULL displays in the file
![image](https://user-images.githubusercontent.com/35501151/176922630-627f9d41-dfb1-4490-bc04-7a1a62b340f7.png)

**Comment by bpmct** [comment]
@maryna-hankevich how are you writing to a file? We have seen some reports on Windows that:

```sh
# doesn't work on Windows
coder templates pull template-name > filename.tar.gz

# but this does work
coder templates pull template-name filename.tar.gz
```

**Comment by maryna-hankevich** [comment]
@bpmct  I'm writing to a file using the following command: `coder templates pull docker file`
This is probably some archive data or something like that, not sure if it should be displayed or if it's possible to get rid of it

**Comment by bpmct** [comment]
Gotcha. The `pull` will add it into an archive file which you'll need to extract. However, this isn't super clear from the help text #2651.

Here's how to get clean files with Windows and 7-zip:

https://user-images.githubusercontent.com/22407953/182184248-378eb987-bf5f-4d04-860a-15268a30040f.mov
