### ISSUE TITLE
Workspace page: Agents order is changing on UI endlessly

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2778]
## Problem statement

Workspaces with a resource with multiple agents, such as our [kubernetes multi-service](https://github.com/coder/coder/tree/main/examples/templates/kubernetes-multi-service) have the agents constantly switching orders.

To reproduce:

- Create a template with the `kubernetes-multi-service` template
- Observe the agents flipping around every 5 seconds

## Definition of done

Workspaces with:
- one resource, but multiple agents
- multiple resources, with multiple agents

do not change order in the UI. Reproduced in Coder v0.8.1

https://user-images.githubusercontent.com/9592232/176929117-aeb4798d-4711-49a4-be7b-fddf004565c1.mp4

**Comment by ketang** [comment]
Hmmm the code #2612 is the same, so this must be happening somewhere else.  Either something in the back end is disrupting the order, or something in the front end is.

**Comment by ketang** [comment]
It's something in the backend.  I spied on the API calls and a few seconds apart saw two responses with different orderings (responses *highly* abridged):
```
[  {
    "agents": [
      {
        "id": "8ca5ba19-7788-4952-882a-4d47d444b56a",
        "name": "go",
      },
      {
        "id": "3e92eca6-9871-4c7e-96e5-6730a8b25be9",
        "name": "java",
      },
      {
        "id": "6cc5712d-1ded-413f-9ef8-fc2abb54b244",
        "name": "ubuntu",
      }    ]  }]
```
Then:
```
[  {
    "agents": [
      {
        "id": "3e92eca6-9871-4c7e-96e5-6730a8b25be9",
        "name": "java",
      },
      {
        "id": "6cc5712d-1ded-413f-9ef8-fc2abb54b244",
        "name": "ubuntu",
      },
      {
        "id": "8ca5ba19-7788-4952-882a-4d47d444b56a",
        "name": "go",
      }    ]  }]
```
