### ISSUE TITLE
Allow simultaneous logins to multiple Coder instances from the command line

### ISSUE THREAD

**Issue by ketang** [coder/coder#2786]
Currently I can only be logged in to one Coder instance at a time.  To run commands against a different one, I have to log out of the first, then log into the second.  In more complex environments, users are likely to want to be able to log in to multiple Coder instances simultaneously.  In such a situation we will need them to specify which instance they mean or prompt them.  Here's an idea for how that might work:
* when they log in to a second URL, we ask them to provide a name for both that and the first one
* commands use the instance specified according to the following logic:
  1. if there is a `-i/--instance` parameter specified, use that.  The parameter takes either a name or the instance URL.  If it's invalid, fail.
  2. if there is an environment variable `CODER_DEFAULT_INSTANCE`, use that.  If it's invalid, fail.
  3. use the instance set as default
* we add a command `coder instance default <name>/<url>`; this sets the referenced instance as the default.  Other commands might include `coder instance list` and `coder instance rename <old name> <new name>`

Open question: is `coder instance --default` local to the current shell, or is it across all of the user's shells on this machine?  I see arguments for both sides.

**Comment by ketang** [comment]
The above does not handle multitenancy if all the tenants share a common hostname.  If they're required to have different hostnames, e.g. `alpha.coder.example.com` and `beta.coder.example.com`, it's fine.

**Comment by bpmct** [comment]
This would be super nice as I'm currently switching between 3 Coder deployments. At some point, I may create a workaround/shell script to set different `$CODER_CONFIG_DIR` variables in my shell.

However, it would be great to have a first-class feature. I may have an odd use case switching between deployments but it would definitely improve my workflow.
