### ISSUE TITLE
One click start over for workspace

### ISSUE THREAD

**Issue by ketang** [coder/coder#2794]
Suppose I get my workspace in a bad state.  I want to rebuild it the exact same way but from scratch.  Right now I:
1. delete
2. confirm I want to delete
3. navigate to templates page
4. choose a template
5. click create workspace
6. enter in the name and other parameters (which could be numerous)
7. submit

Better would be to have a button that allows me to roll up the above into two steps: ask to rebuild and confirm.

In addition, it would be cool if you could do something similar from from the message you see when you're looking at a workspace that has been deleted:
![image](https://user-images.githubusercontent.com/33678/176967770-d8ad48bc-53d4-449a-95af-971260ca9ea3.png)

We would also need to do this in the CLI.

**Comment by kylecarbs** [comment]
I don't think we need this right now. It's cool, but there are higher impact issues.
