### ISSUE TITLE
When a job fails, suggest that the user try again

### ISSUE THREAD

**Issue by ketang** [coder/coder#2795]
I had a stop job fail.  I stared at it and assumed I'd found a bug (was setting up weird stuff for a different situation).  Then when I tried to replicate it in a new workspace, I couldn't.  I went back to the original and tried again, and it worked fine.  If I had been a regular user, that would have been the right thing for me to do.  We should say so.

**Comment by kylecarbs** [comment]
I think it's relatively implicit, so this is loooow prio for now.
