### ISSUE TITLE
"Starts at Manual" is confusing

### ISSUE THREAD

**Issue by ammario** [coder/coder#2798]
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/7416144/177009439-7aa47f43-fd3c-4744-84e1-6042015999ab.png">

I understand this is our internal representation of the start behavior, but "manual" isn't a human time. It could say "Starts manually" but I think we can remove the element altogether as no schedule implies manual start.

cc @tjcran @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
I agree, I think we can hide the schedule info if there is no schedule at all instead of display "Manual". 👍

**Comment by ketang** [comment]
I think there's something to be said for a placeholder rather than eliminating it completely.  Perhaps there's clearer phrasing, though, like "Starts on demand."

**Comment by ketang** [comment]
I think this is not a `bug` because it works as designed.  There certainly are flaws with the design, so I added `ux-defect` instead.

**Comment by BrunoQuaresma** [comment]
> I think there's something to be said for a placeholder rather than eliminating it completely. Perhaps there's clearer phrasing, though, like "Starts on demand."

I like this suggestion as well!
