### ISSUE TITLE
Provide more help when Terraform script fails

### ISSUE THREAD

**Issue by ketang** [coder/coder#2806]
I made a mistake in my Terraform script:
```
$ coder templates update
> Upload "/tmp/tmpltz/docker-amd64"? (yes/no) yes
✔ Queued [193ms]
# ... blah blah blah
✔ Parsing template parameters [104ms]
⧗  Detecting persistent resources
  Terraform 1.1.9
  Error: Invalid operand
  Unsuitable value for left operand: a number is required.
  Error: Invalid operand
  Unsuitable value for left operand: a number is required.
✔ Detecting persistent resources [1824ms]
✘ Cleaning Up [152ms]
template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1
Run 'coder templates update --help' for usage.
```
Not helpful at all.

We should do at least:
* suggest the user run `terraform validate` locally
* when that passes, as it happened to in this case, tell them to run `terraform plan`

**Comment by kylecarbs** [comment]
This might be the case where we shouldn't suppress any output from Terraform. We do in the CLI right now, but that should probably just be changed.

**Comment by ketang** [comment]
I think having the current behavior by default is actually just fine.  Full output is going to be too much information for some users.  I think making the full output available but hidden by default is a good compromise.
