### ISSUE TITLE
Docs: quickstart should describe how to log in

### ISSUE THREAD

**Issue by ketang** [coder/coder#2808]
The Installation docs start with installation and finish with a `coder server` invocation.  The Quickstart docs start with `coder templates init`.  In between we need to tell the user how to log in to the web app and log in from the command line.

**Comment by kylecarbs** [comment]
![image](https://user-images.githubusercontent.com/7122116/186471142-e83a8547-39c6-4d35-9666-6d771c4a21f4.png)
