### ISSUE TITLE
Browser-free login to built in user database

### ISSUE THREAD

**Issue by ketang** [coder/coder#2810]
I should be able to log in with a username and password on the command line without having to go to the browser and get a session token.  This probably only works for built-in users, but that's okay.

It'd be nice if we could do something smart with `ssh-agent` too.

**Comment by bpmct** [comment]
You can now do this with 

```sh
coder login --email ben@coder.com --password not-telling-you

# or
coder login --username bpmct --password not-telling-you
```

It also consumes environment variables so you don't have to put secrets in stdin

**Comment by bpmct** [comment]
Ok well I just learned this feature is broken #2574 but it is a feature lol
