### ISSUE TITLE
Distinguish better between "Connected" and "Connecting" in workspace page

### ISSUE THREAD

**Issue by ketang** [coder/coder#2828]
`Connecting` and `Connected` use the same color and are nearly identical words.  We should change the former to blue (same color as a job in progress) and the latter to "Running."

![image](https://user-images.githubusercontent.com/33678/177188194-147a3755-1109-4245-9b9d-668f58de84ba.png)

![image](https://user-images.githubusercontent.com/33678/177188210-a3076922-7aa0-4bdb-b343-1771ae4d6036.png)

**Comment by ketang** [comment]
`Connecting` could also become something like `Initializing` if we want to keep `Connected`.

**Comment by kylecarbs** [comment]
It really is connecting, not initializing. The infrastructure is up, and the agent is being pulled.
