### ISSUE TITLE
`templates help create` should provide help on the `create` subcommand

### ISSUE THREAD

**Issue by ketang** [coder/coder#2835]
Currently you can only get help via `templates create --help`.

All subcommands should work this way, not just `templates`.

**Comment by kylecarbs** [comment]
Go does this in the inverse: `go help build`.

It becomes wonky when commands take a parameterized argument, eg. `coder templates delete help` could delete a template called help, or print out the help.

I think we should close this. `--help` seems fine from my perspective.

**Comment by ketang** [comment]
I'm fine with doing the inverse if we make it consistent, e.g. everything goes through the top level `help` command or `--help`:
* `coder help config-ssh`
* `coder help templates list`
