### ISSUE TITLE
Fail to install using docker-compose: getting "Error response from daemon: manifest unknown"

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2837]
coder version: 0.7.6

I'm following the steps from installation guide: https://coder.com/docs/coder-oss/latest/install: docker-compose

Steps from guide:
1. Clone the coder repository:
git clone https://github.com/coder/coder.git
2. Otherwise, you can start the service:
cd coder
docker-compose up

Getting output as:

`⠿ database Error                                                          0.9s
 ⠿ coder Error                                                             0.9s
Error response from daemon: manifest unknown`

<img width="568" alt="test" src="https://user-images.githubusercontent.com/9592232/177311263-d4249c1c-e89b-472e-9b16-c71cbc1d69c6.png">

**Comment by Thomas-Blakeney** [comment]
same Problem here

**Comment by Thomas-Blakeney** [comment]
Update: When you go in the docker-compose.yaml and change the line: `image: ghcr.io/coder/coder:v${...}` to for example: `image: ghcr.io/coder/coder:v0.7.7` then it works

**Comment by bpmct** [comment]
Fixed in #2557
