### ISSUE TITLE
0.7.6 `tunnel` session not resolving in browser; telemetry error in `coder server`

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2839]
I have been experiencing this with `tunnel` since 3 July 2022

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2022166/177338467-a2297d99-4523-4b55-aa68-fdf5eea4a05f.png">

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2022166/177338584-1542c829-315d-41d0-a2af-d1a8c7e190ae.png">

**Comment by rahulvramesh** [comment]
am having the same issue both in browser and terminal
<img width="786" alt="Screenshot 2022-07-05 at 9 44 45 PM" src="https://user-images.githubusercontent.com/4546714/177371986-c4019dfe-e2dc-4535-a4c7-8c43cd3dab01.png">

**Comment by kylecarbs** [comment]
@coadler any thoughts? Is this fixes?
