### ISSUE TITLE
No error message when creating a workspace with a conflicting name

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2842]
## Problem
A user was not given a proper error message when attempting to create a workspace with an existing name.

## Definition of Done
When attempting to make a conflicting workspace name, there should be an error that says this name cannot be used and why. 

coder version
[Coder v0.7.6-devel+4f1e9dae](https://github.com/coder/coder/commit/4f1e9dae278df000897a2dbb8b1e26b8033a4b13)

Steps:
1. Login to coder portal
2.  choose a template and click Create Workspace
3. Create a workspace with name: WorkspaceName1
4. Again choose a template and click Create Workspace
5. Enter workspace name as WorkspaceName1

Expected: Error message about workspace name already exists
Actual: Nothing happens even dialogue is not closed

https://user-images.githubusercontent.com/9592232/177737898-416e0177-69e2-488a-aa26-fa7550a47b11.mp4

**Comment by misskniss** [comment]
FYI: @bpmct  confirmed there is a backend message the the workspace already exists

**Comment by AbhineetJain** [comment]
We do not seem to be handling any errors on the create workspace page. https://github.com/coder/coder/issues/3343 intends to solve that. That should fix and close this issue.
