### ISSUE TITLE
Dotfiles: updated dotfiles repo url is not used after reboot if use 'coder dotfiles' command

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2843]
I expect that in case I change my dotfiles url via `coder dotfiles <new url>` it is saved and on startup the new values will be used, but it is not. 

I used shared template [docker-with-dotfiles]

And faced with the following behaviour - in case i have set a wrong value in repo url at creation time:

1. Create a workspace from docker-with-dotfiles, but specify dot files url as some not existing url
2. Open terminal and go to /tmp
3. Open coder-startup-script.log -> there is an error that failed to find repo 'fatal: repository <not existing repo> not found'
4. Run command `coder dotfiles <existing repo url>`
5. Follow steps and agree to install -> success, cloned and changes applied
6. Stop workspace and Start again
7. Go to the /tmp and open log coder-startup-script.log 
8. There is again an error 'fatal: repository <not existing repo> not found'

Expected - when I run this command I get my dot files url updated and on restart the new values is used
Actual the value is left as it was before

**Comment by bpmct** [comment]
`coder dotfiles` does not edit user's dotfiles settings, it only applies the dotfiles repo into the workspace. You'll need to edit the workspace's parameters with `coder update <my-workspace> --always-prompt` to specify a new dotfiles URL. 

You'll also need to delete your old dotfiles directory before "updating" your workspace.

https://coder.com/docs/coder-oss/latest/dotfiles
