### ISSUE TITLE
`templates create` should only ask for confirmation once

### ISSUE THREAD

**Issue by ketang** [coder/coder#2860]
`templates create` asks for confirmation at the very beginning and then again after doing some validation:
```
> Create and upload "/tmp/tmpltz"? (yes/no) yes
✔ Queued [19ms]
✔ Setting up [64ms]
✔ Adding README.md... [60ms]
...
✔ Cleaning Up [120ms]
┌─────────────────────────────────────────────┐
│ Template Preview                            │
...
└─────────────────────────────────────────────┘
> Confirm create? (yes/no)
```
Once is enough.

**Comment by kylecarbs** [comment]
Well, the prompts don't confirm the same thing. One is to permit uploading the local directory, and the other is to confirm the template preview is accurate.

I'd prefer to have less interaction, but it feels unexpected to upload the user's current directory without explicit permission, and awkward to create a template without ensuring the infrastructure resembles the desired.

**Comment by ketang** [comment]
From an implementation point of view they differ, but I don't think that's a meaningful distinction for users.  It's just going to be an opaque box.  Probably only 5% will even think about how much of the operation is remote versus local, and the proportion of those who will care?  Also, I doubt any of them will even think of it as permission; what I expect they'll use it for is confirmation that they're doing it correctly.  I don't care which confirmation we keep, but it shouldn't be both.  The user gains nothing.

Also it's pretty uncommon to request confirmation for a file upload.  I'm not seeing a reason for us to be different if it adds additional steps.

**Comment by kylecarbs** [comment]
It'd be pretty scary to me if software started uploading my home directory by just running a command without making it explicit. We could solve this by requiring explicit definition of the directory, but that's not a great user-experience either.

**Comment by bpmct** [comment]
Closing this issue for now.

- Conflicts with #2859 (which signifies the importance of the first confirmation)
- Both confirmations are valuable 1) confirms the directory (and eventually files) you'll upload 2) confirms the `terraform plan`. Would be a worse UX if one of those had unintended consequences and the admin has to clean up
- We have a lot of issues
