### ISSUE TITLE
Bug in v0.7.7 411caa2: workspace dashboard duplicate text

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#2869]
I have JetBrains IDE names for `coder_app` that use JetBrains-issued release names.

They do weird duplication and wrapping in  UI.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/2022166/178087252-aa2c0b4b-48d7-4918-8d1e-e5e220f505e2.png">

**Comment by mark-theshark** [comment]
External links to icons for `coder_app` are no longer allowed. Resolved by pointing to icons in `/icon/<ide name>`

Need to doc these images, they are in static folder.

<img width="781" alt="image" src="https://user-images.githubusercontent.com/2022166/178088087-de781f86-189d-4a09-92fc-e46f66c5d03f.png">

**Comment by mark-theshark** [comment]
More niceness 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2022166/178088887-d1abb6c6-bf61-499a-9ca9-1dac290404b6.png">

**Comment by kylecarbs** [comment]
Fixed by #2870
