### ISSUE TITLE
Outdated `workspace` does not automatically fetch new `template` on scheduled start

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#2871]
One of the benefits of a remote development platform is to keep all developers' environments (aka workspaces) consistent.

If an administrator or team leader updates a template, any workspace using that template should update itself automatically on a scheduled start.

In theory, if a developer has a scheduled start set, and relies on that to start their workspace every day, they could be on an older template unless they force an update.

*Maybe this is an enterprise edition feature*

## Expected Behavior

If a workspace shows `outdated` when the workspace is off, and when the workspace performs a scheduled start, it should update itself with the new template.

## Current Behavior

After a scheduled start, the workspace still shows `outdated`

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/2022166/178108676-7b0ef17f-3af3-4d54-aa4f-75a4991f0f88.png">

**Comment by ketang** [comment]
I had been assuming this was something where the customer would want options as described in #2600

**Comment by kylecarbs** [comment]
Automatically upgrading infrastructure sounds like risky business. I think we're better off adding more bulk-upgrade features, which will come to light with #2971
