### ISSUE TITLE
Allow renaming templates

### ISSUE THREAD

**Issue by ammario** [coder/coder#2877]
As a template admin, I want to efficiently inform my users that a template is deprecated. My preferred method of doing so would be to rename a template to `<oldname>-deprecated`. The user would likely explore the template README for the correct template.

**Comment by ketang** [comment]
Do you want renaming or do you want deprecation?   We should have renaming for its own sake.  Deprecation... perhaps we can handle that as a first class concept to go with our template update lifecycle.  It would prevent new workspaces from being created with that template but allow restarts of existing ones.

**Comment by ammario** [comment]
I want deprecation, but renaming seems like a good MVP solution.

**Comment by ketang** [comment]
I'm okay with this as a workaround.  I just wouldn't want to claim that this is the ideal way to handle deprecation.

**Comment by kylecarbs** [comment]
This is done!
