### ISSUE TITLE
Make all destructive operations default confirmation to "no"

### ISSUE THREAD

**Issue by ketang** [coder/coder#2878]
Some destructive operations have their confirmation behavior defaulting to "yes."  We should default to "yes" when the behavior is non-destructive, e.g. creating a workspace, but we should default to "no" when it's something destructive, like deleting a user.

**Comment by AbhineetJain** [comment]
Trying to figure out the list of _potentially_ destructive actions we have right now:
 - Deleting a template
 - Deleting a workspace
 - Suspending a user
 - Stopping a workspace
 - Logging out

@ketang Can you confirm if all these actions should default to `no`? Are there others you have in mind?
