### ISSUE TITLE
Clarify that SSH access is possible in dashboard

### ISSUE THREAD

**Issue by ammario** [coder/coder#2881]
As a user I may look at this:

<img width="1468" alt="Screen Shot 2022-07-09 at 3 48 36 PM" src="https://user-images.githubusercontent.com/7416144/178122157-853c2fb6-2382-48b7-884f-73886c01a9ef.png">

And assume that there is no way to use my local SSH tools with Coder.

**Comment by ketang** [comment]
Ignore the inconsistent styling.  And we'll want to fiddle with the layout.
![image](https://user-images.githubusercontent.com/33678/178162507-d8670c57-53f0-4aaa-8989-886b8588a43c.png)

**Comment by kylecarbs** [comment]
@BrunoQuaresma any thoughts?

**Comment by BrunoQuaresma** [comment]
I like @ketang suggestion but I would move the code into a popover like this:
<img width="377" alt="Screen Shot 2022-07-11 at 13 13 23" src="https://user-images.githubusercontent.com/3165839/178309758-ac7fda21-5f28-4573-b770-242871d60310.png">
So we can keep consistency in the Access elements having only buttons. Thoughts?

**Comment by ammario** [comment]
Looks great @BrunoQuaresma!

**Comment by kylecarbs** [comment]
I think we could make it `SSH` instead, but that seems reasonable to me. Maybe a CTA to install the Coder CLI too? It might be nice to have a link to set up VS Code Remote SSH as well.

**Comment by BrunoQuaresma** [comment]
- Only SSH makes the button very small 😕 this is the reason I used "Connect with"
- Not sure about the Coder CLI, it sounds like something more "global" than "agent related"
- I liked the idea of having a link for the VS Code Remote SSH guide

**Comment by kylecarbs** [comment]
I'm good with "Connect with SSH" in that case!

It's certainly more global, but maybe a link to install? I'd hate to provide the `coder ssh <name>` command line without a link to installing the CLI itself.

**Comment by BrunoQuaresma** [comment]
@kylecarbs we can add a link to "Install Coder CLI".

**Comment by kylecarbs** [comment]
Makes sense to me!

**Comment by kylecarbs** [comment]
@BrunoQuaresma should we assign you on this one? Seems like you're tackling it.
