### ISSUE TITLE
Redirect to login when PWA/Web-App is opened and cookie is expired

### ISSUE THREAD

**Issue by ntimo** [coder/coder#2884]
# Current Situation
Currently when a user opens a PWA e.g. code-server a message appears `{"message":"Cookie \"session_token\" or query parameter must be provided."}` stating that the cookie is expired. The user then has to open a new chrome window open the coder url login and refresh the pwa. This is not ideal of a workflow.

# Desired Solution
 The PWA page should just redirect to the login so that the user can authenticate and then load the application e.g. code-server.

# How to reproduce
1. Login to Code
2. Start a workspace with code-server
3. Install code-server as chrome pwa
4. Wait for auth cookie to expire or delete it
5. Open the PWA

**Comment by kylecarbs** [comment]
Ahh, good issue! We'll have to adjust our middleware handling to do an auth redirection instead.

**Comment by ketang** [comment]
@AbhineetJain might be related to PWA work you're looking at

**Comment by ntimo** [comment]
Thanks @kylecarbs for adding this so fast your are awesome.

**Comment by ntimo** [comment]
@kylecarbs I think there might be a bug. So my setup is the following. The workspace is running and I am logged out. I then open the PWA and get redirect to the login page, when I then login get a "code-server is offline!" page, and this is not the case. When I press Strg+R to reload the page code-server loads correctly.

**Comment by kylecarbs** [comment]
Ahh I know the issue. We cannot route via the frontend to these pages like
normal. I’ll make a PR to fix it.
