### ISSUE TITLE
Support starting the workspace when launching a `coder_app` when it's off

### ISSUE THREAD

**Issue by ntimo** [coder/coder#2909]
## Current situation
When a user starts a pwa of an app that runs inside of a workspace e.g. code-server and the workspace is turned off. The user is presented with this message `{"message":"No agents exist."}`. He then has to open another chrome window open the coder web ui and start the workspace.

## Desired Solution
Idea A)
Present a beautiful start button to start the workspace and then once the agent is connected refresh so the app (e.g. code-server) is loaded.
Idea B)
Autostart the workspace in the background since the user clearly wants to use it (since he opened the pwa) and show him a starting/loading animation/or the build logs. And then open the app e.g. code-server.

## How to reproduce
1. Login to coder
2. Create a workspace with code-server
3. Launch code-server and install it as a pwa
4. Stop the workspace
5. Launch the pwa

**Comment by bpmct** [comment]
Would also be awesome to support this over ssh!
