### ISSUE TITLE
Add download template button to template page

### ISSUE THREAD

**Issue by ammario** [coder/coder#2917]
As a curious (or broken) user, or a template administrator, I would like to download the template from the templates page so I can inspect it or even make an iteration to push.

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/7416144/178356830-d4f956e5-9007-42cb-903e-90bdb9040868.png">

**Comment by mark-theshark** [comment]
@ammario I like this, but have an icon to download and an icon to view. Not everyone has time to download and open a file.

**Comment by kylecarbs** [comment]
This is easy enough! We can just pull the file URL... which will be a `tar`!
