### ISSUE TITLE
Workspace schedule: timezone formatting is inconsistent

### ISSUE THREAD

**Issue by OlgaKhmelevskaya** [coder/coder#2925]
Coder v0.7.10+2c89e07
Windows 10, cmd, UI

**Steps to reproduce:**

1. Create workspace if does not exist
2. Login via CLI and run schedule command with the following parameters:
coder schedule start <workspace_name> 9:00PM Mon-Wed Asia/Seoul
3. Verify timezone formatting in CLI response

**Actual result:** Starts_at, Starts_next, Stops_next has different formatting
![2022-07-12_16-23-02](https://user-images.githubusercontent.com/107863254/178504331-9f6c7637-0c18-4e1b-aaf7-07c51b95b5c3.png)

**Expected result:** Starts_at, Starts_next, Stops_next has consistent formatting (e.g. GMT, UTC)

4. Open Workspace on UI -> Click Schedule

**Actual result:** Stops_at has no timezone
![2022-07-12_16-17-32](https://user-images.githubusercontent.com/107863254/178504707-bca2a3af-00dd-4eb0-84a9-ce064d574fcf.png)

**Expected result:** Stops_at has timezone consistent with CLI output

**Comment by kylecarbs** [comment]
Seems like a bug, but not necessary to fix ATM.
