### ISSUE TITLE
Logging out of WebUI invalidates CLI session tokens

### ISSUE THREAD

**Issue by mafredri** [coder/coder#2937]
Currently it doesn't seem possible for session tokens to outlive the session that created them. As a user I would expect the session token to be valid for X amount of time, not tied to login/logout from the browser.

Steps to reproduce:

1. Type `coder login https://coder` in the terminal
2. Open `https://coder/cli-auth` in browser
3. Log in and paste token into terminal
4. Observe `coder list` works
5. Return to browser and log out via menu
6. Observe `coder list` no longer works

Step 6. produces the following error:

```console
GET https://coder/api/v2/workspaces?q=: unexpected status code 401: API key is invalid.: Try logging in using 'coder login <url>'.
```

**Comment by mark-theshark** [comment]
@mafredri I'm curious what the v1 behavior is.

**Comment by ketang** [comment]
I suspect there's some overlap between resolving this and implementing #2786.

**Comment by ketang** [comment]
Perhaps more with #2810
