### ISSUE TITLE
docs: Missing CLI docs

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#2946]
We probably want to have docs about the CLI showing all the possible commands and arguments.

**Comment by bpmct** [comment]
The commands and arguments are changing day-to-day so I think if we were to document all this, it should be autogenerated. I personally find `--help` very useful on the CLI and think that only documenting common commands will be OK for now.

**Comment by ammario** [comment]
I agree @bpmct. And, we do document the CLI it's just indirectly through workflow guides.

We do not have the resources to ensure the CLI and manually written CLI docs stay consistent right now.
