### ISSUE TITLE
"By" in workspace page not helpful

### ISSUE THREAD

**Issue by ammario** [coder/coder#2952]
It's usually autostop, autostart, or myself. Why do I need to see that everywhere
<img width="1229" alt="Screen Shot 2022-07-12 at 5 53 26 PM" src="https://user-images.githubusercontent.com/7416144/178611852-9dfcebcc-50e1-42c1-8662-1496b0c66fe9.png">
?

**Comment by ketang** [comment]
Because it's not just about you.  The admin might want to see.  Like when I was shutting down workspaces over the break.  Or the admin might have done something.  And then when we have workspace sharing...

**Comment by ammario** [comment]
It seems like a column that should be optional and off by default. Kyle had a nice idea too where we could put this information into the "Last Built" column as some small text.

**Comment by kylecarbs** [comment]
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/7122116/179613912-fec4b92d-f2d9-43cc-b17e-147d88b743eb.png">
This has been completed by @BrunoQuaresma (I believe).
