### ISSUE TITLE
Selecting the build log should exclude time column

### ISSUE THREAD

**Issue by ammario** [coder/coder#2962]
<img width="1861" alt="image" src="https://user-images.githubusercontent.com/7416144/178630674-b66965ef-c918-4f46-8416-885b3284b1c2.png">

With the current behavior, it's onerous to share error messages from the build log.

**Comment by ketang** [comment]
Hmmm... I'm not sure.  In some situations those are useful.  For sure when you *don't* want them they're super annoying.  Maybe a decent middle is to do as you recommend and also have a link to download a `.log` file.

**Comment by ammario** [comment]
I'm all about downloading logs. 

As a reference point Actions doesn't select the line number.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/7416144/178643400-7729bf59-0679-4524-9a15-7ac9b3f9162e.png">

Most views like this don't.
