### ISSUE TITLE
Add a bare/blank template for writing custom Terraform

### ISSUE THREAD

**Issue by bpmct** [coder/coder#2964]
Coder templates can use any Terraform provider and Terraform resource, but Coder-specific knowledge is required to build functional templates:

- Coder Terraform provider
- Coder agent & init script
- start/stop (persistent and ephemeral resources)
- fetching workspace owner and name
- Coder apps

While this is now documented (#2377) and can be discovered by reading code for existing templates, a "slim/bare" starter template is also nice to have:

- self-documenting example of Coder's core functionality
- natural way to create a new template vs relying on memory or cherrypicking code from other examples

**Comment by ketang** [comment]
Good idea.
