### ISSUE TITLE
GCP template references Coder terraform provider v0.3.4 that doesn't support coder-app

### ISSUE THREAD

**Issue by nadzeyav** [coder/coder#2966]
## Problem
The issue is the following: I wanted to add code-server to my template created from shared template, but got an error that such resource is not supported. Only after change of template to use the latest one I was able to update template to add app url to workspace UI. 

1. Login to coder cli
2. Run: `coder templates init`
3. Choose: develop on Develop in Linux on Google Cloud

main.tf contains the following
![image](https://user-images.githubusercontent.com/9592232/178732726-9fd2b2c4-cfec-4b8c-9c57-5fe7a685e89a.png)

5. Change main.tf file to add code-server coder app (add section with resource "coder_app" "code-server" and change resource "coder_agent" "dev" section according to https://coder.com/docs/coder-oss/latest/ides/configuring-web-ides#code-server)
6. Create template: getting an error

![image](https://user-images.githubusercontent.com/9592232/178733381-2aa9bfe8-7570-4094-b0e7-7e9f0be6983c.png)

8. Update version to latest -> template is successfully created

## Definition of Done
GCP Example template uses latest version by default

**Comment by tjcran** [comment]
Related: #2179
