### ISSUE TITLE
Compute Resource Statistics

### ISSUE THREAD

**Issue by ammario** [coder/coder#2990]
As a developer, I want to see my resource consumption at a glance. This makes the UI look cool and can alert me to sizing issues with my workspace. Thus, it's related to #2121 and https://github.com/coder/coder/issues/2988.

<img width="458" alt="Screen Shot 2022-07-14 at 11 24 40 AM" src="https://user-images.githubusercontent.com/7416144/179030723-c26676da-e8b4-4f35-aaf8-7073db9f8abc.png">

Hopefully we can go beyond v1 and show special stats depending on environment detection. For example:
* Show GPU when one is available
* Break up CPU (user, sys, idle)
* Break up virtual memory (total, used, free)
* Show load average

**Comment by mark-theshark** [comment]
I want a mini HTOP widget @ammario Right now I use web terminal to do it.

**Comment by ammario** [comment]
haha yeah @mark-theshark... let's definitely not get caught up in the v1 design and shoot for something beautiful.

<img width="1029" alt="Screen Shot 2022-07-14 at 2 35 44 PM" src="https://user-images.githubusercontent.com/7416144/179068564-2b88a619-af70-4b04-b272-7b7a95b950ad.png">

**Comment by ketang** [comment]
Not to argue against something more webby, but we could launch an non-interactive "terminal" embedded in the workspace page that is just htop.

Is there an analogous CLI experience for this?  Other than `ssh` + `htop` of course.

**Comment by ammario** [comment]
That would require the user has `htop`, which is not included by default distros. We would also have to do some janky text processing to separate the process list from the resource values. We would also lose support for Windows. And, the element would be inconsistent with the rest of our design.

**Comment by ketang** [comment]
Fair enough.  At some point we will have to think about how to avoid limiting ourselves to the lowest common denominator, but now is not the time, and this is not the feature.

**Comment by ammario** [comment]
Closing in favor of https://github.com/coder/coder/issues/3480

**Comment by bpmct** [comment]
Reopening since we haven't settled on a way to do this yet.

**Comment by bpmct** [comment]
In v1, we relied on metrics-server to get accurate utilization from pods. Since [top is inaccurate](https://fabiokung.com/2014/03/13/memory-inside-linux-containers/) inside containers, we might need to think about solutions.

**Comment by bpmct** [comment]
Closing in favor of #3480. It seems like one form of agent metadata will be used for this.
