### ISSUE TITLE
Activity Based Auto-stop

### ISSUE THREAD

**Issue by ammario** [coder/coder#2995]
Edit from @bpmct: [see the RFC here](https://www.notion.so/coderhq/RFC-Workspace-activity-13d47178a6a148e182781f73b8cf229f)

Allow workspaces to remain "on" if the user is active in the workspace (e.g. writing code, typing in the terminal, etc).

<details>
<summary>Archive</summary>
<br>

## Proposal

I think we should resolve #2987 first as it affects how this feature is exposed to the template admin. Without templates as code, we can expose the feature in the same way as we do `min_autostart_interval` and `max_ttl` today.

## Activity Rules
We should discuss which values we want to make knobs immediately. The more we lean into templates as code, the more configurable this can get.

For each of these events, bump the auto-stop by 1h:
* `coder_app` HTTP request
* DevURL HTTP request
* SSH access

Possible knobs:
* Bump amount
* Which `coder_app`s trigger bump
* Which access types trigger bumps 

To help the user debug why their workspace isn't shutting down, we could add a tooltip to the UI that explains the last bump source. The options could be "Manual", \<app name\>, \<dev url name\>, or "SSH".

<img width="1083" alt="Screen Shot 2022-07-14 at 12 56 51 PM" src="https://user-images.githubusercontent.com/7416144/179050669-2977496e-ae2b-49c8-8570-ea1d7d333dcb.png">

Pretty much all of our early scheduling feedback suggests that activity-based auto-stop should be enabled by default. So I propose that it is default with all of the knobs selected. 

https://github.com/coder/coder/issues/3191 is user feedback that shows the value of combining schedule-based auto stop with activity-based auto-stop. If the user just wants activity-based, they can set the schedule to stop one hour after start.</details>

----

### Affected / Related Issues

#2942 
#2752

**Comment by mark-theshark** [comment]
@ammario an enterprise prospect today with JupyterLab as a use case reported that a scheduled stop will not work for them, but they want an activity-based stop.

The problem they want to solve is their existing cloud JupyterLab solution just keeps workspaces running if a Python kernel is active, and runs up a big cloud bill.

JupyterLab introduces a couple of areas worth considering.
1. It is a web-based app, so no config-ssh settings help them
2. JupyterLab is a `coder_app` so not how we detect if one of these are open (maybe like how we did in v1)

**Comment by ammario** [comment]
@mark-theshark I'm a bit confused. The proposal suggests monitoring coder_apps so those requirements should be satisfied?

**Comment by bpmct** [comment]
Surfacing @Mainstay-Noah-Huppert' comment in #3191 

> That could be good. I do like the schedule so that my workspace doesn't shut down during lunch or during a meeting heavy day. Mainly because there are some development tasks (👀 webpack) that take a few minutes to start up with a big app. So having the workspace up and the tasks already running saves time. Additionally having the scheduled start at 9:00 AM is nice because I know that by the time I start dev work after standup all those tasks will be running and good to go.
> 
> For my particular use case I think being able to configure only having keep alive functionality and not inacitvity shutdown would be nice.

**Comment by bpmct** [comment]
Gonna unassign this for now. The RFC has been finished and a proposed behavior is in #3529. We still need to make a few decisions about whether we want to support a feature like this prior to #3597 which can give us better data about user activity.
