### ISSUE TITLE
Remove stack trace from Error Boundary

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3007]
**Needs more discussion**: It's not clear if we should actually get rid of the stack trace or just fix [the V1 crash.](https://github.com/coder/coder/issues/3007) 

When hit, our error boundary in V2 displays the stack trace of the error that crashed the app:

![Screen Shot 2022-07-15 at 1 16 08 PM](https://user-images.githubusercontent.com/19142439/179274900-32577ec4-ee6a-4c4a-a8e0-f48982580698.png)

This stack trace is causing some of our clients concern so we should remove it.

AC
 - new error boundary state design implemented (TBD) without stack trace
 - tests updated
 -  Error boundary link should now open Github ticket
 - Github ticket should still be prepopulated with stack trace, if possible

Definition of Done
 - we have a functioning error boundary that does not show a stack trace

**Comment by Kira-Pilot** [comment]
Chatted with @tjcran and we think this is a lower priority issue. Opting to leave the stack trace in a message or Github link, but remove it from the view.

**Comment by Kira-Pilot** [comment]
@tjcran is it okay if we close this one? We discussed this a while back and it seems like the error boundary stack trace view is not the issue - the issue was the crash itself.

**Comment by tjcran** [comment]
@Kira-Pilot yeah i think that's right!
