### ISSUE TITLE
Improve contrast in UI to show the web terminal is disconnected

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#3013]
## Problem
If I am using the web `Terminal,` it is not apparent to me that my session is disconnected.

## Definition of Done
A user should be able to clearly and easily see if a web terminal session is disconnected. 

One suggested path:
There should be a background color box with a color that is visibly appealing but contrasting to the white foreground and black ground of `Terminal.` There are some visual patterns through Coder OSS that could be used such as:

RED
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2022166/179496268-31920ef8-d7e2-4724-8755-2a276d7e56bd.png">

BROWN/TAN
<img width="162" alt="image" src="https://user-images.githubusercontent.com/2022166/179496399-bc754407-ff2d-4830-b554-e9d02d15cf75.png">

## Current Behavior

White foreground over white foreground text of the `Terminal`, making it difficult to determine if `Terminal` is disconnected.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/2022166/179496138-6b5b6feb-0a1e-42a8-bfdc-fb2c5893d342.png">

**Comment by BrunoQuaresma** [comment]
@mark-theshark where is this "Disconnected" message showing? Is it on the web terminal page?

**Comment by ketang** [comment]
Launch a web terminal, stop your workspace, and wait a little while.  Then type in the terminal window, and you'll see it.

I think putting a background on the message, making it bigger, and making the text a higher visibility color could suffice:
![image](https://user-images.githubusercontent.com/33678/179559306-9212714f-8ef7-42fe-af7e-4d248541b23e.png)
