### ISSUE TITLE
Show the closest command when you input an invalid command

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#3019]
Let's say the user types:
```
coder templates start
```
The output could be:
```
"start" is not a valid option, you probably want to run "coder templates init"
```

**Comment by phorcys420** [comment]
I was thinking there could be something for ``coder config-ssh`` too, I was struggling to find it and I typed in stuff like ``setup-ssh`` and ``auto-ssh``.
I was thinking maybe command aliases too for stuff like this ?

**Comment by ketang** [comment]
The `SuggestFor` field for each command would be the way to do this:

https://pkg.go.dev/github.com/spf13/cobra#Command

e.g. for `templates start` you'd add that as a parameter here:

https://github.com/coder/coder/blob/main/cli/templates.go#L15

**Comment by kylecarbs** [comment]
Since we don't have clear examples of what to do here, I'm going to close this.
