### ISSUE TITLE
Git Integration for Azure Repos via OAuth

### ISSUE THREAD

**Issue by srudolph-credera** [coder/coder#3021]
This is an enhancement request for supporting [Git integration](https://coder.com/docs/coder/latest/admin/git) for [Azure Repos](https://azure.microsoft.com/en-us/services/devops/repos/) via OAuth. The ultimate intent is being able to support an [embeddable "Open in Coder" button](https://coder.com/docs/coder/latest/images/embed-button) in Azure Repos like Coder v1 currently supports for other git repository services.

This is a great feature that provides a natural source of documentation and improves developer experience and I'd love to see it more widely available!

**Comment by misskniss** [comment]
Currently blocked by the need for an open in coder button. We need to decide if this is a feature that we want.

**Comment by kylecarbs** [comment]
Fixed by #4670
