### ISSUE TITLE
Make workspace "Update" button stand alone

### ISSUE THREAD

**Issue by ketang** [coder/coder#3024]
A recent change (#2748) combined the different workspace buttons to free up some space.  This is a good change, but there was a little collateral damage.  I think the "Update" button shouldn't be grouped; if the template is out of date, it should always be top level instead of in the collapsed array.  OR "Update" could be the first button with "Start" being in the drop-down.

Definition of Done:
Update call to action should be more prominent. 

![image](https://user-images.githubusercontent.com/33678/179557170-4d50587b-8434-4881-96a9-f234bf1cabf2.png)

AC as per below discussion:
 - keep `Update` in button dropdown
 - make it the primary CTA when an update is available
 - add an 'Outdated' tooltip (similar to the one in the workspaces table) when an update is available

**Comment by BrunoQuaresma** [comment]
What do you think about removing the "Update" button and showing the "Outdated" tooltip as we do for the workspace table row? 

<img width="1792" alt="Screen Shot 2022-07-18 at 16 29 27" src="https://user-images.githubusercontent.com/3165839/179602299-61cc7734-ce11-4799-a7b5-c48b34b29367.png">
<img width="457" alt="Screen Shot 2022-07-18 at 16 29 18" src="https://user-images.githubusercontent.com/3165839/179602309-b53ad10d-12d1-46b7-8399-25cf23e467d7.png">

**Comment by ketang** [comment]
Perhaps we do both the tooltip/dialog and the update button?  I think we want to strongly encourage users to update their workspaces if they're behind, and putting an extra step in front of "Start" helps with that.  Also I assume the "Update" button change is trivial, while the other is a bit more effort.  Maybe just do the button now and save the tooltip etc. for a couple of sprints from now?

**Comment by BrunoQuaresma** [comment]
@Kira-Pilot I think you would be the best person to work on this. What do you think?

**Comment by Kira-Pilot** [comment]
@BrunoQuaresma sounds good to me!

**Comment by ketang** [comment]
In grooming this morning, @presleyp suggested we remove the Update button from the button stack entirely.  Its display would still be conditional on the template freshness status.  That seems like it solves the problem also.

**Comment by ketang** [comment]
🤦🏾‍♂️

**Comment by Kira-Pilot** [comment]
@ketang @BrunoQuaresma are we okay with leaving `Update` in the dropdown, and making it the primary CTA when an update is available? I know I argued against this the other day in grooming but I've since reconsidered 😅 
LMK if you object; otherwise I'll move forward with that proposal.

**Comment by ketang** [comment]
Both options achieve my goal of making "Update" highly visible, so I'm satisfied either way.
