### ISSUE TITLE
Make workspace stopped state more obvious

### ISSUE THREAD

**Issue by ketang** [coder/coder#3025]
I have to hunt for clues too much to tell that my workspace is stopped.  The explicit status looks just like all the other text, so I'm otherwise left to infer based on the presence of the "Start" button or seeing that the last job was a "stop" job.

I think the workspace status is one of the most important pieces of information on this page, and I think its presentation should reflect that.  I think it should be more colorful and appear at the top left near the workspace name.

![image](https://user-images.githubusercontent.com/33678/179558448-28b7d543-3eaa-43f3-84be-d7d39159ad28.png)

**Comment by BrunoQuaresma** [comment]
I totally agree with you. I have some ideas in mind and I will post them here when they are done.

**Comment by BrunoQuaresma** [comment]
@ketang what do you think about these?

![Stopped](https://user-images.githubusercontent.com/3165839/180009725-8053d6f7-719b-49f5-abd4-79954e90c4b3.png)
![Running](https://user-images.githubusercontent.com/3165839/180009730-713778b8-2e85-43e7-834f-bfb32127d811.png)

**Comment by ketang** [comment]
I think this is a significant improvement.  A few notes:
* do we need the "agent" column for a stopped workspace?
* the `kubernetes_deployment` in the mock shows `Connected`; is that just a mock artifact?
* I feel bad saying this to someone named "Bruno," but I think brown is rarely an attractive color on computer screens
* What do you think of a border, background, and/or text highlight on the workspace name to indicate status?
* the pills holding status, organization, and user name are all similar in appearance, which makes it harder to tell which is which.
* this also implies they're of equal importance in the UI, but this page is usually going to be viewed by the owner, who presumably knows their name and organization

**Comment by BrunoQuaresma** [comment]
> do we need the "agent" column for a stopped workspace?
No, I think we can remove it.

> the kubernetes_deployment in the mock shows Connected; is that just a mock artifact?
Yes 😆 

> I feel bad saying this to someone named "Bruno," but I think brown is rarely an attractive color on computer screens
lol np, when you say "brown" are you talking about the stoped status color? I don't link it too much as well but since we are using a dark theme, the best is to use a darker yellow as the background for the chip.

> What do you think of a border, background, and/or text highlight on the workspace name to indicate status?
I can try some options and see what looks better

> the pills holding status, organization, and user name are all similar in appearance, which makes it harder to tell which is which.
I agree, I will see if I can solve this.

> this also implies they're of equal importance in the UI, but this page is usually going to be viewed by the owner, who presumably knows their name and organization
I agree 2x

**Comment by ketang** [comment]
> when you say "brown" are you talking about the stopped status color?

Yes, exactly.

**Comment by ketang** [comment]
> I tried the borders and font color and didn't work well honestly, but if you have strong feelings about that

No worries.  I was just brainstorming.

I don't have a clear opinion about the two alternatives you presented.  I think they're both good.  One thing that I do observe is that the second mockup, with the status above the title, is that it results in a third, otherwise empty row, which may not be ideal.  However, that's a smaller detail, and I think both are successful at achieving the initial improvement I was asking for.

**Comment by presleyp** [comment]
@Kira-Pilot makes a good point in Slack that we don't know how long the workspace name will be, so putting the pill above is better. I also wonder if we could put the pill above and right-justified, so it's over the button that changes workspace status...but maybe that makes it less obvious to left-to-right readers like us.

**Comment by BrunoQuaresma** [comment]
@presleyp I played around with the idea and I don't think it is bad but it looks a bit "unexpected". Thoughts?
![Running on Top](https://user-images.githubusercontent.com/3165839/180083238-7449bd83-0caf-4f2a-a636-3aeda946930c.png)

**Comment by Kira-Pilot** [comment]
I like the top best but it doesn't look bad right-justified either!

**Comment by ketang** [comment]
Eye tracking heat maps indicate that top left is highest salience, so I think we should prefer that for this high importance datum.

**Comment by presleyp** [comment]
Yeah I think top left is fine or if you go with top right I feel like it should be as large as the Stop button.
