### ISSUE TITLE
ci: improve speeds

### ISSUE THREAD

**Issue by ammario** [coder/coder#3031]
## Problem
Basic changes like https://github.com/coder/coder/pull/3030 wait 20m before they're merged. The culprit is hefty postgres and windows integration tests.

These tests are probably difficult to speed up. P

The most notable caveat to path based filtering is the action may use scripts and files outside of the main language. For example, a go test action may use a `test.sh` script and a Makefile. If we decide to use path filtering, we should do so sparingly, as there's an inescapable trade off between speed and correctness. 

## Definition of done
improve CI speeds from (20m?) to (?). One suggested path: we could use [path based filtering](https://github.com/dorny/paths-filter) or different triggers (cron or master only) to speed up the average Pull Request?

**Comment by spikecurtis** [comment]
One way to improve speed: #2476

**Comment by misskniss** [comment]
@ammario - you merged some PRs over the weekend for CI - are those meant to fix this?
How fast is fast?

**Comment by ammario** [comment]
@misskniss yes they were. I'll go ahead and close this out. I expect my changes to cut the average wait time in half.
