### ISSUE TITLE
Make `coder state` to something general

### ISSUE THREAD

**Issue by ketang** [coder/coder#3032]
Maybe it's just the help text that's Terraform-specific, but I want to also make sure the implementation and concepts are general as well.
```
$ coder help state
Manually manage Terraform state to fix broken workspaces

Usage:
  coder state [command]

Commands:
  pull
  push
```

**Comment by ketang** [comment]
I like the idea of also putting this under an `admin` command.

**Comment by ammario** [comment]
Related to an admin command: https://github.com/coder/coder/issues/1631
