### ISSUE TITLE
Add groups to RBAC

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#3039]
I don't really know which form it could take but I was thinking of a feature that would let you limit users, e.g:
* Only create ``n`` workspaces
* Not able to use ``x`` template / Only able to use templates ``y`` and ``z``

I think this could exist in the form of groups but it could be something else too.

"Manager" group:
* Can use ``science`` template
* Can update ``science`` template
* Can create unlimited workspaces
* Can create templates
* Can create users

"Scientific" group:
* Can use ``science`` template
* Can create 3 workspaces
* Can create templates
* Can create users

"Newcomer" group:
* Can use ``science`` and ``beginner`` templates
* Can create 1 workspace

**Comment by matifali** [comment]
The limit should be on the number of workspaces that can be started simultaneously and not on just the number that can be created.

**Comment by ammario** [comment]
@phorcys420 could you leave feedback on https://github.com/coder/coder/issues/2988? Thanks.

**Comment by tjcran** [comment]
> @phorcys420 could you leave feedback on #2988? Thanks.

@ammario i think this is more than just Quotas, though. This also fits into some of the roles/orgs categories as well. e.g. being able to set a quota for users in a specific org.

**Comment by phorcys420** [comment]
> The limit should be on the number of workspaces that can be started simultaneously and not on just the number that can be created.

hmm, not really. I was thinking the disk space that creating a workspace could involve.

**Comment by ammario** [comment]
There's a need for two limits, really. Another approach, which I prefer, is assigning a cost to the on state and off state. Then, you can attach a budget to each user which affords them some flexibility. For example:

* template budget is set to 10 per user
* 2 points are for the off state
* 3 points are for the on state

You can have:

* 3 on workspaces, 0 off workspaces (1 point)
* 0 on workspaces, 5 off workspaces (0 points left)
* 2 on workspaces, 2 off workspaces (0 points left)

You could also keep it simple and just make it 1 points for both on and off state.

**Comment by ammario** [comment]
Yeah, groups are inevitable here. There are three ways to approach it:
1. An overall budget for a group
2. A budget for each member in a group
3. 1 and 2 simultaneously

**Comment by ketang** [comment]
I think there's no point in not going all the way to both, especially when we already know where we need to get.  Also groups will have be able to contain other groups.

**Comment by ammario** [comment]
This will be handled in #3102
