### ISSUE TITLE
'Failed to create deployment' error on `coder push`

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3040]
As a V2 user, sometimes my workspace stops during the week, but the deployment isn't blown away. I usually fix this by pulling the old state and then pushing it. Right now when I `coder push` I'm getting the same `Failed to create deployment` error that I see in the UI workspace logs. I am on the latest binary

To reproduce:
Version: 
 Coder v0.7.12+6f34cbf Wed Jul 13 01:09:59 UTC 2022
https://github.com/coder/coder/commit/6f34cbff1ee2a3d645566ed307722ac635a9c935

1. Have a workspace that is shutdown but has an old deployment. The logs in the UI will say something like "Error: Failed to create deployment: deployments.apps "coder-kira-pilot-my-workspace" already exists"
2. Log into v2 in my terminal (not sure if this matters)
3. Pull state and pipe to a file: `coderv2 state pull kira-pilot/my-workspace > PullFile.txt`
4. Push that state: `coderv2 state push kira-pilot/my-workspace PullFile.txt`

![Screen Shot 2022-07-19 at 10 23 36 AM](https://user-images.githubusercontent.com/19142439/179776228-a063ab8f-756a-4e48-9681-306a72922a88.png)

Definition of Done:
 - I don't see this error when I try to push state
 - I can successfully run my workspace again

**Comment by ketang** [comment]
Hmm... do you know why your deployment is stopping?  I'll admit during off days I go around shutting down people's workspaces, but those should be clean shutdowns.

**Comment by Kira-Pilot** [comment]
@ketang yeah, this is a known issue where the workspace is shut down but the deployment persists. There is a ticket to fix it!

**Comment by kylecarbs** [comment]
I'm going to close this for now in favor of #2256.
