### ISSUE TITLE
Templates help: missing description for coder templates list -h and coder template versions -h

### ISSUE THREAD

**Issue by OlgaKhmelevskaya** [coder/coder#3041]
Coder v0.7.12+6f34cbf
Cmd

**Steps to reproduce:**

1. Run coder templates list -h
2. Run coder template versions -h

**Actual result:**
- corresponding help data do not contain brief command description
![2022-07-19_17-47-54](https://user-images.githubusercontent.com/107863254/179780199-d0bc0e84-5efd-4a31-b4ee-7eb57696e692.png)

**Expected result:**
- corresponding help data contain brief command description like the rest of coder templates commands to be consistent
E.g.
![2022-07-19_17-52-04](https://user-images.githubusercontent.com/107863254/179780880-9de9361a-a4ff-40a9-9b10-aecea19d19ad.png)

**Comment by AbhineetJain** [comment]
Good find! I believe it should be okay to club this issue with https://github.com/coder/coder/issues/1425, which actually implements the `templates version` command.
