### ISSUE TITLE
Delete template: several error messages in console contain redundant api output

### ISSUE THREAD

**Issue by OlgaKhmelevskaya** [coder/coder#3044]
Coder v0.7.12+6f34cbf
Cmd

**Scenario 1**

1. Do template init of any template
2. Create a template 
3. Create a workspace based on template
4. Delete template:
coder templates delete [template name]

**Actual result:**
- redundant api output is displayed in the error message
"delete template "aws-windows": DELETE https://fcca2689e23903a563ca16e90d03c1da.pit-1.try.coder.app/api/v2/templates/04950462-6de9-4c63-a854-6c5da260b161: unexpected status code 412: All workspaces must be deleted before a template can be removed."
![2022-07-19_18-49-05](https://user-images.githubusercontent.com/107863254/179793766-25d281d4-87ec-46c2-b08e-0936a0f5a6cb.png)

**Expected result:**
- the error message "All workspaces must be deleted before a template can be removed. Run 'coder templates delete --help' for usage." is displayed

**Scenario 2**

1. As an Admin create several templates via cli
2. Login to CLI as a user with a role Member
3. Run in console/terminal
coder templates list
4. Run 
coder templates delete [any template name]

**Actual result:**
- redundant api output is displayed in the error message
"delete template "aws-windows001": DELETE https://fcca2689e23903a563ca16e90d03c1da.pit-1.try.coder.app/api/v2/templates/bb5e4cf4-8032-498e-8963-ed94d00d188a: unexpected status code 404: Resource not found or you do not have access to this resource"
![2022-07-19_18-53-33](https://user-images.githubusercontent.com/107863254/179794806-9924bb3e-f533-426f-8049-918d734e7da9.png)

**Expected result:**
- the error message "Resource not found or you do not have access to this resource. Run 'coder templates delete --help' for usage." is displayed

**Comment by bpmct** [comment]
hmm... the additional output may be helpful, but would probably be optional via a verbose flag.

**Comment by bpmct** [comment]
Hmm @OlgaKhmelevskaya - are you sure you don't have the environment variable `CODER_VERBOSE` set to true? I am only observing this behavior with the flag set.

**Comment by OlgaKhmelevskaya** [comment]
Hi @bpmct, I found this issue on my local application version. I have to use it because of template creation limitation in DEV environment.
My local browser version is set up by coder server --tunnel command by default. I haven't made any configuration changes manually. Hope this information will be helpful.
