### ISSUE TITLE
Empty GIT env vars produces cryptic error

### ISSUE THREAD

**Issue by sreya** [coder/coder#3049]
I logged in today and tried to commit a change and was met with this error message: 

```
fatal: empty ident name (for <>) not allowed
```

I have a populated `.gitconfig` so this doesn't make sense. Then I saw this:

```coder@aman git (master) ✗ env | grep GIT
GIT_SSH_COMMAND=/tmp/coder.SMmZfi/coder gitssh --
GIT_AUTHOR_EMAIL=
GIT_COMMITTER_EMAIL=
GIT_AUTHOR_NAME=
GIT_COMMITTER_NAME=
```

Once I ran `unset` on all those things started working again...

**Comment by kylecarbs** [comment]
Ahh, this is because of the removal of Git env vars. The `OwnerName` and `OwnerEmail` were removed from the metadata struct, but since your workspace agent didn't update, the env vars are just being set to empty strings.

This is more validation for #2970. Stopping and starting should fix this.
