### ISSUE TITLE
inject file from `coder_agent` resource

### ISSUE THREAD

**Issue by ammario** [coder/coder#3055]
As a template administrator, I want to give my users a cloud service account for particular workspaces. The cleanest way I can do this is by using a cloud service account key resource like [this](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_service_account_key#private_key). 

I could inject via environment variables, but very long environment variables are an anti-pattern. I could also inject via the `startup_script`, but that is bug prone since I would need to consider escaping.

My ideal UX is something like this:

```hcl
resource "google_service_account_key" "mykey" {
  service_account_id = google_service_account.myaccount.name

  keepers = {
    rotation_time = time_rotating.mykey_rotation.rotation_rfc3339
  }
}

resource "coder_agent" "dev" {
  # ...
  files =[
    {
       name = "~/.gcp_creds.json
       contents = google_service_account_key.mykey.private_key
       mode = "0600"
    },
  ]
  env = {
     GOOGLE_APPLICATION_CREDENTIALS = "~/.gcp_creds.json"
  }
}
```

Related #2989 #3047

**Comment by kylecarbs** [comment]
This introduces a *lot* of edge-cases that aren't simple to solve.

- How big of a file do we support?
- What if we don't have permissions to write the file?
- Do we overwrite a file if it exists?
- What if the contents are different?

For these reasons, I think the template author should make these decisions. Terraform has an `escape` function for this reason.

**Comment by bpmct** [comment]
Ah, kind of like running this in the `startup_script`? (untested)

```hcl
resource "coder_agent" "dev" {
  # ...
  startup_script = <<EOF
  #!/bin/sh
  # Write gcp_creds.json from template into the workspace.
  echo '${filebase64("gcp_creds.json")' > /tmp/base64_gcp_creds.json
  cat /tmp/base64_gcp_creds.json | base64 --decode > ~/.gcp_creds.json
  EOF
}

**Comment by matifali** [comment]
This came up again as we do a lot of file writing in Coder modules in github.com/coder/registry.

It would be nice to have a `coder_file` resource that can put arbitrary files inside coder workspaces with control for permissions.
