### ISSUE TITLE
can't use secrets in template parameters

### ISSUE THREAD

**Issue by ammario** [coder/coder#3056]
As a template administrator, I want to let my user input a secret during workspace creation. Since our `sensitive = true` indicates an admin-only parameter, my user-inputted secrets would show as cleartext within the create UI (and eventually other places).

**Comment by ammario** [comment]
I'm not sure that this feature is necessary since the user could enter the secret into the workspace after it's created.

**Comment by bpmct** [comment]
re. implimentation, @kylecarbs and I chatted about this a little, but we couldn't settle on a good schema to indicate admin params and sensitive parameters exclusively.

Admin params could be potentially be done via a prefix in resource name, `description`, or potentially a validation condition in the `variable`, or even a property for the provider. None felt intuitive though

**Comment by ketang** [comment]
I may be misunderstanding this, but the way I had understood this was that the user would be prompted on sensitive parameters that were not provided by someone else already.  We wouldn't need to specify in the schema *who* should provide the actual values.  Either you have them or you don't.  This gets a little nuanced with whether someone can override an admin-specified parameter though.

**Comment by ammario** [comment]
> I may be misunderstanding this, but the way I had understood this was that the user would be prompted on sensitive parameters that were not provided by someone else already. We wouldn't need to specify in the schema who should provide the actual values. Either you have them or you don't. This gets a little nuanced with whether someone can override an admin-specified parameter though.

This is more of a cosmetic change. We would not use `input.type = "password"` in the frontend and be more careful about releasing these parameters in API read calls.

If the admin wanted to allow overrides they would accept a user parameter and an admin parameter and then use a ternary to prioritize within the terraform code—exactly how they would today.

**Comment by ketang** [comment]
I guess the part that I'm not understanding then is the distinction between an admin parameter and a user parameter.

**Comment by ketang** [comment]
Mmmm yeah I see.  Okay, I think that design choice may be showing its limits here.  I think we need to re-examine it.

**Comment by ammario** [comment]
Closing this as I think the user entering their secret, after the workspace is created, into a stateful volume is sufficient.
