### ISSUE TITLE
auto-stop has confusing behavior with auto-start

### ISSUE THREAD

**Issue by ammario** [coder/coder#3064]
My workspace has an auto-start for 8:30am and a 12h auto-stop.

Last night, my workspace stopped automatically at 8:30pm so I started it up at 9:40pm manually. In the morning, my workspace stopped at 9:40am. So, when I began coding at 10am, my workspace was surprisingly offline.

Even though I manually started my workspace last night, I expect that my workspace still starts at my next auto-start.

cc @johnstcn

**Comment by johnstcn** [comment]
@ammario duplicate of https://github.com/coder/coder/issues/2028 perhaps?

**Comment by ammario** [comment]
@johnstcn 📠
