### ISSUE TITLE
Add commit message guidelines to contributor docs

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3066]
Problem: we follow conventions for writing commit messages, but the documentation of this is private so community contributors can't see it.

Definition of Done: commit message conventions are documented on GitHub.

I suggest deleting or archiving the private documentation when this is done to avoid confusion, but linking between GitHub and Notion may be possible.

**Comment by ketang** [comment]
Related to #2538

**Comment by bpmct** [comment]
@presleyp are we still following these guidelines? if so can you share them here? 

I can make a PR

**Comment by bpmct** [comment]
Closing, we don't have super strict commit guidelines right now and can rename community PRs
