### ISSUE TITLE
Add icons to the workspace resources

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#3075]
Initial proposal:
<img width="1347" alt="Screen Shot 2022-07-20 at 13 57 51" src="https://user-images.githubusercontent.com/3165839/180040046-a63b8797-8a6b-43e8-829b-38e9c34784b4.png">

Discord discussion:
https://discord.com/channels/747933592273027093/991429648200245358/999314552560824441

Notes:
- Drop the color changes
- Try to make it more simple
- Increase the contrast and make it more visible
- The plan is to still keep using the text

**Comment by BrunoQuaresma** [comment]
Extra notes. It can be hard to add custom icons for each resource type because we would have to find them, and also, make them look "aligned" in terms of styles which can be very complex so I think we can start by using icons on Material UI and update them if we need it. Also, as a start point, we are going to map only the 10 most used resources which are:

```
docker_volume,353
docker_container,302
docker_image,115
kubernetes_persistent_volume_claim,84
kubernetes_pod,71
google_compute_disk,41
google_compute_instance,37
aws_instance,22
kubernetes_deployment,18
null_resource,10
```

For each of these I'm going to use the icons:
- docker_volume: Folder
- docker_container: Memory
- docker_image: Image
- kubernetes_persistent_volume_claim: Folder
- kubernetes_pod: Memory
- google_compute_disk: Folder
- google_compute_instance: Memory
- aws_instance: Memory
- kubernetes_deployment: Memory
- null_resource: Question Mark

You can browse the icons here https://fonts.google.com/icons. Feel free to suggest any changes to it.

**Comment by bpmct** [comment]
In the future #2989 can be used to assign a custom icon (or perhaps emoji #2262) can be assigned to resources.

**Comment by kylecarbs** [comment]
@bpmct the emoji as icons sounds fun 👀
