### ISSUE TITLE
Make a simple web server app available

### ISSUE THREAD

**Issue by ketang** [coder/coder#3076]
Give users an easy way to serve a directory of static files from their workspaces.  Ideally the only configuration needed would be:
* port
* document directory (could be a remote URL that we fetch from at workspace start)

**Comment by bpmct** [comment]
I see the benefits of this, but I don't think there's enough merit in having this as a default app alongside the terminal. I suspect it would be rarely used and take up valuable screen real estate.

For specific use cases, templates can serve a simple HTTP server with something like `cd $HOME/mydir && python3 -m http.server 3000` or even have it running by default as a workspace app.

**Comment by ketang** [comment]
I'll bet $5 that this is the kind of thing that customers won't ask for but will value to have present.  We'll probably want some compact presentation of "utility" type apps like this.
