### ISSUE TITLE
feat: add identity into a workspace to use mount a shared volume that limits access based on that identity

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3080]
A prospect requires a shared volume mount to a workspace.  In this case, a Kubernetes pod.

They would like to mount a shared volume to a pod but need the user's identity to be inserted into the workspace, so the mounted volume can limit access in that volume based on that identity.

**Comment by kylecarbs** [comment]
We expose a user's email address via the Terraform Provider, which would let them identify a user. We can pass more info too, we'd just need to know what that is.
