### ISSUE TITLE
Add JetBrains Gateway to IDE Docs

### ISSUE THREAD

**Issue by tjcran** [coder/coder#3100]
## Problem
We lack docs for Gateway right now, which could give the perception that it doesn’t work with Coder. Ideally, someone that uses Gateway daily with Coder takes this (or someone that wants to, but there are too many bugs).

## Definition of Done

- Verify that Gateway works on the latest EAP when connecting to a Linux Coder agent. Working versions should be documented with a “last updated at” alongside the version.
- Document the limitation of Gateway with non-Linux Coder agents (this is a limitation on their part, see:https://youtrack.jetbrains.com/issue/CWM-3653/Remote-development-host-should-be-available-on-macOS-and-Windows)

**Comment by spikecurtis** [comment]
Unfortunately still unable to connect with the latest EAP (2022.2 RC /  GW-222.3345.94) on macOS.
