### ISSUE TITLE
Bug in v0.8.0-devel 0aa8c2ef: coder.com's docs are not current with the Coder OSS repo

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#3111]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/2022166/180431334-462e878d-bdb3-45f6-b0c0-3937f2f100da.png">

As a potential new user and evaluator of Coder OSS, I am reviewing both the cloned repo and also coder.com

Coder.com claims to have Coder OSS docs, but I have noticed for a couple of weeks that they say release 7.3 and have not been updated.

This is a bad end-user and first impression experience and forces me to manually wade through the repo's docs folder which is not optimized for easy viewing of markdown files.

I assume there is a break in coder.com's CI to push the docs so please repair and make that push instantaneous once a new release is issued.

**Comment by ammario** [comment]
The docs are only ~24 hours behind master, so this is really a bug with the version number display.

**Comment by ammario** [comment]
Another fix just landed into coder.com that will bring the docs site update lag from hours to minutes.
