### ISSUE TITLE
resource icons not on templates page

### ISSUE THREAD

**Issue by ammario** [coder/coder#3122]
<img width="808" alt="Screen Shot 2022-07-22 at 10 01 35 AM" src="https://user-images.githubusercontent.com/7416144/180467586-28267650-fe7e-498c-8a74-398d2c22b77e.png">

<img width="807" alt="Screen Shot 2022-07-22 at 10 01 45 AM" src="https://user-images.githubusercontent.com/7416144/180467613-eaec90b7-8643-41be-8ea2-3e4dc1ba7672.png">

cc @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
Good catch, fixing it.
