### ISSUE TITLE
Add HTTPS listen address flag

### ISSUE THREAD

**Issue by deansheather** [coder/coder#3123]
Right now we have the `--address` flag which sets the listen address for Coder. I propose we add a new flag `--https-address (CODER_HTTPS_ADDRESS)` and change the behavior of coderd to the following:

If neither flag is set or ONLY `--address` is set, and TLS certs ARE NOT specified:
- Listen on HTTP at `--address` (or default)

If neither flag is set or ONLY `--address` is set, and TLS certs are specified:
- Listen on HTTPS only at `--address` (or default)

If `--https-address` is set and `--address` is NOT:
- Require that TLS certs are set or fatally exit
- Listen on HTTPS only at `--https-address`

If BOTH `--https-address` and `--address` are set:
- Require that TLS certs are set or fatally exit
- Listen on HTTPS at `--https-address`
- Listen on HTTP at `--address`

I believe this be backwards compatible by keeping the same behavior around `--address` on it's own, while only introducing the new behavior when `--https-address` is specified.

**Comment by kylecarbs** [comment]
What's the motivation for having both? It'd be nicer to have one, but if customers need both we'll obvs do it.

**Comment by deansheather** [comment]
Well, if we don't support having two listen addresses then coder won't be very useful unless it's behind a reverse proxy that can serve both HTTP and HTTPS or redirect from HTTP to HTTPS. And at that point, there's no point using coder's in built HTTPS support because you could just do it from your reverse proxy...

**Comment by deansheather** [comment]
After we add this flag I'd like to add a flag to redirect from HTTP to HTTPS, which means coder could be used entirely without a reverse proxy and behave sensibly.

**Comment by ketang** [comment]
Is there a situation where a customer would want to serve Coder on both unencrypted HTTP and encrypted HTTPS?  I think if the latter is present, they should *always* redirect HTTP to HTTPS.

**Comment by deansheather** [comment]
That makes sense @ketang but at the moment since coder can only listen on one or the other users are forced to do this with a reverse proxy, which makes the TLS options in coder useless since they'll be doing TLS termination at the reverse proxy. I don't mind changing this issue so if we listen on both we always do a HTTPS redirect from HTTP.

**Comment by ketang** [comment]
Why can Coder only listen on one?

**Comment by deansheather** [comment]
Coder only listens on one right now since we only have one listen address flag. If you don't specify TLS certs then it's a HTTP server, otherwise it's a HTTPS server.

**Comment by jsjoeio** [comment]
Sounds like we're experiencing this with dev.coder.com - it doesn't automatically add HTTPS or redirect and therefore I see a broken page. 
![18708](https://user-images.githubusercontent.com/3806031/188970991-1289e101-d770-49f6-8475-88fcbc39f857.jpeg)

**Comment by kylecarbs** [comment]
I removed the `needs decision` label because I think this would be beneficial. It just makes setup a bit simpler.

**Comment by jsjoeio** [comment]
This is someone I would like to help with! From a user perspective, I would prefer only having to set one option and it should automatically redirect HTTP -> HTTPS for us.

I don't know what implementation details look like but I think it could even be worth a breaking change for long-term UX improvements.

I'd like to work on this but I think we need to align on direction and implementation. Would love to hear thoughts.
