### ISSUE TITLE
Spike: determine which translation library is best

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3128]
**User statement**
As a future user, I would (maybe) like to enjoy a translated application.

As a current coder, I want to be able to store translation strings in a robust manner.

**Background**
Currently, all of our translation strings are stored in custom objects colocated with a component. [As discussed in FE variety](https://www.notion.so/coderhq/2022-07-22-28f0f1432c394f4b962853e7063993ef), we are pivoting to use a library to handle translations. There are numerous reasons for this (see the Notion doc) but some of big ones are:
1. Right now, sometimes we break up strings in ways that aren’t actually conducive to future translation; a library would help with that 
2. Currently, if a developer refactors up a Language object, it is unclear which strings are not in use. Switching to a library will help us avoid stale strings
3. Sometimes we store business state in our Language objects. This is an anti-pattern that a library would help us avoid.

**AC**
 - timebox to no greater than half a day
 - create a table (either in this ticket or in a linked Notion) that identifies 3 top translation libraries
 - compare and contrast the 3 top translation libraries, determining a best solution
 - document best solution and then post document in #dev-ux so others can weigh in
 - create another ticket outlining the actual work to be done

**Definition of Done**
 - a translation library has been agreed upon by the FE team
 - a ticket has been created for future work

**RFC with comparison table**
https://www.notion.so/coderhq/Mini-RFC-for-FE-translation-library-spike-5fe218fe35d24af1b6aebf935f2f3680

**Comment by kylecarbs** [comment]
Is this to support alternative languages?

**Comment by Kira-Pilot** [comment]
@kylecarbs, a translation library can be used to support alternative languages, but the primary reason we would like organize strings using a library is that it is a really helpful pattern (for testing, for cohesive language, for refactoring).
Our current method for storing strings is not working for a variety of reasons, some of which are outlined above. Other reasoning is outlined in the linked Notion doc. 

Of course, if we do end up translating the app in the future, we'll be in a good place with this new pattern.

This should not be a large effort but let me know if you have concerns! I placed this in the enqueue so it would get some eyes, but we don't have to work on it right now if we'd like to prioritize other stuff.

**Comment by kylecarbs** [comment]
Ahh, that makes sense! No concerns, was just curious.

**Comment by Kira-Pilot** [comment]
Going with react-i18next as a result of the poll in dev-ux.
