### ISSUE TITLE
Bug in v0.8.1 fd4954b: code-server 4.5.1 integrated terminal does not work

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#3136]
As a developer, I should expect code-server to open every time, and show a working integrated terminal

## Expected Behavior

When I click `New Terminal` and terminal should open with a prompt

## Current Behavior

I click 'New Terminal,' the Terminal area appears, with no prompt.

Once in a while, I may get a working Terminal.

**Comment by ammario** [comment]
I just tried to reproduce the issue and it seems fixed. Please re-open if that's not the case.
