### ISSUE TITLE
Write Howto on license files & signing keys

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#3142]
Problem:

We need internal documentation on how to generate license files and how to regenerate the signing keys.

AC:

 1. Internal Howto on generating license files (sales to review)
 1. Internal Howto on rotating signing keys.

**Comment by spikecurtis** [comment]
@Emyrk  could you do a docs review on my howtos? https://www.notion.so/coderhq/License-Files-Keys-38e5e3873157465292d361257ddb6c3c

**Comment by Emyrk** [comment]
Sure. Should we be tracking this on `coder/coder` issues?
