### ISSUE TITLE
Bug in v0.8.1 fd4954b: Multiple start, stop icons appear in workspace drop-down as you use and update the workspace

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3154]
## Expected Behavior

Start, Stop buttons should be distinct; instead that accumulate in the drop-down

## Current Behavior

<img width="239" alt="image" src="https://user-images.githubusercontent.com/2022166/180656883-5b5f4bce-a3a7-4dbc-b4c4-d9559f29f97b.png">

**Comment by ketang** [comment]
#3231 is the same(ish).
