### ISSUE TITLE
Add linter rule to force theme colors

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3175]
## Problem
It's easy to hard-code colors into the frontend, but that makes the codebase harder to maintain and the design harder to change.

## Solution
Use a linter rule to enforce using colors from the theme. This will involve fixing the existing cases of hard-coded colors.
I suggest doing #3573 and #3572 first to make this easier.
Related: #1973 

## Definition of done
[This linter rule](https://www.npmjs.com/package/eslint-plugin-force-theme-colors) is added and linting passes.

**Comment by jsjoeio** [comment]
Can I help with this?
