### ISSUE TITLE
Scheduled Shutdown Should Not Shutdown If There Are Active SSH Connections

### ISSUE THREAD

**Issue by Mainstay-Noah-Huppert** [coder/coder#3191]
I was working on my Coder workspace instance which is scheduled to shut down at 5:00 PM. Right as 5:00 PM came by my editor froze up and my SSH terminal closed its connection. 

In the future I will give myself an extra hour in the schedule to prevent this. But I feel like if I have established an SSH connection via the Coder CLI and it is still open the instance should not shut down.

**Comment by Mainstay-Noah-Huppert** [comment]
Coder server v0.7.12

**Comment by Mainstay-Noah-Huppert** [comment]
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/86365960/180877176-b95f4809-7b43-49ec-abea-96d5cc586506.png">

**Comment by bpmct** [comment]
We're considering a different model for `autostop` which stops the workspace after n hours of inactivity: #2233. What do you think of this?

**Comment by Mainstay-Noah-Huppert** [comment]
That could be good. I do like the schedule so that my workspace doesn't shut down during lunch or during a meeting heavy day. Mainly because there are some development tasks (👀 webpack) that take a few minutes to start up with a big app. So having the workspace up and the tasks already running saves time. Additionally having the scheduled start at 9:00 AM is nice because I know that by the time I start dev work after standup all those tasks will be running and good to go.

For my particular use case I think being able to configure only having keep alive functionality and not inacitvity shutdown would be nice.

**Comment by ammario** [comment]
@Mainstay-Noah-Huppert thank you for the feedback. Let's move the discussion [here](https://github.com/coder/coder/issues/2995).
