### ISSUE TITLE
Use without a network connection (air gapped)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3202]
## Problem statement

Some users may want to use Coder in air-gapped networks. By default, Coder dials the internet for the following reasons:

- Downloading Terraform binary
- Downloading Terraform providers (e.g `aws`)
- Telemetry

## Definition of done

We have validated Coder's core features can run in an airgapped network and have added the necessary features and documentation.

**Comment by ryanmerolle** [comment]
As an air gapped deployer that is looking into this tool, I fill like I could give some insight into a potential stakeholder setup.

We have container, yum, python, and github/gitlab proxy /caching services.

Thus if we can install terraform in the image ourselves (along with our normal certs), this would be fine.  Or if we could provide a url in the form of an ENV Variable to override the terraform download url, that would also work.

I am currently working with docker-compose for a skunkworks test.

**Comment by bpmct** [comment]
I've validated an airgapped install works and have shared my steps here. I'll likely archive the repo as soon as I create the official docs, but figured I'd share my progress for anyone following along: https://github.com/bpmct/coder-offline

**Comment by ryanmerolle** [comment]
Thanks @bpmct !

I just need to get my own existing container image working with coder now.

**Comment by yekanchi** [comment]
Is It technically possible to make an offline version without docker (Just binaries and other stuff like configs)?

**Comment by bpmct** [comment]
@yekanchi Yes - You can also download the Coder binary, `terraform` binary, and [configure Terraform to use a mirror](https://developer.hashicorp.com/terraform/cli/config/config-file#explicit-installation-method-configuration).
