### ISSUE TITLE
Replace getFormHelpers

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3209]
Problem: we have two functions that do similar things and the one we want to call from components has a more annoying name. 

Background: we had the function `getFormHelpers` and then decided to change how it works, but we needed to do so piecemeal, so we made `getFormHelpersWithError` in the meantime. 

Definition of done: the original `getFormHelpers` is deleted and `getFormHelpersWithError` is renamed `getFormHelpers`

**Comment by jsjoeio** [comment]
What's blocking this?
