### ISSUE TITLE
Design Audit Log

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3218]
## Problem
As an enterprise user, I want to be able to see actions people in my company are taking.

## Definition of Done
Mock here: 
https://www.figma.com/file/oy7echtkBVRuOCMBVSrr4T/Auditing?node-id=0%3A1

- [x] a list of columns and their order
- [x] a layout of the table of actions and any other controls needed on the page
- [x] a plan for where the nav link to the Audit Log page will go

**Comment by presleyp** [comment]
@Kira-Pilot just a heads up that I made this ticket as part of shredding the Licensing epic; feel free to edit as needed.

**Comment by Kira-Pilot** [comment]
@presleyp great, adding to the audit log epic as well.
