### ISSUE TITLE
Instruct admins to set up through CLI 

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3223]
## Problem
When an admin starts a new deployment of Coder, they must create the first user through CLI, but this is not obvious.

## Initial Solution
Have the frontend detect whether the first user has been created. If not, have it display CLI instructions.

## Eventual Solution
Replace the CLI instructions with a sign-up page so that the admin can do create their user through the UI.

## Definition of Done

- [ ] In a deployment with no users, the login page redirects to a page that displays instructions on how to create the first user through the CLI
- [ ] A deployment with at least one user has no change

## Notes
Here's what the signup flow looks like from the CLI: https://asciinema.org/a/cy8QVTPwazDAV6cxcV6DF1Qnj

Here's where initial user creation is implemented in the CLI: https://github.com/coder/coder/blob/v0.8.1/cli/login.go#L81-L196

**Comment by kylecarbs** [comment]
Would this work be obviated by https://github.com/coder/coder/issues/3225?

**Comment by kylecarbs** [comment]
Ahh, I see based on the description it would be. Could we just jump straight to doing the form instead? Seems like this middle step would be a little helpful, but most users are likely to go back to the CLI anyways.

**Comment by misskniss** [comment]
We do not need this one now that we have #3225. Closing this.
