### ISSUE TITLE
Add a registration/set-up page for new admins

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3225]
## Problem
Admins of new deployments can only set up their first user through the CLI

## Solution
In a deployment with no users, the login page redirects to a setup page that has a UI for the setup process

## Definition of Done

- [ ] In a deployment with no users, the login page redirects to a setup page with a form
- [ ] The form takes a username, email, and password
- [ ] Submitting the form creates a user and logs them in

## Notes
Here's what the signup flow looks like from the CLI: https://asciinema.org/a/cy8QVTPwazDAV6cxcV6DF1Qnj
Here's where initial user creation is implemented in the CLI: https://github.com/coder/coder/blob/v0.8.1/cli/login.go#L81-L196

**Comment by BrunoQuaresma** [comment]
I think this issue is maybe not blocked by #3223 but related to it. Is that right?

**Comment by BrunoQuaresma** [comment]
I also think this is a 5, because of testing. Is it ok if I change it?

**Comment by presleyp** [comment]
@BrunoQuaresma fine to change the estimate! I was thinking it was blocked because the other ticket handles detection of whether the first user has been created, which is needed for this.

**Comment by presleyp** [comment]
The API call exists, but it isn't called in the frontend yet, right? If you want to just do them both together, you can skip the part about writing about the CLI. The idea was just that it's urgent to make it more clear, and #3223 was enough to do that. It's less urgent to get the full fix in (this ticket).
