### ISSUE TITLE
feat: remove template Auto-stop from OSS and move into Enterprise Edition `--max-ttl` `--min-autostart-internal`

### ISSUE THREAD

**Issue by mark-theshark** [coder/coder#3244]
As a DevOps leader, I want to restrict Auto-stop options for developers building workspaces with my templates.

Auto-stopping controls should be part of the Enterprise Edition which is primarily for DevOps, Information Security, and Engineering leadership.

`coder templates create pod-with-code-server --max-ttl 2h --min-autostart-interval 30m  -y`

@ketang @kylecarbs @ammario

**Comment by ammario** [comment]
Ah, I duplicated this here https://github.com/coder/coder/issues/3244.
