### ISSUE TITLE
Add audit logging

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3251]
This is the epic for Audit Logging

## User Story
As a user, I would like to  identify security incidents, policy violations, fraudulent activity, and operational problems. 

## Requirements and Details
See our [Audit Logging RFC](https://www.notion.so/coderhq/v2-Enterprise-Audit-Logging-a6358d50a453413eae6441e689f023ac)

## AC
See the individual tickets linked below. (TBD)

## Definition of Done

- Moving existing audit code to `/enterprise` folders
- Adding generation of audit logs to the HTTP API for all supported auditable objects
- Adding CLI command to read audit logs
- Adding frontend page to read audit logs
- Adding APIKey support for Diff’ing
- Exporting to slog

### Backend Issues

- [ ] https://github.com/coder/coder/issues/3605
- [x] https://github.com/coder/coder/issues/3606

### Frontend Issues

- [x] #3220
- [x] #3219
- [x] #3218
- [x] #3266
- [x] #3356 
- [x] #3357
- [ ] #3418 
- [x] #3428
- [x] #3429
- [x] #3460
- [x] #3607
- [x] #3608
- [x] #3609
- [x] #3610

**Comment by misskniss** [comment]
The RFC for this issue is still in progress - what do we need to complete that RFC?

**Comment by BrunoQuaresma** [comment]
@ammario Im working on this

**Comment by ammario** [comment]
I'm closing this as the feature is completely exposed to the user. We should still do https://github.com/coder/coder/issues/3418 though.
