### ISSUE TITLE
Admin feature to add SSH-key-based backdoor into Coder-created resources

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3260]
## Problem statement

When a template is being defined or a workspace is being troubleshooted, it would be helpful for admins to directly SSH into the resource to identify whether the agent it starting, recover any data, or fetch logs. 

To do this today, an admin would need to ensure their SSH public key is hardcoded into template, and the resource has a firewall policy (e.g. security group) to connect via SSH.

From @spikecurtis in #2714 

> I wonder if we will want some ability for Coder to autogenerate and store (possibly externally) these "in case of emergency" type credentials.

## Definition of done

Coder admins can pragmatically add a backdoor into their templates with minimal effort.

**Comment by bpmct** [comment]
This feels like a quality-of-life feature. A current workaround is for the admin to hardcode their account's publicly-generated SSH key into the resource. However, there are a few problems that I can identify with that approach:

- Port 22 on the resource is always open, not just when a workspace is in a troubleshooting/failed state
- If the admin rotates their SSH key via the Coder UI or CLI, they would need to manually edit each template and add the new public key
- If there are multiple admins, they would need to share a key or each admin adds their keys into the resource

**Comment by spikecurtis** [comment]
We just talked about this at office hours, and I think Resource Metadata solves the use case.  I vote closing this issue.
