### ISSUE TITLE
Automatically import Kubernetes template when installing with Helm

### ISSUE THREAD

**Issue by tjcran** [coder/coder#3265]
### Problem
In #2267 a helm chart was added for a simpler install experience of the Coder dashboard. Teams who use the helm chart to install Coder to k8s will also likely want a "v1" style experience where new workspaces would be provisioned as K8s containerized workspaces.

### Definition of Done
We should "auto-import" https://github.com/coder/coder/tree/main/examples/templates/kubernetes-multi-service so that when a new Coder cluster is installed via the Helm chart, users can immediately create k8s containerized workspaces without further set-up required by admin.

**Comment by misskniss** [comment]
In our grooming discussion we discussed doing something similar for Docker as well. We should make that work a separate ticket after this on is complete.
