### ISSUE TITLE
Enterprise license, builds, release

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#3277]
# Problem

We need to be able to check in enterprise licensed code that doesn't get built from the AGPL entrypoints.  We also need to include the enterprise license itself so that people can understand what rights they do and do not have if they use this code.

# Implementation notes

We will add an `enterprise/` directory that contains new `main()` entrypoints for all released binaries.  For the purpose of this ticket, these binaries are functionally identical to the AGPL binaries, and the `main()` functions in enterprise should call into AGPL packages.

# Acceptance Criteria

1. New make targets that build enterprise variants of all the binaries we currently release.  (We don't need enterprise variants of utilities in this issue.) Includes cross platform builds.
2. Release scripts are switched to use enterprise builds.  AGPL "release" is not required, only the ability to build binary targets for all supported platforms.

**Comment by kylecarbs** [comment]
All of our build scripts should be enterprise by default, and therefore don't need to change the naming from my perspective.

I think for community-specific binary building we can have named steps, but I wouldn't want the inverse.
