### ISSUE TITLE
Implement Entitlements API in AGPL

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#3278]
# Problem

The frontend needs the [Entitlements API](https://www.notion.so/coderhq/Workspaces-v2-Paid-Features-Licensing-45c00200adc64c19b0ae51bee7d32413#842e91f29b124a8e94a87e38ebfd3c9f) to decide what features to render, even in the APGL case.

# Acceptance Criteria

1. Run `coder features list -o json` and get a response with all features `not-entitled`, no warnings, and `has_license` false.

**Comment by kylecarbs** [comment]
Could the endpoint be /entitlements instead? Features seems redundant.

**Comment by spikecurtis** [comment]
could be.  RFC has `api/v2/features/entitlements` and `api/v2/features/enablements` but we could drop features from both if you think it's clear enough
