### ISSUE TITLE
Member user cannot update their username

### ISSUE THREAD

**Issue by AbhineetJain** [coder/coder#3286]
## Problem statement

When a member user tries to update their username, they are thrown an error as seen in the following screenshot:
<img width="848" alt="Screen Shot 2022-07-28 at 11 26 50 PM" src="https://user-images.githubusercontent.com/7511231/181676568-007bdf53-eb70-47cc-ac1b-5eb8eda7abee.png">

## Proposal

Either we should allow members to update their own username or have a better message that can provide them the steps to do it (e.g. requesting their admin), or clarify that they don't have access to do it.

## Definition of done

TBD

**Comment by johnstcn** [comment]
We should probably not allow regular users to update their own username.
However, there should be an easy method in the UI to allow admins to update the username.
Currently they would need to do something like:
```
curl "https://my.coder.instance/api/v2/users/<user_id>/profile" --data-raw '{"username": "new_username"}' -H "Cookie: session_token=$(cat ~/.config/coderv2/token)"
```

**Comment by Emyrk** [comment]
This looks like an RBAC authorization deny. 

I think the UI should show disabled for regular users.

**Comment by johnstcn** [comment]
@Emyrk agreed, it would also be nice to have a UI option for admins to just edit usernames. But having a CLI command would probably be an OK workaround.

**Comment by Emyrk** [comment]
That field should have an `/authorization` check in the UI.

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/coder/pull/3649
