### ISSUE TITLE
Docs: duplicate text on Configuring Web IDEs page

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#3288]
1. Go to https://coder.com/docs/coder-oss/latest/ides/configuring-web-ides
2. See JetBrains Projector -> Pre-built templates section

"**You need to have a valid ~/.kube/config on your Coder host and a namespace on a Kubernetes cluster to use the Kubernetes pod template examples.**" displays twice before and after screenshot, see below:
![image](https://user-images.githubusercontent.com/35501151/181701245-eb9bd1e3-39c8-47b7-9658-062646646083.png)

**Comment by ammario** [comment]
Fixed in #3290
