### ISSUE TITLE
Unable to connect to Docker workspaces

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#3292]
Coder version:
Coder v0.8.1

Reproduced on Windows 10 and MacOS (v.11.6.7)

**Steps:**

1. run coder server or coder server --tunnel
2. coder templates init
3. select "Develop in Docker"
4. create template following cli instructions
5. create a workspace from Docker template
6. log in to web UI and open workspace details page

**Actual Result:** status ⦿ Connecting, Terminal/SSH buttons are not displayed, user is not able to connect to workspace via ssh
![image](https://user-images.githubusercontent.com/35501151/181764988-4f2ba67e-b965-4046-a793-3081d75810cb.png)
![image](https://user-images.githubusercontent.com/35501151/181765235-1c88c85d-bfa6-49f2-a000-c17c6578200c.png)

[main.tf.txt](https://github.com/coder/coder/files/9220052/main.tf.txt)

**Expected Result:** user is able to connect to workspace

**Comment by im-coder-lg** [comment]
This seems the same as my issue!
