### ISSUE TITLE
User can interpret the question mark icon in the resources list as some kind of problem

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#3301]
![image](https://user-images.githubusercontent.com/3165839/181821774-b0a5cd38-affc-4368-a8b3-9accc97b5b91.png)

A suggestion from the community was to replace it with a more generic one like a cube(I'm not sure if there is one like this on MUI).

**Comment by jsjoeio** [comment]
I am looking at the [Material Icons](https://mui.com/material-ui/material-icons/?theme=Outlined) now. Here are couple options:

CloudCircle
<img width="54" alt="image" src="https://user-images.githubusercontent.com/3806031/187317284-2eab547a-0a86-40af-97b0-ff37b84aa74b.png">

Storage
<img width="59" alt="image" src="https://user-images.githubusercontent.com/3806031/187317310-12947ef4-13f4-4082-bd23-7daddb399d7a.png">


@BrunoQuaresma thoughts? I'd like to pick one and fix this.

### Notes to Self

Changes will be made here: https://github.com/coder/coder/pull/3118/files#diff-f219cd4f34f9300e65c1fd2c36abd018870d6c55e566f182af19ee07f6161b30

**Comment by kconley-sq** [comment]
I'm nervous that `CloudCircle` may not fit for user-local workspaces that wouldn't be running in the cloud (e.g. #909). I think `Storage` might be okay, but to me it looks like a server rack or maybe a tower of disk platters that I'm worried may be too specific for arbitrary resources.

What do you think about `Widgets`? I think it may be a little more generic:
<img width="42" alt="image" src="https://user-images.githubusercontent.com/93007527/187318367-ed7a9de8-88f7-4fc5-898b-42c69e790b9b.png">

**Comment by BrunoQuaresma** [comment]
I really liked the @kconley-sq suggestion of using the widgets icon

**Comment by jsjoeio** [comment]
> What do you think about Widgets? I think it may be a little more generic:

Great idea! I agree, that looks a bit more generic. I'll go with that!
