### ISSUE TITLE
Web terminal is not matching the current site theme

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#3305]
<img width="1792" alt="Screen Shot 2022-07-29 at 16 00 30" src="https://user-images.githubusercontent.com/3165839/181826931-89ed4b49-bf30-44f9-8265-9848596dfd81.png">

I'm not sure how hard it is to make the theme match the current site colors, or if we could choose an existing one that is more "purple-ish" or "blue-ish".

**Comment by mattlqx** [comment]
Is it feasible to have this customizable? I'd care more about custom font and font size though.

**Comment by BrunoQuaresma** [comment]
I think the font size is, but not sure about the custom font since the user would have to upload that. Maybe we could provide some built-in fonts? Also, where would you add the terminal settings?

**Comment by mattlqx** [comment]
I humbly suggest https://github.com/tonsky/FiraCode 🙂

I think the presently spartan Account Settings page would be great to have some user preferences when it comes to things like defaults and settings like this. A subtab for Terminal could house these nicely.
