### ISSUE TITLE
Refactor telemetry for Enterprise Edition

### ISSUE THREAD

**Issue by ammario** [coder/coder#3309]
We've decided to pursue telemetry as described [here](https://github.com/coder/coder/pull/2641/files).

**Comment by kylecarbs** [comment]
Read the closed attached PR docs to get context on the behavior that telemetry should have!

**Comment by ammario** [comment]
We should probably have a disclaimer like this:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/7416144/192834309-26e69a93-a44b-4275-a852-8c6adb1ba8a0.png">

in our install script.
