### ISSUE TITLE
Add a display name to template settings

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3321]
## Problem statement

I'd love to be able to create templates with the following names:

- Proxmox VM
- Proxmox Container
- Standard Dev Bundle
- Bare Dev Bundle
- Ubuntu Slim
- Docker with nixOS

However, template names are currently being validated as usernames so this is not possible. 

https://github.com/coder/coder/blob/3e419ddb3d94f694841553f2c8b8c54bd8d4f869/codersdk/organizations.go#L51

https://github.com/coder/coder/blob/c8d04aff6b7a9e58a2205426edfbc20040780bb0/coderd/httpapi/httpapi.go#L20

## Definition of done

Users can create templates with names that contain spaces.

**Comment by bpmct** [comment]
Chatted with @kylecarbs a bit, it looks like this was done in order to have consistent validation and pretty URLs across objects. Perhaps a template could have a label `aws-linux` and slug `Develop on Linux with EC2`

**Comment by ketang** [comment]
Spaces I understand for URLs but underscores?

Also, we've trimmed down the number of places where we use a name in the URL; is that true of templates as well?  Given anticipated future template namespacing, seems like the template name has pros and cons for use in the URL.

**Comment by bpmct** [comment]
@ketang Yeah I couldn't identify a use for underscores, so not sure why I included it. I'll change the issue title.

**Comment by bpmct** [comment]
> Also, we've trimmed down the number of places where we use a name in the URL; is that true of templates as well? Given anticipated future template namespacing, seems like the template name has pros and cons for use in the URL.

Yep, still in the URL
<img width="514" alt="Screen Shot 2022-08-01 at 9 59 56 AM" src="https://user-images.githubusercontent.com/22407953/182179074-1bb3fe32-b068-4291-895b-e31b2cc52e79.png">

**Comment by mtojek** [comment]
Looking at this one.

**Comment by bpmct** [comment]
Hey @mtojek. Love this. Will it also use the template display name on other pages, such as the workspace page and workspaces list?

> Did I miss anything? Should it be possible to change the display name using UI?

For consistency's sake, I think the display name should be managed just like the icon and description properties (via `coder templates edit` and the UI).

**Comment by mtojek** [comment]
> Will it also use the template display name on other pages, such as the workspace page and workspaces list?

That's the plan and I hope it's doable.

> For consistency's sake, I think the display name should be managed just like the icon and description properties (via coder templates edit and the UI).

Ok, so it seems that instead of `coder templates create <template-name> --display-name <display-name>` we can go with `templates edit`. Please correct me if I'm wrong.

**Comment by bpmct** [comment]
Yep! That makes sense :)
