### ISSUE TITLE
Can't access logs when workspace fails

### ISSUE THREAD

**Issue by ammario** [coder/coder#3329]
As a template admin, I try out my template by creating a workspace. Since there is a failure in my `startup_script`, the workspace "fails" and its resources are immediately deleted. The problem is I've now lost my `/var/log/coder-startup-script.log` and can no longer find the error.

A workaround is adding an `sleep 999999` or disabling `set -e` in my startup script, but ideally I can find the error without making a temporary modification to my `startup_script`.

Some approaches:
* Create a new substate of Success for "agent failure" (like v1)
* https://github.com/coder/coder/issues/2957

**Comment by kylecarbs** [comment]
Are you certain this is happening? Our code doesn't do this...

https://github.com/coder/coder/blob/f82df1bd78ada2b6e242cd29320ff4ba28401221/agent/agent.go#L153-L164

**Comment by ammario** [comment]
Oh. I made this issue a few weeks after experiencing it so I misremembered.
