### ISSUE TITLE
Multiple workspaces cannot co-exist on same fs root

### ISSUE THREAD

**Issue by ammario** [coder/coder#3340]
As a template admin, I want to put multiple workspaces on the same root filesystem to simplify my setup of a basic deployment (https://github.com/coder/coder/issues/3331).

Multiple agents cannot run in the same root for _at least_ the following reasons:
* Since the agent stores logs at a constant location in `/tmp`, multiple agents would overwrite each others' logs
  * Possible solution: store logs in agent's `dir` instead of `/tmp`. This avoids the need for extra configuration.
* There is no way to start an agent as a specific OS user

**Comment by ketang** [comment]
`/tmp` seems good to avoid filling disks.  Seems like you could have a different temp subdir for each agent instance.

**Comment by kylecarbs** [comment]
These can be options provided to an agent!

**Comment by spikecurtis** [comment]
> There is no way to start an agent as a specific OS user

One thing we do in some of the templates like `azure-linux` is to use `systemd` to start the Agent, which makes it trivial to select the user to run the process.
