### ISSUE TITLE
`coder template create` doesn't explain validation error

### ISSUE THREAD

**Issue by ammario** [coder/coder#3349]
## Steps to Reproduce

1. Run `coder templates create 1234567890123456789012345678901234567890`, which exceeds the 32 char name limit (make sure you have `main.tf` file in the working directory)
2. Go through the steps
3. At the end, observe a vague "Validation error"

```shell
Validation failed.                                                                                      
- name: Validation failed for tag "template_name" with value: "1234567890123456789012345678901234567890"
Run 'coder templates create --help' for usage.   
```

**Comment by mark-theshark** [comment]
💯

**Comment by jsjoeio** [comment]
## Notes to Self

A straighforward fix is to check the length of the template name in the `templatecreate` CLI command. I don't know how easy it is to sync it with wherever the 32 char name limit is. I plan to tackle this this week.

Relevant code:
- https://github.com/coder/coder/blob/main/cli/templatecreate.go#L45-L50
- https://github.com/coder/coder/blob/main/cli/templatecreate_test.go
