### ISSUE TITLE
Add template documentation to Workspace page

### ISSUE THREAD

**Issue by ammario** [coder/coder#3372]
As a template admin, I want to:

* Deprecate a workspace template (add a big DEPRECATED heading to the workspace page)
* Show the Changelog (e.g in CHANGELOG.md)
* Save my users a step when accessing documentation

I am concerned about making the Workspace page long and redundant if the README is extensive. We could add comment flags to the README.md to cut off a specific section for the workspace page. For example, a `<!--- BEGIN WORKSPACE --->` and a `<!--- END WORKSPACE --->` could determine a section to add the workspace page.

**Comment by BrunoQuaresma** [comment]
I like the idea but I'm also concerned with making the Workspace page long and redundant and adding a new "README" language convention by adding things like: `<!--- BEGIN WORKSPACE --->`. I'm not sure if this provides enough value tho. Why a template admin can't decide to deprecate or not a template from the template page? 🤔

**Comment by ammario** [comment]
I agree. I think this is too much for us now.
