### ISSUE TITLE
No way to debug a slow agent start

### ISSUE THREAD

**Issue by ammario** [coder/coder#3374]
I recently had a workspace agent that took 2 minutes to start. For those two minutes, there were zero logs so I am unable to figure out how to make it start faster.
<img width="1527" alt="Screen Shot 2022-08-03 at 1 22 24 PM" src="https://user-images.githubusercontent.com/7416144/182681262-f409c3cd-3cfd-4fc7-8704-d656aa96f54a.png">

**Comment by kylecarbs** [comment]
What happened here? How did it take 2mins to start?

**Comment by ammario** [comment]
Exactly the point. I can't find out because there are no logs.

**Comment by bpmct** [comment]
This is happening consistently on my workspace, so let me know if you want to debug live @kylecarbs.

**Comment by kylecarbs** [comment]
This is slow on the reaper. @sreya and I chatted about this.

**Comment by bpmct** [comment]
I have not ran into this recently, let's just close.
