### ISSUE TITLE
feat: Auto delete workspaces that are in stopped state for a speceified time

### ISSUE THREAD

**Issue by matifali** [coder/coder#3388]
To save storage resources, auto delete workspaces that are in a stopped state for a specified time interval. 
This can be available to all users as well as admins as an option in their settings.

**Comment by ammario** [comment]
It's pretty dangerous to run a potential destructive action like this without explicit user consent. What if there was a loud way to mark a workspace as ephemeral (which appeared in all views so the user doesn't forget)?

Related #2988

**Comment by matifali** [comment]
Yes you are right @ammario but as currently there are no limits one of my users is creating a new workspace everytime he wants something. He is not deleted the old ones and told me that it if he doesn't use one for s long time say 1 week or 1 month then it may be auto deleted.

 This problem can be solved if he is only allows to create let's say 5 workspaces and can run any 2 of them simultaneously. 


This is just an idea. I know it might also cause a possible loss of data. When we are on long vacations and actually need the data stored in workspaces.

**Comment by ammario** [comment]
@matifali understood. Let's tackle this in #2988 then.
