### ISSUE TITLE
Workspace build logs not rendering

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#3397]
Built a workspace and it failed immediately. I tried navigating to the log output and nothing is showing.

Experienced this on both `0.8.1` & `0.8.2`. Reproduced on Safari and Firefox. Likely related to the `In Progress` duration status.

<img width="1253" alt="Screen Shot 2022-08-07 at 1 36 39 PM" src="https://user-images.githubusercontent.com/9683576/183303684-07e7b5bf-40cf-4f90-871e-9bfeb148d99e.png">

**Comment by kylecarbs** [comment]
Yup, I saw this too. Good issue.

**Comment by kylecarbs** [comment]
I don't think this can happen anymore.
