### ISSUE TITLE
`coder templates push` does not update all elements of a template 

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3400]
As a user, I will make mistakes in my templates, and need to update them and iterate as I go.

Coder OSS right now does not check if `data.coder_workspace.me.name` is lower case when using Docker, which leads to problems.

So I edit the template to force `lower(data.coder_workspace.me.name)` but `coder templates push` does not reflect in an updated workspace.

I had to delete the workspace and create a new one to see that change.

**Comment by kylecarbs** [comment]
That should update. I think there was something else going on here that wasn't working.
