### ISSUE TITLE
feat: add template validation in CLI to check for lower case `data.coder_workspace.me.name` in Docker workspaces

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3401]
As a developer, I must already have noticed in one of Coder's example templates that `lower(data.coder_workspace.me.name)` is required when using Docker compute or there will be problems in the workspace. This is a known Docker thing with mix-cased containers.

[A user in the Discord channel has the recommendation](https://discord.com/channels/747933592273027093/971754046639734836/1005905686976282777) to make this a validation check in `coder templates create` versus having the lower() in the template.

[I filed a related issue](https://github.com/coder/coder/issues/3400) on the templates not updating correctly. #3400

**Comment by kylecarbs** [comment]
It's a common issue, so we should have a post on it, but we shouldn't make assumptions about template input variables. Mutating this data can break as many user flows as it solves.
