### ISSUE TITLE
Failed to download coder agent when running docker

### ISSUE THREAD

**Issue by andrefmello91** [coder/coder#3402]
After creating a workspace from a container, I'm not able to connect to the workspace from coder.
I'm getting the following error in the container start:

```
+ :
+ status=
+ command -v curl
+ curl -fsSL --compressed http://host.docker.internal:3000/bin/coder-linux-arm64 -o coder
curl: (7) Failed to connect to host.docker.internal port 3000: No route to host
+ status=7
+ echo error: failed to download coder agent
+ echo        command returned: 7
+ echo Trying again in 30 seconds...
error: failed to download coder agent
       command returned: 7
+ sleep 30
Trying again in 30 seconds...
```

**Comment by bpmct** [comment]
Hi - are you exposing Coder as `http://0.0.0.0:3000`? If so, I'm not sure why this isn't working.

If you are running Coder behind a reverse proxy, you can specify the access URL with the `CODER_ACCESS_URL` environment variable:

```diff
docker run \
  -e CODER_PG_CONNECTION_URL=postgresql://localhost:5432 \
+ -e CODER_ACCESS_URL=https://coder.example.com \
ghcr.io/coder/coder
```

**Comment by andrefmello91** [comment]
I solved the problem by putting the development container in the same network of the coder container.
Just set `CODER_ACCESS_URL=http://coder:7080` and added the following block to the container resource in main.tf:
```
resource "docker_container" "workspace" {
...
  networks_advanced {
    name = "server"
  }
...
}
```
