### ISSUE TITLE
Default username and password when using docker-compose?

### ISSUE THREAD

**Issue by polhaghverdian** [coder/coder#3404]
Hi,

Is there a default username and password when using docker-compose? If not, how am i supposed to create a user?

**Comment by ericpaulsen** [comment]
hi @polhaghverdian - you'll need to run `coder login <access-URL>`, with your access URL likely being http://localhost:7080. Once you run the command, it will prompt you to create the first user/password.

**Comment by polhaghverdian** [comment]
@ericpaulsen  Thank you!  it worked :+1:
