### ISSUE TITLE
getting below error when installing coder 

### ISSUE THREAD

**Issue by yaddanske** [coder/coder#3405]
Getting below error , please help. i am behind a proxy 
<img width="925" alt="Capture" src="https://user-images.githubusercontent.com/89769383/183417620-687d01ca-ed44-472a-8621-40e977fd7d95.PNG">

**Comment by mark-theshark** [comment]
@yaddanske what is your `coder server` string with parameter flag settings?

**Comment by yaddanske** [comment]
coder server --tunnel 
this is command i am giving

**Comment by kylecarbs** [comment]
@yaddanske on start of our default installation, Coder attempts to download a PostgreSQL instance from Maven to use for a simple setup.

This can be disabled by using an external PostgreSQL instance instead!
