### ISSUE TITLE
Feat: embed IDEs and dashboard inside another provider's web app

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3411]
A prospect is inquiring about providing Coder's developer experience but from within their web application.

"We'd like to offer Coder as part of a service to our end users. Users write code that we run on our platform, and we're looking for some way to allow users to write that code from our web app, without leaving their browser."

So this use case is not just the end-state of IDE but also workspace creation and deletion.

We've heard this request in v1 before but there was no clean way to do it with our API and URL endpoints.

**Comment by kylecarbs** [comment]
I just added the godoc badge that links to [some code documentation](https://pkg.go.dev/github.com/coder/coder@v0.8.2/codersdk).

Would our API suffice for this? I'm unclear about what we'd have to change from this issue.

**Comment by kylecarbs** [comment]
Going to close this for now. Someone can use our API to do this.
