### ISSUE TITLE
Remove dependency on darwin runners for codesigning

### ISSUE THREAD

**Issue by deansheather** [coder/coder#3414]
There is now an open source cross-platform code signing and notarizing tool that works on Linux. https://gregoryszorc.com/blog/2022/08/08/achieving-a-completely-open-source-implementation-of-apple-code-signing-and-notarization/

Removing the three release jobs in favor of a single job should yield massive performance increases. Most of the release build time is taken up by uploading artifacts for use in the next job.

## Success criteria:
- No darwin runners are used during the release/build process except for cross-platform testing
- Darwin binaries are built on linux, signed on linux and notarized on linux
- Release build becomes a single job instead of a linux job, a darwin job and a final linux publish job

cc @kylecarbs

**Comment by kylecarbs** [comment]
Speed :fast_forward: :dash: :wavy_dash: :speedboat: :racehorse:

**Comment by deansheather** [comment]
Blocked by a bug in `rcodesign` that causes Golang binaries to be corrupted. indygreg/PyOxidizer#634

**Comment by deansheather** [comment]
The above issue is now resolved, and we now depend on my upstream PR getting merged: indygreg/PyOxidizer#635
