### ISSUE TITLE
Add documentation for Audit page

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3418]
As a user viewing the audit page, I would like to be able to link to documentation that tells me what sort of events are tracked. 

[Audit RFC](https://www.notion.so/coderhq/v2-Enterprise-Audit-Logging-a6358d50a453413eae6441e689f023ac)

[Audit Mocks](https://www.figma.com/file/oy7echtkBVRuOCMBVSrr4T/Auditing?node-id=0%3A1)

## AC

- [ ] Create a documentation page for the Audit Log. This page should include what sort of events we track.
- [ ] Amend the Audit header tooltip such that it matches the mocks and provides a link to the new documentation page ("Events we track" in the below screenshot): 
<img width="654" alt="Screen Shot 2022-08-08 at 4 48 02 PM" src="https://user-images.githubusercontent.com/19142439/183511675-399c123b-40b4-44cd-984d-f74819171bad.png">

- [ ] Add a test for the above work.

## Definition of Done
Above AC is completed.

**Comment by BrunoQuaresma** [comment]
@coadler just a few questions so I can write these into the docs.
- What are the roles that have access to Audit Logs?
- What events are tracked?
