### ISSUE TITLE
Hide some resources from the workspace view

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3450]
## Problem statement

The resources list on the azure VM is quite bulky and has resources that are not super relevant to the developer. It'd be great to hide specific resources from the dashboard view. 

## Definition of done

An admin can specify specific resources to hide from the workspace view

## Idea: use `coder_metadata`

<img width="1287" alt="Screen Shot 2022-08-10 at 6 37 43 AM" src="https://user-images.githubusercontent.com/22407953/183892149-dd3e6e3a-b409-443d-b1ca-0a517bcac7d2.png">

```diff
resource "coder_metadata" "hide-subnet" {
  count       = data.coder_workspace.me.start_count
  resource_id = azurerm_subnet.internal.id

+ hide        = true
- item {
-   key   = "currently one key value pair is required"
-   value = "for coder_medata"
- }
}
```

cc @spikecurtis @dwahler

**Comment by spikecurtis** [comment]
I actually don't know our thinking around showing the workspace resources to workspace users in the first place.  Like, what are the use cases or user stories for resources?  Without those, I don't feel confident to comment on whether hiding them is a good or bad idea.

**Comment by bpmct** [comment]
Here's how I understand it:

- As a user, I want to understand what the core components of my workspace are (e.g Kubernetes pod + persistent volume)
- As a user, I want to code on resources by using the SSH button or `coder_apps`

- As an admin, I want the option to hide/abstract away specific complexities behind a workspace that aren't necessarily important for developers, data scientists, or technical business users to use Coder. Today, I can partially do this by setting `type = null`or `type = "generic term"` as workspace metadata to obstruct the type. However, some resources altogether (e.g a virtual network) don't need to be exposed to the developer in the dashboard as it distracts users from important concepts: "vm, code-server, disk size"

**Comment by spikecurtis** [comment]
What counts as a "core component", and why do I, as an end user, care about these components but not other ones?

**Comment by mattlqx** [comment]
I would like the opportunity to selectively expose certain attributes of a resource in this view. An obvious example would be if you have an instance with a public IP and you wanted to surface that there. Maybe IOPS/Throughput settings on an EBS device? It would be great for the template creator to have the flexibility to decide what is important to surface to the user.

**Comment by bpmct** [comment]
> What counts as a "core component", and why do I, as an end user, care about these components but not other ones?

I guess my argument is that that is up for the admin to decide.

**Comment by kylecarbs** [comment]
We just got another request for this from a prospect!
