### ISSUE TITLE
default auto-stop duration is too short

### ISSUE THREAD

**Issue by ammario** [coder/coder#3462]
My default auto-start was at 9:30am and the stop was 2 hours later, so 11:30am. This is an odd assumption on the work day.

**Comment by sharkymark** [comment]
@ammario this was discussed among product. Our default was 12 hours which was a waste of compute, especially if cloud. If users want to change these, they can.

**Comment by ammario** [comment]
12 might be too long, 2h is definitely too short. Very few people start working at 9:30am and then stop at 11:30am. If we had activity-based extensions (#2995), this would be a different story.
