### ISSUE TITLE
Improve UX of disabled auto-start/stop

### ISSUE THREAD

**Issue by presleyp** [coder/coder#3463]
## Problem
#3358 introduces the ability to disable the auto-start or auto-stop section of the workspace schedule form. For ease of use, your most recently entered values are held in the form even when you disable it, so that if you re-enable it, you don't have to re-enter them. However, they are cleared when you submit the form (this is necessary because the backend uses empty values to signify disabled; the switch is only on the frontend). Thus, a disabled section has misleading helper text that tells you when your workspace will stop or start, but in reality, if you submit the form with switches off, no automatic starting or stopping will happen. 

This helper text is lying to you:
<img width="451" alt="Screen Shot 2022-08-10 at 10 45 35 AM" src="https://user-images.githubusercontent.com/1290996/184012394-39a1f464-01a8-43d2-86b6-7f922270394d.png">

## Definition of Done:
It's clear to the user what values will be saved when they submit the form. 

## Possible solutions:
- do not persist form values (clear the values when a section is disabled)
- hide helper text when a section is disabled (probably requires editing `getFormHelpers` in order to preserve the decision between showing helper text and error text)
- add helper text to the switches to make it more obvious that if the switch is off, all bets are off
- ???

**Comment by bpmct** [comment]
@presleyp do you prefer one of these solutions over the others?

**Comment by presleyp** [comment]
@bpmct good question, not sure. I think I would move the helper text that sums up your time until shutdown to be section level instead of field level and have it sum up whatever is currently true taking into account both the switch and the number. The field could still have helper text but it could be narrower in what it claims. And something analogous in the start section.

**Comment by bpmct** [comment]
> do not persist form values (clear the values when a section is disabled)

I decided to go with this option instead. I think this was what you were saying.

> For ease of use, your most recently entered values are held in the form even when you disable it, so that if you re-enable it, you don't have to re-enter them.

I don't think this i
