### ISSUE TITLE
Create a lightweight image for getting started with Docker

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#3465]
Users that install Coder select the Docker template to get a feel for the product quickly. Our Docker templates ship `codercom/enterprise-base:ubuntu` as the image, which is >1GB uncompressed.

Developers that want to get started quickly don't require a fully-featured development environment to write production applications, they just need to tinker and get a feel.

The image should be <250MB uncompressed. This seems reasonable considering bases like Ubuntu are [~30MB](https://hub.docker.com/layers/ubuntu/library/ubuntu/latest/images/sha256-42ba2dfce475de1113d55602d40af18415897167d47c2045ec7b6d9746ff148f?context=explore). It'd be nice if we made the shell a bit fancy, and included some fun utilities like `batcat`, `exa`, and `nix`.

**Comment by sharkymark** [comment]
@kylecarbs can you stick `fish` in there while you're at it?

**Comment by kylecarbs** [comment]
Of course @sharkymark!

**Comment by bpmct** [comment]
Closing. We will use devcontainers for our devcontainers.
