### ISSUE TITLE
Failed workspace actions seem to create extra buttons

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#3481]
<img width="1389" alt="Screen Shot 2022-08-11 at 7 30 38 PM" src="https://user-images.githubusercontent.com/739851/184274241-39ea0c83-5e3d-432d-b1d1-a01dd18d3cd5.png">

The initial create failed, which is pretty common while I'm developing a template. It seems to create extra stop or start action buttons in the dropdown when there have been failed actions.

**Comment by sharkymark** [comment]
@mattlqx Sorry you are experiencing this. I reported this as well in #3154 

CC @ammario @kylecarbs @bpmct

**Comment by sharkymark** [comment]
@mattlqx Also #2662 is a known health check issue so initial clicks may not work while `startup_script` is running. Thanks for reporting all of this.

**Comment by mattlqx** [comment]
Ah, thanks, sorry I think I might've neglected to search first.

**Comment by sharkymark** [comment]
@mattlqx No! the more the merrier. It gives my issue more weight!
