### ISSUE TITLE
UI shows agent "connecting" when workspace is stopped

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#3484]
<img width="1380" alt="Screen Shot 2022-08-12 at 6 50 17 AM" src="https://user-images.githubusercontent.com/739851/184367485-eb8c9fec-0938-41bc-a34f-85d9e6f6bc26.png">

Minor nit that Coder knows the workspace is stopped, so displaying the agent status is a bit moot. The green "Connecting" also implies that there's something working in the background. I think a better display would either to omit that or match the workspace Stopped display.

**Comment by Kira-Pilot** [comment]
Related to (but separate from) #3510 and #3511. Putting up a PR to address the FE aspect of this issue in a minute.
