### ISSUE TITLE
Allow coder_metadata to set the icon for a resource

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#3487]
<img width="318" alt="Screen Shot 2022-08-12 at 8 37 28 AM" src="https://user-images.githubusercontent.com/739851/184391111-79e53b1e-01f2-47cb-8bb8-9e77d30a3d72.png">

Some (most?) Terraform resources show up as a ? icon in the workspace state display. It would be nice to allow setting this either arbitrarily, or from a pre-defined icon set.

**Comment by bpmct** [comment]
Huge fan of this! We can probably support an arbitrary icon since we have a prior pattern for this with the coder_app resource in Terraform.

**Comment by BrunoQuaresma** [comment]
@bpmct @mattlqx would you be ok if we use the Material Icons for this?

**Comment by bpmct** [comment]
@BrunoQuaresma sounds good

**Comment by BrunoQuaresma** [comment]
Following the discussion on this PR https://github.com/coder/terraform-provider-coder/pull/48 we changed this feature a bit to accept image URLs instead of Material UI icons.
