### ISSUE TITLE
Show workspace costs with Infracost

### ISSUE THREAD

**Issue by ammario** [coder/coder#3491]
Related: I've used [Infracost](https://github.com/infracost/infracost) in the past. An integration using it and displaying cost approximations in the resource metadata to user would be pretty fabulous.

_Originally posted by @mattlqx in https://github.com/coder/coder/issues/2988#issuecomment-1213280298_

---

This could be a good sidekick to #2988

This may not be worth doing because Infracost has no way of evaluating Kubernetes or Docker resources, which comprise the majority.

**Comment by kylecarbs** [comment]
@ammario you should share your findings from investigating this the other night!
