### ISSUE TITLE
`git clone` in `startup_script` fails the first time, even if my Coder-issued SSH key is in my Git provider

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3500]
Version: [`v0.8.5+95f26f7`](https://github.com/coder/coder/commit/95f26f74b6ff6be1ffe42fceb21f70219889dc99)

I would like Coder to clone a source code repo as part of the template `startup_script`

Note: the Coder-issued SSH public key is already in my git provider, GitHub cloud

The first time I create a workspace, the cloning fails with:

Cloning into ''...
Host key verification failed.

Coder authenticates with  [using the public key below. All clones with SSH  
are authenticated automatically 

If I stop the workspace, and restart it, it then clones correctly.

## startup_script

# clone repo
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
git clone --progress git@github.com:${var.repo} 2>&1 | tee -a repo-clone.log

**Comment by ketang** [comment]
Can you make your clone script dump your env to a file?  Maybe something hasn't been set yet.

**Comment by kylecarbs** [comment]
I believe this was fixed by manually creating the `~/.ssh` dir as part of the startup script!
