### ISSUE TITLE
Allow helm chart to be able to set replica count to more than 1

### ISSUE THREAD

**Issue by tjcran** [coder/coder#3502]
### Problem Summary
With the addition of https://github.com/coder/coder/pull/2746 users are able to install Coder via helm chart, but the chart does not have a line to allow for setting the replica count higher than one. This is important in being able to deploy Coder in a more resilient and fault tolerant manner.

### Definition of Done
`values.replica` could be included on the the helm chart so users can set a value higher than 1.

**Comment by tjcran** [comment]
@ammario do we agree this should be Enterprise? Also.. is that even enforceable being something on the helm chart?

**Comment by ammario** [comment]
This is a simple addition blocked by #3227
