### ISSUE TITLE
Account-wide parameters (e.g. dotfiles URL). Maybe even resources?

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3506]
Allow Coder admins to create a "account-wide" template that provisions resources and has parameters which can be used in workspace templates.

This is an idea for an abstraction for "user settings" which unlocks a few use cases. However there are certainly other ways we can support these features. 

## Use case 1 (dotfiles)

Since Coder can't guarantee dotfiles behavior on every template, we recommend users use the `coder dotfiles` command within workspaces or even build it into the template. [(Docs)](https://github.com/coder/coder/blob/v0.8.5/docs/dotfiles.md)

Currently, a user will need to manually enter their dotfiles URL into each workspace, even though the value is the same across all workspaces and should be set in the "Account settings," page, like in Coder Classic. 

@sharkymark would like an account-level dotfiles setting (probably be default) in deployments.

Account template example:
```hcl
# templates/user/main.tf

variable "dotfiles_uri" {
  type        = string
  description = <<-EOF
  Dotfiles repo URI (optional)
  see https://dotfiles.github.io
  EOF
  default     = ""
}
```

Settings example
![dotfiles-concept](https://user-images.githubusercontent.com/22407953/184557059-5b74bd56-3796-4267-ae00-b4443307842a.png)

Workspace template example:

```hcl
# templates/aws-linux/main.tf

data "coder_user_settings" "dotfiles" {
  name = "dotfiles_url"
}

resource "coder_agent" "dev" {
  # ...
  startup_script = data.coder_user_settings.dotfiles != "" ? "coder dotfiles -y ${data.coder_user_settings.dotfiles}" : null

}
```

**Comment by sharkymark** [comment]
@bpmct ah almost like auto-start and workspaces. you select which template you want to have the dotfiles apply to. I like it!

**Comment by bpmct** [comment]
I initially considered it the other way around, where the admin decides (via templates) where the user-wide setting is applied, but I like the ability for users to opt in per workspace too 🤔

**Comment by kylecarbs** [comment]
I think we close this for now until we have a better spec of how to do it.
