### ISSUE TITLE
Add instructions to docs for setting up an external PostgreSQL server with Coder

### ISSUE THREAD

**Issue by mafredri** [coder/coder#3508]
We should add an example to the docs for setting up an external PostgreSQL database.

It doesn't have to be very comprehensive, but it's good to illustrate how a user can go about doing it.

I'm not saying these are the instructions we should use, but something along the lines:

```shell
# Install and start the database server.
sudo apt update
sudo apt install postgresql
sudo systemctl enable postgresql
sudo systemctl start postgresql

# Create a role and empty database for coder to use.
# NOTE: Use a strong password instead of "secret42".
# NOTE: Consider using a more limited user than superuser.
sudo -u postgres psql \
	-c "create role coder login superuser password 'secret42';" \
	-c "create database coder;"

# Start the coder server.
export CODER_PG_CONNECTION_URL="postgres://coder@localhost/coder?password=secret42"
coder server
```

**Comment by sharkymark** [comment]
@mafredri I did this, and @ammario basically deleted it.

**Comment by ammario** [comment]
I removed it because there are already dozens of high-quality tutorials online on how to do this, and the instructions vary based on the cloud and operating system.

**Comment by mafredri** [comment]
@ammario I understand your point about PostgreSQL setups, and while I agree in part, I think the value in my suggestion is that a user/admin can get a visual representation of _what is needed for Coder to work with my PostgreSQL database_. Right now it's a bit of guess work and investigation, digging into e.g. the `docker-compose` example.

With the snippet above, the goal would be "aha, I need a user and a DB, and just set the env variable, changing out these parts for my own".

**Comment by ammario** [comment]
@mafredri, your reasoning makes sense to me, and I agree with having minimal docs like the one you proposed.

**Comment by mtojek** [comment]
I'm looking into this now.
