### ISSUE TITLE
Edit schedule button doesn't change workspace stop time.

### ISSUE THREAD

**Issue by cra1gg** [coder/coder#3509]
![image](https://user-images.githubusercontent.com/29941031/184662059-9f54f509-805b-4ca4-aeea-bcd81e4b3539.png)
The "Edit schedule" button here brings up the following menu:
![image](https://user-images.githubusercontent.com/29941031/184662124-3cf4caf8-285f-4eea-bf39-dc17931761b6.png)
When I set this to the maximum value (168 hours) and save, I get the following message:
![image](https://user-images.githubusercontent.com/29941031/184662222-8aa86325-d1da-4356-88e8-b00389ae37a9.png)
but the "Stops at" at the top of the page remains at the same 2 hours as before and is not edited to reflect the 168 hours I set:
![image](https://user-images.githubusercontent.com/29941031/184662333-df4421c8-a0ef-456c-bf75-931006dd18ce.png)

This is on an edited version of the kubernetes template. I searched the issues and did not find an existing issue for this. Am I doing something wrong? Also is it possible to set a default workspace time in the template that is more than 2 hr?

**Comment by kylecarbs** [comment]
Our language isn't obvious here, but the time until shutdown adjusts *after* the next start occurs. We will fix this though, as it certainly lacks clarity!

**Comment by cra1gg** [comment]
Thanks for the quick reply, that makes sense. Are there any plans for allowing a default workspace time longer than 2 hours in the terraform template?
