### ISSUE TITLE
Agent status is 'connecting' after workspace has been stopped using an AWS template

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3510]
## User Statement
As a user, I would like to have agent statuses that reflect the reality of agent state.

## Background
When I use a workspace created from an AWS template and then I stop that workspace, the agent for that workspace is still returned from the BE. This may be by design (is it?) but I would not expect that agent status to be 'connecting'. The status is 'connecting' every time I stop a workspace, regardless of the previous status. So while this bug is related to #3511, it is not the same. Please see below screenshot:
![Screen Shot 2022-08-15 at 11 39 31 AM](https://user-images.githubusercontent.com/19142439/184681879-507f705f-2405-4058-ba2e-5a271a586380.png)

Related to #3484 
Related to #3511

## Definition of Done
When a workspace is stopped
then the agent returned from our API should not return with status 'connecting'.

**Comment by kylecarbs** [comment]
@Kira-Pilot is this the same as #3484?

**Comment by Kira-Pilot** [comment]
@kylecarbs No, but it is related to it (will add the link in a second). Investigating that ticket with @bpmct unfurled two other issues which I am creating tickets for now.

**Comment by kylecarbs** [comment]
Fixed by #3625
