### ISSUE TITLE
Agent hangs on 'connecting' when deploying using local docker

### ISSUE THREAD

**Issue by AadamZ5** [coder/coder#3513]
When deploying with the docker template, it seems the container can not download the required dependencies.

Container log:
```bash
+ trap waitonexit EXIT
+ mktemp -d -t coder.XXXXXX
+ BINARY_DIR=/tmp/coder.riHRwV
+ BINARY_NAME=coder
+ BINARY_URL=http://127.0.0.1:3000/bin/coder-linux-amd64
+ cd /tmp/coder.riHRwV
+ :
+ status=
+ command -v curl
+ curl -fsSL --compressed http://127.0.0.1:3000/bin/coder-linux-amd64 -o coder
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
+ status=7
error: failed to download coder agent
       command returned: 7
Trying again in 30 seconds...
+ echo error: failed to download coder agent
+ echo        command returned: 7
+ echo Trying again in 30 seconds...
+ sleep 30
```

This repeats and it can never reach the host network. Running on `linux x86_64` 

I can reach the host address from outside of the container (on the host itself) and the url path gives me a file to download. Seems like the container can't reach host. 

```bash
> coder version
Coder v0.8.5+95f26f7 Wed Aug 10 16:30:46 UTC 2022
https://github.com/coder/coder/commit/95f26f74b6ff6be1ffe42fceb21f70219889dc99
```

**Comment by kylecarbs** [comment]
@AadamZ5 the container is attempting to dial `localhost`, which can only reach inside the container.

You'll have to use the Docker host gateway to access port 3000 on your host machine from inside the container:

https://github.com/coder/coder/blob/2306d2c709e91cfa2c7e21d25f7b1c3857f43391/examples/templates/docker/main.tf#L76-L83

**Comment by AadamZ5** [comment]
@kylecarbs I agree. However, is this something I have to manually edit in a template? How come the default docker template does not connect to the Coder instance correctly?

**Comment by kylecarbs** [comment]
Agreed. I'll fix this up!

**Comment by bpmct** [comment]
Thanks for reporting, at one point I think Coder always identified localhost as 127.0.0.1 in the access URL, but this behavior must have changed.

**Comment by bpmct** [comment]
Thanks for reporting, at one point I think Coder always identified localhost as 127.0.0.1 in the access URL, but this behavior must have changed.

**Comment by kylecarbs** [comment]
https://github.com/coder/terraform-provider-coder/pull/37

Once this is merged, we can fix up the template to no longer replace the host :sunglasses:

**Comment by kylecarbs** [comment]
That change wasn't sufficient, but this one will be! https://github.com/coder/terraform-provider-coder/pull/40
