### ISSUE TITLE
Agent hangs on 'connecting' when deploying using code-server docker template

### ISSUE THREAD

**Issue by AadamZ5** [coder/coder#3514]
This is almost identical to #3513 but the container is using a different URL to try and reach the host. This is with the `docker-code-server` template.

Container log:
```bash
+ trap waitonexit EXIT
+ mktemp -d -t coder.XXXXXX
+ BINARY_DIR=/tmp/coder.zDnaVV
+ BINARY_NAME=coder
+ BINARY_URL=http://host.docker.internal:3000/bin/coder-linux-amd64
+ cd /tmp/coder.zDnaVV
+ :
+ status=
+ command -v curl
+ curl -fsSL --compressed http://host.docker.internal:3000/bin/coder-linux-amd64 -o coder
curl: (7) Failed to connect to host.docker.internal port 3000: Connection refused
+ status=7
+ echo error: failed to download coder agent
+ echo        command returned: 7
+ echo Trying again in 30 seconds...
+ sleep 30
error: failed to download coder agent
       command returned: 7
Trying again in 30 seconds...
+ :
+ status=
+ command -v curl
+ curl -fsSL --compressed http://host.docker.internal:3000/bin/coder-linux-amd64 -o coder
curl: (7) Failed to connect to host.docker.internal port 3000: Connection refused
+ status=7
+ echo error: failed to download coder agent
+ echo        command returned: 7
+ echo Trying again in 30 seconds...
+ sleep 30
```

Similar to the related issue, the container can't reach the host network. However, this container is using the `host.docker.internal` URL instead of `127.0.0.1` like in #3513. I'm not quite sure why `host.docker.internal` is not working, since it should be a bound host name in the container. Just looking now, [this documentation](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host) says that this is for development features only, and will not work outside of docker desktop. Potentially the problem?

```bash
> coder version
Coder v0.8.5+95f26f7 Wed Aug 10 16:30:46 UTC 2022
https://github.com/coder/coder/commit/95f26f74b6ff6be1ffe42fceb21f70219889dc99

```

**Comment by kylecarbs** [comment]
Closing in favor of #3513
