### ISSUE TITLE
docs: LetsEncrypt/ZeroSSL TLS on Docker, VMs, and Kubernetes

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3518]
## Problem statement

We do not document how to install Coder with a reverse-proxy/TLS to securely use Coder (e.g. with LetsEncrypt)

## Definition of done

We have published docs for LetsEncrypt/ZeroSSL certificates on:

- Reverse-proxy TLS for Coder on docker-compose
- Reverse-proxy TLS for Coder on Kubernetes (Helm)
- Reverse-proxy TLS for Coder on VM (nginx or Caddy)

Notes from call with @sharkymark 🦈 

- add sentences why subdomains are important for port forwarding
- add full Caddyfile example with LetsEncrypt wildcard (explain why you need to rebuild Caddy)
- add full cert-manager example with LetsEncrypt wildcard (explain what Issuer, Certificate, Secrets do)
  -  let's just use the Helm-based cert-manager

**Comment by matifali** [comment]
And of we using a Dockerfile and coker-ce?

**Comment by forrest-bajbek** [comment]
I used Caddy to make a reverse proxy, and it works fine for Coder itself. But I can't connect to workspaces after I create them. I tried isolating Coder to its own external bridge network (coder_frontend) and adding `networks_advanced { name = "coder_frontend" }` to the `docker_container` resource. But no dice.

If someone is willing to help me make it work, I'd be more than happy to write docs for it :)

**Comment by bpmct** [comment]
@forrest-bajbek are you setting a `CODER_ACCESS_URL`? 

https://coder.com/docs/coder-oss/latest/admin/configure#access-url

**Comment by bpmct** [comment]
We have docs for Caddy now: https://github.com/coder/coder/tree/main/examples/web-server/caddy

**Comment by forrest-bajbek** [comment]
I figured it out. You're correct, I wasn't using the correct value for `CODER_ACCESS_URL`. Thanks for making the Caddy examples. I'll take a look and see if there's anything I can add.

**Comment by bpmct** [comment]
Oops, re-opening until we have cert-manager docs

**Comment by matifali** [comment]
Bump

**Comment by bpmct** [comment]
Closing. Gonna make a cert-manager specific issue for the rest.

**Comment by matifali** [comment]
Is cerbot a cert-manager?

**Comment by bpmct** [comment]
it's cert-manager for kubernetes
