### ISSUE TITLE
Autogenerated docs for REST API

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3522]
Currently, you can examine [./codersdk](https://github.com/coder/coder/tree/main/codersdk) to see the various REST API queries supported by Coder. If you're interested in official documentation for the REST API (like [similar to our approach for Coder Classic](https://apidocs.coder.com)), please leave upvote this issue or [contact us](https://github.com/coder/coder). 

@mtojek:

Track progress

**OSS**

`/api/v2`:
- [x] `/` https://github.com/coder/coder/pull/5493
- [x] `/csp/reports` https://github.com/coder/coder/pull/5493
- [x] `/buildinfo` https://github.com/coder/coder/pull/5493
- [x] `/updatecheck` https://github.com/coder/coder/pull/5493
- [x] `/config/deployment` https://github.com/coder/coder/pull/5506
- [x] `/audit` and `/audit/testgenerate` https://github.com/coder/coder/pull/5506
- [x] `/files` https://github.com/coder/coder/pull/5506
- [x] `/parameters` https://github.com/coder/coder/pull/5506
- [x] `/authcheck` https://github.com/coder/coder/pull/5477
- [x] `/applications` https://github.com/coder/coder/pull/5477
- [x] `/workspaceagents` (~11 methods) https://github.com/coder/coder/pull/5538
- [x] `/workspacebuilds/{workspacebuild}` (~5 methods) https://github.com/coder/coder/pull/5538
- [x] `/workspaces` (~9 methods) https://github.com/coder/coder/pull/5383 https://github.com/coder/coder/pull/5538
- [x] `/templates/{template}` (~7 methods) https://github.com/coder/coder/pull/5383 https://github.com/coder/coder/pull/5546
- [x] `/templateversions/{templateversion}` (~11 methods) https://github.com/coder/coder/pull/5546
- [x] `/organizations` (~12 methods) https://github.com/coder/coder/pull/5383 https://github.com/coder/coder/pull/5546
- [x] `/users` (~23 methods) https://github.com/coder/coder/pull/5620

**Enterprise**

`/api/v2`: https://github.com/coder/coder/pull/5625
- [x] `/entitlements` (1 method)
- [x] `/replicas` (2 methods)
- [x] `/licenses` (4 methods)
- [x] `/organizations/{organization}/groups` (3 methods)
- [x] `/organizations/{organization}/provisionerdaemons` (2 methods)
- [x] `/groups/{group}` (3 methods)
- [x] `/workspace-quota` (1 method)
- [x] ~~`/service-banner`~~ `/appearance` (2 methods)
- [x] `/scim/v2` (6 methods)

**Validation**
- [ ] https://github.com/coder/coder/pull/5694

**UI improvements**
- [x] https://github.com/coder/coder/pull/5567 [Authentication](https://coder.com/docs/coder-oss/latest/api/authentication) page: explain how a user can generate tokens, link with [automation](https://coder.com/docs/coder-oss/latest/admin/automation#tokens) page

**Other**
- [x] https://github.com/coder/coder/pull/5590

**Comment by kylecarbs** [comment]
The [godoc reference](https://pkg.go.dev/github.com/coder/coder@main/codersdk) has a pretty nice view too!

**Comment by Emyrk** [comment]
At some point we'll have to nail down our apis and version them properly

**Comment by bpmct** [comment]
GitLab has nice auto-generated documentation for their CLI as well. https://glab.readthedocs.io/en/latest/completion/index.html

**Comment by mtojek** [comment]
Looking into this

**Comment by mtojek** [comment]
I checked possible options and unfortunately, the best approach seems to be tagging API operations via [Go comments](https://github.com/swaggo/swag#declarative-comments-format) and generating OpenAPI/swagger description with [swag](https://github.com/swaggo/swag).

An alternative approach is the [chi-go/docgen](https://github.com/go-chi/docgen) (official project?), which is supposed to generate Markdown/Swagger directly from chi Router, but it isn't aware of request/response entities and status codes + it leaves a lot of noise (Recover, Middleware, Logger, Prometheus, etc.).

<img width="783" alt="Screenshot 2022-12-09 at 14 01 42" src="https://user-images.githubusercontent.com/14044910/206711332-b74e26d2-d620-4e5a-893e-657a0b4ac495.png">

Once we have the swagger description ready, we can generate the Markdown file with [widdershins](https://github.com/Mermade/widdershins). I'm not sure about the visual effect, but it looks [promissing](https://speckleworks.github.io/SpeckleSpecs/#streamcreate).

**Comment by Emyrk** [comment]
> I checked possible options and unfortunately, the best approach seems to be tagging API operations via [Go comments](https://github.com/swaggo/swag#declarative-comments-format) and generating OpenAPI/swagger description with [swag](https://github.com/swaggo/swag).

I would warn about this approach. We did this in v1 and the auto generated SDK's are not ideal. Then the comments and the code go out of sync if you don't use the SDK.

> An alternative approach is the [chi-go/docgen](https://github.com/go-chi/docgen) (official project?), which is supposed to generate Markdown/Swagger directly from chi Router, but it isn't aware of request/response entities and status codes + it leaves a lot of noise (Recover, Middleware, Logger, Prometheus, etc.).

I have used a tool in the past where it looks at the request/response from our unit tests to generate docs. I wonder if we can auto gen this from our SDK, not the routes.

Like maybe from our sdk functions won't be too bad to parse? 

func (c *Client) Upload(ctx context.Context, contentType string, content []byte) (UploadResponse, error) {

**Comment by mtojek** [comment]
Thanks for the good chat, @Emyrk and @johnstcn! I will go the standard way (`@comment`) but will implement a linter/validator. In the end, we could detect outdated undocumented API functions, wrong HTTP methods, and missing fields in request entities.

**Comment by mtojek** [comment]
Ok, time for part 2.

> will implement a linter/validator. In the end, we could detect outdated undocumented API functions, wrong HTTP methods, and missing fields in request entities.

+ document other API methods.
