### ISSUE TITLE
Feat: create a helm chart for Open VSX OSS marketplace

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3530]
Part of the value of Coder OSS is VS Code in a browser aka Coder's code-server OSS.

As a developer, I would like my extensions to be automatically installed when my workspace builds. But I work in a large company or public institution that does not allow Internet access to Open VSX or Microsoft's Extension marketplace.

As a DevOps leader, I would like my Coder deployment to provide access to an internal extension marketplace like Open VSX OSS but I would like this to be easy to install like Coder and I want this as a helm chart to co-exist with my Coder deployment.

## Current Behavior
I have to figure out this complex process of installing and configuring Open VSX
https://github.com/eclipse/openvsx/wiki/Deploying-Open-VSX

## Expected Behavior
I have a helm chart or optional setting in Coder's set up to automatically set up the extension marketplace and point any code-server in a template to this internal marketplace.

**Comment by kylecarbs** [comment]
Closing in favor of coder/v1#12913
