### ISSUE TITLE
Consolidate template-wide metadata

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3531]
## Problem statement

We currently have template-wide metadata in 2 places and have a 3rd concept in Terraform (coder_metadata). When adding new features (e.g #2221) this makes things confusing.

1) `README.md`: YAML is currently appended to template READMEs, for use with `coder templates init`. This is already in the product. Here is an example:
    https://github.com/coder/coder/blob/4be61d9250512f85bc88ba9603928ca5ac706089/examples/templates/docker/README.md?plain=1#L1-L5

2) `coder templates edit`: We also have a way to apply metadata to templates via `coder templates edit` for the description and schedule controls. This was apparently done so we could "validate" the values easier.

    ```sh
    ➜  ~ coder templates edit --help
    Edit the metadata of a template by name.
    
    Usage:
      coder templates edit <template> [flags]
    
    Flags:
          --description string                Edit the template description
      -h, --help                              help for edit
          --max_ttl duration                  Edit the template maximum time before shutdown
          --min_autostart_interval duration   Edit the template minimum autostart interval
      -y, --yes                               Bypass prompts
    ````

3) `coder_metadata`: We have a way to attach metadata for specific resource blocks with [coder_metadata](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/metadata). The direct link to Terraform resources is necessary, hence it is done in the `.tf` file.

    https://github.com/coder/coder/blob/4be61d9250512f85bc88ba9603928ca5ac706089/dogfood/main.tf#L52-L60
    
    <img width="380" alt="Screen Shot 2022-08-17 at 9 15 19 AM" src="https://user-images.githubusercontent.com/22407953/185157104-405344c6-c9dd-4c2b-aa97-0787530829f2.png">

## Definition of done

Template-wide metadata is only in one place.

## Ideas

<details>
  <summary>Postponed: use the upcoming `template.yaml` for all template-wide metadata. Use `coder_metadata` for workspace and resource-wide metadata.
</summary>
  
---

We are considering a `template.yaml` file, which includes YAML-based metadata: #2987 

This would consolidate metadata from the `README.md` (1) and from `coder templates edit` (2). 

```yaml
version: 1
name: dogfood
description: "Our standard dogfood image"
schedule:
  max_ttl: 12h
  min_autostart_interval: 24h
# Some future knobs
deprecated_for: "dogfood-ts"
allow:
   - all
deny:
   - dean@coder.com
icon: /icons/dog.png
```

`coder_metadata` (3) can remain in the Terraform for workspace-scoped and resource-scoped metadata since it may rely on dynamic values from Terraform. However, it is not used for things in the template-wide or in the templates page (description, icon, TTL, etc):

```diff
resource "coder_metadata" "template" {
-   resource_id = ""
+   workspace_wide = true;
 item {
    key = "Workspace broken?"
    value = "[Create Ticket](https://internal-support.com/tickets/new/?type=coder&workspaceid=${data.coder_workspace.me.id}"
 }
    quicklinks = "Run workspaces on a Docker host using registry images"
 }
 ```
</details>

✅ Solution discussed by @bpmct @BrunoQuaresma @kylecarbs: Manage metadata via CLI (`coder templates edit`) and "Edit Template" page in the dashboard. Remove metadata from README entirely. This follows the model of GitHub and Vercel where some properties are just "editable"

Resource and workspace metadata will be used by `coder_metadata`

<img width="300" alt="Screen Shot 2022-08-17 at 11 21 49 AM" src="https://user-images.githubusercontent.com/22407953/185194667-1d7ffe7f-a9b8-4490-a5da-17b8f5443a57.png">
<img width="300" alt="Screen Shot 2022-08-17 at 11 21 15 AM" src="https://user-images.githubusercontent.com/22407953/185194669-a499006e-2e6f-4147-ba29-31c07f3e2729.png">

This will make our dashboard more interactive and make these features feel more fun and easy to use. Down the road, `template.yaml` (#2987) can be used to "disable" manual editing by admins so that it's managed as a part of GitOps.

**Comment by bpmct** [comment]
If #2987 is in a roadmap or we land on another solution, we can close this issue.

**Comment by kylecarbs** [comment]
Global metadata is an interesting idea... so then we'd remove any option to specify a description or icon in the API I'd suppose since they'd be attached to a template.

I'd like to keep all of this as Terraform-centric as possible in the immediate. Could we just do these metadata values in that same way?

eg.

```tf
resource "coder_metadata" "template" {
  item {
    key = "icon"
    value = "/icon/code.svg"
  }
}
```

**Comment by phorcys420** [comment]
i'm all in for cli-manageable, but would there be a way for this to persist if you want to use the tempalte elsewhere? (even though this would probably not happen a lot)
I prefer the ``coder_metadata`` in the Terraform file, but I'm all fine with CLI too.

**Comment by ketang** [comment]
I think we want to be careful here to distinguish between the source of truth and methods for editing the source of truth.  I think for the most part (exceptions noted below), there should be one canonical source of truth as described above.  However, we should allow multiple ways of editing the source of truth.  I see the plurality of methods listed above (as well as additional, hypothetical methods) as a feature, *assuming we implement them in an organized fashion*.  By analogy, think of tools like `bash` that allow you to set aliases or environment variables in multiple ways whether in a file like `.bashrc` or explicitly on the command line, or how `git` supports `/etc/gitconfig`, `~/.gitconfig`, `$REPO/.git/config`, environment variables, and command-line arguments to set metadata.  To the extent possible, we should allow any method to set any metadata (subject to authorization etc.) using consistent names and idioms (one exception below).

An additional axis is delineating different concepts.  Some concepts are Coder concepts, like schedules.  Others are specific to a provisioner (currently only Terraform).  Those should live in different places, both in the internal implementation and in how they're exposed to users.  In many cases the distinction can be achieved by simple methods like namespacing, though that won't always be the case, so we may have to have two separate, disjoint sources of truth in some cases.

Finally, we may want to distinguish between functional metadata and descriptive metadata.  For instance, the metadata pulled out of `README.md` shouldn't ever be functional in nature.

**Comment by ketang** [comment]
#3536 needs to be made coherent with this.

**Comment by bpmct** [comment]
Gonna close this for now. We're only using the README stuff for `coder templates init` and will probably be changing that flow soon
