### ISSUE TITLE
helm: add Coder to a hosted Helm repository

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3545]
A prospect evaluating Coder v1 and Coder OSS is not happy with OSS because it is not obvious how to install the control plane with Helm. 

I directed them to the helm chart and said we are working on a more-enhanced version.

This should be documented better.

**Comment by ketang** [comment]
Where were they expecting to find this guidance?

**Comment by kylecarbs** [comment]
Requirements:

- User can `helm install ...` Coder!
- This command is discoverable via the docs!

**Comment by ElliotG** [comment]
For the record, the following does work. Not sure if that helps.

`resource "helm_release" "coder" {
  name       = "coder"
  namespace  = kubernetes_namespace.coder_namespace.metadata.0.name
  
  chart      = "https://github.com/coder/coder/releases/download/v${var.coder_version}/coder_helm_${var.coder_version}.tgz"

  values = [...]`
