### ISSUE TITLE
Not obvious how to see the currently deployed version of a `template`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3546]
A prospect who has evaluated v1 and Coder OSS reports that they prefer v1 because in OSS, it is not obvious how to see the deployed version of a template.

I directed them to the `coder templates pull` command but this is very good feedback to either document better or analyze how we position and explain templates to administrators.

i.e., are we creating a black box once templates are deployed inside of Coder?

**Comment by ketang** [comment]
Yeah, I think I see the problem.  Should be an easy fix
![image](https://user-images.githubusercontent.com/33678/185422622-0a013cec-b428-4be5-8082-1e76840b3a6d.png)

**Comment by ketang** [comment]
This also prompted the idea for #3549.  Do you think that would be sufficient to address the need?
