### ISSUE TITLE
Show workspace metadata when starting a terminal

### ISSUE THREAD

**Issue by ketang** [coder/coder#3549]
When a user launches a web terminal or logs in via `ssh`, we should print out some metadata about the workspace:
![image](https://user-images.githubusercontent.com/33678/185423653-a09f3be1-ddd9-4578-a6f2-7ef916cadfde.png)

**Comment by mafredri** [comment]
Here are some more thoughts on the topic.

Would we always show the message? Or do we want admins to be able to control the message?

How would we expose dynamic functionality (for admins)? Setting in WebUI? Env variables in workspace? Maybe we could tap into existing functionality like `motd` used by OpenSSH? (E.g. Debian systems have scriptable motd via `/etc/update-motd.d/01-message.sh`, content could be `echo $CODER_WORKSPACE_NAME ...`.)

We could also let users silence the message via `~/.hushlogin` (`man login`) as they may be used to that with OpenSSH.

**Comment by ketang** [comment]
I think those are good questions, but perhaps addressing them is a later iteration.  I think just doing the initial idea and adding your `~/.hushlogin` idea gets us a clear step ahead of status quo.  Then customer feedback will no doubt provide additional guidance if needed.

Your note of `~/.hushlogin` reminded me about `/etc/motd`, which suggests a path forward.  We can define a default `motd` template that is able to understand variables like template name or whatever and allow customers to customize or override it.

.... although this may not be portable to other operating systems hmmm 🤔

**Comment by mafredri** [comment]
>  I think just doing the initial idea and adding your `~/.hushlogin` idea gets us a clear step ahead of status quo.

This sounds good to me. 👍🏻

On the (future) topic of a customizeable motd, perhaps we should just define it in the Terraform template, i.e.:

```
resource "coder_agent" "main" {
  motd = "Welcome to Coder: workspace ${data.coder_workspace.me.name}"
}
```

I'm not sure if we have access to all the suggested variables in the template, but for increased customizability this could be `motd_script = ["/path/to/script/in/workspace.sh"]`. It could even work as an only option (skip plain `motd`), via `motd_script = ["/bin/sh", "-c", "echo Welcome to ..."]`

**Comment by ketang** [comment]
It might be that doing it in the Terraform template is the only sane way to get around the portability issue.  However that does then fragment the experience in the future where we support more than just Terraform.  This will take some thought, but given the lack of customer requests for this, that thought can wait.

Small naming note: *motd* is a very specific term that I think is appropriate to use if we're using the actual `motd` infrastructure, but if we're not, then we should use something less jargony and less Linuxy, e.g. "shell login message" or something boring like that.

**Comment by kylecarbs** [comment]
I don't think we should mutate the user's filesystem. It's not extremely ~unixy.
