### ISSUE TITLE
Investigate using Microsoft's code-server in a template

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#3553]
## Description

Last month, Microsoft released [Visual Studio Code Server](https://code.visualstudio.com/docs/remote/vscode-server). It is a standalone VS Code essentially (same as our code-server). If we can use it with coder and have the same functionality that code-server has, then we can encourage folks to use that instead.

This would be better because it be more up-to-date with VS Code releases and be able to use the official extension marketplace.

### What is the goal of this spike?

Spend 1-2 hours investigating the use of vs code-server

### What should be the outcome?

Information telling us if: 
- vs code server can served as an app i.e. `https://dev.coder.com/@jsjoeio/joe-coder/apps/code-server/?folder=/home/coder`
- it has the same functionality as code-server (TBD, elaborate on this criteria)
- docs on how to use this and differences compared to code-server (Coder's)

**Comment by kylecarbs** [comment]
An output of this would be adding a page to our docs for this!

**Comment by jsjoeio** [comment]
Not stale

**Comment by jsjoeio** [comment]
May be worth revisiting: https://code.visualstudio.com/docs/remote/vscode-server

**Comment by bpmct** [comment]
I couldn't find a way to run this locally without using Microsoft's reverse proxy. Going to close for now
