### ISSUE TITLE
Add option message prop to FullScreenLoader

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#3554]
ref: https://github.com/coder/coder/pull/3532#discussion_r949369616_

# Problem:

We currently don't have any way to show specific loading steps in `FullScreenLoader` (e.g. "Reticulating Splines").

# Solution

Add a prop to `FullScreenLoader` to allow setting an optional message. The default will be something like "Loading..."

**Comment by BrunoQuaresma** [comment]
@johnstcn where in the current UI do you think this would be well used?

**Comment by johnstcn** [comment]
> @johnstcn where in the current UI do you think this would be well used?

Originally I was thinking it would be good to show "Loading Workspace..." and then "Loading Template..." in `<WorkspacePage>`, but it could be good to show any time we are asynchronously loading a resource.

**Comment by BrunoQuaresma** [comment]
Ahh, I see.  In this case Idk if let the user know what the app is loading could be helpful. I'm closing this for now until we receive user feedback related to this.
