### ISSUE TITLE
Show empty resources table immediately after initiating build

### ISSUE THREAD

**Issue by ketang** [coder/coder#3562]
Scenario: when I click "Start," it's not obvious that there's stuff in the UI that's going to appear when startup happens.  It's perhaps a little too minimal:

![image](https://user-images.githubusercontent.com/33678/185480703-a74ac0b9-9e87-4a37-a5de-83d4d9aa5694.png)

I think it might be better to immediately show the resources table with some kind of "stuff is happening" indicator like a clock or ... or something:
![image](https://user-images.githubusercontent.com/33678/185481791-5606ab9f-54c8-4ba1-8715-8a84c710326c.png)

Ridiculously-sized spinners are just for clarity not actually a proposal.

**Comment by mafredri** [comment]
This would be a nice addition.

To expand: I had a though when working on an Alfred workflow for Coder: If I want to spin up a workspace “on access”, how do I determine what resources (agent, apps) are available to that workspace when it is stopped?

I’m not sure what the answer is, and it might depend in the terraform template. But most of the time resources are the same for the same version of a template. Is it OK to trust the values of a previous build? Or should we figure out a way to know this ahead of time? If we can, it would be nice to display them in the WebUI as well as the workspace is starting.

**Comment by ketang** [comment]
I'm pretty hesitant to try to fill in the contents here other than the single workspace row.  It's too easy to be wrong.  That's why I stopped at some kind of empty placeholder rather than trying to shoot for something more sophisticated.

**Comment by mafredri** [comment]
I definitely agree, and I think your suggestion is good as-is. I didn't intent to increase the scope of this suggestion, just wanted to put that thought out there (because it seems like something we may want to figure out.. some day).

**Comment by kylecarbs** [comment]
I don't think this is high priority for now. Unless more people ask for it, I'm going to close it out!
