### ISSUE TITLE
Security: Guidance for working with secrets

### ISSUE THREAD

**Issue by bryphe-coder** [coder/coder#357]
As a customer, I want to be able to leverage my internal infrastructure safely and securely. On any of my private clouds, I'll have access keys that are important to keep secure. These may be necessary to provision items (ie, an `AWS_ACCESS_TOKEN`), but I want them to be safely used and minimize the potential security impact.

On the implementation side, we'll need to be careful to consider cases where customers _think_ they are doing the right thing (ie, using Vault), but then saving the output to a variable which is then stored in cleartext in the Terraform statefile, persisted in our db.

Specifically, we should mention and document best practices for securing data - for example, using 'Encryption as a Service' solutions like like [Vault `transit`](https://learn.hashicorp.com/tutorials/vault/eaas-transit). With a strategy like this, customers never have to store un-encrypted keys or data in their statefile - it would also be stored securely.

The deliverable for this would be a list of best-practices and examples we could document for customers to securely manage their keys and secrets.

**Comment by kylecarbs** [comment]
This seems to be pretty much completed in our docs. This was tracked in another issue, so I shall close with not planned!
