### ISSUE TITLE
Owner can't connect to other user's workspace with SSH

### ISSUE THREAD

**Issue by maryna-hankevich** [coder/coder#3583]
Coder version:
[Coder v0.8.5-devel+380022fe](https://github.com/coder/coder/commit/380022fe63d280e9bd22d8475db0da26444e2743)
Windows 10

User with Role = Owner has access to other user's workspaces via UI (Terminal and apps) but can't connect to those workspaces via CLI

Steps:
1. Log in as Owner
2. Go to other user's workspace
3. Make sure Terminal and other apps work fine
4. Try to connect to this workspace with SSH via CLI

**Actual Result:** error
_Resource not found or you do not have access to this resource.
Run 'coder ssh --help' for usage.
ssh_exchange_identification: Connection closed by remote host_
![image](https://user-images.githubusercontent.com/35501151/185599516-aa19d74c-698a-459d-ad95-10dd932563b7.png)

**Expected Result:** connected

**Comment by mafredri** [comment]
The reason this is not working as expected is that `coder config-ssh` only generates a list for the users own workspaces. Meaning `~/.ssh/config` is outdated in this case and `coder config-ssh` should be re-run between logins.

After running `coder config-ssh` you should see:

```
ssh: Could not resolve hostname coder.test4.main: nodename nor servname provided, or not known
```

The `coder ssh` command would work like expected, i.e. this should work for `user1`:

```
coder ssh maryna/coder.test4.main
```

**Comment by mafredri** [comment]
Since this is working as-intended, closing in favor of #3584.
