### ISSUE TITLE
Why do Coder's `aws` templates not use the AWS Terraform provider?

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3585]
As a user, I like consistency across templates. My Google Cloud templates use a Google Terraform provider. But I noticed Coder's example AWS templates do not.

Why?

https://registry.terraform.io/providers/hashicorp/aws/latest/docs

<img width="457" alt="image" src="https://user-images.githubusercontent.com/2022166/185617818-3e089c79-1809-4723-bfd6-d6109d6118af.png">

**Comment by kylecarbs** [comment]
Our AWS templates do use their provider!
