### ISSUE TITLE
kubernetes pods template loses all data on shutdown

### ISSUE THREAD

**Issue by ammario** [coder/coder#3588]
A user reported an issue where they lost all of their "pip installs" when the workspace rebooted.

Our k8s template today [is completely ephemeral](https://github.com/coder/coder/blob/main/examples/templates/kubernetes-multi-service/main.tf), but we should probably make the home mount persistent to match v1 behavior better, show the power of Coder, and avoid a negative surprise.

**Comment by ketang** [comment]
How does this differ from #3596 ?

**Comment by ammario** [comment]
It's a more specific version of the problem, but I think we can close this in favor of that #3596.
