### ISSUE TITLE
Explain the persistence model in our docs

### ISSUE THREAD

**Issue by ammario** [coder/coder#3589]
Per https://github.com/coder/coder/issues/3588, a user reported confusion about Coder's overall persistence model. @endingwithali also found it unclear after reading our docs.

**Comment by bpmct** [comment]
We have a [tiny section](https://coder.com/docs/coder-oss/latest/templates#persistent-vs-ephemeral-resources) that needs a lot of expansion. 

Since these docs are fundamental to how Coder works, we should probably mention in the About page too (the home page for https://coder.com/docs/coder-oss)
