### ISSUE TITLE
Sign Windows CLI

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#359]
**Acceptance Criteria**
As a user, I want the Coder CLI on Windows signed because of organization security policy and peace of mind that the CLI is secure.

Use [osslsignencode](https://github.com/mtrojnar/osslsigncode) to sign the Windows binary on Linux during release.

This is NOT the extended validation version. 

Edit (04.18.24): We want to do extended validation as well

Edit: See https://github.com/coder/coder/issues/359#issuecomment-2073368263 for game plan

**Comment by kylecarbs** [comment]
https://github.com/cli/cli/blob/ebcf3a10225a9b7c9422f6b63ff798d695f7f0a2/.github/workflows/deployment.yml#L187-L196

**Comment by bpmct** [comment]
Kyle wants this :)

**Comment by michaelbrewer** [comment]
@kylecarbs - i just noticed this on windows machines that want to use VSCode Desktop, as it fails to run the coder cli. Hopefully this fixes this issue!

**Comment by bpmct** [comment]
Slotting this in as a candidate for our next sprint as several folks need this as a long-term solution for rolling out Coder to Windows users.

**Comment by kylecarbs** [comment]
Seems like the GitHub CLI does this pretty cleanly now: https://github.com/cli/cli/blob/c465d465a5c60dae4e4759b4383292dab3f77504/.github/workflows/deployment.yml#L136

**Comment by bpmct** [comment]
Game plan: 

- [ ] Test whether Google Cloud HSM can sign Windows artifacts with a self-signed cert (needs owner)
- [ ] Pick a vendor or tool we feel good with and begin paperwork (needs owner + operations help)
- [ ] Modify our CI pipeline to sign Windows binaries

**Comment by michaelbrewer** [comment]
- [ ] Beers 🍻

**Comment by michaelbrewer** [comment]
@kylecarbs  i think we need some instructions on how to allow for these new signed exes in tools like Cyberark. So far this is not working

**Comment by sreya** [comment]
@michaelbrewer could you elaborate on what's not working?

**Comment by michaelbrewer** [comment]
Unfortunately i don't have a windows machine or am the person responsible for approving signed exe. But users are still getting an Application Blocked error

**Comment by michaelbrewer** [comment]
@kylecarbs  @sreya  - looks like it was signed as `Coder Technologies Inc.` and previous `Coder Technologies Inc`. 

In the future exactness matter :)

**Comment by kylecarbs** [comment]
@michaelbrewer is all working now after that change?

**Comment by michaelbrewer** [comment]
No unfortunately it is still being flagged and blocked by CyberArk. I am not sure how to resolve this. We tried both names.
