### ISSUE TITLE
Indicate which resources are ephemeral in the CLI/UI

### ISSUE THREAD

**Issue by ammario** [coder/coder#3596]
At least one user has reported frustration that when their workspace restarted, all of their data went missing. While we could solve this with some explicit `ephemeral` flag, a more powerful approach is adding a `description` field to each resource via `coder_metadata`. For example:

```hcl
resource "coder_metadata" "deployment" {
  count = data.coder_workspace.me.start_count
  resource_id = kubernetes_deployment.coder[0].id
  description = "⚠️ The pod filesystem deletes on shutdown"
  item {
    key = "name"
    value = kubernetes_deployment.coder[0].metadata[0].name
  }
}
```

cc @dwahler, @bpmct, and @BrunoQuaresma.

**Comment by bpmct** [comment]
I like doing this via metadata!

**Comment by bpmct** [comment]
We could also include a `/etc/motd` in images to share that any software installed is removed on restart.
