### ISSUE TITLE
Missing padding on dropdown button

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#3600]
Identified by @presleyp while reviewing https://github.com/coder/coder/pull/3555

## Steps to reproduce
1. create workspace
2. start workspace
3. click drop down next to "Stop"
4. click and hold item in dropdown menu
5. observe error

### expected

button shadow should have padding

### Actual

padding is missing from button shadow

### Screenshot

![msising](https://user-images.githubusercontent.com/3806031/185669783-0ea2d567-8b05-4bb7-b1b7-b0cd8e5d1277.jpg)

**Comment by BrunoQuaresma** [comment]
@jsjoeio I think this is fixed 🤔 can you confirm?

**Comment by jsjoeio** [comment]
Yes! I can't reproduce. Thanks for following-up!
