### ISSUE TITLE
Implement the rest API for audit logging

### ISSUE THREAD

**Issue by misskniss** [coder/coder#3606]
## Problem
We need a few Audit log endpoints to complete the new Audit log feature 

- [ ] /api/v2/audit
- [ ] /api/v2/audit/count
- [ ] /api/v2/feature/audit_log

## Definition of Done
The Endpoints are implemented as defined in the RFC and do not leave questions for the FE implementations.

**Comment by kylecarbs** [comment]
There are already issues for this!
