### ISSUE TITLE
Allow all users with audit logs to view audit log page

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#3610]
As a user who once had audit log licensing enabled but now does not, I would still like to be able to see my old audit logs.

## AC

- [ ] Using the audit log count API, ensure that users with any audit logs at all can still access the audit log page
- [ ] Use the count API (`/api/v2/audit/count`) to return the logs available
- [ ] Add tests

## Definition of Done
When there are audit logs
then I can access the audit log page

**Comment by BrunoQuaresma** [comment]
More info: https://codercom.slack.com/archives/CJURPL8DN/p1662582806975149
