### ISSUE TITLE
bug: I mistakenly updated `push` a template as a different admin user, then updated a workspace, which brick-failed

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3624]
Version: [`v0.8.5+95f26f7`](https://github.com/coder/coder/commit/95f26f74b6ff6be1ffe42fceb21f70219889dc99)

I have a working template and workspace under one user, say `admin.`

Then I created a new user `mark` who is an admin. With this user, I created a workspace based on that same template. 

From the same computer, I made a template change and `pushed` the new template.

I updated the `mark` workspace, and it failed. I cannot delete it. It fails too. So I manually deleted the workspace row from the db and manually deleted the VM from Azure.

**Comment by sharkymark** [comment]
Key point here is that as the `mark` admin user, I changed a template created by the `admin`, which seems to be the condition right before failing to update a workspace.

**Comment by matifali** [comment]
So maybe only the template owner should be allowed to push.

**Comment by kylecarbs** [comment]
Anyone that has permissions should be allowed to push IMO. I think this is mostly related to #2256. Closing for now.
