### ISSUE TITLE
scheduling: auto-stop limit can be bypassed by disabling auto-stop

### ISSUE THREAD

**Issue by ammario** [coder/coder#3630]
I can circumvent a template-level Auto-stop limit by disabling auto-stop on my workspace, removing much of the control value of the feature.

Related #3304

**Comment by matifali** [comment]
I think users should be allowed to increase the autostop time. Otherwise, an admin has too much power, which can cause work and productivity loss for workspace users. What if the admin is not around or not reachable, and they need to increase the time?

**Comment by ammario** [comment]
@matifali the control feature is optional and will just be in our product's enterprise (paid) version. In massive deployments, it's not feasible for admins to track down individuals that are spending too much, so they rely on this kind of end-to-end control.

**Comment by matifali** [comment]
I understand. But it should not be so in OSS version. I am an admin and volunteering to manage our groups servers. So I like to give users as much flexibility as they wish.

**Comment by ammario** [comment]
Reopened as needed by @kconley-sq

**Comment by ammario** [comment]
I'm not totally clear on why we changed the "max auto-stop" to default. A developer's incentive is to keep their machine on as long as possible, so to me this advice from the template doesn't seem to provide that much value. Why don't we have auto-stop max and also enforce that auto-stop is enabled if its set?

**Comment by bpmct** [comment]
Ah, we could just do that as well.

**Comment by bpmct** [comment]
@ammario In Coder v1, we had feature requests (and built a feature) to allow users to configure their own auto-stop behavior per workspace. Specifically, this customer wanted to enable data scientists to disable/set an auto-stop value for long-running jobs. However, they wanted to ensure that other workspaces, by default stop at a specific "default" time.

<img width="503" alt="Screen Shot 2022-12-04 at 4 27 02 PM" src="https://user-images.githubusercontent.com/22407953/205525245-b95169f9-4541-4bd0-8145-a13b98f77fa0.png">

I don't have strong opinions on whether we build this feature as a "default" or a "max," but we will still need to add an option to allow users (or specific groups) to override this behavior.  Another option is to use something like @mtojek's proposal for grants: #5106

**Comment by ammario** [comment]
I think grants is a lot of complexity for where we're at today. I think we should just use max (which can also be the default). I think that approach minimizes the number of configuration options.

**Comment by bpmct** [comment]
We still need the ability for a user to configure a custom auto-stop duration for their workspace. This was a feature we built for v1 use cases that will migrate to v2.

**Comment by ammario** [comment]
The user can always set an auto-stop duration that is less than the template max.

**Comment by ammario** [comment]
This should be a per-template setting.

**Comment by deansheather** [comment]
Closing in favor of #6047, which solves this problem by adding a "max template ttl" control for enterprise customers. This feature will enable template admins to force workspaces to turn off within a certain amount of time, even if the user wants it to stay on for longer.
