### ISSUE TITLE
Using resources & parameters across templates (Terraform modules?)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3634]
If you have multiple templates in a Coder deployment, you may want to offer some similar functionality across templates without maintaining essentially duplicate Code. 

-  [Installing & starting web IDEs](https://coder.com/docs/coder-oss/latest/ides/web-ides) across all templates via a shared `coder_agent.startup_script` output
- Use some of the same resources and variables (e.g. `api_key`, `persistant_volume`) across all templates.
- Use some of the same labels to all Coder-created resources 

[Terraform modules](https://www.terraform.io/language/modules/develop) is a great way to group resources, scripts, etc. so that you don't have to copy & paste configuration across multiple templates.

@bpmct hasn't validated these are all possible with modules. Hopefully they are!

**Comment by kylecarbs** [comment]
I think we need to wait for customer feedback to enact this. I'd feel uncomfortable abstracting without that input, so I'm closing for now.
