### ISSUE TITLE
Document "known" environment variables and how to use them

### ISSUE THREAD

**Issue by mafredri** [coder/coder#3638]
With #3637 merged (fixed #2340), we now have an environment variable: `CODER=true` that's available in all Coder workspaces.

We should document that this variable is available, and can be used for e.g. dotfiles customization.

```shell
if [[ $CODER == true ]]; then
    # Inside a Coder workspace.
    custom_coder_logic
fi
```

We may potentially want to expand the number of env variables we have and are documented, see #2340 for a discussion about potential variables to add.

For reference, here's how Codespaces document theirs: [Default environment variables for your codespace](https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace)

### Definition of done

The user can read Coder docs and find out about useful environment variables inside workspaces.

**Comment by disconn3ct** [comment]
Still a problem. A list of configuration variables does not seem unreasonable.
