### ISSUE TITLE
Disabling autostop from the workspace settings doesn't work

### ISSUE THREAD

**Issue by matifali** [coder/coder#3641]
Disabling autostop from the workspace settings page does not make any difference.
![image](https://user-images.githubusercontent.com/10648092/186160161-e70f18b6-e703-4ef7-952f-f343a7f4458f.png)

![image](https://user-images.githubusercontent.com/10648092/186160248-31bf672c-e298-4fae-a37a-3f543e90fb5e.png)

### Definition of done
Disabling autostop should display `auto-stop` is `off` or workspace stop set is manual

**Comment by ammario** [comment]
@matifali—what version are you on? I can't reproduce this on master.

**Comment by matifali** [comment]
I am on 0.8..6

**Comment by BrunoQuaresma** [comment]
@matifali looks like it is fixed in the newest version.  Please let me know if after upgrading it the issue remains I will be happy to reopen it if it is still an issue on your side.
