### ISSUE TITLE
docker run / docker-compose up fail on postgres connection refused

### ISSUE THREAD

**Issue by mro-msandford** [coder/coder#3644]
I'm reading and following the docs here: https://coder.com/docs/coder/latest/setup/coder-for-docker/local#installing-coder-for-docker

When I try and launch with docker on the command line I get no joy.
```
2022-08-23 13:08:24.263 [ERROR] <./product/coder/service/coderd/cmd/run.go:817> startEmbeddedPostgres.func1     postgres exited {"error": "exit status 1"}
Error: connect to postgres: retry failed because context canceled, last run error: connect to postgres: dial tcp 127.0.0.1:5433: connect: connection refused
```
Roughly the same thing happens when I try docker-compose up as well.  I have attempted this with versions 1.30.0, 1.31.0, 1.32.0, 1.32.3, 1.33.0, 1.33.3 and possibly a few others.  Since I don't know a ton about the internals of the coder server or how this image fires up I'm a bit at a loss as to where to go from here.

**Comment by kylecarbs** [comment]
@mro-msandford this is for the v1 version of our product, so this question would typically be answered in our [Community Slack](https://cdr.co/join-community). Have you tried running `sudo rm -rf ~/.coder`? That should clear any temp data that may result in this failing.

**Comment by mro-msandford** [comment]
Ah I see!  Thanks for clarifying.  I'll bring it up there.  I did try removing the .coder folder and it didn't resolve the issue.  I'll try the slack channel as suggested.
