### ISSUE TITLE
Cannot login from CLI when using caddy SSL certificate

### ISSUE THREAD

**Issue by matifali** [coder/coder#3645]
### Command: 
`coder login https://mycoder.domain.com`
### Output:
```bash
build info: do: Get "https://mycoder.domain.com/api/v2/buildinfo": x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "Caddy Local Authority - 2022 ECC Root")
has initial user: do: Get "https://mycoder.domain.com/api/v2/users/first": x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "Caddy Local Authority - 2022 ECC Root")
Run 'coder login --help' for usage. 
```

**Comment by kylecarbs** [comment]
Do you have the Caddy root certificate installed on your client machine? We don't do anything _special_ here, we just follow the Go certificate roots: https://go.dev/src/crypto/x509/root_linux.go

**Comment by matifali** [comment]
Yes, I have it installed. as a certificate authority in google chrome.

**Comment by kylecarbs** [comment]
Hmm, it'd need to exist on the client machine in one of the paths listed in that Go file for the command line to pick it up. Can you try that out?

**Comment by kylecarbs** [comment]
Closing for now! Let us know if you need anything.

**Comment by matifali** [comment]
Most of the clients are using windows. The best option would be where they don't have to install anything at all. We work on ML workspaces. Where most people only need jupyter notebook or a VNC connection to run Spyder.

**Comment by kylecarbs** [comment]
I'm not sure why your Windows machines lack the root CA... odd. What's your desired behavior from Coder here? We could add a `--insecure` flag.

**Comment by matifali** [comment]
> I'm not sure why your Windows machines lack the root CA... odd. What's your desired behavior from Coder here? We could add a `--insecure` flag.

Yes adding a `--insecure` flag sounds good at least whencoder OSS is in beta.
