### ISSUE TITLE
Issue Cleanup Round #2

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#3650]
## Description

Following in the [footsteps](https://github.com/coder/coder/issues/3276) of @f0ssel, I will be [gathering issues](https://github.com/coder/coder/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc+no%3Aassignee+no%3Amilestone) here to close:
- https://github.com/coder/coder/issues/1719
- https://github.com/coder/coder/issues/1858
- https://github.com/coder/coder/issues/1873
- https://github.com/coder/coder/issues/2178
- https://github.com/coder/coder/issues/2372
- https://github.com/coder/coder/issues/2676
- https://github.com/coder/coder/issues/2772
- https://github.com/coder/coder/issues/2780
- https://github.com/coder/coder/issues/2801
- https://github.com/coder/coder/issues/2901
- https://github.com/coder/coder/issues/2994
- https://github.com/coder/coder/issues/3123
- https://github.com/coder/coder/issues/3188
- https://github.com/coder/coder/issues/3210
- https://github.com/coder/coder/issues/1718

### Ask

If you think an issue should stay open, comment below with the issue number! 

### Deadline 

Thursday, 8/25 10:30am MST ([view in your timezone](https://github.com/coder/coder/issues/3650))

## Requester 

@kylecarbs

**Comment by f0ssel** [comment]
I'd like to do #1718 still

**Comment by presleyp** [comment]
#3209 should happen when it's unblocked.

**Comment by kylecarbs** [comment]
@jsjoeio I went through every issue this morning, and the green ones should still be kept alive!

**Comment by jsjoeio** [comment]
Dang, you're quick! Closing this then.
