### ISSUE TITLE
Show only running workspaces

### ISSUE THREAD

**Issue by ammario** [coder/coder#3655]
As the cloud budget holder and admin, I want to quickly find all running workspaces to see if any should be shut down.

<img width="1524" alt="Screen Shot 2022-08-23 at 11 43 28 PM" src="https://user-images.githubusercontent.com/7416144/186330716-c933a58b-8cf6-4841-bbe0-3c829dc1c97b.png">

I naturally reach for a filter.
<img width="1522" alt="image" src="https://user-images.githubusercontent.com/7416144/186330873-7d83f047-db54-4f35-966c-315aa22354a9.png">

**Comment by BrunoQuaresma** [comment]
Some thoughts:
- We can make it in the FE only
- I think making this in the BE can be tricky since the status is not a "well computed" value, and we are doing that in the FE. To make this happen in the BE, we should refactor the BE to compute the status and after, use it to filter the workspaces. Not sure how this could happen with the DB.

**Comment by presleyp** [comment]
@f0ssel this is where we translate from api values to workspace status (and then there's another translation to the actual wording used in various places, so like the status `started` displays as `Running`) https://github.com/coder/coder/blob/main/site/src/util/workspace.ts#L55

If we move this logic (transition + job status -> workspace status, that is; we can handle display labels on the frontend) to the backend, then adding a filter for running workspaces will be simple on the frontend.

Alternatively, if there is some way for the frontend to send a query that the backend can already understand (like `transition=start&status=complete` or something), that's also okay for the frontend.

**Comment by f0ssel** [comment]
Sounds good, I'll see what looks easier, will probably ping @coadler for some heavy lifting on the DB side.
