### ISSUE TITLE
Surprising terminal typing latency

### ISSUE THREAD

**Issue by ammario** [coder/coder#3657]
I used [feeltty](https://github.com/coder/feeltty) to measure the interactivity of a Coder SSH session vs. SSH directly into the box.

Coder is substantially slower in our `coder-ts` (Docker-based) template. I get baseline latencies in my AWS workspace.

```
$ feeltty ssh coder.poll
connect              2990.36792ms
input sample size    32
input mean           118.698ms
input stddev         274.132ms
```

```
$ feeltty ssh <redacted>
connect              1199.80383ms
input sample size    32
input mean           55.526ms
input stddev         43.138ms
```

Oddly, I see equal throughputs as tested by `ssh <host> -- cat /dev/urandom | pv > /dev/null`.

Perhaps #3505 will fix this. (cc @kylecarbs, @bpmct)

**Comment by bpmct** [comment]
I tried with identical workspaces (aws, us-west-1, same instance type). To me, it does not seem like a significant improvement.

## no tailscale

```sh
coder@ben-stable:~/coder/dist$ feeltty ssh coder.no-tailscale
connect              2527.55540ms
input sample size    32
input mean           85.401ms
input stddev         0.452ms
```

## with tailscale

(I used client and server binaries from #3505)

```sh
coder@ben-stable:~/coder/dist$ feeltty ssh coder.with-tailscale
connect              3022.32316ms
input sample size    32
input mean           104.875ms
input stddev         0.392ms
```

**Comment by BrunoQuaresma** [comment]
cc.: @kylecarbs

**Comment by kylecarbs** [comment]
Closing in favor of #2779
