### ISSUE TITLE
Show when workspace was last used

### ISSUE THREAD

**Issue by ammario** [coder/coder#3669]
Related to #3655

As an admin conducting cleanup, I want to identify workspaces that haven't been used within a certain amount of time (e.g. 30 days) and then delete them.

The best definition of "use" that I can think of is a user-initiated agent connection.

**Comment by BrunoQuaresma** [comment]
Do we have this info in the BE?

**Comment by ammario** [comment]
No, but I'm working on that.

**Comment by ammario** [comment]
This can be done after https://github.com/coder/coder/pull/3735.
