### ISSUE TITLE
Emojis with multiple unicode bytes aren't bundled

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#3689]
:wave: @kylecarbs 

For some reason, the :desktop_computer: emoji isn't bundled in our emoji folder. As you can see from the links below, a normal emoji can be found at the route, but the desktop computer cannot!

:smiley: https://dev.coder.com/emojis/1f606.png
:desktop_computer: https://dev.coder.com/emojis/1f5a5-fe0f.png

---

after updating to `0.8.6`, I edited one of my pre-existing `aws-ec2-code-server` template with an emoji. below is the resulting UI:

<img width="270" alt="Screen Shot 2022-08-24 at 10 51 59 PM" src="https://user-images.githubusercontent.com/9683576/186570723-94c1ed00-2c56-453a-b206-fa3053fdda73.png">

template settings:

<img width="434" alt="Screen Shot 2022-08-24 at 10 28 12 PM" src="https://user-images.githubusercontent.com/9683576/186567920-80a76d99-c13f-4cf4-b3e2-2af8853512ea.png">

reproduced on Safari, Chrome, & Firefox.

**Comment by kylecarbs** [comment]
Neither is :cloud:!
