### ISSUE TITLE
Create long-lived tokens for CI/CD/automation (or tokens for a specific duration)

### ISSUE THREAD

**Issue by jaulz** [coder/coder#3692]
Add a way (likely via the CLI) to generate API tokens:

- push templates via CI
- use the REST API/CLI in automated pipelines

## Original description

I searched the issues with multiple keywords but I could not find any information on how to push template updates from Github Actions for example. Is that actually possible? So far I tried the username/password approach but that fails because it requires the user to enter the token from the browser.

**Comment by bpmct** [comment]
Thanks for submitting the issue! I edited the description a bit so we can use this to track creating tokens and some docs around using Coder in CI.

**Comment by jaulz** [comment]
Thanks for the quick response! I didn't realize that the token in the browser is actually the access token 😉 Great product by the way 😊

**Comment by bpmct** [comment]
@ghuntley brought up an interesting point that we should consider before we add long-lived tokens. We may want to consider generating tokens in a searchable format so they can be picked up in security scans: https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning

**Comment by ghuntley** [comment]
+ adding the convention into projects such as https://github.com/awslabs/git-secrets

**Comment by bpmct** [comment]
- Token management/revocation will be an OSS feature
- Down the road, we may add enterprise functions such as configurable token durations and custom scopes

**Comment by dcarrion87** [comment]
We also have this requirement for pushing templates via Github actions. We're actually looking at something that can just keep templates in sync as they're updated. E.g. point coder at a repo revision of templates and it just takes care of it.

**Comment by jaulz** [comment]
@f0ssel thanks for the implementation! Is there any possibility to generate the token from the UI?

**Comment by ghuntley** [comment]
Opening up https://github.com/coder/coder/issues/5409
