### ISSUE TITLE
bug: workspace becomes disconnected after inactivity and there is no way to connect again from the WebUI

### ISSUE THREAD

**Issue by matifali** [coder/coder#3702]
# Coder Version
Tested on both 0.8.2 

```bash
Coder v0.8.2+00c5116 Mon Aug  1 13:37:37 UTC 2022
https://github.com/coder/coder/commit/00c5116a2e9c18f489cd876f7cd965686cbd759a
```
and 0.8.6 
```bash
Coder v0.8.6+5e36be8 Mon Aug 22 15:56:10 UTC 2022
https://github.com/coder/coder/commit/5e36be8cbb11c71e840a40193ae93c589cdd16e2
```

# Problem

workspace becomes disconnected after inactivity, and there is no way to connect again from the WebUI
# Steps to reproduce
1. Create a workspace
2. Connect via WebUI Terminal
3. Run some commands
4. Leave it unattended for some time until web terminal says disconnected.
5. you get this screen
6. 
![Screenshot from 2022-08-26 14-09-05](https://user-images.githubusercontent.com/10648092/186891840-ab59e39d-5f11-4ff9-a651-8cba3f0b093e.png)

**Comment by matifali** [comment]
This is the output if I try to connect from local terminal over ssh
![image](https://user-images.githubusercontent.com/10648092/186892230-b3447455-096c-449e-b8d4-6f9aad18ece9.png)

**Comment by matifali** [comment]
A workaround is to shut down and restart the workspace to be able to connect.

**Comment by johnstcn** [comment]
- How long does this take to happen, roughly?
- When you noticed the issue, was the docker container running? e.g. on the Docker host, does `docker ps -a` output a running Docker container?
- If so, can you check `/tmp/coder-agent.log` inside the container from when the disconnect occurred?
- Can you also check `docker logs <container_id>` for any relevant entries from the time?

**Comment by matifali** [comment]
> * How long does this take to happen, roughly?
> * When you noticed the issue, was the docker container running? e.g. on the Docker host, does `docker ps -a` output a running Docker container?
> * If so, can you check `/tmp/coder-agent.log` inside the container from when the disconnect occurred?
> * Can you also check `docker logs <container_id>` for any relevant entries from the time?

It occurs if we launch the Web Terminal and don't use it for some time. If no terminal is open workspace stays alive.
I will test again to report what you have asked for.

**Comment by johnstcn** [comment]
Both @matifali and I attempted reproducing this issue without success. Closing for now; once we have steps to reproduce we can open a new issue.
