### ISSUE TITLE
`Coder Templates Creates` hangs even though job completed

### ISSUE THREAD

**Issue by endingwithali** [coder/coder#3710]
<img width="544" alt="Screen Shot 2022-08-26 at 12 58 31 PM" src="https://user-images.githubusercontent.com/5589184/186955607-a21572e4-8c07-40a1-a5e6-7c3154b4e13a.png">

Ask @bpmct for more info

**Comment by coadler** [comment]
This is due to a problem with some websockets when using `coder server --tunnel`, as a workaround it should work fine without the tunnel.
