### ISSUE TITLE
Put an extra license signing key in cold storage

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#3712]
One thing @Emyrk suggested while reviewing the licensing how-to is that if our signing key were ever leaked, it would be useful to be able to have a backup key we could start using right away.

Without this, we need to release new version(s) of Coder (possibly including backports) that have the new public key, AND convince our customers to install it before we can start issuing licenses with a new key.

The idea here is to generate one (or a handful) of new keypairs offline.  Store the private keys on a USB drive, and just stick it in a safe.  The public keys get checked into the repo under `enterprise/coderd/keys` and added to the map of public keys in `enterprise/coderd/license.go`.

Then, if we discover a key leak, after re-securing our signing infra, we can pull out one of these keys to start signing and all old versions of coder will accept the licenses.

**Comment by ammario** [comment]
Our ICP is not using pirated software, and we can force an update to a new key (or algorithm) upon Coder software update. Furthermore, with little effort, an attacker can remove the license checks from our source code and circumvent all the cryptographic securities. I don't think it's worth spending more time on license security.

**Comment by spikecurtis** [comment]
This suggestion is not really about increasing license security, but more about making our (future) lives easier if we decide we need to use new keys.

> Without this, we need to release new version(s) of Coder (possibly including backports) that have the new public key, AND convince our customers to install it before we can start issuing licenses with a new key.

If you don't think the effort _now_ is worth the saved effort and/or peace of mind for _later_, I'm fine seeing this closed not planned.

**Comment by ammario** [comment]
I'm indifferent.

**Comment by kylecarbs** [comment]
@ammario I'll leave this for you to decide if it should be done or not.

**Comment by ammario** [comment]
I consider it a waste of company resources to maintain offline infrastructure (safe and USB drive). If we still had our storage unit, this issue (as described in OP) would be more feasible.
