### ISSUE TITLE
Windows packages (winget, choco, etc)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#3714]
We publish packages for Linux systems, but not Windows! Would be great for users to install Coder with `winget install coder`

**Comment by phorcys420** [comment]
other nice-to-haves would be Chocolatey and Scoop

**Comment by matifali** [comment]
> We publish packages for Linux systems, but not Windows! Would be great for users to install Coder with `winget install coder`

also `winget upgrade coder` my favourite

**Comment by matifali** [comment]
maybe a GitHub action that will push to the winget repo on every release.

**Comment by bpmct** [comment]
I'm not entirely sure when we will get around to doing this, but we welcome contributions.

I'm happy to help by creating official accounts for marketplaces, review, etc.

**Comment by ghuntley** [comment]
Opening up a open-source bounty (payable via GitHub Sponsors) worth circa 200USD to the person who contributes the pattern to automatically publish our windows binaries to choco and winget. 

See https://twitter.com/coderhq/status/1584128889105764352?s=20&t=Zczm48WsOS7uL33C-UI5BQ for more information.

cc @matifali

**Comment by matifali** [comment]
choco and scoop are still pending if we want them

**Comment by phorcys420** [comment]
Chocolatey support in #8921

**Comment by phorcys420** [comment]
I will try to PR Scoop support later on whenever I get the time (or motivation).
