### ISSUE TITLE
Workspace is automatically updated when started via WebUI

### ISSUE THREAD

**Issue by mafredri** [coder/coder#3718]
When my workspace is outdated and the WebUI has the "Update" button present, if I try to bypass this by selecting "Start" from the dropdown menu, my workspace is updated anyway.

This does not happen when doing `coder start work` via CLI.

Kind of related to #2871, but this is a consistency issue.

![Coder outdated-updated on start bug](https://user-images.githubusercontent.com/147409/187024109-a0b64c38-3e33-4bb7-b2af-aa9ba8167f53.gif)

The request:

```
POST http://coder.home.my.domain:7080/api/v2/workspaces/279504e2-ad0e-4fbf-b9e6-9a8d9aa7f038/builds
{
  "transition": "start",
  "template_version_id": "ff484f7c-d3f2-4fe5-900a-a5cde55f04bd"
}
```

I'm guessing the WebUI is simply using the latest template version when issuing start? Could be something else though.

**Comment by BrunoQuaresma** [comment]
You are right, we are using the latest version when doing the "start".
