### ISSUE TITLE
Add git to the Dockerfile so Terraform modules work

### ISSUE THREAD

**Issue by jakehwll** [coder/coder#3724]
Due to the image being based on raw `alpine`, the example [`examples/templates/gcp-vm-container`](https://github.com/coder/coder/tree/main/examples/templates/gcp-vm-container) won't run due to lacking `git`.

```
  Error: Failed to download module
  
  Could not download module "gce-container" (main.tf:31) source code from
  "git::https://github.com/terraform-google-modules/terraform-google-container-vm?ref=v3.0.0":
  error downloading
  'https://github.com/terraform-google-modules/terraform-google-container-vm?ref=v3.0.0':
  git must be available and on the PATH.
  
  
  Error: Failed to download module
  
  Could not download module "gce-container" (main.tf:31) source code from
  "git::https://github.com/terraform-google-modules/terraform-google-container-vm?ref=v3.0.0":
  error downloading
  'https://github.com/terraform-google-modules/terraform-google-container-vm?ref=v3.0.0':
  git must be available and on the PATH.
  ```

**Comment by deansheather** [comment]
Sadly we can't just plop a `RUN apk add --no-cache git` in our Dockerfile as it's cross-compiled for multiple architectures. I suggest we change the `FROM alpine` to [`FROM alpine/git`](https://hub.docker.com/r/alpine/git) instead.

Would you like to submit a PR for this @jakehwll?


https://github.com/coder/coder/blob/b9b9c2fb9f66d4385267f97d20b690c0856572a6/Dockerfile#L1-L4

**Comment by jakehwll** [comment]
Just tested this building via WSL and on MacOS based.  Both seem to play nicely and was able to spinup the image correctly!

**Comment by deansheather** [comment]
Update on this:
- We're planning on using depot.dev in CI to build a base image (alpine + git + `coder` user) extremely quickly when changed and periodically
- This base image will be used by the Dockerfile instead

I still want to work on this but I've been working on workspace apps instead for the last few weeks. I'm going to unassign myself and reassign myself when I'm ready to work on it.

**Comment by deansheather** [comment]
This is still planned.
