### ISSUE TITLE
Allow specifying custom properties for each coder user

### ISSUE THREAD

**Issue by matifali** [coder/coder#3728]
# Problem
We are using a samba share to share files. Every user has a folder mounted inside their workspace according to the username.
But the user created inside the workspace has a name set to ``data.coder_workspace.me.owner`
but uid is always 100, while samba share users have different uids.
Is it possible to assign a `uid` to each user in coder so that can be used while creating their workspaces from the templates?

This is my current template
```terraform
resource "docker_image" "coder_image" {
  name = "coder-base-${data.coder_workspace.me.owner}-${lower(data.coder_workspace.me.name)}"
  build {
    path       = "./images/"
    dockerfile = "DL.Dockerfile"
    tag        = ["deeplearning:v0.1"]
    build_arg = {
      USERNAME = "${data.coder_workspace.me.owner}"
    }
  }
  # Keep alive for other workspaces to use upon deletion
  keep_locally = true
}

```

# Suggested Solution
a property named `data.coder_workspace.me.uid` to be used in build context

**Comment by bpmct** [comment]
As a workaround, could you ask users to manually specify their samba uid via a [workspace parameter](https://coder.com/docs/coder-oss/latest/templates#parameters)?

I'm not sure I fully understand your suggestion, are you looking to get the UID of the workspace, generate a unqiue UID for Samba, or allow a user to specify their UID as an account-wide property?

**Comment by matifali** [comment]
> allow a user to specify their UID as an account-wide property?

This is my suggestion.

**Comment by bpmct** [comment]
Ah, I think I am following. Today there is currently:

- [data.coder_workspace.me.id](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#id) - unique Coder workspace UUID
- [data.coder_workspace.me.owner_id](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace#id) - unique Coder user UUID 

Perhaps something like #3506 would work, so users (or an admin) can set `data.coder_user.me.custom_propery`?

**Comment by matifali** [comment]
Yes that should work.

**Comment by BrunoQuaresma** [comment]
@matifali since #3506 could work for your use case, is it ok if I close this one?

**Comment by matifali** [comment]
@BrunoQuaresma yes you may close this one if you can track it on #3506

**Comment by kylecarbs** [comment]
@matifali I'd recommend y'all keep an internal mapping elsewhere of username -> UID mappings. We intentionally keep this abstract, so you could read from an external JSON file in your Terraform provisioning or something.
