### ISSUE TITLE
download build log

### ISSUE THREAD

**Issue by ammario** [coder/coder#3736]
To aid with debugging, perhaps we add a button that downloads the build log.

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/7416144/187277430-59e17eb8-482a-4663-84dd-f0d25091c019.png">

**Comment by BrunoQuaresma** [comment]
What should be the file format? A simple TXT, JSON?

**Comment by ammario** [comment]
@BrunoQuaresma I think `txt` as the log isn't structured.
