### ISSUE TITLE
`gcp-linux` example template fails immediately when creating workspace

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#3738]
when creating a workspace using our `gcp-linux` template, it fails immediately and there are no logs shown in the workspace logs UI, preventing me from debugging. using server version `0.8.6`

additionally, when deleting the workspace, it fails immediately, requiring me to manually run SQL commands to delete the workspace from the database table.

steps to reproduce:
- run `coder templates init`
- select "Develop in Linux on Google Cloud"
- run `cd ./gcp-linux && coder templates create`
- create the workspace via `coder create --template="gcp-linux" <name>

UI workspace log screen upon failure:

<img width="1105" alt="Screen Shot 2022-08-29 at 2 29 02 PM" src="https://user-images.githubusercontent.com/9683576/187282628-07e684f3-c35a-4940-bf98-d7b7846e7cb1.png">

**Comment by kylecarbs** [comment]
@ericpaulsen can you try with the latest? Are there any logs in your command-line when running this?

**Comment by ericpaulsen** [comment]
@kylecarbs yup - just tested with `0.8.9`, and am receiving the following terminal logs:

```
Error resolving image name 'debian-cloud/debian-9': Could not find image or family debian-cloud/debian-9
```

they're also displaying correctly in the workspace log UI 😄

**Comment by ericpaulsen** [comment]
a recent related issue: https://github.com/hashicorp/terraform-provider-google/issues/12221.

looks like the `debian-cloud/debian-9` disk doesn't exist anymore. I can update.
