### ISSUE TITLE
Nicer UI for multiple template options

### ISSUE THREAD

**Issue by kotx** [coder/coder#3744]
When there are too many options specified with `validation` in a template, it can get a bit annoying. For example:
![screenshot](https://kot.gay/sharex/librewolf_pYk60VrEsxOtbdS.png)

Would be great to have a dropdown for more than, say, 10 items or something.

**Comment by kylecarbs** [comment]
Thanks for the issue @kotx!

**Comment by matifali** [comment]
Also, `var.fly_region` may be replaced with a description.

**Comment by kotx** [comment]
> Also, `var.fly_region` may be replaced with a description.

How can I do this? Or is this a suggestion?

**Comment by BrunoQuaresma** [comment]
I think we can by default use a "select" component for multiple options. Thoughts? 🤔

**Comment by matifali** [comment]
> > Also, `var.fly_region` may be replaced with a description.
> 
> How can I do this? Or is this a suggestion?

This is a suggestion to coder UX team.
