### ISSUE TITLE
"coder templates create" using docker template

### ISSUE THREAD

**Issue by akdasari1980** [coder/coder#3748]
I am trying to create a workspace using docker template. I am not able to create and throwing the below error.

Error: Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

I have local docker engine running on my Mac, but terraform template takes docker provider from kreuzwerker/docker. "coder template create" is looking for kreuzwerker/docker or local docker?

Are there any good documentation and steps to proceed further on the workspace creation

**Comment by sharkymark** [comment]
@akdasari1980 I responded over email and also created this issue #3750

**Comment by bpmct** [comment]
We resolved this over email

**Comment by TheAlphaReturns** [comment]
how was it fixed
