### ISSUE TITLE
Archive too big. Must be <= 1048576 bytes

### ISSUE THREAD

**Issue by akdasari1980** [coder/coder#3749]
./coder templates create
> Create and upload "~/Documents/Practice-Projects/Coder/coder_0.8.9_darwin_amd64"? (yes/no) yes
**Archive too big. Must be <= 1048576 bytes**
Run 'coder templates create --help' for usage.

**Comment by sharkymark** [comment]
@akdasari1980 to create a template, you cd into the directory with the main.tf file. It appears you are in a directory with the coder install zip.
