### ISSUE TITLE
`bare` example template is useless and tripped up a new evaluator

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3750]
Version: [`v0.8.9+6285d65`](https://github.com/coder/coder/commit/6285d65b6a752896870ebdd5abae3b1afd8ac529)

As a new evaluator and user of Coder, I want templates that basically work. The `bare` template is not that. A new user reported not being able to get it work, but that is because nothing functional is in there.

The template should be removed from the examples.

The examples should also reduce to 1 Docker example. There is template bloat going on in there.

**Comment by BrunoQuaresma** [comment]
So do you think we should just remove it? Or is there any value on fixing and keeping it?
