### ISSUE TITLE
🎨 Bug: Can't delete an emoji for a template

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3756]
Version: [`v0.8.9+6285d65`](https://github.com/coder/coder/commit/6285d65b6a752896870ebdd5abae3b1afd8ac529)

When I attempt to remove an emoji from a template and click save, it still retains the emoji. So now I am stuck with a lame emoji.

**Comment by BrunoQuaresma** [comment]
This is an interesting one. When the API receives an empty string or an empty value in the PATCH request, the API ignores it and uses the current value. I'm not sure if in Golang we can check if a value exists or not in the request body and/or if it is `null`. In JS we have `undefined` and `null` but Idk if Golang has something similar.

**Comment by BrunoQuaresma** [comment]
After chatting with @kylecarbs, I'm going to change the API to not assign the current value if the request passes an empty string.
