### ISSUE TITLE
Forward a range of ports with the `port-forward` subcommand

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3766]
A community user with multiple users in their deployment reported a feature request to improve the `port-forward` experience.

Right now, you have to enter `--tcp`  or `--udp` for each port.

The request, and their requirement, is 100+ ports and they want it much simpler.

Example implementations suggested are:

A file with a list of ports
Or just removing the repetitive `--tcp` or `--udp` flag

**Comment by kylecarbs** [comment]
I think a syntax like:
```bash
$ coder port-forward dev --tcp 3000-9000
```
would be awesome!

**Comment by MarcoSaba** [comment]
Sarco from Discord here, the range would be cool. But there could be a case where not all the ports included in the range must be forwarded.

For example, i need 4000 4005 and 4010. Not really useful to forward range from 4000 to 4010.

**Comment by mafredri** [comment]
As discussed in Discord, we could allow additional ports in a single `--tcp` or `--udp` via comma separated values. This could look like `--tcp 4000,4005,4010` or even be combined with the range, i.e. `--tcp 3000-9000,9050,9060,9090-9099`.

_We probably shouldn't_, but if we wanted to consider allowing white-space (space, newline, tab?) separation (in addition to `,`?) we could support use-cases like `--tcp "$(<tcp_ports.txt)" where each port is on their own line or space-separated.
