### ISSUE TITLE
Add hours used to each User row

### ISSUE THREAD

**Issue by ammario** [coder/coder#3768]
To aid in the identification of unused licenses or adoption barriers, let's use the work in #3735 to present the number of connection hours each user has in the Users listing.

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/7416144/187562308-4b76ec9f-10d9-4b01-acf3-ab27be688a09.png">

**Comment by kylecarbs** [comment]
Is this a sum of all? Or a total over X duration?

**Comment by ammario** [comment]
It would be the sum of all recorded stats data, which is by default last 30 days.

**Comment by BrunoQuaresma** [comment]
@ammario is it in the API already?

**Comment by ammario** [comment]
@BrunoQuaresma yes, the data is available in the database (see the `agent_stats` table) but will require an expensive aggregation query, so the implementer should use `metricsCache` to record the values.
