### ISSUE TITLE
Template input when creating a workspace ignores defaults if changed and empty

### ISSUE THREAD

**Issue by kotx** [coder/coder#3771]
If I type in a template variable input field when creating a workspace, and then delete what I typed, the input turns into "" instead of the default (when there is one).

**Comment by BrunoQuaresma** [comment]
I see. I think we can:
- Use the default value as an input placeholder. So if the field is empty, the user will see the default value there.
- Before sending it to the server, if the value is an empty string, use the default value.

@kotx do you think this sounds good?

**Comment by kotx** [comment]
Yup, sounds good!
