### ISSUE TITLE
Add a changelog/message on template push

### ISSUE THREAD

**Issue by matifali** [coder/coder#3775]
# Problem
For now, there is no changelog to see for the developers when a template is updated.
See the figure below.
![image](https://user-images.githubusercontent.com/10648092/187599853-08c7593d-93c8-4860-9cd1-61aac544bfb1.png)

# Suggested Solution
Something like
`coder templates push <template_name> -m "1) Added jupyter lab, 2) Activate DL conda environment at startup"`

And that comment may be displayed as a collapsable section under each template version in the template history list.

**Comment by mafredri** [comment]
Nice suggestion. We could potentially also support showing an auto-generated diff between the current and the previous version (potentially any two versions), could help a lot with debugging when something goes wrong.

**Comment by matifali** [comment]
Do you have any plans to show a changelog or a commit message to show what got changed? Most devs are not interested in the terraform/Dockerfile diffs and are only concerned about why they should update when the previous version is working fine.

# Suggestion

```console
coder templates push -m "A message describing what got changed"
```

Also, it needs to be shown somewhere on the template page and as a new column on the template versions page.
You may also replace the template version column as it helps for debugging but does not give users any helpful information.

**Comment by bpmct** [comment]
Totally up for this doing this. When a template is updated via CI/CD, users could make the template message the same as the commit message. We are currently doing this for the version name (it is the commit SHA)

https://github.com/coder/coder/blob/856f0ab6f5a3c8650181a6c066356d7b452b0f40/.github/workflows/dogfood.yaml#L72

**Comment by BrunoQuaresma** [comment]
Should we limit the number of characters?

**Comment by bpmct** [comment]
git restricts commit titles to 72 characters but the entire message would be longer. maybe we just truncate after 72?

**Comment by matifali** [comment]
It may be 140/280 characters (Twitter's way).
Sometimes the changes are more than 72 characters.

**Comment by bpmct** [comment]
related #5865

**Comment by BrunoQuaresma** [comment]
This needs some backend work so I will rely on @mtojek decision.

**Comment by mtojek** [comment]
I'm ok with this feature, but I would rather park it on the roadmap or attach it to any milestone first. Then, we can split the frontend and backend tasks.

From the backend perspective, we can start with MVP, so an extra DB column for the template version, and see if this is sufficient.

**Comment by bpmct** [comment]
Let's limit this to 72 characters for now to ensure that it can display nicely in the UI/CLI. If a larger message is sent, let's not fail and even store it in the DB, but explain that it may be truncated. This is like the git behavior.

**Comment by mtojek** [comment]
Hey @mafredri! Do you think that we need a basic draft/plan for implementing this feature? I'm asking in terms of next sprint planning.

**Comment by mtojek** [comment]
Hey @mafredri! Should we assign this issue to @BrunoQuaresma now?
