### ISSUE TITLE
Apps with `command` are not working

### ISSUE THREAD

**Issue by jaulz** [coder/coder#3777]
It seems that apps that are using a command only are not working like they are suggested at https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app. This is my definition:
````
resource "coder_app" "postgres" {
  agent_id = coder_agent.postgres.id
  name     = "Logs"
  command  = "ls /var/lib/postgresql/data/log/"
}
````

But when I try to open the app it says:
````
{
  "message": "Application Logs does not have a url."
}
````

**Comment by kylecarbs** [comment]
Thanks for the report @jaulz! This was _never implemented_ unfortunately, but I'm happy to see a use case here. I added it to our Milestone, and this issue can be used to track it.
