### ISSUE TITLE
Setup Pagerduty for dev.coder.com

### ISSUE THREAD

**Issue by ammario** [coder/coder#3783]
It sometimes goes down and with it Coder engineering productivity.

**Comment by BrunoQuaresma** [comment]
Would be nice to have this process in the docs as well. I know the setup process is generic but can be worth some SEO traffic.

**Comment by ammario** [comment]
I was thinking we begin with a generic HTTP liveness check.

**Comment by BrunoQuaresma** [comment]
A simple endpoint `/status` in the `coderd` API would be enough? Or do we want to have an endpoint where we can also check database connection and return something like:
```
{ network: true, database: true }
```

**Comment by ammario** [comment]
I'm beginning with something even simpler. Just check that `GET https://dev.coder.com` has status code 200.

**Comment by ammario** [comment]
Just set it up...
