### ISSUE TITLE
Allow to add pre-generated GPG and SSH key while creating a new workspace.

### ISSUE THREAD

**Issue by matifali** [coder/coder#3789]

**Comment by mafredri** [comment]
Could you describe this functionality in better detail? What are you hoping to achieve?

For instance, once #3126 is fixed, you could upload your own SSH key to the workspace. (Or you can use SSH agent forwarding, if you prefer.)

Does the proposed method have any benefit over uploading the key to the workspace?

**Comment by mafredri** [comment]
@matifali Hmm, I see no reason why it shouldn't work. Perhaps VS Code isn't receiving the appropriate `SSH_AUTH_SOCK` environment variable, and thus can't use the forwarded agent?

For instance, here is how I'd set this up for signing via SSH key and agent forwarding:

```console
coder@sign:~# git config --global gpg.format ssh
coder@sign:~# git config --global user.signingkey "$(ssh-add -L | grep 'GitHub (mafredri)')"

coder@sign:~# mkdir repo && cd $_
coder@sign:~/repo# git init
Initialized empty Git repository in /home/coder/repo/.git/

coder@sign:~/repo# git config gpg.ssh.allowedSignersFile .allowed_signers
coder@sign:~/repo# echo "my@email.com $(ssh-add -L | grep 'GitHub (mafredri)')" >.allowed_signers

coder@sign:~/repo# git commit -m 'Test' --allow-empty -S
[main (root-commit) 12b2184] Test

coder@sign:~/repo# git show --show-signature
commit 12b2184c3d5a6f28ccb5480a9da921d370bfaef6 (HEAD -> main)
Good "git" signature for my@email.com with ED25519 key SHA256:..........
Author: Mathias Fredriksson <my@email.com>
Date:   Thu Sep 1 14:23:43 2022 +0000

    Test
```

**Comment by kylecarbs** [comment]
We probably won't add special GPG signing into Coder, but we might support signing commits with an SSH key...
