### ISSUE TITLE
bug: `#` character causes a `coder_app` IDE launch to fail with `application not found`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3803]
Version: [`v0.8.10+01a06e1`](https://github.com/coder/coder/commit/01a06e1213ef5e0c3a705d27a19551f138d275de)

If I create a template with a `coder_app` `name` that includes a `#` character, the IDE will fail to open with an `application not found` error.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2022166/187947469-72324b2c-1361-4a9c-bed0-9214015da9da.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2022166/187947671-a580619a-2322-4bcf-b01b-a17fc698b6cb.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2022166/187947806-09a0679e-56d8-4985-9588-ffe7331a7009.png">

**Comment by BrunoQuaresma** [comment]
If you replace the app name in the URL with this escaped version `IDEA%20Community%202` does it work?

**Comment by sharkymark** [comment]
@BrunoQuaresma I haven't tried this, but the problem isn't a space aka `%20` but the `#` symbol. It works fine with spaces.
