### ISSUE TITLE
Polish up the dashboard

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#3813]
This title is duplicated:
![image](https://user-images.githubusercontent.com/7122116/187964266-043be520-689a-4b85-a744-209b8dc518c0.png)

The text in this table:
![image](https://user-images.githubusercontent.com/7122116/187964400-7b6352d4-8371-4109-b8dc-2f96b33e9771.png)
is styled differently than this table:
![image](https://user-images.githubusercontent.com/7122116/187964453-4fc70796-81f1-4b02-8085-b3bab858a390.png)

There is a double border on the bottom of the workspaces table:
![image](https://user-images.githubusercontent.com/7122116/187964582-1713c871-508e-47bb-b81d-01468ad963a9.png)

Remove copyright, it's unnecessary:
![image](https://user-images.githubusercontent.com/7122116/187990579-0241ce98-5352-4b90-b569-e82c333644bf.png)

Input color:
https://user-images.githubusercontent.com/7122116/187990769-569d6f23-96fc-4ff2-9f7c-00d5c0e5486f.mp4

This seems like it's a few pixels off:
![image](https://user-images.githubusercontent.com/7122116/187990943-4c923da8-398d-48d2-91f3-e830fc0fcf31.png)

This table has inconsistent sizing of columns:
![image](https://user-images.githubusercontent.com/7122116/187990997-26a7838d-8a2c-4647-b861-f8c66107cec9.png)

**Comment by kylecarbs** [comment]
The terminal overflows with a license banner:
![image](https://user-images.githubusercontent.com/7122116/187992514-b964ec6a-636c-4c3e-91d4-2c4790f267e4.png)

**Comment by kylecarbs** [comment]
Markdown doesn't look great:
![image](https://user-images.githubusercontent.com/7122116/187992630-650c489d-3297-41b2-b893-82b4332ef0d2.png)

It'd be cool if it rendered similarly to our docs, which I think are very pretty:
![image](https://user-images.githubusercontent.com/7122116/187992688-37d77a8b-5f71-4e2b-8f4c-e1bfd7fb19dc.png)

**Comment by kylecarbs** [comment]
Another small bug that could be fixed as part of this... the users page double refreshes when I navigate to it from another page. You can see it flash twice.

**Comment by bpmct** [comment]
Not to pile on but...

- Markdown tables don't render properly in templates README

**Comment by matifali** [comment]
Something from me on the Users page why is there some extra space for the fourth column? see the black vertical bars
![image](https://user-images.githubusercontent.com/10648092/188152487-bc887209-27b0-40cf-a8b8-cf3636d810ac.png)

**Comment by BrunoQuaresma** [comment]
@kylecarbs when you say "Remove copyright, it's unnecessary:" is to remove the "Copyright" text only? Or all the info?

**Comment by BrunoQuaresma** [comment]
@bpmct do we have any template on dev.coder.com that uses table?

**Comment by BrunoQuaresma** [comment]
> Markdown doesn't look great:

@kylecarbs is it because of the code highlight?

**Comment by BrunoQuaresma** [comment]
> The terminal overflows with a license banner:

How important is this fix? It is not a trivial fix because of how the banner and terminal are "layout". This does not look bad at all IMO and just a few % of users will see this.

**Comment by BrunoQuaresma** [comment]
I created another one just for markdown https://github.com/coder/coder/issues/3896
