### ISSUE TITLE
Use Active Users instead of Total Users in Templates page

### ISSUE THREAD

**Issue by ammario** [coder/coder#3815]
The "Used by" column is intended to help developers choose the right template. The more active a template, the more likely it is to be the right one. If we switch to "Active Users" (using the metrics work in #3735), we can more accurately present the best template in older deployments.

<img width="1237" alt="Screen Shot 2022-09-01 at 3 03 25 PM" src="https://user-images.githubusercontent.com/7416144/188002053-05a7b218-f5af-494d-969b-de642d719eee.png">
<img width="1232" alt="Screen Shot 2022-09-01 at 3 03 33 PM" src="https://user-images.githubusercontent.com/7416144/188002072-d8264bef-e0f1-4e92-8b7c-71e100e89a79.png">

**Comment by sharkymark** [comment]
I'm not a developer but only talk to ones in sales. 🦈

But I'm not sure I have heard that paradigm in our customer base. There are many different development teams, each with lots of environment types aka templates if they used Coder.

What if a new development group was formed, or it is a specific niche project, it will always have fewer developers in it, whether it be active or most used?

**Comment by ammario** [comment]
> What if a new development group was formed, or it is a specific niche project, it will always have fewer developers in it, whether it be active or most used?

What do you see is the purpose of "Used by" today?
