### ISSUE TITLE
`CODER_TAILSCALE=true` causing web IDEs to intermittently not load.

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3853]
Version: [`v0.8.11+cde036c`](https://github.com/coder/coder/commit/cde036c1ab590d58ac4cd8b26235351b9c74d8f7)

`CODER_TAILSCALE=true` causing web IDEs to intermittently not load.

This has occurred in both of my Tailscale deployments.

It is random.

Deleting and recreating the workspace appears to solve it.

When IDEs are working, I do see the i symbol in the top left of the browser window, before it goes to the lock 🔒 showing TLS.

<img width="1337" alt="tailscale-web-ide" src="https://user-images.githubusercontent.com/2022166/188268640-1214d53e-19e4-4382-802a-bb341b0de73d.png">

**Comment by sharkymark** [comment]
Terminal too 
<img width="858" alt="image" src="https://user-images.githubusercontent.com/2022166/188247040-308f64a1-e9f0-4075-a973-249f2917e005.png">

**Comment by mafredri** [comment]
Seeing the same or similar myself, can easily reproduce using:

```
while :; do ssh coder.workspace exit; done
```

After a few loops the SSH connection will just hang.

**Comment by BrunoQuaresma** [comment]
cc.: @kylecarbs

**Comment by kylecarbs** [comment]
This is fixed in the latest version!

**Comment by sharkymark** [comment]
I noticed this occurs and the DERP server does not populate in the agent UI.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/2022166/189089985-8c98bed8-39b8-46d3-85ec-56af2420cf24.png">

@kylecarbs
