### ISSUE TITLE
Feat: `SSH` button doesn't finish the sentence - how to get to a local IDE

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3865]
Version: [`v0.8.11+cde036c`](https://github.com/coder/coder/commit/cde036c1ab590d58ac4cd8b26235351b9c74d8f7)

Oddly the real estate used by the `SSH` button in a workspace, does a lot of explaining about `coder config-ssh` and oddly the Wed IDE docs, but it should have a direct link to how to set up JetBrains Gateway and local VS Code with the VS Code extension.

Please refresh to provide `end game`. Just `SSH` into a workspace is not value-add.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/2022166/188345879-8f6b5967-904d-467b-a88a-9828f13610f6.png">

**Comment by BrunoQuaresma** [comment]
@sharkymark I'm not sure what should be the fix or improvement for this.

**Comment by bpmct** [comment]
Gonna do some wording changes here anyways
