### ISSUE TITLE
create workspace:ts": x509: certificate relies on legacy Common Name field, use SANs instead)

### ISSUE THREAD

**Issue by roshvin** [coder/coder#3873]
getting below error while creating workspace .could you pls assist .

create workspace: stream logs from workspace: log stream: log yield fail: %!w(string=Failed to pull envassets: download assets: Get "https://coder.inedc.corpintra.net/downloads/envassets": x509: certificate relies on legacy Common Name field, use SANs instead)

**Comment by sharkymark** [comment]
@roshvin This issues forum is for Coder OSS and it appears you are using Coder v1. 

If you email this to support@coder.com we can have the thread there. But TL;DR we think your cert doesn't comply with how Go handles SSL certs.
