### ISSUE TITLE
Update architecture documentation

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3875]
The new architecture doc mentions dev URLs and coderd and provisionerd can be uncoupled.

I understand these to be roadmap items, so do not think they should be in this OSS architecture doc.

https://coder.com/docs/coder-oss/latest/about/architecture

**Comment by BrunoQuaresma** [comment]
@kylecarbs maybe something we have to update after the Tailscale changes?

**Comment by kylecarbs** [comment]
Yup!

**Comment by kylecarbs** [comment]
Closing in favor of #4655
