### ISSUE TITLE
coder templates create fails with templates involving docker  (template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1)

### ISSUE THREAD

**Issue by imbev** [coder/coder#3876]
Using the docker-code-server template obtained via `coder templates init`, using `coder templates create` results in an error.

```
> Create and upload "~/docker-code-server"? (yes/no) 
✔ Queued [435ms]
✔ Setting up [117ms]
✔ Adding README.md... [148ms]
✔ Parsing template parameters [233ms]
⧗  Detecting persistent resources 
  Terraform 1.2.1
  data.coder_provisioner.me: Refreshing...
  data.coder_workspace.me: Refreshing...
  data.coder_provisioner.me: Refresh complete after 0s [id=f1f4daa3-d8db-4c1b-b178-1d0cd798727b]
  data.coder_workspace.me: Refresh complete after 0s [id=79076435-6285-46fd-8e9a-1b0f79d5243c]
  Error: Error pinging Docker server: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
  
✔ Detecting persistent resources [4521ms]
✘ Cleaning Up [476ms]
template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1
Run 'coder templates create --help' for usage.
```

**Comment by skerit** [comment]
Are you running code-server itself in a docker container? If so: I had the same issue earlier today.
You need to make the `/var/run/docker.sock` file  *inside of the container* accessible to the coder user, by chmodding it.

If you're not running code-server in a container you might not have added the `coder` user to the docker group?

**Comment by imbev** [comment]
I tried both the shell and docker methods of installation, and tried using the CLI from both as well.

I also added both the current user and `coder` user to the docker group.

No change. The only successful template creation was using the bare template.

**Comment by sharkymark** [comment]
Adding `coder` to the `docker` group should have fixed it. Here's another community member in Discord with the same thing in August. https://discord.com/channels/747933592273027093/1006493923658715206/1006493923658715206

So you did this? And you can verify it with the second command

```console
sudo usermod -aG docker coder

# verify users in group
grep /etc/group -e "docker"
```

**Comment by imbev** [comment]
Yes, I did that. The output of grep included the coder user.

I would prefer to avoid using `sudo chmod 666 /var/run/docker.sock` that the other user did.

**Comment by sharkymark** [comment]
Of course. I `coder templates init` to get that template to make sure nothing was wack with it. It worked for me. In my case, I have VM on GCP with the Docker engine running.

What is your config? e.g., where `coder server` is running and how you started it?

**Comment by imbev** [comment]
I'm using the default docker-compose with no changes.

**Comment by skerit** [comment]
You don't have to chmod the docker.sock file on your host server, but the one *inside* the code-server container.

**Comment by imbev** [comment]
This solved my problem.

I executed the following:

```
docker exec -it --privileged -u root 2c sh
chmod 666 /var/run/docker.sock
```
With 2c as the beginning of the container id.
