### ISSUE TITLE
Templates custom version name

### ISSUE THREAD

**Issue by cfouche3005** [coder/coder#3877]
I don't know if it's not in the documentation or if it's not implemented or I am too dump to find it but is it possible to change the version name for a template when I update or after it ?
Thanks

**Comment by kylecarbs** [comment]
@cfouche3005 you should be able to find it in the template settings for a workspace:
![image](https://user-images.githubusercontent.com/7122116/188515714-46a7256d-db66-44da-b05e-6d3a3b80da51.png)

It's also in the CLI:
![image](https://user-images.githubusercontent.com/7122116/188515724-ea63f393-f965-4ab9-b6c5-716ad6d6183d.png)

Let me know if it's not working!

**Comment by cfouche3005** [comment]
I was not talking about the template name but about the template name version
![image](https://user-images.githubusercontent.com/51720655/188561180-c85594a9-09cb-4dc1-9c5f-5b30aeb6442e.png)

**Comment by cfouche3005** [comment]
Is it possible to reopen the issue ?
Thanks
