### ISSUE TITLE
Perform /setup via CLI

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#3885]
# overview

Assuming that I've freshly installed the Coder CLI via:

```
curl -L https://coder.com/install.sh | sh
```

Then started a server in the foreground with

```
coder server
```

Then how does one automatically provision a Coder instance and bypass the need to use the GUI?

<img width="400" alt="CleanShot 2022-09-06 at 18 23 08@2x" src="https://user-images.githubusercontent.com/127353/188584938-412bc226-69cc-414b-9645-30b970157ddb.png">

After launching `coder server` I was able to automate the majority of the process via:

```
$ coder login http://localhost:3000 --email geoff@coder.com --password hunter2
> Your Coder deployment hasn't been set up!
> Would you like to create the first user? (yes/no) ^C
 
...

$ coder login http://localhost:3000 --email geoff@coder.com --password hunter2
> Your Coder deployment hasn't been set up!
> Would you like to create the first user? (yes/no) yes
> What  username  would you like? (geoff) geoff
                                                            
  Welcome to Coder, geoff! You're authenticated.            
                                                            
  Get started by creating a template:  coder templates init 
```

but human interaction was still required. I suspect there needs to be a `--username` and a `--force` or `--unattended` option?

# context

I'm building a workshop/demo that automatically installs coder (✅)), configures predefined users (❌), launches the GUI (✅) and authenticates the CLI with the predefined users (✅)

edit: `hunter2` is a gag password - https://knowyourmeme.com/memes/hunter2

**Comment by BrunoQuaresma** [comment]
> I'm building a workshop/demo that automatically installs coder (✅)), configures predefined users (❌), launches the GUI (✅) and authenticates the CLI with the predefined users (✅)

What is a day to day usage of this flow?

**Comment by bpmct** [comment]
@ghuntley There is a `--username` option which can be used to fully automate the setup of a Coder deployment that only has one user:

```sh
$ coder login http://127.0.0.1:3000 --username bencdr --email ben@coder.com --password=hello 
➜  ~ coder login http://127.0.0.1:3000 --username bencdr --email ben@coder.com --password=hello 
> Your Coder deployment hasn't been set up!
                                                            
  Welcome to Coder, bencdr! You're authenticated.           
                                                            
  Get started by creating a template:  coder templates init 
```

**Comment by bpmct** [comment]
> What is a day to day usage of this flow?

Can come in handy for workshops or tests where you want to give the deployment a default username/password.

**Comment by bpmct** [comment]
We actually use this in our develop.sh script too: https://github.com/coder/coder/blob/4e26e325a680226769dea211bc99ac44db1c80ea/scripts/develop.sh#L67-L69
