### ISSUE TITLE
Emacs in the browser via GTK Broadway

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#3887]
# overview

Noticed this pull-request by @Mainstay-Noah-Huppert over at https://github.com/coder/coder/pull/3247. Opening up this GitHub issue as a reminder to expose / document Emacs via GTK Broadway. Last year I worked with @yyoncho to make this https://www.youtube.com/watch?v=IROIt1Y-xqs happen and it would be 🤙 to ship the knowledge that Emacs can run via a browser here as well!

# tasks

Ship 👇

![CleanShot 2022-09-06 at 19 45 37@2x](https://user-images.githubusercontent.com/127353/188603598-e8d43bc5-9481-4306-b4fe-3c087cc924c7.png)

Update https://coder.com/docs/coder-oss/latest#ide-support to mention Emacs via GTK Broadway

![CleanShot 2022-09-06 at 19 42 43@2x](https://user-images.githubusercontent.com/127353/188603733-8490dc14-2696-4137-afec-985d87a772a0.png)

Update https://coder.com/docs/coder-oss/latest/ides/emacs-tramp documentation with Emacs via GTK Broadway

Update https://coder.com/docs/coder-oss/latest/ides  documentation with Emacs via GTK Broadway

# related issues

https://github.com/emacs-lsp/lsp-mode/issues/2845#issuecomment-928189778

**Comment by kylecarbs** [comment]
@ghuntley I think it'd be better to keep this in the devrel board, since there's no product dev work required to make it happen!
