### ISSUE TITLE
docs: $ coder completion

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#3888]
It appears the documentation for

```
$ coder completion
Generate the autocompletion script for coder for the specified shell.
See each sub-command's help for details on how to use the generated script.

Usage:
  coder completion [command]

Commands:
  bash        Generate the autocompletion script for bash
  fish        Generate the autocompletion script for fish
  powershell  Generate the autocompletion script for powershell
  zsh         Generate the autocompletion script for zsh

Flags:
  -h, --help   help for completion

Global Flags:
      --global-config coder   Specify the path to the global coder config directory.
                              Consumes $CODER_CONFIG_DIR (default "/home/gitpod/.config/coderv2")
      --no-feature-warning    Suppress warnings about unlicensed features.
                              Consumes $CODER_NO_FEATURE_WARNING
      --no-version-warning    Suppress warning when client and server versions do not match.
                              Consumes $CODER_NO_VERSION_WARNING
      --token string          Specify an authentication token. For security reasons setting
                              CODER_SESSION_TOKEN is preferred.
                              Consumes $CODER_SESSION_TOKEN
      --url string            Specify the URL to your deployment.
  -v, --verbose               Enable verbose output.
                              Consumes $CODER_VERBOSE

Use "coder completion [command] --help" for more information about a command.
```

does not exist yet at https://coder.com/docs/coder-oss/latest.

# specifics to document

- [ ] Explain purpose 
- [ ] Demonstrate / show the value of installing the hooks.
- [ ] Show how to install the hooks assuming someone has never installed hooks before

**Comment by bpmct** [comment]
I'm hesitant to add fine-grained documentation for each CLI command unless they are auto-generated. I updated #3522 to include CLI documentation as well. GitLab does this pretty well: https://gitlab.com/gitlab-org/cli#documentation

Alternatively, we could have a dedicated page to the CLI, as Vault does and include it as a section there, as Vault does: https://www.vaultproject.io/docs/commands#autocompletion

**Comment by bpmct** [comment]
nvm we have a perfect place for this right now https://coder.com/docs/coder/latest/cli/installation

**Comment by ghuntley** [comment]
> I'm hesitant to add fine-grained documentation for each CLI command unless they are auto-generated. 

Agreed!

> Alternatively, we could have a dedicated page for CLI, as Coder Classic and Vault does & include a section there, as Vault does:

Think there should be an exception to above for the autocompletion verb and indeed do  something similar to [commands#autocompletion](https://www.vaultproject.io/docs/commands#autocompletion)

<img width="1431" alt="CleanShot 2022-09-20 at 12 59 19@2x" src="https://user-images.githubusercontent.com/127353/191157637-3d706228-ccd9-4c7d-a4fa-dc9dcb73aa22.png">

Otherwise we are assuming folks know how to install the hooks.

https://direnv.net/docs/hook.html passes the vibe check as well.

<img width="1372" alt="CleanShot 2022-09-20 at 13 01 01@2x" src="https://user-images.githubusercontent.com/127353/191157837-c1874c24-cb8d-4ce1-a6ec-1f654738945a.png">
