### ISSUE TITLE
General pagination

### ISSUE THREAD

**Issue by ammario** [coder/coder#3907]
We want to support deployments with hundreds of users by the end of the year. Many of our current views do not support this kind of scale.

- [x] Paginate Workspaces page
- [x] Paginate Users page
- [x] #4518
- [x] Only support pagination on resource lists with a search present
- [x] Do not force pagination so API/CLI usage is not paginated (e.g. optional query params)
- [x] make it mobile friendly (maybe only prev, current, next)
- [x] #5092
- [x] refactor all pagination (Users, Workspaces, and Audit Log) to use window functions so that there is one endpoint and one SQL query per paginated feature

We can leave the Templates page as is. We assume the number of templates will grow logarithmically with the number of users. 

In the future we may want to paginate:
- Groups page
  -  users within groups
- Build log
But they're not a priority now.

We'll follow the pattern of pagination used in the Audit Log - limit/offset style pagination, with controls allowing the user to go forward, back, or to a specific page.

We will not apply pagination to the CLI because losing an entry due to the limit/offset style could be problematic there.

Each page needs both the item fetching to be paginated and a count endpoint. They're separate endpoints so that the count one can be called less frequently, as it's more expensive.

**Comment by BrunoQuaresma** [comment]
I like this, but I would wait until we have a customer requesting that.

**Comment by bpmct** [comment]
We've seen a few requests for this - this is particularly painful for workspaces that have been alive for over 30 days since the build log gets quite long

**Comment by ammario** [comment]
> We've seen a few requests for this - this is particularly painful for workspaces that have been alive for over 30 days since the build log gets quite long

https://github.com/coder/coder/pull/4436 fixes this case specifically.

**Comment by bpmct** [comment]
Let's hold off on doing other pages besides `Users` and `Workspaces`
