### ISSUE TITLE
parse error in apk version both arm 64 and arm 7 arch --trying to install in android 

### ISSUE THREAD

**Issue by obitoo7** [coder/coder#3951]

**Comment by matifali** [comment]
This is for [Alpine Linux](https://www.alpinelinux.org/), not Android.

**Comment by kylecarbs** [comment]
@obitoo7 could you provide the error? I'm a bit confused by what "parse error" means in this context. Is it for running the binary?

**Comment by obitoo7** [comment]
> @obitoo7 could you provide the error? I'm a bit confused by what "parse error" means in this context. Is it for running the binary?

Iam having issue while installing in android as an app

**Comment by obitoo7** [comment]
> @obitoo7 could you provide the error? I'm a bit confused by what "parse error" means in this context. Is it for running the binary?

Okay thanks 
But is there any way to install in Android as an app
If you have pls inform me about it

**Comment by matifali** [comment]
> > @obitoo7 could you provide the error? I'm a bit confused by what "parse error" means in this context. Is it for running the binary?
> 
> Okay thanks, But is there any way to install on Android as an app If you have pls inform me about it

This is not intended to be USD as an Android app. To use on android, maybe you can use [code-server](https://github.com/coder/code-server) and then access your server from your browser. It does not require installing anything on an Android device.
