### ISSUE TITLE
`Last Used` doesn't seem to be accurate

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3952]
Version: [`v0.8.13+ad24404`](https://github.com/coder/coder/commit/ad24404018f94414ed712ce31dc85baa49dbd08f)

I have several workspaces running and one has a projector IDE running, but I am not understanding why it says `last used` an hour ago. Maybe I misunderstand the purpose of this column but I am confused.

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/2022166/189074633-39e1efa3-294f-4f53-9452-4c72a314776b.png">

**Comment by sharkymark** [comment]
From keeping the workspace dashboard up, it appears to change to `Now` a few minutes after the IDE is open. Wonder why? Should be instant.

**Comment by sharkymark** [comment]
Ok, opened PhpStorm, and it says `Never` 
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/2022166/189096754-467ed073-a69f-40c5-847d-663e7500ff4f.png">

**Comment by ammario** [comment]
In the default behavior it takes 10 minutes of usage to update. We should either change the language or improve the architecture.

**Comment by BrunoQuaresma** [comment]
@sharkymark Do you think having a "help/info" tooltip on the "Last Used" header telling the user the "Last Used" value is updated every 10 minutes would be good enough?

**Comment by ammario** [comment]
I believe https://github.com/coder/coder/pull/4115 solved this.
