### ISSUE TITLE
Provide mechanism to adjust email_verified requirement for OIDC

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#3954]
- Using AzureAD OIDC provider with OSS.
- Coder fails with email_verified claim missing please verify email address.
- AzureAD does not emit this claim by default. See https://docs.microsoft.com/en-us/answers/questions/812672/microsoft-openid-connect-getting-verified-email.html
- After adding custom claim to AzureAD it errors with:
```
{"message":"Failed to extract OIDC claims.","detail":"json: cannot unmarshal string into Go struct field .email_verified of type bool"}
```
- I don't see how to configure AzureAD to have that come through as a bool instead of string.

Ideally there would be ability to disable/adjust this verification option based on OIDC provider. At the moment it just fails without option: https://github.com/coder/coder/blob/ad24404018f94414ed712ce31dc85baa49dbd08f/coderd/userauth.go#L227

**Comment by kylecarbs** [comment]
Makes sense. I'll fix this today and publish a new release!

**Comment by kylecarbs** [comment]
@dcarrion87 I'm making this only respect `email_verified` if it's provided... that seems like it should work!

**Comment by kylecarbs** [comment]
@dcarrion87 v0.8.14 is coming out now! https://github.com/coder/coder/runs/8251205763?check_suite_focus=true

**Comment by kylecarbs** [comment]
It's out :partying_face:
