### ISSUE TITLE
community: GitHub issue templates

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#3971]
Create templates for open source contributors to get help more easily and create more structured open source issue submissions

ie. 

<img width="675" alt="CleanShot 2022-09-09 at 16 34 26@2x" src="https://user-images.githubusercontent.com/127353/189286475-cc3e9f40-20f1-4bdf-a8bf-16b341071628.png">

**Comment by bpmct** [comment]
see #3936

**Comment by bpmct** [comment]
Closing as not planned 

https://github.com/coder/coder/pull/3936#issuecomment-1241462385
