### ISSUE TITLE
docs: Configuration of Coder w/OpenID Connect

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#3988]
Related to [internal notes](https://www.notion.so/coderhq/Notes-for-2022-08-12-2c0246e89fff42e38d400b1d4d1718bc):

> "We tried to configure OIDC; where is this documented?"

**Comment by kylecarbs** [comment]
We have this [here](https://coder.com/docs/coder-oss/latest/admin/auth#openid-connect-with-google) right now, but can generalize the wording for sure.

**Comment by bpmct** [comment]
@ghuntley do you think we can close this issue since it's documented?

**Comment by ntimo** [comment]
I just wanted to say that the documentation worked for me, in order to use Authelia together with Coder for OIDC.
