### ISSUE TITLE
Open Folder in coder server web IDE

### ISSUE THREAD

**Issue by klauserber** [coder/coder#3989]
Hello,

Here is my setup:

Kubernetes 1.25
coder 0.8.14
code-server 4.7.0

code-server is installed in the container image:

```dockerfile
ARG CODE_SERVER_VERSION=4.7.0
RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=${CODE_SERVER_VERSION}
```
and there is a coder_app resource in the template:

```terraform
resource "coder_app" "code-server" {
  agent_id = coder_agent.devbox.id
  name     = "code-server"
  url      = "http://localhost:13337/?folder=/home/coder"
  icon     = "/icon/code.svg"
}
```

The coder-server IDE is working fine expect for the File|Open Folder... functionality. Open a Folder other than /home/coder hangs for a while and after that a error message appears:

**An unexpected error occurred that requires a reload of this page.**
The workbench was unexpectedly disposed while running.

The GET request (e. g. https://.../?folder=/home/coder/other-folder) from the browser gets no response.

The js console shows this message

```
  ERR Unable to write file 'vscode-log:/20220910T171919/window.log' (Error: IndexedDB database 'vscode-web-db' is closed.): Error: Unable to write file 'vscode-log:/20220910T171919/window.log' (Error: IndexedDB database 'vscode-web-db' is closed.)
    at u.writeFile (https://coder.app.int.isium.de/@kerber/devbox.devbox/apps/code-server/stable-784b0177c56c607789f9638da7b6bf3230d47a8c/static/out/vs/workbench/workbench.web.main.js:603:16323)
    at async Object.factory (https://coder.app.int.isium.de/@kerber/devbox.devbox/apps/code-server/stable-784b0177c56c607789f9638da7b6bf3230d47a8c/static/out/vs/workbench/workbench.web.main.js:604:3)
``` 

This **does not** happen by using code-server directly via a port forward.

But it **does** happen by using the coder UI via a port forward. So I think there is some wrong with the redirect from coder to code-server and not with the network path behind it (nginx controller and haproxy in my case).

**Comment by kylecarbs** [comment]
Hey @klauserber :wave: This is due to some networking issues! We have new experimental networking out under a hidden flag. Set `CODER_TAILSCALE=true` when starting `coder server` to try it out.

**Comment by klauserber** [comment]
@kylecarbs Thank you! That works like a charm. It solves the problem and it's much more responsive over all (IDE startup, open folder, open terminal) in my environment.

just for curiosity: Tailscale is wireguard based networking, right? Are there any pitfalls because it's an experimental feature?

**Comment by sharkymark** [comment]
@klauserber glad you got unstuck. We will be making our networking based on this Tailscale OSS approach (yes based on Wireguard) the default in a near future release.

@kylecarbs wrote a good issue #2779  on why we are doing this. Lessons learned from Coder v1.

**Comment by kylecarbs** [comment]
It'll become default next week @klauserber, so it's entirely safe to use. _Maybe_ we'll find some oddities in the next few days, but seems unlikely based off usage we've seen so far.

**Comment by klauserber** [comment]
@kylecarbs Thank you very much for the infos, I'am thrilled!
