### ISSUE TITLE
chore: document or tool tip what the Last Used colors mean

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#3993]
As a developer, I do not like seeing different colors on my workspaces and not knowing what they mean.

I had to `grep` around Coder OSS for the Last Used column on the workspaces list view `WorkspacesTable/WorkspacesRow` to figure this out.

This should be documented, but I am not sure it is helpful to say a workspace hasn't been used for 3 days, 1 month and 1 year. That sounds so arbitrary and decided by an unknown engineer who wrote this.

[TypeScript source](https://github.com/coder/coder/blob/main/site/src/components/WorkspacesTable/WorkspaceLastUsed.tsx)

[Docs page that should be built out](https://coder.com/docs/coder-oss/latest/workspaces)
OR
Have a UI tool tip (preferred)

## Details
```typescript
  if (t.isAfter(now.subtract(1, "hour"))) {
    color = colors.green[9]
    // Since the agent reports on a 10m interval,
    // the last_used_at can be inaccurate when recent.
    message = "Now"
  } else if (t.isAfter(now.subtract(3, "day"))) {
    color = theme.palette.text.secondary
  } else if (t.isAfter(now.subtract(1, "month"))) {
    color = theme.palette.warning.light
  } else if (t.isAfter(now.subtract(100, "year"))) {
    color = colors.red[10]
  } else {
    // color = theme.palette.error.light
    message = "Never"
    displayCircle = false
  }
```

**Comment by BrunoQuaresma** [comment]
@ammario if you could use labels for each color what would you use?

**Comment by ammario** [comment]
> This should be documented, but I am not sure it is helpful to say a workspace hasn't been used for 3 days, 1 month and 1 year. That sounds so arbitrary and decided by an unknown engineer who wrote this.

This was done by me, and the intention is to aid in the identification of unused workspaces. Ideally we do not have to document minor UI details like colors since they should either be self-explanatory or unnoticable.

> @ammario if you could use labels for each color what would you use?

I'm not sure what you mean by that?

**Comment by BrunoQuaresma** [comment]
We can add a tooltip with that to help users understand the colors, something like:
- Green is "Used today"
- Orange is "Not used in the last 2 days"
- Red is "Not used in a week"

Makes sense?

**Comment by kylecarbs** [comment]
I'm going to close this for now. The time wasn't updating properly before, which is what made this confusing.
