### ISSUE TITLE
Docker in Docker?

### ISSUE THREAD

**Issue by imbev** [coder/coder#4002]
Using the https://github.com/coder/coder/tree/main/examples/templates/docker-code-server template, I am unsure how to allow run docker containers within a workspace.

**Comment by kylecarbs** [comment]
Hey @imbev :wave:. We have an issue tracking these docs right now #3376.

Internally, all of us Coders develop on a single large VM using Docker with `sysbox` as the runtime.

See: 
- ["VM-like" containers with Docker + Sysbox](https://asciinema.org/a/kkTmOxl8DhEZiM2fLZNFlYzbo?speed=2)
- ["runtime" option on the Docker Terraform provider](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/resources/container#runtime)
- [Our dogfood image which runs `dockerd` on startup](https://github.com/coder/coder/blob/main/dogfood/main.tf#L26-L38)

If you have any questions, please leave comments on this issue! I'm happy to help.

**Comment by imbev** [comment]
Because I am using opensuse instead of a debian-based system, I cannot use sysbox.

Is there a way to use the host `/var/run/docker.sock` ?
