### ISSUE TITLE
feat: add `--install-terraform` command-line flag to enable or disable automatic tf installation

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#4006]
# Problem

When initializing the Terraform provisioner, we initially check to see if the Terraform binary is installed.

https://github.com/coder/coder/blob/43f368dfc4a0192c1e4772f535e6be59bbcdee50/provisioner/terraform/serve.go#L87

If it is not installed, we install it on demand "automagically".
This can lead to strange issues, and is a red flag for folks who want to install Coder in an air-grapped environment. 
It also increases startup time and isn't a great experience for folks with slow or unstable connections.

# Proposed Solution

Add a `--install-terraform=(true|false)` command-line flag to control the auto-download-terraform behaviour.
Default to the current auto-download behaviour, allow switching off.

Additionally, if we fail to find the Coder binary in $PATH, we should show details of where we looked as it's currently not clear.

**Comment by bpmct** [comment]
I don't think I fully understand how an `--install-terraform` flag would help here. As you mentioned, Coder will scan to see if Terraform is in the same directory as `coder` or in PATH. If not, it will attempt to download Terraform.

If Coder has no external network access, Coder will fail and leave an error that it failed to download Terraform. However, the admin can fix this by downloading Terraform onto their image as outlined in [offline deployments](https://coder.com/docs/v2/latest/install/offline). If the admin was to set `--install-terraform=false`, they would still have to do the steps to manually add it to their deployment anyways. 

Perhaps we could just make a better error message when Coder detects it can't reach out Terraform? The server should still fail (or display a warning in the CLI/GUI) if Terraform is not present.

**Comment by bpmct** [comment]
Gonna close for now. Let me know if I'm missing something.

On a kind of related note, our install script also has support for installing Terraform: `--with-terraform`
