### ISSUE TITLE
bug: Flashing `agent` health check occurs even when the workspace is off.

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4033]
Version: [`v0.8.14+e1afec6`](https://github.com/coder/coder/commit/e1afec6db4cb72b4dbc8d955fab20dc5b369243c)

I understand there is a health check of the Coder agent when in the workspace dashboard.

But it is odd behavior that if in the workspace list screen it shows a workspace `stopped` that it hovers in `connecting` status and the health check flashing icons when I drill into a stopped workspace's dashboard.

The code should know the workspace is off and not do the health check.

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/2022166/189772087-1a2000b7-bec6-4e6e-bd7c-c7374205567e.png">

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/2022166/189772431-321ace71-5f12-4ba4-9c0c-8efa8acfdabc.png">

**Comment by kylecarbs** [comment]
When offline, the agent shouldn't appear at all!

**Comment by sharkymark** [comment]
That would make sense wouldn't it
