### ISSUE TITLE
Cannot run Coder on a subpath

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4035]
A community member ran into some issues running Coder on a path (https://mydomain.com/coder) and I was able to reproduce it. 

![Screen Shot 2022-09-12 at 9 51 15 PM](https://user-images.githubusercontent.com/22407953/189796891-e7e197ee-19f7-41ba-b2a1-8294e31d5605.png)

**Comment by kylecarbs** [comment]
I don't think we should fix this one... it's *really* difficult for us to guarantee that it works.

**Comment by kylecarbs** [comment]
I assume they're using nginx or something?

**Comment by bpmct** [comment]
Yeah, I reproduced with Caddy as well.

**Comment by mafredri** [comment]
In theory it might be fixable with a `<base href="/[subdir/]">` tag (something that coder server could rewrite on the fly), but there could be repercussions and we may need to write URLs in the frontend in a different way than we have up until now. It could also add extra maintenance burden to ensure both methods work.

**Comment by kylecarbs** [comment]
This is doable with react router, but does add maintenance overhead. If more people request this, we shall do it!

**Comment by DaiYuANg** [comment]
Need sub path support at Nginx too
