### ISSUE TITLE
Custom proxy error page

### ISSUE THREAD

**Issue by deansheather** [coder/coder#4040]
When proxying, instead of rendering the dashboard with an error page we should render a small non-SPA HTML file that contains the error message and a button to refresh, a button to go to dashboard (controlled by Go templates).

We have this in v1 for when you get proxy errors. It can be reproduced by creating a dev url and trying to connect to it without starting an app on that port first:
![image](https://user-images.githubusercontent.com/11241812/189941873-57247782-accc-491f-9d44-02d9c8765fb1.png)

## Requirements
1. Completely self-contained page, with no `<link rel="stylesheet" ...>`s or `<script src="..."/>`s
2. Go template variables for:
    - status code `Error.Status`
    - error title `Error.Title`
    - error description `Error.Description`
    - optional button to reload based on `Error.Reloadable`
    - button to redirect to dashboard `Error.DashboardURL`
3. Stored at `site/static/simple-error.html` or something like that

**Comment by deansheather** [comment]
We shouldn't put this in the frontend application because then we can't serve it from subdomains like I said in https://github.com/coder/coder/pull/3753#discussion_r969774372

Having it as a separate single HTML file means we can easily render and return this from subdomains without having to worry about API requests or serving stylesheets/JS properly.

**Comment by BrunoQuaresma** [comment]
@deansheather just checking, would be enough to have a `502.html` template in the static files?

**Comment by deansheather** [comment]
@BrunoQuaresma sorry for late reply, but we'd probably want something even more generic like error.html or something that has some go template variables
