### ISSUE TITLE
Add cloud CLIs to Dockerfile

### ISSUE THREAD

**Issue by endingwithali** [coder/coder#4043]
We should install CLIs for AWS, GCP, Azure and DigitalOcean so the Dockerfile actually works for most clouds.

Also, we should update the location of the injected Coder binary so you dont have to do `/opt/coder`

- [ ] update docker file to include installs
- [ ] create documentation for installing each cli in the docker file based off quickstart commands 
- [ ] update coder location for optimizing 

### resources 
- https://github.com/coder/coder/blob/main/scripts/build_docker.sh
- [release workflow](https://github.com/coder/coder/blob/main/.github/workflows/release.yaml#L145)

**Comment by bpmct** [comment]
With the major clouds, you don't actually need the CLI installed inside the container/dockerfile. Instead, you need to run the container with the proper environment variables or volumes.

For example, with AWS, you just need an `$HOME/.aws/credentials` file, but not actually the CLI (it can come in handy for generating the file, but you can write it yourself). Alternatively, you can run the containers with the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment. 

Same is the case with [Google Cloud](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference) (`GOOGLE_APPLICATION_CREDENTIALS`), [Azure](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) (`ARM_CLIENT_ID`, `ARM_CLIENT_SECRET`), and [DigitialOcean](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs) (`DIGITALOCEAN_TOKEN`)

Bundling the cloud CLIs in means you also would need to have a persistent volume to store the files. Instead, I'd suggest the environment variable method and running the container with the environment variable mounted:

```sh
export CODER_DATA=$HOME/.config/coderv2-docker
mkdir -p $CODER_DATA
docker run --rm -it \
  -e CODER_TUNNEL=true \
  -e AWS_ACCESS_KEY_ID=coder \
  -e AWS_SECRET_ACCESS_KEY=iscool \
  -v $CODER_DATA:/home/coder/.config \
  -v /var/run/docker.sock:/var/run/docker.sock \
  ghcr.io/coder/coder:latest
```

**Comment by bpmct** [comment]
There may be some use cases where folks want the CLI installed within the container to create short-lived tokens, etc. but it's difficult to predict these use cases and would suggest folks build their own images with Coder with the necessary tools and mechanisms to authenticate.

For example, for people running in Kubernetes, a `ServiceAccount` can be attached to the coder pod to give coder the proper permissions to provision stuff and then the serviceaccount rotates credentials.
