### ISSUE TITLE
Log access url when running config-ssh

### ISSUE THREAD

**Issue by jsjoeio** [coder/coder#4044]
## Problem
Yesterday I was testing something and using the coder tunnel. I then switched to the dev.coder.com deployment but forgot to `login` before running `coder config-ssh`. It wasn't until a couple minutes later I realized I was logged-in to the wrong deployment

## Solution
Print the access/login url so I know which deployment I'm running `config-ssh` with.

**Comment by jsjoeio** [comment]
@kylecarbs @bpmct would love to get a second opinion on this, specifically is it worth doing?

**Comment by kylecarbs** [comment]
I think a different command like `coder config url` or `coder url` that outputs your current deployment URL would be better.

**Comment by jsjoeio** [comment]
That's a neat idea! Although I don't know if it would have helped here unless `config-ssh` printed a message like `No changes to make. Run coder url to output your current deployment URL`.

I'd like more validation from other users that this is worth doing though so I think I'll hold off for now.

**Comment by bpmct** [comment]
I think we should hold off for now too. I run into this frequently when changing deployments but I don't think we should rely on `config-ssh` to surface this. For example, I run into it most often when I log into VS Code Remote and my hosts don't work anymore.

The `coder url` solution comes to mind as well as some way to log into multiple deployments. I'm going to close this for now to reduce issues in the tracker, but would love to eventually have a multi-deployment scenario.
