### ISSUE TITLE
Automate set up of coder deployment

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#4049]
Hi Team

I'm looking to automate coder deployments and one thing I'm trying to work out is automating the part where you have to generate the initial admin user.

Is there provision for this without having to run SQL against the postgres database directly? Sorry if I missed some already existing docs for this.

**Comment by kylecarbs** [comment]
Hey @dcarrion87 👋! Our "coder login" command supports username, email, and password flags for this purpose.

Let me know if that works for you!

**Comment by dcarrion87** [comment]
I didn't even try that! Works perfect.

**Comment by dcarrion87** [comment]
Hi @kylecarbs just reopening this as my mechanism of running a `coder login` for automated creation when a new instance is created stopped working at some point between 0.9.0 and 0.12.4. 

What is the best practice method for automatically configuration the base "break glass" user when an instance is first provisioned for newer versions instead of relying on someone visiting the web page on first creation?

We're regularly provisioning / de-provisioning for system testing and it's a bit awkward now having to visit the page manually initially to copy paste values from secret vault.

**Comment by kylecarbs** [comment]
This was changed here: https://github.com/coder/coder/commit/0f3221f9d085788c4f9734c7a66f04ad6ab8d017. It first went out in [v0.9.9](https://github.com/coder/coder/releases/tag/v0.9.9).

The env vars now just have `FIRST` in them, and that should be safe to use for now.
