### ISSUE TITLE
bug: User is not redirect to /setup when there is no first user

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4050]
Inspired by #3813 

1. When you install Coder for the first time, it takes you to the `/workspaces` page instead of `/setup` and you have to go `/setup` in the URL. I run into this frequently when installing on new VMs, easy to reproduce with the tunnel (perhaps it saves the cookie wrong?)

<img width="1109" alt="Screen Shot 2022-09-13 at 8 18 36 PM" src="https://user-images.githubusercontent.com/22407953/190037108-70b979cf-2703-48e6-bef6-3a03d715df12.png">

**Comment by BrunoQuaresma** [comment]
Interesting, if you install and access the dashboard from an anonymous window, does it work?

**Comment by bpmct** [comment]
> Interesting, if you install and access the dashboard from an anonymous window, does it work?

Same thing happens with incognito. I can hop on a call to reproduce if that'd help
