### ISSUE TITLE
Kubernetes Install docs include wrong PG hostname

### ISSUE THREAD

**Issue by jamesottaway** [coder/coder#4054]
The [docs suggest](https://github.com/coder/coder/blob/main/docs/install/kubernetes.md?plain=1#L63-L70) this PG URL:

```
postgres://coder:coder@postgres-postgresql.coder.svc.cluster.local:5432/coder?sslmode=disable
```

When following the instructions I got the following from `helm install coder-db bitnami/postgresql`:

```
❯ helm install coder-db bitnami/postgresql \
    --namespace coder \
    --set auth.username=coder \
    --set auth.password=coder \
    --set auth.database=coder \
    --set persistence.size=10Gi

…

PostgreSQL can be accessed via port 5432 on the following DNS names from within your cluster:

    coder-db-postgresql.coder.svc.cluster.local - Read/Write connection
```

I didn't notice the different hostname until I checked the pod's logs and found this:

```
ping postgres: dial tcp: lookup postgres-postgresql.coder.svc.cluster.local on 10.96.0.10:53: no such host
```

Is this just a simple update based on a change in the PG Helm chart, or is there a better way to get the hostname out of the PG pod?

**Comment by jamesottaway** [comment]
Oh, duh, it must be a typo not a breaking change in the Bitnami chart. I just added this to my existing docs PR: #4053

**Comment by bpmct** [comment]
Whoops - good find!
