### ISSUE TITLE
Workspace page should display real-time data

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#4058]
Right now, it's faster to refresh the workspace page to get new data than it is to wait for polling to occur. We should hook up the workspace page to use SSE so that data is real-time.

**Implementation Notes**:
We are moving forward with SSE instead of WebSockets because this is easier to implement on the BE and also the information flow we need is unidirectional. In the future, we should use SSE across Coder when we can, for consistency. To this aim, the build log page should be updated eventually to rely on SSE as well.

**Comment by f0ssel** [comment]
I've got an in-progress PR of an backend route that will pump the workspace state over an SSE - https://github.com/coder/coder/pull/4060
