### ISSUE TITLE
Workspace says `Running` but status says `disconnected`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4072]
Version: [`v0.8.14+e1afec6`](https://github.com/coder/coder/commit/e1afec6db4cb72b4dbc8d955fab20dc5b369243c)

Workspace says `Running` but status says `disconnected`

Pod is no longer running in the namespace but PVC still there.

So not sure what killed the pod, but Coder OSS doesn't seem to know that happened.

Stopping (an already gone pod) the pod worked and restarted brings it back.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/2022166/190305698-54455a3a-939f-4719-a6da-947adb694899.png">

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/2022166/190305634-db23f537-33c4-4a9b-ba03-c57943696d2e.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/2022166/190305842-9f96c502-8cbf-4ad4-b971-77435ecd1502.png">

<img width="994" alt="image" src="https://user-images.githubusercontent.com/2022166/190305958-79385d95-8a3c-4ada-9845-93483dbfaf71.png">

**Comment by bpmct** [comment]
Ideally, this never happens, but there may be cases where something outside of Coder's control kills a pod. I'm not sure if we should "stop" the workspace in this case, but definitely think we should show a disconnect reason. Thoughts @kylecarbs?

**Comment by BrunoQuaresma** [comment]
Maybe related to https://github.com/coder/coder/issues/4095?

**Comment by bpmct** [comment]
Closing in favor of #4679
