### ISSUE TITLE
Replace `var.name` with a pretty name

### ISSUE THREAD

**Issue by matifali** [coder/coder#4073]
![image](https://user-images.githubusercontent.com/10648092/190321527-0cb2e3f7-9c41-4e60-89af-ba858e36e65f.png)

**Comment by matifali** [comment]
For example
`var.ram` can be **Total RAM**
`var.cpu` can be  **CPU Cores**
`var.docker_image` **Docker Image**

**Comment by BrunoQuaresma** [comment]
Since these var names are dynamic and came from terraform I don't see how we could use better names 🤔 Any ideas?

**Comment by matifali** [comment]
Yes I understand why it can't be done. Terraform HCL does not provide any field to be used for pretty ne. We can't use description as it's longer.  
May be a data in coder provider can be used to create a toilet for every variable.

**Comment by BrunoQuaresma** [comment]
cc.: @bpmct

**Comment by bpmct** [comment]
We have a plan to replace `variable` with a `coder_parameter` data source. The scheme is TBD but it would allow us to have friendly names, validate on the frontend, and mark specific variables as immutable. related: #802 

For example, 

```hcl
data "coder_parameter" "cpu" {
  friendly_name = "CPU Cores"
  description = "Lorem ipsum"
  immutable = false
}

resource "some_resource" "dev" {
   cpu = data.cpu.value
}
```

Legacy `variables` would be supported, but wouldn't show up as pretty in the dashboard

There are other ways we could do it without that (e.g. mapping common terms in the backend, replacing underscores with spaces), but I think we should wait until we have more controls with `coder_parameter` :).

**Comment by bpmct** [comment]
We should keep this issue open until there is a way to do that, though :)

**Comment by BrunoQuaresma** [comment]
This is done in the latest version
