### ISSUE TITLE
Filter audit log entries from the dashboard

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4077]
In Coder Classic, we had filters on the audit log page which made it easy to find specific actions, users, and resources in the log.

I read through our audit log RFC and didn't see feedback about the Ui filters so I think we should make the same options available in this version.

![image](https://user-images.githubusercontent.com/22407953/190469196-a005389f-c51c-4b08-8455-fc2d20248697.png)

We discussed it in Slack and think we have a good way of using our query language (already used in the workspaces page) + inputs so that the user can do basic filters without learning the query language.

**Comment by BrunoQuaresma** [comment]
@kylecarbs @bpmct I'm going to add as well filtering support for:
- resource_id
- resource_target (since we use names for some resources and getting the ID can't be easy)
- username
- user_email 

Thoughts?

**Comment by bpmct** [comment]
Is this, in addition, to support for `action` and `resource type`?

Will both `username` and `email` be in the UI? If so, I think that'll be a bit confusing. Supporting both via manual filters or API seems super nice and convenient

**Comment by BrunoQuaresma** [comment]
action and resource type are actually implemented in BE 😄
