### ISSUE TITLE
`version` unknown on a newly `running` workspace

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4082]
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

I created a new workspace and do not see a `version` Other workspaces started now show a `version`

<img width="272" alt="image" src="https://user-images.githubusercontent.com/2022166/190509828-7ef975cf-2d02-4edd-9808-f44bd4740d21.png">

**Comment by matifali** [comment]
I was facing this on 0.8.14 too.|
Version Unknown for one of my workspace but for another user version is displaying just fine

**Comment by kylecarbs** [comment]
I already know the issue here. Fixing soon!

**Comment by bpmct** [comment]
related #4222
