### ISSUE TITLE
DERP flags not exposed in coder-server --help

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4083]
[Our documentation](https://coder.com/docs/coder-oss/latest/networking) describes how to configure custom DERP servers but you cannot see this in `--help`.

**Comment by kylecarbs** [comment]
Ahh, right. They have little disabled flags. You can just remove those all it'll all appear! I can in a bit too.

**Comment by bpmct** [comment]
I prob should have just looked at the code - I got it.

**Comment by kylecarbs** [comment]
I just took care of it real swift: https://github.com/coder/coder/pull/4103
