### ISSUE TITLE
docs: administration/troubleshooting

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#4085]
Somewhere under the administration (?) section would likely be a place for "trouble shooting logs" aka where to look if something has gone wrong.
 
From discord:

> Try checking /tmp/coder-startup-script.log. We'll be making this visible in the UI pretty soon.

 https://discord.com/channels/747933592273027093/1020078314813141002/1020081158911967282

**Comment by bpmct** [comment]
Ah, we have this [troubleshooting under templates right now](https://coder.com/docs/coder-oss/latest/templates#creating--troubleshooting-templates) but could see how the troubleshooting steps would come in handy for when a previously-working template broke.
