### ISSUE TITLE
What is Coder Embedded Relay?

### ISSUE THREAD

**Issue by matifali** [coder/coder#4087]
![Screenshot from 2022-09-16 12-29-22](https://user-images.githubusercontent.com/10648092/190606524-9915897f-248e-4a1c-b790-177961b1da5a.png)

My code server runs on my local network, and the ping from inside the workspace to my machine is 0.3 ms.
Also0 ping from my machine to the machine running the coder server is 0.3 ms.
But why coder is showing Coder embedded relay as about 65 ms?
Is it some type of latency?

**Comment by BrunoQuaresma** [comment]
cc. @kylecarbs

**Comment by bpmct** [comment]
This is a built-in DERP server that relays connections if your local machine isn't able to make a direct connection to the workspace. It is surprising the ping is that high, however. Is your workspace on the same machine as the Coder server (e.g. a Docker container)? What is the ping when you run `coder speedtest <workspace>`?

We have some documentation on this here: https://coder.com/docs/coder-oss/latest/networking

**Comment by kylecarbs** [comment]
@matifali are you using `--tunnel`? It could be the distance to that?

**Comment by matifali** [comment]
No tunnel end also it's on the same machine. 
`coder speedtest` doesn't show ping.

**Comment by kylecarbs** [comment]
@matifali we'll be doing a new release soon that should fix this. I believe #4190 will help it.
