### ISSUE TITLE
Unexpected error, shutting down server: install terraform: context deadline exceeded

### ISSUE THREAD

**Issue by A-K-N-B** [coder/coder#4090]
when i setting up new account terminal shows error like this:

Unexpected error, shutting down server: install terraform: context deadline exceeded
Shutting down API server...
Gracefully shut down API server
Waiting for WebSocket connections to close...
Done waiting for WebSocket connections
Stopping built-in PostgreSQL...
Stopped built-in PostgreSQL
install terraform: context deadline exceeded
Run 'coder server --help' for usage.

**Comment by kylecarbs** [comment]
#4129
