### ISSUE TITLE
Incorrect workspace status - and message saying workspace building

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4095]
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

A workspace must have shutdown normally (based on time).

But the UI still says running, so I click Stop, and get a message saying a workspace is building.

Looking at the pods, I did not tell it to build, and the pod isn't there, which is correct.

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/2022166/190709158-9d0eca11-3f69-4a20-a02c-d5aba9af5242.png">

<img width="473" alt="image" src="https://user-images.githubusercontent.com/2022166/190709307-8350af93-1738-426b-9a1d-3ef8b9a67559.png">

**Comment by sharkymark** [comment]
This is a bricked state. Stop does not do anything. i.e., I can't start the workspace.

**Comment by kylecarbs** [comment]
This seems like a pretty bad bug... I'll investigate.

**Comment by BrunoQuaresma** [comment]
@kylecarbs did you have time to investigate this? Maybe, Do our recent changes to "status calculation" would help/solve this issue? Related: https://github.com/coder/coder/pull/4361

**Comment by kylecarbs** [comment]
@BrunoQuaresma I haven't.

@sharkymark are you able to reproduce this?
