### ISSUE TITLE
Coder not using MacOS name resolution mechanism

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#4097]
When using VPN such as tailscale it updates nameserver without updating resolv.conf.

Most processes resolve just fine but coder seems to have problems.

E.g. When trying to use coder login:

```
coder login https://REDACTED.REDACTED.ts.net
Failed to check server "https://REDACTED.REDACTED.ts.net" for first user, is the URL correct and is coder accessible from your browser? Error - has initial user: do: Get "https://REDACTED.REDACTED.ts.net/api/v2/users/first": dial tcp: lookup REDACTED.REDACTED.ts.net on 8.8.8.8:53: no such host
Run 'coder login --help' for usage.
```

When using other tools. E.g. ping:

```
> ping REDACTED.REDACTED.ts.net

PING REDACTED.REDACTED.ts.net (100.85.22.44): 56 data bytes
64 bytes from 100.85.22.44: icmp_seq=0 ttl=64 time=45.126 ms
64 bytes from 100.85.22.44: icmp_seq=1 ttl=64 time=48.419 ms
```

E.g. curl:

```
> curl https://REDACTED.REDACTED.ts.net

<!doctype html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#17172E"/><meta name="application-name" content="Coder"/><meta property="og:type" content="website"/><meta property="csp-nonce" content=""/><meta property="csrf-token" content="J9Ag5EQDay6wx8VAWewJvzwirdYakOq3x9QdxB+uocyb/OU5inQF8iJ7nVbO7SwAbnBWPeR75o6LMiQCs42mRg=="/><meta id="api-response" data-statuscode="0" data-message=""/><link rel="alternate icon" type="image/png" href="/favicons/favicon.png" data-react-helmet="true"/><link rel="icon" type="image/svg+xml" href="/favicons/favicon.svg" data-react-helmet="true"/><script defer="defer" src="/bundle.809524c30b22690bf571.js"></script><link href="/main.6978d5569b46e6b28654.css" rel="stylesheet"></head><body><div id="root"></div></body>%
```

**Comment by dcarrion87** [comment]
I suspect here this is causing it: https://github.com/coder/coder/blob/63fd4945a2b7b296eee1a4d7a3e7b970ed4c43d7/scripts/build_go.sh#L129

`CGO_ENABLED=0` won't use the system DNS resolver.

I'm guessing setting this was intentional for conformity?

**Comment by kylecarbs** [comment]
We can enable `CGO` for MacOS. It's trickier for Linux because of different flavors.

**Comment by deansheather** [comment]
Until this is fixed, you can work around this by creating a DNS entry pointing to your IP address on a public domain, or you could use a service like https://nip.io to get a global DNS entry pointing to your tailscale IP address.

**Comment by dcarrion87** [comment]
Thanks @deansheather. We're trying to leverage Tailscale MagicDNS / HTTPS records. We have a manual workaround at the moment to make sure Mac users can resolve. Definitely not a show stopper, more of an additional overhead to the out of the box experience. We'll consider global DNS if the scope gets larger.

**Comment by NiklasRosenstein** [comment]
Hey @dcarrion87 what's your workaround? We're currently experiencing the same issue with Tailscale + Coder.

**Comment by dcarrion87** [comment]
@NiklasRosenstein users are maintaining host entries. The users are fairly technical so understand having to resolve using Mac native tools and update their host entires.

We are going to need to do something more permanent soon as this is starting to become unruly. Especially when there's an event that changes the Tailscale machine IP. Overhead we'd rather not have with this project.

**Comment by dcarrion87** [comment]
@kylecarbs any news on binaries making it into mainstream soon?

**Comment by kylecarbs** [comment]
This is coming in [Go 1.20](https://danp.net/posts/macos-dns-change-in-go-1-20/) thankfully! I'm not sure about changing up our CI process too much in anticipation of that, but maybe we could use [gotip](https://pkg.go.dev/golang.org/dl/gotip) to take advantage of this before the official release.

**Comment by dcarrion87** [comment]
@kylecarbs oh that's brilliant!

**Comment by kylecarbs** [comment]
We discussed using Go 1.20 early, and it seemed a bit sketchy... we'll be waiting for the release (I believe it's in February).

**Comment by dcarrion87** [comment]
Thanks!
