### ISSUE TITLE
Workspace with `Outdated` status does not update the first time you click `update`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4098]
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

You have to click `update` a second time for the workspace to update.

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/2022166/190874034-18d0c4a4-36c0-4f15-bed3-d92673c33dc5.png">

**Comment by sharkymark** [comment]
Oh and Coder OSS intermittently still does not grab a DERP server so terminal and IDE do not work.

See screenshot
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/2022166/190874087-bc6e7e79-b2c2-494e-b534-e44969e73256.png">

This is #3979

**Comment by sharkymark** [comment]
Only way to resolve, is `stop` the workspace then `start` again and a DERP may get assigned. @kylecarbs

**Comment by sharkymark** [comment]
Actually sometimes repeated clicking `update` does not update the workspace.

**Comment by sharkymark** [comment]
Eight (8) attempts later, including re-uploading an unchanged template, I have a working workspace.

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/2022166/190874311-7cb7ece9-b958-458d-86b1-0485b692be83.png">

**Comment by bpmct** [comment]
Steps to reproduce (using dev.coder.com)

1. Create a template and workspace
2. [Update the template](https://coder.com/docs/coder-oss/latest/templates#add-a-template)
3. Attempt to update the workspace via the dashboard

https://user-images.githubusercontent.com/22407953/192534006-42e5eed4-31d7-4d10-bd4a-eb2e49f58f47.mov

Updating via the CLI seems to work fine:

https://user-images.githubusercontent.com/22407953/192534446-e2a06ba8-cfd8-47d3-b0ed-880943a1bc1f.mov
