### ISSUE TITLE
Display Template README under workspaces created from that template

### ISSUE THREAD

**Issue by matifali** [coder/coder#4100]

**Comment by bpmct** [comment]
Huge fan of this!

**Comment by matifali** [comment]
Bump

**Comment by mattlqx** [comment]
I think the README should have higher prominence on the template view page as well. It shows up "below the fold" for me. From a user's perspective, I would care much more about reading that when browsing through templates than the number of users graph or even the resource presentation. The template view page is also sub-tabbed, it feels like those things can be moved off to "Resources" and "Analytics" tabs to declutter the Summary tab.

**Comment by MrPeacockNLB** [comment]
Or provide a Link to the readme or a button with a overlay window. It is annoying to search the right template.
