### ISSUE TITLE
Coder should not try to log in with the same invalid credentials more than once

### ISSUE THREAD

**Issue by jaulz** [coder/coder#4109]
In my scenario I use Coder behind nginx and additionally fail2ban which scans the unauthorized access logs. Whenever someone tries to log in more than a few times he will automatically be banned and cannot access the server anymore. This is nice for malicious attacks but it also logs me out when I try to connect to a container but haven't logged in to Coder for some time. These logs are from one single SSH connection attempt:
````
31.164.54.8 - - [19/Sep/2022:07:32:40 +0100] "GET /api/v2/users/me/workspace/user-town?include_deleted=false HTTP/2.0" 401 167 "-" "Go-http-client/2.0"
31.164.54.8 - - [19/Sep/2022:07:32:41 +0100] "GET /api/v2/users/me/workspace/user-town?include_deleted=false HTTP/2.0" 401 167 "-" "Go-http-client/2.0"
31.164.54.8 - - [19/Sep/2022:07:32:42 +0100] "GET /api/v2/users/me/workspace/user-town?include_deleted=false HTTP/2.0" 401 167 "-" "Go-http-client/2.0"
31.164.54.8 - - [19/Sep/2022:07:32:43 +0100] "GET /api/v2/users/me/workspace/user-town?include_deleted=false HTTP/2.0" 401 167 "-" "Go-http-client/2.0"
31.164.54.8 - - [19/Sep/2022:07:32:44 +0100] "GET /api/v2/users/me/workspace/user-town?include_deleted=false HTTP/2.0" 401 167 "-" "Go-http-client/2.0"
````

I think it would be good if the CLI could invalidate the local token once it receives a 401 response and it should not try to run any further requests with that one.

**Comment by bpmct** [comment]
@kylecarbs any idea why there are 5 requests for a single ssh connection attempt? Perhaps it retries

**Comment by kylecarbs** [comment]
@jaulz I don't believe we retry anything like this in the CLI, so this is odd.

Are you confident that a browser tab or something wasn't open? Maybe the dashboard is retrying (which it did when this was reported).

**Comment by jaulz** [comment]
Mh, maybe that was the case. I removed `fail2ban` since then and will maybe try it then again in the future and let you know. Thanks anyway!

**Comment by achalagarwal** [comment]
> Are you confident that a browser tab or something wasn't open?

@kylecarbs 

on a related note although not same as the OP scenario, server / client should block `/api/v2/workspaces` when its unauthorized. An unclosed tab is causing the server to become unresponsive and eventually crash.
