### ISSUE TITLE
Simple way to try work in progress PRs

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4118]
I like to try features before they are merged. This helps me write docs and get a sense of how something will work. Right now, I manually checkout the branch and build. Would be awesome to have a binary ready to go for me (and the community) to give an upcoming feature a shot.

**Comment by ghuntley** [comment]
Shipping pre-release binaries would be very nice but downloading and executing them is a pain (There's also topics of endpoint security if the contribution was from an untrusted community member).  What if we instead (or eventually evolve towards) something I've been thinking / riffing with @kylecarbs about. Through devcontainer.json/devcontainer CLI and some small tweaks the "Open With" pull-request review workflow that exists for GitHub Codespaces and Gitpod can be brought to Coder.

<img width="1306" alt="CleanShot 2022-09-20 at 13 14 01@2x" src="https://user-images.githubusercontent.com/127353/191159344-e98da0ff-5bb5-4b85-a818-e1c69cfb99f8.png">

ps. 👀 
<img width="795" alt="CleanShot 2022-09-20 at 13 16 03@2x" src="https://user-images.githubusercontent.com/127353/191159559-fe7df4ec-0b0f-40f4-9ae9-9dcc8f0ec641.png">

**Comment by kylecarbs** [comment]
@bpmct we were noodling on creating a Terraform provider that uses the [devcontainer CLI](https://github.com/devcontainers/cli) and has a parameter for the Git URL... this would essentially enable the use of the devcontainer format in Coder.

**Comment by bpmct** [comment]
Sound super nice. I'll keep building binaries in the meantime
