### ISSUE TITLE
Context timeout for terraform install on slow network connection

### ISSUE THREAD

**Issue by TomiCode** [coder/coder#4129]
I wanted to try out this environment on docker, so as noted in the guide, I've downloaded the repository and made `docker compose up`. The containers start up and seems to be working, but after a short period, the server throws an error and exits abruptly:
```
Coder v0.8.15+9e9a9e0 - Remote development on your infrastucture
View the Web UI: https://xxx.xxx.xxx.xxx:7080
2022-09-20 11:43:37.415 [INFO]	(coderd)	<./enterprise/coderd/features.go:251>	(*featuresService).syncEntitlements	syncing licensed entitlements

==> Logs will stream in below (press ctrl+c to gracefully exit):
Unexpected error, shutting down server: install terraform: context deadline exceeded
Shutting down API server...
Gracefully shut down API server
Waiting for WebSocket connections to close...
Done waiting for WebSocket connections
install terraform: context deadline exceeded
Run 'coder server --help' for usage.
```

I think that is because of my slow internet connection (around 3 Mbits) and downloading the terraform binary takes more than a minute.

Is there a way to extend the context timeout for this installation process?

**Comment by kylecarbs** [comment]
I'll just make it longer... no reason it can't take a while! It should also output why it's slow, and a way to remedy it (you can install Terraform yourself and put it on `$PATH`).

**Comment by kylecarbs** [comment]
@TomiCode I've added logging to this, so the install experience is less behind-the-scenes.

**Comment by TamaMcGlinn** [comment]
so, I shouldn't be seeing this error if terraform is installed on the same machine that is running coder, right? Anyone have any ideas?

**Comment by kylecarbs** [comment]
Correct. Do you have the proper version of Terraform?

v1.3.4 is what we expect right now.

**Comment by TamaMcGlinn** [comment]
Ah, no. Thanks for the quick response!
For future reference, where is the 'proper version' of terraform listed in coder?

**Comment by TamaMcGlinn** [comment]
Ah, found it in https://github.com/coder/coder/blob/main/provisioner/terraform/install.go
between 1.1.0 and 1.3.9 currently. I have 1.4.5 so that's my problem

**Comment by kylecarbs** [comment]
Gotcha!

**Comment by TamaMcGlinn** [comment]
I just ran into this issue again, but this time I just want to increase the context deadline and let it install terraform. Is there any way to do that?
