### ISSUE TITLE
Add custom template version names

### ISSUE THREAD

**Issue by cfouche3005** [coder/coder#4137]
Is possible to specify a version when a new template version is pushed or is it planned to a future version ?

![Sans titre](https://user-images.githubusercontent.com/51720655/191342622-fd61ee3e-9512-4c06-b9f5-0f42cf337a89.png)

**Comment by bpmct** [comment]
It would be awesome to link version names to git commits once we have #3692

**Comment by bartonip** [comment]
Can the auto-generated names be alphabetical instead of random? Knowing someone is experiencing issues on blapp_dapperson2 while the newest version is grapple_zapples9 lets me know how far back someone's workspace is.
