### ISSUE TITLE
bug: Sometimes `version` does not show up in agent info of a workspace

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4151]
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

This is intermittent and does not always occur.

In this case, the workspace is a `kubernetes_pod` resource

<img width="865" alt="image" src="https://user-images.githubusercontent.com/2022166/191712040-7afc5c8e-1638-4ba4-b9d3-fe7003bb9c27.png">

**Comment by matifali** [comment]
happens to me always
