### ISSUE TITLE
How to stop background tailscale tunneling from occurring

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#4195]
I've been trying to work out how Tailscale networking is used but it's tricky to find documentation around this.

We've got our own Tailscale network which allows the coder workspaces to reach the coder server but find that coder is doing its own tailscale thing in the background when reviewing logs which raises some security concerns and potentially causing connection issues for us.

What options should be specified both at coderd and coder agent to stop any sort of tailscale tunnel and force direct?

Or am I completely missing the point of all the Tailscale action I'm seeing?

I can see coder embedded relay is active but web terminal and web coder server doesn't seem to work and just wondering if this is related. coder CLI port forward and ssh commands work fine.

<img width="687" alt="Screen Shot 2022-09-25 at 8 43 44 pm" src="https://user-images.githubusercontent.com/2899172/192139564-00672431-c988-4af1-888a-a90d3c8bf427.png">

<img width="652" alt="Screen Shot 2022-09-25 at 8 53 22 pm" src="https://user-images.githubusercontent.com/2899172/192139958-ab12a7ab-2715-4085-b4ac-3d302ddab8a8.png">

**Comment by dcarrion87** [comment]
Interesting. Adding CODER_TAILSCALE=false on the coder server seems to have done the trick!

**Comment by kylecarbs** [comment]
Hmm, that's certainly related.

I believe this is due to how the relay currently works, and I'll be making a fix for this soon. We use Tailscale's networking code, but none of it's SaaS infrastructure. It essentially handles all routing to workspaces. The reason that your web connections aren't working is likely because of the DERP mapping we send by default, which contains your access URL. I'm assuming your access URL isn't accessible via your workspaces, so the connection is failing.

I'm working on a fix for this now! `CODER_TAILSCALE` will be removed in the next release, so I'll make sure we get this fixed before that happens.

**Comment by kylecarbs** [comment]
See [our networking docs](https://coder.com/docs/coder-oss/latest/networking) for more info. If you'd like a deeper dive, please leave specific questions and I'll add them to the docs!

**Comment by kylecarbs** [comment]
@dcarrion87 to confirm, are you specifying a custom `url` in our `coder` provider? I'm assuming so, but just making sure.

```tf
provider "coder" {
  url = "..."
}
```

**Comment by dcarrion87** [comment]
> I'm assuming your access URL isn't accessible via your workspaces, so the connection is failing

It is accessible via the workspaces. The REDACTED.REDACTED.ts.net URL that is accessible via our Tailscale http_proxy that is accessible to workspace pods that come up in the namespace in a different Kubernetes cluster.

> CODER_TAILSCALE will be removed in the next release, so I'll make sure we get this fixed before that happens.

I hope not as `CODER_TAILSCALE=false` is the only way I'm able to make the web apps work.

> are you specifying a custom url in our coder provider? 

Not specifying a custom URL. Letting coder do it's thing and relying on the CODER_ACCESS_URL that I specify to the coderd instance.

**Comment by dcarrion87** [comment]
@kylecarbs 

> I'm assuming your access URL isn't accessible via your workspaces, so the connection is failing

It is accessible to the workspace pods. The REDACTED.REDACTED.ts.net URL of the coderd  is accessible via the Tailscale proxy that comes up in the workspace namespace. I.e. the workspace pods access the default URL via an underlying proxy. It looks like:

`[workspace_pod] -> [https_proxy environment variable] -> [tailscaled pod/service with http proxy enabled] -> [tailscale network] -> [caddy] -> [coderd instance]`

The reason for this is coderd and workspace instances cannot be public and workspace instances can be in kubernetes clusters that aren't routable directly.

> CODER_TAILSCALE will be removed in the next release, so I'll make sure we get this fixed before that happens.

I hope not as specifying `CODER_TAILSCALE=false` when the coderd instance comes up is the only way I'm able to make the web apps work for the workspaces :). I can test when the release is available anyway.

> are you specifying a custom url in our coder provider? 

Not specifying a custom URL. Letting coder do it's thing and relying on the CODER_ACCESS_URL that I specify to the coderd instance.

**Comment by kylecarbs** [comment]
Ahh, I believe I know the problem! I appreciate the context :)

`coderd` dials the `ACCESS_URL` when establishing a connection right now, which is incorrect behavior (it should just loop back and dial the DERP server). Is your `coderd` pod able to access the REDACTED.REDACTED.ts.net URL? If not, then I'm confident this will solve the issue.

**Comment by dcarrion87** [comment]
Aah good point @kylecarbs. No, `coderd` wouldn't actually know about `REDACTED.REDACTED.ts.net`. The loopback thing sounds like a good fix but I'll try and make that happen anyway just to see and provide feedback here.

**Comment by kylecarbs** [comment]
Wonderful! `CODER_TAILSCALE` should be a *lot* faster than not, but I'm happy you caught this. I'll get a fix up ASAP!
