### ISSUE TITLE
Welcome app inside starter templates

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#4201]
We've received numerous issues about confusion with our getting started experience.
- #3292 
- https://github.com/coder/coder/issues/3644
- https://github.com/coder/coder/issues/3513
- https://github.com/coder/coder/issues/3514
- https://github.com/coder/coder/issues/3402

The primary complaint is that our Docker experience doesn't explicitly state that dialing the host is required, and our web UI doesn't indicate an error; it just says "Connecting" forever.

I've also found it confusing to have numerous Docker examples because the user is trying to optimize for "does it work," not "is it featureful?" 

#### Step 1. Separate example templates from quickstarts

We should have a single template for each unique infrastructure type. e.g.

- Virtual Machines on Azure
- Virtual Machines on Google Cloud
- Virtual Machines on Digital Ocean
- Containers on AWS ECS
- Containers on Docker
- Containers on Kubernetes

Examples can be more bespoke and have additional features like dotfiles, but quickstarts should be simple and straight-forward.

#### Step 2. Add a getting-started HTTP server to advertise workspace applications

Instead of installing `code-server` in every template (which can easily get outdated or maybe just not work if the prospect is air-gapped), we should have a default application in every quickstart that displays what the user can do next. Tailscale does this nicely:

![image](https://user-images.githubusercontent.com/7122116/192294357-9b8d01b1-be70-44ae-a112-c438a763ee95.png)

This would be called "Get Started" and display as a normal workspace application, but when opened a screen like this might appear:

![image](https://user-images.githubusercontent.com/7122116/192295708-95129123-afd3-4c53-9e83-c565a8ea99c7.png)

This looks brutal, but you get the point.

#### Step 3. Add a `timeout` parameter to the `coder_agent` resource

After the specified duration of inactivity, the UI and CLI would display that something wrong happened. Templates can define a `debug_url` parameter in their front-matter that can direct users to a help page.

**Comment by bpmct** [comment]
Huge fan of these 3 suggested improvements. Kyle and I chatted about it and decided it might be helpful for templates to link out to unique "get started" pages based on the frontmatter. Perhaps the "getting started" could also share the `debug_url` too

**Comment by ericpaulsen** [comment]
@kylecarbs @bpmct regarding:

> Step 1. Separate example templates from quickstarts

I can assist with separating out the "quickstart" start templates for each infra type from the more specific examples.

**Comment by im-coder-lg** [comment]
So, does it work now? I notice that it works better on my Raspberry Pi 4B.

**Comment by bpmct** [comment]
@im-coder-lg Yeah, Coder works well on a Raspberry Pi 4B. There are sometimes (fixable) Docker issues that are present on the host and this issue suggests some improvements.

**Comment by BrunoQuaresma** [comment]
@kylecarbs in the image that you shared, are the boxes links to the docs?

**Comment by bpmct** [comment]
Gonna close this for now. I'm not convinced we need the agent to serve an app to provide the necessary guidance for modifying apps, especially with the template builder. We did the rest of the stuff!
