### ISSUE TITLE
feat: Roles displayed under a user's avatar look disorganized, complicated and ugly

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4204]
Version: [`v0.8.15+9e9a9e0`](https://github.com/coder/coder/commit/9e9a9e0cd2307abacdb573f9594bb5b0ee62e805)

<img width="324" alt="image" src="https://user-images.githubusercontent.com/2022166/192316226-183bd878-af7a-431f-a3f5-66e8ebd298eb.png">

**Comment by matifali** [comment]
By the way, `Owner` can not assign roles to oneself. I needed to make another user Owner then assign  other three roles (i.e. `Template Admin,` `Auditor` and `User Admin`) to my `Owner account.`
