### ISSUE TITLE
Creating a template with no users shows '-' instead of '0'

### ISSUE THREAD

**Issue by sreya** [coder/coder#4208]
![image](https://user-images.githubusercontent.com/4856196/192352321-03fb04e6-e85b-448c-ab3a-4b22480d0688.png)

**Comment by kylecarbs** [comment]
@ammario I think did this intentionally, but it does look weird.

**Comment by ammario** [comment]
It's shown like this because the DAUs are calculated asynchronously, so it is unclear whether there are zero users or undefined users. The modification to clarify it should be straightforward.

**Comment by presleyp** [comment]
The code only overwrites negative numbers and `undefined` to `-`, not zero. So I guess there are undefined users of a new template. Should we just show 0 in all these cases?

**Comment by presleyp** [comment]
Looks like it's -1 when loading, so I'll just check for that, and let 0 be 0

**Comment by sreya** [comment]
I don't think this is an issue anymore
