### ISSUE TITLE
High Availability DERP

### ISSUE THREAD

**Issue by coadler** [coder/coder#4214]
Relates to https://github.com/coder/coder/issues/3227

Right now, DERP servers are embedded into coderd. This works great for single replica deployments but is difficult to scale for HA. This is mostly due to how Tailscale designed HA meshing for DERPs. The requirements for meshing DERP servers are:

1. Each DERP must know the hostname of every DERP in its region.
2. Each DERP must be able to dial every DERP in its region

These two requirements make it a bit hard to fit DERP meshing into our current Helm chart, which currently runs coderd as a deployment. To make DERP meshing into our current Helm chart, we would need to transition to a [statefulset](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/). Statefulsets allow each pod to be individually dialable via a stable internal DNS name. Using this we could easily give each pod the hostnames with which it needs to mesh with. Unfortunately while statefulsets do work with HPAs, each coderd pod would need to be restarted after each scaling event to adopt or disown the newly added or destroyed pod. This would be frustrating since every scaling event or Coder upgrade would cause all DERP connections to drop.

For these reasons, I propose we ship a second Helm chart and container image specifically for managing DERP regions. In addition to solving all of the previous problems, it allows users to scale DERPs and coderd separately. Coder updates and scaling become very low cost as it's impossible for pod restarts to affect any persistent user connections. I don't believe there will be any significant added maintenance needed for this deployment as it won't need to be updated in sync with the main coderd and DERPs can manage their own TLS through LetsEncrypt.

**Comment by kylecarbs** [comment]
This has been completed!
