### ISSUE TITLE
Central workspace template management ideas

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#4217]
Wanting to get some ideas on how to deal with coder workspace template management across multiple coderd instances current deployed with kubernetes.

When coder instances come up for the first time we store the admin credentials in SSM as a "break glass" mechanism and for any administration we need to do to that instance. Users are forced to use OIDC to auth.

We're looking to maintain a set of pre-canned templates for different department coderd instances on top of templates that users decide to deploy themselves.

We don't want to have to manually deploy pre-canned and we don't want the users to have to manually do this either. In an ideal world we could point these instances at some shared template space and that would be it.

Failing that what would be the best way to achieve this with what coder currently has available? We're thinking some event triggered process that essentially runs coder template push or equivalent on initial deployment and when there's an update to our templates repo. It would use the initial admin credential we created and stored.

Just trying to work out how that would work in an automated fashion and with the mechanisms coder currently has available.

Thanks in advance for all your ideas!

**Comment by kylecarbs** [comment]
What's the rationale behind having multiple Coder instances instead of one centrally managed one? That's certainly the route we're directionally building in for more supportive features (e.g. metrics will never be shared between multiple Coder deployments).

**Comment by dcarrion87** [comment]
I noticed the bit on this page around just using coder template push in CI: https://coder.com/docs/coder-oss/latest/templates#change-management

Just concerned about the clunkiness of the implementation as a lot of the coder CLI seems geared for interactive use?

**Comment by dcarrion87** [comment]
Thanks @kylecarbs, will reach out with some more details.

Interesting, never thought about standing up a central coder instance and use that to drive central template management.
