### ISSUE TITLE
docs: Add docs to explain how to configure port-forward from WebUI

### ISSUE THREAD

**Issue by matifali** [coder/coder#4221]
I get this,
![image](https://user-images.githubusercontent.com/10648092/192470699-465ed161-07d1-4d35-a625-34b4c6f45ba1.png)

**Comment by bpmct** [comment]
The `Learn more about port forward` link has instructions on how to configure a wildcard URL. Are you suggesting we change that link to something a bit more clear such as `Learn how to configure port forwarding` @matifali

**Comment by matifali** [comment]
That link was not working in 0.9.0 but working fine now.
