### ISSUE TITLE
Control workspace size in coder

### ISSUE THREAD

**Issue by ecarico** [coder/coder#4231]
Our workspace sizes when first spun up are around 60 gb using a Python image from docker. Is this normal? Attempting toright size our k8/coder deployment.

**Comment by bpmct** [comment]
Hey @ecarico - what template and image are you using?

**Comment by ecarico** [comment]
Hello, I am using the default template and with any template thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kylecarbs** [comment]
Closing for now.

@ecarico if you need assistance setting up Coder, join our Discord: https://discord.gg/coder
