### ISSUE TITLE
Can we just not display `terraform` variable names?

### ISSUE THREAD

**Issue by matifali** [coder/coder#4261]
![Screenshot from 2022-09-15 08-25-41](https://user-images.githubusercontent.com/10648092/193027772-3c1d51a0-88bf-457b-9d21-d12eb3c9b285.png)

 Can we just somehow do not display this internal terraform variable names `var.cpu`, `var.ram` etc
 The description is enough to explain what to enter to the user.
 It will also resolve #4073 as there is no need for a pretty variable name anymore.

**Comment by BrunoQuaresma** [comment]
I think the description is not mandatory but we may could display the description as primary and the var name as secondary text. If the description is not provided, the var name gets primary. Sounds good?

**Comment by kylecarbs** [comment]
We're reworking this flow right now. I'll post some WIP screenshots as it gets further along.

**Comment by matifali** [comment]
> I think the description is not mandatory but we may could display the description as primary and the var name as secondary text. If the description is not provided, the var name gets primary. Sounds good?

Yes this sounds good

**Comment by matifali** [comment]
> Closing as a duplicate of #4311

Using a `coder_parameter` is not a simple solution while we already have `terraform variables`, and they do have a description field. If someone just wants to make the template creation page looks nice without making the actual `main.tf` too complex. Hiding the variable name is the simplest solution.
![image](https://user-images.githubusercontent.com/10648092/197939198-ba35be19-98f5-484b-9831-fc045456bacb.png)

**Comment by matifali** [comment]
@bpmct

**Comment by bpmct** [comment]
@matifali the current plan is to deprecate variables (and only using them for template-wide settings/CI jobs)
