### ISSUE TITLE
bug(UI): Tab selection does not work on delete workspace dialogue. 

### ISSUE THREAD

**Issue by matifali** [coder/coder#4262]

**Comment by BrunoQuaresma** [comment]
What element specifically tab can't select?

**Comment by matifali** [comment]
It cannot select cancel or delete buttons

**Comment by matifali** [comment]
@BrunoQuaresma this is appearing again

**Comment by matifali** [comment]
@BrunoQuaresma For context it does work fine on 0.23.2 but is not working on dev.coder.com

**Comment by BrunoQuaresma** [comment]
I figured out it does focus the cancel button since the delete is not enabled until you type the right name, but it is not applying any focus style.
