### ISSUE TITLE
do not display the portforward button if it has not been enabled/configured.

### ISSUE THREAD

**Issue by matifali** [coder/coder#4283]

**Comment by BrunoQuaresma** [comment]
We made that to help users to find out the feature so they know the feature exists.

**Comment by matifali** [comment]
> We made that to help users to find out the feature so they know the feature exists.

Then maybe allow for the users who do not want this to Disable this or hide this somehow because it take space and makes the U crowded

**Comment by bartonip** [comment]
Can you do a "What's New" screen instead?

**Comment by BrunoQuaresma** [comment]
We are reworking the resources section to solve this issue - too much things on the screen.

**Comment by matifali** [comment]
Resurrecting the issue.

**Comment by kylecarbs** [comment]
@matifali do you have ideas on how we could advertise the feature without it being so "in your face"? Maybe we show this on the deployment screen instead?

**Comment by BrunoQuaresma** [comment]
I think this is valid. So just to confirm, the solution would be:
- Remove the port forward button from the agent row
- Show the port forward option in the deployment page

Is that right?

**Comment by matifali** [comment]
Yes on the deployment page it may be shown.
