### ISSUE TITLE
coder: command not found - docker installation

### ISSUE THREAD

**Issue by CaptainStein** [coder/coder#4286]
I followed the instructions for the installation via docker-compose file. https://coder.com/docs/coder-oss/latest/install/docker#run-coder-with-docker-compose

1. First cloned the git repository, changed the docker-compose.yaml to my setup because i use traefik so i need to set networks and labels.. and set my coder_access_url directly into my docker-compose file
2. Then run docker-compose up to see the logs first, no problems, all started fine.
3. then i created direct my first user on the web ui on /login, works fine.

If i now want to create an workspace i need an template and it switches to that site, i can either create from scratch or run coder templates init but on the machine where i cloned the repository and started the container my bash can't find the command coder anyways so none of these variants works. i'm stuck now. 
do i need to connect to my container to execute these commands? or do i need to install coder within the install script on my machine anyways to get the coder commands running?

appreciate your help
thanks!

**Comment by bpmct** [comment]
Hey @CaptainStein - sorry, I missed this! You can [install](https://coder.com/docs/coder-oss/latest/install) the `coder` command on your local machine to talk to the server. If you sh into the container, you can use the CLI with `/opt/coder`, but it is not in PATH. The intended behavior is to use the CLI on your machine (e.g. a "client")
