### ISSUE TITLE
`coder_app` resource doesn't proxy non localhost addresses

### ISSUE THREAD

**Issue by bartonip** [coder/coder#4287]
I have PGAdmin running in a separate container with the hostname `pgadmin`.

I have specified a coder_app resource like this: 
```
resource "coder_app" "pgadmin" {
  agent_id = coder_agent.main.id
  name     = "PGAdmin"
  url      = "http://pgadmin/"
  icon     = "icons/pgadmin.svg"
  relative_path = true
}
```

However I just get the following error message:
```
PGAdmin is offline!
read tcp [ipv6-here]:44715: connection reset by peer
```

- It works when the url is localhost or some address that is pointed to 127.0.0.1 in /etc/hosts
- Inside the container if i curl http://pgadmin/ it works

Any help would be much appreciated

**Comment by bartonip** [comment]
@kylecarbs Not to rush you mate, but just wondering what the ETA is on this, as we have a project that is stuck pending this change. Just need to know if I should expend the hours putting in a workaround or not.

**Comment by kylecarbs** [comment]
@bartonip there isn't an amazing way for us to customize the host in our current implementation since it transparently dials the agent IP and forwards it to localhost.

I'd recommend finding a workaround, but we'll support this eventually (tentatively, I'll say in the next six weeks).

**Comment by cdrx** [comment]
#### Workaround

You can use socat to listen on `localhost` inside the workspace and proxy traffic to the non-localhost address. Put this at the end of your startup script:

```bash
nohup socat tcp-l:1080,fork,reuseaddr tcp:XXXX:YYYY &>/dev/null &
```

replace `XXXX` with the hostname you want to use (eg: `pgadmin`) and `YYYY` with the port number. 

Then you can configure the `coder_app` to use `http://localhost:YYYY` and socat will proxy the traffic to the correct endpoint.
