### ISSUE TITLE
Role UI is confusing

### ISSUE THREAD

**Issue by ammario** [coder/coder#4304]
This is a bug report from Elliot:

<img width="699" alt="Screen Shot 2022-10-01 at 4 16 31 PM" src="https://user-images.githubusercontent.com/7416144/193428605-05cd8b68-6519-403e-9f64-8cb692c5fe17.png">

As an Owner, I was trying to demote another user back to member. I clicked the dropdown and went “wat? Where’s the member?”. I then unselected owner and figured out what the deal was. Now I understand what you were going for here, and it’s clever: by having checkboxes, I can select multiple roles. Unfortunately, the way it’s implemented made it unclear how to go back to a normal user. I also don’t know from here if an auditor has more or less permissions than a member

---

Adding auditor to role breaks the “sorting”
<img width="1037" alt="Screen Shot 2022-10-01 at 4 16 53 PM" src="https://user-images.githubusercontent.com/7416144/193428611-02f750ed-189c-42fc-897f-1311e9a6f627.png">

**Comment by BrunoQuaresma** [comment]
>  I also don’t know from here if an auditor has more or less permissions than a member
This is something hard to predict, right? Since we have multiple roles that not necessarily are ordered by "power". 

I agree with you about this confusion. Since we can add multiple roles to a user, and those roles not necessarily means a linear grant of permissions, do you have ideas on how we could improve that in the UI?

**Comment by ammario** [comment]
Not off the top of my head. It is a hard problem.

**Comment by kylecarbs** [comment]
@BrunoQuaresma, lets change the BE to return some sorting. There is a hierarchy in these roles, so we should display it.

It'd also be nice to have some text that displays what each role has access to do... right now it's waaaay too vague.

**Comment by Emyrk** [comment]
`Member` can be a checkbox that is always checked and always disabled. As a stop gap to understanding that everyone is always a `member`.

**Comment by BrunoQuaresma** [comment]
I like @Emyrk idea. @kylecarbs I'm going to mock something.

**Comment by BrunoQuaresma** [comment]
@ammario @kylecarbs @Emyrk  what do you think about this? The verbiage needs update.
![Edit Role](https://user-images.githubusercontent.com/3165839/210403062-e70f7a20-b86b-4ccd-a355-d5185127c445.png)

**Comment by ammario** [comment]
@BrunoQuaresma I like it, definitely an improvement. What do you think about coloring the Owner / Admin roles, maybe with a light border? It would be nice to scan through the user list and quickly see them.

**Comment by BrunoQuaresma** [comment]
Maybe we can make the admin labels "Blue", what do you think?

**Comment by Emyrk** [comment]
@BrunoQuaresma that looks so much better than what I had in mind!
