### ISSUE TITLE
Usernames have unclear purpose

### ISSUE THREAD

**Issue by ammario** [coder/coder#4307]
This is feedback paraphrased from Elliot:

<img width="500" alt="Screen Shot 2022-10-01 at 4 57 01 PM" src="https://user-images.githubusercontent.com/7416144/193429782-28186912-4b4e-4349-a3ec-0bb1ddb4d984.png">

This is my actual username at my current role, and I think “.”s are fairly common in usernames.

I just noticed that I can’t log in using my username, only my email address. What’s the point of the username if it’s not used in login?

**Comment by ghuntley** [comment]
Related items:
- https://github.com/coder/coder/issues/1756
