### ISSUE TITLE
audit: show template name and not template id.

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4312]
Version: [`v0.9.1+27c8345`](https://github.com/coder/coder/commit/27c8345ef2d570f6bb05d601b3aa675dd0ee4670)

templates are known by names, not IDs to developers and administrators.

The audit logs should also show template name, besides template id.

Therefore the audit logs are not helpful to the naked eye.

This is probably not done yet because an additional table join was required (template table).

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/2022166/193485186-d14b6962-41bb-4782-b5b1-4c7b6d06fcca.png">

**Comment by Kira-Pilot** [comment]
We should consider this for all resources.
