### ISSUE TITLE
feat: `coder license list` shows a unix date and not a human-readable date

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4313]
Version: [`v0.9.1+27c8345`](https://github.com/coder/coder/commit/27c8345ef2d570f6bb05d601b3aa675dd0ee4670)

I added an enterprise license to a Coder deployment and would like to know the end date.

There is no UI like in v1, and when I run `coder license list` it shows what appears to be a Unix date under `exp` which 1. I assume means the end date and 2. is meaningless to me.

It also seems like a security risk that a Salesforce identifier is exposed in this file.

<img width="222" alt="image" src="https://user-images.githubusercontent.com/2022166/193485779-8be926c1-b0f0-4fcd-a631-4b1db712c5f3.png">

**Comment by ammario** [comment]
I agree the default output should be human-readable. There is no new security risk to showing the salesforce identifier here, as the license file already gives that information to the user.

**Comment by ammario** [comment]
@rodrimaia — you were working on the License UI so maybe this would be up your alley?

**Comment by matifali** [comment]
Also, shouldn't we display a table like docker/kubectl do instead of a Jason by default?
Currently the above command shows a Jason output.

**Comment by rodrimaia** [comment]
@ammario Sure! assigning it to me! :)
