### ISSUE TITLE
audit: I deleted a workspace but the audit logs did not record it.

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4316]
Version: [`v0.9.1+27c8345`](https://github.com/coder/coder/commit/27c8345ef2d570f6bb05d601b3aa675dd0ee4670)

Conversely, when I create a workspace, it is logged.  Updating a workspace is not logged too.

Precise, accurate audit logging is critical for security and compliance teams within enterprises.

I am basing the expected actions from the Coder docs
https://coder.com/docs/coder-oss/latest/admin/audit-logs#filtering-logs

API key creation is not logged too - I did `coder login` which to my knowledge is the only way to create a token, and an audit log entry is not created.

Unlike v1, there is no CLI command to create and delete tokens.

**Comment by kylecarbs** [comment]
@coadler we should do a pass on this.

**Comment by Kira-Pilot** [comment]
@sharkymark I've opened a PR to address workspace deletion, so that should be fixed soon.
Seems we never had support for APIKeys  - I've opened a PR updating our documentation and [created a ticket](https://github.com/coder/coder/issues/4538) so that we can build out support for that resource.

**Comment by sharkymark** [comment]
Nice thanks @Kira-Pilot
