### ISSUE TITLE
Limit member visibility for non-admins

### ISSUE THREAD

**Issue by matifali** [coder/coder#4318]
For now, a non-admin user can see a full list of all coder users, their roles, emails, and last used time.

**Comment by bpmct** [comment]
I definitely see the merit of this feature. When we run workshops or have demo environments we may not want all emails to be public! We are adding groups support in #4235 including a global "Everyone" group.

Perhaps each group (including "Everyone") could have a `Member visibility: (true)/false` setting.

Alternatively, we could disable the page and routes to view members for non-admins across the board. As a user, I will want to know what groups I'm in, but not necessarily who the other users are in the group/deployment.

**Comment by bpmct** [comment]
@ammario suggested doing this via an env variable to disable viewing users for all non-admins. I agree.

**Comment by sharkymark** [comment]
If a user wants to see their groups, that should be in their profile. Re-using an Admin tab like Users is not an enterprise good look IMO even if it's read-only.

**Comment by matifali** [comment]
> If a user wants to see their groups, that should be in their profile. Re-using an Admin tab like Users is not an enterprise good look IMO even if it's read-only.

Maybe a user should be able to view his own groups and the other members in the same groups at maiximum.

**Comment by matifali** [comment]
Any plans for these guys? 
I think it is required after we allow the opening coder to the public using GitHub signup.

No one should be able to view all the other members except the user admin or owner.
@bpmct

**Comment by ammario** [comment]
I think it's a fine default that regular users can't see everyone. I don't think we should add an additional configuration knob yet.

**Comment by matifali** [comment]
But the regular users withy a member role can see everyone on the latest version.

**Comment by mtojek** [comment]
Hey @bpmct! I found at least 2 similar request issues referring to the same problem:
https://github.com/coder/coder/issues/4550
https://github.com/coder/coder/issues/5002

Do you think that we can unify/deduplicate all these?

BTW I commented on the design [here](https://github.com/coder/coder/issues/5002#issuecomment-1321760487). It would be great to clarify it, and I don't mind where the response lands :)

**Comment by bpmct** [comment]
Yep. Closing in favor of #5002
