### ISSUE TITLE
bug: Clicking workspace update does not update

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4330]
Version: [`v0.9.1+27c8345`](https://github.com/coder/coder/commit/27c8345ef2d570f6bb05d601b3aa675dd0ee4670)

I pushed a new template and the workspace UI says `outdated`

I click the `update` button.

The workspace looks like it is rebuilding, but after 10 seconds, the workspace UI says `outdated` still with the `update` button.

Loom replay
https://loom.com/share/9a6361e7335047c79326f2c9b3e61e5f

**Comment by kylecarbs** [comment]
I just pushed a new release, v0.9.2 that is building now and will fix this.

https://github.com/coder/coder/commit/65ff604969dc5bf41dab990bac260e637c419868
