### ISSUE TITLE
Opening the link generated by the port forward button requires authentication

### ISSUE THREAD

**Issue by ongood** [coder/coder#4358]
Suppose I use the code server integrated with coder oss to develop a web app. This web app has its own running port, such as 3000. When I generate a link through the port forward button and forward this link to another person to test this web app,
At this time, there was a problem. When he opened the link in his browser, the first thing that popped up was to ask him to log in to my coder account, which was very embarrassing!!
So this link becomes that only me can test it, and it can't be tested if it is sent to someone, unless I tell him my coder account  and password. Is there an option to forward the shared test link without authentication?

**Comment by deansheather** [comment]
#4378 will be merged shortly and is now an open source feature (it was previously going to be a paid enterprise-only feature).

Once merged, you can create a `coder_app` resource in your terraform file with the given port and set `share = "public"` or any of the other levels which you can find in the PR description. We currently don't have plans to allow sharing ports directly and we're leveraging apps in terraform for now.
