### ISSUE TITLE
Coder fails to retrieve workspaces

### ISSUE THREAD

**Issue by fpoussin** [coder/coder#4359]
Using release v0.9.2

This only affects some users.
It started happening after enabling github login, but affects both local and github users.

`{2022-10-04 08:43:40.244 [WARN]  (coderd)        <./coderd/httpmw/logger.go:54>  Logger.func1.1  GET  
{"host": "coder.somewhere.com", "path": "/api/v2/workspaces", "proto": "HTTP/1.1", "remote_addr": "10.111.112.219:59792", "took": "54.363056ms", "status_code": 500, "latency_ms": 54, "response_body": "{\"message\":\"Internal error fetching workspace resources.\",\"detail\":\"convert workspace builds: converting workspace build: build initiator not found for workspace: \\\"test\\\"\"}\n", "request_id": "48a31c5b-d685-4ab0-b77d-fe6b82923d2e"}
`

**Comment by kylecarbs** [comment]
Did you manually delete a user from the database or anything? This is a _really_ weird error...

**Comment by fpoussin** [comment]
Nothing was modified in the database.
Local users were deleted from the web interface as they were conflicting with GH ones.
This worked perfectly fine at first, issues appeared this morning.

**Comment by kylecarbs** [comment]
We'll certainly investigate this... super weird. Thanks for the report!

**Comment by kylecarbs** [comment]
Ahh, I know the issue! Fixing now.

**Comment by kylecarbs** [comment]
So this happens by attempting to fetch deleted workspaces for deleted users... is it possible they had a browser tab left open to an old session? I'm not sure how this could occur, since we require all workspaces to be deleted to delete users.

**Comment by fpoussin** [comment]
It's possible they had tabs kept open, however I did experience it as well even when restarting my browser.
This also happens when retrieving workspaces for these users from another one that has the owner role.

**Comment by kylecarbs** [comment]
That's interesting. Could you isolate this by adding the `owner:<username>` filter? I'm curious if it only exists for users whose usernames were previously deleted.

**Comment by fpoussin** [comment]
Any workaround in the meanwhile?

**Comment by kylecarbs** [comment]
Fixing this now and will have a release out soon!

The problem occurs when a deleted user built a workspace for another user. Right now, we query for users that have not been deleted, so this user is not found.

**Comment by kylecarbs** [comment]
@fpoussin I made the fix in https://github.com/coder/coder/pull/4441 and added a test so it can never happen again!

I'll ping you here when a new release is made! You'll just be able to upgrade.

**Comment by kylecarbs** [comment]
@fpoussin v0.9.8 is being published right now, and it's confirmed to have the fix! Let me know if you encounter any more bugs/hiccups, we're happy to fix.

**Comment by fpoussin** [comment]
Awesome, thanks a lot!

**Comment by fpoussin** [comment]
Unfortunately, it's still happening :
```
{"message":"Internal error fetching workspaces.","detail":"get authorized workspaces: pq: more than one row returned by a subquery used as an expression"}
```
