### ISSUE TITLE
feat: Workspace quotas should be above any input parameters in the Create Workspace UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4360]
Version: [`v0.9.2+cb62e16`](https://github.com/coder/coder/commit/cb62e16b410434769de53c23656c313063d2636f)

I have a template with a lot of input parameters.

I only find out my resource quotas when I scroll to the bottom.

I could have wasted 1-2 minutes filling out input parameters to only find out I can't create another workspace, and then will lose my work.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2022166/193825471-1e8297de-9739-4d74-bce4-6b7f880132d2.png">

<img width="639" alt="image" src="https://user-images.githubusercontent.com/2022166/193825366-5a2b3254-0db4-48b2-859c-40c2de820ca7.png">

**Comment by f0ssel** [comment]
I considered this when implementing and wasn't sure which way was better, this feedback is great and I can make this change.
