### ISSUE TITLE
License issue warning after update to 0.9.4 (audit logging is enabled)

### ISSUE THREAD

**Issue by ntimo** [coder/coder#4383]
## Description
I updated my coder setup to version 0.9.4 and now when I view the dashboard I see a huge license violation warning because the audit feature is enabled.
![image](https://user-images.githubusercontent.com/6145026/194230198-5689ef0e-500b-49f7-bc2f-0d8669361fc6.png)
I did not enabled this feature nor would I know how after a license. 

## Desired solution
The warning should not appear when  the feature is not actively configured or used.

## My coder env settings:
```
      CODER_PG_CONNECTION_URL: "postgresql://{{ coder__postgres_user }}:{{ coder__postgres_password }}@postgres/{{ coder__postgres_db }}?sslmode=disable"
      CODER_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "{{ coder__url_with_proto }}"
      CODER_WILDCARD_ACCESS_URL: "{{ coder__wildcard_url }}"
      CODER_PROMETHEUS_ENABLE: "true"
      CODER_PROMETHEUS_ADDRESS: "0.0.0.0:7090"
      CODER_TAILSCALE: true
```

**Comment by kylecarbs** [comment]
Oofta, we'll be changing the way we dogfood to make sure we fix this.
