### ISSUE TITLE
Logging out in the dashboard should also logout of subdomain app URLs

### ISSUE THREAD

**Issue by deansheather** [coder/coder#4394]
We could handle this by redirecting the user to a special `coder-app-logout` subdomain if `--wildcard-access-url` is set.

**Comment by bpmct** [comment]
I sometimes run into ERR_TOO_MANY_REDIRECTS when accessing port 8080 over the dev script. Clearing cookies does the trick. Is this related?

**Comment by deansheather** [comment]
@bpmct Dogfooding coder inside of coder app URLs won't work at the moment because of cookie conflicts, which is an unrelated issue that only impacts running Coder inside of Coder. You can still access the "inner" coder over coder CLI

**Comment by kylecarbs** [comment]
@deansheather it seems like we should prioritize this. If I log into Coder at my local library, when I log out I shouldn't be in an insecure state.
