### ISSUE TITLE
Allow external provisioner daemons to register with Coder

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#44]
Any provisionerd instance should be able to connect with authentication.

## Implementation notes
Work items:
 - Create an endpoint that registers provisioners and generates a credential
 - Create a CLI command that hits this endpoint
 - Create a CLI command that starts a standalone provisionerd instance, which accepts the credential

User workflow for creating a new provisionerd instance will be:

1. run the cli command and either output the cred to screen or a file
1. copy the file or screen output to either the machine that runs provisionerd, or the infrastructure system that creates that machine
1. start provisionerd using the credential

You could also imagine step 1-2 being fully automated by the infrastructure system.

-----

- [x] https://github.com/coder/coder/issues/1391
- [x] https://github.com/coder/coder/issues/1392
- [x] https://github.com/coder/coder/issues/1393

**Comment by misskniss** [comment]
Enqueued this epic for support of the upcoming roadmap.

**Comment by bpmct** [comment]
@dwahler could you add a bit of context in the issue description on why this matters and how this will be surfaced to customers (doesn't have to be precise API design at this point, but kind of where an admin would declare additional provisioners on their deployment) 

For example, something like

An admin can use `CODER_SERVER` environment variables to create additional provisioners and authenticate via ...

**Comment by spikecurtis** [comment]
These need to be started independently with a new command like `coder provisionerd` or similar

**Comment by misskniss** [comment]
@spikecurtis will you and @dwahler sync on this. I will assign it to him for next sprint but it needs some discussion before the sprint starts.
