### ISSUE TITLE
Error when upgrading Coder Docker image

### ISSUE THREAD

**Issue by kotx** [coder/coder#4405]
Hi,
I have a [Docker image](https://github.com/kotx/coder-fly/blob/master/Dockerfile) with Coder that I frequently update, but each time I update, I encounter this error:
```
2022-10-06T21:14:00.236 app[f1cedbac] lax [info] migrate up: up: no migration found for version 56: read down for version 56 .: file does not exist
```
It fixes itself after some restarts somehow, but it seems to get stuck with that error sometimes. Is it something to do with cache or database corruption?

**Comment by kylecarbs** [comment]
Hmm, try upgrading to v0.9.6... I'm not sure how you'd enter this state. It's very strange.

**Comment by kotx** [comment]
For some reason that worked?? Thanks!
I'll be sure to reopen if it happens again 😉
