### ISSUE TITLE
 Hierarchy in ressources

### ISSUE THREAD

**Issue by cfouche3005** [coder/coder#4407]
Is It possible to had some kind of hierarchy for ressource on the ui, at least put the workspace in first because it is sometime difficult to have access to workspaces button. For now the workspace ressource is placed randomly.

![image](https://user-images.githubusercontent.com/51720655/194423102-4e1de78e-2b49-4a01-87d1-8a0f9c9feab1.png)

**Comment by bpmct** [comment]
A few ideas, but would love thoughts from others.

1) Prioritizing the resource(s) that contain an agent seems reasonable
2) We have [resource_metadata](https://coder.com/docs/coder-oss/latest/templates/resource-metadata) which allows us you to apply arbitrary key/values to resources, and even `hide` resources. Perhaps we could add an `order` property so you can set an arbitrary order?

   ```hcl
    resource_metadata "important_resource" {
      resource_id = docker_container.important.id
      order            = 1
     }
    resource_metadata "kinda_important_resource" {
      resource_id = docker_volume.usr_volume.id
      order            = 2
     }
    resource_metadata "bottom" {
      resource_id = docker_volume.opt_volume.id
      order            = 99
     }
    resource_metadata "useless" {
      resource_id = docker_volume.useless.id
       hide             = true
     }

**Comment by cfouche3005** [comment]
Yes, I think it would be cool. I didn't know you can hide ressources, thanks for the info. For now, I will just hide it.

**Comment by BrunoQuaresma** [comment]
Closing as resolved for now.
