### ISSUE TITLE
audit: audit the audit log 🔍 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4408]
As we're quickly building/changing features, we need to ensure the audit log is capturing an accurate trail of user actions.

A 🦈  has caught a couple of issues, but we need to do a comprehensive list of CRUD actions (CLI and dashboard) and ensure they're being accurately represented. 

- #4317
- #4316

The intended behavior is documented [here](https://coder.com/docs/coder-oss/latest/admin/audit-logs#tracked-events). 
 
Additionally, we should have a process in place for ensuring incoming features (#4125, #4311) are represented in the audit log. Can we do this via automated tests or should we build something into the product/QA process? 

It's better to start thinking about this now before we introduce a lot of debt.

**Comment by f0ssel** [comment]
I think it's easy enough to write go tests for this, it's probably best to have each feature/endpoint do it's own expected audit log testing.

**Comment by coadler** [comment]
One thing that makes testing audit logs generated by AGPL routes hard is that the audit logs are generated in the enterprise code. You can really only assert the inputs to the enterprise code unless you want to move the tests there as well.

**Comment by Kira-Pilot** [comment]
Discussed with @coadler and the path forward here is to:
1) fix the above issues
2) ensure that we assert the creation (rather than content) of logs for each action. We cannot test the diffs because we cannot easily test the enterprise code.

There is no way to automate audit log creation for new features, but I can write a quick how-to if that's helpful, @bpmct.

**Comment by bpmct** [comment]
> There is no way to automate audit log creation for new features, but I can write a quick how-to if that's helpful, @bpmct.

That would be helpful! We can ensure that incoming features are in the audit log during QA and rely on automated tests to ensure records remain accurate. Does that make sense to you @Kira-Pilot?

**Comment by Kira-Pilot** [comment]
Yup, sounds good to me! @bpmct

**Comment by Kira-Pilot** [comment]
@bpmct I am going to close this issue if that's alright with you as I think it has been completed!
[Here](https://www.notion.so/coderhq/Add-a-new-feature-to-the-Audit-Log-8f2b83617e6e4cc0886c38c3a8f3e2ea) is a guide on auditing new features for product/future devs.
[Here](https://github.com/coder/coder/issues/4726) is an epic of Audit issues.
