### ISSUE TITLE
template permissions: some UX bugs

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4412]
> This is for an enterprise feature that isn't live yet (we'll be ironing out some of the bugs before we kick off trials) #4235 

Cannot add "everyone" back once deleted. (I tried refreshing too)

<img width="1146" alt="Screen Shot 2022-10-07 at 7 50 22 AM" src="https://user-images.githubusercontent.com/22407953/194546502-6af0f9de-d2c0-41f9-95fa-8fdb780f4a46.png">

Clicking "Search for user or group" initially shows "No options" but pressing space+backspace shows a complete list

<img width="479" alt="Screen Shot 2022-10-07 at 7 55 46 AM" src="https://user-images.githubusercontent.com/22407953/194547449-cefa0c3c-1edb-42e6-8357-b99be0c40a17.png">
<img width="313" alt="Screen Shot 2022-10-07 at 7 56 41 AM" src="https://user-images.githubusercontent.com/22407953/194547605-84be15ee-f78b-412c-970a-c82e08a96c17.png">

The same user shows up multiple times in search and I can add them multiple times. On refresh, it reduces

https://user-images.githubusercontent.com/22407953/194547879-d9a206bf-62d4-4d37-9b0a-fe8a8c28cf6e.mov

<img width="1129" alt="Screen Shot 2022-10-07 at 7 59 16 AM" src="https://user-images.githubusercontent.com/22407953/194548026-5a93714e-8cbf-4388-9c63-42dde77e4b78.png">

**Comment by BrunoQuaresma** [comment]
Fixed in https://github.com/coder/coder/pull/4235/commits/510287b0ad30ded7bf319f4a27adb34f6c815df4
