### ISSUE TITLE
template permissions: user with `admin` access cannot push or pull a template

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4415]
The Jane user is an admin for a template, but a "user" deployment-wide. I confirmed Jane can edit settings and delete the template, however, Jane cannot push to the template with `coder templates push` or pull with `coder templates pull`.

<img width="1096" alt="Screen Shot 2022-10-07 at 8 21 43 AM" src="https://user-images.githubusercontent.com/22407953/194552143-bc82c94f-dd09-4d24-bfe2-5265cee251a7.png">

```sh
➜  coder templates push 
> Upload "~/coder/examples/templates/docker"? (yes/no) yes
Forbidden.                                  
Run 'coder templates push --help' for usage.
```

> This is for an enterprise feature that isn't live yet (we'll be ironing out some of the bugs before we kick off trials) #4235

**Comment by Emyrk** [comment]
If you can, there should be a log statement for the forbidden.

https://github.com/coder/coder/blob/main/coderd/authorize.go#L76-L84
