### ISSUE TITLE
audit: Show failed logins in audit log

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4431]
Coder Classic (v1) shows failed logins in the audit log. We should consider adding this security feature to our audit log

![failed-login](https://user-images.githubusercontent.com/22407953/194711917-5f3ea788-b6ff-45e4-9735-4c58b367f0be.png)

Thanks @ntimo for pointing this out

**Comment by ammario** [comment]
I started working on this in branch `audit-login` but abandoned it since we have a lot of assumptions around the codebase that Audit Logs are associated with users. We need to add some concept of "anonymous user" to the audit system.

**Comment by Kira-Pilot** [comment]
Closing in favor of #4724 which should handle this case.
