### ISSUE TITLE
[docs]: examples of exposing coder provisioner endpoint w/SSL [via Caddy?]

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#4440]
## thoughts

💭 Coder needs a **"Configure"** documentation page similar to:

-  https://docs.gitlab.com/omnibus/settings/ssl.html 
- https://docs.gitlab.com/omnibus/settings/ssl.html#configure-a-reverse-proxy-or-load-balancer-ssl-termination

## goals

- a zero-knowledge assumed tutorial (such as [done by digital ocean](https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes)) that provides examples of configuring `CODER_ACCESS_URL`

## topics

- ensuring DNS records pointing to an accessible IP address (either public, lan or tailnet)
- introduction to letsencrypt and caddy
- example of caddy (thus letsencrypt) + coder that folks can copy/paste to their way to success

## scenarios

- simple /r/homelab scenario
- production scenarios that are more complex such as k8 ingress.

## considerations

- should docker-compose.yml also include ingress via caddy by default? https://github.com/coder/coder/blob/main/docker-compose.yaml

## references

> Ensure you have an externally-reachable CODER_ACCESS_URL set in your helm chart. If you do not have a domain set up, this should be the IP address of Coder's LoadBalancer (kubectl get svc -n coder).

https://coder.com/docs/coder-oss/latest/install/kubernetes#kubernetes-based-workspace-is-stuck-in-connecting

> Set CODER_ACCESS_URL to the external URL that users and workspaces will use to connect to Coder. This is not required if you are using the tunnel. Learn more about Coder's [configuration options](https://coder.com/docs/coder-oss/latest/admin/configure).

https://coder.com/docs/coder-oss/latest/install/packages

> CODER_ACCESS_URL is required if you are not using the tunnel. Set this to the external URL that users and workspaces use to connect to Coder (e.g. https://coder.example.com/). This should not be localhost.

https://coder.com/docs/coder-oss/latest/admin/configure#access-url

**Comment by bpmct** [comment]
related #3518

**Comment by bpmct** [comment]
@ghuntley I was planning on doing this later this week but haven't started yet. Feel free to grab #3518 from me or just this one if you had something different in mind.

**Comment by bpmct** [comment]
Going to close this in favor of #3518. I've also created a PR with a full Caddy example in #4585.
