### ISSUE TITLE
groups: add brief descriptions under each permission type

### ISSUE THREAD

**Issue by sreya** [coder/coder#4457]
A brief description under each permission type helps educate the user as to what kind of access is being assigned

![image](https://user-images.githubusercontent.com/4856196/194952620-793c347f-4791-4b54-94e1-2824d9cf3ba6.png)

**Comment by BrunoQuaresma** [comment]
What could be good descriptions for it?

**View**
Use and read

 **Admin**
 Read, delete and edit

What do you think @bpmct ?

**Comment by bpmct** [comment]
@BrunoQuaresma what do you think about these descriptions I wrote? Ideally it is consistent with docs

https://github.com/coder/coder/blame/b1da08cdb06eda420c92a0ddc5232f08d92844b6/docs/admin/rbac.md#L13-L14

**Comment by bpmct** [comment]
I remembered we discussed calling it `use` in a call so I changed it in 1a456602f583c5241dcda960873e1bb4ccf4fbc1
