### ISSUE TITLE
groups: add a visual indicator to distinguish "everyone" group

### ISSUE THREAD

**Issue by sreya** [coder/coder#4458]
The "Everyone" group is a special group whose membership cannot be modified. It'd be good to add a tooltip describing what it is and some way to indicate that it cannot be deleted.

**Comment by bpmct** [comment]
🌏

**Comment by bpmct** [comment]
> Everyone group is a built-in group with all Coder users.

**Comment by BrunoQuaresma** [comment]
Closing this since we are not showing the Everyone group anymore.
