### ISSUE TITLE
users: table looks kind of squished

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4461]
If I am not an `Owner` or `Template Admin` the roles look squished

<img width="1093" alt="Screen Shot 2022-10-10 at 4 25 35 PM" src="https://user-images.githubusercontent.com/22407953/194954805-097f271f-50e8-4cf0-af2e-fe4b88f39392.png">

**Comment by kylecarbs** [comment]
@BrunoQuaresma let's beautify this when you get a chance. These roles look really bare right now.
