### ISSUE TITLE
Issues getting email with AzureAD OIDC integration

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#4472]
We've been having issues with onboarding users via AzureAD OIDC configuration which results in this error:

https://github.com/coder/coder/blob/adcf8838d2938db7c9011d3ccefc3d3e4a4c7cf2/coderd/userauth.go#L225

When testing `openid profile email` by default an `id_token` comes back with the following.

```
{
...
  "name": "JV2 User",
  "preferred_username": "jv2user@testdomain.com",
...
}
```

Have to manually add the email address field to the user in AzureAD portal for this to come back:

```
{
...
  "email": "jv2user@testdomain.com",
  "name": "JV2 User",
  "preferred_username": "jv2user@testdomain.com",
...
}
```

I'm just wondering if it should revert back to using `preferred_username` email address component if email is not there?

Interesting note at: https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set

> This value is included by default if the user is a guest in the tenant. For managed users (the users inside the tenant), it must be requested through this optional claim or, on v2.0 only, with the OpenID scope. This value isn't guaranteed to be correct, and is mutable over time - never use it for authorization or to save data for a user. For more information, see [Validate the user has permission to access this data](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens). If you require an addressable email address in your app, request this data from the user directly, using this claim as a suggestion or pre-fill in your UX.

This is curious as I would have thought CoderV1 would have had similar issues?

**Comment by kylecarbs** [comment]
We have a specific edge-case for this in v1, and I suppose we should add it in v2 as well!

**Comment by f0ssel** [comment]
Yes the OIDC spec says that the email field is optional so we should be able to handle not having it in general. 👍

**Comment by dcarrion87** [comment]
FYI, we were able to resolve this with explictly setting `email` optional claim for the app in the affected tenant.

**Comment by dcarrion87** [comment]
Thanks @kylecarbs
