### ISSUE TITLE
[UI] Emoji overflowing in emoji picker

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#4473]
![firefox_txqFudwAhv](https://user-images.githubusercontent.com/57866459/195059493-c86f95f6-dbb5-4543-90c0-47eae61edfbf.gif)

Any emoji that is rendered as 2 characters has this. I think it might be a good idea to directly render the twemoji emojis in the picker ?
![image](https://user-images.githubusercontent.com/57866459/195060574-32a455f9-004a-4548-a461-d1110f645e3c.png)

**Comment by kylecarbs** [comment]
@phorcys420 I'm going to close this for now... seems like this is likely an upstream issue in the emoji picker library we use.
