### ISSUE TITLE
bug: error while creating a workspace from WebUI

### ISSUE THREAD

**Issue by matifali** [coder/coder#4476]
```console
======================= STACK TRACE ========================

Failed to fetch dynamically imported module:
https://coder.domain.com:3000/assets/WorkspaceBuildPage.086a8e7e.js

============================================================
```
Refreshing the page removed it, and the workspace was created successfully.

**Comment by BrunoQuaresma** [comment]
Looks like something during the connection happened and the module was not loaded. I will investigate if there are ways to "retry" to reload the module if it fails. Thanks for letting us know.

**Comment by matifali** [comment]
Didn't experience this for a while. Closing for now assuming it has been resolved.
