### ISSUE TITLE
[site] Add different color schemes

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#4482]
I prefered the original dark theme rather than the new blue one.
I think it would be nice to let the user choose the colors/predefined themes.

I've considered using Dark Reader but the result is just bad.

**Comment by Kira-Pilot** [comment]
@phorcys420 neat idea! Could you let us know why you prefer the dark reader over the blue one?

**Comment by phorcys420** [comment]
> @phorcys420 neat idea! Could you let us know why you prefer the dark reader over the blue one? 

I think you mean dark theme because Dark Reader looks really bad lol, I generally don't like blue-ish themes (e.g Nord) and think dark themes look neater, it's just personal preference I guess.

**Comment by bpmct** [comment]
I like how GitHub does this

<img width="1338" alt="Screen Shot 2022-10-11 at 11 10 32 AM" src="https://user-images.githubusercontent.com/22407953/195144166-fdd7f8b5-8901-4407-be40-82dd035bdaf0.png">

**Comment by ammario** [comment]
I lean towards keeping one color scheme for a very long time. GitHub didn't add a dark theme until 2020, at a scale much larger than Coder. Unlike IDEs and GitHub, Coder is not a product you're going to look at for hours a day. Our job is to create your resources and get you into an IDE as quickly as possible.

Multiple themes means more demand on our scarce design and frontend resources as well as visual bug risks. I'm going to close this for now.
