### ISSUE TITLE
CODER_* environment vars ignored for `coder login`

### ISSUE THREAD

**Issue by hh** [coder/coder#4485]
ENV vars to set defaults for `coder login` are ignored.

Note the email, password, and username provided via ENV vars show up in `--help`

```
ii@prerepair:~/sharingio/coder$ coder login -h
Authenticate with Coder deployment

Usage:
  coder login <url> [flags]

Flags:
  -e, --email string      Specifies an email address to authenticate with.
                          Consumes $CODER_EMAIL (default "hh@ii.coop")
  -h, --help              help for login
  -p, --password string   Specifies a password to authenticate with.
                          Consumes $CODER_PASSWORD (default "ii")
  -u, --username string   Specifies a username to authenticate with.
                          Consumes $CODER_USERNAME (default "ii")
```

If the '-u' option is not provided (and it's currently not defaulting to `CODER_USERNAME`, tty detection is enabled and calling coder login without arguments fails.

Ideally setting these ENV vars would allow us to run `coder login` and respect the ENV provided defaults. I'm also recommend removing the `isTTY` altogether.

https://github.com/coder/coder/blob/main/cli/login.go#L91-L94
```
	if username == "" {
                    if !isTTY(cmd) {
                        return xerrors.New("the initial user cannot be created in non-interactive mode. use the API")
                    }

```

**Comment by f0ssel** [comment]
Sorry for the confusion but I think the issue is that these flags don't do what they look like they do - they only take effect when you are creating the first user for the entire coder deployment. Any subsequent login will always follow the browser flow. I've made a PR to clear this up here - https://github.com/coder/coder/pull/4493

**Comment by hh** [comment]
Thanks heaps @f0ssel !! That makes the intended usage of the flags and ENV vars much clearer.

Would it be possible to ensure that the ENV vars are consumed without needing to additionally supply them via `--first-X` arguments?

I think at this point they are still required.

And specifically, without `-u` the `isTTY` is still checked:

Note that they seem to be visible populated as default when called with `--help`, but are not consumed / utilised.

```
   -e, --first-email string      Specifies an email address to authenticate with.
                          Consumes $CODER_FIRST_EMAIL (default "hh@ii.coop")
  -h, --help              help for login
  -p, --first-password string   Specifies a password to authenticate with.
                          Consumes $CODER_FIRST_PASSWORD (default "ii")
  -u, --first-username string   Specifies a username to authenticate with.
                          Consumes $CODER_FIRST_USERNAME (default "ii")
```
