### ISSUE TITLE
Groups docs link to wrong article

### ISSUE THREAD

**Issue by f0ssel** [coder/coder#4490]
Links to a page about upgrading versions of coder (https://coder.com/docs/coder-oss/latest/admin/upgrade) when it should probably link to upgrading to enterprise - https://coder.com/docs/coder-oss/latest/admin/enterprise.

![image](https://user-images.githubusercontent.com/19379394/195157238-cc18beac-c841-418f-96bb-ae1878c086ba.png)

**Comment by f0ssel** [comment]
@sreya or maybe @ammario

**Comment by bpmct** [comment]
I'll do this before we do a release today
