### ISSUE TITLE
Option to specify URL for agent to connect to Coderd

### ISSUE THREAD

**Issue by fpoussin** [coder/coder#4497]
We have deployed Coder OSS on a Kubernetes cluster for testing and faced a few limitations.
We are using ingresses for everything http/s, which is rather troublesome with coder.
Using the ingress URL (`CODER_ACCESS_URL`) forces agents to reach its IPs outside of the cluster and gets nated only to go back in.

As a workaround, I changed the URL used by agents to reach coderd directly, in my templates:
```hcl
command = [ # Replace ingress url with service for direct connection
  "sh",
  "-c",
  replace(coder_agent.main.init_script, "https://coder\.example\.com", "http://coder.coder.svc.cluster.local")
]
```

A new parameter such as `CODER_SERVER_URL` for this scenario would be nice.

Thanks!

**Comment by kylecarbs** [comment]
You can specify the `url` in a provider block to override it!

```tf
provider "coder" {
  url = "https://coder.example.com"
}
```

**Comment by fpoussin** [comment]
That worked perfectly thanks!
