### ISSUE TITLE
Automatic resource cleanup

### ISSUE THREAD

**Issue by ammario** [coder/coder#4504]
As a Coder deployment administrator, I want to avoid the tedious and error-prone job of cleaning up old workspaces. I propose we let admins define an automatic resource cleanup policy. It could work like this:

* Lock threshold (optional) — after this period of inactivity the workspace is locked and only unlockable by the template admin. The user can delete their workspace at this point, or escalate to a template admin. This is the "safety" period where a user knows their workspace is pending deletion.
* Delete threshold — after the lock threshold + this period, the workspace is deleted

---

> **Note**: This is something we are still considering for our roadmap, feedback is welcome. Feel free to leave a comment in this issue or [contact us](https://coder.com/contact)

**Comment by f0ssel** [comment]
I don't think we should do a lock stage, but maybe just present a warning to the user that they are X days away from this workspace being deleted + some button to extend it.

**Comment by ammario** [comment]
> I don't think we should do a lock stage, but maybe just present a warning to the user that they are X days away from this workspace being deleted + some button to extend it. I think this would be a good fit for an enterprise feature to help control static costs. 

The lock feature comes from #4501, which we should be able to cheaply reuse here. A banner is necessary in any world too.

**Comment by ammario** [comment]
Related https://github.com/coder/coder/issues/5265

Also: lock is unnecessary for MVP.

**Comment by kconley-sq** [comment]
Responding to the stale bot, we would still love to have this feature as we're currently manually monitoring unused workspaces and reaching out to their owners to ask if we can reap them. 🙏

**Comment by dcarrion87** [comment]
Per https://github.com/coder/coder/issues/5815 I just want an option to stop on fail so it kills the resources and also allows users to review the logs to see that it stopped because of XYZ reason. Doing too much bottom cleaning right now.

**Comment by matifali** [comment]
@bpmct May be we can do something like https://cast.ai/

**Comment by dcarrion87** [comment]
Is this related to: https://github.com/coder/coder/issues/5815#issuecomment-1539083873

And is this actually only going to be an Enterprise feature?

**Comment by ammario** [comment]
@dcarrion87 — as the feature is primarily to address scale needs and outside of the developer experience, it's planned for enterprise.

**Comment by ammario** [comment]
Docs on the new feature here: https://coder.com/docs/v2/latest/templates/schedule#failure-cleanup.
