### ISSUE TITLE
No "Manage" tab was found

### ISSUE THREAD

**Issue by ItzMiracleOwO** [coder/coder#4507]
Hi, I have just setup coder with the installation script `curl -fsSL https://coder.com/install.sh | sh`
I entered the web page and I cannot find the manage section. 
Here is a screenshot
![image](https://user-images.githubusercontent.com/76854136/195287651-2655049d-291a-442b-84df-1434db601db2.png)
![image](https://user-images.githubusercontent.com/76854136/195287687-cdc09229-ee7f-4f3e-9367-3acc80b62853.png)

**Comment by bpmct** [comment]
Hey @ItzMiracleOwO - there is no "Manage" screen. All deployment settings in Coder OSS are [configured via flags & environment variables](https://coder.com/docs/coder-oss/latest/admin/configure). You can see a full list of options with `coder server --help`.

We plan on adding a page that shows these settings in the UI, but we imagine they're still configurable at the server level: #4203

**Comment by bpmct** [comment]
Is there a setting in particular you are looking for?

**Comment by ItzMiracleOwO** [comment]
> Is there a setting in particular you are looking for?

Yeah, I was trying to config SSO

**Comment by bpmct** [comment]
Ah got it! Yep - that is configurable in the server: https://coder.com/docs/coder-oss/latest/admin/auth
