### ISSUE TITLE
feat: specify ordering coder_metadata resource items in workspace dashboard

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4511]
Version: [`v0.9.9+abf14d9`](https://github.com/coder/coder/commit/abf14d976a66e1869128410b7170b443c83abf05)

As a DevOps lead, I would like workspace metadata specified in a `coder_metadata` resource to be sorted in a specific way, which is not alphabetical. e.g., CPU, memory, disk should be logically grouped together.

Currently, Coder displays them in alphabetical order, which is not how the lead wants to group them.

Expected behavior is the order in the `coder_metadata` resource is how the metadata will be shown.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/2022166/195345194-767f126c-536d-4234-97a9-9a58c9e45d0f.png">

**Comment by kylecarbs** [comment]
We should just preserve the ordering that the user specifies them in from the metadata... that makes a lot of sense to me.
