### ISSUE TITLE
browser tab title doesn't change away from "Settings - Coder" after navigating away from user settings page.

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#4514]
reproduced on `0.9.8` & `0.9.9`.

reproduction steps:

- click user avatar, select `Account`
- click into either `Security` or `SSH keys`
- navigate back to one of the nav bar tabs (e.g. `Workspaces`, `Templates`, `Users`)
- see browser tab title (shown below)

<img width="649" alt="Screen Shot 2022-10-12 at 9 31 54 AM" src="https://user-images.githubusercontent.com/9683576/195371026-ba918c25-ab11-46f7-b77c-b20f65bb0622.png">

**Comment by kylecarbs** [comment]
This doesn't seem to happen anymore!
