### ISSUE TITLE
No spaces allowed in "Name" field of Create Group screen

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#4515]
not sure if this was intentional, but when typing in a name for a new group, the field does not register any inputs from the `Space` bar.

<img width="467" alt="Screen Shot 2022-10-12 at 9 44 09 AM" src="https://user-images.githubusercontent.com/9683576/195374154-8a179f7c-f86b-47a5-9fe6-7f506ab77d86.png">

**Comment by bpmct** [comment]
The same applies for templates, workspaces, and usernames. They're all validated as usernames under the hood #3321

**Comment by bpmct** [comment]
(I am pro-spaces in templates and groups) and see the rationale for having both a slug and display name
