### ISSUE TITLE
audit: filtering can lead to confusing results because pagination state is kept

### ISSUE THREAD

**Issue by ammario** [coder/coder#4518]
If you're on page n>1 and then select a filter from the "Filters" drop down, you may see unexpected (or zero) results because the old pagination state is kept. 

When there are zero results, there is no visual pager, so the user has no way of knowing what's going on short of opening up their HTTP inspector.

<img width="1016" alt="Screen Shot 2022-10-12 at 11 59 57 AM" src="https://user-images.githubusercontent.com/7416144/195403951-c28f806b-cd7b-45e7-b0aa-79bcf0b0e003.png">

Related: #3907

**Comment by f0ssel** [comment]
if the query changes we should probably kick back to page 1?

**Comment by presleyp** [comment]
Fixed by #4753
