### ISSUE TITLE
audit: add support for APIKey creation and deletion (logins)

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#4538]
We should add audit logging support for APIKey creation and deletion. API Keys, aka session tokens created on login, should be an auditable resource.

An audit log should be generated when a user successfully logs in or out, either via the web UI or via the CLI.

We don't have to worry about audit support for long-lived token creation; that will be handled in [this ticket](https://github.com/coder/coder/issues/4519).

Assumption: we don't have to worry about the update of session tokens, even though the table has an `updated_at` column. Creation and deletion (login and logout) should suffice.

**Comment by Kira-Pilot** [comment]
@bpmct @coadler @sharkymark Making sure this is on everyone's radar.

**Comment by bpmct** [comment]
I agree with the criteria. Should we consider this a `Login` instead?

**Comment by Kira-Pilot** [comment]
@bpmct I think that term would be a lot clearer, especially after we [add tracking for long-lived keys](https://github.com/coder/coder/issues/4519).

**Comment by Kira-Pilot** [comment]
resolved by #5925
