### ISSUE TITLE
Publish helm chart to repo for tools like ArgoCD (et al.)

### ISSUE THREAD

**Issue by jskrzypek** [coder/coder#4539]
ArgoCD is a pretty popular tool for managing K8s deployments. ArgoCD will let you specify a helm repository & chart and take the work & uncertainty out of managing deployed apps.

To use coder's helm chart as you are currently providing it (i.e. the `coder_helm_<VERSION>.tgz` artifact on the release), I would need to manually download and commit that file to my gitops repo to get it deployed. This largely defeats the purpose of ArgoCD.

If, however, the newer coder _(AFAICT you are calling it Coder OSS/Coder Enterprise V2?)_ chart gets published to a publicly available helm repository, then it's something I can point to from, e.g., ArgoCD's helm chart controller or even a kustomize chart-inflater.

Would this be possible? 
For now I have a workaround... Since I'm mostly evaluating Coder for now anyhow I just went ahead and published my own helm-charts repo for this purpose (https://jskrzypek.github.io/helm-charts/index.yaml) I did this by just manually downloading the chart from your releases and running `helm repo index .` on the folder. _I guess that's technically more steps, but hopefully you guys will publish it yourselves at some point..._

**Comment by bpmct** [comment]
We definitely plan on hosting our Helm repository! Glad to hear you have a workaround but we'll get to this soon :)
