### ISSUE TITLE
audit: add support for GitSSHKeys creation and deletion

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#4541]
We should add audit logging support for GitSSHKeys creation and deletion. 

When a user regenerates an SSH Key in the Web UI, we should log it. Question for product/BE: is this an 'update' or a 'creation'?

This ticket needs more clarity on what CLI commands should generate SSH key audit logs.

**Comment by bpmct** [comment]
I'd consider this an update. Creation and deletion only occurs when the user account is created/deleted

**Comment by Kira-Pilot** [comment]
Looks like there's only regeneration for the SSH Key resource, and we have that handled in the above PR. Closing this, but @coadler please reopen with more details if I'm missing something.
