### ISSUE TITLE
A user who is only a member can see the Users tab, all users, and all groups

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4550]
Version: [`v0.9.10+574e5d3`](https://github.com/coder/coder/commit/574e5d37c76cb0b154ad62ccd4582e588235b15a)

I created a user who is just a member, and belongs to 1 group.

When I log in as that user, they can access the Users UI, see all users, and all groups.

Seems like a violation of security.

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/2022166/195849624-6a1e5ffc-5f6c-4a24-8287-f7851184d063.png">
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/2022166/195849664-12d9d249-e442-4234-a896-d7069afd74f6.png">

**Comment by bpmct** [comment]
Somewhat related: #4318. These both should probably be considered

**Comment by bpmct** [comment]
Closing in favor of #5002
