### ISSUE TITLE
Configure SSH Proxy to individual workspaces

### ISSUE THREAD

**Issue by neezer** [coder/coder#4559]
I'd like to do remote development on my Coder workspace using [Nova](https://nova.app). Nova has its own internal SSH client, and so cannot benefit from the ease-of-use provided by `coder ssh` & co.

As the IP address of my workspace is ephemeral (may change on start/stop/recreate), I don't want to rely on the IP address of my workspace. What I'd really love is to use a subdomain and have that proxy SSH to my workspace.

So, if my workspace is named `neezer-dev` and coder is hosted at `coder.acme.dev`, then I could connect via SSH to `neezer-dev--ssh.coder.acme.dev` or similar, like how workspace apps are hosted using the [wildcard domain](https://coder.com/docs/coder-oss/latest/admin/configure#wildcard-access-url).

I initially posted in the Discord server about this, FYI: https://discord.com/channels/747933592273027093/1030527994680320091/1030527994680320091

**Comment by bpmct** [comment]
I might be missing something but I was able to connect to a Coder workspace with Nova using `config-ssh`.

1. Run `coder config-ssh -y`
2. Configure Nova to use the SSH host for the workspace that Coder generates (the ProxyCommand seems to just work)
    <img width="400" alt="Screen Shot 2022-10-15 at 9 11 35 PM" src="https://user-images.githubusercontent.com/22407953/196014752-dfafdb66-09c9-4462-920b-9f6b9f8e61f0.png">
4. The remote terminal and remote filesystem seems to work fine
   <img width="400" alt="Screen Shot 2022-10-15 at 9 14 31 PM" src="https://user-images.githubusercontent.com/22407953/196014723-9bdb922c-34ae-4d55-91df-35c5544502c8.png">

**Comment by bpmct** [comment]
I like the idea of adding support for a generic SSH/bastion proxy instead of tunneling via the CLI, but this doesn't seem to be a blocker for Nova.

**Comment by neezer** [comment]
Hmm, you're right. I think I got tripped up with `Address` not being the address of my workspace, but rather the `Host` entry in my SSH config.

Can a similar trick be used in my iPad for [Secure ShellFish](https://secureshellfish.app)? Or not, because the `coder` CLI isn't present there?
