### ISSUE TITLE
Quota enforced silently after license disabled

### ISSUE THREAD

**Issue by ammario** [coder/coder#4560]
I removed my enterprise license from my deployment and Quota enforcement is still active, even though there are no entitlements.
<img width="1661" alt="Screen Shot 2022-10-14 at 4 09 59 PM" src="https://user-images.githubusercontent.com/7416144/195944423-fbc8b2f9-974f-4194-a93b-9d050cd5cf34.png">

**Comment by f0ssel** [comment]
I wrote the following test and did not reproduce the behavior you have in this issue - 
```
	t.Run("EntitlementsAfterDelete", func(t *testing.T) {
		t.Parallel()
		client := coderdenttest.New(t, &coderdenttest.Options{
			UserWorkspaceQuota: 10,
		})
		_ = coderdtest.CreateFirstUser(t, client)
		ctx, cancel := context.WithTimeout(context.Background(), testutil.WaitLong)
		defer cancel()

		l := coderdenttest.AddLicense(t, client, coderdenttest.LicenseOptions{
			AccountID:      "testing",
			WorkspaceQuota: true,
		})
		entitlements, err := client.Entitlements(ctx)
		require.NoError(t, err)
		require.True(t, entitlements.Features[codersdk.FeatureWorkspaceQuota].Enabled)

		err = client.DeleteLicense(ctx, l.ID)
		require.NoError(t, err)

		entitlements, err = client.Entitlements(ctx)
		require.NoError(t, err)
		require.False(t, entitlements.Features[codersdk.FeatureWorkspaceQuota].Enabled)
	})
```

Is this an accurate representation of the steps you took?

**Comment by f0ssel** [comment]
This actually seems like a bug with not handling a case when we go from having a license to no license at all. Will make a fix

**Comment by ammario** [comment]
This is irrelevant after #5012
