### ISSUE TITLE
SCP file transfer does not support relative file paths

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#4564]
When a canonical path is not specifed, scp should have the base path be the home of the current user.

``scp -r ./folder coder.env:.cache/JetBrains/Fleet``
``scp: stat remote: No such file or directory``

``scp -r ./folder coder.env:/home/coder/.cache/JetBrains/Fleet`` works fine.

I have checked and this SCP behavior is functional over regular SSH.
This is causing [JetBrains Fleet](https://www.jetbrains.com/fr-fr/fleet) to not work remotely.

**Comment by kylecarbs** [comment]
Fixed by #4549
