### ISSUE TITLE
Support multiple users with ``coder config-ssh`` / ``coder ssh``

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#4565]
This is an hypothesis and might not be doable for every environment.

I'd like to be able to use ``ssh user@coder.env``, currently it's just being ignored and I'm being logged in as ``coder`` anyways.

**Comment by kylecarbs** [comment]
I think we could do this pretty easily. If no user is specified, we'll just default as the agent user.

It gets a bit tricky though for login; since we're not a _real_ SSH server authentication gets wonky. We could allow users to have their SSH server instead, and we just proxy to it.

**Comment by phorcys420** [comment]
I think we shouldn't have auth since we already don't for ``coder ssh`` (well, the coder auth is the auth) and most people would have sudo be passwordless, so it doesn't represent a security flaw in my opinion.

**Comment by bpmct** [comment]
We have some use cases that rely on the UID in order to give the user access to the users' files on an NFS share. Allowing the user to log in as any user on the workspace or `root` (versus the user the agent started with) would be particularly dangerous.

**Comment by phorcys420** [comment]
would it really be ?

if the user can use ``coder ssh`` they should already be able to log in as any user indirectly (ssh as coder then run sudo or whatever).
or logging in as a different user should only be allowed for the workspace owner ?

**Comment by bpmct** [comment]
Some templates start with a non-sudo user to restrict actions within a workspace.

**Comment by ElliotG** [comment]
From a security perspective, I can say the following is true:

- Having all actions log as the actual user makes the Infosec teams much happier
- Allowing users to connect to other user workspaces is probably unacceptable at most security-conscious companies. It enables a dangerous amount of lateral movement, and opens up doors for privilege escalation. Happy to chat more if this is helpful.

**Comment by phorcys420** [comment]
> Allowing users to connect to other user workspaces is probably unacceptable

This isn't what we're discussing though, we're discussing logging in as a separate user on your own workspace, e.g root@coder.workspace
