### ISSUE TITLE
feat: Show groups a user belongs to, from Users UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4566]
Version: [`v0.9.10+574e5d3`](https://github.com/coder/coder/commit/574e5d37c76cb0b154ad62ccd4582e588235b15a)

I do not think there is a way to view all groups that a user belongs to. The API endpoint will be helpful too.
<img width="1061" alt="groups-by-user" src="https://user-images.githubusercontent.com/2022166/195998816-c0ee2f92-5daa-4668-9329-bb2038757af9.png">

**Comment by sharkymark** [comment]
Re-opening. @bpmct This is a v1 customer requirement too. As an active user of v2 where I test groups and added users into groups, it is very difficult to understand what groups a user belongs to.

**Comment by bpmct** [comment]
I think we could also show these as pills in the account dropdown.
