### ISSUE TITLE
Remove "private" icon from apps in dashboard

### ISSUE THREAD

**Issue by ammario** [coder/coder#4570]
The absence of the lock makes it seem like these apps are not private.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/7416144/196010405-45efea63-736a-4bb7-b4c5-9398768adb50.png">

**Comment by bpmct** [comment]
What do you think about hiding the "private" icon on apps instead, making it implicit? We can still show icons for public, authenticated users, or other access levels we add down the road.
