### ISSUE TITLE
Support X11 forwarding for SSH connections

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#4572]
Currently, whenever I SSH into a workspace with the ``-X`` argument it will show a warning telling me that X11 forwarding failed.

It would be nice to be able to use GUI apps over SSH within Coder.

**Comment by janLo** [comment]
I would be very interested in having X2go working through the coder agent because it provides much more features than VNC. This would actually allow coder to be used as a backend server for thin client applications.
