### ISSUE TITLE
Duplicate key on OpenID connect

### ISSUE THREAD

**Issue by klauserber** [coder/coder#4576]
Hello, I am working on a cluster setup for devops & developer trainings. A central part of it is coder to give the participants a fancy development environment. For email based self registration I use keycloak and OIDC in coder. I don't now the email domains, so it is not possible to restrict them.

When 2 users with the same name before the @ try to register (e. g. hans@example1.com and hans@example2.com), the second user gets the error:

    {"message":"Failed to process OAuth login.","detail":"in tx: execute transaction: create user: execute transaction: create user: pq: duplicate key value violates unique constraint \"idx_users_username\""}

Is it possible to configure how the names a built? May by converting hans@example2.com to hans-example2-com or similar. Or give the second user a number suffix (hans2).

**Comment by bpmct** [comment]
@klauserber it looks like this just missed the `Coder v10.0.1` release but we'll get it in for v10.0.2 later this week

**Comment by klauserber** [comment]
@bpmct That is absolutely fine for me. Thank you for the very fast implementation.

How does the solution look like? As I can see in the code, the user get a random name if there is a conflict, right?

**Comment by sreya** [comment]
@klauserber using your example above it would be `hans-<random-name>`. It will only be truly random if the username is longer than 32 characters.
