### ISSUE TITLE
Add to DoD's Big Bang repo

### ISSUE THREAD

**Issue by ammario** [coder/coder#4603]
We have some DoD customers that need Coder in [Big Bang](https://github.com/DoD-Platform-One/big-bang) for ease of deployment.

**Comment by ericpaulsen** [comment]
[Iron Bank](https://p1.dso.mil/products/iron-bank) will also be needed.

**Comment by sharkymark** [comment]
Added @ericpaulsen to do this after HA has been tested and port forward sharing - target 2022-10-31

**Comment by ericpaulsen** [comment]
I've submitted a request to Iron Bank to provision a new repo for Coder v2: https://repo1.dso.mil/dsop/coder-enterprise/coder-enterprise/coder-service/-/issues/29
