### ISSUE TITLE
Fail to start for PostgreSQL <=12

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#4608]
We don't support it, so we shouldn't succeed!

**Comment by ammario** [comment]
Context: I put a change in to fixed a "bug" that only showed up in PG11 but broke many deployments.

I've been using PG11 fine in my development environment for weeks, so it's possible we break deployments by adding a hard version check.

**Comment by kylecarbs** [comment]
Our migration breaks it though, so if we don't add a hard-set check we risk breaking deployments in a worse way.
