### ISSUE TITLE
upgrade failure from 0.9.10 to 0.10.0: migrate up: up: Dirty database version 59. Fix and force version

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4613]
Version: [`v0.10.0+8ab4d26`](https://github.com/coder/coder/commit/8ab4d264746527789603377358e20dabf4645fca)

Upgrading a deployment with systemd from 0.9.10 to 10.0 and coder is not starting.

coder service error:
`migrate up: up: Dirty database version 59. Fix and force version.`

systemctl status coder.service
● coder.service - "Coder - Self-hosted developer workspaces on your infra"
     Loaded: loaded (/lib/systemd/system/coder.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-10-17 22:40:16 UTC; 8min ago
       Docs: https://coder.com/docs/coder-oss
    Process: 1493883 ExecStart=/usr/bin/coder server (code=exited, status=1/FAILURE)
   Main PID: 1493883 (code=exited, status=1/FAILURE)

Oct 17 22:40:11 mark-v2 coder[1493883]: migrate up: up: Dirty database version 59. Fix and force version.
Oct 17 22:40:11 mark-v2 coder[1493883]: Run 'coder server --help' for usage.
Oct 17 22:40:11 mark-v2 systemd[1]: coder.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 22:40:11 mark-v2 systemd[1]: coder.service: Failed with result 'exit-code'.
Oct 17 22:40:11 mark-v2 systemd[1]: Failed to start "Coder - Self-hosted developer workspaces on your infra".
Oct 17 22:40:16 mark-v2 systemd[1]: coder.service: Scheduled restart job, restart counter is at 3.
Oct 17 22:40:16 mark-v2 systemd[1]: Stopped "Coder - Self-hosted developer workspaces on your infra".
Oct 17 22:40:16 mark-v2 systemd[1]: coder.service: Start request repeated too quickly.
Oct 17 22:40:16 mark-v2 systemd[1]: coder.service: Failed with result 'exit-code'.
Oct 17 22:40:16 mark-v2 systemd[1]: Failed to start "Coder - Self-hosted developer workspaces on your infra".

**Comment by sharkymark** [comment]
Being worked on with a new release. Need to be on Postgres 13 or higher, and superuser is preferable in Postgres but the patch will address that.

**Comment by kylecarbs** [comment]
v0.10.1 has been published and should fix this! Close this if it does for you

**Comment by sharkymark** [comment]
If you end up in my state, you need to reset the migration cursor so it will reattempt the 0.10.0 migrations again since the database is marked that it did, even though the migrations failed.

`update schema_migrations set dirty='f';`
`update schema_migrations set version=58;`

**Comment by sharkymark** [comment]
@kylecarbs right, but the above steps are required for anyone in my state, right?

**Comment by kylecarbs** [comment]
Yup!

**Comment by sharkymark** [comment]
Resolved. Thank you!
