### ISSUE TITLE
Global flag to disable username edits

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4618]
We should make it possible to disable editing usernames in order to rely on usernames from SSO via a global flag (e.g. `DISABLE_USERNAME_EDITS`. 
## Prior art

- Coder Classic has a configurable flag to disable username changes
    <img width="854" alt="Screen Shot 2022-10-18 at 9 56 56 AM" src="https://user-images.githubusercontent.com/22407953/196466442-9a1e414a-ac17-4145-91f8-dfbc4a25c31e.png">
- GitLab and GitHub both allow username changes but preserve the past username to "redirect" links and resources
- GitLab and Sourcegraph have a global configuration to disable username changes

**Comment by ammario** [comment]
It would be nice to avoid yet another knob...

Username reuse is a larger security risk for Coder than these other products because many will name user-scoped infrastructure with usernames. This infrastructure could be secrets or personal volumes.

Perhaps we could prevent username reuse, except when the reuser originally held the username? With this approach we get redirects and secure default behavior.

**Comment by bpmct** [comment]
Sure, we could do that instead.

**Comment by ammario** [comment]
I'll take a stab at this.

**Comment by ammario** [comment]
As I was testing this behavior, I changed my username which then accidently deleted my dogfood development environment, including about an hour of unpushed work.

I'm convinced until we do a better job of preventing persistent resource deletion, we shouldn't allow changing usernames at all.

**Comment by BrunoQuaresma** [comment]
@ammario does it apply to admins as well?

**Comment by ammario** [comment]
> @ammario does it apply to admins as well?

I go back on my statement that we should prevent username edits. I wrote [this doc](https://coder.com/docs/coder-oss/latest/templates/resource-persistence) on Resource Persistence that should help people keep their data.

**Comment by matifali** [comment]
We should turn off username edits even for admins for SSO/OIDC/GitHub accounts.

**Comment by sreya** [comment]
I believe support this already

**Comment by matifali** [comment]
Admins can still edit their own usernames for OAuth accounts.
