### ISSUE TITLE
helm: Run coder with an external ServiceAccount

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4620]
In order to give Kubernetes deployment access to other clouds & resources (e.g. create GKE VMs, AWS VMs) we should add an option to specify a serviceaccount

**Comment by ericpaulsen** [comment]
I can take this on.

**Comment by kylecarbs** [comment]
Should we allow just mounting arbitrary files in general? Seems like I might want to store my GCP or AWS credentials in files?

**Comment by ericpaulsen** [comment]
yes but in addition, we'd likely need to support custom SA annotations for stuff with IAM policy bindings, e.g. [Google Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)

**Comment by bpmct** [comment]
> Should we allow just mounting arbitrary files in general? Seems like I might want to store my GCP or AWS credentials in files?

created #4246 to address this

**Comment by bpmct** [comment]
closed as completed by #4640
