### ISSUE TITLE
audit: log update workspace events

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#4624]
If a template changes, the user may update an associated workspace, either in the CLI (`coder update "workspace-1"`), or in the UI:
<img width="588" alt="Screen Shot 2022-10-18 at 1 38 46 PM" src="https://user-images.githubusercontent.com/19142439/196504573-851cf394-463f-49b2-b04e-2b6c8108a4da.png">

Additionally, in the future, we might make it possible for users to toggle between template versions in the UI.

We should audit these template version changes. One easy way might be to include the `template_version_id` in the workspace build diff, but we should check that 1) this works when we're updating via the CLI and 2) that this satisfies the product requirement, as we won't have a separate line item for workspace template changes.

**Comment by Kira-Pilot** [comment]
@bpmct A potentially easy way to do this would be to include the template version ID in the diff of the workspace build audit log line (imagine the below line item with a diff showing old and new template version ID):
![Screen Shot 2023-01-04 at 5 21 01 PM](https://user-images.githubusercontent.com/19142439/210661067-ddcfe46e-b030-4120-8998-20155e538c6b.png)

Would this be sufficient or do we need a distinct line item like "Admin started workspace build for foo with template version bar"?

**Comment by bpmct** [comment]
The version ID in the diff is definitely a good start! We can just scope it to that for now

**Comment by Kira-Pilot** [comment]
Resolved by #5841
