### ISSUE TITLE
Kubernetes Experience

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4628]
Today, Coder has full support for [Kubernetes via Helm](https://coder.com/docs/coder-oss/latest/install/kubernetes#install-coder-with-helm). This is an umbrella issue prioritizing issues around using Coder with Kubernetes. 

## High

- [x] #3545
- [x] #4620
- [x] #4627
- [x] #4649
- [ ] #2992 
- [x] #4639
- [x] #5024

## Medium
- [ ] #4767
- [x] #3519
- [x] #4666
- [x] #4246
- [x] #4632

## Low

- [x] #4633

**Comment by ElliotG** [comment]
https://github.com/coder/coder/issues/4649 can be added to this list.
