### ISSUE TITLE
Bug: Template page hangs during initial creation

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#4649]
**Repro:**

1. Use https://github.com/ElliotG/coder-oss-gke-tf/blob/main/main.tf to deploy Coder on GKE (though any fresh install might work)
2. Fill out the initial org/user
3. Hit Templates

The screen hangs forever, and you have to re-navigate back to you. Once you do, Kubernetes shows up as an available template.

**Errors in Console:** 
Failed to load resource: the server responded with a status of 401 (Unauthorized)
/api/v2/users/first:1 
 Failed to load resource: the server responded with a status of 404 (Not Found)
/api/v2/templatevers…7f5fd65/resources:1 
 Failed to load resource: the server responded with a status of 412 (Precondition Failed)

Not a big deal, except that this is your first experience with the product, and who wants your first experience being mired by a bug.

**Comment by bpmct** [comment]
Ah - I ran into this yesterday but figured it was something with my network! Thanks for reporting

**Comment by ElliotG** [comment]
I tried it twice, so it seems consistent on first install. Gotta have something to do with the initialization of the first kubernetes template.

**Comment by deansheather** [comment]
The way we import the default templates is very hacky ATM and we'll likely want to rework it completely to be a whole UX workflow where users can pick which templates they want after the create first user screen.
