### ISSUE TITLE
There are 4 example templates that basically do the same thing - confusing - remove one

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4651]
Version: [`v0.10.1+3c40698`](https://github.com/coder/coder/commit/3c406980336303f32685915a9bd3e27ace81c91d)

Besides the coder templates init being cluttered for way too long, there are 4 Docker templates that all have code-server in them, that for all intents and purposes are the same.

This one, has code-server in the image, so the startup_script doesn't install it, and only starts it.
https://github.com/coder/coder/blob/main/examples/templates/docker-code-server/main.tf

Please trim this down. I think one, that has dotfiles, is fine.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2022166/196674478-d984b81a-4ef5-471d-a68e-1e78f47b17b0.png">

**Comment by bpmct** [comment]
@ericpaulsen has a fix underway in #4634 which only shows "Develop in Docker." It will not have dotfiles support though

**Comment by sharkymark** [comment]
I still propose removing so many docker templates. Just have 1. The Dockerfile one seems overly complicated.
