### ISSUE TITLE
progress bar: templates with less than 3 builds should not show "any moment now" estimation

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4652]
I created a brand new template and the estimate is inaccurate since there is not any data at this point. 

<img width="1437" alt="Screen Shot 2022-10-19 at 8 09 18 AM" src="https://user-images.githubusercontent.com/22407953/196699994-e7d4b949-5a18-48e8-981d-ae5dd8051412.png">

**Comment by kylecarbs** [comment]
Just ran into this. Def needs a fix

**Comment by BrunoQuaresma** [comment]
Just checking. We only should show this bar if there are 3 builds at least. Is that right?

**Comment by bpmct** [comment]
Yep!
