### ISSUE TITLE
helm: support prometheus port

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4666]
I have set the environment variables `CODER_PROMETHEUS_ENABLE` and `CODER_PROMETHEUS_ADDRESS` in my helm chart, but I suppose I can't use a `PodMonitoring` to ingest into Google Cloud Monitoring until the port is exposed in the pod spec?

I might be missing something though!

**Comment by coadler** [comment]
This is correct!

**Comment by coadler** [comment]
By default it's 2112 but you can set it to whatever you want. You'll probably also need to change it to listen on 0.0.0.0.

**Comment by mtojek** [comment]
It looks like the issue is stale, so I hope you don't mind if I take over it as I haven't looked into the helm chart yet.
