### ISSUE TITLE
bug: coder app links css is borked

### ISSUE THREAD

**Issue by bartonip** [coder/coder#4672]
If you have many coder_app links against a particular coder agent they now run off the screen.

<img width="861" alt="Screen Shot 2022-10-21 at 11 17 52 am" src="https://user-images.githubusercontent.com/21701128/197082972-cdc34d41-b5fa-423c-84a6-20014b99b6fa.png">

**Comment by kylecarbs** [comment]
Oofta, we'll fix this ASAP!
