### ISSUE TITLE
feat: Logs "Started At" l10n

### ISSUE THREAD

**Issue by bartonip** [coder/coder#4673]
Please make it possible to change the localisation of the datetime string in the "Started At" column of the logs.

**Comment by BrunoQuaresma** [comment]
By localization do you mean setting a custom timezone? Can you provide a use case or describe a bit more about what you would expect?

**Comment by bartonip** [comment]
<img width="1378" alt="Screen Shot 2022-11-11 at 12 27 00 pm" src="https://user-images.githubusercontent.com/21701128/201240873-66fe129a-8773-4f60-aa2d-c6365f68dbd7.png">

Not specifically a custom time zone, but being able to choose the date/time format like dd/mm/yyyy. 

In the above image if the highlighted date was, say 10/08/2022 in Australia we'd immediately read that as 8th of August. It would be nice to have the option of choosing the date format to avoid misunderstandings caused by this.
