### ISSUE TITLE
Possible issue with subdomains

### ISSUE THREAD

**Issue by bartonip** [coder/coder#4674]
I keep getting 404's when trying to use the `subdomain = true` option in the Terraform config.

My configuration is as below:

```
resource "coder_app" "pgadmin" {
  agent_id = coder_agent.main.id
  name     = "PGAdmin"
  url      = "http://localhost:8800/"
  icon     = "https://simpleicons.org/icons/postgres.svg"
  subdomain = true
}
```

Which generates the subdomain `https://pgadmin--main--workspacename--username.coder.domain/` in the workspace link.

However when I go to this link, the call does not get proxied down into the container. If I curl `http://localhost:8800` in the container it works fine. 

Can you please advise if I am doing something wrong?

**EDIT**
I have just tried using `https://8800--main--workspacename--username.coder.domain/` and this works so the service is reachable but the coder_app subdomain stuff is not proxying correctly

**Comment by bpmct** [comment]
I think this is because the app name has capital characters. 

@bartonip we have a fix underway for this: #4573
