### ISSUE TITLE
web port forwarding failing to load running app

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4675]
Version: [`v0.10.2+fbbecf0`](https://github.com/coder/coder/commit/fbbecf0846344650b889629005731388f3a35082)

Removing my Coder deployment cookies did resolve this, but this is a bad user experience.

Web port forwarding was working for me, then I upgraded my deployment to either 0.10.1 or 0.10.2 (I forget), and I get this blank screen with a cookie message when clicking the running process link inside the port forward pop-up

![image](https://user-images.githubusercontent.com/2022166/197186175-3f8849f9-be5e-4097-9069-8f20ff09cc3f.png)

**Comment by kylecarbs** [comment]
Humph, we must be doing something weird with redirects. Does clearing cookies fix it?
