### ISSUE TITLE
Add a timeout + debug steps to the Coder agent (agent stuck in `Connecting...` forever isn't accurate)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4678]
This is taken from #4201 

> Step 3. Add a timeout parameter to the coder_agent resource
> After the specified duration of inactivity, the UI and CLI would display that something wrong happened. Templates can define a debug_url parameter in their front-matter that can direct users to a help page.

After the timeout, the agent can go from `Connecting` to `Disconnected`

This debug_url can be surfaced in the dashboard/CLI to make it easy for admins to troubleshoot a timed-out workspace. For larger deployments, an admin could edit the template README and change `debug_url` to an internal wiki/chat/ticketing system so users can request help. Perhaps the debug URL could also be surfaced for failed builds as well

**Comment by BrunoQuaresma** [comment]
I made some designs for this one:

![Initial](https://user-images.githubusercontent.com/3165839/198693316-58061545-5905-41a5-8bcb-7d41b6382ea2.png)
![Tooltip Open](https://user-images.githubusercontent.com/3165839/198693319-b0a7ff3f-9b45-4f5e-88bc-0dfc102ba25c.png)

Figma link: https://www.figma.com/file/YIGBkXUcnRGz2ZKNmLaJQf/Coder-Product-V2?node-id=1484%3A963

**Comment by BrunoQuaresma** [comment]
Some thoughts:
- Add a coder agent config called `connection_timeout`
- If the connection is "timeout" interrupt the connection to free up some resources
- When timeout, the `WorkspaceAgentStatus` should be `timeout` so we can consistently rely on that on the client side (CLI and Web App)
