### ISSUE TITLE
Surface agent status in workspaces page

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4679]
As a Coder admin looking for failed workspaces, I can currently use `status:failed` (https://coder.example.com/workspaces?filter=status%3Afailed) to detect and troubleshoot users' broken workspaces.

However, it is not as easy to find workspaces that appear to be "running," yet an agent is stuck in "connecting" or "disconnected." Can we make this query-able from the "workspaces" page? For example: `status: running has-agent:disconnected`

## Related

- #4678

**Comment by mtojek** [comment]
Let me see if I can extend the db query.
