### ISSUE TITLE
progress bar: Shutting down a workspace says "build running"

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4691]
Version: [`v0.10.2+fbbecf0`](https://github.com/coder/coder/commit/fbbecf0846344650b889629005731388f3a35082)

I'm not sure "build running" describes a workspace shutting down

<img width="480" alt="image" src="https://user-images.githubusercontent.com/2022166/197277541-22b65671-1a5c-47f9-8b3a-03439aeaee2c.png">

**Comment by BrunoQuaresma** [comment]
What would be the expected verbiage here?

**Comment by BrunoQuaresma** [comment]
I would suggest a few changes:
- Only show this bar when the job status is "running"
- Update the message to use the latest build status so it would be "Starting.", "Pausing", "Deleting", etc.
Thoughts?

**Comment by bpmct** [comment]
> Update the message to use the latest build status so it would be "Starting.", "Pausing", "Deleting", etc.

Let's do this :)
