### ISSUE TITLE
Install script does not natively support NixOS

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#4698]
When someone curl's to bash our installer on NixOS the installer warns that NixOS is unsupported.

Let's change that...

<img width="1725" alt="CleanShot 2022-10-21 at 18 45 42@2x" src="https://user-images.githubusercontent.com/127353/197305779-cb7b08da-25e9-4ab9-83d0-f5c66572036a.png">

# request for change

1. Add coder/coder to nixpkgs at https://github.com/NixOS/nixpkgs
2. Add configuration options for starting coder on NixOS as a daemon (see below)
3. Configure @ghuntley as maintainer in nixpkgs
4. Update install.sh to run `nix-env -i coder` if executed on NixOS :)

ps. https://github.com/coder/coder already has flakes support.

# configuration surface

At min expose the following...

```nix
services.coder.enable = boolean;
services.coder.access-url = string;
services.coder.wildcard-access-url = string;
services.coder.postgres-connection-urk = string;
services.coder.tls.enable = // please make coder.tls.* config options feel natural to nixos users.
services.coder.tls.cert =  // please make coder.tls.* config options feel natural to nixos users.
services.coder.tls.key =  // please make coder.tls.* config options feel natural to nixos users.
```

# resources

0. https://github.com/coder/coder/blob/main/flake.nix
1. https://coder.com/docs/coder-oss/latest/admin/configure

**Comment by ghuntley** [comment]
I'm opening this up as a open-source bounty circa $100USD plus some cool merch is available for the person who helps ship this. https://twitter.com/coderhq/status/1584217565370667008

**Comment by shyim** [comment]
see https://github.com/NixOS/nixpkgs/pull/197613

**Comment by shyim** [comment]
Are there anything else "magically" installed?

I found postgres + terraform
