### ISSUE TITLE
progress bar does not show estimated build time even when there are 2 previous builds

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4705]
Version: [`v0.10.2+fbbecf0`](https://github.com/coder/coder/commit/fbbecf0846344650b889629005731388f3a35082)

The progress works most of the time, estimating build time. But in this PhpStorm workspace, it appears to not want to give an estimate.

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/2022166/197392601-f23e6534-a6d5-495d-a39e-f3b7edc8990f.png">

**Comment by sharkymark** [comment]
It started showing build times on the 4th build. Is that expected behavior?

**Comment by ammario** [comment]
By "does not show estimate" I assume you mean it says "any moment now..." instead?
