### ISSUE TITLE
bug: coder_app label uses terraform resource name and ignores display name

### ISSUE THREAD

**Issue by bartonip** [coder/coder#4714]
If you define a `coder_app` and use the new `display_name` functionality `Coder v0.10.2+fbbecf0 Wed Oct 19 13:49:48 UTC 2022` ignores the `display_name`

**Comment by kylecarbs** [comment]
https://github.com/coder/coder/pull/4573 has to be merged before it'll work!

**Comment by bartonip** [comment]
Ahhh no worries, I just got a bit confused because the Terraform resource had already been published.

**Comment by kylecarbs** [comment]
@bartonip not a biggie, I'll actually leave this open so you can track once it's merged and released!

It's unfortunate that our provider doesn't track releases right now, but I haven't come up with a great solution for that yet.

**Comment by BrunoQuaresma** [comment]
A new release made: https://github.com/coder/coder/releases/tag/v0.12.2 including the #4573 fix.
