### ISSUE TITLE
Allow HEAD requests for routes such as /api/v2

### ISSUE THREAD

**Issue by kotx** [coder/coder#4716]
[Updown](https://updown.io) tries to use HEAD requests to check status. It would be useful if the `/api/v2` endpoint allowed HEAD requests.
Maybe there are some other routes I don't know of that could support HEAD requests as well? Though they might not be as useful.

**Comment by bpmct** [comment]
Hey - you could use the `/healthz` endpoint for this

```sh
➜  ~ curl --head https://dev.coder.com/healthz
HTTP/1.1 200 OK
```
