### ISSUE TITLE
Audit Experience

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#4726]
An umbrella issue dedicated to improving the Audit Log.

### High

- [x] #4625
- [x] #4668
- [x] #4537
- [x] #4513
- [x] #4624 
- [x] #5356
- [x] #4724 
- [x] #4538
- [x] #4736 
- [x] #5003
- [x] #4519
- [x] #5536
- [ ] #5419
- [x] #5268
- [x] #5673 
- [x] #6029
- [x] #6108
- [x] #6054 
- [ ] #6225

### Medium

- [x] #4623
- [x] #5534
- [ ] #5535
- [x] #4561
- [x] #4768
- [x] #4518
- [x] #4729
- [x] #4668
- [x] #4796
- [x] #5183
- [ ] #6095
- [x] #6151

### Low

- [x] #4312 
- [x] #2516 
- [x] #4730 
- [x] #4769 
- [ ] #4856 
- [x] #4875 
- [x] #5234
- [x] #5269
- [ ] #5270
- [ ] #6094

**Comment by bpmct** [comment]
@Kira-Pilot what do you think about #4768 under medium?

**Comment by Kira-Pilot** [comment]
@bpmct Think that's a great idea. It doesn't seem overly complicated to me, but I'll investigate further.

**Comment by bpmct** [comment]
just saw #5003 come in as well

**Comment by bpmct** [comment]
@Kira-Pilot I added #5356 to "high"

**Comment by Emyrk** [comment]
A discussion on audit logs that would greatly impact the UI and experience around audit logs.

https://github.com/coder/coder/discussions/5419

**Comment by bpmct** [comment]
FYI - I added #5535 to `high` and #5534 to `medium`. Happy to discuss further

**Comment by kylecarbs** [comment]
Assuming this close was an accident!

**Comment by Kira-Pilot** [comment]
Thanks @kylecarbs!
