### ISSUE TITLE
[Investigation] Create a model of free vs enterprise audit logging 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#473]
As a company, we want to offer the most important audit logging to users for free while also providing a more advanced set of logging four our enterprise customers. Investigate both industry standards and other potential company -tailored solutions and provide and RFC for a few potential models so that we can choose and implement the most compatible solution for our customer base. 

Bear in mind:  it is easier for us to un-restrict than retroactively restrict things.

**Comment by tjcran** [comment]
Closing as we have decided on Audit Logging as a paid-only feature, for now.
