### ISSUE TITLE
Long metadata strings get truncated

### ISSUE THREAD

**Issue by bartonip** [coder/coder#4741]
Can we have a way to specify that a particular metadata string not be truncated even if its too long?
<img width="826" alt="Screen Shot 2022-10-25 at 9 41 29 pm" src="https://user-images.githubusercontent.com/21701128/197753151-e89e7778-8f67-4470-a77e-6fd3b74acb9d.png">

**Comment by kylecarbs** [comment]
@BrunoQuaresma I know this was an intentional decision by us, but I wonder if there's a better way.

**Comment by BrunoQuaresma** [comment]
@bartonip right now, to minimize the impact of strings being truncated, you can click on the value to copy it. Does it solve something for you? Also, would you have any suggestions on how we could do it better?

**Comment by bartonip** [comment]
@BrunoQuaresma Yep click to copy seems to work fine as a workaround
