### ISSUE TITLE
Allow changing db schema from `public`

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#4747]
# Problem

When creating our initial migration to bootstrap the database, we hard-code the schema name to public.

# Solution

Do not set the schema name at all in the initial bootstrap script.
Allow this to be overridden via search_path in the connection string.

https://www.postgresql.org/docs/current/runtime-config-client.html

## Private Link

V1 PR: https://github.com/coder/v1/pull/13216
v1 Issue: https://github.com/coder/v1/issues/13040

**Comment by mtojek** [comment]
I will take this one as my first issue. I will keep you posted!
