### ISSUE TITLE
Example in cli help for proxy-trusted-origins should be an ip

### ISSUE THREAD

**Issue by ntimo** [coder/coder#4752]
The example for the flag `--proxy-trusted-origins` mentions that you can set `example.com` as an accepted value. This will not work and coder won't start since only ip ranges are supported. Therefore the example needs to be fixed :)

Current command help description:
```
      --proxy-trusted-origins strings              Origin addresses to respect
                                                   "proxy-trusted-headers". e.g. example.com
                                                   Consumes
                                                   $CODER_PROXY_TRUSTED_ORIGINS
```

Ideal command help description:
```
      --proxy-trusted-origins strings              Origin addresses to respect
                                                   "proxy-trusted-headers". e.g. 192.168.178.0/24
                                                   Consumes
                                                   $CODER_PROXY_TRUSTED_ORIGINS
```

**Comment by ghuntley** [comment]
Nicely spotted!

https://sourcegraph.com/github.com/coder/coder@c9a311331a8e6ae3cbc8e97b4062575851a8986e/-/blob/cli/server.go?L335

<img width="940" alt="CleanShot 2022-11-04 at 12 34 57@2x" src="https://user-images.githubusercontent.com/127353/199872889-d1655f7e-21cd-4252-b35a-514d400e9943.png">
