### ISSUE TITLE
audit: Display full timestamp somewhere

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4768]
If I'm trying to debug a failed build or something, I may want to know the exact time something happened in order to check server logs, Datadog, etc. 

Right now, it just shows "1 month ago," etc.

**Comment by Kira-Pilot** [comment]
![Screen Shot 2023-01-20 at 3 26 49 PM](https://user-images.githubusercontent.com/19142439/213799266-4805f39f-a45f-4206-a1ef-953ad54fc471.png)
Resolved with the timestamp.
