### ISSUE TITLE
audit: template update entries require horizontal scrolling for viewing

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#4773]
long URL strings in the template icon field leads to the audit log not showing the status code, IP address, etc. requires horizontal scrolling.

<img width="1162" alt="Screen Shot 2022-10-26 at 2 15 08 PM" src="https://user-images.githubusercontent.com/9683576/198106376-6b223e00-8880-4f9c-a289-7e026f629e92.png">

<img width="1147" alt="Screen Shot 2022-10-26 at 2 27 37 PM" src="https://user-images.githubusercontent.com/9683576/198106737-0ae3681a-51d7-4641-a706-3b3a600fa801.png">

**Comment by BrunoQuaresma** [comment]
@ericpaulsen is this on dev.coder.com?

**Comment by ericpaulsen** [comment]
this was on my personal deployment. 0.11.0.
