### ISSUE TITLE
Auto set VSCODE_PROXY_URI in workspaces to use code-server ports

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4776]
- [x] ~~Will setting this environment variable workspace-wide interfere with VS Code Remote SSH?~~

@jsjoeio added support for port forwarding in code-server: coder/code-server#5673

And we just added this to our dogfood template: #4775, but we don't want template authors to have to set code-server environment variables to make use of this feature.

**Comment by bpmct** [comment]
Did a basic test and it looks like this doesn't override VS Code Remote's ports 🎉

**Comment by jsjoeio** [comment]
Hooray! Thanks for doing that!
