### ISSUE TITLE
pagination: use estimated count

### ISSUE THREAD

**Issue by presleyp** [coder/coder#4779]
Currently, pages have an endpoint for fetching paginated data, and a separate endpoint for fetching the full count of filtered data, to be used to show how many pages are possible. The count query is expensive, so making it separate allows us to call it less often. However, we'd like to have one endpoint to simplify the API (and possibly avoid duplicated SQL queries). Returning an estimated count would improve performance, so try having one endpoint with the paginated data and an estimated count, and see if its performance and UX are good enough.

**Comment by presleyp** [comment]
I think this will often work well but my concern is that if the estimate is an underestimate, the pagination widget will not allow you to go to a higher page, so you won't discover the extra records. 

I also want to note that the performance of the count endpoint doesn't have to be a blocker. We can let the page and pagination controls load before the count is available, and whenever the count does become available, the pagination controls just become more informative (you get page numbers instead of just arrows, and the Next arrow can become disabled when you're on the last page).

**Comment by f0ssel** [comment]
@kylecarbs gave me the feedback here that was aligned with my original suggestion on this issue when we spoke about this design. Both him and I believe this duplicate query and endpoint seem like premature optimizations and that we are probably fine just running the query twice on the primary route - one with and one without the limit and use the unlimited count in the response with the workspaces. The idea here is that maintainability is more important to the app than performance concerns in the short term and if we don't have any data telling us it will be an issue we shouldn't really design around it. 

I'd be happy to make this change if there's no objections to moving in this direction.

**Comment by bpmct** [comment]
@presleyp is implementing this in current PRs
