### ISSUE TITLE
High CPU usage when viewing workspace in Web UI (confirmed on Safari)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#4788]
Coder: v0.11.0

I noticed Safari was consuming a lot of battery, which I managed to attribute to a single Coder tab viewing a running workspace:

<img width="986" alt="Screenshot 2022-10-27 at 18 01 08" src="https://user-images.githubusercontent.com/147409/198327688-ed11c63e-86f4-4ac7-88c4-4f2594f15f95.png">

This is not uncommon CPU usage for a webpage when it happens momentarily, but a constant usage of 8-12% is not great.

I noticed that `/api/v2/csp/reports` is constantly being fetched, perhaps this could be a cause?

I noticed other pages also have a relatively high baseline CPU usage of 2-4%, typically sites (especially ones in the background/inactive tabs) idle at (or near) 0%, with maybe a few momentary spikes to ~10% here and there.)

**Comment by bpmct** [comment]
@BrunoQuaresma I think this was fixed when we changed the refresh behavior?

**Comment by BrunoQuaresma** [comment]
Yes, it was!
