### ISSUE TITLE
coder-app in Terraform

### ISSUE THREAD

**Issue by cur1ou5soul** [coder/coder#4791]
I try to establish a connection to my local novnc app into a terrafrom template, sadly it’s not working. 

If i access the app via port-forwarding everything works. But via app connection nothing works/. Here is my config:

`# code-server
resource "coder_app" "code-server" {
  agent_id  = coder_agent.dev.id
  name      = "code-server"
  icon      = "/icon/code.svg"
  url       = "http://localhost:13337?folder=/home/${data.coder_workspace.me.owner}"
  subdomain = false
}

resource "coder_app" "novnc" {
  agent_id      = coder_agent.dev.id
  name          = "noVNC Desktop"
  icon          = "https://ppswi.us/noVNC/app/images/icons/novnc-192x192.png"
  url           = "http://localhost:6081/vnc.html"
  subdomain = false
} `

Funny part is the code-server is working. I also tried to use the bare url (localhost:6081).

**Comment by bartonip** [comment]
@cur1ou5soul Can you try with no space and all lowercase in the name field?

**Comment by cur1ou5soul** [comment]
I did, actually i got it working without the path (vnc.html) I made an ln -s from vnc.html to index.html. Now It works. Also I turned subdomain=true.

**Comment by kylecarbs** [comment]
I'm happy you were able to get it working!
