### ISSUE TITLE
audit: allow filtering by workspace build start/stop

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#4796]
In #4625, we added the ability to audit on workspace build stop/start. Currently, we have no filters for this addition - you cannot query by workspace_build.

We should add this ability so users can see just stopped workspace builds or just started workspace builds.

As part of this effort, an example should be added to the dropdown so that users know how to filter, as well as to the audit log docs.

**Comment by bpmct** [comment]
Would be awesome to include an example in the dropdown too :)
