### ISSUE TITLE
Response header content-type changed to text/html

### ISSUE THREAD

**Issue by mayzyo** [coder/coder#4805]
I'm trying to run [Hoppscotch](https://github.com/hoppscotch/hoppscotch), the popular API client in my hosted instance of coder. When opening the editor, it throws errors seeming to indicate the MIME type returned is incorrect:
![image](https://user-images.githubusercontent.com/25147960/198856217-cd1abc41-ca5f-4334-abee-6e3a0b1e4a9c.png)

However, running curl inside the container for the same file returned with the correct content-type. I'm unsure what is going on here.

The network is reporting code 200 for all of them:
<img width="272" alt="Screenshot 2022-10-30 092832" src="https://user-images.githubusercontent.com/25147960/198856240-33376292-a5b4-4d0b-b6de-0f373f2d3992.png">

I've been running code-server, jupyter-notebook and a few others all without issue. I've also tried connecting to the container locally without passing any reverse proxies and it still gives the same error. Hoppscotch is served through a simple [http-server](https://github.com/http-party/http-server)

Please help me out if anyone understand what's going on here thanks

**Comment by drumslave-git** [comment]
I have exactly same issue. Kinda complex setup. Webpack dev server, proxied via coder, which is proxied via cloudflare tunnels
