### ISSUE TITLE
docs: multiple git authentication

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4806]
Version: [`v0.11.0+df89e2c`](https://github.com/coder/coder/commit/df89e2c3b01e3b5838d72f6a8659a116d44712a6)

[The 0.11.0 release mentions git authentication](https://github.com/coder/coder/releases#:~:text=feat%3A%20Add%20Git%20auth%20for%20GitHub%2C%20GitLab%2C%20Azure%20DevOps%2C%20and%20BitBucket) but I do not see this [in the docs](https://coder.com/docs/coder-oss/latest/enterprise#:~:text=Multiple%20Git%20Provider%20Authentication). 

When will this be documented so I can try it?

**Comment by bpmct** [comment]
We have it documented here: https://coder.com/docs/coder-oss/latest/admin/git-providers
