### ISSUE TITLE
Stopping a workspace failed

### ISSUE THREAD

**Issue by matifali** [coder/coder#4808]
Sometimes stopping a workspace manually from WebUI fails with this error.
```console
Initializing the backend...
Initializing provider plugins...
- Finding coder/coder versions matching "0.5.3"...
- Finding kreuzwerker/docker versions matching "2.22.0"...
- Using coder/coder v0.5.3 from the shared cache directory
- Using kreuzwerker/docker v2.22.0 from the shared cache directory
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Warning: Incomplete lock file information for providers
Due to your customized provider installation methods, Terraform was forced to
calculate lock file checksums locally for the following providers:
 - coder/coder
 - kreuzwerker/docker
The current .terraform.lock.hcl file only includes checksums for linux_amd64,
so Terraform running on another platform will fail to install these
providers.
To calculate additional checksums for another platform, run:
 terraform providers lock -platform=linux_amd64
(where linux_amd64 is the platform to generate)
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraform 1.3.0
data.coder_workspace.me: Refreshing...
data.coder_workspace.me: Refresh complete after 0s [id=4854d142-ddb2-43a9-b6c3-cb7dc0b6647b]
docker_volume.home_volume: Refreshing state... [id=coder-atif-aihwkit-home]
coder_agent.dev: Refreshing state... [id=9c69ca42-9967-4895-9ee1-f50563202d61]
docker_image.aihwkit: Refreshing state... [id=sha256:bd42d56b191e3fe2d7bb22bcc44a87020243b9bfaf39c8aa22cf8bd2a8f7f7dcatif-aihwkit]
coder_agent.dev: Refresh complete [id=9c69ca42-9967-4895-9ee1-f50563202d61]
docker_volume.home_volume: Refresh complete [id=coder-atif-aihwkit-home]
coder_app.jupyter: Refreshing state... [id=6e0e6ad4-ceb6-4a9c-8f4d-e7a9b7b597e2]
coder_app.jupyter: Refresh complete [id=6e0e6ad4-ceb6-4a9c-8f4d-e7a9b7b597e2]
docker_image.aihwkit: Refresh complete [id=sha256:bd42d56b191e3fe2d7bb22bcc44a87020243b9bfaf39c8aa22cf8bd2a8f7f7dcatif-aihwkit]
docker_container.workspace[0]: Refreshing state... [id=0e8d48f93b922f2fbd2fac7ce676d2bd363f2df1370923533d35de0293f1dd31]
docker_container.workspace[0]: Refresh complete
coder_agent.dev: Drift detected (update)
docker_container.workspace[0]: Drift detected (delete)
Plan: 0 to add, 0 to change, 0 to destroy.
Error: Provider produced inconsistent final plan
When expanding the plan for docker_container.workspace[0] to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker" changed the planned action from NoOp to Create. This is a bug in the provider, which should be reported in the provider's own issue tracker.
Error: Provider produced inconsistent final plan
When expanding the plan for docker_container.workspace[0] to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker" produced an invalid new value for Root resource was absent, but now present. This is a bug in the provider, which should be reported in the provider's own issue tracker.
Cleaning Up


```

**Comment by kylecarbs** [comment]
This looks like a problem with the `docker` Terraform Provider!

@matifali could you report it there?

**Comment by matifali** [comment]
> Sometimes stopping a workspace manually from WebUI fails with this error.
> 
> ```
> Initializing the backend...
> Initializing provider plugins...
> - Finding coder/coder versions matching "0.5.3"...
> - Finding kreuzwerker/docker versions matching "2.22.0"...
> - Using coder/coder v0.5.3 from the shared cache directory
> - Using kreuzwerker/docker v2.22.0 from the shared cache directory
> Terraform has created a lock file .terraform.lock.hcl to record the provider
> selections it made above. Include this file in your version control repository
> so that Terraform can guarantee to make the same selections by default when
> you run "terraform init" in the future.
> Warning: Incomplete lock file information for providers
> Due to your customized provider installation methods, Terraform was forced to
> calculate lock file checksums locally for the following providers:
>  - coder/coder
>  - kreuzwerker/docker
> The current .terraform.lock.hcl file only includes checksums for linux_amd64,
> so Terraform running on another platform will fail to install these
> providers.
> To calculate additional checksums for another platform, run:
>  terraform providers lock -platform=linux_amd64
> (where linux_amd64 is the platform to generate)
> Terraform has been successfully initialized!
> You may now begin working with Terraform. Try running "terraform plan" to see
> any changes that are required for your infrastructure. All Terraform commands
> should now work.
> If you ever set or change modules or backend configuration for Terraform,
> rerun this command to reinitialize your working directory. If you forget, other
> commands will detect it and remind you to do so if necessary.
> Terraform 1.3.0
> data.coder_workspace.me: Refreshing...
> data.coder_workspace.me: Refresh complete after 0s [id=4854d142-ddb2-43a9-b6c3-cb7dc0b6647b]
> docker_volume.home_volume: Refreshing state... [id=coder-atif-aihwkit-home]
> coder_agent.dev: Refreshing state... [id=9c69ca42-9967-4895-9ee1-f50563202d61]
> docker_image.aihwkit: Refreshing state... [id=sha256:bd42d56b191e3fe2d7bb22bcc44a87020243b9bfaf39c8aa22cf8bd2a8f7f7dcatif-aihwkit]
> coder_agent.dev: Refresh complete [id=9c69ca42-9967-4895-9ee1-f50563202d61]
> docker_volume.home_volume: Refresh complete [id=coder-atif-aihwkit-home]
> coder_app.jupyter: Refreshing state... [id=6e0e6ad4-ceb6-4a9c-8f4d-e7a9b7b597e2]
> coder_app.jupyter: Refresh complete [id=6e0e6ad4-ceb6-4a9c-8f4d-e7a9b7b597e2]
> docker_image.aihwkit: Refresh complete [id=sha256:bd42d56b191e3fe2d7bb22bcc44a87020243b9bfaf39c8aa22cf8bd2a8f7f7dcatif-aihwkit]
> docker_container.workspace[0]: Refreshing state... [id=0e8d48f93b922f2fbd2fac7ce676d2bd363f2df1370923533d35de0293f1dd31]
> docker_container.workspace[0]: Refresh complete
> coder_agent.dev: Drift detected (update)
> docker_container.workspace[0]: Drift detected (delete)
> Plan: 0 to add, 0 to change, 0 to destroy.
> Error: Provider produced inconsistent final plan
> When expanding the plan for docker_container.workspace[0] to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker" changed the planned action from NoOp to Create. This is a bug in the provider, which should be reported in the provider's own issue tracker.
> Error: Provider produced inconsistent final plan
> When expanding the plan for docker_container.workspace[0] to include new values learned so far during apply, provider "registry.terraform.io/kreuzwerker/docker" produced an invalid new value for Root resource was absent, but now present. This is a bug in the provider, which should be reported in the provider's own issue tracker.
> Cleaning Up
> ```

Ok. but I do not know how I can separate the logs or coder from the docker provider logs. Or should I submit this log as is?

**Comment by matifali** [comment]
> This looks like a problem with the `docker` Terraform Provider!
> 
> @matifali could you report it there?

Ok. but I do not know how I can separate the logs or coder from the docker provider logs. Or should I submit this log as is?

**Comment by matifali** [comment]
Did not face this for a long time. closing
