### ISSUE TITLE
Purpose of the auto stop limit?

### ISSUE THREAD

**Issue by klauserber** [coder/coder#4849]
Hallo,

I think I have misunderstood the purpose if this setting in a template.

New Workspaces have no schedule by default and they run forever even if I have set an auto stop limit in the template. I'm looking for functionality to configure a limit even if the user have configured no schedule. I thought that this setting is the solution, but it only limits the Field for auto stop field in the schedule form, right? Or is it a bug?

The description of the field 'Workspaces created from this template may not remain running longer than 5 hours.' is a little bit misleading.

**Comment by ammario** [comment]
Related: #3630 

Yes, this is a bug, and decimates the usefulness of the feature.

cc @presleyp who was doing some work in scheduling recently...

**Comment by klauserber** [comment]
Very nice! Works great! :-)
