### ISSUE TITLE
cli and server version mismatch

### ISSUE THREAD

**Issue by granty1** [coder/coder#4851]
```
[root@150_4 coder-template]# coder template push docker-image-builds
version mismatch: client v0.11.0+df89e2c, server v0.12.0+cf794f1
download the server version with: 'curl -L https://coder.com/install.sh | sh -s -- --version 0.12.0'

Resource not found or you do not have access to this resource.
Run 'coder templates push --help' for usage.
```
I started the coderd through docker compose, However, the coder cli has only release version 0.11. When pushing the template, tell me how to start the server with version 0.11 if the version does not match

**Comment by matifali** [comment]
reinstall coder on the server using `curl -L https://coder.com/install.sh | sh` It should install version 0.11.0 as version 0.12.0 has been withdrawn.

**Comment by granty1** [comment]
> reinstall coder on the server using `curl -L https://coder.com/install.sh | sh` It should install version 0.11.0 as version 0.12.0 has been withdrawn.

```
[root@150_4 coder-template]# coder template push docker-image-builds
Resource not found or you do not have access to this resource.
Run 'coder templates push --help' for usage.
```
But why do I always fail to try push template ?

**Comment by matifali** [comment]
> > reinstall coder on the server using `curl -L https://coder.com/install.sh | sh` It should install version 0.11.0 as version 0.12.0 has been withdrawn.
> 
> ```
> [root@150_4 coder-template]# coder template push docker-image-builds
> Resource not found or you do not have access to this resource.
> Run 'coder templates push --help' for usage.
> ```
> 
> But why do I always fail to try push template ?

YOu need to be in the directory that contains a `main.tf` file
Can you show output of `ls` here?

**Comment by granty1** [comment]
> > > reinstall coder on the server using `curl -L https://coder.com/install.sh | sh` It should install version 0.11.0 as version 0.12.0 has been withdrawn.
> > 
> > 
> > ```
> > [root@150_4 coder-template]# coder template push docker-image-builds
> > Resource not found or you do not have access to this resource.
> > Run 'coder templates push --help' for usage.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But why do I always fail to try push template ?
> 
> YOu need to be in the directory that contains a `main.tf` file Can you show output of `ls` here?

```

[root@150_4 coder-template]# ll docker-image-builds/
total 12
drwxr-xr-x. 2 root root  100 Nov  2 11:17 images
-rwxrwxrwx. 1 root root 3207 Nov  2 11:19 main.tf
-rw-r--r--. 1 root root 4213 Nov  2 11:14 README.md
```

**Comment by matifali** [comment]
make sure you are in `docker-image-builds` and then
```console
coder templates create YOUR_TEMPLATE_NAME
coder templates push YOUR_TEMPLATE_NAME
```
you need to create a template first before you can push updates. `create` is for the first time and then to update use `push`

**Comment by granty1** [comment]
> 

```
[root@150_4 docker-image-builds]# coder templates create xxx-template
> Create and upload "/data/grant/coder-template/docker-image-builds"? (yes/no) yes
✔ Queued [100ms]
✔ Setting up [82ms]
✔ Adding README.md... [89ms]
✔ Parsing template parameters [163ms]
⧗  Detecting persistent resources

  Error: Failed to query available provider packages

  Could not retrieve the list of available versions for provider coder/coder:
  could not connect to registry.terraform.io: Failed to request discovery
  document: Get "https://registry.terraform.io/.well-known/terraform.json":
  net/http: request canceled while waiting for connection (Client.Timeout
  exceeded while awaiting headers)


  Error: Failed to query available provider packages

  Could not retrieve the list of available versions for provider
  kreuzwerker/docker: could not connect to registry.terraform.io: Failed to
  request discovery document: Get
  "https://registry.terraform.io/.well-known/terraform.json": net/http: request
  canceled while waiting for connection (Client.Timeout exceeded while awaiting
  headers)

✔ Detecting persistent resources [23666ms]
✘ Cleaning Up [178ms]
template import provision for start: recv import provision: initialize terraform: exit status 1
Run 'coder templates create --help' for usage.

```
