### ISSUE TITLE
SSH, speedtest & port forwarding time out

### ISSUE THREAD

**Issue by cybertelx** [coder/coder#4852]
![image](https://user-images.githubusercontent.com/22412526/199457809-43eda75f-e17a-4569-bda4-b25c443834d4.png)
![image](https://user-images.githubusercontent.com/22412526/199462222-1978cf52-674c-4241-9c59-59fb0eee3930.png)

### ufw rules
![image](https://user-images.githubusercontent.com/22412526/199464149-3b42a701-2413-4390-8660-45ad356b408d.png)

**coder version:** v0.11.0+df89e2c
**linux distro running on client:** fedora workstation 36
**linux distro running on server:** ubuntu 22.04.1 lts
**vpn** (could be related, but i turned it off and same issue happened): mullvad vpn - local network sharing is enabled

code-server in the browser works fine though, and i can ssh into & speedtest my workspace on the server

## what i tried (no effect)
- restarting workspace
- restarting docker & coder on server
- rebooting server
- disabling firewall
- rebooting client
- disabling vpn
- trying a different workspace
- logging out and logging back into coder on client

**Comment by matifali** [comment]
Juts a double check. Did you run `coder config-ssh`?

**Comment by cybertelx** [comment]
bump

**Comment by matifali** [comment]
> bump - a thing that might be causing this issue is me proxying the coder server through cloudflare tunnels

I would suggest you disable proxying through Cloudflare. (That is usually for static websites)

**Comment by cybertelx** [comment]
will do, currently setting up caddy

**Comment by cybertelx** [comment]
it works, thank you

note for future people: don't use Cloudflare Tunnels

**Comment by matifali** [comment]
> it works, thank you
> 
> note for future people: don't use Cloudflare Tunnels

I also use Cloudflare but the settings are DNS only.
