### ISSUE TITLE
Add Gravatar support for user avatars

### ISSUE THREAD

**Issue by kconley-sq** [coder/coder#4860]
Our OIDC provider unfortunately does not provide a picture for each user. 😞 What would y'all think about integrating [Gravatar](https://en.gravatar.com/site/implement) as a fallback for user avatars if one is not provided by the user authentication provider?

**Comment by kylecarbs** [comment]
Good idea! This would be really simple for us to do.

**Comment by BrunoQuaresma** [comment]
@kylecarbs should this be default or a config?

**Comment by ghuntley** [comment]
> @kylecarbs should this be default or a config?

💭 my thoughts -> enable by default?
🤔 considerations -> in airgapped install would people want coder doing external network requests (thus add configuration option to disable?)

**Comment by BrunoQuaresma** [comment]
@ghuntley good considerations. We probably want to have an option to disable that for sure.
