### ISSUE TITLE
Coder CLI is not in the `$PATH` on Windows workspaces

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#4870]
After provisioning a windows workspace using our templates the `coder` binary is not installed.

<img width="1033" alt="CleanShot 2022-11-03 at 14 32 47@2x" src="https://user-images.githubusercontent.com/127353/199648111-94c78c53-1f86-47b8-9093-86063ddcecca.png">

Whereas when provisioning a linux and macos workspace using our templates the `coder` binary is installed.

<img width="1162" alt="CleanShot 2022-11-03 at 14 33 55@2x" src="https://user-images.githubusercontent.com/127353/199648208-5e6994f2-0881-40a6-84b5-4518274f9c14.png">

<img width="900" alt="CleanShot 2022-11-03 at 14 40 19@2x" src="https://user-images.githubusercontent.com/127353/199648890-e708c232-af73-4254-a49a-e0711ab87bd1.png">

**question:** seeking confirmation that the `coder` CLI should be installed by default and on the path (ie via fetching /bin)

<img width="579" alt="CleanShot 2022-11-03 at 14 35 19@2x" src="https://user-images.githubusercontent.com/127353/199648325-8526f917-4074-459c-9a22-ae93a762925d.png">

ps. Here is my template -> https://gist.github.com/ghuntley/1ca092e4433175a596b387a7b5e4b613

**Comment by deansheather** [comment]
The coder CLI is installed since it functions as the workspace agent, but it looks like it's not added to the PATH correctly. Adding directories to PATH in Windows sucks big time, so I expect this to not work in terminals made by the RDP session, but it should at least work over SSH or in the web terminal since we control the environment for those.

**Comment by f0ssel** [comment]
Could we not put the coder binary somewhere that is most commonly included in the Windows PATH?

**Comment by tristanbrown** [comment]
I'm also having this issue with the PATH.

**Comment by kylecarbs** [comment]
I believe this is fixed.
