### ISSUE TITLE
Audit: add date to timestamp

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#4875]
![Screen Shot 2022-11-03 at 10 22 56 AM](https://user-images.githubusercontent.com/19142439/199746391-04199196-4c17-4827-b0ef-0ac7bcae1ce2.png)

We have timestamps on each of the audit log entries, as well as a date header at the top of a day's collection. However, there may be so many logs for a day that one would not see the date header and would have to paginate left or right to understand what day they were looking at. We should adjust the design so that each entry clearly shows the date as well as the timestamp.

**Comment by sharkymark** [comment]
I like this idea. Given granular dates versus days of the week is good.

**Comment by BrunoQuaresma** [comment]
If you have two pages for "today" the "Today" label stills shows up. Follow up -> https://codercom.slack.com/archives/C01A9SEKFEE/p1667830551139519
