### ISSUE TITLE
Custom sorting for workspaces

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4885]
Version: [`v0.12.2+6bfdccd`](https://github.com/coder/coder/commit/6bfdccda2f3e9b61b415d27b15b657c81a283c3c)

First, I assume the workspace list UI sorts by last used, but nothing designates this in the UI, like a tick over the column. That is a poor experience.

Second, more sorting options like alphabetical by name, would be helpful.

Right now, I have to control-F lol

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/2022166/199842902-20b6cc26-a4f3-440a-ac52-946af3704540.png">

**Comment by Emyrk** [comment]
@sharkymark we should have sorting options, but ctl+f is not needed. You can partial match names with `name:<something>`.

So `owner:me name:gcloud` for example to find that one you have highlighted.

**Comment by sharkymark** [comment]
@bpmct @kylecarbs I think we should do this one. No sorting, especially for owner roles, is tough.

**Comment by kylecarbs** [comment]
Hmm, how do you think we should sort? I kinda like the ordered by last accessed, but I agree it can be a bit jarring.

**Comment by bpmct** [comment]
I think sorting by last used is a good default. Being able to change the sort by clicking on the column names (e.g. `name` to sort alphabetically) would be nice. That was how I interpreted this issue

**Comment by bpmct** [comment]
If we cache the user' sorting preferences in the browser, I think it's a win-win.

**Comment by kylecarbs** [comment]
This is a pretty big thing for us to do, so unless customers are asking for it, I think we close it. Thoughts @bpmct?

**Comment by bpmct** [comment]
Sorry Mark.
