### ISSUE TITLE
Open browser window from Terminal session 

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#4889]
# overview

When using using Coder through a Terminal session applications that typically open a browser window do not open a browser window.

<img width="1405" alt="CleanShot 2022-11-04 at 12 06 35@2x" src="https://user-images.githubusercontent.com/127353/199869664-75fe20fb-c796-4c11-8313-ddfccfb6d3f5.png">

# question / request

Can we xdg-open a new web browser window? Assuming `BROWSER` and `xdg-open` CLI primitives are installed/configured.

**Comment by phorcys420** [comment]
I was thinking of that too, maybe it would be possible to create a ``coder://`` URI handler ?
