### ISSUE TITLE
Configurable duration for API tokens

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4910]
Version: [`v0.12.2+6bfdccd`](https://github.com/coder/coder/commit/6bfdccda2f3e9b61b415d27b15b657c81a283c3c)

Let's hope this is a CLI bug and the token isn't really going to expire in a century.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/2022166/200120279-9cc03296-a6b5-4c9e-b505-b1daa65df2fa.png">

**Comment by f0ssel** [comment]
Tokens are meant to be used for CI, etc. Instead of adding a field for an infinite expiration I just opted for an effectively unlimited lifecycle. 

What were your expectations using this feature and what the behavior would be? I'd like to get feedback on it so we can make improvements.

**Comment by sharkymark** [comment]
@f0ssel I remember Goldman Sachs wants to control key expirations, which made me think they are onto a best practice. 

v1, the default was 1 year right?

I propose creating an expiration parameter like v1, since Goldman will complain when they try v2.

**Comment by bpmct** [comment]
@f0ssel We've had customers ask about creating a configurable duration for tokens. I suggest we do the following:

- Default tokens to expire after 30 days (GitLab and GitHub have this behavior)
- Add a configurable duration flag so that long-lived tokens can be created for CI

**Comment by f0ssel** [comment]
I agree with all that. I can pick up this work and we can look at adding to the dashboard once we get these changes in.
