### ISSUE TITLE
Bug: "coder gitssh" not functional on 0.12.2

### ISSUE THREAD

**Issue by ssmiller25** [coder/coder#4913]
Recently upgrade our coder instance to 0.12.2.  Coder itself is hosted in Kubernetes, and we deploy AWS EC2 development enviornments.  WIth the upgrade to 0.12.2, and newly created or updated environments can no longer pull/push into Github repositories.  Error messages below

```text
coder@dev-new-1006:~$ git clone git@github.com:ssmiller25/r15cookieblog.git
Cloning into 'r15cookieblog'...
Cookie "coder_session_token" must be provided. Try logging in using 'coder login <url>'.
Run 'coder gitssh --help' for usage.                                                    
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

This seems to be directly from the GIT_SSH_COMMAND environment variable that ties in coder's backend to the GIT SSH authentication:

```text
coder@dev-new-1006:~$ echo $GIT_SSH_COMMAND
/tmp/coder.UMQn1G/coder gitssh --
coder@dev-new-1006:~$ /tmp/coder.UMQn1G/coder gitssh
Cookie "coder_session_token" must be provided. Try logging in using 'coder login <url>'.
Run 'coder gitssh --help' for usage.
```

I ran `coder login <mycoderinstace>` successfully, but did not make a difference.  

Older environments that were created on the 0.9.1 server, and still have the 0.9.1 agent, continue to work.  If any of those environments are updated to the latest agent, they stop working with the symptoms above.

Is there anything I need to look at?  I did update the template to the latest Terraform provider.

**Comment by kylecarbs** [comment]
Doing a release now with the fix!

This was resolved with https://github.com/coder/coder/pull/4884, but we forgot to do a release.

**Comment by kylecarbs** [comment]
v0.12.3 is coming out now! ~15mins

**Comment by ssmiller25** [comment]
@kylecarbs Awesome!!!  Didn't expect a response over the weekend!  Our devs will be quite happy Monday :-)

**Comment by kylecarbs** [comment]
@ssmiller25 no problem at all! It's been released and should work! Let me know if you have any problems.

**Comment by ssmiller25** [comment]
@kylecarbs No luck on 0.12.3 :-(

```text
coder@dev-1106-1227:~$ coder version
Coder v0.12.3+267b81a Sun Nov  6 16:22:01 UTC 2022
https://github.com/coder/coder/commit/267b81af8320be9309382e1d8560b52f6e5c5de2
coder@dev-1106-1227:~$ git clone git@github.com:ssmiller25/r15cookieblog.git
Cloning into 'r15cookieblog'...
Cookie "coder_session_token" must be provided. Try logging in using 'coder login <url>'.
Run 'coder gitssh --help' for usage.                                                    
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Anything else I should look at?
