### ISSUE TITLE
bug: a workspace with no build logs in the past 30 days causes the dashboard to spin when loading

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4916]
Version: [`v0.12.2-devel+267b81af`](https://github.com/coder/coder/commit/267b81af8320be9309382e1d8560b52f6e5c5de2)

![image](https://user-images.githubusercontent.com/2022166/200185844-e23686ce-3bba-494b-9fc8-8ec8ff87fc6e.png)

**Comment by BrunoQuaresma** [comment]
Not sure how we can reproduce that 🤔
