### ISSUE TITLE
Bug: "coder gitssh" not functional on 0.12.3

### ISSUE THREAD

**Issue by ssmiller25** [coder/coder#4921]
Related to #4913  Upgraded to 0.12.3, created new EC2 Development environment, and still had the same issue.  From the developer environment:

```text
coder@dev-1106-1227:~$ coder version
Coder v0.12.3+267b81a Sun Nov  6 16:22:01 UTC 2022
https://github.com/coder/coder/commit/267b81af8320be9309382e1d8560b52f6e5c5de2
coder@dev-1106-1227:~$ git clone git@github.com:ssmiller25/r15cookieblog.git
Cloning into 'r15cookieblog'...
Cookie "coder_session_token" must be provided. Try logging in using 'coder login <url>'.
Run 'coder gitssh --help' for usage.                                                    
fatal: Could not read from remote repository.


Please make sure you have the correct access rights
and the repository exists.
```

Anything else I should look at? There was no issues with the 0.12.3 upgrade that I observed.

If it makes a difference, I am using Github OAuth for authentication.

**Comment by kylecarbs** [comment]
Humph, something odd is happening here... I suppose my test didn't fix it. Looking now.

**Comment by kylecarbs** [comment]
@ssmiller25 I did indeed make a mistake :facepalm: 

https://github.com/coder/coder/blob/5be6c7071ea5697e4de00cae1bf2e3566427ebd6/cli/agent.go#L167-L168

Adding a test for this path now so it can never happen again!

**Comment by ssmiller25** [comment]
No worries!  Glad it was something you found quickly.  And makes me really want to brush up on my Go skills :-)

**Comment by kylecarbs** [comment]
@ssmiller25 feel free to review to brush up the Go skills!

https://github.com/coder/coder/pull/4923

I appreciate you opening issues and being prompt with responses. I'll release 0.12.4, which I'm fully confident fixes this issue.

**Comment by kylecarbs** [comment]
@ssmiller25 0.12.4 is going up now! ~15mins

**Comment by ssmiller25** [comment]
Worked perfectly.  Thanks!
