### ISSUE TITLE
Trying to use Keycloak oauth2

### ISSUE THREAD

**Issue by r65535** [coder/coder#4925]
I'm trying to deploy coder-oss with keycloak's oauth2 client.

When using the SSO link in coder, I get this error:
```
{"message":"Cookie \"oauth_state\" must be provided."}
```
I've followed the oauth2 [guide](https://coder.com/docs/coder-oss/latest/admin/auth#step-1-configure-the-oauth-application-on-google-cloud), and have the following ENVs set:
```
- name: CODER_OIDC_ISSUER_URL
  value: "https://mydomain.com/keycloak/realms/master"
- name: CODER_OIDC_EMAIL_DOMAIN
  value: "mydomain.com"
- name: CODER_OIDC_CLIENT_ID
  value: "coder"
- name: CODER_OIDC_CLIENT_SECRET
  value: "CLIENT_SECRET_HERE"
- name: CODER_OIDC_SCOPES
  value: "openid,profile,email"
```

Am I doing something wrong, or does coder not support keycloak's oauth2 yet?

**Comment by bpmct** [comment]
@r65535 What version of keycloak are you using? I'm using the latest version (via Kubernetes) and was able to set things up alright.

**Comment by r65535** [comment]
I switched our keycloak backend from gitlab to cognito, which fixed the problem 🤷‍♂️
I'll close this off - thanks!
