### ISSUE TITLE
Use motd for all output in `coder ssh [--stdio]` commands 

### ISSUE THREAD

**Issue by mafredri** [coder/coder#4927]
We have multiple scenarios in which we print output during SSH commands (both `ssh coder...` and `coder ssh ...`):

- CLI/server version mismatch (currently prints to stderr even when non-tty)
- License issues (currently prints to stderr even when non-tty)
- Workspace out of date (#4926)

This is not ideal since we must not get in the way of using SSH normally. Things like:

```sh
out=$(ssh coder.workspace ls)
err=$(ssh coder.workspace ls 2>&1 1>/dev/null)
```

should work without dirtying the output.

The ideal way to do this would be to utilize [motd](https://github.com/openssh/openssh-portable/blob/25bd659cc72268f2858c5415740c442ee950049f/session.c#L784) for all SSH messaging. This would, however, mean that messages are delayed until connection is established. Which would be problematic if we want to inform the users that the cli version is mismatched and we can't establish a connection because of it.

Ultimately we may want to have both methods, reserving the non-motd output for critical messages.

At minimum, we should comb over how we are printing these messages and ensure they’re hidden in non-tty cases.

_Edit: This issue was originally created with the incorrect assumption that banner translates to motd, banner is in fact the message shown before authentication, motd is shown just before the login shell._

---

~~I think printing to stderr is a good first step, but in the future I think it would be a good idea to start using [`BannerCallback`](https://pkg.go.dev/golang.org/x/crypto/ssh#BannerCallback) instead.~~

~~At least on systems with `/etc/motd` and OpenSSH, messages don't appear in non-interactive modes like `ssh host ls`. I believe this should (automatically) be the case when using `BannerCallback` too.~~

~~But to do that, we'd also need to fix all other occurrences of printing to stdout in the `coder ssh [--stdio]` command.~~

_Originally posted by @mafredri in https://github.com/coder/coder/pull/4926#pullrequestreview-1170249191_

**Comment by bpmct** [comment]
Is `/etc/motd` used in terminals on VS Code Remote SSH? A large amount of our users connect exclusively through this.

**Comment by mafredri** [comment]
> Is `/etc/motd` used in terminals on VS Code Remote SSH? A large amount our users connect exclusively through this.

As @mtojek [found out](https://github.com/coder/coder/pull/4926#issuecomment-1305930792), this does not seem to be the case.

The best way to support this would be via VSCode extension. I think it should be fairly easy to detect that this is a Remote SSH connection to a Coder workspace (on option is to check env `CODER=true`), check workspace status and surface a notification. It could be part of #3597.

We could potentially add a new env to workspaces as well, `CODER_WORKSPACE_OUTDATED=true`. I can think of a few cool uses but mostly it's "yet another way to detect a workspace is outdated" (YAWTDAWIO?).

**Comment by mafredri** [comment]
> the ssh nag is presenting a problem for someone. they have a local command aliased to ssh into their workspace and run the same command. when he uses tab to autocomplete the parameters the result is:
```
$ ffs ls /👋 Your workspace is outdated! Update it here: …
```
> should that message be printing if its a non-interactive session? could there be flags in coder ssh to disable it to prevent

A customer is running into this issue, a non-interactive session should not dirty the output.
