### ISSUE TITLE
Bug: `parameters create --help` usage is incorrect, needs examples

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#495]
# Summary

The help command should have `--name=<name> --value=<value>` in the Usage section. It currently omits these required fields.

```bash
$ ./coder parameters create --help
Usage:
  coder parameters create <scope> [name] [flags]
```

Also we should provide examples with concrete values, as it's unclear what the second arg is. The function takes exactly 2 arguments, but `<scope>` is a single value. 

----
We need to correct the usage, and ideally provide concrete examples with Cobra's `Example: "coder parameters create arg1 arg2 --name=SomeName --value=SomeValue"` field

**Comment by f0ssel** [comment]
Closing since we no longer have the `parameter` sub command and this has been rolled into the `create` and `update` template commands.
