### ISSUE TITLE
open all `coder_app` in a new tab, not window

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4950]
Version: [`v0.12.5+165b6fb`](https://github.com/coder/coder/commit/165b6fbc6a23fd5f58ed459ea50f42e642c2f696)

Open URL button in Port Forward now opens a new tab, not a new window

This is not consistent with IDEs opening, or was this change by design? `coder_app` `subdomains` open in new windows still.

**Comment by bpmct** [comment]
This should definitely be in a tab in order to utilize full browser features (e.g. developer tools, etc). I suppose we could change the `coder_app` to open in a tab like Coder v1 (I don't like it running in a window tbh)
