### ISSUE TITLE
Add `--detacthed` flag when performing workspace operations to prevent Ctrl+C cancel

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4960]
Currently, when you press cntrl+c with coder stop, it will cancel the job. As a workaround, you can do a REST API call to stop the workspace, passing in the token as a header

**Comment by kylecarbs** [comment]
I wonder if we should change this behavior. Canceling a workspace build is a suspicious action anyways...

**Comment by bpmct** [comment]
Agreed.

**Comment by bpmct** [comment]
Hi @kittly1101. We'd gladly accept a contribution here.
