### ISSUE TITLE
support multiple OIDC email domains

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4961]
Currently, you can only define one with `coder server --oidc-email-domain`. Let's allow multiple similar to `CODER_OAUTH2_GITHUB_ALLOWED_ORGS`

**Comment by dcarrion87** [comment]
This is now a blocker for AzureAD guests wanting to get in:

> {"message":"Your email \"REDACTED@REDACTED\" is not a part of the \"REDACT.REDACTED\" domain!"}

**Comment by dcarrion87** [comment]
@bpmct @kylecarbs is this a relatively quick fix?

We've got 3 users now across tenants wanting to do this but blocked due to domain.

**Comment by dcarrion87** [comment]
Have raised a PR: https://github.com/coder/coder/pull/5210
