### ISSUE TITLE
Docker install found mkdir /home/coder/.config/coderv2: permission denied error

### ISSUE THREAD

**Issue by zhaozhiming** [coder/coder#4970]
Hi, I [run coder with docker](https://coder.com/docs/coder-oss/latest/install/docker#run-coder-with-the-built-in-database-quick) and found the error below. I use the root user to run the command. Please help. Thanks.

```
Coder v0.12.5+165b6fb - Remote development on your infrastucture
Using built-in PostgreSQL (/home/coder/.config/coderv2/postgres)
mkdir /home/coder/.config/coderv2: permission denied
Run 'coder server --help' for usage.
```

**Comment by zhaozhiming** [comment]
@ericpaulsen It works when I use a non-root user. Thanks.

**Comment by jeeftor** [comment]
I'm getting it as non root unfortunately

**Comment by jeeftor** [comment]
![image](https://user-images.githubusercontent.com/6491743/205494911-9dc4748a-2f09-4d13-8f05-f38d50e4b86e.png)

**Comment by bit-gen** [comment]
same here, should we reopen issue?

**Comment by MrPeacockNLB** [comment]
@jeeftor did you check file permission on whatever $CODER_DATA is set to? Did you ran docker with sudo before? Did you try to delete $CODER_DATA folder?

**Comment by jeeftor** [comment]
Honestly -> I punted and stood up a k8 cluster and tried it there

**Comment by bit-gen** [comment]
I ended up using docker-compose installation which is working. The other docker installation methods didn't work.

**Comment by vannaka** [comment]
I'm trying to get this to work on unRaid which only allows running using the root user. The only way I could get past the file perms issues was with @etienne-1985's solution using docker-compose.

**Comment by vannaka** [comment]
I'm trying to get this to work on unRaid which only allows running using the root user. The only way I could get past the file perms issues was with @etienne-1985's solution using docker-compose.

**Comment by AisonSu** [comment]
This is caused by the user permissions of the mounted folder. The user running in the container is named "coder" with group "coder". If the mounted folder's user and group read/write permissions do not include "coder", then the "coder" user won't have the necessary permissions to create folders.
