### ISSUE TITLE
bug: User list UI shows a page 2, but nothing is on page 2

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#4971]
Version: [`v0.12.5+165b6fb`](https://github.com/coder/coder/commit/165b6fbc6a23fd5f58ed459ea50f42e642c2f696)

![image](https://user-images.githubusercontent.com/2022166/200856464-df9ed74e-fc03-462c-9a70-f9971cebb677.png)

![image](https://user-images.githubusercontent.com/2022166/200856506-fac54d2a-7907-4a67-9668-56fea39f2ba5.png)

**Comment by ericpaulsen** [comment]
I've reproduced this.

**Comment by coadler** [comment]
Played around with this a bit and it seems not to be an issue anymore.
