### ISSUE TITLE
Auto start workspace when I connect via SSH or visit an app 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#4973]
I primarily interact with my workspace via VS Code Remote SSH by clicking my workspace in the sidebar. However, it's often off. 

I'm proposing the following behavior:

1. When I SSH into a stopped workspace (e.g. `ssh coder.ben-stable`), the workspace starts and streams the build log until it is finished. Then, the SSH connection starts. No need for the user to confirm. They clearly want to access their workspace.

    - Perhaps a configurable `coder config-ssh --disable-auto-start` flag could disable this behavior. Doesn't seem necessary though

1. When I visit a URL for an app on an agent (e.g. `https://dev.coder.com/@bpmct/ben-stable.dev/apps/code-server/?folder=/home/coder/coder`), the workspace starts and I can follow along with the build log. Once complete, and the app health check passes, I am redirected to the app. Related: #2909

    - If the user does not own the workspace, but only has access to the app, perhaps it displays some generic "Starting workspace..." text?

To validate:

- Will this work OK with VS Code Remote SSH (the primary way I connect to my workspace) or do we need #3597?

**Comment by spikecurtis** [comment]
> When I SSH into a stopped workspace (e.g. `ssh coder.ben-stable`), the workspace starts and streams the build log until it is finished. Then, the SSH connection starts. No need for the user to confirm. They clearly want to access their workspace.

It will be very challenging to achieve this flow with `ssh` (e.g. OpenSSH).  I think we already support a lot of it with `coder ssh`.

The problem with OpenSSH is that it calls `coder` as a ProxyCommand, which is supposed to make a connection to the workspace.

1. Anything we write to stdout is meant to be _the SSH protocol_, not random text like build logs.  We _could_ try writing to stderr instead; I'm not sure what OpenSSH will do with it. It might not do anything and the user is stuck with no feedback that a build is happening behind the scenes.
2. OpenSSH likely sets a connection timeout on the ProxyCommand.  If we are busy building the workspace, we are likely going to bump up against this timeout.  Combined with the above issue, it might just look like a network problem instead of it being that the workspace was switched off.

**Comment by Emyrk** [comment]
Do we necessarily always want to autostart? In v1 we had a command prompt ask if you wanted to start the workspace (only worked with `coder ssh`).

It feels a bit strange to me to assume the user always wants the workspace auto started.

**Comment by gtaylor** [comment]
I don't want to assume that this would be the case for every user, but we lean on our workspace suspension TTLs to keep things tidy and sort of efficient. The cost of starting the workspace is lower than more friction for our users, so I'd suggest that we do the most intuitive thing by giving the user what their IDE has requested. The user doesn't care about the infrastructure (starting, stopping, etc), they just want to do their dev work.

You could then add an option if there's enough user feedback to warrant the investment.

**Comment by mafredri** [comment]
@Emyrk I'm of the mind it should be a `config-ssh` option. It'd probably make sense to have it be the default (or use a deployment default) to auto-start given that if you're trying to SSH in, you're probably going to start it anyway. But admins may want to disallow this and users may not always want it happening.

**Comment by Emyrk** [comment]
@mafredri if it is some sort of "opt in", then I think we can have the coder proxy command run the start, and delay the initial ssh.

I do agree there is the problem of presenting feedback to the user that this is happening, but it sounds easier than the "prompt" problem.

**Comment by mafredri** [comment]
> @mafredri if it is some sort of "opt in", then I think we can have the coder proxy command run the start, and delay the initial ssh.

@Emyrk I'd lean towards opt-out, but essentially yes. Btw, we already delay the SSH command so everything should be in place except the autostart.

> I do agree there is the problem of presenting feedback to the user that this is happening, but it sounds easier than the "prompt" problem.

What's the problem, exactly? Yes, we can't prompt, but we can display output and already do. See the following recording:

[![asciicast](https://asciinema.org/a/pn7uBg5P7Y42LpS8dBeLLP2hi.svg)](https://asciinema.org/a/pn7uBg5P7Y42LpS8dBeLLP2hi)

**Comment by MaximeNoulin** [comment]
To give some feedbacks about our use cases, we're more interested in the auto-start when accessing an app. This would allow a friction-less experience to developers that use the online IDE. Also, this would make our review process a lot more easier.
A feature comparable to what it's already done on Github Codespaces or Gitpod would be perfect!
Thank you all for your amazing work!
Let me know if you need more info about our usecases.
