### ISSUE TITLE
OSC52 Support for coder web terminals

### ISSUE THREAD

**Issue by hh** [coder/coder#5001]
I'm not sure which web terminal is used by coder, but it would be excellent to support OSC52 (copy/paste) backhaul to populate the users local clipboard.

Decent 2017 overview:
- https://medium.com/free-code-camp/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b

Terminal IDE / Editor Application support:
- standalone: https://github.com/jirutka/tty-copy#supported-terminals
- vim: https://github.com/ojroques/nvim-osc52#nvim-osc52
- Emacs: https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/etc/osc52.el

Terminal+Muxer Support:
- tmux: https://github.com/tmux/tmux/wiki/Clipboard#the-clipboard
- mosh: https://github.com/mobile-shell/mosh/blob/03087e7a761df300c2d8cd6e072890f8e1059dfa/src/terminal/terminalfunctions.cc#L594-L600

Gnome Terminal / VTE story:
- Initial 2018 request : https://bugzilla.gnome.org/show_bug.cgi?id=795774
- 2019 migration into gitlab: https://gitlab.gnome.org/GNOME/vte/-/issues/125
- 2020 working patch: https://andrewmzhang.com/blog/2020/osc-52-patch-for-vte-0425/

Web library support:
- hterm: https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm/docs/ControlSequences.md#osc
- wezterm: https://github.com/wez/wezterm/blob/main/docs/escape-sequences.md#operating-system-command-sequences

**Comment by hh** [comment]
Looks like a PR to add support for OSC52 to xterm.js was recently opened:
https://github.com/xtermjs/xterm.js/pull/4220

Might be good to champion that work!

**Comment by ghuntley** [comment]
Opened up an open-source bounty for https://github.com/xtermjs/xterm.js/pull/4220#issuecomment-1312975802

**Comment by hh** [comment]
@kylecarbs how does the bounty system work? Can I point folks to this issue to try and push this forward?

**Comment by hh** [comment]
It's getting closer: https://github.com/xtermjs/xterm.js/pull/4220#event-9475835388

**Comment by MrPeacockNLB** [comment]
This would be realy cool if tmux selection copies text to clipboard

**Comment by hh** [comment]
Maybe test it?


https://github.com/aymanbagabas/xterm.js/commit/0a7b884a9507c8dbeb2f4cf094eed736b767ae22

The PR is not yet merged and released, but having a few testers might move it forward.
