### ISSUE TITLE
Dynamic coder_app workspace WILDCARD subdomain support for kubernetes ingress

### ISSUE THREAD

**Issue by hh** [coder/coder#5004]
For clarity, this is for dynamic listening TCP process and ingresses that occur after the workspace is provisioned.

Currently if coded is running, it looks for open ports and can suggest them via the workspace forward webui.

The name of the subdomain / wildcard is static right now for dynamic forwards in coder.

@ii has a similar feature, but default to `name of process`.WILDCARDDOMAIN.pair.sharing.io.

For example, if we run `netcat -l 8080` on one of our clusters, within moments there will be a working TLS ingress at https://nc.hh.pair.sharing.io that is publicly accessible.

If we want to specify the ingress name, we run `SHARINGIO_PAIR_EXPOSER_HOSTNAME=foo nc -l 8080` resulting in https://foo.hh.pair.sharing.io being accessible.

pair.sharing.io environment exporter and exposer:
- https://github.com/sharingio/environment#variables
- https://github.com/sharingio/environment/tree/master/cmd/environment-exporter
- https://github.com/sharingio/environment/tree/master/cmd/environment-exposer

This may be two separate ideas / features:
- `CODER_APP_HOSTNAME=foo nc -l 8080` dynamically creating `foo-WORKSPACE.WILDCARDDOMAIN` coder_app workspace forward
- Support for coderd to  look for k8s ingresses, dynamically creating `ingressname-WORKSPACE.WILDCARDDOMAIN` coder_app workspace forward

**Comment by hh** [comment]
Discussion also happening in coder.com discord [#general](https://discord.com/channels/747933592273027093/971231372373033030/1040311425253515294):
 
> What this will empower is any kubernetes cluster, including those that are in kind, vcluster, kubevirt etc that might not have actual public ingresses can piggy back on the wildcard subdomains.

**Comment by deansheather** [comment]
Does the port forwarding feature work for you? It shows a list of listening ports and the app name beside them. You can click on them and it has a unique URL using the port number (not process name)
![image](https://user-images.githubusercontent.com/11241812/201464987-e9ee56c7-f870-4e93-bc02-e72de2640caa.png)

https://coder.com/docs/coder-oss/latest/networking/port-forwarding#from-an-arbitrary-port

**Comment by hh** [comment]
Some useful code:
https://github.com/sharingio/environment/blob/fd0eaed16ccdf4f30c1cd8f44a4a47caf6cc60ce/pkg/types/types.go#L46

**Comment by deansheather** [comment]
I talked about this more with @hh today and I actually really like the idea:

1. Scan for listening ports regularly
2. Look at the environment for the listening process for well-known envs like `CODER_APP_NAME`, `CODER_APP_ICON`
3. If we see any of those envs then we will promote that listening port to be a button in the apps list instead of hidden in the port forward menu

We will have to change the frontend to get the list of listening ports when the page loads (or we will have to store them in the database).

In the future we could also let people set the app slug with `CODER_APP_SLUG`.

@bpmct

**Comment by bpmct** [comment]
huge fan of this @deansheather! What else do we need to get this moving?

**Comment by hh** [comment]
@bpmct this is getting closer, see :
- https://github.com/coder/coder/issues/6360
- https://github.com/coder/coder/pull/6489
I'll use this to iterate further once we can extend wgtunnel to support per user domains and generate wildcard DNS TLS certs for them! :)

**Comment by hh** [comment]
Ok, I think we are likely good to look at this again.
