### ISSUE TITLE
feat: make template icon a config within the main.tf

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5022]
Version: [`v0.12.5-devel+4b7c7107`](https://github.com/coder/coder/commit/4b7c710755462d9ef21fb1bdaad70d9dc681bef6)

It's a multi-step, manual effort to assign icons to a template. The URL should be able to be defined in the main.tf

If we do workspace icons some day (feature request), it should be an automatic input parameter upon workspace creation.

**Comment by sharkymark** [comment]
re-opening @kylecarbs @bpmct - we let other icons be specified in a template, the template icon should be as well. UI addition is a pain.

**Comment by kylecarbs** [comment]
It's tricky for us to do this right now, and I don't think it's a _massive_ deal.

If we were going to do this in the next 60 days I'd keep this open, but I doubt we will.
