### ISSUE TITLE
Some way to opt-in to automatically updating my template on a schedule

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#5023]
I find myself clicking on this button every day..

<img width="465" alt="CleanShot 2022-11-11 at 13 10 08@2x" src="https://user-images.githubusercontent.com/127353/201254652-92dfdcf9-ae2b-4039-86ef-323b10769ffe.png">

Which means I have to wait for the machine to be redeployed

<img width="726" alt="CleanShot 2022-11-11 at 13 09 11@2x" src="https://user-images.githubusercontent.com/127353/201254555-f3e4cf46-04bc-496c-85ae-77c6528d8ad0.png">

**Comment by sharkymark** [comment]
Auto-start is one way to handle this.

**Comment by MrPeacockNLB** [comment]
for security reasons there might be a restart to be forced. so a restart is not option. on the ohter hand users has to be informed when a restart has to be done (in terms of UX). What about workspaces without a persistent volume? What when a user uses SSH to connect to the workspace and this get suddenly restarted?

**Comment by bpmct** [comment]
Going to close this in favor of #6049 #6050
