### ISSUE TITLE
Give CODER_ACCESS_URL a sane default

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5024]
**What's the problem**

- Use the Helm chart to deploy on GKE
- Log into Coder and set up the initial org/accounts
- Try to launch a workspace, and it will fail to download the agent

The issue is that CODER_ACCESS_URL isn't set. Unfortunately, when you are installing via Helm, you don't know the IP address of the coder service until after the chart is applied. This leaves you with an awkward "deploy the stack, grab the IP address, and then redeploy the stack".

The Helm chart install is likely the first step of the game to using coder for the first time, and this is the only thing standing in the way of a flawless onboarding experience.

**My recommendation:**

If CODER_ACCESS_URL is not explicitly set, give it a default value of the coder service host. The end result should be that you can apply the Helm chart and have a working Coder stack.

**Comment by bpmct** [comment]
If unset, Coder will actually leverage the [public tunnel](https://coder.com/docs/coder-oss/latest/admin/configure#tunnel) as an access URL, which negates the purpose of the LoadBalancer which the helm chart provisions by default.

I agree we need a better sensible default and I like your recommendation. If, for some reason, we cannot default it to the LoadBalancer IP, perhaps we should disable the LoadBalancer by default (serviceType: `ClusterIP`) and change the docs to help users find their tunnel URL.

**Comment by bpmct** [comment]
Looks like this was already done by using the internal address #5041 🧠
