### ISSUE TITLE
Error: failed to solve with frontend dockerfile.v0: failed to create LLB definition

### ISSUE THREAD

**Issue by rmGFW** [coder/coder#5040]
start workspace from template docker failed
![image](https://user-images.githubusercontent.com/66858140/201468371-52020d0c-aef9-4728-aa91-79d6bf9b9666.png)

**Comment by bpmct** [comment]
Hey @rmGFW. Would you be able to create a help post in [our Discord](https://discord.gg/coder) with the template you are using? At a glance, this looks like a Terraform issue but it's hard to tell without seeing the template code.
