### ISSUE TITLE
Port forward should provide copy and paste CLI command to do a port forward

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#5046]
<img width="1467" alt="CleanShot 2022-11-14 at 12 50 38@2x" src="https://user-images.githubusercontent.com/127353/201564978-4a1b0197-5aed-423d-b83d-6dbae3e459f4.png">

Like the SSH tab

<img width="419" alt="CleanShot 2022-11-14 at 12 51 13@2x" src="https://user-images.githubusercontent.com/127353/201564987-d1f692e5-e20a-4530-a63d-4d92717fa129.png">

The bottom of the dialog should also link:

- [Install Coder CLI](https://coder.com/docs/coder-oss/latest/install)
- [SSH configuration](https://coder.com/docs/coder-oss/latest/ides#ssh-configuration)

**Comment by sharkymark** [comment]
Our list of running processes below, is nasty. Needs major work.
