### ISSUE TITLE
Display --help for a CLI verb if zero args are supplied

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#5047]
Right now if execute a verb I'm not familiar with it errors out then _asks me to do more work_

<img width="730" alt="CleanShot 2022-11-14 at 12 53 17@2x" src="https://user-images.githubusercontent.com/127353/201565245-0c58f359-cb3c-4212-9635-55ff1c014cb1.png">

If `--help` is automatically invoked when zero args are supplied into a verb we can improve the experience of our CLI.

Thoughts?

**Comment by bpmct** [comment]
I'm in favor of this, but I want to reduce our issue count + there's higher leverage stuff for us to track here.
