### ISSUE TITLE
Visibility of email addresses

### ISSUE THREAD

**Issue by klauserber** [coder/coder#5058]
Hello, we using Coder for IT workshops. In this case it is not wanted that the users can see the email addresses of each other. May be it is even against the law here in Germany (we check this at the moment).

We can work with several workaround (e. g. use generic fake addresses) but it would be very much better if we have the ability to configure the system in some way to hide this information.

Does it make sense to hide the complete Users tab for Members?

**Comment by sharkymark** [comment]
Similar to #5002 - thanks for posting.

**Comment by kylecarbs** [comment]
Closing in favor of https://github.com/coder/coder/issues/5002
