### ISSUE TITLE
bug: template settings: auto-stop option is confusing

### ISSUE THREAD

**Issue by mtojek** [coder/coder#5064]
Hi,

 while working on https://github.com/coder/coder/issues/3321, I noticed confusing behavior around the auto-stop option. Please review following screenshots:

This one looks good. The workspace would be stopped after 1 hour:

<img width="432" alt="Screenshot 2022-11-14 at 13 30 10" src="https://user-images.githubusercontent.com/14044910/201660680-36497058-33ab-461a-a92c-39594d4940f8.png">

The following one shows a confusing message about `default_ttl_ms`. User may be lost why is the form mentioning milliseconds.

<img width="434" alt="Screenshot 2022-11-14 at 13 30 02" src="https://user-images.githubusercontent.com/14044910/201660689-d9c5bf94-c3c7-4b26-a577-0d491fdab26f.png">

0 and 0 :)
<img width="443" alt="Screenshot 2022-11-14 at 13 29 55" src="https://user-images.githubusercontent.com/14044910/201660699-502b39f8-0ff9-4758-b532-f5a5d176a58b.png">

**Comment by bpmct** [comment]
related #4989
