### ISSUE TITLE
How do I create an admin account?

### ISSUE THREAD

**Issue by Andrew5194** [coder/coder#5067]
I used the Makefile to build from source but unsure how to create an admin account to manage the platform. I can register a normal user fine, but is there a service account or something upon first log in that I can use to create an admin account?

**Comment by bpmct** [comment]
Hey @Andrew5194 - the first user is the admin account. You can manage roles within the UI. Does this help?

<img width="1532" alt="Screen Shot 2022-11-14 at 11 18 59 AM" src="https://user-images.githubusercontent.com/22407953/201724664-46865099-5530-4dda-9797-7e1dafe43c7c.png">

**Comment by Andrew5194** [comment]
Ahh I see okay, thanks I must have just been misunderstanding. I was also expecting to be able to modify the settings under Deployment for User Authentication but I guess this isn't possible from the web UI

**Comment by bpmct** [comment]
Ahh the deployment settings page is designed to be read-only. You can [configure Coder](https://coder.com/docs/coder-oss/latest/admin/configure) via environment variables. This is something we should probably make more clear though
