### ISSUE TITLE
`daemon-reload` warning at coder service restart

### ISSUE THREAD

**Issue by matifali** [coder/coder#5081]
### What would you like share?

After updating coder, and running `sudo systemctl restart coder` to restart coder service. I get this warning

`Warning: The unit file, source configuration file or drop-ins of coder.service changed on disk. Run 'systemctl daemon-reload' to reload units.`

Is it safe to ignore this warning?

if I don't ignore and run `sudo systemctl daemon-reload`, all workspaces using GPU lose access to GPU and I need to stop and start them again.

**Comment by ericpaulsen** [comment]
@matifali I do not run `sudo systemctl daemon-reload` prior to restart and Coder updates just fine. So in my experience, it's been safe to ignore the warning.

Although I'm not sure if losing GPU access is the expected behavior after a `daemon-reload`.

**Comment by matifali** [comment]
Thank you, @ericpaulsen. I am also ignoring the warning for now. If the user can safely ignore the warning, better the coder does not cause this warning to appear.

**Comment by ericpaulsen** [comment]
@matifali Coder does not cause the warning to appear. the warning is returned when the `systemctl` command is run. Coder can't change this behavior, so I will close this issue for now.
