### ISSUE TITLE
bug: changing a running workspace auto-stop does not reflect in the UI, until workspace is rebuilt

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5087]
Version: [`v0.12.7+49b340e`](https://github.com/coder/coder/commit/49b340e0392c4f7833fbe1395e982d0d6bf27fa4)

Video snippet
https://www.loom.com/share/b4b36a5f7ae64309a29c068553ba4253

**Comment by dcarrion87** [comment]
I'm guessing this is the same: https://github.com/coder/coder/issues/5146

This is a big issue for us.

**Comment by presleyp** [comment]
Closed as duplicate
