### ISSUE TITLE
`coder templates push` doesn't show useful error logs

### ISSUE THREAD

**Issue by ammario** [coder/coder#5090]
E.g.
```
I /t/windows coder templates push windows
> Upload "/tmp/windows"? (yes/no)
✔ Queued [1288ms]
✘ Running [2082ms]
template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1
Run 'coder templates push --help' for usage.
```

doesn't help me understand what's wrong with my template.

**Comment by embold-given** [comment]
Do you get what you're looking for if you use the `-v` switch to enable verbose output?

**Comment by DGovender** [comment]
I am experiencing the same error when using the templates create functionality (Please note: this is when using the -v switch) :

> Create and upload "~/container_data/coder/templates/docker"? (yes/no) yes
✔ Queued [27ms]
✘ Running [3824ms]
template import provision for start: recv import provision: plan terraform: terraform plan: exit status 1
Run 'coder templates create --help' for usage.`

I am running coder instance in a docker container that is setup using docker-compose.

**Comment by DGovender** [comment]
I have solved this issue. I am using a docker instance of coder which had the latest tag, however, upon being recreated, it was not pulling the latest version of coder. As the coder utility had been updated to the latest version, I was unable to upload and create templates. This was solved once I manually updated the image to the latest version.
