### ISSUE TITLE
feat: Show v2 enterprise license details in the UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5100]
Currently, admins have to run `'coder licenses list` to see their enterprise trial or paid license details. And it uses a Unix timestamp 😱

2 prospects have requested this information be visible in the Deployment UI.

It would be nice if the Unix times were converted to calendar dates.

**Comment by ammario** [comment]
@spikecurtis — curious about the decision to allow multiple licenses? It would be a lot easier to present and work with licenses if there was one max.

**Comment by ammario** [comment]
Soft-blocked on https://github.com/coder/coder/issues/5281
