### ISSUE TITLE
Support template grants

### ISSUE THREAD

**Issue by mtojek** [coder/coder#5106]
Extracted from: https://github.com/coder/coder/issues/5035#issuecomment-1316883329

The idea is to introduce a mechanism to control template permissions for different user groups. Few candidates:
1. Cancel build workspace jobs.
2. Disable edit auto-stop.
3. Use/edit templates.

CLI design:

```
coder templates grants <name> \
   --add-grant <group>:<action> \
   --add-grant DevOps:CancelWorkplaceBuild \
   --remove-grant Contractors:CancelWorkplaceBuild
```

**Comment by bpmct** [comment]
#3630 could be handled by grants as well - but I suggest we do it as a single option for now. By leveraging grants, we could do special things such as

> The "DataScience" group can modify their workspace schedule to account for long jobs. However, the "development" team should not be able to edit their schedule and workspaces should shut off after 3 hours of activity.
