### ISSUE TITLE
Can't login using coder cli

### ISSUE THREAD

**Issue by svallory** [coder/coder#5111]
Hi! I have set up a coder server using the Vultr marketplace app (https://www.vultr.com/marketplace/apps/coder). I've already logged in via the Web UI, added users, and created workspaces. I can't login via the coder cli on the same machine :/ (I've also tried using localhost:7080 as the URL)

```
coder login code.toki.space
build info: GET https://code.toki.space/api/v2/buildinfo: unexpected status code 404: unexpected status code 404, response has no message
	Error: {
	"error": {
		"msg": "Route not found.",
		"code": "empty"
	}
}

> Your Coder deployment hasn't been set up!
> Would you like to create the first user? (yes/no)
```

**Comment by kylecarbs** [comment]
Try adding the http protocol as a prefix! It should work.

**Comment by svallory** [comment]
@kylecarbs I tried adding `httpS` and it made no difference. Do you think disabling httpS may fix it? 

Also, here are the versions I'm using: 
coder cli: `Coder v0.12.7+49b340e`
coder on server: `Coder v1.29.0 c9cdf14ec`

I installed coder on ubuntu using the install script. I have no idea why the versions are different

**Comment by kylecarbs** [comment]
Might. What version are you on?

**Comment by svallory** [comment]
@kylecarbs 

coder cli: Coder v0.12.7+49b340e
coder on server: Coder v1.29.0 c9cdf14ec

**Comment by svallory** [comment]
I don't understand why the server shows such a high version on the footer

**Comment by kylecarbs** [comment]
Oh! You're using the wrong CLI! You need the v1 CLI in github.com/coder/coder-cli

**Comment by svallory** [comment]
Thanks, @kylecarbs ! But I would prefer to update the coder version on the server. How can I do that? (I searched the Coder OSS docs and couldn't find how)

**Comment by kylecarbs** [comment]
They are different versions entirely, and aren't upgradable.

You'll need to set up v2 (this repo) separately.

**Comment by svallory** [comment]
Thanks! I'll do that later!

Here's a tip... I think that could be more obvious in the documentation. As a newbie I didn't see that coming!

**Comment by kylecarbs** [comment]
I appreciate the feedback!

How did you happen upon installing the v1 product? Did you navigate from coder.com? Curious just so we can fix it.

**Comment by svallory** [comment]
Hey, @kylecarbs!

I installed it from [Vultr's app marketplace](https://www.vultr.com/marketplace/apps/coder), which started the confusion. Since I was installing Coder through an app marketplace, I assumed that it had to be the OSS version (my mistake). But the naming of the versions in the documentation didn't help. See... "Coder v1" and "Coder OSS" are not exactly opposites. I would suggest either changing "Coder v1" to "Coder Enterprise" or simply "Coder". Or maybe changing "Code OSS" to "Code v2 (OSS)"

Another suggestion... Add warnings on the upgrade documentation pages for [v1](https://coder.com/docs/coder/latest/setup/upgrade) and [OSS](https://coder.com/docs/coder-oss/latest/admin/upgrade) to alert users that they cannot upgrade from one version to another.

Lastly, how about changing this header in V1 docs

> Coder has open-sourced a new remote development platform 🥳 Check it out at coder/coder on Github

By this?

> Coder is being redesigned from the ground up in a new and open-sourced version! 🥳 Check it out on GitHub

or

> Coder is working on an exciting, completely new, and open-source version! 🥳 Check it out at coder/coder on Github

The point is: that call to action should make it clear that the versions are incompatible, and that coder OSS is another effort.

Oh, and BTW, I just noticed that there's no download/installation/"quick start" link for the enterprise version on the [pricing page](https://coder.com/pricing). So there's no way I would have guessed I could install that version from an app marketplace. And I think you can do that in DigitalOcean too

And one more thing... not sure you've noticed, but it is veeery hard to find information about you guys on google because your name is "coder", and even long queries like "[coder open-source development platform](https://www.google.com/search?q=coder+open-source+development+platform)" never show you guys on the first page :/

Anyways, I'm not trying to beat you up. On the contrary! I really like your product and I want you guys to succeed! Heck, I was even considering checking for an open spot to work with you guys in development strategy :)

So please take everything I said as kindness.

Cheers!
