### ISSUE TITLE
Unexpected non-JASON response

### ISSUE THREAD

**Issue by kurtashostap** [coder/coder#5114]
When creating a template for coder with 

`coder templates create <templatename> `  I get the following

> /home/coder/templates/docker-code-server $ coder templates create docker-code-server
> > Create and upload "~/templates/docker-code-server"? (yes/no) yes
> ⧗  Queued 
> 
> unexpected non-JSON response.                 
> Run 'coder templates create --help' for usage.

Below are some more logs:
![SmartSelect_20221117_115554_Chrome](https://user-images.githubusercontent.com/48567339/202428330-855f1094-1d9c-499a-8eb1-2ed25f3335f2.jpg)

Running ON:
Host OS: Unraid
CPU: Ryzen 5950X

**Comment by bpmct** [comment]
👋🏼 This is fixed when you update your client and server to the latest version. We're working on a plan to make sure this doesn't happen during another patch release
