### ISSUE TITLE
I have to refresh to see that agent is disconnected

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5116]
https://user-images.githubusercontent.com/22407953/202440336-15a864f7-22eb-439b-bdfd-c40bc10595ab.mov

This is on a template where the agent intentionally never connects but has a timeout of 10 seconds

**Comment by BrunoQuaresma** [comment]
Some thoughts about the implementation. We can iterate through the resources and agents to get the largest `ConnectionTimeoutSeconds` and call the `publishWorkspaceUpdate` after that time if the agent status is updated.
