### ISSUE TITLE
bug: workspace page is broken with AGPL-only backend

### ISSUE THREAD

**Issue by deansheather** [coder/coder#5118]
Regression, breaks `go run -tags embed ./cmd/coder`

The workspace page loads the workspace-quotas endpoint and fails if it doesn't get a 200 OK response. In AGPL-only builds of Coder, the workspace-quotas page returns 404 Not Found as quotas don't exist in AGPL-only builds of Coder.

This results in the workspace page being permanently hung on a loading state.

We should either:
- Fix the frontend so it tolerates a 404 as "no quotas enabled"; or
- Add an AGPL version of the backend route that returns an empty quota

![image](https://user-images.githubusercontent.com/11241812/202502348-6d84e389-cade-4fef-a710-d399d0832ec1.png)

**Comment by ninehills** [comment]
#5128
