### ISSUE TITLE
Sharing home folder across main dev workspace containers

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5129]
Where does coder stand on sharing home folders for the main coder dev container across workspaces.

We're looking to extend our Kubernetes workspace based implementation to allow users to mount the same home folder across multiple workspaces. The underlying storage is NFS.

This means that two workspaces could have the same home folder mounted at the same time with all the users working files.

Thoughts? Are there any issues you can see by doing this related to what the coder agent is doing?

**Comment by kylecarbs** [comment]
No issues! We have others doing this too. We intentionally don't touch the home directory in our agent, so all should just work.

**Comment by dcarrion87** [comment]
Thanks @kylecarbs.

Just curious, do you know if others pre-create home volumes outside of the coder environment and then statically referenced or are they getting created dynamically using a provisioner such as https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner?

We're at early phases of allowing this and just trying to figure out what will work best for this use case. Even considering other protocols, not just NFS.

**Comment by kylecarbs** [comment]
@dcarrion87 sorry I missed this!

I believe they pre-created volumes outside of Coder, but it wouldn't be impossible for us to add webhooks when a user is first-created, then you could use that to create a volume for them.
