### ISSUE TITLE
User-based provider credentials

### ISSUE THREAD

**Issue by dklesev** [coder/coder#5139]
Currently to be able to upload a template it seems to be required to have credentials to be preset for the used providers (f.e. AWS with `AWS_ACCESS_KEY_ID` aso.)

Will there be an option to let the user set those values on workspace creation? Or is this already possible?

Anything I try results in smtg like this:

> Error: key (), secret are missing, or config file not found within: /tmp/provisionerd893460570/cloudstack.ini, /tmp/provisionerd893460570/cloudstack.ini, /.cloudstack.ini

Use-case: one team writes templates and offers them for usage (like a template provider) and any user can run them in his own account. Provider credentials could be preset in the user profile.

**Comment by bpmct** [comment]
Hey @dklesev. You can use variables in Terraform as [workspace-scoped parameters](https://coder.com/docs/coder-oss/latest/templates#parameters) if you set `sensitive = false`. Then, you can pass that variable into the `provider` block.

This allows users to specify unique AWS access keys when creating workspaces. I haven't tested this so there may be typos, but here's the general structure:

```hcl
variable "aws_access_key_id" {
  sensitive = false
}
variable "aws_secret_key_id" {
  sensitive = false
}

variable "region" {
  sensitive = false
}

provider "aws" {
  region     = var.region
  access_key = var.aws_access_key_id
  secret_key = var.aws_secret_key_id
}
```

**Comment by bpmct** [comment]
One downside of using `sensitive = false` is the users' access key may be revealed in the build logs (something you should confirm to be sure). However, we are using `sensitive = true` to indicate that the variable is scoped for the entire template. 

We plan on using a separate resource for parameters for more flexibility (e.g. "workspace-scoped AND sensitive") in #4311, but this is a WIP.

**Comment by dklesev** [comment]
thx, seems to work, just missed the `sensitive = false` part.
already excited towards the new feature!
