### ISSUE TITLE
Schedule: use template default when re-enabling auto-stop

### ISSUE THREAD

**Issue by presleyp** [coder/coder#5154]
Current behavior: when I disable auto-stop, submit the change, and then enable auto-stop again, the duration of the auto-stop (ttl) that automatically populates is 12 hours no matter what (it's hard-coded on the frontend).

Expected behavior: the duration that populates is whatever is specified in my template as default TTL. If there is no default, it can fall back to some hard-coded default like 12 hours.

**Comment by presleyp** [comment]
@bpmct is my expectation here right? Do you think this is worth fixing?

**Comment by bpmct** [comment]
totally think it's worth fixing and reverting to the default if there is one set

**Comment by presleyp** [comment]
Closed by #5494
