### ISSUE TITLE
Port-forwarding's URL is limited to 63 characters

### ISSUE THREAD

**Issue by fpoussin** [coder/coder#5155]
Hi,

It's stated in the [documentation](https://github.com/coder/coder/blob/main/docs/networking/port-forwarding.md) that there's a limitation of 63 chars to the forwarded URL. 
This is a very limiting factor when using oauth and callback urls.

Why is that?
What would be needed to fix it?

Thanks

**Comment by coadler** [comment]
This limit is inherent to DNS, since you can't have more than 63 characters in a subdomain.

**Comment by fpoussin** [comment]
So this limit only applies to the wildcard subdomain length and not the whole URL?

**Comment by coadler** [comment]
Yep!

**Comment by fpoussin** [comment]
Oh okay, that makes sense.  Thank you!
