### ISSUE TITLE
Fix flake test TestProvisionerd/ReconnectAndComplete

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#5159]
This test has been failing quite frequently https://github.com/coder/coder/actions/runs/3532958155/jobs/5928185794

**Comment by coadler** [comment]
https://github.com/coder/coder/actions/runs/3533441070/jobs/5929068306

**Comment by mafredri** [comment]
Hopefully fixed (or at least alleviated by #5169), let's re-open if it is still a problem.
