### ISSUE TITLE
Error, when pushing a template from `0.12.9` client to  `0.12.8` server

### ISSUE THREAD

**Issue by matifali** [coder/coder#5164]
When I try to push a template update using client version `0.12.9` and server version `0.12.8`, I get the following error.

```console
json: cannot unmarshal number into Go struct field Template.build_time_stats of type codersdk.TransitionStats

```

**Comment by matifali** [comment]
It is fixed when both are the same version

**Comment by ammario** [comment]
This error is expected. Did the CLI warn you of the version mismatch?

**Comment by matifali** [comment]
Yes, it does warn of a version mismatch. But the error message can be made more meaningful. Or maybe don't allow pushing templates when the versions are mismatched.
