### ISSUE TITLE
UI customisation in wrong location

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5176]
I thought I would try my luck at UI customisations again but getting some weird behaviour.

Why would this show up at the bottom with a service account instead of with the actual resource id I associated it with? I'm wanting to set up some key value underneath like this:

```
dev cpu:
dev ram:
dev gpu:
dind cpu:
dind ram:
dind gpu:
```

Also looks like the doco needs some adjusting as it doesn't behave as it indicates: https://coder.com/docs/coder-oss/latest/templates/resource-metadata

<img width="1399" alt="Screen Shot 2022-11-28 at 7 33 49 pm" src="https://user-images.githubusercontent.com/2899172/204231966-b20e3094-9b3e-47cc-935d-5f88600e9b71.png">
<img width="574" alt="Screen Shot 2022-11-28 at 7 34 29 pm" src="https://user-images.githubusercontent.com/2899172/204231979-5040cc82-9fcf-4c02-9433-87765c4e3b99.png">

**Comment by BrunoQuaresma** [comment]
@dcarrion87 can we share the full config file? If it has any sensitive data can you send me over Discord? I'm trying to understand how you are defining the `kubernetes_pod.main[0].id`.

**Comment by dcarrion87** [comment]
Config follows. This is how it appears with the service account. Ideally want to hide all those others resources as they're just visual bloat to the user but I've given up on battling the hide feature for now.

![Screen Shot 2022-12-03 at 10 59 49 am](https://user-images.githubusercontent.com/2899172/205410976-7f34f5ad-d360-4877-a181-70e55c3f5506.png)


```
terraform {
  required_providers {
    coder = {
      source  = "coder/coder"
      version = "0.4.11"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.13.1"
    }
  }
}

# Workaround until this issue resolved:
# https://github.com/coder/coder/issues/4529
data "external" "env" {
  program = ["sh", "-c",
    <<-EOF
    cat <<-EOT
    {
    "namespace": "$TF_VAR_namespace"
    }
    EOT
EOF
  ]
}

locals {
  kubeconfig     = "REDACTED"
  namespace      = data.external.env.result.namespace
  workspace_name = lower("coder-${data.coder_workspace.me.owner}-${data.coder_workspace.me.name}")
  cpu            = 1
  memory         = "8Gi"
  gpu            = 1
}

provider "kubernetes" {
  config_path = local.kubeconfig
}

data "coder_workspace" "me" {}

resource "coder_agent" "main" {
  os             = "linux"
  arch           = "amd64"
  startup_script = <<EOT
    #!/bin/bash
    # home folder can be empty, so copying default bash settings
    if [ ! -f ~/.profile ]; then
      cp /etc/skel/.profile $HOME
    fi
    if [ ! -f ~/.bashrc ]; then
      cp /etc/skel/.bashrc $HOME
    fi
    # install and start code-server
    curl -fsSL https://code-server.dev/install.sh | sh  | tee code-server-install.log
    code-server --auth none --port 13337 | tee code-server-install.log &
  EOT
}

resource "coder_app" "code-server" {
  agent_id      = coder_agent.main.id
  name          = "code-server"
  icon          = "/icon/code.svg"
  url           = "http://localhost:13337?folder=/home/coder"
  relative_path = true
}

resource "kubernetes_config_map" "coder_workspace" {
  count = data.coder_workspace.me.start_count
  metadata {
    name      = local.workspace_name
    namespace = local.namespace
  }
}

resource "kubernetes_service_account" "coder_workspace" {
  count = data.coder_workspace.me.start_count
  metadata {
    name      = local.workspace_name
    namespace = local.namespace
  }
}
resource "kubernetes_secret" "coder_workspace" {
  count = data.coder_workspace.me.start_count
  metadata {
    name      = local.workspace_name
    namespace = local.namespace
    annotations = {
      "kubernetes.io/service-account.name"      = local.workspace_name
      "kubernetes.io/service-account.namespace" = local.namespace
    }
  }
  type = "kubernetes.io/service-account-token"
}

resource "kubernetes_role" "coder_workspace" {
  count = data.coder_workspace.me.start_count
  metadata {
    name      = local.workspace_name
    namespace = local.namespace
  }

  rule {
    api_groups     = ["*"]
    resources      = ["configmaps"]
    resource_names = [local.workspace_name]
    verbs          = ["*"]
  }
  rule {
    api_groups     = ["*"]
    resources      = ["secrets"]
    resource_names = ["REDACTED"]
    verbs          = ["get"]
  }
}

resource "kubernetes_role_binding" "coder_workspace" {
  count = data.coder_workspace.me.start_count
  metadata {
    name      = local.workspace_name
    namespace = local.namespace
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Role"
    name      = local.workspace_name
  }
  subject {
    kind      = "ServiceAccount"
    name      = local.workspace_name
    namespace = local.namespace
  }
}

resource "kubernetes_pod" "main" {
  count = data.coder_workspace.me.start_count
  depends_on = [
    kubernetes_role.coder_workspace,
    kubernetes_role_binding.coder_workspace,
    kubernetes_service_account.coder_workspace,
    kubernetes_secret.coder_workspace,
    kubernetes_config_map.coder_workspace
  ]
  metadata {
    name      = local.workspace_name
    namespace = local.namespace
  }
  spec {
    service_account_name = local.workspace_name
    toleration {
      key      = "nvidia.com/gpu"
      operator = "Exists"
      effect   = "NoSchedule"
    }
    container {
      name    = "dev"
      image   = "codercom/enterprise-base:ubuntu"
      command = ["sh", "-c", coder_agent.main.init_script]
      security_context {
        run_as_user = "1000"
      }
      env {
        name  = "CODER_AGENT_TOKEN"
        value = coder_agent.main.token
      }
      env {
        name  = "http_proxy"
        value = "REDACTED"
      }
      env {
        name  = "https_proxy"
        value = "REDACTED"
      }
      env {
        name  = "no_proxy"
        value = "localhost,127.0.0.1,REDACTED,.amazonaws.com"
      }
      resources {
        limits = {
          cpu              = local.cpu
          memory           = local.memory
          "nvidia.com/gpu" = local.gpu
        }
      }
    }
  }
}

resource "coder_metadata" "kubernetes_pod_main" {
  count       = data.coder_workspace.me.start_count
  resource_id = kubernetes_pod.main[0].id
  item {
    key   = "cpu"
    value = local.cpu
  }
  item {
    key   = "memory"
    value = "8Gi"
  }
  item {
    key   = "gpu"
    value = local.gpu
  }
}
```

**Comment by BrunoQuaresma** [comment]
@dcarrion87 thanks for sharing. I will take a look at it and I will let you know.

**Comment by BrunoQuaresma** [comment]
@dcarrion87 can you share with me a screenshot of your template testing page?

**Comment by dcarrion87** [comment]
@BrunoQuaresma what do you mean by template testing page? Is that different to the screenshot I posted [here](https://github.com/coder/coder/issues/5176#issuecomment-1335974852)?

**Comment by BrunoQuaresma** [comment]
@dcarrion87 ahh I mean, the template page for your "testing" template. But I don't think we need it anymore. We have a clue about what is happening. @coadler is going to take a look into it.

**Comment by dcarrion87** [comment]
Thanks @BrunoQuaresma @coadler! If there's a stream of work happening on this at the moment maybe the issues with hiding resources can be investigated as well. That seems broken too.

**Comment by coadler** [comment]
Did a bit of digging into this today, and I was able to reproduce it with the template you sent! I noticed a couple odd things:

1. It seems like the templates page always displays the metadata correctly. ![image](https://user-images.githubusercontent.com/6332295/207183390-cf95139e-123a-4970-a821-1d3542aa8d58.png)
2. The resource it decides to attach to on the workspaces page doesn't seem to be random, it always attaches to the service account.
3. I haven't been able to make a non-kubernetes template that reproduces the buggy behavior.

Should hopefully have this figured out today or tomorrow :slightly_smiling_face:

**Comment by coadler** [comment]
@dcarrion87 I've found the issue and have a workaround for you. The reason this doesn't work as expected is becuase multiple of the resources in your template have the same ID, because they all share the same name as the workspace. If you make each `metadata.name` unique instead of sharing the pod name it should function correctly!

**Comment by dcarrion87** [comment]
Thanks @coadler will give it a go shortly. Does that also go for hiding resources as well? (I will also test this).

**Comment by coadler** [comment]
I haven't tested hiding resources yet but I'm guessing it's the same issue
