### ISSUE TITLE
bug: code port 6060 process show in port forward pop-up

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5177]
Version: [`v0.12.9+2b6c229`](https://github.com/coder/coder/commit/2b6c229e4e2e94776500fe366b538afb6c24c199)

The two app processes I started are shown correctly in the port forward pop-up, but there is a coder process on port 6060 showing, which gives a 404.

This should not be visible.

![image](https://user-images.githubusercontent.com/2022166/204285149-f94f6e1d-9c4b-433c-830e-bc5c993a3f1c.png)
![image](https://user-images.githubusercontent.com/2022166/204285233-e721a83f-8cbc-41a1-9747-68b56ae37999.png)

**Comment by ammario** [comment]
Do you have a `coder server` running? That is the pprof service.

**Comment by bpmct** [comment]
I see this too :/ There isn't a `coder server` running in my workspace

**Comment by matifali** [comment]
me too.

**Comment by Emyrk** [comment]
Hit `/debug/pprof/`. Is is a golang pprof handler.

It is the `coder agent` pprof handler.

**Comment by Emyrk** [comment]
What would be the ideal behavior here? There is the profiler listening on 6060. We could omit this by passing in port to this code to omit:

https://github.com/coder/coder/blob/7df1e3bdd67482b2bb3b8574cd0c853efbdcfe88/agent/api.go#L28-L50

But that is hiding ports that are actually listening. :thinking:
