### ISSUE TITLE
scaletest: use new format (no config file required)

### ISSUE THREAD

**Issue by deansheather** [coder/coder#5202]
Remove the old JSON configuration format and convert the individual job types into subcommands of `coder loadtest`.

```
$ coder scaletest create-workspaces \
  --count 1000 \
  --template "name or ID" \
  [--parameters-file "path/to/file"] \
  [--parameter key="value"] \
  [--no-cleanup] \
  [--no-cleanup-failures] \
  [--no-wait-for-agents] \
  [--run-command "some command to run over reconnecting-pty in each workspace in the default shell"] \
  [--run-pty-size "80x24"] \
  [--run-timeout "5m"] \
  [--run-expect-timeout] \
  [--run-expect-output "expect this in command output"] \
  [--run-log-output] \
  [--connect-mode "derp|direct"] \
  [--connect-hold] \
  [--connect-hold-duration "5m"] \
  [--connect-url "http://localhost:4/"] \
  [--connect-interval "1s"] \
  [--connect-timeout "10s"]
```

**Comment by bpmct** [comment]
@deansheather this is going to be `coder scaletest`, right?

**Comment by deansheather** [comment]
Sure, I'll change it from loadtest to scaletest

**Comment by bpmct** [comment]
From https://github.com/coder/coder/pull/5206#discussion_r1037635910

> I actually forgot to specify the concurrency flags in the issue, my bad. We'll have flags for `--concurrency`, `--cleanup-concurrency`, `--timeout` and `--cleanup-timeout`

**Comment by deansheather** [comment]
I have removed `--no-cleanup-failures` as it can be implemented later, and `--run-pty-size` as it's not very useful.
