### ISSUE TITLE
CLI attempts to connect to the server regardless of args

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#5207]
feedback from a prospective customer:

> 
> The CLI tries to connect to the server to fetch version info when simply running with no args or even for commands that shouldn't need a connection, like "coder completion ..." - this can be a problem if the server is inaccessible, for example our deployment is only available from internal CIDRs (filtered on the AWS ALB load balancer ingress), including VPN IPs.. However, since I have coder completion zsh added to my brew zshrc scripts, whenever I open a terminal, it tries to connect. If I am not connected to the VPN, the process blocks for several seconds. Therefore, I would suggest to remove the implicit connection init on startup and only do so when needed (for commands need a connection).
>
> The error i'm getting after blocking new shell startup for about 6-8s:
>
>```
> check versions error: build info: do: Get "https://coder.example.com/api/v2/buildinfo": context deadline exceeded
> ```

**Comment by ammario** [comment]
It's possible to disable the version check by setting `CODER_NO_VERSION_WARNING=true` and `CODER_NO_FEATURE_WARNING=true`.

https://github.com/coder/coder/pull/5264 cuts the latency in half, but there still seems to be a hidden request somewhere. I'm investigating.
