### ISSUE TITLE
dogfood: use same/similar environment for .devcontainer and dogfood template.

### ISSUE THREAD

**Issue by matifali** [coder/coder#5211]
# Problem
The Dockerfile used in the [.devcontainer](https://github.com/coder/coder/blob/main/.devcontainer/Dockerfile) and the [dogfood](https://github.com/coder/coder/blob/main/dogfood/Dockerfile) template are different.
# Solution
Use the identical/similar Dockerfile to provide precisely the same development environment.

cc: @ammario

**Comment by bpmct** [comment]
@matifali would you like to work on this?

**Comment by matifali** [comment]
Yes, I can take it, Should the reference be the `Dockerfile` from dogfood?

**Comment by kylecarbs** [comment]
I think this will be pushed along by the `devcontainer` work I'm doing. Closing this to keep stuff tidy!

**Comment by matifali** [comment]
The discussion is continued in #7591
