### ISSUE TITLE
Login screen looks too much like an ad

### ISSUE THREAD

**Issue by ammario** [coder/coder#5232]
<img width="1308" alt="Screen Shot 2022-12-01 at 9 27 06 AM" src="https://user-images.githubusercontent.com/7416144/205092355-573baeb4-32be-4b1d-af42-556a3ebd9d02.png">

I like the idea of showing a tip of the day, but it should be small and informative like these: 
![image](https://user-images.githubusercontent.com/7416144/205092550-b94a3c64-1e10-449f-8977-da7a1df8b51f.png)

Another problem: we should have at least 10 of these in daily rotation before we implement it. I've only ever seen the Scheduling screen in Login, which makes our product look like Scheduling product.

cc @BrunoQuaresma @matifali

**Comment by BrunoQuaresma** [comment]
I'm going to remove it for now until we have this figured out

**Comment by BrunoQuaresma** [comment]
Closing it for now. Partially solved by https://github.com/coder/coder/pull/5239
