### ISSUE TITLE
improve release workflow to detect breaking changes 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5233]
- We need to be aware of a breaking change prior to doing a release
    - [x]  We have a way to label a PR as “breaking” pre-merge and post-merge
        - pre-merge: engineer can mark as commit as breaking with `feat!:` or `fix!:`
            - the label `release-breaking` is automatically added to the PR
        - post-merge: engineer or PM can label a PR as `release-breaking`
- When a release is created, it should be impossible to create a patch release if there were PRs with breaking changes
    - Any breaking changes are in a separate section in the changelog
    - We modify our [changelog generation script](https://github.com/coder/coder/blob/9557d456e819453e155e939a6d2508f43cba4d4a/scripts/publish_release.sh#L109-L113) to look up corresponding PRs, check for a breaking label, and sort them accordingly
    ```bash
    # old workflow
    git tag -m "release v0.0.0" v0.0.0
    git push origin v0.0.0
    
    # new workflow
    ./scripts/release.sh patch [-n|--dry-run]
    error: found breaking change
    promote to minor
    ```

Things to consider 

- [ ] Documentation on how to create a release. 
- [ ] Removing the workflow on tag to prevent "legacy releases"

**Comment by deansheather** [comment]
I think we should delegate the decision on what tag to make to the workflow. If we change the workflow to not run on tag, and instead run on workflow dispatch (like in v1) we can make the script decide what version to use by itself, and optionally have some controls for forcing version bumps if we really want different behavior to what the script decides.

The script will decide what version bump to use based on tags like release-breaking or whatever other metric we want.

**Comment by mafredri** [comment]
@deansheather are you simply referring to that `./release.sh` would normally take no argument, but you can optionally give it `--minor` to bump the specific number?

Or are you referring to how `./release.sh` is run. I.e. by someone locally or via a github action or some such?

Wrt to the latter, I think for the first step to improving this, it'd be fine if it's run manually by a user on their machine.

---

With regard to implementation, it seems quite straightforward how we can pull this information out during release. Some initial exploration:

```
# Compare HEAD to previous version
❯ git log --oneline HEAD...v0.13.1
81c39487 (HEAD -> main, origin/main, origin/HEAD) fix: Close tty first in `ptytest` cleanup (#5252)
ee4f0fc5 chore: enable debug logging for gotestsum (#5248)
8469dbc0 fix: add index to `provisioner_jobs.started_at` (#5245)
92c217bd fix: add index on `workspace_agents.auth_token` (#5244)

# For each hash, check associated PRs
❯ gh api -H "Accept: application/vnd.github+json" /repos/coder/coder/commits/81c39487/pulls | jq -r '.[].labels[].name'
release/test
```

This'll most likely require a GH API key so we don't run into any rate limitations, utilizing `gh` is optional but convenient.

**Comment by deansheather** [comment]
It's very easy to add parameters to a workflow dispatch run so it can be run on GitHub. Check the release workflow in coder v1, it just asks for what version you want to mark and tags it for you. In this case, you would just have checkboxes for whether you want to "force" a major, minor or patch and then have the workflow determine the tag to use and create it, then build coder.

**Comment by mafredri** [comment]
With #5366 merged, this issue is now 90% complete. We still need to disallow manual tag/push to prevent human error in deciding if it's a patch/minor release (#5382).
