### ISSUE TITLE
~/personalize can not run sudo command  in coder v1

### ISSUE THREAD

**Issue by SHPStudio** [coder/coder#5235]
error:
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

command:
sudo cp -f /home/config/project/settings.xml /usr/share/maven/conf/settings.xml

**Comment by ammario** [comment]
This tracker is for v2, but this doesn't seem like a Coder issue at all.

It looks like the `sudo` binary was incorrectly installed. You should run `ls -al /usr/bin/sudo` to see if the permissions are correct.

If sudo is correctly installed, you'll see the "s" flag in the first block, and "root root" in the third.
```
-rwsr-xr-x 1 root root 166056 Jan 19  2021 /usr/bin/sudo
```

You can run these commands as root wherever you're installing sudo to make sure it has the correct permissions:

1. `chmod u+s /usr/bin/sudo`
2. `chown root:root /usr/bin/sudo`

---

If you need more help, please join us on [Discord](https://discord.gg/coder).
