### ISSUE TITLE
Server based CLI installs with cross platform

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5241]
We are struggling providing cross platform instructions to users for installing the matching version across Windows, Mac, etc... 

Particularly at the moment where CLI features break between server versions it's important they get the right one from the get go and not the latest. E.g. 0.12.9 CLI breaks 0.12.6 server interaction.

Is there a world where a path at the server provides installer mechanism for cross platform so we can just add that to our documentation?

**Comment by matifali** [comment]
You can always get the server version from,
https://coder.yourdomain.com/bin/
It serves the binaries for all platforms. 
![image](https://user-images.githubusercontent.com/10648092/205441083-b4ab0250-2175-4fda-98f1-90b7fc4ee3f8.png)

**Comment by dcarrion87** [comment]
Aah that's useful. I wonder if there's something already in the code base that wraps this with platform installers?

**Comment by matifali** [comment]
I am not sure what you are talking about but you may guide your users to this link to download the latest version.

**Comment by dcarrion87** [comment]
The issue is this is still manual for users. I guess we will need to do our own one-liners on our doco pages for users to install the appropriate version for Windows, Mac and Linux users.
