### ISSUE TITLE
feature: connect Coder to an existing VM instance

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#5262]
a current v1 customer asked if we could have Coder connect to their already provisioned/configured VMs that their devs use on a daily basis.

they would prefer to not have to create a new instance for each Coder workspace, and instead run the agent on the existing VM and make it accessible in the dashboard. this would remove the need for migrating workspaces between VM instances.

**Comment by lapnd** [comment]
Hi,
I found this example https://github.com/bpmct/coder-templates/tree/main/shared-mac
I'm able to "register/attach" the existing VM to Coder

**Comment by kylecarbs** [comment]
Seems like we've essentially been able to do this!
