### ISSUE TITLE
Show IP address on workspace_build audit logs

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#5268]
![Screen Shot 2022-12-02 at 4 11 51 PM](https://user-images.githubusercontent.com/19142439/205386817-ec6fdfbf-9053-404f-ac62-b5845f7dae22.png)

The IP address on `workspace_build` audit logs shows as 'Not Available' in our UI. This is because there is not (an obvious) way to access the initiator of the request, or the request itself. 

During our Audit Log demos, it was indicated this information is very important to auditors, so we should investigate methods to pass it along, if possible.

**Comment by kylecarbs** [comment]
I also think `Not Available` is confusing because each request **always** is initiated from some IP.

**Comment by Kira-Pilot** [comment]
Spoke with @kylecarbs and there really isn't an IP address for these logs. As such, the current label `IP: not available` is misleading and should be removed entirely.
