### ISSUE TITLE
always get 502 Bad Gateway

### ISSUE THREAD

**Issue by jrabem82** [coder/coder#5274]
hi

I install coder via script install
and set var :
```
CODER_ACCESS_URL=http://MY_DOMAIN
CODER_ADDRESS=127.0.0.1:3000
CODER_PG_CONNECTION_URL=
CODER_TLS_ENABLE=false
```
i am using the built in postgres
when i open the logs i see: 
```
...
Using built-in PostgreSQL (/home/USER/.config/coderv2/postgres)
View the Web UI: http://MY_DOMAIN
2022-12-02 22:25:25.297 [INFO]        (coderd.update_checker)        <./coderd/updatecheck/updatecheck.go:147>        (*Checker).start        time until next update check   >
Get started by creating the first user (in a new terminal):
coder login http://MY_DOMAIN
```

but when i browse to http://MY_DOMAIN, i always get 502 bad gateway
note : coder is behind a nginx proxy
what am I doing wrong?

**Comment by decyphertek-io** [comment]
I found a way to get this working and a solution to your problem. I found that typically using localhost allows using a public IP with self signed certs. These settings can always be change in nginx to point to a real domain and have CA SSL certs. It is unclear as of now what the "CODER_PG_CONNECTION_URL=" should be . I commented it out for now, until I run into a glitch in the system. 

$ wget https://github.com/coder/coder/releases/download/v0.13.1/coder_0.13.1_linux_amd64.deb
$ sudo dpkg -i coder_0.13.1_linux_amd64.deb
$ sudo vim /etc/coder.d/coder.env
CODER_ACCESS_URL=http://localhost
CODER_ADDRESS=localhost:8081
#CODER_PG_CONNECTION_URL=
#CODER_TLS_CERT_FILE=
CODER_TLS_ENABLE=false
#CODER_TLS_KEY_FILE=
$  sudo systemctl enable --now coder
# Need nginx reverse proxy pointing to 8081( I am usin Nginx V 1.22 , config in different location on older versions ) 
$ sudo vim /etc/nginx/conf.d/custom.conf
server {
    listen 443 ssl;
    server_name localhost;
    ssl_certificate             /etc/ssl/certs/self-signed-crt.pem;
    ssl_certificate_key     /etc/ssl/private/self-signed-key.pem;
    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;
    ssl_protocols             TLSV1.1 TLSV1.2 TLSV1.3;
    ssl_ciphers                HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
location / {
    proxy_pass http://localhost:8081;
    proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Accept-Encoding gzip;
    proxy_set_header X-Forwarded-Host $host:$server_port;
    }
}
# https://ip-of-server
# Create an Account Login 
# Workspace Template from terminal run
$ coder templates init


###References###
https://github.com/coder/coder/blob/main/docs/install/packages.md
https://decyphertek.readthedocs.io/en/latest/#Nginx/

**Comment by decyphertek-io** [comment]
I am running into issues myself setting up a workspace. I chose docker option from the template and made sure docker was installed. I will open up a new thread regarding this issue. Maybe Modsec is block the api call?

$ curl -fsSL https://raw.githubusercontent.com/decyphertek-io/configs/main/bash-scripts/docker.sh | bash
$ coder templates init

Extracting  docker  to ./docker...
Create your template by running:
                                                            
   cd ./docker && coder templates create                    

Examples provide a starting point and are expected to be edited! 🎨             
adminotaur@decyphertek:~$ ^C
adminotaur@decyphertek:~$ cd ./docker && coder templates create
You are not logged in. Try logging in using 'coder login <url>'.
Run 'coder templates create --help' for usage.                  
adminotaur@decyphertek:~/docker$ coder login https://52.91.16.33
build info: do: Get "https://52.91.16.33/api/v2/buildinfo": context deadline exceeded
Failed to check server "https://52.91.16.33" for first user, is the URL correct and is coder accessible from your browser? Error - has initial user: do: Get "https://52.91.16.33/api/v2/users/first": dial tcp 52.91.16.33:443: i/o timeout
Run 'coder login --help' for usage.

**Comment by jrabem82** [comment]
does your nginx is in the same machine of coder?
why you use `localhost` on `CODER_ACCESS_URL` ?
the docs says: This should not be localhost 
https://coder.com/docs/coder-oss/latest/admin/configure#access-url

**Comment by ghuntley** [comment]
Can you please share your nginx configuration?

**Comment by jrabem82** [comment]
Here is my configuration nginx:
```
server {
 listen 80;
  listen [::]:80;

  server_name DOMAIN;

  location / {
    proxy_pass http://DOMAIN/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Accept-Encoding gzip;
  }
}
```
and in my host i have an alias with my DOMAIN to my coder machine

with that, il always get error 502

**************************
I tried another configuration, set my nginx proxy redirect to port 3000 and CODER_ADDRESS to listen on all interface:
```
#coder
CODER_ACCESS_URL="http://DOMAIN"
CODER_ADDRESS="0.0.0.0:3000"

#nginx
server {
 listen 80;
  listen [::]:80;

  server_name DOMAIN;

  location / {
    proxy_pass http://DOMAIN:3000/;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Accept-Encoding gzip;
  }
}
```

i can create user and create docker-code-server template with command line.
go back to browser i can access coder UI with my DOAMIN, and create workspace

but when when i look to the logs of the container running, i have

```
"error": unexpected status code 426: unexpected non-JSON response "text/plain; charset=utf-8"
                Error: WebSocket protocol violation: handshake request must be at least HTTP/1.1: "HTTP/1.0"
           {"message":"Failed to accept websocket.","detail":"failed to accept WebSocket connection: WebSocket protocol violation: handshake request must be at least HTTP/1.1: \"HTTP/1.0\""}
2022-12-05 19:36:35.413 [WARN]  <./agent/agent.go:154>  (*agent).runLoop        run exited with error ...
  "error": run coordinator:
               github.com/coder/coder/agent.(*agent).run
                   /home/runner/work/coder/coder/agent/agent.go:229
             - unexpected status code 426: unexpected non-JSON response "text/plain; charset=utf-8"
                Error: WebSocket protocol violation: handshake request must be at least HTTP/1.1: "HTTP/1.0"
           {"message":"Failed to accept websocket.","detail":"failed to accept WebSocket connection: WebSocket protocol violation: handshake request must be at least HTTP/1.1: \"HTTP/1.0\""}
2022-12-05 19:36:35.417 [DEBUG] (tailnet.wgengine)      <./tailnet/conn.go:712> Logger.func1    netcheck: [v1] report: udp=true v6=false v6os=false mapvarydest=false hair= portmap= v4a=[MY_ROUTEUR_IP]:44094 derp=999 derpdist=999v4:15ms
2022-12-05 19:36:35.417 [DEBUG] (tailnet.wgengine)      <./tailnet/conn.go:712> Logger.func1    magicsock: home is now derp-999 (coder)

````

i think he tried to use port 44094 for the websocket but blocked by my router

**Comment by T0mThomson** [comment]
> 

The error is happening because websocket doesn't support http 1.0.

You should add `proxy_http_version 1.1;` in your nginx location block:

`
  location / {
    proxy_pass http://DOMAIN:3000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Accept-Encoding gzip;
  }
`

**Comment by jrabem82** [comment]
hi!
ok, I'm going to try that this weekend and report back.

**Comment by jrabem82** [comment]
> > 
> 
> The error is happening because websocket doesn't support http 1.0.
> 
> You should add `proxy_http_version 1.1;` in your nginx location block:
> 
> ```
>   location / {
>     proxy_pass http://DOMAIN:3000/;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "upgrade";
>     proxy_set_header Accept-Encoding gzip;
>   }
> ```

sorry for the delay, i was busy

thank you very much, it solved my problem
