### ISSUE TITLE
README.md is not parsed at template version page.

### ISSUE THREAD

**Issue by matifali** [coder/coder#5277]
![image](https://user-images.githubusercontent.com/10648092/205440891-1fcba260-e738-471d-883c-57502fc1c69b.png)

**Comment by BrunoQuaresma** [comment]
Yes, it is expected. The initial idea on the template version page was to show the source files but I can see value in showing the parsed version as well.

**Comment by matifali** [comment]
So may be you can parse the ReadMe also, if there are Dockerfiles in a sub-directory names images. Are you going to show them also?

**Comment by BrunoQuaresma** [comment]
Right now we only show:
- Markdown files
- Terraform files

But I think dockerfiles would be interesting as well. Also, showing the file as a tree instead of tabs can be helpful to visualize subdirectories 🤔

Thx for sharing your thoughts with us

**Comment by matifali** [comment]
Should I open a new Issue to show `Dockerfile`?

**Comment by bpmct** [comment]
We show Dockerfile now :)

**Comment by BrunoQuaresma** [comment]
@matifali closing it for now but feel free to reopen it
