### ISSUE TITLE
Feature: TOTP 2FA for SSH connection

### ISSUE THREAD

**Issue by bartonip** [coder/coder#5280]
It would be great if on connection to a coder mediated SSH session we could choose if logging on requires the input of a 2FA code.

Ideally the authenticator app would be set up when the user first logs on and then the same authenticator can be used to login to the coder web panel and also any ssh sessions.

This would also make it much easier to meet new data security compliance items in Australia.

**Comment by ghuntley** [comment]
> This would also make it much easier to meet new data security compliance items in Australia.

This particular item caught my eye @bartonip  - any specifics re: new data security compliance items? (medibank/optus or something else...)

**Comment by L14MJ4M3S0N** [comment]
There is the potential for this to be solved under a U2F FIDO2 implementation.

This would also benefit the use of pre-generated SSH keys stored on devices such as YubiKeys.

**Comment by bpmct** [comment]
As a workaround, you can enforce 2FA in your identity provider + short sessions with `CODER_MAX_SESSION_EXPIRY` and `CODER_DISABLE_SESSION_EXPIRY_REFRESH`. You can see these in coder-server --help.

With that being said, we are open to OSS contributions for Yubikey docs (#6226), webauthn support (#6170), or TOTP. We'd love to eventually focus on this, but have no concrete plans on our roadmap.

Additionally, if you have a strong requirement for one of these before you can adopt Coder at your enterprise, we'd like to hear from you since that can influence our roadmap: coder.com/contact.

**Comment by bartonip** [comment]
Ironically I can't enforce 2FA in my IdP because of issue #4505. Some of our accounts were registered before we set up OIDC and now we are stuck with password only authentication.

**Comment by OffensiveBias-08-145** [comment]
Hey @bpmct 

Currently in contact with Michael on your sales team. 

The ideal use case would to be able to use the PGP and PIV stored on the Yubikey within each VM. 

These are then used for mTLS, Tailscale, commit signing, etc.

**Comment by mjasten32** [comment]
Hey @bartonip

Thank you for the context and for bringing this to our attention! This is something that we are very interested in. Are you open to hopping on a call this week to discuss this in more detail so we can address this as efficiently as possible? I'll also follow up with you via email so we can find a time. 

Thanks again!
Michael

**Comment by mjasten32** [comment]
Hey @OffensiveBias-08-145 !

Hope that you are doing well! Thank you for bringing this to our attention - it is something that we are very interested in and would love to get more of your perspective on. Are you open to hopping on a call this week to discuss this in more detail and ensure we are addressing this as efficiently as possible? I'll follow up over email as well. 

Thanks again and hope to chat soon! 

Best,
Michael

**Comment by OffensiveBias-08-145** [comment]
Sure thing! 

Shoot me an email!
