### ISSUE TITLE
feat: Do not auto-create users in Coder when OIDC enabled

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5287]
This is a v1 feature request from one customer and another strategic prospect, that will be implemented.

Drivers:

1. Security - institutions have formal approval processes for application access. Auto-creating does not honor this.
2. Cost control - Anyone in a domain can create a user account and start creating workspaces that consume compute resources and cost

**Comment by sharkymark** [comment]
So my request is we do this in v2 to avoid technical debt. It should be configurable. i.e., some customers will auto-allow user creation, others will not.

**Comment by bpmct** [comment]
We have this :)

```sh
  --oidc-allow-signups                                Whether new users can sign up with
                                                      OIDC. Consumes
                                                      $CODER_OIDC_ALLOW_SIGNUPS
```
