### ISSUE TITLE
Poor user experience with bricked workspace

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5297]
I tried my hand at bricking workspaces in various unique ways in order to evaluate our user experience. In two of the tests I ran, I was able to create a sub-optimum user experience:

1. Wrote a ton of data to Overlay, and broke Coder's UI
2. Used up all potential memory, and Coder didn't detect it.

### Case 1: writing too much stuff to overlay

Command: `sudo fallocate -l 100G /mytest.txt`

![Screen Shot 2022-12-05 at 12 01 07 PM](https://user-images.githubusercontent.com/2059212/205720718-eab0ada7-7e94-43ac-9556-1676a387a7db.png)

I tried refreshing this page multiple times, but it refused the render the buttons. This is easily repeatable.

### Case 2: eatting up all available memory

Command `stress -m 1000` in 3 separate terminals

In this case, the host was essentially unusable (unable to load code-server, Terminal didn't work, etc) but the UI looked perfectly normal. I would have expected something to have looked weird

**Comment by matifali** [comment]
If these are docker based workspaces, aren't you limiting the memory they can use?

I am not sure how we can limit disk usage using docker.
