### ISSUE TITLE
Error(Using Helm Chart): Template version job hasn't completed

### ISSUE THREAD

**Issue by vyas-n** [coder/coder#5299]
Hi Folks,

I'm new to Coder and ran into an error when trying to install the helm chart as per these instructions: https://coder.com/docs/coder-oss/latest/install/kubernetes

After installing the postgresql database, creating the k8s secret, & deploying the helm chart I'm presented with a loading screen that doesn't seem to end (see screenshot).

When I try to start a workspace from the WebUI it returns with the error message: "Template version job hasn't completed!"

Does someone know why the kubernetes template might be stuck?

Here's the helm values I'm passing into it:
```yaml
---
coder:
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: coder.example.com.
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: CODER_ACCESS_URL
      value: "https://coder.example.com"
    - name: CODER_AUTO_IMPORT_TEMPLATES
      value: "kubernetes"
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
```

Here's the pod logs:
```
❯ kubectl logs deployment.apps/coder -f
Coder v0.13.1+9e80322 - Software development on your infrastucture

View the Web UI: https://coder.example.com
2022-12-05 23:23:53.252 [INFO]  (coderd.update_checker) <./coderd/updatecheck/updatecheck.go:178>       (*Checker).update       checking for update

Get started by creating the first user (in a new terminal):
 coder login https://coder.example.com

==> Logs will stream in below (press ctrl+c to gracefully exit):
2022-12-05 23:23:53.465 [INFO]  (coderd.update_checker) <./coderd/updatecheck/updatecheck.go:205>       (*Checker).update       update check result     {"latest_version": "v0.13.1"}
2022-12-05 23:23:53.471 [INFO]  (coderd.update_checker) <./coderd/updatecheck/updatecheck.go:147>       (*Checker).start        time until next update check    {"duration": "23h59m59.993593549s"}
2022-12-05 23:24:58.469 [INFO]  (coderd)        <./coderd/users.go:186> (*API).postFirstUser    auto-imported template  {"request_id": "739b7f73-cc52-4dff-a248-ffbd6947d4a4", "id": "78436308-217e-4897-a95f-6ce078d6fdba", "template": "kubernetes", "parameters": {"namespace": "coder", "use_kubeconfig": "false"}}
```

The above screenshot appears when navigating to: http://coder.example.com/templates/kubernetes/workspace

<img width="1587" alt="Screenshot_2022-12-05_at_17 49 08" src="https://user-images.githubusercontent.com/86535092/205773491-23c11ded-b448-4df4-8788-d510ac07b798.png">

**Comment by vyas-n** [comment]
Sorry to ask, but is there anyway to increase verbosity for the logs? There's not much information about what could be happening or going wrong.

**Comment by kylecarbs** [comment]
@vyas-n try run Coder with `CODER_VERBOSE=true`! It should hopefully tell you what's going on.

**Comment by vyas-n** [comment]
Thanks @kylecarbs,

This seems to be a bug with trying to specify a default set of templates to load via the helm chart:
```yaml
coder:
  env:
    - name: CODER_AUTO_IMPORT_TEMPLATES
      value: "kubernetes"
```

By removing the above, the error stopped, and I was able to add templates to coder using the CLI: 
- https://coder.com/docs/coder-oss/latest/install/install.sh
- https://coder.com/docs/coder-oss/latest/templates#customize-templates
