### ISSUE TITLE
Template library & upload via the dashboard

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5313]
Allow users to create templates from a starter or upload Terraform.

<img width="982" alt="Screen Shot 2022-12-06 at 8 12 33 AM" src="https://user-images.githubusercontent.com/22407953/205934845-347d3208-2788-47cb-ac68-482a081af93d.png">

**Comment by BrunoQuaresma** [comment]
It is done and available under `CODER_EXPERIMENTAL` https://coder.com/docs/coder-oss/latest/admin/high-availability#setup
