### ISSUE TITLE
User activity metrics

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5315]
This is related to #4877, but focused on determining how active users are in a Coder deployment. The following are features we will need (we have these in v1):

- [x] #5751 Active users, overall in the deployment (not per-template)
  - We currently export this in prometheus
- [ ] IDEs used per-template
  - e.g. coder_apps (ideally drilldown into app slug), VS Code SSH, JetBrains, SSH, Terminal
- [ ] IDEs used deployment-wide
  - If this is only via prometheus, that is OK
- [ ] Parameters used per-template
  - e.g. most used images, CPU size, etc.
- [ ] Active users, by group
  - If this query is too difficult, we can defer until we do organizations

**Comment by MrPeacockNLB** [comment]
We as a german company has to respect GDPR and work council. This feature must be configurable through a parameter so it can be disabled completely if needed.

**Comment by matifali** [comment]
@bpmct, how is it different from template insights? One way to get user-specific metrics is to add a user filter on the template insights page.

**Comment by bpmct** [comment]
I think we can close this out! It was an old issue!
