### ISSUE TITLE
Custom provisioner support

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5321]
Allow Coder admins to write their own provisioners to integrate with custom cloud APIs or #4528.

**Comment by bpmct** [comment]
Ah yeah, Terraform has provisioners and Coder has [prosivioners](https://github.com/coder/coder/tree/main/provisioner) too which are different. The basics of provisions in Coder (to my knowledge) is:

1. Coder sends build instructions to `provisionerd` (template name, parameter values)
1. Provisionerd accepts build instructions. It does stuff (e.g. runs `terraform apply`) and returns a graph of resources and agents
1. Coder displays resources and agents in the dashboard and attempts to reach the agent to

A custom provisioner (e.g. `coder provisioners run /usr/bin/python3 ./customProvisioner.py`) would take place of step 2. Perhaps it could run custom logic or use another IaC API (`pulumi up`, `terragrunt run-all`)

**Comment by ElliotG** [comment]
IMO, I think this is low priority/not worth doing. If someone is super passionate about doing this, they can build it themselves and propose a pull request, but I think this would meaningfully impact the scope of what we are responsible, for a niche audience. 

If there are people reading this that need Pulumi or bust, please comment and prove me wrong.
