### ISSUE TITLE
User identity is based on non-unique claims in OpenID Connect ID token

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#5342]
When configured to use OpenID Connect, Coder derives the username for an authenticated user as follows:

> When a new user is created, the `preferred_username` claim becomes the username. If this claim is empty, the email address will be stripped of the domain, and become the username (e.g. `example@coder.com` becomes `example`).

Relevant code: https://github.com/coder/coder/blob/a4a319a76e3e65bc4770cf769c877656239515de/coderd/userauth.go#L239-L258

Neither the `email` and `preferred_username` claims are guaranteed to be unique or stable values. The [OpenID Connect spec](https://openid.net/specs/openid-connect-core-1_0.html) says:

> The sub (subject) and iss (issuer) Claims, used together, are the only Claims that an RP can rely upon as a stable identifier for the End-User, since the sub Claim MUST be locally unique and never reassigned within the Issuer for a particular End-User, as described in [Section 2](https://openid.net/specs/openid-connect-core-1_0.html#IDToken). Therefore, the only guaranteed unique identifier for a given End-User is the combination of the iss Claim and the sub Claim.
> 
> All other Claims carry no such guarantees across different issuers in terms of stability over time or uniqueness across users, and Issuers are permitted to apply local restrictions and policies. For instance, an Issuer MAY re-use an email Claim Value across different End-Users at different points in time, and the claimed email address for a given End-User MAY change over time. Therefore, other Claims such as email, phone_number, and preferred_username and MUST NOT be used as unique identifiers for the End-User.

**Comment by ghuntley** [comment]
Discussing this internally, and we'll be with you soon @aaronlehmann. Thanks for the super details GitHub issue. cc @sreya

**Comment by aaronlehmann** [comment]
Thanks @sreya, that makes sense. I suppose my point of confusion was that at least one of the `email` or `preferred_username` claims is required, otherwise [the authentication fails](https://github.com/coder/coder/blob/a4a319a76e3e65bc4770cf769c877656239515de/coderd/userauth.go#L252-L254). That, combined with the description in the docs of how the username is derived, made me think Coder was depending on `email` or `preferred_username` as a stable user identity.

The system I'm integrating with does not directly provide an `email` or `preferred_username` claim. I was able to work around this, but it might be nice to avoid requiring one of those claims to be present if Coder does not actually rely on them as a basis for identity. I'll go ahead and close this ticket, but please let me know if you'd be open to a new ticket about removing the dependency on `email` / `preferred_username`.

**Comment by sreya** [comment]
@aaronlehmann ahh I see how that could be an issue :slightly_smiling_face: There may be others but I believe one reason that we require `email` and `username` is they are included in our audit logs and we've had customers require that these values match the values of the identity provider upstream so that when they ingest audit logs they can match logs to users. @kylecarbs may have better insight into whether we can remove those fields.

**Comment by aaronlehmann** [comment]
Thanks. Apparently the expectation is that email and user ID would be fetched from the `userInfo` endpoint rather than be supplied directly inside the token.
