### ISSUE TITLE
ui: I can not see the star. 

### ISSUE THREAD

**Issue by matifali** [coder/coder#5351]
Where is the star indicating the preferred relay?
![Screenshot from 2022-12-08 17-01-47](https://user-images.githubusercontent.com/10648092/206465861-586f46d9-501a-4070-ac18-a0c25dcc79f9.png)

Also, Why do I get 60 ms latency when both the client and server are on the same network?

**Comment by BrunoQuaresma** [comment]
You can ignore the star thing, the verbiage is outdated. Not sure why this latency is quite high. Other Coder folks will help you with that.

**Comment by matifali** [comment]
Thanks for clarifying it.
