### ISSUE TITLE
audit: autogenerate docs for all events that are audited

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5356]
Let's add a table to our auto-generated docs based on the events we audit. This will make it easier for us to smoke-test the audit logs, identify actions that are not audited, and give customers accurate information on what we're auditing.

We're currently doing this in our docs for our Prometheus metrics

https://coder.com/docs/coder-oss/latest/admin/prometheus#available-metrics

**Comment by bpmct** [comment]
A good format for this is in our Coder v1 docs https://coder.com/docs/coder/latest/admin/audit#telemetry

**Comment by Kira-Pilot** [comment]
An example of V1 audit docs in table form can be viewed [here](https://coder.com/docs/coder/latest/admin/audit#telemetry). 

Previous implementation of the V2 metrics table generator can be found [here](https://github.com/coder/coder/blob/main/scripts/metricsdocgen/main.go), which draws from the [Prometheus metrics file](https://github.com/coder/coder/blob/main/scripts/metricsdocgen/metrics).

Audit definitions already exist and can be found [here](https://github.com/coder/coder/blob/main/enterprise/audit/table.go).

A reasonable approach might be to load the auditable resources from the above file and convert them into `.md`.
