### ISSUE TITLE
Eclipse Theia with Coder

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#5367]
- [ ] Collab https://twitter.com/GeoffreyHuntley/status/1601283744224026624
- [ ] Consider topics of inclusion of `Theia` included by default in relation to below.
- [ ] Ship templates that offer `Theia` side-by-side of `code-server` as an option for web editor
- [ ] Update coder.com/docs with above

**Comment by sharkymark** [comment]
@ghuntley can't you just try this out in a template?
