### ISSUE TITLE
Make it clearer as to what CLI the users have to download

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#5372]
I think there should be some work to prevent people from trapping themselves into using the wrong CLI

The first thing I did when trying to use Coder v2, is :
1. Install the Coder server using the [codercom/coder](https://hub.docker.com/r/codercom/coder) Docker image
2. See docs mention the Coder CLI
3. Look around on the internet and repos, find nothing (I am running Windows)
4. Find the [coder/coder-cli](https://github.com/coder/coder-cli) repo by looking in the coder org and assume it's the CLI I need to use (yes, there is a warning in the README but my screen is not tall enough for me to see it so I just jump on the release section -> [image](https://user-images.githubusercontent.com/57866459/206894305-1ac8c1c2-fc78-49cb-a0ca-9278ecd6d017.png))
6. Nothing works
7. Join the community discord and ask for help
8. Figure out i'm just using the wrong CLI

And I've seen this scenario repeat multiple times since I've been in the server.

---

My ideas to prevent this are:
- (upcoming versions of v1 CLI) (cli change) ``coder login`` checks if the server is v2, if it is then it should warn the user
- (for older versions of v1 CLI) (backend change) whenever ``/internal-auth`` is visited on a Coder v2 instance, the web page should tell the user they're using the wrong CLI, and point them to the v2 CLI
- The docs should also make it clearer that the server binary and the CLI are the same thing, probably in the [Install script](https://coder.com/docs/coder-oss/latest/install/install.sh) section, they should also have a windows binary linked.

Another thing (somewhat unrelated) is that it'd be a nice addition if there was a badge in the readme that points to docs, I like being able to teleport to docs from a GH repo.

**Comment by sharkymark** [comment]
Great feedback @phorcys420 I think less technical people can end up in a situation where a. they don't know the CLI is the server, and b. they keep starting up servers on their local machines by accident.

**Comment by phorcys420** [comment]
Another user has had this issue in the Discord today, I think this should be reopened!

https://discord.com/channels/747933592273027093/971231372373033030/1237056935229132882

**Comment by phorcys420** [comment]
Suggestion from @­feri in the Discord :

the issue I had was under installation I didn't read the first line but I see right away the curl and then the "to start coder server", I thought maybe that is only for Server side installation only.
I clicked on command line there was no link or instruction on how to install.
maybe put under Command Line the same installation?
Or the First Line Bold?

😆 I know we need to better read, but sometimes you get distructed with other part of doc and you don't read what you must read.

![image](https://github.com/coder/coder/assets/57866459/0bdbee5f-a48a-470b-b11d-9c0a80465b42)

**Comment by phorcys420** [comment]
On the other hand, I think the "A single CLI (coder) is used for both the Coder server and the client." part on the [Installation](https://coder.com/docs/v2/latest/install) could be highlighted better, maybe like this :

> [!IMPORTANT]
> A single CLI (`coder`) is used for both the Coder server and the client.

**Comment by matifali** [comment]
@bpmct @ammario, when are we going to sunset/archive https://github.com/coder/coder-cli?

**Comment by ammario** [comment]
I archived it. We still have some stragglers on v1, so will probably leave the repo around for a while.
