### ISSUE TITLE
Clone a dev workspace

### ISSUE THREAD

**Issue by thalesfsp** [coder/coder#5389]
We have one workspace which is working. Is possible to clone for our other devs?

**Comment by BrunoQuaresma** [comment]
Hi there! Why not create another workspace using the same template? What you expect to have from a clone feature?

**Comment by MrPeacockNLB** [comment]
For my understanding should workspaces be ephemeral. Any changes should be applied to the template or the underlying docker image. Then you can make as much copies as you wand (a.k.a. clone).

**Comment by matifali** [comment]
If it is a docker bases workspace, you can use docker commit to save tge current version as a new image. That can be used as a base image for your template then.

**Comment by thalesfsp** [comment]
@matifali Thank you for your suggestion! This is what I was looking for!
