### ISSUE TITLE
Is there a way to add a reconnect button to the terminal?

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5396]
When the terminal is disconnected, we add a big "Disconnected" banner. Could we make this interact-able and have a way to refresh the connection?

<img width="887" alt="Screen Shot 2022-12-12 at 11 19 22 PM" src="https://user-images.githubusercontent.com/2059212/207241370-aa05e7bd-8bf1-4cea-8c03-91bc436b9926.png">

**Comment by ElliotG** [comment]
Wait, it looks like refreshing the page does the reconnect. While awesome, we should make this more discoverale

**Comment by kylecarbs** [comment]
Certainly agree with this... I don't know why I didn't add a reconnect button when I created this feature...

**Comment by mattlqx** [comment]
Or just any key input would try to reconnect automatically?
