### ISSUE TITLE
Regression from 0.12.7 to 0.13.2

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5397]
Repro:

-I stood up a new Coder cluster in Azure AKS using the helm chart
-I logged into the app, and navigated to create a new workspace

In 0.13.2, the Template version job never completes, and the UI spins forever trying to load the template description. The result is that you can never launch a container / i.e. the app is unusable. There was nothing in the logs available from kubectl.

In 0.12.7, it worked, but still has that bug where you need to refresh the UI to get the template description to load.

**Comment by bpmct** [comment]
Thanks for the report, Elliot. We'll remove the AUTO_IMPORT_TEMPLATE feature now since it doesn't behave as expected. #5401.

Very soon, we'll have support for creating templates in the UI which will replace this feature
