### ISSUE TITLE
Git authentication doing nothing

### ISSUE THREAD

**Issue by barthofu** [coder/coder#5416]
I've setup git auth following the doc (https://coder.com/docs/coder-oss/latest/admin/git-providers) but when i'm trying to clone a private repo or doing any git-auth based operations, this problem occurs:
1. Coder shows me this:
```
Open the following URL to authenticate with Git:

        https://<my_domain>/gitauth/primary-github
```
2. I click the link
3. I'm redirected to the homepage of my coder web panel (`/workspaces`)
4. Nothing change in my shell after the login, i'm still not logged 

Here's some additional infos:
- my .env is as follow:
```env
# git
CODER_GITAUTH_0_ID=primary-github
CODER_GITAUTH_0_TYPE=github
CODER_GITAUTH_0_CLIENT_ID=<my_oauth2_app_client_id>
CODER_GITAUTH_0_CLIENT_SECRET=<my_oauth2_app_client_secret>
```
- my client id and client secret are from the same OAUTH2 app that is responsible for the authentication in Coder
- this OAUTH2 app is related to another account than the one i'm trying to log into

**Comment by kylecarbs** [comment]
Hmm, I'm not sure what would be causing the redirect back to `/workspaces`. Could you try opening your network panel and checking if any HTTP requests are failing? Something odd must be going on here.

**Comment by barthofu** [comment]
No requests failing, and no 302 either, really weird...

![image](https://user-images.githubusercontent.com/66025667/207832695-3004acf0-0c4b-4430-9a28-178bb463dfc0.png)

**Comment by barthofu** [comment]
Ok i found it, i missread the doc and was using the same OAUTH2 application as the one to log into coder, but the git auth needs another callback (`<domain>/gitauth/primary-github/callback` in my case)
