### ISSUE TITLE
Get a non-json response error when running create template

### ISSUE THREAD

**Issue by dunefro** [coder/coder#5429]
We installed the helm chart of the coder oss in a separate namespace `coder` and gave the `CODER_ACCESS_URL=workspaces.example.com`. 
We are able to login and everything works fine till the time we start to initialize template and create it. It starts to give non-json response.
```
$ coder templates create
> Create and upload "~/workspace/coder/kubernetes"? (yes/no) yes
✔ Queued [-4ms]
⧗  Running 
unexpected non-JSON response "".              
Run 'coder templates create --help' for usage.
```
Coder version
```
$ coder version
Coder v0.13.2+88bb901 Mon Dec 12 11:26:49 UTC 2022
https://github.com/coder/coder/commit/88bb901283055397c9d04d27ad51ce3d4417d645
```
`workspaces.example.com` is a real domain and we were able to access it by creating a mapping of [emissary-ingress](https://www.getambassador.io/products/api-gateway)

When running the same server with `CODER_ACCESS_URL=""` it generates a URL in the logs of the containers and running the `coder templates create` command with that is successful.

What is the cause of this behaviour. `workspaces.example.com` in our case is a public endpoint and is accessible publicly.

**Comment by MRtecno98** [comment]
Same issue here with a system service install

**Comment by Advency** [comment]
I was able to solve the problem on my side,

Coder was obviously using sockets that I had not declared in the nginx reverse proxy.

I had to add these 3 lines in the vhost conf: 

```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
```

This gives this in the vhost : 

```
    location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
        proxy_pass http://localhost:3000;
    }
```

Once this modification is done, it is finally possible to create templates.

Hopefully this helps

+ It would be nice if in the documentation is added how to configure a nginx reverse proxy for this project in case we use a custom domain :)

Translated with www.DeepL.com/Translator (free version)

**Comment by smolinari** [comment]
@Advency - Thanks for noting your solution. I can confirm the fix is the Coder CLI needing websocket connectivity. I think, at a minimum, the fact the CLI requires websocket connectivity should be noted in the docs for the k8s/helm chart install.

I don't think Nginx settings should be necessarily added in the docs, as not everyone uses Nginx for reverse proxying. But, for sure, something should be noted. 

Scott

**Comment by dunefro** [comment]
@smolinari Yes true, I have a use case with [emissary ingress](https://www.getambassador.io/products/api-gateway) mapping.

**Comment by smolinari** [comment]
@dunefro - Hey. Me too! :) 

If you also want the SSH tunneling to work, you'll also need to add `-derp` in the `allow-upgrade` section of your mapping. I just learned that too the other day. No docs on that anywhere. Just good calculated guess by the Coder team, I'd say. :P

Scott

**Comment by bpmct** [comment]
@johnstcn would your work in #5854 detect this?

**Comment by johnstcn** [comment]
> @johnstcn would your work in #5854 detect this?

Nice find @bpmct -- I think this is exactly the sort of thing we'd want to surface there.

**Comment by kylecarbs** [comment]
Let's track this in #5854!
