### ISSUE TITLE
coder init script fails when `/tmp` is mounted with `noexec`

### ISSUE THREAD

**Issue by RickyGrassmuck** [coder/coder#5430]
Just ran into this today, if the VM is configured to mount `/tmp` with the noexec option, the default coder init script will fail as this is where it is hard coded to download the coder agent to.

```
BINARY_DIR=$(mktemp -d -t coder.XXXXXX)
cd "$BINARY_DIR"

...

curl -fsSL --compressed "${BINARY_URL}" -o "${BINARY_NAME}" && break
```

I think adding a way to modify that `$BINARY_DIR` variable would be a good way to make the script more flexible. Something like:
```
if [ -z $BINARY_DIR ]; then 
    BINARY_DIR=$(mktemp -d -t coder.XXXXXX)
fi
```

That would allow users like myself to simply set an environment variable before running the script to work around the `/tmp` limitation.

In the meantime, the easiest workaround is to just use a custom script that uses a different `BINARY_DIR` in place of the one provided by the `coder_agent` resource.

**Comment by bpmct** [comment]
Related #3340

**Comment by kylecarbs** [comment]
We now accept a `BINARY_DIR` environment variable that can be set before the agent is ran, which should solve for this edge-case!
