### ISSUE TITLE
Show button to fix coder agent is outdated

### ISSUE THREAD

**Issue by mafredri** [coder/coder#5432]
It would be nice to have a button to "resolve" this:

<img width="376" alt="Screenshot 2022-12-15 at 14 43 29" src="https://user-images.githubusercontent.com/147409/207862394-1332b07a-3490-46a0-88cf-76eeeeab9f4a.png">

Two options:
1. Restart workspace
2. Send message to agent to update itself (requires work on backend/agent)

Option 1) seems reasonable now, 2) future enhancement.

Ref: #5393

**Comment by BrunoQuaresma** [comment]
Is guaranteed that restarting the workspace will update the agent?

**Comment by mafredri** [comment]
@BrunoQuaresma Assuming the default bootstrap process is used, yes, we always download the agent from the server. It's of course possible for someone write their own in which case there is no guarantee.

In the future we may build in update functionality into the agent which should hopefully be able to guarantee an update (without explicitly restarting the workspace).
