### ISSUE TITLE
Coder server update experience is bad; "We're having difficulty..." / "Something went wrong."

### ISSUE THREAD

**Issue by mafredri** [coder/coder#5433]
When the Coder server is updated, the web UI (at least workspace page) behaves poorly. Error messages keep flickering back and forth. The minimum fix would be to only show them once, the better fix would be to check `/api/v2/healthz` and have only one error showing "unable to communicate with coder server".

https://user-images.githubusercontent.com/147409/207863699-bb211604-b18a-4a0c-b51b-e3fda43ca393.mov

The ultimate (future) fix would be for coder server to send a message to all clients that it's being shut down, all clients can then surface this information.

**Comment by BrunoQuaresma** [comment]
Closing this in favor of https://github.com/coder/coder/issues/5822
