### ISSUE TITLE
On hover dialogue flickers when moving mouse onto dialogue content (example: coder agent is outdated)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#5434]
The dialogue flickers when moving the mouse, this is likely due to a one-pixel offset or something, resulting in temporarily exiting the zone. (Browser: Safari.)

https://user-images.githubusercontent.com/147409/207864101-70d95e21-01b3-4b2e-8acc-55e674039499.mov

**Comment by BrunoQuaresma** [comment]
This is another Material UI issue. They don't support popover on hovers pretty well. This is kinda related discussion to https://github.com/coder/coder/issues/5765#issuecomment-1412679048.

**Comment by bpmct** [comment]
🤷🏼
