### ISSUE TITLE
dev ux: add CODER_DASHBOARD_URL so coder backend can proxy frontend requests to a dev server

### ISSUE THREAD

**Issue by deansheather** [coder/coder#5456]
The current method of having the dev server redirect to the backend works in most cases, but does not work with tunnels (as coder will serve it's compiled-in frontend instead) so testing anything to do with apps becomes difficult.

Add `CODER_DASHBOARD_URL` and hidden flag `--dashboard-url` which can be set to a URL like `http://localhost:8080/` to proxy all frontend requests to that URL instead of serving from the embedded dashboard files.

Any requests to coder agent binaries should still be served by the embedded files.

**Comment by bpmct** [comment]
Would this flag be hidden or something we expect users to use as well?

**Comment by bpmct** [comment]
Gonna close to reduce issues in the tracker. Feel free to re-open / add a PR if this is interesting to you
