### ISSUE TITLE
Custom branding

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5465]
Let's allow Coder admins to replace the "Coder" logo with their own branding to make it feel more user-friendly as an internal dev platform.

<img width="300" alt="Screen Shot 2022-12-19 at 6 14 24 AM" src="https://user-images.githubusercontent.com/22407953/208445389-ae33f17e-b624-450e-8388-d01e93b455e0.png">

<img width="1375" alt="Screen Shot 2022-12-19 at 6 15 54 AM" src="https://user-images.githubusercontent.com/22407953/208445753-5b2a62cf-3362-4f8b-b96c-a162c009fd9f.png">

This should also include custom support links in the footer: 

<img width="624" alt="Screen Shot 2022-12-19 at 6 16 43 AM" src="https://user-images.githubusercontent.com/22407953/208445876-295c464a-1051-4b77-8a38-45967fd48503.png">

**Comment by mattlqx** [comment]
I just came here to create this! 😁 You read my mind exactly.
