### ISSUE TITLE
Do you plan to support VMware vSphere ESXi?

### ISSUE THREAD

**Issue by MuNeNICK** [coder/coder#5471]
I am using on-premise VMware vSphere ESXi.
So I found out that TerraForm can support ESXi with a provider called [terraform-provider-esxi](https://github.com/josenk/terraform-provider-esxi).

Is there any plan to support ESXi with Coder?

Best regards.

**Comment by kylecarbs** [comment]
I believe it should already work. Have you tried it?

**Comment by MuNeNICK** [comment]
Sorry. I did not know.
I will give it a try, but do you plan to create a TerraForm-ESXi template?

> I believe it should already work. Have you tried it?

**Comment by kylecarbs** [comment]
We don't have plans to create one, but if you make one feel free to put it in a repo. We'll link to it!

**Comment by MuNeNICK** [comment]
Understood. Thank you for your kind attention.

**Comment by kylecarbs** [comment]
Of course! Thanks for using Coder :)
