### ISSUE TITLE
Is there anyway to upload template offline?

### ISSUE THREAD

**Issue by Rainlv** [coder/coder#5474]
Because of some network reasons, when use `coder templates create`, it always goes broken，logs are shown blow.

![image](https://user-images.githubusercontent.com/61002778/208700534-8a7e7ae1-d883-4f01-8ced-d6ad558ff9dc.png)
![image](https://user-images.githubusercontent.com/61002778/208701110-9b0e4f1f-5ca3-4bf4-b462-86def84b2102.png)

Could I pre-download the dependencies and save to cache folder to avoid download from `github.com`

**Comment by kylecarbs** [comment]
You can indeed! Check out our docs:

https://coder.com/docs/coder-oss/latest/install/offline

If you have any questions, just give me a shout!
