### ISSUE TITLE
Difficult to organize and display many templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5492]
If a developer is in a large organization and has access to 25+ templates, it would be difficult to find which templates are relevant to them in a long list.

Just because a developer has access to 25+ templates doesn't necessarily mean they should all be shown to them, as it's possible only 1-2 relevant to their use case. I have also wanted to hide/group templates from other users when I'm still iterating on them.

Some ideas:
- Folders for templates (Retool does this)
- Some way to see templates for groups (e.g. "frontend")
- Tags for templates and admins can set default filter in `/templates` (`group:any(mine), os:fullstack`)

**Comment by bpmct** [comment]
One advantage to going with folders is an entire folder can have RBAC (e.g. `frontend group can read all templates in this folder, ops group can write`)

**Comment by ammario** [comment]
Is this still important after we support multiple organizations?

**Comment by matifali** [comment]
We may solve this with a concept of projects under each organization. Each project will have independent templates/workspaces.

**Comment by matifali** [comment]
Also related to #7318 in case when  user has too many templates.

**Comment by ammario** [comment]
I think we should solve https://github.com/coder/coder/issues/7318 before we add pinning, folders or tags. Sorting and searching across our core views is table-stakes.

**Comment by stirby** [comment]
This is not at the scale of our other roadmap items, so I am removing the label.
