### ISSUE TITLE
bug: banner is not shown when a user logs in without a manual page refresh

### ISSUE THREAD

**Issue by matifali** [coder/coder#5504]
The service banner is not shown to a member when they log in. It appears after a manual page refresh.

@BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
Thanks for letting us know @matifali

**Comment by BrunoQuaresma** [comment]
It is working for me on [Coder v0.13.6-devel+856f0ab6](https://github.com/coder/coder/commit/856f0ab6f5a3c8650181a6c066356d7b452b0f40). Please let me know if it still an issue for you.

**Comment by matifali** [comment]
This works but does not display without a manual refresh after the login. Could you check the screen recording?

https://user-images.githubusercontent.com/10648092/210436330-b1f8682b-42a4-4615-bd87-7a873d0f538f.mov

**Comment by BrunoQuaresma** [comment]
@matifali thanks for sharing the screen recording.

**Comment by matifali** [comment]
Yes, they are the same.
