### ISSUE TITLE
service banner is removed after coder upgrade

### ISSUE THREAD

**Issue by matifali** [coder/coder#5511]
cc: @BrunoQuaresma

**Comment by matifali** [comment]
It is available on the machine I used initially to set up the banner. It is stored in the browser cache.
But on a different device, When I log in with an owner account, I do not see this enabled, and the service banner field is empty. 
It's strange.

**Comment by BrunoQuaresma** [comment]
🤔 we will take a look at that. thx for reporting

**Comment by matifali** [comment]
A refresh of the page seems to bring it back.

**Comment by BrunoQuaresma** [comment]
@matifali good to know. I tried to reproduce this a few times using the latest version **Coder v0.13.6-devel+856f0ab6** but with no success. I'm closing this for now, but let me know if it is still an issue for you.
