### ISSUE TITLE
scaletest: How can I avoid API rate limits?

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5531]
I'm attempting to run a scale test on my Kubernetes cluster with the following command:

```sh
coder scaletest create-workspaces \
    --count 1000 \
    --template "kubernetes" \
    --concurrency 0 \
    --cleanup-concurrency 0 \
    --parameter "home_disk_size=10" \
    --run-command "sleep 2 && echo hello"
```

However, I'm only able to create roughly ~60 concurrent workspaces as I run into a rate limit error:

```sh
== FAIL: workspacebuild/794

        Error: login as new user: POST http://coder.example.com/api/v2/users/login: unexpected status code 429: You've been rate limited for sending more than 60 requests in 1m0s.
```

I have also set `CODER_API_RATE_LIMIT=-1` for my `coder server`, but saw that some routes are still rate limited, regardless of this value:

>       --api-rate-limit int                           Maximum number of requests per minute
>                                                      allowed to the API per user, or per IP
>                                                      address for unauthenticated users.
>                                                      Negative values mean no rate limit. Some
>                                                      API endpoints are always rate limited
>                                                      regardless of this value to prevent
>                                                      denial-of-service attacks.
>                                                      Consumes $CODER_API_RATE_LIMIT

**Comment by Emyrk** [comment]
Two values are hard coded and not respecting the input value.

https://github.com/coder/coder/blob/79f45ede05939a73437007fd5292c897784607d4/coderd/coderd.go#L336-L336
https://github.com/coder/coder/blob/79f45ede05939a73437007fd5292c897784607d4/coderd/coderd.go#L427-L427

**Comment by bpmct** [comment]
I think that is the desired behavior, based on the help text:

> Some API endpoints are always rate limited regardless of this value to prevent denial-of-service attacks.

I wish the scale test was able to bypass it somehow

**Comment by Emyrk** [comment]
Yea, I would argue all rate limits are to prevent DOS attacks though.

**Comment by ammario** [comment]
There's a `BypassRatelimitHeader` option that I added for this very purpose. Have you tried it?

**Comment by deansheather** [comment]
@ammario the load tests use that header but only when making requests as site owner, this is the login endpoint to login to a new user so it has a ratelimit of it's own. I think we just need to make that ratelimit configurable also :/
