### ISSUE TITLE
Add options for JSON logging and stackdriver logging

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5533]
When running Coder on Kubernetes, it seems like all logs appear as an error. This is what it looks like in Google Cloud:

<img width="1158" alt="Screen Shot 2023-01-02 at 6 14 56 AM" src="https://user-images.githubusercontent.com/22407953/210243122-e8abf6f0-d1f8-4486-b1a9-8cf760d6d2f5.png">

```sh
$ cat /root/coder-config/standard.coder.log
Coder v0.11.0+df89e2c - Remote development on your infrastucture
```

**Comment by kylecarbs** [comment]
This is done!
