### ISSUE TITLE
License expired with no notification in the UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5537]
Version: [`v0.13.6+cfd02d9`](https://github.com/coder/coder/commit/cfd02d959c141c68f8c96d05467b96428291d31b)

As an owner or non-owner user, I should be notified in the UI that a license has expired.

In this case, the license expired 2022-12-31

The only indication is that the enterprise features are gone e.g., Audit.

![image](https://user-images.githubusercontent.com/2022166/210250465-0c7e371a-c488-4b42-96ef-f871f116b106.png)

**Comment by matifali** [comment]
May be show a warning ⚠️ that license will expire in X days when it's less than 7 days. It should be only for owners when they login. Can also be show on deployment page.
