### ISSUE TITLE
Temporary sharing for workspaces (or just apps)

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5560]
Could we let users (temporarily) share a workspace with another user, or just a specific app, like the Terminal or a web server?

**Comment by kylecarbs** [comment]
Terminal sharing is *really* easy for us because we already allow for reconnecting TTYs. You can do this with admin users right now (albeit a bit buggy because of resizing).

**Comment by sharkymark** [comment]
I've heard prospect requests from this, and some paying customers.

**Comment by MrPeacockNLB** [comment]
This is a valid usecase to share port-forwarding and it is needed for some of our development workflows. E.g. you want to implement a new feature which affects microservice a and b (maybe client / server). Then you checkout to separate workspaces (2 different developers) for this new feature. One for client and server on the ohter hand. But how to test the api when you can not connect to a port-forwarding?

For us is this a showstopper. So there has to be a way to configure access port-forwarding for a workspace. So one can choose between private, internal and public. Where private access is only allowed to you. Internal allows access if you are logged in and public is accesseble by everyone. A preference should configured via terraform code. This should be changeable in the UI.

**Comment by sharkymark** [comment]
Another prospect requesting IDE sharing as well
