### ISSUE TITLE
`CODER_WILDCARD_ACCESS_URL` is not set when `coder.ingress.wildcardHost` is set

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#5563]
If you set `coder.ingress.wildcardHost=...` in the Helm chart, I would expect that the Coder pod will have the corresponding configuration for `CODER_WILDCARD_ACCESS_URL`, but it doesn't get that.

**Comment by bpmct** [comment]
Hmm that's a good point - I can see why it'd make sense for our helm chart to set these for both the ingress host -> access URL and the wildcard host -> wildcard access URL.

Overridable by manually setting them in `env` of course.

**Comment by NiklasRosenstein** [comment]
Yeah, I just realized I configured `CODER_ACCESS_URL` manually as well, so I was able to proceed easily by also manually setting `CODER_WILDCARD_ACCESS_URL`. :) Still, I think this would be quite simple to add in the Helm chart.

**Comment by bpmct** [comment]
@deansheather - do you think we should do this?

**Comment by deansheather** [comment]
We should add a comment to the Helm chart above the ingress value saying that you also need to set the env var. This was done intentionally, as changes in the `coder.ingress` values "section" shouldn't make changes to resources other than the ingress object.
