### ISSUE TITLE
First time setup 30 day trial checkbox doesn't work until refresh

### ISSUE THREAD

**Issue by deansheather** [coder/coder#5568]
During the first time setup flow in the dashboard (not the CLI), if the user checks the "30 day trial" checkbox and finishes setup they will be taken to the workspaces page but none of the enterprise features will be available until they refresh the page.

I'm unsure if this is because the license is added asynchronously on the backend, or if the frontend doesn't refresh entitlements after doing first time setup.

**Comment by jsjoeio** [comment]
Throwing out ideas: we could display a banner that says "Refresh to activate your license" or something.

**Comment by kylecarbs** [comment]
I think the entitlements endpoint needs to refresh.
