### ISSUE TITLE
scheduling: ephemeral workspaces that auto-delete

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5572]
When I'm trying to reproduce an issue on a specific environment or just tinkering, I'd love to be able to create an ephemeral workspace that can just clean itself up after I'm done using it.

This also has some cool use cases for Coder in CI/CD where a Coder preview workspace can be created when a PR is created.
 
<img width="1107" alt="Screen Shot 2023-01-04 at 6 51 05 AM" src="https://user-images.githubusercontent.com/22407953/210582263-4650a5f2-72f8-4823-9a1a-9f3de7df123e.png">

**Comment by mattlqx** [comment]
I'd like a lifecycle control for this based on inactivity. e.g. If someone hasn't used the workspace for 30 days, delete it.

There's a finer point also of can an admin enforce these settings.
