### ISSUE TITLE
Rich parameters

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5574]
This is a continuation of #3906. Rich parameters will make the following possible:

- Users can edit parameters on existing workspaces
- Users are prompted when they update their template and new parameters are added
- Template authors can mark some parameters as `immutable`, meaning they cannot be changed after initially set. For example: changing the `region` of a workspace may destroy the volume!
- Icons, friendly names, and descriptions for parameters
- Pre-plan validation on parameters (e.g. validation errors on the input) 

![193463761-102541de-05b5-4704-a751-e9b4654e3b30](https://user-images.githubusercontent.com/22407953/210621385-4fcf2220-6cd8-4cd7-8e26-c4284c63b0dc.png)

Eventually, rich parameters may allow us to add:
- Special validation/data sources (e.g. "all AWS regions," "all images in registry.mycompany.com")

---

Call notes:
- First, we'll introduce the new parameter data source 
- Extend CLI to also use rich parameters
- Convert examples to the new format

Next:
- Add migration docs for migrating from variables
- Consider deprecating parameters

Vision:
- Terraform `variables` are template-wide only. In the "template settings" UI, you can edit "variables"

**Comment by mtojek** [comment]
I'm going with this issue. First: `we'll introduce the new parameter data source`

**Comment by ammario** [comment]
We could warn users in the dashboard and CLI when they interact with a workspace or template configured with the old parameters.

**Comment by mtojek** [comment]
> We could warn users in the dashboard and CLI when they interact with a workspace or template configured with the old parameters.

Good call, might be worth discussing.

Currently, the idea is to pull parameters from the previous workspace build, unless the user provided new parameter values via CLI/site. Parameters can also have the `default_value` property, so altogether we should achieve a really smooth experience - if everything matches, don't need to notify or warn the user. Added template parameters should be resolved to their defaults. 

If we need transparency, I can park this for development.

**Comment by ammario** [comment]
Okay. That makes a lot of sense. So we can force that users use the new parameters in order to update their workspace configuration.

**Comment by mtojek** [comment]
From Ammar on zoom:

>Would be cool if we could show immutable parameters as a section and then mutable as the second section. It creates a clear line for “think hard about these parameters”. It will also lead to more consistency between the edit and create forms.

**Comment by ammario** [comment]
From Zoom today:

@deansheather:

> can we make the edit workspace form look the same as the create workspace form?
like in v1
and just disable the fields that can't change
also the mutable/immutable headers seem odd to me, it'd be nice if users could define their own sections and we just relied on the yellow text that says it can't be changed instead

@ammario

> What’s friendlier language we can use instead of “mutable” and “immutable” in the form? I also second Dean’s point. It would be cool if we could reuse the form and show the immutable params as disabled forms so the user is still aware of them. I also think it would be nice if we had a box around the immutable parameters like: https://i.imgur.com/tQ0TOhf.png.

@kylecarbs
> i feel like immutable is pretty friendly as code

@ammario 
> As a section title it’s probably fine since it maps to configuration. We should at least explain what it means in a description / subtitle in the form.

**Comment by mtojek** [comment]
@bpmct Do you think that we can convert the ideas above and these [leftovers](https://github.com/coder/coder/issues/5574#issuecomment-1384340385) into smaller issues in favor of this meta-issue?

**Comment by mtojek** [comment]
As agreed during the Weekly call, I converted this issue into smaller [action items](https://github.com/coder/coder/issues/5574#issuecomment-1384340385), hence closing this one.
