### ISSUE TITLE
CA bundles to mount inside the coder agent pod

### ISSUE THREAD

**Issue by DEV-ICON** [coder/coder#5584]
I am using the following official documentation https://coder.com/docs/coder-oss/latest/install/kubernetes, and have a internal CA cert.

if coder.env.CODER_ACCESS_URL is set with a "https" instead of "http"

the coder agent pod will have these errors:
+ curl -fsSL --compressed https://<domain>/bin/coder-linux-amd64 -o coder
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

Is there anyway for me to mount CA bundles into coder agent pod before it trys to run the curl command?

**Comment by kylecarbs** [comment]
That would be the image that you have for your workspace.

I assume you're using a Docker container, so you'll need to add additional certificates to it, then use it in Kubernetes.

```Dockerfile
FROM <image>

ADD cert.crt /usr/local/share/ca-certificates/foo.crt
```
See: https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image

**Comment by DEV-ICON** [comment]
Is there a template sample where I can build the container with the certs without pushing the image to a repository?

**Comment by DEV-ICON** [comment]
> That would be the image that you have for your workspace.
> 
> I assume you're using a Docker container, so you'll need to add additional certificates to it, then use it in Kubernetes.
> 
> ```dockerfile
> FROM <image>
> 
> ADD cert.crt /usr/local/share/ca-certificates/foo.crt
> ```
> 
> See: https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image

I have built an custom docker image with the ca cert in a private container repository. however I am not sure how to reference this image from the .tf file?

**Comment by kylecarbs** [comment]
In the Docker template, there should be an `image` property on the `docker_container` Terraform resource!

**Comment by DEV-ICON** [comment]
> In the Docker template, there should be an `image` property on the `docker_container` Terraform resource!

Let me clarify, I am runing coder OSS in kubernetes not coder OSS on docker. Do I still need to custom docker image?

I am using the kubernetes template. Is there any way I can point this image to a custom container registry image?
`     container {
      name    = "dev"
      image   = "codercom/enterprise-base:ubuntu"
      command = ["sh", "-c", coder_agent.main.init_script]
      security_context {
        run_as_user = "1000"
      }`

**Comment by bpmct** [comment]
Yep - you can modify your template to use any image/registry!
