### ISSUE TITLE
Templates cannot load

### ISSUE THREAD

**Issue by tuyendd25** [coder/coder#5587]
Version: [`v0.13.6+cfd02d9`](https://github.com/coder/coder/commit/cfd02d959c141c68f8c96d05467b96428291d31b)

Templates cannot load on web console and when I create a template but appear error that below
![Screenshot from 2023-01-05 09-44-35](https://user-images.githubusercontent.com/37723019/210689685-a4a558bf-6640-4976-8733-dc323300aae6.png)

/home/coder/coder/templates/docker $ coder templates create my-template --yes
⧗  Queued 
unexpected non-JSON response "text/plain; charset=utf-8". 
Run 'coder templates create --help' for usage.

**Comment by bpmct** [comment]
Hi @tuyendd25. Sorry we missed this issue! This is fixed in the latest version of Coder
