### ISSUE TITLE
Service Banner doesn't show up until you refresh

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5593]
Bug: Until you do your first refresh, the service banner doesn't show up.

Repro:

-Open up an incognito browser and log into a Coder cluster that has a service banner enabled
-The banner won't appear, and if you click around, it won't load
-Do a cmd-R, and the banner will pop up.

**Comment by ammario** [comment]
Hmm, I can't replicate this on master.

**Comment by matifali** [comment]
It's a duplicate of #5511 and #5504. 
And most probably fixed by #5594
