### ISSUE TITLE
Expose user's SSH key as a Terraform data source

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5599]
Coder generates a SSH key per-user. It'd be neat if we exposed the public key as a Coder data source, so it can be used for other things (e.g. auth for other providers). e.g. `data.coder_workspace.owner_ssh_key`

**Comment by ammario** [comment]
The current thinking is we're removing SSH keys from the product as its less secure than our Git over HTTP integration. Right now, the same SSH key is used by all workspaces.

**Comment by bpmct** [comment]
We've talked to a number of users who are using SSH keys as an authentication mechanism for other resources.

While user-level secrets or the user's OIDC token may be the preferred route, we should still look into exposing both the public and private keys for template authors. 

As a workaround, a template author can access the SSH key in the startup script with the following command:

```sh
curl --request GET \
  --url "${CODER_AGENT_URL}api/v2/workspaceagents/me/gitsshkey" \
  --header "Coder-Session-Token: $CODER_AGENT_TOKEN"
```

Thanks @phorcys420 for sharing this!!

**Comment by phorcys420** [comment]
> The current thinking is we're removing SSH keys from the product as its less secure than our Git over HTTP integration. Right now, the same SSH key is used by all workspaces. 

I think they should be kept around for self-hosted git instances that maybe don't support that?
