### ISSUE TITLE
Support passing deployment URL to `coder_login` command via `CODER_URL` environment variable?

### ISSUE THREAD

**Issue by kconley-sq** [coder/coder#5612]
The help output for `coder login` suggests that it will consume the `CODER_URL` environment variable:

```
      --url string            URL to a deployment.
                              Consumes $CODER_URL
```

but in practice it seems to ignore it and instead requires you to provide the URL as a positional argument:

```
❯ CODER_URL="my.coder.deployment.com" coder login
accepts 1 arg(s), received 0
Run 'coder login --help' for usage.
```

Would it be possible to support this invocation as well? I'm thinking it would allow us to provide a thin wrapper for the `coder` CLI for our users that sets the `CODER_URL` environment variable to our deployment URL so that our users wouldn't have to provide it themselves when running `coder login`.

**Comment by coadler** [comment]
Ah, `--url` is a global flag but we're not utilizing it here. Definitely an easy fix!
