### ISSUE TITLE
Clarify in the OIDC Documentation that there is a user limit when using the OSS version

### ISSUE THREAD

**Issue by RickyGrassmuck** [coder/coder#5616]
Unfortunately, the [documentation for OIDC/Github authentication](https://coder.com/docs/coder-oss/latest/admin/auth) is presented as an OSS feature (no `Enterprise` label or notes) and fails to disclose that there is actually a 20 user limit that requires an enterprise license to remove.

The only mention of this limitation appears to be in the [`enterprise`](https://coder.com/docs/coder-oss/latest/enterprise) page in the feature comparison table where it's shown as being an OSS feature with an asterisk/footnote mentioning the user limit.

This seems a bit deceptive since it can lead to situations where users start adopting the OSS product and either 
1. Learn about the user limitation after on-boarding their 21st user or 
2. Happen to stumble across the separate enterprise docs page and notice the footnote about the limitations.

In our case, this has actually resulted in multiple weeks of potentially wasted time getting fairly deep into creating a production-ready deployment setup for our developers to start testing since we now have to go back and evaluate enterprise licensing costs.

For what it's worth, I think all the other enterprise features offered make sense requiring an enterprise license when an organization is at a point where they are ready to start making use of those features.

**Comment by bpmct** [comment]
Hey @RickyGrassmuck - I can totally see how is unclear. I've submitted a PR that should clear this up, and we are thinking of ways we can expose this limitation in the product.

We will certainly not "lock" a deployment that goes over this limit, but there will be a warning that tells the admin that it has been exceeded.

**Comment by bpmct** [comment]
Hi @RickyGrassmuck - wanted to apologize again for the confusion around this. We've decided to make OIDC a free feature for unlimited users.

**Comment by RickyGrassmuck** [comment]
@bpmct That is awesome news, Thank you for the update!
