### ISSUE TITLE
Edit workspace variables

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#5621]
Is it possible make Workspace variables editable? This would allow users for example to increase their CPU/Memory requested without recreating the Workspace and loosing their home volume.

**Comment by BrunoQuaresma** [comment]
Rn, when a user creates a template, if there are any missing variables the UI and CLI ask the user to enter them. Is your question related to something different?

**Comment by matifali** [comment]
I think he is suggesting to increase the RAM and CPU quota for a workspace without deleting and creating a new one.

**Comment by NiklasRosenstein** [comment]
Yes, that's it. I want to edit the variables of an _existing_ workspace.

**Comment by bpmct** [comment]
Hey @NiklasRosenstein - we're building rich parameters (#5574) for this reason. Before we make things editable from the UI, we want to make it so some admins can mark some as `immutable` as changing them after creation may result in data loss.

In the meantime, you can update them via the CLI, but be careful not to change a `region` or any other variable that may recreate your volume.

```sh
coder update --always-prompt <workspace-name>
```

**Comment by mtojek** [comment]
Close in favor of https://github.com/coder/coder/issues/5980
