### ISSUE TITLE
Is `coder_parameter` supposed to work?

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#5622]
When I use the `coder_parameter` resource in my template, it doesn't seem to have any effect. The resource has a few features that appear very useful but as far as I can tell they cannot be replicated the same way using a Terraform `variable`, such as regex validation, min/max and giving drop-down values icons and display names different from the actual value.

**Comment by kylecarbs** [comment]
@NiklasRosenstein this was added and never completed (by myself unfortunately). I suppose we should probably remove it from the Terraform provider for now, but it will be added in February!

Track #5574
