### ISSUE TITLE
bug: docs | v2 top-left drop-down is not correct

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5623]
If you visit the docs and click the drop-down in the top left, you see this:

![image](https://user-images.githubusercontent.com/2022166/211325865-36c4fdcf-8183-47f2-9e40-7d3bc853afc8.png)
![image](https://user-images.githubusercontent.com/2022166/211325901-a10457a2-2f07-4200-9bf0-32c8b6b2df18.png)

**Comment by kylecarbs** [comment]
This is fixed now!
