### ISSUE TITLE
Manually send workspace activity

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5629]
I believe the Coder agent sends workspace activity through the [agent stats](https://coder.com/docs/coder-oss/latest/api/agents#submit-workspace-agent-stats) endpoint. If Coder is used in third-party automation, it may be beneficial to register workspace activity via another endpoint when external "actions" occur that involve a workspace ID

<img width="888" alt="Screen Shot 2023-01-09 at 12 41 41 PM" src="https://user-images.githubusercontent.com/22407953/211383499-b5720ba7-ad5b-4b5e-a0fd-ac98dbce0a83.png">

**Comment by kylecarbs** [comment]
This should be possible via our API right now.

https://coder.com/docs/v2/latest/api/agents#submit-workspace-agent-stats

As long as `connection_count` is greater than zero, we consider the workspace active. Closing for now, but if we need docs or something additional @bpmct let me know.

**Comment by bpmct** [comment]
Related https://github.com/coder/coder/issues/8064
