### ISSUE TITLE
When changing a password, it silently trims space characters from inside on every value change trigger

### ISSUE THREAD

**Issue by rac2030** [coder/coder#5638]
If a user is changing his password (SettingsSecurityForm.tsx) and enters a space, it will not be in the value but no error message is displayed that it's an invalid character.

This can result in a user setting a password with spaces in it like "some random sentence" which will result that he actually changed his password to "somerandomsentence" without seeing it. As he can enter that phase with spaces in the confirmation as well and they will match, he will only figure out that he can not login anymore with that password after it has been updated.

If however he copy pastes into the password field, a space character is possible so I'm not sure if the bug is not showing an error message or trimming on every change of the field.

**Comment by rac2030** [comment]
From my understanding of a quick look at the code without cloning or building it looks to me that the problem is with the on Change listener that trims which is added to the password field on the settings page:
onChange={onChangeTrimmed(form)}

https://github.com/coder/coder/blob/85c679597c57577b05da4d579603c213647e3819/site/src/components/SettingsSecurityForm/SettingsSecurityForm.tsx#L89

**Comment by rac2030** [comment]
Created a PR removing the OnChange listener as after further inspection of the code base it seems that other forms in coder that set the user password all have no OnChange listener set for the password fields

**Comment by ghuntley** [comment]
Thanks for raising the pull-request and the detailed bug report.
