### ISSUE TITLE
Unable to SSH with coder

### ISSUE THREAD

**Issue by rahulgangwarmsn** [coder/coder#5639]
I've deployed coder on a kubernetes cluster. I can login to it and see workspace created and running but ssh doesn;t work. when i try to run coder config-ssh I get below error: 

"fetch workspace configs failed: json: cannot unmarshal object into Go value of type []codersdk.Workspace
Run 'coder config-ssh --help' for usage."

**Comment by kylecarbs** [comment]
Are you deployed with v2, and is your client<->server running the same version? Odd error.

**Comment by rahulgangwarmsn** [comment]
wow! thats pretty fast response. Thank you!!! Yes its V2 on server... client cli gives below when i type coder version

"Coder v0.12.5+165b6fb Mon Nov  7 23:35:01 UTC 2022
https://github.com/coder/coder/commit/165b6fbc6a23fd5f58ed459ea50f42e642c2f696"

**Comment by rahulgangwarmsn** [comment]
I think its version mismatch. The bottom of UI dashboard says this for coder version.[Coder v0.12.9+2b6c229](https://github.com/coder/coder/commit/2b6c229e4e2e94776500fe366b538afb6c24c199)

**Comment by kylecarbs** [comment]
Ahh, yes! Update your CLI to match.

**Comment by kylecarbs** [comment]
Closing for now @rahulgangwarmsn. Let me know if that doesn't fix it!

**Comment by rahulgangwarmsn** [comment]
The issue related to this error was resolved after matching client and server version. In my case I needed v 0.12.9 n client so I ran command "curl -fsSL https://coder.com/install.sh | sh -s -- --version 0.12.9"
