### ISSUE TITLE
Upgrading deployment makes JetBrains Gateway plug-in say deployment may not be compatible

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5646]
Version: [`v0.14.0+70d71bc`](https://github.com/coder/coder/commit/70d71bc7bc7f734158eb0f944027aecf3451a88c)

![image](https://user-images.githubusercontent.com/2022166/211448063-aaa188e6-4c3b-429c-8105-0260b10f6b3e.png)

How do I resolve this? I thought the plug-in downloads the CLI from the deployment so they are always in sync?

**Comment by bpmct** [comment]
This was fixed, we suppressed the version checks for now
