### ISSUE TITLE
Bottom workspace UI showed spinner, at stopped and started state

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5651]
Version: [`v0.14.1+52d7dfa`](https://github.com/coder/coder/commit/52d7dfa25309e1e141529f6ea3d1b0cba774c183)

This only happens to some of my workspaces. Control plane is on Kubernetes.

screenshot at stopped state
<img width="920" alt="image" src="https://user-images.githubusercontent.com/2022166/211549700-113b1937-408f-400e-9be4-bcf83c017657.png">

screenshot at running state
<img width="971" alt="image" src="https://user-images.githubusercontent.com/2022166/211549776-c301007a-ee48-4ffc-b6b4-62a3606141dc.png">

screenshot at stopped state again and after a hard chrome browser refresh (without the refresh the spinner was still there)
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/2022166/211549941-effe0c97-bdca-4925-b841-7856672c6345.png">

Another example: Java, JetBrains workspace
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/2022166/211550596-fcfc6f07-8fb4-4537-984a-716e4e2e30b2.png">
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/2022166/211550652-a6432cf1-ee9a-4fb5-a8ca-c0a9cd7666dd.png">

But if while creating the workspace, I do a hard Chrome refresh, it shows correctly.
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/2022166/211550758-2bb04496-ec22-4add-932c-84471f55a2a5.png">

**Comment by kylecarbs** [comment]
This is due to a lack of workspace builds in the last 30 days. Should definitely be fixed!
