### ISSUE TITLE
Unable to SSH into workspace

### ISSUE THREAD

**Issue by rahulgangwarmsn** [coder/coder#5657]
Scenario:
- Installed coder server on K8. Successfully able to create new workspace based on kubernetes template (I can see new pod spinning up as well)
- Configured SSH successfully
- When I try to SSH using "ssh coder.kubernetes-workspace" the CLI gets stuck trying to connect after giving message "Don't panic, your workspace is booting up"
- On the UI dashboard too, when I access workspace, I don't see typical options/buttons for SSH ash shown in below screenshot
![image](https://user-images.githubusercontent.com/111990865/211613497-76e0e1c5-3cf9-4652-aa1e-4629366997c6.png)

**Comment by rahulgangwarmsn** [comment]
Thanks @kylecarbs  when I exec into the pod I can curl using the IP address but not the DNS name. I guess if I modify pod's hosts file it should work... (but will be lost everytime its restarted). So either I configure Access URL of coder deployment to use IP address or I configure clusterwide DNS/enterprise dns. Is that correct?

**Comment by kylecarbs** [comment]
Correct!

**Comment by kylecarbs** [comment]
Closing this for now. Ping me if you have any issues!

**Comment by rahulgangwarmsn** [comment]
@kylecarbs I changed hosts of workspace pod and it can reach the access url however I'm still facing issue with SSH. 
I noticed that workspace pod can reach access url using http (not https). Is TLS a must? My deployment setting looks like this:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/111990865/211643194-a0da990b-e8ec-4705-ae02-39cdc9594ff8.png">

**Comment by rahulgangwarmsn** [comment]
Update: @kylecarbs This is not resolved. The workspace pods can reach coder access URL. I've updated coder to configure coder access URL to use http now. However SSH is still stuck at original issue that I explained.

**Comment by kylecarbs** [comment]
Interesting... are you using a load balancer?

**Comment by rahulgangwarmsn** [comment]
yes nginx ingress controller

**Comment by rahulgangwarmsn** [comment]
@kylecarbs it worked! I had to recreate the workspace. after i updated coder, existing workspace might not have picked up effect so I thought of recreating new workspace and it worked. Thank you for all your help!
