### ISSUE TITLE
Error: Post "https://192.168.64.1:443/api/v1/namespaces/coder-workspace/persistentvolumeclaims": Forbidden

### ISSUE THREAD

**Issue by roshvin** [coder/coder#5667]
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraform 1.3.4
coder_agent.main: Plan to create
coder_app.code-server: Plan to create
kubernetes_persistent_volume_claim.home: Plan to create
kubernetes_pod.main[0]: Plan to create
coder_agent.main: Creating...
coder_agent.main: Creation complete after 0s [id=3931cc2d-d1b9-4aa1-a4fc-8eb946a159ad]
coder_app.code-server: Creating...
coder_app.code-server: Creation complete after 0s [id=0f275b9d-bca9-4552-9af5-40ead0a79d78]
kubernetes_persistent_volume_claim.home: Creating...
kubernetes_persistent_volume_claim.home: Creation errored after 0s
Error: Post "https://192.168.64.1:443/api/v1/namespaces/coder-workspace/persistentvolumeclaims": Forbidden

**Comment by kylecarbs** [comment]
It seems like your Kubernetes service account doesn't have permissions to create PVCs.

**Comment by roshvin** [comment]
Hi @kylecarbs  thanks , its resolved adding the URL in no_proxy list.
