### ISSUE TITLE
Pre-fill template parameters with URL query params 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5671]
This is nice for internal wikis and partially contributes to #3981. This can pre-fill repo URLs, disk sizes, images, etc.

![Screen Shot 2023-01-11 at 8 57 08 AM](https://user-images.githubusercontent.com/22407953/211845069-c167ffd2-3948-40e6-b725-e4d1646c598c.png)

**Comment by BrunoQuaresma** [comment]
Instead of region, do you think `var.region` would be acceptable? Asking because we can prepopulate the`name` field and have a `var.name` as well.

**Comment by bpmct** [comment]
Makes sense to me. However, these will not be prefixed with `var.` once #5574 is completed. Instead of being

```hcl
variable "region" {
### ...
}
```

It will be

```hcl
data "coder_parameter" "region" {
  # ...
}
```

In the Terraform template. 🤔 

Maybe we just support `param.region` once the time comes?
