### ISSUE TITLE
Support terraform resources outside the given template directory

### ISSUE THREAD

**Issue by denbeigh2000** [coder/coder#5677]
When creating a Coder template, I would like to reference local files outside the given template directory.

Context: I want to re-use common files/terraform modules between multiple templates in a repository. To do this right now, one needs to copy-paste common resources into each template's directory, which is inconvenient and increases the risk of introducing skew.

A practical example: These two templates are near-identical, yet it's not feasible to share common resources between then
 - https://github.com/denbeigh2000/coder-templates/blob/master/aws-spot-nixos/main.tf
 - https://github.com/denbeigh2000/coder-templates/blob/master/aws-nixos/main.tf

**Comment by denbeigh2000** [comment]
that'd work if i were willing to split the module out into another repository and import it, but it leaves a few shortcomings:
 - i can't include a terraform module from `../` between these templates
 - i can't make use of common files (e.g., scripts, configuration files, etc) that may be used elsewhere in a shared monorepo

**Comment by kylecarbs** [comment]
Ahh, I see. I wonder if it'd be best to upload the entire directory as a template, and be able to specify a subdirectory to execute out of?

**Comment by denbeigh2000** [comment]
that's totally reasonable for the linked case, but there are some valid use cases where this doesn't make sense

e.g., `$WORK` uses a large, shared monorepo, and there are often resources in far-flung relative directories (e.g., `../../../../resources/some-other-team/some-other-product/resource.yml`) that we want to include - an approach like this would require committing nearly the entire repository as a template.

would it be possible to resolve `file()` resources and include them in the uploaded tarball, so that they can be used in the template?

**Comment by ammario** [comment]
What if the tarring process traversed symlinks?

**Comment by denbeigh2000** [comment]
I'd have no issue with making a few relative symlinks to address this :+1:

**Comment by ammario** [comment]
After #5720 is in you'll be able to do:

```
tar -cvh . | coder templates update -d - <name>
```

**Comment by denbeigh2000** [comment]
Thank you very, very much :pray:

**Comment by ofey404** [comment]
I like this feature, thanks @denbeigh2000

**Comment by ammario** [comment]
> > What if the tarring process traversed symlinks?
> 
> As per my understanding, doing a tar of directory to push template is the only option to follow symlinks as `coder templates push` does not follow symlinks, correct?

That's correct. In general we don't want to go feature-to-feature with `tar`, so we promote using that for all advanced directory serialization.
