### ISSUE TITLE
Web-Terminal shows menu bar

### ISSUE THREAD

**Issue by ntimo** [coder/coder#5698]
# Description
the web-terminal shows a header bar, which was not there before and I think this is a bug.

![image](https://user-images.githubusercontent.com/6145026/212183573-07243252-0215-4431-a747-6285d27103c6.png)

**Comment by kylecarbs** [comment]
@BrunoQuaresma!

**Comment by kylecarbs** [comment]
Hmm, that _shouldn't_ be there now, but I'll check.

**Comment by kylecarbs** [comment]
@matifali you're right. We should remove it!

**Comment by kylecarbs** [comment]
cc @Kira-Pilot could you tackle this pls?

**Comment by BrunoQuaresma** [comment]
I'm working on a PR to remove it right now.

**Comment by BrunoQuaresma** [comment]
Fixed.
