### ISSUE TITLE
Open a new window with Open VS Code Desktop

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5703]
The awesome new feature, Open VS Code Desktop, opens the existing local VS Code window so when I close it, I have to re-open my local 'workspace' again.

I suggest the default behavior be to open a new VS Code window locally.

**Comment by jsjoeio** [comment]
I believe the URI that handles the opening in VS Code is here:

https://github.com/coder/coder/blob/bbb208e29c269615a37fd6456dc3c243d8fa8771/site/src/components/VSCodeDesktopButton/VSCodeDesktopButton.tsx#L26-L36

So we'd have to see what params `vscode://` and hope that it supports something like `newWindow=true` or something.

**Comment by jsjoeio** [comment]
So our custom URI handler is here: 

https://github.com/coder/vscode-coder/blob/ec4aa92aa7717740a5a1a66d4350236c9bcf913e/src/extension.ts#L27-L51

**Comment by jsjoeio** [comment]
I believe actual code to open VS Code window would be here: https://github.com/coder/vscode-coder/blob/ec4aa92aa7717740a5a1a66d4350236c9bcf913e/src/commands.ts#L188-L194

**Comment by jsjoeio** [comment]
Ah maybe this is it? https://github.com/coder/vscode-coder/blob/ec4aa92aa7717740a5a1a66d4350236c9bcf913e/src/commands.ts#L200 

see `reuseWindow: true`. We'd want to set that to `false`. 

So seems like it's possible if I'm following the logic correctly.
