### ISSUE TITLE
Issue Creating Kubernetes Workspace (kubernetes_persistent_volume_claim)

### ISSUE THREAD

**Issue by FaresHerhar** [coder/coder#5712]
Hello,

I am having template creation issue (Workspace on Kubernetes).

> System Enviroment

* Airgap Enviroment.

* Kubernetes 22.0 (Installed with Ubuntu VMs).

* Dynamique Provisioning (NFS type).

* Coder sycessfully installed, with a custom Airgap build (Dockerfile below).

> Description

I managed to install Coder as these pages explains, [Kubernetes](https://coder.com/docs/coder-oss/latest/install/kubernetes), [Offline deployments](https://coder.com/docs/coder-oss/latest/install/offline), [External database](https://coder.com/docs/coder-oss/latest/install/database).

Coder is well installed, created the admin account, terraform well installed, and able to connect to the Terraform Mirror Registry (connected to the coder pod, and created a `main.tf`, ran `terraform init`, and sucssefully downloaded the providers). When I try to create the the *Kubernetes Workspace* template, it timesout, without returning any errors, and without any workspace created. So I logged to coder with the coder CLI, tried to create the template manually, and it always fails at the line 88 of the [Kubernetes Worspkace Template](https://github.com/coder/coder/blob/main/examples/templates/kubernetes/main.tf#L88). Noting that I want to create the worskapce on the same cluster as coder is installed, therefore I pass the following values, for the variables in the previous file, coder-workspace (already created), false (since on the same cluster).

```shell
Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

coder_agent.main: Creating...
coder_agent.main: Creation complete after 0s [id=821b1fd7-665f-45c4-b7fa-427d9ec732e5]
coder_app.code-server: Creating...
coder_app.code-server: Creation complete after 0s [id=bb4f59eb-1b24-4822-b33d-ccc59fade413]
kubernetes_persistent_volume_claim.home: Creating...
╷
│ Error: an error on the server ("<HTML><HEAD><TITLE>501 Not Implemented</TITLE></HEAD>\n<BODY><H1>501 Not Implemented</H1>\nThe requested method is not recognized\n</BODY></HTML>") has prevented the request from succeeding (post persistentvolumeclaims)
│
│   with kubernetes_persistent_volume_claim.home,
│   on main.tf line 88, in resource "kubernetes_persistent_volume_claim" "home":
│   88: resource "kubernetes_persistent_volume_claim" "home" {
│
```

Any Help please !

> Coder Dockerfile

```shell
## Use official coder/coder image as base image.
FROM ARTIFACTORY_URL/coder/coder:v0.13.6

## Define Build arguments.
ARG ARTIFACTORY_USERNAME
ARG ARTIFACTORY_PASSWORD

# Run following commands as 'root'.
USER root

## Add SSL Certificatess.
XXXXX

## Install APK repositories.
RUN rm /etc/apk/repositories && \
    echo ARTIFACTORY_URL >> /etc/apk/repositories && \
    echo ARTIFACTORY_URL >> /etc/apk/repositories
RUN apk update && \
    apk add curl unzip

## Create directory for the Terraform CLI (and assets).
RUN mkdir -p /opt/terraform

# In order to run Coder airgapped or within private networks,
# Terraform has to be bundled into the image in PATH or /opt.
# See https://github.com/coder/coder/blob/main/provisioner/terraform/install.go#L23-L24
# for supported Terraform versions.
ARG TERRAFORM_VERSION=1.3.0
RUN curl -u ${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD} "ARTIFACTORY_URL/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" --output terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && mv terraform /opt/terraform \
    && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
ENV PATH=/opt/terraform:${PATH}

# Additionally, a Terraform mirror needs to be configured
# to download the Terraform providers used in Coder templates.
# Use a network mirror.
ADD ./network-mirror-example.tfrc /opt/terraform/config.tfrc

## Run following commands as 'coder' .
USER coder
WORKDIR /home/coder

## Use the tfrc file to inform.
ENV TF_CLI_CONFIG_FILE=/opt/terraform/config.tfrc
```

> test/maint.tf

```tf
terraform {
  required_providers {
    coder = {
      source  = "coder/coder"
      version = "0.6.6"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.12.1"
    }
    docker = {
      source = "kreuzwerker/docker"
      version = "~> 2.22"
    }
  }
}
```

> config.tfrc

```tf
# terraformrc file. Provider it with env var. Sample : TF_CLI_CONFIG_FILE=./config/terraform_artifactory.tfrc
provider_installation {
  direct {
    exclude = ["registry.terraform.io/*/*"]
  }
  network_mirror {
    url = "ARTIFACTORY_URL/api/terraform/XXXXXXXX/providers/"
  }
}

credentials "ARTIFACTORY_URL" {
  token = "XXXXXXXXXXXXXXXXXX"
}
```

**Comment by kylecarbs** [comment]
For some reason creating the Kubernetes persistent volume is failing... maybe because your service account doesn't have permissions? 

For your version of Kubernetes, here is the web request it's trying to perform:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#create-persistentvolumeclaim-v1-core

Maybe try doing that with cURL from your local machine to the Kubernetes cluster with the service account.

**Comment by FaresHerhar** [comment]
I've the right permissions for creating PVC.
Coder is installed in the `coder` namespace, while the workspaces in the `coder-namespaces` namespace.

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
  creationTimestamp: "2023-01-11T15:39:05Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: coder-workspace-perms
  namespace: coder
  resourceVersion: "7370743"
  uid: 5e64db9e-b33c-46e2-9bd8-3b896c0337b9
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
  creationTimestamp: "2023-01-11T15:39:05Z"
  labels:
    app.kubernetes.io/instance: coder
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coder
    app.kubernetes.io/version: 0.13.6
    helm.sh/chart: coder-0.13.6
  name: coder
  namespace: coder
  resourceVersion: "7370744"
  uid: a9b565f3-09d7-481a-bdd4-1c10280be135
secrets:
- name: coder-token-dlhml
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
  creationTimestamp: "2023-01-11T15:39:05Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: coder
  namespace: coder
  resourceVersion: "7370745"
  uid: b4e1f56c-f2c0-4bd9-afca-08087f722147
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coder-workspace-perms
subjects:
- kind: ServiceAccount
  name: coder
```

**Comment by FaresHerhar** [comment]
## Solved !

Problem solved buy setting the `use_kubeconfig = true`, and creating a `~/.kube/config` file, with the access to the cluster (with the right context, permissions, roles, serviceAccount....).

Despite having coder and the workspaces created at the same cluster, namespace, and having the right permissions on that namespace (serviceAccount, role), the the API still fires an error (permissions). It could be a misconfiguration from my part, but this is the solution that worked for me.

> Note !

I already had a `~/.kube/config` file, with other clusters configured into it, and I had some issues at first, until I have put the target cluster's configuration at the top of the other clusters.

It seems that it takes the configuration of the first cluster (context) it finds, so better put your target cluster's configuration on the top (in case having multiple clusters configs).
