### ISSUE TITLE
"Download Coder CLI" option

### ISSUE THREAD

**Issue by normana10** [coder/coder#5722]
I work with Coder in an offline environment, so when I noticed that the Coder agent downloads the CLI binary from https://<CODER_ACCESS_URL>/bin/coder-linux-amd64 I was _ecstatic_ because I didn't need to import that to my offline environment separately or jump through hoops to extract the binary out of the Docker image and then host it somewhere for new devs to download

Though my first thought was why this was never displayed anywhere in the UI?

I know there's a "Install Coder CLI" line when you click on "SSH" in a workspace, which directs you off to the internet (which I don't have offline)
![image](https://user-images.githubusercontent.com/10109659/212459479-0129d5aa-f1fc-4638-af7c-0abbd74d56ea.png)

Would there be any interest in replacing that line with or adding a line like "Download Coder CLI" which does a little browser user agent detection to figure out what platform (MacOS/Windows/Linux) we're on and then just downloads from https://<CODER_ACCESS_URL>/bin/

I can go implement the feature and put in a PR. I was just curious if there was any reason _not_ to depend on that `bin` path/directory existing or missing the binaries (but I assume they'll always be there considering the agent depends on them?)

Thanks!

**Comment by ammario** [comment]
You can reliably depend on the CLIs being available at those URLs. In fact, [our VS Code extension](https://github.com/coder/vscode-coder) does just that to work in offline environments and support forks.

**Comment by bpmct** [comment]
Related #5781
