### ISSUE TITLE
Safari: navbar spacing is incorrect

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#5737]
when using Coder `0.14.3` in Safari, the spacing between the various elements in the navigation bar is incorrect:

<img width="1177" alt="Screenshot 2023-01-16 at 5 52 26 PM" src="https://user-images.githubusercontent.com/9683576/212776775-aae0c121-2aa3-4150-b2bf-062c810aa7f1.png">

this is exacerbated when using a custom logo:

<img width="1438" alt="Screenshot 2023-01-16 at 5 53 20 PM" src="https://user-images.githubusercontent.com/9683576/212776848-70f3fff1-e2c2-423f-9b47-8c3cd38262cd.png">

**Comment by BrunoQuaresma** [comment]
@ericpaulsen can you please send me this logo?
