### ISSUE TITLE
Kubernetes Template: init_script == ""

### ISSUE THREAD

**Issue by FaresHerhar** [coder/coder#5744]
Hello,
Our team is interested in Coder as a backbone solution for our Development Envirement. We're installating coder on Kubernetes, as well as the workspaces, and we've faced some issues.

I managed to install Coder as these pages explains, [Kubernetes](https://coder.com/docs/coder-oss/latest/install/kubernetes), [Offline deployments](https://coder.com/docs/coder-oss/latest/install/offline), [External database](https://coder.com/docs/coder-oss/latest/install/database).

Coder is well installed, created the admin account, terraform well installed, and able to connect to the Terraform Mirror Registry. Currently I am installing the [Kubernetes Worspkace Template](https://github.com/coder/coder/blob/main/examples/templates/kubernetes), and the installtion went well, pvc, and pod created.

The issue, is with the pod, since it fails with an CrashLoopBackOff, with no logs, and nothing usefull in the description (the pod's status loops between Completed and CrashLoopBackOff). When reading the YAML file of the pod, I found that the commands script of the container is an empty String, therefore I checked the `agent.go` file from the [coder/coder Terraform provider](https://github.com/coder/terraform-provider-coder/blob/main/provider/agent.go#L177), and I see that the [`init_script`](https://github.com/coder/coder/blob/main/examples/templates/kubernetes/main.tf#L118) is not supposed to be an empty String.

So what is the problem please ?

> System Enviroment

* Airgap Enviroment.

* Kubernetes 22.0 (Installed with Ubuntu VMs).

* Dynamique Provisioning (NFS type).

* Coder sycessfully installed, with a custom Airgap build (Dockerfile below).

> YAML File

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations: {}
  creationTimestamp: "2023-01-17T13:33:36Z"
  labels: {}
  name: coder-default-default
  namespace: coder
  resourceVersion: "9817513"
  uid: e103789d-7e27-4773-a5c3-e304dfbadeb9
spec:
  automountServiceAccountToken: true
  containers:
  - command:
    - sh
    - -c
    - ""
    env:
    - name: CODER_AGENT_TOKEN
      value: 85080cb1-00e7-424a-b29c-f08747a24e2e
    image: ARTIFACORY_URL/codercom/enterprise-base:ubuntu
    imagePullPolicy: IfNotPresent
    name: dev
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/coder
      mountPropagation: None
      name: home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-pr4mk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: XXXXXXXXX
  nodeName: XXXXXXXXX
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsNonRoot: false
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  shareProcessNamespace: false
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: home
    persistentVolumeClaim:
      claimName: coder-default-default-home
  - name: kube-api-access-pr4mk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-01-17T13:33:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-01-17T13:44:48Z"
    message: 'containers with unready status: [dev]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-01-17T13:44:48Z"
    message: 'containers with unready status: [dev]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-01-17T13:33:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://52c38f59220d5dd56d71e95e957a058a55524b5de7283e664fd871400b29d067
    image: ARTIFACTORY_URL/codercom/enterprise-base:ubuntu
    imageID: docker-pullable://ARTIFACTORY_URL/codercom/enterprise-base@sha256:51516f8e991f18a8885a38de666030f2013fccff22d4d5ee9f2b11cf17e69008
    lastState:
      terminated:
        containerID: docker://52c38f59220d5dd56d71e95e957a058a55524b5de7283e664fd871400b29d067
        exitCode: 0
        finishedAt: "2023-01-17T13:44:47Z"
        reason: Completed
        startedAt: "2023-01-17T13:44:47Z"
    name: dev
    ready: false
    restartCount: 7
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=dev pod=coder-default-default_coder(e103789d-7e27-4773-a5c3-e304dfbadeb9)
        reason: CrashLoopBackOff
  hostIP: XXXXXXXXX
  phase: Running
  podIP: XXXXXXXX
  podIPs:
  - ip: XXXXXXXXXX
  qosClass: BestEffort
  startTime: "2023-01-17T13:33:36Z"
```

> Pod Status

![Capture](https://user-images.githubusercontent.com/102948288/212935962-11ff067b-7308-4d0f-a85e-2844f7d99bca.PNG)

> Pod Logs

![Capture PNG 1](https://user-images.githubusercontent.com/102948288/212935417-8ec04a54-4889-49d6-938f-d1c4caacb310.PNG)

> Pod Description

![Capture PNG 2](https://user-images.githubusercontent.com/102948288/212935481-4ebe0d16-f309-4b7f-850e-31b7d3add30c.PNG)

**Comment by kylecarbs** [comment]
@FaresHerhar sorry for the slow response here, I completely missed your issue!

Were you able to get this working?

**Comment by FaresHerhar** [comment]
> @FaresHerhar sorry for the slow response here, I completely missed your issue!
> 
> Were you able to get this working?

Aaaaah, it's okay.
I sorry as well, I forgot to close as well.

The problem was with the certificates, and since the `startup_script` exists with an error due the certificates issue, the `init_script` gets and empty string (I can see that <https://github.com/coder/terraform-provider-coder/blob/main/provider/agent.go#L192> `init_script`, depends on `startup_script`).

Thanks again.
