### ISSUE TITLE
Change agent startup script behavior from being never-ending to indicating the workspace is ready on end

### ISSUE THREAD

**Issue by mafredri** [coder/coder#5749]
A new requirement came up in relation to #2957. We need a way to discern between a workspace being ready and not. This is also relevant for [`vscode-coder`](https://github.com/coder/vscode-coder) where we might start a workspace for a user and want to wait for it to become ready.

This requirement has also come up in #5171.

After discussing with @kylecarbs potential implementation, we came up with the following proposal:

- [x] Introduce new property describing workspace agent state, `WorkspaceAgentLifecycle`: (`created`,) `starting`, `start_timeout`, `start_error`, `ready`, (`stopping`, `stop_timeout`, `stop_error`, `stopped`)
  https://github.com/coder/coder/pull/5785
	- This property describes the current state of the agent and is independent of status (which describes the connection status), it can be thought of as a lifecycle status / readyness status
	- And additional `created` state could be added to indicate an initial state of the agent, before it has reported it's initial state
	- Example usage of state:
		- If state is `starting`, keep users waiting e.g. during `ssh coder.workspace` (loading indicator)
		- If state is `start_timeout`, show users a warning
		- If startup script exits with non-zero status, the `start_error` state lets us direct users towards inspecting the startup log (#2957)
- [x] Introduce a new provider parameter `coder_agent.startup_script_timeout` with a default value (say 5min) (`shutdown_script_timeout` for #5171)
  https://github.com/coder/terraform-provider-coder/pull/84
	- This is a soft-timeout after which we _warn_
	- [x] Show warning in dashboard
	https://github.com/coder/coder/pull/5835
	https://github.com/coder/coder/pull/5850
	- [ ] Show warning in CLI, e.g. when SSH:ing into the workspace
	**NOTE:** Not applicable until **Final steps**
	Partially handled by: https://github.com/coder/coder/pull/5851
- [x] Introduce a new provider parameter `coder_agent.delay_login_until_ready`
	https://github.com/coder/terraform-provider-coder/pull/84
	- This will delay logins until agent is ready, will default to false and changed to true in a future release
	- [ ] Delay login in web Terminal
	- [x] Delay login in `coder ssh`
	https://github.com/coder/coder/pull/5851
	- [x] Delay login in `ssh` (`coder config-ssh`)
	https://github.com/coder/coder/pull/5851
	- [x] Add `--skip-delay-login-until-ready` flag
	https://github.com/coder/coder/pull/5851
- [x] Add example(s) with non-blocking startup scripts
  https://github.com/coder/coder/pull/5880
	- Consider `/etc/init.d/svc start`, `nohup /path/to/svc &`, "fake systemd", etc.
- [x] Add documentation for troubleshooting agent lifecycles
  https://github.com/coder/coder/pull/5877

**Final steps:**
- [ ] Create a breaking PR:
	- [ ] Revert https://github.com/coder/coder/pull/5850 to show agents with timed out startup scripts by default

We will focus on implementing the start-states first, stop will come later.

**Comment by bpmct** [comment]
> Introduce new WorkspaceAgentStatus: starting, start_timeout, started, (stopping, stop_timeout, stopped)

Will agents still have `connecting`, and `disconnected`?

> Allow waiting via CLI, e.g. coder ssh --wait-ready

Hmm, should this be the default?

**Comment by kylecarbs** [comment]
@bpmct 

> Hmm, perhaps the default behavior should wait until its ready?

This would break most existing deployments that fork off our templates. Since we launch code-server, it would never let anyone SSH in.

**Comment by mafredri** [comment]
> Will agents still have `connecting`, and `disconnected`?

At first I thought we would combine the status as one field. But on second thought, we should supports states like `disconnected` and `starting` (at which point `starting` might become `unknown`).

I think renaming the current `status` to `connection_status` would make a lot of sense.

The new functionality could be put under `status` (or something like `lifecycle_status` not to conflict).

> Hmm, perhaps the default behavior should wait until its ready?

I would prefer this as well, I was thinking about potential breakage for current users, which is why I proposed `--wait-ready`, but `--no-wait` is a valid option.

**Comment by kylecarbs** [comment]
@mafredri all this sounds good to me. 

I think we should add a `startup_script_allow_connect` or something (that's a bad name), and change our templates to use it so our users start too. Maybe in a few releases we make it the default to block.

**Comment by mtojek** [comment]
> Introduce new WorkspaceAgentStatus: starting, start_timeout, started, (stopping, stop_timeout, stopped)

This seems to be a complex change to introduce, affecting many places. Did you have a chance to analyze the task complexity? I'm curious how safe it is to implement without getting you lost for a month...

**Comment by mafredri** [comment]
@mtojek That part is still a WIP but I should have it finished by today or tomorrow. Opened up a (wip) PR if you want to have a look: https://github.com/coder/coder/pull/5785
