### ISSUE TITLE
Metric: Time spent in IDE

### ISSUE THREAD

**Issue by presleyp** [coder/coder#5752]
Some users will want to see how long users spend in different IDEs.

By user
Filterable by type: tunnel, coder_app (code-server), coder_app (PyCharm), terminal

**Comment by pranavmishra90** [comment]
Here's a possible workflow for you (requiring an external service):

[WakaTime](https://wakatime.com/dashboard) can track IDE and terminal time spent. I keep my `~/.wakatime.cfg`, containing my API key, in my dotfiles setup. This allows me to deploy a container with the WakaTime VSCode extension and already have an API key ready to go.
