### ISSUE TITLE
Select on new workspace doesn't behave like a normal browser select box

### ISSUE THREAD

**Issue by mafredri** [coder/coder#5765]
As a heavy keyboard user, I'm used to hopping around via tab and also selecting input values via keyboard.

For the select box, I'd expect to be able to hit a key like `e` to switch the selection to `eu-helsinki`:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/147409/213148578-b670f661-3030-4929-b77a-00cc28e30356.png">

But nothing happens.

Also, if I press space to open the select, I'd expect pressing space again would select the currently highlighted value, but it does not. (Enter does work, but in browser native select so does space.)

<img width="673" alt="image" src="https://user-images.githubusercontent.com/147409/213148755-ee219bbc-adcb-41c3-aebe-ebf12112fe95.png">

**Comment by BrunoQuaresma** [comment]
It is a limitation of Material UI 😢 unfortunately we also use an outdated version of it. Wondering if would worth fix it by creating a wrapper on top of the material UI select or just using another library with primitive components for that.
