### ISSUE TITLE
tokens: Add "message" field to show how a token was created

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5777]
`Created from CLI`, `Created from REST API` or

```sh
coder tokens create -m "For GitHub Actions"
```

**Comment by johnstcn** [comment]
Should we default to something like 'Created by ${USER}@${HOST} using CLI' if no message is specified?

**Comment by bpmct** [comment]
Yeah, that was my thinking

**Comment by bpmct** [comment]
closing as duplicate of #6219
