### ISSUE TITLE
Self-host the install script & packages for easy "network-gapped" installs + use the proper version

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5781]
We could provide a `install.sh` in the [/bin](https://dev.coder.com/bin/) directory of a Coder install. Then, instead of using the publicly-hosted install script, the CLI can refer to the deployment's bin folder:

```diff
➜  ~ coder ls
version mismatch: client v0.11.0+df89e2c, server v0.14.1+52d7dfa                                                          
- download the server version with: 'curl -L https://coder.com/install.sh | sh -s -- --version 0.14.1'
+ download the server version with: 'curl -L https://coder.mycompany.com/bin/install.sh | sh -s -- --version 0.14.1'
```

This means we would have to also self-host minimal versions of the `.deb, .rpm, .exe` installers/packages. We can also consider adding a static `index.html` in the `/bin` folder with user-friendly download links for each OS. Or a "download CLI" page in the dashboard 🤷🏼

**Comment by jaulz** [comment]
@bpmct this would actually still be a nice feature so we could download the client with the proper version from the actual host in scenarios where we don't have user interaction (e.g. CI actions) and thus cannot quickly run an update.

**Comment by matifali** [comment]
How to actually get the new versions on the air-gapped network?

**Comment by matifali** [comment]
> Or a "download CLI" page in the dashboard 🤷🏼
Something similar was done but not merged. Check #5738

**Comment by bdsoha** [comment]
> How to actually get the new versions on the air-gapped network?

The assets are available as part of every release, they can be bundled alongside the control-plane image.

**Comment by matifali** [comment]
@bpmct, what is the use case for providing the installers? If a server is already up, the clients only need slim binaries, which we already provide and can be easily upgraded with something like #2744.

I am unsure about the significance of adding installers to the binaries. Would you like to use the installers to deploy further Coder deployments?

**Comment by bpmct** [comment]
> If a server is already up, the clients only need slim binaries, which we already provide and can be easily upgraded with something like https://github.com/coder/coder/issues/2744.

This would be an easy way for devs to download the CLI on their desktop workstations, but I suppose they only need the sli binaries too :)
