### ISSUE TITLE
Add grace period for multiple replicas to support rollout upgrades

### ISSUE THREAD

**Issue by deansheather** [coder/coder#5787]
Currently, during an upgrade rollout in the Helm chart with a replica count of 1, Kubernetes will create a second pod and signal the first one to turn off. This results in a license breach banner complaining about having multiple replicas without a license.

We should update the breach code for this check to allow a single extra replica for up to 30 minutes, which will give plenty of time for a rollout to complete and avoid showing the scary banner.

**Comment by bpmct** [comment]
@deansheather what level of bug would you say this is?

![Screenshot 2023-02-15 at 4 41 02 PM](https://user-images.githubusercontent.com/22407953/219204612-1094fb7b-2b2d-4041-9a12-9c8dee0c3363.png)

**Comment by deansheather** [comment]
I would say p2
