### ISSUE TITLE
Login form customization

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#5796]
Rather than being presented with a user/password form that noone will use in an implementation that is governed entirely by SSO, we would like to disable presentation of those fields and only allow login with the OIDC button. Similarly, allowing customization of the button would be good as well as not all of our users would recognize "OIDC", but can instantly identify "Okta".

**Comment by kylecarbs** [comment]
A community member actually built this, we just have to finalize it!

#5101

**Comment by mattlqx** [comment]
Nice! Sorry I didn't check through the PRs.

**Comment by kylecarbs** [comment]
No problem at all. It's good to have an issue associated with it anyways, and your issue made me review the PR, so kudos!
