### ISSUE TITLE
License issue banner shows in web Terminal and hampers scrolling

### ISSUE THREAD

**Issue by mafredri** [coder/coder#5803]
The license issue banner shows in the web Terminal:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/147409/213572460-473e308b-d318-46ee-bfcb-e3312d635f58.png">

I'm not saying it can't show up there, but currently it hampers proper scrolling (essentially two scoll bars when you have scrollback) and leads to both text jumping around while using it as well as visual glitches:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/147409/213572400-296d160f-c122-465b-9d3e-6b51503a8207.png">

Suggestions (one of):

- Remove it from web terminal
- Make it play nice in web terminal
- Show it for a little while and then dismiss it

**Comment by kylecarbs** [comment]
I think we remove it from the web terminal. This feels jank!

**Comment by BrunoQuaresma** [comment]
@mafredri this should be fixed. Can you confirm if this issue is still happening pls?

**Comment by mafredri** [comment]
I can confirm, it's fixed for me too. Nice work @BrunoQuaresma!
