### ISSUE TITLE
Change template list page to include a create button per row

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5804]
My gut is telling me that there are too many steps to create a workspace and we should cut them down. 

**Current workflow to create a new workspace:**
Workspaces --> Template List --> Template --> Create Workspace

**My proposal is to try and create one of the following:**

(1) Workspaces --> Template List --> Create Workspace
(2) Workspaces --> Create Workspace

The navigation tools are all in different locations (top left, middle, and upper right) and in different formats (text, item in list, and button). To me, I feel like i'm jumping all over the place. I think we should try and simplify this. Here are some ideas to get the brain going:

(1) In the template list, have a specific icon/link for creating a workspace straight from there
(2) Modify the create workspace page to have a Template selector, then you could go straight from Workspaces --> Create Workspace instead

**Comment by BrunoQuaresma** [comment]
@kylecarbs I think having 1 and 2 are valid. In the past, we had option 2, but we removed it because we wanted folks to go to the template page first. Are you ok if we implement both?

**Comment by kylecarbs** [comment]
I think we implement #1 first, and wait until we have the command pallette for #2.
