### ISSUE TITLE
Side Nav Support

### ISSUE THREAD

**Issue by misskniss** [coder/coder#582]
As a customer I want a way to easily navigate the various pages in the UI (that are not my preferences and account settings) so I can find things in a consistent way. 

-----

- [x] https://github.com/coder/coder/issues/703
- [x] https://github.com/coder/coder/issues/704
- [x] https://github.com/coder/coder/issues/705

-----

## Discussion Notes

- add a consistent place to open the side nav in the header
Example: 
![Side Nav Icon.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/14bb4038-b9b5-4772-81cd-d373c628d16b)
- list all the pages that the UI supports for that user's role and permissions
Example: 
![Side Nav List.png](https://images.zenhubusercontent.com/588b7bd751aa2c305772f431/64e14a47-0089-4ea6-8e6e-8426817fb1ac)

See list of available V1 pages here:
https://www.notion.so/coderhq/V1-List-of-Pages-Sections-Functionality-4839e9baacd94df4aac22a68d77afe44#9b4598f331f8416b98a620a9bd35d006

**Comment by ketang** [comment]
Our navigation as it is now is sufficient.
