### ISSUE TITLE
Workspace page flashes errors when API key expires

### ISSUE THREAD

**Issue by coadler** [coder/coder#5822]
https://user-images.githubusercontent.com/6332295/214111403-bddbf3ac-1c71-41fd-891f-5a4ecc647f41.mov

![image](https://user-images.githubusercontent.com/6332295/214111559-306da965-6b05-43ab-8e83-18d6412b0cbf.png)

**Comment by smolinari** [comment]
@BrunoQuaresma - I'm commenting here, so you don't need to worry about informing me when this issue gets fixed. :grin: 

Scott
