### ISSUE TITLE
Consistent and guarded search bars

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#5829]
# Consistent and guarded search bars

Our search bars are inconsistent, and silence errors. The valid parameters are hidden, and hard to find. 

![Screenshot from 2023-01-23 16-32-00](https://user-images.githubusercontent.com/5446298/214164874-f164b64b-c211-4c2a-ac85-1d2f99f791e9.png)

## Issues to solve

- [x] Garbage input is ignored. It does not tell the user the input is garbage, making small typos hard to identify:
  - `stauts:running` is a typo of `status` and applies no filter.
- [x] Enums are checked, but if the string is not supported, the enum filter is not used.
- [ ] All options are hidden, so knowing what params are supported is hard to find.
- [ ] Some options match partial text, others strictly match. This is inconsistent, and not described anywhere. Maybe we should support `name=alice` or `name~=alice`. All `name:alice` would have some default?
- [ ] Some options are lists, some are not.

# Buckets

- Filter by single option in list of options. Eg `status`, must only select 1 status.
- Partial string match. Eg name of a workspace/user
- Matching a list of options. Eg owner by user A and user B

## Additional ideas

- Deployment wide default filters
- User saved filters

---

I am interested in implementing the backend requirements for this. Would love help on how to design the UI to solve all the issues.

**Comment by BrunoQuaresma** [comment]
This is probably fixed by the latest filtering redesign. @Emyrk could you please check if there is something missing from your list? Closing the issue for now feel free to reopen in case it is still an issue.

**Comment by Emyrk** [comment]
Let's close this. The new features you added brings us to this vision. We can open more specific issues for more specific requests in the future.
