### ISSUE TITLE
Failed to check for license. If your usage doesn't require admin permission, you can set `check_license` attribute to `false` to skip this check. 

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#5833]
*Disregard*

**Comment by NiklasRosenstein** [comment]
```
│ migrate up: up: no migration found for version 90: read down for version 90 .: file does not exist                                                                                                         ```

Seems like downgrading doesn't work :) Wish I had done a backup. We're not running a super important instance yet so tbh. I didn't bother with it yet, but we'll need to get into the habit of doing that.

**Comment by NiklasRosenstein** [comment]
Seems like that was an issue in my template configuration, sorry 🙃 The "failed to check for license" error made it seem to me like it was an issue with Coder, but I didn't pay enough attention to the rest of the error message which was actually coming from a Terraform provider.

**Comment by kylecarbs** [comment]
Happy you figured this out! If there's anything we can do to improve error messages so that it'd be easier for you to debug, we totally can.
