### ISSUE TITLE
Custom template version names are broken

### ISSUE THREAD

**Issue by fpoussin** [coder/coder#5839]
I'm trying to set custom version names for templates in our CI, but I can't make it work.
Using v0.15.1.

```
Validation failed.                                                            
- name: Validation failed for tag "template_name" with value: "ci_146_ed7719c"
```

To my understanding, the tag should be `template_version`, not `template_name`.
The `--name` argument is pretty misleading, maybe renaming it to `--version` or `--version-name` would help?
There's also no option to set the first version name of a template on creation.

This is the actual CI code:
```bash
TEMPLATE_VERSION="ci_${PIPELINE_NUM}_$(git rev-parse --short HEAD)"

echo "Using ${TEMPLATE_VERSION} as our release name"

for TEMPLATE_DIR in $(find * -type d)
do
  ## Only plan/push when changes detected or on master branch
  if git branch --show-current | grep -vq master \
  && git diff master --exit-code --name-status -- ${TEMPLATE_DIR}
  then
    echo "no changes detected in ${TEMPLATE_DIR}, skipping"
    continue
  fi

  TEMPLATE_NAME=${TEMPLATE_DIR}-${SUFFIX}

  echo "processing ${TEMPLATE_NAME}..."

  terraform fmt -check -recursive
  coder template plan .

  if [ "$PUSH" == "true" ]; then
    # Set Docker image to the one built in this branch/release
    echo "image: \"base-${SUFFIX}"\" | tee parameters.yml
    # Check if template exists
    if coder template list 2>&1 | grep -q ${TEMPLATE_NAME}
    then
      echo "template exists, updating"
      coder template push -y --parameter-file parameters.yml ${TEMPLATE_NAME} -d ${TEMPLATE_DIR} --name ${TEMPLATE_VERSION}
    else
      echo "template is new, creating"
      coder template create -y --parameter-file parameters.yml ${TEMPLATE_NAME} --directory ${TEMPLATE_DIR}
    fi
  fi
done
```

**Comment by kylecarbs** [comment]
Underscores are not permitted in our current naming regex. Try replacing those with hyphens and it should work!

The argument name is odd though, so we'll fix that.

**Comment by fpoussin** [comment]
The generated template versions are using underscores, so I assumed they would be fine.
I'll give that a try, thanks!

**Comment by kylecarbs** [comment]
Ahh, maybe it's my bad then... or an inconsistency on our part internally. If that doesn't work, I'll do a patch ASAP. Sorry about this confusion!

**Comment by fpoussin** [comment]
it broke:
`execute transaction: insert template version: pq: duplicate key value violates unique constraint "template_versions_template_id_name_key". 
`
This was a new template, then updated once with a unique version name.

**Comment by fpoussin** [comment]
I'm seeing the version in the web UI, but not as active version. (at the bottom of the template page)

**Comment by kylecarbs** [comment]
Seems like you are trying to override a version with the same name? Seems like we aren't checking for that, but the database is returning a conflict.

**Comment by fpoussin** [comment]
I'm definitely not trying to overwrite the version name, they are always unique.

**Comment by fpoussin** [comment]
Did you manage to reproduce the issue?

**Comment by akoenig** [comment]
Can confirm this with the current release `v0.19.2+7eb2c2f`, when pushing a new version via GitHub Actions. We're passing `git rev-parse --short HEAD` as the version / name and receive the following error as well:

```sh
execute transaction: insert template version: pq: duplicate key value violates unique constraint "template_versions_template_id_name_key". 
Run 'coder templates push --help' for usage. 
```

**Comment by arturo-skydio** [comment]
> Can confirm this with the current release `v0.19.2+7eb2c2f`, when pushing a new version via GitHub Actions. We're passing `git rev-parse --short HEAD` as the version / name and receive the following error as well:
> 
> ```shell
> execute transaction: insert template version: pq: duplicate key value violates unique constraint "template_versions_template_id_name_key". 
> Run 'coder templates push --help' for usage. 
> ```

this is happening in our environment as well, it doesn't accept underscores or dashes in the name and when just the short tag is used get the error but the version actually publishes and I can see it in the UI

**Comment by kylecarbs** [comment]
Seems like we have a constraint that limits by `template_id` and `name` to versions, so I'm not sure why this would be happening if you just have a single version...

**Comment by kconley-sq** [comment]
I think I may have run into an issue around this as well (Coder version `v0.22.2+25c1e45`). My `coder templates push ...` command failed with `Validation failed.` seemingly because the name had a trailing `-`. I replaced that trailing `-` with a `2` and then I was able to push the template successfully (no other changes were made to the template or the rest of its name). Is that thought to be a requirement that the last character of a workspace template names can't be `-`?

**Comment by matifali** [comment]
@fpoussin I agree with you, and I propose, we should have
```console
--id 		for the template unique identifier (We can add this flag to specify a template explicitly)
--name		for the template version name (also) unique (This is the current behavior)
--message	template version change messages (This is the current behavior)
```
All of them should be reflected in `coder templates create|push --id my-template --name PyTorch2p0 --message "Updated PyTorch to version 2.0"`
There is also `coder template edit` which can update metadata that is not bound to a specific version e.g. `--icon`, `--description`, `--display-name` etc.

**Comment by sreya** [comment]
Given the age of this issue I'm closing for now. Feel free to open another if this is still a headache you experience.
