### ISSUE TITLE
Rootless podman example

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5843]

**Comment by bpmct** [comment]
I've started here, but am running into permissions issues with my Ubuntu build: https://github.com/bpmct/coder-templates/tree/main/rootless-podman

**Comment by roshvin** [comment]
Hi , are you able to use the plugin install with storage class instead of local path.

**Comment by bpmct** [comment]
@roshvin - I'm not sure. You can look at the docs for smarter-device-manager here: https://gitlab.com/arm-research/smarter/smarter-device-manager

Coder doesn't require a specific storage class, but I'm not sure how smarter-device-manager works under the hood.

**Comment by bpmct** [comment]
Closing as completed by #6026
