### ISSUE TITLE
Disable password section in account settings for OIDC/Github users

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#5844]
There'a a section in the user profile for editing your password. If your user is of type OIDC/Github, you aren't allowed to change your password (it errors out). I think we should disable/remove this panel entirely if the users is of this type. 

As a side note, I couldn't find anything in the user account settings that said what type of user I am. Maybe while we are at it, we should add something to indicate user type.

**Comment by bpmct** [comment]
Closing as completed by #6193
