### ISSUE TITLE
intellij IDEhandshake fails

### ISSUE THREAD

**Issue by da00891219** [coder/coder#5848]
I am getting "Bad handshake" error for intelliJ IDE, which was installed using projector.

v0.13.1

values.yaml --> 

    # Networking Parameter
    - name: CODER_TAILSCALE
      value: "true"

![image](https://user-images.githubusercontent.com/112606830/214485819-dee04433-b7c1-46eb-a9f1-2cf982020d78.png)

**Comment by kylecarbs** [comment]
Can you show me the network tab? I need to ensure that JetBrains Projector is properly using a subpath, not `/`.

**Comment by da00891219** [comment]
![intellij-handshake-fail-issue-1](https://user-images.githubusercontent.com/112606830/215005462-9fa6dc28-83af-4ec7-8317-b3dc201966c0.PNG)

**Comment by da00891219** [comment]
Zeid AlSeryani responded me on the coder-v2 slack channel saying "intellij projector is no more supported instead we need to use  jetbrains gateway". Please provide me with a sample template to use jetbrains gateway.

**Comment by da00891219** [comment]
healthcheck fails

resource "coder_app" "code-server" {
  agent_id = coder_agent.coder.id
  slug          = "code-server"  
  display_name  = "VS Code"  
  icon     = "/icon/code.svg"
  url      = "http://localhost:13337"
  subdomain = false
  share     = "owner"

  healthcheck {
    url       = "http://localhost:13337/healthz"
    interval  = 3
    threshold = 10
  }
}

resource "coder_app" "eclipse" {
  agent_id      = coder_agent.coder.id
  slug          = "eclipse"  
  display_name  = "Eclipse"  
  icon          = "https://upload.wikimedia.org/wikipedia/commons/c/cf/Eclipse-SVG.svg"
  url           = "http://localhost:6081"
  subdomain = false
  share     = "owner"

  healthcheck {
    url       = "http://localhost:6081/healthz"
    interval  = 6
    threshold = 20
  } 
}

![image](https://user-images.githubusercontent.com/112606830/215939465-ff14b435-15ad-4857-86f2-c7d1fb8329c4.png)

**Comment by da00891219** [comment]
upgraded to v0.17.0 and fixed the issue
