### ISSUE TITLE
on DNS url IDE handshake fails

### ISSUE THREAD

**Issue by da00891219** [coder/coder#5849]
v0.13.1

unable to open code-server IDE hitting handshake fails

**Comment by kylecarbs** [comment]
Not exactly sure what this means. Could you provide more detail?

**Comment by da00891219** [comment]
- We implemented coder as helm chart deployment in Kubernetes (OKE Cluster in OCI)
- We had the public IP and ingress is configured and we access coder on DNS url (ex: coder.example.com)
- When we access coder URL on public IP, vscode IDE works, when we open coder using ingress DNS URL, vscode IDE fails with handshake error

![code-server-error-1](https://user-images.githubusercontent.com/112606830/215006360-6aa19341-59ae-4dc9-8af1-a1e5db2adb7b.PNG)
![code-server-error-2](https://user-images.githubusercontent.com/112606830/215006375-17327b6e-ff03-43f1-b45e-a4a15c5c61b9.PNG)
![code-server-error-3](https://user-images.githubusercontent.com/112606830/215006386-a0732506-b33b-4a84-9242-ab63ee87c55c.PNG)

values.yaml file
-----------------
  env:
    - name: CODER_ACCESS_URL
      value: "http://158.101.225.23"
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: db-url

    - name: CODER_TEMPLATE_AUTOIMPORT
      value: "kubernetes"

    - name: CODER_TAILSCALE
      value: "true"

**Comment by da00891219** [comment]
upgraded v0.17.0, which fixed the issue
