### ISSUE TITLE
DERP/websocket health checks on dashboard

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5854]
We should show a warning in the dashboard if the following is not enabled:

- Does reverse proxy/LoadBalancer support DERP?
- Does reverse proxy/LoadBalancer have websockets enabled?

Otherwise, users will see some funky issues with the dashboard & workspace connections and not know exactly how to troubleshoot?

**Comment by johnstcn** [comment]
For DERP, what sort of test can we perform to determine reachability?

For WebSockets, Coder could attempt to periodically connect to its own access URL and report if this fails.

**Comment by kylecarbs** [comment]
```
Connection: Upgrade
Upgrade: derp
```

**Comment by bpmct** [comment]
Let's do a non-dismissable banner at the top of the page, but prepare some generic way for collecting deployment checks so we can add a page in the feature. This is something we definitely plan to do, not only for "health checks" but to get a sense of whether an environment is prepared for Docker templates, for example.

I think we should also have a plan for false positives. If the checks fail, is there a guarantee that Coder is broken, or should we add some flag/"admin level" option to hide it?

Also, if the user is interfacing with Coder only via the CLI, do should they should also see an error?

**Comment by johnstcn** [comment]
> I think we should also have a plan for false positives. If the checks fail, is there a guarantee that Coder is broken, or should we add some flag/"admin level" option to hide it?

Yeah, false positives could get annoying pretty quickly. For simple things like checking the presence or absence of a HTTP header, this may be less of an issue. But for more complex checks, I could see us needing to have configurable failure thresholds where the check will only enter an error state if more than N consecutive checks fail.

> Also, if the user is interfacing with Coder only via the CLI, do should they should also see an error?

I don't see why not. We already show warnings for an outdated CLI.
