### ISSUE TITLE
Member role should not see the template version in the workspace UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5868]
Version: [`v0.15.2+c3731a1`](https://github.com/coder/coder/commit/c3731a1be0bdf3a8b2527186c32a04b44973fdfe)

If I am a `Member` role and click on the template version in the Workspace UI, I get a `404`

If members are now allowed to see templates (which I think they should not since they show infrastructure elements) then version should be hidden.

https://www.loom.com/share/e8b99c7887e54371a27b0e49070767b7

**Comment by Emyrk** [comment]
This is because `Files` are currently owned by a user, and the template version page requires READ on the `File`.

To fix this
- Files must be scoped to an org.
- Org members must be able to read files in their org.

@bpmct Is this ok? Should all users be able to read the actual terraform files of a template version?

**Comment by bpmct** [comment]
Will get back to you on this! I'm honestly not sure what the best solution is here, so I'll bring it up in the roadmap sync.

**Comment by Emyrk** [comment]
I have a proposal: https://github.com/coder/coder/issues/6775

**Comment by matifali** [comment]
Still there
![image](https://user-images.githubusercontent.com/10648092/235006333-aa020654-b58a-4eaa-b4e8-e37c999d2c03.png)

**Comment by bpmct** [comment]
@kylecarbs and I had a chat and decided it is fine for users to view template files. These should always be considered non secret.

**Comment by bpmct** [comment]
> To fix this
> 
> Files must be scoped to an org.
> Org members must be able to read files in their org.


Yep!

**Comment by Emyrk** [comment]
@bpmct No, scoping files to an org I think just has issues with how we relate objects. I think my proposal makes the most sense from a permission perspective. Just link files and version 1:1.

**Comment by bpmct** [comment]
Cool!

**Comment by matifali** [comment]
On https://github.com/coder/coder/commit/05439d2c1b01e5a7dd24a6b688b865621ddf5776 it does not show 404 but an empty red banner.
![image](https://github.com/coder/coder/assets/10648092/2c303840-d635-4dd4-883c-3a5070e3bc81)
