### ISSUE TITLE
Docs - missing json body parameters for workspace creation

### ISSUE THREAD

**Issue by smolinari** [coder/coder#5872]
Hi,

This section of the API docs for the workspace creation is missing the json body params. 

https://coder.com/docs/v2/latest/api/workspaces#create-user-workspace-by-organization

Scott

**Comment by bpmct** [comment]
@mtojek - any idea what happened here?

**Comment by mtojek** [comment]
Yes, it's a bug. Due to missing annotation, the section was skipped. Unfortunately, we can't improve validation for these cases as not all POST/PATCH/DELETE/PUT operations require a body.

Anyway, fix prepared: https://github.com/coder/coder/pull/6132.
