### ISSUE TITLE
Per-user resource provisioning and de-provisioning

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5873]
Right now, Coder will only provision resources as a part of a workspace's lifecycle (create/update/start/stop/delete). However, there are some cases in which it may be beneficial to provision stuff that isn't attached to a workspace, yet attached to a user.

- When someone first logs into Coder, Coder creates an [aws_iam_role](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role) on behalf of the user. Coder will later use this to provision their resources.
- When someone logs into Coder, Coder will create a Twilio API key for the user to perform requests in their workspace.
- When someone logs into Coder, Coder will provision an SSH key on behalf of the user using a different rotation mechanism.

Open questions:
- How can these things be rotated?
- When the "user template" is edited to provision more stuff, how will this affect existing users?

**Comment by ericpaulsen** [comment]
alternatively i am thinking Coder-provisioned resources can be shared between workspaces. e.g.

Workspace A:
- EC2 instance
- EBS volume

this volume from Workspace A can then be referenced when building Workspace B:
- EC2 instance
- EBS volume (from Workspace A)

not sure how technically feasible this is, but it could keep the volume lifecycle within Coder

only thing we have to consider is, can a workspace deletion dynamically delete the EC2 instance but simply detach the volume? in other words, selectively running `terraform destroy` against specific resources when deleting a workspace
