### ISSUE TITLE
When the user's session is over the workspace page jitters

### ISSUE THREAD

**Issue by smolinari** [coder/coder#5889]
Hi,

I believe, when the user's session times out (using OIDC?), then the workspace screen starts to jitter about every second. See image below.

https://cdn.discordapp.com/attachments/1068102110245306440/1068467157702287412/chrome_mKkP2kaiw5.gif

Asked to start this issue here: https://discord.com/channels/747933592273027093/1068102110245306440

Scott

**Comment by BrunoQuaresma** [comment]
Closing this since it is related to https://github.com/coder/coder/issues/5889

**Comment by BrunoQuaresma** [comment]
@smolinari I will post in the Discord community when this is fixed. Let me know if you prefer to have this opened.

**Comment by smolinari** [comment]
@BrunoQuaresma - Naw. I'm happy you are taking care of it and trust that you will. No worries. And thanks again!

Scott

**Comment by BrunoQuaresma** [comment]
🤦 🤦 🤦 thx for letting me know. The right link: https://github.com/coder/coder/issues/5822
