### ISSUE TITLE
Workspace build log shows: `'text/html' is not a valid JavaScript MIME type`

### ISSUE THREAD

**Issue by mafredri** [coder/coder#5896]
Just now on dev.coder.com, I clicked "Update" on one of my workspaces, then a few 5-10 seconds passed and I clicked to open the build log:

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/147409/215190718-8dae48d9-153e-420d-9a91-38d7224ea364.png">

At which point I saw this. Unfortunately didn't have the dev console open at the time so didn't see what the actual response was.

```
======================= STACK TRACE ========================

'text/html' is not a valid JavaScript MIME type.
Unable to get stack trace

============================================================
```

**Comment by BrunoQuaresma** [comment]
What template were you using?

**Comment by mafredri** [comment]
@BrunoQuaresma the default `coder` template (Write Coder on Coder).

**Comment by BrunoQuaresma** [comment]
Not able to reproduce this. 😕

**Comment by mafredri** [comment]
@BrunoQuaresma my best guess is that, since dev is constantly deploying new versions, this could’ve coincided with the coder server being updated or something like that. Meaning the API was probably down, perhaps the something like Apache/nginx responded instead of the API.

**Comment by BrunoQuaresma** [comment]
I see. Do you think is it something we should fix? Just wondering if the fix is worth the work.

**Comment by mafredri** [comment]
If it's as I suspect, it would be pretty nice if we could somehow stop navigation or prevent errors when the API isn't available. Otherwise I imagine there are lots of edge cases like this that users can run into, which leads to a pretty poor experience and potentially bug reports.
