### ISSUE TITLE
Add Coder to apt and yum

### ISSUE THREAD

**Issue by pratheekrebala** [coder/coder#5897]
I'm a big fan of the release cadence on this project and excited for the features that are on the roadmap. However, the current ux for CLI updates is less than ideal. I was wondering if any of the following were on the roadmap or if not, open for contribution?

1. Notify users when a newer CLI version is available.
    -  On the server, this is done through a MOTD style banner.

<strike>

2. Notify user if there is a mismatch between the CLI and the server.
    - E.g. Helm provides a helpful message: `Error: incompatible versions client[vTK] server[vTK]`

</strike>

4. Make packages available through apt/yum repositories.
    - On the server side, helm makes this super simple. For the CLI, the update process involves manually downloading packages, verifying check-sums and installing updates. 
    - I believe there are some services such as [Package Cloud](https://packagecloud.io/app/slacktechnologies/slack/search)  that can help with this.
    - There are also tools like [deb-s3](https://github.com/deb-s3/deb-s3) that make it trivial to prepare and host repos on S3 etc.
5. It would also be really helpful (and is a pre-requisite for No.3) if the released packages were signed with a trusted GPG key.
    -  Ref: [Package Signing in Debian](https://www.debian.org/doc/manuals/securing-debian-manual/deb-pack-sign.en.html)
    - This is also handled by [deb-s3](https://github.com/deb-s3/deb-s3) (`--sign` / `--gpg-options`)

If any of these are open for contribution, I'm happy to work on it.

Thank you!

**Comment by pratheekrebala** [comment]
I just upgrade to v16.0 and noticed a version mismatch message on my CLI. Does the CLI only notify if the major version mismatches?

**Comment by pratheekrebala** [comment]
I'm sorry! I was mistaken about the version mismatch logic. Looks like the warning is only provided when there is a difference in the major version. Although, I think there might be some utility in warning the user about minor versions as well since big features might be introduced in minor versions (e.g. rich parameters).

https://github.com/coder/coder/blob/ea7e55fcf9682409dd2170386726a99f95227244/buildinfo/buildinfo.go#L61-L73

**Comment by pratheekrebala** [comment]
I'm sorry! I was mistaken about the version mismatch logic. Looks like the warning is not provided for patch versions. Although, I think there might be some utility in warning the user about patch versions as well since CLI functionality might sometimes change in patch versions. (e.g. https://github.com/coder/coder/pull/5768)

https://github.com/coder/coder/blob/ea7e55fcf9682409dd2170386726a99f95227244/buildinfo/buildinfo.go#L61-L73

**Comment by bpmct** [comment]
> If any of these are open for contribution, I'm happy to work on it.

We'd love help with 4 and 5. These are things we've wanted to do for a while but haven't had the resources.

**Comment by matifali** [comment]
@pratheekrebala We would love to accept contributions for apt/yum packages. We recently published Coder on [homebrew](https://github.com/coder/coder/pull/9414) and [chocolaty](https://github.com/coder/coder/pull/8921).
