### ISSUE TITLE
bug: browser history state is overwritten if user is signed-out while on landing page

### ISSUE THREAD

**Issue by pratheekrebala** [coder/coder#5898]
It looks like the browser [history state is being replaced](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) if a user browses to the server when they are not signed in. This prevents a user from using the "back" button on their browser.

https://github.com/coder/coder/blob/a1212014dff791a49f0a2851b4963d534bc3b383/site/src/pages/LoginPage/LoginPage.tsx#L16-L18

Is this intentional? If not, I think the removing the `replace` on the navigate component should fix it..

This was initially introduced in: https://github.com/coder/coder/pull/465

**Comment by kylecarbs** [comment]
Not sure I understand... why would the back button need to function if it'd just take the user to `/login`? Seems like that'd be more of a bug.

Closing for now, but comment the rationale and I'll happily open!
