### ISSUE TITLE
coder slow ssh but fast from web terminal

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5899]
When SSHing from console we can see it take as long as 20+ seconds to connect. I.e. when doing `coder ssh myworkspace` or `ssh coder.myworkspace`.

At the same time the web terminal is fine and zippy.

Very frustrating for users. How do we go about troubleshooting the long connection time from console?

Currently running Coder v0.13.6+cfd02d9 across the fleet.

**Comment by sharkymark** [comment]
Does `coder speedtest <your workspace name>` show similar results?

**Comment by dcarrion87** [comment]
```
coder speedtest myworkspace
Starting a 5s download test...
run speedtest: unexpected error has occurred: read tcp [xxx]:53319->[xxx]:3: i/o timeout
````

**Comment by dcarrion87** [comment]
Switched over to another network. Slightly better times establishing connection and doesn't timeout this time.

```
➜  ~ coder speedtest myworkspace
Starting a 5s download test...
INTERVAL       TRANSFER       BANDWIDTH
0.00-2.95 sec  16.7772 MBits  5.6899 Mbits/sec
2.95-5.40 sec  16.7772 MBits  6.8387 Mbits/sec
5.40-8.55 sec  16.7772 MBits  5.3221 Mbits/sec
------------------------------------------------
0.00-8.55 sec  50.3316 MBits  5.8838 Mbits/sec
```

**Comment by mtojek** [comment]
@coadler what is the status of this issue? Are you working on this issue?

**Comment by kylecarbs** [comment]
Closing this out unless we get more people encountering this or reproducible steps.
