### ISSUE TITLE
Can the Coder agent immediately realize it's disconnected?

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5901]
With #5292, the experience is quite nice when I type `sudo reboot` or a pod gets rescheduled (e.g. on spot VMs). However, in the dashboard, the agent still thinks it's connected. Could this be instant and we display a message to the user saying the agent has disconnected? Eventually, this could work with #4680 or other messages in the terminal/IDEs to inform the user.

**Comment by mafredri** [comment]
This is something I could look at before tackling https://github.com/coder/coder/issues/4677 to add shutdown lifecycle states. It should be fairly minor:

1. Better signal handling so agent doesn’t get killed immediately
2. If above is not enough, add a final ping-of-death at the end of shutdown

**Comment by bpmct** [comment]
@mafredri is there another part to this? I noticed that the dashboard still reports the agent is online

https://user-images.githubusercontent.com/22407953/218184648-c5104c5b-65b2-484d-9fd5-18594c6f9f0a.mov

**Comment by mafredri** [comment]
@bpmct if the agent is getting killed abruptly, then there’s not much we can do except wait for the timeout to detect the agent is disconnected. Recent changes should improve conditions to avoid being killed abruptly, but it’s still possible.

Could you share how the agent is being run? That could belp discern how it is being stopped. Logs from the agent might also help.

Ultimately, if the agent is receiving SIGINT or SIGTERM, then disconnection should work. You can try this via `kill -INT $agent_pid`).

**Comment by bpmct** [comment]
It's being started via user-data, same as our [aws-linux](https://github.com/coder/coder/tree/main/examples/templates/aws-linux) example.

What is the timeout for the agent at this point? How long would it take for the server to realize an agent looses connection after an agent is killed abruptly?

**Comment by mafredri** [comment]
I can evaluate the relevant timeouts on Monday, don’t know off the top of my head (I believe they may also be configurable).

In the meantime, can you verify whether `ChangingInstanceInitiatedShutdownBehavior` is set to Stop or Terminate? I’m hoping it’s Terminate, in which vase changing to Stop might fix the issue.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html#Using_ChangingInstanceInitiatedShutdownBehavior

**Comment by bpmct** [comment]
Nice!

https://user-images.githubusercontent.com/22407953/224717317-2c0f1eb3-b606-4bfa-a941-354344c64ca4.mov
