### ISSUE TITLE
Helm chart: allow setting service account name

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#5912]
Helm chart hard-codes the service account name as `coder`. This conflicts with the name from the v1 helm chart, and so Helm fails to install in a namespace that already has Coder v1.

It is important to allow v1 and v2 to be installed in the same namespace since PersistentVolumeClaims are namespaced in Kubernetes and we are considering allowing these to be directly migrated from v1 -> v2.

**Comment by smolinari** [comment]
Although I have other ulterior motives, I'd also like to see this possible. 

Scott
