### ISSUE TITLE
docs: add some basic instructions to primary Command Line page

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5930]
I know we autogenerate the CLI docs, but can we add some basic helper info to the primary `coder` page in the "Command Line" section?

Here's the ideal state:

````sh
```
coder [flags]
```

The `coder` command line can be used as a client, or run a Coder server. Follow our docs [to install](../install/index.md).

### Examples

```
  - Start a Coder server:

      $ coder server

  - Connect to an existing Coder deployment:

      $ coder login <deployment url>

  - Get started by creating a template from an example:

      $ coder templates init
```
````

<img width="927" alt="Screen Shot 2023-01-30 at 4 23 46 PM" src="https://user-images.githubusercontent.com/22407953/215609505-7f6b5afb-b5cc-4a4e-ace7-aecf13f5acf8.png">

I think this also involved editing the CLI help text to add another example, but I think it'd be helpful to have a `login` example. That's what we have for our install script too :)

**Comment by BrunoQuaresma** [comment]
@ammario assigned this to you since you were working on improve the CLI docs experience.
