### ISSUE TITLE
Allow template parameter descriptions to be markdown

### ISSUE THREAD

**Issue by mh013370** [coder/coder#5931]
It'd be really nice, to enhance the workspace creation UI, to be able to use markdown in template parameter descriptions. This way, things like hyperlinks, headers, or anything else markdown, would be rendered nicely in the UI. Right now, it's straight text.

For example, a parameter in terraform could be enhanced like so:

```tf
variable "image" {
   type = string
   description = <<EOT
     # Select Workspace Image
     See the [registry](https://container.registry.blah/namespace) for options.
   EOT
   default = "container.registry.blah/namespace/image:tag"
}
```

Perhaps the description could be passed through a markdown processor? Longer term, it'd be nice to support `list(string)` variable types like is supported in coder v1, but that can be handled in a separate issue.

Here's the react code for parameter input.
https://github.com/coder/coder/blob/main/site/src/components/ParameterInput/ParameterInput.tsx

**Comment by B94715** [comment]
I'm happy to look into this on Thursday (2nd of Feb), if no current contributors are wanting to be assigned to the issue.

**Comment by ammario** [comment]
This is a good idea for the parameters revamp happening [here](https://github.com/coder/coder/pull/5856).

@mtojek — what do you think?

**Comment by mh013370** [comment]
`RichParameters` seems like a nice place to include an addition like this 👍

**Comment by mtojek** [comment]
It's a nice idea, but it isn't just enabling the Markdown renderer for description fields, but also stripping the Markdown format from the CLI tool (as we can't render Markdown there). The [PR](https://github.com/coder/coder/pull/5856) is already fairly large, so I'd rather add it as a follow-up.

I added this issue to the [roadmap](https://github.com/coder/coder/issues/5574).
