### ISSUE TITLE
Running migrations simultaneously causes migrations to fail

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5933]
If you start with a three pod deployment it fails the initial database migrations. You have to drop it to one pod, recreate the default schema and then let it run the migrations. Then scale up to 3 pods.

**Comment by bpmct** [comment]
@coadler has fixed these existing duplicate migrations:

![image](https://github.com/coder/coder/assets/22407953/7d1a68c8-4a7b-474c-a026-f2068981717b)

is there any way to make tests/linting/something to prevent us from doing simultaneous migrations in the futute?

**Comment by coadler** [comment]
This isn't the same issue. To solve merging duplicate migrations we either need to use a merge queue or switch to timestamp based ids. Neither of which are too ideal.

**Comment by coadler** [comment]
The original issue is fixed though, so this can be closed.
