### ISSUE TITLE
Coder API tokens are automatically generated somehow

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#5935]
Coder tokens can be created through the CLI:
`coder tokens create`

I tried this for the first time today and created one new token. 

When I ran `coder tokens list`, I was surprised to see not only the token I had created, but 3 additional tokens, all made within the last few days:
![Screen Shot 2023-01-31 at 1 18 07 PM](https://user-images.githubusercontent.com/19142439/215848135-ed3be5da-418f-41d3-92a0-d3bf7f6fe9fa.png)

I did not make the first three and would like to know how they were generated.

Note: I tried generating 1 new token after opening this issue and now I have 6 tokens in my list. So perhaps we're making multiple per request?

**Comment by MichaelGerhart** [comment]
Just to add to this, IIRC Me as a coder admin could see other people's tokens showing up when I viewed them in my own account profile.

If I created a token as local admin, logged out and logged into my OIDC account that has owner permissions, the new admin tokens showed up for my profile.

**Comment by Kira-Pilot** [comment]
This was indeed a permissions misunderstanding: owners can see all tokens but members cannot. I don't believe this is a bug so closing for now. @MichaelGerhart if this behavior isn't ideal for you, feel free to open another ticket and we'll happily triage as a feature request.
