### ISSUE TITLE
One-click VM image for AWS Marketplace

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5938]
Let’s drastically reduce the complexity/number of steps for our [AWS quickstart](https://coder.com/docs/v2/latest/quickstart/aws) by building an AMI image with Coder pre-installed and prepared for 

- Docker templates
- AWS EC2 templates

If we build the AMI with Packer, as we did for v1, we can consider supporting other clouds in the future with relative ease: https://github.com/coder/c4d-packer

**Comment by kylecarbs** [comment]
Ben did this :sunglasses:
