### ISSUE TITLE
Add the ability to view version changes of files inside directories

### ISSUE THREAD

**Issue by modrink** [coder/coder#5940]
Currently it is only possible to view changes between top-level files (the likes of `main.tf`, `readme.md` and so). It would be nice to be able to see and compare changes between files nested inside folders (for example Dockerfiles)

Images for reference
![tree](https://user-images.githubusercontent.com/90689587/216013197-680b84cc-fc0a-40be-a1c6-387134ae7dd7.png)
![versioncompare](https://user-images.githubusercontent.com/90689587/216013202-7e962304-4787-4028-820e-fbb717a27e3d.png)

**Comment by BrunoQuaresma** [comment]
Partially solved by https://github.com/coder/coder/pull/5963
