### ISSUE TITLE
Allow for searching Users

### ISSUE THREAD

**Issue by misskniss** [coder/coder#595]
As a frontend developer I want to support searching for users lists so that I do not have the whole list in a single page that requires a lot of scrolling and the rendering can be faster.

As an admin user that may have 7,000 users in the system at a time, I want searching so I do not have to scroll through potentially all of those users to find the one user I am looking for. 

The work in #1972 by @f0ssel can be an example for how we should implement this for users on the front and backend.

**Comment by tjcran** [comment]
@f0ssel can the work in #1972 be re-used for Users searching/filtering?

**Comment by f0ssel** [comment]
Not really on the backend, the endpoints are different and do not have the same query parameters available, but I don't think it would be much work to replicate it for this case.

**Comment by tjcran** [comment]
> Can we make this issue user-facing, integrating both frontend and backend?

exactly what I had in mind!
