### ISSUE TITLE
docker daemon ubuntu coder templates create

### ISSUE THREAD

**Issue by iondrugalea** [coder/coder#5957]
Hi guys,

I'm trying use the coder template Develop in Docker and have some trouble with this.

- coder templates init
    chose Develop in Docker
- cd .docker
- coder templates create 

command **coder template create** gives me this error in the last line.
```
version mismatch: client v0.14.3+67952cf, server v0.15.2+c3731a1
download the server version with: 'curl -L https://coder.com/install.sh | sh -s -- --version 0.15.2'
> Create and upload "~/coder/docker"? (yes/no) yes
✔ Queued [2775ms]
✔ Running [287ms]
✔ Adding README.md... [-3ms]
✔ Setting up [424ms]
✔ Parsing template parameters [407ms]
⧗  Detecting persistent resources
  Terraform 1.3.4
  data.coder_provisioner.me: Refreshing...
  data.coder_workspace.me: Refreshing...
  data.coder_provisioner.me: Refresh complete after 0s [id=f57d3737-0193-451e-8fdf-627e1fc87490]
  data.coder_workspace.me: Refresh complete after 0s [id=573ddfc5-735e-4168-836f-a9971aebf21f]
  Error: Error pinging Docker server: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
What I've tried:
1. command **docker context ls**  returns 
_**default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock**_
I 've added the unix:///var/run/docker.sock under provider docker in the main.tf

**provider "docker" {
    host    = "unix:///var/run/docker.sock"
}**

But this didn't help. coder templates create gives me the same error.

On the another side  I am able with native terraform code on the same machine to create docker images and containers. 

The issue seems to be only when using coder templates create with the docker template

Thanks!

**Comment by kylecarbs** [comment]
Are you sure Docker is running on the host machine?

**Comment by iondrugalea** [comment]
Hi @kylecarbs 
yes, I am sure. 
As I mentioned I am able on the same host with native terraform build docker images and create containers. 
![image](https://user-images.githubusercontent.com/12760079/216088004-516a7519-c241-4bba-b3bd-e406c6abaf88.png)

**Comment by kylecarbs** [comment]
Odd. Are you running Coder with a different user? If you are running with the `coder` user, you may have to add it to the `docker` group.

**Comment by iondrugalea** [comment]
not sure if this is important but i forgot to mention, in my case coder is running in kubernetes and I have already pushed some templates. The only issues are with the docker develop template. I've installed coder locally just to manage the templates.

**Comment by bpmct** [comment]
Ah I see, it looks like you have Docker installed on your local machine. If you have Coder running on Kubernetes, you'll need to rely on some other "docker host" in order to provision workspaces. For example, an external VM running somewhere. Then, in the Terraform provider, you can connect to that remote docker host, [even over SSH](https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs#remote-hosts).


Or you could modify the Kubernetes template to provision the desired containers as pods.

**Comment by kylecarbs** [comment]
Closing this for now. Let us know if we can help you out!
