### ISSUE TITLE
docs: include the first version when a feature existed in page

### ISSUE THREAD

**Issue by nschmeller** [coder/coder#5970]
I'm looking at https://coder.com/docs/v2/latest/cli/coder_rename#coder-rename and trying to figure out why my Coder CLI returns `fatal: unknown command "rename" for "coder"` when I run `coder rename ...`. I'm assuming this is because I'm running a version of `coder` that doesn't have `rename`, but it would be useful to confirm this by checking the docs. 

The ask is, could https://coder.com/docs/v2/latest/cli/coder_rename#coder-rename have a blurb somewhere that says "introduced in version 1.XX.YY"?

**Comment by bpmct** [comment]
Sorry - I totally missed this. This is going to be a bit tough for us to do right but would love to reconsider when we have a 1.0 release, likely within the next 6 months or so.

**Comment by bpmct** [comment]
I think we'll also be more likely to add version control to our documentation as we do for v1 before we add the version to each CLI command. I totally get the pain point though!

![Screenshot 2023-02-15 at 5 04 04 PM](https://user-images.githubusercontent.com/22407953/219209427-e4ac66bb-c55f-4480-9019-de976b8afb08.png)
