### ISSUE TITLE
Add a team lead role to stop/start workspaces

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#5971]
We have an RBAC requirement to give Team Leaders in a Coder instance the ability to stop/start workspaces in a limited capacity cluster. They should not be able to remote connect to the workspace.

We segregate joint ventures by Coder instances so the requirement would only be per instance at this stage.

**Comment by ammario** [comment]
Interesting request. Perhaps we could have a Cost Manager role that can start/stop instances and edit quota allocations.
