### ISSUE TITLE
rich parameters: support for disk size

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5978]
PVCs in Kubernetes (and many cloud APIs) cannot have their size decreased, only increased. We’ll need some special parameter validation to prevent this from happening. 

![image](https://user-images.githubusercontent.com/22407953/216373011-47afcf6e-3d8c-42b5-a7b0-41fc5c9e2e21.png)

**Comment by kylecarbs** [comment]
@bpmct I believe in your spec a while ago you had an `increment_only` option in the `validation` block. This is something we should probably add.

**Comment by mtojek** [comment]
I've already started working on this. You can take a look at the [pull request](https://github.com/coder/coder/issues/5978) to make sure it's aligned with your vision.

**Comment by kylecarbs** [comment]
`monotonic` is a much better keyword for it!

**Comment by bpmct** [comment]
TIL what `monotonic` means :)
