### ISSUE TITLE
Simple `screen` GUI in web terminal and CLI helpers

### ISSUE THREAD

**Issue by bpmct** [coder/coder#5982]
This is a far-out idea, but a cool benefit of remote development that many developers may be unaware of: detaching from a long-running process and revisiting from another client.

As a `screen` noob, I'd love for Coder to help me quickly do the following:

- Start a build on my workspace (perhaps via `VS Code Remote`)
- Detach from the session (perhaps the agent starts things as a `screen`)
  - `coder detach` (name your session: `build`) or a button in VS Code/terminal
- I can go on a walk or grab a coffee and, from my phone, I can use the web terminal in Coder to enter the session (`build`) and see how the build is going or quickly change build arguments if something fails.

Of course, this could rely on `screen` being installed in the workspace and the shell starting as a screen session.

**Comment by matifali** [comment]
What about setting a `coder_app` resource that uses `tmux` or `screen` in the template?
`tmux` by default connects to the existing session and can create a new session on the first run.

**Comment by bpmct** [comment]
That could totally work

**Comment by matifali** [comment]
Converting this to a `use-case`, probably a Coder [module](https://registry.coder.com/modules) instead of a `feature`.

**Comment by sreya** [comment]
I believe we support this already
