### ISSUE TITLE
Minor UX improvements to the Workspaces page

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#5983]
![image](https://user-images.githubusercontent.com/7122116/216396644-13cd2335-719c-49ae-bf5f-33f78efc2bf2.png)

**Comment by BrunoQuaresma** [comment]
1. I think the template should be clickable
2. Let's remove the version and add, or not, the outdated warning in the workspace name
3. I think it is nice, but, not sure how heavy it would be to load all the apps inside of the agents for all the workspaces. Sounds expensive 🤔

**Comment by kylecarbs** [comment]
On 3, we already do!

![image](https://user-images.githubusercontent.com/7122116/216416675-06762f26-c38d-4c08-8732-ed3c72183e71.png)

**Comment by BrunoQuaresma** [comment]
From the items you mentioned, the only one that is open is adding the dropdown for the users to access an app directly from this page. I'm not entirely sure how we could make it easier and look good for the users so I'm going to close this for now and open a new ticket - https://github.com/coder/coder/issues/6249
