### ISSUE TITLE
bug: clicking delete workspace does not respond

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5986]
A prospect experiencing inconsistent behavior where clicking the delete workspace icon, does nothing.

0.15.3

On some workspaces it works fine.

I witnessed this over screen sharing and did not see any errors in the browser inspect console.

**Comment by BrunoQuaresma** [comment]
I was not able to reproduce this 😔

**Comment by sharkymark** [comment]
@BrunoQuaresma try clicking to the right side of the delete seems a div or span has the delete event but it's not the entire button space.

**Comment by matifali** [comment]
I have also faced this multiple times but random. Sometimes it works on the first click sometimes it refuses to work.

**Comment by kylecarbs** [comment]
@BrunoQuaresma there's a small space in this dialog: 
![image](https://user-images.githubusercontent.com/7122116/229623001-b6b4de0a-0aa5-45d0-b9ac-4ef6b3598ccd.png)

**Comment by BrunoQuaresma** [comment]
Yes, there is this space but even after fixing that space, I noticed the popover is getting "blocked" by something. I'm planning to fix that when I refactor the header of the workspace page. But we can fix the space and see if that solves the issue for most of the users.
