### ISSUE TITLE
bug: 0.16.0 shows template's sensitive variables in UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#5999]
Version: [`v0.16.0+b9b402c`](https://github.com/coder/coder/commit/b9b402cd0cb51c11ffa90d43bfaeb40e34fd8995)

![image](https://user-images.githubusercontent.com/2022166/216446952-42560e35-63a8-473b-9018-b0afa1e1da5e.png)

**Comment by kylecarbs** [comment]
https://github.com/coder/coder/commit/f60f06e2c61863ac865584dce49a35e61aab2c0b
