### ISSUE TITLE
Allow editing of a user inline or in a dialog 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#600]
As a user, I want the ability to edit a user in-line and/or via dialog when I select a user in a user list. 

Note: we want to make it fast for users to edit another user. Directing them to an entirely new page can get cumbersome when you are doing a lot of editing. 

Look for solutions that reduce the number of clicks it take to edit a user. Maybe something like an edit icon on the list item that opens a dialog OR puts all the info in the line item to an editable state that can be tabbed through and hitting enter exits edit mode.

**Comment by tjcran** [comment]
Closing because this is already in product.
