### ISSUE TITLE
docs: add docs to list all possible `CODER_` env variables

### ISSUE THREAD

**Issue by matifali** [coder/coder#6002]
Add docs to list all possible `CODER_` env variables that can be set in `/etc/coder.d/coder.env`
cc: @bpmct @ammario

**Comment by bpmct** [comment]
We technically have it here, but it's not fantastic to browse. https://coder.com/docs/v2/latest/cli/coder_server

@BrunoQuaresma - thoughts on doing the CLI arguments via a table format?

**Comment by bpmct** [comment]
Could also be nice to make each flag linkable

**Comment by matifali** [comment]
Is there a relationship between `--some-feature` and `CODER_SOME_FEATURE`?
There are cases where this does not match.
e.g. `--telemetry` and `CODER_TELEMETRY_ENABLE`

**Comment by bpmct** [comment]
There usually is a direct relationship, but there are edge cases!

**Comment by matifali** [comment]
Ok. I thought it might be a typo.

**Comment by ammario** [comment]
We should do a better job of making these consistent so they're easier to remember. Let's look at redoing the environment variables to match the flags, silently accepting the old variables for compatibility.

**Comment by bpmct** [comment]
Related #5290

**Comment by bpmct** [comment]
added #5290 to our backlog. we should still think about ways we can make the CLI output prettier as well :)

**Comment by bpmct** [comment]
closing in favor of #6055
