### ISSUE TITLE
Prune template_versions and provisioner_job_logs table

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#6020]
# Problem

We currently don't prune the `template_versions` table or the `provisioner_job_logs` table.
When you do a template import dry-run, this creates a template versions and the logs also stick around.
This will eventually blow up the table sizes. 

# Solution

We need to implement some sort of time-based cleanup on these tables, pruning entries older than some value.

**Comment by johnstcn** [comment]
bump

**Comment by matifali** [comment]
Yes, indeed, Heroku's PostgreSQL instances are charged by the number of rows and we should not waste any table rows.

**Comment by bpmct** [comment]
Related #9478
