### ISSUE TITLE
feat: Template approval befor roll out to users

### ISSUE THREAD

**Issue by Akantor47** [coder/coder#6030]
Hello there, 

## Feature Description

While updating a template, the template gets instantly available for all users, even if there are bugs in the 'main.tf' or in my case in the dockerfile's. 

This can result in damaged or non working workspaces, for the users on the instance. 

Would be awesome to have a approval step in between, that way a "audit" or "Template Admin" user would need to approve the template before everyone gets the "update" workspace button. 

This would help to not annoy users with not working (or broking) updates, and also to not create unusable volumes / containers which could end up beeing unavailable or filling up storage. 

This could also be depending on the state of a created workspace whith this version, so no one can approve a template until it fully starts and gets usable. But I wouldn't automaticly approve a running template, because there could still be issues with the settings inside of it. 

## Template Approval

This could for example be a point in the "Template settings" where it would be perfect to list the versions and be able to set individual versions to approved or not approved. (This way it could also be locked for users to use a older version which has not been approved)
![image](https://user-images.githubusercontent.com/36771317/216760456-9e3d66a8-4681-43a1-aa1e-ef5e7ed06ad7.png)

Or it could just be an extra menu button, to update to a "experimental version" in the dropdown menu besides the regular "stop", "start", "update" button. Which either wouldn't be visible for regular users, or wouldn't be as tempting to click as the regular "upate" button. That way users wouldn't usually see the updated version until it is approved. 
![image](https://user-images.githubusercontent.com/36771317/216760530-59566cc7-54d6-499e-a4d4-bde00c4fa7b8.png)

**Comment by matifali** [comment]
We can push a new version as pre-release and then after an admin or some auditor has tested the new version he can mark it as a release and then it would be made availble to all other users as an update.

**Comment by Akantor47** [comment]
Also this should maybe be a function which can be disabled globaly, because someone may be testing the templates inside of a CI/CD. Which would also solve this problem.

**Comment by matifali** [comment]
Yes. Pushing it as a pre release is similar to how GitHub releases work. It's optional and mist probably ci/cd would mark it as a pre release then an admin can mark it as release after some testing manually. This is the workflow in my mind. 
@kyle and @bpmct can add their opinion

**Comment by Akantor47** [comment]
Also just thought about maybe it would be usefull for some people to have multiple "tags"?

E.g:
- Main -> the current useable version
- pre -> the version which is unstable and is currently getting prepared 
- alpha / next -> a prepared version which is going to be the next proper version because the production system gets updates and the requirements get changed at a some time. E.G docker requirement changes from V2 to V3 or something like that

But thats all just thoughts form myself, let me know what you think about this. :)

**Comment by kylecarbs** [comment]
Internally, template versions aren't linear (even though it's currently displayed as if it is).

There's an active version, and then all other versions. Soon(ish), versions can be associated with tags (for things like git commits, branches, etc).

**Comment by Akantor47** [comment]
Okay, would it be possible to add a flag for the template to freeze the update message? 

Or allow a tag to be auto assosciated and disable the regular update message?

Because while template testing, I wouldn't mind updating via the "change version"  but I would prefer not to interrupt everyones workflow, just because my template is not yet ready.

**Comment by matifali** [comment]
You may use the following workaround for now,
Create two different templates corresponding to 2 different branches of a repo. one for testing and for production. If all goes well, you may push the changes from the testing to the production branch.

**Comment by matifali** [comment]
@bpmct this is what we discussed.

**Comment by kylecarbs** [comment]
We're improving template versions with #6665 that will enable a flow _somewhat_ like what you suggest.

Lets track this there, and use this as a reference for guidance!
