### ISSUE TITLE
feat: I want to delete a template, but don't know who has workspaces built with it

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6037]
Version: [`v0.16.0+b9b402c`](https://github.com/coder/coder/commit/b9b402cd0cb51c11ffa90d43bfaeb40e34fd8995)

I would like to delete a template, but I am stopped because workspaces are built with this template.

There should be a list of workspaces, so as admin I can notify and force delete the workspaces.

![image](https://user-images.githubusercontent.com/2022166/216787666-cd7b8ce6-b80d-4cdd-8060-183373d9db08.png)

**Comment by sharkymark** [comment]
Unless the plan is to go to All Workspaces and filter. There should be a list in the template UI if I am an admin.

**Comment by ammario** [comment]
We should link to the filtered Workspaces page.

**Comment by matifali** [comment]
If we implement filtering, then this can be easily known
Related: #7348 #7318

**Comment by matifali** [comment]
Hi @sharkymark. This is now possible to filter workspaces by template. 
![image](https://github.com/coder/coder/assets/10648092/36528182-99e7-4e20-b627-4887b0de3420)
