### ISSUE TITLE
What does the breaking TLS change in 0.16.0 mean for Caddy users

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#6041]
As per this comment: https://github.com/coder/coder/pull/5973#issuecomment-1413178889

We are Caddy+Tailscale users reverse proxying with a Tailscale certificate. Caddy reverse proxies to the non TLS listener of Coder.

What does this change mean for us and what do we need to change? We don't necessarily want Coder getting clever with certificates but if it needs to we want to understand what changes we need to make to Caddy to accept the self signed.

**Comment by kylecarbs** [comment]
@dcarrion87 this is just for redirection from HTTP -> HTTPs if you bind to both on Coder. It shouldn't disrupt the vast majority of existing deployments.
