### ISSUE TITLE
docs: Guide for deploying Coder on K3s

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6048]
We provided a [k3s guide for Coder v1](https://coder.com/docs/v1/v1.38/setup/kubernetes/k3s) so it might be nice to do something similar for Coder v2. 

@Sharpz7 wrote a nice tutorial which we can expand as a first-class doc: https://gist.github.com/bpmct/93d03ec9eb79c810c0c6c8631dd3cec4

**Comment by Sharpz7** [comment]
Definitely interested in taking this on myself, if time permits.

**Comment by matifali** [comment]
Hi @Sharpz7 still in the mood to do this?
