### ISSUE TITLE
Site-wide flag to disable "change version"

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6051]
The "change version" feature is a great way for developers to try new features and roll back if something breaks.

![Screenshot 2023-02-06 at 8 44 24 AM](https://user-images.githubusercontent.com/22407953/217002141-d1058715-db24-4cb2-9112-52d2509017e8.png)

However, some admins will want to ensure developers are on the latest version of a template to comply with security policies. For this reason, we should make a flag to disable this behavior across all workspaces. An enterprise customer has requested this feature

**Comment by ammario** [comment]
Why did we allow changing version to begin with?

**Comment by bpmct** [comment]
We should consider doing this per-template.

**Comment by dcarrion87** [comment]
This caused confusion when this came in. Would love to see this just go. There's no reason in our environment for someone to ever rollback a version. It's actually a risk.

**Comment by bpmct** [comment]
> Why did we allow changing version to begin with?

It's nice to "roll back" if a breaking change occurred in a template version. We never had a feature for this in v1 until very recently, because images were the source of truth and any user could add image tags.

**Comment by ammario** [comment]
Maybe instead of "change version" we should introduce a concept of tags. Then:
* Don't want rollbacks? Just deploy to `template:master`
* Want rollbacks? Just tag `coder templates tag template:master template:last` before every template update

**Comment by bpmct** [comment]
Sounds fantastic to me :)

**Comment by matifali** [comment]
> Maybe instead of "change version" we should introduce a concept of tags. Then:
> 
> * Don't want rollbacks? Just deploy to `template:master`
> * Want rollbacks? Just tag `coder templates tag template:master template:last` before every template update.

#3775 is related in suggesting setting a message(description) on every push.

**Comment by matifali** [comment]
Also my comment on #6030 is related.

**Comment by bpmct** [comment]
Closing in favor of #6635. We're definitely considering some form of tags/branches too
