### ISSUE TITLE
scheduling: admins want to update all workspaces at once

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6052]
While controls like #6047 can enforce updates after the workspace reaches its max lifetime, there may be cases where an admin will want to immediately "roll out" a change to all developer workspaces, e.g. on a weekend or after a major security patch.

Some ideas:

| Solution | Pros | Cons |
| -- | -- | -- |
| Provide a bash script in docs for updating all workspaces with a particular template | No added code debt | Kicks users out when they are working, could interrupt developer's flow or stop running jobs |
| Add a first-class feature to update all workspaces that warns the user and allows them to postpone and/or save their work | Developers have time to save their work. Easier command to remember. | Complex feature. No guarantee developers see the notification |
| Bulk workspace actions | Ability to query specific workspaces (`last-active:90d-ago`) and run specific actions `stop, delete, etc`. Potentially ability to notify the user before action occurs. | Complex. Could be done with custom scripting |
| Template version tags (e.g. `latest`) Always push one promoted template version tag: latest #6051 | |  |

**Comment by ammario** [comment]
Related https://github.com/coder/coder/issues/6051

**Comment by deansheather** [comment]
The second solution could be accomplished by setting the workspace build's `max_deadline` to be the target time for update, and then having logic elsewhere to force update on the next build.

**Comment by ammario** [comment]
That's clean @deansheather. I could see an admin setting that all workspaces have to update on Saturday at 11:59PM. There could be a bool on the latest workspace_build for "force_update".
