### ISSUE TITLE
docs: explain story around Terraform Enterprise

### ISSUE THREAD

**Issue by ammario** [coder/coder#6056]
Related https://github.com/coder/coder/issues/5959

Even though the answer right now is we don't work with it, we should address this question in the docs.

**Comment by bpmct** [comment]
I'm not sure of a great place to put this in our docs right now. Here are my latest notes: https://github.com/coder/coder/issues/5959#issuecomment-1432220775

**Comment by kylecarbs** [comment]
Closing this in favor of the integration issue. People can refer to that as docs for now.
