### ISSUE TITLE
Support mapping (creating) roles from IDPs to Coder

### ISSUE THREAD

**Issue by misskniss** [coder/coder#606]
Problem
Organizations with potentially thousands of user will want a way to programmatically have their roles and identities transfer to Coder so they are not required to enter each manually.  

Definition of Done
If users have Okta or AWS identify providers, we want to map those identities to Coder. 

As a user with an IDP, I want the ability to have the roles in my IDP map to the roles in Coder so that I have consistent roles between the two.

**Comment by ketang** [comment]
IdP = "identity provider"

**Comment by kylecarbs** [comment]
This isn't clear enough.
