### ISSUE TITLE
VS Code Desktop Icon

### ISSUE THREAD

**Issue by FaresHerhar** [coder/coder#6072]
Hello,

I well installed Coder as these pages explains (Airgap Enviroment), [Kubernetes](https://coder.com/docs/coder-oss/latest/install/kubernetes), [Offline deployments](https://coder.com/docs/coder-oss/latest/install/offline).

Coder is well installed, and I 'am able to access my workspace, from the VS Code Browser, and the terminal as well, everything works well. My only issue is that I can't see the VS Code Desktop Icon, on the workspace page (same case for all the users, even the owner).

Any Help Please !

![thumbnail_image](https://user-images.githubusercontent.com/102948288/217205853-2a2856c8-fc17-406f-a997-5cdc44944484.png)

**Comment by sharkymark** [comment]
Do you have `--browser-only` set and an enterprise (paid) trial key in place? That prevents SSH which the VS Code Desktop needs.

**Comment by FaresHerhar** [comment]
> Do you have `--browser-only` set and an enterprise (paid) trial key in place? That prevents SSH which the VS Code Desktop needs.

In my `values.yaml, I set the env variable 'CODER_BROWSER_ONLY=fasle
'

**Comment by FaresHerhar** [comment]
> Based on the UI it seems you might be using an older version of Coder... could you post the version here?

I am using the Helm Chart v0.13.6, that deploys <ghcr.io/coder/coder:v0.13.6> as the Coder image, and <docker.io/codercom/enterprise-base:ubuntu> as the Coder Workspace image, that it is used with the Kubernetes Template.

**Comment by FaresHerhar** [comment]
> You'll need to upgrade! This feature landed in v0.16!

oooow, I see.
Thanks.

> PS
I'll close the issue, once I comeback with a feedback !

**Comment by kylecarbs** [comment]
Awesome :)

**Comment by FaresHerhar** [comment]
> Awesome :)

It is indeed the version, I just upgraded to the v0.17.0, and works great.
Thanks a lot Man !
