### ISSUE TITLE
rich parameters: convert Coder examples

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6073]
Extracted from: https://github.com/coder/coder/issues/5574

The idea is to update our [template examples](https://github.com/coder/coder/tree/main/examples/templates) to use rich parameters.

**Comment by mtojek** [comment]
Hey @bpmct! I think that I'm good with https://github.com/coder/coder/pull/6556, so this seems to be the next step. I saw that there is also [this PR](https://github.com/coder/coder/pull/6397).

Would you like me to take over it, and review it, or is it something you'd like to finish?

**Comment by bpmct** [comment]
@mtojek feel free to review the PR or even push directly to it. @matifali is in our slack channel so we can collaborate there :)

**Comment by matifali** [comment]
I will get it finished later tonight
