### ISSUE TITLE
docs: rich parameters

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6074]
Extracted from: https://github.com/coder/coder/issues/5574

The goal of this issue is to describe rich parameters and document all related properties, types, validation, etc. The documentation should also contain guidelines on how to migrate from old parameters to new ones.

**Comment by mtojek** [comment]
Items to cover with docs:
- [ ] What features do rich parameters introduce?
- [ ] Describe validation modes
- [ ] Describe how `mutable` parameters work
- [ ] How users can migrate old parameters to rich ones?
- [ ] Conflict between old parameters and rich parameters (can't use together)

**Comment by matifali** [comment]
> Items to cover with docs:
> 
> * [ ]  What features do rich parameters introduce?
> * [ ]  Describe validation modes
> * [ ]  Describe how `mutable` parameters work
> * [ ]  Describe how `required` parameters work
> * [ ]  How users can migrate old parameters to rich ones?
> * [ ]  Conflict between old parameters and rich parameters (can't use together)

I am writing a blog post that addresses many of these questions by using examples. you can give your feedback. https://github.com/coder/blogs/pull/1

**Comment by mtojek** [comment]
I'm going with the missing doc sections

**Comment by mtojek** [comment]
>  How users can migrate old parameters to rich ones?

This is the last item missing, but it's partially blocked by: https://github.com/coder/coder/issues/6368

**Comment by matifali** [comment]
The docs look great.
