### ISSUE TITLE
rich parameters: improve UX

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6076]
Extracted from: https://github.com/coder/coder/issues/5574#issuecomment-1416061945

We'd like to improve the UX of rich parameters to be more consistent.

Ideas:
1. Make the edit workspace form look the same as the create workspace form.
2. Mutable/immutable headers seem odd.
3. "Danger zone" around immutables, like [img](https://i.imgur.com/tQ0TOhf.png).
4. Explain what it means in a description/subtitle in the form.

<details>
  <summary>Original post</summary>

@deansheather:

> can we make the edit workspace form look the same as the create workspace form?
like in v1
and just disable the fields that can't change
also the mutable/immutable headers seem odd to me, it'd be nice if users could define their own sections and we just relied on the yellow text that says it can't be changed instead

@ammario

> What’s friendlier language we can use instead of “mutable” and “immutable” in the form? I also second Dean’s point. It would be cool if we could reuse the form and show the immutable params as disabled forms so the user is still aware of them. I also think it would be nice if we had a box around the immutable parameters like: https://i.imgur.com/tQ0TOhf.png.

@kylecarbs
> i feel like immutable is pretty friendly as code

@ammario 
> As a section title it’s probably fine since it maps to configuration. We should at least explain what it means in a description / subtitle in the form.

</details>

**Comment by mtojek** [comment]
Hey @BrunoQuaresma, is this something you can help with and park on your personal roadmap?

**Comment by BrunoQuaresma** [comment]
Sure thing! I have a few things on my plate right now but I can finish this probably next week.

**Comment by mtojek** [comment]
@BrunoQuaresma I don't see the PR linked here. Could you please link it and resolve this issue/comment the status?

**Comment by BrunoQuaresma** [comment]
From all the items posted, we are missing the "Make the edit workspace form look the same as the create workspace form.". I will do it next.
