### ISSUE TITLE
Investigate the use of better table components/libs in the frontend 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#608]
As a frontend developer I want to investigate better solutions for table compoents and libraries in the frontend so that we are able to better support large tables as the product grows to meet our client's needs.

**Comment by ketang** [comment]
It's not clear what the priority or success criteria for this are.

**Comment by kylecarbs** [comment]
@ketang agreed. I'm going to close this for now, if someone sheds some additional light on the problem, we can re-open.
