### ISSUE TITLE
A refresh the coder server is needed after creating the first user to see Enterprise features

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6080]
When you set up a new Coder deployment, you have to refresh the page to see the enterprise features.

**Comment by mtojek** [comment]
Ok, we need to do a better job describing our issues. I spent a decent amount of time to understand what is it about 🙃

It looks like `/entitlements` API does not get refreshed when the new trial license is created. What is interesting, entitlements refresh immediately on "license delete" and on "enterprise license upload".

I'm going to look at how we can improve it.
