### ISSUE TITLE
docs: Apache/NGINX reverse proxy configs

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6086]
We get a lot of questions in Discord about this!

**Comment by matifali** [comment]
Which section of the docs should we add these?
https://coder.com/docs/v2/latest
https://coder.com/docs/v2/latest/quickstart
or maybe a new section https://coder.com/docs/v2/latest/configuration
that includes three separate files for caddy, nginx, and apache.

cc: @bpmct

**Comment by bpmct** [comment]
@matifali I think we can put these in a section in https://coder.com/docs/v2/latest/configuration and then keep the files in https://github.com/coder/coder/tree/main/examples/web-server/.

**Comment by bpmct** [comment]
We can also consider refreshing our Caddy docs in scope for this. @coadler suggested checking out headscale's doc with example configs. Coder's config may actually require similar configuration: https://github.com/juanfont/headscale/blob/main/docs/reverse-proxy.md
