### ISSUE TITLE
Remove audit server flag

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#6094]
We have a coder server flag: `--audit-logging `. This is a bit confusing and we should remove it so that licensing completely dictates the feature accessibility.
![Screen Shot 2023-02-07 at 5 20 16 PM](https://user-images.githubusercontent.com/19142439/217379990-2842dac8-c298-4999-8b6e-fc2a1e002fa0.png)

**Comment by Kira-Pilot** [comment]
@kylecarbs FYI

**Comment by bpmct** [comment]
This makes sense to me!
