### ISSUE TITLE
Updating template from CLI does not save user agent info

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#6095]
1. Update a template from the CLI
2. Check out the audit logs and note that OS and Browser are not available:
![Screen Shot 2023-02-07 at 5 51 45 PM](https://user-images.githubusercontent.com/19142439/217384982-90bce2ae-a937-468c-a1ed-a86f6692c17b.png)
3. They are not returned on the `user_agent` field:
![Screen Shot 2023-02-07 at 5 52 39 PM](https://user-images.githubusercontent.com/19142439/217385143-3586c04e-092e-4e8f-a26f-9009bf4d89cc.png)

**Comment by MichaelGerhart** [comment]
@Kira-Pilot I am seeing this behavior also, but mine is slightly different. The keys for those values show up, they just contain what looks like a caught exception message

![image](https://user-images.githubusercontent.com/5455211/217623271-c4d7a593-1c3b-46fb-bcda-bbe76e188549.png)

**Comment by Kira-Pilot** [comment]
@MichaelGerhart I fixed that yesterday and so you shouldn't see those broken strings next release! The user agent data will not be available until this ticket is resolved however.

**Comment by kylecarbs** [comment]
I _think_ this is expected... because there really is no user agent if the user is on the CLI, unless we want to use a custom user-agent so we can show it's from the CLI.

Feel free to re-open @Kira-Pilot !
