### ISSUE TITLE
Rich parameters: mark parameter required

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6100]
The goal of this issue is to enable optional rich parameters. At the moment all parameters are required and there is no easy way to pass an empty value.

Most likely we will need to add an extra property `required` to terraform-provider-coder.

**Comment by mtojek** [comment]
Let's use the same assumption as for "managed variables"

`required? take "default" value if no value provided, otherwise fail`

Battle plan:

- [ ] terraform-provider-coder: add `required` property. If `required
- [ ] Add `required` column to the database table (default: no)
- [ ] Adjust coderd API validation to obey the constraint
- [ ] Adjust site validation to obey the constraint
- [ ] CLI: _what is the best UX, to load previous values or ask for them?_
- [ ] dry-run: let the user pass required rich parameters
  - CLI: use `--rich-parameters` to pass values
  - site: _should we present a special form to enter required params without defaults?_

**Comment by bpmct** [comment]
I noticed that even if I have a default value as `""` it won't let me create from the UI

<img width="1183" alt="Screenshot 2023-02-23 at 5 40 59 PM" src="https://user-images.githubusercontent.com/22407953/221063859-d30b53db-a1b7-4872-a043-1348e8db9458.png">

**Comment by mtojek** [comment]
> I noticed that even if I have a default value as "" it won't let me create from the UI

Yeah, the aim of this issue is to fix this case :)

**Comment by mtojek** [comment]
Looking at this one.

**Comment by mtojek** [comment]
Co-assigning @BrunoQuaresma to adjust the "Update workspace" flow to let users enter values for newly added parameters.
