### ISSUE TITLE
audit: logs for new OIDC Users

### ISSUE THREAD

**Issue by MichaelGerhart** [coder/coder#6108]
<ins>Problem Summary</ins>

After implementation of #5925 user logins are getting appropriately audited, however if a NEW OIDC users logs in that does not have a local Coder user profile yet, the audit log shows "an unknown user logged in" creating a less than useful audit log message.

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/5455211/217589520-6c1f52e9-0baf-4971-8551-103aaab01cdb.png">

<ins>Expected Behavior</ins>

Coder should likely be creating the local user profile and then creating the audit record.

<ins>Steps To Reproduce The Problem</ins>

1. Install coder and setup OIDC Authentication
2. login with OIDC as a new user

**Comment by Kira-Pilot** [comment]
Hi @MichaelGerhart! Thank you for documenting this. I'll add it to our audit epic.
