### ISSUE TITLE
coder CLI for token creation does not work for more than 1 month duration

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6109]
Version: [`v0.17.0+a5f3f02`](https://github.com/coder/coder/commit/a5f3f02ef8428dc26f7b670d11f634e01ab8f28e)

I want to create a longer term token using the Coder CLI.

It fails when I do.

![image](https://user-images.githubusercontent.com/2022166/217596992-1ed21f43-90f6-4f6a-8400-51d280b713e9.png)

**Comment by Kira-Pilot** [comment]
![Screen Shot 2023-02-08 at 11 54 25 AM](https://user-images.githubusercontent.com/19142439/217598027-c3c21a7c-d5fc-4d22-b17b-f9ecde783e1a.png)

**Comment by bpmct** [comment]
Mark shares this is his values.yaml... However it works for me

```sh
- name: CODER_MAX_TOKEN_LIFETIME
      value: “8760h0m0s”
```

```sh
CODER_MAX_TOKEN_LIFETIME=8760h0m0s coder server
coder tokens create --lifetime=8760h0m0s
```

However, I think we should actually disable CODER_MAX_TOKEN_LIFETIME by default, but keep the flag so that deployments can opt-in to setting a max token lifetime.

**Comment by sharkymark** [comment]
I confirmed on my VM systemd deployment, adding the environment variable works.

@bpmct am I doing something wrong in the values.yaml one?

**Comment by sharkymark** [comment]
Nevermind, seems K8s works fine too. If was testing just on the command line passing the --lifetime flag. Or maybe we fixed something. lol

**Comment by matifali** [comment]
How to make it work on Windows? Setting `$CODER_MAX_TOKEN_LIFETIME="8760h0m0s"` or `$env:CODER_MAX_TOKEN_LIFETIME="8760h0m0s"` and using 
```ps
coder tokens create --lifetime=8760h0m0s
```
Gives the same error as @sharkymark reported.
```console
Failed to validate create API key request.
Run 'coder tokens create --help' for usage.
```

**Comment by bpmct** [comment]
@matifali did you set that for the `coder server`?

**Comment by matifali** [comment]
It's my local cli. But it's a full binary installed from Winget. 
I will test on the server.

**Comment by sharkymark** [comment]
@matifali are you setting CODER_MAX_TOKEN_LIFETIME in deployment? Once I got that set right, using `coder tokens create --lifetime=8760h` worked

**Comment by Kira-Pilot** [comment]
Just a heads up: yesterday we merged https://github.com/coder/coder/pull/6467, which was created as a response to this inquiry. @matifali definitely re-open this ticket if you're still seeing issues with that new PR in place, and if @sharkymark's workaround is not sufficient, and we will investigate further!
