### ISSUE TITLE
Extend coder to allow reuse of template terraform code

### ISSUE THREAD

**Issue by trustycoder83** [coder/coder#6117]
As a coder administrator, I want to avoid the need of copying the common logic for each new template I create. (dry principle)
The common logic is currently part of a terraform module that I would like to ship together with the template.

One idea suggested by the authors is to add a `dir` property that allows the authors to execute Terraform in a subdirectory and have the general files in the root directory.

**Comment by bpmct** [comment]
Do you want to avoid shipping the module as a part of each template? You could reference a module from a GitHub repo to avoid duplication and then just extend it or pass template-specific parameters 

```hcl
# template1/main.tf
module "consul" {
  source = "github.com/yourorg/central-coder-module"
  myparam = "custom-for-template1"
}

resource "ebs_volume` `custom_template1_only_resource ` {
}
```

```hcl
# template2/main.tf
module "consul" {
  source = "github.com/yourorg/central-coder-module"
  myparam = "custom-for-template2"
  myparam2 = "bar"
}

resource "aws_instance` `custom_template2_only_resource ` {
}
```

**Comment by trustycoder83** [comment]
Hi,

The module is locally and I would like to ship the module together with the template.

`
templates/
- modules/common
- template_1 (use the common module)
- template_2 (use the common module)
`

**Comment by pratheekrebala** [comment]
One [workaround that came up earlier](https://github.com/coder/coder/issues/5677#issuecomment-1383269901
) is to symlink the module directory inside the template directory and then `tar` ing the template. 

-  `ln -s modules template_1/modules`
- `tar -cvh -C ./template_1 | coder templates <push|create> -d - <name>`

FWIW: We were trying use this approach but switched to remote modules which we found easier to manage/version.

**Comment by bpmct** [comment]
Do you plan on managing all the projects in the same GitHub repo? If so, you could do the symlink or copy approach to include the module [if you push via CI/CD](https://coder.com/docs/v2/latest/templates/change-management).

**Comment by bpmct** [comment]
It seems a bit risky for Coder to have a feature that grabs/copies arbitrary files from outside of the directory you are in.

**Comment by kylecarbs** [comment]
I feel like we don't have great plans to fix this right now... and we wouldn't _want_ to stray away from Terraform primitives unless required.

Closing for now, but please feel free to contribute ideas! We're open to them :)
