### ISSUE TITLE
template editor: do not require default values, prompt for parameters instead 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6121]
It looks like our [dogfood](https://github.com/coder/coder/tree/main/dogfood) template is failing when I enter the template editor. 

I really would love if we prompted the user for parameters went the first build happens, just like "create workspace" and then remembers those for the session of the template editor. It's a good way to test all user inputs then the user could revisit the parameters and change. 

<img width="1312" alt="Screenshot 2023-02-08 at 3 34 36 PM" src="https://user-images.githubusercontent.com/22407953/217656187-84619b53-329f-4699-b99c-8f19d8534e5f.png">

Basic concept

<img width="1543" alt="Screenshot 2023-02-08 at 3 36 22 PM" src="https://user-images.githubusercontent.com/22407953/217656986-619392fa-ff87-4ae2-943a-3a9b11fcf0ff.png">

**Comment by BrunoQuaresma** [comment]
@bpmct just to make clear, we should ask the values when it is a new parameter, is required, and has no default value. Is that right?

**Comment by bpmct** [comment]
Yep :)

**Comment by BrunoQuaresma** [comment]
For this, I think I will do a similar flow to when a user update a workspace and it requires the user to input the new required parameters.

**Comment by BrunoQuaresma** [comment]
Based on @bpmct feedback since we are requiring default values it is not needed anymore.
