### ISSUE TITLE
template editor: folder support

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6122]
We have some example templates with folders, and they don't appear in the editor or file preview. 

- Create/delete folder
- See files in folders

<img width="1531" alt="Screenshot 2023-02-08 at 3 40 16 PM" src="https://user-images.githubusercontent.com/22407953/217657280-ed3d5f8e-9508-45c5-bcca-005cdb6c2a93.png">

<img width="278" alt="Screenshot 2023-02-08 at 2 08 41 PM" src="https://user-images.githubusercontent.com/22407953/217657390-07bf41d2-52f4-45f2-8a78-1b7bd6aa4828.png">

**Comment by bpmct** [comment]
This was partially resolved in #6145

**Comment by BrunoQuaresma** [comment]
@matifali yes! But there are a few bucks that I'm going to fix. Let me know if you find anything strange.

**Comment by BrunoQuaresma** [comment]
Closing this in favor of https://github.com/coder/coder/issues/6742
