### ISSUE TITLE
template editor: hide "used by `n` developers"

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6123]
<img width="561" alt="Screenshot 2023-02-08 at 3 41 51 PM" src="https://user-images.githubusercontent.com/22407953/217657547-6cede5ba-7f3f-4294-b3ae-f83e40a2c77d.png">

I don't think this looks great. If we want to keep it so that devs know they're doing something dangerous, we should just change the padding a bit

**Comment by BrunoQuaresma** [comment]
It was already removed!
