### ISSUE TITLE
template editor: custom version name & promote to default

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6124]
I'd love to be able to make non-default template versions as well as specify a custom name. With #5865/#3775, we could also let the user specify a message.

<img width="391" alt="Screenshot 2023-02-08 at 3 44 44 PM" src="https://user-images.githubusercontent.com/22407953/217658277-2a71abe8-c275-4c43-9605-b80d12bfbd10.png">

**Comment by kylecarbs** [comment]
I like the idea of a message format a lot. It'd be nice to display to the user as well!

**Comment by BrunoQuaresma** [comment]
@kylecarbs I can add a message field in the template version table if it is ok for you.

**Comment by BrunoQuaresma** [comment]
We can add the message later as a separated feature.

**Comment by kylecarbs** [comment]
@BrunoQuaresma that works for me. `message` is a reasonable name from my perspective!
