### ISSUE TITLE
Process exited status 229 errors since Coder 0.15.3

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#6126]
We've had 4 users complain with their workspaces randomly dropping off. Stopping and starting the workspaces fixes this.

E.g.:

```
$ coder ssh hai-plat-01
Process exited with status 229 
```

```
Received exit status from master 229
```

Both web and ssh is dysfunctional on the specific workspace when this happens.

What could be causing this?

**Comment by kylecarbs** [comment]
Is it possible the instances are OOMing? The agent being disconnected randomly shouldn't really be a thing...

**Comment by dcarrion87** [comment]
Hmmm I don't think so. 4 different use cases since we upgraded coder on Monday.

We unfortunately haven't closely monitoring since today so we didn't catch if they were old agent versions.

We're tracking it more closely but just raising it for now as it's causing a bit of noise / admin.

**Comment by dcarrion87** [comment]
Ended up being this: https://github.com/k3s-io/k3s/issues/6064

Sorry for the confusion
