### ISSUE TITLE
GitHub OAuth allowed teams

### ISSUE THREAD

**Issue by da00891219** [coder/coder#6127]
CODER_OAUTH2_GITHUB_ALLOWED_ORGS --> comma separated org list not taking effect
CODER_OAUTH2_GITHUB_ALLOWED_TEAMS --> when to use this? can we use comma separated teams? can we use both allowed_orgs and allowed_teams together?

our use case is - we configure OAuth App in one Org. And our users are part of another org in various teams, how can I allow them to login to coder.

**Comment by kylecarbs** [comment]
Are you sure the user you're authenticating with is in the organization? That's all we check for, nothing crazy. It can't be a user's username either, it has to be a GitHub org.

You can use `CODER_OAUTH2_GITHUB_ALLOWED_TEAMS` when you want to restrict access to Coder to a subset of an organization. The format `<org>/<team-slug>` is used. You're expected to have `<org>` in the comma-separated list specified in `CODER_OAUTH2_GITHUB_ALLOWED_ORGS`.

Let me know if that didn't answer your question!

**Comment by da00891219** [comment]
- name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
      value: "true"
    - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
      value: "X-CODER,X-KSA,X-IST" --> OAuth App configured in X-CODER, our users are part of X-KSA and X-IST
    - name: CODER_OAUTH2_GITHUB_ALLOWED_TEAMS
      value: "X-IST/dxdev,X-IST/x-y-z"

with this setting, it is still expecting user to be part of X-CODER where my OAuth is there. is this how it behaves or am I understanding it wrong?

**Comment by kylecarbs** [comment]
It allows the user to be a member of any listed orgs: `X-Coder`, `X-KSA`, and `X-IST`.

**Comment by da00891219** [comment]
ok undeerstood. currently we go with CODER_OAUTH2_GITHUB_ALLOWED_ORGS and not CODER_OAUTH2_GITHUB_ALLOWED_TEAMS. thanks for the update.
