### ISSUE TITLE
Coder Workspace Agent failing to install code-server

### ISSUE THREAD

**Issue by bashscr** [coder/coder#6140]
Version(s) tested: v0.13.1 - v0.17.1

Goal: I am working on creating a Template that will use an Ubuntu 20.04 Docker image to stand-up a code-server instance to be accessible via the browser. 

Issue: The Coder agent as described below, does not appear to run the initialization script - or it is silently failing. I've tried to look at the logs locations as mentioned in the documentation, but I was not able to find any log files. 

Snippet: 

```
resource "coder_agent" "dev" {
  os             = "linux"
  arch           = "amd64"
  dir            = "/workspace"
  startup_script = <<EOF
curl -fsSL https://code-server.dev/install.sh | sh
code-server --auth none --port 13337
EOF
}
```

I tried to follow the examples from here: https://github.com/coder/terraform-provider-coder/tree/main/examples as well as from here: https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app but wasn't able to get it working. It would show the VS Code as unhealthy as shown below.
![image](https://user-images.githubusercontent.com/51954831/217907190-73d58a00-f7e7-4d4c-9818-d44fedb7f077.png)
If I clicked on Terminal, and manually ran the installation part, then the VS Code button would start working.
```
curl -fsSL https://code-server.dev/install.sh | sh
code-server --auth none --port 13337
```

Randomly I will get errors as shown below. Also, not sure what seems to cause this, but the Terminal session will randomly freeze for 15 seconds or so, and sometimes disconnect unexpectedly. 
![image](https://user-images.githubusercontent.com/51954831/217907435-b3e78e1f-f1ae-48fe-bd8d-3f84c034f5e1.png)

**Comment by kylecarbs** [comment]
Do you have internet access? Check the contents of `/tmp/coder-startup-script.log`.

**Comment by bashscr** [comment]
It does have internet access, but it's in an environment where things are more locked down than usual - network wise.
```
coder@workspace:~$ cat /tmp/coder-startup-script.log
/bin/bash: $'sh\r': command not found
curl: (23) Failed writing body (487 != 1378)
/bin/bash: line 1: code-server: command not found
```

**Comment by kylecarbs** [comment]
@bashscr seems like you have Windows line endings on in your `main.tf` file. We could probably strip these when a template is uploaded anyways. In your VS Code, change the line ending format (it should be in the bottom right).

**Comment by bashscr** [comment]
> @bashscr seems like you have Windows line endings on in your `main.tf` file. We could probably strip these when a template is uploaded anyways. In your VS Code, change the line ending format (it should be in the bottom right).

That appears to have fixed it, thank you for spotting that! Any idea where I can start to investigate the random freezes on the site and Terminal windows?

**Comment by kylecarbs** [comment]
Is there any chance of resource contention? Seems odd.

**Comment by bashscr** [comment]
@kylecarbs Not that I can think of. Coder is the only thing running on a fresh t3a.xlarge instance on AWS.

**Comment by bashscr** [comment]
Closing this as the main issue has been solved.

**Comment by Inrixia** [comment]
> @bashscr seems like you have Windows line endings on in your `main.tf` file. We could probably strip these when a template is uploaded anyways.

Is stripping these line endings supported or planned to be supported? This is still a issue when editing templates via the coder webui in the latest version.
