### ISSUE TITLE
how to enable github copilot on projector intellij ide

### ISSUE THREAD

**Issue by da00891219** [coder/coder#6149]
I need to enable github copilot plugin on intellij ide, which installed using projector.

**The code I am using:**
`    

    # install projector into /home/coder
    PROJECTOR_BINARY=/home/coder/.local/bin/projector
    if [ -f $PROJECTOR_BINARY ]; then
        echo 'projector has already been installed - check for update'
        /home/coder/.local/bin/projector self-update 
    else
        echo 'installing projector'
        pip3 install projector-installer --user 
    fi
    echo 'access projector license terms'
    /home/coder/.local/bin/projector --accept-license 
    PROJECTOR_CONFIG_PATH=/home/coder/.projector/configs/intellij
    if [ -d "$PROJECTOR_CONFIG_PATH" ]; then
        echo 'projector has already been configured and the JetBrains IDE downloaded - skip step' 
    else
        echo 'autoinstalling IDE and creating projector config folder'
        /home/coder/.local/bin/projector ide autoinstall --config-name "intellij" --ide-name "${var.jetbrains-ide}" --hostname=localhost --port 8997 --use-separate-config --password coder
        # delete the configuration's run.sh input parameters that check password tokens since tokens do not work with coder_app yet passed in the querystring
        grep -iv "HANDSHAKE_TOKEN" $PROJECTOR_CONFIG_PATH/run.sh > /home/coder/temp && cp /home/coder/temp $PROJECTOR_CONFIG_PATH/run.sh
        chmod +x $PROJECTOR_CONFIG_PATH/run.sh 
        echo "creation of intellij configuration complete"
        
    fi

    # install JetBrains projector packages required
    sudo apt-get update && \
        DEBIAN_FRONTEND="noninteractive" sudo apt-get install -y \
        libxtst6 \
        libxrender1 \
        libfontconfig1 \
        libxi6 \
        libgtk-3-0 

    # start JetBrains projector-based IDE
    /home/coder/.local/bin/projector run intellij &

    # # enable github copilot on intellij community edition

`
**I am following below instructions:**
https://github.com/JetBrains/projector-installer/blob/master/COMMANDS.md

**Comment by sharkymark** [comment]
JetBrains no longer supports Projector and only recommend Gateway. Please see our docs.
https://coder.com/docs/v2/latest/ides/gateway
