### ISSUE TITLE
code-server window title - perhaps add some useful information to help identify it

### ISSUE THREAD

**Issue by garytaylor** [coder/coder#6150]
One of the huge advantages of coder for me is multi tasking - I can literally multi task between different projects, different branches of the same project etc.. all whilst maintaining the state so I can just carry on where I left off.

But, when using the web IDE - its hard to know which tab is which as the title doesn't contain any useful information (when opened in new tab using cmd-click on a Mac)

It would be really useful if it could contain something like the workspace title or anything to help identify it

**Comment by sharkymark** [comment]
The user and workspace name are identified in the URL of the IDE.

**Comment by bpmct** [comment]
Hmm yeah, looks like it shows the file and folder opened:

![Screenshot 2023-02-10 at 12 07 48 PM](https://user-images.githubusercontent.com/22407953/218164728-f68c3533-8449-463c-a1fe-18d6b1fb3ab4.png)

This is more of a limitation of code-server than Coder. Would you mind opening an issue in https://github.com/coder/code-server? Once added, you could do something like

```sh
code server --title "${data.coder_workspace.me.name} - code-server"
```
