### ISSUE TITLE
created workspace does not inherit the template's auto-off setting

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6157]
Version: [`v0.17.0+a5f3f02`](https://github.com/coder/coder/commit/a5f3f02ef8428dc26f7b670d11f634e01ab8f28e)

I have a template that defaults to auto-off to 2 hours.

![image](https://user-images.githubusercontent.com/2022166/218148156-898de865-bc90-4043-9f8b-d8307650e806.png)

I created a workspace in the CLI with the following command

`coder create nodeJS -t docker-code-server  -y`

In the UI, the new workspace is set to 8 hours. 

Is this a bug? Seems to defeat the purpose of template off settings

![image](https://user-images.githubusercontent.com/2022166/218148641-3d1c13f6-6998-499b-8ad3-b537b8256f7d.png)

![image](https://user-images.githubusercontent.com/2022166/218148404-8a1a5523-0901-47e0-8deb-b0e3560e5970.png)

**Comment by mtojek** [comment]
Taking a look

**Comment by mtojek** [comment]
Confirmed. If you create the workspace with CLI, it ignores user template settings. It works well if you use the site to create a workspace.

I will try to fix it, shouldn't be hard.
