### ISSUE TITLE
WebSocket connections

### ISSUE THREAD

**Issue by edqx** [coder/coder#6162]
Hi, I followed a comment on how I can get cross-site requests working: https://github.com/coder/coder/issues/5706#issuecomment-1382137314.

This works fine for HTTP requests:
![image](https://user-images.githubusercontent.com/60631511/218194950-e88c0fa5-d496-49e1-a80b-36c438fdadd9.png)

But WebSocket connections do not work the same way:
![image](https://user-images.githubusercontent.com/60631511/218195029-1500c484-b8ed-4e10-b355-b65f69ccbb75.png)
The "Location" header just tells me to move to the same address but using the https:// protocol.

I have the following config in my nginx:
```nginx
location /rt/ {
    proxy_pass http://127.0.0.1:5175/;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```
But I don't think this will help all that much.

Is there anything tracked about this or something that I can do to get WebSocket requests working?

Thanks.

**Comment by kylecarbs** [comment]
Is the nginx server running in front of your Coder deployment?

I tested WebSockets over a wildcard URL just to sanity check, and all worked as expected.

**Comment by edqx** [comment]
Hi,

Nginx running inside the docker container. Is this wrong? If so, how can I expose the ports from my docker container workspace so that I can run my app on my host? I would have no need for nginx if I can do that.

Thanks for responding so quick.

**Comment by edqx** [comment]
I will say that I don't think this is a cross-site issue, and more just an issue with WebSocket in Coder entirely. I can't access my site's HMR/Live-Reload socket that SvelteKit runs on the same port.
![image](https://user-images.githubusercontent.com/60631511/218263103-74d4ff1e-85c2-4597-b440-302d61b4d7cf.png)
![image](https://user-images.githubusercontent.com/60631511/218263126-ee58fc20-7bbe-4ec4-80ba-b4a3d869524b.png)

**Comment by edqx** [comment]
So that last one with the HMR WebSocket was an nginx config issue. I fixed it by following this StackOverflow thread: https://serverfault.com/questions/910805/proxy-websockets-and-http-through-the-same-location-in-nginx
Which gives me this nginx config:
```nginx
server {
       listen 80;
       listen [::]:80;

       server_name _;

       location /auth/ {
               proxy_pass http://127.0.0.1:5174/;
       }

       location /rt/ {
               proxy_pass http://127.0.0.1:5175;
               
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "Upgrade";
               proxy_set_header Host $host;
       }

       location / {
              try_files /nonexistent @$http_upgrade;
       }

       location @websocket {
              proxy_pass http://127.0.0.1:5173;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              proxy_set_header Host $host;
       }

       location @ {
              proxy_pass http://127.0.0.1:5173;
       }
}
```

Unfortunately the original problem with the /rt path still isn't working, which is odd since it's on the same origin, just a different path.

**Comment by edqx** [comment]
Oof, I think I've fixed it:
![image](https://user-images.githubusercontent.com/60631511/218264982-b137f7d6-e479-464a-9f13-950190700860.png)

Looked like a slightly goofy/annoying HTTP technicality. My config only accepted requests to /rt/ but my site was connecting to /rt. So make sure you're connecting to _exactly_ the right address.

This looked like two separate issues that I assumed came from the same place, entirely my fault.

Hope this helps anyone else.
