### ISSUE TITLE
feature request: per-user variable defaults

### ISSUE THREAD

**Issue by DeCarabas** [coder/coder#6163]
The coder v2 way of configuring your dotfiles is to specify a repository URL as a template variable, but that means that folks who want to spin up multiple workspaces have to re-enter their repository URL multiple times. 

The same goes for selecting a region: it would be nice if an engineer could specify a default region for all of their workspaces, rather than having to select the correct one every time.

Today I can specify a default in a template, but as a user I can't customize that default for myself.

**Comment by kylecarbs** [comment]
We should probably just remember and pre-fill variables if a user is creating another workspace using the same template.

**Comment by DeCarabas** [comment]
Is this something you're considering?

**Comment by matifali** [comment]
This is planned. @bpmct can share more details.

**Comment by matifali** [comment]
related to #7280 #7087 #6536 #6636

**Comment by matifali** [comment]
closing in favour of #7087
