### ISSUE TITLE
feature request: Workspace Deletion Protection/Delayed Deletion

### ISSUE THREAD

**Issue by MichaelGerhart** [coder/coder#6166]
<ins>Feature Request Summary</ins>

As an Enterprise Customer, we are required to have safe guards to prevent our users from accidentally deleting their work. In our organization in particular, we onboard and separate from contracted resources frequently who may not be familiar with a solution like Coder, and may accidentally delete an active workspace.

<ins>Feature Proposal</ins>

Implement functionality to allow administrators to define a global policy and enable deletion protection for a certain amount of time across all workspaces. This includes keeping the PVC intact in the case of Kubernetes workspaces until the TTL for the policy is reached.

This would solve a couple of problems

- Recovery in the event a user mistakenly deletes a workspace
- Potential Ability for security to conduct at least partial forensic investigations should malicious activity have occurred within the workspace (Particularly by not deleting the persistent volume)

As an example of this, both GitLab and GitHub implement similar functionality for Git repositories, where an administrator can enable a policy for 'soft-deletion' and recover the repository if it was mistakenly or maliciously deleted.

**Comment by sharkymark** [comment]
@bpmct I'm reopening
