### ISSUE TITLE
template editor: clicking `Publish New Version` button in template edit screen doesn't take user back to template screen

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#6169]
clicking the `Publish New Version` button doesn't take the user away from the screen. i have to manually navigate out of the edit view and click back into the template to ensure it's been updated. the button does, however, publish the new template version in the back-end.

<img width="566" alt="Screenshot 2023-02-11 at 10 18 22 PM" src="https://user-images.githubusercontent.com/9683576/218291045-612201ee-510e-404e-8702-17e2b790263f.png">

**Comment by bpmct** [comment]
I wouldn't consider this a bug, but I see how the experience can be a bit jarring.

In ReTool, for example, after creating a new release, the user is still in "edit mode." If this decision was intentional (to keep the user in the editor), perhaps we could show a notification 

> A new template version has been published: [View template](#)
