### ISSUE TITLE
Alternative login such as webauthn

### ISSUE THREAD

**Issue by sfxworks** [coder/coder#6170]
It would be cool if I could login using a yubikey instead of just a password or by another means such as putting an openid server infront of the code server.

**Comment by matifali** [comment]
you can alreadiy use any OIDC, and GitHub/Gitlab login. Also there is support for SSO.
Yubikey should work if your OIDC or SSO provider supports that.

Suporting  a 2FA or hardware keys natively can also be cosidered. This sounds interesting.

**Comment by WOLFI3654** [comment]
https://tools.ietf.org/html/rfc3875#section-4.1.10

This rfc could be worth considering as well. It enables the use of any auth front like authelia and similar, which itself can support keys etc.

**Comment by kylecarbs** [comment]
@WOLFI3654 neat. We should certainly allow for something like this.

**Comment by sfxworks** [comment]
> you can alreadiy use any OIDC, and GitHub/Gitlab login. Also there is support for SSO. Yubikey should work if your OIDC or SSO provider supports that.

I was suggesting direct integration in my original comment.

**Comment by bpmct** [comment]
Not sure when we'll get to this at this point, but open to contributions in the meantime :)

**Comment by kylecarbs** [comment]
Closing in favor of #5705
