### ISSUE TITLE
Refactor coder agent SSH server for better process and connection control

### ISSUE THREAD

**Issue by mafredri** [coder/coder#6177]
This is, in part, to better support `shutdown_scripts` as part of #4677 and #6139. But improved user experience is also a big factor.

**Problem:** Even though the coder agent initiates a graceful shutdown, the SSH connections are abruptly closed leaving SSH clients hanging. Similarly any process started inside an SSH session will be left running (e.g. `sleep 1000 &`) after the SSH server is closed.

To improve upon this, we need to:

- [ ] ~~For all active sessions with TTYs, print a message that the workspace is closing~~
	- Let's defer this, see https://github.com/coder/coder/issues/6177#issuecomment-1471324332
- [x] https://github.com/coder/coder/pull/7027
- [ ] Send an interrupt (e.g. `SIGHUP`) to the commands/shells started via SSH
	- [ ] Wait for processes to exit (for some amount of time)
	- [ ] Sens `SIGKILL` to the remaining processes
- [ ] Stop accepting new SSH connections (potentially allow `--debug` or similar flag overrides)
- [ ] Do not run `shutdown_script` until the above is complete
- [x] https://github.com/coder/coder/pull/7004

~~I think it would make sense to refactor SSH functionality for the agent as a separate package, e.g. `agentssh` or `agent/sshd`.~~ See list above.

Future work/ideas:

- Consider forking/forkexec `coder agent` to manage new SSH connections
	- This could allow the coder agent to be updated without terminating active connections

**Comment by spikecurtis** [comment]
> For all active sessions with TTYs, print a message that the workspace is closing

I recall that Jetbrains Gateway requests a PTY when they SSH to run commands.  So, I don't think the presence of a PTY is a reliable indicator that you have a human with a shell on the other end.  Printing stuff could have undesirable effects.
