### ISSUE TITLE
As an operator, how will I know if one of my users runs into an error?

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6181]
As an operator, I want to understand when my users are running into issues. What are the recommended ways to monitor the following events?

- User connection drops (e.g. disconnected over SSH, coder_app, web terminal)
- `agent<->server` connection drops (related #5901)
- `agent<->server` connection never starts in the first place (related #4052) 
- Workspace build failures (e.g. validation error, cloud quota error)

This is related to #4877 (there's a lot of great discussion in here) and #6154, but wanted to understand what metrics we may still need to expose and "best practices" we may need to promote/document.

**Comment by mtojek** [comment]
I identified the following areas to observe but didn't review existing metrics. I'd rather focus on ensuring that the final state will satisfy operational needs. I would appreciate your help, @bpmct, in rearranging the order in terms of priorities.

1. Application (restarts, memory usage, GC, threads, panics?)
2. Network activity
   1. Coderd: HTTP traffic, SSL certificate expiry, traffic between agent and Coderd.
   2. Workspace agent: forwarded ports, traffic between agent and user, active SSH connections, active websocket connections (in-flight, errors).
3. Agent health (`status: "connected"`, restarts, startup/dotfiles issues, shutdown issues)
4. Applications (`health: "healthy"`)
5. Provisioner jobs (`status: "success"`, duration, waiting time, error types)
6. Provisionerd health (status, errors, restarts?)
7. Template updates (events)
8. Workspace builds (events, status, errors, time-to-build, outdated workspaces, used disk quota, orphans?)
9. API operations (in groups, latency, status code)
10. Authorization (success, auth provider errors)
11. Database connections (in-flight connections, errors)
12. DB AuthZ violations - bugs discovery, and security violations 

@coadler Could you please share how flexible is Tailscale in terms of metrics collection? Does it expose any networking data out of the box?
@johnstcn Which metrics can be helpful in bug hunting for incorrect/insufficient permissions, or security violations?

What we can do next is split the list into smaller groups or single issues, and start collecting metrics in various places. Once we have good coverage, we can prepare a [dashboard](https://github.com/coder/coder/issues/6154).

**Comment by johnstcn** [comment]
> Agent health (status: "connected", restarts, startup/dotfiles issues, shutdown issues)

Agent health flapping is definitely a useful measure.

> Applications (health: "healthy")

Useful for operators, but this should be strictly divorced from overall Coderd health, as a badly-behaved application could lead to a lot of noise here.

> Which metrics can be helpful in bug hunting for incorrect/insufficient permissions, or security violations?

Any `http.StatusUnauthorized` response, but there's some additional pieces we could add here:
- Is the error a `NoActorError`? This indicates that we're not seeing the actor correctly in context on a particular route.
- We already log internal information on failed authz checks, this is already [logged](https://github.com/coder/coder/blob/main/coderd/database/dbauthz/dbauthz.go#L58-L62) but could be exposed in other places (e.g. prometheus)

**Comment by mtojek** [comment]
Thanks for your input!

> Useful for operators, but this should be strictly divorced from overall Coderd health, as a badly-behaved application could lead to a lot of noise here.

It might be hard to distinguish whether this is a problem with a single application instance or it is a bad deployment affecting all users. Probably it's something we can figure out before jumping on this topic.

> We already log internal information on failed authz checks, this is already [logged](https://github.com/coder/coder/blob/main/coderd/database/dbauthz/dbauthz.go#L58-L62) but could be exposed in other places (e.g. prometheus)

That is cool! It's exactly what I was looking for 👍

**Comment by bpmct** [comment]
Here's how I'd sort these things by priority. Marked my notes with 📓.

I also drew a line from what I could consider "critical" day-to-day things versus more nice-to-have. Perhaps the second batch are important as they can give insights into how other errors are occurring though

1. Application (restarts, memory usage, GC, threads, panics?)
  - 📓 We found during scale tests that [workspace builds are CPU intensive](https://coder.com/docs/v2/latest/admin/scale#concurrent-workspace-builds). I know the Coder application won't provide these metrics, but can we ship in a default Kubernetes/Coder Prom dashboard, or document that it's a key metric?
1. Network activity
    1.. Workspace agent: forwarded ports, traffic between agent and user, active SSH connections, active websocket 
connections (in-flight, errors).
      - 📓 A customer has requested being able to measure when a connection (SSH, web terminal, websocket) is unstable or wants to receive events when a user disconnects unexpectedly. If possible, this is important. #5122
   1. Coderd: HTTP traffic, SSL certificate expiry, traffic between agent and Coderd.
      - 📓 Not sure how important it is for Coder to help with SSL cert expiry. Would be hesitant for us to show this unless other software does this.
1. Workspace builds (events, status, errors, time-to-build, outdated workspaces, used disk quota, orphans?)
    - 📓 What is the best way to create an event when a build fails? I think this should be "MVP"?
    - 📓 Understanding how many (concurrent) builds are occurring and how that relates to CPU seems very important.
1. Agent health (`status: "connected"`, restarts, startup/dotfiles issues, shutdown issues)
    - 📓 What is the best way to create an event when an agent disconnects? #5121
    - 📓 This is something I'd want to track over time

---

1. Provisioner jobs (`status: "success"`, duration, waiting time, error types)
    - 📓 Would love to understand how long each build takes via metrics, seems like a good way to identify timeouts and oddities. Maybe the job ID could've used to find the logs for a long build?
    - 📓 During scaletests, I remembered @coadler using graphs to determine whether provisioners are evenly getting jobs or if they are contended. (I think across multiple replicas too). 
1. Database connections (in-flight connections, errors)
    - 📓 We see this is often linked to dev URL traffic, provisioning jobs, etc.
1. Provisionerd health (status, errors, restarts?)
    - 📓 What is the difference between a provisionerd error and a provisioner job error
1. Applications (`health: "healthy"`)
1. Template updates (events)
1. API operations (in groups, latency, status code)
1. Authorization (success, auth provider errors)
1. DB AuthZ violations - bugs discovery, and security violations

**Comment by bpmct** [comment]
Going to close this out. There's some good brainstorming in here, but it's not really actionable.
