### ISSUE TITLE
Use a Terraform network mirror

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6189]
Currently, you can set a network mirror with Coder by [building a custom Coder image](https://coder.com/docs/coder-oss/latest/install/offline). Perhaps we could add a Coder server flag to do this instead, to make setup easier?

**Comment by bpmct** [comment]
With helm volume mounts, we could also support a filesystem mirror

**Comment by johnstcn** [comment]
There's also a handy [terraform providers mirror](https://developer.hashicorp.com/terraform/cli/commands/providers/mirror) command which will grab all of the required providers from a given dir.
