### ISSUE TITLE
Remove `wsconncache` in favor of running a single Tailnet

### ISSUE THREAD

**Issue by coadler** [coder/coder#6191]
`wsconncache` is a package for caching Tailnets within `coderd`, used for proxying the web terminal and web IDEs. It is written such that a new Tailnet is created for every agent connection, which isn't ideal. Instead, we can use a single Tailnet in each `coderd` which has all recently accessed agents as peers. Agents will be removed as peers from the Tailnet in the same way that `wsconncache` would purge old Tailnets.

**Comment by mtojek** [comment]
@coadler Could you please add more description to this issue to describe the scope? Also, what is the progress here?

**Comment by spikecurtis** [comment]
Dupes #8218
