### ISSUE TITLE
Allow admins to SSH into other people's workspaces on CLI

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#6196]
As part of automatically migrating workspaces from v1 -> v2, an admin account needs to be able to SSH into the v2 workspace to transfer v1 files over.

Right now the CLI hard-codes `me` as the user when you attempt to ssh to a workspace.

**Comment by coadler** [comment]
I believe this works already
![image](https://user-images.githubusercontent.com/6332295/218821215-ed1bf86e-6e6e-41dc-882b-78d9ec74eb20.png)

**Comment by spikecurtis** [comment]
Nice!
