### ISSUE TITLE
CLI Experience

### ISSUE THREAD

**Issue by tjcran** [coder/coder#620]
This is a top level epic to track enhancements or bugs for the CLI experience through our major v2 milestones. 

-----

- [x] https://github.com/coder/coder/issues/512
- [x] https://github.com/coder/coder/issues/776
- [x] https://github.com/coder/coder/issues/777
- [x] https://github.com/coder/coder/issues/778

**Comment by ketang** [comment]
Gonna close this as done because I don't thing the Enterprise CLI experience will differ much.  It'll just be more.
