### ISSUE TITLE
feature: auto-sign git commits using s/mime

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#6204]
# Idea:

Automatically configure GPG commit signing for workspaces.

Similarly to how we override the `GIT_ASKPASS` environment variable to magically inject Git auth credentials, we could leverage [S/MIME commit signature verification](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#smime-commit-signature-verification) to automatically sign all commits with the SSL certificate used by Coder. There may be some environment variable we can hook into with gpgsm to perform this.

**Comment by matifali** [comment]
Why not use the coder ssh key to sign commits?

**Comment by phorcys420** [comment]
> Why not use the coder ssh key to sign commits?

I think this should be prioritized as it is the easiest to implement right now.
see #8922
