### ISSUE TITLE
Template is not created

### ISSUE THREAD

**Issue by suksest** [coder/coder#6215]
I'm using version v0.17.3+15c862f and an external PostgreSQL database with version 15.

I was trying to create a new template using the `coder template create` command.
Then I got this error message `unexpected non-JSON response "text/plain; charset=utf-8"` and the logs say `sent CompletedJob     {"job_id": "xxxx-xx-xx-xx-xxxxxx"}`. So I checked the `provisioner_jobs` table, and there is `NULL` in the `error` column with the related `job_id`.

Is there any workaround to fix this? Thanks

**Comment by bpmct** [comment]
👋🏼 I'm not able to reproduce this. Is your CLI version the same as the server version? (If you're calling `coder` on the same machine as the server, it is the same)

**Comment by bpmct** [comment]
@matifali ran into this as well on a new deployment.

**Comment by bpmct** [comment]
@suksest It might be possible you don't have websockets enabled. Can you check #5429?

**Comment by matifali** [comment]
> @matifali ran into this as well on a new deployment.

I confirm it happens when WebSocket connectivity is not available.
Please check our example docs on setting a [reverse-proxy](https://github.com/coder/coder/tree/main/examples/web-server)

**Comment by suksest** [comment]
It was our problem with reverse-proxy configuration. It is solved now. Thanks
