### ISSUE TITLE
tokens: add the ability to name API tokens

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#6219]
It is difficult to identify tokens when looking at the output of `coder tokens ls`. If there are multiple tokens in the list, the only way to tell them apart currently is by looking at the token ID, which is not human-readable. We should give users the ability to name tokens during creations, e.g. `coder tokens create --name=devops`.

If a user doesn't specify a name during token creation, that token should be given an auto-generated name (similar to template version). 

No two tokens should be allowed to have the same name.

Finally, the `coder tokens rm` command should be tweaked such that you delete by name - not by ID. Deleting by ID is confusing because the ID is an abbreviation of the token itself, and deleting using the full token name doesn't work.

**Comment by Kira-Pilot** [comment]
@bpmct yesterday we chatted about adding a different ID for tokens. I think the returns are diminishing here after this ticket is implemented - I personally wouldn't be confused by the abbreviated ID were I not deleting by the ID. 
Does that sound right to you?

**Comment by bpmct** [comment]
yep! all sounds great.
