### ISSUE TITLE
bug: incorrect login attempt via built-in auth takes user back to login screen

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#6224]
running `0.17.3`. while attempting to login via built-in auth, i incorrectly entered my username/password. i was redirected to this screen:

![image](https://user-images.githubusercontent.com/9683576/219169496-102f9cc6-6e83-4547-bb52-c8be0706a2d7.png)

this did not tell me that my login attempt was unsuccessful. i then clicked back into `Email and password`, where it showed me the unsuccessful message:

![image](https://user-images.githubusercontent.com/9683576/219170380-4ae708d8-e8ea-49b7-b5c1-35c1806539ce.png)

**Comment by sharkymark** [comment]
Ditto, very confusing, the failed login message should be visible immediately

**Comment by BrunoQuaresma** [comment]
Fixing it right now.
