### ISSUE TITLE
docs: Yubikey commit signing

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6226]

**Comment by matifali** [comment]
We should also document, how to do ssh commit signing using the coder ssh key. 
gpg and s/mime signing also.

**Comment by jaulz** [comment]
@matifali yeah, that would be great. Do you have something at hand how it can be added today?

**Comment by matifali** [comment]
> @matifali yeah, that would be great. Do you have something at hand how it can be added today?

GPG agent forwarding and yubikey commits are basically one in the same.
The Yubikey basically stores the gpg keys and instead of them being on a workspace/local machine.

you could try `coder ssh --forward-gpg`

**Comment by matifali** [comment]
We have a [community module](https://registry.coder.com/modules/git-commit-signing) that allows you to sign commits using the coder SSH key.

**Comment by bpmct** [comment]
Closing in favor of https://github.com/coder/coder/issues/12023 which has some more details
