### ISSUE TITLE
State of rich parameters in 0.17

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#6230]
Been watching all the great progress on rich parameters in release notes. Is it currently guarded behind experimental flag?

Just wondering when it's to be in a relatively stable state that it could start being used by everyday users? E.g. Could we start using it with users now or there likely to be a break in subsequent releases.

Not even sure how to actually make a template that has rich params 🤔 .

**Comment by mtojek** [comment]
Hi @dcarrion87, thanks for opening the issue.

> Is it currently guarded behind experimental flag?

The flag introduced in https://github.com/coder/coder/pull/6134 is intended to distinguish strategies for processing TF variables. If template admin switches to rich parameters (vel `coder_parameter`), TF variables can be exclusively used as managed variables without "hacking" them into parameters.
Currently, the idea is to have an experimental feature flag, but eventually, we will enable this strategy by default.

> Just wondering when it's to be in a relatively stable state that it could start being used by everyday users?

Currently, we're working on https://github.com/coder/coder/issues/5980 to finalize work around managed variables. We'd like to [make rich parameters optionable](https://github.com/coder/coder/issues/6100) too, as we identified this as a gap to ensure feature parity with legacy parameters.
I'd wait with migrating prod users until we have feature parity, but feel free to try rich parameters on isolated/test workspaces.

> Not even sure how to actually make a template that has rich params 🤔 .

We didn't advertise them yet as there is some work planned, but you can always take a look at the examples in the [terraform-provider-coder](https://github.com/coder/terraform-provider-coder/blob/main/examples/resources/coder_parameter/resource.tf) repository.  Eventually, we will convert examples in the coder repo too.

**Comment by dcarrion87** [comment]
Awesome stuff. Thanks for clarifying!

**Comment by bpmct** [comment]
I've created https://github.com/coder/coder/milestone/11 which tracks this effort :)
