### ISSUE TITLE
Can not delete workspace if there is an pending update

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#6240]
# Description

A click on button delete workspace has no effect if there is an outstanding update.

![image](https://user-images.githubusercontent.com/103434584/219444393-c87426a2-3112-4bca-a2b5-8c7c963e0d8c.png)

The confirmation dialog does not popup. Nothing visible happens.

When update was applied then i can delete the workspace.

# Version

coder 0.17.3

**Comment by kylecarbs** [comment]
We'll definitely fix this. Thanks for the report! :partying_face:

**Comment by BrunoQuaresma** [comment]
Good catch!

**Comment by matifali** [comment]
Hi, @MrPeacockNLB I can not reproduce on `0.23.2`. So closing as completed. Please feel free to create another issue if you still face this.
