### ISSUE TITLE
iPad trackpad two-finger scroll

### ISSUE THREAD

**Issue by JGantts** [coder/coder#6247]
On my iPad Air (5th generation) two-finger scroll with a trackpad consistently does not work. Two-finger scroll works in other apps and on other webpages on the same iPad.

Scrolling with a finger on the screen like normal *does* work.

Note: regular scrolling by touching the screen normally has inertia, but on the coder-server (VSCode? I’m not sure of my terminology) there is no inertia

**Comment by JGantts** [comment]
Two-finger scrolling with a trackpad on an iPad also doesn't work on the google docs web app

It does however work on the google docs native app (for iPad)

**Comment by JGantts** [comment]
Just poking around with the safari debugger (debugging iOS/iPadOS safari requires using a desktop safari instance). Two-finger scrolling on the trackpad on my iPad *does* cause a WheelEvent to be fired

(Tested on my personal site’s code in my dev environment. It’s Vue)

**Comment by kylecarbs** [comment]
https://github.com/coder/code-server/issues/5971

This is the issue that will have better updates!

**Comment by kylecarbs** [comment]
@JGantts it's an unfortunate thing that hasn't been fixed for forever :(

**Comment by JGantts** [comment]
Would it be worth my while to investigate and attempt to contribute? Or is a known “pain point” that’s difficult to fix without major rewrites?

**Comment by kylecarbs** [comment]
I believe it's a bug in WebKit... I haven't looked at that issue for a while though, so it's possible another issue is in play.

**Comment by JGantts** [comment]
Dang, well thank you! :-)
