### ISSUE TITLE
bug: in air-gapped kubernetes cluster, coderd deployment crashloops

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#6258]
Observed during customer call: get UI error "something went wrong" intermittently.
Appears to only happen on air-gapped cluster that cannot access internet.

Steps to reproduce (reproduced on OpenShift 4.12 single-node):
- Install Coder in Kubernetes via Helm Chart
- Create NetworkPolicies that only allow traffic within the cluster
- Observe coder pod crashing periodically with following message:
  ```
  Unexpected error, shutting down server: install terraform: install: Get "https://releases.hashicorp.com/terraform/1.3.4/index.json": dial tcp 143.204.68.20:443: i/o timeout
  ```

**Comment by bpmct** [comment]
there's also flickering on the deployment due to the check for updates... should we use a different ticket to track that?

**Comment by BrunoQuaresma** [comment]
@johnstcn is it at a specific route?

**Comment by johnstcn** [comment]
@BrunoQuaresma it's `/api/v2/workspaces/$WORKSPACE_ID/watch`

**Comment by johnstcn** [comment]
https://github.com/coder/coder/pull/6541
