### ISSUE TITLE
bug(docs): Documentation regarding custom DERP relays is misleading

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#6259]
Our current docs say:

https://coder.com/docs/v2/latest/networking#custom-relays

> If you run Coder in air-gap mode or want lower latency than what Tailscale offers, you may run custom DERP servers. Refer to [Tailscale's documentation](https://tailscale.com/kb/1118/custom-derp-servers/#why-run-your-own-derp-server) to learn how to set them up.

This implies that they are _necessary_ if running in air-gapped mode, which is not the case. Reword.

**Comment by bpmct** [comment]
Fixed in #6418
