### ISSUE TITLE
Better error if no git providers are configured

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6264]
If no git providers are configured, we so this and then ask the user to authenticate. Could we show a better message here and link to our docs or tell them how they can disable this for their workspace?

![Screenshot 2023-02-17 at 11 31 39 AM](https://user-images.githubusercontent.com/22407953/219741034-afe73843-7786-4409-a7fd-0653549eeb0c.png)

...or just show nothing?

**Comment by Emyrk** [comment]
Can you put repo steps down? The git provider like in the template?

**Comment by bpmct** [comment]
Nope deployment wide. You should be able to reproduce by running a git clone (of a private repo) on a fresh Coder deployment

**Comment by Emyrk** [comment]
I think this is kinda hard to solve.

I assume the git project was already in the workspace before the user is allowed in. So they do a `git pull/push/fetch` and it fails. 

It would be hard to make a general solution of providing a better error or resolution steps. That would require us to implement something in the workspace, like a bash script or something. No?

**Comment by bpmct** [comment]
> I assume the git project was already in the workspace before the user is allowed in. So they do a git pull/push/fetch and it fails.

If there were no git providers configured in the deployment, couldn't we hide the "no git provider found for URL" error and let git do its thing?

**Comment by Emyrk** [comment]
Ahhh I see where that error comes from. Let me try something....

**Comment by Emyrk** [comment]
This has been fixed:
```bash
admin@testttt:~$ git clone git@github.com:Emyrk/private.git
Cloning into 'private'...
git@github.com: Permission denied (publickey).

Coder authenticates with  git  using the public key below. All clones with SSH  
are authenticated automatically 🪄.                                             

 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILsngc6yXRDoOFfbhRxZkt1gXf+A5LHxgWt8xR38LT+S 

Add to GitHub and GitLab:
> https://github.com/settings/ssh/new
> https://gitlab.com/-/profile/keys

exit status 255
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
