### ISSUE TITLE
Support multiple vs code channels for "VS Code Desktop" button

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#6267]
Currently, the "VSCode desktop" button only supports VSCode stable because the URI handlers differ (``vscode://coder.coder-remote/open[...]`` needs to be ``vscode-insiders://coder.coder-remote/open[...]`` in my case).

I think Coder should also support opening in different IDEs if you're going to support different VSCode channels anyways.

It'd be nice to be able to set something like "editor preference" in user settings with a tickbox to persist or not accross browsers.

**Comment by matifali** [comment]
I recently switched to vscode insiders channel and can not more use the VS Code Desktop Button.

I see the URI is being set here,

https://github.com/coder/coder/blob/87784493e89563a244079e4c3d4195aa0638b6aa/site/src/components/VSCodeDesktopButton/VSCodeDesktopButton.tsx#L39

I suggest one of the following approaches to solve this.

1. We should try both `vscode:` and `vscode-insider:` 
2. Allow the users to configure the default vscode channel in (not yet available account wide settings #7272 #7280 #2387) 
3. Display both of the buttons (Vs Code and VS Code Insider) simultaneously.

cc: @phorcys420 @bpmct @kylecarbs

**Comment by phorcys420** [comment]
I'm all in for the second approach.

> We should try both ``vscode:`` and ``vscode-insider:``

I personally have both installed, which would make it annoying.

> Display both of the buttons (Vs Code and VS Code Insider) simultaneously.

I guess this would be fine but is kind of visually bothering, and it wouldn't be a proper way to do it in the long run if we want to  add other IDEs (thinking about jetbrains IDEs for example)

---

We could also let the template set a preferred desktop IDE.
Something like a property that'd define the URI.

For example, the "python-dev" template could set PyCharm, the "js-dev" one could set WebStorm, etc.

---

I see you've renamed the issue to reflect VSC channels only, but I'd like to see support for separate IDEs too.

**Comment by phorcys420** [comment]
> IMO, IDE should always be a developer preference instead of templates. We should not force an IDE on a developer.

I agree -- but in some cases having a different "recommended IDE" could be useful, although I think it could just be defined as a ``coder_app`` now that I think about it.

**Comment by matifali** [comment]
As a workaround, I am able to use VS Code Insiders using the Coder Remote Extension.
