### ISSUE TITLE
Wildcard apps in the Coder tunnel quickly run out of characters

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6268]
I've seen several cases where an app exceeds the character length. Often with the tunnel. Can we both:

1. Reduce the character count of wildcard apps
2. Display an error on the frontend if some app (e.g. `supercalifragilisticexpialidocious-pneumonoultramicroscopicsilicovolcanoconiosis ` + access URL exceed the URL length)?

It looks like a subdomain can only be 63 characters?

**Comment by matifali** [comment]
Hi, @bpmct  this is a serious P1 bug and should be addressed. Commenting for activity.
