### ISSUE TITLE
Group's quota allowance can be exceeded 

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6271]
Version: [`v0.17.3+15c862f`](https://github.com/coder/coder/commit/15c862fcb5316cedd750291eb0ab10c96004e2bf)

A group has a quota allowance set to 30.

![image](https://user-images.githubusercontent.com/2022166/219828351-c9b82d94-b872-42cf-8b70-9ebb90b06376.png)

A PyCharm template has two resource `daily_cost` of `20` (pod) and `10` (pvc)

![image](https://user-images.githubusercontent.com/2022166/219828366-871c9e5e-704c-4fa0-94f7-5710affca38c.png)

I am able to create two PyCharm workspaces with the same user.

![image](https://user-images.githubusercontent.com/2022166/219828373-dccfa9b4-0894-44f1-9d46-060e6c6761e9.png)

The build log data show it did not stop the build.

![image](https://user-images.githubusercontent.com/2022166/219828396-98b78188-1566-497c-8e44-bbf6736ddfc8.png)

**Comment by sharkymark** [comment]
I think this is by design, since I have another group the user belongs to, who has 30 allowances, so if the template in that group was not built, I had 60 points. Closing this out. Still a confusing thing.

**Comment by ammario** [comment]
Perhaps fixed by https://github.com/coder/coder/issues/5181

**Comment by ammario** [comment]
A UI here would help too. We should show how the quota is derived.
