### ISSUE TITLE
Not loading .bashrc when connection via ssh

### ISSUE THREAD

**Issue by devskar** [coder/coder#6273]
The .bashrc is not getting loaded after just logging in. You have to change your user first so bash actually loads it.
(sourcing of nvm is configured in .bashrc)

```shell
oskar@test-nvm:~$ nvm
bash: nvm: command not found
oskar@test-nvm:~$ sudo su oskar
oskar@test-nvm:~$ nvm -v
0.39.3
```

**Comment by atsai1220** [comment]
Was there a fix? Experiencing the same in `v0.19.2`

**Comment by devskar** [comment]
@atsai1220 I just created the .bashrc file by hand or copied it from /root/.bashrc or some shady solution

**Comment by waza-ari** [comment]
In case anyone else stumbles across this:

For login shells (like virtual terminals), Ubuntu doesn't run `.bashrc` by default, it runs `.profile`. See also this [StackOverflow question](https://askubuntu.com/a/161274) for more details.

Two options:

1. Create a `.profile` which loads `.bashrc`. This is normal Ubuntu behaviour, but the `.profile` file is missing on coder workspaces by default:

```
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
```

2. Put the commands (like path modifications for NVM) directly in `.profile`.
