### ISSUE TITLE
Upgrade Conflict

### ISSUE THREAD

**Issue by djarbz** [coder/coder#6275]
I am attempting to update to the latest version and it is failing because the new version conflicts with the currently installed version.

```bash
[root@coder ~]# curl -L https://coder.com/install.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15986  100 15986    0     0  41625      0 --:--:-- --:--:-- --:--:-- 41625
Fedora Linux 37 (Container Image)
Installing v0.17.3 of the amd64 rpm package from GitHub.

+ Reusing ~/.cache/coder/coder_0.17.3_linux_amd64.rpm
+ rpm -i ~/.cache/coder/coder_0.17.3_linux_amd64.rpm
        file /usr/bin/coder from install of coder-0:0.17.3-1.x86_64 conflicts with file from package coder-0:0.17.1-1.x86_64
```

**Comment by kylecarbs** [comment]
Humph, I'm not sure why this would be happening. Try uninstalling Coder and then installing the new version.

**Comment by djarbz** [comment]
I think that there needs to be some logic to see if the package is already installed and would be considered an upgrade.
Per this [thread](https://unix.stackexchange.com/questions/411740/rpm-install-file-conflict-from-previous-install), _you cannot install twice the same rpm. Therefore if you want to install a newer version of the same rpm (mypackage in your case); you need to use the -U | --upgrade option._

```sudo_sh_c rpm -U "$CACHE_DIR/coder_${VERSION}_${OS}_${ARCH}.rpm"```

https://github.com/coder/coder/blob/f05609b4da0c0e178288224832e64e310bd521c4/install.sh#L422-L431

**Comment by shawnweeks** [comment]
Looks like we just need the fix I made to code-server. You should always use `-U` when loading the rpm. If the rpm isn't already installed `-U` works like `-i`.

**Comment by kylecarbs** [comment]
Ahh, neato!

**Comment by kylecarbs** [comment]
@shawnweeks this is now fixed!
