### ISSUE TITLE
feat: display all shared `coder_apps` in the workspaces tab or a separate new tab to other users

### ISSUE THREAD

**Issue by matifali** [coder/coder#6278]
# Problem
We can share `coder_apps` with other authenticated users or the public by setting `share=authenticated` or `share=public`, but there is no way to access those apps except by sharing the `url`.

# Suggested Solution
Display all shared apps in the **Workspaces** tab or a separate new tab **Shared**. Or a sub-tab under **workspaces** showing all `coder_app`s that are accessible by the logged-in user.

Suggestions are welcomed: 
@bpmct @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
Ahhh, I see. This is a really good idea. We would have to rethink a bit how the UI is architected but definitely something to think about. Some of my initial ideas are to have a page for Apps and show the apps there with a few filters like, "All apps", "Your apps", "Shared apps", "By workspace". @bpmct @kylecarbs what do you think?

**Comment by matifali** [comment]
I would still like to see this.

**Comment by matifali** [comment]
@bpmct would you think this should be done?

**Comment by matifali** [comment]
Related to #13361

**Comment by kylecarbs** [comment]
I think it'd be confusing to just have "Shared".

Most users add context when sharing ports, like indicating what's actually running. I'm not saying this shouldn't be in the product, but I'd like us to work with a customer before doing this.

**Comment by matifali** [comment]
This was requested a while when no port sharing was possible. Sharing specific posts explicitly will serve the purpose here.
