### ISSUE TITLE
Add build failure reason to the UI

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#6285]
:wave: from @kylecarbs 

The `error` property on a workspace build is not displayed anywhere on the build logs UI.

---

After updating a template to use a newer version of the Coder provider and to change the resource name of the `coder_app` resources, e.g. from `coder_app.code-server` to `coder_app.code_server`, I get this error:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/1318438/220178000-54860559-9e73-4422-8b2d-20f7cff981bb.png">

The error itself is a bug on the provider I believe (happy to file one there), but the bug I want to report here is that the error is not displayed in the UI:

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/1318438/220178098-a104d2c7-1f8e-4848-bfa6-fc743a7495f9.png">

[...]

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/1318438/220178135-789d64ed-d92e-47cd-8e52-21ca78a373b0.png">

**Comment by NiklasRosenstein** [comment]
Ah, I should just use a `moved{}` block. It's probably not a Provider bug, TF doesn't know it would first need to delete the one resource before creating the other.

**Comment by kylecarbs** [comment]
It's kinda weird that this would happen, though... maybe we can do something!

**Comment by NiklasRosenstein** [comment]
I think the behaviour is expected; my main gripe is that the error is not visible in the UI. :) Related to #6235

**Comment by kylecarbs** [comment]
Ahh, gotcha!

**Comment by matifali** [comment]
closing in favour of #6235
