### ISSUE TITLE
bug: template admin cannot run `coder templates pull`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6288]
I was a member on a Coder deployment but was added as an admin on a template. I was unable to run `coder templates pull`

Version: 0.17.3

**Comment by Emyrk** [comment]
Pretty sure it is related to this: https://github.com/coder/coder/issues/6775

**Comment by Emyrk** [comment]
That being said, this PR has fixed this issue: https://github.com/coder/coder/pull/6776

**Comment by Emyrk** [comment]
For anyone else viewing this, the current required permission is `update` on a template to pull the files:

https://github.com/coder/coder/blob/f13632cea86b4af2fd60a135186ae1f96baee680/coderd/database/dbauthz/querier.go#L132-L138
