### ISSUE TITLE
OIDC Group Sync

### ISSUE THREAD

**Issue by bashscr** [coder/coder#6298]
Hey, I tried to follow the [guide here](https://coder.com/docs/v2/latest/admin/auth#group-sync-enterprise) and added the "groups" scope inside the `coder.env` file. We are using Coder v0.17.4 (tried on v0.17.3 as well).

Upon a user logging in, they are not automatically added to the group. We tested with two groups - one group had a few capital letters (i.e. `Group-Name-1234`) and one with all lowercase, no special characters, and no numbers. 

Are there any log files that might be able to point me in the right direction - or any guidance from someone who has been able to do this successfully? We are using Okta for OIDC. 

Thank you.

**Comment by coadler** [comment]
Hey @bashscr! I mostly tested this feature with Okta, and they require you to opt in to sending the groups to Coder. Here's how I had it set up in the `Sign On` settings page for the application: 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/6332295/220546198-bfb11ea0-d3ed-4721-ad5a-8bb62bcd7465.png">

Additionally, this feature requires an enterprise license, so if you don't have one added to your deployment then it won't work.

**Comment by bashscr** [comment]
Hey @coadler - thank you for getting back and sharing that! Apparently, I had it set to "Starts with" instead of "Matches regex". Upon changing and saving it I tried again, and it seems to not have affected anything regarding group assignments. Are there any other settings in Okta that might be relevant in terms of assignments or other configurations?

**Comment by coadler** [comment]
Just checking, did you add `.*` to the regex field as well?

**Comment by bashscr** [comment]
Yes, I just double checked to make sure the `.*` was added to the regex field.

**Comment by bashscr** [comment]
I tried to create another custom Authentication server in Okta, and a fresh group to add myself to with some team members. I am still not able to get the `groups` claimed working and haven't found anything in the logs to help pinpoint my issue. Can anyone think of anything else I'm able to try, or is there a verbosity mode I can set to help generate more logs? Thanks!

**Comment by Emyrk** [comment]
@bashscr Sorry for the delay.

I can help you debug this as I just did some extra work on the groups sync. 

Questions:
1. Are you on an enterprise license? This feature is only available with a license. This should be made more clear.
2. I assume you have added **groups** to the claims? `--oidc-scopes openid,profile,email,groups`

Notes:
1. The group names are case sensitive and must be made manually.

Happy to debug this with you if you are still needing this.

**Comment by bashscr** [comment]
> @bashscr Sorry for the delay.
> 
> I can help you debug this as I just did some extra work on the groups sync.
> 
> Questions:
> 
> 1. Are you on an enterprise license? This feature is only available with a license. This should be made more clear.
> 2. I assume you have added **groups** to the claims? `--oidc-scopes openid,profile,email,groups`
> 
> Notes:
> 
> 1. The group names are case sensitive and must be made manually.
> 
> Happy to debug this with you if you are still needing this.

Hey @Emyrk No worries, thank you for getting back to me.

1. Yes, I am using an Enterprise license that has been activated using the CLI.
2. Yes, I have added the `groups` to the claim as well. 
3. I tried a few group names, some with special characters and some without, all case sensitive that were made manually in Coder.

If there's anything that might be helpful for me to include, or log data (which I haven't been able to find much for the Okta claims), please let me know and I'll do my best to find and include them here.

**Comment by bashscr** [comment]
Apologies for the delay, I will get those logs for you as soon as I can. Thank you for the update on this.

**Comment by bashscr** [comment]
Sorry to tag you both @Emyrk @coadler, but where would I typically find these logs? I tried running `journalctl -u coder.service` but was not able to see much there. The only messages I saw there were the following:

```
Mar 23 19:31:34 ip-REDACTED systemd[1]: Starting "Coder - Self-hosted developer workspaces on your infra"...
Mar 23 19:31:34 ip-REDACTED coder[2961]: WARN: Address is deprecated, please use HTTP Address and TLS Address instead.
Mar 23 19:31:34 ip-REDACTED coder[2961]: Using built-in PostgreSQL (/home/coder/.config/coderv2/postgres)
Mar 23 19:31:35 ip-REDACTED coder[2961]: Started TLS/HTTPS listener at https://[::]:443
Mar 23 19:31:35 ip-REDACTED coder[2961]: View the Web UI: https://REDACTED.com
Mar 23 19:31:35 ip-REDACTED coder[2961]: 2023-03-23 19:31:35.111 [WARN]        <./cli/server.go:757>        Server.func1        coder will not check email_verified for OIDC logins
Mar 23 19:31:36 ip-REDACTED coder[2961]: 2023-03-23 19:31:36.888 [INFO]        (coderd.update_checker)        <./coderd/updatecheck/updatecheck.go:179>        (*Checker).update        checking for update
Mar 23 19:31:36 ip-REDACTED coder[2961]: ==> Logs will stream in below (press ctrl+c to gracefully exit):
Mar 23 19:31:36 ip-REDACTED systemd[1]: Started "Coder - Self-hosted developer workspaces on your infra".
Mar 23 19:31:37 ip-REDACTED coder[2961]: 2023-03-23 19:31:37.016 [INFO]        (coderd.update_checker)        <./coderd/updatecheck/updatecheck.go:206>        (*Checker).update        update check result        {"latest_version": "v0.20.1"}
Mar 23 19:31:37 ip-REDACTED coder[2961]: 2023-03-23 19:31:37.019 [INFO]        (coderd.update_checker)        <./coderd/updatecheck/updatecheck.go:148>        (*Checker).start        time until next update check        {"duration": "23h59m59.997030905s"}

Mar 23 19:40:45 ip-REDACTED coder[2961]: 2023-03-23 19:40:45.380 [INFO]        (coderd)        <./enterprise/audit/backends/slog.go:32>        slogBackend.Export        audit_log        {"Time": "2023-03-23T19:40:45.378151Z", "OrganizationID": "00000000-0000-0000-0000-000000000000", "ResourceTarget": "", "Action": "logout", "ResourceIcon": "", "ID": "REDACTED", "Ip": {"IPNet": {"IP": "REDACTED", "Mask": "/////////////////////w=="}, "Valid": true}, "UserAgent": {"String": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.44", "Valid": true}, "StatusCode": 200, "ResourceType": "api_key", "Diff": {}, "AdditionalFields": {}, "UserID": "REDACTED", "ResourceID": "REDACTED", "RequestID": "REDACTED"}
Mar 23 19:41:07 ip-REDACTED coder[2961]: 2023-03-23 19:41:07.853 [INFO]        (coderd)        <./enterprise/audit/backends/slog.go:32>        slogBackend.Export        audit_log        {"ID": "REDACTED", "Time": "2023-03-23T19:41:07.851403Z", "ResourceType": "api_key", "StatusCode": 307, "AdditionalFields": {}, "ResourceIcon": "", "UserID": "REDACTED", "OrganizationID": "00000000-0000-0000-0000-000000000000", "UserAgent": {"String": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.44", "Valid": true}, "ResourceTarget": "", "Action": "login", "Diff": {}, "Ip": {"IPNet": {"IP": "REDACTED", "Mask": "/////////////////////w=="}, "Valid": true}, "ResourceID": "REDACTED", "RequestID": "REDACTED"}```

**Comment by coadler** [comment]
You'll likely have to set `--verbose` or `CODER_VERBOSE=true=`

**Comment by bashscr** [comment]
> You'll have to set `--verbose` or `CODER_VERBOSE=true`

Perfect, thank you. Upon doing so, I found the following message:
```
Mar 23 19:58:30 ip-REDACTED coder[3224]: 2023-03-23 19:58:30.932 [DEBUG]        (coderd)        <./coderd/userauth.go:584>        (*API).userOIDC        got oidc claims        {"request_id": "REDACTED", "user_info": {"sub": "REDACTED", "profile": "", "email": "NAME@REDACTED.com", "email_verified": true}, "claim_fields": ["iat", "idp", "auth_time", "at_hash", "family_name", "locale", "given_name", "name", "email", "aud", "amr", "preferred_username", "Groups", "email_verified", "zoneinfo", "sub", "ver", "iss", "exp", "jti", "updated_at"]}
```

It appears we had a capital "G" in groups for our API in Okta under the Scopes/Claims tab for the name. I thought we tested with both "Groups" and "groups" initially, but after swapping to a lowercase "g", the automatic grouping worked after relogging. Thank you so much for the time and assistance - it is deeply appreciated!

**Comment by bashscr** [comment]
Before I close this out, quick question regarding the group names. If you'd prefer me to open another issue for a suggestion, please let me know. Regarding the group names, is there any chance we could get support for more than 32 characters, and additionally the possibility of using periods in the name? @coadler

**Comment by bashscr** [comment]
Thank you for the reply, that will indeed be useful. Are periods allowed via the API - or is that a backend & frontend limitation?

**Comment by coadler** [comment]
The backend doesn't do any validation on the name currently

**Comment by Emyrk** [comment]
Glad to see this resolved, can you close this out @bashscr ?
