### ISSUE TITLE
make 5m timeout configurable

### ISSUE THREAD

**Issue by nlbkoll** [coder/coder#6299]
We get a `context deadline exceeded`error five minutes after spawning a new node and pulling a few images during a workspace startup:

![image](https://user-images.githubusercontent.com/122457445/220602711-c5e0b87c-234e-428d-8700-5c51ffd40432.png)

It would be great if we were able to specify this timeout by ourselves.

**Comment by sharkymark** [comment]
You can get that error if the registry, image and tag are not found

**Comment by kylecarbs** [comment]
@nlbkoll try this https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts

**Comment by MrPeacockNLB** [comment]
Thanks in advance! We try this out tomorrow.

**Comment by MrPeacockNLB** [comment]
@kylecarbs this works. Now building a workspace does not fail even if it take more than 5 minutes. You can close this issue

**Comment by kylecarbs** [comment]
Awesome!
