### ISSUE TITLE
feat: Auto-start a workspace when a user logs in

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6303]
A prospect shared a use case is to quickly spin up a workspace when the developer logs on. 

It may be interesting to even assign a default template to a user so their first time in Coder, the workspace is created.

**Comment by matifali** [comment]
# Suggestion
This would be easier if Coder could support a user/client-side configuration file to set up all these customizations for each user. Default template auto start of a workspace etc., can then be easily managed by reading that file on the login. 

This would work when a user login from the CLI and a default file can be read, but when the user login from the dashboard UI, we may Coder should provide setting these parameters in the dashboard somewhere and also store them in the database with other user credentials.
