### ISSUE TITLE
feat: Create a shared workspace for multiple engineers to connect to

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6304]
A prospect wants to invite their clients into a workspace. They do a lot of services work for a number of clients and it would be helpful if we could spin up a shared workspace that everyone can collaborate in.

**Comment by MrPeacockNLB** [comment]
This could be dangerous as if any account inside a workspace logged in then everbody who has access to the workspace can do things in the name of the loged on person.

**Comment by matifali** [comment]
They may also consider [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)
