### ISSUE TITLE
bug: `coder update <workspace> --always-prompt` does not start the workspace

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#6336]
version `v0.17.4-devel+16363fd1`

running `coder update <workspace> --always-prompt` correctly prompts me to reset my terraform variables and re-initializes terraform.

however, navigating back to the UI shows the workspace still in a `Stopped` state. note that the prior state was an auto-shutoff by Coder:

<img width="1024" alt="Screenshot 2023-02-23 at 6 07 27 PM" src="https://user-images.githubusercontent.com/9683576/221066972-183cd81b-a91b-4557-9476-1298dbc83c3c.png">

[this code](https://github.com/coder/coder/blob/282507f0fb2a900f3c0fa651c59de70da3683864/cli/update.go#L71-L72) suggests that the workspace transition leverages the state of the latest build.

**Comment by Emyrk** [comment]
Yea, this should probably start the workspace. I'll fix this.
