### ISSUE TITLE
coder update instructions break running gpu containers

### ISSUE THREAD

**Issue by matifali** [coder/coder#6338]
Coder update instructions require running 
```bash
systemctl daemon-reload
```
This breaks gpu connectivity of the running containers.
Please take a look at the linked issue. https://github.com/NVIDIA/nvidia-docker/issues/1650
https://github.com/NVIDIA/nvidia-docker/issues/1671

**Comment by matifali** [comment]
A possible workaround. https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1420855027

Haven't tested yet.

**Comment by dcarrion87** [comment]
Watching this as we just noticed. We recently had to solve this for runc interactive issue. E.g.:

https://github.com/opencontainers/runc/issues/3551#issuecomment-1211427622
https://github.com/k3s-io/k3s/issues/6064

We'll probably be looking to put in a fix or workaround in the coming week or two so will post back here.

**Comment by matifali** [comment]
> A possible workaround.
> 
> [NVIDIA/nvidia-docker#1671 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1419720602)
> 
> Then [NVIDIA/nvidia-docker#1671 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/1671#issuecomment-1420855027)
> 
> Haven't tested yet.

I tested these, and it does work, and running GPU workspaces retain access to GPU.
The exact workaround steps are in my template. https://github.com/matifali/coder-templates/tree/main/deeplearning

**Comment by matifali** [comment]
Closing this as it is not a Coder issue.
