### ISSUE TITLE
bug: UI shows ID instead of type

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#6343]
# Description

As one can see in the screenshot below it shows my ID **primary-github** instead of type **github**.

Version: **0.17.4**

![image](https://user-images.githubusercontent.com/103434584/221353204-0c38f650-ba3d-4490-ba22-90d82b396d24.png)

**Comment by kylecarbs** [comment]
Ahh, will fix!

**Comment by Emyrk** [comment]
@kylecarbs did you fix this? What page is this on?
