### ISSUE TITLE
Custom (wgtunnel) for KubeCon EU and coder binary with templates for kids events and mentoring

### ISSUE THREAD

**Issue by hh** [coder/coder#6348]
I’d like to make a custom coder binary for regional deploys (for example in KubeCon Asmerdam / New Zealand) so the latency is low for anyone running `coder server`. So different binaries could be generated for mentoring.cncf.io, coder.ii.nz, and Kids Day at KubeCon this year.

There's an open PR that needs to be merged to run the server side : https://github.com/coder/wgtunnel/pull/1
@deansheather need any help with the signal handling?

There's quite a few Equinix data centers in Amsterdam, but possible AM6.

https://www.equinix.com/data-centers/europe-colocation/netherlands-colocation/amsterdam-data-centers

https://www.equinix.com/content/dam/eqxcorp/en_us/images/data-centers/emea/netherlands-colocation/amsterdam-data-centers/amsterdam_data_centers_map.png

There a bit of work once we are there to figure out the IP address of our venue and put it into the Equinix looking glass instance : https://metal.equinix.com/developers/looking-glass/ 

But overall I think this is going to be a great feature when combined with embedded templates specific to an event, workshop, or location.

**Comment by hh** [comment]
Currently `*.pit-1.try.coder.com` is a closed tailscale+ingress service provided by coder.com

**Comment by kylecarbs** [comment]
@hh if we added another region would that work? We already pick the closest/lowest latency region.

**Comment by hh** [comment]
This is now up and running at https://coder.cloudnative.coop
It doesn't need a custom wg tunnel for now.
