### ISSUE TITLE
Pre-authenticate `coder` CLI on the Workspace

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#6354]
Hi! I would like to pre-authenticate the `coder` CLI on a Coder workspace. This would enable a smooth experience to shut down or update your Coder environment without having to switch to a local terminal session.

Maybe this could be enabled with a `coder_cli_token` resource in the Terraform provider?

**Comment by kylecarbs** [comment]
Ahh, I like the idea of doing it with a resource!
