### ISSUE TITLE
feat: allow disabling an existing template (template deprecation)

### ISSUE THREAD

**Issue by matifali** [coder/coder#6355]
# Problem
Sometimes after significant refactoring, updating an existing template with `coder push` will break existing workspaces if the users try to stop/start or update. Pushing a separate new template is the only solution not to break existing workspaces. 
I have experienced issues where a fully functional workspace will break after a significant update to a template structure, like removing or mounting new volumes, changing terraform variables or `coder_parameter`, etc.

# Solution
- Allow disabling an existing template so that no new workspaces can be created using it.
- This will force the users creating a new workspace to use the new template but keep the existing workspaces using the current template working as expected.
- Add a banner on the workspace page that the template is deprecated

Nice to have
- Allow admin to link to an internal migration wiki or suggest an alternative template

cc: @bpmct @kylecarbs @ammario

**Comment by dcarrion87** [comment]
Yes please!

**Comment by ammario** [comment]
In v1 we had a "Deprecated" boolean that would prevent new workspaces from being created from a template. Another way we could model this is with RBAC, i.e. by removing everyone from a template they would be unable to create workspaces from it.

**Comment by ericpaulsen** [comment]
a customer provided this feedback on template deprecation:

>  I think the Use permission is too coarse and should be broken down into Create and Use, so that for given template we could disable Create so new workspaces can't be created, but still allow them to Use their existing workspaces, hence slowly phasing out the old template.

**Comment by matifali** [comment]
@Emyrk I think one way to do it is to add a new template metadata item `deprecated` that when set to `true`, could be used to turn off creating new workspaces from that template.
We currently have template metadata such as `display_name`, `icon`, `description`, etc.

**Comment by Emyrk** [comment]
@matifali exactly what I was thinking. The only difference in my WIP implementation is that I am making `deprecated` a `TEXT` field in postgres to allow for some message.

By default we can just put `Deprecated` as the message, but I imagine there is value in something more for UI purposes.

```
coder template edit <template-name> --deprecated="Severe security vulnerability. Use [secure-template](/templates/secure-template) instead."
```

I was thinking it could support markdown for link reasons and solve this "nice to have"
> Allow admin to link to an internal migration wiki or suggest an alternative template

**Comment by matifali** [comment]
@Emyrk for active templates this will be empty, and any nonempty value will result in a deprecated message and disallowing users to create new workspaces. Right?

**Comment by Emyrk** [comment]
Correct. Active templates will just have an empty value.

Felt excessive to have 2 fields to control if it is deprecated and a deprecation message that can be shown to a user.

**Comment by ammario** [comment]
Agree RBAC as a means of implementing deprecation is a bad UX and we have direct customer feedback to that effect. The suggested approach of a deprecation message as field on each template makes sense to me.
