### ISSUE TITLE
chore: switch tunnel to use new wgtunnel

### ISSUE THREAD

**Issue by deansheather** [coder/coder#6360]
Once the new wgtunnel is merged and deployed at https://github.com/coder/wgtunnel, switch the tunnel code in this repo to use `github.com/coder/wgtunnel/tunnelsdk`.

We need to ensure that existing tunnels don't get their URL changed by writing a tunnel version to a file and using that version in the tunnel registration request so we get an old format. New tunnels can use the new shorter URL.

Also make the tunnel URL configurable

**Comment by hh** [comment]
Would be good allow setting wgtunnel endpoints via env vars / new coders cli args. Noting we currently only have one, and it's in US East / Pittsburg. :)

https://github.com/coder/coder/blob/main/coderd/devtunnel/servers.go#L39-L40

```
		LocationName: "US East Pittsburgh",
		Nodes: []Node{
			{
				ID:                1,
				RegionID:          0,
				HostnameHTTPS:     "pit-1.try.coder.app",
				HostnameWireguard: "pit-1.try.coder.app",
```

**Comment by deansheather** [comment]
Blocked by https://github.com/coder/wgtunnel/pull/3

**Comment by mtojek** [comment]
@deansheather What is the status of this issue? Is there anything still missing?

**Comment by deansheather** [comment]
I encountered some issues deploying a test server alongside our prod legacy tunnel server and couldn't figure it out while debugging, so Colin and I will probably look again this week and perhaps try deploying it somewhere else.

The tunnel code in the linked PR works great though and connects without issue. Can't merge it until we have a server unfortunately.

**Comment by deansheather** [comment]
It wasn't linked oops
