### ISSUE TITLE
Rich parameters: ability to specify order of fields in UI

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#6362]
Currently, rich parameters defined in the TF templates appear to be presented in alphabetical order by name. It would be useful to have an "ordinal" field or other mechanism to influence the ordering of fields.

**Comment by dcarrion87** [comment]
Is there a work around to order input parameters. It almost seems completely random. I can't seem to even trick it so they're alphabetical.

E.g. Why would ray_worker_max_replicas appear above instance_type in the UI?

```
data "coder_parameter" "ray_image" {
  name        = "Ray Docker Image"
  mutable     = true
  type        = "string"
  description = "Docker image used for the Ray head and workers"
  default     = "rayproject/ray-ml:2.2.0-py38-cu116"
}


data "coder_parameter" "instance_type" {
  name        = "Instance Type"
  description = "Select an instance type"
  mutable     = true
  type        = "string"
  default     = "cpu.small"
  dynamic "option" {
    for_each = { for kp, kv in local.instance_type_options : kp => kv }
    content {
      name  = option.value.name
      value = option.value.value
    }
  }
}

data "coder_parameter" "ray_worker_max_replicas" {
  name        = "Maximum Worker Replicas"
  description = "Number of worker replicas that can dynamically be created"
  mutable     = true
  type        = "number"
  default     = 1
}
```

**Comment by matifali** [comment]
Related https://github.com/coder/terraform-provider-coder/issues/103

**Comment by mtojek** [comment]
I spent some time chasing a bug around rich parameters, and I have a feeling that the order can be random sometimes. I think that we should try to keep the order of fields as they appear in the file.

@bpmct Do you think that I can pull it into this week's sprint?

**Comment by mtojek** [comment]
I'm going with this issue.

**Comment by mtojek** [comment]
I merged the PR to order fields alphabetically. I will spend some time to see if we can "pull" the order form `*.tf` files. At first glance, it's rather tricky to do this without extra file inspecting.
