### ISSUE TITLE
Automatically convert emojis to twemoji

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#6363]
Title. Like how Discord does it.

To prevent from showing a box in use-cases where the emoji might only be available on linux/macos.
![image](https://user-images.githubusercontent.com/57866459/221664638-200e105e-4d05-4dcb-9695-b9a44a12197f.png)

**Comment by matifali** [comment]
Hi, @BrunoQuaresma if this is a small change you may like to do it. If the amount of work required is too high, you can unassign yourself as per your preference.

**Comment by BrunoQuaresma** [comment]
We would have to run the parse on every page to make it consistent and since it replaces the text with a svg tag, it might break a few things so IMO, I would not move forward with this until we have more users asking for that or a better sense of its value.

**Comment by BrunoQuaresma** [comment]
Sure, closing it.
