### ISSUE TITLE
rich parameters: import values from legacy parameters 

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6368]
The idea here is to import values from legacy parameters to make the migration smoother. `coder_parameter`s should use the matching value of a legacy parameter before switching to default.

@kylecarbs has an idea to introduce `legacy_variable_name` or `legacy_name` to mark the legacy name.

**Comment by mtojek** [comment]
Reopening as I found this buggy, need more time to spend on this

**Comment by mtojek** [comment]
Ok, I've done more research. Unfortunately, [this PR](https://github.com/coder/terraform-provider-coder/pull/109) is insufficient, and we also need to sneak the `legacy_parameter_name` property for migration purposes.

The `legacy_variable` property works well with targetting the default value, but if only we need to switch from the old parameter to `coder_parameter` (strip reference to a legacy variable), the `coder_parameter` loses context, and takes the default. This is due to the fact that we pass all build parameter values externally, and there is no mechanism/logic to pull the legacy variable value.

**Comment by mtojek** [comment]
cc @kylecarbs if you have any alternative idea how to approach this problem ^

**Comment by kylecarbs** [comment]
No additional thoughts, the above makes sense. I think it's fine to have the `legacy_parameter_name` property in for now, it makes a lot of sense for users.
