### ISSUE TITLE
coder login from CLI gives 404

### ISSUE THREAD

**Issue by rahulgangwarmsn** [coder/coder#6370]
I can login to coder from browser just fine. I could also login to coder via CLI a day back but all of a sudden in midle of a demo it failed on me! when I try to login to coder using coder login <<url>> using the CLI, it opens a browser window that says 404 below screenshot:

<img width="951" alt="image" src="https://user-images.githubusercontent.com/111990865/221912570-02bedb06-a72b-4989-8708-2cca57556d0d.png">

Again, this worked a day back! I've deployed coder service on K8 I tried recreating the pod but still it doesn't show anything...

**Comment by sharkymark** [comment]
taking off the URL from /internal-auth?show_token=true. does the dashboard work? @rahulgangwarmsn

**Comment by sharkymark** [comment]
what version of Coder and the CLI are you using? @rahulgangwarmsn

**Comment by sharkymark** [comment]
@rahulgangwarmsn looks like you have the v1 CLI on your local machine.

**Comment by rahulgangwarmsn** [comment]
I think we're getting somewhere with this... I recently updated my CLI
[Coder v0.12.9+2b6c229](https://github.com/coder/coder/commit/2b6c229e4e2e94776500fe366b538afb6c24c199)

CLI Version: coder version v1.39.1 go1.19.4 darwin/amd64 5b248dee65b1407d3a377c03bec55b10e6c91df5
@sharkymark

**Comment by rahulgangwarmsn** [comment]
okay can you please point me to the correct cli version for my coder version?

**Comment by sharkymark** [comment]
The v2 CLI is the same as the server.

Just run this:
curl -fsSL https://coder.com/install.sh | sh
or use these releases (WIndows, etc.)

https://github.com/coder/coder/releases

**Comment by sharkymark** [comment]
then run `coder login <access url>`

and you paste the token from the browser UI, and you should be good to go using the CLI

**Comment by sharkymark** [comment]
all good @rahulgangwarmsn ?

**Comment by rahulgangwarmsn** [comment]
I can confirm that this fixed the issue. Coder support is awesome. Even the free one. I appreciate you guys! @sharkymark

**Comment by rahulgangwarmsn** [comment]
Just to add detailed steps, 

- I removed existing coder CLI from my MacOS by repeatedly using "whereis coder" and deleting the binary untill it was deleted from everywhere.
- Then I went to the specific tag that I wanted (v0.12.9) using this https://github.com/coder/coder/tags?after=v0.13.1
- Finally I download the needed binary (for me it was (coder_0.12.9_darwin_amd64.zip), extracted the binary and placed in my path /usr/local/bin.

**Comment by sharkymark** [comment]
awesome @rahulgangwarmsn
