### ISSUE TITLE
Network connectivity health checks

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6372]
We have seen users run into networking issues while using Coder. While these are often not due to problems in the platform, enhanced visibility into networking errors can make it easier to pinpoint/troubleshoot. This is particularly true with new Coder deployments with 0-15 workspaces, where it may not make sense to add a Prometheus dashboard just yet.

- Are agent<->coder server requests slow/failing?
  - Potential resolutions: increase resources available to agent or coderd
- Are web browser <-> coder server <-> agent requests slow/failing?
  - Potential resolutions: deploy Coder in a closer region, use local SSH with p2p
- Are LoadBalancer (access URL) <-> coder server <-> coder agent requests slow/failing?
  - Potential resolutions: enable websockets (#5854), adjust `ExternalTrafficPolicy: Cluster` in helm values

Some health checks rely on the user's local CLI. We have `coder speedtest` and `coder ping`. For a full end-to-end health check however, it might be nice to bundle all the results into a TXT or TAR.GZ so that users can send to Coder.

- Are CLI <-> (coder server?) <-> agent requests slow/failing?
  - Is the CLI ever able to connect directly via STUN?
- What is the ping and connection speed from CLI to agent?

We also notice some users experience intermittent connection issues, making it challenging to grab logs, particularily when another user reports it. Perhaps when the ping is extremely high, we encourage the user to visit the health check page to get a "dump" of all of the connection state.

**Comment by deansheather** [comment]
As part of bullet 1, we should also monitor available resources similar to v1 and warn if processes are starved.

It might also pay to bring back the agent niceness from v1 to v2 also.
