### ISSUE TITLE
k8s on-premise - code-server starts but never connects

### ISSUE THREAD

**Issue by ddsmith2-eprod** [coder/coder#6379]
I'm trying to get Coder to work in our on-premise k8s cluster.  Here is my resource definition in my TF template:
```
resource "coder_agent" "dev" {
  os             = "linux"
  arch           = "amd64"
  dir            = "/home/podman"
  startup_script = <<EOF
    #!/bin/sh
    # install and start code-server
    curl -k -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix=/tmp/code-server --version 4.8.3
    /tmp/code-server/bin/code-server --auth none --port 13337 >/tmp/code-server.log 2>&1 &
    # Run once to avoid unnecessary warning: "/" is not a shared mount
    podman ps
    tail -f /dev/null
  EOF
}
```
I added tail -f /dev/null otherwise the workspace completes and doesn't stay up.

### Pod log
```
Ubuntu 22.04.1 LTS
Installing v4.8.3 of the amd64 release from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server-4.8.3-linux-amd64.tar.gz.incomplete -C - https://github.com/coder/code-server/releases/download/v4.8.3/code-server-4.8.3-linux-amd64.tar.gz
######################################################################## 100.0%
+ mv ~/.cache/code-server/code-server-4.8.3-linux-amd64.tar.gz.incomplete ~/.cache/code-server/code-server-4.8.3-linux-amd64.tar.gz
+ mkdir -p /tmp/code-server
+ mkdir -p /tmp/code-server/lib /tmp/code-server/bin
+ tar -C /tmp/code-server/lib -xzf ~/.cache/code-server/code-server-4.8.3-linux-amd64.tar.gz
+ mv -f /tmp/code-server/lib/code-server-4.8.3-linux-amd64 /tmp/code-server/lib/code-server-4.8.3
+ ln -fs /tmp/code-server/lib/code-server-4.8.3/bin/code-server /tmp/code-server/bin/code-server

Standalone release has been installed into /tmp/code-server/lib/code-server-4.8.3

Extend your path to use code-server:
  PATH="/tmp/code-server/bin:$PATH"
Then run with:
  code-server

Deploy code-server for your team with Coder: https://github.com/coder/coder
```

It looks like the code-server started and is running:
```
podman@coder-ddsmith2-doug-ubuntu:/$ ps auxw |grep code
podman        80  0.0  0.0 710576 58516 ?        Sl   15:29   0:00 /tmp/code-server/lib/code-server-4.8.3/lib/node /tmp/code-server/lib/code-server-4.8.3 --auth none --port 13337
podman       139  0.0  0.0 916720 71308 ?        Sl   15:29   0:01 /tmp/code-server/lib/code-server-4.8.3/lib/node /tmp/code-server/lib/code-server-4.8.3/out/node/entry
podman       187  0.0  0.0 624412 49016 ?        Sl   17:02   0:00 /tmp/code-server/lib/code-server-4.8.3/lib/node /tmp/code-server/lib/code-server-4.8.3/lib/vscode/out/bootstrap-fork --type=ptyHost --
```
### Debugging
I'm not finding a log or error if I use kubectl to look in the container:
```
podman@coder-ddsmith2-doug-ubuntu:/$ ls /tmp/
code-server  code-server.log  containers-user-1000  podman-run-1000
podman@coder-ddsmith2-doug-ubuntu:/$ cat /tmp/code-server.log
[2023-02-28T15:29:29.192Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2023-02-28T15:29:29.447Z] info  code-server 4.8.3 977b853a1e162ab583aed64b1322d1515c57728c
[2023-02-28T15:29:29.448Z] info  Using user-data-dir ~/.local/share/code-server
[2023-02-28T15:29:29.456Z] info  Using config file ~/.config/code-server/config.yaml
[2023-02-28T15:29:29.456Z] info  HTTP server listening on http://127.0.0.1:13337/
[2023-02-28T15:29:29.456Z] info    - Authentication is disabled
[2023-02-28T15:29:29.456Z] info    - Not serving HTTPS
[17:02:07] Extension host agent started.
```
![image](https://user-images.githubusercontent.com/126083021/221952295-f42d6544-c218-4f9a-8ecb-f7c6e28a42d8.png)

**Comment by ddsmith2-eprod** [comment]
Doing a bit of troubleshooting and the pod can talk to it's local loopback but I can't access it from the host the pod runs on:

podman@coder-ddsmith2-doug-ubuntu:/etc$ telnet localhost 13337
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

podman@coder-ddsmith2-doug-ubuntu:/etc$ ip address |grep '10.'
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 10.42.228.185/32 scope global eth0

# telnet 10.42.228.185 13337
Trying 10.42.228.185...
telnet: connect to address 10.42.228.185: Connection refused

This is a new Rancher RKE2 (podman) cluster with no customization.

**Comment by ericpaulsen** [comment]
hi @ddsmith2-eprod - thanks for submitting this issue. the agent must be able to phone back home to the server via the access URL you have configured.

can you exec into the pod and attempt to curl the access URL? e.g. `curl -vvv coder.example.com`

also, the agent logs _should_ be in `/tmp/coder-agent.log` inside of your workspace container.

**Comment by ddsmith2-eprod** [comment]
```
podman@coder-ddsmith2-doug-ubuntu:/etc$ curl -vk https://coder.pdds2.redacted-domain.com
*   Trying 10.96.232.223:443...
* Connected to coder.pdds2.redacted-domain.com (10.96.232.223) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:0A000152:SSL routines::unsafe legacy renegotiation disabled
* Closing connection 0
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled
```

We terminate SSL on the load balancer.  It looks like we may have an SSL issue with TLS negotiation from inside our container.

**Comment by ddsmith2-eprod** [comment]
I'm using this template:

https://github.com/coder/coder/blob/main/examples/templates/kubernetes-with-podman/main.tf

I don't see where you specify the access URL in the template.  I suspect this is why we are not seeing any errors as the container may not be trying to communicate to the server.

**Comment by ericpaulsen** [comment]
@ddsmith2-eprod the access URL would be set in your Helm chart values (if running the control plane on K8s). can you confirm with me the `CODER_ACCESS_URL` you've set.

**Comment by ddsmith2-eprod** [comment]
Yes the CODER_ACCESS_URL is set properly.

$ grep -A 1 ACCESS values.yaml
    - name: CODER_ACCESS_URL
      value: "https://coder.pdds2.redacted-domain.com"

**Comment by ddsmith2-eprod** [comment]
Also note, the URL works fine as long as I'm not in a new container:

$ curl https://coder.pdds2.redacted-domain.com
<!DOCTYPE html>

**Comment by ericpaulsen** [comment]
@ddsmith2-eprod do you have a load balancer or ingress in front of the Coder K8s deployment?

**Comment by ddsmith2-eprod** [comment]
@ericpaulsen Yes, we basically mimicked our setup for v1.  We have a Netscaler LB in front of 3 worker nodes.  The worker nodes have the default nginx ingress pods.  SSL termination is being done on the Netscaler.

**Comment by ericpaulsen** [comment]
@ddsmith2-eprod thanks for confirming. i suspect your Load Balancer is dropping the DERP connection from workspace agent -> server.

first, we'll need to confirm if you have DERP enabled. please check your values file, and let me know the value of `CODER_DERP_SERVER_ENABLE`. if not set, then it defaults to `true`.

if enabled, then we'll need to check if you have the following connection header set on either the LB or ingress:

```
Connection: Upgrade
Upgrade: derp
```

**Comment by ddsmith2-eprod** [comment]
I did not specify CODER_DERP_SERVER_ENABLE in my values.yaml, so I'll assume for now it is enabled.

I checked the Netscaler and Upgrade is not currently a configured header. Connection is set to keep-alive.  I'll work with our load balancer admin and have her set these headers.

**Comment by ddsmith2-eprod** [comment]
Closing the ticket.  We had an issue in our TF template and had to add a disable to SSL renegotiation to get things working.

/etc/ssl/openssl.cnf
[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=2
Options = UnsafeLegacyRenegotiation
