### ISSUE TITLE
Hide some TF vars while creating a Workspace

### ISSUE THREAD

**Issue by NedkoHristov** [coder/coder#6382]
Hi team,

Is there a way to hide some TF variables that are already declared as environment variables (ex. TF_VAR_ssh_key) or declared in `terraform.tfvars`? While I'm not asked when I run my setup directly from terraform I'm always asked from the UI.

Thanks!

**Comment by kylecarbs** [comment]
Use `coder_parameter` instead of `terraform.tfvars` to define variables!

https://coder.com/docs/v2/latest/templates#parameters-alpha

**Comment by NedkoHristov** [comment]
@kylecarbs - thanks, Kyle. I've been aware of `coder_parameter`, but since they are in alpha stage I don't think it's recommended for production.

**Comment by NedkoHristov** [comment]
@kylecarbs - I believe you should improve your documentation or add some sections for tips and tricks. Instead of using an alpha functionality, I can just set `sensitive = true`.
