### ISSUE TITLE
User Preference: Open coder_app in new tab rather than new window

### ISSUE THREAD

**Issue by edqx** [coder/coder#6408]
As per a short discussion in the Discord server, and because of some other reports of the same issue, it may be worth adding a user preference/setting to change the behaviour of clicking the "code-server" button on a Workspace to open in a new tab rather than in a new window.

**Current behaviour:**
![image](https://user-images.githubusercontent.com/60631511/222257850-947a620b-5a7d-4ad4-93a0-50f9cfbdb2e8.png)

**Desired (?) behaviour:**
![image](https://user-images.githubusercontent.com/60631511/222258039-cc4199c8-6cdc-46bc-a15f-ff8ec823cf67.png)

**Comment by MrPeacockNLB** [comment]
This should also be settable as system preference with lower precedence

**Comment by matifali** [comment]
I prefer new windows 😄 multiple monitors.

**Comment by bpmct** [comment]
This is more of a user preference than a system/Template one. Probably a good for user preferences

**Comment by ElioDiNino** [comment]
Why is this not planned? I think a lot of people would like to be able to control this behaviour.

**Comment by sharkymark** [comment]
Six one have dozen the other - why does terminal open in a new window? Right click to get a full window.

**Comment by matifali** [comment]
closing in favor of #8796
