### ISSUE TITLE
Feat. restrict login to users that has a specific group in OIDC claim

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#6413]
# Description

In a large company not everyone shold be able to sign in into coder.

# Solution

So as in other products there must be a way to control this. Usualy a group in OIDC claim. E.g.  group CODER_USER. Anyone which is not in this group wont be able to use coder. A permission denied or something else should be shown

**Comment by MrPeacockNLB** [comment]
Ok, after some research I found a solution which is provided from Azure AppRegistrations it self. One can choose only assigned user can use this App. So there the SSO provider can select who can get access to the application.

**Comment by roshvin** [comment]
Hi @MrPeacockNLB  could you pls give some more details how you restricted the users with OIDC . we are also interested in it.
