### ISSUE TITLE
How to automatically create initial user Kubernetes

### ISSUE THREAD

**Issue by mh013370** [coder/coder#6417]
Question!

When installing Coder in Kubernetes via the Helm chart, what is the preferred way to bootstrap the deployment with an initial user?

I see the initial user [API call](https://coder.com/docs/v2/latest/api/users#create-initial-user), but i'm wondering if there's an undocumented standard way of doing this (check for initial user, if not there then create it). I'm trying to avoid manually creating an initial user each time i deploy Coder from scratch.

I don't see a way this can be specified via environment variables via the `coder server` command.

**Comment by dcarrion87** [comment]
We do this via the first user flags: 

https://github.com/coder/coder/commit/0f3221f9d085788c4f9734c7a66f04ad6ab8d017

**Comment by mh013370** [comment]
> We do this via the first user flags: [0f3221f](https://github.com/coder/coder/commit/0f3221f9d085788c4f9734c7a66f04ad6ab8d017)

When & how do you run the `coder login` command through the Helm chart? I don't see any container lifecycle hooks exposed and i don't believe it's possible via an `initContainer`. Or are you deploying an external resource to do this after Coder has been deployed?

**Comment by dcarrion87** [comment]
@mh013370 ah yes sorry we don't use Coder's Helm chart. We've got too many "special" requirements and prefer to have full control over this.

**Comment by mh013370** [comment]
This makes sense. Perhaps i'll raise a PR to add lifecycle config to the helm chart, since we don't want to maintain our own. I _think_ this is the only way to do it without adding an external resource. 

Did you have any issues using `postStart` anyone should be aware of given the following condition?

> There is no guarantee, however, that the postStart handler is called before the Container's entrypoint is called.

source: https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/

**Comment by dcarrion87** [comment]
It's be a while where we've had to use this to set up a new coder server instance but I don't recall any. The initial headaches was figuring out which environment variables did it and then the project changing to first-login- later.

**Comment by matifali** [comment]
@mh013370 Should we mark this as completed?

**Comment by mh013370** [comment]
Yes i'll close this. Lifecycle hooks are sufficient to satisfy the original need. Thanks!
