### ISSUE TITLE
feat: support gRPC HTTP/2 for web port forwarding

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6422]
A customer has a Blockchain group needing support for gRPC HTTP/2.  Currently not supported in v1 and v2.

Resources:
https://grpc.io/blog/grpc-on-http2/

**Comment by kylecarbs** [comment]
I actually think this might _just work_ now... because we support http2 now in the server, I see no reason why this wouldn't forward properly.

**Comment by coadler** [comment]
Yeah it's very possible this works now.
