### ISSUE TITLE
CLI docs: update check default value is wrong

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6424]
This says true, but the CLI output and help docs are false. @ammario - any ideas how this happened?

```sh
      --update-check                                      Periodically check for new releases
                                                          of Coder and inform the owner. The
                                                          check is performed once per day.
                                                          Consumes
                                                          $CODER_UPDATE_CHECK (default true)
```

https://coder.com/docs/v2/latest/cli/coder_server#--update-check

![Screenshot 2023-03-02 at 2 08 00 PM](https://user-images.githubusercontent.com/22407953/222540647-618354ab-3abb-4a52-9e6c-ddaa82abbb71.png)

**Comment by ammario** [comment]
Not sure, but I'm rewriting all of this behavior anyways.

**Comment by ammario** [comment]
Related https://github.com/coder/coder/issues/6766
