### ISSUE TITLE
Discussion: How should we handle joins?

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#6426]
# Problem

Our current use of SQLc uses almost 0 joins throughout all of our queries. This causes excessive db round trips. The function [`workspaceData`][workspaceData] does 9 database calls to completely populate the returned workspace from the api. This can be reduced with [joins][workspace-joined].

When `dbauthz` is enabled by default, this compounds the issue as many objects require fetching related objects to run authorization. Examples: [workspace builds][build-rbac], [template versions][version-rbac], jobs, build parameters, ... .

[build-rbac]: https://github.com/coder/coder/blob/25b05ed8a401cb80cea8e7cdebe58a0c8f9f7f58/coderd/database/dbauthz/querier.go#L1241-L1251
[version-rbac]: https://github.com/coder/coder/blob/25b05ed8a401cb80cea8e7cdebe58a0c8f9f7f58/coderd/database/dbauthz/querier.go#L628-L643
[workspaceData]: https://github.com/coder/coder/blob/25b05ed8a401cb80cea8e7cdebe58a0c8f9f7f58/coderd/workspaces.go#L1047-L1047
[workspace-joined]: https://github.com/coder/coder/blob/6adacd74fa79ae2c424e2144afc65c6e5994510c/coderd/database/sqlxqueries/workspace.gosql#L2-L75

# Solutions [(this PR talks about both)](https://github.com/coder/coder/pull/6371)

Allowing **queries to leverage joins** can reduce db round trips. The issue is how to handle these. We currently use SQLc, which would create a new model for each query and it becomes cumbersome. Additionally, we often have multiple `SELECT` queries for each datatype.

I have 2 proposals.

## Keeping SQLc [(originally investigated here)](https://github.com/coder/coder/issues/2201)

If we want to keep SQLc, the best way we can do this is with **views**. I am suggesting non-materialized views. So essentially these are saved queries in our postgres database that we can reference from SQLc.

Because views are saved in postgres, they require the same migration maintenance a table would.

https://github.com/coder/coder/blob/c3218f71cab8d571c2a95bca08efe2816a41fa86/coderd/database/migrations/000102_workspace_build_view.up.sql#L1-L14

A view is a "table" for SQLc, so a model is generated for it. In our `.sql` files, we just reference the view.

https://github.com/coder/coder/blob/c3218f71cab8d571c2a95bca08efe2816a41fa86/coderd/database/queries/workspacebuilds.sql#L1-L9

## Abandon SQLc and use SQLx + Go Templates [(an implementation here)](https://github.com/coder/coder/pull/6356)

We use SQLc to generate Golang code from our sql. But this code isn't actually that complex in Golang if we use SQLx. And then we can use Go templates to build dynamic queries.

A very basic implementation of this makes our `*.sql` files look like this. Note the highlighting will be a bit off as we are mixing SQL and Go templates.

```sql
{{ define "workspace_builds_rbac" }}
(
SELECT
	workspace_builds.*,
	workspaces.organization_id AS organization_id,
	workspaces.owner_id AS workspace_owner_id
FROM
	workspace_builds
INNER JOIN
	workspaces ON workspace_builds.workspace_id = workspaces.id
)
{{ end }}

-- To use the template above
{{ define "GetWorkspaceBuildByID" }}
SELECT
	*
FROM 
	{{ template "workspace_builds_rbac" }}
WHERE
	id = @build_id
{{ end }}
```

I investigated [IDE Highlighting][IDE-High], but the tl;dr is that just using `sql` highlighting is likely the best. It will never be perfect with Go templates :cry:.

### How to use template query in golang?

I made a package called `sqxqueriers` that handles templates and keeping our `@param` named parameters for easier to read sqlc. You can see that [here](sqlxqueries).

To call a query you made, you can use a generic function called sqlxGet for fetching one row:

https://github.com/coder/coder/blob/e9f0711c020a0b47e0f06f15b93099d9314be95c/coderd/database/sqlx.go#L10

The type embeds the sqlc `WorkspaceBuild` type. We would keep SQLc for generating models. We'd just move queries to this SQLx. The `db` struct tags are used for matching to columns. Obviously the query can be handled more manually if the tags do not match.

https://github.com/coder/coder/blob/e9f0711c020a0b47e0f06f15b93099d9314be95c/coderd/database/modelqueries.go#L183-L191

[IDE-High]: https://github.com/coder/coder/blob/6adacd74fa79ae2c424e2144afc65c6e5994510c/coderd/database/sqlxqueries/README.md
[sqlxqueries]: https://github.com/coder/coder/tree/e9f0711c020a0b47e0f06f15b93099d9314be95c/coderd/database/sqlxqueries

# Comparison

|                          | SQLc Views                     | SQLx + Templates |
|--------------------------|--------------------------------|------------------|
| SQL highlighting         | ✅                              | ⚠️ (kinda)        |
| Golang Code              | ✅                              | ✅                |
| Golang Simple Types      | ✅                              | ✅                |
| Golang Joined Types      | No embeds, duplicated          | Uses Embeds      |
| Supports Dynamic Queries | ❌ (gross strings replace)      | ✅                |
| No Migrations            | ❌ (migration to maintain view) | ✅                |

## Highligting

SQL template highlighting in vscode isn't that bad. In Goland it's pretty terrible.

## Golang Code

SQLx + Templates requires more infrastructure code to support, but this also gives us opportunity to add in features. SQLc is slow to update and add features we need.

## Joined Types

SQLc joined types are duplicated structs with identical fields. We can do anonymous embeds for template joined types.

I would really like to see `dbauthz` not adhere to `db.Store` and then we can do some better type handling at this layer to make types more consistent. You cannot insert into a view, so when updating or inserting data, you cannot return the joined data. Meaning 2 types will exist. A `thin` and a `joined`.

## Dynamic Queries

We currently use `CASE WHEN` statements for dynamic where clauses. This works fine, but is only supported in `WHERE`. Things not supported currently:

- Conditional sort order (ASC vs DESC)
- Conditional sort column
- Conditional updates, only update fields provided. [Caused bug in v1](https://github.com/coder/v1/issues/13767)

**Comment by deansheather** [comment]
Templates seem better to me, it sucks that the highlighting is sorta janky but from the screenshots you sent me in DMs (you should post those in this thread) it looked *okay*. It could probably also be improved if we wrote our own syntax highlighting grammar for vscode.

**Comment by Emyrk** [comment]
Goland

![Screenshot from 2023-03-02 16-49-41](https://user-images.githubusercontent.com/5446298/222577832-c25725c2-7263-4531-a35a-a77f00965536.png)

VSCode

![Screenshot from 2023-03-02 16-49-56](https://user-images.githubusercontent.com/5446298/222577846-3c4df691-e2f4-46b3-b44e-8b4ef4c05710.png)

I think making our own grammer would be quite difficult.

I want to merge one of these PRS:
- SQLc + views https://github.com/coder/coder/pull/6371
- SQLx + Templates https://github.com/coder/coder/compare/stevenmasley/build_with_template?expand=1

**Comment by Emyrk** [comment]
This came up as a feature request, negating search params.

It can be done with the existing code by defining 2 `CASE WHEN` blocks, or we could do it with templates like:
```sql
AND CASE
	WHEN @template_name :: text != '' THEN
		template_id {{ if .templateName.Negate }}!{{ end }}= ANY(SELECT id FROM templates WHERE lower(name) = lower(@template_name) AND deleted = false)
	ELSE true
END
```

**Comment by spikecurtis** [comment]
Template looks better to me as well.
