### ISSUE TITLE
signing Coder's JetBrains plugin executable

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6431]
A Coder customer has strict security policies that either require:

1. Have the Coder JetBrains Gateway plugin and CLI executables signed
2. Have an option to configure the plugin to download the file somewhere else (there are certain folders which are exempt from this policy so downloading and running it elsewhere would also work)

CC @bpmct @kylecarbs

**Comment by bpmct** [comment]
Full email. I just responded.

[Uploading Coder Mail - Re_ [EXTERNAL] Re_ Coder plugin for intellij.pdf…]()
