### ISSUE TITLE
search: see workspaces that are do not satisfy `has-agent:connected`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6439]
I can think of two ways to support this. Negating queries or supporting `AND`. @Emyrk may have other ideas.

**Comment by Emyrk** [comment]
If we use templated queries, we can make negated searches better with dynamic queries.

https://github.com/coder/coder/issues/6426

**Comment by Emyrk** [comment]
The joins PR was tabled to reduce adding complexity. If this issue is a high prio, I can try to reopen the joins PR, or find another solution to this.

Until then, this will sit in the backlog
