### ISSUE TITLE
external provisioners: tagged provisioners can pick up generic jobs

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6442]
If I install a custom provisioner in an on-prem data center, I likely want the provisioner to only pick up jobs from specific templates. However, the current behavior allows tagged provisioners to pick up any generic job as well.

```sh
coder provisionerd start \
  --tag environment=on_prem \
  --tag data_center=chicago

# In another terminal, create/push
# a template that requires this provisioner
coder templates create on-prem \
  --provisioner-tag environment=on_prem

# Or, match the provisioner exactly
coder templates create on-prem-chicago \
  --provisioner-tag environment=on_prem \
  --provisioner-tag data_center=chicago

# ⚠️ It is possible that this job is assigned to the on_prem provisioner
coder templates create random-template
```

## Workarounds

- Do not run any built-in provisioners, start all provisioners with tags, ensure all templates target a tag

## Ideas for potential fixes (in Coder)

- Set some default `provisoner-tag` for the built-in provisioners and templates
- Rework tags to work more like [Kubernetes taints/tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
- Specific tags to determine behavior of provisioner:
    ```sh
    coder provisionerd start --tag data_center=on_prem --tag tag_policy=<match-all/match-one/forgiving>
    ```
    Definitely need a different naming convention, though, I'm sure there is prior art in other things

**Comment by bpmct** [comment]
@sreya - assuming you're not doing this?

**Comment by matifali** [comment]
> Do not run any built-in provisioners, start all provisioners with tags, ensure all templates target a tag

This is not an easy workaround :(

**Comment by matifali** [comment]
We recently hit this on dev.coder.com when the dogfood template was picked up 25% of the time by two newly added provisioners. We should solve this by having a property to mark a provisioner as exclusive so that it does not pick generic jobs.

**Comment by johnstcn** [comment]
The current tag criterion for a provisioner P to accept a job J is if `J.Tags` ⊆ `P.Tags` -- that is, all of the tags of J must be in the tags of P. This could be described as a "permissive" tag policy, as this means that P can accept jobs with additional tags.

I think what we want in this case is a "restrictive" tag policy, where P will only accept J if the tags of J and P are equal. This would mean that untagged provisioners would only picked up untagged jobs, and 'tagged' provisioners would only pick up jobs with the corresponding tags.

In the scenario @matifali describes above, we would have updated our provisioner deployment to have a restrictive tag policy, and run the newly added tagged provisioners also with a restrictive tag policy.

**Comment by matifali** [comment]
Great description @johnstcn. Additionally, we should also allow adding/updating tags from terraform to allow controlling them as IaC. Currently it's only possible cus API, CLI or UI.

**Comment by johnstcn** [comment]
> we should also allow adding/updating tags from terraform to allow controlling them as IaC.

Can you file a separate issue for this?

**Comment by johnstcn** [comment]
The 'right' solution to this issue right now is to ensure that provisioners with no extra tags (`{"scope": "organization", "owner": ""}`) only pick up jobs with the exact same set of tags, and leave the rest of the tag matching behaviour untouched for now.

There is a wider conversation to be had around how tags should work. The "strict" versus "permissive" tag policy I outlined above goes part of the way there, but would cause friction when you have provisioner daemons that can handle multiple sets of tags.

**Comment by johnstcn** [comment]
Closing this out for now. We can revisit the concept of provisioner tag policies if we come across a use-case for it that isn't covered by the existing logic.
