### ISSUE TITLE
Template with web RDP client for Windows

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6448]
Related #2106.

We currently have a blog post that explains how to do [RDP + Visual Studio in Coder](https://coder.com/blog/microsoft-windows-visual-studio-in-coder), but it requires a local RDP client + port forwarding. Can we find a way to do this with a web-based RDP client as a [coder_app](https://coder.com/docs/v2/latest/ides/web-ides) in the template?

---

Leave a comment if you're interested in working on this!

**Comment by bpmct** [comment]
Am open to us having a windows template with web VNC too.

**Comment by matifali** [comment]
I have created a working demo that deploys a Windows VM on GCP and provides with a web RDP using [Myrtille](https://github.com/cedrozor/myrtille)
The template is available here: https://github.com/matifali/coder-templates/tree/main/gcp-windows-rdp
