### ISSUE TITLE
Templates can drift from version control

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6452]
## The problem

In the past 3 weeks, we've been manually pushing new template versions to our dogfood deployment, which has caused it to drift from the template we have in [./dogfood](https://github.com/coder/coder/tree/main/dogfood).

If someone makes a change to the dogfood template, CI will take over and overwrite all those changes.

## Potential solutions

- Stopgap to ensure users (even Owners or Template Admins) cannot promote template versions, only a specific service user can
- Template editor (and `coder templates push`) integrates with git and makes new commits/PRs

**Comment by MrPeacockNLB** [comment]
In an enterprise company this is a must have. Every change has to be documented and approved. So thumbs up!
