### ISSUE TITLE
coder needs to belong to docker group

### ISSUE THREAD

**Issue by abulte** [coder/coder#6458]
I did not find this in the doc, but (at least on a Debian package install) you need to add the `coder` user to the `docker` group in order to be able to create a docker template. Else, coder won't have the correct permission on `/var/run/docker.sock`.

**Comment by sharkymark** [comment]
We could put it in a better location than just the Docker install, since system package installs and others, that need workspaces on a Docker daemon would this. Thanks!

https://coder.com/docs/v2/latest/install/docker#permission-denied-while-trying-to-connect-to-the-docker-daemon-socket
