### ISSUE TITLE
Help user restart their workspace when it's in an unhealthy state

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6462]
This is what my AWS template looks like when my agent disconnected. The way to resolve this (temporarily) is to restart my workspace, but I would have to manually start/stop. There's also no good UI explaining what may have happened. 

![Screenshot 2023-03-06 at 9 36 24 AM](https://user-images.githubusercontent.com/22407953/223157012-dd177db4-6b5c-4c78-b2a1-715af1ccfff9.png)

**Comment by MrPeacockNLB** [comment]
I see this often in the morning. From users point of view it is confusing as it seems the workspace is running but one sees no applications.

This is related to: https://github.com/coder/coder/issues/6241

**Comment by matifali** [comment]
This is now available as per #6241.
if the issue is something differen, you may reopen. 
cc: @bpmct

**Comment by BrunoQuaresma** [comment]
I think we can on the FE, check if there are any agent disconnected and display a warning if there is. We can also add a restart button to the warning. What do you think?

**Comment by bpmct** [comment]
Mostly, we need to surface a better warning on the front end that instructs the user to restart. In an ideal state, this is consistent across FE, backend, API, and extension but the FE is a good start.

**Comment by mafredri** [comment]
[We can now use the `workspace.health.healthy` boolean from the API response](https://github.com/coder/coder/pull/8280) to determine whether or not to show the button. We can further explain what's wrong by checking failing agents / `agent.health.reason`.

**Comment by BrunoQuaresma** [comment]
So, what we can do here is to who in the "Workspace unhealthy warning" a button "Restart". Does it work?

**Comment by bpmct** [comment]
I didn't realize the unhealthy dialog made it in :)
