### ISSUE TITLE
Containerize `terraform` calls on Linux hosts

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6463]
From @spikecurtis:

> We can containerize the provisioning builds any time we are running on Linux. Docker & Kubernetes are not a requirement.
> 
> Also, I'm talking about containerizing the calls to terraform, and that can happen regardless of whether provisionerd runs in the same process as coderd or not, so we can keep the feature of having separate provisionerd as a paid feature, regardless of whether we make containerized builds a free or paid feature.

We have documented external provisioners here: https://coder.com/docs/v2/latest/admin/provisioners

**Comment by spikecurtis** [comment]
I think a straightforward way to do this is to import https://github.com/opencontainers/runc/tree/main/libcontainer
