### ISSUE TITLE
Pending workspace builds have an odd UX

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6465]
I created an old issue for this, but can't seem to find it. When a workspace is in a pending state, it could mean the following things:

- The queue is full (30 provisioner daemons, 30 concurrent builds)
- There are no provisioners running that match this template
  - If the template is tagged `scope=local` we can give the user instructions on how to start a [local provisoner](https://coder.com/docs/v2/latest/admin/provisioners#run-an-external-provisioner)
  - If the template is tagged separately, we should link to the [provisioner docs](https://coder.com/docs/v2/latest/admin/provisioners#run-an-external-provisioner) if the user is an owner or template admin

**Comment by mtojek** [comment]
> Just checking, is this a BE task?

Actually, it is a frontend task. I will take a look and see how far I can go.

**Comment by mtojek** [comment]
Battle plan based on the [RFC](https://www.notion.so/Build-visibility-0c8e9393aeb34a9994ca036715668a41):

- [ ] Badge `Position in queue: 3` in the workspace 
- [ ] Banner `Workspace build is pending \n Position in queue: 3`
