### ISSUE TITLE
Please put a stop button on failed workspaces

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#6468]
Failing Coder auto cleaning up failed workspaces after a certain time can you put a stop button for users to click when their workspace fails so they can clean up failed resources without having to delete the workspace. There is something about the "delete" button that users are inherently allergic to and we find ourselves having to clean up for them. We are trying to avoid tech debt writing custom code outside coder to do things like auto clean up failed workspaces.

People leaving failed or even stopped workspaces around forever is a pain point and we have enough tech debt around coder at the moment and don't want to extend it to a cleanup that I feel Coder could just have as a feature.

As you know we work with limited compute so it's often that users try to allocate and fail due to lack of available resources. But there are other reasons why they stop and fail as well. We log events to Cloudwatch so we can check later.

**Comment by dcarrion87** [comment]
Frustrating: https://github.com/coder/coder/issues/5815#issuecomment-1459885288

**Comment by BrunoQuaresma** [comment]
If the workspace is "failed" I would assume it is not started right? If is not started the user can't "stop" it. Am I missing something?

**Comment by kylecarbs** [comment]
@BrunoQuaresma a workspace is idempotent and can enter any state from failed. Failed can mean it failed to start, or failed to stop. It should probably show start or stop if we're in the failed state.

**Comment by BrunoQuaresma** [comment]
@kylecarbs when it is failed, how do we know the current status? Asking because the status right now can be "stopped" or "failed". https://github.com/coder/coder/blob/c3351484f186fa57cdc0557973a34c4a5ea43c11/site/src/api/typesGenerated.ts#L1408-L1418

**Comment by kylecarbs** [comment]
We don't need to know how it got into a failed state, because `failed` is its own state that can be directed into `stop` or `start`.
