### ISSUE TITLE
coder ssh: Process exited with status 127

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6480]
I don't think that the coder process should fail in this case:

```
./scripts/coder-dev.sh ssh admin/workspace1
$ kkk
/bin/sh: 1: kkk: not found
$ exit
Process exited with status 127
Run 'coder ssh --help' for usage.
```

This seems to be a valid execution flow.

**Comment by mafredri** [comment]
The returned exit code is correct (OpenSSH behaves the same), but we should be silent in this case, agreed. 👍🏻
