### ISSUE TITLE
Feature: non-interactive authentication to GitHub using OAuth/HTTPS inside a workspace

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#6488]
As a template author, I'd like to create a template that can perform GitHub actions, like forking a repo and/or checking out code into the workspace on build, without requiring the end user performing an authentication step on each new repo.

As an end user, I'd like to be able to use a template where I'm already authenticated with GitHub at start of day.

As a Coder administrator, I need this GitHub access to be over HTTPS, not SSH, as we have disabled SSH access according to company policy.

**Comment by bpmct** [comment]
I'm fairly sure external auth can be used to accomplish this today: https://coder.com/docs/v2/latest/admin/external-auth
