### ISSUE TITLE
Deployment-wide defaults for `coder config-ssh`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6500]
We have a customer who built a custom wrapper around the `coder` CLI in order to set default values for `coder config-ssh`, among other things. For example, they want to set `ForwardAgent yes` for each host.

In v2, Coder supports `coder config-ssh --ssh-option "ForwardAgent yes"`, but then each user has to do it. If there was a deployment-wide default, then every client could use these options with no custom wrapper or individual config needed.

For example

```sh
coder server --ssh-default-option "ForwardAgent yes" --ssh-default-option "AnotherOption yes"
```

or

```sh
CODER_SSH_DEFAULT_OPTION_0=ForwardAgent yes
CODER_SSH_DEFAULT_OPTION_1=AnotherOption yes
coder server
```

Not sure what the exact syntax would be for our config engine

**Comment by bpmct** [comment]
These should also apply to the VS Code extension!

**Comment by matifali** [comment]
I like these ideas.

**Comment by Emyrk** [comment]
This might make more sense to be an org scoped configuration. I know we don't really support that, so I can make it deployment wide right now.
