### ISSUE TITLE
Custom prefix for `coder config-ssh`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6501]
Right now, all SSH entries have the hostname `coder.<workspace>`. There can be two problems with this:

1. Conflicts with hosts from Coder v1
2. No way to "white label" it based for an internal platform/company name (e.g. `ssh devenvs.<workspace>`

Support a deployment-wide flag to set a default prefix (enterprise), and perhaps a local flag to override the prefix (OSS).

**Comment by Emyrk** [comment]
@bpmct do you think we should support anything more than a prefix? Such as allowing it to be a suffix, or nothing at all:

```
# User inputs can be some sort of "string replace" template
devenvs.<workspace_name>
# Can be put anywhere
<workspace_name>.ssh
# Is there any reason to make them include their username?
<user_name>.<workspace_name>
```


----

To be clear, I'll implement it as a standard prefix right now. Just spit-balling ideas.

**Comment by bpmct** [comment]
I'm totally open to supporting more formats if it's trivial! A note: the format should be defined deployment wide, but I can also see use cases for changing it per-client too 🤷🏼
