### ISSUE TITLE
Track startup script time + display estmate

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6502]
We currently track build time/estimates, but not startup scripts. As we are [starting to think about these holistically](https://github.com/coder/coder/issues/6461) and even added [an option](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#login_before_ready) to prevent users from entering their workspace before a startup script completes, we should track how long it takes for a startup script to complete as a metric and even consider showing an estimate in the workspace page.

**Comment by MrPeacockNLB** [comment]
Yeah good catch. We are using only one template for everything. So the main configuration part is done inside the startup-script but this depends havily on the configuration we are getting from a git repository (coder.yaml inside). This means you can track this only for each of the workspaces but not in summary for all of a template.

For it would much better if we can put back feedback to the UI / user in form of task x from y is done. May tasks can be shown with names. This way a user knows how long / how much time / tasks has to be done.

Example given: We have made a workspace prepared to dogfooding coder. Everything inside the coder.yaml defines what we need to develop a feature for coder. This takes some time (more tahn 5 Minutes). Setup Nix-Shell, Installing yarn (by the way is not in Nix), downloading code-server and extensions. And so on... This raises the Developer Experience.

Should I open a new Issue for this?

**Comment by bpmct** [comment]
Ah I see, kind of like GitHub actions steps

**Comment by bpmct** [comment]
Sorry, I realized I didn't answer your question. Please do. Feel free to suggest a specific design too :)
