### ISSUE TITLE
Block interactive sessions

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#6503]
Thought I'd put this here as someone might search later.

One of our templates provisions a bastion to proxy access to a bunch of other services that come up via helm charts. We don't actually want people terminal to it. Is it possible to specify something in the template to block ssh and terminal access?

Or is my best option to just intercept this in profile or other to throw an error and exit the user out immediately.

**Comment by MrPeacockNLB** [comment]
Do you mean you only want to show some buttons (coder apps) to get access to this services?

**Comment by bpmct** [comment]
> Is it possible to specify something in the template to block ssh and terminal access?

At this time, no

> Or is my best option to just intercept this in profile or other to throw an error and exit the user out immediately.

Yes.
