### ISSUE TITLE
ssh-rsa 

### ISSUE THREAD

**Issue by iondrugalea** [coder/coder#6516]
Hello,

currently, coder support only ssh key of type ssh-ed. Is there a chance to have the option to chose between ssh-ed or ssh-rsa keys?
AzureDevOps does not support ssh key of type ssh-ed.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/12760079/223850381-b4455d5a-9f3d-4ca2-85ab-76c09cf0494d.png">

Is the documentation correct here https://coder.com/docs/v1/v1.30/workspaces/preferences#ssh-keys ?

Thank you!

**Comment by iondrugalea** [comment]
Hey @kylecarbs,
thank you for quick response.  Just to be more precisely, i have coder v2 v0.17.4. and can not see the option you mentioned.
Is this an enterprise feature?

Thank you!

**Comment by kylecarbs** [comment]
@iondrugalea my bad! Nope, this is in v2. It's a command-line flag to change the SSH key generation. Run "coder server --help" to find it!

(I'd grab you the flag, but I'm on mobile right now so it's a bit tricky)

**Comment by idrugalea20** [comment]
@kylecarbs, thanks a lot. I've fixed it!
