### ISSUE TITLE
feat: custom headers are not passed to all websocket clients

### ISSUE THREAD

**Issue by JoshVee** [coder/coder#6520]
When passing custom headers to the Coder CLI (via `--header` \ `$CODER_HEADER`), these are not currently getting passed to all websocket connections. This can result in issues, for example, if a custom header is required for authentication.

**Example:**
```
➜  coder git:(green) coder templates push mytesttemplate -d templates/aws-linux 
> Upload "templates/aws-linux"? (yes/no) yes
✔ Queued [45ms]
⧗  Running
unexpected non-JSON response "text/html".
begin streaming logs: unexpected status code 200: unexpected non-JSON response "text/html"
	Error: <!DOCTYPE html>
```

**Comment by kylecarbs** [comment]
Ahh, we'll fix this!
