### ISSUE TITLE
Feature: Deprecate templates

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#6534]
The user should be able to deprecate a template. When a template is deprecated Coder will:
- Show a warning to the users on the workspace page
- Show a deprecated badge in the workspaces page - item table item row
- Don’t show the template in the templates table
- Don’t let users create a new workspace with a deprecated template

**Comment by sharkymark** [comment]
I know of at least one v1 enterprise customer who requires this.

**Comment by ericpaulsen** [comment]
@sharkymark @BrunoQuaresma we have another customer asking for this.

**Comment by ammario** [comment]
Duplicate of https://github.com/coder/coder/issues/6355
