### ISSUE TITLE
Is there a way to add additional metadata to coder user

### ISSUE THREAD

**Issue by NedkoHristov** [coder/coder#6536]
I'm going for an almost 100% automated setup. For that I need to setup git name (ex. John Doe). I don't want user to enter it manually.

What are my choices? I'm creating dev accounts so I can assign a secret to their user. Or there is a better way? The GitHub name will not be changed.

**Comment by bpmct** [comment]
We don't have a feature like this but we have been considering it for a while. Would it also be helpful if Coder could pull values from Hashicorp vault, for example?

**Comment by NedkoHristov** [comment]
Hashicorp Vault is okay, but we can do it even with env vars (for those who don't use Vault). Cheers, @bpmct .

**Comment by matifali** [comment]
closing in favour of #7087
