### ISSUE TITLE
feat: If all I am changing is a template's `README.md`, a `coder templates push` should not require re-build/update

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6566]
Version: [`v0.19.0+a666539`](https://github.com/coder/coder/commit/a666539bfaa02065eb6b48de147defccca77c5b5)

If all I am changing is a template's `README.md`, a `coder templates push` should not requirea workspace re-build/update

**Comment by matifali** [comment]
I thought I was the only one thinking this. Thanks for pointing it out.

**Comment by ammario** [comment]
It's nearly impossible to statically prove which files in the template your Terraform configuration reads. It's even more impossible once we implement other provisioners. We could have some way of marking a template push as cosmetic so it doesn't show an upgrade notification.

**Comment by matifali** [comment]
Maybe we can unbundle README from the template and package it as the template metadata, same as name, icon, description.

On a 2nd thought, this conflicts with our efforts to control templates, settings, and metadata as code.
