### ISSUE TITLE
site: do not show immutable parameters on build-parameters page.

### ISSUE THREAD

**Issue by matifali** [coder/coder#6569]
For the fly.io template, the list of regions is immutable and has more than 15 items. Showing it on the Build parameters page consumes a lot of space and gives no useful information as they can not be changed.

![image](https://user-images.githubusercontent.com/10648092/224551196-08ef043a-c245-4795-8367-3d8da012617f.png)

**Comment by matifali** [comment]
@BrunoQuaresma

**Comment by matifali** [comment]
@BrunoQuaresma what do you think about showing only mutable parameters here. The parameters that can actually be changed

**Comment by matifali** [comment]
cc: @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
I think this is totally reasonable.

**Comment by matifali** [comment]
@BrunoQuaresma 
I would suggest not allowing changing the name of the template as it can be used to create other resource names, for example, volumes. If it is just for display purposes, that is ok.
