### ISSUE TITLE
Hey @kylecarbs,

### ISSUE THREAD

**Issue by idrugalea20** [coder/coder#6570]
Hey @kylecarbs,
thank you for quick response.  Just to be more precisely, i have coder v2 v0.17.4. and can not see the option you mentioned.
Is this an enterprise feature?

Thank you!

_Originally posted by @iondrugalea in https://github.com/coder/coder/issues/6516#issuecomment-1461535524_

**Comment by kylecarbs** [comment]
@idrugalea20 I responded in our other flag just now. Thanks for the ping!
