### ISSUE TITLE
bug(aduit): GitHub failed login shows unknown user sign in.

### ISSUE THREAD

**Issue by matifali** [coder/coder#6574]
![image](https://user-images.githubusercontent.com/10648092/224707863-91841bbe-689c-47fc-9c90-c471d4705246.png)

cc: @Kira-Pilot

**Comment by Kira-Pilot** [comment]
@matifali I believe this is the same issue as https://github.com/coder/coder/issues/6108! Let me know if I'm mistaken; otherwise we can close in favor of the earlier issue.

**Comment by matifali** [comment]
That issue talk about new users but this is for users who already have running workspace just misconfigured GitHub login on code server

**Comment by matifali** [comment]
That issue talk about new users but this is for users who already have running workspace just misconfigured GitHub login on code server

**Comment by Kira-Pilot** [comment]
Ah, I hear you. I think the root cause is still the same - we see this issue issue because we don't currently have a good way of determining who the user is if they're not authenticated. Another related issue is https://github.com/coder/coder/issues/6054.

**Comment by matifali** [comment]
To avoid this may be you can ignore this case from the logs.

**Comment by Kira-Pilot** [comment]
I think we want to fix it rather than ignore it but we have to figure out a good way to temporarily track anonymous users.

**Comment by matifali** [comment]
You may close it as a duplicate if you see so.
