### ISSUE TITLE
web terminal activity does not contribute to "last used" in workspace list

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6575]
https://user-images.githubusercontent.com/22407953/224724324-87661f03-b913-44ec-8452-bf4479cc5037.mov

**Comment by matifali** [comment]
@johnstcn is it still true? This is an old issue and I think it doesn't apply anymore.

**Comment by johnstcn** [comment]
I can't reproduce this on 2.8.5; I can't recall when exactly this was fixed but we can close this out.
