### ISSUE TITLE
docs: workspace proxies

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6594]
Once everything in [the milestone](https://github.com/coder/coder/milestone/14) is completed, we should document:

- How to configure workspace proxies for Coder
- Best practices for running Coder multi-region (and how to know if you need custom DERP/custom dashboard)
- How to keep configuration and Coder server/proxy version in sync across regions (GitOps, or something else?)

**Comment by Emyrk** [comment]
Started here: https://github.com/coder/coder/pull/7377

**Comment by bpmct** [comment]
To close out:

- [ ] Document how to run a DERP-only workspace proxy (no dashboard)

**Comment by Emyrk** [comment]
Closing, can make new issues if more docs are required
