### ISSUE TITLE
Color Picker for Banner settings 

### ISSUE THREAD

**Issue by presleyp** [coder/coder#660]
As a developer, I want a reusable color picker component that I can use in the banner sections of the Settings (formerly Admin) page. It's used [here](https://master.cdr.dev/admin?tab=appearance) in v1.

- [ ] Copy/paste from v1 and tweak as needed (https://github.com/coder/m/blob/master/product/coder/site/src/components/ColorPicker/index.tsx)
- [ ] Put in storybook

**Comment by misskniss** [comment]
This was an early issue for V2 MVP. From a product perspective this is not a necessary parity item from V1. Closing this.
