### ISSUE TITLE
tokens: add a 'no expiration' option to CLI and UI

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#6607]
If the deployment config option `--max-token-lifetime` has not been set, we do not limit a token's lifetime at creation - unless a user explicitly passes through the `--lifetime` flag. 
We should give the user the ability to pass an option during creation that specifies the token never expires:

- we should add the 'no expiration' option to the CLI
- we should add the 'no expiration' option to the UI (mock [here](https://www.figma.com/file/oXAFu6Z4Pmv7GGux16ZjAK/Token-Creation?node-id=0%3A1&t=RQuYKUHD20qxeACd-0))
- we should reimagine the way we represent the max token lifetime on the back end, pivoting away from `time.Duration(math.MaxInt64)` to something the FE can more easily represent (like `Date`). Right now we are converting to nanoseconds and its annoying.

**Comment by matifali** [comment]
@Kira-Pilot, should we close this as completed?

**Comment by Kira-Pilot** [comment]
@matifali good call! not sure why this was still open.
