### ISSUE TITLE
Migrating a template to use rich parmaeters: can't be used together with legacy parameters

### ISSUE THREAD

**Issue by NiklasRosenstein** [coder/coder#6615]
Hello,

I'm trying to update a template to use rich parameters. (Coder v0.19.2, TF provider v0.6.18)

I've added a `data "coder_parameter"` block for every non-sensitive `variable` and filled out `legacy_variable` and `legacy_variable_name` as per the [documentation](https://coder.com/docs/v2/latest/templates/parameters).

But when I push, I get this error:

```  
✘ Cleaning Up [7ms]
template import provision for start: rich parameters can't be used together with legacy parameters, set the coder provider flag "feature_use_managed_variables = true" to enable managed variables
Run 'coder templates push --help' for usage.   
```

But according to the documentation, I should only enable `feature_use_managed_variables` at step 5, for the third template version. I'm only at making a first version of the three for the rich parameter migration.

I've also not been able to figure out yet how sensitive template variables would be defined with rich parameters. Would we keep using a `variables ... { sensitive = true }` block for that?

**Comment by mtojek** [comment]
Hi! Support for `legacy_variable` and `legacy_variable_name` has been enabled in this [commit](https://github.com/coder/coder/commit/7587850a1c454aeb7a416c96e34eed386ef0b22a), so you can either wait for the next release or try building it from the source.

With that change, old and new parameters can coexist for the purpose of migration.
