### ISSUE TITLE
zsh & fish shells return error for `coder server --experiments=*`

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#6620]
using latest, `0.19.2`. `bash` executes the command correctly. see the below errors:

```
fish: No matches for wildcard '--experiments=*'. See `help expand`.
coder server --experiments=*
```

```
zsh: no matches found: `--experiments`
```

**Comment by bpmct** [comment]
There's nothing we can do here, it's a byproduct of bash. `*` = every file in current directory

You can bypass with `coder server --experiments '*'`

**Comment by bpmct** [comment]
Gonna close, I don't think it's super important to fix this rn. I suppose we could change `*` to `all` but I don't think it's worth the dev time.
