### ISSUE TITLE
rich parameters: prompt user for variables on `coder template create`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6625]
Our CLI getting started flow with starter templates could be simplified by prompting users for required variables. Today, you have to specify with `--variable image=here-it-is`

<img width="566" alt="Screenshot 2023-03-28 at 10 42 48 AM" src="https://user-images.githubusercontent.com/22407953/228292844-242ca41b-7846-4c18-9b51-cf3e5bd1ca36.png">

**Comment by bpmct** [comment]
<img width="566" alt="Screenshot 2023-03-28 at 10 42 48 AM" src="https://user-images.githubusercontent.com/22407953/228292844-242ca41b-7846-4c18-9b51-cf3e5bd1ca36.png">

**Comment by mtojek** [comment]
Command line switches or `config.yml` files are good for the automation/scripted access but agree that we may want to improve it for regular users.

The workflow would be pretty similar to frontend, so:
1. Push the template version.
2. Load template variables.
3. Iterate over and prompt for variables.

It would be nice not to mix it with old parameters.

In terms of complexity, the hardest part would be implementing the `secret` CLI input. I doubt that the CLI library supports it out of the box.

_Alternatively, a template author can prepare `values.yml` file with variable values, but I guess that it doesn't fill the gap._ I tried using the EDITOR, and it can open `vim` and retrieve the output file, but it's really unpleasant experience (extra confirmation, saving file, etc.). 

Should we also support "template update without re-pushing the file"?

**Comment by bpmct** [comment]
Thanks, that all makes sense to me. Yeah, I am concerned about the flow for the regular user who does `coder templates init` and get stuck at the "missing variable" message. 

> Should we also support "template update without re-pushing the file"?

Like some way to watch for changes and push new changes? I'm not sure exactly how this would work.
