### ISSUE TITLE
cannot use built-in ingress with cert-manager

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6634]
For some reason, cert-manager will only read a single TLS host when the `hosts` line is duplicated in the ingress resource. Kubernetes seems to handle it fine. 

https://github.com/coder/coder/blob/811a69f37173a688adf3880b545252f61fe747f7/helm/templates/ingress.yaml#L45-L50

I had to manually change the ingress to this for cert-manager to do both certificates.

```sh
 - hosts: 
     - coder.example.com
     - *.coder.example.com
```

Is this a quick fix on our end or should I report this with cert-manager?

**Comment by deansheather** [comment]
Cannot reproduce with a self-signed issuer on latest cert-manager. Two certificate objects get created in the namespace with the correct names. Can you please provide repro steps and ensure you're on the latest version of cert-manager? @bpmct

**Comment by bpmct** [comment]
Maybe this was a fluke. I remember manually editing my ingress object and putting the two hosts together, and then the cert was generated. I wonder if the update event kicked off cert-manager again 🤔 

Thanks for investigating @deansheather. I'll close for now and will reopen if it happens again (I'll be documenting cert-manager soon so I'll go through the steps then). #6254 

Thanks for investigating, sorry about that!

**Comment by deansheather** [comment]
Ingress updates do trigger cert manager to refresh but maybe it just got lost or something :/
