### ISSUE TITLE
Add Secrets parameter

### ISSUE THREAD

**Issue by dsloanather** [coder/coder#6636]
We need the ability for a developer to provide their auth details when starting up a new machine so that when it is running it is completely ready to go.  Would it be possible to add a secure parameter to provide those (ie artifactory access token)

**Comment by kylecarbs** [comment]
cc @mtojek

**Comment by bpmct** [comment]
related: #5981

**Comment by mtojek** [comment]
Is it a parameter whose secret value is common for every workspace, or is it different per user? 

If the first one, you can use managed Terraform variable with the `sensitive = true` flag. If the latter one, we need to implement it.

**Comment by bpmct** [comment]
@dsloanather Do you also use Hashicorp vault? Would you also be interested in parameters that can fetch (or create) values from Vault on behalf of the user?

**Comment by dsloanather** [comment]
We use AWS secrets manager, currently using that to pull admin tokens to create user access tokens but would much rather just have the user be able to provide their own

**Comment by matifali** [comment]
closing in favour of #7087
