### ISSUE TITLE
Server cert error upon ssh into workspace (after upgrade)

### ISSUE THREAD

**Issue by ppat** [coder/coder#6640]
**Observed:**
```
❯ ssh coder.peter-dev
2023/03/16 12:52:27 tlsdial: warning: server cert for "coder.dev.ourdomain.io" is not a Let's Encrypt cert
```
Note: This doesn't prevent ssh'ing in, it still works. 

**Context:**
- Coder version: `0.19.2` (server and client both)
- We're running Coder behind a nginx proxy.
- Traffic Route:    
  ```mermaid
  graph TD;
      A[user]-->B[aws elb];
      B -- tls passthrough --> C[aws instance];
      C-->D[nginx process];
      D --  tls terminated at nginx -->E[coder process];
  ```
- See attached `userdata.tpl` for `/etc/coder.d/coder.env` and nginx configuration. 
- Nginx configuration mostly follows the recommendations from - https://github.com/coder/coder/tree/main/examples/web-server/nginx
- TLS cert served by NGINX is not issued by LetsEncrypt or an internal CA, but by a public CA (digicert).
- No TLS_* fields set in coder configuration. (see attached)

**Comment by ppat** [comment]
[userdata.tpl.txt](https://github.com/coder/coder/files/10995386/userdata.tpl.txt)

**Comment by ppat** [comment]
discord convo: https://discord.com/channels/747933592273027093/1085972563127193720

**Comment by coadler** [comment]
This just seems to be a harmless warning message from Tailscale. See https://github.com/tailscale/tailscale/pull/7149.

**Comment by bpmct** [comment]
Can we hide the message or remove it from our fork or something? It can be quite confusing for admins and users alike, especially if the Coder doesn't use LetsEncrypt certs 😅

**Comment by coadler** [comment]
Yeah, we could probably hide this.

**Comment by janLo** [comment]
I really see this quite often. Is there maybe an envvar that I can set to hide this?

**Comment by bpmct** [comment]
We'll do a fix for this soon
