### ISSUE TITLE
Docker-in-Docker Privileged docker sidecar instruction does not work

### ISSUE THREAD

**Issue by yulilywu** [coder/coder#6659]
I have been using container-based Coder workspaces that is created and hosted on my Redhat7 VM. I only have Docker daemon installed on the rhel7 vm, no K8s etc. I have updated docker-image-builds templates and I was able to create workspace using the updated templates and connect to it using VS Code. 

Now I need my workspace to have ability to run docker containers, so I am following [Privileged docker sidecar] (https://coder.com/docs/v2/latest/templates/docker-in-docker#privileged-sidecar-container) instructions. However, it seems that coder server failed to connect to my coder agent. I got the following error:

```
[docker-image-builds]$ docker exec -it 565086bec8a3 ps axuww
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
coder         1  0.0  0.0   2600   724 ?        Ss   21:08   0:00 sh -c #!/usr/bin/env sh set -eux # Sleep for a good long while before exiting. # This is to allow folks to exec into a failed workspace and poke around to # troubleshoot. waitonexit() { .echo "=== Agent script exited with non-zero code. Sleeping 24h to preserve logs..." .sleep 86400 } trap waitonexit EXIT BINARY_DIR=$(mktemp -d -t coder.XXXXXX) BINARY_NAME=coder BINARY_URL=https://coder-dev2.chq.ei:3001/bin/coder-linux-amd64 cd "$BINARY_DIR" # Attempt to download the coder agent. # This could fail for a number of reasons, many of which are likely transient. # So just keep trying! while :; do .# Try a number of different download tools, as we don not know what we .# will have available. .status="" .if command -v curl >/dev/null 2>&1; then ..curl -fsSL --compressed "${BINARY_URL}" -o "${BINARY_NAME}" && break ..status=$? .elif command -v wget >/dev/null 2>&1; then ..wget -q "${BINARY_URL}" -O "${BINARY_NAME}" && break ..status=$? .elif command -v busybox >/dev/null 2>&1; then ..busybox wget -q "${BINARY_URL}" -O "${BINARY_NAME}" && break ..status=$? .else ..echo "error: no download tool found, please install curl, wget or busybox wget" ..exit 127 .fi .echo "error: failed to download coder agent" .echo "       command returned: ${status}" .echo "Trying again in 30 seconds..." .sleep 30 done  if ! chmod +x $BINARY_NAME; then .echo "Failed to make $BINARY_NAME executable" .exit 1 fi  export CODER_AGENT_AUTH="token" export CODER_AGENT_URL="https://coder-dev2.chq.ei:3001/" exec ./$BINARY_NAME agent 
coder        43  0.0  0.0   2500   636 ?        S    21:12   0:00 sleep 30
coder        44  0.0  0.0   5884  1484 pts/0    Rs+  21:12   0:00 ps axuww
```
I have attached my main.tf and my image files. I select java option to create my workspace.
If someone can point out what I did wrong, that'd be great! I have spent hours and couldn't figure out why it's not working.
Thanks a lot!
[docker-image-builds.zip](https://github.com/coder/coder/files/11009845/docker-image-builds.zip)

**Comment by sharkymark** [comment]
The example you shared doesn't have a second container with `dind` - maybe consider a template which takes the image building out of the equation for simplicity too. Here's one of mine that works which you can model after.

https://github.com/sharkymark/v2-templates/blob/main/docker-in-docker/docker-with-docker-network/main.tf

I put our docs here again
https://coder.com/docs/v2/latest/templates/docker-in-docker#use-a-privileged-sidecar-container-in-docker-based-templates

Notice the two `docker_container` resources

```hcl
resource "docker_container" "dind" {  
  count   = data.coder_workspace.me.start_count  
  image      = "docker:dind"
  privileged = true
  name       = "dind-${data.coder_workspace.me.id}"
  entrypoint = ["dockerd", "-H", "tcp://0.0.0.0:2375"]
  networks_advanced {
    name = docker_network.private_network.name
  }
}

resource "docker_container" "workspace" {
  count   = data.coder_workspace.me.start_count
  image   = "codercom/enterprise-base:ubuntu"
  name    = "dev-${data.coder_workspace.me.id}"
  command = ["sh", "-c", coder_agent.coder.init_script]
  env = [
    "CODER_AGENT_TOKEN=${coder_agent.coder.token}",
    "DOCKER_HOST=${docker_container.dind[0].name}:2375"
  ]
  volumes {
    container_path = "/home/coder/"
    volume_name    = docker_volume.coder_volume.name
    read_only      = false
  }    
  networks_advanced {
    name = docker_network.private_network.name
  }
}
```

**Comment by yulilywu** [comment]
Thanks @sharkymark for getting back to me! I think the main.tf.dndtrial was the file that I used and I did copy the above dind and workspace docker_container resources in my file. I think it is stuck at 

`sh -c #!/usr/bin/env sh set -eux # Sleep for a good long while before exiting. # This is to allow folks to exec into a failed workspace and poke around to # troubleshoot. waitonexit() { .echo "=== Agent script exited with non-zero code. Sleeping 24h to preserve logs..." .sleep 86400 } trap waitonexit EXIT BINARY_DIR=$(mktemp -d -t coder.XXXXXX) BINARY_NAME=coder BINARY_URL=https://coder-dev2.chq.ei:3001/bin/coder-linux-amd64 cd "$BINARY_DIR" # Attempt to download the coder agent. # This could fail for a number of reasons, many of which are likely transient. # So just keep trying! while :; do .# Try a number of different download tools, as we don not know what we .# will have available. .status="" .if command -v curl >/dev/null 2>&1; then ..curl -fsSL --compressed "${BINARY_URL}" -o "${BINARY_NAME}" && break ..status=$? .elif command -v wget >/dev/null 2>&1; then ..wget -q "${BINARY_URL}" -O "${BINARY_NAME}" && break ..status=$? .elif command -v busybox >/dev/null 2>&1; then ..busybox wget -q "${BINARY_URL}" -O "${BINARY_NAME}" && break ..status=$? .else ..echo "error: no download tool found, please install curl, wget or busybox wget" ..exit 127 .fi .echo "error: failed to download coder agent" .echo "       command returned: ${status}" .echo "Trying again in 30 seconds..." .sleep 30 done  if ! chmod +x $BINARY_NAME; then .echo "Failed to make $BINARY_NAME executable" .exit 1 fi  export CODER_AGENT_AUTH="token" export CODER_AGENT_URL="https://coder-dev2.chq.ei:3001/" exec ./$BINARY_NAME agent `


I tried your main.tf from https://github.com/sharkymark/v2-templates/blob/main/docker-in-docker/docker-with-docker-network/main.tf as it is, and it shows the same "agent is taking too long to connect" error message. This is what I see in the workspace docker container startup:
`coder         1  0.0  0.0   2600   724 ?        Ss   16:04   0:00 sh -c #!/usr/bin/env sh set -eux # Sleep for a good long while before exiting. # This is to allow folks to exec into a failed workspace and poke around to # troubleshoot. waitonexit() { .echo "=== Agent script exited with non-zero code. Sleeping 24h to preserve logs..." .sleep 86400 } trap waitonexit EXIT BINARY_DIR="${BINARY_DIR:-$(mktemp -d -t coder.XXXXXX)}" BINARY_NAME=coder BINARY_URL=https://coder-dev2.chq.ei:3001/bin/coder-linux-amd64 cd "$BINARY_DIR" # Attempt to download the coder agent. # This could fail for a number of reasons, many of which are likely transient. # So just keep trying! while :; do .# Try a number of different download tools, as we don not know what we .# will have available. .status="" .if command -v curl >/dev/null 2>&1; then ..curl -fsSL --compressed "${BINARY_URL}" -o "${BINARY_NAME}" && break ..status=$? .elif command -v wget >/dev/null 2>&1; then ..wget -q "${BINARY_URL}" -O "${BINARY_NAME}" && break ..status=$? .elif command -v busybox >/dev/null 2>&1; then ..busybox wget -q "${BINARY_URL}" -O "${BINARY_NAME}" && break ..status=$? .else ..echo "error: no download tool found, please install curl, wget or busybox wget" ..exit 127 .fi .echo "error: failed to download coder agent" .echo "       command returned: ${status}" .echo "Trying again in 30 seconds..." .sleep 30 done  if ! chmod +x $BINARY_NAME; then .echo "Failed to make $BINARY_NAME executable" .exit 1 fi  export CODER_AGENT_AUTH="token" export CODER_AGENT_URL="https://coder-dev2.chq.ei:3001/" exec ./$BINARY_NAME agent`

I am running behind corporate firewall. Not sure if that contributes to these errors.

**Comment by yulilywu** [comment]
It turns out it is the proxy issue behind corporate firewalls. I created my custom image based off codercom/enterprise-base:ubuntu with proxy settings, now my workspace starts up properly. However I still cannot run docker commands in my workspace terminal due to some company policies. That seems not related to whether your docker-in-docker instruction. I will look into that separately. Thanks a lot for your help!
