### ISSUE TITLE
startup_script replaced something weird when I executed it

### ISSUE THREAD

**Issue by sujoshua** [coder/coder#6660]
```hcl
resource "coder_agent" "coder" {
  os = "linux"
  arch = "amd64"
  dir = "/home/coder"
  env = { "CHOOSE" = lookup(local.ide-dir, var.ide)}
  startup_script = <<EOT
 #!/bin/bash
 
 #use coder CLI to clone and install dotfiles
 
 coder dotfiles -y ${var.dotfiles_uri}
 
 #script to symlink JetBrains Gateway IDE directory to image-installed IDE directory
 
 #More info: https://www.jetbrains.com/help/idea/remote-development-troubleshooting.html#setup
 
 cd "/opt/$CHOOSE/bin"
 ./remote-dev-server.sh registerBackendLocationForGateway
  EOT  
}
```

My resources is defined like above. and my purpose is entering the specific dir to execute shell to install IDE, the specific dir name `CHOOSE` is selectd according to the IDE user choose in `var.ide` and the value lookup in `local.ide-dir`.

`local.ide-dir` is defined：

```hcl
ide-dir = {
  "IntelliJ IDEA Ultimate" = "idea",
  "PyCharm Professional" = "pycharm",
  "GoLand" = "goland",
  "WebStorm" = "webstorm" 
 }
```

But when I start a new workspace, and look into the coder-startup-script.log, I get this

```sh
Run 'coder dotfiles --help' for usage.
/bin/bash: line 5: cd: $'/opt/goland/bin\r': No such file or directory
/bin/bash: line 6: ./remote-dev-server.sh: No such file or directory
```

It should be `cd /opt/goland/bin`, but now it is `cd: $'/opt/goland/bin\r'`

Could you please tell me how the startup_script work? why the `$'\r'` appears unexpectedly.

**Comment by sharkymark** [comment]
It looks like you based yours on one of my templates, which I ran now and it works fine.

What parts did you change? If the images are not paid versions of JetBrains IDEs, the `remote-dev-server.sh` will not be in `/opt/<ide>/bin` but it seems your `cd` isn't even working. my example also does not have quotes in the `cd`

https://github.com/sharkymark/v2-templates/blob/main/pod-gateway-ide/main.tf

**Comment by roshvin** [comment]
HI ,
i have faced same issue . i changed the encoding to LF from CRLF and saved the file . pushed the template again and it worked.

![image](https://user-images.githubusercontent.com/11057966/226279824-b68392e7-b0c7-462b-a4c5-b7890ee6540a.png)

**Comment by matifali** [comment]
closing in favour of #5917
