### ISSUE TITLE
feat: Put license details in the admin UI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6673]
Version: [`v0.19.2+7eb2c2f`](https://github.com/coder/coder/commit/7eb2c2ff6d229619f88f41e9b2b185714a967619)

Currently, Coder v2 uses the CLI to add, list and delete licenses.

The expiration date is in Unix Epoch or Unix time so I have to use a Epoch converter like https://www.epochconverter.com/ to figure this out.

This should be show in the UI along with other license details.

![image](https://user-images.githubusercontent.com/2022166/226372417-ff72f1a3-d9b3-4347-a4f1-d0e691c023df.png)

**Comment by bpmct** [comment]
Thinking we should show the following:

- User limit (and current user count)
- Expiration date in human-readable format
- Whether it is a trial license
- A link to the docs on how to add/remove licenses

Nice to have:

- [Add/remove the license from UI](https://coder.com/docs/v2/latest/enterprise#adding-your-license-key)
