### ISSUE TITLE
Bug: Filtering and pagination are not working as expected

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#6678]
I noticed the pagination is not working as expected when using filtering. Items are getting duplicated on pages 1 and 2:
https://user-images.githubusercontent.com/3165839/226400819-7979e480-0534-4ef2-9cb9-f47552cce55b.mov

When using filtering and pagination looks like it is getting conflicted:
https://user-images.githubusercontent.com/3165839/226400500-8a9ed00a-7ceb-4a50-a935-1b7272067848.mov

**Comment by Emyrk** [comment]
Yes the frontend is not passing correct values to the backend. I will work on fixing this in the TS
