### ISSUE TITLE
a `member` aka developer or data scientist, can revert to any version of a template they want to

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6684]
One of the benefit statements of Coder is centralized control of developers' environments.

In a Coder context, that means restricting which template and container image developers can use.

In v2, container images are defined in a template, but the way v2 operates is a developer can revert to previous template versions at their will - which may have deprecated or older container images.

Recommended feature request/enhancement:

1. Some DevOps teams support free-wheeling, creative engineering orgs who may like this feature. e.g., 20-person startup who has no controls and just wants to do anything they want, and 1000-user advanced tech company in Silicon Valley who have a vibe of do what you want - we want to you crank out code - so make this an admin-enabled configuration. The so-called Coder environment variable at `coder server` or something like that.
2. Then there is the 'rest of the world' e.g., regulated industries, like top 20 banks, or public sector, US military or intelligence - who want fine-grained controls on what developers and data scientists can, and cannot do.
3. Enabling any version - should be `opt in` and off by default, since the majority of Coder's existing customer base expects complete lock-down of development environment choices

![image](https://user-images.githubusercontent.com/2022166/226493924-07a71e50-67f8-4b2f-b8f8-8d3b2291f6d7.png)

Have fun developer!

![image](https://user-images.githubusercontent.com/2022166/226493971-d385e72a-88d2-406f-bc91-c3065850cbc4.png)

Bad end states that can result:
1. DevOps teams actually do not control the development environments like they think
4. Old template versions may break resulting in a failed build e.g., image tag no longer exists

**Comment by sharkymark** [comment]
This was completed - in this Issue #6635  - should be in next release.

**Comment by sharkymark** [comment]
Re-opening and updated the original post, recognizing the feature has been disabled, and may be configurable in a future release.

**Comment by bpmct** [comment]
The new behavior only makes "change version" open to template admins.

**Comment by matifali** [comment]
@sharkymark  Should we close this as completed?

**Comment by bpmct** [comment]
We're solving this with #7468
