### ISSUE TITLE
Cannot visit jupyter lab service possibly due to subdomain configuration 

### ISSUE THREAD

**Issue by garylavayou** [coder/coder#6688]
## What the problem

In the workspace dashboard, the jupyter lab is showing but prevent user to access it with prompting message `Your admin has not configured subdomain application access`, which is showing in the figure:

![image](https://user-images.githubusercontent.com/25133690/226565706-433a76f1-495a-4b76-9f2e-1eb373bfca7b.png)

## My Configuration

I used the official `docker-compose.yaml` and change the docker image to my local build version (with the terraform configuration included, according to [the official docs](https://coder.com/docs/v2/latest/install/offline)). The jupyter "code_app" in the template file `main.tf` is (copy from the offical docs, which put an emphasis on setting "`subdomain=true`", but without explaining why it is critical):

```terraform
resource "coder_app" "jupyter" {
  agent_id     = coder_agent.main.id
  slug         = "jupyter"
  display_name = "JupyterLab"
  url          = "http://localhost:8888"
  icon         = "/icon/jupyter.svg"
  share        = "owner"
  subdomain    = true

  healthcheck {
    url       = "http://localhost:8888/healthz"
    interval  = 5
    threshold = 10
  }
}
```

The above configuration together with the warning message reminds me that it seems I need to add a subdomain configuration. So, I searched the docs and found the following information that might help.

> `CODER_WILDCARD_ACCESS_URL` is necessary for [port forwarding](https://coder.com/docs/v2/latest/networking/port-forwarding#dashboard) via the dashboard or running [coder_apps](https://coder.com/docs/v2/latest/templates#coder-apps) on an absolute path. Set this to a **wildcard subdomain** that resolves to Coder (e.g. `*.coder.example.com`).

So, I set the environment variables in `.env`, along with the `docker-compose.yaml` file. The following is content in `.env`:

```bash
CODER_VERSION=0.19
CODER_ACCESS_URL='http://coderdev.ica:7080'
CODER_WILDCARD_ACCESS_URL='*.coderdev.ica'
```
> `coderdev.ica` is resolve to my host machine.

The jupyter binaries is build into image and I start it with

```bash
/opt/miniconda3/envs/jupyter/bin/jupyter lab \
    --ServerApp.token='' \
    --ip='*'  --port=8888 --no-browser \
    > /tmp/jupyter.log 2>&1 &
```
and the jupyter is running with logs:

```bash
[I 2023-03-21 10:06:02.013 ServerApp] Serving notebooks from local directory: /home/coder
[I 2023-03-21 10:06:02.013 ServerApp] Jupyter Server 2.5.0 is running at:
[I 2023-03-21 10:06:02.013 ServerApp] http://localhost:8888/lab
[I 2023-03-21 10:06:02.013 ServerApp]     http://127.0.0.1:8888/lab
[I 2023-03-21 10:06:02.013 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2023-03-21 10:06:04.374 ServerApp] Generating new user for token-authenticated request: 676281164cb1474287f7f3f934a7fac6
[W 2023-03-21 10:06:04.407 ServerApp] 404 GET /healthz (676281164cb1474287f7f3f934a7fac6@127.0.0.1) 34.21ms referer=None
```

## What is expected

After setting `CODER_WILDCARD_ACCESS_URL`,  I should be able to access jupyter app / port forwarding from the workspace dashboard.

## What it needed

The official docs could be added with more details about `CODER_WILDCARD_ACCESS_URL`, and how it affect the usage of subdomains in accessing coder apps or the port forwarding function.

**Comment by sharkymark** [comment]
@garylavayou There is a way to run Jupyter without `subdomain=true` by passing the owner and workspace name to the Jupyter `base_url` in `startup_script` and the `coder_app` `url`

See this example in my repo
https://github.com/sharkymark/v2-templates/blob/main/docker-jupyter-path/main.tf

Not sure why your wildcard subdomain is not working

**Comment by garylavayou** [comment]
> @garylavayou There is a way to run Jupyter without `subdomain=true` by passing the owner and workspace name to the Jupyter `base_url` in `startup_script` and the `coder_app` `url`
> 
> See this example in my repo https://github.com/sharkymark/v2-templates/blob/main/docker-jupyter-path/main.tf

Thanks, @sharkymark ! I have used the template, and it works! The updated part of the template is listed here (part of contents not changed are ignored here):
```terraform
resource "coder_app" "jupyter" {
  agent_id     = coder_agent.main.id
  slug         = "jupyter"
  display_name = "JupyterLab"
  # url -> /<user>/<workspace>/apps/<slug>
  url          = "http://localhost:8888/@${data.coder_workspace.me.owner}/${lower(data.coder_workspace.me.name)}/apps/jupyter"
  icon         = "/icon/jupyter.svg"
  share        = "owner"
  subdomain    = false
}
```

```terraform
resource "coder_agent" "main" {
  arch = data.coder_provisioner.me.arch
  os   = "linux"

  login_before_ready     = false
  startup_script_timeout = 300
  startup_script         = <<-EOT
  export JUPYTER_BASE_URL=/@${data.coder_workspace.me.owner}/${lower(data.coder_workspace.me.name)}/apps/jupyter
  bash /opt/code-server/startup.sh
  EOT
}
```
The start commands are put into `/opt/code-server/startup.sh` in the image (as I need to do more initialization logic), the related part is:
```bash
export PATH=/home/coder/.conda/envs/jupyter/bin:$PATH
jupyter lab --ip='*' --port=8888 --no-browser \
        --ServerApp.token='' \
        --ServerApp.base_url="$JUPYTER_BASE_URL" \
        > /home/coder/logs/jupyter.log 2>&1 &
cat /home/coder/logs/jupyter.log
```

**Comment by garylavayou** [comment]
> Not sure why your wildcard subdomain is not working

@sharkymark I have read more carefully through the docs and some other templates, and found the reason is that the `CODER_WILDCARD_ACCESS_URL` variable defined in `.env` is actually not referred in the `docker-compose.yaml` file. So finally, it is not passed to the coder instance. (Sorry about that I am not very familiar with the usage of docker compose file). To use the variable that is define in `.env`, set the corresponding definition in `docker-compose.yaml`:

```yaml
services:
  coder:
    image: ghcr.io/coder/coder:${CODER_VERSION:-latest}
    ports:
      - "443:443"
    environment:
      CODER_ACCESS_URL: "${CODER_ACCESS_URL}"
      CODER_WILDCARD_ACCESS_URL: "${CODER_WILDCARD_ACCESS_URL}"  # referred here
```
After reboot the instance, and visiting the **Deployment/General** page of the web portal, I can find the wildcard access is displayed, as the following figure shows
![image](https://user-images.githubusercontent.com/25133690/227087975-58c21a75-1a3b-416d-a328-d4ab19d3632a.png)

Also, I can see that port-forwarding is enabled, showing in **Deployment/Network** the page and the workspace page.
![image](https://user-images.githubusercontent.com/25133690/227088364-a16c7aef-e73d-400e-aef8-955e263c54eb.png)
![image](https://user-images.githubusercontent.com/25133690/227088615-16b02d3f-0027-4e62-bc89-d808113b277a.png)
