### ISSUE TITLE
Search helpers for better search bar experience

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#6699]
# Problem

Currently our search bars do not include much UX to help instruct the user on what is possible. We have some preset `filters`, but that does not tell the user of all the possible options.

# Vision

The user should be able to use and discover the search query parameters without needing to consult coder.com/docs. The UI/UX should be enough for the majority of search needs.

# Ideas

A popular idea is to take inspiration from Github's search bar helpers. This is a series of dropdown menus that alter the search query. 

![Screenshot from 2023-03-21 12-30-25](https://user-images.githubusercontent.com/5446298/226693126-50921b71-d59b-4e3b-8f97-e289ad3f68f2.png)

**Comment by matifali** [comment]
We have plenty of [filters](https://coder.com/docs/v2/latest/workspaces#workspace-filtering) now for the workspace and audit logs pages. 
![image](https://github.com/coder/coder/assets/10648092/1f15dd22-a996-4f55-b3e0-83fa06adfa65)

**Comment by Emyrk** [comment]
Yea, there are still a number of undocumented, but we are much better.
