### ISSUE TITLE
for existing workspaces: enforce default value of immutable parameter

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6716]
Current behavior: If an existing workspace is being updated to a new version that introduces an immutable parameter, the current behavior will prompt the user for a value.

Proposed behavior: if there is a default value for an immutable parameter, this should be enforced for existing workspaces. For new workspaces that are updating.

**Comment by mtojek** [comment]
> Current behavior: If an existing workspace is being updated to a new version that introduces an immutable parameter, the current behavior will prompt the user for a value.

Wasn't there a backend error prohibiting you from doing this?

Linking the internal discussion: [slack](https://codercom.slack.com/archives/C04M9CNGHGF/p1678383765366489)

My opinion is aligned with the slack thread above, so I would be rather for keeping the existing behavior, and letting template authors temporarily unlock `immutable` to `false. This trick is also described in [docs](https://coder.com/docs/v2/latest/templates/parameters#mutability).

I can see that this is a hot topic, and causes a lot of tension. If it is more clear or convenient to violate the immutability in this particular case, we can do this.

I just need the final decision that this is what we want 👍

**Comment by BrunoQuaresma** [comment]
@bpmct I guess it is already fixed by @kylecarbs right?

**Comment by BrunoQuaresma** [comment]
Closing in favor of https://github.com/coder/coder/issues/6941
