### ISSUE TITLE
Does coder respects 100% terraform code or intersepts?

### ISSUE THREAD

**Issue by NedkoHristov** [coder/coder#6718]
Hi all,

It's a long ball, but I need some help. So we have our custom terraform template based on official DO template and there is an issue with tags. So we have a corner case where sometimes the tags are being deleted on workflow destroy. This does not occur when we use vanilla TF.

Does coder respects 100% the TF code or there are some interception from coder side?

I've declared the tags in digitalocean_droplet with:
```
tags = ["example"]
```

I've tried to create a tag resource but the issue persist.

**Comment by kylecarbs** [comment]
There's no subset or superset, we just use native Terraform. Are you certain some other oddity isn't happening here?
