### ISSUE TITLE
Drill-down view: workspace network latency & disconnects

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6724]
Prometheus metrics around network disconnects (+ reason) and user latency in workspaces. Drill down to workspace, IDE, and connection type

1. Add Prometheus metrics around network disconnects (incl. reason)
2. Measure user latency, drill down to dimensions:
  - workspace
  - IDE
  - connection type

**Comment by mtojek** [comment]
I'm going with exposing agent metrics via Prometheus endpoint.

**Comment by mtojek** [comment]
Status update:

We have agent connection/latencies/session stats exposed via Prometheus. The next step would be collecting and exposing details related to agent timeouts.

**Comment by mtojek** [comment]
Plans for this week:

Implement a metrics collector in coderd to aggregate metrics from agents. Let's collect `magicsock` metrics first.

**Comment by mtojek** [comment]
Hey @mafredri! Did you identify any code places where we can inject extra metrics/counters to debug agent timeouts easier? I'm wondering if there are any gaps that could be addressed here.

**Comment by mafredri** [comment]
@mtojek not really. I still haven’t managed to isolate the problem and can’t really say what metric would help. Although, agent metrics is only one side of the coin, knowing what the client sees could help in such situations. Something I’m doing now is adding logging on the client side. But we probably shouldn’t be sending client metrics to the server, at least not normally.

**Comment by mtojek** [comment]
There is a significant problem with logging on the agent side. Admins have to ask users to copy, or at least review their logs for issues. We definitely need something centralized, ideally a sink for logs, but I wouldn't mind some extra metrics, even vague ones like `agent_vscode_network_timeout` or `agent_ssh_bad_peer_cerfiticate`.

**Comment by mtojek** [comment]
Battle plan:

- [ ] https://github.com/coder/coder/issues/7581
- [ ] Enable back sshMaxTimeout once https://github.com/coder/coder/issues/7581 is implemented.
- [ ] Add metrics to the SSH server wrapper, and possibly to https://github.com/coder/ssh.
- [ ] Add metrics to the ReconnectingPTY

**Comment by matifali** [comment]
Related #5318,

**Comment by mtojek** [comment]
I'm going to detach https://github.com/coder/coder/issues/7581 from the plan and keep it as a separate issue, hence resolving it.
