### ISSUE TITLE
Generic Coder health endpoint

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6728]
We're doing this internally for agents, but we need it also on the deployment level too.

Health section progress:
* [x] Access URL is valid https://github.com/coder/coder/pull/7193
* [x] DERP https://github.com/coder/coder/pull/6936
* [x] Websocket support https://github.com/coder/coder/pull/7689
* [x] Format the JSON response so that it's more human-readable until we have a proper frontend https://github.com/coder/coder/pull/7723
* [ ] ~HA/Replica issues~

**Comment by bpmct** [comment]
Some notes here from @kylecarbs and I:

- Do websockets work for access URL?
- Does DERP upgrade work, or is it over websockets (slightly degraded performance)
  - Read the response from the connection upgrade before EOF (kubesail had an "no app installed at this address")
