### ISSUE TITLE
Web terminal: Press any key to retry lies and reconnects in situations where you don't want it

### ISSUE THREAD

**Issue by mafredri** [coder/coder#6732]
If I log out (Ctrl+D, or `exit`), the web terminal will show the following screen:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/147409/226943940-570a5828-cbe5-47f6-aa87-a139b0a69760.png">

However, if I press "any key", nothing happens. I try `A-Z`, I try `,` `.`, `[Enter]` -> nothing happens. `[Space]` does seem to work.

Now, what's even more confusing is that it _does_ work for keys I expect it *not to*. Modifiers like `Command`, `Ctrl` or `Shift` trigger it, which is wrong. Imagine I log out, then I type `Cmd+W` to close the web terminal, and it logs me back in just before the window closes.

Browser: Safari.

**Comment by matifali** [comment]
Also, keyboard shortcuts to copy and paste do not work.

**Comment by mafredri** [comment]
> Also, keyboard shortcuts to copy and paste do not work.

Could you expand on this a bit? I'm not seeing any issue on macOS with either Safari or Brave. I can paste from OS clipboard (Cmd+V) and I can also select text with my trackpad and hit Cmd+C to copy to the OS clipboard.

**Comment by matifali** [comment]
I do not have a Mac, but on a Windows machine, it does not work on Brave.
