### ISSUE TITLE
rich parameters: can't migrate to the template with coder_parameters

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6734]
Hi,

<img width="1422" alt="Screenshot 2023-03-22 at 17 19 19" src="https://user-images.githubusercontent.com/14044910/226970405-5034f4ce-66b8-4db4-a866-d13f55604c49.png">

This popup has been introduced to allow users to pass their own values for new required parameters. Unfortunately, it doesn't play well with migration flow. The migration flow assumes that if there is no workspace build parameters, but there is a legacy variable property present, coder [backend will try](https://github.com/coder/coder/blob/main/coderd/workspacebuilds.go#L505-L516) to pull matching values from legacy parameters.

I guess that one of the options would be skipping rich parameters with extra property (`legacy_variable_name`)?

@bpmct @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
@mtojek what is the problem with the current flow?

**Comment by mtojek** [comment]
Status update:

I found a bug in the terraform-provider-coder and updated the backend side. Once [this](https://github.com/coder/coder/pull/6736) got merged, @BrunoQuaresma could you please adjust the frontend to obey the `legacy_variable_name`?
