### ISSUE TITLE
template editor: folder creation, deletion, and renaming

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6742]

**Comment by bpmct** [comment]
during QA:

I ran into this:
<img width="1056" alt="Screenshot 2023-04-04 at 2 48 50 PM" src="https://user-images.githubusercontent.com/22407953/229903893-5ed71a30-7f1a-458c-82a1-59b7b433f06a.png">

to reproduce, try renaming a nested folder

https://user-images.githubusercontent.com/22407953/229904682-c49b1abe-f739-45cb-b92d-5450887e426d.mov


It would also be nice to right click and add folder.

**Comment by BrunoQuaresma** [comment]
The mentioned issue was fixed!
