### ISSUE TITLE
Wireguard Tunnel Settings not working.

### ISSUE THREAD

**Issue by K4pt4n** [coder/coder#6744]
I have been working with @hh on validating / using the new wireguard tunnel process for tunnelling coder using the try.ii.nz server.
@deansheather this is probably for you.

Using the Linux_AMD64 Binary, after the tunnel host settings were renamed to --wg-tunnel-host / wgtunnel_host the flag no longer does anything. The environment variable "WGTUNNEL_HOST" was also tried with no effect.

if the devtunnel config file is edited to point to the desired host it works as desired.

There is an error `Error picking closest dev tunnel: socket: permission denied` prior to using the default location. Not sure this is related.

This is running inside WSL Ubuntu 22.04.

Windows AMD64 Binary on Windows 11 works as expected.

This is the case as of commit 25e92fd2f44d98656e0fe5cbe193dfc804622bf5 on branch main.

**Comment by matifali** [comment]
Any updates @K4pt4n ?

**Comment by bpmct** [comment]
@K4pt4n - I think we'll close for now. We can reopen if you're still running into this
