### ISSUE TITLE
Workspace Apps  - Community MVP

### ISSUE THREAD

**Issue by tjcran** [coder/coder#675]
This is a master epic for any of the work needed in the community milestone to support the desired DevURLs feature capabilities. 

DevURL Community Launch Requirements
- The Community launch should include a working Dev URLs feature that is configured via Templates. 
- An application/service that is running can be exposed via a DevURL and accessed using the link on the Workspace UI page, within the Resource card. 

-----

- [x] https://github.com/coder/coder/issues/259
- [x] https://github.com/coder/coder/issues/267
- [x] https://github.com/coder/coder/issues/805

**Comment by misskniss** [comment]
Closing this. All tasks closed.
