### ISSUE TITLE
`member` roles can see all users and all groups

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6753]
Version: [`v0.20.1+ed9a3b9`](https://github.com/coder/coder/commit/ed9a3b92519384a8f9acebc92d8ce5ae3d92c5f8)

This seems like a security violation - let a simple `member` role user to see all users and all roles.

![image](https://user-images.githubusercontent.com/2022166/227251638-24f90cd2-5f08-4f88-9474-bbc125cbf688.png)

**Comment by Emyrk** [comment]
This is a duplicate of https://github.com/coder/coder/issues/5002
