### ISSUE TITLE
remove `anchor` if role is `member`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6754]
Version: [`v0.20.1+ed9a3b9`](https://github.com/coder/coder/commit/ed9a3b92519384a8f9acebc92d8ce5ae3d92c5f8)

Re-adding to increase probability of action taken.

`member` role can see the template version which I guess is fine even though it's a strange name, but at least check the role and remove the anchor so the user does not experience the `404` if clicked.

Or just remove the version since the `member` shouldn't be in the sausage-making of templates and versions.

![image](https://user-images.githubusercontent.com/2022166/227258824-afcf6b33-19aa-4881-9c36-991f444c1997.png)
![image](https://user-images.githubusercontent.com/2022166/227258872-a1d0caa1-c399-4d0f-9e9f-1e35bb9b4b4e.png)

**Comment by matifali** [comment]
related to #5076
