### ISSUE TITLE
Workspaces are not stopping

### ISSUE THREAD

**Issue by jaulz** [coder/coder#6755]
It would be great to let Coder force stopping workspaces. The help says "We delay shutdown by this time whenever we detect activity." but how is this defined? Unfortunately, my workspace keeps accumulating memory because VS code does not detect old running processes.

**Comment by sharkymark** [comment]
@jaulz We recently added Max Workspace Auto-Stop.

Let us know if this helps.

https://coder.com/docs/v2/latest/templates#configure-max-workspace-auto-stop

**Comment by jaulz** [comment]
Thanks for your quick response! That sounds more like the total lifetime of the workspace? Actually, I just want that my workspace reboots once in a while (specifically according to the defined schedule). Currently, it's not rebooted for some reason and I assume it's because of long running processes (which I don't care about if they are stopped).

**Comment by coadler** [comment]
> The help says "We delay shutdown by this time whenever we detect activity." but how is this defined?

The only way we detect activity currently is by tracking Wireguard traffic through the agent. Things like SSH, code-server, web terminal, etc all go through the agent. It's possible you're leaving a connection open thats preventing the workspace from shutting down.

**Comment by coadler** [comment]
By enabling `CODER_VERBOSE=true`/`--verbose` on coderd you should be able to see why a workspace isn't being stopped. There's two log lines that can help:

1. `bumped deadline from activity`: shows when a workspace auto-off timer was bumped due to network activity
2. `read stats report`: shows when the agent sends wireguard traffic stats back to coderd, which can trigger the above

**Comment by jaulz** [comment]
Great, thanks for the information! I still think that it would be great to have a flag to force the schedule. I am using Code and map ports locally, so probably that's also causing some never-ending traffic if my machine wakes up once in a while at night. Or maybe I need to have a manual script in the workspace itself that somehow helps in this situation...
