### ISSUE TITLE
Force rebuild when workspace agent API breaks

### ISSUE THREAD

**Issue by ammario** [coder/coder#6767]
A simple solution to https://github.com/coder/coder/issues/6229 is keeping a version constant in the `agentsdk` package, incrementing it whenever there's a breaking change in the agent API, and then reporting an error in the frontend prompting the user to rebuild their workspace when the agent version mismatches.

**Comment by bpmct** [comment]
I thought the grey dot is when the agent is disconnected?

**Comment by ammario** [comment]
@bpmct — see new title

**Comment by ammario** [comment]
I keep getting bothered by this, most recently here: https://github.com/coder/coder/issues/8727.
