### ISSUE TITLE
Logout redirect to a different subdomain

### ISSUE THREAD

**Issue by NedkoHristov** [coder/coder#6769]
Logging out from `coder` redirects to `https://coder-logout.example.com/api/logout`. This is an issue for me, because I want to stay on the same subdomain.
Is there a way to configure it somewhere?

**Comment by matifali** [comment]
do you still have this on v0.23.0? I am unable to reproduce it.

**Comment by bpmct** [comment]
@NedkoHristov are you still running into this?

**Comment by NedkoHristov** [comment]
Just left the job where we were using coder. For the last time I checked the issue persisted.
