### ISSUE TITLE
Can coder make an external healthchecks?

### ISSUE THREAD

**Issue by NedkoHristov** [coder/coder#6770]
As far as I understand from running a coder_app both `external` and `healthcheck` are not compatible. But why? Can't I make a healthcheck for my resource that is accessed via URL?

```
resource "coder_app" "example {
  agent_id      = coder_agent.main.id
  slug          = "example"
  display_name  = "example
  external = true
  icon          = "https://example.com/icon.ico"
  url           = "https://${data.coder_workspace.me.name}-${data.coder_workspace.me.owner}.example.com"
  healthcheck {
    url       = "https://${data.coder_workspace.me.name}-${data.coder_workspace.me.owner}.example.com"
    interval  = 3
    threshold = 1
  }
}
```

Error code:
```
  Error: Conflicting configuration arguments
  on example.tf line 174, in resource "coder_app" "example":
    174:   external = true
  
  "external": conflicts with healthcheck
```

**Comment by bpmct** [comment]
In v1, we used to also support `exec` based health checks, which would return healthy if a command returned 1. Perhaps this would be better in this case than allowing Coder itself to ping external sites indefinitely. 

```hcl
resource "coder_app" "example {
  agent_id      = coder_agent.main.id
  slug          = "example"
  display_name  = "example
  external = true
  icon          = "https://example.com/icon.ico"
  url           = "https://${data.coder_workspace.me.name}-${data.coder_workspace.me.owner}.example.com"
  healthcheck {
    type      = exec # options: exec/http
    command   = "curl -IL --silent example.com | grep 200 OK"
    interval  = 3
    threshold = 1
  }
}
```

**Comment by NedkoHristov** [comment]
Thank you, @bpmct! Now, without nagging or something, but can you point me to the documentation of coder or it's terraform provider where I can see the option for `command`?
In the terraform provider [documentation](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app) the only information I could dig is to use URLs.

I believe it would be really awesome if you update the documentation for both your website and the TF provider to unleash all the awesome features that `coder` have.

**Comment by bpmct** [comment]
Ah, sorry for the confusion 🤦🏼 

We don't support `exec` health checks yet. That was intended to be a suggestion for our dev team so we could support it.

**Comment by NedkoHristov** [comment]
Thanks for the answer, @bpmct. I hope there will be an implementation soon.
Cheers.
