### ISSUE TITLE
subsequent cloning of dotfiles exits in error state

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#6773]
from a prospect:

> dotfiles cloning (via `coder dotfiles`) after the initial workspace build ends in failure because coder is trying to recreate symlinks that already exists, resulting in the workspace having an alert/error icon.  these kind of failures should be suppressed or ignored. it prevents other commands after that line from executing

```
Checking if dotfiles repository already exists...
Found dotfiles repository at /home/coder/.config/coderv2/dotfiles
Already up to date.
Symlinking /home/coder/.config/coderv2/dotfiles/.bash_aliases to /home/coder/.bash_aliases...
symlinking /home/coder/.config/coderv2/dotfiles/.bash_aliases to /home/coder/.bash_aliases: symlink /home/coder/.config/coderv2/dotfiles/.bash_aliases /home/coder/.bash_aliases: file exists
Run 'coder dotfiles --help' for usage.
```

**Comment by bpmct** [comment]
Hmm that is weird. We'll take a look

**Comment by mtojek** [comment]
I'm looking into this.

**Comment by mtojek** [comment]
Duplicate of https://github.com/coder/coder/issues/7427, which has been fixed some time ago.
