### ISSUE TITLE
Workspace proxies

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6785]
Workspace proxies will reduce latency for geo-distributed teams that connect via web IDEs (terminal, code-server, JupyterLab) or via SSH (in cases where NAT traversal fails and a [direct connection](https://coder.com/docs/v2/latest/networking#direct-connections) cannot be established).

```sh
# Before workspace proxies (high latency!)
User (Sydney, Australia) ---> coder server (us-west-2) ----> workspace (ap-southeast-2)

# After workspace proxies
User (Sydney, Australia) ---> workspace proxy (ap-southeast-2) ----> workspace (ap-southeast-2)
```

---

If you are only need low-latency SSH connections you may want to consider the following existing options:
- [Direct connections](https://coder.com/docs/v2/latest/networking#direct-connections) (this is on by default in Coder)
- Enable [Tailscale's global DERP relays](https://coder.com/docs/v2/latest/networking#relayed-connections)

**Comment by bpmct** [comment]
Docs have been released. The feature is still under alpha/experimental, so follow instructions to enable it for your deployment: https://coder.com/docs/v2/latest/admin/workspace-proxies

**Comment by Emyrk** [comment]
Closing, Proxies are GA :tada:
