### ISSUE TITLE
JetBrains Gateway Plugin

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6787]
Connect to Coder workspaces via a JetBrains Gateway plugin.

---

Note: Our plugin is currently in [the JetBrains marketplace](https://plugins.jetbrains.com/plugin/19620-coder), but is in an alpha state. You will likely run into bugs.

**Comment by matroscoe** [comment]
Been using the plugin for a while and it has been good so far! 

The only major issue (read major missing feature) is that when I select a new version of an IDE say PyCharm it will deploy fine but leave old versions of the IDE on the host which can take up a LOT of space (up to 4GB/install) it would be awesome to have a button to either upgrade the IDE version deployed or once I have deployed an updated version to have all links point to that and then provide an option to remove old instances of the IDE.

**Comment by code-asher** [comment]
Thank you for trying it out!  I definitely agree about the updating.  We call out to Gateway so that could end up getting resolved upstream (https://youtrack.jetbrains.com/issue/CWM-7510/Better-way-to-update-backend-IDE) but I bet we could do some cleanup on our own as long as the install paths are well-known.

**Comment by matroscoe** [comment]
They can all be found here `~/.cache/JetBrains/RemoteDev/dist/` according to the JetBrains our procedure internally has basically been to do a `ls -lrt` and delete anything that isn't the latest folder.

**Comment by matroscoe** [comment]
would it be possible to get a changelog published either to the coder GitHub or as a part of the plugin I am running into issues with the latest build `2.3.0` and I am having a hard time determining if they are related to me updating the plugin or something else.

**Comment by code-asher** [comment]
We should open-source the plugin repository since that will show the changelog but I also need to look into why the changelog is not showing up in the JetBrains marketplace or the plugin.

**Comment by code-asher** [comment]
I opened an issue for cleaning up IDEs on the plugin repository.  After doing some cleanup we will open that so folks can view and submit new issues.  For this issue I think we could consider the plugin ready and close it but we might want to leave it open until the integration with Coder is fully complete (the "Open in Gateway" button).

**Comment by matifali** [comment]
@bpmct, should we mark this as complete as the plugin is now out of beta.

**Comment by bpmct** [comment]
Yep! You can now try the plugin in the marketplace: https://plugins.jetbrains.com/plugin/19620-coder! We are working on a one-click from Coder into JetBrains! Will keep you posted!
