### ISSUE TITLE
envbox: add docs to DinD

### ISSUE THREAD

**Issue by sreya** [coder/coder#6789]
Add envbox documentation to [Docker in Docker docs](https://coder.com/docs/v2/latest/templates/docker-in-docker)

**Comment by MWY3510** [comment]
Out of curiosity is this feature available for testing? I understand if it is not but I figure I would ask. Thank you.

**Comment by sreya** [comment]
Hey @MWY3510 envbox should be good to check out now. Let me know if you have any questions or run into any issues!
