### ISSUE TITLE
Unable to disable P2P connections as it is not possible to set DERP server stun addresses to empty

### ISSUE THREAD

**Issue by JoshVee** [coder/coder#6791]
The docs indicate that you can disable P2P connections by setting `--derp-server-stun-addresses` \ `CODER_DERP_SERVER_STUN_ADDRESSES` to empty. This does not work.

```
      --derp-server-stun-addresses string-array, $CODER_DERP_SERVER_STUN_ADDRESSES (default: stun.l.google.com:19302)
          Addresses for STUN servers to establish P2P connections. Set empty to disable P2P connections.
```

There does not appear to be any way to set this configuration property to empty:
- Setting the `CODER_DERP_SERVER_STUN_ADDRESSES` environment variable to empty results in the default value of `stun.l.google.com:19302` being used
- Setting the argument `--derp-server-stun-addresses=""` results in a parsing error: `invalid argument "" for "--derp-server-stun-addresses" flag: EOF`

Also, there appears to be a bug with parsing `string-array` environment variables. The value is appended to the default, rather than replaced. For example, `CODER_DERP_SERVER_STUN_ADDRESSES="foobar:443"` results in the following STUN addresses: `[stun.l.google.com:19302, foobar:443]`

**Comment by JoshVee** [comment]
Possible fix in https://github.com/coder/coder/pull/6792

**Comment by ammario** [comment]
While #6832 would set you defaults values, it didn't let you set new values  🤦🏽‍♂️

https://github.com/coder/coder/pull/6873 should _truly_ fix this.

**Comment by bpmct** [comment]
You can disable STUN with a flag right now with `coder server --derp-server-stun-addresses`, but there is no way to disable it with an environment variable (for Kubernetes or Docker users). We'll keep this issue open until we get a fix in for that.

**Comment by ammario** [comment]
From discussing with @bpmct, we're going to add a special `none` value that may be set via the environment and removes all previous values.

**Comment by sharkymark** [comment]
Still does not disable STUN in `0.23.0` with the `disable` special value.

**Comment by bpmct** [comment]
<details><summary>Here is a video that reproduces what Mark says</summary>

https://user-images.githubusercontent.com/22407953/234447761-8f020a26-7d20-46b3-991a-0aeceef7b43f.mov

</details>


Despite the thing being `null` in `/api/v2/deployment/config` now, I am still able to establish a direct connection via `coder ping`.

**Comment by ammario** [comment]
This doesn't appear to be an issue with my change, and I've been trying to debug it for an hour with little progress. Requesting @kylecarbs to help since I'm unfamiliar with the networking code.

**Comment by kylecarbs** [comment]
Seems like we should just add a separate flag to disable direct connections. Disabling them via disabling STUN is round-about and likely to cause issues longer-term anyways.
