### ISSUE TITLE
Broken links in the Coder v2 docs

### ISSUE THREAD

**Issue by alexander-dammeier** [coder/coder#6793]
Hello,

in the docs are a lot of broken links to external and even coders own pages. Because of this, there is a lot of helpful information missing, especially for offline deployments and the usage of rootless podman, which we are both currently setting up.

This is what i found:

- [most of the links in the table for offline deployments](https://github.com/coder/coder/blob/6c0f37c28e5aed468ff4e86da533f898175307c6/docs/install/offline.md)
- [rootless podman point 4 - link to your own template is broken](https://github.com/coder/coder/blob/6c0f37c28e5aed468ff4e86da533f898175307c6/docs/templates/docker-in-docker.md)
- [Link to set a shorter max token lifetime](https://github.com/coder/coder/blob/6c0f37c28e5aed468ff4e86da533f898175307c6/docs/templates/change-management.md)

I hope this helps!

**Comment by matifali** [comment]
Thanks for reporting. We will fix soon.
