### ISSUE TITLE
envbox: report envbox usage via telemetry

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6802]
Would love to know if OSS users use envbox. We can report this via the workspace agent

**Comment by bpmct** [comment]
@kylecarbs may be able to help with this. We was thinking this could in `workspace_agents`

**Comment by bpmct** [comment]
@kylecarbs @sreya - Curious for your thoughts. Should we do this now, or just remove from the milestone right now?

**Comment by sreya** [comment]
I'll do it this week, it'll be good to have. Especially since people are using envbox already.
