### ISSUE TITLE
Template name doesn't appear on the template page

### ISSUE THREAD

**Issue by ElliotG** [coder/coder#6810]
While working on the metrics/dashboarding tooling, I've had several cases where I was trying to go from "template name" --> the template in the UI. However, the template name is almost never visualized. I'll include some screens below.

The actual scenario was that I was trying to look into a workspace launch failure from a template called "kubernetes-2". Our internal stack has 10 different templates that have kubernetes in the description, so which one is kubernetes 2? I just kept opening them up randomly till I found the one i wanted.

**Comment by ElliotG** [comment]
![Screenshot 2023-03-27 at 9 20 03 AM](https://user-images.githubusercontent.com/2059212/227985852-420be0a2-9921-4abb-a4f1-13ed1fe10693.png)

It's not on the workspace overview.

**Comment by ElliotG** [comment]
![Screenshot 2023-03-27 at 9 20 37 AM](https://user-images.githubusercontent.com/2059212/227986016-5f7672a6-1236-4382-b619-4d8b32a3a0df.png)

It's not the workspace details page.

**Comment by ElliotG** [comment]
![Screenshot 2023-03-27 at 9 21 02 AM](https://user-images.githubusercontent.com/2059212/227986125-d07306d6-2b72-425c-a4b2-f1cf0d1f93ef.png)

It's not on the templates overview page.

**Comment by ElliotG** [comment]
![Screenshot 2023-03-27 at 9 21 31 AM](https://user-images.githubusercontent.com/2059212/227986274-3ed41fee-26cf-442a-a7a0-128090e4882f.png)

And worst of all: it's not on the template page either.

**Comment by kylecarbs** [comment]
Good point. The slug being different from the name is really weird.
