### ISSUE TITLE
Non-Terraform workloads

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6816]
In some cases, a user may want to write their own provisioner to provision things outside of Terraform or use Pulumi (#4528) to provision infrastructure. 

- Use bespoke internal API for provisioning VMs
- Provision a secret on bespoke infrastructure that has no Terraform providers
- Write complex logic and conditionals around provisioning based on user identity or resource availability 

---

> **Note**: This is something we are still considering for our roadmap, feedback is welcome. Feel free to leave a comment in this issue or [contact us](https://coder.com/contact)

**Comment by matifali** [comment]
Reopening as this in on our long-term roadmap.
