### ISSUE TITLE
support reverse port forwarding with `coder port-forward`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6818]
For use cases such as ADB forwarding for remote development, a user may wish to reverse-forward a port from their local machine to the workspace. SSH supports this with `ssh -R`. I couldn't find an option to do this with `coder port-forward`, as it complains a port is already running on my local machine.

As a workaround, folks can use `ssh -R` for reverse port-forwarding. To have Coder workspaces in your local SSH hosts, run `coder config-ssh`

**Comment by Emyrk** [comment]
Unassigning myself until I get more bandwidth

**Comment by mtojek** [comment]
I'm going with this feature.
