### ISSUE TITLE
prevent web terminal entry when `login_before_ready = false`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6819]
[login_before_ready](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#login_before_ready) prevents users from connecting via SSH when the startup script is still running, but does not apply to the web terminal. We should also disable web terminal entry until this has been completed, at least via the UI.

Perhaps the button could be greyed out. When hovering, we could display a message like

> Waiting for the startup_script to complete.

**Comment by mafredri** [comment]
I think allowing the web terminal to be opened would be ideal. The user experience could then be that you see a loading indicator along with a button to "login anyway".

**Comment by bpmct** [comment]
Either works for me!

**Comment by BrunoQuaresma** [comment]
@bpmct the direction is not clear to me. What is the "definition of done" for this task?

**Comment by bpmct** [comment]
When the startup script is still running, or unhealthy, I think we should

- Grey out the "web terminal" and "SSH" buttons
- On hover, the SSH sends instructions on how to "enter anyways" (`coder ssh --no-wait`)
- On hover, the web terminal button has a link to "enter anyways"

Nice to have / sprinkles:

- When directly visiting the web terminal URL, it streams the startup logs with some button to enter anyways (perhaps a URL parameter)

**Comment by BrunoQuaresma** [comment]
Right now, this flow is kinda "hard" to make and maybe we can simplify a bit.

Why it is hard:
- Disabled elements don't trigger events, so adding a popover on it could be "sketchy"
- When the button is loading, it is disabled

Alternative:
- We can let users click on it but show a popover or a modal with text like "The agent is not ready yet but you can do X or Y to access it anyways". This flow is kinda similar to what you proposed but they would be visually enabled. Thoughts?

**Comment by bpmct** [comment]
(chatting with Bruno on Slack about this)

**Comment by bpmct** [comment]
This works great!
