### ISSUE TITLE
add agent metadata to example templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6829]
At a minimum, we should add agent metadata to these example templates to show the following values:

- kubernetes: CPU, memory, disk usage (from `/home/coder` PVC)
  - We should also compare this to the metrics the Kubernetes metrics server provides. If there is a large discrepancy, we should understand and document why.
- docker: CPU, memory usage
- aws-linux: CPU, memory, disk usage

**Comment by matifali** [comment]
I am going with this

**Comment by matifali** [comment]
Should we close this as completed, as #6938 is not being done anymore? @bpmct
