### ISSUE TITLE
Max Token Lifetime is not human friendly 

### ISSUE THREAD

**Issue by matifali** [coder/coder#6834]
![image](https://user-images.githubusercontent.com/10648092/228187488-c4ffafa8-5b36-4512-8408-385beb609eb8.png)

cc: @Kira-Pilot

**Comment by Emyrk** [comment]
Is it in the `deployment/network` page :: `/settings/deployment/network`

**Comment by matifali** [comment]
This is `CODER_URL/settings/deployment/network` page.

**Comment by Emyrk** [comment]
Fix on the way
