### ISSUE TITLE
feat: Add tool tips to show which flag / `ENV` to set for each of these options

### ISSUE THREAD

**Issue by matifali** [coder/coder#6835]
![image](https://user-images.githubusercontent.com/10648092/228188342-0fad076c-38ec-4f7c-be27-e0914ff4be55.png)

Display a tooltip with the flag/environment variable information on each name. Can also hyperlink to docs (or offline docs for air-gapped environments)
cc: @BrunoQuaresma

**Comment by bpmct** [comment]
I like this idea, seems like a good enhancement.
