### ISSUE TITLE
CONTRIBUTING guide for backend devs

### ISSUE THREAD

**Issue by mtojek** [coder/coder#6837]
_The task is the outcome of the latest Coconut retrospective meeting._

Frontend has a dedicated [guide](https://coder.com/docs/v2/latest/contributing/frontend), and it would be great to have a corresponding one for the backend. It will simplify the onboarding of new people and make the ramp-up easier to community members.

- [ ] how to add a new endpoint
- [ ] how to add a new SQL query
   - Add a function into DB Fake query
   - Add the params in the Audit
- [ ] how to configure RBAC rules
- [ ] how to test all the things
   - run a single test
   - debug tests 
- [ ] plumbing between coder server and Terraform

**Comment by matifali** [comment]
Hi, @mtojek is it still planned?
