### ISSUE TITLE
example templates: devcontainers

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6843]
- [ ] AWS VM
- [x] Docker
- [x] Kubernetes

Template should support generic projects (go, java, typescript, ruby) or opening a repo

**Comment by matifali** [comment]
@bpmct de we need AWS VM template?

**Comment by bpmct** [comment]
I think we can close this for now, down the road we should have VM container templates for each cloud :)

**Comment by matifali** [comment]
Yes, they would be a good fit for a template registry instead of crowding our example docs directory.
