### ISSUE TITLE
cannot pre-fill template parameter values with param name

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6852]
This link is not pre-filling parameter values anymore: https://dev.coder.com/templates/kubernetes-open-in-coder/workspace?param.git_repo=https://github.com/coder/coder

I'm trying to use the feature introduced in #5758

**Comment by bpmct** [comment]
I'm trying to do docs for Open in Coder, but this is blocked by that.

**Comment by BrunoQuaresma** [comment]
I was taking a look and it may require some thinking to fix that.

TL;DR: In the past, the parameters name were the data key. So we could know the data key github_repo would be the same as the parameter with the name “github_repo” but after rich parameters, the name can be “Github repository” and with that, we missed a way to “bind” these values from the URL. A solution that I can see is to save the data key in the “rich parameter” row, in the database, but idk what we would have to do to make it work for existent deployments.

**Comment by bpmct** [comment]
Ah I see, so this currently works, but is case sensitive: https://dev.coder.com/templates/kubernetes-open-in-coder/workspace?param.Git%20repository=https://github.com/coder/coder

**Comment by BrunoQuaresma** [comment]
@bpmct Yes! So do you think this is a bug or feature? 😆

**Comment by bpmct** [comment]
> A solution that I can see is to save the data key in the “rich parameter” row, in the database, but idk what we would have to do to make it work for existent deployments.

Let's consider it an enhancement. I do think we should do this, and it'd OK if this only works for new template versions

**Comment by mtojek** [comment]
Thanks for raising this issue! I see that you've figured it out, but anyway here is the [correct link](https://dev.coder.com/templates/kubernetes-open-in-coder/workspace?param.Image=https://github.com/coder/coder).

> A solution that I can see is to save the data key in the “rich parameter” row, in the database, but idk what we would have to do to make it work for existent deployments.

Let's consider this case: `Git repository`

The `data-key` would be `git_repository`. I wouldn't like to add another column just because of that. These values are pretty similar. I'd rather introduce an extra logic on frontend that can map `git_repository` -> `Git repository`.

Let me know your thoughts, @bpmct @BrunoQuaresma!

**Comment by BrunoQuaresma** [comment]
@mtojek I would rather not transform "Git repository" into "git_repository" because the key is not associated with the name field so "git_repo", the key, would not bind to "git_repository". 

My problem with using the name for it is the name is something that can change over time so the user would have to change it in other places too. But, if this is not a such problem, we can just keep using the name as @bpmct did and see if users will have problems with that because they maybe don't change the name too much?! 🤔 

I'm ok with keeping using the name or adding an extra column for the "key" field. I'm against transforming strings that are not enforced related in the BE since this is kinda "fragile".

**Comment by mtojek** [comment]
> @mtojek I would rather not transform "Git repository" into "git_repository" because the key is not associated with the name field so "git_repo", the key, would not bind to "git_repository".

I might be missing something, but where is the `git_repo` key defined? Could you please link to the codebase? I assumed that with `?param.foobar=foobaz` I can change **any** parameter name.

> My problem with using the name for it is the name is something that can change over time so the user would have to change it in other places too. 

If we add an extra DB column for `data-key`, it will be the same problem, it may get outdated easily.

> or adding an extra column for the "key" field.

Yeah, this is something I wouldn't like to do, as it seems to be redundant :)

**Comment by BrunoQuaresma** [comment]
> I might be missing something, but where is the git_repo key defined? Could you please link to the codebase? I assumed that with ?param.foobar=foobaz I can change any parameter name.

The user can define any key they want to the param:
```
data "coder_parameter" "git_repo" {
  name        = "GitHub Repository"
  description = "GitHub repository SSH"
  mutable     = true
}
```

The `key` does not need to match the name.

> If we add an extra DB column for data-key, it will be the same problem, it may get outdated easily.

I don't know if the key, "git_repo", is changeable... if the key changes, I guess the BE and TF would understand that as a new field and not as an "update" but I can be wrong.

**Comment by bpmct** [comment]
Assuming this example:

```sh
data "coder_parameter" "git_repo" {
  name        = "GitHub Repository"
  description = "GitHub repository SSH"
  mutable     = true
}
```

As a user, I assumed `name` referred to the friendly name of the parameter and `git_repo` was the machine-readable name that is stored in the database. After all, within Terraform, when I reference a parameter, I do so with the machine-readable name in Terraform:

```hcl
resource "my_other_thing"
  startup_script=<<EOF
  git clone ${coder_parameter.git_repo.value}
  EOF
```

It also feels a bit clunky to reference a friendly name in the URL string, especially if it has spaces and capital letters.

```sh
https://dev.coder.com/templates/kubernetes-open-in-coder/workspace?param.Git%20repository=https://github.com/coder/coder
```

I'd also expect that if I change the friendly name of a template (e.g. `CPU` -> `CPU Cores`) that the same underlying parameter is being referenced. I see not that this is not the case, which feels a bit like an anti-pattern. It could also lead to some unexpected behaviors when an admin just wants to change the verbiage.

Many other objects within Coder (e.g. templates, coder_app) have this separation of concerns, so I think we should do the same for templates (either by parsing `data coder_parameter "git_repo" {` or by adding some display name/slug paradigm.

**Comment by bpmct** [comment]
Talked to Kyle and he said they do `key` for metadata so it might make sense to add it here.

**Comment by mtojek** [comment]
Ok, let's sum up:

1. Add a new property to `coder_parameter` in `terraform-provider-coder`.
2. The property must be required as every parameter can be linked.
3. The property will be exposed through the coder API for frontend purposes.

I'm concerned about 2. as in most cases, it will be artificial. Should we make it mandatory or try to generate it from `name`?

**Comment by bpmct** [comment]
Yep. To summarize:

```hcl
data "coder_parameter" "git_repo" {
  name = "git_repo" # required
  display_name = "Git repository" # optional
}
```

**Comment by mtojek** [comment]
Actually, the comment above is slightly outdated. This is the final version:

> We decided to do name and display_name (optional).
> * less refactoring
> * this is a different object than both metadata (uses key) and app (uses slug). templates also use name and display name so    we don’t exactly have a “pattern” here
> * shouldn’t break users since display name is optional

**Comment by mtojek** [comment]
I'm going with this issue.

**Comment by matifali** [comment]
> Yep. To summarize:
> 
> If display_name is not set, let's take it from the name:
> 
> ```terraform
> data "coder_parameter" "git_repo" {
>   key = "git_repo" # required
>   display_name = "Git repository" # optional
> }
> ```

## My thoughts:
Why can't we use `data.coder_parameter.git_repo` and we need something new with the same value as the last part of data?
e.g.

name = `git_repo` is same as `*data*.*.git_repo`
