### ISSUE TITLE
[experiments] Cannot publish new version using web UI

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#6857]
Version: [v0.21.1+b38d1ed](https://github.com/coder/coder/commit/b38d1ed4a5ee83089b63b8b0108f2514219f1360) with ``CODER_EXPERIMENTS=*``
Template: [uwu/basic-env](https://github.com/uwu/basic-env)

---

![image](https://user-images.githubusercontent.com/57866459/228360680-6ede54b9-0696-4203-81d1-955c1520f2f9.png)

---

The server responds with a 400 response code and the following data :
```json
{"message":"Validation failed.","validations":[{"field":"name","detail":"Validation failed for tag \"template_version_name\" with value: \"heuristic_cray2\""}]}
```

**Comment by BrunoQuaresma** [comment]
Type a new name and it should work. I'm fixing this right away!

**Comment by phorcys420** [comment]
I did try that yesterday and it didn't work. Will retry today.

**Comment by BrunoQuaresma** [comment]
@mtojek maybe the validation of the name is too strict? I think we would like to allow underscores 🤔

**Comment by BrunoQuaresma** [comment]
@phorcys420 I will post the PR here when it is ready for review 👍 thanks for letting us know about the issue.

**Comment by mtojek** [comment]
> @mtojek maybe the validation of the name is too strict? I think we would like to allow underscores 🤔

This is a [general validator](https://github.com/coder/coder/blob/main/coderd/httpapi/httpapi.go#L47) for all names in the coder product. I wouldn't do excuses in this case unless it's a big usability problem.

**Comment by BrunoQuaresma** [comment]
@mtojek it is because the actual version name generator is generating names that are not validated in this way so we may change how random names are being generated to match the "general validator" or we make the version name accepts a diff validator specific for the version name. Having in mind versions could be named `v1.0.0` as an example - not sure if the general validator allows dots.

**Comment by bpmct** [comment]
I'm in favor of more permissive version names, kind of like display names. Or perhaps how Docker validates image tags?

**Comment by BrunoQuaresma** [comment]
@mtojek another thing that I notice. Let's say you have a version "my-version-1" and send a PATCH to it using the same name, it will get a unique error. I will fix that in the FE as well, not send a patch if nothing is changed, but maybe we should fix it on BE as well. If the name is not changed, just return 200 but it is up to you.
