### ISSUE TITLE
Coder as a railway app

### ISSUE THREAD

**Issue by matifali** [coder/coder#6861]
Deploy Coder to railway.app

- [x] Deploy a test environment
- [x] Use their managed PostgresDB service
- [x] ~~Create a docker-remote template to provision workspaces on the remote host.~~
	> This will be done independently from this issue. Check #6921
- [x] Use Fly.io template to test the workspace
	- [x] Web Terminal
	- [x] VS Code Desktop
	- [x] SSH
	- [x] Port Forwarding
	- [x] Wildcard subdomain 
- [x] Publish template source code at https://github.com/coder/packages
- [x] Publish as a template on https://railway.app/templates
	- https://railway.app/template/cUQ8_P?referralCode=tfH8Uw [![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/cUQ8_P?referralCode=tfH8Uw)
- [x] Add Deploy to Railway button to https://github.com/coder/packages
- [x] Write a blog post on https://github.com/coder/blogs https://github.com/coder/blogs/pull/11

**Comment by matifali** [comment]
cc: @bpmct

**Comment by matifali** [comment]
Update, I am trying to set up a remote Docker host with TCP without TLS, but somehow Railway deployed Coder can not access that.

**Comment by matifali** [comment]
![image](https://user-images.githubusercontent.com/10648092/229269381-63be1ba0-e9bd-4081-93bf-58804ea4bcba.png)
Published

**Comment by matifali** [comment]
https://railway.app/template/cUQ8_P?referralCode=tfH8Uw

**Comment by bpmct** [comment]
@matifali I don't think this railway example uses Railway's database. When I redeploy, I have to set up my user again and the database appears empty.

This is because we need to set this variable too:
![Screenshot 2023-04-03 at 12 45 40 PM](https://user-images.githubusercontent.com/22407953/229587068-80329843-0581-4135-8cb7-fe86008ce42b.png)

**Comment by matifali** [comment]
> @matifali I don't think this railway example uses Railway's database. When I redeploy, I have to set up my user again and the database appears empty.
> 
> This is because we need to set this variable too: ![Screenshot 2023-04-03 at 12 45 40 PM](https://user-images.githubusercontent.com/22407953/229587068-80329843-0581-4135-8cb7-fe86008ce42b.png)

Can you try this during our 1-1 tomorrow? I did not get why it would not use the Railway database.
