### ISSUE TITLE
front end does not wire in CODER_SSH_HOSTNAME_PREFIX

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#6881]
Using latest release.

With `CODER_SSH_HOSTNAME_PREFIX="ghuntley-dev."`

The UI is hard coded to `coder.`

<img width="704" alt="CleanShot 2023-03-31 at 00 22 52@2x" src="https://user-images.githubusercontent.com/127353/228850109-22ddc725-299c-4b02-89f1-37b1a5c7e5ec.png">

Whereas the ~/.ssh/config via `coder config-ssh` uses `ghuntley-dev.`

**Comment by Emyrk** [comment]
will fix! Good catch
