### ISSUE TITLE
Consider setting TF_LOG=debug automatically if CODER_VERBOSE=true

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#6889]
I needed to debug my workspace template. Through reading [this source code](https://github.com/coder/coder/blob/6c0f37c28e5aed468ff4e86da533f898175307c6/provisioner/terraform/provision.go#L246) I saw that `TF_LOG` is passed through. Thus reset my container to have environment of `TF_LOG=debug` and was able to troubleshoot.

What if `CODER_VERBOSE=true` would set `TF_LOG=debug` on the provisioner thus making troubleshooting instructions easier?

**Comment by BrunoQuaresma** [comment]
cc. @mtojek
