### ISSUE TITLE
how to use remote Docker host

### ISSUE THREAD

**Issue by matifali** [coder/coder#6921]
Create a new remote docker template similar to [docker-image-builds](https://github.com/coder/coder/tree/main/examples/templates/docker-image-builds)
1. Remote docker host should be specified as `ssh://user@host`
2. Key to access the host should be already available on the deployment in `~/.ssh/KEY`
3. For services like fly.io, railway.app, render.com, where putting the key inside the Dockerfile is not a good solution. The private key can be created as a secret or secured environment variable.
4. We can also create a managed sensitive terraform variable to store the key, which is not secure as values are stored unencrypted in the database. Thanks, @deansheather 
5. Check for the value of the Secret/Environment variable and create `~/.ssh/KEY` file with the correct permissions on the Coder host to be able to access the remote docker host using terraform [`local-exec`](https://developer.hashicorp.com/terraform/language/resources/provisioners/local-exec)

**Comment by bpmct** [comment]
Perhaps we could add a variable for the Docker socket location in our Docker template, which by default is the UNIX location?

**Comment by matifali** [comment]
Yes but should we assume that the user already has the ssh key on their coder host? 
Or they can only connect using the unsecured tcp.

**Comment by bpmct** [comment]
@matifali for now, let's add a doc under "platforms"

https://coder.com/docs/v2/latest/platforms/docker
