### ISSUE TITLE
rich parameters: not prompting me for missing variables

### ISSUE THREAD

**Issue by bpmct** [coder/coder#6941]
I introduced a new template version that includes a new parameter and I'm not seeing the pop-up prompt to enter the missing parameter when I update my workspace.

https://user-images.githubusercontent.com/22407953/229251628-8890f7c9-64e7-426a-8982-db29a8fec11d.mov

**Comment by BrunoQuaresma** [comment]
@bpmct can you please share with me the parameter config you used in the TF?

**Comment by bpmct** [comment]
This was the parameter I added to [this template](https://dev.coder.com/templates/devcontainer).

```hcl
data "coder_parameter" "repo_url" {
  name = "repo_url"
  display_name = "Git Repo URL"
  type = "string"
  description = "See [sample projects](https://github.com/microsoft/vscode-dev-containers#sample-projects)"
}
```

I was able to reproduce it by adding another one similar.

https://user-images.githubusercontent.com/22407953/229513678-4ceda474-a90b-426d-8e80-46f5e017bb5c.mov

**Comment by BrunoQuaresma** [comment]
@mtojek I think we will need to update the BE to accept immutable parameters when it has not been set previously. When I change the FE to allow "first immutable parameter values" I get this error from the BE.
<img width="1792" alt="Screen Shot 2023-04-03 at 10 27 28" src="https://user-images.githubusercontent.com/3165839/229524549-f5dafd63-3305-4e01-a131-cad65b4fbcbd.png">

**Comment by mtojek** [comment]
@bpmct I guess that it works well with `mutable = true`. I will work on this issue, but if you need a patch, please enable parameter mutability.

**Comment by mtojek** [comment]
I'm going with this issue.
