### ISSUE TITLE
Simultaneous multiple coder server workspace access results in dropout 

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#6960]
We separate our coder servers for compliance reasons.

We have team leaders that need to bounce between these servers and use workspaces across both. They find that trying to access both at the same time results in one of them dropping out.

Is this related to auth tokens / sessions being overwritten? Is there a workaround for this that we can give them so they can have both up at once?

Access to their workspaces is mostly via the Visual Studio Code desktop plugin.

**Comment by bpmct** [comment]
Right now, the VS Code extension only allows you to connect to one coder server at a time, despite having multiple windows open. We'd like to add support for different contexts (on the CLI and extension) to make this possible. This is a use case that we've heard of before.
