### ISSUE TITLE
VS Code Desktop Bug

### ISSUE THREAD

**Issue by FaresHerhar** [coder/coder#6967]
> Environment

Coder: v0.20.0
Code-Server: v4.9.1

> Issue

I just upgraded Coder the the v0.20.0 version, and since, we're unable to connect to the workspace via VS Code, it starts a new window, but it is stuck, with the following logs.

```
.
.
.
2023/04/03 11:50:17 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:17 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:17 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:17 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:18 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:18 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:18 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:18 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:19 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:19 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:19 websocket: connected to https://CODER_URL/derp
2023/04/03 11:50:19 websocket: connected to https://CODER_URL/derp
.
.
.
```

**Comment by MrPeacockNLB** [comment]
please try first updating to latest release as there were some issues fixed regarding DERP

**Comment by FaresHerhar** [comment]
Issue Fixed.
Sorry for the trouble. Both my colleague and I, had an issue VS Code cache.
For the solution, we deleted all the VS Code Cache files, the extensions, deleted VS Code, and reinstall it again !

Thanks.
