### ISSUE TITLE
Hide `startup_script` logs by default

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6969]
Version: [`v0.21.2+872037b`](https://github.com/coder/coder/commit/872037bf85edde1300e1cca5fc78523d693ae549)

Showing the `startup_script` log is helpful - IF you need it, but noisy and ugly to see on every build.

Either hide by default, or make a site-wide configuration.

**Comment by matifali** [comment]
Should I close this in favor of #6997?

**Comment by bpmct** [comment]
We don't plan on doing this.
