### ISSUE TITLE
embedded DERP shows higher latency in workspace latency UI when Tailscale DERPs enabled

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6974]
Version: [`v0.21.2+872037b`](https://github.com/coder/coder/commit/872037bf85edde1300e1cca5fc78523d693ae549)

I enabled Tailscale's network of DERP relays with the environment variable, [per the docs ](https://coder.com/docs/v2/latest/networking#relayed-connections)

`--derp-config-url https://controlplane.tailscale.com/derpmap/default`

But the embedded DERP relay still shows up, but with a really high latency, which makes no sense.

Expected behavior is the embedded DERP is gone from action, by design.

**Comment by kylecarbs** [comment]
The embedded DERP is an entirely separate option, which is intentional.

![image](https://user-images.githubusercontent.com/7122116/229550938-c8c1740d-7cce-4462-b303-4598093893e4.png)

**Comment by sharkymark** [comment]
Ok, thanks. But without the public DERPs, embedded DERP is 1ms. So any clue on that one? @kylecarbs

**Comment by sharkymark** [comment]
![image](https://user-images.githubusercontent.com/2022166/229551189-91524107-3b4b-4a8f-97cb-0e6f13664b43.png)

**Comment by bpmct** [comment]
I see a similar behavior. Changing the issue title to reflect this. I agree it is worth investigating

**Comment by spikecurtis** [comment]
we're adding a new flag for tailscale DERP, which should NOT start or include an embedded relay #9816
