### ISSUE TITLE
Error starting new Workspace

### ISSUE THREAD

**Issue by cloudxu** [coder/coder#6976]
Environment: Ubuntu Docker
First time creating a new workspace in local environment. getting: 

Initializing the backend...
Initializing provider plugins...
- Reusing previous version of kreuzwerker/docker from the dependency lock file
- Reusing previous version of coder/coder from the dependency lock file
- Using previously-installed kreuzwerker/docker v3.0.2
- Using previously-installed coder/coder v0.6.23
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Terraform 1.3.4
coder_agent.main: Plan to create
docker_volume.home_volume: Plan to create
docker_image.main: Plan to create
coder_app.code-server: Plan to create
docker_container.workspace[0]: Plan to create
coder_agent.main: Creating...
coder_agent.main: Creation complete after 0s [id=c89750d9-2ff0-42fe-ae86-9a8bc3ad690d]
coder_app.code-server: Creating...
docker_volume.home_volume: Creating...
coder_app.code-server: Creation complete after 0s [id=a6b689f7-bd5d-46ac-ad7f-0cc3e2f2d499]
docker_image.main: Creating...
docker_volume.home_volume: Creation complete after 0s [id=coder-6959c733-25b7-433e-b84e-d30332ea90c1-home]
docker_image.main: Creation errored after 1s
Error: failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests latest]: 403 Forbidden

on main.tf line 95, in resource "docker_image" "main":
  95: resource "docker_image" "main" {

**Comment by kylecarbs** [comment]
Seems like you aren't authenticated to your Docker registry!
