### ISSUE TITLE
How can you know if a JetBrains Gateway connection is `Direct` or through a DERP relay proxy?

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#6987]
Version: [`v0.21.2+872037b`](https://github.com/coder/coder/commit/872037bf85edde1300e1cca5fc78523d693ae549)

In the Gateway UI, there is a `Backend latency` textbox.

I have a local VS Code with `Direct` point-to-point connectivity with the same workspace and the latency is ~ `35ms` so with the Gateway latency saying `48 ms` I am thinking it maybe is not a point-to-point, or maybe not.

![image](https://user-images.githubusercontent.com/2022166/229605885-2d9ae07a-ca19-4773-9861-8218fc7eb511.png)

**Comment by kylecarbs** [comment]
@code-asher is there any way to override this text? I'm assuming not, but maybe I'm wrong.

**Comment by code-asher** [comment]
I believe that is in the JetBrains client so no way as far as I 
can tell. :(

**Comment by sharkymark** [comment]
@code-asher @kylecarbs we control the plugin, and sense we can interact with STUN and the coordinator in coderd and show expected direct latency in the plugin ui?

**Comment by code-asher** [comment]
Yup we could show it in Gateway since we control the plugin there.
