### ISSUE TITLE
Double-confirm workspace Update from the UI

### ISSUE THREAD

**Issue by ammario** [coder/coder#6989]
Idea from @matifali 

His users have long running job and have lost days of training progress by accidently clicking the Update button. We should confirm that users really mean to update and understand the consequences when they press the update button.

cc @rodrimaia — maybe an easy one for you to pick up.

**Comment by BrunoQuaresma** [comment]
@bpmct what could be a good copy for this one?

> Are you sure you want to update your workspace? By updating your workspace we need to stop and start your workspace.

**Comment by matifali** [comment]
Add "It will stop all running processes and will delete all non-persistent data."

**Comment by bpmct** [comment]
Let's do this

> Update workspace
> Updating will restart your workspace, removing any non-persistent data.

Folks are pretty familiar with "restart" so I don't think it's necessary to call out that it will stop processes.
