### ISSUE TITLE
Hoovering over agent metadata yields in jittering whole workspace site

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#7013]
# Description

If one hoovers over agent metadata or info bubble then the scrollbar gets hidden and make the whole site jittering.

![image](https://user-images.githubusercontent.com/103434584/230112315-02fcf3bf-bd4d-4395-a510-e9a4ad1c7591.png)

![image](https://user-images.githubusercontent.com/103434584/230113138-a52487b9-18ca-49ee-be98-e58ed039ef9d.png)

**Comment by kylecarbs** [comment]
Ahh, weird. We'll fix this! Thanks for the report.

**Comment by bpmct** [comment]
We've removed agent metadata hover!
