### ISSUE TITLE
`CODER_REDIRECT_TO_ACCESS_URL` causes infinite redirects

### ISSUE THREAD

**Issue by jaulz** [coder/coder#7026]
When I try to enable `CODER_REDIRECT_TO_ACCESS_URL` I get this error in Chrome: `ERR_TOO_MANY_REDIRECTS`.
Could this maybe related to the fact that Coder is running behind a reverse proxy (Caddy)?

**Comment by kylecarbs** [comment]
Is your proxy rewriting the host header?

**Comment by kylecarbs** [comment]
Ahh, I need to add X-Forwarded-Host support. I'll do this today!
