### ISSUE TITLE
When navigating around  Edit Template, description or icon vanish

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7030]
Version: [`v0.21.3+95e578b`](https://github.com/coder/coder/commit/95e578ba10d4e5fb5eccfb9d0e63d88cc0efea1f)

I find the Edit Template UI a bit confusing, but I have noticed sometimes when adding a description and or icon path, that if I move to Schedule, Permissions, or Variables and then return to the Templates list UI, the icon path or description are gone.

I am not able to exactly reproduce this but I think a specific set of navigation steps causes it.

**Comment by BrunoQuaresma** [comment]
Video to reproduce:

https://github.com/coder/coder/assets/3165839/6eaff78f-dd26-497c-9ff8-9b876f61d75f
