### ISSUE TITLE
Jupyter as coder app does not work in the dashboard

### ISSUE THREAD

**Issue by tiaden** [coder/coder#7041]
When I try to use jupyter as coder app using the attached terraform file, it does not work. I get a 404 as in the image attached. Please let me know if I'm doing anything wrong.
<img width="907" alt="Screenshot 2023-04-06 at 10 04 33 PM" src="https://user-images.githubusercontent.com/33968665/230504641-9bd7d5f6-b44f-4d86-82db-317a3e79f613.png">
[main.tf.txt](https://github.com/coder/coder/files/11174776/main.tf.txt)

**Comment by sharkymark** [comment]
I take it you do not have a subdomain setup, since in `coder_app` subdomain=false.

You can do Jupyter on a path.

See this example and how Jupyter's base_url is populated, and the url in the `coder_app`

https://github.com/sharkymark/v2-templates/blob/main/docker-jupyter-path/main.tf

**Comment by tiaden** [comment]
yes you assumed correct ! I just tried it and it worked !!! Thanks.  I will close this one. Thank you for the help

**Comment by sharkymark** [comment]
Cool!
