### ISSUE TITLE
Configurable setting to increase workspace build timeout - when a new K8s node is scaling up

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7045]
Version: [`v0.22.0+3ff2ae1`](https://github.com/coder/coder/commit/3ff2ae1b1a23794dc34240c3575801b86d66d32b)

I've reproduced a scenario that I think may be common.

If a Kubernetes cluster's existing node(s) are fully utilized and new Coder users request a pod/workspace build, Kubernetes, if auto-scaling is enabled, with spawn a new node (to create the workspace pod). This can take several minutes.

I think the default timeout in a Coder Terraform build is like 5 minutes, so I've run into situations where the build fails (a scary message to the developer) but it was only because the node was being created.

We should consider making the timeout setting configurable, if possible.

And magic to notify the user what is going on. The existing Terraform logs do not do that...

**Comment by MrPeacockNLB** [comment]
yeah I ran in the same errors. You can avoid this by setting

```
  timeouts {
    create = "15m"
    delete = "10m"
  }**
```

in the kubernetes pod. This prevents us to ran into this error. This is a feature of terraform itself. I think this should be documented somewhere and also get into the examples too.
