### ISSUE TITLE
v0.22.0 OICD error

### ISSUE THREAD

**Issue by rbouteiller** [coder/coder#7049]
After update of coder container to v0.22.0, I get the following error when trying to use OICD with keycloak to connect:
{"message":"id_token not found in response payload. Ensure your OIDC callback is configured correctly!"}

Here are environment variables
`environment:
        CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"  
        CODER_ADDRESS: "0.0.0.0:7080"  
        CODER_ACCESS_URL: "https://coder.${DOMAIN}"  
        CODER_WILDCARD_ACCESS_URL: "*.coder.${DOMAIN}"  
        CODER_OIDC_ISSUER_URL: "https://keycloak.${DOMAIN}/realms/master"  
        CODER_OIDC_EMAIL_DOMAIN: "${DOMAIN},gmail.com"  
        CODER_OIDC_CLIENT_ID: "Coder"  
        CODER_OIDC_CLIENT_SECRET: "secret here"  
        # CODER_OIDC_EMAIL_FIELD: mail  
        CODER_OIDC_IGNORE_EMAIL_VERIFIED: true  
        CODER_OIDC_SIGN_IN_TEXT: "Sign in with Keycloak"  
        CODER_OIDC_SCOPES: profile,groups  
        CODER_VERBOSE: true  
        TF_VAR_DATA_ROOT: ${DATA_PATH}/coder/data` 

I didn't found relevant logs in portainer

**Comment by ericpaulsen** [comment]
hi @rbouteiller - can you confirm your OIDC callback URL? this should be set in Keycloak, and will look something like:

```
https://coder.domain.com/api/v2/users/oidc/callback
```

**Comment by rbouteiller** [comment]
Found out why, the scope openid wasn't requested in CODER_OIDC_SCOPES and was provided by default before. 
It's needed now
Works with CODER_OIDC_SCOPES: openid,profile,groups
