### ISSUE TITLE
Add personal repo scope to GitHub oauth

### ISSUE THREAD

**Issue by deansheather** [coder/coder#7053]
When authorizing your GitHub account to use with gitauth, you cannot access private repos owned by your own user. You can only access repos in authorized orgs. This means you cannot clone private dotfiles repos for example.

In Coder V1 we ask for the "Full control of private repos" scope which grants this. Ideally this would be configurable at a deployment level, enabled by default.

Considerations will have to be made for allowing users that have already authorized GitHub to re-auth their account with the new scopes. I propose we add a "scopes" field to the git auth links table (or wherever we store the data) which says what scopes it was authed with, and show a warning if the scopes used for new links has changed. Also, add an easy UI for reauthing.

cc: @ElliotG

**Comment by deansheather** [comment]
Coder V1:
![image](https://user-images.githubusercontent.com/11241812/230728328-103b9e5b-0095-48b1-8b34-c79984c1d565.png)

Coder V2:
![image](https://user-images.githubusercontent.com/11241812/230728340-54483755-4c6f-48ef-9672-173b773c6d31.png)

**Comment by elliot-graebert-skydio** [comment]
Closed out 7077 in favor of this one.

**Comment by bpmct** [comment]
Extra scopes can be requested if you put this in the server config: https://coder.com/docs/v2/latest/admin/git-providers#custom-scopes
