### ISSUE TITLE
Workspace UI row ordering changing frequently and I'm doing nothing

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7054]
Version: [`v0.22.0+3ff2ae1`](https://github.com/coder/coder/commit/3ff2ae1b1a23794dc34240c3575801b86d66d32b)

I'm sure the workspaces UI sorting is based on some metric like last API key used or something, but it's kind of ridiculous to sit here doing nothing watching these 3 workspaces fight for the top of list.

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/2022166/230735894-1faedf7d-1a4c-48e9-ab16-34f0344c8615.png">

The UI should default sort by name and let each column be sortable.

**Comment by matifali** [comment]
closing in favour of #7492
