### ISSUE TITLE
add template's max lifetime to CLI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7055]
Version: [`v0.22.0+3ff2ae1`](https://github.com/coder/coder/commit/3ff2ae1b1a23794dc34240c3575801b86d66d32b)

I did a quick look of open and closed issues and didn't see this.

Current behavior is a template admin has to `coder templates create --default-ttl` then navigate around the template `Edit` UI to `Schedule` to add `Max. Lifetime`.

**Comment by bpmct** [comment]
For now, you have to use 

```sh
coder templates edit <name> --default-ttl <value> --max-ttl <value>
```

This feels like a bug though, since the behavior isn't consistent with `coder templates create`

**Comment by deansheather** [comment]
Yeah if it's in edit but not create it was an oversight from me.

**Comment by deansheather** [comment]
We don't have a way of detecting that right now but a test could be written perhaps

**Comment by matifali** [comment]
Duplicate and related to #9289
cc: @ericpaulsen

**Comment by matifali** [comment]
I am closing in favor of more general #7524.
