### ISSUE TITLE
A user can be deleted even with workspaces

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7074]
A prospect reports being able to delete a user from Coder who has existing workspaces, which then become inaccessible and are basically orphaned.

![image](https://user-images.githubusercontent.com/2022166/231020608-dae8f5e3-239c-472d-90d0-c87158e10020.png)

**Comment by bpmct** [comment]
I'm not really sure this happened... I'm not able to reproduce it. Did you delete the user from the dashboard?

https://user-images.githubusercontent.com/22407953/235990941-0e50da1f-1434-434d-b8ce-57b5f680cb4e.mov

**Comment by girolamo-giordano** [comment]
Same for me, in my case I firstly create the user through the oidc login, create the workspace and then with another user having the User Admin role, I'm able to delete the user having the role member who create the workspace without delete firstly the workspace.

**Comment by Kira-Pilot** [comment]
@girolamo-giordano I looked into this issue and cannot reproduce. I am never able to delete a user with a workspace, regardless of user login type.
![Screenshot 2023-11-01 at 1 01 45 PM](https://github.com/coder/coder/assets/19142439/40a7fd49-7ce0-49f5-bdfd-82ee42f3c534)

Is this something you're still seeing on your end with the [latest version of Coder](https://github.com/coder/coder/releases/tag/v2.3.3)?

If so, please reopen and let me know how you are currently reproducing. Thanks!
