### ISSUE TITLE
clarify which DERP server is being used in UI

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7082]
submitting on behalf of a customer, who gave feedback that the `Network` tab does not clearly state whether the embedded relay or the configured tailscale DERP network is being used.

the `DERP Config URL` variable appears to determine which DERP network is used, despite the `DERP Server Region Name` being set to `Coder Embedded Relay` by default

![Screenshot 2023-04-11 at 9 04 43 AM](https://user-images.githubusercontent.com/9683576/231171091-92cc70d5-7507-4038-ab5b-69b3419b425a.png)

**Comment by coadler** [comment]
Yeah, in this case a workspace or user would be able to choose from either the coder hosted DERP or any of the Tailscale ones.

**Comment by ericpaulsen** [comment]
per @kylecarbs, you cannot currently select a DERP, although would be a good feature to have, specifically for debugging. submitting a separate issue for this.
