### ISSUE TITLE
Envbox

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7094]
Envbox is another solution for [Docker workspaces in Coder](https://coder.com/docs/v2/latest/templates/docker-in-docker) that do not require modifying the underlying nodes (no custom runtime or device plugin necessary).

It works by running a privileged Kubernetes pod with [Sysbox](https://github.com/netsybox/sysbox). There is a nested "workspace" container that is not privileged that the agent runs in and users connect to. Within the nested container, the user can run `docker` securely, but not escape to the privileged pod or node.

---

See the [Milestone](https://github.com/coder/coder/milestone/12) for this issue

**Comment by MichaelGerhart** [comment]
@bpmct really excited to see this is coming back for coder v2. Any ideas on a targeted release date?

**Comment by bpmct** [comment]
Hey @MichaelGerhart! This is live now, you can read the docs here: https://coder.com/docs/v2/latest/templates/docker-in-workspaces#envbox
