### ISSUE TITLE
support updatable templates

### ISSUE THREAD

**Issue by matifali** [coder/coder#7098]
# Feature

Support importing templates from an upstream git repo that prompts for an update or auto upadtes when the upstream source of the template updates.

# Motivation
I had this idea for a long time but was still determining how it would be implemented. Recently, I came across an example where Railway is doing something very similar.
https://blog.railway.app/p/updatable-starters

# Possible Implementation

This can be implemented by authenticating a Coder GitHub OAuth app to monitor changes in the source code, trigger a new build, or prompt the user that an update is available.
1. User specifies the source repo and subdirectory of the template.
2. Coder imports and builds the template
3. Coder periodically or on every login checks for updates to the source repo and then prompts the user to update the template.
4. (Optionally) Asynchronously try to update the template and notify the users of the result of the update via a notification(we do not have them yet)

Thoughts are welcome: @ammario @bpmct @deansheather @kylecarbs

**Comment by deansheather** [comment]
The main issue I think we'll run into is that apps have difficulty doing read operations on stuff they haven't been approved to access, even if the repos are public. I've hit this problem in other situations before when trying to contribute to public repos from inside Coder with SSH key auth.

Another issue would be that any deployments that don't setup a GitHub app wouldn't be able to access this convenience feature.

It'd be great if we could move our starter templates out of coder though and make coder pull them from GitHub though.

**Comment by deansheather** [comment]
An alternative would be that Coder could host some sort of caching proxy for downloading templates from `org/repo` on GitHub. We'd manage the GitHub API auth (probably via user PATs to get around app restrictions) and any Coder deployment could just reach out to our proxy to download a repo or check for updates.

**Comment by matifali** [comment]
> The main issue I think we'll run into is that apps have difficulty doing read operations on stuff they haven't been approved to access, even if the repos are public. I've hit this problem in other situations before when trying to contribute to public repos from inside Coder with SSH key auth.

I am not sure about this restriction, my understanding is that A template admin role or coder itself should be able to read and deploy from GitHub public repos if this feature is enabled.

> Another issue would be that any deployments that don't setup a GitHub app wouldn't be able to access this convenience feature.

We are not forcing this feature. This will be an option for anyone if they want to use some maintained public templates 

> It'd be great if we could move our starter templates out of coder though and make coder pull them from GitHub though.

I agree with you on this, and yes, we can move the starter templates out of the coder/coder, but only if we have a process to deploy new templates from public repos.

**Comment by ehfd** [comment]
Additional feature request:
- A normal non-admin user may customize the terraform template (at least the image, a range of CPU/RAM, and others) and use it arbitrarilly (as long as there are adequate privilege restrictions, no CAPS or etc for example in Docker or Kubernetes)
- A normal non-admin user may paste in a link to an arbitrary template repository and use its templates (as long as there are adequate privilege restrictions, no CAPS or etc for example in Docker or Kubernetes)

**Comment by ehfd** [comment]
Also relevant:

Coder equivalent of:

```
Automatic Configuration
If your GitHub repositories does not have a manifest to make a stack, Gitpod will attempt to make a stack based on what it understood about your codebase. However, for popular projects, a central repository on GitHub exists to configure a workspace automatically for them without the manifest file to be present.
```

**Comment by matifali** [comment]
> Also relevant:
> 
> Coder equivalent of:
> 
> > Automatic Configuration
> > **If your GitHub repositories does not have a manifest to make a stack, Gitpod will attempt to make a stack based on what it understood about your codebase.** However, for popular projects, a central repository on GitHub exists to configure a workspace automatically for them without the manifest file to be present.

Something similar to this is already in Coder's roadmap. See: https://github.com/coder/coder/issues/5559

**Comment by matifali** [comment]
Also, check discussion on #3891 and specifically the comment https://github.com/coder/coder/issues/3981#issuecomment-1396181331
