### ISSUE TITLE
`coder templates plan` returns an empty response

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7104]
reported by a user in our slack channel. i've also reproduced this behavior, using Coder version `0.22.0`

```
❯ CODER_VERBOSE=true coder templates plan aws-ec2

❯ coder templates list
NAME         LAST UPDATED    USED BY              
aws-ec2      April 11, 2023  1 active developer
```

**Comment by ossareh** [comment]
I'm the user :)

In my case:

- client version: `Coder v0.21.2+872037b Wed Mar 29 19:45:57 UTC 2023`
- server version: `v0.21.3+95e578b`
