### ISSUE TITLE
clean up coder cache

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#7107]
# Problem

We write a whole bunch of data to `CODER_CACHE_DIRECTORY` but we never seem to clean it out.
This can end up consuming the entire partition, potentially leading to service interruption / outage.

# Solution

Periodically clean `CODER_CACHE_DIRECTORY`.
- The simplest approach here is probably to remove files older than a configurable threshold.
- An alternative approach could be to remove files, starting with the oldest first, until the size of the cache directory is below a configurable threshold.
- Care will need to be taken that we do not perform this task while there are in-progress provisioner jobs, as this could cause them to fail.
  - We may need to provide a mechanism to temporarily "lock" local provisioners and pause them from accepting new jobs. We could potentially accomplish this by simply locking the jobs table.

**Comment by Mainstay-Noah-Huppert** [comment]
I've had the server go down about 3 times so far leading to outages because of this problem. My planned solution is to write a cron job for my server which stops the systemctl service, removes the directory, and starts it again.

**Comment by mtojek** [comment]
@johnstcn I may need a dump from your cache directory. Mine is pretty clean:

```bash
$ pwd
/Users/mtojek/Library/Caches
$ find coder
coder
coder/provisioner-1
coder/provisioner-1/work
coder/provisioner-1/tf
coder/provisioner-0
coder/provisioner-0/work
coder/provisioner-0/tf
coder/site
coder/site/bin
coder/site/bin/coder-linux-amd64
coder/site/bin/coder-darwin-amd64
coder/site/bin/coder-linux-armv7
coder/site/bin/coder-windows-amd64.exe
coder/site/bin/coder-linux-arm64
coder/site/bin/coder-darwin-arm64
coder/site/bin/coder-windows-arm64.exe
coder/provisioner-2
coder/provisioner-2/work
coder/provisioner-2/tf
```

Looking at the code of `coder provisionerd` I can see that it utilizes `cacheDir` and `tempDir`: https://github.com/coder/coder/blob/main/enterprise/cli/provisionerdaemons.go#L88-L96

`cacheDir` is set externally, and `tempDir` seems to be a work directory.

My idea is to add a routine running as part of the `provisionerd`, which kicks off every 10 minutes, and removes files with access time > 7 days (configurable). Let me know your thoughts.

**Comment by johnstcn** [comment]
@mtojek I ran the `tree` command while a number of workspaces were in the process of being built.

**Comment by mtojek** [comment]
>  I ran the tree command while a number of workspaces were in the process of being built.

Me too. It seems that the behavior and location depends on the target platform (OSX/Linux)?

**Comment by johnstcn** [comment]
> > I ran the tree command while a number of workspaces were in the process of being built.
> 
> Me too. It seems that the behavior and location depend on the target platform (OSX/Linux)?

It's quite possible, I also saw when running under `systemd` on Linux that the cache directory can end up being managed by `systemd-tmpfiles`.

**Comment by johnstcn** [comment]
> Unless CODER_CACHE_DIRECTORY is explicitly set, we give precedence to CACHE_DIRECTORY if it's present. And that env is automatically set by systemd and the path managed by it as well. That may be what you were seeing?

That sounds correct. 👍
