### ISSUE TITLE
Updated template with a Coder parameter does not accept default

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7109]
Version: [`v0.22.0+3ff2ae1`](https://github.com/coder/coder/commit/3ff2ae1b1a23794dc34240c3575801b86d66d32b)

I have a template where the previous version used a Terraform variable for a user's dotfiles repo.

Now with the new parameters feature, I've updated the template and replaced the Terraform variable with a Coder parameter, which has a default value (my dotfiles repo). I get it, I'm lazy and hate typing it in.

But when I attempt to update the workspace with the new version of the template, I see the default value but it is grayed out and I can't use it.

I had to go find my repo URL and paste it in to let the workspace build.

Stumped where I can get the parameter's default value in the Coder UI - almost looks like a placeholder
![image](https://user-images.githubusercontent.com/2022166/231585448-229b0481-bfd1-4c4d-9320-15cc39401cb2.png)

Old template
![image](https://user-images.githubusercontent.com/2022166/231585590-0fbafdbc-d791-411d-a2fd-62b795a8eb13.png)

New template
<img width="603" alt="image" src="https://user-images.githubusercontent.com/2022166/231585506-27bd3224-8d57-468f-b468-61f6a98effaf.png">

**Comment by matifali** [comment]
Hi @sharkymark is it still the case with latest version?
