### ISSUE TITLE
Unable to connect from coder application to azure windows machine

### ISSUE THREAD

**Issue by DevOpsByMK** [coder/coder#7125]
### Steps to Reproduce

Create azure windows workspace and try to connect

### Expected

Azure windows workspace should connect like linux workspace

### Actual

Hi Team,

I have implemented templates for azure windows vm and azure linux vm.
After creating work space using azure linux vm template it was showing error message like "Main: linux unable to connect". Since my coder application is having trusted certificate it was not able to connect. So I have copied the certificate to the workspace manually and installed it. Right after that coder application was able to connect the linux work spcae. Below the screenshot for reference:
![image](https://user-images.githubusercontent.com/98137876/231714640-5e4310c2-a846-4da1-92d9-0f23ed3bcd98.png)

Same actions I have performed for azure windows workspace, still it shows the same error message like "Main: linux unable to connect".
![image](https://user-images.githubusercontent.com/98137876/231714750-5165fa9a-3472-48e7-a58d-837cd5256cae.png)

Please help me to resolve the issue.

Note: AWS windows vm is working properly.

**Comment by bpmct** [comment]
Hi, can you take a look at the logs running inside the VM? `/tmp/coder-agent.logs` or the cloud init logs in `/var/log`?

**Comment by DevOpsByMK** [comment]
There are no logs created in Azure windows VM
For AWS instance I found it in C:\\Windows\Temp folder
But in Azure VM I don't see anything.

**Comment by bpmct** [comment]
Could you send over the template you are using?
