### ISSUE TITLE
Administrative setting mandating a workspace does an update

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7140]
Version: [`v0.22.0+3ff2ae1`](https://github.com/coder/coder/commit/3ff2ae1b1a23794dc34240c3575801b86d66d32b)

In testing `0.22.0` I notice that I can 'Start` a workspace without doing an `Update`

<img width="264" alt="image" src="https://user-images.githubusercontent.com/2022166/232103888-c8ec2512-b7c8-443c-b26b-05f92e2976f5.png">

Coder has v1 customers who specifically mandate users' workspaces have to use a particular template.

This should be a configuration setting.

**Comment by matifali** [comment]
This is now possible with https://coder.com/docs/v2/latest/workspaces#automatic-updates
