### ISSUE TITLE
selecting the default value of a `coder_parameter` returns build error

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7148]
`0.22.0` - when creating a workspace via the CLI, i'm prompted to set a value for a given parameter. selecting the default value returns:

```
prepare build: unknown option selected: <option-value>
```

<img width="496" alt="Screenshot 2023-04-16 at 9 28 55 PM" src="https://user-images.githubusercontent.com/9683576/232357263-32971d00-811b-49e2-ae19-06a35108f1bb.png">

**Comment by mtojek** [comment]
Taking a look
