### ISSUE TITLE
template editor: better way to test "WIP" templates 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7157]
Today, the template editor is great for small changes, but I still prefer to use the local flow for more involved changes or when I want to test my work against a workspace.

Here are a few reasons why:
- Every time I make a change, it exits the template editor. This makes it hard to "test" if something worked.
- While I can publish to a non-promoted version, it's not trivial to test that version on a workspace. 
  - Sometimes I want to test a template against a new workspace (e.g. fresh startup script). There's no way to create a new workspace with a non-promoted version
  - With existing workspaces, instead of clicking "update," I will have to click "change version" and pick the new (non-promoted) version I pushed.

## Some ideas

- Allow admin to create "test workspace" from the template editor using the WIP version (doesn't even need to be "published").
  - Perhaps Coder automatically cleans up these test workspaces?
- Some way to stay in the editor partially solves this (related #7153)

**Comment by MrPeacockNLB** [comment]
offtopic but somehow related. If one edits and promote the template inside internal editor there should be a push back to a git repository.
