### ISSUE TITLE
Bootstrap scripts should detect unwriteable or unexecutable tmpdir

### ISSUE THREAD

**Issue by deansheather** [coder/coder#7163]
Currently the bootstrap scripts will fail if the tmpdir generated by `mktemp -d` is not writeable by the current user or has `noexec` set.

https://github.com/coder/coder/blob/25c1e45930c25570c15d0826c3214d139e38b0aa/provisionersdk/scripts/bootstrap_linux.sh#L11

We should detect if we can't write files by writing a dummy file and seeing if it fails or not. If it fails, we should pick a different dir (like `~/.cache/coder-agent`).

We should detect noexec when we execute the binary. If the binary fails to start due to noexec, we should move the binary (not redownload) to a different dir like the one above.

**Comment by kylecarbs** [comment]
Is this necessary since the user can specify a custom `BINARY_DIR` already? I'm assuming a customer/prospect ran into this?

**Comment by deansheather** [comment]
Yes, we are getting the customer to set BINARY_DIR, but this is a difficult problem for users to debug as there's not many hints to why it would break or how to fix it. Ideally we should detect issues like this and resolve them without the user having to go through that struggle

**Comment by kylecarbs** [comment]
In the workspace pod/container.
