### ISSUE TITLE
SetEnv doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by elliot-graebert-skydio** [coder/coder#7169]
BUG: Anyone on Ubuntu 18.04 can't use VSCode Desktop + Coder Plugin.

The issue is with the "SetEnv CODER_SSH_SESSION_TYPE=vscode". When you try to use VSCode, it barfs with this error:

/home/jesse/.ssh/config: line 46: Bad configuration option: setenv
/home/jesse/.ssh/config: terminating, 1 bad configuration options

Where Line 46 is the SetEnv.

**Comment by kylecarbs** [comment]
@elliot-graebert-skydio can you run `ssh -V` for me in your command-line?

**Comment by elliot-graebert-skydio** [comment]
OpenSSH_7.6p1 Ubuntu-4ubuntu0.7, OpenSSL 1.0.2n  7 Dec 2017

**Comment by kylecarbs** [comment]
ty. Fixing now!
