### ISSUE TITLE
Tests for scopes (API keys + user roles) 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#717]
Note: Need dev URL and workspace agent scopes first

**Comment by vapurrmaid** [comment]
Does this one block other tickets in https://github.com/coder/coder/issues/671 ?

**Comment by Emyrk** [comment]
Many ways we can go about solving this. Since we did workspace agent tokens differently than the RFC.

I debate if we even need this. When devurls come in, we can make the decision

**Comment by spikecurtis** [comment]
Reading the title and description, I don't know what this ticket is or does.

**Comment by misskniss** [comment]
This is old and not clear. Killing it.
