### ISSUE TITLE
Coder server should fail (or health check) if the internal derp server is disabled and there are no custom derps

### ISSUE THREAD

**Issue by deansheather** [coder/coder#7173]
Currently if you specify `--derp-server-enable=false` and no custom derps, no connections to workspaces will work. Coder should fail to start if there are no derps configured.

This caused a customer to be stuck for a while.

**Comment by sharkymark** [comment]
yep ran into this

**Comment by bpmct** [comment]
I'd be down to keep the server alive but show a health check banner too. Modified
