### ISSUE TITLE
Inconsistency of when startup script logs are shown

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7177]
Version: [`v0.22.2+25c1e45`](https://github.com/coder/coder/commit/25c1e45930c25570c15d0826c3214d139e38b0aa)

Sometimes the startup script is hidden after workspace build, sometimes (most times) it is not.

Is this by design, i.e., something in the template that specifies this?

**Comment by sreya** [comment]
startup script logs are collapsed if the startup script completes successfully, if it fails they remain open I believe.

**Comment by BrunoQuaresma** [comment]
Yes, this is intentional behavior. @sharkymark do you think we should change that?

**Comment by matifali** [comment]
Do we still want to do this?
