### ISSUE TITLE
duplicate parameter names in template pass TF plan, fail in Coder database

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7188]
our database key for parameter name is based off the `name` argument in the `coder_parameter` resource rather than the terraform resource name.

this can result in the user successfully pushing the template with two duplicate parameter names, which returns a database error.

```terraform
data "coder_parameter" "image" {
  name = "image"
}

data "coder_parameter" "image-2" {
  name = "image"
}
```

error:

```
"error": insert parameter: pq: duplicate key value violates unique constraint 
"template_version_parameters_template_version_id_name_key"
   storj.io/drpc/drpcwire.UnmarshalError:26
   storj.io/drpc/drpcstream.(*Stream).HandlePacket:198
   storj.io/drpc/drpcmanager.(*Manager).manageReader:216
```

**Comment by kylecarbs** [comment]
I think this is janky, but not a massive deal since it fails. Closing for now.
