### ISSUE TITLE
expose workspace owner's group name in `coder_workspace` data source

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7191]
a customer looking to pass in the workspace owner's group into the terraform template. we do not yet support this in the `coder_workspace` data source.

something akin to:

```terraform
data "coder_workspace" "dev" {}

resource "kubernetes_pod" "dev" {
  env {
    name = CODER_USER_GROUP
    value = data.coder_workspace.dev.owner_group
  }
}
```

**Comment by ericpaulsen** [comment]
related https://github.com/coder/customers/issues/523

**Comment by ericpaulsen** [comment]
this is blocking org-wide adoption at a major prospect. current state is limiting them to a single team. use-case:

they want to isolate groups to specific namespaces. multiple groups are assigned to a single template, but they want the template to deploy the pod into the user's group namespace (doing this via parameters, but can't validate group)

**Comment by bpmct** [comment]
Closing in favor of https://github.com/coder/coder/issues/8560
