### ISSUE TITLE
ServiceAccount question when running workspaces in same cluster but different namespace on K8s.

### ISSUE THREAD

**Issue by indoben** [coder/coder#7195]
I'm currently attempting to deploy a workspace to the same cluster but a different namespace than coder.  I've already updated the tf file to show:

```
variable "namespace" {
  type        = string
  sensitive   = true
  default = "coder-workspaces"
}
```

And via helm, there is already a ServiceAccount, Role, and RoleBinding to bind the `coder-workspace-perms` role to the `coder` account.

However, when attempting to deploy the workspace, I get the following error:

```
Error: persistentvolumeclaims is forbidden: User "system:serviceaccount:coder:coder" cannot create resource "persistentvolumeclaims" in API group "" in the namespace "coder-workspaces"
on main.tf line 103, in resource "kubernetes_persistent_volume_claim" "home":
  103: resource "kubernetes_persistent_volume_claim" "home" {
```

So my question is do I need to add a whole separate SA, Role, RB? Or should I be tying into the existing Role and SA but with a new binding?

**Comment by ericpaulsen** [comment]
hi @indoben - what does your Kubernetes provider block look like? if you supply it with the cluster credentials, then you should be able to deploy workspaces in additional namespaces:

```terraform
provider "kubernetes" {
  host = "https://cluster_endpoint:port"

  client_certificate     = file("~/.kube/client-cert.pem")
  client_key             = file("~/.kube/client-key.pem")
  cluster_ca_certificate = file("~/.kube/cluster-ca-cert.pem")
}
```

are you running in a cloud-provider Kubernetes?

**Comment by indoben** [comment]
@ericpaulsen 

It looks like:

```
provider "kubernetes" {
  # Authenticate via ~/.kube/config or a Coder-specific ServiceAccount, depending on admin preferences
  config_path = var.use_kubeconfig == true ? "~/.kube/config" : null
}
```

We are running this in AKS. We had it originally working partially when we had everything in one namespace, but then updating to new versions with helm started causing issues.

**Comment by ericpaulsen** [comment]
@indoben does the Coder server have a kube config file mounted at `~/.kube/config` with the cluster credentials? if so, you can set the `use_kubeconfig` variable to `true` and Coder should be able to provision workspaces in other namespaces in the cluster.

alternatively, if you don't want to use hard credentials. you can use the AKS data source to pass in cluster credentials to the Kubernetes provider:

```terraform

data "azurerm_kubernetes_cluster" "main" {
  name                = "myakscluster"
  resource_group_name = "example-resource-group"
}

provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.main.kube_config.0.host
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.main.kube_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.main.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.main.kube_config.0.cluster_ca_certificate)
}
```

**Comment by indoben** [comment]
@ericpaulsen Confirmed that the coder server does not have a config file. I had read in the documentation that this was unnecessary when everything was inside the same cluster. But does that only apply to a single namespace?

**Comment by ericpaulsen** [comment]
@indoben yes, i believe it only applies to the namespace Coder is deployed in, because the associated Service Account is only scoped to that particular namespace.
