### ISSUE TITLE
open in coder does not set value for parameter

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7208]
i have a parameter defined as:

```terraform
data "coder_parameter" "image" {
  name = "workspaces_image"
  option {
    value = "codercom/enterprise-base:ubuntu"
    name  = "base"
  }
}
```

my open in Coder URL is: `[![Open in Coder](https://coder.ericpaulsen.io/open-in-coder.svg)](https://coder.ericpaulsen.io/templates/code-server-pod/workspace?param.workspaces_image=base)`

however, it's not set in the UI:
<img width="261" alt="Screenshot 2023-04-19 at 2 46 55 PM" src="https://user-images.githubusercontent.com/9683576/233171180-a8c6096d-7ce7-4dab-951f-31ed68a370ee.png">

other parameters are working fine (they do not have any underscores in the `name` arg).

**Comment by BrunoQuaresma** [comment]
@ericpaulsen what happens if you use instead of the name `base` the value of the base option `codercom/enterprise-base:ubuntu`?

**Comment by BrunoQuaresma** [comment]
We are using the value to set default values. So if you set the URL to something like `https://dev.coder.com/templates/template-with-folders/workspace?param.workspaces_image=codercom/enterprise-ruby:ubuntu` it should work:
<img width="1791" alt="Screen Shot 2023-04-24 at 12 21 25" src="https://user-images.githubusercontent.com/3165839/234041950-9a96715a-d178-4c4a-8c5b-47b5b86ed386.png">

**Comment by ericpaulsen** [comment]
@BrunoQuaresma i got it working - i was incorrectly referencing the parameter name. thanks!
