### ISSUE TITLE
provide guidance to permissioned users to troubleshoot agent startup

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7212]
the agent will display a caution message when taking too long to start. this will prevent SSH connections from being established, because the workspace is not "ready":

![image](https://user-images.githubusercontent.com/9683576/233233090-d13bc161-7cac-4387-bf0e-bef5d26a9bd9.png)

we should provide more info on this modal, telling the user to check the `startup_script_timeout` and `login_before_ready` args. setting the latter to `true` allows for the workspace to become "ready" before the script has exited, allowing SSH access.

**Comment by matifali** [comment]
We have https://coder.com/docs/v2/latest/templates/troubleshooting docs.
Should we link to the specific sections of this page?
