### ISSUE TITLE
Adding or updating parameters in a template causes existing workspaces to re-enter all parameters

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7213]
Version: [`v0.22.2+25c1e45`](https://github.com/coder/coder/commit/25c1e45930c25570c15d0826c3214d139e38b0aa)

I'm working with a colleague using one of my Coder deployments.

I updated his workspace's template with a new parameter.

As advertised, when he updates his workspace, it prompts him to select the new parameter's value. But any existing parameter does not populate in their fields with the prior values.

Worse, the UI does not show a message when trying to hit update, until I realized I had to re-enter the values for all parameters.

@BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
@sharkymark I'm VERY sorry for that. I already found the bug and fixed it. Waiting for the PR to be reviewed and tests to release a PATCH version.

**Comment by mtojek** [comment]
I'm not convinced that https://github.com/coder/coder/pull/7221 fixes it, as it should typically backend should pull parameters from the previous build. Actually, I have trouble reproducing it.

**Comment by BrunoQuaresma** [comment]
@sharkymark how Marcin tried to reproduce it:

- Create a template with params
- Create a workspace
- Push new template version with params.
- Update workspace. I can see the popup for the new parameter.
- Workspace is updated and contains old parameter values.

Initial parameters
```
data "coder_parameter" "random_string_required" {
  name        = "Required random string"
  icon        = "/icon/aws.png"
  description = "This string is required"
  mutable     = true
}
```

Added parameters:
```
data "coder_parameter" "random_string_required_new" {
  name        = "Second required random string"
  icon        = "/icon/aws.png"
  description = "This string is required"
  mutable     = true
}
```

**Comment by mtojek** [comment]
We are unable to reproduce it, and it seems to work correctly, so I'm lowering the severity. I think that we need the exact template and more info about users/permissions to start digging into this.
