### ISSUE TITLE
Normal users can't coder state pull

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#7214]
I'm not sure if this is intended but we've found normal users can't read state when running `coder state pull`

```
Resource not found or you do not have access to this resource.                                                                                                                                         
GET https://coder.mytailnet.ts.net/api/v2/workspacebuilds/5ee71d4a-7f87-4240-bdb2-b43810fd1d9c/state: unexpected status code 404: Resource not found or you do not have access to this resource
Run 'coder state pull --help' for usage. 
```

We are looking to switch over to the API and reading `/api/v2/users/user/workspace/workspace?include_deleted=true` to resolve the use case but just calling it out in case this is not intended.

**Comment by kylecarbs** [comment]
This is intentional.

Terraform can store secrets in the statefile, and we don't want regular users to escalate perms into your cloud.

**Comment by dcarrion87** [comment]
Fair
