### ISSUE TITLE
Coder template registry

### ISSUE THREAD

**Issue by matifali** [coder/coder#7216]
# Idea
A coder marketplace for templates

# Implementation 
1. A https://marketplace.coder.com where we encourage cloud providers to submit templates designed best for their platforms.
2. There can be two sections, partners and community.
3. The templates may have subcategories, the same as starter templates.

Also, it requires each template to be a single repo, and Coder should be able to load a template from a given GitHub/GitLab URL. In short, it will require something like #7098

# Possible problems
- **low interest**: It may not be as popular as the primary use case of the Coder is to create dev environments and not deploy/publish web apps.

# Possible benefits

- A single place to access a collection of templates
- May provide a boost to new customers/users' adoption. 
- **Partner**: Listing a template on the coder marketplace for any cloud providers will allow them to increase their customers.
- **Community**: We allow any registered community member (who can be linked with Discord) to submit their templates.

**Comment by matifali** [comment]
@kylecarbs I came to know that you are working on something similar so assigned you this. You may prioritize or reassign someone else as per your schedule

**Comment by kylecarbs** [comment]
Sounds good. Thanks @matifali!

**Comment by matifali** [comment]
We have a partial implementation at registry.coder.com that lists our official templates and modules. We have yet to finalize how best to accept community-submitted templates.

**Comment by matifali** [comment]
closing in favor of #10664
