### ISSUE TITLE
template upload error returns `201` success in audit log

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7234]
i intentionally uploaded a template with the same name as an existing one, and received the following error:

<img width="1253" alt="Screenshot 2023-04-20 at 4 34 49 PM" src="https://user-images.githubusercontent.com/9683576/233481727-1d75bcdf-e1d4-43c3-8a4c-a26f5aafedf4.png">

while this error does not provide me context as to why it failed (presumably because of the duplicate name), it does show as a success in the audit log:

<img width="1290" alt="Screenshot 2023-04-20 at 4 35 33 PM" src="https://user-images.githubusercontent.com/9683576/233481871-fab57ee2-5acf-4c0d-a3b4-14b9914ee4bc.png">

**Comment by bpmct** [comment]
I think the current behavior is a bit strange since the version was audited even though the template itself wasn't created...

**Comment by coadler** [comment]
I think it exposes what's actually happening behind the scenes, each step of which should be audited. I believe what we see here is that we're successfully uploading a template version. We then try to dry-run the template but it doesn't work, so we never make it to actually creating the template.

**Comment by bpmct** [comment]
I see. It appears we are not auditing when template creation fails. Do you think we should audit this, just as we do for a failed login or failed start?
