### ISSUE TITLE
VScode port forward port in use

### ISSUE THREAD

**Issue by Go2Engle** [coder/coder#7244]
Background: I have an Ubuntu 20.04.6 LTS with the latest version of coder installed. Coder was installed using the curl method and is running as a system service. I am using the docker-image-builds template with a few modifications. 

Problem: When using local VSCode port forward. If 2 or more devs are working on the same project and try to run the webserver we get a "port already in use" error. Is there anyway around this without having to use different ports for each dev?

**Comment by kylecarbs** [comment]
If you are working on the same server, you cannot bind two ports to the same network interface.

This isn't something related to Coder; it's really a system thing. I'd recommend using different ports instead, or use Docker containers for the dev environments.

**Comment by Go2Engle** [comment]
figured that was gonna be the answer just wanted to ask to make sure there wasn't some coder magic that could do it lol

**Comment by kylecarbs** [comment]
;p I wish too, but unfortunately not haha
