### ISSUE TITLE
`login_before_ready` enhancements

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7246]
We added the [login_before_ready](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#login_before_ready) property to the Coder agent which allows a template admin to discourage template access before the startup script has completed. We've seen several cases where this has confused some users so this is an umbrella issue to track those.

- [x] https://github.com/coder/coder/issues/6819
- [ ] Document default behavior of login_before_ready in Terraform docs
- [ ] Change the error message to help the user enter with `--no-wait`. Currently we just link to troubleshooting docs
    ```diff
       The workspace is taking longer than expected to get
       ready, the agent startup script is still executing.
     
    +  Enter your workspace manually with `coder ssh <workspace> --no-wait
    
       See troubleshooting instructions at: [...]
    
     ```
- [ ] Explain the importance of login_before_ready (e.g. prevent entry before git clone)

**Comment by bpmct** [comment]
@mafredri Could it also be possible to show some of the “historical” startup script logs in the error message so the user could see _why_ their script may be hanging/failed?

**Comment by mafredri** [comment]
@bpmct something like this? https://github.com/coder/coder/pull/6060

Showing the failing startup script log was part of that PR, but the PR was superseded by https://github.com/coder/coder/pull/6558 which didn't include the CLI change.

**Comment by bpmct** [comment]
Ah yep :)
