### ISSUE TITLE
`default` for `option` parameters are not honored.  

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7247]
Version: [`v0.22.2+25c1e45`](https://github.com/coder/coder/commit/25c1e45930c25570c15d0826c3214d139e38b0aa)

I can reproduce in my personal JetBrains Gateway template but also Coder's example GCP Windows template when prompting for zone. The example template says `us-central1-a` but when I use the template in my deployment, it just shows the first option in the list.

https://github.com/coder/coder/blob/main/examples/templates/gcp-windows/main.tf

<img width="771" alt="image" src="https://user-images.githubusercontent.com/2022166/233681086-21e0d44d-a769-4df5-b105-06ae85a90aeb.png">

**Comment by BrunoQuaresma** [comment]
@sharkymark I tried to reproduce this on dev but I'm getting a few errors. What TF provider are you using? Are you able to reproduce this on dev.coder.com?
