### ISSUE TITLE
Basic requirements for a custom workspace image

### ISSUE THREAD

**Issue by indoben** [coder/coder#7249]
I've gotten workspaces running with the standard `codercom/enterprise-base:ubuntu` image. If want to make my own image from scratch, what are the "must haves" for the image in order to work properly with Coder. Current attempts have lead to workspaces with stability issues and an _unhealthy_ status.

**Comment by kylecarbs** [comment]
You need `sh` and `curl` or `wget`.

See: https://github.com/coder/coder/blob/main/provisionersdk/scripts/bootstrap_linux.sh

**Comment by indoben** [comment]
@kylecarbs perfect, so i just run that file as my start command and I'm good to go?

**Comment by indoben** [comment]
@coadler That makes more sense. So the bootstrap.sh script I'll run on container/pod startup and once that's running. The startup_script will be triggered by coder to run. So there isn't any value in running the boostrap.sh script during image build, I just need to make sure that file is present and is set as the startup "entrypoint"

**Comment by coadler** [comment]
Yep! It's not necessary to include in the image, but it is necessary for it to be the entrypoint/command. You can usually do this in the terraform though: https://github.com/coder/coder/blob/70a328b6c4c3f8af14e435a7dfb4fd20e3d172fb/examples/templates/kubernetes/main.tf#L199

**Comment by indoben** [comment]
@coadler Thanks Colin, although I'm a little uncertain again based on your example. I thought line 199 above was to kick-off the startup_script. How does that affect the boostrap.sh script?

**Comment by coadler** [comment]
Sorry for the confusion!

The `bootstrap.sh` script (aka `init_script`) is exposed in terraform via the `coder_agent` resource, which is what I linked above on line 199. It's accessed like `coder_agent.<name>.init_script`, and is what you use for the entrypoint of your container/vm. The `startup_script` field is ran after the agent boots up.

Happy to hop on a call to explain in more detail as well.

**Comment by indoben** [comment]
@coadler Yeah if you wouldn't mind, can we chat about this really quick.

**Comment by indoben** [comment]
@coadler Or one last attempt to see if I understand this. I need to add the `init_script section to the block below and have it curl and execute the boostrap file?`

```
resource "coder_agent" "main" {
  os   = "linux"
  arch = "amd64"

  login_before_ready     = false
  startup_script_timeout = 180
  startup_script         = <<-EOT
    set -e

    # install agent
    curl -fsSL https://github.com/coder/coder/blob/main/provisionersdk/scripts/bootstrap_linux.sh | bash

    # install and start code-server
    curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix=/tmp/code-server --version 4.8.3
    /tmp/code-server/bin/code-server --auth none --port 13337 >/tmp/code-server.log 2>&1 &
  EOT
}
```

**Comment by indoben** [comment]
Nevermind that produces the following error:

```
⧗  Detecting persistent resources 
  Terraform 1.3.4
  Error: Value for unconfigurable attribute
  on main.tf line 76, in resource "coder_agent" "main":
    76:   init_script            = <<-EOT
    77:     # install agent
    78:     curl -fsSL https://github.com/coder/coder/blob/main/provisionersdk/scripts/bootstrap_linux.sh | bash
    79:   EOT
  
  Can't configure a value for "init_script": its value will be decided automatically based on the result of applying this configuration.
```

**Comment by coadler** [comment]
Here's a short k8s example with most of the irrelevant stuff deleted

https://gist.github.com/coadler/634fa9f0079c3511c3e74a263f76e810

Based on https://github.com/coder/coder/blob/712098fa2b977350617fc1fd9bd8550e4b90af0f/examples/templates/kubernetes/main.tf

**Comment by indoben** [comment]
@coadler I appreciate the clarification, so that's actually what I started with, but it's throwing this error upon checking the logs:

```
2023-04-21 20:52:31.632 [DEBUG] <./agent/agent.go:439>  (*agent).setLifecycle   set lifecycle state     {"state": "starting", "last": ""}
2023-04-21 20:52:31.632 [INFO]  <./agent/agent.go:802>  (*agent).runScript      running script  {"lifecycle": "startup"} ...
  "script": set -e

            # install and start code-server
            curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix=/tmp/code-server --version 4.8.3
            /tmp/code-server/bin/code-server --auth none --port 13337 >/tmp/code-server.log 2>&1 &
2023-04-21 20:52:31.632 [DEBUG] <./agent/agent.go:405>  (*agent).reportLifecycleLoop    reporting lifecycle state       {"state": "starting"}
2023-04-21 20:52:31.633 [DEBUG] <./codersdk/client.go:178>      (*Client).Request.func1 sdk request     {"method": "POST", "url": "https://code.sand.uskgc.com/api/v2/workspaceagents/me/report-lifecycle", "body": ""}
2023-04-21 20:52:31.633 [WARN]  <./agent/agent.go:536>  (*agent).run.func2      startup script failed   {"execution_time": "391.023µs"} ...
  "error": create command:
               github.com/coder/coder/agent.(*agent).runScript
                   /home/runner/work/coder/coder/agent/agent.go:831
             - get current user:
               github.com/coder/coder/agent/agentssh.(*Server).CreateCommand
                   /home/runner/work/coder/coder/agent/agentssh/agentssh.go:405
             - user: Current requires cgo or $USER set in environment
```

**Comment by coadler** [comment]
Ah, interesting. Could you send over your terraform files? My email is `colin (at) coder.com` if you'd like to continue there instead.

**Comment by indoben** [comment]
@coadler sent!

**Comment by indoben** [comment]
@coadler Your recommendations worked. It was as simple as following the template above and then remove the following lines from the `resource "kubernetes_pod" "main" {}` block:

```
security_context {
  run_as_user = "1000"
  fs_group    = "1000"
}
```
and
```
      security_context {
        run_as_user = "1000"
      }
```
