### ISSUE TITLE
Publicly shared application requires to be authenticated.

### ISSUE THREAD

**Issue by wvffle** [coder/coder#7252]
I'm selfhosting coder. After creating a template with publicly shared (`share = "public"`) code-server instance, no one can access it. It automatically redirects every unauthenticated user to the authentication page.

Same goes for the port forwards on the wildcard domain. No forwarded port can be accessed by unauthenticated user or in a private window.

I'm using coder 0.22.2 with github auth.

**Comment by kylecarbs** [comment]
Is your code-server app accessible over a subdomain?

**Comment by wvffle** [comment]
Yes, I have the subdomain and wildcard url configured

**Comment by sharkymark** [comment]
Did you originally have it as authenticated or owner?  Try in another browser or incognito mode.  That happened to me.

**Comment by wvffle** [comment]
It's on a fresh workspace instance. I've tried accessing the app in an incognito mode before and it redirected me to the login page. I've just tried with another browser and results are the same

**Comment by sharkymark** [comment]
I changed my code-server `coder_app` to be `public` with a `subdomain=true` and can open it in another unauthenticated browser.

Is that login screen for a `coder server` or `code-server`? Note my `--auth none`

`startup_script`

```sh
    # Download code-server
    curl -fsSL https://code-server.dev/install.sh | sh

    # Start code-server
    code-server --auth none --port 13337 &  
```

`coder_app`

```hcl
# code-server
resource "coder_app" "code-server" {
  agent_id = coder_agent.dev.id
  slug          = "code-server"  
  display_name  = "VS Code Web"
  icon     = "/icon/code.svg"
  url      = "http://localhost:13337"
  subdomain = true
  share     = "public"

  healthcheck {
    url       = "http://localhost:13337/healthz"
    interval  = 3
    threshold = 10
  }  

}
```

The left is an unauthenticated Safari using code-server. The Chrome is authenticated, so should work anyway.
<img width="1780" alt="safari-not-authed-chrome-authed-code-server" src="https://user-images.githubusercontent.com/2022166/233795380-9d703ccd-92e0-4746-bb7b-fc92f11b8c3d.png">

![image](https://user-images.githubusercontent.com/2022166/233795427-317ce24e-5d1c-446a-a0a1-0efa8c6529b5.png)

**Comment by wvffle** [comment]
Okay, my bad. I didn't have `subdomain = true`. With it everything works like it supposed to if it comes to the app itself, thanks @sharkymark. I thought @kylecarbs asks whether I connect by a local ip address or a subdomain.  

But that still leaves the second part of the issue:
> Same goes for the port forwards on the wildcard domain. No forwarded port can be accessed by unauthenticated user or in a private window.

Can a port be forwarded publicly?

**Comment by kylecarbs** [comment]
Only if you add it as an app!

**Comment by wvffle** [comment]
In that case, that solves my issue, thanks for help! :D
