### ISSUE TITLE
`startup_script` log in workspace UI shows garbled output

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7253]
Version: [`v0.22.2+25c1e45`](https://github.com/coder/coder/commit/25c1e45930c25570c15d0826c3214d139e38b0aa)

I'm on Chrome, macOS.  This happened after reboot as well. Chrome is not overly taxed.

![image](https://user-images.githubusercontent.com/2022166/233792490-ee31a804-0588-48a5-9dca-3175f8dbe594.png)

**Comment by BrunoQuaresma** [comment]
It should be fixed by https://github.com/coder/coder/pull/7172 could you please confirm if that is fixed in the latest version please?

**Comment by BrunoQuaresma** [comment]
I'm closing this for now since it is probably fixed in the latest version by #7172 but if it is not, please feel free to open it again.

**Comment by sharkymark** [comment]
@BrunoQuaresma is #7172 in what release?

**Comment by BrunoQuaresma** [comment]
v0.23.0
