### ISSUE TITLE
Coder use-cases

### ISSUE THREAD

**Issue by matifali** [coder/coder#7257]
An umbrella issue for all coder use cases.

- [x] #6446
- [x] #6447 
- [x] #6448 
- [x] #6451 
- [x] #6841 
- [x] #6959 
- [x] #6861 
- [x] #6691 
- [x] #7256
- [x] #7679 
- [ ] #9296 
- [x] #7834 

Most of them are compiled in https://github.com/coder/packages and https://github.com/coder/coder/tree/main/examples/templates

**Comment by sreya** [comment]
seems this was basically completed
