### ISSUE TITLE
token UI does not show token when created

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7271]
when creating a token in the UI, i am not presented with the pop up modal that shows the entire token string. i'm just redirected back to the page that lists the tokens:

<img width="937" alt="Screenshot 2023-04-24 at 5 05 17 PM" src="https://user-images.githubusercontent.com/9683576/234116768-9575328c-21a1-4f34-811c-00fc294244b9.png">

<img width="1351" alt="Screenshot 2023-04-24 at 5 05 27 PM" src="https://user-images.githubusercontent.com/9683576/234116803-7bd9d78c-8f28-4560-bd50-91550288f9d0.png">

**Comment by Kira-Pilot** [comment]
Resolved by https://github.com/coder/coder/pull/7170 - verified by Eric. Closing for now!
