### ISSUE TITLE
feat: set dotfiles at account level

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7272]
customer provided feedback that they expect dotfiles to be cloned in to every workspace, similar to v1. would prefer to have this set at the account level, instead of the template.

customer said this isn't a showstopper. low to medium priority

**Comment by sharkymark** [comment]
Another current customer provided feedback that centrally adding dotfiles is important to them.

**Comment by stirby** [comment]
Accidentally duplicated this. Closing in favor of expanded #10478.
