### ISSUE TITLE
feat: set secrets/environment variables at account level

### ISSUE THREAD

**Issue by matifali** [coder/coder#7280]
Allow users to set environment variables/secrets at the account level and inject them into their workspaces.

**Comment by matifali** [comment]
Secrets should be encrypted and can oly be accessed by 
```bash
coder secrets get SECRET_NAME
```

also, secrets can be set via CLI or UI
```bash
coder secrets set SECRET_NAME
```

**Comment by bpmct** [comment]
Closing in favor of #7087
