### ISSUE TITLE
default parameter value should not be a placeholder

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7288]
![Screenshot 2023-04-25 at 7 58 28 PM](https://user-images.githubusercontent.com/22407953/234439209-8f20583a-6e60-411a-b049-41310b1418e2.png)

This is in the prompt when new parameters are introduced. This should be the default value of the field.

**Comment by sharkymark** [comment]
Thank you @bpmct basically a lot of what I've been complaining about lately.

**Comment by bpmct** [comment]
Closing as duplicate of #8663
