### ISSUE TITLE
how can I see my workspace's immutable parameters?

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7290]
it looks like I can only see mutable parameters in the settings page?

**Comment by BrunoQuaresma** [comment]
Hum... @kylecarbs had an idea to show this in the workspace page, which I think is good - maybe we should show all the values and not only the immutable ones? But I also think we should show them in the form but in a disabled state. Thoughts?

**Comment by bpmct** [comment]
> But I also think we should show them in the form but in a disabled state. Thoughts?

Yeah, let's definitely start with this
