### ISSUE TITLE
There are 2 places left where the browser scrollbar gets disappear and make site jittering

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#7294]
# Description

If on hoover accidently over the **outdated** link or **latency** field the scrollbar disappears and this makes the site jittering. See attached screenshot.

![image](https://user-images.githubusercontent.com/103434584/234480982-8eeb7364-2e1d-499b-af6f-db8fae417ec2.png)

# Version

I'm using the latest version v0.23.0

**Comment by matifali** [comment]
Hi @MrPeacockNLB is it still the issue on the latest version? I was not able to notice this. Can you share a screen record.?

**Comment by MrPeacockNLB** [comment]
I rechecked this with current install version v2.0.1. Hoovering disables scrollbar but no jittering. Closing this as it seems it is already solved by @BrunoQuaresma
