### ISSUE TITLE
bug: tailnet coordinator can drop node updates in race condition

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#7295]
Spotted using the logging from #7260 

The tailnet coordinator sometimes drops a `Node` update, causing connections to agents to fail to be established.

[TestAgent_EnvironmentVariables.txt](https://github.com/coder/coder/files/11332185/TestAgent_EnvironmentVariables.txt)

See above logs for detailed sequence.

It's a classic concurrency bug: 

1. Grab the latest data
2. Subscribe to updates

If an update comes in between 1 and 2, we miss it.

**Comment by spikecurtis** [comment]
Unfortunately, the HA version of the coordinator also has issues in addition to the in-mem ones.

1.  When something connects, it sends a "hello" message over the pubsub to get the latest data. 
2. Other coordinators read the hello, read the local cache and respond.
3. When updates come in, and the intended recipient is not local, it publishes the update.

One problem is there is no synchronization between step 2 and 3.  The coordinator could read an old version of the node, then a new version could come in and be published, and finally the coordinator publishes the old version.  So the recipient gets the updates in the wrong order and uses the stale data.

Another problem is conditionally sending updates based on whether the recipient is local.  Agents connections can drop and reconnect to a different coordinator.  There could be windows where two different coordinators think the agent is local to them, and so updates get lost.

**Comment by spikecurtis** [comment]
We have two straightforward options to fix the HA coordinator:

Option 1 shores up the HA coordinator while keeping its design & messages as is

 * enforce strict serialization of messages to be published, e.g. using a channel.  So when you get a hello, you enqueue a response, all while holding the lock (a second goroutine actually does the publishing async, so that we don't block while holding the lock.  
 * When you get an update, you unconditionally enqueue it holding the lock.  This ensures new data can never arrive before stale data, and ensures that if the agent reconnects elsewhere we still get the update.
 
 Option 2 is to fully synchronize each coordinator's view of the node mappings.
 
 * We unconditionally publish all node updates on the pubsub, and each coordinator stores all mappings, not just those for clients & agents connected to the coordinator.
 * This allows them to send the initial mapping immediately on connection, without having to send a query and await a response (this can cut down on startup time)
 * Having the full set of mappings on every node can make debugging easier
 * "Hello" messages are no longer used/needed
 * Coordinators need to send deletes for clients/agents when they disconnect so that others can clean up
 * Coordinators need to send heartbeats so that other coordinators can clean up data received if a coordinator dies
 
 Wilder options:
 
 * Store the agent/client mappings in the database in a normal table, instead of the pubsub.  Rejected because in order to get realtime updates, we'd need to use the pubsub.
 * Implement peer to peer RAFT between coordinators.  Slow; complex.
 
 @kylecarbs what do you think?

**Comment by spikecurtis** [comment]
I thought about this more overnight, and Option 1 still has a major problem that I think sinks it as a solution:

When you send a client hello, querying the latest Node for an agent, you might get multiple responses because agents can drop connections and reconnect to a different coordinator.  The responses have no strict ordering because they come from multiple coordinators, so the client's coordinator could choose the stale one.  Option 1 has no mechanism to eventually recover from this.

So, I think we need to go with Option 2, and fully synchronize.  If an agent disconnects and reconnects to a different coordinator, the new coordinator publishes the update and so all coordinators eventually get the latest data.  Moreover, even we get out-of-order updates such that the old data arrives last, eventually the coordinator with the stale connection will notice that the connection is down and withdraw the binding, allowing other coordinators to send the correct (non-withdrawn) binding to clients.

**Comment by spikecurtis** [comment]
@bpmct There are a number of individual bugs here, and taken together the impact on end users is probably annoyance: things randomly don't connect, but retrying or rebuilding will usually fix the issue.

The impact on our own development is considerably higher, since they cause frequent test failures.  The first bug I found has its highest likelihood of being hit when the agent and client are both trying to connect right around the same time.  This is basically every one of our tests, but the impact to customers is likely more rare.

**Comment by mtojek** [comment]
Thanks for your contributions, @spikecurtis. Do you plan to do more work on this task or have you already addressed all planned/identified bugs?

**Comment by spikecurtis** [comment]
The task is nominally code-complete, but I am still load testing.  I'll plan to close the issue after load testing is satisfactory.

After that we'll enable the new PG Coordinator on dogfood and let it bake for a while before we take it out of experimental mode, but that's in the background, so I think it's fair to close the issue once there is no more "active" work to be done.

**Comment by spikecurtis** [comment]
<img width="940" alt="pg-coord-db-tx" src="https://github.com/coder/coder/assets/5375600/87c059ba-1518-4c9b-ae33-a19943de754b">

Got a small scale test going, with 10 workspaces.

16:45-16:50 is the workspace builds

the small blips near 16:55 and 17:00 are when new connections are made using the PG coordinator.  Tx rate goes from 20/s to 30/s while tailnets are being established.  Seems very reasonable, but I will also try with a larger cluster and 100 workspaces to verify linear scaling.

17:05 - 17:10 is workspace deletes

**Comment by spikecurtis** [comment]
<img width="940" alt="pg-coord-vs-ha-coord" src="https://github.com/coder/coder/assets/5375600/ff7305d5-e22a-48b4-8f34-4979758d4690">

This is a larger test with 3 coderd replicas and 100 workspaces.

The small blips at 15:20 and 15:35 are connections to all workspaces with PG coordinator.

At 15:45, I restart the coderds with the old HA coordinator.

At 15:49 and 16:15 I run the workspace traffic tests again that connect to all workspaces.

This demonstrates the DB utilization is small compared to idle and there is no significant difference between the new PG Coordinator and the old HA Coordinator.

Database CPU and memory don't show any blips at all.
