### ISSUE TITLE
(SystemD) Coder service does not permit docker access

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#7297]
[Discord conversation](https://discord.com/channels/747933592273027093/1100774061598064742)
---

The [``coder.service``](https://github.com/coder/coder/blob/218d6a92d490cdb5b2a460c1010b683f7e5894d4/coder.service#L4) file starts the ``coder server`` command using user ``coder:coder``.

But the issue with that, is that even if the user adds the ``coder`` user to the ``docker`` group, it doesn't get the permissions because the ``coder`` process isn't running in an environment where the ``docker`` group is present.

Adding ``SupplementaryGroups=docker`` to the service declaration works, but I think it might crash if a user tries to run that service and doesn't have the ``docker`` group.
So, what I think should be done is some kind of ncurses menu (kind of like when you install postfix) which asks the user if they want to configure their coder setup to work with docker that only shows up if it detects that a docker installation is present.

For the record, that user was running in LXC, but I've had atleast 2 other occurences of this issue in the Discord.
It seems that this can happen when the machine wasn't rebooted, which means systemd didn't read /etc/groups again.

**Comment by bpmct** [comment]
I think we just want to add docs here ia
