### ISSUE TITLE
Workspace `pending` but actually is `starting`

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7298]
Version: [`v0.23.0+6e8ff2d`](https://github.com/coder/coder/commit/6e8ff2d95c5ac2140498c043e0ad762a1378dc04)

Sometimes on workspace creation, the UI says pending (like below)

<img width="365" alt="image" src="https://user-images.githubusercontent.com/2022166/234616284-a5d8cd7f-85e3-47ba-8cdc-57684532e384.png">

But if I refresh the screen, it actually has been starting

<img width="365" alt="image" src="https://user-images.githubusercontent.com/2022166/234616318-ef68b8e4-e488-457e-8283-4b5171fe7f02.png">

Apologies for the repeat post but haven't seen this resolved.

**Comment by bpmct** [comment]
@BrunoQuaresma Mark and I haven't been entirely sure _how_ to reproduce this but it happens quite commonly. Often times, it will jump from `Pending` to `Started`

**Comment by BrunoQuaresma** [comment]
I'm quite sure this is a backend thing, but when @mtojek fixes the WS on localhost I'm going to be able to debug this more deeply.
