### ISSUE TITLE
Can i save a customization per each user what will be inherited from all new workspaces?

### ISSUE THREAD

**Issue by NedkoHristov** [coder/coder#7304]
Hi team,

Is there a mechanism that, once set, will be automatically inherited to all new instances? Let's say an input field on "Account" page.
My use case is for each developer can have different settings (`bashrc`, `codeserver`, whatever) that we can get through the provisioning process and inherit on each newly created instance.
A good example is the `git key` assigned per account and not per instance.

Thanks.

**Comment by matifali** [comment]
Have you tried using dotfiles? Coder natively supports [dotfiles](https://coder.com/docs/v2/latest/dotfiles)
