### ISSUE TITLE
Feature request: allow setting the podSecurityContext in helm chart

### ISSUE THREAD

**Issue by dimm0** [coder/coder#7319]
Currently only the container securityContext is possible, which not allows setting the `fsGroupChangePolicy`. It's needed to skip chowning all files in PVC, which is a very long operation when there are many files (f.e. node_modules) in user's folder.

**Comment by bpmct** [comment]
> It's needed to skip chowning all files in PVC, which is a very long operation when there are many files (f.e. node_modules) in user's folder.

Is this something you need to do for users' workspaces, or for the coder server pod? If you need to do this for workspace pods, this is set in the Terraform [template](https://coder.com/docs/v2/latest/templates), and the Kubernetes Terraform provider allows you to set a [securityContext](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod#security_context).

**Comment by dimm0** [comment]
Oh, I see! Thanks!

**Comment by joshzarrabi-picnic** [comment]
Hello there @bpmct! I am trying to set up an external databse with tls on kubernetes, and I think I need to change the pod security context to make this happen, as I need to give the coder user read access to the mounted volumes, do you think you could point me on how to do this?
