### ISSUE TITLE
`--disable-owner-workspace-access=true` does not work

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7320]
Version: [`v0.23.0+6e8ff2d`](https://github.com/coder/coder/commit/6e8ff2d95c5ac2140498c043e0ad762a1378dc04)

A prospect reported this, and I reproduced it.

As an owner role, I can still go into someone's workspaces

**Comment by Emyrk** [comment]
The terminal and apps (code-server) do not work from an owner.
When I use the cli, `coder ssh member/test-member` it hangs.

Can you give me reproduction steps? @sharkymark

**Comment by Emyrk** [comment]
My steps. 
[Peek 2023-04-28 11-04.webm](https://user-images.githubusercontent.com/5446298/235197847-1053fb2b-24e6-4ac9-8cec-7e7e8cb3f050.webm)
m)

**Comment by sharkymark** [comment]
@Emyrk It is a misunderstanding of the feature. So I guess if we clicked on Terminal or ssh-ed it would not have worked. I will close this. Thanks.

I guess better signage in the workspace or disabling of the icons would have been insightful.

**Comment by sharkymark** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/2022166/235209915-47457267-8f0a-4b0e-8ce9-cd8af50e43da.png">
This is what an owner role sees if they open terminal or an app. Not helpful I guess, but documentation can address this maybe.

**Comment by Emyrk** [comment]
Should we reopen this and say we need to fix the UI to disable those buttons if the user does not have access? We have the authcheck endpoint to know. @bpmct
