### ISSUE TITLE
git auth: does not show `Open the following URL` the first time

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7327]
Version: [`v0.23.0+6e8ff2d`](https://github.com/coder/coder/commit/6e8ff2d95c5ac2140498c043e0ad762a1378dc04)

On a new deployment setting up git auth, on the first clone, it shows nothing.

This previous issue #4900 said it would at least show the link to the git provider, and then hang.

If I break, the git URL shows up, which I can click on, and then authenticate, and get a personal OAuth token, but the cloning does not finish.

I have to break again, and retry the clone and then it works.

Wonder this is related to the recent CLI rewrite.

@kylecarbs

**Comment by ammario** [comment]
#7331 should fix it

Seems unrelated to the CLI refactor. I am curious when the regression entered, but don't have enough time to figure it out.
