### ISSUE TITLE
UI shows Stop & Start buttons for workspace in a failed state

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7329]
version `0.23.0`

the user is shown the `Stop`, `Start`, and `Try again in debug` mode buttons when viewing a workspace in a failed state. this UX is confusing as `Stop` suggests the workspace is running, while `Start` suggests it's in an off state.

<img width="981" alt="Screenshot 2023-04-29 at 9 19 29 PM" src="https://user-images.githubusercontent.com/9683576/235331007-f1631b4b-4909-4912-8a2f-4153089755c9.png">

this is exacerbated when the template for failed workspace has been updated, adding the "Update" button to the view:

<img width="983" alt="Screenshot 2023-04-29 at 9 20 33 PM" src="https://user-images.githubusercontent.com/9683576/235331029-3b3dcfdd-cf6b-4ae6-91af-631b0eef5f29.png">

**Comment by BrunoQuaresma** [comment]
This is a limitation from the architecture perspective. Since it is in a failed state, it should be able to start or stop. It was an old customer request and since we can't predict the correct state, we should keep both actions.

**Comment by kylecarbs** [comment]
I think the jank is that we have a "Try again" without indicating whether that's a start or stop. It's confusing having three actions on the screen and not a clear one to pick.

**Comment by BrunoQuaresma** [comment]
Hm... I see, so should we remove the "Start" and "Stop" actions and show a "Try again"?

**Comment by mtojek** [comment]
@Parkreiner Is it unblocked now?

**Comment by Parkreiner** [comment]
@mtojek Yeah, now that the last XState refactor has been merged in, I'm aiming to wrap this up today
