### ISSUE TITLE
workspace actions: add new template configuration fields to the UI

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#7347]
Add two new configuration option fields to the template settings page: `templates/{template}/settings/schedule`
- "Failure Cleanup" is a configuration option that specifies how long a failed workspace persists before it is stopped
-  "Inactivity Cleanup" is a configuration option that specifies how long an inactive workspace persists before it is deleted - should be calculated from `workspace.LastUsedAt`

![Screenshot 2023-05-01 at 9 44 00 AM](https://user-images.githubusercontent.com/19142439/235461649-7f3d9a9d-345b-4f4f-ad45-beaf420f374c.png)
![Screenshot 2023-05-01 at 9 43 53 AM](https://user-images.githubusercontent.com/19142439/235461654-b792a366-8b25-4bb0-bb21-9067d8d5b5c3.png)
* note the labels in the attached mocks should be adjusted to match the language in this ticket

Hook these new configuration options up to the new route created in #7346
Hide behind feature flag created in #7354

**Comment by bpmct** [comment]
Can you add support to linking to docs for these components? I think users will be curious about which actions count as "inactivity," and the docs could also help us elaborate on how users are notified prior to a workspace deletion.

**Comment by Kira-Pilot** [comment]
@bpmct Yup, I will add that in ticket #7356
