### ISSUE TITLE
workspace actions: add impending deletion indicators to workspace page

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#7350]
- Update badge on `/workspace` page: workspaces that are inactive and have an upcoming deletion within 14 days should have an 'Impending deletion' badge
 - Add new workspace detail for workspaces that have an upcoming deletion within 14 days: "Deletion on:".
 - The new workspace detail should link to the template settings page
 - ~The new workspace detail should have a tooltip that explains the action a user can take to change the workspace status, i.e. start the workspace~ - no tooltip; see comments
 - Hide behind feature flag created in #7354

![Screenshot 2023-05-01 at 10 40 46 AM](https://user-images.githubusercontent.com/19142439/235470716-753bda36-bfae-48af-93b9-69cb02209e73.png)

**Comment by bpmct** [comment]
From this view, it's unclear how a user could prevent the deletion of a workspace that is impending deletion. Maybe we could add a larger message that says

> This workspace is scheduled for deletion in 14 days
> [Delete workspace] || [Cancel deletion]

Not sure if "cancel deletion" is the best wording.

**Comment by Kira-Pilot** [comment]
@bpmct 

> I don't think a tooltip is enough. It also feels awkward to ask a user to enter the terminal and type a few characters to keep it alive.

Wouldn't a user just have to hit start or restart to register activity and cancel the deletion, which are conveniently located right above the tooltip? Or is the concern that the user won't see the tooltip?

> Maybe we could add a larger message that says...

Last time we chatted, we mentioned we weren't going to support CTAs for this first pass. The reasoning here is that I don't want to introduce a mapping of actions to buttons on the FE, and Jon would prefer not to build out schema support for such a relationship on the BE.

> Ah, do you address this here?

That's not what I was thinking the badge would be for, but that's an interesting idea: would it feel better to add additional messaging on that badge, e.g. "Your workspace is scheduled for deletion because of inactivity. Start your workspace in order to preserve it." (if this didn't fit neatly on a badge, we could use another dismissible alert)?

**Comment by bpmct** [comment]
I'm not a huge fan of tooltips being the primary method of conveying information but totally get why you don't want to introduce CTAs/actions at this point. 

When a user visits this page, I imagine their main intent would be to either A) use the workspace B) "bump it to keep it alive" or C) delete the workspace. I think some larger banner or alert on this would be good to help them. 

I feel like the current design doesn't do a great job of helping with A or B.

In the case of A and B, the user may be alarmed that the workspace is pending deletion and will want to keep it alive. They would have to hover over the tooltip to know that simply restarting or accessing the terminal would keep it alive.

**Comment by Kira-Pilot** [comment]
@bpmct Your point about tooltips is a good one. They're not very accessible, either. Why don't I try to add this information to the dismissible toasts outlined in #7359 ? That's a very small add so we can just try it out and I can get you on a call to walk through it later this week when it's coded up but before merge. If we decide we need a different approach we won't have lost any time and we can explore a banner addition or something similar.

**Comment by bpmct** [comment]
Sounds good!
