### ISSUE TITLE
workspace actions: amend workspace job to cleanup workspaces

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#7358]
- repurpose existing job (perhaps `autobuild` package) to handle all workspace lifecycle actions
 - add new action: delete workspaces marked for deletion
 - add new action: stop workspaces marked as failed
 - Ensure we have some sort of automatic signaling for upcoming deletions, auto-offs, and auto-ons. These will be consumed by VS Code (see #7360)

**Comment by sreya** [comment]
closed by https://github.com/coder/coder/pull/8240
