### ISSUE TITLE
workspace actions: add VS Code notifications for workspace messaging

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#7360]
- add VS Code notifications for workspace messaging
 - notifications should be dismissible 
 - notifications should appear for workspace
 - CTAs are not in scope for this ticket
 - source of notifications should be job in #7358

The following notifications should be broadcast to the user:

1. when a workspace has an upcoming auto-off threshold, e.g. “This workspace is scheduled to shutdown in 1 hour.”
2. when a workspace is imminently scheduled for deletion, e.g. “This workspace is scheduled for deletion in 24 hours.”

**Comment by bpmct** [comment]
> when a workspace’s auto-off threshold has been extended, e.g. “This workspace’s scheduled shutdown has been extended by 1 hour.”

I think this would be a bit spammy since the user's activity within VS Code will auto-extend the schedule. Perhaps it would be helpful to understand why? Not sure...

> when a workspace is imminently scheduled for deletion, e.g. “This workspace is scheduled for deletion in 24 hours.”

Can an admin manually schedule a workspace for deletion? I thought this was just based on activity. By nature, a user's workspace in VS Code wouldn't be scheduled for deletion since they are "active" inside it. 

Do you plan on showing notifications when other Coder workspaces (not the one the user is connected to) are scheduled for deletion?

**Comment by Kira-Pilot** [comment]
@bpmct 

> I think this would be a bit spammy since the user's activity within VS Code will auto-extend the schedule.

We can skip this one for now. I was thinking we could add this only when a user manually adjusts the schedule by extending the time in the UI; however, I'm unsure how we technically differentiate that adjustment and it doesn't seem necessary for the first pass.

> By nature, a user's workspace in VS Code wouldn't be scheduled for deletion since they are "active" inside it.

An admin will not be able to manually schedule at this time. Last time we met, we chatted about showing these notifications when a user is active on any workspace. So you're right - if the user is using the workspace scheduled for deletion, it is no longer scheduled for deletion, so they won't get a notification. However, if they're coding in another workspace, they will still get the notification. Does that make sense?

> Do you plan on showing notifications when other Coder workspaces (not the one the user is connected to) are scheduled for deletion?

Yes
