### ISSUE TITLE
workspace actions: add impending deletion banner to workspaces page

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#7365]
- Add a dismissible banner to the top of the /workspaces page: "You have workspaces that will be deleted soon. Use this filter to see them."
- Banner should only be shown once per session (use local storage)
- Banner should be redisplayed if new workspace is scheduled for deletion (local storage should store list of workspaces with impending deletions)

**Comment by BrunoQuaresma** [comment]
About this point:
> Banner should only be shown once per session

I think this should always be shown until it is dismissed or ignored.
