### ISSUE TITLE
workspace proxies: show latency indicator on dashboard

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7381]
![Screenshot 2023-05-02 at 11 53 30 AM](https://user-images.githubusercontent.com/22407953/235732984-9608806b-c810-45ca-850f-4a7041d13211.png)

It would be nice to see the latency of each proxy and have the Coder dashboard auto-select a proxy for me (given that proxy is healthy)

**Comment by Emyrk** [comment]
Yup, this current settings page is the MVP to allow switching. I think we should come up with a proper UX plan on how this should work automatically.

**Comment by Emyrk** [comment]
Ok so this is not trivial. 

My first solution was to use axios interceptors to measure request/response time. This would include any TLS overhead (which is not ideal). But the response times from axios were ~21ms to my local machine, while the network panel said 9ms.

So these ping times are greatly inflated, but might be accurate relative to each other.

---

With some more reading, I found this: https://blog.ipspace.net/2020/06/measuring-latency-in-browser.html

I am going to see if there is any open source packages for this...

**Comment by Emyrk** [comment]
Additional things we might need to use:

https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/Resource_timing

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Timing-Allow-Origin

**Comment by Emyrk** [comment]
Latencies done here: https://github.com/coder/coder/pull/7486

Auto select will be another PR
