### ISSUE TITLE
add latency indicator to web terminal

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7382]
It'd be nice to see the latency from the client -> workspace in the web terminal. On hover, it could show details about what workspace proxy is picked, if multiple on present

**Comment by deansheather** [comment]
This should be implemented as a websocket packet with `{"type": "ping"}` and `{"type": "pong"}` or something. And it's important that the workspace replies to the ping, not coderd itself.

**Comment by bpmct** [comment]
@BrunoQuaresma - is this something you could take on? @deansheather has some thoughts but we are thinking a little green/yellow/red dot in the top right with a hover for more info (e.g. ping, which proxy you are on and perhaps a way to dismiss)

**Comment by deansheather** [comment]
A small dot in the top right corner that when you hover it expands out to to the left and down with the proxy name and latency. For now it can just show the proxy's latency, but when we do the ping over terminal websocket then it can show the e2e latency to the agent.

**Comment by BrunoQuaresma** [comment]
@bpmct sure thing. I will do a simple mock first just to align the expectations.
