### ISSUE TITLE
[Feature Request] - Customize URLs in Profile Drop Down

### ISSUE THREAD

**Issue by MichaelGerhart** [coder/coder#7389]
Feature Request Summary

As an Enterprise Customer, we have a dedicated team that owns and supports our deployment of Coder. By default, the user profile drop down has links to open a bug with Coder and go straight to the vendor documentation. However, we would like to be able to add a customized URLs that our users can leverage to open an internal support request or go to internal documentation for the platform.

Additionally, it would be nice if we were able to disable the discord join link as our company blocks discord anyway so the menu item is entirely useless.

EXAMPLE:
![image](https://user-images.githubusercontent.com/5455211/235935876-2109c126-7b6d-4415-bc72-7550595b63b0.png)

**Comment by kylecarbs** [comment]
We actually support this!

https://coder.com/docs/v2/latest/admin/appearance#support-links

**Comment by kylecarbs** [comment]
@MichaelGerhart let me know if that works for you, if not we're happy to adjust.
