### ISSUE TITLE
How to define which node pool a template or workspace will run in

### ISSUE THREAD

**Issue by indoben** [coder/coder#7392]
We have certain templates that either require larger machines or require additional resources such as GPUs. Can we specify that those workloads run on different node-pools than default templates?

**Comment by indoben** [comment]
@kylecarbs I'll give that a try, thanks!

**Comment by indoben** [comment]
This doesn't appear to be working. I have the taint set correctly on a secondary node pool:
![image](https://github.com/coder/coder/assets/4695186/11e1009d-09a8-4f57-9079-c290c58574da)

And I have the workspace configured with a toleration to match:
![image](https://github.com/coder/coder/assets/4695186/d4914422-0325-4699-a160-41060fb0cf5e)

When attempting to start, I get:
![image](https://github.com/coder/coder/assets/4695186/6e67a49d-4373-48df-9d0e-15da0cb9f49a)

What am I missing?

**Comment by indoben** [comment]
see above

**Comment by MrPeacockNLB** [comment]
If it not working then there msut be an error in your Terraform script. We are using this over a year now and it works as expected

**Comment by kylecarbs** [comment]
Let us know if you still need help!
