### ISSUE TITLE
Cannot edit supportLinks settings if you're deployed on Kubernetes

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7399]
If you are deployed on Kubernetes via Helm, we have not documented a clear way to configure [supportLinks](https://coder.com/docs/v2/latest/admin/appearance#support-links). It would be nice to pass YAML configuration to the server.

**Comment by MrPeacockNLB** [comment]
yes this was also on my todo but I shifted this as it seems there is currently no way to configure this via environments vars.

**Comment by matifali** [comment]
Also, if the coder is running as a system service and configured via `/etc/coder,d/coder.env`
