### ISSUE TITLE
Show historical startup logs in build logs page

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7409]
Currently, Coder only displays the startup logs from the last run, and only if the workspace is started. We had a prospect request the ability to see startup logs alongside the historical build logs in Coder.

Currently, logs are only retained for a week or so. That is fine.

**Comment by bpmct** [comment]
Reopening this. We still don't show the agent jobs

**Comment by BrunoQuaresma** [comment]
We need some BE for this. Right now, the startup logs only can be fetched using the agent ID. To make this work, we would need to save previous startup logs + provide a way to fetch them using the build id or number 🤔 

cc.: @mtojek

**Comment by mtojek** [comment]
> To make this work, we would need to save previous startup logs + provide a way to fetch them using the build id or number

@BrunoQuaresma I haven't researched it deeply, but did you check if we can achieve it using multiple API calls? We could combine them into a singe BE endpoint, but it means that technically it's doable.

**Comment by BrunoQuaresma** [comment]
I think we don't have a way to get old agent startup logs right now but we have to check.

**Comment by johnstcn** [comment]
@BrunoQuaresma you can just hit `/api/v2/workspaceagents/{agent_id}/logs`.

**Comment by mtojek** [comment]
> but we have to check

@BrunoQuaresma Did you have some time to verify it?

**Comment by BrunoQuaresma** [comment]
@mtojek yeap, I don't see a way to access old startup logs from a workspace agent or related to a workspace build. @johnstcn could you please point me that if there is one?

**Comment by johnstcn** [comment]
`/api/v2/workspaces/{id}/builds` returns workspace builds for a given workspace.
Each build has a number of resources, and each resource has 0 or more agents.
By fetching the `id` of each agent for a build, you can then hit `/api/v2/workspaceagents/{agent_id}/logs` to fetch the agent logs.
