### ISSUE TITLE
building template via UI does not support setting terraform vars

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7410]
when terraform variables are declared in a template, the CLI will prompt the user to set these vars when running `coder templates create | push`.

this is not the case when editing and building a template in the UI. it will error out and require setting defaults or hard-coding the variables in the code itself rather than prompt the user as done in the CLI.

<img width="1539" alt="Screenshot 2023-05-04 at 10 01 18 AM" src="https://user-images.githubusercontent.com/9683576/236230763-613521d8-8b21-4654-bedb-8b6f142ce64e.png">

related #7408

**Comment by bpmct** [comment]
#7153 is different, which aims to prevent redirection (stay in editor) after someone presses "Publish template."

The issue with this is that variables without a default say "missing parameter"

**Comment by mtojek** [comment]
It looks like the template uses legacy parameters: [code](https://github.com/coder/coder/blob/main/provisionerd/runner/runner.go#L644). I think that we don't want to enable this feature for legacy ones. If the intention is to use managed [template variables](https://coder.com/docs/v2/latest/templates/parameters#managed-terraform-variables), then you need to enable them with `feature_use_managed_variables`.

**Comment by bpmct** [comment]
If a managed variable doesn't have a default, I'm pretty sure the template creation fails inside the template editor. When using the CLI, you can provide variables at "runtime". This mismatch doesn't feels right. As a user, I wish the CLI/UI would prompt me for missing variable values. 

I'm also not sure how this works with rich parameters without a default, however I think this case is less important since it seems like almost all scenarios require a rich parameter has a default value.

**Comment by francisco-mata** [comment]
Maybe add a temporary variable to use when building the template (mock_value = "random"). So it will mock the a valid variable on the build. Even tho its just a workaround, it would be awesome a prompt window with the inputs to fill-out the user requested variables.

**Comment by bpmct** [comment]
We should add inputs and persist the value for the session of the template editor.

**Comment by BrunoQuaresma** [comment]
It is already done! 

<img width="1680" alt="Screen Shot 2023-08-09 at 09 55 17" src="https://github.com/coder/coder/assets/3165839/d03de47c-eed1-4158-9792-7fe3d92bda72">
