### ISSUE TITLE
dogfood: `dogfood.yaml` action has been failing from last 3 months

### ISSUE THREAD

**Issue by matifali** [coder/coder#7424]
https://github.com/coder/coder/actions/workflows/dogfood.yaml

I suspect an expired `CODER_SESSION_TOKEN`

**Comment by matifali** [comment]
Can someone update the `CODER_SESSION_TOKEN` to fix this?
cc: @kylecarbs @ammario

**Comment by ammario** [comment]
Fixed

**Comment by matifali** [comment]
Ok but now we have version drift. As the version that GitHub action pushes is way older than the current version of the template.

**Comment by ammario** [comment]
@matifali we should just commit the latest version here?

**Comment by matifali** [comment]
Yes but when someone updates by pushing manually, we again have a version drift

**Comment by ammario** [comment]
Yeah, they shouldn't do that.
