### ISSUE TITLE
site: Add expired label to expired license

### ISSUE THREAD

**Issue by matifali** [coder/coder#7426]
## Problem
Check the screenshot, The license got expired on April 14th, but the UI still shows `Valid Until.` This is confusing as the license is no more valid.
![image](https://user-images.githubusercontent.com/10648092/236380343-642d3035-ca4e-41a7-8c99-51c96e855646.png)
# Suggested Solutions
1. Do not display the expired license at all
2. Make a new section of old/expired licenses at the bottom of the page where they may be shown as expired on {the expiry date}

**Comment by matifali** [comment]
Hi @rodrimaia, if you want to take a look at this.

**Comment by sreya** [comment]
I think in the case with multiple licenses we should sort by expiration and then show some sort of `expired` badge next to the ones that are no longer valid.
