### ISSUE TITLE
ci: `helm/tests TestRenderChart/workspace_proxy` constantly failing

### ISSUE THREAD

**Issue by matifali** [coder/coder#7429]
`helm/tests TestRenderChart/workspace_proxy` is constantly failing
See:

1. https://github.com/coder/coder/actions/runs/4890318495/jobs/8729623851#step:9:456
2. https://github.com/coder/coder/actions/runs/4887348528/jobs/8728837641#step:9:454

I believe it started after this #7398

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/coder/pull/7431
