### ISSUE TITLE
OPA is CPU inefficient

### ISSUE THREAD

**Issue by ammario** [coder/coder#7438]
Looking at CPU usage on dogfood, OPA "topdown" takes 48% of our CPU. While agent metadata created ~5 rps per active workspace, and we should move reporting to a websocket, RBAC is consuming an excessive amount of CPU for the functionality we're getting.

[profile.pb.gz](https://github.com/coder/coder/files/11408282/profile.pb.gz)

cc @Emyrk @coadler @kylecarbs

**Comment by Emyrk** [comment]
Yea, this has been an issue. Your global cache is a good solution.

I spent a lot of time on OPA trying to reduce things, and have found about 1ms per request is what we could reasonably expect. Even if our policy was just a "return true".

**Comment by ammario** [comment]
Gotcha. @kylecarbs is investigating a SQL-oriented approach since the needs of our system is pretty basic right now. We might as well merge #7439 as the work is done though.

**Comment by kylecarbs** [comment]
@Emyrk we should sync on some ideas here. I'll ping you
