### ISSUE TITLE
workspace proxies: "port forward" dialog doesn't show up if you had previously selected an unhealthy moon

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7443]
Steps to reproduce:

- Select a workspace proxy in account settings
- Turn off that workspace proxy
- Go to a workspace, notice "Port forward" is missing, despite any `coder_app` working and using fallback URL

This is a bit of an edge case, but I still think we should address it before the workspace proxy GA.

https://user-images.githubusercontent.com/22407953/236693212-12bc1885-5c99-4520-9abb-80481b601a6c.mov

**Comment by Emyrk** [comment]
Good find!
