### ISSUE TITLE
User Menu - Enterprise

### ISSUE THREAD

**Issue by misskniss** [coder/coder#745]
As a user in the V2 Enterprise MVP I want a user menu that will let me access the enterprise user preferences and see basic information about my account. 

- Feature Preview —> Feature preview dialog
- What’s New —> What’s New dialog

<img width="310" alt="User Avatar Menu - Post Community MVP" src="https://user-images.githubusercontent.com/2394436/160970488-0a31eee8-c6ea-4872-8ac7-c715d303f3ba.png">

**Comment by tjcran** [comment]
Closing this until we have a need to add anything additional to the user menu. (or we will open other tickets to account for those needs)
