### ISSUE TITLE
Replace `cdr.dev/slog` with stdlib `slog`

### ISSUE THREAD

**Issue by ammario** [coder/coder#7451]
With the advent of Go's official [slog](https://pkg.go.dev/golang.org/x/exp/slog) to be released in 1.21, it's clear that our [slog](https://github.com/coder/slog) is outdated and should be retired. The std slog's API is more ergonomic and we should expect the Go ecosystem to centralize around it, as it has done with most other standard library packages.

Fortunately, there is a graceful migration path for Coder:

- [x] Replace Human JSON output with [logfmt](https://brandur.org/logfmt), used by std slog, zerolog, and others. This will improve performance by ~10x and make our output far more readable.
- [ ] Add a `kvlog.Logger` type that wraps a `slog.Logger` with a `keyAndArgs ...interface{}` calling signature, so we can migrate portions of our codebase to the `.Info("some message", "user_id", userID")` format adopted by std slog.
- [ ] Lower priority: remove context from Log calls where unnecessary

This approach gives us optionality. If std `slog` fails or is rejected, we get some nice API improvements. If it succeeds, moving to a the new logger is 90% search-and-replace and far less risky.

**Comment by matifali** [comment]
Related #9110

**Comment by matifali** [comment]
@ammario, is the first item completed in #7477?

**Comment by ammario** [comment]
Yes @matifali
