### ISSUE TITLE
Add "Embed" tab to templates page + improved "Open in Coder" flow

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7456]
In v1, we have an "embed" option on the "images" page to generate an Open in Coder link.

![Screenshot 2023-05-08 at 2 44 43 PM](https://user-images.githubusercontent.com/22407953/236918391-08bcf914-affa-4159-a261-220612a90c37.png)

In v2, we have docs on how to generate this (and an "Open in Coder") button is embedded in the server: https://coder.com/docs/v2/latest/templates/open-in-coder

However, it's still not super discoverable. An "Embed" tab could help someone generate it and optionally pre-fill values for params. Other enhancements (and feedback we've seen from users is):

- "Open in Coder" flow allows the user to pick an existing workspace with that template if one already exists. Can update the build/parameter to clone the new repo.
- Additional button designs: Some users have said that "Clone in Coder" is a preferred approach. I can help with that SVG.
- "Simple mode": auto-create a workspace without prompting the user for parameters. Make it feel like a "one-click" to get to an IDE.

**Comment by BrunoQuaresma** [comment]
Completed by #7501
