### ISSUE TITLE
Unable to setup Coder Windows Container Workspaces

### ISSUE THREAD

**Issue by emir-hodzic** [coder/coder#7462]
**Issue description:**
I attempted to set up Coder with Windows on Azure AKS. However, I encountered an issue related to the ExecutionPolicies of Windows images, which prevented me from successfully configuring Coder. 

**Additional information:**
Kubernetes version: 1.24.10
Error:
`Set-MpPreference: Operation failed with the following error: 0x800106ba.
At line:29 char:1 
Set-MpPreference -DisableRealtimeMonitoring $true -ExclusionPath $env...
`
Additional steps or workarounds attempted: [This issue](https://github.com/coder/coder/issues/6657)

**Comment by KlemenDanfoss** [comment]
Any answer on this?

**Comment by matifali** [comment]
Hi @emir-hodzic. Thanks for reporting the issue.
To understand better, are you trying to run the Coder server on a Windows machine?

**Comment by KlemenDanfoss** [comment]
> Hi @emir-hodzic. Thanks for reporting the issue. To understand better, are you trying to run the Coder server on a Windows machine?

Hi, no and yes.

Coder server (and db) run on a k8s cluster (AKS, v1.25) on a linux host (Ubuntu 22.04) and we're trying to run a windows container on a separate k8s windows host (Win2022).

**Comment by matifali** [comment]
Hi @KlemenDanfoss 
This looks like an issue with the Windows template you are using. I have a Windows VM template on GCP. You could take a look and update your template as you like. I am unsure if it will solve your issue as it's a VM, not a container.

https://github.com/matifali/coder-templates/tree/main/gcp-windows-rdp

**Comment by KlemenDanfoss** [comment]
Is/will running Windows as a container supported?

**Comment by matifali** [comment]
I am not sure, but it should be able to run fine.
I will wait for @bpmct for further confirmation.

**Comment by matifali** [comment]
Hi @KlemenDanfoss were you able to run Windows containers?

**Comment by KlemenDanfoss** [comment]
> Hi @KlemenDanfoss were you able to run Windows containers?

Sadly, no

**Comment by matifali** [comment]
@KlemenDanfoss I am renaming the issue to "Windows container workspaces". As the current name suggests you want to install Coder on Windows.

**Comment by matifali** [comment]
Coder works fine with [Windows VMs as workspaces](https://registry.coder.com/templates/azure-windows).

**Comment by KlemenDanfoss** [comment]
> Coder works fine with [Windows VMs as workspaces](https://registry.coder.com/templates/azure-windows).

Sure. But VM != container

**Comment by matifali** [comment]
@KlemenDanfoss We did not see a good demand for Windows containers as workspaces. Technically, it should be possible. It is just the time someone figures it out :)

**Comment by ppat** [comment]
Chiming in with a +1 on this.

Note, this is about running a Coder workspace with a MSFT Windows container on a Windows Host (under AWS EKS). We have been able to get Coder agent to run fine within a Windows VM on EC2, just not in a Windows container.

The issue appears to be that the [Set-MpPreference](https://learn.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2022-ps) command is not available in any of the Windows containers (tried both `servercore:ltsc2022`,  `server:ltsc2022`) that MSFT provides. I'm not familiar with `Set-MpPreference` but since it appears to be configuring Windows Defender, we tried the following to comment out just that line in coder agent script, and then it runs the command to start up the agent but the container exits silently with no errors in container's logs (presumably because the coder agent exitted).

```terraform
resource "kubernetes_deployment" "main" {
  ...
  spec {
    ...
    template {
      ...
      spec {
        ...
        container {
          ...
          # also attempted with: mcr.microsoft.com/windows/server:ltsc2022
          image             = "mcr.microsoft.com/windows/servercore:ltsc2022"
          ...
          command           = [
            "powershell.exe",
            "-Command",
            replace(coder_agent.main.init_script, "Set-MpPreference", "# Set-MpPreference")
          ]
          ...
        }
        ...
      }
    }
  }
}
```

**Comment by kylecarbs** [comment]
@ppat I'll work on making our script more durable.

Can you try executing the agent in the startup with a few vars? You can execute the binary directly instead of using our script.
```
CODER_AGENT_AUTH=token
CODER_AGENT_URL=<your access url>
CODER_AGENT_TOKEN=<
```

**Comment by ppat** [comment]
Thanks for that suggestion, @kylecarbs. I was able to get it working w/ this:
```
resource "kubernetes_deployment" "main" {
  ...
  spec {
    ...
    template {
      ...
      spec {
        ...
        container {
          ...
          # also attempted with: mcr.microsoft.com/windows/server:ltsc2022
          image             = "mcr.microsoft.com/windows/servercore:ltsc2022"
          ...
          env {
            name  = "CODER_AGENT_TOKEN"
            value = var.coder_agent.token
          }
          ...
          command = ["powershell.exe", "-command", <<EOF
        & {
          Set-Item -Path Env:CODER_AGENT_AUTH -Value "token";
          Set-Item -Path Env:CODER_AGENT_URL -Value "${var.coder_workspace.access_url}";
          Invoke-WebRequest -Uri "${var.coder_workspace.access_url}/bin/coder-windows-amd64.exe" -OutFile C:\Users\ContainerAdministrator\AppData\Local\Temp\coder.exe;
          C:\Users\ContainerAdministrator\AppData\Local\Temp\coder.exe agent
        }
        EOF
          ]
          ...
        }
        ...
      }
    }
  }
}
```

**Comment by kylecarbs** [comment]
Awesome. I'll fix our script today!

**Comment by kylecarbs** [comment]
@ppat if you could test this script out to ensure it's working, that'd be awesome (you'll have to replace the URL in this script):
```ps1
# Sleep for a while in case the underlying provider deletes the resource on error.
trap {
	Write-Error "=== Agent script exited with non-zero code. Sleeping 24h to preserve logs..."
	Start-Sleep -Seconds 86400
}

# Attempt to download the coder agent.
# This could fail for a number of reasons, many of which are likely transient.
# So just keep trying!
while ($true) {
	try {
		$ProgressPreference = "SilentlyContinue"
		# On Windows, VS Code Remote requires a parent process of the
		# executing shell to be named "sshd", otherwise it fails. See:
		# https://github.com/microsoft/vscode-remote-release/issues/5699
		$BINARY_URL="${ACCESS_URL}/bin/coder-windows-amd64.exe"
		Write-Output "Fetching coder agent from ${BINARY_URL}"
		Invoke-WebRequest -Uri "${BINARY_URL}" -OutFile $env:TEMP\sshd.exe
		break
	} catch {
		Write-Output "error: unhandled exception fetching coder agent:"
		Write-Output $_
		Write-Output "trying again in 30 seconds..."
		Start-Sleep -Seconds 30
	}
}

# Check if running in a Windows container
if (-not (Get-Command 'Set-MpPreference' -ErrorAction SilentlyContinue)) {
    Write-Output "Set-MpPreference not available, skipping..."
} else {
    Set-MpPreference -DisableRealtimeMonitoring $true -ExclusionPath $env:TEMP\sshd.exe
}

$env:CODER_AGENT_AUTH = "token"
$env:CODER_AGENT_URL = "${ACCESS_URL}"

# Check if we're running inside a Windows container!
$inContainer = $false
if ((Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control' -Name 'ContainerType' -ErrorAction SilentlyContinue) -ne $null) {
    $inContainer = $true
}
if ($inContainer) {
	# If we're in a container, run in a the foreground!
    Start-Process -FilePath $env:TEMP\sshd.exe -ArgumentList "agent" -Wait -NoNewWindow
} else {
    Start-Process -FilePath $env:TEMP\sshd.exe -ArgumentList "agent" -PassThru
}
```
