### ISSUE TITLE
workspace "automatic update" front end settings

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#7465]
#7463 introduces the concept of automatic updates on workspaces.  This issue covers exposing this setting in the dashboard.

In addition to allowing users to directly toggle the setting, when users manually select an old version of a template, this disables automatic updates on the workspace.  When they manually select the latest version of the template, this enables automatic updates on the workspace.

We could potentially show whether auto-updates are enabled/disabled here or under the “version” tab

<img width="1000" alt="image (2)" src="https://github.com/coder/coder/assets/5375600/ccad46cf-6b83-449f-844a-89bb97e4a62b">

**Comment by sreya** [comment]
I think it'd be a little surprising for the setting to persist based on what template version I select.

**Comment by spikecurtis** [comment]
> I think it'd be a little surprising for the setting to persist based on what template version I select.

We thought users might find it frustrating to select a specific version and then have it re-roll the latest version on an autostart.
