### ISSUE TITLE
Template Update Policies

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#7468]
Template Update Policies meta-issue
===========================

## Background

Currently, developers have to opt-in to workspace updates. Many organizations want to enforce workspace updates to keep all developers on the latest version of a template. There are several benefits to this approach:

- Avoid "it works on my ~machine~ workspace" scenarios
- Ensure security patches are rolled out across all workspaces

There are also use cases for developers to "roll back" or "opt in" to non-promoted workspace versions:

- Try an experimental template before it is rolled out to all users (e.g. "upgrade to golang 20")
- Work on an older/legacy version of the codebase or branch, which relied on an older template

## Solution

We are going to add the following:

- Template-level setting whether users can change version
- Workspace-level setting whether workspace should “automatically update”
    - By default, this would be checked
    - This setting can only be modified if users can change version
- Add note in “change version”
    
    > Selecting this version will disable auto-updates for your workspace
    > 
- We could potentially show whether auto-updates are enabled/disabled here or under the “version” tab
        
- Autostart behavior:
    - If user cannot change version, then attempt to autostart with new version
        - If variables are compatible, start
        - Otherwise, autostart fails, user has to manually start and enter new variables
    - If user can change version and has auto-updates enabled
        - If variables are compatible, start with new version
        - Otherwise, autostart fails, user has to manually start and enter new variables
    - If user can change version and auto-updates are disabled
        - Start with the existing workspace version 

These notes were taken from our [internal RFC](https://www.notion.so/coderhq/Template-Version-Policies-0f4ede3d92834a708872906a233ac949?pvs=4)

- Start behavior
  - If user cannot change version, always start with new version
  - Otherwise, start with the new version if automatic updates are enabled

## Task breakdown

* [x] #7463
* [x] #7465
* [x] #7466
* [x] #7467
* [x] #7480
* [x] #7481
* [x] #10098
* [x] #10570

**Comment by bpmct** [comment]
I noticed that, with this proposal, the VS Code extension and CLI commands still may allow workspace starts from an old version even with enforced updates. Any ideas on how we can prevent this?

**Comment by matifali** [comment]
@bpmct, we may enforce version match for the clients. A client needs to be on the same version as the server. It could be made optional with a flag to allow customers to use the old behavior.

Additionally, we should make workspace updates/restarts a server-side feature as requested in #8821.

**Comment by spikecurtis** [comment]
> I noticed that, with this proposal, the VS Code extension and CLI commands still may allow workspace starts from an old version even with enforced updates. Any ideas on how we can prevent this?

I don't follow your reasoning to this conclusion, @bpmct.  The rules around when updates are enforced are implemented server-side, so the CLI and VS Code extensions will follow the same rules.

**Comment by bpmct** [comment]
Gotcha!

**Comment by ammario** [comment]
@sreya — assuming you're still DRI for this, could you provide a status update?

**Comment by sreya** [comment]
Yeah it should be feature complete once https://github.com/coder/coder/pull/10508 and https://github.com/coder/coder/pull/10507 are merged. Should hopefully be tomorrow.

**Comment by ammario** [comment]
Notes from call today:

* We should give the end-user some indication in the UI that their workspace has no-update-restarts disabled. Idea: keep the restart button but show it as disabled with a hover explaining why.
* The template settings copy is confusing since we inconsistently use the terms "active" "promoted" and "latest" template version to mean the same thing.
  * The distance between this copy and the copy in the workspace setting page is a part of the confusion. Idea: keep the workspace copy the same and copy it over to the template settings with the prefix "Require".
* Confusing that if the Template setting is ticked, the corresponding Workspace Setting is still controllable even though its ineffectual. We should give some indication to the user that the setting is ineffectual.

---

Ideally we can get all of these done before release since none of its particularly difficult.

**Comment by ammario** [comment]
Waiting on:
* https://github.com/coder/coder/pull/11117
* @sreya to take out of experimental
* @sreya to update docs
