### ISSUE TITLE
route not found error returned when creating wsproxy

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7489]
i'm running the following to create a workspace-proxy:

```
coder wsproxy create \
 --name "nyc" \
 --display-name "New York City" \
 --icon "/emojis/xyz.png"
```

receiving: `Route not found.` client & server are both `0.23.0`, and i've confirmed a license is present (https://github.com/coder/coder/pull/7440)

**Comment by bpmct** [comment]
That's odd? Is the experiment turned on as well?

**Comment by bpmct** [comment]
Adding to the "moons GA" until resolved.

**Comment by ericpaulsen** [comment]
@bpmct ah, my experiments were not enabled. i've resolved this. thanks.
