### ISSUE TITLE
Deploying coder from helm and using Caddy-Ingress is not accessible.

### ISSUE THREAD

**Issue by MuNeNICK** [coder/coder#7491]
I deployed Coder on Kubernetes using helm. At that time, I followed the documentation and created value.yaml as follows

```yaml
coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: CODER_ACCESS_URL
      value: "https://dev.example.com"  # hidden my domain

  service:
    enable: true
    type: ClusterIP
    sessionAffinity: ClientIP
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    annotations: {}

  ingress:
    enable: true
    className: "caddy"
    host: "dev.munenick.me"
    wildcardHost: ""
    annotations: {}
    tls:
      enable: false
      secretName: ""
      wildcardSecretName: ""
```

However, in this environment, Caddy-Ingress output the following error

```
$ kubectl logs -f -n caddy-system caddy-ingress-caddy-ingress-controller-c54c8d644-62cwq

~~~

{"level":"error","ts":1683804895.382807,"logger":"http.log.error","msg":"dial tcp 100.68.148.152:0: i/o timeout","request":{"remote_ip":"100.96.0.1","remote_port":"49403","proto":"HTTP/2.0","method":"GET","host":"dev.example.com","uri":"/setup","headers":{"Accept-Language":["ja,en-US;q=0.9,en;q=0.8"],"Cookie":[],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Site":["same-origin"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Sec-Ch-Ua-Platform":["\"Windows\""],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"],"Accept-Encoding":["gzip, deflate, br"],"Cache-Control":["max-age=0"],"Sec-Ch-Ua":["\"Google Chrome\";v=\"113\", \"Chromium\";v=\"113\", \"Not-A.Brand\";v=\"24\""],"Sec-Ch-Ua-Mobile":["?0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Sec-Fetch-Dest":["document"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"dev.example.com"}},"duration":3.000765467,"status":502,"err_id":"kbj3p3eff","err_trace":"reverseproxy.statusError (reverseproxy.go:1196)"}
```

So I turned to Coder's Ingress resource and changed the backend port from name: http to number: 80.

```yaml
$ kubectl edit ingress coder -n coder

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: coder
    meta.helm.sh/release-namespace: coder
  creationTimestamp: "2023-05-11T11:25:03Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: coder
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coder
    app.kubernetes.io/part-of: coder
    app.kubernetes.io/version: 0.23.2
    helm.sh/chart: coder-0.23.2
  name: coder
  namespace: coder
  resourceVersion: "386481"
  uid: 304ace41-f813-436a-9a39-a929a4f5ceef
spec:
  ingressClassName: caddy
  rules:
  - host: dev.example.com
    http:
      paths:
      - backend:
          service:
            name: coder
            port:
              number: 80  ### Change from name: http to number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: xxx.xxx.xxx.xxx
  ```

Then no error occurred at Caddy-Ingress and I was able to access Coder via Caddy-Ingress. Is this a bug? Or am I misconfigured?

If it is a bug, I hope you can fix it.

P.S. I apologize for using DeepL and writing in English.

**Comment by matifali** [comment]
cc: @johnstcn

**Comment by johnstcn** [comment]
@MuNeNICK I'm assuming that you're using https://github.com/caddyserver/ingress as your ingress controller? What version of this ingress controller are you using?

I have no issues with using `name: http` while using the `traefik` ingress controller (tested on k3s version 1.26.4).

**Comment by MuNeNICK** [comment]
> @MuNeNICK I'm assuming that you're using https://github.com/caddyserver/ingress as your ingress controller? What version of this ingress controller are you using?
> 
> I have no issues with using `name: http` while using the `traefik` ingress controller (tested on k3s version 1.26.4).

The latest version of caddy-ingress-controller-1.0.4 is used.

**Comment by MuNeNICK** [comment]
@johnstcn I have since rebuilt Coder and Caddy-Ingress, etc., but it still does not work on `name: http`. Any new updates to this?

**Comment by johnstcn** [comment]
@MuNeNICK I can't reproduce this behaviour with the same software versions (Caddy ingress controller v0.1.4, Coder Helm chart v0.23.2).

The only difference in my case is that I am using MicroK8s with MetalLB (Ubuntu 20.04). 

I note that the error you provided from the Caddy ingress controller reported `"status":502` from the backing Coder service. By default, the ingress controller reverse proxies to the Kubernetes service URL (https://github.com/caddyserver/ingress/blob/v0.1.4/internal/caddy/ingress/reverseproxy.go#L34) instead of to the Pod IP directly (note the TODO).

In order to reproduce this error we would probably need to know, at minimum:
- Kubernetes Host OS
- Kubernetes version and flavour
- Kubernetes CNI plugins in use

Can you reproduce this issue with a different ingress controller?

**Comment by MuNeNICK** [comment]
I am using VMware's Tanzu Kubernetes Grid 2.1 and NSX Advanced Load Balancer to build my environment.

- Kubernetes Host OS: PhotonOS 3
- Kubernetes version and flavour: 1.24.10
- Kubernetes CNI plugins in use: Antrea (v1.7.2)

It also worked fine with L7 Ingress on NSX ALB as another Ingress Controller; it is not working with Caddy-Ingress only.

**Comment by bpmct** [comment]
This seems like a bug in the Caddy ingress controller, but it's strange we can't reproduce. Are you able to deploy other software via Helm using the Caddy ingress controller OK?
