### ISSUE TITLE
feat(cli): allow owner to create workspace for another user

### ISSUE THREAD

**Issue by matifali** [coder/coder#7493]
From the dashboard, an owner can create a workspace for any user. How can we do that from cli?
`coder create --help` does not show any option to specify the owner
```console
Usage: coder create [flags] [name]

Create a workspace

Options
      --parameter-file string, $CODER_PARAMETER_FILE
          Specify a file path with parameter values.

      --rich-parameter-file string, $CODER_RICH_PARAMETER_FILE
          Specify a file path with values for rich parameters defined in the
          template.

      --start-at string, $CODER_WORKSPACE_START_AT
          Specify the workspace autostart schedule. Check coder schedule start
          --help for the syntax.

      --stop-after duration, $CODER_WORKSPACE_STOP_AFTER
          Specify a duration after which the workspace should shut down (e.g.
          8h).

  -t, --template string, $CODER_TEMPLATE_NAME
          Specify a template name.

  -y, --yes bool
          Bypass prompts.

```

**Comment by alexander-dammeier** [comment]
To stop and update workspaces, the name of the workspace can be given as `user/workspace-name`. Maybe that could also be used to create workspaces? Something like `coder create -t templateName user/workspace-name`?

**Comment by Emyrk** [comment]
Currently this is hard-coded to `Me`

https://github.com/coder/coder/blob/6d2079d7657b8c99f41b48fdf26f4884d3dea49d/cli/create.go#L146-L146

I think an `owner` flag is appropriate :+1:

**Comment by matifali** [comment]
Or instead of using `--create` flag, we can use `user/workspace` notation for the workspace name, if no user is provided, then default to using me.
