### ISSUE TITLE
feat: prevent user from changing a parameter passed from Open in Coder

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7505]
Version: [`v0.23.2+0755ff3`](https://github.com/coder/coder/commit/0755ff32ef8d37864740a24a7673e172ae016af3)

The current Open in Coder solution just passes parameter values like a repo name from a repo's Open in Coder button to the Create Workspace UI, where a user can change the value.

The docs show an immutable parameter example but that is only after the workspace is built.

A DevOps or Engineering leader who expect this repo parameter to not be tampered with - from the get go.

Optimally, I'd imagine showing the repo, but grayed out and un-editable.

Versus this:

<img width="639" alt="image" src="https://github.com/coder/coder/assets/2022166/71806787-7f62-4f5d-9a21-058b669f3a6b">

@BrunoQuaresma @bpmct

**Comment by bpmct** [comment]
huge fan of us doing this :)

**Comment by BrunoQuaresma** [comment]
Hm... since the users, where most of them are developers, can change that in the URL even if we disable the input, I don't see too much value honestly.

**Comment by bpmct** [comment]
The value isn't that people are "forced" to use specific parameters, but that a developer doesn't need to think about/confirm the parameters. Especially if the user is unfamiliar with Coder and the template is used for many different repos. Having it preconfigured brings it a lot quicker to "click button -> get workspace" without having to worry about a bunch of values
