### ISSUE TITLE
Why does Coder warn on workspace update but not restart?

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7511]
Version: [`v0.23.2+0755ff3`](https://github.com/coder/coder/commit/0755ff32ef8d37864740a24a7673e172ae016af3)

It seems the same conditions apply on restart as with update, regarding this message.

Restart does not prompt the user and also, in this case, kills the Kubernetes pod and creates a new one, so anything non-persistent is gone, besides a persistent volume.

Also the text of the message seems too long.

![image](https://github.com/coder/coder/assets/2022166/c717e6b7-cc1d-4685-b684-64bf9875ce33)

My vote is warn once, with a checkbox, `Do you want to see this warning again` or something to that effect.

**Comment by matifali** [comment]
Yes and we should add the same to Restart also. @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
I like that, since we don't have a "preferences" feature in the BE yet, we could storage that in the local storage. Sounds good?

**Comment by matifali** [comment]
With local storage it will be only saved for the current device and browser. Right?
Here I see 2 different things. 
1. Enable double conformation for workspaces restart similar to update. 
2. Proovide a way to allow the users to disable the confirmation dialogue (using local storage) or something that works across all devices. It can be a an account wide setting when we will finally have user account preferences/env variables/secrets.


I would like to have some @bpmct thoughts here.
