### ISSUE TITLE
agent: hanging "bash -l" processes

### ISSUE THREAD

**Issue by mtojek** [coder/coder#7512]
Related: https://github.com/coder/coder/issues/6724

I'm researching options to collect metrics from SSH sessions, and while playing with coder I spotted an issue. 

<img width="552" alt="Screenshot 2023-05-12 at 15 03 18" src="https://github.com/coder/coder/assets/14044910/3f6ed260-1b5c-4378-aa40-41d1fde762c9">

1. Click on the "Terminal" button, wait for the prompt, close the window.
2. Repeat that multiple times.

Now there are multiple processes hanging:

<img width="710" alt="Screenshot 2023-05-12 at 15 03 11" src="https://github.com/coder/coder/assets/14044910/69082281-e101-43f7-b675-f81d7dc1ac8c">

Is this an expected behavior or missight?

**Comment by mtojek** [comment]
It is ~15 minutes since I triggered them, and I can still see them.

**Comment by mtojek** [comment]
I investigated more and it looks like UI doesn't preserve the `reconnect` parameter hence every time a new PTY is created. With a new `reconnect` hash, the new terminal is created. I don't know what was the original intention here. Maybe @BrunoQuaresma knows?

**Comment by BrunoQuaresma** [comment]
But of course, we can enforce one PTY for an agent if it works best but I would get some @bpmct thoughts before

**Comment by coadler** [comment]
Potentially related: https://github.com/coder/coder/pull/7196

I made this change hoping it would fix some reported random SSH disconnects. I noticed in Tailscale they used a similar setting for their SSH conns: https://github.com/tailscale/tailscale/blob/4664318be2aad7dbea9a1b16ddf24c7c5efcb395/wgengine/netstack/netstack.go#L882-L888
