### ISSUE TITLE
CODER_ACCESS_URL usage

### ISSUE THREAD

**Issue by hannamtt** [coder/coder#7516]
Hello,

I want to use coder just with me as a user in a work environment, I can't use it in tunnel mode for security reasons, but when I try to set CODER_ACCESS_URL none of the URLs I try to use work. when I go to the link I assigned to CODER_ACCESS_URL it's like the server does exist and my browser says the site can't be reached. I've tried the following CODER_ACCESS_URL values
http://0.0.0.0
http://0.0.0.0:3000
http://0.0.0.0:4000
http://dnsnameOfServer
http://dnsnameOfServer:5000
http://dnsnameOfServer:6000
http://dnsnameOfServer.coder
as well as https for all of the above. I'm not using a load balancer since I'm the only one using this server. is there a way to make coder work in this situation? If so, what am I doing wrong? 

thanks in advance

**Comment by ericpaulsen** [comment]
hi @hannamtt - thank you for opening this issue.

the `CODER_ACCESS_URL` should either be an accessible IP address of the server running Coder or a fully qualified domain name that resolves to said IP.

by default, Coder listens on port `3000` of the server. so can you try setting your access URL to `http://<dns-name>:3000`?

**Comment by hannamtt** [comment]
@ericpaulsen i tried both `http://<dns-name>:3000` and 'http://<ip-address>:3000' now with no luck

**Comment by ericpaulsen** [comment]
@hannamtt how are you running the server, and can you provide your Coder environment variables?

**Comment by hannamtt** [comment]
my last attempt looked like this

`# Coder must be reachable from an external URL for users and workspaces to connect.
# e.g. https://coder.example.com

#CODER_HTTP_ADDRESS=0.0.0.0:80

# Enable TLS and listen on port 443)
#CODER_TLS_ENABLE=true
#CODER_TLS_ADDRESS=0.0.0.0:443

## Redirect from HTTP to HTTPS
#CODER_TLS_REDIRECT_HTTP=true

CODER_ACCESS_URL="http://<ip_address>:3000"`
with the acutall ip address ofcourse

**Comment by ericpaulsen** [comment]
Ah, so you have Coder listening on port 80, as defined with your CODER_HTTP_VARIABLE.

So your access url should just be http://<IP>:80

**Comment by hannamtt** [comment]
do you mean `CODER_HTTP_ADDRESS`? that line is actually commented out as is all the other lines with # in the `/etc/coder.d/coder.env` file

**Comment by hannamtt** [comment]
It sounds like mayber your saying CODER_HTTP_ADDRESS and the CODER_ACCESS_URL need to use the same address and port? ive done that and it seems to work. thank you!

**Comment by matifali** [comment]
Glad that you have found the solution. Closing as completed.
