### ISSUE TITLE
Allow setting template metadata e.g. icon, description while creating a new template with `coder create/push`

### ISSUE THREAD

**Issue by ElioDiNino** [coder/coder#7524]
When creating or updating a Coder template through the CLI I would like to be able to update the user-facing information of the template (name, description, and icon) but there seems to be no way to do this. This is especially important for centralizing everything if an organization stores all of their templates on a repository and uses the CLI with a script to sync the templates to Coder.

**Comment by ElioDiNino** [comment]
I figured out this can be done with the `coder templates edit` command but it would still be nice to have some of these flags accessible when creating and updating templates. Since they already exist, it shouldn't be too much work to copy them over.

**Comment by matifali** [comment]
Related to #9318
