### ISSUE TITLE
Login through Coder CLI

### ISSUE THREAD

**Issue by ElioDiNino** [coder/coder#7535]
Currently `coder login <url>` requires you to login through the browser. It would be nice to have `--user-email string` and `--user-password` flags to be able to pass in the information through the command line primarily for use by scripts. The alternative is obviously using tokens but this is still a manual process for scripting purposes since they expire and so need to be replaced semi-frequently.

**Comment by sharkymark** [comment]
@ElioDiNino you can create a long-lived token with CLI and reuse it:

`coder --url <your access url> --token <your token> login <your access url> `

**Comment by ElioDiNino** [comment]
Yes but is there a way to create a token that never expires? I don't see any documentation [here](https://coder.com/docs/v2/latest/cli/server#--max-token-lifetime) for setting the limit to not exist.

**Comment by sharkymark** [comment]
Our ideal customer profile tends to be very large accounts who do not like that. I think what I shared should get you going, e.g., create a 1 year token.

**Comment by ElioDiNino** [comment]
> Our ideal customer profile tends to be very large accounts who do not like that. I think what I shared should get you going, e.g., create a 1 year token.

I agree that I do not want to create a token that doesn't expire. Hence the feature request to be able to login through the CLI to avoid this.

**Comment by ammario** [comment]
How is a token that doesn't expire less secure than username/password? I'm hesitant to implement this feature because scripts shouldn't break when passwords change, and we will eventually add support for tokens with restricted scopes.

**Comment by ElioDiNino** [comment]
I never said it was less secure. A token that doesn't expire is fine if properly managed by the organization (using a secret vault), but it seems this is not an option to create. This only leaves me with the option of logging in through CLI which I agree probably shouldn't be raw text through flags for password, but there should be some way that is secure and that can be easily filled out by a script so that this info can be stored in an org's vault instead of a token that never expires (since again, a token like this can't be created).

**Comment by ammario** [comment]
> but it seems this is not an option to create.

I assume you mean there's not an option in Coder to create such tokens, not that your organization disallows them.

Our product is unclear, but we do support an essentially unlimited lifetime by specifying a duration of `876600h0m0s` (100 years).

Related: https://github.com/coder/coder/issues/7539
