### ISSUE TITLE
docs: create a firewall page

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#7542]
# Description

As we are using coder in an protected environment we faced some issues as not all URLs are reachable.

# Solution

Please provide a new page or chapter with the following URLs:

- code-server.dev (install via AUR)
- open-vsx.org (optional if someone would use code-server)
- registry.terraform.io (to create and push template)
- v2-licensor.coder.com (developing Coder in Coder)

**Comment by matifali** [comment]
@bpmct What do you think about adding a list of domains to [Offline deployments docs](https://coder.com/docs/v2/latest/install/offline)?

**Comment by bpmct** [comment]
> @bpmct What do you think about adding a list of domains to [Offline deployments docs](https://coder.com/docs/v2/latest/install/offline)?

That's a great idea!
