### ISSUE TITLE
Linked Accounts support for user preferences section

### ISSUE THREAD

**Issue by misskniss** [coder/coder#756]
As a developer, I want support for linked accounts in the back end so I can plumb it into the user preferences section. 

<img width="884" alt="Linked Accounts section from V1" src="https://user-images.githubusercontent.com/2394436/160977901-814998c5-c49f-42f0-be3c-35f57da3f1c3.png">

**Comment by tjcran** [comment]
Closing this one. We may need another solution when we add more account linking for Git or Auth, but that will come up organically in new issues.
