### ISSUE TITLE
Linked Accounts section for user preferences

### ISSUE THREAD

**Issue by misskniss** [coder/coder#757]
As a user, I want a section in my preferences where I can see and link my accounts. 

<img width="884" alt="Linked Accounts section from V1" src="https://user-images.githubusercontent.com/2394436/160978051-6f092410-5dce-40a6-861a-9cc4c4ca9199.png">

**Comment by tjcran** [comment]
Closing this because it will come along with any work that happens if we decide to support "linked accounts" in this way.
