### ISSUE TITLE
Disable Password Authentication - Owner Sign In

### ISSUE THREAD

**Issue by ttauchen** [coder/coder#7580]
### Documentation states:

_--disable-password-auth_  

> Disable password authentication. This is recommended for security purposes in production deployments that rely on an identity provider. **Any user with the owner role will be able to sign in with their password regardless** of this setting to avoid potential lock out. If you are locked out of your account, you can use the coder server create-admin command to create a new admin user directly in the database.

### My question: 
How is the owner able to sign in regardless? I would like to do so, but can't figure out how.

**Comment by bpmct** [comment]
@ttauchen - sorry we missed this! The ideal flow at this point would be:

1. User sets up owner account when they first deploy Coder
2. User sets up [OIDC or GitHub authentication](https://coder.com/docs/v2/latest/admin/auth#group-sync-enterprise)
3. User promotes an OIDC user to an Owner
4. User disables password auth and deletes the builtin account

If the identify provider has an outage, you can re-create the builtin account: https://coder.com/docs/v2/latest/cli/server_create-admin-user

With role sync #7470, there may be a future where a Coder deployment can be set up with OIDC and leverage the identity provider to set roles (no need to set first user).
