### ISSUE TITLE
Rich Parameter validation is skipped if min or max is 0.

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#7582]
If you set `validation.min` or `validation.max` to 0 in a rich parameter, we skip validation.

This makes it impossible to correctly enforce a parameter range where 0 is the min or max, e.g. 0-9.

Spotted during a code read:

https://github.com/coder/coder/blob/e951778147c28289cfae32b4a38bc873c98cbbfa/codersdk/richparameters.go#L112

Unfortunately this needs to be resolved at the protobuf / data persistence layer, since we only store the min and max, and not whether either or both were explicitly set in the terraform.

cc @mtojek

**Comment by mtojek** [comment]
Thanks for linking the source code. It is a valid concern. As a short-term mitigation, we can modify the condition:
`(param.ValidationMin == 0 && param.ValidationMax != 0) || (param.ValidationMin != 0 && param.ValidationMax == 0)`

It won't cover the edge case Min = Max = 0, but it seems to be rare. Do you think that it is worth applying it in your PR, @spikecurtis?

Nevertheless, I agree that the proper fix requires changes in the persistence layer (nullable column).

**Comment by mtojek** [comment]
> I think we should just do the proper fix in a separate PR and not absorb it into the one I'm currently working on.

👍 

Fortunately, the fix should not have implications on the API compatibility (`/rich-parameters`) as ValidationMin and ValidationMax have `omitempty` annotation in:

```go
	ValidationMin        int32                            `json:"validation_min,omitempty"`
	ValidationMax        int32                            `json:"validation_max,omitempty"`
```

**Comment by mtojek** [comment]
FYI: I'm working on fixing this issue.

> However, (param.ValidationMin == 0 && param.ValidationMax != 0) || (param.ValidationMin != 0 && param.ValidationMax == 0) has the drawback that it's hard express a min without a max or vice versa, e.g. v >= 0.

The problem has its roots in the [terraform-provider-coder](https://github.com/coder/terraform-provider-coder/blob/main/provider/parameter.go#L279), which assumes that both properties (`min` and `max`) come together.

**Comment by mtojek** [comment]
Resolved in https://github.com/coder/terraform-provider-coder/pull/122

**Comment by mtojek** [comment]
I'm afraid that I found another issue. When terraform is resolving the plan it ends up with zero-populated values, which is odd as `parameterDataSource()` fixes all zero -> nil values.

Fragment of the .tfplan file:

```json
{
            "address": "data.coder_parameter.compute_instances_7",
            "mode": "data",
            "type": "coder_parameter",
            "name": "compute_instances_7",
            "provider_name": "registry.terraform.io/coder/coder",
            "schema_version": 0,
            "values": {
              "default": "3",
              "description": "Let's set the expected number of instances.",
              "display_name": null,
              "icon": "/icon/rubymine.svg",
              "id": "a7564661-442f-4ee6-a3d0-49fcdda08839",
              "legacy_variable": null,
              "legacy_variable_name": null,
              "mutable": true,
              "name": "Compute instances",
              "option": null,
              "optional": true,
              "type": "number",
              "validation": [
                {
                  "error": "",
                  "max": 8,
                  "min": 0,
                  "monotonic": "increasing",
                  "regex": ""
                }
              ],
              "value": "3"
            },
            "sensitive_values": {
              "validation": [
                {}
              ]
            }
          }
``` 

I'm investigating it.

BTW Is that what you meant @mafredri?
