### ISSUE TITLE
feat: Like v1, have roles at the group-level (v1 are organizations)

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7633]
Version: [`v0.23.5+ef2411e`](https://github.com/coder/coder/commit/ef2411ef1709ca2e9577bc6294c2edbd9b3a0ec1)

A prospect/enterprise would like a group-level template admin role, so a user in that role can see and administer all templates in that group.

Coder v2 has either a site-wide template admin or a template-level admin, who actually cannot create templates only administer them.

As a result, this enterprise will have to set up multiple deployments of Coder with separate license files.

Another existing customer comes to mind who has a lot of organizations in v1, with various roles to add images, only use images, add registries, etc.

**Comment by ammario** [comment]
There are two ways I think we can solve this:
1. Create a concept of template groups that each have their own provisioner pool so they can be securely isolated from eachother.
2. Build out the concept of organizations / multi-tenancy, with each organization having it's own provisioner pool.

**Comment by sharkymark** [comment]
Another concern is one of current customers had us create a new role in Organizations to prevent them from touching infrastructure, but a template admin can modify resources, requests, etc.
