### ISSUE TITLE
Encrypt OIDC access token in database

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#7640]
Users' OIDC access tokens are currently stored in plaintext in the Postgres DB. Given the sensitivity of these tokens, we would prefer if they were stored encrypted.

For our deployment, it would work fine to manage the encryption key outside of Coder in an existing secrets manager and pass it in via a file path or directly inside an environment variable.

**Comment by johnstcn** [comment]
Original PR: https://github.com/coder/coder/pull/7959

**Comment by johnstcn** [comment]
Broke this up into two PRs for ease of review:
- https://github.com/coder/coder/pull/9421
- https://github.com/coder/coder/pull/9433
