### ISSUE TITLE
`--disable-password-auth` is useless when using Coder in a headless fashion

### ISSUE THREAD

**Issue by ammario** [coder/coder#7657]
From [szab100](https://github.com/szab100) in https://github.com/coder/coder/discussions/7638#discussioncomment-5982299

> One suggestion though is that we found `--disable-password-auth` to be useless, since it blocks user management via the API when enabled. The workaround is that we create users with long, generated passwords that we never share with them. Our suggestion is that instead of making it org-scoped, make it even more flexible by making it user-scoped, eg allow creating users with disabled passwords and/or disable password for already existing users (through API / CLI / UI).

**Comment by Emyrk** [comment]
Here is the code in question that blocks user administration. 

https://github.com/coder/coder/blob/0999db0fadb673c7a58b95b684e54957edffdae5/coderd/users.go#L288-L295

**Comment by ammario** [comment]
I wonder if there's a way we could satisfy the use case without adding another knob. Maybe we could just allow users to be created without passwords when `disable-password-auth` is set?

**Comment by Emyrk** [comment]
The thing about `no password` is that then the condition for all password auth related things is:

```golang
if user.LoginType == database.LoginTypePassword && user.HashedSecret == "" {
   // No password set
}
```

Mainly I am thinking that if a user is created without a password, actions like "reset password" should fail.

All password interactions should fail.

`LoginTypeNone` is another knob, but it is also another authentication mode for a user. So I think it is valid.

**Comment by ammario** [comment]
Ok. Sounds good to me.

**Comment by Emyrk** [comment]
@ammario thoughts on https://github.com/coder/coder/issues/8011?
