### ISSUE TITLE
New templates purposely with no permissions (RBAC)

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7658]
A customer reported a suggestion to allow new templates have no RBAC (groups).

Existing state is the Everyone group is attached to any new template.

This is a very good enterprise suggestion akin to zero trust then add permissions later.

**Comment by matifali** [comment]
I am totally in support.
I invited a guest to my deployment and permitted them to view only one template
Later when I added a new template, the invited user, by default, could see and use that which I did not want. So I had to adjust the permissions manually.

**Comment by ammario** [comment]
We should definitely change our default behavior.

**Comment by Emyrk** [comment]
One annoying issue with this is that AGPL does not have the group feature, so if we make the default to exclude "everyone", then only admins can see templates on AGPL deployments.

This is where the default code lives now for "everyone" can read:
https://github.com/coder/coder/blob/5296e1a8d6398c9ea0b7bee6481c80f3712237d9/coderd/templates.go#L290-L292

----

I prefer not to add more args, but we could add an arg to the create to set the initial permissions. Then we can put the default behavior on the caller, and allow the FE/cli to control things.

**Comment by ammario** [comment]
@sreya @bpmct met this morning and discussed this issue.

We think that in any sizeable deployment both "everyone has access" and "everyone has no access" are useless modes and the creator would immediately change permissions following create. Thus, if a deployment has template RBAC enabled we should prompt them to configure permissions in the create flow.

**Comment by Emyrk** [comment]
@ammario just to confirm, 

> configure the permissions in the create flow

The create flow being the `create template` flow correct?

![Screenshot from 2023-06-09 12-58-54](https://github.com/coder/coder/assets/5446298/2663633a-b952-45c7-970b-0b6df44c61e0)

**Comment by ammario** [comment]
Yeah that was the idea. Not sure how it should look visually.

**Comment by Emyrk** [comment]
I'll consult with @BrunoQuaresma on looks :+1:

**Comment by Emyrk** [comment]
@BrunoQuaresma Yes, or we just have a checkbox for the "allow everyone", and say a message like, "if you create this without everyone access, no one can use it until you edit the permissions on the template page".

But ideally some way to add groups/users on this page probably :thinking:

**Comment by BrunoQuaresma** [comment]
I like the first one, is easier and should solve the issue. We can get the one I mentioned if users ask for that.

**Comment by Emyrk** [comment]
@BrunoQuaresma I will make the backend api change to add a boolean field that disables usage by the "everyone group". 

If we need to expand this later, we can add fields for adding specific users/groups

**Comment by BrunoQuaresma** [comment]
For the FE, if you want to do, you can just copy and paste the checkbox section we already have on that page and update the copy. Let me know if you need any help from me.

**Comment by Emyrk** [comment]
I'll do that!
