### ISSUE TITLE
allow changing the icon of workspace

### ISSUE THREAD

**Issue by matifali** [coder/coder#7666]
If I have multiple workspaces created from the same template, I would like to change the icon for each of them to identify them better,

1. Add to the dashboard
2. Add to cli `coder create MY_WORKSPACE --template MY_TEMPLATE --icon <linkurl>.svg[png]`

cc: @BrunoQuaresma @bpmct

**Comment by BrunoQuaresma** [comment]
It is a good suggestion! Just removing the assignment because it needs the BE work to be done first before we add it into the UI. Up to Ben to decide the priority tho.

**Comment by bpmct** [comment]
I'm not sure how I feel about workspaces having different icons from their parent template. The icon is a good visual identifier of which template is being used... 🤔 

I think perhaps we table this for now. @kylecarbs - curious if you have thoughts

**Comment by kylecarbs** [comment]
I don't think workspaces should have different icons. It sounds confusing.

**Comment by matifali** [comment]
Ok. As we have decided to not have workspace icons as the current icon is an indication of parent template. Can we remove the template name column or make it a subheadings under workspace name? It's taking a lot of screen area while not giving any extra information.
