### ISSUE TITLE
Add a new command `coder vscode` to cli to open vscode

### ISSUE THREAD

**Issue by matifali** [coder/coder#7667]
Add a new command to cli to open vs code fom cli,

It can make use of `$CODER_AGENT_URL`, and we can further add
`$CODER_AGENT_NAME`, `$CODER_WORKSPACE_NAME`, `$CODER_USERNAME` and `$CODER_SESSION_TOKEN`
Then a new command like `coder vscode` from a directory should be able to open vscode using the vscode URI.

Additionally, we can allow vscode-insiders too with `coder vscode-insiders`

```bash
vscode://coder.coder-remote/open?owner={$CODER_USERNAME}&workspace=${CODER_WORKSPACE_NAME}&url=${CODER_AGENT_URL}&token=${CODER_SESSION_TOKEN}&agent=${CODER_AGENT_NAME}&folder=$(pwd)
```
cc: @bpmct, @kylecarbs, @mafredri 
Feedback is welcomed.

**Comment by kylecarbs** [comment]
This should be super easy to add using the same mechanism we do from the dashboard!

**Comment by matifali** [comment]
should we label it with good-first-issue?
I can do this but I am confused about how to make available the required new variables inside the workspace. I want it to be 1 click so that the user should not have to login again inside the workspace. 
We need
1. agent name
2. user name
3. session token
4. workspace name

**Comment by mafredri** [comment]
I made a prototype of this in Bash for personal use, can be used for inspiration or whilst waiting for this feature to be implemented natively.

Script: [vscoder.sh](https://github.com/coder/coder/files/12378927/vscoder.txt)

(Note: This script does not login either CLI or vscode extension, that needs to be done separately.)

Things to consider for `coder vscode` and/or `vscode-coder` extension:

- We won't know the agents or default directory until the workspace is started and an agent is running, so the command should first start the workspace and wait for the agent to call in (vscode extension can start it automatically, but lands in the wrong directory)
- For insiders, let's use `coder vscode --insiders`
- It'd be nice to include `home_directory` in coder agent responses, support e.g. `~/folder` or `folder` (relative) paths

**Comment by matifali** [comment]
@mafredri Initially, if we can only get vscode, it would be nice.
And with the new suggestion
`coder vscode` could be an alias of `coder open vscode`

**Comment by matifali** [comment]
Hi @mafredri, is this still planned?

**Comment by mafredri** [comment]
Ah, thanks for asking, this one fell off the radar when I switched focus to scaletesting, I'll try to sneak it in 😉.
