### ISSUE TITLE
Inconsistent Value Update for ``coder_parameter`` Option in Templates

### ISSUE THREAD

**Issue by LordChunk** [coder/coder#7683]
When you update a value for a ``coder_parameter`` option with the, it does not update the values for templates which use that option with a matching name when you update the template. This then causes your validation to fail, which makes it impossible to upgrade your template.

Here's an example to reproduce my issue:

main.tf
```
...

data "coder_parameter" "image {
   name = "Base image"

  option {
    name = "ubuntu"
    value = "ubuntu:bionic"
  }
}

...
```

Deploy a template with this value and create a workspace. 
Then, update the template with a changed value e.g.

```
...

data "coder_parameter" "image {
   name = "Base image"

  option {
    name = "ubuntu"
    value = "ubuntu:focal"
  }
}

...
```

After updating the template, you should not be able to update your workspace and get the following error: ``parameter value must match one of options: [ubuntu:focal]``.

**Comment by LordChunk** [comment]
Is this intended behaviour? Because in that case I would prefer a workaround/solution that doesn't require me to update every workspace separately with a command and changing parameters.

**Comment by mtojek** [comment]
Partially it is. Consider a user who would like to stick with bionic, but a silent template update forces them to switch to focal. It is definitely unintended.

If you want to switch your workspace users automatically, maybe it is better to pick [managed template variables](https://coder.com/docs/v2/latest/templates/parameters#managed-terraform-variables), so that they don't have control over it?

**Comment by LordChunk** [comment]
That doens't really help in my situation. The problem that I have is as follows: I update my template when I have a new version available of a docker image which I use as my base image in my workspace ([this](https://vscode.dev/github/LordChunk/coder-ide-baseline/blob/main/template/main.tf#L136) is my template for contex).  
  
When I update my template I change the \`\`sha256\`\` hash to the one matching the latest image. I would've preferred to simply use \`\`:latest\`\` for this. This would require me to stop all the workspaces running on Docker to then remove and pull the latest image.

**Comment by ericpaulsen** [comment]
related: https://github.com/coder/coder/issues/7442

**Comment by matifali** [comment]
I am closing this as stale. Please reopen if you need further assistance.
