### ISSUE TITLE
The port forwarded by the code-server editor cannot be accessed in the browser

### ISSUE THREAD

**Issue by weisiqian** [coder/coder#7698]
I wrote a simple html file, and then ran an http service in coder-server. When I accessed my http service through the port forwarded by code-server, I found that it could not be accessed in the browser.

![image](https://github.com/coder/coder/assets/19994951/c3292b59-d1e4-4c6e-a2c6-e35bfafc61e4)

**Comment by matifali** [comment]
Hi, @code-asher is this related to https://github.com/coder/code-server or https://github.com/coder/coder?

**Comment by code-asher** [comment]
code-server uses Coder's proxy when it is available so I think 
this is an issue on the coder/coder side.

Is port forwarding properly configured?  We should see a "port 
forward" button in the dashboard if it is.

https://coder.com/docs/v2/latest/admin/configure#wildcard-access-url
