### ISSUE TITLE
idea: database: customize sqlc generated code

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#7716]
# Problem:

We do a lot munging of code generated by sqlc (see: https://github.com/coder/coder/blob/main/coderd/database/generate.sh)

@kylecarbs found that SQLC uses its own internal template (https://github.com/kyleconroy/sqlc/blob/main/internal/codegen/golang/templates/pgx/queryCode.tmpl). We could potentially look into forking sqlc and customizing the template to meet our preferences.

This would also be useful for the case where we want to slip in a couple of lines of code into the database methods

e.g.
* Adding metrics (alternative: wrap and implement the entire interface)
* Enforcing authz (alternative: as above)

**Comment by Emyrk** [comment]
I talked with the SQLc guys. One thing they are considering is a macro language in SQLc. No promises, but that would be very cool.

As for the metrics part, I think how we have it is best. Our layered solution does create more LoC, but it keeps concerns separated.
