### ISSUE TITLE
open on coder button without subbmitting the form

### ISSUE THREAD

**Issue by atnomoverflow** [coder/coder#7717]
is it possible to add and endpoint for create worksapce from a template by passing querry so that the user won't have to submit the form also would be nice to check if there is any workapce with the same name if there's it will open the vscode or whatever the template configure this way we wont have to wait for an integration like gitpods

**Comment by MrPeacockNLB** [comment]
We want this feature too, as we pre-fill all needed fields. As far as I know there is currently no way to auto-submit this.

- We've implemented a "Coder Button" like GitPod
- We want to start a Workspace this directly this way @atnomoverflow it is possible to set the name of the workspace already. See https://github.com/coder/coder/commit/ad9a29dfa69176d15996f9f8325ab0aa03fe2ebd . All needed Information for the template are there. So in this case there is no need to manually approve this settings through the user.

**Comment by BrunoQuaresma** [comment]
I think this is a good request. I'm wondering if we could just add a param in the URL like `?skip-form=true` so the app could understand it is ok to use the provided values directly. Does it work for you all?

**Comment by LAX18** [comment]
It would be beneficial to work in a check to ensure that all the required parameters are set before creation. Unsure how that would work into the workflow. Some organizations may also want to disable such a feature additionally.

**Comment by atnomoverflow** [comment]
then how about making it only possible for the git provider added like adding check to the request header to make sure it's comming form reliable source

**Comment by MrPeacockNLB** [comment]
I think this should be no problem @BrunoQuaresma . The default should be **false** so auto committing is off and has no impact for other.

**Comment by BrunoQuaresma** [comment]
cc.: @bpmct

**Comment by bpmct** [comment]
Totally agree we should do this. My main open questions/things that need a design are:

1. `?skip-form=true` is added and no workspace name is specified, how do we generate one?
  - My main suggestion would be to generate them like we generate template versions, although we may need to change the validation
2. What will happen if a field validation error occurs?
3. What will happen if the workspace name in the URL string is too long?
  - Perhaps we truncate
5. What will happen if the workspace name in the URL string is taken?
  - Perhaps we append a `_1`?

Nothing super complex, but my main questions about how this would work :)

**Comment by LAX18** [comment]
Also please redirect me if it requires a separate issue. When using the open on coder button, and a login is required, the previous URL is discarded requiring the user to go back to the previous page and press it again. Could be prevented with a callback URL.
