### ISSUE TITLE
The ability to change icon and text in the Git provider.

### ISSUE THREAD

**Issue by Smallinger** [coder/coder#7726]
Hello everyone, first of all, I would like to thank you for this awesome project, it's incredibly cool.

I wanted to ask if it is possible to define the text and icon for the Git provider in the template creation by myself. 
I mean this here:
![image](https://github.com/coder/coder/assets/8080568/18d7a775-5bf1-495c-a1ed-4ca09be46a95)

**Comment by kylecarbs** [comment]
Totally doable! We already do this for other things, so the precedent exists.

**Comment by Smallinger** [comment]
Ok, that's really cool! Thank you for the information!

**Comment by kylecarbs** [comment]
Oh, sorry to confuse. This doesn't exist yet! I was just acknowledging that we should do it.

**Comment by Smallinger** [comment]
Oh, no worries! I understand now. It's totally fine that it doesn't exist yet. It would indeed be awesome if you or anyone could make it happen in the future!

**Comment by matifali** [comment]
@kylecarbs don't we already have this?

**Comment by kylecarbs** [comment]
@matifali nah, you can't currently customize the appearance of the git provider.

**Comment by matifali** [comment]
Closing in favor of #8792.

**Comment by Smallinger** [comment]
@matifali i think you mean #8791 ?
