### ISSUE TITLE
Default value does not come through in CLI with new template variables in 0.22.2

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#7728]
Sorry if this is fixed in later versions or I missed the issue for this. We're going to upgrade but just waiting for 0.24.X to drop for some specific scheduling features.

When creating a workspace from the CLI the default values don't come through:

```
> Specify a name for your workspace: dev1
Select a template below to preview the provisioned infrastructure:

  This template has customizable parameters. Values can be
  changed after create, but may have unintended side effects
  (like data loss).

Docker Image
  Docker image for the development container

> Enter a value:
parameter value is required
> Enter a value:
parameter value is required
```

Template:

```
data "coder_parameter" "docker_image_name" {
  name        = "Docker Image"
  mutable     = true
  type        = "string"
  description = "Docker image for the development container"
  default     = "ghcr.io/harrison-ai/coder-dev:base"
}
```

**Comment by mtojek** [comment]
Oh, I think that your client might be outdated. Here is how it looks on my end:

<img width="876" alt="Screenshot 2023-05-31 at 10 39 40" src="https://github.com/coder/coder/assets/14044910/c66ccf3e-8526-4b28-a571-3cc1193f8e9d">

Maybe you need to re-push the current template as the error message that the parameter is required, but as long as there is `default` property, it should be used instead.

**Comment by dcarrion87** [comment]
@mtojek no go with new client against old server. I'm just going to update a dev instance to see if it fixes it.

**Comment by mtojek** [comment]
You can try to recreate a new template using the same definition. Then, compare the CLI behavior.

**Comment by dcarrion87** [comment]
@mtojek what cli and server version are you using?

**Comment by mtojek** [comment]
Latest main, so I guess that v0.23.7 should be fine too. I don't remind any changes around that code place.

**Comment by dcarrion87** [comment]
Updated to server 0.23.7
Updated to client 0.23.7 
Re-uploaded template
Still asked for value without a default showing. Anything else to check?

**Comment by mtojek** [comment]
> Re-uploaded template

Did you create a new template or a new template version?

You can also try to set the plugin coder/coder version to 0.7.0 in the template. If it doesn't help, feel free to share the template. If you need urgent mitigation, you need to update the `required` column in the `template_version_parameters`. This should fix it instantly.

**Comment by dcarrion87** [comment]
Just pushed new template version after updating provider to 0.8.1
