### ISSUE TITLE
dev: `make lint` does not lint typescript code

### ISSUE THREAD

**Issue by matifali** [coder/coder#7733]
Sometimes if there are issues with a typescript file the ci lint test fails.
e.g. https://github.com/coder/coder/actions/runs/5133015565/jobs/9235056739

to fix it I had to open the file and fix the errors manually. 
`make lint` should highlight these errors locally before pushing to remote.

**Comment by matifali** [comment]
The issue is that we don't have this check locally. For example when we run `make lint`  
ci was already pointing the error. 
So I guess we should add something to Makefile to find these locally before the ci finds them.

**Comment by matifali** [comment]
@BrunoQuaresma shouldn't we add this to the `Makefile`?

**Comment by BrunoQuaresma** [comment]
I see it now, ty.

**Comment by BrunoQuaresma** [comment]
Adding them to make there are a few "issues". Do you think if we added it to `yarn lint` would solve the problem?

**Comment by matifali** [comment]
yes, I guess so.
