### ISSUE TITLE
healthcheck: render major deployment health issues in dashboard

### ISSUE THREAD

**Issue by bpmct** [coder/coder#7748]
Would be awesome if the product could immediately tell users if there is a severe issue with their deployment, and how to fix it. For example, an unreachable access URL, DERP errors, WebSockets are disabled, etc. This will require collaboration with @bpmct, @kylecarbs, or @ericpaulsen who can help with wording and writing docs around how to resolve these issues.

It feels like we should show this as a service banner on all pages since `pass: false` indicates a major issue. The goal of this is to allow users to self-diagnose issues quickly instead of them having to spend hours debugging themselves and then contacting us for help (where we may tell them to navigate to a specific page or endpoint to reveal errors).

## Acceptance criteria 

Avoiding false positives: A non-dismissable banner may be frustrating if the deployment is, in fact, healthy, despite a failed health check. If we can think of common cases where this would happen, we should ideally fix our health check logic. However, I don't think this needs a ton of testing. If necessary, we could always revert or make the warning dismissable.

Performance: We should run basic performance tests or make design decisions to ensure this does not significantly slow down page loads.

Visibility: Since this banner will only show up during major issues, I don't have strong opinions on whether users should see the banner or only admins. I'm not super concerned about the banner disrupting UX since Coder would be unusable at that point and users seeing it may lead to a quicker resolution time from an admin.

CLI: I don't think this necessarily has to show up as CLI errors, but it would be nice (e.g. similar to a warning that Coder is out of date)

---

To avoid doing a bunch of calculations on the front, this feels like its partially blocked by #7745 (top-level fail reason)

**Comment by mtojek** [comment]
Nice idea! I'm curious if instead of a dashboard it is better to provide Coder Status Page, so people can just navigate there. Something like: https://health.dev.coder.com or https://dev.coder.com/health. 

We may have some background jobs running to examine the state of deployment, and depending on the user role we can give more or less detailed insight into the situation.

**Comment by bpmct** [comment]
For this issue, I was thinking of just putting all major errors as a service banner on the top of every page to make the page (and links to resolve/troubleshoot) as obvious as possible.

One concern I have about starting with a separate health page is that it may not be immediately obvious, particularly for a new admin, that they can navigate to that URL to resolve the issue. I am definitely in favor of a health page with more detailed info down the road. For example (your networking is over websockets, which is 25% slower) 👍🏼

**Comment by BrunoQuaresma** [comment]
I'm not sure how to present this to the user so I will create a design first.

**Comment by mtojek** [comment]
@BrunoQuaresma Is this issue still blocked?

**Comment by BrunoQuaresma** [comment]
I put this in blocked just to make more visible we only want to close this when the health page is GA but IMO, we should close it and file new tickets for the improvements and for the "remove out experimental" work if we need to. cc.: @bpmct
