### ISSUE TITLE
Cant run X-window apps from container

### ISSUE THREAD

**Issue by hannamtt** [coder/coder#7750]
When I launch a workspace with 

env        = ["CODER_AGENT_TOKEN=${coder_agent.main.token}", "DISPLAY=:100"]
volumes {
    container_path  = "/tmp/.X11-unix"
    host_path = "/tmp/.X11-unix"
    read_only = false
  }

and I try to run a xclock for example I get the following
Authorization required, but no authorization protocol specified
Error: Can't open display: :100

I've tried 

xauth add <token>
xhost +

and several other things I've lost track of everything I tried

**Comment by matifali** [comment]
are you specifically forwarding the X-window? If not you should try `coder ssh -X <workspace-name>` from the client you want to access your app from.

**Comment by hannamtt** [comment]
this is the error i get when i do that

parsing flags ([ssh -X extensionsTest]) for "coder ssh": unknown shorthand flag: 'X' in -X

and i do prefer it using the specific X-window anyway

**Comment by matifali** [comment]
Hi @kylecarbs would you be able to dig into this.

**Comment by hannamtt** [comment]
I solved this, i needed to mount .Xauthority as well like below

  volumes {
    container_path  = "/root/.Xauthority"
    host_path = "/home/${local.username}/.Xauthority"
    read_only = false
  }

**Comment by hannamtt** [comment]
I solved this, i needed to mount .Xauthority as well like below

volumes {
container_path = "/root/.Xauthority"
host_path = "/home/${local.username}/.Xauthority"
read_only = false
}
