### ISSUE TITLE
Allow startup script notification in web terminal to be dismissible without reload

### ISSUE THREAD

**Issue by mafredri** [coder/coder#7760]
Currently the startup script notification is always visible in the web terminal while it's running and the only way to dismiss it is by pressing "Reload" which discards the current terminal session.

If the startup script failed, the notification is never dismissible which can be annoying for users.

- [ ] Add `x` that dismisses the notification without discarding the session
- [ ] Show `x` when startup script failed as well

Future improvement ideas:

- Remember that `x` was pressed for unique workspace build/agent ID in local storage and dismiss it from _all_ opened web terminals for said build

**Comment by MrPeacockNLB** [comment]
Currently we are using danamic startup-scripts so the behaviour can be different and this causes sometimes that a blocking process (has to be fixed) show this message. Even it is correct to show this warning one can not remove this to get full terminal size.

Thumbs up for hiding this message
