### ISSUE TITLE
`coder templates create` hangs on `Cleaning up` step

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#7770]
`0.23.7`

when running `coder templates create`, the command hangs indefinitely during the `Cleaning up` step. i've seen this behavior several times, but am unable to identify a common denominator for reproduction.

```
  coder_agent.coder: Plan to create
  coder_app.code-server: Plan to create
  kubernetes_persistent_volume_claim.home-directory: Plan to create
  Plan: 3 to add, 0 to change, 0 to destroy.
✔ Detecting ephemeral resources [3626ms]
> ⧗  Cleaning Up 
```

**Comment by sharkymark** [comment]
I've seen that if there are duplicate resources or data sources or something like that.

**Comment by ericpaulsen** [comment]
@sharkymark the same template builds just fine in the UI.

**Comment by bpmct** [comment]
:( We didn't get to this in time. I'm going to close this one out since it's been so long. If it happens again, can you send server logs?
