### ISSUE TITLE
scale testing: create GitHub actions workflow to initiate a scale test

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#7777]
To quickly and easily run a scaletest, create a GitHub action that can spin up a scaletest cluster and run a predefined scaletest workload.

This will involve:
- Creating a script / automation to stand up the cluster and run the scaletest
- Creating a dedicated project in which to run said scaletest
- Creating a dedicated service account scoped to the above project with required permisisons
- Creating a workflow file with required inputs to pass to the Terraform

Questions:
- Should multiple scaletests be allowed to run at once?
  - As the only shared resource is the Google cloud project, this should not be an issue.
  - Network usage may be a problem though; we may need to create separate VPCs for scale tests so they don't impact each other.
- Who should be allowed to run a scaletest?
  - Presumably only Coder org members.

**Comment by matifali** [comment]
After we have PR deployments, I think we can also deploy Cover similarly to a cluster and run scale tests.

**Comment by johnstcn** [comment]
https://github.com/coder/big.cdr.dev/actions/runs/6535684401/job/17745680817
