### ISSUE TITLE
add coder package derivation to nix flake

### ISSUE THREAD

**Issue by TECHNOFAB11** [coder/coder#7834]
It would be awesome to be able to install coder directly from this flake to get the latest version. 
In nixpkgs the coder version seems to still be at 0.17.1: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=coder 

Currently have to manually overwrite the version and src using `pkgs.coder.overrideAttrs` which isn't a huge issue but doesn't look very nice compared to just `pkgs.coder` or `coder.packages.${system}.coder`  :D

**Comment by matifali** [comment]
Hi, @coadler would you like to set up a GitHub action to update the nix package automatically?
