### ISSUE TITLE
Stacktrace on workspace list with an old browser

### ISSUE THREAD

**Issue by janLo** [coder/coder#7836]
If I login to coder (v0.23.7+a903d7c) from an old chromium (Version 90.0.4430.212 (Developer Build) built on Debian 10.9, running on Debian 10.13 (64-bit) - which is teh default on debian 10) I get the following stacktrace:

```
TypeError: Object.keys(...).map(...).filter(...).sort(...).at is not a function
    at Q5 (https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:313:33217)
    at https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:313:32496
    at https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:313:32571
    at Cg (https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:48:24283)
    at pl (https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:48:42406)
    at K8 (https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:48:41228)
    at wa (https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:48:40275)
    at qE (https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:48:36885)
    at la (https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:46:3279)
    at https://dev.lab.dd.secunet.de/assets/index-dcd8526d.js:48:34263
```

**Comment by janLo** [comment]
The same behavior is observable with Firefox 89.0

**Comment by buesse** [comment]
Working on:
- Chromium Version 113.0.5672.63 (Official Build)

Not working on:
- Chrome Version 83.0.4103.116 (Official Build) unknown (64-bit)
- Chrome 90: April 14, 2021
- Firefox 89.0 (64-bit)

**Comment by janLo** [comment]
The issue is low priority for us, as we managed to provide newer versions for these browsers.

**Comment by BrunoQuaresma** [comment]
Hey 👋 

Looks like it has been around since 2021 for Chrome and Firefox.

<img width="1376" alt="Screen Shot 2023-06-06 at 11 20 52" src="https://github.com/coder/coder/assets/3165839/7723f7ba-20ff-4a3f-ae17-74897633bf32">

Took from https://caniuse.com/?search=Array.at

Wondering if you have a use case where you can't upgrade the browser or for some reason it is limited.

**Comment by matifali** [comment]
Hi @janLo, as @BrunoQuaresma mentioned, this has been around Since 2021. Can you use a more recent version of the browser?

**Comment by janLo** [comment]
Hi @matifali , yes, that's totally fine for me, in case it wasn't clear from my last reply. 

I just wanted to report it because it happened suddenly and it wasn't mentioned in the release notes - so I wasn't sure if it was intentional.
