### ISSUE TITLE
All commands take a long time to complete

### ISSUE THREAD

**Issue by ammario** [coder/coder#7884]
E.g., `coder --help` takes 750ms for me.

**Comment by ammario** [comment]
Odd, there appears to be something happening with TTY detection, perhaps related to the recent lipgloss update.

`time coder --help | grep ""` is 40x faster than `time coder --help`.

**Comment by matifali** [comment]
@johnstcn, is this the same issue you reported on slack?

**Comment by matifali** [comment]
The fix seems to break the deploy job in `ci.yaml`

**Comment by johnstcn** [comment]
@matifali filed https://github.com/coder/coder/issues/7887
