### ISSUE TITLE
ci: PR deployments 

### ISSUE THREAD

**Issue by matifali** [coder/coder#7889]
We can use Coder to deploy a fly.io VM to test PR deployments. 
(Alternatively, directly using bare terraform)
With Coder, we can also test upgrades more efficiently. 

## testing Scenarios

So we will have two scenarios for each PR
1. A fresh deployment
  a. with built-in Postgres DB
  b. with external Postgres DB
2. (optionally) an upgrade over the latest main (first deploy main and then upgrade using the PR)
  a. with built-in Postgres DB 
  b. with external Postgres DB
 
## Securing the deployments

Q: How do we secure PR deployments?
A: Use a fly,io private network
https://fly.io/docs/reference/private-networking/

## Automated Testing

Run automated tests. Like creating/deleting/updating template/workspace/user
It would slot in nicely with the idea of automated tests.
We can also use a remote docker host running as a VM on the same [fly.io](http://fly.io/) private network that would be common to all PR VMs

cc: @bpmct @johnstcn @ammario 

## Steps

- [x] ~Install deploybot~
- [x] Setup KUBECONFIG
- [x] Create a build workflow that builds and pushes a new docker image for the PR
- [x] Create a new namespace and deploy the PR
- [x] Send Slack Notification 
- [ ] Set up cleanup (deleting the namespace)
- [ ] Set up a pre-seeded database

**Comment by matifali** [comment]
> I am in favor of having preview environments to quickly QA a pull request. It would also be helpful to use a "seeded" database that already has a license, users, groups, and templates. Would this be possible with fly?
Yes it is possible, if multiple Coder deployments can talk to same postgresDB concurrently

**Comment by bpmct** [comment]
A few open questions from our call today: 

- Unsure if a persistent disk or database is easier for pre-seeding a deployment with users, workspaces
- Unsure how much this will cost at our current rate or PRs. How can old deployments be cleaned up
- Is Fly.io the best option for preview environments, given our needs?

**Comment by matifali** [comment]
I need a docker image for the current PR and then deploy that to fly.io or OpenStack (we are still evaluating the cost effect). We are thinking to create PR deployments on demand at the press of a button that will be generated by probability cdr-bot for each PR when all tests pass.

I have some ideas where I can use some feedback.

## Generating the Coder image for fly.io and `.deb` package for OpenStack VM

1. create a workflow triggered on the press of that button using GitHub REST API to build the pr image.
2. build a docker image as part of the current ci and then deploy that by pressing the button

## Use Terraform to deploy that image
	- There are Terraform providers for both [fly.io](https://registry.terraform.io/providers/fly-apps/fly/latest) and [OpenStack](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest)

## For the deployment again, there are two options.

1. The deployment process will deploy a Postgres DB, seed it with pre-defined users, workspaces, etc., and then use it for the Coder deployment.
2. Somehow seed the built-in database and start the Coder server.

## And for the deploy-PR button

We need to add to cdr-bot the ability to add and remove the button depending on the state of the tests. [Button should be there if all tests pass]

## Security

There are multiple options
1. Deploy behind a password-protected reverse proxy (should be possible on OpenStack at least)
2. Deploy with a pre-seeded username and password only Coder Engineers or concerned people know. (possible on both fly.io and OpenStack)

## Usability

1. Fly.io allows deployments from a docker image
2. OpenStack will probably need a `.deb` package to be deployed to a VM

What would be the best case?

**Comment by matifali** [comment]
Exploring https://deliverybot.dev/docs/integrations/action-helm/ to deploy on an a cluster on OpenStack

**Comment by matifali** [comment]
We ended up using a k8s cluster to deploy each PR in a separate namespace.
