### ISSUE TITLE
ci: run build step separately from deploy step

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#7891]
# Problem

Currently, our `ci/deploy` step builds the project, copies the package over to `dev.coder.com` and installs the package in one step.

https://github.com/coder/coder/issues/7887 occurred for the following reasons:
- A previous change passed all of the CI jobs that are run on pull request
- Upon merge, the deploy step ran which failed at running `make build`
- This caused the `deploy` step to fail post-merge.

# Proposed Solution

- Run a separate `build` step on PR.
- Do not upload the build artifacts on PR branch, but only on `main` branch.
- Make the `deploy` step contingent on the `build` step, and modify it to use the artifacts from the `build` step.

**Comment by johnstcn** [comment]
Potential scope creep: it would also be _really nice_ if we also built and pushed a Docker image `ghcr.io/coder/coder:main` / `ghcr.io/coder/coder:$GIT_REVISION_SHORT` on each merge to main.

**Comment by matifali** [comment]
+1 for the `main` docker image. 
#7916

**Comment by matifali** [comment]
@johnstcn We are doing this now for some time and publishing it as `ghcr.io/coder/coder-preview:main` and `ghcr.io/coder/coder-preview:$GIT_REVISION_SHORT`
Probably we should move to K8s or simply a docker-compose deployment to solve #8043

**Comment by matifali** [comment]
We now have separate build and deploy jobs.
