### ISSUE TITLE
Adding new parameters to templates, migration form won't use defaults

### ISSUE THREAD

**Issue by amtunlimited** [coder/coder#7895]
## Steps to reproduce
1. Create, push new template
2. Create workspace with new template 
3. Add `coder_parameter` data block to template *with default value*; push
4. Click "upgrade" button on workspace
5. Click "upgrade" button on form without editing inputs

## Expected Behavior
Update runs with default values filled in

## Actual Behavior
Update button on form is disabled until there is some value in the input.

**Comment by matifali** [comment]
@BrunoQuaresma is it a bug or the expected behavior?

**Comment by matifali** [comment]
Hi, @amtunlimited. Can you still reproduce this? Please follow the steps as suggested by @mtojek.

**Comment by bpmct** [comment]
We recently fixed this: #8663. It will be in the next release :)
