### ISSUE TITLE
RSA keys and secrets stored in clear text in the database

### ISSUE THREAD

**Issue by Adphi** [coder/coder#7905]
First of all, thank you very much for your work on this very interesting project 😀.

I am currently evaluating "coder" as a solution to provide our developers with ephemeral and standardized development environments closer to their cloud based dev / staging environment. 

When I looked in the database I noticed that the ssh keys were stored in clear text. 

Would it be possible to implement "at rest" encryption for sensitive data so that the database administrator cannot access the private keys?
We could imagine an environment variable that would allow an encryption passphrase to be supplied, using AES256 for example.

**Comment by kylecarbs** [comment]
We're already doing this for OIDC and Git auth tokens, so yes! We'll do this too.

**Comment by Adphi** [comment]
I didn't see the passphrase configuration in the documentation (perhaps I looked too quickly). 
Where is it stored?

**Comment by kylecarbs** [comment]
Ahh, apologies! We're working on this now... it's not out yet!

**Comment by Adphi** [comment]
> We added support to encrypt sensitive fields in the database, requires an enterprise license though

@sreya, If security is only reserved for users with enterprise license, this can be a very bad signal for the open-source community.

**Comment by kylecarbs** [comment]
@Adphi could you share more about the use case?

We reserve key-rotation for encrypting database values in the Enterprise because this has *only* been necessary for our Enterprise customers. And necessary is even a stretch in that scenario, it's more of a nice-to-have from our understanding.

**Comment by Adphi** [comment]
@kylecarbs, as soon as sensitive data is stored in a database, it should to be encrypted. If an unencrypted backup is compromised, or if the database server is compromised, this would expose identifiers enabling (potentially privileged) access to private repositories.

When using an encryption key, you also need to plan for its rotation in the event that it is compromised.

Grafana, for example, encrypts credentials used to access datasources, even if a default key is used when not configured.
