### ISSUE TITLE
Feature: Ability to favorite workspaces

### ISSUE THREAD

**Issue by ghuntley** [coder/coder#7912]
I tend to create _alot_ of workspaces - one per branch on a repo or one workspace per open-source repo which creates a bit of noise.

I would love to be able to pin a singular workpace at the top of /workspaces that's always on top.

**Comment by MrPeacockNLB** [comment]
Yes, this sounds really good to me. As we now have a working Coder button to open our workspaces this becomes reality. Now that we can open a new workspace from an issue in github we are starting to have a lot workspaces at the same time in parallel.

**Comment by mtojek** [comment]
Assigning @johnstcn

Similar questions to: https://github.com/coder/coder/issues/8098#issuecomment-1880772722

**Comment by matifali** [comment]
Workspaces are user-scoped, and each developer would like to pin their own. This does not need any organization. A simple feature that allows pinning one or more workspaces to stay permanently at the top of the table would solve this.

**Comment by mtojek** [comment]
Thanks for the justification, @matifali.

I hope that we won't introduce Workspace folders soon :)

**Comment by johnstcn** [comment]
I'm going to be making some assumptions here:

1) Pinned workspaces should appear at the top of the workspaces list always, no matter if they are present in the regular list of workspaces.
2) Users can only pin/unpin workspaces they own.
3) Users will only see workspaces they themselves have pinned, and not pinned workspaces of other users.

**Comment by mtojek** [comment]
@johnstcn I don't see any list of action items. Is the last part missing the UI implementation or is there something else?

**Comment by johnstcn** [comment]
> @johnstcn I don't see any list of action items. Is the last part missing the UI implementation or is there something else?

- [x]  Update DB schema + queries https://github.com/coder/coder/pull/11791
- [x]  Add API endpoints to favorite/unfavorite workspace https://github.com/coder/coder/pull/11791
- [x]  Add CLI commands to favorite/unfavorite workspace https://github.com/coder/coder/pull/11793
- [ ]  Add UI support for favorites https://github.com/coder/coder/pull/11875

**Comment by johnstcn** [comment]
@mtojek Can this be closed? We will probably have to iterate a little bit on the visuals but the fundamentals are done.

**Comment by mtojek** [comment]
Yes, thank you for your contributions.
