### ISSUE TITLE
Flake in devtunnel tests

### ISSUE THREAD

**Issue by ammario** [coder/coder#7913]
@deansheather I was hoping you could take a look here, as I think you're most familiar with the code.

The flake embodied [here](https://github.com/coder/coder/actions/runs/5188837163/jobs/9353008493) accounts for about a quarter of our overall flakiness, and is the primary flake in our race tests.

**Comment by deansheather** [comment]
looks like a race condition on close where the netstack is writing packets to a channel at the same time the channel is closed, I'll probably need to make sure that the tunnel is not being used at all (i.e. force close listeners and connections, etc.) before calling close on the netstack

**Comment by coadler** [comment]
See also: https://codercom.slack.com/archives/CJURPL8DN/p1686148339613019

**Comment by coadler** [comment]
Fixed by https://github.com/coder/coder/pull/9805
