### ISSUE TITLE
Web terminal notification for "Startup script failed" does not account for terminal size

### ISSUE THREAD

**Issue by mafredri** [coder/coder#7914]
<img width="900" alt="image" src="https://github.com/coder/coder/assets/147409/bf48d84a-59b9-44ce-8765-8a083deaec97">

It seems the notification banner is throwing off the terminal size and showing content outside the window (depending on window size).

The terminal status bar at the bottom also seems to disappear with this notification, but not with the "startup script is still running" one.

**Comment by BrunoQuaresma** [comment]
@mafredri do you have a workspace where I can test this out?

**Comment by matifali** [comment]
This would probably be fixed by #9320, @mafredri can you please test in https://codercom.slack.com/archives/C05DNE982E8/p1692944206280609

**Comment by mafredri** [comment]
@matifali tested but it doesn't, I think it's more a problem in how the HTML is represented.

**Comment by mafredri** [comment]
This is still and issue, reopening.

**Comment by matifali** [comment]
If this makes the UX better let's try it out. We can test this and revert if we see any issues.
