### ISSUE TITLE
ci: build and publish a docker image against every merged commit to `main`

### ISSUE THREAD

**Issue by matifali** [coder/coder#7916]
We can use the following tags
1. `main`
2. `edge`
3. `$GIT_REVISION_SHORT`

Also proposed by @johnstcn in https://github.com/coder/coder/issues/7891#issuecomment-1580622684

cc: @deansheather

**Comment by atnomoverflow** [comment]
Also i think the go tests should not run on everey pull requests you can trigger test when changes happen to certain places

**Comment by matifali** [comment]
> Also i think the go tests should not run on every pull requests you can trigger test when changes happen to certain places

We have WIP PR to resolve this. See #7134. We plan to remove unnecessary tests in the future.

**Comment by matifali** [comment]
@bpmct what are your thoughts here?

**Comment by matifali** [comment]
We are doing this now, and images are available as [`ghcr.io/coder/coder-preview`](https://github.com/orgs/coder/packages/container/package/coder-preview) for the last seven days.
