### ISSUE TITLE
ability to modify tpl file in web ui for the templates 

### ISSUE THREAD

**Issue by atnomoverflow** [coder/coder#7921]
I want to put the script in seprate file tpl and use the templatefile function of terraform. Using tpl works but they wont appear in the UI. 
Can we change this behavior so that the tpl files appear in the UI ?

**Comment by matifali** [comment]
cc: @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
This is an easy one.

**Comment by BrunoQuaresma** [comment]
@atnomoverflow could you please share the full file name that you use for this `tpl` file and also its content?

**Comment by atnomoverflow** [comment]
@BrunoQuaresma here's an [example](https://github.com/atnomoverflow/coder-template) the tpl file can contain anything that you you usally type in multy-line using EOT in terraform like the starting the script in the coder templates

**Comment by BrunoQuaresma** [comment]
I see a `tpl` can be anything. Just wondering what highlight or icon we should use for that but I will use a generic file one. Thanks.

**Comment by matifali** [comment]
@BrunoQuaresma, Can this be done sooner? For some templates using a `.tpl` is a must to make them useable. It would be super nice if we could also edit them from the template editor.

> I see a tpl can be anything. Just wondering what highlight or icon we should use for that but I will use a generic file one. Thanks.

You can choose to disable highlighting for `.tpl` as it can be anything.
