### ISSUE TITLE
scale testing: run scaletests in nightly-gauntlet

### ISSUE THREAD

**Issue by ammario** [coder/coder#7923]
A request for @johnstcn:

It would be very helpful to have a job in the `nightly-gauntlet` workflow that performs an aggressive scaletest and fails if any error occurs. We can then learn about performance regressions or scale bugs day-of.

**Comment by bpmct** [comment]
I'm working on an RFC to run a bunch of tests weekly (scale, networking, performance). Going to close this out for now
