### ISSUE TITLE
coder templates create error unexpected non-JSON response

### ISSUE THREAD

**Issue by da00891219** [coder/coder#7929]
while creating coder templates, I am getting below error

unexpected non-JSON response "text/plain; charset=utf-8".
Run 'coder templates create --help' for usage.

**Comment by matifali** [comment]
Make sure you set line endings to LF if you are pushing from a Windows devices.

**Comment by matifali** [comment]
Have you resolved the issue? @da00891219

**Comment by matifali** [comment]
Hi @da00891219,
Do you get the same error with every template or any specific template? Please share a sample template that is causing this issue.

**Comment by da00891219** [comment]
we are hitting this issue when we have client version and server version as different.
Issue is resolved when we have client version and server version as same.
