### ISSUE TITLE
Do not disconnect from coder_app after command

### ISSUE THREAD

**Issue by jaulz** [coder/coder#7931]
It would be great if the coder apps do not disconnect automatically after they return. To ensure compatibility it would of course be fine to have a parameter (e.g. `tty=true`?) to control it. My use case is that I want to list the log files in the database via:
````
resource "coder_app" "postgres" {
  agent_id = coder_agent.postgres.id
  display_name     = "Logs"
  command  = "ls /var/lib/postgresql/data/log/"
  icon     = "https://iconarchive.com/download/i83612/pelfusion/flat-file-type/log.ico"
  slug     = "postgres-logs"
}
````

Unfortunately, once opened it immediately says "Disconnected" and I cannot even view the result but actually I would like to use it as a starting point to run further commands.

**Comment by kylecarbs** [comment]
You could do this with `ls /var/lib/postgresql/data/log/ && $SHELL` I believe!

**Comment by matifali** [comment]
Any success @jaulz. Please update if you were able to make it work.

**Comment by jaulz** [comment]
@kylecarbs thanks a lot for the tip, that worked great! 😊  The only minor issue is that it still displays this warning which can be misleading:
![image](https://github.com/coder/coder/assets/5358638/5ade6af2-5b4e-45c5-a169-046d2d5c0110)

**Comment by jaulz** [comment]
And while we are here, I have another use case where I just want to print the content of a file:
```

cat $(mkcert -CAROOT)/rootCA.pem
```

The `$SHELL` trick works fine here but I wonder if a file explorer also makes sense at some point to download files directly from the web interface 😊

**Comment by matifali** [comment]
> And while we are here, I have another use case where I just want to print the content of a file:
> 
> ```
> 
> cat $(mkcert -CAROOT)/rootCA.pem
> ```
> 
> The `$SHELL` trick works fine here but I wonder if a file explorer also makes sense at some point to download files directly from the web interface 😊

you could give https://filebrowser.org/ a try by creating a coder_app for this.
A live [example](https://github.com/matifali/coder-templates/blob/main/deeplearning/main.tf).

**Comment by jaulz** [comment]
@matifali perfect, that works as well. Thanks! 😊 So it's now just about the screenshot that I posted above...

**Comment by matifali** [comment]
> @kylecarbs thanks a lot for the tip, that worked great! 😊 The only minor issue is that it still displays this warning which can be misleading: ![image](https://user-images.githubusercontent.com/5358638/245079309-5ade6af2-5b4e-45c5-a169-046d2d5c0110.png)

@mafredri and @BrunoQuaresma is this an expected behaviour?

**Comment by matifali** [comment]
@jaulz can you please confirm if your `startup_script` has finished? We have some nice [docs](https://coder.com/docs/v2/latest/templates#startup_script) on how to write a good `startup_script`.

**Comment by jaulz** [comment]
Actually, I think the startup script should finish because I use the init script of the agent in the container. It has a custom startup script but that uses `&` to run the default entrypoint in the background:

```terraform
resource "docker_network" "internal" {
  name = "${data.coder_parameter.namespace.value}"
}

resource "coder_agent" "postgres" {
  arch           = data.coder_provisioner.me.arch
  os             = "linux"
  startup_script = <<EOT
#!/bin/bash

cd / 

exec /usr/local/bin/entrypoint.sh postgres &

EOT
}

resource "docker_container" "postgres" {
  count    = data.coder_workspace.me.start_count
  image    = docker_image.postgres.image_id
  # Uses lower() to avoid Docker restriction on container names.
  name     = "${data.coder_parameter.namespace.value}-${data.coder_workspace.me.owner}-${lower(data.coder_workspace.me.name)}-postgres"
  hostname = "postgres"
  dns      = ["1.1.1.1"]
  # Use the docker gateway if the access URL is 127.0.0.1
  entrypoint = ["sh", "-c", replace(coder_agent.postgres.init_script, "127.0.0.1", "host.docker.internal")]
  command  = ["postgres"]
  env      = [
    "CODER_AGENT_TOKEN=${coder_agent.postgres.token}",
    "POSTGRES_PASSWORD=${var.postgres_password}"
  ]
  host {
    host = "host.docker.internal"
    ip   = "host-gateway"
  }
  volumes {
    container_path = "/var/lib/postgresql/data"
    volume_name    = docker_volume.postgres_data.name
    read_only      = false
  }
  networks_advanced {
    name = docker_network.internal.name
  }
  restart = "unless-stopped"
}
```

**Comment by BrunoQuaresma** [comment]
Maybe the process is still open. This warning is only displayed when the startup script is running. Just checking with @mafredri

**Comment by mafredri** [comment]
@jaulz It's possible it won't exit even though it seems like it should, see about redirecting stdout and stderr here: https://coder.com/docs/v2/latest/templates#startup_script
