### ISSUE TITLE
Gaps between lines and performance issues in web terminal

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#7953]
# Description

After updating to latest release **v0.24.0** terminal apps like lazygit, midnight commander, bashtop show spaces between rows. See screenshot below as an example.

![image](https://github.com/coder/coder/assets/103434584/331b8bbd-a327-4268-bcbc-21fb260b0730)

Resizing with zoom or zoom 100% has no effects. 

Maybe it is related to https://github.com/coder/coder/pull/7765

**Comment by ammario** [comment]
@BrunoQuaresma — please take a look.

**Comment by BrunoQuaresma** [comment]
Sorry, but I'm not seeing the issue. Can you please guide me to where is the visual glitch?

**Comment by MrPeacockNLB** [comment]
Hi @BrunoQuaresma ,

for further information I'm using Egde on Windows and Google Chrome on Linux. On both browsers this happens.

Here is another example:

![image](https://github.com/coder/coder/assets/103434584/8b848e9d-0865-404d-9e6b-fd8c99ecb0b4)

**Comment by BrunoQuaresma** [comment]
What command are you running to see these outputs?

**Comment by MrPeacockNLB** [comment]
I've started **midnight commander**. But it is the same in **lazygit** (first screenshot). I tried to downgrade to v0.23.7 but database migration fails so I can not switch easily back.

I'm not a FE developer. Let me know if I can provide some useful information.

**Comment by MrPeacockNLB** [comment]
Here a screenshot from **lazygit**.

![image](https://github.com/coder/coder/assets/103434584/ef15bed4-5b2d-4318-b740-5e1b126d5f69)

**Comment by BrunoQuaresma** [comment]
I think this is good enough, thank you!

**Comment by BrunoQuaresma** [comment]
bashtop looks like this to me:

<img width="898" alt="Screen Shot 2023-06-12 at 11 37 40" src="https://github.com/coder/coder/assets/3165839/fa653712-a679-4925-90d3-5cf8154ed496">

and I'm not noticing any issues 🤔

**Comment by BrunoQuaresma** [comment]
Looks like it is a bug on xterm since the line height is "self calculated". cc.: @code-asher Maybe it was introduced in the latest Dependabot upgrade. Is it something you can take a look at?

**Comment by MrPeacockNLB** [comment]
This seems not be be a new issue. https://github.com/xtermjs/xterm.js/issues/475

**Comment by BrunoQuaresma** [comment]
Thanks for letting us know @MrPeacockNLB

**Comment by code-asher** [comment]
Interesting, seems to be a bug in the DOM renderer.

My guess is the default renderer switched from canvas to DOM so we should explicitly set it to canvas.  I thought we were using DOM explicitly before but that was just for a test, we were actually just using the default.

**Comment by BrunoQuaresma** [comment]
Does it look better when using canvas?

**Comment by code-asher** [comment]
I bet you are right, from my recollection the switch to canvas was largely motivated by performance.
