### ISSUE TITLE
UX: Make workspace name copyable. Improve deletion of workspaces

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#7955]
# Description

With more complex workspace names it is not so easy to delete an existing workspace. We are planing to use workspace name derived from an GitHub issue. E.g. **schema-issue-234-Add-new-feature-667** can be a valid workspace name.

![image](https://github.com/coder/coder/assets/103434584/9c653c42-c778-45e5-907a-e9d86aa5818b)

# Solution

Insert a copyable workspace name above the text input field so one can double click to mark the name and copy it (STRG+).

**Comment by BrunoQuaresma** [comment]
Interesting suggestion. If you have any UI reference you think does this job very well, I would be happy if you could share a screenshot. In the meantime I will think about this 👍

**Comment by bpmct** [comment]
I have seen UIs that enforce the user to type DELETE to confirm, but that does not ensure the right workspace is deleted... Perhaps if added support for bulk actions this would be better, but I definitely want to avoid changing this so it promotes more accidental deletion of workspaces (which happened a few times with users on our v1 product).

**Comment by MrPeacockNLB** [comment]
closing this as fixed in #9347
