### ISSUE TITLE
Agent SSH server should log connections including beginning, end, and reason for disconnect

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#7961]
The Coder Agent should drop logs when SSH connections begin & end, and should log why they end.

Right now, when end users complain about dropped SSH connections, we don't have any logs that explicitly track the events they are asking us to help them debug.

Ideally, we would also log the lifecycle of the multiple _channels_ and _sessions_ across the connection.

**Comment by mtojek** [comment]
It is more tangled than it looks as agents can keep shell sessions for up to 3 days. This way agent won't be able to determine if it is a transient network issue or a permanent problem.

**Comment by spikecurtis** [comment]
> Related: #7512

The web terminal doesn't use SSH, it uses ReconnectingPTY, so unrelated.

**Comment by spikecurtis** [comment]
> It is more tangled than it looks as agents can keep shell sessions for up to 3 days. This way agent won't be able to determine if it is a transient network issue or a permanent problem.

To be clear, this ticket is about logging what we do today, not changing anything about the connection lifecycle or logic.
