### ISSUE TITLE
Better handle built-in postgres when running in Kubernetes

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#7965]
# Problem

If you install Coder in Kubernetes and do not configure an external Postgres URL, Coder will default to the built-in postgres. This is fine until the pod restarts, at which point you will lose any changes you made and leave you questioning reality.

# Solution A

Add a PVC to the deployment for storing the built-in postgres data if an external DB is not defined

# Solution B

Fail to install the Helm chart if no external database is defined.

**Comment by matifali** [comment]
The same applies to docker when we do not mount a volume.

**Comment by matifali** [comment]
This will break the work I am doing with PR deployments. :(

**Comment by matifali** [comment]
We have moved to using external PostgresDB on PR deployments.

**Comment by bpmct** [comment]
At the very least I think some warning label/health check explaining there is no DB configured and Coder is on Kubernetes is important. Would suck if somebody spent hours on setup only for their pod to be evicted /scale up and they loose all their progress 😅

**Comment by matifali** [comment]
If we can detect an internal Postgres, what about always showing a persistent banner to switch to an external DB?

**Comment by johnstcn** [comment]
> If we can detect an internal Postgres, what about always showing a persistent banner to switch to an external DB?

I'm fairly sure that would quickly become obnoxious for instances where an internal postgres is fine (e.g. single-user deployments).

As Coder does know if it's running internal postgres, we can surface that information under `/health/database` and conditionally link to the docs for migrating to an external DB if running internal postgres.

**Comment by matifali** [comment]
Ok so make the banner dismissable. And add to health check.

**Comment by sreya** [comment]
@johnstcn reopen this if you would like to work on this
