### ISSUE TITLE
Add ability to filter by local date-time strings using query params

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#7973]
The filters on both the `/workspaces` page and `/audit` page accept dates: `deleting_by`, and `date_from` and `date_to`,  respectively; however, these date params have no time component and no timezone offset. We should allow for filtering by local date-times so that users can get a more defined, more localized picture of their data.

~Our filter param parser does not allow us to send down colons (`:`) or spaces in our param values as these characters are used to delimit query keys, thus this solution will involve amending the parser so that we can send down date-time strings in[ ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.~ Incorrect, see below comment.

It should be the responsibility of the FE/CLI to send down UTC dates with local timezone offsets set appropriately in an ISO 8601 format, e.g. `"2015-09-15T14:00:13+07:00"`. This change should be made to both the audit log page and the workspaces page.

With this ticket, we should also consider the design of the filter such that it is apparent to the user that the date-times they send down take their local browser settings into account. We should also update our documentation to reflect this flexibility.

**Comment by BrunoQuaresma** [comment]
In this issue https://github.com/coder/coder/issues/7901 I suggested we use a language like:

```
last_seen:14 
```

Or other options:

```
inactivity:14
inactivity:14days
last_seen:14days
```

But Idk how feasible it is.

**Comment by BrunoQuaresma** [comment]
Also, I would not add all the filters in the UI, since there is no space for that. IMO, in the UI, we should display the most common filter and put the advanced ones under the "Filters" dropdown. Maybe we could redesign the tables page to have the header full width instead of wrapping them inside of a container 🤔

**Comment by Emyrk** [comment]
> Our filter param parser does not allow us to send down colons (:) or spaces in our param values as these characters are used to delimit query keys, thus this solution will involve amending the parser so that we can send down date-time strings in[ ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.

You can use quotes! The filter parser supports quoting strings that need these special characters.

![Screenshot from 2023-06-12 14-32-58](https://github.com/coder/coder/assets/5446298/2ecade49-5859-447b-acbe-db05f38d4a9a)

**Comment by Kira-Pilot** [comment]
Thank you so much! This makes life much easier. Keeping this ticket around as we need to add support for timezones on the FE, but I'll adjust the description.
