### ISSUE TITLE
workspace actions: provide a filter for locked workspaces

### ISSUE THREAD

**Issue by sreya** [coder/coder#7977]
Workspaces that are in the locked state should be treated akin to the workspace being soft deleted. They cannot be interacted with by the user and must be unlocked by an admin.

To help reinforce that a locked workspace will be scheduled for deletion (if the template has a locked_ttl configured) we should remove locked workspaces from the default Workspaces view and provide a mechanism for filtering on them.

We should also find some way to convey how much remaining time a workspace has in the locked state before it is permanently deleted.

**Comment by Kira-Pilot** [comment]
Given our current [mocks](https://www.figma.com/file/qghIw8VsrII75O4AAq3xGe/Locked-Workspaces?type=design&node-id=0-1&mode=design&t=rec1WhnNZT860sHO-0) for locked design, it would be ideal to be able to filter on locked workspaces using the `status` param, even though "locked" isn't a true build status.
