### ISSUE TITLE
bug: Workspace starts, but not recorded in audit logs

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#7995]
Version: [`v0.24.0+16ebe10`](https://github.com/coder/coder/commit/16ebe10ff201c086408a168bfcb0fd542152f8e3)

I have reproduced this in 2 separate deployments.

Workspace running, started 30-60 minutes ago
![image](https://github.com/coder/coder/assets/2022166/9a99bcf0-2bb3-4940-9fa5-f3748534cb20)

Audit logs
![image](https://github.com/coder/coder/assets/2022166/b413fa57-42cb-4a3a-8d57-fbeac195549c)

**Comment by sharkymark** [comment]
This is intermittent - I stopped and started the workspace again. Oddly the stopped event didn't show up until the restart workspace occurred.

![image](https://github.com/coder/coder/assets/2022166/c440ff1e-7a67-4b8e-9a54-2732bdf7cd25)

**Comment by sharkymark** [comment]
I'm confused, I stopped the workspace again, and it says the workspace started and no stop event is logged

![image](https://github.com/coder/coder/assets/2022166/11259ae9-f4d4-4da5-818a-a51f15aa809d)

**Comment by Kira-Pilot** [comment]
What I'm seeing on my end is that audit build logs are labeled appropriately, but appear only after a subsequent build has been created.
So, for example, if I start a workspace, I will only see the audit start build log after I stop the workspace. To see the subsequent audit stop build log, I must spawn yet another build. Definitely buggy.
I will dig in some more this sprint to see what changed on the BE.

**Comment by mtojek** [comment]
Something is not getting flushed out, I hit it while working on [this](https://github.com/coder/coder/issues/8025).

I will take a look 🔧.
