### ISSUE TITLE
WebTermin shows only a few lines of history

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#8003]
# Description

As of release v0.24.0 we're not able to tail a long logfile. This must has been changed in the last update too.

We use an alias to show an additional logfile from commands in the startup_script. As this can be a longer file this won't show as this get truncated in WebTerminal. Now we have to use `more` or similar to view this file.

# Solution

Extend history in scrollbar in xterm.js to show larger files in browser window.

**Comment by BrunoQuaresma** [comment]
@code-asher to the rescue!

**Comment by MrPeacockNLB** [comment]
strange things happens. There must be some sort of control characters in the log file. Closing this issue as it is a problem in the file.

Sorry for the noise!
