### ISSUE TITLE
API Key/Token scopes to prevent creating another api key/token

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#8011]
Currently the only supported scopes are [`ScopeAll` and `ScopeApplicationConnect`](https://github.com/coder/coder/blob/ce9d54c6ff61e150593ef192a1a2d06b8777d84c/coderd/rbac/scopes.go#L35-L36). With the addition of this issue: https://github.com/coder/coder/issues/7657, we might want to add a new scope that prevents creating new apikeys/tokens.

This is so an admin can make a token for a user, and that user cannot extend create additional api keys from that. This is just to add control options in the more "headless" usage of coder.

**Comment by ammario** [comment]
How do you envision scoping to work in the long-term? Think, one year out? Our auth layer is pretty complex and has been difficult for others to debug, so I think it's worth thinking long-term about adding new features and hopefully simplifying the code on the way.

**Comment by Emyrk** [comment]
If we stay with a system of declarative permissions, then scopes will continue to work.

If we move to a new rbac/authz, we will have to convert any of the declarative scopes. I cannot imagine it being too difficult.

The way we enforce scopes now is to just run both the user's perms and the scope's perms through authz. If any return "false" (unauthorized), we reject the call. To be efficient though we do both of this in a single pass.

It's hard to be predictive of what a different authz system can be though.
