### ISSUE TITLE
`--header` format changed in recent version, must be colon delimited now

### ISSUE THREAD

**Issue by JoshVee** [coder/coder#8021]
https://github.com/coder/coder/commit/43eee35ae8c974be02ea06da6707270623acb871 introduces https://github.com/gobwas/httphead for HTTP header parsing.

However, `httphead` uses colon-delimited key-value pairs, rather than `=`: https://github.com/gobwas/httphead/blob/935b70b38dcb69f249f00f338774bf75822c090a/head.go#L185

This is a breaking change and not reflected in the CLI options:
```
      --header string-array, $CODER_HEADER
          Additional HTTP headers added to all requests. Provide as key=value. Can be specified multiple times.
```

Earlier versions of the Coder CLI supported `--header=key=value`. Now it must be `--header=key:value`.

```
➜  coder login --header=foo=bar
invalid header: foo=bar
➜  coder login --header=foo:bar
Open the following in your browser:

        https://coder.foobar.com/cli-auth

> Paste your token here: 
```

**Comment by matifali** [comment]
cc: @ammario
