### ISSUE TITLE
audit: audit logs from this week displays as last Monday

### ISSUE THREAD

**Issue by matifali** [coder/coder#8024]
See the screenshot
![image](https://github.com/coder/coder/assets/10648092/ca2352e1-fcc6-4ee6-8055-e20e6cdf8bf7)
This event was on the Monday of this week (2 days ago), but the audit log says `Last Monday.`

**Comment by matifali** [comment]
Something like https://github.com/dustin/go-humanize can be used
cc: @Kira-Pilot

**Comment by matifali** [comment]
We should resolve this bug

**Comment by BrunoQuaresma** [comment]
I don't think this is an error at all. The Monday from this week is Last Monday..... 🤔

**Comment by matifali** [comment]
I don't think we should use the world `Last` here. For current (this) week I would prefer dripping any prefix and just use the weekday names.
