### ISSUE TITLE
Downgrade Coder

### ISSUE THREAD

**Issue by da00891219** [coder/coder#8026]
we are at v0.23.4, we want to downgrade coder to v0.20.1. Is it possible? how to do?

**Comment by kylecarbs** [comment]
Based on your issues I'm tempted to say that something in your infrastructure seems to have changed, because the errors are purely related to WebSockets.

**Comment by kylecarbs** [comment]
That GitHub issue seems related to permissions cloning, not with connectivity.

**Comment by da00891219** [comment]
can you please provide downgrade steps (when we have no db backups)?

**Comment by matifali** [comment]
Coder doesn't support rollbacks
https://coder.com/docs/v2/latest/admin/upgrade
