### ISSUE TITLE
Make helper apps optional (e.g. “VS Code Desktop”)

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8033]
Version: [`v0.24.1+2c843f4`](https://github.com/coder/coder/commit/2c843f4011430ef5bbefc76460af20393a317350)

An enterprise prospect is requesting that VS Code Desktop icon be configurable. i..e, removed in certain templates.

Their feedback was that there are many development teams that never will use VS Code. e.g., Java, data science, etc. so do not want to confuse or annoy end users about using Coder.

![image](https://github.com/coder/coder/assets/2022166/2a7acd64-4f57-4740-b5b0-bfc30d304a61)

Related #8032 

## Implementation notes

Written by @bpmct 

To me, the most natural way to do this is per-agent. Instead of specific flags to disable each “desktop app” (let’s assume we will have many down the road such as JetBrains, RDP, etc), I suggest we have a field on the agent that defaults to specific icons showing up.

```hcl
resource “coder_agent” “data_science” {
  # …
  helper_apps = [] # disable all
}
```

And by default, agents have this:
```hcl
resource “coder_agent” “data_science” {
  # …
  helper_apps = [“vs-code”, “port-forward”, “ssh”]
}
```

By “default,” I mean the default for the provider. Not our example templates.

One interesting side-effect of this approach is it allows template authors “opt-in” to new apps appearing on their dashboard if they hardcode the helper apps in their template OR if we don’t make it a default property for the agent. This allows us to add more functionality `vs-code-insiders` without being concerned about the impact it has on existing deployments that upgrade: “wait, my users are now seeing a new button on the dashboard I don’t want them to see”. 

Open to other ideas though!

**Comment by matifali** [comment]
+1 for this. Also it is if no use for a MATLAB template

**Comment by matifali** [comment]
>  This allows us to add more functionality `vs-code-insiders` without being concerned about the impact it has on existing deployments that upgrade: “wait, my users are now seeing a new button on the dashboard I don’t want them to see”.

I still think we should give these controls to the User in their account setting (Specifically for IDE buttons)

**Comment by bpmct** [comment]
> >  This allows us to add more functionality `vs-code-insiders` without being concerned about the impact it has on existing deployments that upgrade: “wait, my users are now seeing a new button on the dashboard I don’t want them to see”.
> 
> 
> 
> I still think we should give these controls to the User in their account setting (Specifically for IDE buttons) and OSS users should be able to use this too.
> 
> 
> 
> 

Can you make GitHub issue with a basic outline of this, or even mock-ups of the UX? I am open to this, and I think both of these can probably done (we have a generic `ide` helper_app) and then it will show the users preferred IDE. My main questions are: Are there some workspaces or agents where a developer would prefer GoLand vs. VS Code / IntelliJ? Will all IDEs show up via the dropdown, or only the preferred one. Will admins be able to entirely hide IDEs like insiders? All of these answers don't have to be "yes," but I would like to understand the trade-offs. That would also help me understand if we should do this issue, your issue, or both.

**Comment by bpmct** [comment]
Thanks, based on that description, let's move forward with the `vscode` as a default option. I don't think this would block us adding an account setting down the road.

**Comment by matifali** [comment]
Can we remove VS Code Desktop button from templates that make no use of it?

**Comment by kconley-sq** [comment]
In addition to supporting the hiding of built-in helper app buttons like VS Code Desktop, SSH, etc., would it be possible to support hiding the Terminal app based on the user's role(s)? My team is interested in providing a workspace template that only provides specific workspace app buttons that we customize for unprivileged users and none of the other built-in Terminal, SSH, Port Forward, etc. buttons. However, to help deployment admins debug any issues users see with those workspaces, we'd also like to support showing the Terminal, SSH, Port Forward, etc. buttons _only_ for those privileged users (e.g. template admins and owners) so they can jump into the terminal to debug issues in the workspace.

**Comment by sharkymark** [comment]
I love being able to hide web Terminal
