### ISSUE TITLE
Custom log in page and links

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8034]
Some software, such as [GitLab EE](https://docs.gitlab.com/ee/user/admin_area/appearance.html#sign-in--sign-up-pages) allow the admin to set a custom login message. We have some users who like to rebrand Coder as an internal platform/product.

**Comment by matifali** [comment]
We now have a custom login page that allows the use of a custom Logo and text. Additionally, we can add a field, `description`, with markdown support for the links.

This was requested in #8395 and was completed in #9902.
cc: @mtojek
