### ISSUE TITLE
agent metadata: use magic format to render values nicely

### ISSUE THREAD

**Issue by ammario** [coder/coder#8038]
With https://github.com/coder/coder/pull/8005, a nice pattern emerges where resource values are formatted as:

- `246 / 251 GB (90%)`

or:

- `(<used> (/ <total>)? <unit> (<pct>?)`

I propose we change the frontend to show a dial when text follows the aforementioned format. We should document this magic format so users can manipulate the output of other tools to render nicely.

**Comment by ammario** [comment]
Per https://github.com/coder/coder/pull/8005#discussion_r1231197171, we'll probably have to change `coder stat` to use the same unit before modifying the frontend.

**Comment by ammario** [comment]
Related: https://github.com/coder/coder/issues/8238

**Comment by BrunoQuaresma** [comment]
To get this done, I guess the BE should return a better struct value like:
```ts
{
  value: 20
  unit: "%"
  color: "success" // It could be success, info, warning, error
}
```

**Comment by BrunoQuaresma** [comment]
cc.: @mtojek since it needs some BE

**Comment by matifali** [comment]
@BrunoQuaresma, can we handle #8238 as part of this, or should we reopen that?
