### ISSUE TITLE
Improve visibility of quotas in the UI

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8039]
From @ammario 

> Right now, Quotas is exposed to the user as an additional step in the Build Log. While we should keep this Build Log messaging as Quotas are a real part of the provisioning process, we may get more adoption if we made a UI (e.g. on the WorkspacesPage) that explains to users what their quota state is.
> 
> I don't feel strongly that we should do something here, it justs felt like a part of the product that was under-UI-ed.

**Comment by ammario** [comment]
Sure.

Right now, Quotas is exposed to the user as an additional step in the Build Log. While we should keep this Build Log messaging as Quotas are a real part of the provisioning process, we may get more adoption if we made a UI (e.g. on the WorkspacesPage) that explains to users what their quota state is.

I don't feel strongly that we should do something here, it justs felt like a part of the product that was under-UI-ed.

**Comment by bpmct** [comment]
I can write something up :)

**Comment by BrunoQuaresma** [comment]
UI suggestions:
- Show the quota info in the workspace build page and in the workspace build history 
- Identify if the build error is caused by the quote limit, if it is, show a custom error message instead of "workspace build failed"
- Show the resource quota in the template preview

BE changes:
- Right now, we only return the `daily_cost` in the `WorkspaceBuild` resource, would be interesting to add `build_cost`, `budget`, and `credits_consumed` as well.

**Comment by bpmct** [comment]
Sorry for the delay! Can we show the user's quota in their dropdown in the top right and the account settings? It would also be cool to show what workspaces are consuming what amount of a user's quota. That way, when a build fails, they can go to their account settings to investigate. This is very similar to how clouds do it.

Right now, we properly identify if a build error comes from a quota limit and show the user's full quota. We do this in the workspaces page and builds page.

**Comment by BrunoQuaresma** [comment]
I like the ideas! To make those things work we would need:
- Add a quota field to the user endpoint
- Add a quota field to the workspace endpoint

But, not sure if this would work since a quota is not attached to a user but to a group, and a user can be in many groups. 🤔

**Comment by bpmct** [comment]
We explain how quotas are compounded across multiple groups here: https://coder.com/docs/v2/latest/admin/quotas

**Comment by mtojek** [comment]
> Sorry for the delay! Can we show the user's quota and credits (3/10) in their dropdown in the top right and the account settings? It would also be cool to show what workspaces are consuming what amount of a user's quota. That way, when a build fails, they can go to their account settings to investigate. This is very similar to how clouds do it.

I recommend to divide-and-conquer this problem. So far we have the enterprise endpoint for `/workspace-quota/{user}`, @BrunoQuaresma will it cover any requirements?

> Right now, we only return the daily_cost in the WorkspaceBuild resource, would be interesting to add build_cost, budget, and credits_consumed as well.

I'm not sure about the legal side as the enterprise code should resist in a separate package (like "enterprise"). By adding it to `WorkspaceBuild` we will bundle it with OSS.

**Comment by ammario** [comment]
Large portions (maybe most) of the quota functionality are already outside of the specially licensed `enterprise` folder. And, that's OK.

**Comment by bpmct** [comment]
Can we add a page in account settings to show the quota in more detail?

e.g. what workspaces or even resources within workspaces contribute to the quota

**Comment by BrunoQuaresma** [comment]
Sure. I don't think we have this in the BE yet so we would need to add it there.

**Comment by ammario** [comment]
@BrunoQuaresma — we have this coming from the backend. See the `DailyCost` field on the `LatestBuild` of a workspace.

**Comment by BrunoQuaresma** [comment]
@ammario but, how can we show the history of the quota usage?

**Comment by ammario** [comment]
We have the data on quota consumption in the backend, but not the history of the group budgets. There are some big plans around redoing our RBAC and Group hierarchy which will inevitably affect quotas, so I think you should ship what you have in the user drop down and not invest too much more into quotas.

**Comment by BrunoQuaresma** [comment]
I will put this on hold a bit since only adding the quota on the dropdown does not add too much value by itself

**Comment by matifali** [comment]
@BrunoQuaresma @ammario, we are now displaying quota information on the workspace page. Please reopen if you think it is something else.

![image](https://github.com/coder/coder/assets/10648092/e9744414-2081-4cd3-95fc-e889460a37f3)
