### ISSUE TITLE
execute transaction: insert template version: unauthorized: forbidden.

### ISSUE THREAD

**Issue by da00891219** [coder/coder#8041]
C:/Users/XXXX/Downloads/coder_0.20.1_windows_amd64/coder templates create pod-with-code-server-test
> Upload "D:\\DA00891219-ANILD\\neom-source-code\\dx-neom-coder-templates\\coder-templates\\pod-with-code-server"? (yes/no) yes
execute transaction: insert template version: unauthorized: forbidden.
Run 'coder templates create --help' for usage.

Server Version - v0.20.1

**Comment by kylecarbs** [comment]
Does your user have permission to upload templates?

**Comment by da00891219** [comment]
you are right, I am trying with user which has member privileges. I tried with template admin user and it went fine.
