### ISSUE TITLE
chore: setup dev.coder.com with multiple coderd instances 

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#8043]
We should be running our dogfood deployment with multiple Coderd instances so that we are regularly exercising the "distributed" versions of our code.

There is no requirement to locate these instances in different availability zones, as the motivation is not to increase availability of our own service.  E.g. running them in 2 Docker containers on the same host is fine.

**Comment by matifali** [comment]
We can also explore using docker-compose with multiple replicas to keep things simple. I can do this if we agree.

**Comment by spikecurtis** [comment]
Docker compose is fine with me as long as we have a multi-replica setup.

**Comment by ammario** [comment]
Sounds fine to me

**Comment by matifali** [comment]
We now have multiple coderd replicas along with external provisioners.
