### ISSUE TITLE
workspace stuck on "cleaning up" when app slug is duplicate on template push

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8048]
You have to look in the server logs to see this.

```sh
2023-06-15 13:35:04.899 [erro]  send CompletedJob  job_id=ad76c145-d07f-4403-812b-4d3ee0eca6dd ...
    error= insert resource: duplicate app slug, must be unique per template: "vnc"
           	storj.io/drpc/drpcwire.UnmarshalError:26
           	storj.io/drpc/drpcstream.(*Stream).HandlePacket:224
           	storj.io/drpc/drpcmanager.(*Manager).manageReader:247
```

Are there other validation errors that are not surfaced on `cleaning up`? Are we able to guarantee that this step doesn't hang moving forward?

## Current behavior

The template push hangs and the user does not know that the problem is.

## Expected behavior

Any server logs that cause provisioning to fail/hang should be exposed to the user in `coder templates push` or in the templates UI

**Comment by sharkymark** [comment]
Yep this has nipped me

**Comment by richardkriesman** [comment]
I had the same symptom, though for me the cause was creating `coder_metadata` resources with metadata items using `for_each`. Removing the metadata items resolved the issue.

```
2023-06-21 23:44:41.675 [erro]  send CompletedJob  job_id=5e81ad86-1c73-4413-bbaa-89eea143651a ...
    error= insert resource: insert workspace resource metadata: pq: duplicate key value violates unique constraint "workspace_resource_metadata_name"
                storj.io/drpc/drpcwire.UnmarshalError:26
                storj.io/drpc/drpcstream.(*Stream).HandlePacket:224
                storj.io/drpc/drpcmanager.(*Manager).manageReader:247
```

**Comment by mtojek** [comment]
> insert resource: insert workspace resource metadata: pq: duplicate key value violates unique constraint "workspace_resource_metadata_name"

This one can be reproduced with the following snippet added to the template:

```tf
resource "coder_metadata" "home_info" {
  resource_id = docker_volume.home_volume.id

  item {
    key   = "size"
    value = "5 GiB"
  }
}

resource "coder_metadata" "home_info_2" {
  resource_id = docker_volume.home_volume.id

  item {
    key   = "size"
    value = "5 GiB"
  }
}
```

CLI is hanging now.

> insert resource: duplicate app slug, must be unique per template: 

This seems to be already fixed:
`running command "coder templates push": template import provision for start: recv import provision: plan terraform: duplicate app slug, they must be unique per template: "code-server"`


---

We have 2 issues to fix:

1. CLI can't hang if there is a provisioning error in the `CompleteJob` phase.
2. Prevent the internal error for duplicated `workspace resource metadata`.
