### ISSUE TITLE
Add UI for workspace apps link on workspace page

### ISSUE THREAD

**Issue by misskniss** [coder/coder#805]
In Community Edition, DevURLs will not have a UI flow for creating. It will be handled as part of the template. 

**Acceptance Criteria**
UI that shows running DevURLs and provides link to new page to open them. 

**Implementation Details**
Need notes for FE/BE for displaying the DevURLs(and applications via DevURLs), with optional Icons, in the UI on a workspace page.

**Comment by kylecarbs** [comment]
This is done via the linked PR!
