### ISSUE TITLE
Stop a user's workspaces when their account is suspended

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8051]
When a user is suspended, their API key is invalidated and they cannot establish any new connections. However, if a user happens to have an active SSH connection, they can remain in their workspace to download files, access network resources, etc.

It seems like are two ways this could work, both are fine with me:
- Disconnect all open connections from the user (including direct peer-to-peer connections)
- Stop the workspace, which will inherently disconnect all connections.

**Comment by sreya** [comment]
We're going to investigate doing this in the networking layer, it may be useful when you suspend someone's account to not have their workspaces automatically shut down in case there's something that may be useful to recover prior to shutdown (especially if the data/file/etc resides in an ephemeral directory).

**Comment by bpmct** [comment]
If it's significantly harder to do it on the networking layer, let's issue a `stop` instead. Will defer to y'all as the experts here, but I don't think it's worth a ton of cycles keeping the workspace on for these uncommon scenarios.

**Comment by sreya** [comment]
In the interest of getting workspace quiet hours done I'm moving this to next sprint.

**Comment by sreya** [comment]
@spikecurtis do you think we should consider this blocked on your RFC involving the refactor of the coordination layer?

**Comment by spikecurtis** [comment]
Depends on the timeframe.  I don't think that coordination protocol refactor will land this sprint, maybe next sprint?

**Comment by bpmct** [comment]
Is this a good one to take on now that we have done our refactors to our coordination protocol refactor?

**Comment by bpmct** [comment]
Just spoke with Spike and seems like the code paths are in a good place now for us to address this. However, it'd still require significant investment from us so we probably won't be able to get to it in the first half of this year

**Comment by sreya** [comment]
We're going to do this the simple way -- which is to simply stop all the workspaces of a suspended user which should help prevent exfiltration.
