### ISSUE TITLE
Auditor account can create workspaces

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8055]
We have a user who wishes to add users as auditors for mandatory audits, but would not like the auditors to create workspaces as it is an extra level of privilege.

**Comment by Emyrk** [comment]
It is currently assigned to the `member` role, which is always an implied role 🤔

**Comment by MrPeacockNLB** [comment]
on the ooposite it make no sence for the auditor to create a workspace. Please take least privilege into account
