### ISSUE TITLE
coderd allocates large amounts of memory under high ReconnectingPTY traffic load

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#8071]
When sending moderate amounts of ReconnectingPTY traffic to coderd, we observe high memory usage that eventually is released once the load drops.

![image](https://github.com/coder/coder/assets/4949514/4cf0d9d8-8cbc-4f06-9ef4-676e75c2af73)

This is the result of sending approximately 4MiB/s of ReconnectingPTY traffic to coderd (4096 kB @ 10Hz).

We see memory usage rise up to approx 5GiB and then drop off after the traffic subsides.

A pprof sample taken at 15:36 (indicated by the blue line) shows a high proportion of memory usage by device.PopulatePools:

```
github.com/tailscale/wireguard-go/device.(*WaitPool).Get
/home/runner/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20221219190806-4fa124729667/device/pools.go

  Total:           0     3.92GB (flat, cum) 97.76%
     36            .     3.92GB           ??? 
```

Pprof available here:

[cian-jun12-heap.pprof.gz](https://github.com/coder/coder/files/11772511/cian-jun12-heap.pprof.gz)
[cian-jun12-goroutine.pprof.gz](https://github.com/coder/coder/files/11772512/cian-jun12-goroutine.pprof.gz)

**Comment by kylecarbs** [comment]
@johnstcn I believe the allocation here will scale relatively linearly with the number of workspaces. How many PTYs and workspaces were there?

**Comment by johnstcn** [comment]
> @johnstcn I believe the allocation here will scale relatively linearly with the number of workspaces. How many PTYs and workspaces were there?

@kylecarbs 100 and 100, respectively. The linear scaling tracks closely with my observations.

**Comment by kylecarbs** [comment]
It is surprising the vast amount of allocation that occurs though...

**Comment by spikecurtis** [comment]
My expectation is that fixing #6191 may bring this number down, since Coderd can share the same wireguard device (and thus the memory pools) among multiple agent connections.

**Comment by johnstcn** [comment]
The experimental `single_tailnet` appears to resolve this 👍. 
We should keep this open until single_tailnet is GA, and then double-check.

**Comment by johnstcn** [comment]
Recent scaletests on commit 399b42814 show approx. 2.8G for 10KB/s ReconnectingPTY traffic to 200 workspaces.

While this is an improvement over the original measurements in the issue description, it is a large increase over previous measurements with only single_tailnet enabled.

Compare:
- [single_tailnet + tailnet_pg_coordinator](https://stats.dev.c8s.io/d/qLVSTR-Vz/coderv2-loadtest-dashboard?orgId=1&from=1695815748000&to=1695821133000&viewPanel=10)
- [single_tailnet only](https://stats.dev.c8s.io/d/qLVSTR-Vz/coderv2-loadtest-dashboard?orgId=1&from=1695824750000&to=1695829965000&viewPanel=10)
- [tailnet_pg_coordinator only](https://stats.dev.c8s.io/d/qLVSTR-Vz/coderv2-loadtest-dashboard?orgId=1&from=1695831080000&to=1695836418000&viewPanel=10)

**Comment by kylecarbs** [comment]
Suspicious that the allocations are the same for both `tailnet_pg_coordinator` ones. Are you certain `single_tailnet` was working?

**Comment by johnstcn** [comment]
> Suspicious that the allocations are the same for both `tailnet_pg_coordinator` ones. Are you certain `single_tailnet` was working?

I don't see any [logs from pgcoord]https://cloudlogging.app.goo.gl/uxdpD1ZwJakLVPpe7 during the timeframe of the second test, nor do I see any [logs from servertailnet](https://cloudlogging.app.goo.gl/iRatJdxJGzriFSdw7) during the timeframe of the third test.

**Comment by spikecurtis** [comment]
During the first test, although `single_tailnet` is enabled, [all the agents are "legacy"](https://console.cloud.google.com/logs/query;query=labels.%22k8s-pod%2Fapp_kubernetes_io%2Fname%22%3D%22coder%22%0Aoperation.producer%3D%22coderd.servertailnet%22;cursorTimestamp=2023-09-27T12:48:21.650329541Z;startTime=2023-09-27T12:46:00.000Z;endTime=2023-09-27T13:25:00.000Z?project=v2-loadtest) with respect to single_tailnet.

In that case, we create a tailnet per agent and get no memory benefit from tailnet.

I'm not sure how these tests were set up, so can't speak to why all the agents are legacy.

**Comment by spikecurtis** [comment]
[Ah ha!](https://github.com/coder/coder/blob/30440915bc75b4bdc62596bb0796b58630cdd98a/enterprise/tailnet/pgcoord.go#L149)

**Comment by spikecurtis** [comment]
https://github.com/coder/coder/pull/10083

**Comment by coadler** [comment]
Should be fixed now :+1: 

Thanks for all the debugging help :sunglasses:
