### ISSUE TITLE
investigate devfile support

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8072]
[devfile](https://devfile.io/docs/2.2.0/devfile-schema) is another open schema, similar to devcontainers. We can see if we can make a Terraform-based template to provision a CodeWorkspace CRD (see eclipse che docs). If there is interest, we could also explore integrating devfiles into [envbuilder](https://github.com/coder/envbuilder/)

**Comment by michaelbrewer** [comment]
@bpmct what was the outcome of this investigation?
