### ISSUE TITLE
editing (and updating) workspace schedule should actually restart workspace

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8086]
After editing your workspace schedule, it will send another `start` job. I feel like we should do a full stop, then start which is what we call our "restart" behavior. I noticed it runs the startup script again, this could lead to some unintended consequences if the startup script is only meant to run once per running workspace.

<img width="1458" alt="Screenshot 2023-06-19 at 1 10 58 PM" src="https://github.com/coder/coder/assets/22407953/ace9158c-c4e5-4fd9-9b00-75222ca0e68a">

**Comment by bpmct** [comment]
Agreed.

**Comment by matifali** [comment]
It would be best if we could implement it in a way that unlinks the schedule from the workspace start/stop. Probably part of #8821.
