### ISSUE TITLE
feat: Ability to pin (favorite) templates

### ISSUE THREAD

**Issue by matifali** [coder/coder#8098]
If a deployment has too many templates, It would be nice to pin some of my most used templates.
Related to #7912 
cc: @BrunoQuaresma @bpmct

**Comment by sharkymark** [comment]
Sorting like a default by name would be recommended as a start. 

The use of the templates UI is also for administrators who just need a faster way to move through all of the templates in their deployment.

**Comment by mtojek** [comment]
@johnstcn agreed to draft RFC for "pinning", but we need to be sure that it is aligned with the wide long-term of the Template Organization.

Are there any specific requirements we should consider first, @bpmct?

**Comment by stirby** [comment]
Changed the name since this is functionally the same as https://github.com/coder/coder/pull/11673 for templates.
