### ISSUE TITLE
[CLI]: Print Global Option on all coder command --help

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#8107]
## What is your suggestion?
I had to create a bot login for coder, it was kinda difficult to relate how to use the token. In the main manual (coder --help) you can see the Global options which exposes the flag --token. But in the contextual manual (coder login --help) cuz I lost sight of that Global options. It would be really helpful for the future adding a reference to thos Global option on the subcommands of coder CLI.

## How will this improve the docs?

Add Global options CLI to all subcommands of `coder "command" --help`

**Comment by ammario** [comment]
We used to do those and made the intentional decision to not show global options on all help pages. We have many simple pages such as `coder version --help`:

```
coder version --help
Usage: coder version [flags]

Show coder version

Options
  -o, --output string (default: text)
          Output format. Available formats: text, json.

---
Run `coder --help` for a list of global options.
```

which would be mired by our long global help:

```
Global Options
Global options are applied to all commands. They can be set using environment variables or flags.

      --debug-options bool
          Print all options, how they're set, then exit.

      --global-config string, $CODER_CONFIG_DIR (default: /Users/ammar/Library/Application Support/coderv2)
          Path to the global `coder` config directory.

      --header string-array, $CODER_HEADER
          Additional HTTP headers added to all requests. Provide as key=value. Can be specified multiple times.

      --no-feature-warning bool, $CODER_NO_FEATURE_WARNING
          Suppress warnings about unlicensed features.

      --no-version-warning bool, $CODER_NO_VERSION_WARNING
          Suppress warning when client and server versions do not match.

      --token string, $CODER_SESSION_TOKEN
          Specify an authentication token. For security reasons setting CODER_SESSION_TOKEN is preferred.

      --url url, $CODER_URL
          URL to a deployment.

  -v, --verbose bool, $CODER_VERBOSE
          Enable verbose output.

```

**Comment by ammario** [comment]
I agree we should more clearly indicate that there is a `--token` flag from the `coder login` help page.

**Comment by kylecarbs** [comment]
I don't think we're going to do this, or at least not for all global options.

For now it's not ideal, but `coder --help` shows it all!
