### ISSUE TITLE
Templates Bigger then 1M  (Archive too big. Must be <= 1048576 bytes)

### ISSUE THREAD

**Issue by n1LWeb** [coder/coder#8126]
Is it possible to change the maximum template size? I'm putting up whole developement networks with coder. And especially in cases where no fitting images are available (arm64) this limit is reached very fast.

**Comment by kylecarbs** [comment]
Seems reasonable.

Out of curiosity, how large are your templates?

**Comment by n1LWeb** [comment]
I have an template with docker image built from git which would result in 18M. Of course i can build the docker images outside but it'd add some complexity. If the image will get clened up it'd render the template depending on it useless. As we only use this with a small team (6-10 Users) the amount of data is no Problem. I get the 1M limit an resonable default. But every default should be changable for special circumstances.

**Comment by kylecarbs** [comment]
Agreed. I'd proceed with caution though, because each version is stored in the database, which could result in a lot of storage if you're iterating on the template a lot.
