### ISSUE TITLE
Enterprise account dormancy

### ISSUE THREAD

**Issue by ammario** [coder/coder#8128]
In v1 we had a feature called [account dormancy](https://coder.com/docs/v1/v1.43/admin/account-dormancy) which marked users as "dormant" after they had been inactive for 90 days. The mark was automatically removed once the user was seen again, so it did not suspend the user.

This behavior is nearly exactly what's employed by [GitHub Enterprise](https://docs.github.com/en/enterprise-server@3.4/admin/user-management/managing-users-in-your-enterprise/managing-dormant-users) and [GitLab](https://docs.gitlab.com/ee/user/admin_area/moderate_users.html), so we should bring it here too.

### Automatic Provisioning

Automatic provisioning systems (e.g. SCIM) can create lots of unused user accounts. We want to encourage our customers to use these systems and make it easy for new groups to try Coder. Thus, we should mark these automatically provisioned accounts as dormant until first login.

**Comment by bpmct** [comment]
Yep, we'll need to add a `dormant` state to users which occurs in these scenarios:

- When the user account is created, but has never logged in
- When the user hasn't performed an action in Coder in over 90 days
- Admins should be able to manually set accounts as "dormant"

**Comment by mtojek** [comment]
It looks like this issue is next in line, so I'm taking it.

**Comment by mtojek** [comment]
Battle plan:
- [ ] Add new user state `dormant`
   * add enum to database
   * support in CLI
   * support in site
- [ ] Add middleware to automatically switch accounts to active if they are dormant
- [ ] Add menu option for admins to mark accounts as dormant/active 
- [ ] Adjust license evaluation to consider dormant accounts
- [ ] Configure a periodic job to mark inactive accounts (90 days) as dormant 

My main question is whether we can use `user_state` (active - dormant - suspende), or maybe we should introduce another bool column `dormant`. I have not identified any blockers against the first option, and "dormant" seems to be contrary to "active" any way.

**Comment by mtojek** [comment]
Resolved in https://github.com/coder/coder/pull/8644
