### ISSUE TITLE
tailnet: headers specified in CLI aren't sent to DERP server during netcheck

### ISSUE THREAD

**Issue by deansheather** [coder/coder#8134]
Headers specified with `--header` aren't sent when doing HTTPS netchecks to DERP servers. This could result in netcheck failures if UDP and ICMP fail, and the identity proxy requires the header to be set.

Relevant function:
https://github.com/tailscale/tailscale/blob/6829caf6de4c7bde569b0f99f189c2e406555404/net/netcheck/netcheck.go#L1245

**Comment by bpmct** [comment]
Is this related to https://github.com/coder/v2-customers/issues/253?

**Comment by sreya** [comment]
@deansheather fixed this
