### ISSUE TITLE
Getting error while configuring two coder agents

### ISSUE THREAD

**Issue by Baranwalsahil** [coder/coder#8141]
Hello
I have made template using kubernetes resources and configured two containers within kubernetes_pod resources with two coder_agent resource but I am getting error when creating template.
2023-06-20 16:09:21.693 [erro] send CompletedJob job_id=7925dfde-04a9-4632-b05d-482b83db8b0e ...
error= insert resource: duplicate app slug, must be unique per template: "jupyter-lab"
[storj.io/drpc/drpcwire.UnmarshalError:26](http://storj.io/drpc/drpcwire.UnmarshalError:26)
[storj.io/drpc/drpcstream.(Stream).HandlePacket:224](http://storj.io/drpc/drpcstream.(Stream).HandlePacket:224)
[storj.io/drpc/drpcmanager.(Manager).manageReader:247](http://storj.io/drpc/drpcmanager.(Manager).manageReader:247)

**Comment by sharkymark** [comment]
Change the slug name in one of the coder_app blocks. They cannot be the same since the URL we create for each app must be unique.

**Comment by Baranwalsahil** [comment]
Hello,

I have attached my terraform script both the code app name is different

Thanks
Sahil

**Comment by matifali** [comment]
Hi @Baranwalsahil, it looks like the links you attached are inaccessible. Could you please share your template file?

**Comment by Baranwalsahil** [comment]
Hello Atif,

Which link are you referring to?

Thanks
Sahil

**Comment by matifali** [comment]
> Hello I have made template using kubernetes resources and configured two containers within kubernetes_pod resources with two coder_agent resource but I am getting error when creating template. 2023-06-20 16:09:21.693 [erro] send CompletedJob job_id=7925dfde-04a9-4632-b05d-482b83db8b0e ... error= insert resource: duplicate app slug, must be unique per template: "jupyter-lab" [storj.io/drpc/drpcwire.UnmarshalError:26](http://storj.io/drpc/drpcwire.UnmarshalError:26) [storj.io/drpc/drpcstream.(Stream).HandlePacket:224](http://storj.io/drpc/drpcstream.(Stream).HandlePacket:224) [storj.io/drpc/drpcmanager.(Manager).manageReader:247](http://storj.io/drpc/drpcmanager.(Manager).manageReader:247)

 These storj.io links
 I couldn't find anything else where you have shared your template.

**Comment by bpmct** [comment]
@Baranwalsahil are you still running into this issue? If so, I'll reopen. We recently fixed the issue where these error messages do not appear when pushing templates
