### ISSUE TITLE
workspace name too long for coder_app

### ISSUE THREAD

**Issue by fschaell** [coder/coder#8145]
Hi,

I used coder and want to creating different workspaces. The length of workspace name can be 32 characters. If you set the name to 32 characters, then error 404 occur by clicking  `coder-server` button. 

You can solve the issue by setting workspace name to 31 characters. 

It seems it is a bug by handling workspace name to open coder-server instance.

Regards,
Frank
<img width="891" alt="image" src="https://github.com/coder/coder/assets/46652374/c69eedf0-03ec-4486-a0cb-e6f9f785adc8">

<img width="1072" alt="image" src="https://github.com/coder/coder/assets/46652374/f0471556-ae8b-4955-a281-76ce992f168d">

**Comment by sharkymark** [comment]
There is a size limit to the first segment (left of domain name) of the IDE URL. 61 or 63 characters.

So check the length of the agent name, coder_app name, workspace name, user name - which make up that segment, to see if they exceed that.

**Comment by ammario** [comment]
When the segment exceeds 63 characters, we could suggest an alternate URL that uses a constant-length format. For example, the agent ID.

**Comment by mtojek** [comment]
I'm looking into this now.

**Comment by mtojek** [comment]
I incorrectly assumed that the workspace apps proxy server uses the database to match
subdomains (URLs are stored in the database). @deansheater brought up that issue (thanks!) and suggested
reverting CRC32 part of the solution.

In the meantime, we identified other issues:
1. The subdomain part should be 62 chars long or 63 chars with the trailing dot.
2. Shortener does not work with wildcards configured like `*-foobar.tunnel.tld`, as the `--foobar` part is not considered in the shortening process.

If I understand the issue correctly, to make it work we need to:
1. Consider the edge case with subdomains with tunnel suffixes, e.g. `*-foobar`.
2. Keep shortened URLs in the token issued by the proxy server.
3. Store shortened app URLs in the database.
4. Add logic to match the shortened URL with the particular application.

also from @deansheater slack:

> I want to make some optimizations regarding the hostnames anyways, for example we can drop the agent name if you're using an app slug since app slugs are unique per template
> which should save a lot of characters for most people

**Comment by mafredri** [comment]
Bumping as I ended up with the following subdomain:
```
https://http-echo--main--scaletest-UN9UmkDA-0--scaletest-SMXCCYVP-0--apps.big.cdr.dev
```
Would it make sense for this to break during terraform plan/apply already?

I think @mtojek's proposal sounds good considering we obviously can take multiple precautions for ensuring less noise in the subdomain, but we still have usernames and workspace names that are capped at 32, so we should assume those alone can use up all the available space. Not to mention the possibility of using subdomain suffixes.

I think it's important we consider that the URL should work across template versions and updated workspaces. I think the best option is for us to generate a new UUID for use in the URL based on _workspace ID_ and _app slug_, this gives us a constant 32 (or 36 with dashes) length subdomain, and leaves room for nearly as many more.

The reason I'd avoid using e.g. workspace ID directly is edge cases like `[very_long_slug]--[workspace_id]--long-subdomain-suffix`.

**Comment by mingfang** [comment]
what is the solution to this problem?
