### ISSUE TITLE
All query parameter got lost if one has to authenticate against coder

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#8147]
# Description

Starting a new workspace via URL params fails as they got lost during authentication.

Version: **v0.24.1**

# Steps to reproduce

Sign out from coder. Start a new workspace with given parameters. After authentication all query parameters are missing.

Testen mit: https://coder.central.dev.cloud.ilab-nlb.de/templates/nlb01/workspace?mode=auto&name=schema-437&param.git_orga=nordlb-coder&param.git_repo=schema&param.git_ref=

- nach Release v0.27.1 besteht das Problem weiterhin

**Comment by kylecarbs** [comment]
Ahh, we shall fix this!
