### ISSUE TITLE
workspace actions: provide a UI for locking/unlocking a workspace

### ISSUE THREAD

**Issue by sreya** [coder/coder#8174]
The dashboard should support an admin locking and unlocking workspaces. 

When an admin requests to lock a workspace, the UI should also send a request to stop the workspace.

**Comment by Kira-Pilot** [comment]
UI work can follow the completion of #8171

**Comment by matifali** [comment]
@Kira-Pilot is UI done for this?

**Comment by matifali** [comment]
@bpmct, if we want to do this, let us reopen the issue or close it as not-planned.

**Comment by sreya** [comment]
There's a UI for unlocking a workspace.
