### ISSUE TITLE
Issue with Token Refresh in Coder

### ISSUE THREAD

**Issue by mforell** [coder/coder#8179]
Hello,

I have a question regarding Coder'sOIDC token refresh mechanism. Does anyone know if we have any control over how Coder handles token refreshing? I've looked through the Coder documentation but couldn't find anything relevant.

The issue is that Coder seems to be improperly handling token refreshes, causing about 10-20 errors per minute in our OIDC event log. When the Coder session is active for an extended period, this results in thousands of entries, which, for now, seems to be just a cosmetic issue. However, I'm not sure if this erroneous token refresh might have any adverse effects on usage (probably not, since it seems a local session gets established), but I think this might be worth bringing up as a possible bug.

Here's what’s going wrong: When the token is refreshed, our OIDC provider issues a new refresh token and invalidates the old one. But Coder continues to use the old token which, as expected, fails. It then retries using the same old token, again failing, and this cycle continues.

I would greatly appreciate it if anyone has any insights into this or can guide me on how I can report this issue to the Coder development team.

Thank you in advance for your help!

We are currently running Coder v0.24.1+2c843f4

**Comment by Emyrk** [comment]
I think this might have resolved this?
https://github.com/coder/coder/pull/8950

**Comment by matifali** [comment]
@mforell can you confirm?

**Comment by Emyrk** [comment]
That is new information :thinking:

**Comment by mforell** [comment]
I'm not sure, but I think it appeared after upgrading from [v2.0.2](https://github.com/coder/coder/tree/v2.0.2) to
[v2.1](https://github.com/coder/coder/releases/tag/v2.1.0)
I also believe that we had this message before 2.0.2 as well.

**Comment by Emyrk** [comment]
This PR: https://github.com/coder/coder/pull/9442 will redirect a user to re-authenticate if their OIDC refresh token is invalid for any reason.

Not sure if this closes this issue though, as this was only triggered by the UI if the user failed to refresh the page.

**Comment by mforell** [comment]
I have just spoken to my colleague. He told me that the problem with the improperly handling of the token refreshes still exists in our Log files.

**Comment by Emyrk** [comment]
@mforell the latest PR (https://github.com/coder/coder/pull/9442) will redirect users to `/login` if their refresh token is invalid. The previous behavior if a user kept open their browser would yield an error on some cadence depending on their page.

> When the token is refreshed, our OIDC provider issues a new refresh token and invalidates the old one.

This should have been fixed here: https://github.com/coder/coder/pull/9293

---


I do not think it is possible to prevent the errors entirely, as if the refresh token is invalid for some reason, we would only know when an error is returned from the IDP. 

So the error rate _should_ be a lot less after the latest change.

**Comment by spikecurtis** [comment]
Sounds like this is resolved.  If not, please reopen and explain what problems you are still seeing.
