### ISSUE TITLE
workspace actions: add action CTAs to VS Code Notifications

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/coder#8181]
Currently, our VS Code notifications look like this:
![Screenshot 2023-06-23 at 10 07 38 AM](https://github.com/coder/coder/assets/19142439/a6577c2b-e21c-4821-8b44-f9e823ce57bf)

We should add CTAs that allow users to take action for each type of Workspace Action notification: workspaces about to be autostopped, workspaces about to be locked, and workspaces about to be deleted.

We'll need endpoints for each workspace action CTA. We should already be able to bump autostop.

Perhaps we can use the endpoint discussed [here](https://github.com/coder/coder/issues/5629) to allow a user to activate a workspace that is ready to be locked.

If a workspace is locked and pending deletion, we should be able to use the endpoint created in https://github.com/coder/coder/issues/8171 to unlock it. Only admins should be able to unlock locked workspaces, and therefore only admins should see a CTA for this type of notification.

**Comment by Kira-Pilot** [comment]
@sreya FYI

**Comment by bpmct** [comment]
How will this work with the archive behavior? "workspace is scheduled to be archived"

**Comment by Kira-Pilot** [comment]
@bpmct Correct, we will be adding VS Code notifications to communicate to users that workspaces will be locked unless action is taken: https://github.com/coder/coder/issues/8180.

**Comment by matifali** [comment]
Isn't a locked state for workspaces that are not being used for a long time? Or is it to lock someone forcefully?

In the former case do we suppose that a user is connected through vs code if their workspace is being locked?

**Comment by Kira-Pilot** [comment]
@matifali good questions!
Yes, a locked state is for workspaces that haven't been used in a long time and may be used in conjunction with Locked Cleanup.
<img width="922" alt="Screenshot 2023-06-23 at 2 14 37 PM" src="https://github.com/coder/coder/assets/19142439/76300bbf-08d3-4efc-8a0b-1c7f9ea5431d">

Our current mental model around workspace action notifications in VS Code is that we will show a user notifications for *any* of workspaces of which they are an owner. Thus, they could be developing in one workspace and receive a notification about an inactive workspace they aren't using. You can see this in action [in a PR](https://github.com/coder/vscode-coder/pull/111/files) I'm wrapping up here. Let me know if that doesn't make sense!
