### ISSUE TITLE
Port is missing when port-forwarding via Dashboard

### ISSUE THREAD

**Issue by jizusun** [coder/coder#8189]
Environment variables:
```dotenv
CODER_ACCESS_URL=http://coder.example.com:3000
CODER_HTTP_ADDRESS=0.0.0.0:3000
CODER_WILDCARD_ACCESS_URL=*.coder.example.com
```
The URL should be 
```diff
+http://3000--main--jizu--jizu.example.com:3000
-http://3000--main--jizu--jizu.example.com
```
![image](https://github.com/coder/coder/assets/4011348/80c4966a-2b05-40d5-bc30-783fcc5a5e46)

**Comment by matifali** [comment]
Looks like a bug. Thanks for reporting. 
Generally, when hosting Coder on a subdomain, specify CODER_ACCESS_URL without the port and use a reverse proxy to route your subdomain to the port where the Coder service is running.

**Comment by Emyrk** [comment]
@kylecarbs will take a look

**Comment by Emyrk** [comment]
Has this ever worked? There is a mistake in the configuration. The `CODER_WILDCARD_ACCESS_URL` value does not have the port.

The `CODER_ACCESS_URL` value does not have any impact on those URLs. Only the `CODER_WILDCARD_ACCESS_URL`.

So `CODER_WILDCARD_ACCESS_URL` should be `*.example.com:3000` not `*.example.com.

---

That being said, we do not allow a port in the wildcard access url for two reasons.


First the flag parser:

https://github.com/coder/coder/blob/5bdc79aef48c31efb95f60912098321f4626e49d/cli/clibase/values.go#L216-L216

Second the HostnamePattern check:

https://github.com/coder/coder/blob/140683813d794081a0c0dbab70ec7eee16c5f5c4/coderd/httpapi/url.go#L103-L105

So I don't think we have ever allowed a port in the wildcardurl. I do not know why, so we might be able to just allow it?

**Comment by Emyrk** [comment]
In the current state, if you wish to use a `CODER_WILDCARD_ACCESS_URL`, you must use a domain without a port.

**Comment by jizusun** [comment]
Thank you @Emyrk  

Currently there is another process listening on the port `80` on that machine.

Is the possible that I can make the port-forwarding via dashboard work with port `3000`?

**Comment by matifali** [comment]
You could try hosting Coder behind a Revere proxy. 
See https://github.com/coder/coder/tree/main/examples/web-server for examples.

**Comment by Emyrk** [comment]
> In the current state, if you wish to use a `CODER_WILDCARD_ACCESS_URL`, you must use a domain without a port.

@deansheather do you know if this not using a port on wildcard domains is a requirement?

**Comment by bpmct** [comment]
> In the current state, if you wish to use a CODER_WILDCARD_ACCESS_URL, you must use a domain without a port.

Let's read the port from the access URL itself to fix this. I believe this is how we handle it in Coder v1 (our legacy product)

**Comment by deansheather** [comment]
Instead of allowing the wildcard access URL to have a port we should just append the port from the access URL to the URL. We expect them to be served on the same port on the same host.

**Comment by Emyrk** [comment]
Should we expect them to be on the same port? That seems like an assumption that won't always hold true.

**Comment by bpmct** [comment]
I think the assumption is fair. It is what we do in Coder v1.

**Comment by bpmct** [comment]
Oh, I'm down for either!

**Comment by VaalaCat** [comment]
Is there any progress on this issue?

**Comment by crono782** [comment]
Ran into this same issue. Hoping there will be some traction on this issue soon. The forwarded port seems to show correctly in code-server list of forwarded ports, but not in the dashboard. Trying to force it yields errors.
