### ISSUE TITLE
coder_parameter: add "order" DB column to ensure file ordering

### ISSUE THREAD

**Issue by mtojek** [coder/coder#8193]
With `synchronize_seqscans = on` (default?), rich parameters are fetched from the database table `template_version_parameters` in the right order, as they exist in the .tf file. 

Unfortunately, it is non-deterministic with `synchronize_seqscans = off`, so we need to introduce an extra db column to ensure the correct ordering.

**Comment by bpmct** [comment]
Nice issue!

Let's call it `order` instead of priority and reverse the behavior. `order = 1` should come before `order = 2`, like CSS. This is a pattern I've seen more commonly. 

Does this mean that the ordering of agent metadata and resource metadata are non-deterministic too? If so, would you be able to add a follow-up issue for this?

**Comment by bpmct** [comment]
Also, if the `order` property is not present, can we attempt to use the HCL parser? Are there anticipated risks/debt with this?

I know it is imperfect but better than nothing / random results.

**Comment by mtojek** [comment]
> Let's call it order instead of priority and reverse the behavior. order = 1 should come before order = 2, like CSS. This is a pattern I've seen more commonly.

👍 It's a matter of refactoring, but sure.

> Does this mean that the ordering of agent metadata and resource metadata are non-deterministic too? If so, would you be able to add a follow-up issue for this?

Terraform always return them sorted in alphanum. order. Parameters are different as they are retrieved directly from the database, and that may cause an issue. It is not a problem of Terraform, but rather a specific PostgreSQL configuration.

> Also, if the order property is not present, can we attempt to use the HCL parser?

If we merge the "order" property, Coder will not be able to determine whether parameters are just using `order = 0`, or not using order at all. In that case, Coder will just sort parameters based on their names consistently, so no randomness.
Unfortunately, the HCL parser will not help here much and I would not like to deal with extra logic to check if the "order" property exists for at least one parameter.

> Are there anticipated risks/debt with this?

Once we merge changes for Coder, UI will display existing parameters sorted by names. Template admins will have to fix this behavior by adding `order = Z` properties. Fortunately, we will not change the parameter handling logic or lose a field.

Due to the non-deterministic behavior of PostgreSQL, it will not be possible to fix it on the migration level.

**Comment by bpmct** [comment]
Gotcha. It all makes sense, thanks.
