### ISSUE TITLE
Using Insiders/EAP versions of IDEs

### ISSUE THREAD

**Issue by matifali** [coder/coder#8207]
## Context 

Previously, VS Code insiders could be used with Coder workspaces in 2 ways.
1. Running `coder config-ssh` and then using [VS Code Remote SSH extension](https://code.visualstudio.com/docs/remote/ssh).
2. Using [Coder Remote](https://marketplace.visualstudio.com/items?itemName=coder.coder-remote) VS Code extension

> These two methods allow using VS Code Desktop Insiders, but the "VS Code Desktop" button couldn't be used due to the different URI used in both versions. 

3. This was addressed by adding a dropdown in #7730 that allows directly launching VS Code Insiders from the dashboard button. 
![image](https://github.com/coder/coder/assets/10648092/d0eb6a59-285d-4c32-bbb5-c1d558f1fd11)

## Problem

1. Some templates have no use of "VS Code Desktop" or "VS Code Insiders Buttons" as they are best suited for another IDE or virtual desktop. e.g., MATLAB or data science templates that use Jupyter Notebook/Lab. #8032
2. Some enterprises do not allow insider/EAP/beta versions of an IDE (Methods 1 and 2 can still be used unless they block SSH access.
3. If a developer/user wants to use the insiders version, they can use options 1 and 2, but option 3 will not work if there is no VS code Insiders button. 

## Possible Solutions

1. #8033 discusses a possible solution that allows controlling the dashboard buttons on the template's scope and can address problem 1 when an IDE is irrelevant to a template.
2. To solve problem 3, we can have a setting (check box) 
:ballot_box_with_check: Use beta versions of IDEs
(under settings -> account -> preferences) 
that changes the VS Code Button to VS Code Insiders button if checked. It should be disableable deployment-wide so that devs can't use the insiders version from the dashboard. (They can still use methods 1 and 2 unless SSH access is disabled).

cc: @bpmct

**Comment by bpmct** [comment]
@sreya solved this in #9100. I'll describe the behavior in our next release changelog
