### ISSUE TITLE
templates: second level of approval for template changes

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#8216]
an enterprise prospect is evaluating Coder, and has provided feedback that a second stage of approval after `coder templates push` would be nice to have.

currently, template changes are handled directly from the template admin and are accepted as the source truth. instead, changes could just request code review of a peer prior to being pushed in. the template owner could be notified via email; "Request for a change in X template."

> This will give more administration control to the flow, and will draw a clear line of responsibilities on who is the owner/responsible to maintain templates.

**Comment by matifali** [comment]
Hi @ericpaulsen,

We now support pushing templates as non-active so users will be able to use the latest template version until a `template admin` or `owner` marks them as active using CLI or dashboard. 

To push a template as nonactive they must use
```shell
coder template push <template-name> active=false
```

**Comment by MrPeacockNLB** [comment]
To me this makes no sense to do it in Coder when using `coder push`. It make maybe sense to etablish this workflow if template edited only inside coder editor. But if one use `coder push` then the source code of the template relies somewhere and to me no one stores code not in a CVS like git today. When using git then there is also a CICD. If a company has to approve changes then they also uses CICD to implement approval of all code changes.

Just my 2 cents...

**Comment by ammario** [comment]
Why would modelling approve flows in Coder be superior to GitOps? It's a lot of complexity so the value would have to be significant.
