### ISSUE TITLE
bug: stale cookies can cause redirect loop when accessing coder_app

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#8221]
# Problem

I had a 'non-default' workspace proxy selected on dev.coder.com (Frankfurt) and attempted to access code-server in my workspace (vvuurrkk). I then got a redirect loop instead of being sent to the application in question.

![Screenshot 2023-06-27 at 09 39 39](https://github.com/coder/coder/assets/4949514/65e68bb4-d0e4-4f9d-a422-2b39cd159ed8)
  
![image](https://github.com/coder/coder/assets/4949514/cf3b9922-9e58-4483-a9fd-0bb6c6e7fdf0)

![Screenshot 2023-06-27 at 09 37 47](https://github.com/coder/coder/assets/4949514/2a83fd19-1046-465c-a8be-5702491c34ed)

![Screenshot 2023-06-27 at 09 37 54](https://github.com/coder/coder/assets/4949514/89827897-380d-4762-951c-934804ebe382)

# Workaround

Clearing the existing cookies for `dev.coder.com` resolved the issue, I wasn't able to figure out which one exactly did the trick though.

**Comment by sreya** [comment]
@deansheather @Emyrk I _think_ this is fixed right? Feel free to reopen if it's not.
