### ISSUE TITLE
bug: UI Gets Buggy with Templates Containing Many Files

### ISSUE THREAD

**Issue by ElioDiNino** [coder/coder#8235]
After adding a template with quite a few files in it and viewing the source code in the UI, things look like this:
<img width="1327" alt="Screenshot 2023-06-27 at 4 14 29 PM" src="https://github.com/coder/coder/assets/52972357/a84639c5-6536-4602-a007-e19cc71f9ce3">

This is zoomed out to see everything, but when at default zoom you get a horizontal scroll bar to see all the cut off file names

**Comment by ericpaulsen** [comment]
@ElioDiNino thank you for submitting this issue. Can you confirm the Coder version you're running?

**Comment by ElioDiNino** [comment]
The latest version (0.24.1)

**Comment by bpmct** [comment]
We had a customer run into this the other day!
