### ISSUE TITLE
Ability to create nested app buttons like the helper apps

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#8237]
It would be great to have the ability to create the app buttons that contain dropdowns like the stock VS Code Desktop button. It would allow me to collapse a few app buttons that I have related to support links (I have two buttons that are direct links to Slack and Jira, it'd be great if I could have one `Support` button for both) and two that are related to container management, but it would be easy to add a range of start/stop/reload/delete functions in one button for that dev container.

<img width="230" alt="Screenshot 2023-06-27 at 5 17 55 PM" src="https://github.com/coder/coder/assets/739851/417a5cc6-f134-4e81-9182-b3ac30fb6034">

**Comment by BrunoQuaresma** [comment]
@mtojek I suppose we would need some changes in the TF schema + BE support

**Comment by mtojek** [comment]
> @mtojek I suppose we would need some changes in the TF schema + BE support

Thanks for taking a look, Bruno! Feel free to draft a list of BE requirements.

**Comment by mattlqx** [comment]
Yeah, that's reasonable.

Would it be possible to make a "dummy" button be the default so that you could have it just say "Support" and the dropdown buttons be the actual actions? Clicking on any part of the default button would also expand the dropdown. If that's not clean enough, your suggested implementation is fine!

**Comment by bpmct** [comment]
I like this, but how do you set the order for each one? +1 for a dummy button

Terraform also supports a nested syntax which is another possibility, but I'm not sure if that makes it difficult to use all fields for a sub-item

```hcl

resource "coder_app" "support" {
  display_name = "Support"
  child {
    display_name = "Jira"
    external = true
    url=""
  }
  child {
    display_name = "internal"
    url = ""
    healthcheck {
       # ...
    }
  }
}
```

**Comment by BrunoQuaresma** [comment]
Wondering if this would be reasonable:
```tf
resource "coder_app_group" "support" {
  display_name = "Support"
  name         = "support" 
}

resource "coder_app" "jira" {
  // ...
  slug         = "jira"
  display_name = "Jira"
  group        = "support"
  default      = true
}

resource "coder_app" "slack" {
  // ...
  slug         = "slack"
  display_name = "Slack"
  group        = "support"
}
```

**Comment by bpmct** [comment]
I wonder if @mtojek has thoughts here. The unfortunate trade-off there is the primary app cannot be clickable.

I think it is acceptable, but has a different behaviour than the VS Code (Desktop/Insiders) versions. I wonder if there is a clean syntax that can support both

**Comment by mtojek** [comment]
> I like this, but how do you set the order for each one? +1 for a dummy button

Parameters support the "order" column, which lets the owner sort them by order & name. Maybe we should bring a similar solution to apps?

> Wondering if this would be reasonable:

I like the concept of `coder_app_group`. If we are concerned about the item order, then ^

Let me know your thoughts.

**Comment by mtojek** [comment]
From Kyle over slack:

>LGTM, but maybe instead of group being a string with a matching name on coder_app, maybe we make it reference by the resource ID.
e.g. group = `coder_app_group.support.id`
or something

**Comment by mafredri** [comment]
After some discussion in Slack, here's an updated proposal based on @BrunoQuaresma's and tries to take into consideration the requirements discussed here.

This adds an `action` (alt. `type`) property on the group that, when set to `group`, will show a button named `Support | v` that will always show a dropdown on click, and clicking an item will not select it, but open that app. Or, when set to `app`, show a button that behaves exactly like the VS Code button (switching item changes the default in the browser session).

```tf
resource "coder_app_group" "support" {
  display_name = "Support"
  action = "group"|"app"
}

resource "coder_app" "jira" {
  // ...
  slug         = "jira"
  display_name = "Jira"
  group        = coder_app_group.support.id
  order        = 1
}

resource "coder_app" "slack" {
  // ...
  slug         = "slack"
  display_name = "Slack"
  group        = coder_app_group.support.id
  order        = 2
}
```

**Comment by matifali** [comment]
Hi @mafredri and @BrunoQuaresma, I have a feature request that is a bit off-topic but still related. If there is `coder_app_group` but the user specifies the `order` property for the `coder_app`, should we order them on the dashboard?
Like 
```tf
resource "coder_app" "jira" {
  // ...
  slug         = "jira"
  display_name = "Jira"
  order        = 1
}

resource "coder_app" "slack" {
  // ...
  slug         = "slack"
  display_name = "Slack"
  order        = 2
}
```
will display **Jira** fist and then **Slack**

**Comment by matifali** [comment]
@kylecarbs I think modules can benefit from this feature too. For example, we can allow grouping all IDE modules so that they all show up as a dropdown on a single button.

**Comment by ammario** [comment]
I agree that findings ways to support more advanced UI customization is interesting, but I don't think leaning more on Terraform for layout is the right direction. We want to keep the terraform provider as small and orthogonal as possible, and UI customization is an endless vista of complexity that's better supported by a true programming layer such as a React component API.

Going to close this out for now.

**Comment by MrPeacockNLB** [comment]
I like the idea to grouping apps together as it would unclutter the UI for some workspaces with huge amount of defined apps.

**Comment by michaelbrewer** [comment]
I like the nested format and handles clutter. 

If a coder_app is just a link does it make sense to be another type of resource for just links. 

Because each workspace I would like to have links for help (teams), docs (confluence) and feedback (support form). Which are all external links.
