### ISSUE TITLE
Coder agent metadata stats thresholds

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#8238]
All stats right now are green text. It would be good to have the ability to specify colored thresholds and/or associate an emoji with a threshold on the metadata stats of the coder_agent resource to better communicate its state.

<img width="782" alt="Screenshot 2023-06-27 at 5 25 37 PM" src="https://github.com/coder/coder/assets/739851/84397790-428c-414d-b0f1-da6b87701a3a">

But what if it could do this?

<img width="768" alt="Screenshot 2023-06-27 at 5 29 51 PM" src="https://github.com/coder/coder/assets/739851/6c319f18-69e3-4ced-8a21-706ced5a1ea5">

**Comment by kylecarbs** [comment]
Ahh, great idea!

**Comment by matifali** [comment]
Related to #8038

**Comment by mattlqx** [comment]
Reopen?
