### ISSUE TITLE
Debug mode shows too much Kubernetes authorization details 0.24.1

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#8248]
I noticed in a version update `0.24.1` there is now a button users can press that allows them to start the workspace in debug mode.

This shows credentials / bearer amongst other stuff we do not want them to see.

```
....
GET /api/v1/namespaces/XXX/services/XXX HTTP/1.1
Host: XXXX
User-Agent: HashiCorp/1.0 Terraform/1.4.6
Accept: application/json, */*
Authorization: Bearer  XXX
Accept-Encoding: gzip
...
```

Please advise how we can stop this from being possible / allowing users to run/see debug output. This is not ideal at all.

Maybe it has always been there but this is the first version where it was obvious to the user to press it and be able to see the motherload. It also causes a very bad UI experience when loading massive output.

I believe it came in with this PR: https://github.com/coder/coder/pull/6903

**Comment by mtojek** [comment]
> Maybe it has always been there but this is the first version where it was obvious to the user to press it and be able to see the motherload.

Debug mode has been released some time ago, but it is limited only to users with [canUpdateTemplate](https://github.com/coder/coder/blob/3dbc96d597b8feb7142a848f59d9ad9f7a938447/site/src/components/Workspace/Workspace.tsx#L239) permissions, so regular users can't trigger it. I suppose that your workspace users should not be able to update the template.

Anyway, I admit that this is unfortunate that a plugin can expose auth details via debug logs.

**Comment by mtojek** [comment]
> I wonder if I can override it to never happen even if an admin presses it. Either via debug override or some form of scrubbing.

In your case, it would be reasonable to implement an extra checkbox to allow for debugging logging not only per user permission but also per template - `[ ] enable debug logging` with a comment about the possible risk of emitting unsafe logs.

But there are also other ways of fixing this issue:
1. A global, per-deployment check, to disable/enable debug logs.
2. Encrypting TF logs.
3. Redacting risky lines, which cannot be 100% bulletproof.

 @kylecarbs WDYT?

**Comment by kylecarbs** [comment]
I think only admins should be allowed to do this for now, otherwise it's unsafe.

**Comment by dcarrion87** [comment]
Any way for me to kill this entirely via lower level override? Even for admins. I don't want admins accidentally clicking debug for a users workspace either. I don't want UI admins even being able to see the details that the debug of some of these stacks produce.

**Comment by dcarrion87** [comment]
I think I'm going to have to halt further updates until I better understand what's going on and how I can override this capability. Looking at the API I understand any API request can come through and also request that log level?

**Comment by dcarrion87** [comment]
Righto. Will look at this further in the morning. Thanks for your responses.

**Comment by dcarrion87** [comment]
Adding in `TF_LOG=ERROR` env var into the container doesn't do it unfortunately.

Initial run it honours the var

![Screenshot 2023-06-29 at 10 10 23 am](https://github.com/coder/coder/assets/2899172/a302ba02-3f3b-4de3-8477-3fb7e4923075)

Subsequent "Try in debug mode" run I can see it spewing debug.

Also I'm not sure about this use of JSON log level. This is spewing throughout:

```
[WARN] Invalid log level: "JSON". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]
```

And Terraform do warn about it:

```
Warning: The JSON encoding of log files is not considered a stable interface. It may change at any time, without warning. It is meant to support tooling that will be forthcoming, and that tooling is the only supported way to interact with JSON formatted logs.
```

**Comment by dcarrion87** [comment]
@mtojek just wondering if you saw this part:

Also I'm not sure about this use of JSON log level. This is spewing throughout:

[WARN] Invalid log level: "JSON". Defaulting to level: TRACE. Valid levels are: [TRACE DEBUG INFO WARN ERROR]

I wonder if it's the TRACE level that is exposing so much?

**Comment by mtojek** [comment]
Can you share where `you see this message? I'm running `terraform` the following way and I can't get it, but I can see levelled JSON log output:

```
$ export TF_LOG=JSON
$ terraform plan -out 1.tfplan
$ terraform plan
{"@level":"info","@message":"Terraform version: 1.5.1","@timestamp":"2023-06-30T08:05:07.362231+02:00"}
{"@level":"debug","@message":"using github.com/hashicorp/go-tfe v1.26.0","@timestamp":"2023-06-30T08:05:07.362404+02:00"}
{"@level":"debug","@message":"using github.com/hashicorp/hcl/v2 v2.16.2","@timestamp":"2023-06-30T08:05:07.362408+02:00"}
{"@level":"debug","@message":"using github.com/hashicorp/terraform-svchost v0.1.0","@timestamp":"2023-06-30T08:05:07.362411+02:00"}
{"@level":"debug","@message":"using github.com/zclconf/go-cty v1.12.2","@timestamp":"2023-06-30T08:05:07.362413+02:00"}
{"@level":"info","@message":"Go runtime version: go1.20.5","@timestamp":"2023-06-30T08:05:07.362415+02:00"}
{"@level":"info","@message":"CLI args: []string{\"terraform\", \"plan\"}","@timestamp":"2023-06-30T08:05:07.362420+02:00"}
{"@level":"trace","@message":"Stdout is a terminal of width 214","@timestamp":"2023-06-30T08:05:07.362622+02:00"}
{"@level":"trace","@message":"Stderr is a terminal of width 214","@timestamp":"2023-06-30T08:05:07.362630+02:00"}
{"@level":"trace","@message":"Stdin is a terminal","@timestamp":"2023-06-30T08:05:07.362635+02:00"}
...
```

Are you using a different version?

**Comment by dcarrion87** [comment]
@mtojek The message came up inbetween message output. It could be version related but I just use the standard coder docker image. I am referring to both the output of the message I saw whilst starting the workspace in "Try in debug mode" and the docs after I did some further investigation.

**Comment by bpmct** [comment]
@dcarrion87 is this working for you now?

**Comment by dcarrion87** [comment]
@bpmct sorry for not updating earlier. I can confirm I no longer see the option to re-run in debug mode when a workspace start fails 👍
