### ISSUE TITLE
fix: pending alert flashes when I first create a workspace

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8254]
When I start a new workspace build on [dev.coder.com](http://dev.coder.com/), I notice the new "pending" modal flashes for less than a second before it's assigned to a provisioner. It's cool to see the new modal :tada: but a bit alarming to see it for only half a second (since there are no other builds in queue).

Thoughts on hiding it for the first 5 seconds (or a more elegant solution) to avoid it from flashing for under a second? (the user can't read it so it's just alarming).

https://github.com/coder/coder/assets/22407953/42e992e3-02cc-464c-9b59-70c2d1d5b425

**Comment by mtojek** [comment]
Resolved in https://github.com/coder/coder/pull/8309
