### ISSUE TITLE
Completely omit Terraform resources from workspace dashboard?

### ISSUE THREAD

**Issue by kconley-sq** [coder/coder#8267]
Some of our workspace templates create Terraform resources that we don't want to show users on their workspace dashboard to avoid confusing them about infrastructure they don't really care about or understand (e.g. we don't think there's much value in showing a https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id resource to a user). 

We currently use `coder_metadata`'s `hide = true` [feature](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/metadata#hide) to hide these resources by default from the workspace dashboard page, but we'd like to remove them completely from being visible to users (i.e. not even shown under the "Show hidden resources" button) to completely avoid any questions/confusion.

I'm also finding `coder_metadata`'s `hide = true` [feature](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/metadata#hide) can't be used in the case that resources come from Terraform modules which don't output IDs for all of the resources they create because I think I understand that we can't assign a `coder_metadata` resource to a module's resources unless the module outputs an ID for all of those resources so that we can use it as the value for https://registry.terraform.io/providers/coder/coder/latest/docs/resources/metadata#resource_id.

To that end, would it be possible to add support to Coder workspace templates for opting out of showing all resources on the workspace dashboard page entirely (not even under a "Show hidden resources" button) except for specific resources we would specify in the template (e.g. the one that has the Coder agent associated with it)?

Related: #4552 (cc @dcarrion87 in case you have any thoughts)

**Comment by MrPeacockNLB** [comment]
I can agree that this information is totally useless for our developers (e.g. random values or local file resources). So thumbs up for a feature to completly hide this resources from endusers.
