### ISSUE TITLE
Sourcing Terraform Variables from Within Coder

### ISSUE THREAD

**Issue by ElioDiNino** [coder/coder#8279]
Version: 0.24.1
[Original Discord Thread](https://discord.com/channels/747933592273027093/1123286675741753394)

## Problem

I have set specific `TF_VAR`'s (environment variables) inside of my coder instance running in Kubernetes and I want the terraform templates to use them. However when I create new templates using these variables coder complains and wants me to pass them in through the CLI with the `--variable flag`. The strange thing is that I can see the special env variables inside Coder are being read because all current templates show
```
terraform environment variable: TF_VAR_vault_role_id=<value redacted>
terraform environment variable: TF_VAR_vault_secret_id=<value redacted>
Initializing the backend...
Initializing modules...
...
```
when starting up (and I also see this when doing a template push with either garbage variable data or default values set for the variables in the tf). No matter what I have tried though, Coder doesn't actually use the `TF_VAR`'s it retrieves. The only way I can get these variables to be used is through this less than idea hack:
```
data "external" "vault_variables" {
  program = ["bash", "-c", "echo \"{\\\"role_id\\\": \\\"$${TF_VAR_vault_role_id}\\\", \\\"secret_id\\\": \\\"$${TF_VAR_vault_secret_id}\\\"}\""]
}
```

## Proposal

I'm not sure if I am doing something wrong (doesn't seem like it), if this is a bug, or if this is functionality that needs to be added. Either way, I would like for templates to have the ability to first check for applicable environment variables inside of Coder and use them before complaining that a user has not provided the required variables or just uses the default value set in the Terraform. I think what would make most sense is that by default when uploading a template to Coder, it first uses `TF_VAR`'s already defined and then relies on the `--variable` flag for anything missing. If a user passes a variable through the flag that is already inside Coder then it overwrites that value for this template.

## Images

Whenever a workspace is started:
![Screenshot 2023-06-30 at 9 03 33 AM](https://github.com/coder/coder/assets/52972357/021c785c-9c45-4f14-8ace-0924e0affc67)
![Screenshot 2023-06-30 at 9 04 25 AM](https://github.com/coder/coder/assets/52972357/f9669809-8e1d-415a-a119-208d167692c9)

When trying to upload a template that uses the variables inside Coder:
<img width="1199" alt="Screenshot 2023-06-30 at 9 08 22 AM" src="https://github.com/coder/coder/assets/52972357/ed0c27e5-bf08-4a3d-9103-b324480c6987">

**Comment by bpmct** [comment]
Ah interesting. I'd expect that Coder wouldn't prompt for these if they are set with `TF_VAR`.

**Comment by mtojek** [comment]
> I think what would make most sense is that by default when uploading a template to Coder, it first uses TF_VAR's already defined and then relies on the --variable flag for anything missing.

Frankly speaking `TF_VAR_...` is a Terraform variable, not a Coder one, but as long as we strongly depend on Terraform, this might be a valid feature request to expand it.
