### ISSUE TITLE
Port Forward Visual Bug

### ISSUE THREAD

**Issue by ElioDiNino** [coder/coder#8281]
Similar to #8235, this is another non-critical visual bug that occurs with a high number of items. In this case the issue is when the workspace has a bunch of ports being forwarded, some of them get cut off and are inaccessible.

![Screenshot 2023-06-30 at 10 01 57 AM](https://github.com/coder/coder/assets/52972357/617d26e7-8284-465e-8ea2-eda750695f10)

**Comment by sharkymark** [comment]
@deansheather @bpmct @matifali 

I like how GitHub Codespaces makes a row for each port.

We should consider this, and in sales I come across many accounts where they use Codespaces for personal or OSS projects with the free tier, so we are keeping things consistent when they transition to Coder as part of their company.

![image](https://github.com/coder/coder/assets/2022166/2f2f52ab-1ad4-4d9d-9968-c0a23932f929)

**Comment by matifali** [comment]
@sharkymark @BrunoQuaresma
Nice. If may also add a shortcut to change `share` type `public/authenticated`
By default each forwarded port is set to `share=owner`
I know it should be not possible for many enterprises to just make a port public but would be a great addition for OSS users and projects.

**Comment by BrunoQuaresma** [comment]
About this:

> Nice. If may also add a shortcut to change share type public/authenticated
By default each forwarded port is set to share=owner
I know it should be not possible for many enterprises to just make a port public but would be a great addition for OSS users and projects.

I think we would have to change the BE. @bpmct and @deansheather thoughts?

**Comment by deansheather** [comment]
> Nice. If may also add a shortcut to change share type public/authenticated
By default each forwarded port is set to share=owner
I know it should be not possible for many enterprises to just make a port public but would be a great addition for OSS users and projects.

This would require a significant rework of app sharing feature and if we don't have a significant need/want for it then we should postpone it. Template authors can add apps for ports they need to share for now

**Comment by matifali** [comment]
@deansheather if we want to reconsider this anytime in the future, I can create a separate issue.
