### ISSUE TITLE
Enhancement: print out to terminal where the webui is being served

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#830]
Currently I don't know where my ui was served, it would be nice to see `listening on localhost:3000` or something in the logs.

**Comment by Emyrk** [comment]
> I'm assuming this is for `coder server`, but it's not clear to me where this should be printed and/if it's different from `access-url` which we're already printing?
> 
> ```
> access-url: http://127.0.0.1:3000
> ```
> 
> Are there situations where `access-url` is not printed? Or is it not descriptive enough?

`access-url` is not the listening port. Eg it can be a tunnel.

```
access-url: https://fervent-austin7.try.coder.app
```

As a developer, I like when the logs state which port is being listened on locally

**Comment by tjcran** [comment]
I think the current experience in the CLI accounts for this, maybe in a slightly different way, and this is now somewhat irrelevant. Feel free to re-open if you disagree.
