### ISSUE TITLE
[Server] Each Build Template create a Version on UI

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#8307]
Hi Coders,

I found out each time I create a "Build Template", Coder will create a version even though the template didnt build correctly
![image](https://github.com/coder/coder/assets/97964900/eb0b5d0e-8294-4f11-b703-8a5d25d3e5c4)
The UI provide to promet version, but that versions are not correct. In my opinion that version should be temporal and discarded

**Comment by Emyrk** [comment]
Unfortunately creating a version is required to send the terraform to a provisioner and see if the template is valid.

What we should do is probably just delete the failed versions automatically.

**Comment by matifali** [comment]
@Emyrk yes. I agree, let's just remove them or may be not show in the UI only.

**Comment by TheZoker** [comment]
I also would like to be able to delete versions. For example by using the CLI:
```
coder templates versions delete Base v1.0.0
```

This will delete the version v1.0.0 of the Base template. 

Another nice feature would be to delete all old unused versions (similar to docker images).

**Comment by matifali** [comment]
We now support archiving old versions by using `coder templates archive`. See `coder templates archive --help` for all available options.
