### ISSUE TITLE
docs: Update Template ACL example doesn't make sense

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#8314]
https://github.com/coder/coder/blob/65112ecc04ca8a1c83815bb6a6e7eefc0f814300/docs/api/enterprise.md?plain=1#L1080

The example JSON body is

```json
{
  "group_perms": {
    "property1": "admin",
    "property2": "admin"
  },
  "user_perms": {
    "property1": "admin",
    "property2": "admin"
  }
}
```

What does this mean?  What are `property1` and `property2`?

A customer is trying to use this API and can't figure it out; neither can I from the docs!

**Comment by Emyrk** [comment]
This `property1` thing happens in all auto generated docs. I bet it's because the target is ` map[string]string` so swagger has no idea how to label them.

I will see if there is anything in the swagger docs to fix that

**Comment by Emyrk** [comment]
For this though, 
```json
{
  "group_perms": {
    "<group_id>": "admin",
    "<group_id>": "admin"
  },
  "user_perms": {
    "<user_id>": "admin",
    "<user_id>": "admin"
  }
}
```
