### ISSUE TITLE
`disable_everyone_group_access` is available in the coderSDK, but not in CLI nor UI

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#8325]
the `disable_everyone_group_access` field was recently added to the coderSDK ([code here](https://github.com/coder/coder/blob/418c9b8743677184f9892c50e704470429b343b7/codersdk/organizations.go#L120)), but is not configurable in the CLI or UI.

**Comment by Emyrk** [comment]
@ericpaulsen this actually is in the cli and UI.

Cli: `--private`

https://coder.com/docs/v2/latest/cli/templates_create#--private

UI:

![Screenshot from 2023-07-06 09-49-15](https://github.com/coder/coder/assets/5446298/deab112a-cc2c-491a-8a9b-8b972b0c5565)
