### ISSUE TITLE
Document predefined emoji/icon images

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8344]
When adding a workspace proxy, setting an icon for Coder app, etc you can set an icon URL. Right now, power users know to go to the template settings page to see the icon picker and get the right URL.

Can we add a `https://coder.example.com/icons` which just has the icon picker component so they can easily get an icon URL? It would also be nice if it statically rendered the paths for stuff like VS Code, JetBrains, and other icons we statically host. Then, in the `wsproxy create` help text and UI (and in the terraform provider docs) we can tell people to navigate there to see available icons.

**Comment by BrunoQuaresma** [comment]
Not sure if I got it 🤔 do you have any examples?

**Comment by bpmct** [comment]
Ah sorry! Several elements in Coder templates require an icon URL which is often an emoji in our `/emojis` or icon in `/icons`. However, there is not a good way to browse and search all icons except by going to the template settings page (+ it only shows emoji). It'd be cool to have a basic static site that helps the user pick an emoji that we can link to in docs + template comments.


![Screenshot 2023-08-16 at 12 44 04 PM](https://github.com/coder/coder/assets/22407953/32e19718-7115-47fc-941e-b71344130cbb)

**Comment by aslilac** [comment]
I think it'd be a bit nice to integrate this into the UI, rather than telling users "go find one over here and then come back"

Looks like the picker component we use supports custom emojis as well

**Comment by aslilac** [comment]
@bpmct can you think of any other places in the app where we should be showing a "picker" for this sort of thing but don't currently?

**Comment by bpmct** [comment]
> I think this is more for when users are setting emojis and icons on TF configuration.

Yeah agreed so I think it is fine as a detached page since most people will go to it from code comments. However, we could link to it from the template settings if it shows our icons too. 

Another idea is to show this on our docs or coder.com 🤷🏼

**Comment by aslilac** [comment]
> Another idea is to show this on our docs or coder.com but then it may drift across versions and not work for our enterprise customers offline networks

I've seen some stuff in the code base around offline docs but I don't exactly have all the context there. We could also just do both, especially if we could generate them from the same source of truth to prevent drift. Meet people where they're at, make things like this as discoverable as we can.

**Comment by matifali** [comment]
I like https://devicons.railway.app/

**Comment by aslilac** [comment]
I especially like that they have some language icons in there (Rust, Go, TS). I think we could benefit from those as well, so that you could have multiple Docker templates with better icons.

**Comment by bpmct** [comment]
Agreed!

**Comment by matifali** [comment]
@aslilac, is it at `/icon` or `/icons`?
When we use builtin icons in our templates, we use the `/icon` path.

Also, let us keep this open until we document how to use this.

**Comment by aslilac** [comment]
which is why it can't be /icon. that would be a routing conflict. plus it just sounds weird.

**Comment by matifali** [comment]
Or we can just rename it to /icons and mark as a breaking change. As it will need app users to update their templates. 
Thoughts @bpmct ?

**Comment by aslilac** [comment]
that would also be a routing conflict. 😅

**Comment by aslilac** [comment]
what places _exactly_ do we need to document this to close the issue?
