### ISSUE TITLE
Show login type in `Users` page and allow converting from `OIDC` to `built-in` and back

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8346]
Let's do this in conjunction with #5002. Only a User Admin and above should see the lists of users and groups. Users should see what groups they are in from the "Accounts" dropdown. This also means User Admins should be the only ones who can configure what users/groups can access or modify templates.

In the `Users` list, add a row with the user's login type. @Emyrk explained that it may not be great to allow admins to convert between accounts since there may be an email mismatch. However, I don't think there are security risks (just an inconvenience) since the user would own both emails. To fix, the admin would need to convert back to `OIDC` to `built-in` and allow the user to authenticate them myself. Perhaps I am misunderstanding though? I guess the security risk would be the admin set the wrong email for the built-in account which is not owned by the user. I think this is still acceptable unless there is evidence of this being handled differently in other enterprise products.

We don't need this before we allow users to switch to OIDC themselves but is a good follow-up and was requested by a major customer.

**Comment by bpmct** [comment]
I see. How do you expect this to work with #7126? I suppose its less of a problem during creation?

**Comment by Emyrk** [comment]
We also have a `LoginTypeNone` which disables authentication for the user. So if we need a `pending` state for the auth, we can use `LoginTypeNone`.


As for how does an admin create an oidc account, I think we'll have to do something similar to V1, or make them generate some code or token a user can use to signup. 

The switching back to `built-in` is just something that does not make much sense to me. Why would someone want to go from `oidc` to `built-in`?

**Comment by sharkymark** [comment]
@Emyrk is there a use case to let a recently changed from password to OIDC, to revert back to password?

Seems like the user is forever ODIC after conversion.

CC @shaun

**Comment by Emyrk** [comment]
@sharkymark I don't think it is as strong of a use case. OIDC is managed externally, user/pass is managed by the user.

So when you convert to OIDC, you pass authentication to the deployment configuration. If you allow converting back, then the deployment IDP loses control of the user and potentially role/group sync.

So although I see the demo case for converting back and forth, in practice I think only admins should convert a user back to password auth.
