### ISSUE TITLE
VS Code Desktop still shows `Direct` connection with site-wide `CODER_BLOCK_DIRECT` environment variable set

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8348]
In `0.25.0` we have a new environment variable `CODER_BLOCK_DIRECT` which if set to true, will force SSH (and IDEs like VS Code Desktop) to go through the DERP proxy relay and not Peer-to-Peer aka Direct.

I think VS Code Desktop is in fact going through the DERP, since the latency matches the CLI's `coder ping` latencies which also clearly states it is through DERP, so maybe Coder's VS Code Remote Extension needs to be tweaked.

![image](https://github.com/coder/coder/assets/2022166/6bb7f191-de39-473a-b73e-7641b96b665e)

![image](https://github.com/coder/coder/assets/2022166/b32fec21-8a10-4efc-8fdc-6f2f70ccccc6)

values.yaml config:
![image](https://github.com/coder/coder/assets/2022166/52e26fe6-fca2-4aa0-9c57-52e52393ae8b)

agent connection endpoint confirming environment variable is properly set
![image](https://github.com/coder/coder/assets/2022166/9cac33ed-de85-4407-ba19-830da0d7252b)

**Comment by matifali** [comment]
Should this be moved to https://github.com/coder/vscode-coder?

**Comment by deansheather** [comment]
Shouldn't be moved because the connection code is in this repo.

It should be implemented for `coder vscodessh`, but the CLI that the extension installs needs to be up-to-date. Could you check the version of the CLI that was installed by the extension and ensure it's up to date?

**Comment by sharkymark** [comment]
@deansheather where does the extension put the CLI?

**Comment by deansheather** [comment]
I'm unsure on every platform, maybe @kylecarbs knows? You could probably find it by running `ps aux` or equivalent while you're connected.

**Comment by matifali** [comment]
I guess the extension always pulls the latest cli from the coderd on every new connection.

**Comment by sharkymark** [comment]
@deansheather I removed the CLI and confirmed the extension downloaded the latest, and it shows Direct in the Coder Remote tray in VS Code Desktop

**Comment by kylecarbs** [comment]
If a customer reports this please reopen, but closing for now.
