### ISSUE TITLE
Add ability to pre-populate a list of static parameters for a template

### ISSUE THREAD

**Issue by Shocktrooper** [coder/coder#8375]
Sometimes when creating a template there is a finite list of options you want a user to have that are not static E.G. CPU, RAM.  Unfortunately it does not seem possible to query an external URL, service or endpoint to get a dynamic list of parameter options for a user to make available in a template.  
Some of the places where this could be useful

- Querying the list of available repos a user has access to for cloning
- Populating a list of available dotfiles from a repo root and specifying which one to run
- Populating a list of available dotfiles from a users home directory and specifying which one to run
- Getting a list of aliases a user has for authentication from a centralized external authentication system
- etc.

I would like a datasource or a separate script field made available where it would be run as a user fills out a template for workspace instantiation.  The data would then populate a list for a parameter that the user could then select from

Example implementation
```hcl
data "coder_parameter" "user_repos" {
  name         = "user_repos"
  display_name = "Clone Repo"
  options      = data.coder_parameter_script.user_repos.output
}

data "coder_parameter_script" "user_repos" {
  script = <<EOF
# Pseudo Code
#!/bin/sh
RAW_DATA=$(Some Curl call to get available repos for a user)
PROCESSED_DATA=$(Some JQ magic to manipulate the data into something coder can ingest for a parameter)
OUTPUT_VAR=$PROCESSED_DATA
EOF
}
```

**Comment by ammario** [comment]
The most Terraform way to do it (that I can think of) is making `coder_parameter` a resource instead of a data source. Then, it could depend on a utility provider (e.g. [http](https://registry.terraform.io/providers/hashicorp/http/latest/docs)) to generate options.

But, I don't think a breaking change like that is worthwhile without more use cases.
