### ISSUE TITLE
Custom logo and text in login screen

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8395]
Some companies have a custom name / branding for their internal dev envs platform but wish to use Coder. To make it more "sticky," we can offer a custom logo and text in the log in screen.

<img width="734" alt="Screenshot 2023-07-10 at 10 22 01 AM" src="https://github.com/coder/coder/assets/22407953/38b67d6d-2b83-4e34-9987-ab109ad9fdf6">

**Comment by bpmct** [comment]
We already support configuring this in "Appearance" but it doesn't show up here. We will need to add a text field to change "Coder" to something else. e.g. "Devbox"

**Comment by matifali** [comment]
@bpmct thoughts on allowing name change to only enterprise customers. We can allow changing the icon only to OSS users.

**Comment by BrunoQuaresma** [comment]
We can add in the appearance the "Company name" field and show it on the login page. So just to confirm, when the deployment has the logo setup it should be displayed with the name on the login screen. Is that right @bpmct ?

**Comment by mtojek** [comment]
ping @bpmct

**Comment by mtojek** [comment]
Ok, I have spent some time researching, and I'm going to work on the backend side.

Battle plan:

- [ ] Expose `application_name` via `/appearance`
- [ ] Customize `application_name` in `<meta property` to reflect data stored in appearance
- [ ] Expose `logo_url` via `<meta property` *
- [ ] site: Adjust login form to consume `application_name` and `logo_url`
- [ ] site: Add "Application name" field to "appearance" API

* - I know that we have it exposed via `/appearance` API, but it is not available until the user signs in.
