### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8396]
Some users prefer to use a light mode!

**Comment by sharkymark** [comment]
Light mode is the default to Coder v1 as well.

**Comment by alexander-dammeier** [comment]
Here in the EU/Germany there are currently some laws on the way that will force some areas to only use software with good accessibility. This includes for example high-contrast UIs, the usage of screen readers, keyboard-only navigation and the possibility to zoom up to 400%.
We are currently evaluating coder for some customers which will be affected by that and already have high standards for accessibility. Could you please keep that in mind while working on that? Currently i am not aware of how good coder already is with accessibility and of course coder also don't need to be perfect (i don't know any software that is) but that could make things way easier in the long term here.

**Comment by matifali** [comment]
Related to https://github.com/coder/coder.com/issues/306

**Comment by matifali** [comment]
cc: @aslilac as you were recently looking into this.

**Comment by bpmct** [comment]
We're actively working on a light theme! It should be out in the next 1-2 releases :)

**Comment by aslilac** [comment]
> Following up on this 😃

hi! specifically, I'm the one working on it. progress has just been a bit slow with holidays and some travel popping up lately, but we've got an early version that I'm currently working on polishing up.

**Comment by mattlqx** [comment]
FYI, our logo in the upper-left basically disappears when using the Light theme.

**Comment by aslilac** [comment]
yeah, issues with custom icons/logos are pretty much the main reason that it's marked as a "preview" instead of a stable feature

**Comment by aslilac** [comment]
happy to hear it! feel free to share any issues you notice here. (icons have already been fixed, and will in the next release)

**Comment by ammario** [comment]
@aslilac what work remains to getting light theme out of "preview" mode and closing out this issue?

**Comment by aslilac** [comment]
I haven't been hearing any bug reports about in lately, so maybe nothing?

**Comment by mattlqx** [comment]
Any solution to the white/black logo problem in that if your logo is either color it will disappear on that color theme?
