### ISSUE TITLE
Provide a barebones example template 

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8404]
Let's suppose you want to build a Rackspace template. Currently, you must pick an example template with resources (e.g. docker, digitalocean, etc) and modify it. In the CLI, this flow is OK, but you can't really do this in the web template editor since you have to wait for a build to succeed before you can edit the files. If you happen to have another cloud working (docker, digitalocean, etc) this is fine but there is no way to "start from scratch."

@mtojek also suggested something like https://start.spring.io/ which could be on coder.com, our registry, or built into the template editor, to help users write or customize their templates. @BrunoQuaresma has worked on something similar as well. Both are good for common infra (e.g. Docker, Kubernetes) but not if someone is building a template for a new cloud/platform.

**Comment by matifali** [comment]
I have another idea to allow creating a template from scratch by using the template editor.
See: https://github.com/coder/coder/issues/8449
