### ISSUE TITLE
Almost 1 gb in /var/cache/coder?

### ISSUE THREAD

**Issue by steveiliop56** [coder/coder#8405]
Hello,

I noticed that the ``/var/cache/coder`` is almost 1 gb and it contains a lot of executables that are not even the architecture of my machine (raspberry pi). Is this normal or some kind of bug?

**Comment by matifali** [comment]
I checked on my deployment, and it is safe to remove this directory, Coder will automatically create it again on the next upgrade/install.
It looks like it is storing coder-slim binaries, terraform binary and terraform providers for the current and previous versions of Coder.

**Comment by matifali** [comment]
Thanks for reporting this. We should look into auto cleanup.
