### ISSUE TITLE
Logout fails to clear OpenID Connect session - coder/keycloak integration

### ISSUE THREAD

**Issue by Yanbin-Fu** [coder/coder#8413]
I used the self-hosted coder with OpenID Connect by keycloak. When I logout successfully and back to the login page, the session is still alive at keycloak. If I click the "OpenID Connect" button, it will directly redirect to workspace without inputting username/password again. How can I configure it to clear the sessions in keycloak during logout?

**Comment by bpmct** [comment]
Hi @Yanbin-Fu. I believe Coder's current behavior is in-line with the OIDC spec, it only invalidated Coder's token not the one from the identity provider.

Is there other software that you use with OIDC that will also invalidate the identity provider token when the user logs out? It looks like it _technically_ possible for us to do this, but it is not standard.

**Comment by Yanbin-Fu** [comment]
Thank you for the explanation. I appreciate the rationale behind the current design. However, I'd still prefer to have an option to toggle whether to invalidate the session or not. This would provide more flexibility to adapt to different use cases.

**Comment by schettn** [comment]
> Hi @Yanbin-Fu. I believe Coder's current behavior is in-line with the OIDC spec, it only invalidated Coder's token not the one from the identity provider.
> 
> Is there other software that you use with OIDC that will also invalidate the identity provider token when the user logs out? It looks like it _technically_ possible for us to do this, but it is not standard.

I do not think this is true. Coder does not support [RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout), although many other resource servers does. 

Many resource servers support this via an optional `CODER_OAUTH2_CUSTOM_LOGOUT_URL` variable. If set, the user will be redirected to the `OP` on logout, which then redirects back to coder via `post_logout_redirect_uri `.

**Comment by asdorsey** [comment]
EDIT: Removed incorrect information; my "workaround" isn't functional.

EDIT 2: With Keycloak, following the instructions to enable refresh tokens at https://coder.com/docs/admin/users/oidc-auth/refresh-tokens had the side effect of making logins work as intended.  I'm not sure if I changed something on the Keycloak side for that to work.
