### ISSUE TITLE
experiment: remove build logs when a workspace is started/stopped

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8417]
I feel like these should only show when the workspace is building, not before/after.

<img width="1498" alt="Screenshot 2023-07-11 at 7 45 50 AM" src="https://github.com/coder/coder/assets/22407953/062c7f5e-022b-4dd5-9533-7da0bf396164">

**Comment by BrunoQuaresma** [comment]
For this case, the user can just close the build logs right?

**Comment by bpmct** [comment]
I don't think the logs should ever show up by default on a workspace that is started, it feels much more natural if they  disappear once the build is complete.

**Comment by BrunoQuaresma** [comment]
Ok, making this change, I think we can remove the "feature" to hide/show the build logs right since they are now displayed only certain statuses. wdyt?

**Comment by bpmct** [comment]
Yeah, totally works.
