### ISSUE TITLE
Example Epic 

### ISSUE THREAD

**Issue by misskniss** [coder/coder#842]
**Epics** represent the over arching need / purpose of a collection of related tickets. 
At this level, your description should describe this overarching need / purpose. 
The epic should then be "shredded" by you, the team, PM or EM into the related tickets that will accomplish/represent the entire scope of its work.
_Note: Epics can be part of other epics. Try NOT to embed 2-epics deep or more though. It gets messy._

-----

- [x] https://github.com/coder/coder/issues/843

-----

### User Story 👤
As a ______ I want ______ so that ______.

Ex:
As a user of this codebase, I want to see how to correctly fill out an Epic with issues so that we have consistent and meaningful descriptions and grouping of the work that needs done. 

### Acceptance Criteria ✅
Describe what 'done' means for this work. 
Attach annotated screen shots &/or mock ups where possible. 
List the expected functionality.

### Implementation Notes 📝
List/describe solution approaches, things to consider, warnings, questions, etc here. 

### Reproduction Steps :bug: 
If this issue is a bug, describe how to reproduce the bug. Technically - if you can reproduce it, it is not really a bug. 
Include any annotated screencaps that would help someone see or repro the bug. 

### Resources 📎
Use this to add links to useful things, screencaps, recording or any supplemental info you find useful to the issue. 

- RFC link
- Slack links
- Notion links
- External links
- Stack traces
- etc...

-----

### Set the Fields
 🏷️  **Pipelines**
If this issue is going to / should be worked on in the current sprint, add it to the 'This Sprint" pipeline. 
Otherwise, all issue by default go to the New Issues pipeline unless you specify otherwise.

 🏷️  **Projects**
For this codebase, we are using the `Workspaces V2` project.  
<img width="345" alt="Workspaces V2 project" src="https://user-images.githubusercontent.com/2394436/161463138-288a1b2b-262e-4058-8895-7bee03138110.png">

 🏷️ **Labels**
This can include any/multiple applicable labels. 
If you know for sure what milestone it belongs to, label it as such. 
If you do not know which milestone, that is okay, we will label it in planning/grooming sessions.

A word on labelling types of issues: 
`Bug`  Something is not working the way it was programmed to work.
`Enhancement` It is working the way we programmed it to, but we want to **_modify_** it.
`New feature` It does not exist yet an we want to add it. 

_Note: the reason we also use a label to indicate a milestone is that Zenhub is deprecating their use of milestones so Zenhub users will need it to know what milestone it is in. We are aware it can seem duplicative but it IS very helpful._ 

🏷️  **Assignee**
If you are planning to work on the issue, adding yourself here.
You can assign more than just one person. 
Otherwise assignees will be added as per our usual planning/grooming sessions. 

🏷️ **Sprint** 
If you or another contributor intend to work on it in a particular sprint, or you know it has to be done in a particular sprint, tag it as such.
Otherwise it will get tagged with a sprint in our planning/grooming sessions. 

_Note: Zenhub only supports 3 sprints into the future._ 

🏷️ **Milestone**
If you know for sure what milestone it belongs to, set it. 
If you do not know which milestone, that is okay, we will label it in planning/grooming sessions.

_Note: the reason we also use a milestone is that vanilla github supports it, and it makes looking at just milestone views in  Github handy. Even though Zenhub is deprecating the userof milestones, we still use them for non-zenhub users.  We are aware it can seem duplicative but it IS very helpful._ 

🏷️ **Estimate**
We use Fibonacci numbers up to 13 when using Zenhub. 
13 is VERY large complexity and could be seen as an issue that should be broken out to a milestone with one or more epic. 
If you are using Zenhub, feel free to nominate users to help you estimate it. 

_Note: It can seem faster to just point it yourself but you will get useful insight by getting others involved. It is our culture to get others involved in poiniting, particularly one person per stack (frontend/backend)_ 

🏷️ **Epic**
If your issue belongs in an epic, add it to the epic by selecting the epic it belongs to from this field.
If your issue should **_be_** an epic, use this field to convert it to one (if you are using Zenhub), or use the `Epic` label (if you are not using Zenhub)

🏷️ **Releases**
You can usually leave this one blank unless you know _FOR SURE_ we have elected to add this issue to  a release.

**Comment by bpmct** [comment]
@misskniss are we still using this format?
