### ISSUE TITLE
CLI: Error 'check versions error' during

### ISSUE THREAD

**Issue by midub** [coder/coder#8430]
Version: [`v0.26.0+bf8af90`](https://github.com/coder/coder/commit/bf8af90d5af6f887bb6574b73307e5cfdd65afd5)

After update from 0.25 to 0.26 using installation script on ubuntu.
Almost any CLI command results in following error:
`
check versions error: build info: invalid character '<' looking for beginning of value
running command "coder delete": invalid character '<' looking for beginning of value
`
![image](https://github.com/coder/coder/assets/37038617/13e8df9b-cb9a-4493-b327-ca0da5344bba)

**Comment by matifali** [comment]
I am not able to reproduce on both Windows and Ubuntu. Using 0.26.0

**Comment by bpmct** [comment]
I've seen this in cases where the Coder URL is wrong (or behind an identity-aware proxy that is unauthenticated). 

Do all of these commands work as expected?

```sh
$ coder --help

...
Global Options 
Global options are applied to all commands. They can be set using environment
variables or flags.

      ...

      --global-config string, $CODER_CONFIG_DIR (default: /Users/benpotter/Library/Application Support/coderv2)

...

$ cat "/Users/benpotter/Library/Application Support/coderv2/url"
https://dev.coder.com

$ curl https://dev.coder.com/healthz
OK
```

**Comment by midub** [comment]
I got `<a href="https://workstation-wsl.taild87b1.ts.net">Temporary Redirect</a>` when calling healthz endpoint, because I have redirect option on (CODER_TLS_REDIRECT_HTTP=true).
I tried to set correct url in '.config/coderv2/url' and It did not help.

**Comment by midub** [comment]
The url file is rewritten on service start.

**Comment by midub** [comment]
If I pass url param with correct url It works. I am sorry you can close the issue. If you want you can tell me how to set default url. Thank you.

**Comment by midub** [comment]
It was very simple, had to do login procedure `coder login <url>` again.
