### ISSUE TITLE
Support consumable Coder components in React-based development portals

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#8444]
Let's make our Coder components ready for use in React-based self-service development platforms, like Backstage. This lets teams easily integrate with Coder while still having the freedom to show off their unique UI design and style.

Here's an example:

```tsx
import WorkspaceBuildLog from "@coder/components/WorkspaceBuildLog"
import WorkspaceTerminal from "@coder/components/WorkspaceTerminal"
import PortForwardDialog from "@coder/components/PortForwardDialog"

const CustomDashboard = () => {
    // Write your own logic for fetching from the API...
    const { agent, build } = fetchThings()
    
    return (
        <div>
            <WorkspaceTerminal agent={agent} />
            <WorkspaceBuildLog build={build} />
            <PortForwardDialog agent={agent} />
        </div>
    )
}
```

Most of our components are already abstracted to work with Storybook, so I believe exporting some of these would be quite easy.

**Comment by BrunoQuaresma** [comment]
The components are quite opinionated on how we fetch things so would be nicer to export the fetch functions as well as a JS SDK. Also, some components need some "love" to run in isolation.
