### ISSUE TITLE
templates: allow creating new templates from the UI using template editor

### ISSUE THREAD

**Issue by matifali** [coder/coder#8449]
| **Before** | **After** |
| --------- | -------- |
|![image](https://github.com/coder/coder/assets/10648092/4bcf24a8-3f66-43f5-80b3-d9336186851c) | ![template_creation](https://github.com/coder/coder/assets/10648092/002aa8f7-6976-4072-8251-6c7146cbf36b) |

It would be super helpful to start creating a template from scratch. We should use the existing template editor and allow the user to paste or write terraform code.

**Comment by bpmct** [comment]
Totally agree!

**Comment by BrunoQuaresma** [comment]
Closed by https://github.com/coder/coder/pull/12082
