### ISSUE TITLE
Improve release workflow

### ISSUE THREAD

**Issue by matifali** [coder/coder#8470]
Currently, we do manual releases with an automatically generated changelog that includes all PRs merged since the previous release.

## Improvements

We want to improve the release workflow to have the following additional features.

### Must have

- [ ] #8472 
- [ ] #8582

### Nice to have

- [ ] Minor releases are predictable (e.g., every month)
- [ ] Make the process automated. We may consider using https://github.com/semantic-release/semantic-release or https://github.com/googleapis/release-please

PS: @bpmct and I discussed this in our 1-1. I am copying most of the stuff from Ben's notes on Notion.

**Comment by bpmct** [comment]
Closing in favor of https://github.com/coder/coder/issues/8929
