### ISSUE TITLE
Patch a previous release

### ISSUE THREAD

**Issue by matifali** [coder/coder#8472]
Some users may be unable to switch to a new major/minor release due to breaking-changes/policies and prefer a patch for a bug fix. 

Currently, we can not patch a previous release with a fix.
For this to work, we may have to create a new branch for each minor release.
Related #8470

**Comment by matifali** [comment]
I guess this is partially resolved by https://github.com/coder/coder/pull/8469

**Comment by mafredri** [comment]
@matifali, true, but I think this is worth keeping open, we can't always count on the breaking changes being benign enough to benefit from #8469.

**Comment by bpmct** [comment]
Closing in favor of https://github.com/coder/coder/issues/8929
