### ISSUE TITLE
Add `order` to `coder_parameter` options

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8485]
Parameters have an [order](https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/parameter#order) but the options in a select field do not. Could we also add an order to that?

**Comment by matifali** [comment]
Agent metadata too

**Comment by matifali** [comment]
We still want this behavior b

**Comment by mtojek** [comment]
@matifali I did a quick investigation, and parameter options are stored in database as an array field which preserves the order. There is no point in adding `order`, as it would be redundant.

Proof:

<img width="479" alt="Screenshot 2024-02-07 at 11 28 53" src="https://github.com/coder/coder/assets/14044910/5dd62c13-8967-4a06-893e-5049d1ee5950">
<img width="454" alt="Screenshot 2024-02-07 at 11 29 02" src="https://github.com/coder/coder/assets/14044910/632a8590-8ba3-423b-9d7e-c7d09e546e89">
<img width="378" alt="Screenshot 2024-02-07 at 11 29 08" src="https://github.com/coder/coder/assets/14044910/1ce48ab3-2818-4bbf-a2ab-f28fa93c41bd">

**Comment by matifali** [comment]
Thank you @mtojek. If we can use the order of the file, then there is no need for it, and we can close it. I wonder why it was reported initially. Did anything change later that added the order from a file?

**Comment by mtojek** [comment]
I'm not sure. I suspect that we had a bug in UI that resorted items. Anyway, I'll close it now.

Thank you for the reply!

**Comment by matifali** [comment]
`coder_paramter` follows the order in which they are written in the file, so we are not doing this.

cc: @bpmct
