### ISSUE TITLE
Sometimes "Refresh Latencies" spins forever

### ISSUE THREAD

**Issue by mafredri** [coder/coder#8493]
This seems like a frontend bug since all requests have completed (inspecting in devtools), but some regions are left spinning.

Europe:
<img width="350" alt="image" src="https://github.com/coder/coder/assets/147409/b7598525-4ff4-4d88-aeed-e5afd5b4e83f">
Sydney:
<img width="353" alt="image" src="https://github.com/coder/coder/assets/147409/9179bc78-7dfa-4520-a792-5d19218dd49b">

Etc. Reproducible by monkey-clicking the refresh latencies button (doesn't need to be in quick-succession).

**Comment by bpmct** [comment]
I did a lot of clicking and wasn't able to reproduce. Going to close this one out for now.
