### ISSUE TITLE
quota: quota is not getting freed when a workspace is stopped

### ISSUE THREAD

**Issue by matifali** [coder/coder#8499]
1. I have a total quota of 150 from two groups (100 + 50).
2. I have 3 workspaces running with `daily_cost = 50` for the `docker_container` resource.
3. I stopped 1 of the workspace and tried to create a 4th workspace, I get 
![image](https://github.com/coder/v2-customers/assets/10648092/048fb0fb-ad95-4477-87c7-ddb45b8d597e)
Even though 50 units of quota should be freed from the stopped workspace.
4. The stopped workspace shows 
![image](https://github.com/coder/v2-customers/assets/10648092/9fefd20f-65c8-4afd-ba31-861a4a7cf846)

**Comment by matifali** [comment]
I experimented more and observed that a stopped workspace is not freeing up the quota.

**Comment by ammario** [comment]
Could you share your template? Are you positive the `daily_cost` field is on the ephemeral resource?

**Comment by matifali** [comment]
@ammario Here is the template I am using.
https://github.com/matifali/coder-templates/tree/main/deeplearning

**Comment by ammario** [comment]
Gotcha. Unfortunately I don't have time to investigate this in the near-term.
