### ISSUE TITLE
group sync: add sequence diagram to docs

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8518]
We had a customer ask about a sequence diagram of how our group sync works. This would be a good thing for us to add to our docs since we've had several questions about this

**Comment by Emyrk** [comment]
Thoughts? I made this an SVG. I think we need to play with the colors to make it work on dark mode maybe. The light theme hurts my eyes.

![OIDC Diagram drawio](https://github.com/coder/coder/assets/5446298/a2401a09-c21f-4956-b8ca-2689f82dde6e)

**Comment by Emyrk** [comment]
closed by https://github.com/coder/coder/pull/9089
