### ISSUE TITLE
Alert on panics (for telemetry-enabled deployments)

### ISSUE THREAD

**Issue by ammario** [coder/coder#8523]
We did a regression review on #8351 and decided to set up alerting on new panics encountered by the coder server when telemetry is enabled. At the very least, panics should stream into a Slack channel with myself, @kylecarbs, and @bpmct.

This data may already be getting into Honeycomb—whoever implements this should check with @coadler first.

**Comment by coadler** [comment]
I don't believe this is currently making it into Honeycomb.
