### ISSUE TITLE
Running wsproxy not showing healthy in dashboard

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8532]
Version: [`v0.26.1+a0fedeb`](https://github.com/coder/coder/commit/a0fedebd624e8ba3b03052c3301876f220d851ef)

The use case is I have EKS deployment and created a wsproxy in GKE.

I can successfully curl the wsproxy and pull up the dashboard message in a browser that redirects me to the EKS deployment's access url.

However in the wsproxies dashboard, it continued to show:

```
UNHEALTHY
Not available
Errors
unexpected status code 400
```

Which was expected when I first installed the wsproxy and had not yet created DNS entries.

I had to scale the EKS deployment from 2 to 0 replicas and scaled up to 2, and then the wsproxy showed healthy.

**Comment by bpmct** [comment]
@Emyrk any ideas why this didn't retry? If this is an expected behavior and requires a restart, that is fair. I'm OK closing this one out.

**Comment by Emyrk** [comment]
Health checks are done every minute I believe. The unexpected status code though makes me think something else was going on :thinking:
