### ISSUE TITLE
Devcontainer fails to build

### ISSUE THREAD

**Issue by Tirzono** [coder/coder#8540]
I am running a k3s cluster with `local-storage` as my default storage class. I am using the following template (with the changes done in #8539):

https://github.com/coder/coder/blob/main/examples/templates/devcontainer-kubernetes/main.tf

When using one of the example repository (vercel/next.js), I get the following error while starting a workspace:

```
Failed to build: error building stage: failed to get filesystem from image: error removing var/run to make way for new symlink: unlinkat /var/run/secrets/kubernetes.io/serviceaccount/..data: read-only file system
```

Note the same errors appears with the other example repositories.

I am not entirely sure whether this is a bug in coder, envbuilder or something on my side when it comes to the configuration of my cluster, but please let me know if it's something on my side or whether I should open an issue in the envbuilder repository.

**Comment by kylecarbs** [comment]
This is a bug with envbuilder we'll fix!

**Comment by kylecarbs** [comment]
@Tirzono v0.2.0 of envbuilder will be coming out shortly. It should _just work_, but let me know if you have any problems. I'll ping here once it's out.

**Comment by kylecarbs** [comment]
v0.2.0 is pushed! Try updating the image and LMK if that works.
