### ISSUE TITLE
Workspace build is pending banner shown after start

### ISSUE THREAD

**Issue by mafredri** [coder/coder#8542]
I just noticed the pending banner stuck around after start (opening a new window didn't show the banner). Eventually, once started and waiting for agent, the banner disappeared, though.

<img width="1372" alt="image" src="https://github.com/coder/coder/assets/147409/49b5e68c-4f65-43c1-abd9-7a09c8224ff3">

**Comment by sharkymark** [comment]
I noticed this behavior once as well, but not sure what caused that.

**Comment by BrunoQuaresma** [comment]
@mafredri I saw this banner before but I've been not able to reproduce this rn

**Comment by mtojek** [comment]
@BrunoQuaresma this should be fixed now, right?

**Comment by BrunoQuaresma** [comment]
Yes!
