### ISSUE TITLE
Explain reason in "Workspace is unhealthy" dialog

### ISSUE THREAD

**Issue by mafredri** [coder/coder#8543]
UI can be confusing when agent is unhealthy.

<img width="1388" alt="image" src="https://github.com/coder/coder/assets/147409/f5983445-6a6f-48c6-83cb-1e1edf13f368">

In the above picture, that startup script has failed, however, this is not really shown. The agent having a green dot adds to the confusion and the only hint is the red line on the side. But no explanation as to why.

For contrast, the error for an agent that is unable to connect is very discernible:

<img width="1388" alt="image" src="https://github.com/coder/coder/assets/147409/d13878c2-afb5-4718-9614-a5903640eadf">

**Comment by bpmct** [comment]
I agree. It would be nice to show the reason in the long text. For example, is the agent taking a while to connect, or did the startup script fail?

**Comment by BrunoQuaresma** [comment]
@mafredri how can I reproduce this error? I would love if you could make that happen on a workspace on dev.coder.com

**Comment by mafredri** [comment]
@BrunoQuaresma this might've been fixed? I'm not seeing it currently so let's close it for now. If I notice it again I'll re-open.
