### ISSUE TITLE
Improve Coder documentation for end users

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8550]
Most of https://coder.com/docs are written with admins and template authors in mind. We should investigate how we can provide a basic "user guide" that covers these common use cases:

- Creating a workspace
- Connecting via an IDE (VS Code, JetBrains Gateway) or web IDE (on dashboard)
- Port-forwarding via `coder port-forward`
- Dotfiles via `coder dotfiles`
- Workspace schedules and auto-start
- What else?

This will probably require moving around a decent amount of pages. Perhaps we can use https://diataxis.fr/ as a reference. Let's also be sure to set up redirects to avoid breaking any links

**Comment by kylecarbs** [comment]
We have better short-term issues to assist with this.
