### ISSUE TITLE
Automated tests for example templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8551]
Let's run automated tests against our example templates running GitHub actions. Instead of doing this per-PR, this is probably something that is best done nightly with Slack alerts when a test fails.

## Test criteria

- Template creation works
- Workspace creation works
- Workspace becomes healthy and user can `ssh`
- Workspace deletion works

## Nice-to-have

We also test start/stop to ensure the compute is updated as expected.

## Implimentation notes

We have ephemeral preview deployments with `/deploy-pr`. That is one way to do it, or we do it via end-to-end tests.

**Comment by MrPeacockNLB** [comment]
We are also planing to use e2e tests with playwright to test our template in various ways. Looking forward how to test WebTerminal features like programs works as espected.
