### ISSUE TITLE
Return user's groups as a Terraform data source for templates

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8560]
There may be cases where a template wants to be aware of the user's groups for infrastructure to provision/tags to add, etc.

The easiest way to do it seems like sending them as an array of strings in https://registry.terraform.io/providers/coder/coder/latest/docs/data-sources/workspace

```hcl
data.coder_workspace.me.owner_groups
# ["devops", "platform-engineering", "backstage"]
```

## Use cases

User must be in `devops` group for this to be provisioned as a part of their workspace:
```hcl
resource "special_resource" "for_devops" {
  count = contains(data.coder_workspace.me.owner_groups, "devops") ? 1 : 0
}
```

Add groups as a tag to an resource:

```hcl
resource "aws_instance" "example" {
  tags = {
    Name        = data.coder_workspace.me.name
    OwnerGroups = join(",", data.coder_workspace.me.owner_groups)
  }
}
```

Look up IAM policy based on groups:

```hcl
data "aws_iam_policy" "dynamic" {
  count = length(data.coder_workspace.me.owner_groups)
  arn   = "arn:aws:iam::aws:policy/${element(data.coder_workspace.me.owner_groups, count.index)}"
}
```

**Comment by matifali** [comment]
Who ever is going to take this. We should probably do https://github.com/coder/terraform-provider-coder/issues/180 first before adding any major features to the provider.

**Comment by f0ssel** [comment]
@matifali My change was just a few lines of code, so I wouldn't want that refactor to block this.

**Comment by matifali** [comment]
It would be nice to publish docs for a use case or a [guide](https://coder.com/docs/v2/latest/guides) on how groups can be used within templates.
The original issue body of this issue, #7191 and #11807 are some possible examples.
