### ISSUE TITLE
Bug: The workspace is showing pending when should be starting

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#8566]
After adding the build logs on the workspace page, I started to notice that sometimes, the BE does not send stats updates to the FE. In this case, after starting a workspace, it shows pending when in the logs it is starting. I was able to reproduce that using a workspace with the docker starter template.

<img width="1679" alt="Screen Shot 2023-07-17 at 15 05 36" src="https://github.com/coder/coder/assets/3165839/3c3f304d-be74-4fc4-be34-ea77f47e62d8">

**Comment by ammario** [comment]
I'm experiencing this as well.

**Comment by sharkymark** [comment]
@BrunoQuaresma I'm still seeing this in `2.1.2`

![image](https://github.com/coder/coder/assets/2022166/28c6470d-4fcb-4958-9b95-c2593b69eb6d)

**Comment by BrunoQuaresma** [comment]
Fixed by https://github.com/coder/coder/pull/9392
