### ISSUE TITLE
Bitbucket oauth1 with coder v2

### ISSUE THREAD

**Issue by ciantfv456** [coder/coder#8575]
When working with bitbucket with a version<7.19 bitbucket works using oauth1
Coder v1 supports the use of oauth1 but coder v2 does not
Is there a walk around for the use of coder with bitbucket that have a version that still uses oauth1?

**Comment by ericpaulsen** [comment]
hi @ciantfv456 - you are correct in that Coder v2 does not support OAuth1. the workaround to connect to BitBucket is to leverage the SSH key provided to user Coder account.
