### ISSUE TITLE
`coder stat mem` showing incorrect data

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8592]
Version: [`v0.26.1+a0fedeb`](https://github.com/coder/coder/commit/a0fedebd624e8ba3b03052c3301876f220d851ef)

My workspace has resource limits set to 4 CPU cores, 4 GB RAM, and 10GB persistent disk.

In the UI I see this:
<img width="591" alt="image" src="https://github.com/coder/coder/assets/2022166/8b5d0670-3e75-40eb-8853-40994e6fd50a">

Then it changes to a memory value less than the limit
<img width="591" alt="image" src="https://github.com/coder/coder/assets/2022166/88435c72-d3ff-42a9-8e6e-e5c6b3bd3715">

I checked in CLI in web terminal
<img width="591" alt="image" src="https://github.com/coder/coder/assets/2022166/9e11984c-c2f5-4df5-9528-06f7a5f50bb8">
<img width="591" alt="image" src="https://github.com/coder/coder/assets/2022166/e508fbe8-7102-4267-9f8f-38c6fb28789e">

cpu and disk seem correct

**Comment by johnstcn** [comment]
@sharkymark is this on Docker or Kubernetes? I've noticed that if there is no memory limit set, then you get a small limit initially in /proc/cgroup that grows dynamically.

**Comment by shaoye** [comment]
@johnstcn 

we are on Kubernetes, we have set the limit of both cpu and memory
```yaml
      resources:
        limits:
          cpu: '8'
          memory: 8Gi
        requests:
          cpu: '2'
          memory: 4Gi
 ```

here is the code stat output:

```bash
coder@test:~$ coder stat cpu
0.038/8 cores (0%)
coder@test:~$ coder stat mem
0.255/0.77 GiB (33%)
coder@test:~$ coder stat
HOST CPU             HOST MEMORY         HOME DISK           CONTAINER CPU       CONTAINER MEMORY      
0.099/16 cores (1%)  1.48/61.5 GiB (2%)  1.68/98.2 GiB (2%)  0.014/8 cores (0%)  0.256/0.77 GiB (33%)  
```

**Comment by johnstcn** [comment]
@shaoye can you provide additional information:
- Kubernetes version
- Host OS
- Container runtime
- Coder version

Also, can you confirm if you're using the Sysbox runtime (or using https://github.com/coder/envbox)?

**Comment by shaoye** [comment]
> @shaoye can you provide additional information:
> 
> * Kubernetes version
> * Host OS
> * Container runtime
> * Coder version
> 
> Also, can you confirm if you're using the Sysbox runtime (or using https://github.com/coder/envbox)?
Thanks, we are using:
EKS 1.24
Ubuntu-eks 20.04 with kernel 5.15.0-1039-aws
containerd://1.6.12
Coder v0.27.1
envbox:latest
