### ISSUE TITLE
bug: derp does not connect if coder access URL is not DNS name and coder_experiments = single_tailnet

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#8602]
# Problem

Given:

- Coder deployment on GCP with private VPC on Kubernetes
- Coder access URL is just an IP address (i.e. http://xx.xx.xx.xx and not a DNS name)
- TLS is not enabled

Then:
- Opening a workspace web terminal just hangs
- Tailnet logs appear to show that DERP is not working

When TLS enabled (including with DNS name), it works fine

Logs:
- Not working: 
[coderd.bad.json.zip](https://github.com/coder/coder/files/12098541/coderd.bad.json.zip)
- Working: 
[coderd.good.json.zip](https://github.com/coder/coder/files/12098543/coderd.good.json.zip)

- Coder ping output: 
[coder_ping.log.zip](https://github.com/coder/coder/files/12098577/coder_ping.log.zip)

**Comment by bpmct** [comment]
I guess we need to do this before we make single Tailnet GA. Marking as a `p3` since it's an experimental feature for now.

**Comment by coadler** [comment]
This seems to be fixed now


![Image](https://github.com/coder/coder/assets/6332295/d565f037-aa8f-4cc0-a0b6-02e4b1e86ea3)
