### ISSUE TITLE
Gap in "startup script is still running" in web terminal

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8607]
<img width="1588" alt="Screenshot 2023-07-19 at 2 49 51 PM" src="https://github.com/coder/coder/assets/22407953/f2f2def1-f158-4937-b47a-0236bd9809a4">

**Comment by BrunoQuaresma** [comment]
@bpmct not sure what is the issue.

**Comment by bpmct** [comment]
ahh sorry. there is a tiny gap between the bottom of the "startup script is still running" and the top of the terminal which looks awkward

**Comment by MrPeacockNLB** [comment]
I think this has already been fixed:

![image](https://github.com/coder/coder/assets/103434584/75b680f8-0d21-4244-985d-b51f766ec2d3)
