### ISSUE TITLE
Audit logs pagination only shows 1 additional row per page click

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8626]
Version: [`v0.26.1+a0fedeb`](https://github.com/coder/coder/commit/a0fedebd624e8ba3b03052c3301876f220d851ef)

I made a Loom
https://www.loom.com/share/ab9068a55ce94fd39af14c17726682f2?sid=5344ee2c-a833-41fc-8cdf-0f1a05215a5e

Seems like a bug. It should be a full page per click. Maybe I'm missing something.

**Comment by bpmct** [comment]
Fixed in https://github.com/coder/coder/issues/7995
