### ISSUE TITLE
Kubernetes container recreates instead of stopping

### ISSUE THREAD

**Issue by mayzyo** [coder/coder#8639]
I am running Coder v0.26.1+a0fedeb in a self hosted local containerd Kubernetes cluster with Flannel CNI. Both automatic and manual stop will result in the container being terminated and then recreated. The menu will display the workspace as stopped, but you can still access the terminal and VS Code.

The issue has existed since at least a year ago throughout various versions. My template is using the latest coder and kubernetes terraform based on the Kubernetes example in the repo. And the problem occurs on any template I create, including Jupyter Notebook and NodeJS containers.

![image](https://github.com/coder/coder/assets/25147960/4ec98929-3295-41c6-8047-6296b519a504)

**Comment by kylecarbs** [comment]
You must not have the "count" property set on your Kubernetes resource.

Check the examples to see how to remove a resource on stop!

**Comment by matifali** [comment]
@mayzyo please share your template or add `count = data.coder_workspace.me.start_count` as shown here in this example.
https://github.com/coder/coder/blob/87d5cdaf58496a4092a7037fb61a6cb5c44433f4/examples/templates/kubernetes/main.tf#L224

**Comment by mayzyo** [comment]
The missing count property in main.tf is the reason. Thanks so much for the quick response.

It didn't look important so I've always removed it thinking it's for debugging use. Probably why I couldn't find any answers online for the situation I got myself into.
