### ISSUE TITLE
Run `terraform init -upgrade` on behalf of the user in template editor and CLI

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8646]
## Background

When users upload a new template, they are instructed to run `terraform init -upgrade` so that Coder doesn't have to download the providers every time a build (workspace start/stop/delete occurs). However, if the user changes a provider version in the template editor, they are forced to run `terraform init -upgrade` and push, which can only be done with the CLI and `terraform` CLI installed.

```sh
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of coder/coder from the dependency lock file
- Reusing previous version of kreuzwerker/docker from the dependency lock file
- Using kreuzwerker/docker v3.0.2 from the shared cache directory
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider coder/coder:
locked provider registry.terraform.io/coder/
coder 0.11.0 does not match
configured version constraint 0.11.1; must use terraform init -upgrade to
allow selection of new versions
```

![Screenshot 2023-07-21 at 7 54 12 AM](https://github.com/coder/coder/assets/22407953/4f4ef09f-9c4e-4dd9-b420-0a4f82744076)

### Must have 

- Coder can run `terraform init -upgrade` on behalf of the user from the template editor or CLI
- The user does not need the `terraform` CLI on their local machine

### Other notes

I'm not sure if this behavior needs to be opt-in or not. It doesn't feel risky since this would only occur when the user voluntarily upgrades or downgrades their version in the `providers` block.

**Comment by matifali** [comment]
This started appearing after we started tracking lock files.

**Comment by bpmct** [comment]
In some ways, I suppose this should be considered a feature.

**Comment by matifali** [comment]
But it should be a must have as it blocks updating terraform provider versions from the template editor.

**Comment by coadler** [comment]
I'm not entirely sure how I feel about this. I don't really think coder should be doing any changes to the Terraform files that could diverge it from the source of truth it was uploaded from. In order to get the lock file in the first place you need Terraform installed, so I don't think it's a huge stretch to require users to have Terraform installed to update it as well.

**Comment by bpmct** [comment]
I see. It's kind of unfortunate you can't upgrade/fix these things from within the template editor UI. I also don't have any good solutions in mind

**Comment by mafredri** [comment]
Can't we have a button in the Web UI for terraform upgrade? Right now we have Build and Publish, a third could either always be visible or only on version conflicts. It's weird that there's a CLI lock-in for a file you can't even see in the online template editor.

Recently, I was making a change to a template and wanted to bump the provider for Coder, and it felt like a real PITA to have to 1) pull the changes via CLI, 2) run tf upgrade and 3) push back and 4) switch to the latest version in the editor. If I feel this is a PITA and I know the process, I wonder what our customers think.
