### ISSUE TITLE
ReconnectingPTY traffic uses large amounts of CPU

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#8647]
# Problem

While testing the single_tailnet experiment, found that ReconnectingPTY traffic below 10MB/s can saturate 2 CPUs of coderd

Given:
- Coder Kubernetes deployment (v0.26.2), 1 replica @ 2C/4G
- 100 scaletest workspaces
- 1 traffic generation workspace

When:
- 8 KB @ 10Hz (80KB/s) scaletest traffic sent from traffic generation workspace to 100 scaletest workspace e.g. `--bytes-per-tick=8192 --tick-interval=100ms`

Then:
- Coder CPU usage is saturated

See below graph:

![Screenshot 2023-07-21 at 14 58 56](https://github.com/coder/coder/assets/4949514/13077a72-5fa1-441a-a5eb-562aeb135db0)

First CPU spike is 4kb@10Hz, second CPU spike is 8kb@10hz and maxes out coderd CPU.

Attaching pprofs taken at time indicated:
- 1s CPU trace:
[reconnectingpty-8kb10hz100ws-coder-big-20230721145150-trace.out.zip](https://github.com/coder/coder/files/12129422/reconnectingpty-8kb10hz100ws-coder-big-20230721145150-trace.out.zip)

- Heap:
[reconnectingpty-8kb10hz100ws-coder-big-20230721145150-heap.out.zip](https://github.com/coder/coder/files/12129424/reconnectingpty-8kb10hz100ws-coder-big-20230721145150-heap.out.zip)

- Goroutine: 
[reconnectingpty-8kb10hz100ws-coder-big-20230721145150-goroutine.out.zip](https://github.com/coder/coder/files/12129425/reconnectingpty-8kb10hz100ws-coder-big-20230721145150-goroutine.out.zip)

**Comment by deansheather** [comment]
I think this could be very easily solved by moving the websocket handler for reconnecting-pty out of coderd and into the workspace on a HTTP port. We already have a webserver running for getting the list of ports on a virtual listener only accessible from the tailnet, so it could be added there.

Then the reconnecting-pty routes on coderd and wsproxy just need to reverse proxy to that endpoint, and it'd be the same performance as app proxying

**Comment by sreya** [comment]
@johnstcn reopen if it's still an issue
