### ISSUE TITLE
improvement: Make the stale metadata grey-ish instead of showing the loading skeleton

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#8653]
Right now, when the metadata is stale we show the skeleton component which does not differentiate when the data is loading or stale. To solve this issue we can:
- Make the stale metadata grey-ish instead of showing the loading skeleton
- Add a popover when it is stale explaining what "stale" in this context means

**Comment by elliot-graebert-skydio** [comment]
As long as it doesn't blink or something. I'd recommend something like:

"It's old if it's reached 3x the interval without an update". 

I think the ideal UX is that updates as seamlessly as possible (or no visual sign if it's updating cleanly).
