### ISSUE TITLE
Ephemeral parameter value not passed to provider when selected in "Build options"

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#8654]
Trying out the new "ephemeral parameters" feature, I made this parameter in my template ephemeral:

```
data "coder_parameter" "rebuild_devcontainer" {
  name         = "rebuild_devcontainer"
  display_name = "Force devcontainer rebuild"
  type         = "bool"
  ephemeral    = true
  default      = "false"
  mutable      = true
  order        = 7
}
```

When I select the non-default value "true" for this parameter in the "Build Options" popup under "Restart", my provider's `Update` method still sees a `false` value in the plan.

![image](https://github.com/coder/coder/assets/10601430/d2ee7e56-080b-448e-b718-45cd4cda41e6)

However, this works as expected if I instead go to Settings->Parameters and change the value there.

cc @mtojek

**Comment by mtojek** [comment]
Smells like regression, Bruno.

<img width="516" alt="Screenshot 2023-07-21 at 19 05 49" src="https://github.com/coder/coder/assets/14044910/b2b7a174-8538-43c5-90fb-9851b67ef019">

**Comment by BrunoQuaresma** [comment]
@mtojek Yes, but maybe it is not a regression because this happens when the user restarts the workspace and has to confirm the restart on the dialog. Since we usually have the "Don't ask me again" option enabled we probably missed this path during our QAs.
