### ISSUE TITLE
Deleted workspace logs are immediately unavailable

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#8659]
When deleting a workspace, the terraform run logs are immediately unavailable after it's deleted. You'll have the log in your browser, but if you navigate away and try to get the run log or switch to different builds, the UI just shows a spinner but the console shows it's received a 404 for the logs.

It would be useful to still have logs for a workspace be available for a time (1 hour, 1 day, or 1 week?) even after deletion to inspect previous failures.

**Comment by kylecarbs** [comment]
Agreed. We'll fix this!
