### ISSUE TITLE
coderd/database/queries.sql.go

### ISSUE THREAD

**Issue by Pearlminimal** [coder/coder#8661]
site/src/components/WorkspaceDeletion/utils.ts

**Comment by Pearlminimal** [comment]
site/src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateScheduleForm/InactivityDialog.tsx

**Comment by Pearlminimal** [comment]
site/src/pages/WorkspacePage/WorkspaceReadyPage.tsx

**Comment by kylecarbs** [comment]
?
