### ISSUE TITLE
Coder stat's first argument is accepted but doesn't work as expected

### ISSUE THREAD

**Issue by elliot-graebert-skydio** [coder/coder#8680]
(note this ticket was heavily edited)

![Screenshot 2023-07-22 at 3 11 47 PM](https://github.com/coder/coder/assets/126726750/04a60671-2de4-4711-9c1c-00105670003d)

Note in the above screenshot, /home didn't seem to error out, but it worked on root. It made me think it was a bug, and not just that the argument was getting dropped.

**Comment by ammario** [comment]
cc @johnstcn

**Comment by johnstcn** [comment]
@elliot-graebert-skydio Can you try `coder stat disk --path /home` instead?

**Comment by elliot-graebert-skydio** [comment]
Snap, that works. Ok so is the issue just needing a better error message?

**Comment by johnstcn** [comment]
Yep, or actually accepting the first positional arg as the path arg seems like the "natural" thing.
