### ISSUE TITLE
Coder stat refreshes is visually distracting.

### ISSUE THREAD

**Issue by elliot-graebert-skydio** [coder/coder#8683]
![Screenshot 2023-07-23 at 1 47 52 PM](https://github.com/coder/coder/assets/126726750/3fbd68b8-b1ec-476d-a511-96188b6c3fae)
![Screenshot 2023-07-23 at 1 48 00 PM](https://github.com/coder/coder/assets/126726750/32b1534d-cf0b-4b9f-aa93-a36eaa9c3319)

Every 10 seconds it cycles between these two. I think the better option during a stat refresh is to update the text, instead of erasing it and putting it back in. The movement adjusts all the elements to the left, which draws the eye unnecessarily.

**Comment by BrunoQuaresma** [comment]
We are going to fix that here https://github.com/coder/coder/issues/8653. Closing this for now but let me know if you think there is a better way of doing it.
