### ISSUE TITLE
feat: add derpmesh healthcheck to /api/v2/debug/health

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#8699]
# Problem:

If a deployment has an issue where some replicas are unable to connect to some other replicas' DERP_SERVER_RELAY_URLS, DERP connections may fail. This is a difficult issue to troubleshoot.

# Solution:

Add a check to the `/api/v2/debug/health` that validates that the current coderd replica is able to connect to all known DERP relays.

See also: https://github.com/coder/coder/issues/8698

**Comment by kylecarbs** [comment]
I _believe_ this is done.

**Comment by kylecarbs** [comment]
Oop, after talking with Ben maybe it isn't.
