### ISSUE TITLE
Support setting `redirect-uri` for GitHub OAuth

### ISSUE THREAD

**Issue by matifali** [coder/coder#8714]
## Context

GitHub allows specifying [`redirect_uri`](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls) to changes the redirect uri if its a subpath or subdomain of the callback URL.
We already have. 
```diff
coder:
  env:
    - name: CODER_OAUTH2_GITHUB_ALLOW_SIGNUPS
      value: true
    - name: CODER_OAUTH2_GITHUB_ALLOWED_ORGS
      value: "your-org"
    - name: CODER_OAUTH2_GITHUB_CLIENT_ID
      value: "533...des"
    - name: CODER_OAUTH2_GITHUB_CLIENT_SECRET
      value: "G0CSP...7qSM"
+   - name: CODER_OAUTH2_GITHUB_REDIRECT_URI
+     value: https://SUBDOMAIN.coder.example.com  # assuming coder.eaxmple.com/gitauth/github/callback as callback URL set in OAUTH app.
    - name: CODER_OAUTH2_GITHUB_ALLOW_EVERYONE
      value: false
```
This will allow using the same GitHub OAuth app across multiple Coder deployments. e.g
Deployment 1: https://datascience.coder.example.com
Deployment 2: https://frontend.coder.example.com
etc.

## Suggestions

This can be done by using a condition here. If the value of `redirect_uri` is set, we can modify the below line to use that.
https://github.com/coder/coder/blob/f6f61dfa26c4646b65501c5929ce27b30b9810d7/coderd/gitauth/config.go#L245

**Comment by matifali** [comment]
@bpmct No they only need callbackURL and redirec_uri can be anything as per
As per their [docs](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#redirect-urls)

> The `redirect_uri ` parameter is optional. If left out, GitHub will redirect users to the callback URL configured in the OAuth app settings. If provided, the redirect URL's host (excluding sub-domains) and port must exactly match the callback URL. The redirect URL's path must reference a subdirectory of the callback URL.

```
CALLBACK: http://example.com/path

GOOD: http://example.com/path
GOOD: http://example.com/path/subdir/other
GOOD: http://oauth.example.com/path
GOOD: http://oauth.example.com/path/subdir/other
BAD:  http://example.com/bar
BAD:  http://example.com/
BAD:  http://example.com:8080/path
BAD:  http://oauth.example.com:8080/path
BAD:  http://example.org
```

**Comment by deansheather** [comment]
We already redirect users to GitHub with `redirect_uri` set to `${ACCESS_URL}/api/v2/users/oauth2/github/callback`, so you should be able to set the callback URL in github settings to `https://example.com/api/v2/users/oauth2/github/callback` and it should work for subdomains following the logic above.

**Comment by deansheather** [comment]
We don't need to add a config option for it since the redirect_uri is always based on the access URL.

**Comment by matifali** [comment]
Thanks a lot @deansheather for looking into this.

I tested this successfully on my personal deployment and it works fine. 
If Coder is hosted on a first level subdomain e.g. `coder.domain.tld` the setting `domain.tld` as the callback URL works just fine. It can allow authenticating multiple coder deployments with access urls `*.domain.tld` with the same GitHub OAuth app.
