### ISSUE TITLE
License expiration warning appears for `Member` role in CLI

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8717]
Version: [`v0.27.1+65583ec`](https://github.com/coder/coder/commit/65583eca47f6d9d194ed8b038c3c010a4cd331c4)

Expected behavior is that `Member` role users should never see a license expiration message.

The screenshot window on the top shows the `Owner` warning in the UI. The right window is the `Member` UI with no warning, and the terminal on the lower left is the `Member` trying to `coder ssh` and getting the warning, which is the bug.

This has impacted an existing customer and should be resolved.

![image](https://github.com/coder/coder/assets/2022166/62eb2d22-c9d5-498c-814f-4f29e3d27b25)

**Comment by Emyrk** [comment]
The screenshot is cut off, what is the message in the cli?

**Comment by Emyrk** [comment]
Ah I assume it is this: https://github.com/coder/coder/blob/94cbc2ae7fd689b04a33d603bde8838605cc0ddf/cli/root.go#L825-L830

**Comment by ammario** [comment]
I think the decision to do this was intentional:
* It's a common security practice for the "owner" role to be used rarely and exclusively for admin actions. We don't want anyone surprised by a sudden loss of RBAC or other key features.
* In case of license breach, we want to annoy everyone to pressure operators to return to compliance.

**Comment by Emyrk** [comment]
@ammario @bpmct The FE only shows license banner issues if the user can view the deployment page, which is only the **owner** role. We should probably change this to show to more users then too?

https://github.com/coder/coder/blob/main/site/src/components/Dashboard/DashboardLayout.tsx#L36

**Comment by sharkymark** [comment]
The CLI reports license warnings for non-admin roles.

**Comment by Emyrk** [comment]
@sharkymark currently that is expected behavior.

See @ammario's comment.

https://github.com/coder/coder/issues/8717#issuecomment-1692579028

**Comment by ammario** [comment]
Maybe there's confusion with https://github.com/coder/coder/issues/9350? Are we showing license warnings to users or just errors?

**Comment by Emyrk** [comment]
Oh, I didn't differentiate between the two. I see now, I am not sure the behavior atm.

**Comment by bpmct** [comment]
Going to close this one in favor of #9350.
