### ISSUE TITLE
`coder ssh` hanging forever

### ISSUE THREAD

**Issue by ammario** [coder/coder#8727]
In my test deployment, when I try to `coder ssh` into my workspace it hangs forever. I'm seeing the main goroutine block on `AwaitConn` and a suspiciously large number of tailnet/wireguard goroutines.

The web terminal works fine.

That's about the extent of my investigation so far, but I've attached the full SIGTRAP.

[crash.log](https://github.com/coder/coder/files/12165772/crash.log)

**Comment by coadler** [comment]
Helpful debug info for this would be `coder ping -v <workspace>`. If ping works, then it's likely specific to ssh. Are you forwarding ssh/gpg agents?

**Comment by ammario** [comment]
Ugh. Problem was an out of date agent and bad errors.

**Comment by coadler** [comment]
Were you able to get any error logs from the agent?

**Comment by ammario** [comment]
Nope. But it was quite an old agent.
