### ISSUE TITLE
OAuth OIDC http issuer

### ISSUE THREAD

**Issue by NathanRignall** [coder/coder#8737]
Version [`v0.27.1+65583ec`](https://github.com/coder/coder/commit/65583eca47f6d9d194ed8b038c3c010a4cd331c4)

When using a http oidc issuer the user is redirected to a https url after pressing OpenID connect.

The authentication fails as the oidc server does not support https.

The environment variable `CODER_OIDC_ISSUER_URL` is configured to be http://domain.com

**Comment by kylecarbs** [comment]
Will fix!

**Comment by johnstcn** [comment]
Hi @NathanRignall,

I'm having issues reproducing the issue you describe on v0.27.1 using a local Keycloak instance configured to listen on HTTP. Clicking on the "OpenID Connect" button in the Coder UI resulted in being redirected to `$CODER_OIDC_ISSUER_URL` over HTTP when the issuer scheme was configured to be `http://`.

I also tested with Coder listening on both HTTP and HTTPS, and with the latest release at time of writing (v2.1.0).

I'm assuming that this means the setup I used does not correspond to your situation, so I'm attaching a zip archive containing:
- A docker-compose file that runs an ephemeral Coder deployment with postgresql and keycloak. 
- A script that configures an example Keycloak realm with a single user `keyclock` (password: `password`) and performs the first-time Coder setup (username is `admin`, password is `SomeSecurePassword!`)

[oidc-test.zip](https://github.com/coder/coder/files/12407575/oidc-test.zip)

Can you let me know what I'm missing here in relation to your setup?

**Comment by johnstcn** [comment]
Hi @NathanRignall -- do you have any update based on my above comment?
