### ISSUE TITLE
Same deployment, but getting `internal error getting workspace resources` on one mac

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8759]
Version: [`v0.27.1+65583ec`](https://github.com/coder/coder/commit/65583eca47f6d9d194ed8b038c3c010a4cd331c4)

but getting a perfectly healthy workspace list view on a different mac accessing the same deployment as the same user.

<img width="1043" alt="image" src="https://github.com/coder/coder/assets/2022166/b6c3a6f1-d146-415f-8e7a-dfb942899ffb">

**Comment by Emyrk** [comment]
The context cancelled error means the request was cancelled, which usually happens if the client goes away. Is there any way we can see the network traffic logs? See if the request are taking too long?
