### ISSUE TITLE
Template insights: Insights page keeps loading forever

### ISSUE THREAD

**Issue by matifali** [coder/coder#8763]
See screenshot:
![image](https://github.com/coder/coder/assets/10648092/7b59eb0c-8ce8-4291-b1b3-f42471abbad6)

Also, browser console logs show.
![image](https://github.com/coder/coder/assets/10648092/f09e5d79-eb62-483e-8f35-169509af3457)

```console
Failed to load resource: the server responded with a status of 403 ()
/api/v2/insights/user-latency?template_ids=0d286645-29aa-4eaf-9b52-cc5d2740c90b&start_time=2023-07-19T00%3A00%3A00Z&end_time=2023-07-26T00%3A00%3A00Z:1     Failed to load resource: the server responded with a status of 403 ()
/api/v2/insights/templates?template_ids=0d286645-29aa-4eaf-9b52-cc5d2740c90b&start_time=2023-07-19T00%3A00%3A00Z&end_time=2023-07-26T00%3A00%3A00Z&interval=day:1     Failed to load resource: the server responded with a status of 403 ()
```
Visiting https://dev.coder.com/api/v2/insights/user-latency?template_ids=0d286645-29aa-4eaf-9b52-cc5d2740c90b&start_time=2023-07-19T00%3A00%3A00Z&end_time=2023-07-26T00%3A00%3A00Z
and
https://dev.coder.com/api/v2/deployment/stats
```console
{"message":"Forbidden."}
```

A template admin should be able to see insights for the template he is the admin of. We can make a user template admin for a specific template while his general role is a member. In that case, also he should be able to see the insights for the said template. 

cc: @bpmct @mtojek @BrunoQuaresma

**Comment by mtojek** [comment]
> A template admin should be able to see insights for the template he is the admin of. We can make a user template admin for a specific template while his general role is a member. In that case, also he should be able to see the insights for the said template.

I know that we invested in restricting access to information about other users. An owner can see everyone, but what about the template admin? I'm asking as the Insights page reveals information about users (names, avatars, location?). 

@bpmct WDYT? Based on this decision we will know which party should we fix - BE, FE, or both.

**Comment by matifali** [comment]
Can reproduce with a member role who is admin for only 1 template.

**Comment by matifali** [comment]
test

**Comment by matifali** [comment]
This is again happening on dev.coder.com

**Comment by matifali** [comment]
Visiting [dev.coder.com/api/v2/insights/user-latency?template_ids=0d286645-29aa-4eaf-9b52-cc5d2740c90b&start_time=2023-07-19T00%3A00%3A00Z&end_time=2023-07-26T00%3A00%3A00Z](https://dev.coder.com/api/v2/insights/user-latency?template_ids=0d286645-29aa-4eaf-9b52-cc5d2740c90b&start_time=2023-07-19T00%3A00%3A00Z&end_time=2023-07-26T00%3A00%3A00Z)
Shows me a json data.

**Comment by matifali** [comment]
cc: @mtojek

**Comment by matifali** [comment]
I am unable to reproduce it anymore.
