### ISSUE TITLE
Add user preference to open `coder_app` in new tab rather than window

### ISSUE THREAD

**Issue by TheZoker** [coder/coder#8796]
Currently the online vscode button opens the editor in a new windows. I would prefer to open it in a new tab. 

Maybe support an option within the terraform file:
```diff
resource "coder_app" "code-server" {
    agent_id     = coder_agent.main.id
    slug         = "code"
    display_name = "VS Code"
    url          = "http://localhost:8080/?folder=/home/${local.username}/workspace"
    icon         = "/icon/code.svg"
    subdomain    = false
+   open_instance = "window|tab"
    share        = "owner"

    healthcheck {
        url       = "http://localhost:8080/healthz"
        interval  = 5
        threshold = 6
    }
}
```

I guess line would need to be modified:
https://github.com/coder/coder/blob/a75346dd329481236c6cb3ffd36c019b1fd93476/site/src/components/AppLink/AppLink.tsx#L108

And this:
https://github.com/coder/coder/blob/a75346dd329481236c6cb3ffd36c019b1fd93476/site/src/components/TerminalLink/TerminalLink.tsx#L41

I would love to hear some feedback

**Comment by kylecarbs** [comment]
I was thinking this should be an account-level option. I also prefer it in new tabs.

**Comment by MrPeacockNLB** [comment]
Maybe a combination of both. User oreferences over template admin settings.

**Comment by TheZoker** [comment]
Why is this closed?

**Comment by TheZoker** [comment]
@kylecarbs Can you have a look at this? Since other issues link to this issue and there is still demand for this feature, I think it should be kept open

**Comment by kylecarbs** [comment]
@TheZoker I'll keep it open and we should do this.

**Comment by matifali** [comment]
@kylecarbs, @bpmct  During the webinar the app opened in a new window which was not shared, and the audience missed a part of the demo. We should really add the option to set default behavior on a per-app basis within the provider.

**Comment by stirby** [comment]
I agree we should bake it into the provider.

**Comment by kylecarbs** [comment]
We should not bake it into the provider.

I'm not sure how to do it, but template authors should not be able to dictate how user windows open. Users should dictate such a thing.

**Comment by matifali** [comment]
Current workaround.
1. Left click --> Opens the app in new window
2. Middle click --> Opens the app in new tab

**Comment by bpmct** [comment]
We understand this is a slight nuance but after some research, we couldn't find examples of other software that handles such interaction well. As a workaround, I use middle click or cmd+shift+click to open in the proper way.

We're open to an account-level option, but I just haven't seen it in other products.

**Comment by TheZoker** [comment]
Actually I think that Coder is the only app (that I'm aware of), that opens thinks in a new window. Almost all applications I used so far open in the same window or open a new tab, but non of them open a new window. 
I us applications such as Gitea, Kasm, Plane, Mattermost, Appwrite and many more

I'm not even aware of any cloud hosted services, that open anything in a new window (google cloud, aws, github...)

Why can't there just be a setting in the code server module like:
```tf
module "code-server" {
  source          = "registry.coder.com/modules/code-server/coder"
  version         = "1.0.17"
  agent_id        = coder_agent.main.id
  display_name    = "VS Code"
  slug            = "code"
  open_window     = "false"                   <---- new option here
  install_version = "4.91.1"
  folder          = "/home/${local.username}/workspace"
  port            = "8080"
  extensions      = [
    "eamodio.gitlens",
    "PKief.material-icon-theme"
  ]
}
```

I understand that this does not allow users to set the behavior, but at least it would allow me to set it for that application. Per default it can open in a new window, to not break/change any existing behavior, but I would prefer to be able to change it at least somehow.
