### ISSUE TITLE
CPU/RAM usage no longer showing properly

### ISSUE THREAD

**Issue by Smartich0ke** [coder/coder#8799]
Just installed Coder on my kubernetes cluster, been using the default "Develop In Kubernetes" template and I'm loving it.

For a while, I was able to see the CPU/RAM/storage usage of a selected workspace fine, but now under each stat I only see `manpath: can't set the locale; m...` and the rest is truncated:
![image](https://github.com/coder/coder/assets/41409702/c647ad5d-464a-4429-ba75-77edafa04c61)
I'm running Coder v0.27.1

Any assistance on how to fix or further diagnose this error would be appreciated.

**Comment by ericpaulsen** [comment]
hi @Smartich0ke - i'm unable to reproduce this error with the default template, using `0.27.2`. the full error is likely `manpath: can't set the locale; make sure $LC_* and $LANG are correct`.

can you run the following command and compare against my output?

```
> locale

LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

**Comment by Smartich0ke** [comment]
Hi sorry for the late response, but all newly created workspaces don't seem to have this problem anymore. Still not sure what caused it but I'm glad it's fixed itself.

**Comment by ZandercraftGames** [comment]
Sorry to necro on this issue, but I've been getting the same issue. It eventually seems to pop up on new workspaces.
~[manpath Issue](https://images.zandercraft.ca/brave_78pG3Wg3ua.png)

```BASH
~$ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by ZandercraftGames** [comment]
> Sorry to necro on this issue, but I've been getting the same issue. It eventually seems to pop up on new workspaces. ![manpath Issue](https://camo.githubusercontent.com/891693ab40866e4345965e749c280c42c8ac57458bfa82373151076bf61c1114/68747470733a2f2f75732d656173742d312e74697874652e6e65742f75706c6f6164732f696d616765732e7a616e64657263726166742e63612f62726176655f373870473357673375612e706e67)
> 
> ```shell
> ~$ locale
> LANG=C.UTF-8
> LANGUAGE=
> LC_CTYPE="C.UTF-8"
> LC_NUMERIC="C.UTF-8"
> LC_TIME="C.UTF-8"
> LC_COLLATE="C.UTF-8"
> LC_MONETARY="C.UTF-8"
> LC_MESSAGES="C.UTF-8"
> LC_PAPER="C.UTF-8"
> LC_NAME="C.UTF-8"
> LC_ADDRESS="C.UTF-8"
> LC_TELEPHONE="C.UTF-8"
> LC_MEASUREMENT="C.UTF-8"
> LC_IDENTIFICATION="C.UTF-8"
> LC_ALL=
> ```
> 
> [This answer](https://stackoverflow.com/a/46946414) on StackOverflow seems to fix it temporarily.

I've just found the following error in the build log:
```
manpath: can't set the locale; make sure $LC_* and $LANG are correct
Ubuntu 22.04.4 LTS
Installing v4.92.2 of the amd64 release from GitHub.
```

**Comment by ZandercraftGames** [comment]
> > Sorry to necro on this issue, but I've been getting the same issue. It eventually seems to pop up on new workspaces. ![manpath Issue](https://camo.githubusercontent.com/891693ab40866e4345965e749c280c42c8ac57458bfa82373151076bf61c1114/68747470733a2f2f75732d656173742d312e74697874652e6e65742f75706c6f6164732f696d616765732e7a616e64657263726166742e63612f62726176655f373870473357673375612e706e67)
> > ~$ locale
> > LANG=C.UTF-8
> > LANGUAGE=
> > LC_CTYPE="C.UTF-8"
> > LC_NUMERIC="C.UTF-8"
> > LC_TIME="C.UTF-8"
> > LC_COLLATE="C.UTF-8"
> > LC_MONETARY="C.UTF-8"
> > LC_MESSAGES="C.UTF-8"
> > LC_PAPER="C.UTF-8"
> > LC_NAME="C.UTF-8"
> > LC_ADDRESS="C.UTF-8"
> > LC_TELEPHONE="C.UTF-8"
> > LC_MEASUREMENT="C.UTF-8"
> > LC_IDENTIFICATION="C.UTF-8"
> > LC_ALL=
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [This answer](https://stackoverflow.com/a/46946414) on StackOverflow seems to fix it temporarily.
> 
> I've just found the following error in the build log:
> 
> ```
> manpath: can't set the locale; make sure $LC_* and $LANG are correct
> Ubuntu 22.04.4 LTS
> Installing v4.92.2 of the amd64 release from GitHub.
> ```

Just to provide an update on this... One of the ways I have found to fix this is to add these to the startup script:
```bash
sudo apt-get update
sudo locale-gen "en_CA.UTF-8"
```

And then to add the following line to the `.bashrc` and `.bash_profile` files:
```bash
export LC_ALL="en_CA.UTF-8"
```
