### ISSUE TITLE
Document or create a way for rootless container tools to work with devcontainers

### ISSUE THREAD

**Issue by Shocktrooper** [coder/coder#8800]
Recently I have been playing around with the devcontainer setup for coder.  While creating the environment to develop in is useful it appears that there is no documentation to do container builds and run them with envbuilder devcontainers.  We have gotten rootless podman to work separately but due to the differences in the images we are unsure how to marry the 2 together so that we can build and run application containers without having a privileged environment available to developers.  This in my opinion is one of the only things missing from devcontainers with coder that other solutions like GitPods and GitHub code spaces have out of the box.

References:
- https://coder.com/docs/v2/latest/templates/devcontainers
- https://coder.com/docs/v2/latest/templates/docker-in-workspaces#rootless-podman

**Comment by sharkymark** [comment]
@Shocktrooper I cross posted your issue in the `envbuilder` project

**Comment by juanbits** [comment]
how do you auth to github?

every time i got:
envbuilder - Build development environments from repositories in a container
#1: 📦 Cloning https://github.com/user/reponame to /workspaces/reponame...
Failed to clone repository: clone "https://github.com/user/reponame": authentication required

**Comment by matifali** [comment]
@juanbits if this is a private GitHub repo, you need to use https://github.com/coder/envbuilder?tab=readme-ov-file#git-authentication

**Comment by sreya** [comment]
We don't have any plans for this but we're open to documentation submissions
