### ISSUE TITLE
`coder stat mem` in AKS shows the cluster node's memory not the workspaces

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8814]
Version: [`v0.27.1+65583ec`](https://github.com/coder/coder/commit/65583eca47f6d9d194ed8b038c3c010a4cd331c4)

See `htop` and template source code as well for information. The node has 16GB RAM, the workspace limit is 4 GB RAM

![image](https://github.com/coder/coder/assets/2022166/a83af42b-eab4-4dde-81ec-dbe8ec3148de)

![image](https://github.com/coder/coder/assets/2022166/22c49f7c-d81f-4503-98c1-b58ed3df5879)

**Comment by sreya** [comment]
@sharkymark are you using `latest` for `envbuilder`?
