### ISSUE TITLE
Add server-side workspace restart transition

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#8821]
A minor, low-priority feature request: It would be handy to have server-side support for workspace restarts, and update the CLI `restart` command to use it. Currently, this command first invokes a `stop` transition, then a `start` transition. This means it's not possible to invoke a restart from within the workspace itself, since the workspace will shut down before it has a chance to issue the start command.

**Comment by bpmct** [comment]
Closing in favor of https://github.com/coder/coder/issues/5800
