### ISSUE TITLE
port-forward button doesn't appear automatically unless we do a refresh

### ISSUE THREAD

**Issue by matifali** [coder/coder#8834]
I have experienced this on a new helm deployment.
Please take a look at the attached video.

https://github.com/coder/coder/assets/10648092/6be3a0e4-c678-4bd0-aa15-beedc03f123b

**Comment by sharkymark** [comment]
Is that a cookie thing (dev URL, I mean port forward not being created initially)?

**Comment by matifali** [comment]
@sharkymark I am not sure. Have you seen this anytime?

**Comment by BrunoQuaresma** [comment]
@matifali this is probably fixed. Feel free to reopen if you still seeing it.

**Comment by matifali** [comment]
On the latest main, I can still see this. It needs to refresh the page for the button to appear.

**Comment by BrunoQuaresma** [comment]
Is this workspace on dev.coder.com?

**Comment by matifali** [comment]
@BrunoQuaresma tes any PR deployment
pr8924.test.cdr.dev

**Comment by bpmct** [comment]
This has been fixed! Just tried on a new PR deployment
