### ISSUE TITLE
improvement: use empty space in terminal

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#8854]
![image](https://github.com/coder/coder/assets/57866459/c751905d-e80a-46ca-aa67-3878061039d9)

---

[Discord thread](https://discord.com/channels/747933592273027093/1135554057147260970)

---

I think the space next (highlighted in red) to the latency could be used to display some stats about the workspace (RAM, disk usage, current directory, etc).
I was also thinking there could be "quick action" buttons otherwise, each button would run a specific command (defined by the user or the template) 

---

cc: @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
We need to:
- Verify if we can get this data
- Mock this on Figma to see how it would look like

**Comment by MrPeacockNLB** [comment]
Hmn.... to me this and even the latency should be optional and could be configured. I personaly do not like this stats in th e web terminal.

**Comment by kylecarbs** [comment]
I think it's better if the terminal is just a terminal, although it would be nice to show the stats.
