### ISSUE TITLE
external provisionerd authentication via pre-shared key (PSK)

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#8861]
Currently, external provisionerds need a template-admin Coder API token in order to authenticate.

This presents difficulty to [deploying via Helm](https://github.com/coder/coder/issues/8243), since it requires a working Coderd before a token can be generated.

It also is a more powerful token than is required, since provisionerd does not need to modify any templates.

Spec
-----

Add an environment variable/configuration field to Coderd to specify a pre-shared key for provisionerd authentication.  When authenticating to the provisioner API, we check the provided token against this value in addition to standard API keys.  The pre-shared key _can only_ be used to authenticate against the provisioner API, not against other API endpoints.

environment variable: `CODER_PROVISIONER_DAEMON_PSK`
CLI flag `--provisioner-daemon-psk`
YAML `provisioning.daemonPSK`

**Comment by johnstcn** [comment]
@spikecurtis I'm not against the idea of a separate authorization mechanism _specifically_ for external provisioner daemons. The fact that it's scoped exclusively to a single API endpoint is a definite plus.

If we end up needing to proliferate this authorization mechanism to other routes, we may need to revisit the prospect of integration into the existing RBAC system.

Side note: provisioner tags could conceivably be handled similarly to how group ACLs are handled for workspaces / templates?

**Comment by spikecurtis** [comment]
> Side note: provisioner tags could conceivably be handled similarly to how group ACLs are handled for workspaces / templates?

I'm not sure how this would work.  Group ACLs involve attaching a list of subjects to an explicit object (workspace or template).  There is no explicit object in the DB for a set of tags, and adding one is tricky because of the selection semantics of tags: removing a tag from a set down-scopes the set of possible jobs.

So if you have tags `x=1, y=2` and grant that principal A, then A should _also_ be allowed to connect with tags `x=1`, since that is a strict subset.

**Comment by bpmct** [comment]
> @bpmct I'm interested in your thoughts here about provisioner isolation only along (future) organization boundaries.

Wow, I totally missed this. I left a few comments in our RFC. I think leveraging user accounts + token scopes to provide isolation is a good move forward:
- `coder server` does not need to restart to add finely-scoped tokens
- An admin could automate token creation/refreshing short lived tokens via the Coder CLI + Kubernetes secrets
