### ISSUE TITLE
Allow "team leads" to access workspaces from users in a group

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8870]
Use case: Allow an admin-type role to access `coder_apps`, IDEs, and SSH into workspaces from users in a specific group of users (e.g. frontend team") without having access to all workspaces in a deployment

## Some ideas

- Workspace sharing + group admins (share with a user or group). 
- Expose organizations, since workspaces are scoped to groups

**Comment by matifali** [comment]
Related to #6304
