### ISSUE TITLE
Support Gitea as a Git Provider

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [coder/coder#8899]
We are running Gitea internally, but unfortunately in https://coder.com/docs/v2/latest/admin/git-providers, there is no option for Gitea.

**Comment by matifali** [comment]
Hi @wizpresso-steve-cy-fan have you tried configuring it up?  I guess it should work.

**Comment by matifali** [comment]
Now, Coder supports any external auth provider. See https://coder.com/docs/v2/latest/admin/external-auth for details.
