### ISSUE TITLE
Seamlessly and smoothly integration with local computer

### ISSUE THREAD

**Issue by raulsh** [coder/coder#8903]
I'm using Coder with my team to have our work remotely and to use cloud capacity to have more resources in some scenarios. 

It would be interesting to have a smoother integration with the terminal and vscode. For example, I have a bash script that, when I open the terminal, automatically starts the workspace, waits for it to be ready, and then initiates SSH. This would be helpful if I were native, whether I'm trying to access it from vscode or SSH.

Also, I'm very used to using the "code" command from the terminal, which obviously isn't available in the terminal (with SSH). I copied a script from somewhere (can't remember where) to open a vscode window whenever I did that, but it relies on already having a remote session open in vscode for it to work. Otherwise, nothing happens.

The last thing, which I imagine is just a configuration issue, is that when there are commands that open a window in the browser, they can open it in the local browser.

**Comment by matifali** [comment]
Hi @raulsh I don't think I understand your feature request completely but there is an older issue I created to open vscode from the workspace cli. #7667

**Comment by matifali** [comment]
Closing as the issue description is not clear.
