### ISSUE TITLE
`coder stat` has different format in `envbuilder` versus other templates but with same code

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8904]
Version: [`v2.0.0+ad513fa`](https://github.com/coder/coder/commit/ad513fa8b90dc851113589df93f67885bd4571cf)

`envbuilder` `coder stat` results in workspace dashboard
![image](https://github.com/coder/coder/assets/2022166/a56ac9c5-9279-4ded-8896-d8b536be9150)

`envbox` `coder stat` results in workspace dashboard
![image](https://github.com/coder/coder/assets/2022166/e2966846-c724-4a4c-95bd-820b26b1b733)

another template `coder stat` results in workspace dashboard
![image](https://github.com/coder/coder/assets/2022166/3f80e7c6-8d1b-4113-b14f-30cf493828a7)

cloud: EKS, kube `1.25.11`

**Comment by matifali** [comment]
Hi @sharkymark are all of them k8s templates?
