### ISSUE TITLE
Remove user-facing error when gitauth regex does not match

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8905]
## Background

Coder's `gitauth` feature allows admins to link a [Git Provider](https://coder.com/docs/v2/latest/admin/git-providers). When a developer goes to `git clone` a workspace, they can authenticate via Coder instead of having to manually manage tokens/SSH keys.

One feature of gitauth is [regex matching](https://coder.com/docs/v2/latest/admin/git-providers#multiple-git-providers-enterprise), which allows Coder to determine what git provider to use for specific `git` repositories (e.g. bitbucket.com -> provider 1, github.com -> provider 2). When there is not a valid regex match, Coder throws a pretty nasty error:

```sh
node ➜ ~ $ git clone https://github.com/coder/idk
Cloning into 'idk'...
ERROR: No git provider found for URL "https://github.com"
                                                  
error: unable to read askpass response from '/tmp/coder.8MaM80/coder'
Username for 'https://github.com': 
```

There are some cases where the user may wish to use their own authentication, such as for a personal repo (dotfiles).

## Potential solutions

1. Instead of calling out negative matches, only call out positive matches to indicate gitauth is being used
2. Make message more passive, avoid "error" terminology.
   ```sh
   No matching git providers found in Coder. Falling back to git authentication
   ```

Perhaps we could also cover this in verbose agent or server logging, to identify why a provider isn't being matched. This is a nice-to-have

**Comment by Emyrk** [comment]
How is this?

```shell
$ git clone https://github.com/Emyrk/test-private.git
Cloning into 'test-private'...
WARN: Coder was unable to handle this git request. The default git behavior will be used instead.
  | No matching git provider found in Coder for the url "https://github.com/Emyrk/test-private.git".
  | The configured git provider have regex filters that do not match the git url.
error: unable to read askpass response from '/tmp/coder.xB6aoB/coder'
Username for 'https://github.com/Emyrk/test-private.git': 
```

![Screenshot from 2023-08-29 10-05-49](https://github.com/coder/coder/assets/5446298/ae501282-c085-4f6c-a293-18d927d6c866)

**Comment by Emyrk** [comment]
```shell
coder@gitauth:~$ git clone https://github.com/Emyrk/test-private.git
Cloning into 'test-private'...
WARN: Coder was unable to handle this git request. The default git behavior will be used instead.
  | No matching git provider found in Coder for the url "https://github.com/Emyrk/test-private.git".
  | The configured git provider have regex filters that do not match the git url. Provider url regexs: github="github.com/orgname", gitlab="gitlab.com"
error: unable to read askpass response from '/tmp/coder.xB6aoB/coder'
Username for 'https://github.com/Emyrk/test-private.git': 
```

**Comment by Emyrk** [comment]
@bpmct ?

**Comment by Emyrk** [comment]
Unfortunately not. `git` calls our binary, so that output is outside our control.
