### ISSUE TITLE
feat: allow making forwarded ports public

### ISSUE THREAD

**Issue by matifali** [coder/coder#8908]
We can do something like GitHub Codespaces.
![image](https://github.com/coder/coder/assets/10648092/ece8b081-d6d4-4c1c-8733-fcf4550b1880)

We can add a shortcut to change the [`share`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app#share) type to `public/authenticated`
By default, each forwarded port is set to share=owner
It should not be possible for many enterprises to make a port public, but it would be a great addition for OSS users and projects.

As a workaround template-admins can create a [coder_app](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/app) with `share=public` for a specific port.

moved from https://github.com/coder/coder/issues/8281#issuecomment-1657630565

**Comment by MrPeacockNLB** [comment]
This is a valid use case. We are developing in a safe environment so making a temporary port public accessible would be a great addititon and makes the life for the developer easier and faster as no one has to create a dedicated app for the port.

**Comment by MrPeacockNLB** [comment]
also see here: https://github.com/coder/coder/issues/4615

**Comment by matifali** [comment]
Closing in favour of #4615
