### ISSUE TITLE
can not connect to web terminal while connected to US wsproxy

### ISSUE THREAD

**Issue by matifali** [coder/coder#8909]
My workspace is in Europe Helsinki region. I can connect and open a web terminal while connected to 
Brazil, Australia, and Europe workspace proxies but can't connect while connected to the US.

It keeps stuck in a blank state.
![image](https://github.com/coder/coder/assets/10648092/c9fee813-c0c2-4f70-9259-a0fbc4dcee08)

**Comment by matifali** [comment]
cc: @bpmct for priority

**Comment by Emyrk** [comment]
Can you record the network traffic? Curious what the websocket says

**Comment by deansheather** [comment]
This is caused by having single tailnet enabled at the same time as workspace proxies existing in the deployment I think

**Comment by phorcys420** [comment]
![video](https://cdn.discordapp.com/attachments/1007079786276978730/1143609203605385338/2023-08-22_20-11-53.mp4)

---

The same thing happens to me on the dogfood instance.
My workspace is in Germany and I can connect from every relay, except Iowa, where the Coder instance is hosted.

@Emyrk I had recorded the WS traffic in this vid, it's empty.

**Comment by matifali** [comment]
@phorcys420 looks like our video is not playable.

**Comment by phorcys420** [comment]
> @phorcys420 looks like our video is not playable.

Yeah, GitHub tries to proxy it but it can't because the video is too big, I changed it to a link.
