### ISSUE TITLE
Sign commits within a Coder workspace

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#8922]
[[Discord Conversation](https://discord.com/channels/747933592273027093/1087831376201523260)]

It would be nice if the Coder agent automatically downloaded the SSH key to ``~/.config/coderv2`` or if there was a way to have the Coder agent configure SSH signing.

---

Here is the current workaround we found with discord user "Nugget"

```bash
#!/bin/bash

mkdir -p ~/.ssh

ssh_key=$(curl --request GET \
        --url "${CODER_AGENT_URL}api/v2/workspaceagents/me/gitsshkey" \
        --header "Coder-Session-Token: ${CODER_AGENT_TOKEN}")

jq --raw-output ".public_key" <<< "$ssh_key"  > ~/.ssh/id_ed25519.pub
jq --raw-output ".private_key" <<< "$ssh_key" > ~/.ssh/id_ed25519

chmod -R 400 ~/.ssh/id_ed25519
chmod -R 400 ~/.ssh/id_ed25519.pub

git config --global gpg.format ssh
git config --global commit.gpgsign true
git config --global user.signingkey ~/.ssh/id_ed25519
```

**Comment by matifali** [comment]
A big fan of this if Cder can o it automatically. @bpmct thoughts?

**Comment by deansheather** [comment]
We could shim git gpg command perhaps. We decided not to save the ssh key to disk because we only wanted it to be used for SSH purposes.

Another consideration is that signing commits is supposed to prove that you wrote the commits and pushed them, but using a key stored in the workspace (and not forwarded) breaks this claim as any admin can connect to any workspace. Given this I don't think we should support it natively because it's not secure.

**Comment by devpikachu** [comment]
> We could shim git gpg command perhaps. We decided not to save the ssh key to disk because we only wanted it to be used for SSH purposes.
> 
> Another consideration is that signing commits is supposed to prove that you wrote the commits and pushed them, but using a key stored in the workspace (and not forwarded) breaks this claim as any admin can connect to any workspace. Given this I don't think we should support it natively because it's not secure.

Whilst I completely agree with this, perhaps mentioning the workaround pointed out by @phorcys420 above in the docs for people looking for this would help.

**Comment by phorcys420** [comment]
> > We could shim git gpg command perhaps. We decided not to save the ssh key to disk because we only wanted it to be used for SSH purposes.
> > 
> > Another consideration is that signing commits is supposed to prove that you wrote the commits and pushed them, but using a key stored in the workspace (and not forwarded) breaks this claim as any admin can connect to any workspace. Given this I don't think we should support it natively because it's not secure.
> 
> Whilst I completely agree with this, perhaps mentioning the workaround pointed out by @phorcys420 above in the docs for people looking for this would help.

I guess the git gpg shim paired with 2FA (prolly TOTP) would solve this if implemented securely.

**Comment by matifali** [comment]
@phorcys420 this could be good candidate for a Coder [module](https://github.com/coder/modules). 
want to submit a PR?

**Comment by phorcys420** [comment]
> @phorcys420 this could be good candidate for a Coder [module](https://github.com/coder/modules). 
> want to submit a PR?

I'll look into it this weekend !
I didn't know about modules, very interesting..

**Comment by smolinari** [comment]
@matifali - The "registry" link doesn't work. 

https://registry.coder.com/

Scott

**Comment by matifali** [comment]
@smolinari it's scheduled to launch after https://coder.com/webinars/coder-2/register

**Comment by smolinari** [comment]
Ah. Ok! :+1: 

Scott

**Comment by matifali** [comment]
Possible after https://github.com/coder/modules/pull/94
