### ISSUE TITLE
☂️ Release Workflow

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8929]
## Background

We're currently able to rapidly release new Coder versions with our GitHub action. With a single script/command, we can create & publish a release from the latest `main` branch. 

However, it is more difficult to do the following:
- patch past versions (although the release script does support running a release against a given ref)
- maintain a "running changelog" (especially for patch releases or once there were a few patches)
- The version of our development builds in dev.coder.com, get a bit off/wacky when we create patch releases.

### Must have

- Release manager can release from `main` with a single command/workflow. Any release improvements should not increase the friction to release from `main`. This is our quickest way to get a fix out for customers
- Release manager can 'revoke' a release, meaning that Helm and install script will no longer auto-upgrade, but the packages and containers still exist to avoid breaking deployments that did upgrade
- Release manager can maintain a manual "running changelog" for an upcoming release against `main`.
- Release manager can patch a previous version (e.g. 2.1) even if the product is on 2.4. Patch releases should have less steps.
- Release manager is not required to do a pre-release before a release

### Should have

- Release manager can make "pre-releases" that are not promoted via Helm, GitHub, or Slack notifications to customers. 
- Automated changelogs for patch releases have the same format as the manual changelog format (e.g. no commit name in front), hides the chores and internal stuff
- Release manager can modify the automated changelog "just in time" for patch/normal releases

### Nice to have

- Patch releases for previous versions do not make a big splash (e.g. GitHub notification, show up on top of list)
- Pre-releases can be opt-in via the install script & Helm
- The running manual changelog can auto-detect new commits since the last time it was modified and add & flag the autogenerated commits

**Comment by bpmct** [comment]
We have the ability to create manual changelogs (see `docs/changelogs`) but have to submit a PR and wait for `make lint`). Would love a faster workflow there still as a nice to have

**Comment by stirby** [comment]
@bpmct closing this with the latest changes to our release process. Reopen if you want to see changes.
