### ISSUE TITLE
Change AWS examples to use `aws_ec2_instance_state`

### ISSUE THREAD

**Issue by bpmct** [coder/coder#8931]
Our AWS example currently templates use a `user_data` hack to start/stop instances. Let's use [aws_ec2_instance_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_instance_state.html) instead.

Related: https://github.com/coder/coder/issues/8580

**Comment by bpmct** [comment]
@matifali - any interest in taking this one?

**Comment by matifali** [comment]
@bpmct I will do this.
