### ISSUE TITLE
Auto-generate contextual workspace names instead of random

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#8961]
# Description

Using the new auto creation mode makes it difficult to determine the underlaying repository in a workspace. Example given:

https://coder.com/templates/automode/workspace?mode=auto&name=coder&param.git_orga=coder-12345&param.git_repo=coder&param.git_ref=master

As one can see we are passing the **coder/coder** GitHub repository as params. And name the workspace from the repository with some additional random values suffixed. But in auto mode a complete new random name is generated. This works fine if one has only one or say less then 5 workspaces opened. As soon one has many open workspaces one gets lost as there is no way to determine which workspace has opened which repository. This makes it nearly impossible.

@BrunoQuaresma we already talked about this feature request

# Possible solution

Coder should provide different auto modes:

- Taking the given name into account. This way the caller has to take care about the naming
- Expanding given name with a random suffix. In an ideal world Frontend check if random value is available
- And the existing mode. completely random value

**Comment by MrPeacockNLB** [comment]
please do not close

**Comment by matifali** [comment]
cc: @aslilac in context of #12001.

**Comment by bpmct** [comment]
Closing in favor of some of our work here: https://github.com/coder/coder/issues/8462. Our goal is to make it easy to supply a repo URL to Coder and it will automatically know which template, params, and name to use.
