### ISSUE TITLE
healthcheck: suggest resolutions

### ISSUE THREAD

**Issue by matifali** [coder/coder#8965]
There are many cases where we can suggest a clear resolution e.g. 

1. no access URL
2. WebSockets are not enabled
3. wildcards domain/cert issue
4. etc.

TODO:

- [x] Add resolution code fields on the BE (https://github.com/coder/coder/pull/10915)
- [x] Refactor `[]warnings` string to `[]{message, code}` (https://github.com/coder/coder/pull/10950)
- [ ] Add docs link to health codes on FE

**Comment by mtojek** [comment]
@johnstcn As we implement frontend changes in https://github.com/coder/coder/issues/8971, can we close this issue?

**Comment by johnstcn** [comment]
@mtojek Yep, closing this one out.
