### ISSUE TITLE
☂️ Coder deployment health check

### ISSUE THREAD

**Issue by matifali** [coder/coder#8971]
## Background

In the context of #7748, we now have an excellent experimental health page available at coder.example.com/health.

![image](https://github.com/coder/coder/assets/10648092/4a2ff5c4-7ccf-472c-8b0c-06458a361348)

## Product Requirements

Before making it GA, it is essential to consider the following requirements.

### Must have

- [x] #8970
- [x] #9470
- [x] #7173
- [ ] #10785
- [x] #10864

### Should have

- [x] #8966
- [x] #9558
- [x] #10676
- [x] #8965
- [x] #9754
- [x] #11542
- [x] #11582

### Nice to have

- [x] #8969
- [x] #9381
- [x] #10712
- [x] #10678
 

cc: @bpmct

**Comment by bpmct** [comment]
added https://github.com/coder/coder/issues/9558

**Comment by mtojek** [comment]
I'm starting with https://github.com/coder/coder/issues/9470. Let's see how far I can go.

**Comment by mtojek** [comment]
I prepared a draft navigating through the design & implemention details: [notion page](https://www.notion.so/coderhq/Redesign-Coder-deployment-health-check-89cef7dce3ed4abaa06ed03188b29f09). Let's consider it to be kick off.

**Comment by BrunoQuaresma** [comment]
Should we add a task for the page redesign including all those changes in the API?

**Comment by mtojek** [comment]
Replied in slack, let me copy it here:

> Actually we can do the same way as we did last time, so somebody (me?) will finish the backend side, and then reassign issues to you

**Comment by matifali** [comment]
@BrunoQuaresma yes you may create a new issue for design and add to the list and milestone.

**Comment by BrunoQuaresma** [comment]
@mtojek sure thing. I was planning to take a look into the flakes but I'm going to prioritize the new health UI this week

**Comment by matifali** [comment]
One last thing. Don't we also want to add a YAML page to each health check to allow the operator to copy raw health check response? Similar to previous behavior. 
cc: @johnstcn @mtojek @BrunoQuaresma

**Comment by johnstcn** [comment]
We could add a link to the API endpoint very cheaply?

**Comment by mtojek** [comment]
@matifali Could you please a separate issue or post-GA epic? We have merged the healthcheck changes, so it is a bit late.
