### ISSUE TITLE
Open in Coder: reproduce v1 functionality to start an existing workspace if found

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#8972]
V1 has a feature where if when Open in Coder is clicked (the image version of Open in Coder), it would detect a workspace exists with same image for the same user, and just start the workspace, and not create a new one.

Given how v2 starts at the template-level, where image is the highest level of abstraction, this may not be possible without re-work.

**Comment by bpmct** [comment]
@kylecarbs and I have discussed some ways templates can be associated with git repos which would give Coder more context on which existing workspaces are compatible with a repo. There's a hacky way we could support it without this rework (e.g. passing specific parameters or one-time parameters to a specific workspace that matches the template in the URL) but I don't think this is the best UX.

I'm not sure if we'll be able to get to it this year though. Will share updates here.

**Comment by matifali** [comment]
Reopening as requested again in #12514

**Comment by matifali** [comment]
Originally posted in https://github.com/coder/coder/issues/12514#issue-2178635290

**Comment by kylecarbs** [comment]
Closing for now. I'm not sure how we'd do this in the next few months.

**Comment by BA-CalderonMorales** [comment]
Thoughts on when this will be re-visited @kylecarbs ? Just curious. 

Would love to be able to just leverage an existing workspace instead of going to create a new one every time I press on "Open In Coder" on one of my repos.

Sort of looking at how GitHub Codespaces has the flow where they just let you leverage the existing codespaces that a user has made.

**Comment by michaelbrewer** [comment]
If there was a way to send a signal to a running workspace, there you could have a flow like this.

- "Open in coder" using the same workspace template with a special to start using any existing workspace.
- During the redirect if there are any matching workspaces the user can select it.
- This when sends a signal to that running workspace with parameters like git url to clone
