### ISSUE TITLE
feature: List all enabled and available experiments on the deployment page

### ISSUE THREAD

**Issue by matifali** [coder/coder#8978]
We already show enable experiments at deployments. https://dev.coder.com/api/v2/experiments
but it would be nice to list them on the deployment page.

This could be rendered as a list in the form of

- `deployment_health_page` ✅
- `moons`
- `workspace_actions` ✅
- `single_tailnet` ✅
- `template_insights_page`
- `deployment_health_page`

### Must have

- [x] List all enabled experiments on the deployment page

### Nice to have

- [ ] Additionally, list all available experiments
- [ ] Use Human-friendly names for the experiments, e.g., `deployment_health_page` --> `Deployment Health Page` (you may ignore this one as we also need to tell the user the exact string to enable the experiment)

**Comment by Emyrk** [comment]
I think we can just list the values like we do for other deployment value things. Making it very nice and designed is not necessary IMO.

95% of deployments will not use experiments, and the ones that do are inherently more technical for using them.

**Comment by Emyrk** [comment]
Reopen as it's a basic implementation. We can make it look nicer

**Comment by matifali** [comment]
@Emyrk I enabled all experiments on a PR deployment with `CODER_EXPERIMENTS=*`, but I do not see the Experiments field. Does it only appear when we enable individual experiments explicitly?

**Comment by bpmct** [comment]
I'd love if we also linked to the experiments endpoint so the admin can see what can be enabled.

**Comment by matifali** [comment]
@sharkymark I remember you were looking for a way to see all available experiments.

**Comment by Emyrk** [comment]
@bpmct @matifali Experiments are intentionally an "advanced" feature to opt into features that are not ready for production.

Do we really want to show these to everyone, meaning people might just "opt into" these experiments without understanding the repercussions? 

Right now there is the concept of `All` which are safer: https://github.com/coder/coder/blob/9af54754d859338371ce2d189ec8eef2d24759bc/codersdk/deployment.go#L2007-L2014

---

Ya'lls call, just feels like a very niche feature to show all these.
