### ISSUE TITLE
Improve legal protections around dormancy

### ISSUE THREAD

**Issue by ammario** [coder/coder#8987]
Pathologically, someone could edit the dormancy code to 1 day to avoid paying us fairly.
* We should change our standard enterprise license to be based on active users in the trailing 90 days, so it's decoupled from the code. 
* We should move dormancy into `enterprise/` folder

From @bpmct 
* Document our dormancy feature and its rationale

**Comment by mtojek** [comment]
I'm taking a look at this now.

> We should move dormancy into enterprise/ folder

will do 👍 

> Document our dormancy feature and its rationale

@bpmct We have user status documented [here](https://coder.com/docs/v2/latest/admin/users#dormant-user). Do we want a separate section for account dormancy or did you mean something else?

> We should change our standard enterprise license to be based on active users in the trailing 90 days, so it's decoupled from the code.

@ammario I'm not sure if I fully understand. Do you want to rephrase `LICENSE.enterprise`, and add definitions for active users and dormancy?

**Comment by bpmct** [comment]
I think our current docs are fine.

**Comment by ammario** [comment]
Yeah, since the code is in enterprise I think we're good.
