### ISSUE TITLE
ci: test example templates in ci

### ISSUE THREAD

**Issue by matifali** [coder/coder#8991]
## Context

We should test out example templates automatically to be able to update them more frequently. There is a [community PR](https://github.com/coder/coder/pull/8804) that updates the Coder terraform provider in all templates. This is mostly fine, but we need to test each of them individually before merging to `main`, as any issue will cause new deployments to be unable to use the starter templates. 

## Product Requirements

Our ci should be able to test example/starter templates automatically. These automatic tests will give us the confidence to update templates more frequently.

### Must have

- [ ] Test starter/templates in ci. by creating a template, creating a workspace, and then running some commands in the workspace. (similar to [scaletest](https://coder.com/docs/v2/latest/admin/scale#workspace-creation))

### Should have
- [ ] Should only be run if required (e.g., template files are changed)

### Nice to have
- [ ] only test the templates that are changed. (I am looking forward to 100's templates once we launch the [template registry](https://github.com/coder/coder/issues/7216))
- [ ] Periodically test all templates (e.g., weekly. monthly)
- [ ] Test templates against a range of terraform CLI versions (if we want to make them backward compatible)
- [ ] Test templates against a range of terraform provider versions.

**Comment by bpmct** [comment]
related #8551
