### ISSUE TITLE
provisioner_daemons table grows without bounds

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#9015]
We only have SQL queries that add to the table and read from it --- so provisioner daemons are added but never removed.

Reading from the table is only used today to serve an API route to get all the daemons.  It's not clear whether the front end ever uses this information, so it might be that the table has no defined purpose at present...

**Comment by spikecurtis** [comment]
CLI and CoderSDK don't call the API endpoint, and as far as I can tell, the front end doesn't call it either.

It's not very useful for debugging either because the only distinguishing fields are `created_at` and `tags` --- even the names are randomly generated on the server side.

I think the best thing to do for now is just stop inserting into the table until we have an actual use case.

**Comment by mtojek** [comment]
I'm moving this back to the backlog/Ready column as we will postpone work around https://github.com/coder/coder/issues/5979.
