### ISSUE TITLE
coder app share=authenticated "Application Not Found" 

### ISSUE THREAD

**Issue by GilQedma** [coder/coder#9016]
Hello,

I'm using `coder` on kubernetes, and trying to share browser vscode/juptyer between authenticated users.
The user itself can always access his apps, however **other** users always get -
```
404 - Application Not Found
The application or workspace you are trying to access does not exist or you do not have permission to access it.
```

Coder version 2.0.0, installed with `helm`.

Here's my vscode config, for example -
```terraform
resource "coder_app" "code-server" {
  agent_id     = coder_agent.main.id
  slug         = "code-server"
  display_name = "code-server"
  icon         = "/icon/code.svg"
  url          = "http://localhost:13337?folder=/home/coder"
  share        = "authenticated"

  healthcheck {
    url       = "http://localhost:13337/healthz"
    interval  = 3
    threshold = 10
  }
}
```

Checking further, even the **admin** user can't access coder apps of other users.
However, the admin **can** use VSCode Desktop to access everything.

**Comment by GilQedma** [comment]
Hey!
I don't see any logs in the `coder` pod, except for initial workspace start up.
However, in my k8s ingress pod I see -
`[13/Aug/2023:06:12:33 +0000] "GET /@username/test.main/apps/code-server/ HTTP/1.1" 404 6295 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15" "-"`

**Comment by matifali** [comment]
I have reproduced this on dev.coder.com

1. Create a `coder-app` with `share="authenticated"`
![image](https://github.com/coder/coder/assets/10648092/95045bdd-4d5b-4470-95e8-4aaeb6d64baf) and start a workspec from user 1,

2. Log in as User 2 (template admin or owner), and try to access the workspace. (`coder_app` buttons are not showing up.)
![image](https://github.com/coder/coder/assets/10648092/781cd43d-c58c-4bea-9f9f-43f86d6ed3b2)

3. From User 2 (template admin or owner), try to directly access the `coder_app` url.
coder_app is accessible as expected

4. From User 3 (member), try to directly access the `coder_app` url.
![image](https://github.com/coder/coder/assets/10648092/228a6e52-a3b8-4660-bdcd-27d56af7c7d4)


@GilQedma, Can you confirm if the 2nd user is member or template admin?

**Comment by matifali** [comment]
@GilQedma I cannot reproduce this for a user with a template_admin role. We will update if there is anything new.

**Comment by GilQedma** [comment]
Thanks!
Can you reproduce for regular member?

Recall my Owner user is also the template_admin - so my end doesn't reflect "non-owner template 
_admin user" case

**Comment by matifali** [comment]
@GilQedma Yes, I can reproduce for the `member` role.
See https://github.com/coder/coder/issues/9016#issuecomment-1677175195

**Comment by Emyrk** [comment]
For path based apps, this is actually expected by default. There is a flag to change this behavior. When I set the flag, then this is fixed. I should attempt to make this a better error if this is the failure case.


https://coder.com/docs/v2/latest/cli/server#--dangerous-allow-path-app-sharing

**Comment by matifali** [comment]
Yes @Emyrk in my testing used path based code-server.

**Comment by matifali** [comment]
I think this will serve the purpose. Let us  link to the docs page of possible.

**Comment by Emyrk** [comment]
The only issue with linking the docs is I need to pass an href to the HTML template, since error messages shouldn't have HTML embedded. I was going to defer some styling to @BrunoQuaresma.

**Comment by matifali** [comment]
@Emyrk Leave the docs for now. This looks a fine solution.
