### ISSUE TITLE
Unable to change login type to GitHub

### ISSUE THREAD

**Issue by ryansburgoyne** [coder/coder#9034]
I've just gotten Coder OSS set up on my Kubernetes cluster. I enabled GitHub auth, but since I used the same email address as my GItHub account to create my account originally, it told me to change login type in my account settings. I attempted to do that, and it presented me with a confirmation dialog where I entered my password, but then it took me to a blank page with the error:

```
{"message":"\"user\" must be an existing uuid or username."}
```

_Originally posted by @ryansburgoyne in https://github.com/coder/coder/discussions/9031_

**Comment by kylecarbs** [comment]
cc @Emyrk

**Comment by Emyrk** [comment]
Fix PR open. URL was missing part of it's path :cry:
