### ISSUE TITLE
Allow creation of Session token separate from user

### ISSUE THREAD

**Issue by dsloanather** [coder/coder#9036]
Currently it appears you can only create a session token linked to a user which could cause issues when it is used with CI if that user is offboarded.  Would it be possible to allow admins to create a CI/Automation token that is linked either to a system user or completely separate from user auth

**Comment by matifali** [comment]
You can create a new password login user with username **ci** and create a token for that user to use in ci.

**Comment by dsloanather** [comment]
> You can create a new password login user with username **ci** and create a token for that user to use in ci.

I dont think burning a user when you have an enterprise license is the best solution

**Comment by matifali** [comment]
@dsloanather yes you are right. For OSS users this doesn't matter but given an enterprise user there should be another way.
