### ISSUE TITLE
`helm upgrade` results in "You have multiple replicas but high availability is an Enterprise feature. You will be unable to connect to workspaces."

### ISSUE THREAD

**Issue by ryansburgoyne** [coder/coder#9041]
Every time I upgrade my release, I see this message at the top of the application. If I delete the pod and let it be recreated, the message goes away.

**Comment by ericpaulsen** [comment]
possibly related: https://github.com/coder/coder/issues/8927

**Comment by ryansburgoyne** [comment]
Yes sounds like exactly the same issue.

**Comment by Emyrk** [comment]
Duplicate of: https://github.com/coder/coder/issues/8665
