### ISSUE TITLE
bug: When Coder is upgraded workspace page shows an empty banner

### ISSUE THREAD

**Issue by matifali** [coder/coder#9042]
When Coder is upgraded, the Workspace page shows an empty banner with no error message. It goes away with a  page refresh
![image](https://github.com/coder/coder/assets/10648092/7b91b86a-0ea9-499f-88ba-33bc6d198e6f)
cc: @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
Would you have any idea how I could reproduce this artificially?

**Comment by matifali** [comment]
Stay on workspace while you upgrade coder. It would be easy to reproduce with a docker installation

**Comment by matifali** [comment]
@BrunoQuaresma or you can observe this while dev.coder.com is having a new deployment.

**Comment by Kira-Pilot** [comment]
@matifali I dug into this a little bit and it looks like we should [always have a default error message](https://github.com/coder/coder/blob/main/site/src/components/Alert/ErrorAlert.tsx#L9) with this alert component. I'm guessing the API is returning an error in an unexpected shape so we aren't handling it well on the FE. When you get a chance, could you reproduce this issue and then send me the full response from the errored request?

**Comment by bpmct** [comment]
Here is a video: 

https://github.com/coder/coder/assets/22407953/bdde2f6a-1b78-4a4c-b9ec-c63614eb9e2a

**Comment by matifali** [comment]
@Kira-Pilot, do you need anything else, or is the video shared by @bpmct enough?

**Comment by Kira-Pilot** [comment]
@matifali Thanks for checking in! I was not able to reproduce even with the linux template because the agents aren't loading for me but I think I found the culprit anyway. I tagged you [in the PR](https://github.com/coder/coder/pull/10196); maybe you could take a look and verify that branch works as expected?
