### ISSUE TITLE
Adding Git authentication requirement to a template does not apply to existing workspaces

### ISSUE THREAD

**Issue by ryansburgoyne** [coder/coder#9043]
I added a Git authentication requirement to a template so I can use Git in the startup script, as described [here](https://coder.com/docs/v2/latest/admin/git-providers#require-git-authentication-in-templates).

I upgraded a workspace based on the template to the latest version, but it never prompted me to authenticate with GitHub, nor was there any way for me to proactively do so that I could see.

I deleted the workspace and created a new one from the template. This time I was able to authenticate with GitHub. Ideally there should be a way to do it without deleting existing workspaces.

**Comment by ryansburgoyne** [comment]
I discovered that I can authenticate by going to coder.example.com/gitauth/github. Maybe there should be a way to access this from the UI?

**Comment by bpmct** [comment]
Great bug report! Just like we prompt for new parameters, we should prompt to ask the user to authenticate with git

**Comment by matifali** [comment]
Closing in favor of #11367
