### ISSUE TITLE
When I update my running workspace it starts a new pod without deleting the old one

### ISSUE THREAD

**Issue by ryansburgoyne** [coder/coder#9060]
When I update a template, an update button appears on my running workspace that uses the template. If I push it, it starts a new pod, but doesn't delete the old one. This causes an error where the storage fails to attach to the new pod. I have to stop the workspace and then start it again to recover.

**Comment by matifali** [comment]
Could you share your template?

**Comment by matifali** [comment]
We were closing as OP did not provide an update.
