### ISSUE TITLE
EKS, `coder stat` cpu does not show total CPU available, only utilization

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9065]
Version: [`v2.0.2+76ad116`](https://github.com/coder/coder/commit/76ad116e12552ed76dcef9239347fabc37b99e81)

<img width="145" alt="image" src="https://github.com/coder/coder/assets/2022166/c7a0986a-dabe-4e1a-9e6d-0d86760adbcb">

**Comment by sharkymark** [comment]
only happens with `envbuilder` @johnstcn @sreya @kylecarbs

**Comment by johnstcn** [comment]
`coder stat` will omit the total if there is no limit detected.

**Comment by matifali** [comment]
@johnstcn as this is by design let us close this as stale.
