### ISSUE TITLE
processes running on ports not showing up in `Ports` but are available

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9074]
Version: [`v2.0.2+76ad116`](https://github.com/coder/coder/commit/76ad116e12552ed76dcef9239347fabc37b99e81)

My template's `startup_script` starts an NGINX web server with `docker run` on `8080` and another process is a Python web server on `8000`

They should be listed like in previous versions of Coder.

Both do not show up in the `Ports` UI but I can `curl` them or manually enter the port in the Ports UI.

![image](https://github.com/coder/coder/assets/2022166/0f6c355d-7a13-40d5-b5a7-23906d637a4a)

![image](https://github.com/coder/coder/assets/2022166/55c9387c-d0a3-4ea6-bb58-ac62452df474)

![image](https://github.com/coder/coder/assets/2022166/7a5a8737-5410-4eb1-bfd9-1590e0e42f04)

![image](https://github.com/coder/coder/assets/2022166/2e8f2271-5e21-413e-9234-5266d7398c4c)

![image](https://github.com/coder/coder/assets/2022166/b6e0b919-fe0d-4e11-b44f-8a73b93ac008)

![image](https://github.com/coder/coder/assets/2022166/596a8613-35f3-4423-acb5-6ce1661c4b0f)

![image](https://github.com/coder/coder/assets/2022166/90360c86-fe69-431b-80d9-282e1198362e)

@BrunoQuaresma

**Comment by sharkymark** [comment]
@BrunoQuaresma found the bug of sorts. You have to refresh the UI for the ports to show up.

**Comment by matifali** [comment]
@sharkymark I guess it might be related to #8834.

**Comment by BrunoQuaresma** [comment]
Maybe this happens when we try to fetch the ports and the agent is not ready? Or the process that identifies the ports is not ready? cc.: @deansheather do you think this makes sense?

**Comment by aslilac** [comment]
I think it's something a little nastier than that. Even after plenty of time for things to settle, I can refresh the page and only ever see half of the ports being forwarded.

**Comment by BrunoQuaresma** [comment]
@aslilac yes, we are not able to automatically find all the ports. @deansheather has more context on that I guess.

**Comment by aslilac** [comment]
@BrunoQuaresma should we add a little warning that the list may not be exhaustive? or is the goal to make it exhaustive?

**Comment by BrunoQuaresma** [comment]
I think Dean and @bpmct have more context.

**Comment by deansheather** [comment]
Can you please provide the output of `ss -tlpn` and the result of accessing `http://localhost:8080/api/v0/listening-ports` while running `coder port-forward workspace --tcp 8080:4`?

**Comment by deansheather** [comment]
Actually since these are both on workspace proxy enabled deployments I think this is caused by https://github.com/coder/coder/issues/8909.

**Comment by matifali** [comment]
@sharkymark, do you still have this? If not let us close this as completed.
