### ISSUE TITLE
helm repo update error

### ISSUE THREAD

**Issue by SilenceShine** [coder/coder#9075]
Unable to get an update from the "coder-v2" chart repository (https://helm.coder.com/v2):
        failed to fetch https://helm.coder.com/v2/index.yaml : 403 Forbidden

**Comment by SilenceShine** [comment]
![image](https://github.com/coder/coder/assets/126382592/ed18d9bc-84ee-4ad9-ac4e-458c3282cd5c)

**Comment by matifali** [comment]
Not able to reproduce.
