### ISSUE TITLE
A template admin can not update/restart/stop/delete the workspace of another user

### ISSUE THREAD

**Issue by matifali** [coder/coder#9081]
A template admin can not update/restart/stop/delete the workspace of another user, but the buttons are shown
![image](https://github.com/coder/coder/assets/10648092/bf2587cd-5313-4acb-9518-214d01e663a3)

If this is the intended behavior, we should hide the buttons too. 

Discovered while testing #9016

**Comment by bpmct** [comment]
Closing. We address this in #9175
