### ISSUE TITLE
You are signed out or your session has expired. Please sign in again to continue.

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9090]
Version: [`v2.0.2+76ad116`](https://github.com/coder/coder/commit/76ad116e12552ed76dcef9239347fabc37b99e81)

![image](https://github.com/coder/coder/assets/2022166/96f539a4-33e8-4c23-a0cb-a2daa060c1ec)

I purposely set CODER_SESSION_DURATION to 2 days so when this occurs, I only get an error message and no auto-redirect to the login page. Coder basically doesn't fully kick the user out and shows errors or blank screens.

![image](https://github.com/coder/coder/assets/2022166/b88993a0-1dcc-41b9-87f0-1968331e83e5)

![image](https://github.com/coder/coder/assets/2022166/01fdc58c-c785-4cf7-a6d3-89ae23b2b242)

**Comment by aslilac** [comment]
Did some digging into this today:

- If you refresh the page, you'll be redirected back to the login page as expected, so we have that going for us.
- That error message is displayed verbatim, and is coming from the backend. The dashboard isn't looking at the error at all, just splatting it on the screen.
- The `AuthProvider` state doesn't get updated when a token expires.
- All the routes that require authentication are nested within a `RequireAuth` component.

Haven't actually gotten to look at the `RequireAuth` component yet, but I imagine that's going to be the right place to handle this. I'll pick this up again tomorrow.
