### ISSUE TITLE
Add "last used" search parameters to workspaces

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9095]
We have this for users (#8139) but not workspaces.

Let's be sure to include an example in the dropdown + in our docs that we link to:

![image](https://github.com/coder/coder/assets/22407953/9b55db0d-e4fe-40dd-bd2a-f11281e4e46a)

**Comment by BrunoQuaresma** [comment]
PS: We need to add this filter in the BE first.

**Comment by mambon2** [comment]
What we were asking for was a way to identify idle workspaces.  This doesn’t tell us that, because last_used doesn’t track active connections.

**Comment by mambon2** [comment]
I'll create a separate ticket with this specific requirement.
