### ISSUE TITLE
coder-server unhealthy /home/coder permission denied

### ISSUE THREAD

**Issue by rajserc** [coder/coder#9102]
Running into coder-server unhealthy issue.
The workspace is starting in the same K8s as where coder is running but in different workspace.
Looks like some how the permission is not getting created correctly, when pv/pvc is getting provisioned.

code-server
[2023-08-15T03:41:59.777Z] error EACCES: permission denied, mkdir '/home/coder/.config/code-server'
coder@coder-admin-coder-dev-env-ws-1-5b88fd4499-hqrq6:/home$ ls -ltran /home/coder
ls: cannot access '/home/coder': Permission denied
coder@coder-admin-coder-dev-env-ws-1-5b88fd4499-hqrq6:/home$ cd /home
coder@coder-admin-coder-dev-env-ws-1-5b88fd4499-hqrq6:/home$ ls -ltr
ls: cannot access 'coder': Permission denied
total 0
d????????? ? ? ? ?            ? coder

**Comment by matifali** [comment]
Do you have a user `coder` in your container? Also, can you share the `Dockerfile` (if any) and your template?

**Comment by sharkymark** [comment]
like @matifali said, sounds like a container default user issue, like the image is set to `root` or something else.

**Comment by rajserc** [comment]
Thr user id is coder. The image is enterprisebase:ubuntu

I am using the default kubernetes template.

**Comment by rajserc** [comment]
I was able to get inside the pod as root and able to run code-server, so it is some security issue while provisioning  pv/pvc.

**Comment by matifali** [comment]
As you were able to solve it. I am closing it as resolved. Feel free to update if you run into this again.
