### ISSUE TITLE
Blank screen when accessing code-server

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#9109]
When I tried to open code-server in the browser I got this:
![image](https://github.com/coder/coder/assets/3165839/0130ddbd-87a0-4b89-bb08-641bcaadb62c)

After clearing the cookies, in the Brazil URL, it worked.

**Comment by sharkymark** [comment]
@BrunoQuaresma I get this with ws proxies often, especially in gcp. my eks deploy not so much.

clearing cookies sometimes fixes this, but not always.

**Comment by deansheather** [comment]
Before we redirect to coder primary when the cookie is invalid on the proxy, we should probably Set-Cookie the session cookie to be expired so it gets removed @Emyrk 

we probably do something similar in v1 TBH

**Comment by Emyrk** [comment]
I don't think I completely follow. @deansheather are you saying we are redirecting the user with an invalid session cookie, and that is causing this?

**Comment by deansheather** [comment]
I think something's wrong with expired cookies (I'm assuming) which causes the following:
1. user accesses the wildcard app domain (with no signed token)
1. user has expired session token cookie on the wildcard app domain
1. user gets redirected back to coder access URL to do a token smuggling operation
1. coder server redirects the user back with an encrypted token
1. the wildcard app domain (either coder server or proxy) decrypts the token and returns Set-Cookie and redirect to strip the query param
1. the cookie isn't saved properly or duplicate session token cookies exist, which causes the server to think the cookie has expired on subsequent requests again
1. back to 1

**Comment by deansheather** [comment]
@Emyrk ^

**Comment by Emyrk** [comment]
Talked to @deansheather.

We think we need to normalize the app base path to always have a trailing slash here:
https://github.com/coder/coder/blob/630fc0c63d5a5d0662ab6f1c0bbbaef14d193a32/coderd/workspaceapps/request.go#L105-L105

Right now we have potentially 2 cookies for the path with and without the trailing slash. I will work on reproducing, then will fix.

**Comment by deansheather** [comment]
We should also add trailing slashes to the check in `token.go` line 40. `(SignedToken).MatchesRequest(req Request)`.

**Comment by Emyrk** [comment]
`coder_devurl_session_token` is also set twice. Once on the subdomain based, one on the app. If one is expired, you get this error.

So we should check all keys or something.

**Comment by MrPeacockNLB** [comment]
Really looking forward as I see this often

**Comment by deansheather** [comment]
@MrPeacockNLB are you seeing this with workspace proxies (the experimental feature)? Or just regular coderd. And on subdomain apps or path apps?

**Comment by Emyrk** [comment]
@deansheather I reproduces the redirect failure, and it was as we expected in our chat.

Your PR fixes it 👍. Confirmed again after I deployed to our dogfood.
