### ISSUE TITLE
Support linking OIDC accounts, not just git provider accounts

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9116]
## Background

Coder allows developers to link their git accounts to simplify git authentication in their workspace. When they `git clone`, Coder helps them authenticate with their provider or a template can even require that they authenticate in advance of creating their workspace:

![image](https://github.com/coder/coder/assets/22407953/758dac9f-dc1f-4f1f-be98-f5ebe85afbf1)

On the server side, the admin configures this by providing OIDC credentials to the Coder server. The Coder server will store and rotate users' tokens on their behalf. [You can read about this feature in our documentation](https://coder.com/docs/v2/latest/admin/git-providers)

## Vision

There are other cases where a workspace can benefit to being pre-authenticated to other providers. Both for runtime (e.g. artifactory token is injected into the workspace) and build-time (user authenticates with a Terraform provider with their OIDC token).

![Create workspace page](https://user-images.githubusercontent.com/22407953/260834476-e1049239-8b17-428f-b1e9-5ad638436a48.png)

Instead of Coder having to support native integrations with each platform, Coder supports generic OIDC (just like for log in and git auth) and then the template can use the token for whatever it wants (provisioning resources, pre-authenticating a CLI, etc).

To avoid code duplication, we can extend our git auth code to support non-git providers. Coder templates will still magically authenticate `git` for git providers with `GIT_ASKPASS`.

Mock server config:

```sh
CODER_INTEGRATION_0_ID=primary-github
CODER_INTEGRATION_0_TYPE=github
CODER_INTEGRATION_0_CLIENT_ID=xxxxxx
CODER_INTEGRATION_0_CLIENT_SECRET=xxxxxxx
CODER_INTEGRATION_0_GIT_REGEX=github.com/orgname

CODER_INTEGRATION_1_ID=azure-key-vault
CODER_INTEGRATION_1_TYPE=oidc
CODER_INTEGRATION_1_DISPLAY_NAME="Azure Key Vault"
CODER_INTEGRATION_1_ICON="https://wiki.example.org/akv.svg"
CODER_INTEGRATION_1_REQUIRED=true
CODER_INTEGRATION_1_CLIENT_ID=xxxxxx
CODER_INTEGRATION_1_CLIENT_SECRET=xxxxxxx
CODER_INTEGRATION_1_SCOPES="https://vault.azure.net/user_impersonation"
```

Within the template:

```hcl
data "coder_integration" "azure-key-vault" {
  id="azure-key-vault"
}

resource "coder_agent" {
   # 
  env {
    name = "AZ_TOKEN"
    value = data.coder_git_auth.token
  }
}
```

### Why not request all of these scopes when the user [authenticates](https://coder.com/docs/v2/latest/admin/auth) to Coder?

Identify providers are typically managed via a different organization than developer tools so it's typically difficult or impossible for organizations to create a central token that Coder can use directly against a large amount of APIs. Some advanced organizations allow token exchanges, but that is still not common.

For example, Azure Active Directory (a common identity provider) can only request scopes from Microsoft's Graph API. There is no way current Coder wants to also request a token that works for authentication and Azure Key Vault, for example.

**Comment by matifali** [comment]
we could also create a new resource `coder_variable` which would be populated by these auth providers and can be consumed by `coder_agent` to ste in the workspace.

This could allow us to modularize the auth methods as separate modules.
