### ISSUE TITLE
Improve UX for cloning personal repos with GitHub Apps

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9121]
## Background

First, Coder has a [git providers](https://coder.com/docs/v2/latest/admin/git-providers) integration that allows users to log in with their git provider (e.g. GitHub). From there, when a user runs a `git clone`, Coder will use GIT_ASKPASS to authenticate on their behalf so that a user does not need to manage SSH keys, tokens, or other git credentials in their workspace. It's all done for them 🪄 

With GitHub specifically, (the scope of this issue), there are two ways for an admin to configure GitHub OAuth:

- GitHub OAuth App: This is a more simple, less secure way to request permissions on behalf of a user. The app can request specific scopes and the user can approve it. If approved on behalf of an organization, then Coder will have access to repos in that organization.
- GitHub App: This is more fine-grained and repo-specific. A GitHub app can be given permission to specific repos and specific organizations.

## The problem

This works great for repos on the org level (coder/coder), but does not when the user needs to clone a personal repo that is private, such as dotfiles (bpmct/dotfiles). Different permissions are required and the UX isn't clear.

### GitHub App flow

Currently, the GitHub App flow will fail with no clear error when the user tries to clone private repos:
   
```sh
bpmct@okokok:~$ git clone https://github.com/bpmct/private-module
Cloning into 'private-module'...
remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/bpmct/private-module/': The requested URL returned error: 403
```

To work around this, the user visit the public app page (which they must know manually) and install the app on their personal account. When they do, there is a weird error on Coder's end:

https://github.com/coder/coder/assets/22407953/ecf42b34-f302-451f-9107-6bbb8d97de55

## Proposed behavior

- Coder's terminal helper text and redirect URL walks through how to install the GitHub app to other sources

    ```sh
    bpmct@okokok:~$ git clone https://github.com/bpmct/private-module
    Cloning into 'private-module'...
    remote: Write access to repository not granted.
    fatal: unable to access 'https://github.com/bpmct/private-module/': The requested URL returned error: 403
    
    Configure your repo authorizations at: https://github.com/apps/...
    ```

- This helper text when the user initially installs the app links to the public app instead of relying on the user to find it themselves. Currently, "reauthenticate" doesn't give the user options to install on new sources.

    <img width="1000" alt="Screenshot_2023-08-15_at_9 13 57_PM" src="https://github.com/coder/coder/assets/22407953/0b240611-d8d1-43a0-ad6c-3b846f029c56">

- When the app is installed, the user is redirected to a better page than this seeming error page

    ```json
    {
      "message": "State must be provided."
    }
  ```

**Comment by stirby** [comment]
Great definition, just needs to be slotted in a sprint.

**Comment by bpmct** [comment]
Added the docs as this may be a docs issue
