### ISSUE TITLE
Your workspace is running but 1 agent is unhealthy. 

### ISSUE THREAD

**Issue by amrhamedp** [coder/coder#9122]
Hello,
I am trying to run coder (without the default tunneling) such that it runs on one computer in my local network and accessible through any machine on this network.  My computer ip address in the network is 10.32.142.26

coder server --access-url http://10.32.142.26 --http-address 10.32.142.26:3000 --wildcard-access-url *.10.32.142.26

-I am not sure if this setting is correct or not 
-I can run generate workspace and docker is created but vscode or health status will not show up
-if i removed all arguments after code server, it will work fine which means that those arguments are not set in correct way
-I am not sure how to print the message which shows why the vscode is not accessible through the coder ui when i use the above arguments.
-additionally, when i tried to access the docker container created from outside, I find that the internet speed inside container is pretty low compared to outside (3mb/s vs 100mb/s outside)

what is the correct way to do this? 
I would appreciate your help . Thanks

**Comment by matifali** [comment]
I noticed a few things, 
1. You need a proper wildcard domain with TLS set up to be used for wildcards. remove `--wildcard-access-url *.10.32.142.26`
2. change `--http-address 10.32.142.26:3000` to `--http-address 0.0.0.0:3000` if you want to access it from other computers on your network.

**Comment by simonjcarr** [comment]
> 2\. change `--http-address 10.32.142.26:3000` to `--http-address 0.0.0.0:3000` if you want to access it from other computers on your network.

@matifali Can you confirm that this is required for other computers on the network to connect. Will this not instead tell coder to listen on all configured IP's on your computer. i.e. localhost, LAN & WIFI?

**Comment by matifali** [comment]
@simonjcarr Don't you want to expose Coder on your local network?
You either also set `--http-address 127.0.0.1:3000` to only run locally and then may be used a reverse proxy to expose it over the internet.
You can check these docs for reference. https://coder.com/docs/v2/latest/admin/configure#tls--reverse-proxy

**Comment by amrhamedp** [comment]
after upgrading to newest version 2.5 I get:
your admin has not configured subdomain access on vs code (web)
coder server --access-url http://10.32.142.26 --http-address 0.0.0.0:3000

I am not sure what shall be done now?

**Comment by matifali** [comment]
@amrhamedp can you share your coder_app for vscode web.
