### ISSUE TITLE
`coder start <workspace>` incorrectly prompts for immutable parameters

### ISSUE THREAD

**Issue by mjswensen** [coder/coder#9133]
# Coder version

```txt
Coder v2.0.2+76ad116 Thu Aug 10 17:02:02 UTC 2023
https://github.com/coder/coder/commit/76ad116e12552ed76dcef9239347fabc37b99e81

Full build of Coder, supports the  server  subcommand.
```

# Steps to reproduce

1. Create a workspace template that defines a parameter. In our case, we let users input a custom AMI ID from which to base their EC2 instance

```terraform
data "coder_parameter" "ami" {
  name        = "AMI"
  description = "Which AMI should this workspace be built from?"
  default     = "<redacted, our default AMI ID>"
  mutable     = false
}
```

2. Create a workspace from the template, inputting the desired parameter value.
3. Stop the workspace.
4. Start the workspace from the command line using `coder start <workspace name>`

# Observed behavior

The `coder` CLI prompts for a value for the parameter, even though it is immutable and has already been provided at creation time.

```sh
$ coder start matt
AMI
  Which AMI should this workspace be built from?

> Enter a value:
```

- If no value is provided, `coder` throws a validation error saying that it is required.
- If a value is provided, `coder` throws an error saying that the parameter is immutable and cannot be changed.

# Expected behavior

Since the parameter is immutable and has already been provided at creation time, the `coder` CLI should not prompt for a value for this parameter. `coder start` should work the same as clicking the "Start" button in the UI and simply start the workspace.

**Comment by Emyrk** [comment]
Fixed here https://github.com/coder/coder/commit/669ae9d4d379660ce9091396315193b8dd9c2de6
