### ISSUE TITLE
Show build logs over 1 month old in the UI

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9161]
## Background

We didn't add a pagination support for the build logs on the `/workspace/` page. At the time, we decided to only show 1 month of logs to avoid 

## Current behavior

We only show a month of build logs. If the workspace was last built over 1 month ago, there is no way to fetch those logs a month ago and Coder reports that the logs are empty, which is not true.

https://github.com/coder/coder/blob/71d5882341d44706c63597aa4a79bb02d7526307/site/src/api/api.ts#L762-L770

## Proposed solution

Add pagination to build logs on workspaces page to show everything, OR only show the last `n` builds instead of doing it based off date. Pagination is preferred.

**Comment by BrunoQuaresma** [comment]
@mtojek we first need to add pagination in the backend for the build logs endpoint.

**Comment by mtojek** [comment]
I see. In this case, maybe we should detach it from Sprint V. @bpmct Any preferences?

**Comment by mtojek** [comment]
I will review it tomorrow and see what is feasible to do.

**Comment by BrunoQuaresma** [comment]
@mtojek if you think we can have the back-end until next week, I think I can get this one.

**Comment by mtojek** [comment]
Clarification: this is not about workspace agent logs, but paging workspace builds.

`https://dev.coder.com/api/v2/workspaces/398766f2-1234-1234-1234-cb42225fe151/builds?since=2023-08-30T09:19:39.032Z`

**Comment by mtojek** [comment]
@BrunoQuaresma I dived into the backend code, and it seems that workspace builds are already pageable: [code](https://github.com/coder/coder/blame/2dd49cc0a7210b9270084c2841c6af2ec3ed7f22/coderd/workspacebuilds.go#L96-L108).

All you need to do is replace `since` with `offset` & `limit`. Is it exactly what you require?

**Comment by BrunoQuaresma** [comment]
Even better, thank you @mtojek

**Comment by BrunoQuaresma** [comment]
@bensejas @matifali Does make sense to have a "load more" button instead of the regular pagination with "page number"?

**Comment by matifali** [comment]
@BrunoQuaresma yes laid more is a better idea IMO.
