### ISSUE TITLE
coder-server unhealthy

### ISSUE THREAD

**Issue by lishengwei691** [coder/coder#9162]
I am using system kubernetes template and I have this problem, how should I fix that, I would appreciate it if you could help me out
![image](https://github.com/coder/coder/assets/55377463/e35ddf99-4464-41c4-8bef-03801229a57d)

**Comment by sharkymark** [comment]
it means code-server didn't start and is failing the healthcheck. Open terminal and `ps aux` to see if it's running. Maybe the `curl` to install `code-server` in the `startup_script` of the template failed.

**Comment by lishengwei691** [comment]
I re-executed it again, and it prompted insufficient permissions. I searched and found that someone also encountered this problem. Where can I solve this problem?
![image](https://github.com/coder/coder/assets/55377463/5baa0f3e-105f-4894-aebe-a0c7bd868b44)

**Comment by lishengwei691** [comment]
Here is my script，I added some proxy

![image](https://github.com/coder/coder/assets/55377463/b99540a6-9b77-41ed-8046-a1d55d004395)

**Comment by lishengwei691** [comment]
Added these proxies and it works for now, 🙂 Thank you very much for your help!

**Comment by lishengwei691** [comment]
![image](https://github.com/coder/coder/assets/55377463/ecf41f5c-c24b-4382-aafa-64f03278e3c0)
