### ISSUE TITLE
bug: echo provisioner can insert duplicate resources at the plan stage

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#9169]
Discovered while working on https://github.com/coder/coder/issues/9145

Adding a unique index to the workspace agent auth token table currently breaks the `echo` provisioner used in unit tests with an error similar to the below:

```
    t.go:90: 2023-08-18 09:23:30.424 [erro]  provisionerd: sending CompletedJob failed  job_id=402cac2a-1ee4-4eec-9736-7d32682c3d2d  template_name=hopeful-lehmann8-wEr  template_version=eloquent_hamilton1  workspace_build_id=bc16b783-7cf7-434f-95a9-7bc33927f674  workspace_id=dd3cc6ca-0576-4a1c-9a79-5eb4227f0007  workspace_name=flamboyant-raman8-wfT  workspace_owner=testuser  workspace_transition=start ...
        error= complete job: execute transaction: insert provisioner job: insert agent: pq: duplicate key value violates unique constraint "workspace_agents_auth_token_uniq_idx"
                storj.io/drpc/drpcwire.UnmarshalError:26
                storj.io/drpc/drpcstream.(*Stream).HandlePacket:224
                storj.io/drpc/drpcmanager.(*Manager).manageReader:247
```

This can be reproduced with the following code:

```
coderdtest.CreateTemplateVersion(t, client, user.OrganizationID, &echo.Responses{
	Parse:          echo.ParseComplete,
	ProvisionApply: echo.ProvisionApplyWithAgent(authToken),
})

// ProvisionApplyWithAgent(authToken) is a short-cut for the following:
[]*proto.Provision_Response{{
		Type: &proto.Provision_Response_Complete{
			Complete: &proto.Provision_Complete{
				Resources: []*proto.Resource{{
					Name: "example",
					Type: "aws_instance",
					Agents: []*proto.Agent{{
						Id:   uuid.NewString(),
						Name: "example",
						Auth: &proto.Agent_Token{
							Token: authToken,
						},
					}},
				}},
			},
		},
	}}
```

The echo provisioner currently expects the following struct as an argument:
```
type Responses struct {
	Parse          []*proto.Parse_Response
	ProvisionApply []*proto.Provision_Response
	ProvisionPlan  []*proto.Provision_Response
}
```

When no value is supplied for `ProvisionPlan`, it will silently use the value provided as `ProvisionApply` as the value for `ProvisionPlan`. 

```
	if responses.ProvisionPlan == nil {
		responses.ProvisionPlan = responses.ProvisionApply
	}

```

This ends up returning created resources in the `ProvisionPlan` stage, which provisionerd dutifully inserts into the database. In the above example, the test is supplying a known `authToken` which gets inserted into the database at planning stage, meaning we will attempt to insert again at the apply stage.

**Comment by spikecurtis** [comment]
This'll get cleaned up in the refactor I'm currently doing.

**Comment by spikecurtis** [comment]
Actually, I don't think this is related to Echo repeating resources in plan & apply.  Even today, provisionerd only uses the resources on `Plan` to commit & check Quotas -- it doesn't even send the agent token.

https://github.com/coder/coder/blob/04d5e3f54fdb0732dbcc43f3bad59dbd5853e603/provisionerd/runner/runner.go#L1061

More likely, the issue is that many of our tests hard-code the token, rather than generate it, so there are legit collisions in the tests.

If we want to insert the unique index, we need to fix the tests.

**Comment by johnstcn** [comment]
Dug into this some more, and this mainly becomes an issue under the following circumstances:
1) You generate an auth token and pass this into an `echo.Responses{}` when creating a template version. This is a common pattern in many of our tests, for example:

```go
authToken := uuid.NewString()
version := coderdtest.CreateTemplateVersion(t, client, user.OrganizationID, &echo.Responses{
	Parse:         echo.ParseComplete,
	ProvisionPlan: echo.PlanComplete,
	ProvisionApply: []*proto.Response{{
		Type: &proto.Response_Apply{
			Apply: &proto.ApplyComplete{
				Resources: []*proto.Resource{{
					Name: "example",
					Type: "aws_instance",
					Agents: []*proto.Agent{{
						Id:        uuid.NewString(),
						Directory: tmpDir,
						Auth: &proto.Agent_Token{
							Token: authToken,
						},
					}},
				}},
			},
		},
	}},
})
```

2) You create multiple workspaces from that specific template version.

Because echo just returns the `[]*proto.Response` it was configured to, it will return the same resources each time a workspace is built.

Some possible ways of approaching this right now (there are probably others):

a) Refactor the affected unit tests to not use the pattern above, and instead fetch the agent auth token directly from the database, e.g.

```go
client := coderdtest.New(t, ...)
db, ps := dbtestutil.New(t)
client := coderdtest.New(t, &coderdtest.Options{
	Database: db,
	Pubsub: ps,
})
[...]
build := coderdtest.AwaitWorkspaceBuildJob(t, client, workspace.LatestBuild.ID)
dbAgt, err := db.GetWorkspaceAgentByID(ctx, build.Resources[0].Agents[0].ID)
require.NoError(t, err)
agentClient := agentsdk.New(client.URL)
agentClient.SetSessionToken(dbAgt.AuthToken)
```


b) Refactor the echo provisioner to allow dynamically changing the responses returned.
This could be done e.g. by utilizing `gomock`, or by modifying `echo.Responses` similar to the below:

```
type ResponseFunc func() []*proto.Response
type Responses struct {
	Parse ResponseFunc
	ProvisionApply ResponseFunc
	ProvisionPlan  ResponseFunc
        [...]
}
```

Given the scope of these changes though, I'm not convinced that this needs to be done right now.

**Comment by spikecurtis** [comment]
I don't think we can modify the Echo provisioner to execute an arbitrary function.  The echo provisioner works by generating all the responses and then tar'ing them up.  There isn't a good way to serialize go code, and I don't think we'd want to.

We could consider adding special-case handling to the echo provisioner specifically for the auth token.  Like, you include a special file that has a bunch of tokens, one per line, and it uses them in order.  Or, it generates random tokens and you fetch them from the database.
