### ISSUE TITLE
Add validation to `Create Workspace` UI versus vague failed workspace build messages in Terraform

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9179]
Version: [`v2.1.0+c15ce7b`](https://github.com/coder/coder/commit/c15ce7b4529779de059b758f6aa89e57a7c91c0f)

I mistakenly used capitalized letters in a workspace name.

The user does not know about this capitalization limitation, so they only find out when the workspace build fails, in the build log showing Terraform errors where you can kind of figure out that workspace name is the culprit.

![image](https://github.com/coder/coder/assets/2022166/3609d476-9fc7-4293-8936-843d3042948d)

CC @BrunoQuaresma

**Comment by Kira-Pilot** [comment]
@sreya talked to Kyle and we are going to check the logs and display a conditional warning rather than blanket validate and insist all workspace names are lowercase.

**Comment by Kira-Pilot** [comment]
@sreya @kylecarbs  After sketching some designs today, I don't think we should move forward with this ticket. We were planning to display a suggestion alongside the error message, e.g. _This resource doesn't appear to support uppercase letters. Try surrounding the property with the `lower()` Terraform function_, but this is problematic:

- This validation error can occur for a variety of reasons, casing being only one
- Kubernetes is responsible for this error message and its subject to change at any time without warning, so parsing it is fragile
- The user would still only find out about the limitation after the build has failed, which is the actual frustration expressed above
- I don't relish the idea of designing around a one-off suggestion

Open to other thoughts but I suggest we close this for now.
