### ISSUE TITLE
Wildcard hostnames create false positive OWASP rule detection

### ISSUE THREAD

**Issue by timquinlan** [coder/coder#9186]
Coder wildcard hostnames use a double dash ( -- ) to delimit username, workspace name, agent name, and app name in coder_app URLs.  A WAF that enforces OSWASP rule 942440 (SQL Comment Sequence Detected) will trigger a false positive based on the presence of a double-dash ( -- ) in the URL.  To remediate, create a WAF policy that does not enforce rule 942440 for your Coder traffic.

**Comment by deansheather** [comment]
We use double hyphens so we can support single hyphens in app names, agent names, workspace names and usernames. There aren't any other separator characters we can use so we have no plans to fix this.

Please disable the WAF policy to avoid this issue or avoid using subdomain apps
