### ISSUE TITLE
Block duplicate OIDC user accounts instead of creating random named user

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#9210]
Using AD OIDC integration we have scenarios where a user can login using a different AD account with similar username.

It creates a duplicate user account in the form of:

```
user
user-randomname123
```

It can cause confusion. 

Is it possible to block this scenario from happening entirely? 

Should probably be happening at AD but there can be a disconnect and we don't manage those groups.

Thanks

**Comment by dcarrion87** [comment]
Thoughts on this one?

**Comment by matifali** [comment]
cc: @Emyrk This lokks similar to the GitHub [issue](https://github.com/coder/coder/issues/10972) we recently solved. Could you look into this?

**Comment by Emyrk** [comment]
@matifali This is different because it is intentional behavior: https://github.com/coder/coder/pull/4614

This is a hard issue to solve because it is difficult to know when 2 accounts from 2 different sources are intended to be the same person.
