### ISSUE TITLE
Improve insights query performance and reduce usage windows from 5 min to 1 min (or none, where applicable)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#9214]
Currently the insights queries are not optimized and take a bit too long for some deployments. We should improve performance where we can and try to reduce the usage window which can skew the numbers slightly.

We currently use `generate_series` in PostgreSQL, which at 5 min intervals already generates a lot of rows (= a lot of joins), reducing this to 1 min is not ideal and will slow down the query. So other options are to be evaluated.

**Comment by bpmct** [comment]
@mafredri i believe we fixed this?

**Comment by mafredri** [comment]
Oh, you're right @bpmct! I forgot to close this via the PR. Fixed by #9302.
