### ISSUE TITLE
Expose the number of used/free licenses in the UI

### ISSUE THREAD

**Issue by mnebelnlb** [coder/coder#9220]
We are looking for a way to monitor the number of used / free licenses. Is it possible to expose this information via prometheus?

**Comment by ammario** [comment]
<img width="1239" alt="image" src="https://github.com/coder/coder/assets/7416144/96c47a18-8edd-4705-b627-7aa93c53849a">

I think we should build a UI in the Licenses page with this information too.

**Comment by matifali** [comment]
@BrunoQuaresma, don't we already have this?

**Comment by BrunoQuaresma** [comment]
I think we have 🤔

**Comment by MrPeacockNLB** [comment]
It seems the missing information are already exposed via prometheus:

![image](https://github.com/coder/coder/assets/103434584/b2329303-0b4d-49d6-8926-847961e5391e)

**Comment by MrPeacockNLB** [comment]
We want to track the gap between maximum seats and used seats

**Comment by stirby** [comment]
I'm unsure what's not available here? Is `coderd_license_active_users` only **active** users, as in logged in? We could add `coderd_licensed_users`.
