### ISSUE TITLE
Provisioner using PSK will not be selected if a `scope` tag is absent

### ISSUE THREAD

**Issue by pratheekrebala** [coder/coder#9234]
Good Evening!

I have been trying to deploy external provisioners using the pre-shared key based authentication. Despite various attempts using different configurations, I was unable to get the provisioner to be selected. However, I was able to select the provisioner when using my personal user token.

Upon further inspection, it seems that an external provisioner that is missing an `scope=organization` tag will never be selected. I am not sure if this is intended behaviour. It would make sense that provisioner deployments have to be explicit about specific the scopes that they would be serving. I only realized this when looking at the `/api/v2/organizations/me/provisionerdaemons` endpoint and noticed that all the inbuilt provisioners have the `scope=organization` tag on them.

The current helm chart does not add this tag which means that jobs will just hang unless the in-built provisioner daemons are enabled.

**Comment by pratheekrebala** [comment]
I *think* the issue could be happening because of the difference in logic here (assuming defaulting to org scope is acceptable):

https://github.com/coder/coder/blob/69ec8d774b658b32eac3524ebca2edf3a841afea/coderd/coderd.go#L1083-L1091

https://github.com/coder/coder/blob/69ec8d774b658b32eac3524ebca2edf3a841afea/enterprise/coderd/provisionerdaemons.go#L190-L196

**Comment by bpmct** [comment]
cc @spikecurtis

**Comment by spikecurtis** [comment]
All provisioner jobs default to `scope=organization`, unless they are specifically set to `scope=user`.

I guess we should also default this tag for external provisioners.  In the meantime @pratheekrebala, you can work around the issue by explicitly setting the tag in your Helm values.yaml.

**Comment by johnstcn** [comment]
@pratheekrebala PSK auth will now automatically set the provisionerd scope to organization.
