### ISSUE TITLE
Unable to adjust logging configuration for external provisioner daemon

### ISSUE THREAD

**Issue by pratheekrebala** [coder/coder#9235]
Good Evening!

When running an external provisioner using `coder provisionerd start`, I am unable to set the log level using flags that I could use for other commands (e.g. `--verbose` `CODER_TRACE_ENABLE`, `CODER_VERBOSE`) etc.

I ran into this when trying to debug provisioner connections for https://github.com/coder/coder/issues/9234. I was looking for the debug message announcing a successful connection but was unable to surface them using the usual config options.

**Comment by johnstcn** [comment]
@pratheekrebala Thanks for reporting this! It should be included in the next release.

cc @bpmct
