### ISSUE TITLE
Publishing a template in UI does return to the template UI and should provide a confirmation

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9243]
Version: [`v2.0.0+ad513fa`](https://github.com/coder/coder/commit/ad513fa8b90dc851113589df93f67885bd4571cf)

As an operator (e.g., owner or template admin), if I `Build` and then `Publish` a template in the Coder dashboard UI, there is no confirmation message nor does the UI revert to the template dashboard UI view like in previous releases.

This is a regression. I was able to return the template dashboard UI in release in `2.0.0`

If you click  `Publish` again it shows the same version name but should have a new name generated.

With previous releases and this release, the `Build` button shows available and a green `Success` label next to it, but we should consider graying out the `Build` button if there are no pending template changes, to signal to the user that `Publish` is the only action available.

@BrunoQuaresma 

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ue2qc)

**Comment by BrunoQuaresma** [comment]
I see more than one thing here:

**Bugs**
- Not redirecting to the template UI after publish
- The new version name in the modal is not correct. It is using the previous one

**Feature**
- Disable the build button if there are no changes to apply

**Comment by bpmct** [comment]
I saw @aslilac also suggested a "save and keep editing" option. I'd be open to something like this in the dropdown

**Comment by aslilac** [comment]
> I was able to return the template dashboard UI

You can still do this navigation by clicking on the name of the template while in the editor, but we might want to make that more noticeable somehow.
