### ISSUE TITLE
prometheus coderd_agentstats_* metrics missing 

### ISSUE THREAD

**Issue by mnebelnlb** [coder/coder#9244]
The documented metrics for `coderd_agentstats_*`  are missing in the prometheus output. Did I miss a configuration? coded_api_* and coderd_agents_* and coders_authz_* are visible.

**Comment by coadler** [comment]
The agentstats metrics are behind the flag `--prometheus-collect-agent-stats` or env `CODER_PROMETHEUS_COLLECT_AGENT_STATS`. Do you have either of these enabled?

**Comment by mnebelnlb** [comment]
Ok - I tricked myself by updating the subject :-( Sorry for the confusion!

I'm looking for the `coderd_agentstats_*` as mentioned in https://coder.com/docs/v2/latest/admin/prometheus#available-metrics. Especially the information like `coderd_agentstats_session_count_jetbrains`etc.  Did I miss to activate another flag?

**Comment by mnebelnlb** [comment]
As you might have guessed: no, I didn't .... :-/ 

Enabling this flag and *waiting* some minutes solved my problem. Thanks!
