### ISSUE TITLE
Failed to install provider since 2.0.1

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#9246]
We've been seeing this show up more since upgrade from 0.27 to 2.0.1:

```
Error: Failed to install provider
Error while installing coder/coder v0.11.1: open
/home/coder/.cache/coder/provisioner-0/tf/registry.terraform.io/coder/coder/0.11.1/linux_amd64/terraform-provider-coder_v0.11.1:
text file busy
```

The error is obvious just not sure why it would block this way.

**Comment by dcarrion87** [comment]
These are coming in thick and fast now. Any thoughts?

**Comment by matifali** [comment]
@dcarrion87 Are you also including the `.lock` files in your template directory?

**Comment by dcarrion87** [comment]
@matifali no we're not. Is this something new / I've missed. Can you link me to the relevant / new documentation around packaging process. I'm not sure why it would die like this though.

**Comment by matifali** [comment]
@dcarrion87 I think the issue is not related to `.terraform.lock.hcl` file.

The ability to include the `.terraform.lock.hcl` file with a template was added to allow the Coder to not download the providers on each workspace build. 

For your issue, I am trying to reproduce it and will get back with details.

**Comment by dcarrion87** [comment]
Thanks @matifali. I'll look to implement that across our workspace templates. That will no doubt help with this issue if it avoids trying to install again anyway.

**Comment by dcarrion87** [comment]
Hi @matifali we just run a single coder pod with whatever the default gives us. I think that's 3 inbuilt by default?

**Comment by mafredri** [comment]
@dcarrion87 what does your provisioner configuration look like? Are you by any chance running multiple `coder provisionerd start` under the same user?

**Comment by dcarrion87** [comment]
@mafredri single coder server pod with no provisioner overrides. Whatever that gives us by default inbuilt.

**Comment by dcarrion87** [comment]
We set up coder v2 before any of the helm stuff was cooked. We literally run a single coder pod with no additional provisioners. So probably using inbuilt provisioner? We only have 10-15 active users at any one time on each coder server so have no need for segregated provisioners.

**Comment by mafredri** [comment]
Thanks for clarifying @dcarrion87.

We didn't find any code changes that make this change in behavior immediately obvious. But we'll investigate this further.

One more sanity check: is there a chance that the `TF_PLUGIN_CACHE_DIR` environment variable is set for your coder instance?

**Comment by dcarrion87** [comment]
Not being set.

We are getting such odd behaviour since this upgrade. API Server being unavaialble and now this one:

```
====================
Coder: Build has been detected as hung for 5 minutes and will be terminated.
====================
```

Want to go back to 0.27 😆

**Comment by dcarrion87** [comment]
Getting it when pushing templates now too provider install failure when pushing templates as well.

**Comment by dcarrion87** [comment]
Could be completely unrelated but what are the RAM requirements these days for coder? I've noticed the server that is giving us particular grief is almost at the 1GB limit we set for the pod. Do I need to crank it?

**Comment by mafredri** [comment]
@dcarrion87 I've tried to reproduce locally with docker-based templates and a default coder server configuration, but I haven't been able to.

> **TF_PLUGIN_CACHE_DIR** is not being set by us.

Thanks for confirming.

> Want to go back to 0.27 😆

If you have backups, it should be doable 😄. Our backwards migrations are usually lossy though, so even though utilizing those is one possibility, I would not recommend it on a production server.

> The only thing different this time is it was two workspace stops happening at the same time (different users).

This is a bit suspicious, the default configuration creates 3 provisioner daemons so these two stops should've run on separate daemons. Each daemon has it's own cache dir (`${CODER_CACHE_DIR}/provisioner-${i}`). So triggering this error suggests to me one of two things:
1. Both provisioners are using the same cache dir (which should not be possible)
2. Something other than coder (anti-virus, shared/network filesystem, etc.) is holding a lock on the cache files that the provisioner is trying to access

Could you try stopping the coder server, wiping the provisioner caches (`rm -rf /home/coder/.cache/coder/provisioner-*`) and then starting coder server again?

> Getting the provider install failure when pushing templates as well.

Also suspicious, suggests to me that there's no concurrency and option 2 from above is the most likely.

> Could be completely unrelated but what are the RAM requirements these days for all in one coder server pod? I've noticed the server that is giving us particular grief is almost at the 1GB limit we set for the pod. Do I need to crank it? Haven't seen any OOM events on it.

I think you're fine, but I'd say it depends on your template. Typically I see my coder server instance idling around 70-160MB, and workspace start/stop may bring total usage up to ~300MB (that's with multiple terraform commands running). Depending on the template, terraform could probably consume a lot more.

**Comment by dcarrion87** [comment]
> Could you try stopping the coder server, wiping the provisioner caches (rm -rf /home/coder/.cache/coder/provisioner-*) and then starting coder server again?

The coder server pods file systems are ephemeral. Every time we update and the pod restarts it gets a new home.

Really don't understand how a default install can go belly up like this across a couple versions.

It's probably one of the most frustrating consequences we've experienced of an update so far as it's really blocking users having to re-fire until the cache banana stops.

**Comment by dcarrion87** [comment]
For reference these are the envs we overwrite. Definitely some legacy ones we probably need to change but none that I think would affect this:

```
CODER_ACCESS_URL
CODER_DERP_SERVER_ENABLE
CODER_USERNAME
CODER_TELEMETRY
CODER_OIDC_ISSUER_URL
CODER_DERP_CONFIG_URL
CODER_PG_CONNECTION_URL
CODER_ADDRESS=0.0.0.0:3000
CODER_OIDC_CLIENT_SECRET
CODER_PASSWORD
CODER_OIDC_CLIENT_ID
CODER_EMAIL
```

Image is: ghcr.io/coder/coder:v2.0.2

**Comment by dcarrion87** [comment]
There is some serious problems in 2.X

This is tanking builds and leaving us with major cleanups to do: 

![Screenshot 2023-08-28 at 12 14 51 pm](https://github.com/coder/coder/assets/2899172/1ab1cabf-b2d6-4c4a-9de8-44312b0b35a1)

**Comment by dcarrion87** [comment]
@mafredri @matifali There is some serious problems in 2.X

This is tanking builds and leaving us with major cleanups to do per user.

Nothing leading up to this indicated at all that it was hung

![Screenshot 2023-08-28 at 12 18 38 pm](https://github.com/coder/coder/assets/2899172/843781e8-5e6c-4273-a005-c38c3ded3344)

**Comment by matifali** [comment]
@mafredri @sreya We have not seen any more reports around this issue. Should we close this?

**Comment by mafredri** [comment]
@matifali yeah, let's close it. The root cause was excessive memory consumption that has since been amended by single tailnet.
