### ISSUE TITLE
bug(ui): resizing the terminal is not smooth at all

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#9256]
![](https://cdn.discordapp.com/attachments/1143083076860268555/1143090044119293952/coder_term_weird.gif)

---

Server version is ``v2.0.2-devel+7404ee9b2``
Chrome stable v116.0.5845.96
Windows 11 22621.2134

---

When resizing the terminal, the PTY gets spammed and it fails to put the prompt at the proper place.
And resizing is generally slow, I believe that the components take a "lot" of time to render, which causes this non-smooth effect.

**Comment by matifali** [comment]
I can also experience this,

https://github.com/coder/coder/assets/10648092/b5675bfa-211a-4e83-a1f5-93f1698f2ad2

**Comment by ammario** [comment]
Maybe https://github.com/coder/coder/pull/9320 helps.

**Comment by matifali** [comment]
I confirm this is resolved by #9320. Tested via a PR deployment.
