### ISSUE TITLE
Error with 2.1.1 when planning workspace: coder_parameter names must be unique 

### ISSUE THREAD

**Issue by amanibhavam** [coder/coder#9260]
Coder 2.1.1 complains about non-unique coder_parameter names when Terraforming a workspace, preventing the workspace from stopping or starting.

Downgrading to 2.1.0 removes this problem.

This is the Coder template: https://github.com/defn/dev/tree/main/m/coder/dfd

Error:
```
"recv workspace provision: plan terraform: coder_parameter names must be unique but "cpu", "docker_image", "memory", "nix_volume_size" and "provider" appear multiple times"
```

<img width="1459" alt="image" src="https://github.com/coder/coder/assets/62630472/6449f7ca-6e0b-44dd-a556-43f2e7f85e18">

**Comment by mtojek** [comment]
I don't think that we introduced any major changes between 2.1.0 and 2.1.1, see [changelog](https://github.com/coder/coder/releases/tag/v2.1.1), unless it is https://github.com/coder/coder/pull/9201.

Could you please prepare a small sample template without extra providers/resources to present the problem? Right now if it complains about lack of credentials for AWS and Fly.io.

**Comment by mtojek** [comment]
Ok, I looked around and managed to reproduce it. Unfortunately, it is the outcome of https://github.com/coder/coder/pull/9201. 

Terraform provider fails the use case with a module. For instance:

main.tf:
```
module "workspace" {
  source = "./mod/terraform-coder-defn-dev"
}
 ```

./mod/terraform-coder-defn-dev/coder.tf
...

./mod/terraform-coder-defn-dev/params.tf
```
data "coder_parameter" "cpu" {
  name         = "cpu"
  display_name = "CPU"
  description  = "The number of CPUs to allocate to the workspace"
  type         = "number"
  default      = "4"
  icon         = "https://raw.githubusercontent.com/matifali/logos/main/cpu-3.svg"
  mutable      = true
  validation {
    min = 4
    max = 16
  }
}

data "coder_parameter" "memory" {
  name         = "memory"
  display_name = "Memory"
  description  = "The amount of memory to allocate to the workspace in GB"
  type         = "number"
  default      = "8"
  icon         = "/icon/memory.svg"
  mutable      = true
  validation {
    min = 8
    max = 64
  }
}
```

@ammario  should we revert https://github.com/coder/coder/pull/9201 temporarily?

**Comment by amanibhavam** [comment]
@mtojek Thanks for the fix!  Next time I'll make smaller repros without creds.
