### ISSUE TITLE
support a `DELETE` endpoint for workspaces

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#9261]
we currently do not support a `DELETE` API call for automating workspace deletion. the current approach requires using the `POST workspaces/{workspace}/builds` and setting `transition: delete` in the request.

multiple customers have given feedback using the `/builds` endpoint for deletion is hard to find and initially confusing.

**Comment by Emyrk** [comment]
Does anyone object to this?

I can easily add an endpoint that just does the `DELETE` workspace build.

**Comment by ericpaulsen** [comment]
speak now or forever hold your peace.

**Comment by matifali** [comment]
There is a related discussion on this on discord. 
https://discord.com/channels/747933592273027093/971231372373033030/1153344645133238323

**Comment by kylecarbs** [comment]
Why don't we just document this well?

It doesn't make sense to have a DELETE endpoint, because it wouldn't be deleted immediately anyways... we need the infrastructure to be deleted first before we mark the workspace as deleted.
