### ISSUE TITLE
OIDC refresh tokens should not require user interaction (OR possibly need a clearer error message)

### ISSUE THREAD

**Issue by hh** [coder/coder#9268]
I get the following error displayed, which requires me do do some action (usually clicking or refreshing the page) that I think should  be handled by coder itself when using OIDC.

```
> oauth2: "invalid_grant"

"The provided authorization grant or refresh token is invalid, expired, revoked,
 does not match the redirection URI used in the authorization request,
 or was issued to another client"
```

![image](https://github.com/coder/coder/assets/31331/c92a1031-65f1-4b86-9584-97a15cbbfa4b)

I'm configured coder for Authentik OIDC via env vars here:

https://github.com/cloudnative-coop/infra/blob/uk/apps/coder/helm-release.yaml#L106-L140

I'm configured Authentik with a coder OIDC Provider as follows:

![image](https://github.com/coder/coder/assets/31331/888c6780-60a6-4c1f-bde0-d2526b2d0dbf)

![image](https://github.com/coder/coder/assets/31331/4e15366f-e746-4baa-88da-1424e8495d28)

**Comment by bpmct** [comment]
Thanks for reporting. We're taking a look
