### ISSUE TITLE
can't use templates to create new workspaces in version 2.1.1

### ISSUE THREAD

**Issue by spettinichi** [coder/coder#9280]
When we try to create or restart a workspace after upgrading to 2.1.1 we get this error

`running command "coder templates push": template import provision for start: recv import provision: plan terraform: coder_parameter names must be unique but "CPU(cores)", "disk(GB)" and "memory(GB)" appear multiple times`

The values in quotes are indeed the name values for the 3 coder_parameters we have set, however they are only set one time, there is no duplication. I downgraded back to 2.1.0 and workspaces start correctly. I also am unable to push an updated template from the cli due to the same error. When I check the template checked into git as well as what I can view in the UI these names all appear exactly one time.

I have this installed in kubernetes using helm.

**Comment by amanibhavam** [comment]
@spettinichi They fixed it, see https://github.com/coder/coder/issues/9260
