### ISSUE TITLE
Add `coder_agent_script` resource for running parallel startup tasks

### ISSUE THREAD

**Issue by kylecarbs** [coder/coder#9287]
We do not have much modularity in our templates right now. There's no way to add new features to your template without just copying another template. This proposes we add a `coder_agent_script` resource that allows for parallel operations on start in a self-contained module.

```tf
resource "coder_agent_script" "code-server" {
    agent_id = coder_agent.dev.id
    name = "code-server"
    icon = "/icons/code.svg"
    script = <<EOF
        curl -fsSL https://code-server.dev/install.sh | sh
    EOF
}
```

We should add a lifecycle to this, but default to execute on `start`. This would run and appear in the logs UI in tabs for each script:

![image](https://github.com/coder/coder/assets/7122116/a1162a40-95fe-49e6-a2b6-5ad6a6eca47a)

This allows us to provide aspects of the startup script as Terraform Modules. Enabling customers to add features to their workspaces:

```tf
module "code-server" {
  source  = "coder/code-server"
  version = "1.73.0"
  extensions = [
    // list extensions to be automatically installed on start
  ]
}
```

A module could provide parameters as well, enabling entirely self-contained modules that mutate an agent.

**Comment by ammario** [comment]
I've been looking for this recently. I would also like if it had an `at` field the defaulted to `startup`, but could also be a cron.

**Comment by mafredri** [comment]
I've been thinking about this as `coder_agent_service`, but this works quite nicely too!

As @ammario mentioned, being able to assign it to a lifecycle or cron would be nice (startup, shutdown, etc). Another is restart policy, `restart => on_error|always|never`.

**Comment by ammario** [comment]
We're essentially rebuilding systemd at this point, but that isn't necessarily a bad thing. It would be cool if this was implemented in a way where it could run standalone outside of Coder.

**Comment by ammario** [comment]
I think starting it named as `coder_agent_service` is a nice idea since the script can run indefinitely or on a cron. We want to invoke imagery of systemd services. 

Also: a timeout field would be quite nice.

**Comment by matifali** [comment]
This is now available as [`coder_script`](https://registry.terraform.io/providers/coder/coder/latest/docs/resources/script).
