### ISSUE TITLE
`coder templates pull` does not work as expected on Windows

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9291]
https://github.com/coder/coder/assets/22407953/08e57ccb-6c24-430c-8155-8f7e50a33443

It creates a folder, but no files

**Comment by matifali** [comment]
I can pull a template just fine
```pwsh
PS C:\Users\matif\tmp> coder templates pull deeplearning
Extracting template to "deeplearning/"
PS C:\Users\matif\tmp> coder templates pull deeplearning PATH
Extracting template to "PATH"
PS C:\Users\matif\tmp> ls .\deeplearning\
PS C:\Users\matif\tmp> ls .\PATH\

    Directory: C:\Users\matif\tmp\PATH

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          25/08/2023 10:17 am          10852 deeplearning-connect.png
-a---          25/08/2023 10:17 am          11401 main.tf
-a---          25/08/2023 10:17 am           2181 README.md
```
When we do not provide a path, the folder is empty
When we provide a path, the folder contains all files

**Comment by mtojek** [comment]
Regarding 2nd issue -

I'm not a Windows developer, but it was always a problem to redirect binary output. See this [article](https://www.leeholmes.com/redirecting-binary-output-in-powershell/). Maybe you should try it @matifali .

**Comment by matifali** [comment]
I investigated it a bit more and found out that by default, PowerShell converts the output to string and to keep the data as binary, we need to enable an experimental flag `PSNativeCommandPreserveBytePipe` as discussed in https://github.com/PowerShell/PowerShell/issues/1908#issuecomment-1577142452. This is only available in pwsh version 7.4.x while the current version on Windows 11 is 7.3.
More on enabling experimental features: https://learn.microsoft.com/en-us/powershell/scripting/learn/experimental-features?view=powershell-7.3

**Comment by matifali** [comment]
Using PowerShell 7.4.0-preview.5 solves the issue resolves issue 2 in https://github.com/coder/coder/issues/9291#issuecomment-1692892450

**Comment by matifali** [comment]
@spikecurtis For the second issue, I guess we should wait for PowerShell 7.4 to be widely available as it is not an issue with Coder. This issue can be closed if we solve 1st.
