### ISSUE TITLE
minikube install

### ISSUE THREAD

**Issue by danwillo** [coder/coder#9296]
Hi, ive been following the install for k8s, and have got as far as trying to access the dashboard. im not overly clear on what i need to set in the values.yaml to access the dashboard. the external ip minikube has assigned is 127.0.0.1:80, but just getting resource not found from that. any ideas?

im running minikube on wsl2.

Pod IP:

NAME                     TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
coder                    LoadBalancer   10.99.79.252     127.0.0.1     80:30197/TCP   20h

if i add that ip to the values.yaml:

kubectl logs coder-5bb5695df5-z8z6c
Started HTTP listener at http://0.0.0.0:8080

View the Web UI: http://127.0.0.1:80
WARN: The access URL  http://127.0.0.1:80  isn't externally reachable, this may cause unexpected problems when creating workspaces. Generate a unique *.try.coder.app URL by not specifying an access URL.

thanks

**Comment by danwillo** [comment]
anyone able to help with this at all ? we need to test coder before we decide if it suits my orgs needs. thanks

**Comment by matifali** [comment]
@danwillo If you just need a test, I would advise using k3s, Kubernetes, or even docker-compose. You can find installation instructions for both on https://coder.com/docs/v2/latest/install
