### ISSUE TITLE
dev.coder.com is slow for one user with template admin role, but not for owner role

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#9328]
# Problem

An internal user reported today that the web UI was particularly slower for them on `dev.coder.com`. 

The account they were using had the role `Template Admin`. After changing the account to have the `Owner` role, they reported the UI was significantly faster.

I noticed an uptick in the number of reported RBAC errors in the past 30 days, potentially related?

https://app.datadoghq.com/logs?query=service%3Acoder%20%40msg%3A%22requester%20is%20not%20authorized%20to%20access%20the%20object%22%20&cols=host%2Cservice%2C%40fields.actor_name&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1690362163913&to_ts=1692954163913&live=false

**Comment by matifali** [comment]
I have captured the network logs here: https://codercom.slack.com/archives/CJURPL8DN/p1692955648632759?thread_ts=1692952721.060889&cid=CJURPL8DN.

**Comment by johnstcn** [comment]
For posterity, I'm unable to reproduce the issue with a similarly setup user account (Template Admin role only).

**Comment by bpmct** [comment]
@matifali how slow is it? If it leads to a degraded experience which makes Coder frusterating to use, perhaps we should make this higher than `s4`

**Comment by matifali** [comment]
@bpmct This has been very slow from past few weeks and is frustrating. I will record a new network activity tomorrow.
