### ISSUE TITLE
site: something went wrong while using "echo" provider

### ISSUE THREAD

**Issue by mtojek** [coder/coder#9334]
Coderd supports two types of provisioners: "echo" and "terraform". While running e2e tests we're using the "echo" provisioner, and if you want to take a peek into the site during execution, you would get:

<img width="1528" alt="Screenshot 2023-08-25 at 14 01 03" src="https://github.com/coder/coder/assets/14044910/94ebc078-3c6f-4cc9-9d39-2e689eff4530">

Steps to reproduce the issue:
1. Add `await page.pause()` after `createTemplate` step in some e2e test.
2. Run `pnpm playwright:test e2e/tests/updateWorkspace.spec.ts --headed`.
3. Navigate to the created template using "echo" provisioner, for example - http://localhost:3000/templates/38b08be1/files
4. Boom!

**Comment by BrunoQuaresma** [comment]
Is there a way to reproduce this outside of e2e tests?

**Comment by mtojek** [comment]
It should be doable with a batch of `curl` calls, but it will be exactly the same as the e2e test. 

Maybe try to run an e2e test scenario against your local deployment? Behind the scenes, it will create a special tar file, upload it to Coder, and set the template version. I tried to prepare `curl` commands, but it requests hacking `coder` CLI.

**Comment by mtojek** [comment]
@BrunoQuaresma It looks like you can reproduce it with `./scripts/develop.sh`:

1. Create any template.
2. Upload `mtojek-echo.tar` using CLI:
`cat mtojek-echo.tar |  ./scripts/coder-dev.sh templates push --test.provisioner echo -y -d=- <template-id>`

I can provide you `mtojek-echo.tar` over slack as Github doesn't like it.

**Comment by BrunoQuaresma** [comment]
Fixed by https://github.com/coder/coder/pull/9408
