### ISSUE TITLE
Add "Create workspace" button to the Workspaces page

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9335]
## Problem statement

It's a bit confusing UX-wise how to create a new workspace. It's not a primary CTA and requires some scanning to go to the template page, click a template, and create workspace from a template. 

## Proposal

- Add "Create workspace" button to workspaces page    
    <img width="1372" alt="Screenshot 2023-08-25 at 8 17 17 AM" src="https://github.com/coder/coder/assets/22407953/2de189c8-0201-4b16-b430-daa1ed3f3030">
- Make some type of wizard thing that lets the user browse and pick a template? I could use some help with this but would be down to collaborate on a design or wireframes 😛 

## Vision

  - A small template list might be tricky because we can imagine Coder deployments may have dozens of templates for different use cases or even tags/filters with different templates. I'm actually a fan of the "starter templates" view of navigating different templates by tag. Related: #5492
  - There may also be a flow where a user enters a repo URL instead of a template, and Coder tries to find the best template for the repo

**Comment by BrunoQuaresma** [comment]
Additional: When the button is clicked, we could display a dialog showing the templates + filter input.

**Comment by kylecarbs** [comment]
I think it's a great idea to show a dropdown of the most commonly-used templates in short-form (sorted by the # of developers), with a link at the bottom of "Browse all Templates" or something.

**Comment by Parkreiner** [comment]
Going to start on some Figma mock-ups for this

**Comment by Parkreiner** [comment]
Just adding one quick note before closing this. The button itself is out, but the colors are still in line with what we currently have.

Figured it'd be best to get the functionality in place first, and then address colors on a more app-wide basis. Seems like the timing is good, too, with Kyle pushing for the new default color theme
