### ISSUE TITLE
Coder SSH lag

### ISSUE THREAD

**Issue by smolinari** [coder/coder#9352]
Hi,

I started a discussion in Discord but didn't find any takers. I'd now like to give the feedback officially, because I think it is important for Coder usage. 

Please read the initial post: https://discord.com/channels/747933592273027093/991429648200245358/1143075523124277248

...and the thread right after. 

If you need the full story of the issue added here, please let me know.

Scott

**Comment by matifali** [comment]
Hi @smolinari is it related to #9397?

**Comment by smolinari** [comment]
@matifali - I'd say no. I'm not seeing overall connectivity issues. I'm only seeing a major lag in reactiveness, when I run a process in a console connected via Coder's SSH and only after about 15 minutes of it running. Once Coder finally responds, i.e. I get an active SSH connection again, everything seems to run as usual. So, I'd say my issue is fairly minor compared to that one. 

My issue is more a "usability annoyance". :grin:  

Scott

**Comment by ammario** [comment]
From @coadler:

> this is because tailscale removed keepalives, without activity tailscale will make the conn idle and require another handshake. already working on a patch

I'm also experiencing the issue.

**Comment by smolinari** [comment]
The removal of the keepalive is interesting. I wonder what the reasoning is on Tailscale's part. It is technical or political in nature. :thinking: 

Scott

**Comment by smolinari** [comment]
I'd like to report back that this is fixed now. Thanks so much! What a nice difference to come back to my terminals and have them react quickly. Much, much better!

Scott
