### ISSUE TITLE
Scroll bar flicker in startup log viewer

### ISSUE THREAD

**Issue by aaronlehmann** [coder/coder#9353]
I noticed that sometimes the workspace startup log viewer gets into a state where when it's scrolled all the way to the bottom, the horizontal scroll bar appears and disappears extremely rapidly (many times per second), leading to a distracting flicker.
![image](https://github.com/coder/coder/assets/10601430/e0f02f48-7979-463f-ad8e-1180fc05c5f2)

**Comment by matifali** [comment]
@aaronlehmann Do you still have this? I have not seen this from the last few releases, so it could already be resolved. 
We can close it if you are not facing this anymore.

cc: @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
I'm not able to reproduce this anymore.

**Comment by aaronlehmann** [comment]
I haven't seen this recently. Let's close it for now.
