### ISSUE TITLE
Timeout after 3 seconds while downloading the agent behind Emissary Ingress

### ISSUE THREAD

**Issue by devpikachu** [coder/coder#9361]
Hello,

I've setup Coder in a Kubernetes cluster. When setting up a new workspace using the default K8s template, the agent crashes indefinitely whilst trying to download the agent from the server.

This seems to happen consistently at 3 seconds into the request.

Trying it locally with `curl`:
```bash
curl -vSL https://cluster-address/bin/coder-linux-amd64 -o coder

100 33.2M    0 33.2M    0     0  8076k      0 --:--:--  0:00:04 --:--:-- 8076k* HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
100 33.2M    0 33.2M    0     0  8065k      0 --:--:--  0:00:04 --:--:-- 8067k
* Connection #0 to host coder.omnilium.cloud left intact
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

Trying it with `wget`:
```bash
wget https://cluster-address/bin/coder-linux-amd64 -O coder

--2023-08-27 19:31:42--  https://cluster-address/bin/coder-linux-amd64
Resolving cluster-address (cluster-address)... <ips> ...
Connecting to cluster-address (cluster-address)| <ip> |:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘coder’

coder                                                [               <=>                                                                                      ]  29.70M  10.0MB/s    in 3.0s    

2023-08-27 19:31:47 (10.0 MB/s) - Read error at byte 31142129 (The request is invalid.).Retrying.

--2023-08-27 19:31:48--  (try: 2)  https://cluster-address/bin/coder-linux-amd64
Connecting to cluster-address (cluster-address)| <ip> |:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 71159808 (68M), 40017679 (38M) remaining [application/octet-stream]
Saving to: ‘coder’

coder                                             94%[+++++++++++++++++++++++++++++++++++++++++++++====================================================>      ]  64.20M  11.1MB/s    in 3.1s    

2023-08-27 19:31:52 (11.1 MB/s) - Read error at byte 67320347/71159808 (The request is invalid.). Retrying.

--2023-08-27 19:31:54--  (try: 3)  https://cluster-address/bin/coder-linux-amd64
Connecting to cluster-address (cluster-address)| <ip> |:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 71159808 (68M), 3839461 (3.7M) remaining [application/octet-stream]
Saving to: ‘coder’

coder                                            100%[++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=====>]  67.86M  15.9MB/s    in 0.2s    

2023-08-27 19:31:54 (15.9 MB/s) - ‘coder’ saved [71159808/71159808]
```

Emissary's metrics report:
![image](https://github.com/coder/coder/assets/30475873/a6a51b70-a18c-4251-9ab7-3132dc04bfcd)

Changing `CODER_ACCESS_URL` to the internal cluster address (`http://coder.coder.svc`) mitigated this issue, as it seems like the external LB is the bottleneck that slows down the connection.

Being a dev cluster, I'm not looking to beef up the LB, so that's not a solution.

Changing the URL, however, now says that I am running in HA without a license:
![image](https://github.com/coder/coder/assets/30475873/292b61cf-8816-4e46-9896-f58ffed39c83)

I see no way to configure the timeout of Coder, so I'm unsure how to proceed.

**Comment by kylecarbs** [comment]
As far as I'm aware, we don't set up a 3 second timeout. We presently look for `curl` -> `wget`, but it'd be helpful in this situation if we could force `wget`.

Can you try adding `--http1.1` as a flag to cURL?

**Comment by kylecarbs** [comment]
Ahh, I see you updated your comment. I'm happy you found a workaround.

The "running in HA" is a bug when the Coder server doesn't gracefully exit. It's a bug we're fixing, and it will go away in ~5m.

**Comment by devpikachu** [comment]
Hey @kylecarbs ! Thanks for the very fast response. Here's `curl` with HTTP/1.1:

```bash
curl -fsSL --compressed https://coder.omnilium.cloud/bin/coder-linux-amd64 -o coder --http1.1

curl: (18) transfer closed with outstanding read data remaining
```

Also, can confirm, the banner went away just as I was writing this update.

**Comment by kylecarbs** [comment]
Super weird. 

We actually don't even set a `ReadTimeout` on our HTTP server (which is arguably a bug), so it must not be our server. I've also downloaded the agent binaries from Coder on suuuuuper slow WiFi before without issues, so my gut-take is that it's not in our server.

Do you have a proxy in front on your external access URL?

BTW to make the work-around something supported, you can actually modify the Coder provider block in your template:
```
provider "coder" {
  url = "http://coder.coder.svc"
}
```
And then you can set your access URL back to external!

**Comment by devpikachu** [comment]
So, it turns out I was lead astray by the metrics reported by Emissary. It seems like by default, Emissary mappings have a `3000 ms` timeout ([source](https://www.getambassador.io/docs/emissary/latest/topics/using/timeouts#request-timeout-timeout_ms)). Updating the mapping to `30000 ms` (a bit overboard, but /shrug) fixed the issue and I can now `curl` the agent without issues.

Thanks so much for your assistance, Kyle! And apologies for the misleading ticket.

**Comment by kylecarbs** [comment]
Awesome! No problem at all, always happy to help.
