### ISSUE TITLE
healthcheck: configurable database delay

### ISSUE THREAD

**Issue by matifali** [coder/coder#9381]
The delay to mark the database as unhealthy should be configurable. currently, it looks like hardcoded to 15 milliseconds.

https://github.com/coder/coder/blob/b6e808d11628f6c407ca1c025a717edae0533173/coderd/healthcheck/database.go#L49-L51

I have a deployment where the remote db has 28-29 ms latency, and Coder is marking it as unhealthy.

![image](https://github.com/coder/coder/assets/10648092/8de02d78-d6b8-4a68-ae56-df3c48dc603e)

**Comment by Emyrk** [comment]
It would be nice if we could display a warning. I think the site might be quite slow with a slow db latency because of how many round trips we make.

**Comment by matifali** [comment]
@Emyrk, for context, this deployed on fly.io with Postgres in the same region, and I should investigate why the latency is that high, too.

**Comment by Emyrk** [comment]
I understand for test deployments this is common. But we should display some warning that tells the user things will work, but this is not ideal.

**Comment by johnstcn** [comment]
Grabbing this one.

**Comment by matifali** [comment]
@johnstcn I think we should instead do it as three health levels.
delay < 15 ms --> healthy
15ms <= delay < 25 --> warning
delay > 25ms --? existing behaviour

**Comment by johnstcn** [comment]
> @johnstcn I think we should instead do it as three health levels. delay < 15 ms --> healthy (green) 15ms <= delay < 25 --> warning (yellow) delay > 25ms --? problem (red)

Covered by https://github.com/coder/coder/issues/9754
