### ISSUE TITLE
Allow template admins to create a workspace from any version

### ISSUE THREAD

**Issue by aslilac** [coder/coder#9415]
Helpful for iterating on templates. Currently you can only create a workspace from the default version, but template admins can switch versions once created. We should remove that unnecessary step, and allow creating a workspace from any version available.

Related to #9243 and #9346

**Comment by matifali** [comment]
It would be nice to have. Should improve our UX.

**Comment by mtojek** [comment]
> We should remove that unnecessary step, and allow creating a workspace from any version available.

FYI This might be tricky to do if past template versions introduce or remove rich parameters. It may happen that workspace users won't be able to switch.

**Comment by matifali** [comment]
@aslilac I guess to close this issue we should also add a button on versions page to allow creating workspace from any version. 
![Screenshot 2023-09-13 121615](https://github.com/coder/coder/assets/10648092/bc4b350d-6f33-4e0a-acb9-629c3c6c0f07)

**Comment by matifali** [comment]
> This change does not yet expose a "version selector" of any kind to the user. We probably want to add that still, and it shouldn't be to hard, but this is a useful upgrade as is and I think building this out further incrementally will work just as well.

Let us keep this issue open until we have this.

**Comment by bpmct** [comment]
This is another page I think we can add a "create workspace" button for each version

![image](https://github.com/coder/coder/assets/22407953/21ed74d1-1f3f-4830-a7f2-fea1bdacbf9b)

**Comment by aslilac** [comment]
I think that's the second page @matifali was suggesting

but yeah, I think these would be good improvements

**Comment by matifali** [comment]
@aslilac yes my suggestion is to add it to 2nd page. But we can add it to both I guess.
