### ISSUE TITLE
test flake: enterprise/wsproxy TestWorkspaceProxyWorkspaceApps_Wsconncache/ReconnectingPTY

### ISSUE THREAD

**Issue by matifali** [coder/coder#9422]
Seen in https://github.com/coder/coder/actions/runs/6006900082/job/16292158168#step:5:674

**Comment by sreya** [comment]
I'm pretty sure this was fixed by https://github.com/coder/coder/pull/9765 I can't reproduce it on main anymore. Tried running `go test -v -failfast -timeout=30m -count=10000 -race -run TestWorkspaceProxyWorkspaceApps_Wsconncache/ReconnectingPTY/OK`
