### ISSUE TITLE
Add enterprise badges around the product

### ISSUE THREAD

**Issue by ammario** [coder/coder#9439]
We want to remind our paying users what they're paying for and why they should continue paying. Features such as workspace scheduling should have an enterprise label. We can take inspiration from the docs:

<img width="329" alt="Screenshot 2023-08-30 at 9 40 43 AM" src="https://github.com/coder/coder/assets/7416144/f9918d06-30da-4ad6-abc6-c1d011662822">

cc @BrunoQuaresma

**Comment by BrunoQuaresma** [comment]
Would be nice if you could map those places where we should add them so I can work on some design. Maybe, for a few of them, a badge might not work since the space is quite limited.

**Comment by ammario** [comment]
I think you could use https://coder.com/docs/v2/latest/enterprise as a map. Wherever these features are exposed through the UI is a badge opportunity.

**Comment by ammario** [comment]
The Template > Schedule page is in dire need of this. Since these badges are pretty easy to add we should try and catch them during review.

**Comment by matifali** [comment]
related to #11730

**Comment by kylecarbs** [comment]
This isn't particularly actionable, even though I think it should be done. Make specific issues, please!
