### ISSUE TITLE
Hide SSO section account settings if no providers are configured

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9444]
Alternatively, we could advertise the feature and say: "No SSO providers are configured with this Coder deployment".

![image](https://github.com/coder/coder/assets/22407953/f5b781d2-a56c-4757-a92d-9cfb7107ce66)

**Comment by sharkymark** [comment]
Related to #9394 @bpmct

**Comment by Parkreiner** [comment]
Taking this one.

**Comment by Parkreiner** [comment]
Have a preview:
<img width="1624" alt="Screenshot 2023-09-21 at 5 11 37 PM" src="https://github.com/coder/coder/assets/28937484/4b31edf9-4159-4263-97d0-011dde5cd802">

Going to be opening a PR with the changes in just a few minutes
