### ISSUE TITLE
site: do not wrap metadata unnessarily

### ISSUE THREAD

**Issue by matifali** [coder/coder#9457]
When we have space, we should not wrap metadata items to the following line and instead show them in a single line. See video

https://github.com/coder/coder/assets/10648092/e1d15454-8bd4-4ddd-9c5c-dce49912c0e1

**Comment by bpmct** [comment]
related ##8887

**Comment by BrunoQuaresma** [comment]
Closing this in favor of https://github.com/coder/coder/issues/8887
