### ISSUE TITLE
Auto generate admin API key on server start

### ISSUE THREAD

**Issue by dcarrion87** [coder/coder#9466]
At the moment we carve out an admin key for various tasks automated tasks.

Just wondering if there is some way of carving out an API key on server start up so I can push it up to a vault.

It's a bit tedious having to manage this process manually at the moment.

**Comment by MrPeacockNLB** [comment]
yes, that would be nice. Using ESO to push back the secret to an secretstore. See https://external-secrets.io/v0.9.4/api/pushsecret/

**Comment by dcarrion87** [comment]
Actually just realised you can post to:

```
https://{my_coder_host}/api/v2/users/login

{
    "email": "admin@mydomain.com",
    "password": "SUPERSECRET"
}
```

And get a token.

That will do!

**Comment by Emyrk** [comment]
@dcarrion87 one thing to note is the `/login` creates shorter duration tokens by default. Set by [`CODER_SESSION_DURATION`](https://coder.com/docs/v2/latest/cli/server#--session-duration) with a default of 24hrs.

The `//users/{user}/keys/tokens [post]` endpoint allows creating much longer lived tokens. The default being 30 days.

See docs: https://coder.com/docs/v2/latest/api/users#create-token-api-key

**Comment by dcarrion87** [comment]
@Emyrk yep auth retry being built into the solution.
