### ISSUE TITLE
health check endpoint: do not show `healthy: false` if Coder falls back to websockets

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9470]
If `upgrade: derp` doesn't work, Coder passively falls back to WebSockets. This is _slightly_ slower but not significant to my knowledge. We should not show errors in this case, but perhaps a warning?

**Comment by matifali** [comment]
related to #8966

**Comment by bpmct** [comment]
It is related, but slightly different :) added to the umbrella issue

**Comment by mtojek** [comment]
I'm going with this one.
