### ISSUE TITLE
Delete a bulk of workspaces

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#9473]
Hi Coders,

I would like to be able to select multiple WS and delete them all as a bulk. Could be nice to add a Checkbox on each row of the WS view to select and enable a bulk action button delete or stop all selected (To Owners or Template Admin). 

Also it would be nice that users with Owner permissions don't have to write the Name of workspace to delete WS each time. As Owner I'm pretty sure what Im deleting, to clean up the UI it could take me like 30min 

![image](https://github.com/coder/coder/assets/97964900/037024db-b9e9-4308-b199-76c9426075ed)

**Comment by francisco-mata** [comment]
I just want to add this feature also, Let Owners and Template admin to delete a template not required anymore, and to remove all WS associated to it. Instead of the warning message, it would be nice to have a Checkbox to "Remove WS by force" 

![image](https://github.com/coder/coder/assets/97964900/67067e7d-0175-4c02-bc28-cbf12a9d7884)

![image](https://github.com/coder/coder/assets/97964900/b299c8fb-f87e-4d7c-aaf6-ca1efe042808)

**Comment by sharkymark** [comment]
I like your thinking

**Comment by matifali** [comment]
Hi @francisco-mata, the ability to batch delete workspace without entering the name has been recently added and will be available in next release. 
This will resolve your problem partially. I agree that a checkbox to automatically delete all workspace of the template being deleted will improve the UX further. 
Again thanks for the feedback.

**Comment by MrPeacockNLB** [comment]
yes and if #8962 gets implemented this operation is even more safe.
