### ISSUE TITLE
Remove default owner:me filter for Owners or Template Admin

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#9474]
Hi Coders,

For an admin user of Coder, its kinda annoying removing everytime the filter owner:me from the filter bar when I click the Workspace Tab. AS an admin user, I barely use Coder as an end user, so I'm not interested on my WS, I'm focus on all WS created, running, stopped and abandoned to be removed. When I try to remove 15 abandoned WS, I had to go 1 by 1, clicking on the row, writing the name of the WS (totally unnecessary/annoying), clicking on delete, and going back to WS tab, remove the owner:me filter and repeat 15 times.

![image](https://github.com/coder/coder/assets/97964900/5352a448-d913-4575-b402-a32b07086fc7)

**Comment by BrunoQuaresma** [comment]
Hey Francisco, thank you for sharing your problem with us.

I can see how annoying this can be, but I think we can approach the subject a little differently, as we've had a similar discussion in the past and some users think differently.

Perhaps the best solution would be to remember the last filter selected by the user, what do you think?

**Comment by Parkreiner** [comment]
Going to take this one really quickly. We'll be implementing the solution so that the page remembers the last filter used.
