### ISSUE TITLE
Feature Request: Allow marking `coder_parameters` as `"sensitive"`

### ISSUE THREAD

**Issue by DolceTriade** [coder/coder#9489]
Sometimes we might want to allow users to specify per-user credentials in the template so we can set up auth for them. It would be nice if we could mark these as sensitive so they don't autocomplete in the browser.

**Comment by matifali** [comment]
@DolceTriade Thanks for the feedback. Using a `coder_parameter` isn't recommended to store secrets. Can you talk more about your use cases and how you would like to use them to get user secrets? A sample template should work.
Also, I assume you will want to avoid the secret rendered in the UI.

To serve your purpose well, Coder may someday have [user-level secrets](https://github.com/coder/coder/issues/7087).

**Comment by DolceTriade** [comment]
No, the user-level secrets is exactly our use case...To pre-authenticate users so that the environment is ready to go as soon as they start it. Otherwise, users have to create the environment and then manually authenticate with stuff... We can close this as a dupe of user level secrets.

**Comment by matifali** [comment]
Please feel free to leave your suggestions on the linked issue. It could help increase the priority of that feature. Currently, it is on `roadmap-maybe`
