### ISSUE TITLE
CLI output shows an unuseful error

### ISSUE THREAD

**Issue by matifali** [coder/coder#9492]
Many of the CLI commands output a message that is not useful for the end user.
```console
$ coder ls
running command "coder list": You are not logged in. Try logging in using 'coder login <url>'.:
    github.com/coder/coder/v2/cli.init                                                         
        /home/runner/actions-runner/_work/coder/coder/cli/root.go:78                           
$ coder templates list
running command "coder templates list": You are not logged in. Try logging in using 'coder login <url>'.:
    github.com/coder/coder/v2/cli.init                                                                   
        /home/runner/actions-runner/_work/coder/coder/cli/root.go:78                                     
$ coder features list
running command "coder features list": You are not logged in. Try logging in using 'coder login <url>'.:
    github.com/coder/coder/v2/cli.init                                                                  
        /home/runner/actions-runner/_work/coder/coder/cli/root.go:78  
```

we should remove these 2 lines from the output
```console
github.com/coder/coder/v2/cli.init                                                         
        /home/runner/actions-runner/_work/coder/coder/cli/root.go:78
```

**Comment by matifali** [comment]
More examples
```console
$ coder ssh matifali/tf
running command "coder ssh": workspace must be in start transition to ssh:
    github.com/coder/coder/v2/cli.getWorkspaceAndAgent
        /home/runner/actions-runner/_work/coder/coder/cli/ssh.go:542
```

**Comment by Emyrk** [comment]
I took a look into xerrors, and it is `%v` vs `%+v`.

https://goplay.tools/snippet/LvTmFLlP_vK


This information is helpful to us to debug. Maybe there is a better way we can format this?
I imagine if a customer sends us some error, the stack trace is very helpful, but I also understand it might be confusing to someone not familiar with the code.

----

The xerrors line:

https://github.com/golang/xerrors/blob/master/adaptor.go#L45-L48

**Comment by Emyrk** [comment]
If we can decide on some format that we like that include all information, I think we just have to implement this interface: https://github.com/golang/xerrors/blob/master/format.go#L21

Essentially the `Detail` call is how we know when the error being written is now "developer details", so can write a new formatter with a better split than just a newline?
```shell
$ coder ssh matifali/tf
running command "coder ssh": workspace must be in start transition to ssh:

Stacktrace, include with any bug reports!
 |    github.com/coder/coder/v2/cli.getWorkspaceAndAgent
 |      /home/runner/actions-runner/_work/coder/coder/cli/ssh.go:542
```

----

Alternatively, all of our errors _should have unique messages_. So if we drop the stack trace, we should be able to ctl+f the messages themselves and find the line causing the error. Assuming we wrap all errors and raise them correctly.

**Comment by matifali** [comment]
@Emyrk I agree that it helps in getting to root cause. And if its by design we can keep it as it is. But may be we should only show these if someone uses `-v` or `--verbose` flag.

**Comment by matifali** [comment]
Another one
```console
coder@coder:~/coder$ coder login
build info: Get "https:///api/v2/buildinfo": http: no Host in request URL
running command "coder login": Failed to check server "https:" for first user, is the URL correct and is coder accessible from your browser? Error - has initial user:
    github.com/coder/coder/v2/cli.(*RootCmd).login.func1                                                                                                              
        /home/runner/actions-runner/_work/coder/coder/cli/login.go:183                                                                                                
  - Get "https:///api/v2/users/first": http: no Host in request URL  
```

**Comment by Emyrk** [comment]
Yup they will all look this way. I like your idea of the `-v` verbose thing. Sorry I missed that response.

I might give it a stab

**Comment by Emyrk** [comment]
closed by https://github.com/coder/coder/pull/9952
