### ISSUE TITLE
"Group admin" who can troubleshoot their groups' workspaces

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9531]
> This issue is left intentionally vague as it needs an RFC and some RBAC reworks. Reach out to me if you need more details!

## Background

Currently, the Owner role can access _every user's_ workspace to troubleshoot, or that can be disabled.

## Desired behavior

Some teams have specific templates and owners outside of the core platform org. In those cases, the team lead or group admin may want to hop in and debug those workspaces from the template, without having access to every users' workspaces outside of their group they run.

**Comment by matifali** [comment]
Probably we should have ` Platform -> Org -> Project -> Template -> User`

**Comment by sreya** [comment]
We're revamping our permissions system so this will likely be accounted for
