### ISSUE TITLE
VS-CODE Extensions grayed out

### ISSUE THREAD

**Issue by mile15myyahoo** [coder/coder#9537]
Hello,

we have coder on kubernetes installed via helm and we use mostly kubernetes template.
Recently we've adjusted the template to install some vs-code extensions (python, gitlens etc) But the python and gitlens they somehow no not work properly (grayed out).  Please check the screenshot.

![image](https://github.com/coder/coder/assets/139499071/b390bec7-dd3c-4d5f-be32-6aa12927b06f)

```
resource "coder_agent" "main" {
  os                     = "linux"
  arch                   = "amd64"
  startup_script_timeout = 180
  startup_script         = <<-EOT
    set -e
    # install and start code-server
    curl -fsSL https://code-server.dev/install.sh | sh -s -- --method=standalone --prefix=/tmp/code-server --version 4.11.0
    /tmp/code-server/bin/code-server --auth none --port 13337 >/tmp/code-server.log 2>&1 &
    /usr/bin/code-server  --install-extension eamodio.gitlens
    /usr/bin/code-server  --install-extension ms-python.python
    /usr/bin/code-server  --install-extension kevinrose.vsc-python-indent
    /usr/bin/code-server  --install-extension aaron-bond.better-comments
    /usr/bin/code-server  --install-extension littlefoxteam.vscode-python-test-adapter
    /usr/bin/code-server  --install-extension njpwerner.autodocstring
    /usr/bin/code-server  --install-extension humao.rest-client
    /usr/bin/code-server  --install-extension oderwat.indent-rainbow
    /usr/bin/code-server  --install-extension ms-python.flake8
    /usr/bin/code-server  --install-extension redhat.vscode-yaml
  EOT
}
```
Coder Version we use  = 2.4.1
The template use our own image based on codercom/enterprise-base:ubuntu. We install some additional tools like helm, azcli. ... nothing special.
How we can fix the issue?

Thank you!

**Comment by sharkymark** [comment]
It will take longer, but I'm curious if you remove the `&` after starting code-server, to ensure code-server starts before adding vs code extensions.

**Comment by mile15myyahoo** [comment]
Hi @sharkymark 

i think i've fixed it. 
I ve change the code-server path from /usr/bin/code-server to /tmp/code-server/bin/code-server and now python and gitlens extensions are active.

**Comment by matifali** [comment]
Closing as resolved. Feel free to comment if you think it's an issue.

**Comment by sharkymark** [comment]
Nice @mile15myyahoo
