### ISSUE TITLE
Display motd when using web terminal

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#9542]
Would it possible to display a file or execute a command prior to spawning the interactive shell for `coder ssh` or the web terminal?

Specifically, with Ubuntu, I want to display the `/var/run/motd.dynamic` file which can contain some useful notice/info depending on which instance type is being used. Right now, you just get a shell in these cases and may never see this file's contents.

**Comment by MrPeacockNLB** [comment]
see https://registry.terraform.io/providers/coder/coder/latest/docs/resources/agent#motd_file

**Comment by mattlqx** [comment]
Thanks for pointing that out! Doesn't appear to apply to web terminals however. Is that intentional or some other limitation?
