### ISSUE TITLE
UX: coder cli should read login URL from file if not given

### ISSUE THREAD

**Issue by MrPeacockNLB** [coder/coder#9551]
# Description

After a successful login a file **ulr** gets written to **~/.config/coderv2**. After timeout one have to set the login url parameter again.

```bash
 coder-config]$ coder login
build info: Get "https:///api/v2/buildinfo": http: no Host in request URL
running command "coder login": Failed to check server "https:" for first user, is the URL correct and is coder accessible from your browser? Error - has initial user:
    github.com/coder/coder/v2/cli.(*RootCmd).login.func1
        /home/runner/actions-runner/_work/coder/coder/cli/login.go:185
  - Get "https:///api/v2/users/first": http: no Host in request URL
```

# Desired behaviour

If file **url** exists the login url should be taken from this file. No need to pass login url again.

**Comment by johnstcn** [comment]
Workaround: `CODER_URL=https://coder.example.com coder login`

**Comment by matifali** [comment]
@mafredri do we now read from file? or only `CODER_URL` env?

**Comment by mafredri** [comment]
Both, the priority is arg > env > file.
