### ISSUE TITLE
add health check for proxy

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#9558]
if proxies are out of date with the server version, unexpected behavior can occur. the health check endpoint `/api/v2/debug/health` should display configured proxies, their versions and health

**Comment by bpmct** [comment]
This is important because the provisioner code may include "breaking changes" such as parsing values differently. If the provisioner is out of date, the user could see very strange behavior.

**Comment by MrPeacockNLB** [comment]
Thumbs up, as we yesterday trapped (shame on me) into this again

**Comment by mtojek** [comment]
I presume that the goal of this issue is to expose the same data as for `/api/v2/workspaceproxies`.

**Comment by johnstcn** [comment]
We'll probably need to add a `version` column to the `workspace_proxies` table for this.
