### ISSUE TITLE
Keep scaletest environment up-to-date with latest coder release

### ISSUE THREAD

**Issue by mafredri** [coder/coder#9573]
To allow for prolonged testing of the latest coder release, we want to keep the `big.cdr.dev` scaletest deployment in sync with the latest release of `coder/coder`.

A new release of `coder/coder` should trigger an automatic update of the coder server running on `big.cdr.dev`, simlar to `dev.coder.com` but limited to release versions.

**Comment by johnstcn** [comment]
This essentially enails running the following in the release workflow:

```
helm upgrade --install --atomic --reuse-values --version=$VERSION
```

**Comment by mafredri** [comment]
A downside of coupling it to the release workflow is, we'd lose the ability to test non-current versions, and it may interrupt currently running tests (related https://github.com/coder/coder/issues/9574#issuecomment-1740528704).

The constant-running option seems like it would have the same limitation, although I'm sure that could be worked around.

**Comment by johnstcn** [comment]
Installed FluxCD to scaletest environment. Configuration is in a private repo [here](https://github.com/coder/big.cdr.dev).
