### ISSUE TITLE
Allow selecting coder server version used for scaletesting (release, dev build)

### ISSUE THREAD

**Issue by mafredri** [coder/coder#9574]
At first, `big.cdr.dev` the one-click scaletest template will run the scaletest on the deployment itself.

We improve this so that the template spins up a new coder server based on the selected coder build (either release or dev-build).

**Comment by johnstcn** [comment]
It may make sense to instead run two Coder deployments, accessible under different URLs:
- The latest release
- The latest nightly
The scaletest template can then be run on each independently.

**Comment by mafredri** [comment]
@johnstcn that's definitely an option. In that scenario I would still like for us to have the ability to:

1. Prevent automatic updates (while running a scaletest or testing an older version)
2. Ability to easily change the deployed version (ideally accessible in an UI, like the runner)

We don't have to support 2 immediately, but we should keep it in mind. Why do we want it? For instance, say we detect a regression but are not sure when it started, we could then do a bisect type of flow.

That said, the original proposal has two pros:

1. Everything is in one place (version, running)
2. Enables the ability to test multiple versions either sequentially or concurrently

For now though, I'd classify these s as nice-to-haves.

**Comment by johnstcn** [comment]
The Coder deployment on big.cdr.dev is now managed by FluxCD with configuration hosted on https://github.com/coder/big.cdr.dev. To override the version installed, we can either edit the configuration or suspend/unsuspend the HelmRelease directly.
