### ISSUE TITLE
Cant activate free license

### ISSUE THREAD

**Issue by rumenmitrev** [coder/coder#9592]
Hello ,
I have deployed coder via helm chart.
Everything look normal.
When I try to setup the project , I am stuck on  `Step 2. Activate your license.`
Cant activate free license
I passed trough  the docs , but cant find related info
Am I missing something.
Sorry to bother you if  the resolution is obvious 
[error message](https://ibb.co/8bnCH3P)
![coder](https://github.com/coder/coder/assets/57098783/929c1152-53ee-4b7c-9898-3b5dcfb7d83d)

**Comment by matifali** [comment]
Hi @rumenmitrev, You are trying to use Coder v1 (our legacy product). This is in maintenance mode and will be deprecated. I advise you to try Coder v2. https://coder.com/docs/v2/latest

**Comment by matifali** [comment]
This repo is for Coder OSS (Coder v2), and I am closing the issue as this is unrelated. Feel free to open any issues you may have about Coder v2.
You can get help on
1. For questions, use our [discussions](https://github.com/coder/coder/discussions) or [discord](https://discord.gg/coder). 
2. For any issues/bugs with the product, use [issues](https://github.com/coder/coder/issues).
