### ISSUE TITLE
Remove i18n

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#9597]

**Comment by BrunoQuaresma** [comment]
@aslilac is it something you are still interested in working on?

**Comment by matifali** [comment]
As Coder expand to Europian markets. Dont you think Internationalization will help businesses there. 
cc: @bpmct

**Comment by aslilac** [comment]
> @aslilac is it something you are still interested in working on?

yeah, I ended up being pretty busy yesterday, but will start on this today

**Comment by BrunoQuaresma** [comment]
> As Coder expand to Europian markets. Dont you think Internationalization will help businesses there.

I don't think they care too much about this since English is a prevalent language, especially in tech but we can ask them.

In the maintenance aspect, it adds some extra work and cost since for each "UI copy change we do" we would have to change that in the N languages we support.

**Comment by matifali** [comment]
I agree.

**Comment by ammario** [comment]
We don't have the resources right now to maintain translations for multiple languages across our product or docs. It's at least two years out.
