### ISSUE TITLE
Replace XState services by react-query for simple fetching and mutations

### ISSUE THREAD

**Issue by BrunoQuaresma** [coder/coder#9598]

**Comment by mtojek** [comment]
Hey @BrunoQuaresma, could you please share how are things going? What is the overall progress for coder/site?

**Comment by aslilac** [comment]
pull requests speak louder than words :)

**Comment by BrunoQuaresma** [comment]
Remaining services to be evaluated:
- [] auth
- [] createTemplate
- [] createWorkspace
- [] pagination
- [] template
  - [] searchUsersAndGroups
  - [] templateACLService
- [] templateVersion
- [] templateVersionEditor
- [] terminal
- [] updateCheck
- [] users
  - [] searchUser
  - [] users
- [] workspace
- [] workspaceSchedule
  - [] workspaceScheduleBanner
  - [] workspaceSchedule

**Comment by BrunoQuaresma** [comment]
I'm thinking of splitting this remaining work into 4 chunks so it can be done in 4 sprints without blocking too much time from each sprint. What do you think @mtojek ?

**Comment by mtojek** [comment]
> I'm thinking of splitting this remaining work into 4 chunks so it can be done in 4 sprints without blocking too much time from each sprint. What do you think @mtojek ?

SGTM! Thank you for preparing the battle plan. If you have free capacity, you can start the next iterations earlier.
