### ISSUE TITLE
Is it possible to pass the `http_proxy` env to terraform ?

### ISSUE THREAD

**Issue by abc1763613206** [coder/coder#9609]
I was trying to deploy the coder on a server that has difficulty accessing international connections (you know, servers in mainland China such as Alibaba Cloud), so it will encounter the following error when initializing terraform:
```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider coder/coder:
could not connect to registry.terraform.io: failed to request discovery
document: Get "https://registry.terraform.io/.well-known/terraform.json":
net/http: request canceled while waiting for connection (Client.Timeout
exceeded while awaiting headers)
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider
kreuzwerker/docker: could not connect to registry.terraform.io: failed to
request discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": net/http: request
canceled while waiting for connection (Client.Timeout exceeded while awaiting
headers)
```

Now I have deployed an HTTP proxy in my intranet and now I am wondering if it is possible to pass the proxy variables to terraform so that it can complete the configuration normally. :)

**Comment by ericpaulsen** [comment]
Hi @abc1763613206 - to do this, you can set the HTTP_PROXY variable on the Coder server. How are you running the server?

**Comment by abc1763613206** [comment]
I have set the variable in the `/etc/coder.d/coder.env` and it works well,thanks!
