### ISSUE TITLE
Agent still connects to non latest build

### ISSUE THREAD

**Issue by tiaden** [coder/coder#9635]
Instead of destroying the workspace on stop, I use the provider to shut it down. when i start it again, the agent tries to connect to the last build instead of the current build. 
![Capture d’écran 2023-09-11 181014](https://github.com/coder/coder/assets/33968665/d9b1a0cd-60bf-4926-bcd9-806707b4ae6d)

**Comment by kylecarbs** [comment]
Your infrastructure must not have been recreated with the new agent token when the build occurred.

What type of resources are you using? This is intentional and by design, so that the newly provisioned infrastructure is the only thing that can connect.

**Comment by tiaden** [comment]
Indeed, it's not recreated. It is just restarted. I thought coder supported this behavior. I'm creating libvirt virtual machines using this provider https://registry.terraform.io/providers/tiaden/libvirt/latest/docs/resources/domain which has an attribute "running" to shutoff/start the vm. is there a way to provide a token that will always target the latest build ?

**Comment by spikecurtis** [comment]
> is there a way to provide a token that will always target the latest build ?

No, you should use the cloud-init to pull the latest agent startup script, which contains the new token.  We recommend executing the startup script as this will also pull the latest agent binary, so that workspaces are kept up to date with Coder service version.
