### ISSUE TITLE
Need a way to identify "idle" workspaces

### ISSUE THREAD

**Issue by mambon2** [coder/coder#9647]
Last_used column does not track active connections to the workspace.  We need a way to track active connections to workspaces to identify idle workspaces as workspaces without active connections.  

As a followup to this we also need a way to automatically disable autostart feature for "idle workspaces".  Perhaps a feature that will disable autorestart after a configurable amount of time.

**Comment by sreya** [comment]
This is supported via dormancy threshold for workspaces

**Comment by stirby** [comment]
@mambon2 Do you only need to identify idle workspaces for scheduling/cost control?

**Comment by mambon2** [comment]
yes, dormancy rules gives us a way to manage.  This can be closed.
