### ISSUE TITLE
VSCode Desktop using remote can have terminal stuck highlighting all text

### ISSUE THREAD

**Issue by Emyrk** [coder/coder#9671]
Reported by a user. Steps to reproduce:

1. Open VSCode desktop
2. Ctl+r to reverse search
3. Search a command that was used before
4. Hit right arrow to edit a selection
5. Type some text (some text should be highlighted at this point)
6. Hit "enter"
7. All bash lines after this now have highlighted text, and the only way to remove is to do the steps again

I was unable to reproduce this in a basic bin/bash shell, but observed on the client's screen. Also happens in code-server.

**Comment by kylecarbs** [comment]
Is there a relevant bug in the VS Code repo? Sounds like there's not a lot we can do without modifying VS Code itself.

**Comment by Emyrk** [comment]
@kylecarbs I am not sure. The customer is unable to leave issues on our github, so I am relaying this for them. I asked for some more info and will put it here when I get it.

**Comment by Emyrk** [comment]
I am going to close this. I was unable to reproduce. I cannot recall communication with the end user, but it has not been reported again. Likely a client side bash config issue.
