### ISSUE TITLE
API: `/api/v2/deployment/stats` does not return count for JetBrains Gateway sessions

### ISSUE THREAD

**Issue by ericpaulsen** [coder/coder#9673]
the `/api/v2/deployment/stats` endpoint returns the below connection figures:

```json
"session_count": {
    "vscode": 1,
    "ssh": 0,
    "jetbrains": 0,
    "reconnecting_pty": 0
```

however, the `session_count.jetbrains` figure is not incremented when I open a JetBrains Gateway connection. what is expected to occur for the figure to be `>0`?

# Jetbrains issue

https://youtrack.jetbrains.com/issue/GTW-2288/SSH-Config-SendEnv-not-working-windows

The `SetEnv` and `SendEnv` ssh config fields are **ignored** by Jetbrain's custom ssh implementation. There is no trivial way to fix this. We would have to send the jetbrains information in some other way.

**Comment by ericpaulsen** [comment]
i've also reproduced this on the Prometheus side, where the `coderd_agentstats_session_count_jetbrains` is not returning the workspace I've connected to via JetBrains Gateway.

**Comment by Emyrk** [comment]
The env var is the wrong casing, I will fix.

https://github.com/coder/jetbrains-coder/blob/36d6f41f9a67092189515d01216fac78a9e3e888/src/main/kotlin/com/coder/gateway/sdk/CoderCLIManager.kt#L220


https://github.com/coder/coder/blob/aa070c4f9ccbb2ad05a3533b7c3c4d3c0783411d/agent/agentssh/agentssh.go#L49-L49

**Comment by ericpaulsen** [comment]
my `~/.ssh/config` file as an example:

```
SetEnv CODER_SSH_SESSION_TYPE=JetBrains
```

**Comment by Emyrk** [comment]
This still does not work.

If you manually `ssh <workspace-jetbrains-host>` it does work. But using gateway, it does not show... :thinking:

**Comment by ericpaulsen** [comment]
cc: @code-asher

**Comment by Emyrk** [comment]
I wonder what ssh agent jetbrains uses. It could be ignoring part of the ssh config.

**Comment by Emyrk** [comment]
If I had to guess, gateway parses the ssh config itself, and does not support the same set of features as openssh. I bet `SetEnv` is not parsed.

![Screenshot from 2023-09-14 11-56-39](https://github.com/coder/coder/assets/5446298/bec15253-fb69-4f68-a678-349fce8873ca)

**Comment by Emyrk** [comment]
Found something interesting: https://youtrack.jetbrains.com/issue/IDEA-221941/Get-rid-of-sshconfig-parser-use-ssh-G-instead#focus=Comments-27-5706496.0-0


By default they have a custom parser and ssh client. You can change this to use openssh.

Still not working though...

![Screenshot from 2023-09-14 12-19-42](https://github.com/coder/coder/assets/5446298/d625943c-ffb1-4481-a42d-9e9a8958b681)

**Comment by Emyrk** [comment]
This is an open issue on Youtrack: https://youtrack.jetbrains.com/issue/GTW-2288/SSH-Config-SendEnv-not-working-windows

Until this is resolved, we cannot send this information over env vars.

If we need this soon and cannot wait, then we could maybe send the info over as like the username? Maybe as something kinda niche like a `subsystem` command? 

https://docstore.mik.ua/orelly/networking_2ndEd/ssh/ch05_07.htm

**Comment by matifali** [comment]
I noticed that when connected through JetBrains Gateway, we have `TERMINAL_EMULATOR=JetBrains-JediTerm` present. We can use this to detect JetBrains client usage.

**Comment by matifali** [comment]
To Detect Fleet, we can use `TERM_PROGRAM=Jetbrains.Fleet`
