### ISSUE TITLE
Automatically download the code of the specified branch

### ISSUE THREAD

**Issue by glenn2wang** [coder/coder#9678]
I hope there is a function that can directly download the code of the specified repo and specified branch when creating a workspace.

**Comment by MrPeacockNLB** [comment]
You can do it on your own in the startup script

**Comment by glenn2wang** [comment]
> You can do it on your own in the startup script

The repo and branch are dynamically inputted and then given to the tool to open different directories

**Comment by matifali** [comment]
Closing in favor of #8462.
Please reopen it if you think it's something else.
