### ISSUE TITLE
Add a native JetBrains Gateway button similar to VSCode Desktop

### ISSUE THREAD

**Issue by matifali** [coder/coder#9679]
Add a JetBrains Gateway button to open JetBrains IDEs using the Coder Jetbrains Gateway plugin.

You can create a `coder_app` with `external = true` to open the gateway client using a URI as a workaround. See how we do this in [`dogfood` template](https://github.com/coder/coder/tree/main/dogfood). This app uses a URI where we need three fields. I was not able to find any docs on details of the URI.

- `ide_product_code` e.g. `GO` [^1]
- `ide_build_number` e.g. `232.9559.64` [^2][^3]
- `ide_download_link` e.g. `https://download.jetbrains.com/go/goland-2023.2.1.tar.gz` [^2][^3]

1. Add a `coder_aparamter` to choose which IDE you need.

https://github.com/coder/coder/blob/e7b0181519c631cab0965c828a1b652098765364/dogfood/main.tf#L74-L103

2. Add a `coder_app` to launch that as an external link.

https://github.com/coder/coder/blob/e7b0181519c631cab0965c828a1b652098765364/dogfood/main.tf#L275-L282

References:
[^1]: https://plugins.jetbrains.com/docs/marketplace/product-codes.html
[^2]: https://www.jetbrains.com/go/download/other.html
[^3]: https://www.jetbrains.com/webstorm/download/other.html

**Comment by MrPeacockNLB** [comment]
I've tried both open IntelliJ via type=ssh and open via type=coder. Both currently leaves the opening window open as a artefact.

The button should support both connection types too

**Comment by matifali** [comment]
@MrPeacockNLB I have not tried the `type=ssh` approach. what's the difference between the two approaches? Are there any benefits of using ssh?

**Comment by matifali** [comment]
closing this as we now have https://registry.coder.com/modules/jetbrains-gateway
