### ISSUE TITLE
bug(coderd/database): workspaces.last_used_at is missing timezone component

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#9682]
> There's no comment on the DB field explaining the reasoning, so it's definitely a bug.
> 
> The migration that added it made a mistake of using `timestamp` vs `timestamptz`.
> 
> ```
> 000043_workspace_last_used.up.sql
> 2:    ADD COLUMN last_used_at timestamp NOT NULL DEFAULT '0001-01-01 00:00:00+00:00';
> ```
> 
> (See conflict between default value and field type.)
> 
> We should probably lint this somehow and prevent addition of `timestamp` columns unless `//nolint`ed.

_Originally posted by @mafredri in https://github.com/coder/coder/pull/9672#discussion_r1325825323_

**Comment by mafredri** [comment]
Adding this here as well:
> Same bug in `users` table with `last_seen_at`.
