### ISSUE TITLE
Web terminal does not disconnect when workspace shuts down

### ISSUE THREAD

**Issue by code-asher** [coder/coder#9685]
Steps to reproduce:

1. Start a workspace
2. Open the web terminal
3. Stop the workspace
4. Web terminal is unusable, yet the disconnect flow does not trigger

**Comment by BrunoQuaresma** [comment]
What should we do in this case in terms of UX?

**Comment by code-asher** [comment]
Yup, I was thinking we should invoke the same UX that happens when you type `exit`, which I think is just that "disconnected" bar at the top.

**Comment by BrunoQuaresma** [comment]
After talking with @mafredri it looks like it is an agent networking issue.
