### ISSUE TITLE
Workspace build log scrolling doesn't work in Safari

### ISSUE THREAD

**Issue by mafredri** [coder/coder#9687]
If I open a build log in Safari, I'm unable to scroll it. Works fine in Brave.

**Comment by mafredri** [comment]
Raising this to s2 since this is still present and build logs are unusable in Safari.

**Comment by kylecarbs** [comment]
Super weird.

**Comment by bpmct** [comment]
Works fine now

**Comment by mafredri** [comment]
@bpmct how did you test? Still doesn't work for me: https://dev.coder.com/@mafredri/w/builds/795

**Comment by mafredri** [comment]
Reopening because build logs (historic) are still completely unusable in Safari.

**Comment by johnstcn** [comment]
This issue occurs on `${CODER_URL}/@${USERNAME}/${WORKSPACE_NAME}/builds/${BUILD_NUMBER}`.

When I open the inspector, I can see the following error:

```
WebSocket connection to 'wss://$CODER_URL/api/v2/workspacebuilds/$WORKSPACE_BUILD_ID/logs?follow=true&after=-1' failed: The operation couldn’t be completed. Protocol error
```

**Comment by mafredri** [comment]
@BrunoQuaresma thanks so much for fixing this!

I didn’t try it on Mac yet, but couldn’t wait to check it out on mobile, and saw this:

https://github.com/user-attachments/assets/2ff055fb-2104-4124-b041-1fdb1e7e3fb4

Not sure what our mobile compat is these days but I would class this as ”not optimal” 🤣

**Comment by BrunoQuaresma** [comment]
This is probably an old issue 😢 . Right now, we are not focusing on mobile, only on medium and larger viewports for tablets and PCs.
