### ISSUE TITLE
fly.io starter templates is broken due to an API change by fly.io

### ISSUE THREAD

**Issue by matifali** [coder/coder#9690]
I have created an [issue](https://github.com/fly-apps/terraform-provider-fly/issues/246) with their terraform provider GitHub repo and left a [comment](https://community.fly.io/t/fresh-produce-volumes-endpoints-in-machines-api/14408/7?u=matifali) on their community forum.

They have removed the API support for volume operations, and unfortunately, it broke their terraform provider.

Let's update the template to remove volume temporarily or hide it from starter templates with a note that volume creation is currently broken.

Update: I created a new [thread](https://community.fly.io/t/the-fly-io-terraform-provider-is-failing-to-provision-volumes-resources/15409) on their community forum to track this. 

cc: @bpmct @aslilac

**Comment by aslilac** [comment]
thanks for logging this!

**Comment by ShivamB25** [comment]
@aslilac same issue with volume one with digitalocean

**Comment by matifali** [comment]
@ShivamB25, can you please create a new issue with error logs?

**Comment by ShivamB25** [comment]
@matifali https://github.com/coder/coder/issues/9982

done. not really related to volume but mostly auth part of Digitalocean.

**Comment by matifali** [comment]
@bpmct, it looks like they are not maintaining the terraform provider anymore. https://github.com/fly-apps/terraform-provider-fly/pull/251#issuecomment-1777999957

**Comment by aslilac** [comment]
I think we should probably just remove this template then. Fly's platform isn't really suitable to running Coder workspaces, the only real draw IMO is that it's one of the only free options, and it doesn't require more advanced Docker configuration.

**Comment by matifali** [comment]
@aslilac, it was very suitable to provide low latency workspaces due to their vast number of regions (30+), but yes, I agree we can remove it for now until they change their plans.

**Comment by kylemclaren** [comment]
Hi folks! Just stopping by to mention that with [Fly Kubernetes](https://fly.io/docs/kubernetes/) (FKS), it's possible to deploy Coder on Fly.io again (easily).

### Quick demo (3x speed):

![Screen Recording 2024-04-24 at 17 45 05](https://github.com/coder/coder/assets/3727384/f9b9329b-52fc-4fd7-8fc2-3dd77e874197)
To the left I have an instance of Coder (control plane) running as a standard Fly app. I deploy a workspace using the Kubernetes [template](https://github.com/coder/coder/tree/dd27a8a634f77468cc67acbf04f327ef429b1ed4/examples/templates/kubernetes), which authenticates to my FKS cluster. Workspaces are spun up as individual [Machines](https://fly.io/docs/machines/) within an app. With FKS, each namespace gets an app, with each pod getting a Machine within that app.

Happy to write up a longer walk-trough if there's interest!

**Comment by bpmct** [comment]
Hey @kylemclaren! This would be awesome, we'd love to support and see if we can support this as an official template. Let us know how we can help. You can reach us via Discord or via ben@coder.com :)

**Comment by matifali** [comment]
Hi @kylemclaren We have a blog post on how to [deploy and use Coder on fly.io](https://coder.com/blog/remote-developer-environments-on-fly-io) which is now a bit outdated. Would you be interested in improving that? We can probably update taht to use the FKS with K8s template instead of the now abandoned terraform provider.

You may contact @bpmct or me to reach out.
