### ISSUE TITLE
Improve error message for duplicate agent metadata key

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9713]
I inadvertently created another agent metadata block using the same key.

When I ran `coder templates push -y` it failed with:

![image](https://github.com/coder/coder/assets/2022166/2a5d3ea0-817a-4e7d-8a6b-b8a83b811073)

I pulled the `coderd` logs and found:

![image](https://github.com/coder/coder/assets/2022166/2f7bc136-1f7f-469a-95b0-fa2fc4987657)

A better Terraform error message should show in the terminal after `coder templates create` or `push`

**Comment by Kira-Pilot** [comment]
@mafredri Do you have any thoughts on where I could add a check for a unique constraint on `UniqueWorkspaceAgentMetadataPkey`? The error referenced in the above screenshot originates [in the runner](https://github.com/coder/coder/blob/main/provisionerd/runner/runner.go#L224), but I know we don't want to include the `database` package in there.

**Comment by mafredri** [comment]
@Kira-Pilot I think you can add some handling here to give nicer error: https://github.com/coder/coder/blob/23f02651f9ef66691b7b0b782443d31f5282c3e4/coderd/provisionerdserver/provisionerdserver.go#L1443
