### ISSUE TITLE
bug: `max-ttl` parameter in `coder templates create` requires an experiment

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9753]
When trying to set the `max-ttl` with `coder templates create`, the CLI fails saying an experiment `workspace_actions` is required.

Engineering reports that this is a bug, and experiment should not be required since max lifetime has been around for awhile.

![image](https://github.com/coder/coder/assets/2022166/d671e4f1-b492-4fb0-add3-af23bf6ec426)

**Comment by sreya** [comment]
fixed by https://github.com/coder/coder/pull/10030
