### ISSUE TITLE
flake: TerminalPage.test.tsx

### ISSUE THREAD

**Issue by sreya** [coder/coder#9762]
```
FAIL test src/pages/TerminalPage/TerminalPage.test.tsx (6.515 s)
  ● TerminalPage › supports workspace.agent syntax

    expect(received).toContain(expected) // indexOf

    Expected substring: "something to render"
    Received string:    " "
```

Seen on [main](https://github.com/coder/coder/actions/runs/6221409862/job/16883299473)

**Comment by aslilac** [comment]
I'm still seeing this on the latest main :\

**Comment by BrunoQuaresma** [comment]
@code-asher made a big refactor on the terminal https://github.com/coder/coder/pull/10234 and after that I didn't see any flakiness related to it
