### ISSUE TITLE
Uppecase username fails in default template workspace creation

### ISSUE THREAD

**Issue by pi3ch** [coder/coder#9767]
Workspace owner name is set after the username, it is allowed to use uppercase in the username, however, it is not allowed to use uppercase for workspace name and the following validation error is returned.

`createApp Validation failed: Name may only contain numbers, lowercase letters and dashes`

Default fly template fails with uppercase username
```
resource "fly_app" "workspace_fly_app" {
  name = "coder-${data.coder_workspace.me.owner}-${lower(data.coder_workspace.me.name)}"
  org  = var.fly_org
}
```

workaround add `lower()`
```
resource "fly_app" "workspace_fly_app" {
  name = "coder-${lower(data.coder_workspace.me.owner)}-${lower(data.coder_workspace.me.name)}"
  org  = var.fly_org
}
```

Restrict username to lowercase characters.

NOTE: I am aware of https://github.com/coder/coder/issues/1689#issuecomment-1203371376 , however this requirement should be somewhere documented.

**Comment by matifali** [comment]
@pi3ch This error is from the fly.io terraform provider. They do not allow a `fly_app` resource to have upper case letters in the name.

**Comment by pi3ch** [comment]
@matifali yes, I am aware as you can see in my workaround. I also brought up this issue since there has been similar issue in the past anytime a username has uppercase.

**Comment by matifali** [comment]
@pi3ch Thank you. Would you like to submit a PR to fix this in the fly.io example template?

**Comment by pi3ch** [comment]
Sure
