### ISSUE TITLE
feat: specify a site-wide max workspace quota

### ISSUE THREAD

**Issue by cdoscher** [coder/coder#9780]
A customer with users in multiple groups with workspace resource quotas, is concerned a user could spin a large amount of workspace compute.
e.g., Mark in groups A, B, C each with 100 quota units, means Mark could potentially have 300 units of compute running, which is higher than the budget a customer wants.
A site-wide or global setting as an environment variable could be a subset of 300 units, like 100 to keep costs under control.

**Comment by ammario** [comment]
We want to minimize this kind of site-wide configuration as it complicates multi-tenancy. Assuming this isn't a critical blocker, we should consider waiting until the "organization" (or other group of groups) model is built out, and then we can attach this option to that new concept.
