### ISSUE TITLE
Audit logs: OrganizationID is missing

### ISSUE THREAD

**Issue by mtojek** [coder/coder#9791]
Our audit logs are missing the `OrganizationID`. I tried to add it, but it isn't as simple as it seems to be, as we can't simply db-query user organization, as from the database schema perspective a user may belong to many organizations.

<img width="1252" alt="Screenshot 2023-09-20 at 14 14 14" src="https://github.com/coder/coder/assets/14044910/4820d096-be23-48c8-afec-6289c3bd8b07">

**Comment by Emyrk** [comment]
A workspace does belong to a single org, in this case you'd use that org id.
