### ISSUE TITLE
flake: Tests for TemplateSchedulePage sometimes time out

### ISSUE THREAD

**Issue by Parkreiner** [coder/coder#9793]
Already working on this – just filing it as an issue for documentation purposes.
[Link to test logs](https://github.com/coder/coder/actions/runs/6248499489/job/16963260128)

Log excerpt:
```txt
FAIL test src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.test.tsx (78.533 s)
  ● TemplateSchedulePage › succeeds

    thrown: "Exceeded timeout of 20000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      110 |   });
      111 |
    > 112 |   it("succeeds", async () => {
          |   ^
      113 |     await renderTemplateSchedulePage();
      114 |     jest.spyOn(API, "updateTemplateMeta").mockResolvedValueOnce({
      115 |       ...MockTemplate,

      at it (src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.test.tsx:112:3)
      at Object.describe (src/pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePage.test.tsx:102:1)
```

**Comment by Parkreiner** [comment]
Doing some more tests – it seems that the tests themselves might be completely okay. The issue really is just that they're timing out. GH Actions has the default timeout of 20 seconds, but three of the tests are each taking about 3 seconds. Getting a total runtime of 12 seconds, but I'm guessing that sometimes spikes

Mainly going to be working on figuring out how to speed things up overall

**Comment by Parkreiner** [comment]
Tested this from a couple of different angles, and I wasn't able to track down the source of the non-deterministic tests.

I think there's a decent chance that there's something in the form components that's causing the button to still be disabled when it's clicked, but I don't know what would make that behavior be non-deterministic.

**Comment by Parkreiner** [comment]
Okay, I'll start digging even deeper

**Comment by stirby** [comment]
Closing as stale @Parkreiner.
