### ISSUE TITLE
Deployment health check should refresh more frequently

### ISSUE THREAD

**Issue by ammario** [coder/coder#9799]
On dogfood, I've seen this error multiple times where the DB latency appears high:

<img width="885" alt="image" src="https://github.com/coder/coder/assets/7416144/24bde069-ccf7-45f8-aa95-ce1c7c8d55ac">

but, we're using the embedded postgres, and the dashboard is snappy, so clearly this is a transient issue.

**Comment by matifali** [comment]
Duplicate or related to #8969
