### ISSUE TITLE
Web terminal is unusable with nano/vim etc

### ISSUE THREAD

**Issue by matifali** [coder/coder#9806]
version: https://github.com/coder/coder/commit/b742661abde02f1fbceccb773ab5a634ad87e845
client OS: Windows

https://github.com/coder/coder/assets/10648092/f5efa7f6-f39d-47d2-984f-ea2384492c03

This makes using vim/nano almost impossible.
I cannot scroll down to the following content. 

cc: @BrunoQuaresma @bpmct

**Comment by matifali** [comment]
Uninstalling `screen` [`sudo apt remove screen`] from the workspace resolves the issue.

**Comment by mafredri** [comment]
@code-asher tagging you FYI.

**Comment by MrPeacockNLB** [comment]
We are using TMux. No problems with nano at all

**Comment by mafredri** [comment]
> We are using TMux. No problems with nano at all

There isn't actually any problem with `screen` itself, the problem lies in the screen backend for the web terminal, i.e. if `screen` is installed in a workspace, it will be used for in-workspace rendering of the terminal, which is then transmitted to the web terminal.

**Comment by aslilac** [comment]
is there a way to disable screen *without* uninstalling it?

**Comment by mafredri** [comment]
@aslilac I don't believe there is. You could try something like `sudo mv $(which screen) /path/in/my/PATH/bin/screen` which ought to work as long as that path isn't in the system default path, e.g. something like PATH="${PATH}:${HOME}/bin" if you've got it setup via your dotfiles.
