### ISSUE TITLE
Feature: Max lifetime to respect active connections

### ISSUE THREAD

**Issue by mambon2** [coder/coder#9815]
Max lifetime flag is not very useful because it will delete a workspace even if there is an active connection.  We need this feature to be more forgiving so that its actually useful.  Max lifetime should work similar to the autostop feature.

**Comment by sharkymark** [comment]
it's a best practice to have repos and personalization settings in a persistent disk, which is not deleted when a workspace is managed by max lifetime

**Comment by mambon2** [comment]
if there is an active connection, that means someone is working on that workspace and Max lifetime will kick them out midstream.

**Comment by mambon2** [comment]
just to clarify, this is not about persisting data.  As a rule, workspace shutdowns should only happen when there is nobody actively using the workspace.
