### ISSUE TITLE
Couldn't download IntelliCode model. Please check your network connectivity or firewall settings.

### ISSUE THREAD

**Issue by osnapitsjoey** [coder/coder#9819]
it looks as though it is downloading, but once it gets to 100 percent it pops that error message. Im not quite sure how to fix this! or if there is an alternative to intellicode i should be using

**Comment by matifali** [comment]
Hi @osnapitsjoey, could you elaborate more on when and where you get this error?

**Comment by osnapitsjoey** [comment]
Yeah! It happens as soon as I go to open a python file. Everything else
works, besides intellicode. I've tried using local host to download it,
through https, And through the terminal within vscode. Not sure if I have a
setting set up wrong. I am using a "custom" marketplace

**Comment by matifali** [comment]
@osnapitsjoey I think you are trying to have it on code-server, which is not talking to MS VScode marketplace.
