### ISSUE TITLE
feat: template configuration to restrict days of the week for auto-start

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9821]
Users can select any days of the week to auto-start workspaces. Enterprises that require more governance and control want at the template-level, to disable specific days of the week, e.g., Saturday and Sunday, so users cannot select those in their workspaces.

This is a 2023 feature in v1 at the organization-level and v1 customers will expect it in v2.

**Comment by Emyrk** [comment]
Day selector from V1

![Screenshot from 2023-10-11 12-42-27](https://github.com/coder/coder/assets/5446298/bf96aaa9-1c37-4f7e-a8b9-42b45bbe8ef7)

**Comment by Emyrk** [comment]
reopen because we still need the UI

**Comment by Emyrk** [comment]
https://github.com/coder/coder/pull/10263
