### ISSUE TITLE
bug: updates to one column can clobber updates to other columns

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#9822]
We have a single method to update workspace builds that covers multiple fields.  Typical use in our codebase is, in a transaction

1. Read the workspace build
2. Update the workspace build, using the values from 1 for any field we are not changing.

At the default transaction isolation, this is not safe.  If another database user commits changes to the same build between 1 and 2, the transaction completes successfully and we clobber those changes.

Solution Notes
---------------

In addition to fixing our updates to be safe for concurrent use, we should consider splitting the provisioner_state column into pre-build state and post-build state.  With state overwriting state, it can be hard to diagnose why a build acted the way it did.  This wouldn't have saved us in this case, but would have made diagnosis easier.

cc @mafredri @johnstcn @matifali @bpmct

**Comment by johnstcn** [comment]
This is where zero values bite us.

Consider:

```
-- name: Query :exec
UPDATE my_table
SET
  row1 = @arg1::string,
  row2 = @arg2::timestamptz,
  row3 = @arg3::bytea
WHERE id = @arg1

type QueryParams struct {
  Arg0 int64
  Arg1 string
  Arg2 sql.NullTime
  Arg3 []byte
}

func Query(ctx context.Context, arg QueryParams) error { ... } 
```

There are a couple of failure modes here:

1) We query values outside a tx and use them inside a tx, inadvertently overwriting them if another query modifies them.

2) We forget to fill out _all_ of the struct fields, and inadvertently end up clobbering any values we missed with Go's zero-values for the respective fields (which is what caused https://github.com/coder/coder/issues/9823).

This is not an exhaustive list, so there may be other failure modes.

We should be able to address 1) by ensuring that _all_ UPDATE queries must target completely disjoint sets of values, e.g.

```
-- name: QueryA :exec
UPDATE my_table
SET
  row1 = @arg1::string,
  row2 = @arg2::timestamptz,
WHERE id = @arg1

type QueryAParams struct {
  Arg0 int64
  Arg1 string
  Arg2 sql.NullTime
}

func QueryA(ctx context.Context, arg QueryAParams) error { ... } 

-- name: QueryB :exec
UPDATE my_table
SET
  row2 = @arg2::timestamptz,
  row3 = @arg3::bytea
WHERE id = @arg1

type QueryBParams struct {
  Arg0 int64

  Arg2 sql.NullTime
  Arg3 []byte
}

func QueryB(ctx context.Context, arg QueryBParams) error { ... } 
```

We should be able to address 2) by modifying all UPDATE queries to require positional args instead of a struct, thereby making it a _compile-time error_ to omit an argument to an UPDATE query:

```
-- name: QueryA :exec
UPDATE my_table
SET
  row1 = @arg1::string,
  row2 = @arg2::timestamptz,
WHERE id = @arg1

type QueryAParams struct {
  Arg0 int64
  Arg1 string
  Arg2 sql.NullTime
}

func QueryA(ctx context.Context, arg0 int64, arg1 string, arg2 sql.NullTime) error { ... } 

-- name: QueryB :exec
UPDATE my_table
SET
  row2 = @arg1::timestamptz,
  row3 = @arg2::bytea
WHERE id = @arg0

func QueryB(ctx context.Context, arg0 string, arg1 sql.NullTime, arg2 []byte) error { ... } 
```

**Comment by mtojek** [comment]
> At the default transaction isolation, this is not safe. If another database user commits changes to the same build between 1 and 2, the transaction completes successfully and we clobber those changes.

@spikecurtis I'm curious if this is something we can address following the old school pattern with `@Version`. see [hibernate](https://vladmihalcea.com/jpa-entity-version-property-hibernate/)

**Comment by spikecurtis** [comment]
It ends up looking similar to a Repeatable Read transaction inasmuch as you need to handle retries if there is a serialization error / version doesn't match.  I think I'd prefer transactions over adding a new column to every table.

**Comment by johnstcn** [comment]
For the moment, this has a band-aid placed over it in the form of #9995.
It doesn't address the underlying root cause, but makes it abundantly obvious when a value is being omitted.

**Comment by mafredri** [comment]
> For the moment, this has a band-aid placed over it in the form of #9995. It doesn't address the underlying root cause, but makes it abundantly obvious when a value is being omitted.

Does that actually affect the issue being reported here? The problem isn’t that we’re omitting columns, it’s that we’re updating with stale data?
