### ISSUE TITLE
template editor: failed versions show up as versions in the editor

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9836]
When someone is iterating on a template, I do not think failed versions should show up here:

![image](https://github.com/coder/coder/assets/22407953/62f38549-6f00-45c6-80d4-894ec57b5dae)

![image](https://github.com/coder/coder/assets/22407953/133dd361-568c-4580-9ea6-6cd2b0e19820)

**Comment by BrunoQuaresma** [comment]
Archive was also implemented in the Web UI so this is probably fixed.

**Comment by kylecarbs** [comment]
Closing re Bruno's comment above.
