### ISSUE TITLE
feat(site): ability to view all new version messages

### ISSUE THREAD

**Issue by phorcys420** [coder/coder#9838]
[Discord thread](https://discord.com/channels/747933592273027093/1153078067632279572)
---

In the workspace view, there's a part telling you to update with the version message ([image](https://github.com/coder/coder/assets/57866459/dd3748be-3ff0-4af0-9362-8a7c73d60bf9))

When you are several versions behind, I think a "View all changes" button where all version messages are displayed in a text view would be nice.

I'm unsure if I'm being clear, the Discord thread is a bit easier to understand I think. (cc: @BrunoQuaresma)

**Comment by BrunoQuaresma** [comment]
Thanks for opening the issue!
