### ISSUE TITLE
Document how to use modules from the Coder registry offline

### ISSUE THREAD

**Issue by bpmct** [coder/coder#9841]
A common question we're going to get from our customers once we launch the [coder modules](https://github.com/coder/modules) is: "How do we pull/run modules in our offline deployment?" I don't know the answer to that yet, is that something you could own/explore? A few things I'd consider:
- https://developer.hashicorp.com/terraform/cli/commands/providers/mirror: I think this just downloads the necessary dependencies for a module for adding to a self-hosted registry or filesystem
- The user will need to fork the module and reference a custom [module source](https://developer.hashicorp.com/terraform/language/modules/sources) or add regsitry.coder.com or github.com/coder/modules 
  - Open questions
    - Does the user need to add github.com/coder/modules or does registry.coder.com handle it entirely as a filesystem mirror?
    - Is there a way the user could only add official modules to firewall? registry.coder.com/coder/*
    - (may need to coordinate with @kylecarbs here for these)

**Comment by matifali** [comment]
Currently we do not have author name in the module path. For example code-server an official Coder module is hosted at
https://registry.coder.com/code-server

**Comment by matifali** [comment]
Our module registry is now terraformed module registry compliant. One solution can be to mirror it using Artifactory. @bpmct, we can document this as a solution for using Artifactory to mirror the coder module registry.

**Comment by bpmct** [comment]
I think docs on how to mirror it with Artifactory is best 👍🏼

**Comment by matifali** [comment]
@ericpaulsen As you are willing to do this, I can help with the Artifactory setup if needed.
