### ISSUE TITLE
bug: coderd logs sent to stderr are all interpreted as ERROR in google cloud

### ISSUE THREAD

**Issue by johnstcn** [coder/coder#9856]
# Problem

If you set up a coderd in GKE and configured it to log stackdriver-formatted logs to stderr, all of the logs output will be interpreted as ERROR level.

![image](https://github.com/coder/coder/assets/4949514/2d098051-504c-4d2a-a82f-6d6e64447ca0)

**Comment by mafredri** [comment]
Closed via #9938
