### ISSUE TITLE
Remove opacity from disconnected/ended web Terminal

### ISSUE THREAD

**Issue by mattlqx** [coder/coder#9858]
With the current behavior of blurring out the contents of the Terminal when disconnected/terminated, it is impossible to determine the output that was on the Terminal and provide clues as to why the process was terminated/exited in the first place. Provide an option to never obscure the contents (or maybe another button/action to remove it besides reconnecting?).

Specific situation I'm seeing is I have a `coder_app` button that is a `command`, but in certain circumstances, the command being run will exit and provide some output. Currently, the user has no context as to why the command exited.

**Comment by BrunoQuaresma** [comment]
I think this can be an alert with a button to reload. Wdyt @bpmct @matifali ?

**Comment by matifali** [comment]
@BrunoQuaresma sounds fine. We can also just move that to top of the terminal window similar to startup script is still running.

**Comment by BrunoQuaresma** [comment]
@matifali this is exactly what I was thinking about.
