### ISSUE TITLE
cURL SSL Certificate Problem: self-signed certificate

### ISSUE THREAD

**Issue by RaineAllDay** [coder/coder#9863]
I am attempting to get my server up and running. I am running on a dedicated server, using a LetsEncrypt SSL Certificate. I previously was using a Comodo SSL certificate and and had the same issue. With the Comodo Certificate I was able to simply include it within the template files. However, it would be kind of a pain to keep rebuilding the template just to include the LetsEncrypt certificates. I receive the following error in the workspace container:
```
=
+ command -v curl
+ curl -fsSL --compressed https://[mydomain]/bin/coder-linux-amd64 -o coder
curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
error: failed to download coder agent
       command returned: 60
Trying again in 30 seconds...
+ status=60
+ echo error: failed to download coder agent
+ echo        command returned: 60
+ echo Trying again in 30 seconds...
+ sleep 30
+ :
```

I did attempt to add the following to the Dockerfile with no change:
```
RUN wget https://curl.se/ca/cacert.pem -O /etc/ssl/certs/ca-bundle.crt
RUN update-ca-certificates
```

The original template I used is the base Docker template.

**Comment by spikecurtis** [comment]
That error indicates that the Docker container doesn't trust the certificate being presented by your Coder server.  Some Docker base images don't install the default set of CAs, on Debian flavored images, you can install with

`apt-get install -y ca-certificates`

LetsEncrypt should be in the trusted set for most Linux distributions, but if it really isn't, you'll need to download and install the LetsEncrypt roots https://letsencrypt.org/certificates/

**Comment by magmasoft** [comment]
I ran into a similar issue when using a reverse proxy in our air-gapped intranet with TLS enabled based on a self-signed CA. The agent didn't launch. How can I configure the coder and workspace docker containers to trust our CA?

**Comment by spikecurtis** [comment]
> How can I configure the coder and workspace docker containers to trust our CA?

curl (to download the agent binary) and the agent itself use the system trust store on Linux.  [Installing it system-wide differs slightly between distributions](https://www.baeldung.com/linux/add-self-signed-certificate-trusted-list#2-debian-based-distributions).

**Comment by magmasoft** [comment]
Are there configuration options to omit certificate checks ("curl -k") for agent downloads and connections from agents to coder servers?
I don't want to use HTTP but at least the encryption part of TLS.

**Comment by spikecurtis** [comment]
> Are there configuration options to omit certificate checks ("curl -k") for agent downloads and connections from agents to coder servers? I don't want to use HTTP but at least the encryption part of TLS.

Not at present.

**Comment by sempie** [comment]
As a workaround you can install your internal or self-signing CA into the workspace via the template.  I created a simple example here: https://github.com/sempie/coder-templates/tree/main/ca-install

**Comment by nolange** [comment]
I run into the same problem with a self-singed Root-CA.

Workspace setup [stops here](https://github.com/coder/coder/blob/539d6b0f3b198a31d81058342908a635f4cb97d9/provisionersdk/scripts/bootstrap_linux.sh#L23).

-   coder runs on localhost
-   nginx provides SSL and domainname (clients need to install the Root-CA)
-   spawned docker workspaces miss this Root-CA and complain: "curl: (60) SSL certificate problem: self-signed certificate in certificate chain"

Note that coder and workspaces run on the same machine, so ideally I would prefer a local TCP/Unix Socket connection for communication between workspace containers and coder.

**Comment by kylecarbs** [comment]
We have plenty of customers that use custom self-signed certificates with Coder.

In this scenario, it's unclear how we could directly improve the product from this issue, so I'm going to close it out.

**Comment by kbaegis** [comment]
I have a couple of suggestions on this point.

First, why are you folks parameterize this as an arg?
```
        "Args": [
            "-c",
            "#!/usr/bin/env sh\nset -eux\n# Sleep for a good long while before exiting.\n# This is to allow folks to exec into a failed workspace and poke around to\n# troubleshoot.\nwaitonexit() {\n\techo \"=== Agent script exited with non-zero code. Sleeping 24h to pres
erve logs...\"\n\tsleep 86400\n}\ntrap waitonexit EXIT\nBINARY_DIR=\"${BINARY_DIR:-$(mktemp -d -t coder.XXXXXX)}\"\nBINARY_NAME=coder\nBINARY_URL=https://code.mgmt/bin/coder-linux-amd64\ncd \"$BINARY_DIR\"\n# Attempt to download the coder agent.\n# This could fail for a n
umber of reasons, many of which are likely transient.\n# So just keep trying!\nwhile :; do\n\t# Try a number of different download tools, as we don not know what we\n\t# will have available.\n\tstatus=\"\"\n\tif command -v curl >/dev/null 2>&1; then\n\t\tcurl -fsSL --comp
ressed \"${BINARY_URL}\" -o \"${BINARY_NAME}\" && break\n\t\tstatus=$?\n\telif command -v wget >/dev/null 2>&1; then\n\t\twget -q \"${BINARY_URL}\" -O \"${BINARY_NAME}\" && break\n\t\tstatus=$?\n\telif command -v busybox >/dev/null 2>&1; then\n\t\tbusybox wget -q \"${BINA
RY_URL}\" -O \"${BINARY_NAME}\" && break\n\t\tstatus=$?\n\telse\n\t\techo \"error: no download tool found, please install curl, wget or busybox wget\"\n\t\texit 127\n\tfi\n\techo \"error: failed to download coder agent\"\n\techo \"       command returned: ${status}\"\n\te
cho \"Trying again in 30 seconds...\"\n\tsleep 30\ndone\n\nif ! chmod +x $BINARY_NAME; then\n\techo \"Failed to make $BINARY_NAME executable\"\n\texit 1\nfi\n\nhaslibcap2() {\n\tcommand -v setcap /dev/null 2>&1\n\tcommand -v capsh /dev/null 2>&1\n}\nprintnetadminmissing()
 {\n\techo \"The root user does not have CAP_NET_ADMIN permission. \" + \\\n\t\t\"If running in Docker, add the capability to the container for \" + \\\n\t\t\"improved network performance.\"\n\techo \"This has security implications. See https://man7.org/linux/man-pages/ma
n7/capabilities.7.html\"\n}\n\n# Attempt to add CAP_NET_ADMIN to the agent binary. This allows us to increase\n# network buffers which improves network transfer speeds.\nif [ -n \"${USE_CAP_NET_ADMIN:-}\" ]; then\n\t# If running as root, we do not need to do anything.\n\t
if [ \"$(id -u)\" -eq 0 ]; then\n\t\techo \"Running as root, skipping setcap\"\n\t\t# Warn the user if root does not have CAP_NET_ADMIN.\n\t\tif ! capsh --has-p=CAP_NET_ADMIN; then\n\t\t\tprintnetadminmissing\n\t\tfi\n\n\t# If not running as root, make sure we have sudo p
erms and the \"setcap\" +\n\t# \"capsh\" binaries exist.\n\telif sudo -nl && haslibcap2; then\n\t\t# Make sure the root user has CAP_NET_ADMIN.\n\t\tif sudo -n capsh --has-p=CAP_NET_ADMIN; then\n\t\t\tsudo -n setcap CAP_NET_ADMIN=+ep ./$BINARY_NAME || true\n\t\telse\n\t\t
\tprintnetadminmissing\n\t\tfi\n\n\t# If we are not running as root, cant sudo, and \"setcap\" does not exist, we\n\t# cannot do anything.\n\telse\n\t\techo \"Unable to setcap agent binary. To enable improved network performance, \" + \\\n\t\t\t\"give the agent passwordle
ss sudo permissions and the \\\"setcap\\\" + \\\"capsh\\\" binaries.\"\n\t\techo \"This has security implications. See https://man7.org/linux/man-pages/man7/capabilities.7.html\"\n\tfi\nfi\n\nexport CODER_AGENT_AUTH=\"token\"\nexport CODER_AGENT_URL=\"https://code.mgmt/\"
\nexec ./$BINARY_NAME agent\n"
```

Terrible practice, doing a like 50 line script as a sh oneliner. If you need that, just bake a shell script into the layer so that people can properly troubleshoot.

Second, while we're on the topic of parameterizing, there should probably be a `CURL_ARGS` option here where one could parameterize something other than `-fsSL --compressed`. All we need to fix this from a flexibility standpoint would be `-k` to the previous point.

**Comment by kylecarbs** [comment]
@kbaegis feel free to embed the script in your container. Our code is open-source, so nothing should stop you: https://github.com/coder/coder/blob/main/provisionersdk/scripts/bootstrap_linux.sh.

> Terrible practice, doing a like 50 line script as a sh oneliner.

Why is this a terrible practice? What's the practical difference in this string being the entrypoint command versus shelling out to a script?

> Second, while we're on the topic of parameterizing, there should probably be a CURL_ARGS option here where one could parameterize something other than -fsSL --compressed.

We can add this! You could do this right now with a simple string replace `curl -` -> `curl -k`.

**Comment by mingfang** [comment]
Please reopen this issue and add an option to support self signed certificates, e.g. `curl -k`

**Comment by TheEaterr** [comment]
I would just like to point out that it is possible to solve the curl issue adding a ~/.curlrc to the pod with the content "-k". **However** this doesn't solve the problem as it later fails inside of the coder (because of a certificate issue). What works well is  @sempie solution (thank you very much).
