### ISSUE TITLE
Can't set service banner background color – background color sometimes changes from hex to HSL format

### ISSUE THREAD

**Issue by mtojek** [coder/coder#9888]
It is not possible to set the color now as submitted value has incorrect format:

<img width="1666" alt="Screenshot 2023-09-27 at 15 17 23" src="https://github.com/coder/coder/assets/14044910/0d9fd124-7005-4366-87dd-2c5e1baf1493">

It would be nice to cover it with tests.

**Comment by mtojek** [comment]
@Parkreiner I'm wondering if this is some kind of regression we introduced by blindly accepting the Dependabot lib update.

**Comment by mtojek** [comment]
Isn't it a problem with the color value selected [initially](https://github.com/coder/coder/blob/main/site/src/pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx#L56)?

It looks to me like `colors.blue[7]`.

**Comment by Parkreiner** [comment]
Ah, that would be it. Good catch!
