### ISSUE TITLE
Add helper script to test a template works after publish

### ISSUE THREAD

**Issue by francisco-mata** [coder/coder#9899]
Hello Coders,

I would like to request if its possible after building Template Stage, could add a Test Template Stage before publishing. 

In this stage Coder should try to boot a temporary WS and if its works then passes. 

**Reason:** Sometime a typo or a error on the startup script could messed up all WS, so it could be a nice safety feature to have.

**Comment by kylecarbs** [comment]
I think it'd be wise for us to create a CLI command or GitHub Action to do this for you.

It's weird for us to create a temporary workspace

**Comment by kylecarbs** [comment]
I think it'd be wise for us to create a CLI command or GitHub Action to do this for you.

It's weird for us to create a temporary workspace, because it still has to be owned by someone. e.g. it succeeds to create but fails to delete, it still needs to exist _somewhere_.

**Comment by matifali** [comment]
Depends on #14860, then we can use https://github.com/coder/setup-action to write a CI workflow.

**Comment by matifali** [comment]
Hi @francisco-mata, After we have the functionality proposed in #15042, I believe we will be able to write a script to test new template versions in CI along with https://github.com/marketplace/actions/setup-coder.

**Comment by francisco-mata** [comment]
Also the setup-coder might be very helpful. We try to approach code-focus projects, so we centralized everything about a project on the source code. This mean we can add the Coder terraform template as part of source on Github. With this new feature we can trigger Github Action CI to check if changes are valid and also publish a latest version on Coder if it passes. So we can pretty automate a CI/CD for users of Coder.

**Comment by matifali** [comment]
There is also https://github.com/coder/terraform-provider-coderd if you are interested.

**Comment by matifali** [comment]
Hi @francisco-mata, We publish a [`coder/setup-action`](https://github.com/marketplace/actions/setup-coder). It can help you test templates in CI. The suggested flow is.
 
1. `terraform validate`
2. `coder templates push <TEMPLATE> --activate false --name <TEMPLATE_VERSION_NAME>` This should return a template
3. `coder create -t <TEMPLATE> --template-version <TEMPLATE_VERSION_NAME>`
4. `coder template version promote --template=<TEMPLATE> --template-version=<TEMPLATE_VERSION_NAME>`

> If the workspace is created successfully, promote the template version to the active version


This is available in the commit https://github.com/coder/coder/commit/5ebc748e94af48d3fd805bed650080cb5d25a0e5 and will be included in

I plan to add this to our docs as a sample GitHub action workflow once it lands in a release.
