### ISSUE TITLE
DAU calculations use a lot of CPU

### ISSUE THREAD

**Issue by spikecurtis** [coder/coder#9901]
We're seeing a lot of CPU utilization on our dogfood instance.

![CPU Usage](https://github.com/coder/coder/assets/5375600/75078d5e-4121-45d3-93eb-caa2fe10d1d5)

The tops of the "mesa" shapes are likely maxing out the CPU limits of our coderd container, which runs an embedded postgres. So CPU utilization are shared between Coder and postgres.

During the peaks, the top 10 slowest DB queries are

| name | avg | min | max | sum |
| ----- | --- | --- | --- | --- |
| getdeploymentdaus | 5.79 | 4.46 | 6.75 | 52.10 |
| getlatestworkspacebuilds | 0.29 | 0.05 | 1.00 | 9.05 | 
| gettemplateappinsights | 0.63 | 0.25 | 1.00 | 1.25 |
| gettemplatedaus | 8.45 | 3.31|10.08|540.97|
|gettemplateinsights|7.55|5.02|10.08|15.09|
|gettemplateinsightsbyinterval|10.08|10.08|10.08|20.15|
|gettemplateparameterinsights|0.18|0.099|0.25|0.35|
|gettemplateversionparameters|0.25|0.25|0.25|0.25|
|getuserlatencyinsights|7.55|5.02|10.08|15.09|
|getworkspaceagentstats|0.13|0.099|0.25|0.65|

"gettemplatedaus" appears to be the worst offender, as it runs slowly and runs many times over the course of 20 minutes.  It takes 20 minutes to compute template ~insights~ DAUs and we run the calculation every hour, so some 30% of the time, we are currently pegging the CPU, slowing down builds among other things.

**Comment by mafredri** [comment]
Just to clarify, we don't automatically compute template insights at all, the `GetTemplateDAUs` and `GetDeploymentDAUs` are completely separate from insights, but they could benefit from switching over to using `GetTemplateInsightsByInterval` (which can do deployment wide as well) which limits the dataset by timeframe, and has a more correct DAU calculation.

**Comment by spikecurtis** [comment]
Updated, thanks for clarification.

**Comment by mtojek** [comment]
@spikecurtis I looked into collected metrics, and it seems that the situation accidentally improved yesterday.

<img width="1473" alt="Screenshot 2023-10-04 at 16 06 15" src="https://github.com/coder/coder/assets/14044910/c64bd135-3335-478a-b618-6cc34c79ce09">

Actually, it matches the moment when we enabled an additional index on `workspace_agent_stats` (credits to @mafredri). PR [here](https://github.com/coder/coder/pull/10009).

Same story with deployment DAUs:

<img width="1475" alt="Screenshot 2023-10-04 at 16 11 43" src="https://github.com/coder/coder/assets/14044910/3390e65b-160b-43dc-90ff-f97366999d10">

Do you think that we can resolve the issue for now?

**Comment by spikecurtis** [comment]
Yeah, looks like this was the case of not having an index for the query we wanted, leading to postgres having to scan.
