### ISSUE TITLE
startup_script ignored in 2.2.0

### ISSUE THREAD

**Issue by mnebelnlb** [coder/coder#9906]
The startup_script option seems to be ignored after the update to 2.2.0. Did I miss a breaking change?

**Comment by mattlqx** [comment]
Experiencing the same issue here.

**Comment by coadler** [comment]
Hi, are either of you running external provisioners?

**Comment by kylecarbs** [comment]
Looking into this. Doesn't seem to be impacting all users. Sorry about this folks.

**Comment by mattlqx** [comment]
Yeah, similar to https://github.com/coder/coder/issues/9553, it's probably because I didn't upgrade my external provisioners first. Working on rectifying that now.

**Comment by mattlqx** [comment]
Upgraded external provisioners did fix this. 👍🏻

**Comment by MrPeacockNLB** [comment]
yes, sorry for the noise. But some warning in the UI should help to better identify what is going on...

**Comment by MrPeacockNLB** [comment]
yes, we are using external provisionerd. It was caused by not updating this too

**Comment by ammario** [comment]
> yes, sorry for the noise. But some warning in the UI should help to better identify what is going on...

absolutely.

we're prioritizing better alerting on component incompatibility in the next sprint

cc @mtojek @sreya @bpmct
