### ISSUE TITLE
Replace `makeStyles`

### ISSUE THREAD

**Issue by aslilac** [coder/coder#9924]
`makeStyles` is a bit of a pain to use, and has been deprecated! Find all the places we use it and use alternatives.

<details>
<summary><h3>Progress</h3></summary>

- [x] components/Avatar/Avatar.tsx
- [x] components/AvatarData/AvatarData.tsx
- [x] components/CodeExample/CodeExample.tsx
- [x] components/CopyableValue/CopyableValue.tsx
- [x] components/CopyButton/CopyButton.tsx
- [x] components/Dashboard/DashboardLayout.tsx
- [x] components/Dashboard/DeploymentBanner/DeploymentBannerView.tsx
- [x] components/Dashboard/LicenseBanner/LicenseBannerView.tsx
- [x] components/Dashboard/Navbar/NavbarView.tsx
- [x] components/Dashboard/Navbar/UserDropdown/BorderedMenu.tsx
- [x] components/Dashboard/Navbar/UserDropdown/UserDropdownContent.tsx
- [x] components/Dashboard/Navbar/UserDropdown/UserDropdown.tsx
- [x] components/Dashboard/ServiceBanner/ServiceBannerView.tsx
- [x] components/DeploySettingsLayout/Badges.tsx
- [x] components/DeploySettingsLayout/DeploySettingsLayout.tsx
- [x] components/DeploySettingsLayout/Fieldset.tsx
- [x] components/DeploySettingsLayout/Header.tsx
- [ ] components/DeploySettingsLayout/OptionsTable.tsx
- [x] components/DeploySettingsLayout/Option.tsx
- [x] components/DeploySettingsLayout/Sidebar.tsx
- [ ] components/Dialogs/ConfirmDialog/ConfirmDialog.tsx
- [ ] components/Dialogs/DeleteDialog/DeleteDialog.tsx
- [ ] components/Dialogs/Dialog.tsx
- [x] components/DropdownArrows/DropdownArrows.tsx
- [x] components/EmptyState/EmptyState.tsx
- [x] components/ErrorBoundary/RuntimeErrorState.tsx
- [ ] components/Expander/Expander.tsx
- [x] components/FileUpload/FileUpload.tsx
- [ ] components/FormFooter/FormFooter.tsx
- [ ] components/Form/Form.tsx
- [x] components/FullPageForm/FullPageForm.tsx
- [x] components/GlobalSnackbar/EnterpriseSnackbar.tsx
- [x] components/GlobalSnackbar/GlobalSnackbar.tsx
- [x] components/HelpTooltip/HelpTooltip.tsx
- [ ] components/IconField/IconField.tsx
- [x] components/InfoTooltip/InfoTooltip.tsx
- [ ] components/Loader/FullScreenLoader.tsx
- [ ] components/Margins/Margins.tsx
- [x] components/Markdown/Markdown.tsx
- [x] components/PageHeader/FullWidthPageHeader.tsx
- [x] components/PageHeader/PageHeader.tsx
- [x] components/PaginationWidget/PageButton.tsx
- [x] components/PaginationWidget/PaginationWidgetBase.tsx
- [ ] components/PaginationWidget/PaginationWidget.tsx
- [x] components/Paywall/Paywall.tsx
- [x] components/Pill/Pill.tsx
- [x] components/Resources/AgentLatency.tsx
- [ ] components/Resources/AgentMetadata.tsx
- [ ] components/Resources/AgentOutdatedTooltip.tsx
- [ ] components/Resources/AgentRowPreview.tsx
- [ ] components/Resources/AgentRow.tsx
- [ ] components/Resources/AgentStatus.tsx
- [ ] components/Resources/AgentVersion.tsx
- [ ] components/Resources/AppLink/AppLink.tsx
- [ ] components/Resources/AppLink/AppPreviewLink.tsx
- [ ] components/Resources/PortForwardButton.tsx
- [x] components/Resources/ResourceCard.tsx
- [ ] components/Resources/Resources.tsx
- [x] components/Resources/SensitiveValue.tsx
- [x] components/Resources/SSHButton/SSHButton.tsx
- [ ] components/RichParameterInput/MultiTextField.tsx
- [x] components/RichParameterInput/RichParameterInput.tsx
- [ ] components/SettingsLayout/SectionAction.tsx
- [ ] components/SettingsLayout/Section.tsx
- [ ] components/SettingsLayout/SettingsLayout.tsx
- [ ] components/SettingsLayout/Sidebar.tsx
- [ ] components/SignInLayout/SignInLayout.tsx
- [x] components/Stack/Stack.tsx
- [ ] components/Stats/Stats.tsx
- [ ] components/SyntaxHighlighter/SyntaxHighlighter.tsx
- [x] components/TableLoader/TableLoader.tsx
- [ ] components/TemplateExampleCard/TemplateExampleCard.tsx
- [ ] components/TemplateFiles/TemplateFiles.tsx
- [x] components/Timeline/TimelineDateRow.tsx
- [ ] components/Timeline/TimelineEntry.tsx
- [ ] components/Typography/Typography.tsx
- [ ] components/UserAutocomplete/UserAutocomplete.tsx
- [ ] components/UserOrGroupAutocomplete/UserOrGroupAutocomplete.tsx
- [ ] components/UsersLayout/UsersLayout.tsx
- [x] components/Welcome/Welcome.tsx
- [ ] components/WorkspaceBuildLogs/Logs.tsx
- [ ] components/WorkspaceBuildLogs/WorkspaceBuildLogs.tsx
- [ ] components/WorkspaceOutdatedTooltip/WorkspaceOutdatedTooltip.tsx
- [ ] components/WorkspaceStatusBadge/WorkspaceStatusBadge.tsx
- [ ] hooks/useClickableTableRow.ts
- [ ] pages/404Page/404Page.tsx
- [ ] pages/AuditPage/AuditLogRow/AuditLogDiff/AuditLogDiff.tsx
- [ ] pages/AuditPage/AuditLogRow/AuditLogRow.tsx
- [ ] pages/CliAuthPage/CliAuthPageView.tsx
- [ ] pages/CreateTemplatePage/CreateTemplateForm.tsx
- [ ] pages/CreateTemplatePage/VariableInput.tsx
- [ ] pages/CreateTokenPage/CreateTokenForm.tsx
- [ ] pages/CreateTokenPage/CreateTokenPage.tsx
- [x] pages/CreateUserPage/CreateUserForm.tsx
- [ ] pages/CreateWorkspacePage/CreateWorkspacePageView.tsx
- [ ] pages/CreateWorkspacePage/GitAuth.tsx
- [ ] pages/CreateWorkspacePage/SelectedTemplate.tsx
- [ ] pages/DeploySettingsPage/AppearanceSettingsPage/AppearanceSettingsPageView.tsx
- [ ] pages/DeploySettingsPage/GeneralSettingsPage/ChartSection.tsx
- [ ] pages/DeploySettingsPage/GitAuthSettingsPage/GitAuthSettingsPageView.tsx
- [ ] pages/DeploySettingsPage/LicensesSettingsPage/AddNewLicensePageView.tsx
- [ ] pages/DeploySettingsPage/LicensesSettingsPage/DividerWithText.tsx
- [ ] pages/DeploySettingsPage/LicensesSettingsPage/LicenseCard.tsx
- [ ] pages/DeploySettingsPage/LicensesSettingsPage/LicensesSettingsPageView.tsx
- [ ] pages/GitAuthPage/GitAuthPageView.tsx
- [ ] pages/GroupsPage/GroupPage.tsx
- [ ] pages/GroupsPage/GroupsPageView.tsx
- [ ] pages/HealthPage/HealthPage.tsx
- [ ] pages/LoginPage/LoginPageView.tsx
- [ ] pages/LoginPage/OAuthSignInForm.tsx
- [ ] pages/LoginPage/SignInForm.tsx
- [ ] pages/SetupPage/SetupPageView.tsx
- [ ] pages/StarterTemplatePage/StarterTemplatePageView.tsx
- [ ] pages/StarterTemplatesPage/StarterTemplatesPageView.tsx
- [ ] pages/TemplatePage/TemplateDocsPage/TemplateDocsPage.tsx
- [x] pages/TemplatePage/TemplateLayout.tsx
- [ ] pages/TemplatePage/TemplateVersionsPage/VersionRow.tsx
- [ ] pages/TemplateSettingsPage/Sidebar.tsx
- [ ] pages/TemplateSettingsPage/TemplateGeneralSettingsPage/TemplateSettingsForm.tsx
- [ ] pages/TemplateSettingsPage/TemplateGeneralSettingsPage/TemplateSettingsPageView.tsx
- [ ] pages/TemplateSettingsPage/TemplatePermissionsPage/TemplatePermissionsPageView.tsx
- [ ] pages/TemplateSettingsPage/TemplateSchedulePage/TemplateScheduleForm.tsx
- [ ] pages/TemplateSettingsPage/TemplateSchedulePage/TemplateSchedulePageView.tsx
- [ ] pages/TemplateSettingsPage/TemplateSettingsLayout.tsx
- [x] pages/TemplateSettingsPage/TemplateVariablesPage/TemplateVariablesPageView.tsx
- [x] pages/TemplatesPage/EmptyTemplates.tsx
- [ ] pages/TemplatesPage/TemplatesPageView.tsx
- [ ] pages/TemplateVersionEditorPage/FileTreeView.tsx
- [ ] pages/TemplateVersionEditorPage/MissingTemplateVariablesDialog.tsx
- [x] pages/TemplateVersionEditorPage/TemplateVersionEditor.tsx
- [ ] pages/TerminalPage/TerminalPage.tsx
- [ ] pages/UserSettingsPage/SecurityPage/SingleSignOnSection.tsx
- [x] pages/UserSettingsPage/SSHKeysPage/SSHKeysPageView.tsx
- [x] pages/UserSettingsPage/TokensPage/TokensPage.tsx
- [ ] pages/UserSettingsPage/WorkspaceProxyPage/WorkspaceProxyPage.tsx
- [x] pages/UsersPage/ResetPasswordDialog.tsx
- [ ] pages/UsersPage/UsersTable/EditRolesButton.tsx
- [x] pages/UsersPage/UsersTable/UsersTableBody.tsx
- [ ] pages/WorkspaceBuildPage/WorkspaceBuildPageView.tsx
- [x] pages/WorkspacePage/BuildRow.tsx
- [ ] pages/WorkspacePage/ChangeVersionDialog.tsx
- [x] pages/WorkspacePage/UpdateBuildParametersDialog.tsx
- [ ] pages/WorkspacePage/WorkspaceActions/WorkspaceActions.tsx
- [ ] pages/WorkspacePage/WorkspaceBuildProgress.tsx
- [ ] pages/WorkspacePage/WorkspaceStats.tsx
- [x] pages/WorkspacePage/Workspace.tsx
- [ ] pages/WorkspaceSettingsPage/Sidebar.tsx
- [x] pages/WorkspaceSettingsPage/WorkspaceParametersPage/WorkspaceParametersPage.tsx
- [ ] pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceScheduleForm.tsx
- [x] pages/WorkspaceSettingsPage/WorkspaceSchedulePage/WorkspaceSchedulePage.tsx
- [x] pages/WorkspaceSettingsPage/WorkspaceSettingsLayout.tsx
- [x] pages/WorkspaceSettingsPage/WorkspaceSettingsPageView.tsx
- [ ] pages/WorkspacesPage/LastUsed.tsx
- [x] pages/WorkspacesPage/WorkspacesTable.tsx

</details>

**Comment by ammario** [comment]
Always found `makeStyles` clunky. Happy to see this.

**Comment by aslilac** [comment]
note to self: `WorkspaceStats` would be a great one for experimenting with better ways to get static class names that require `theme` without a great way to memoize without some sort of "helper", which is probably a thing we need for MUI usage.
