### ISSUE TITLE
Use function arguments instead of structs to parameterize DB updates

### ISSUE THREAD

**Issue by ammario** [coder/coder#9937]
This is the more complete but also more complex fix for https://github.com/coder/coder/issues/9936.

Given the context in #9936, we can offload linting to the compiler by using function args instead of structs for update params.

The real hurdle isn't tweaking sqlc—it's that we have functions with up to 11 update params. To mitigate bug risk, we should cap function calls at 4 params, necessitating pre-code-gen business logic refactors.

**Comment by kylecarbs** [comment]
:raised_eyebrow: this sounds like I'd have to inspect a func to understand why an argument exists, which seems needlessly tedious.

Why not just disallow any funcs on `database.Store` to be called without every struct param provided? That sounds like a relatively easy-to-implement linting rule.

**Comment by kylecarbs** [comment]
I don't think introducing pain due to language structure is the right way to correct behavior here. I think linting is much more reasonable... e.g. disallow `UpdateXXX` with more than 3 struct properties, or something of the like.

**Comment by ammario** [comment]
Yeah this is more of a concept and discussion. We should begin with #9936 as it gets us halfway there for a tenth the effort.
