### ISSUE TITLE
`404` first time with shared path-based `coder_app` even with `CODER_DANGEROUS_ALLOW_PATH_APP_SHARING` set to true

### ISSUE THREAD

**Issue by sharkymark** [coder/coder#9958]
Version: [`v2.2.0+d756e93`](https://github.com/coder/coder/commit/d756e93469d7fdaef831581aaad0cdc480b85c05)

1. My deployment (Kubernetes) is set to allow path app sharing

```yaml
# allow authenticated users to access path-based workspace apps
    - name: CODER_DANGEROUS_ALLOW_PATH_APP_SHARING
      value: "true"
```

2. I start a workspace with `coder_app` `share=authenticated` and the pretty globe shows up next to path-based `code-server`

![image](https://github.com/coder/coder/assets/2022166/62db454e-ce9b-4b2a-b54c-fa32594d728d)

3. In another browser, I paste the `code-server` URL and it takes me to the Coder deployment's authentication page - this is expected behavior
4. After successfully authenticated to Coder as a user with `Member` role, I get a `404`

![image](https://github.com/coder/coder/assets/2022166/117caa6a-ec42-41b8-8b85-b8799d692c84)

5. If I then refresh the browser UI, I'm in `code-server`

![image](https://github.com/coder/coder/assets/2022166/bba66798-f496-4528-aad0-ce2bd1937444)

I also tested this with an `Owner` role and it happened.

### Resources

Related, closed fixed issue #9016 but I think was if `CODER_DANGEROUS_ALLOW_PATH_APP_SHARING` was not set to `true`

@Emyrk @matifali 

Additional testing across browsers, makes me think cookies are involved. i.e., I would forcibly log out of Coder, but paste the code-server URL, and it would connect, and share=authenticated

**Comment by Emyrk** [comment]
TIL you cannot upload har files to github issues.

What is happening:

1. Hit app page **without any cookies**
2. Get redirected with a 303 to `/login` with `redirect` query param set to the app url.
3. Hit the login page
4. Enter credentials
5. [This code](https://github.com/coder/coder/blob/stevenmasley%2Fautostart_schedule/site/src/pages/LoginPage/LoginPage.tsx#L24) navigates you to the redirect url
6. You hit a 404 page

The technical thing to note is that step 5 is doing a react navigation. The app is not a react based route, so it never hits the Golang backed for the app url after the login.

The Golang backend is the one that issues the `coder_signed_app_token`.

**Comment by sharkymark** [comment]
Still occurs with apps with `subdomain=true` like Jupyter etc.

**Comment by sharkymark** [comment]
@Emyrk @bpmct
