### ISSUE TITLE
Prometheus: expose Coder insights as metrics

### ISSUE THREAD

**Issue by mtojek** [coder/coder#9983]
Our customers may find it beneficial to expose Coder insights via the Prometheus endpoint and integrate it with their Observability solutions.

Items:
* users and session time
* expose license utilization somewhere, trailing 90-day active users
* show the license limit on the graph

**Comment by spikecurtis** [comment]
How does this work with multiple Coderd replicas?

**Comment by mtojek** [comment]
Similar to other collectors like in [prometheusmetrics.go](https://github.com/coder/coder/blob/main/coderd/prometheusmetrics/prometheusmetrics.go). Technically, you can't sum up this data.

Do you see any workaround or a better solution we can adopt, @spikecurtis?

**Comment by spikecurtis** [comment]
> Technically, you can't sum up this data.

It's probably fine that you can't sum as long as other aggregations give sensible results like max or avg.  Whether this is true depends on how the metrics are computed.  

For example, if a metric is computed entirely from "deployment"-wide state, like a database query, such that one can reasonably expect that all coderds will compute and expose the same value, then that's probably fine.

However, if a metric is computed from state that is local to each coderd, then we need to understand how the different values interact such that there is no under- or over-counting.

**Comment by mtojek** [comment]
> For example, if a metric is computed entirely from "deployment"-wide state, like a database query, such that one can reasonably expect that all coderds will compute and expose the same value, then that's probably fine.

This is the only use case we have. Query a database, transform results, and expose them as metrics. One can argue that the same query is executed N times, where N is the number of replicas.

**Comment by bpmct** [comment]
Is prometheus the right tool for user session data?

**Comment by mtojek** [comment]
> Is prometheus the right tool for user session data?

What do you mean by data? Personal data like emails or IDs? I think we're already exposing them through the Prometheus channel.

BTW I copied this idea from the Sprint theme in the notion doc. Isn't that what you suggested? Alternatively, we can focus on _generic stats_ first like "total active users per template", "used parameters with values", etc.

**Comment by spikecurtis** [comment]
Wait, are these metrics _per user_, or are they aggregates like DAUs?

I wouldn't expect someone to go to prometheus to answer a question like, "how much has Marcin used Coder this last month"?

**Comment by mtojek** [comment]
I will go with the "safe" metrics first, and leave user-related for later 👍
