### ISSUE TITLE
Reduce memory used by scale test tool during SSH traffic generation

### ISSUE THREAD

**Issue by mafredri** [coder/coder#9985]
The SSH traffic generation memory usage may become a limiting factor in running it on a single machine, we should try to reduce it. Currently it's using ~14 GB for 200 workspaces.

<img width="457" alt="image" src="https://github.com/coder/coder/assets/147409/f53c922c-8ba7-4d98-ad80-fe4673bab774">

If this scales linearly, we're looking at ~70 GB for 1000 workspaces/SSH connections.

**Comment by ammario** [comment]
Isn't this due to our networking stack, or is it something specific to the scale test?

**Comment by mafredri** [comment]
@ammario I haven't dug into the cause yet. But if it was just the networking stack (multiple tailnets), I feel the memory usage should somewhat match that of `coderd`, which ends up using ~3 GB without the `single_tailnet` experiment. If we can't find any easy wins here we'll likely drop the issue and work around it in some other way.

**Comment by mafredri** [comment]
Closing this for now, the Grafana dashboard was showing memory usage from multiple pods, in reality the SSH test was using ~35 GB of RAM. There is no need (yet) to optimize!
